#ifndef _MMIWRE_CHARSET_H_
#define _MMIWRE_CHARSET_H_
//////////////////////////////////////////////////////////
#define  _LT_ENGLISH		MMISET_LANGUAGE_ENGLISH      //英文
#define  _LT_SIMP_CHINESE	MMISET_LANGUAGE_SIMP_CHINESE  //中文简体 
#define  _LT_TRAD_CHINESE	MMISET_LANGUAGE_TRAD_CHINESE   //中文繁体
#define  _LT_ARABIC			MMISET_LANGUAGE_ARABIC         //阿拉伯
#define  _LT_FRENCH			MMISET_LANGUAGE_FRENCH         //法语
#define  _LT_HINDI			MMISET_LANGUAGE_HINDI          //印第
#define  _LT_HUNGARIAN		MMISET_LANGUAGE_HUNGARIAN      //匈牙利
#define  _LT_INDONESIAN		MMISET_LANGUAGE_INDONESIAN     //印度尼西亚
#define  _LT_MALAY			MMISET_LANGUAGE_MALAY          //马来
#define  _LT_PORTUGUESE		MMISET_LANGUAGE_PORTUGUESE     //葡萄牙
#define  _LT_RUSSIAN		MMISET_LANGUAGE_RUSSIAN        //俄语
#define  _LT_SPANISH		MMISET_LANGUAGE_SPANISH        //西班牙
#define  _LT_TAGALOG		MMISET_LANGUAGE_TAGALOG        //他加诺
#define  _LT_THAI			MMISET_LANGUAGE_THAI           //泰语
#define  _LT_UIETNAMESE		MMISET_LANGUAGE_VIETNAMESE     //越南语
#define  _LT_URDU			MMISET_LANGUAGE_URDU           //乌尔都
#define  _LT_ITALIAN		MMISET_LANGUAGE_ITALIAN        //意大利
#define  _LT_PERSIAN		MMISET_LANGUAGE_PERSIAN        //波斯
#define  _LT_TURKISH		MMISET_LANGUAGE_TURKISH        //土耳其
#define  _LT_GERMAN			MMISET_LANGUAGE_GERMAN         //德语
#define  _LT_GEEK			MMISET_LANGUAGE_GREEK          //希腊
#define  _LT_HEBREW			MMISET_LANGUAGE_HEBREW         //希伯莱
#define  _LT_BENGALI		MMISET_LANGUAGE_BENGALI        //孟加拉
#define  _LT_CZECH			MMISET_LANGUAGE_CZECH          //捷克
#define  _LT_SLOVENIAN		MMISET_LANGUAGE_SLOVENIAN      //斯诺文尼亚
#define  _LT_ROMANIAN		MMISET_LANGUAGE_ROMANIAN       //罗马尼亚
#define  _LT_TELUGU			MMISET_LANGUAGE_TELUGU
#define  _LT_MARATHI		MMISET_LANGUAGE_MARATHI
#define  _LT_TAMIL			MMISET_LANGUAGE_TAMIL
#define  _LT_GUJARATI		MMISET_LANGUAGE_GUJARATI
#define  _LT_KANNADA		MMISET_LANGUAGE_KANNADA
#define  _LT_MALAYALAM		MMISET_LANGUAGE_MALAYALAM
#define  _LT_ORIYA			MMISET_LANGUAGE_ORIYA
#define  _LT_PUNJABI		MMISET_LANGUAGE_PUNJABI
#define  _LT_AFRIKAANS		MMISET_LANGUAGE_AFRIKAANS
#define  _LT_ALBANIAN		MMISET_LANGUAGE_ALBANIAN
#define  _LT_ARMENIAN		MMISET_LANGUAGE_ARMENIAN
#define  _LT_AZERBAIJANI	MMISET_LANGUAGE_AZERBAIJANI
#define  _LT_BASQUE			MMISET_LANGUAGE_BASQUE
#define  _LT_BULGARIAN		MMISET_LANGUAGE_BULGARIAN
#define  _LT_CATALAN		MMISET_LANGUAGE_CATALAN
#define  _LT_CROATIAN		MMISET_LANGUAGE_CROATIAN
#define  _LT_DANISH			MMISET_LANGUAGE_DANISH
#define  _LT_DUTCH			MMISET_LANGUAGE_DUTCH
#define  _LT_ESTONIAN		MMISET_LANGUAGE_ESTONIAN
#define  _LT_FILIPINO		MMISET_LANGUAGE_FILIPINO
#define  _LT_FINNISH		MMISET_LANGUAGE_FINNISH
#define  _LT_GALICIAN		MMISET_LANGUAGE_GALICIAN
#define  _LT_GEORGIAN		MMISET_LANGUAGE_GEORGIAN
#define  _LT_HAUSA			MMISET_LANGUAGE_HAUSA
#define  _LT_ICELANDIC		MMISET_LANGUAGE_ICELANDIC
#define  _LT_IGBO			MMISET_LANGUAGE_IGBO
#define  _LT_IRISH			MMISET_LANGUAGE_IRISH
#define  _LT_KAZAKH			MMISET_LANGUAGE_KAZAKH
#define  _LT_LATVIAN		MMISET_LANGUAGE_LATVIAN
#define  _LT_LITHUANIAN		MMISET_LANGUAGE_LITHUANIAN
#define  _LT_MACEDONIAN		MMISET_LANGUAGE_MACEDONIAN
#define  _LT_MOLDOVAN		MMISET_LANGUAGE_MOLDOVAN
#define  _LT_NORWEGIAN		MMISET_LANGUAGE_NORWEGIAN
#define  _LT_POLISH			MMISET_LANGUAGE_POLISH
#define  _LT_SERBIAN		MMISET_LANGUAGE_SERBIAN
#define  _LT_SESOTHO		MMISET_LANGUAGE_SESOTHO
#define  _LT_SLOVAK			MMISET_LANGUAGE_SLOVAK
#define  _LT_SWEDISH		MMISET_LANGUAGE_SWEDISH
#define  _LT_UKRAINIAN		MMISET_LANGUAGE_UKRAINIAN
#define  _LT_YORUVA			MMISET_LANGUAGE_YORUBA

///////////////////////////////////////////////////////////
int cp_wcstombs  ( int  flags,  
				  const unsigned short *  src,  
				  int  srclen,  
				  char *  dst,  
				  int  dstlen,  
				  const char *  defchar,  
				  int *  used 
				  );   

/* return -1 on dst buffer overflow, -2 on invalid input char */
int cp_mbstowcs(int flags,
				const char *s, int srclen,
				unsigned short *dst, int dstlen );

int GetDefaultLanguage(void);
#endif //_ADAPTOR_CHARSET_
