
#if defined(DRM_SUPPORT)

//[[define image infomation

RES_ADD_IMG(IMAGE_DRM_PROMPT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_PROMPT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_AUDIO_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_AUDIO_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_AUDIO_UNLOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_AUDIO_UNLOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_IMAGE_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_IMAGE_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_IMAGE_UNLOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_IMAGE_UNLOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef JAVA_SUPPORT
RES_ADD_IMG(IMAGE_DRM_JAVA_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_JAVA_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_JAVA_UNLOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_JAVA_UNLOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_DRM_TEXT_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_TEXT_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_TEXT_UNLOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_TEXT_UNLOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_UNKNOWN_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_UNKNOWN_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_UNKNOWN_UNLOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_UNKNOWN_UNLOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_VIDEO_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_VIDEO_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_VIDEO_UNLOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_VIDEO_UNLOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_DRM_PIC_UNKNOW_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_PIC_UNKNOW_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_PIC_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_PIC_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_PIC_UNLOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_PIC_UNLOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef  VIDEOTHUMBNAIL_SUPPORT
RES_ADD_IMG(IMAGE_DRM_MOVIE_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_MOVIE_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DRM_MOVIE_UNLOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DRM_MOVIE_UNLOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//]]define image infomation


//[[define anim infomation
//]]define anim infomation


//[[define string infomation//
//]]define string infomation


//[[define data infomation
//]]define data infomation

#endif
