#ifdef DL_SUPPORT
//[[define image infomation
RES_ADD_IMG(IMAGE_DL_DOWNLOADED,"\\MMI_RES_##\\IMAG\\IMAGE_DL_DOWNLOADED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DL_DOWNLOADING,"\\MMI_RES_##\\IMAG\\IMAGE_DL_DOWNLOADING.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DL_FAILED,"\\MMI_RES_##\\IMAG\\IMAGE_DL_FAILED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DL_WAITING,"\\MMI_RES_##\\IMAG\\IMAGE_DL_WAITING.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DL_PAUSED,"\\MMI_RES_##\\IMAG\\IMAGE_DL_PAUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DL_FOLDER_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DL_FOLDER_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DL_FOLDER_ICON_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_DL_FOLDER_ICON_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DL_DOWNLOADMANAGER,"\\MMI_RES_##\\IMAG\\IMAGE_DL_DOWNLOADMANAGER.png",IMG_CMP_PNG_ARGB_RLE,0)

//]]define image infomation


//[[define anim infomation

//]]define anim infomation


//[[define string infomation
RES_ADD_STRING(TXT_DL_DOWNLOAD_URL_EMPTY,"URL is empty")
RES_ADD_STRING(TXT_DL_DOWNLOAD_AUTH,"License verification")
//RES_ADD_STRING(TXT_DL_DOWNLOAD_AUTH_ACCOUNT,"Account")    //replaced by common ID TXT_ACCOUNT
//RES_ADD_STRING(TXT_DL_DOWNLOAD_AUTH_PASSWORD,"Password")  //replaced by common ID TXT_COMMON_PASSWORD
RES_ADD_STRING(TXT_DL_DOWNLOAD_AUTH_ACCOUNT_EMPTY,"Account is empty")
RES_ADD_STRING(TXT_DL_DOWNLOAD_AUTH_PASSWORD_EMPTY,"Password is empty")
RES_ADD_STRING(TXT_DL_DOWNLOAD_AUTH_FAIL,"Account or password error")
RES_ADD_STRING(TXT_DL_DOWNLOAD_INPUT_FILENAME,"Download file name")
RES_ADD_STRING(TXT_DL_DOWNLOAD_MANAGER,"Download management")    //replaced by common ID TXT_DOWNLOAD_MANAGER
//RES_ADD_STRING(TXT_DL_DOWNLOAD_SAVE_FILENAME,"File name:")  //replaced by common ID TXT_INPUT_FILE_NAME
//RES_ADD_STRING(TXT_DL_DOWNLOAD_SAVE_PATH,"Save to:")  //replaced by common ID TXT_COMM_FILE_SAVE_TO
//RES_ADD_STRING(TXT_DL_DOWNLOAD_APPOINT,"Appoint")    //replaced by common ID TXT_SPECIFY
RES_ADD_STRING(TXT_DL_EMPTY_LIST,"List is empty")
RES_ADD_STRING(TXT_DL_DOWNLOAD_COMPLETE,"Download completed")
//RES_ADD_STRING(TXT_DL_DOWNLOAD_ERROR,"Download failed")    //replaced by common ID TXT_DOWNLOAD_FAILED 
RES_ADD_STRING(TXT_DL_TASK_FULL,"Download list is full,arrange download mangagement")
RES_ADD_STRING(TXT_DL_TASK_REPEAT,"The task has existed in download list,re-download")
RES_ADD_STRING(TXT_DL_PAUSE_DOWNLOAD,"Pause download")
RES_ADD_STRING(TXT_DL_RESUME_DOWNLOAD,"Resume download")
RES_ADD_STRING(TXT_DL_RE_DOWNLOAD,"Re-download")
RES_ADD_STRING(TXT_DL_DEL_TASK,"Delete task")
//RES_ADD_STRING(TXT_DL_DELETE_ALL_TASK,"Delete all tasks")     //replaced by common ID TXT_DELALL
RES_ADD_STRING(TXT_DL_QURERY_RE_DOWNLOAD,"Re-download")
//RES_ADD_STRING(TXT_DL_QURERY_DEL_TASK,"Delete")        //replaced by common ID TXT_COMMON_CONFIRM_DELETE
RES_ADD_STRING(TXT_DL_QURERY_DEL_ALL_TASK,"Delete all")
//RES_ADD_STRING(TXT_DL_TASK_DETAIL,"Task detail")    //replaced by common ID STXT_DETAIL
RES_ADD_STRING(TXT_DL_FILE_EXPLORER,"File explorer")
//RES_ADD_STRING(TXT_DL_SETTINGS,"Setting")        //replaced by common ID STXT_MAIN_SETTING
//RES_ADD_STRING(TXT_DL_DETAIL,"Detail")    //replaced by common ID STXT_DETAIL
//RES_ADD_STRING(TXT_DL_DETAIL_FILENAME,"File name:")  //replaced by common ID TXT_INPUT_FILE_NAME
//RES_ADD_STRING(TXT_DL_DETAIL_URL,"URL:")  //replaced by common ID TXT_COMMON_URL
//RES_ADD_STRING(TXT_DL_DETAIL_SIZE,"File size:")  //replaced by common ID TXT_FILE_DETAIL_SIZE
RES_ADD_STRING(TXT_DL_DETAIL_PATH,"Save path:")
//RES_ADD_STRING(TXT_DL_DOWNLOAD_NO_SPACE,"Disk space insufficient")  //replaced by common ID TXT_COMM_NO_SPACE
//RES_ADD_STRING(TXT_DL_DOWNLOAD_SETTINGS,"Setting")       //replaced by common ID STXT_MAIN_SETTING
RES_ADD_STRING(TXT_DL_SETTINGS_METHOD,"Mode")
RES_ADD_STRING(TXT_DL_SETTINGS_METHOD_APPOSITE,"Parallelly")
RES_ADD_STRING(TXT_DL_SETTINGS_METHOD_QUEUE,"Serially")
RES_ADD_STRING(TXT_DL_SETTINGS_PATH,"Path")
//RES_ADD_STRING(TXT_DL_SETTINGS_PATH_CUSTOM,"Customize")  //replaced by common ID TXT_EXPORT_LOC_CUSTOM
RES_ADD_STRING(TXT_DL_SETTINGS_PATH_DEFAULT,"Default path")
//RES_ADD_STRING(TXT_DL_DIAL_FAIL,"Dial failed") //replaced by common ID TXT_DIAL_FAILED
//RES_ADD_STRING(TXT_DL_PICTURE,"Picture")  //replaced by common ID TXT_COMMON_PIC
//RES_ADD_STRING(TXT_DL_MUSIC,"Music")    //replaced by common ID TXT_COMMON_MUSIC
//RES_ADD_STRING(TXT_DL_VIDEO,"Video")    //replaced by common ID TXT_VIDEO
//RES_ADD_STRING(TXT_DL_OTHERS,"Others")            //replaced by common ID TXT_TOOLS_OTHERS
//RES_ADD_STRING(TXT_DL_SAVE_COMPLETE,"Save complete") //replaced by common ID TXT_COMM_SAVE_SUCCESS
RES_ADD_STRING(TXT_DL_PATH_TOO_LONG,"Save path is too long")
//RES_ADD_STRING(TXT_DL_FLIENAME_INVALID,"File name is invalid")    //replaced by common ID TXT_DC_NAMEINVALID
//RES_ADD_STRING(TXT_DL_DD_DETAIL,"œÍœ∏")    //replaced by common ID STXT_DETAIL
RES_ADD_STRING(TXT_DL_TASK_DOWNLOADING,"Downloading...")
//RES_ADD_STRING(TXT_DL_SELECT_WLAN," «∑Ò π”√WLANÕ¯¬Á")  //replaced by common ID TXT_WLAN_QUERY
//]]define string infomation


//[[define data infomation
//]]define data infomation
#endif