

//[[define image infomation
RES_ADD_IMG(IMAGE_SECMENU_ICON_APPLE, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_APPLE.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_UMVCHAT, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_UMVCHAT.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_RADIO, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_RADIO.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_TV1, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_TV1.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_TV2, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_TV2.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_TV3, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_TV3.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_SXH_3G_UMVCHAT,"\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_3G_UMVCHAT.png",IMG_CMP_PNG_ARGB,0)


RES_ADD_IMG(IMAGE_SECMENU_ICON_Games, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_Games.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_UMMUSIC, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_MUSIC.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_VIDEODL, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_VIDEODL.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_WEATHER, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_WEATHER.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_TV, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_TV1.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_BOOK, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_BOOK.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_SECMENU_ICON_SXH_UMPLAYER, "\\MMI_RES_##\\IMAG\\IMAGE_SECMENU_ICON_SXH_TV1.png", IMG_CMP_PNG_ARGB,0)

RES_ADD_IMG(IMAGE_MAINMENU_ICON_APPLE, "\\MMI_RES_##\\IMAG\\IMAGE_MAINMENU_ICON_APPLE.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_MAINMENU_ICON_APPLETV, "\\MMI_RES_##\\IMAG\\IMAGE_MAINMENU_ICON_APPLETV.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_MAINMENU_ICON_BOOK, "\\MMI_RES_##\\IMAG\\IMAGE_MAINMENU_ICON_BOOK.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_MAINMENU_ICON_ONGAME, "\\MMI_RES_##\\IMAG\\IMAGE_MAINMENU_ICON_ONGAME.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_MAINMENU_ICON_UMPLAYER, "\\MMI_RES_##\\IMAG\\IMAGE_MAINMENU_ICON_UMPLAYER.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_MAINMENU_ICON_UMCHAT, "\\MMI_RES_##\\IMAG\\IMAGE_MAINMENU_ICON_UMCHAT.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_MAINMENU_ICON_APPLERP, "\\MMI_RES_##\\IMAG\\IMAGE_MAINMENU_ICON_APPLERP.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_MAINMENU_ICON_APPLEMUSIC, "\\MMI_RES_##\\IMAG\\IMAGE_MAINMENU_ICON_APPLEMUSIC.png", IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_MAINMENU_ICON_VIDELDL, "\\MMI_RES_##\\IMAG\\IMAGE_MAINMENU_ICON_VIDELDL.png", IMG_CMP_PNG_ARGB,0)

//[[define anim infomation
//]]define anim infomation





//[[define string infomation


RES_ADD_STRING(TXT_SXH_APPLE,"Apple")
RES_ADD_STRING(TXT_SXH_TV,"TV")
RES_ADD_STRING(TXT_SXH_TV1,"TV1")
RES_ADD_STRING(TXT_SXH_TV2,"TV2")
RES_ADD_STRING(TXT_SXH_TV3,"TV3")
RES_ADD_STRING(TXT_SXH_UMVCHAT,"UMChat")
RES_ADD_STRING(TXT_SXH_RADIO,"Radio")
RES_ADD_STRING(TXT_SXH_3GVEDIODAIL, "3GVEDIODAIL")
RES_ADD_STRING(TXT_SXH_UMVCHATDEMO, "UMVCHATDEMO")
RES_ADD_STRING(TXT_SXH_UMPLAYER,"UMPLAYER")

RES_ADD_STRING(TXT_SXH_Games,"Games")
RES_ADD_STRING(TXT_SXH_MUSIC,"UMMUSIC")
RES_ADD_STRING(TXT_SXH_VIDEODL,"VIDEODL")
RES_ADD_STRING(TXT_SXH_WEATHER,"WEATHER")

RES_ADD_STRING(TXT_SXH_BOOK,"BOOK")

//]]define string infomation


//[[define data infomation
//]]define data infomation
