/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#ifndef PINMAP_H_
#define PINMAP_H_

//THIS FILE HAS BEEN GENERATED WITH COOLWATCHER. PLEASE EDIT WITH CARE !

//==============================================================================
// pinmap
//------------------------------------------------------------------------------
///
//==============================================================================
#define REG_PIN_BASE             (0x5010C000)
#define REG_ANALOG_REG_BASE      (0x50109000)

/*registers define*/
#define PIN_SPI_FLASH_CLK_CFG_REG                (REG_PIN_BASE + 0x00000000)
#define PIN_SPI_FLASH_CS_CFG_REG                  (REG_PIN_BASE + 0x00000004)
#define PIN_SPI_FLASH_SEL_CFG_REG                (REG_PIN_BASE + 0x00000008)
#define PIN_SPI_FLASH_SIO_0_CFG_REG            (REG_PIN_BASE + 0x0000000C)
#define PIN_SPI_FLASH_SIO_1_CFG_REG            (REG_PIN_BASE + 0x00000010)
#define PIN_SPI_FLASH_SIO_2_CFG_REG            (REG_PIN_BASE + 0x00000014)
#define PIN_SPI_FLASH_SIO_3_CFG_REG            (REG_PIN_BASE + 0x00000018)
#define PIN_SDMMC1_CLK_CFG_REG                    (REG_PIN_BASE + 0x0000001C)
#define PIN_SDMMC1_CMD_CFG_REG                   (REG_PIN_BASE + 0x00000020)
#define PIN_SDMMC1_DATA_0_CFG_REG             (REG_PIN_BASE + 0x00000024)
#define PIN_SDMMC1_DATA_1_CFG_REG             (REG_PIN_BASE + 0x00000028)
#define PIN_SDMMC1_DATA_2_CFG_REG             (REG_PIN_BASE + 0x0000002C)
#define PIN_SDMMC1_DATA_3_CFG_REG             (REG_PIN_BASE + 0x00000030)
#define PIN_AUD_DA_SYNC_CFG_REG                  (REG_PIN_BASE + 0x00000034)
#define PIN_AUD_DA_D1_CFG_REG                     (REG_PIN_BASE + 0x00000038)
#define PIN_AUD_DA_D0_CFG_REG                     (REG_PIN_BASE + 0x0000003C)
#define PIN_AUD_AD_SYNC_CFG_REG                  (REG_PIN_BASE + 0x00000040)
#define PIN_AUD_AD_D0_CFG_REG                     (REG_PIN_BASE + 0x00000044)
#define PIN_AUD_SCLK_CFG_REG                        (REG_PIN_BASE + 0x00000048)
#define PIN_ADI_SDA_CFG_REG                           (REG_PIN_BASE + 0x0000004C)
#define PIN_ADI_SYNC_CFG_REG                         (REG_PIN_BASE + 0x00000050)
#define PIN_ADI_SCL_CFG_REG                           (REG_PIN_BASE + 0x00000054)
#define PIN_SPI_LCD_SIO_CFG_REG                    (REG_PIN_BASE + 0x00000058)
#define PIN_SPI_LCD_SDC_CFG_REG                    (REG_PIN_BASE + 0x0000005C)
#define PIN_SPI_LCD_CLK_CFG_REG                     (REG_PIN_BASE + 0x00000060)
#define PIN_SPI_LCD_CS_CFG_REG                       (REG_PIN_BASE + 0x00000064)
#define PIN_SPI_LCD_SELECT_CFG_REG               (REG_PIN_BASE + 0x00000068)
#define PIN_LCD_FMARK_CFG_REG                        (REG_PIN_BASE + 0x0000006C)
#define PIN_LCD_RSTB_CFG_REG                           (REG_PIN_BASE + 0x00000070)
#define PIN_I2C_M1_SCL_CFG_REG                       (REG_PIN_BASE + 0x00000074)
#define PIN_I2C_M1_SDA_CFG_REG                      (REG_PIN_BASE + 0x00000078)
#define PIN_CAMERA_RST_L_CFG_REG                  (REG_PIN_BASE + 0x0000007C)
#define PIN_CAMERA_PWDN_CFG_REG                  (REG_PIN_BASE + 0x00000080)
#define PIN_CAMERA_REF_CLK_CFG_REG               (REG_PIN_BASE + 0x00000084)
#define PIN_SPI_CAMERA_SI_0_CFG_REG              (REG_PIN_BASE + 0x00000088)
#define PIN_SPI_CAMERA_SI_1_CFG_REG              (REG_PIN_BASE + 0x0000008C)
#define PIN_SPI_CAMERA_SCK_CFG_REG               (REG_PIN_BASE + 0x00000090)
#define PIN_GPIO_13_CFG_REG                             (REG_PIN_BASE + 0x00000094)
#define PIN_GPIO_0_CFG_REG                               (REG_PIN_BASE + 0x00000098)
#define PIN_GPIO_1_CFG_REG                               (REG_PIN_BASE + 0x0000009C)
#define PIN_GPIO_2_CFG_REG                               (REG_PIN_BASE + 0x000000A0)
#define PIN_GPIO_3_CFG_REG                               (REG_PIN_BASE + 0x000000A4)
#define PIN_GPIO_4_CFG_REG                               (REG_PIN_BASE + 0x000000A8)
#define PIN_GPIO_5_CFG_REG                               (REG_PIN_BASE + 0x000000AC)
#define PIN_GPIO_7_CFG_REG                               (REG_PIN_BASE + 0x000000B0)
#define PIN_AP_JTAG_TCK_CFG_REG                     (REG_PIN_BASE + 0x000000B4)
#define PIN_AP_JTAG_TRST_CFG_REG                   (REG_PIN_BASE + 0x000000B8)
#define PIN_AP_JTAG_TMS_CFG_REG                     (REG_PIN_BASE + 0x000000BC)
#define PIN_AP_JTAG_TDI_CFG_REG                      (REG_PIN_BASE + 0x000000C0)
#define PIN_AP_JTAG_TDO_CFG_REG                     (REG_PIN_BASE + 0x000000C4)
#define PIN_GPIO_14_CFG_REG                              (REG_PIN_BASE + 0x000000C8)
#define PIN_GPIO_15_CFG_REG                              (REG_PIN_BASE + 0x000000CC)
#define PIN_GPIO_18_CFG_REG                              (REG_PIN_BASE + 0x000000D0)
#define PIN_GPIO_19_CFG_REG                              (REG_PIN_BASE + 0x000000D4)
#define PIN_GPIO_20_CFG_REG                              (REG_PIN_BASE + 0x000000D8)
#define PIN_GPIO_21_CFG_REG                              (REG_PIN_BASE + 0x000000DC)
#define PIN_GPIO_22_CFG_REG                              (REG_PIN_BASE + 0x000000E0)
#define PIN_GPIO_23_CFG_REG                              (REG_PIN_BASE + 0x000000E4)
#define PIN_GPIO_8_CFG_REG                                (REG_PIN_BASE + 0x000000E8)
#define PIN_GPIO_9_CFG_REG                                (REG_PIN_BASE + 0x000000EC)
#define PIN_GPIO_10_CFG_REG                              (REG_PIN_BASE + 0x000000F0)
#define PIN_GPIO_11_CFG_REG                              (REG_PIN_BASE + 0x000000F4)
#define PIN_GPIO_12_CFG_REG                              (REG_PIN_BASE + 0x000000F8)
#define PIN_KEYIN_0_CFG_REG                              (REG_PIN_BASE + 0x000000FC)
#define PIN_KEYIN_1_CFG_REG                              (REG_PIN_BASE + 0x00000100)
#define PIN_KEYIN_2_CFG_REG                              (REG_PIN_BASE + 0x00000104)
#define PIN_KEYIN_3_CFG_REG                              (REG_PIN_BASE + 0x00000108)
#define PIN_KEYIN_4_CFG_REG                              (REG_PIN_BASE + 0x0000010C)
#define PIN_KEYIN_5_CFG_REG                              (REG_PIN_BASE + 0x00000110)
#define PIN_KEYOUT_0_CFG_REG                           (REG_PIN_BASE + 0x00000114)
#define PIN_KEYOUT_1_CFG_REG                           (REG_PIN_BASE + 0x00000118)
#define PIN_KEYOUT_2_CFG_REG                           (REG_PIN_BASE + 0x0000011C)
#define PIN_KEYOUT_3_CFG_REG                           (REG_PIN_BASE + 0x00000120)
#define PIN_KEYOUT_4_CFG_REG                           (REG_PIN_BASE + 0x00000124)
#define PIN_KEYOUT_5_CFG_REG                           (REG_PIN_BASE + 0x00000128)
#define PIN_DEBUG_HOST_RX_CFG_REG                (REG_PIN_BASE + 0x0000012C)
#define PIN_DEBUG_HOST_TX_CFG_REG                (REG_PIN_BASE + 0x00000130)
#define PIN_DEBUG_HOST_CLK_CFG_REG               (REG_PIN_BASE + 0x00000134)
#define PIN_SIM_1_CLK_CFG_REG                           (REG_PIN_BASE + 0x00000138)
#define PIN_SIM_1_DIO_CFG_REG                           (REG_PIN_BASE + 0x0000013C)
#define PIN_SIM_1_RST_CFG_REG                           (REG_PIN_BASE + 0x00000140)
#define PIN_SIM_2_CLK_CFG_REG                           (REG_PIN_BASE + 0x00000144)
#define PIN_SIM_2_DIO_CFG_REG                           (REG_PIN_BASE + 0x00000148)
#define PIN_SIM_2_RST_CFG_REG                           (REG_PIN_BASE + 0x0000014C)

#define ANALOG_PIN_RESETB_CFG                           (REG_ANALOG_REG_BASE + 0x00000184)
#define ANALOG_PIN_ADI_CFG                                 (REG_ANALOG_REG_BASE + 0x00000188)
#define ANALOG_PIN_AP_JTAG_CFG                         (REG_ANALOG_REG_BASE + 0x0000018C)
#define ANALOG_PIN_SPI_CAMERA_CFG                   (REG_ANALOG_REG_BASE + 0x00000190)
#define ANALOG_PIN_CAMERA_CFG                           (REG_ANALOG_REG_BASE + 0x00000194)
#define ANALOG_PIN_DEBUG_HOST_CFG                   (REG_ANALOG_REG_BASE + 0x00000198)
#define ANALOG_PIN_GPIO_CFG1                              (REG_ANALOG_REG_BASE + 0x0000019C)
#define ANALOG_PIN_GPIO_CFG2                              (REG_ANALOG_REG_BASE + 0x000001A0)
#define ANALOG_PIN_GPO_CFG                                  (REG_ANALOG_REG_BASE + 0x000001A4)
#define ANALOG_PIN_I2C_CFG                                   (REG_ANALOG_REG_BASE + 0x000001A8)
#define ANALOG_PIN_KEYIN_CFG                               (REG_ANALOG_REG_BASE + 0x000001B0)
#define ANALOG_PIN_KEYOUT_CFG                            (REG_ANALOG_REG_BASE + 0x000001B4)
#define ANALOG_PIN_LCD_CFG                                   (REG_ANALOG_REG_BASE + 0x000001B8)
#define ANALOG_PIN_GPIO13_CFG                             (REG_ANALOG_REG_BASE + 0x000001BC)
#define ANALOG_PIN_SDMMC1_OTHERS_CFG             (REG_ANALOG_REG_BASE + 0x000001C8)
#define ANALOG_PIN_SDMMC1_DATA_CFG                 (REG_ANALOG_REG_BASE + 0x000001CC)
#define ANALOG_PIN_SIM_1_CFG                               (REG_ANALOG_REG_BASE + 0x000001D0)
#define ANALOG_PIN_SIM_2_CFG                               (REG_ANALOG_REG_BASE + 0x000001D4)
#define ANALOG_PIN_SPI_LCD_CFG1                         (REG_ANALOG_REG_BASE + 0x000001E0)
#define ANALOG_PIN_SPI_LCD_CFG2                         (REG_ANALOG_REG_BASE + 0x000001E4)
#define ANALOG_PIN_UART_1_CFG                            (REG_ANALOG_REG_BASE + 0x000001EC)
#define ANALOG_PIN_UART_2_CFG                            (REG_ANALOG_REG_BASE + 0x000001F0)

//PIN REG FUNC DEFINE
#define PIN_OEN_FRC       (1<<28)
#define PIN_OUT_FRC       (1<<24)
#define PIN_OUT_REG       (1<<20)
#define PIN_OEN_REG       (1<<17)
#define PIN_PULL_FRC      (1<<16)
#define PIN_PULL_UP       (1<<9)
#define PIN_PULL_DN       (1<<8)

//PIN ANALOG REG FUNC DEFINE 
//ANALOG_PIN_ADI_CFG
#define ANALOG_PIN_ADI_SCL_DRV(n)                    (((n)&3)<<13)
#define ANALOG_PIN_ADI_SCL_IE                        (1<<12)
#define ANALOG_PIN_ADI_SCL_SE                        (1<<11)
#define ANALOG_PIN_ADI_SCL_WPUS                      (1<<10)
#define ANALOG_PIN_ADI_SDA_DRV(n)                    (((n)&3)<<8)
#define ANALOG_PIN_ADI_SDA_IE                        (1<<7)
#define ANALOG_PIN_ADI_SDA_SE                        (1<<6)
#define ANALOG_PIN_ADI_SDA_WPUS                      (1<<5)
#define ANALOG_PIN_ADI_SYNC_DRV(n)                   (((n)&3)<<3)
#define ANALOG_PIN_ADI_SYNC_IE                       (1<<2)
#define ANALOG_PIN_ADI_SYNC_SE                       (1<<1)
#define ANALOG_PIN_ADI_SYNC_WPUS                     (1<<0)

//ANALOG_PIN_AP_JTAG_CFG
#define ANALOG_PIN_AP_JTAG_TCK_DRV(n)                (((n)&3)<<23)
#define ANALOG_PIN_AP_JTAG_TCK_IE                    (1<<22)
#define ANALOG_PIN_AP_JTAG_TCK_SE                    (1<<21)
#define ANALOG_PIN_AP_JTAG_TCK_WPUS                  (1<<20)
#define ANALOG_PIN_AP_JTAG_TDI_DRV(n)                (((n)&3)<<18)
#define ANALOG_PIN_AP_JTAG_TDI_IE                    (1<<17)
#define ANALOG_PIN_AP_JTAG_TDI_SE                    (1<<16)
#define ANALOG_PIN_AP_JTAG_TDI_WPUS                  (1<<15)
#define ANALOG_PIN_AP_JTAG_TDO_DRV(n)                (((n)&3)<<13)
#define ANALOG_PIN_AP_JTAG_TDO_IE                    (1<<12)
#define ANALOG_PIN_AP_JTAG_TDO_SE                    (1<<11)
#define ANALOG_PIN_AP_JTAG_TDO_WPUS                  (1<<10)
#define ANALOG_PIN_AP_JTAG_TMS_DRV(n)                (((n)&3)<<8)
#define ANALOG_PIN_AP_JTAG_TMS_IE                    (1<<7)
#define ANALOG_PIN_AP_JTAG_TMS_SE                    (1<<6)
#define ANALOG_PIN_AP_JTAG_TMS_WPUS                  (1<<5)
#define ANALOG_PIN_AP_JTAG_TRST_DRV(n)               (((n)&3)<<3)
#define ANALOG_PIN_AP_JTAG_TRST_IE                   (1<<2)
#define ANALOG_PIN_AP_JTAG_TRST_SE                   (1<<1)
#define ANALOG_PIN_AP_JTAG_TRST_WPUS                 (1<<0)

//ANALOG_PIN_SPI_CAMERA_CFG
#define ANALOG_PIN_SPI_CAMERA_SCK_DRV(n)             (((n)&3)<<13)
#define ANALOG_PIN_SPI_CAMERA_SCK_IE                 (1<<12)
#define ANALOG_PIN_SPI_CAMERA_SCK_SE                 (1<<11)
#define ANALOG_PIN_SPI_CAMERA_SCK_WPUS               (1<<10)
#define ANALOG_PIN_SPI_CAMERA_SI_0_DRV(n)            (((n)&3)<<8)
#define ANALOG_PIN_SPI_CAMERA_SI_0_IE                (1<<7)
#define ANALOG_PIN_SPI_CAMERA_SI_0_SE                (1<<6)
#define ANALOG_PIN_SPI_CAMERA_SI_0_WPUS              (1<<5)
#define ANALOG_PIN_SPI_CAMERA_SI_1_DRV(n)            (((n)&3)<<3)
#define ANALOG_PIN_SPI_CAMERA_SI_1_IE                (1<<2)
#define ANALOG_PIN_SPI_CAMERA_SI_1_SE                (1<<1)
#define ANALOG_PIN_SPI_CAMERA_SI_1_WPUS              (1<<0)

//ANALOG_PIN_CAMERA_CFG
#define ANALOG_PIN_CAMERA_WPDI                       (1<<15)
#define ANALOG_PIN_CAMERA_PWDN_DRV(n)                (((n)&3)<<13)
#define ANALOG_PIN_CAMERA_PWDN_IE                    (1<<12)
#define ANALOG_PIN_CAMERA_PWDN_SE                    (1<<11)
#define ANALOG_PIN_CAMERA_PWDN_WPUS                  (1<<10)
#define ANALOG_PIN_CAMERA_REF_CLK_DRV(n)             (((n)&3)<<8)
#define ANALOG_PIN_CAMERA_REF_CLK_IE                 (1<<7)
#define ANALOG_PIN_CAMERA_REF_CLK_SE                 (1<<6)
#define ANALOG_PIN_CAMERA_REF_CLK_WPUS               (1<<5)
#define ANALOG_PIN_CAMERA_RST_L_DRV(n)               (((n)&3)<<3)
#define ANALOG_PIN_CAMERA_RST_L_IE                   (1<<2)
#define ANALOG_PIN_CAMERA_RST_L_SE                   (1<<1)
#define ANALOG_PIN_CAMERA_RST_L_WPUS                 (1<<0)

//ANALOG_PIN_DEBUG_HOST_CFG
#define ANALOG_PIN_DEBUG_HOST_CLK_DRV(n)             (((n)&3)<<13)
#define ANALOG_PIN_DEBUG_HOST_CLK_IE                 (1<<12)
#define ANALOG_PIN_DEBUG_HOST_CLK_SE                 (1<<11)
#define ANALOG_PIN_DEBUG_HOST_CLK_WPUS               (1<<10)
#define ANALOG_PIN_DEBUG_HOST_RX_DRV(n)              (((n)&3)<<8)
#define ANALOG_PIN_DEBUG_HOST_RX_IE                  (1<<7)
#define ANALOG_PIN_DEBUG_HOST_RX_SE                  (1<<6)
#define ANALOG_PIN_DEBUG_HOST_RX_WPUS                (1<<5)
#define ANALOG_PIN_DEBUG_HOST_TX_DRV(n)              (((n)&3)<<3)
#define ANALOG_PIN_DEBUG_HOST_TX_IE                  (1<<2)
#define ANALOG_PIN_DEBUG_HOST_TX_SE                  (1<<1)
#define ANALOG_PIN_DEBUG_HOST_TX_WPUS                (1<<0)

//ANALOG_PIN_GPIO_CFG1
#define ANALOG_PIN_GPIO_0_DRV(n)                     (((n)&3)<<18)
#define ANALOG_PIN_GPIO_0_IE                         (1<<17)
#define ANALOG_PIN_GPIO_0_SE                         (1<<16)
#define ANALOG_PIN_GPIO_0_WPUS                       (1<<15)
#define ANALOG_PIN_GPIO_1_DRV(n)                     (((n)&3)<<13)
#define ANALOG_PIN_GPIO_1_IE                         (1<<12)
#define ANALOG_PIN_GPIO_1_SE                         (1<<11)
#define ANALOG_PIN_GPIO_1_WPUS                       (1<<10)
#define ANALOG_PIN_GPIO_2_DRV(n)                     (((n)&3)<<8)
#define ANALOG_PIN_GPIO_2_IE                         (1<<7)
#define ANALOG_PIN_GPIO_2_SE                         (1<<6)
#define ANALOG_PIN_GPIO_2_WPUS                       (1<<5)
#define ANALOG_PIN_GPIO_3_DRV(n)                     (((n)&3)<<3)
#define ANALOG_PIN_GPIO_3_IE                         (1<<2)
#define ANALOG_PIN_GPIO_3_SE                         (1<<1)
#define ANALOG_PIN_GPIO_3_WPUS                       (1<<0)

//ANALOG_PIN_GPIO_CFG2
#define ANALOG_PIN_GPIO_4_DRV(n)                     (((n)&3)<<13)
#define ANALOG_PIN_GPIO_4_IE                         (1<<12)
#define ANALOG_PIN_GPIO_4_SE                         (1<<11)
#define ANALOG_PIN_GPIO_4_WPUS                       (1<<10)
#define ANALOG_PIN_GPIO_5_DRV(n)                     (((n)&3)<<8)
#define ANALOG_PIN_GPIO_5_IE                         (1<<7)
#define ANALOG_PIN_GPIO_5_SE                         (1<<6)
#define ANALOG_PIN_GPIO_5_WPUS                       (1<<5)
#define ANALOG_PIN_GPIO_7_DRV(n)                     (((n)&3)<<3)
#define ANALOG_PIN_GPIO_7_IE                         (1<<2)
#define ANALOG_PIN_GPIO_7_SE                         (1<<1)
#define ANALOG_PIN_GPIO_7_WPUS                       (1<<0)

//ANALOG_PIN_GPO_CFG
#define ANALOG_PIN_GPIO_8_DRV(n)                     (((n)&3)<<23)
#define ANALOG_PIN_GPIO_8_IE                         (1<<22)
#define ANALOG_PIN_GPIO_8_SE                         (1<<21)
#define ANALOG_PIN_GPIO_8_WPUS                       (1<<20)
#define ANALOG_PIN_GPIO_9_DRV(n)                     (((n)&3)<<18)
#define ANALOG_PIN_GPIO_9_IE                         (1<<17)
#define ANALOG_PIN_GPIO_9_SE                         (1<<16)
#define ANALOG_PIN_GPIO_9_WPUS                       (1<<15)
#define ANALOG_PIN_GPIO_10_DRV(n)                    (((n)&3)<<13)
#define ANALOG_PIN_GPIO_10_IE                        (1<<12)
#define ANALOG_PIN_GPIO_10_SE                        (1<<11)
#define ANALOG_PIN_GPIO_10_WPUS                      (1<<10)
#define ANALOG_PIN_GPIO_11_DRV(n)                    (((n)&3)<<8)
#define ANALOG_PIN_GPIO_11_IE                        (1<<7)
#define ANALOG_PIN_GPIO_11_SE                        (1<<6)
#define ANALOG_PIN_GPIO_11_WPUS                      (1<<5)
#define ANALOG_PIN_GPIO_12_DRV(n)                    (((n)&3)<<3)
#define ANALOG_PIN_GPIO_12_IE                        (1<<2)
#define ANALOG_PIN_GPIO_12_SE                        (1<<1)
#define ANALOG_PIN_GPIO_12_WPUS                      (1<<0)

//ANALOG_PIN_I2C_CFG
#define ANALOG_PIN_I2C_M1_SCL_DRV(n)                 (((n)&3)<<18)
#define ANALOG_PIN_I2C_M1_SCL_IE                     (1<<17)
#define ANALOG_PIN_I2C_M1_SCL_SE                     (1<<16)
#define ANALOG_PIN_I2C_M1_SCL_WPUS                   (1<<15)
#define ANALOG_PIN_I2C_M1_SDA_DRV(n)                 (((n)&3)<<13)
#define ANALOG_PIN_I2C_M1_SDA_IE                     (1<<12)
#define ANALOG_PIN_I2C_M1_SDA_SE                     (1<<11)
#define ANALOG_PIN_I2C_M1_SDA_WPUS                   (1<<10)
#define ANALOG_PIN_GPIO_14_DRV(n)                    (((n)&3)<<8)
#define ANALOG_PIN_GPIO_14_IE                        (1<<7)
#define ANALOG_PIN_GPIO_14_SE                        (1<<6)
#define ANALOG_PIN_GPIO_14_WPUS                      (1<<5)
#define ANALOG_PIN_GPIO_15_DRV(n)                    (((n)&3)<<3)
#define ANALOG_PIN_GPIO_15_IE                        (1<<2)
#define ANALOG_PIN_GPIO_15_SE                        (1<<1)
#define ANALOG_PIN_GPIO_15_WPUS                      (1<<0)

//ANALOG_PIN_KEYIN_CFG
#define ANALOG_PIN_KEY_WPDI                          (1<<30)
#define ANALOG_PIN_KEYIN_0_DRV(n)                    (((n)&3)<<28)
#define ANALOG_PIN_KEYIN_0_IE                        (1<<27)
#define ANALOG_PIN_KEYIN_0_SE                        (1<<26)
#define ANALOG_PIN_KEYIN_0_WPUS                      (1<<25)
#define ANALOG_PIN_KEYIN_1_DRV(n)                    (((n)&3)<<23)
#define ANALOG_PIN_KEYIN_1_IE                        (1<<22)
#define ANALOG_PIN_KEYIN_1_SE                        (1<<21)
#define ANALOG_PIN_KEYIN_1_WPUS                      (1<<20)
#define ANALOG_PIN_KEYIN_2_DRV(n)                    (((n)&3)<<18)
#define ANALOG_PIN_KEYIN_2_IE                        (1<<17)
#define ANALOG_PIN_KEYIN_2_SE                        (1<<16)
#define ANALOG_PIN_KEYIN_2_WPUS                      (1<<15)
#define ANALOG_PIN_KEYIN_3_DRV(n)                    (((n)&3)<<13)
#define ANALOG_PIN_KEYIN_3_IE                        (1<<12)
#define ANALOG_PIN_KEYIN_3_SE                        (1<<11)
#define ANALOG_PIN_KEYIN_3_WPUS                      (1<<10)
#define ANALOG_PIN_KEYIN_4_DRV(n)                    (((n)&3)<<8)
#define ANALOG_PIN_KEYIN_4_IE                        (1<<7)
#define ANALOG_PIN_KEYIN_4_SE                        (1<<6)
#define ANALOG_PIN_KEYIN_4_WPUS                      (1<<5)
#define ANALOG_PIN_KEYIN_5_DRV(n)                    (((n)&3)<<3)
#define ANALOG_PIN_KEYIN_5_IE                        (1<<2)
#define ANALOG_PIN_KEYIN_5_SE                        (1<<1)
#define ANALOG_PIN_KEYIN_5_WPUS                      (1<<0)

//ANALOG_PIN_KEYOUT_CFG
#define ANALOG_PIN_KEYOUT_0_DRV(n)                   (((n)&3)<<28)
#define ANALOG_PIN_KEYOUT_0_IE                       (1<<27)
#define ANALOG_PIN_KEYOUT_0_SE                       (1<<26)
#define ANALOG_PIN_KEYOUT_0_WPUS                     (1<<25)
#define ANALOG_PIN_KEYOUT_1_DRV(n)                   (((n)&3)<<23)
#define ANALOG_PIN_KEYOUT_1_IE                       (1<<22)
#define ANALOG_PIN_KEYOUT_1_SE                       (1<<21)
#define ANALOG_PIN_KEYOUT_1_WPUS                     (1<<20)
#define ANALOG_PIN_KEYOUT_2_DRV(n)                   (((n)&3)<<18)
#define ANALOG_PIN_KEYOUT_2_IE                       (1<<17)
#define ANALOG_PIN_KEYOUT_2_SE                       (1<<16)
#define ANALOG_PIN_KEYOUT_2_WPUS                     (1<<15)
#define ANALOG_PIN_KEYOUT_3_DRV(n)                   (((n)&3)<<13)
#define ANALOG_PIN_KEYOUT_3_IE                       (1<<12)
#define ANALOG_PIN_KEYOUT_3_SE                       (1<<11)
#define ANALOG_PIN_KEYOUT_3_WPUS                     (1<<10)
#define ANALOG_PIN_KEYOUT_4_DRV(n)                   (((n)&3)<<8)
#define ANALOG_PIN_KEYOUT_4_IE                       (1<<7)
#define ANALOG_PIN_KEYOUT_4_SE                       (1<<6)
#define ANALOG_PIN_KEYOUT_4_WPUS                     (1<<5)
#define ANALOG_PIN_KEYOUT_5_DRV(n)                   (((n)&3)<<3)
#define ANALOG_PIN_KEYOUT_5_IE                       (1<<2)
#define ANALOG_PIN_KEYOUT_5_SE                       (1<<1)
#define ANALOG_PIN_KEYOUT_5_WPUS                     (1<<0)

//ANALOG_PIN_LCD_CFG
#define ANALOG_PIN_LCD_MSEN                          (1<<15)
#define ANALOG_PIN_LCD_MS                            (1<<14)
#define ANALOG_PIN_LCD_FMARK_DRV(n)                  (((n)&15)<<10)
#define ANALOG_PIN_LCD_FMARK_IE                      (1<<9)
#define ANALOG_PIN_LCD_FMARK_SE                      (1<<8)
#define ANALOG_PIN_LCD_FMARK_SPU                     (1<<7)
#define ANALOG_PIN_LCD_RSTB_DRV(n)                   (((n)&15)<<3)
#define ANALOG_PIN_LCD_RSTB_IE                       (1<<2)
#define ANALOG_PIN_LCD_RSTB_SE                       (1<<1)
#define ANALOG_PIN_LCD_RSTB_SPU                      (1<<0)

//ANALOG_PIN_GPIO13_CFG
#define ANALOG_PIN_MIPIDSI_WPDI                      (1<<7)
#define ANALOG_PIN_MISC_L_WPDI                       (1<<6)
#define ANALOG_PIN_MISC_R_WPDI                       (1<<5)
#define ANALOG_PIN_GPIO_13_DRV(n)                    (((n)&3)<<3)
#define ANALOG_PIN_GPIO_13_IE                        (1<<2)
#define ANALOG_PIN_GPIO_13_SE                        (1<<1)
#define ANALOG_PIN_GPIO_13_WPUS                      (1<<0)

//ANALOG_PIN_SDMMC1_OTHERS_CFG
#define ANALOG_PIN_SDMMC1_MS   (1<<15)
#define ANALOG_PIN_SDMMC1_MSEN (1<<14)
#define ANALOG_PIN_SDMMC1_CLK_DRV(n) (((n)&15)<<10)
#define ANALOG_PIN_SDMMC1_CLK_IE (1<<9)
#define ANALOG_PIN_SDMMC1_CLK_SE (1<<8)
#define ANALOG_PIN_SDMMC1_CLK_SPU (1<<7)
#define ANALOG_PIN_SDMMC1_CMD_DRV(n) (((n)&15)<<3)
#define ANALOG_PIN_SDMMC1_CMD_IE (1<<2)
#define ANALOG_PIN_SDMMC1_CMD_SE (1<<1)
#define ANALOG_PIN_SDMMC1_CMD_SPU (1<<0)

//ANALOG_PIN_SDMMC1_DATA_CFG
#define ANALOG_PIN_SDMMC1_DATA_0_DRV(n) (((n)&15)<<24)
#define ANALOG_PIN_SDMMC1_DATA_0_IE (1<<23)
#define ANALOG_PIN_SDMMC1_DATA_0_SE (1<<22)
#define ANALOG_PIN_SDMMC1_DATA_0_SPU (1<<21)
#define ANALOG_PIN_SDMMC1_DATA_1_DRV(n) (((n)&15)<<17)
#define ANALOG_PIN_SDMMC1_DATA_1_IE (1<<16)
#define ANALOG_PIN_SDMMC1_DATA_1_SE (1<<15)
#define ANALOG_PIN_SDMMC1_DATA_1_SPU (1<<14)
#define ANALOG_PIN_SDMMC1_DATA_2_DRV(n) (((n)&15)<<10)
#define ANALOG_PIN_SDMMC1_DATA_2_IE (1<<9)
#define ANALOG_PIN_SDMMC1_DATA_2_SE (1<<8)
#define ANALOG_PIN_SDMMC1_DATA_2_SPU (1<<7)
#define ANALOG_PIN_SDMMC1_DATA_3_DRV(n) (((n)&15)<<3)
#define ANALOG_PIN_SDMMC1_DATA_3_IE (1<<2)
#define ANALOG_PIN_SDMMC1_DATA_3_SE (1<<1)
#define ANALOG_PIN_SDMMC1_DATA_3_SPU (1<<0)

//ANALOG_PIN_SIM_1_CFG
#define ANALOG_PIN_SIM_1_MS    (1<<22)
#define ANALOG_PIN_SIM_1_MSEN  (1<<21)
#define ANALOG_PIN_SIM_1_CLK_DRV(n) (((n)&15)<<17)
#define ANALOG_PIN_SIM_1_CLK_IE (1<<16)
#define ANALOG_PIN_SIM_1_CLK_SE (1<<15)
#define ANALOG_PIN_SIM_1_CLK_SPU (1<<14)
#define ANALOG_PIN_SIM_1_DIO_DRV(n) (((n)&15)<<10)
#define ANALOG_PIN_SIM_1_DIO_IE (1<<9)
#define ANALOG_PIN_SIM_1_DIO_SE (1<<8)
#define ANALOG_PIN_SIM_1_DIO_SPU (1<<7)
#define ANALOG_PIN_SIM_1_RST_DRV(n) (((n)&15)<<3)
#define ANALOG_PIN_SIM_1_RST_IE (1<<2)
#define ANALOG_PIN_SIM_1_RST_SE (1<<1)
#define ANALOG_PIN_SIM_1_RST_SPU (1<<0)

//ANALOG_PIN_SIM_2_CFG
#define ANALOG_PIN_SIM_2_MS    (1<<22)
#define ANALOG_PIN_SIM_2_MSEN  (1<<21)
#define ANALOG_PIN_SIM_2_CLK_DRV(n) (((n)&15)<<17)
#define ANALOG_PIN_SIM_2_CLK_IE (1<<16)
#define ANALOG_PIN_SIM_2_CLK_SE (1<<15)
#define ANALOG_PIN_SIM_2_CLK_SPU (1<<14)
#define ANALOG_PIN_SIM_2_DIO_DRV(n) (((n)&15)<<10)
#define ANALOG_PIN_SIM_2_DIO_IE (1<<9)
#define ANALOG_PIN_SIM_2_DIO_SE (1<<8)
#define ANALOG_PIN_SIM_2_DIO_SPU (1<<7)
#define ANALOG_PIN_SIM_2_RST_DRV(n) (((n)&15)<<3)
#define ANALOG_PIN_SIM_2_RST_IE (1<<2)
#define ANALOG_PIN_SIM_2_RST_SE (1<<1)
#define ANALOG_PIN_SIM_2_RST_SPU (1<<0)

//ANALOG_PIN_SPI_LCD_CFG1
#define ANALOG_PIN_SPI_LCD_CLK_DRV(n) (((n)&15)<<10)
#define ANALOG_PIN_SPI_LCD_CLK_IE (1<<9)
#define ANALOG_PIN_SPI_LCD_CLK_SE (1<<8)
#define ANALOG_PIN_SPI_LCD_CLK_SPU (1<<7)
#define ANALOG_PIN_SPI_LCD_CS_DRV(n) (((n)&15)<<3)
#define ANALOG_PIN_SPI_LCD_CS_IE (1<<2)
#define ANALOG_PIN_SPI_LCD_CS_SE (1<<1)
#define ANALOG_PIN_SPI_LCD_CS_SPU (1<<0)

//ANALOG_PIN_SPI_LCD_CFG2
#define ANALOG_PIN_SPI_LCD_SDC_DRV(n) (((n)&15)<<17)
#define ANALOG_PIN_SPI_LCD_SDC_IE (1<<16)
#define ANALOG_PIN_SPI_LCD_SDC_SE (1<<15)
#define ANALOG_PIN_SPI_LCD_SDC_SPU (1<<14)
#define ANALOG_PIN_SPI_LCD_SELECT_DRV(n) (((n)&15)<<10)
#define ANALOG_PIN_SPI_LCD_SELECT_IE (1<<9)
#define ANALOG_PIN_SPI_LCD_SELECT_SE (1<<8)
#define ANALOG_PIN_SPI_LCD_SELECT_SPU (1<<7)
#define ANALOG_PIN_SPI_LCD_SIO_DRV(n) (((n)&15)<<3)
#define ANALOG_PIN_SPI_LCD_SIO_IE (1<<2)
#define ANALOG_PIN_SPI_LCD_SIO_SE (1<<1)
#define ANALOG_PIN_SPI_LCD_SIO_SPU (1<<0)

//ANALOG_PIN_UART_1_CFG
#define ANALOG_PIN_GPIO_18_DRV(n) (((n)&3)<<8)
#define ANALOG_PIN_GPIO_18_IE  (1<<7)
#define ANALOG_PIN_GPIO_18_SE  (1<<6)
#define ANALOG_PIN_GPIO_18_WPUS (1<<5)
#define ANALOG_PIN_GPIO_19_DRV(n) (((n)&3)<<3)
#define ANALOG_PIN_GPIO_19_IE  (1<<2)
#define ANALOG_PIN_GPIO_19_SE  (1<<1)
#define ANALOG_PIN_GPIO_19_WPUS (1<<0)

//ANALOG_PIN_UART_2_CFG
#define ANALOG_PIN_GPIO_22_DRV(n) (((n)&3)<<18)
#define ANALOG_PIN_GPIO_22_IE  (1<<17)
#define ANALOG_PIN_GPIO_22_SE  (1<<16)
#define ANALOG_PIN_GPIO_22_WPUS (1<<15)
#define ANALOG_PIN_GPIO_23_DRV(n) (((n)&3)<<13)
#define ANALOG_PIN_GPIO_23_IE  (1<<12)
#define ANALOG_PIN_GPIO_23_SE  (1<<11)
#define ANALOG_PIN_GPIO_23_WPUS (1<<10)
#define ANALOG_PIN_GPIO_20_DRV(n) (((n)&3)<<8)
#define ANALOG_PIN_GPIO_20_IE  (1<<7)
#define ANALOG_PIN_GPIO_20_SE  (1<<6)
#define ANALOG_PIN_GPIO_20_WPUS (1<<5)
#define ANALOG_PIN_GPIO_21_DRV(n) (((n)&3)<<3)
#define ANALOG_PIN_GPIO_21_IE  (1<<2)
#define ANALOG_PIN_GPIO_21_SE  (1<<1)
#define ANALOG_PIN_GPIO_21_WPUS (1<<0)


#define PIN_PULL_FRC_UP   (PIN_PULL_FRC | PIN_PULL_UP)
#define PIN_PULL_FRC_DN   (PIN_PULL_FRC | PIN_PULL_DN)
#define PIN_PULL_FRC_DEFAULT  (0)
#define PIN_PULL_FRC_NONE (PIN_PULL_FRC)

#define PIN_OUT_FRC_HIGH       (PIN_OEN_FRC | PIN_OUT_FRC | PIN_OUT_REG)
#define PIN_OUT_FRC_LOW        (PIN_OEN_FRC | PIN_OUT_FRC)
#define PIN_IN_FRC                    (PIN_OEN_FRC | PIN_OEN_REG)
#define PIN_IO_DEFAULT         (0)

#define PIN_FUNC_SEL(n)   (((n)&15)<<0)

typedef struct ANA_PIN_FUN_BIT
{
	uint8 pad_wpus_bitmask;
	uint8 pad_se_bitmask;
	uint8 pad_ie_bitmask;
	uint8 pad_drv_bitmask;
	uint8 pad_whole_bitmask;
	uint8 pad_whole_bitcnt;
}T_ANA_PIN_FUN_BIT;

#endif
