/*
 * Copyright (C) 2021 UNISOC Technologies Co.,Ltd. All Rights Reserved
 *
 * Automatically generated by code_generator_unirtos.pm.
 */
#ifndef __JERRY_GUI_H__
#define __JERRY_GUI_H__

//#include "ual_type.h"

#ifdef __cplusplus
extern "C" {
#endif

    void js_register_gui_functions(void);

#ifdef __cplusplus
}
#endif

#endif // __JERRY_GUI_H__
