/*
 * Copyright (C) 2021 UNISOC Technologies Co.,Ltd. All Rights Reserved
 *
 * Automatically generated by code_generator_unirtos.pm.
 */

#ifndef __JS_LIST_H__
#define __JS_LIST_H__

#include "jerry_bindings.h"

#ifdef __cplusplus
extern "C" {
#endif

DECLARE_PUBLIC_HANDLER(js_gui_list_create);
DECLARE_PUBLIC_HANDLER(js_gui_list_append_data);
DECLARE_PUBLIC_HANDLER(js_gui_list_set_bg_color);
DECLARE_PUBLIC_HANDLER(js_gui_list_set_text_scroll);
DECLARE_PUBLIC_HANDLER(js_gui_list_set_font);
DECLARE_PUBLIC_HANDLER(js_gui_list_set_scrollbar);
DECLARE_PUBLIC_HANDLER(js_gui_list_destroy);
DECLARE_PUBLIC_HANDLER(js_gui_list_setMaxItem);
DECLARE_PUBLIC_HANDLER(js_gui_list_set_item_height);
DECLARE_PUBLIC_HANDLER(js_gui_list_set_font_size);
DECLARE_PUBLIC_HANDLER(js_gui_list_get_cur_index);
DECLARE_PUBLIC_HANDLER(js_gui_list_set_item_font_color);

#ifdef __cplusplus
}
#endif

#endif // __JS_LIST_H__

