/*****************************************************************************
 ** File Name:   mmisms_phizlistwin.c
 ** Author:      sam.hua
 ** Date:        23/aug/2012
 ** Copyright:   2012 Spreadtrum, Incorporated. All Rights Reserved.         *
 ** Description: This file is used to describe phizlist Win
 *****************************************************************************
 **                         Important Edit History                           *
 ** -------------------------------------------------------------------------*
 *  ** DATE           NAME             DESCRIPTION                           *
 *  23/aug/2012      sam.hua       written
 ****************************************************************************/

#include "guilistbox.h"
#include "guimenu.h"
#include "mmisms_text.h"
#include "mmisms_image.h"
#include "mmisms_anim.h"
#include "mmisms_id.h"
#include "mmisms_app.h"
#include "mmisms_mainmenuwin.h"
#include "mmisms_messagecountwin.h"
#include "mmisms_messageboxwin.h"
#include "mmisms_commonui.h"
#include "guiiconlist.h"
#include "mmismsapp_interface.h"

/*---------------------------------------------------------------------------*/
/*                            DEFINES                                        */
/*---------------------------------------------------------------------------*/
#if defined (MAINLCD_SIZE_128X160)
#define MMISMS_EMOJI_NUM    21    //
#define EMOJI_MAX_LEN 7
#define MMISMS_EMOJI_HEIGHT  30//phiz height
#define MMISMS_EMOJI_ROW     3
#define MMISMS_EMOJI_COL    4
#define MMISMS_EMOJI_NUM_LIST      12
#define MMISMS_EMOJI_FONT  SONG_FONT_18
#else
#define MMISMS_EMOJI_ROW     4
#define MMISMS_EMOJI_COL    4
#define MMISMS_EMOJI_NUM    (MMISMS_EMOJI_ROW * MMISMS_EMOJI_COL)
#define EMOJI_MAX_LEN 7
#define MMISMS_EMOJI_HEIGHT  40//phiz height
//#define MMISMS_EMOJI_NUM_LIST      875
#define MMISMS_EMOJI_FONT  WATCH_DEFAULT_NORMAL_FONT
#endif

#define MMISMS_EMOJI_TOP_MARGIN  30  //bug:1921548
#define MMISMS_EMOJI_MARGIN_V  3
/*---------------------------------------------------------------------------*/
/*                          TYPE AND CONSTANT                                */
/*---------------------------------------------------------------------------*/
//emoji的属性定义
const MMISMS_EMOJI_INFO_T s_emoji_image_text_convert_table[] =
{
#if 0
    { 0X203C, {0X203C}, TXT_NULL, IMAGE_NULL },
    { 0X2049, {0X2049}, TXT_NULL, IMAGE_NULL },
    { 0X2194, {0X2194}, TXT_NULL, IMAGE_NULL },
    { 0X2195, {0X2195}, TXT_NULL, IMAGE_NULL },
    { 0X2196, {0X2196}, TXT_NULL, IMAGE_NULL },
    { 0X2197, {0X2197}, TXT_NULL, IMAGE_NULL },
    { 0X2198, {0X2198}, TXT_NULL, IMAGE_NULL },
    { 0X2199, {0X2199}, TXT_NULL, IMAGE_NULL },
    { 0X21A9, {0X21A9}, TXT_NULL, IMAGE_NULL },
    { 0X21AA, {0X21AA}, TXT_NULL, IMAGE_NULL },
    { 0X231A, {0X231A}, TXT_NULL, IMAGE_NULL },
    { 0X231B, {0X231B}, TXT_NULL, IMAGE_NULL },
    { 0X23E9, {0X23E9}, TXT_NULL, IMAGE_NULL },
    { 0X23EA, {0X23EA}, TXT_NULL, IMAGE_NULL },
    { 0X23EB, {0X23EB}, TXT_NULL, IMAGE_NULL },
    { 0X23EC, {0X23EC}, TXT_NULL, IMAGE_NULL },
    { 0X23F0, {0X23F0}, TXT_NULL, IMAGE_NULL },
    { 0X23F3, {0X23F3}, TXT_NULL, IMAGE_NULL },
    { 0X24C2, {0X24C2}, TXT_NULL, IMAGE_NULL },
    { 0X2600, {0X2600}, TXT_NULL, IMAGE_NULL },
    { 0X2601, {0X2601}, TXT_NULL, IMAGE_NULL },
    { 0X260E, {0X260E}, TXT_NULL, IMAGE_NULL },
    { 0X2611, {0X2611}, TXT_NULL, IMAGE_NULL },
    { 0X2614, {0X2614}, TXT_NULL, IMAGE_NULL },
    { 0X2615, {0X2615}, TXT_NULL, IMAGE_NULL },
    { 0X261D, {0X261D}, TXT_NULL, IMAGE_NULL },
    { 0X263A, {0X263A}, TXT_NULL, IMAGE_NULL },
    { 0X2648, {0X2648}, TXT_NULL, IMAGE_NULL },
    { 0X2649, {0X2649}, TXT_NULL, IMAGE_NULL },
    { 0X264A, {0X264A}, TXT_NULL, IMAGE_NULL },
    { 0X264B, {0X264B}, TXT_NULL, IMAGE_NULL },
    { 0X264C, {0X264C}, TXT_NULL, IMAGE_NULL },
    { 0X264D, {0X264D}, TXT_NULL, IMAGE_NULL },
    { 0X264E, {0X264E}, TXT_NULL, IMAGE_NULL },
    { 0X264F, {0X264F}, TXT_NULL, IMAGE_NULL },
    { 0X2650, {0X2650}, TXT_NULL, IMAGE_NULL },
    { 0X2651, {0X2651}, TXT_NULL, IMAGE_NULL },
    { 0X2652, {0X2652}, TXT_NULL, IMAGE_NULL },
    { 0X2653, {0X2653}, TXT_NULL, IMAGE_NULL },
    { 0X2660, {0X2660}, TXT_NULL, IMAGE_NULL },
    { 0X2663, {0X2663}, TXT_NULL, IMAGE_NULL },
    { 0X2665, {0X2665}, TXT_NULL, IMAGE_NULL },
    { 0X2666, {0X2666}, TXT_NULL, IMAGE_NULL },
    { 0X2668, {0X2668}, TXT_NULL, IMAGE_NULL },
    { 0X267B, {0X267B}, TXT_NULL, IMAGE_NULL },
    { 0X267F, {0X267F}, TXT_NULL, IMAGE_NULL },
    { 0X2693, {0X2693}, TXT_NULL, IMAGE_NULL },
    { 0X26A0, {0X26A0}, TXT_NULL, IMAGE_NULL },
    { 0X26A1, {0X26A1}, TXT_NULL, IMAGE_NULL },
    { 0X26BD, {0X26BD}, TXT_NULL, IMAGE_NULL },
    { 0X26BE, {0X26BE}, TXT_NULL, IMAGE_NULL },
    { 0X26C4, {0X26C4}, TXT_NULL, IMAGE_NULL },
    { 0X26C5, {0X26C5}, TXT_NULL, IMAGE_NULL },
    { 0X26CE, {0X26CE}, TXT_NULL, IMAGE_NULL },
    { 0X26D4, {0X26D4}, TXT_NULL, IMAGE_NULL },
    { 0X26EA, {0X26EA}, TXT_NULL, IMAGE_NULL },
    { 0X26F2, {0X26F2}, TXT_NULL, IMAGE_NULL },
    { 0X26F3, {0X26F3}, TXT_NULL, IMAGE_NULL },
    { 0X26F5, {0X26F5}, TXT_NULL, IMAGE_NULL },
    { 0X26FA, {0X26FA}, TXT_NULL, IMAGE_NULL },
    { 0X26FD, {0X26FD}, TXT_NULL, IMAGE_NULL },
    { 0X2702, {0X2702}, TXT_NULL, IMAGE_NULL },
    { 0X2705, {0X2705}, TXT_NULL, IMAGE_NULL },
    { 0X2708, {0X2708}, TXT_NULL, IMAGE_NULL },
    { 0X2709, {0X2709}, TXT_NULL, IMAGE_NULL },
    { 0X270A, {0X270A}, TXT_NULL, IMAGE_NULL },
    { 0X270B, {0X270B}, TXT_NULL, IMAGE_NULL },
    { 0X270C, {0X270C}, TXT_NULL, IMAGE_NULL },
    { 0X270F, {0X270F}, TXT_NULL, IMAGE_NULL },
    { 0X2712, {0X2712}, TXT_NULL, IMAGE_NULL },
    { 0X2714, {0X2714}, TXT_NULL, IMAGE_NULL },
    { 0X2716, {0X2716}, TXT_NULL, IMAGE_NULL },
    { 0X2728, {0X2728}, TXT_NULL, IMAGE_NULL },
    { 0X2733, {0X2733}, TXT_NULL, IMAGE_NULL },
    { 0X2734, {0X2734}, TXT_NULL, IMAGE_NULL },
    { 0X2744, {0X2744}, TXT_NULL, IMAGE_NULL },
    { 0X2747, {0X2747}, TXT_NULL, IMAGE_NULL },
    { 0X274C, {0X274C}, TXT_NULL, IMAGE_NULL },
    { 0X274E, {0X274E}, TXT_NULL, IMAGE_NULL },
    { 0X2753, {0X2753}, TXT_NULL, IMAGE_NULL },
    { 0X2754, {0X2754}, TXT_NULL, IMAGE_NULL },
    { 0X2755, {0X2755}, TXT_NULL, IMAGE_NULL },
    { 0X2757, {0X2757}, TXT_NULL, IMAGE_NULL },
    { 0X2764, {0X2764}, TXT_NULL, IMAGE_NULL },
    { 0X2795, {0X2795}, TXT_NULL, IMAGE_NULL },
    { 0X2796, {0X2796}, TXT_NULL, IMAGE_NULL },
    { 0X2797, {0X2797}, TXT_NULL, IMAGE_NULL },
    { 0X27A1, {0X27A1}, TXT_NULL, IMAGE_NULL },
    { 0X27B0, {0X27B0}, TXT_NULL, IMAGE_NULL },
    { 0X27BF, {0X27BF}, TXT_NULL, IMAGE_NULL },
    { 0X2934, {0X2934}, TXT_NULL, IMAGE_NULL },
    { 0X2935, {0X2935}, TXT_NULL, IMAGE_NULL },
    { 0X2B05, {0X2B05}, TXT_NULL, IMAGE_NULL },
    { 0X2B06, {0X2B06}, TXT_NULL, IMAGE_NULL },
    { 0X2B07, {0X2B07}, TXT_NULL, IMAGE_NULL },
    { 0X2B50, {0X2B50}, TXT_NULL, IMAGE_NULL },
    { 0X3297, {0X3297}, TXT_NULL, IMAGE_NULL },
    { 0X3299, {0X3299}, TXT_NULL, IMAGE_NULL },
#endif
    { 0X1F004, {0XE000}, TXT_NULL, IMAGE_NULL },
    { 0X1F0CF, {0XE001}, TXT_NULL, IMAGE_NULL },
    { 0X1F170, {0XE002}, TXT_NULL, IMAGE_NULL },
    { 0X1F171, {0XE003}, TXT_NULL, IMAGE_NULL },
    { 0X1F17E, {0XE004}, TXT_NULL, IMAGE_NULL },
    { 0X1F17F, {0XE005}, TXT_NULL, IMAGE_NULL },
    { 0X1F18E, {0XE006}, TXT_NULL, IMAGE_NULL },
    { 0X1F191, {0XE007}, TXT_NULL, IMAGE_NULL },
    { 0X1F192, {0XE008}, TXT_NULL, IMAGE_NULL },
    { 0X1F193, {0XE009}, TXT_NULL, IMAGE_NULL },
    { 0X1F194, {0XE00A}, TXT_NULL, IMAGE_NULL },
    { 0X1F195, {0XE00B}, TXT_NULL, IMAGE_NULL },
    { 0X1F196, {0XE00C}, TXT_NULL, IMAGE_NULL },
    { 0X1F197, {0XE00D}, TXT_NULL, IMAGE_NULL },
    { 0X1F198, {0XE00E}, TXT_NULL, IMAGE_NULL },
    { 0X1F199, {0XE00F}, TXT_NULL, IMAGE_NULL },
    { 0X1F19A, {0XE010}, TXT_NULL, IMAGE_NULL },
    { 0X1F1E6, {0XE011}, TXT_NULL, IMAGE_NULL },
    { 0X1F1E7, {0XE012}, TXT_NULL, IMAGE_NULL },
    { 0X1F1E8, {0XE013}, TXT_NULL, IMAGE_NULL },
    { 0X1F1E9, {0XE014}, TXT_NULL, IMAGE_NULL },
    { 0X1F1EA, {0XE015}, TXT_NULL, IMAGE_NULL },
    { 0X1F1EB, {0XE016}, TXT_NULL, IMAGE_NULL },
    { 0X1F1EC, {0XE017}, TXT_NULL, IMAGE_NULL },
    { 0X1F1ED, {0XE018}, TXT_NULL, IMAGE_NULL },
    { 0X1F1EE, {0XE019}, TXT_NULL, IMAGE_NULL },
    { 0X1F1EF, {0XE01A}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F0, {0XE01B}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F1, {0XE01C}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F2, {0XE01D}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F3, {0XE01E}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F4, {0XE01F}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F5, {0XE020}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F6, {0XE021}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F7, {0XE022}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F8, {0XE023}, TXT_NULL, IMAGE_NULL },
    { 0X1F1F9, {0XE024}, TXT_NULL, IMAGE_NULL },
    { 0X1F1FA, {0XE025}, TXT_NULL, IMAGE_NULL },
    { 0X1F1FB, {0XE026}, TXT_NULL, IMAGE_NULL },
    { 0X1F1FC, {0XE027}, TXT_NULL, IMAGE_NULL },
    { 0X1F1FD, {0XE028}, TXT_NULL, IMAGE_NULL },
    { 0X1F1FE, {0XE029}, TXT_NULL, IMAGE_NULL },
    { 0X1F1FF, {0XE02A}, TXT_NULL, IMAGE_NULL },
    { 0X1F201, {0XE02B}, TXT_NULL, IMAGE_NULL },
    { 0X1F202, {0XE02C}, TXT_NULL, IMAGE_NULL },
    { 0X1F21A, {0XE02D}, TXT_NULL, IMAGE_NULL },
    { 0X1F22F, {0XE02E}, TXT_NULL, IMAGE_NULL },
    { 0X1F232, {0XE02F}, TXT_NULL, IMAGE_NULL },
    { 0X1F233, {0XE030}, TXT_NULL, IMAGE_NULL },
    { 0X1F234, {0XE031}, TXT_NULL, IMAGE_NULL },
    { 0X1F235, {0XE032}, TXT_NULL, IMAGE_NULL },
    { 0X1F236, {0XE033}, TXT_NULL, IMAGE_NULL },
    { 0X1F237, {0XE034}, TXT_NULL, IMAGE_NULL },
    { 0X1F238, {0XE035}, TXT_NULL, IMAGE_NULL },
    { 0X1F239, {0XE036}, TXT_NULL, IMAGE_NULL },
    { 0X1F23A, {0XE037}, TXT_NULL, IMAGE_NULL },
    { 0X1F250, {0XE038}, TXT_NULL, IMAGE_NULL },
    { 0X1F251, {0XE039}, TXT_NULL, IMAGE_NULL },
    { 0X1F300, {0XE03A}, TXT_NULL, IMAGE_NULL },
    { 0X1F301, {0XE03B}, TXT_NULL, IMAGE_NULL },
    { 0X1F302, {0XE03C}, TXT_NULL, IMAGE_NULL },
    { 0X1F303, {0XE03D}, TXT_NULL, IMAGE_NULL },
    { 0X1F304, {0XE03E}, TXT_NULL, IMAGE_NULL },
    { 0X1F305, {0XE03F}, TXT_NULL, IMAGE_NULL },
    { 0X1F306, {0XE040}, TXT_NULL, IMAGE_NULL },
    { 0X1F307, {0XE041}, TXT_NULL, IMAGE_NULL },
    { 0X1F308, {0XE042}, TXT_NULL, IMAGE_NULL },
    { 0X1F309, {0XE043}, TXT_NULL, IMAGE_NULL },
    { 0X1F30A, {0XE044}, TXT_NULL, IMAGE_NULL },
    { 0X1F30B, {0XE045}, TXT_NULL, IMAGE_NULL },
    { 0X1F30C, {0XE046}, TXT_NULL, IMAGE_NULL },
    { 0X1F30D, {0XE047}, TXT_NULL, IMAGE_NULL },
    { 0X1F30E, {0XE048}, TXT_NULL, IMAGE_NULL },
    { 0X1F30F, {0XE049}, TXT_NULL, IMAGE_NULL },
    { 0X1F310, {0XE04A}, TXT_NULL, IMAGE_NULL },
    { 0X1F311, {0XE04B}, TXT_NULL, IMAGE_NULL },
    { 0X1F312, {0XE04C}, TXT_NULL, IMAGE_NULL },
    { 0X1F313, {0XE04D}, TXT_NULL, IMAGE_NULL },
    { 0X1F314, {0XE04E}, TXT_NULL, IMAGE_NULL },
    { 0X1F315, {0XE04F}, TXT_NULL, IMAGE_NULL },
    { 0X1F316, {0XE050}, TXT_NULL, IMAGE_NULL },
    { 0X1F317, {0XE051}, TXT_NULL, IMAGE_NULL },
    { 0X1F318, {0XE052}, TXT_NULL, IMAGE_NULL },
    { 0X1F319, {0XE053}, TXT_NULL, IMAGE_NULL },
    { 0X1F31A, {0XE054}, TXT_NULL, IMAGE_NULL },
    { 0X1F31B, {0XE055}, TXT_NULL, IMAGE_NULL },
    { 0X1F31C, {0XE056}, TXT_NULL, IMAGE_NULL },
    { 0X1F31D, {0XE057}, TXT_NULL, IMAGE_NULL },
    { 0X1F31E, {0XE058}, TXT_NULL, IMAGE_NULL },
    { 0X1F31F, {0XE059}, TXT_NULL, IMAGE_NULL },
    { 0X1F320, {0XE05A}, TXT_NULL, IMAGE_NULL },
    { 0X1F330, {0XE05B}, TXT_NULL, IMAGE_NULL },
    { 0X1F331, {0XE05C}, TXT_NULL, IMAGE_NULL },
    { 0X1F332, {0XE05D}, TXT_NULL, IMAGE_NULL },
    { 0X1F333, {0XE05E}, TXT_NULL, IMAGE_NULL },
    { 0X1F334, {0XE05F}, TXT_NULL, IMAGE_NULL },
    { 0X1F335, {0XE060}, TXT_NULL, IMAGE_NULL },
    { 0X1F337, {0XE061}, TXT_NULL, IMAGE_NULL },
    { 0X1F338, {0XE062}, TXT_NULL, IMAGE_NULL },
    { 0X1F339, {0XE063}, TXT_NULL, IMAGE_NULL },
    { 0X1F33A, {0XE064}, TXT_NULL, IMAGE_NULL },
    { 0X1F33B, {0XE065}, TXT_NULL, IMAGE_NULL },
    { 0X1F33C, {0XE066}, TXT_NULL, IMAGE_NULL },
    { 0X1F33D, {0XE067}, TXT_NULL, IMAGE_NULL },
    { 0X1F33E, {0XE068}, TXT_NULL, IMAGE_NULL },
    { 0X1F33F, {0XE069}, TXT_NULL, IMAGE_NULL },
    { 0X1F340, {0XE06A}, TXT_NULL, IMAGE_NULL },
    { 0X1F341, {0XE06B}, TXT_NULL, IMAGE_NULL },
    { 0X1F342, {0XE06C}, TXT_NULL, IMAGE_NULL },
    { 0X1F343, {0XE06D}, TXT_NULL, IMAGE_NULL },
    { 0X1F344, {0XE06E}, TXT_NULL, IMAGE_NULL },
    { 0X1F345, {0XE06F}, TXT_NULL, IMAGE_NULL },
    { 0X1F346, {0XE070}, TXT_NULL, IMAGE_NULL },
    { 0X1F347, {0XE071}, TXT_NULL, IMAGE_NULL },
    { 0X1F348, {0XE072}, TXT_NULL, IMAGE_NULL },
    { 0X1F349, {0XE073}, TXT_NULL, IMAGE_NULL },
    { 0X1F34A, {0XE074}, TXT_NULL, IMAGE_NULL },
    { 0X1F34B, {0XE075}, TXT_NULL, IMAGE_NULL },
    { 0X1F34C, {0XE076}, TXT_NULL, IMAGE_NULL },
    { 0X1F34D, {0XE077}, TXT_NULL, IMAGE_NULL },
    { 0X1F34E, {0XE078}, TXT_NULL, IMAGE_NULL },
    { 0X1F34F, {0XE079}, TXT_NULL, IMAGE_NULL },
    { 0X1F350, {0XE07A}, TXT_NULL, IMAGE_NULL },
    { 0X1F351, {0XE07B}, TXT_NULL, IMAGE_NULL },
    { 0X1F352, {0XE07C}, TXT_NULL, IMAGE_NULL },
    { 0X1F353, {0XE07D}, TXT_NULL, IMAGE_NULL },
    { 0X1F354, {0XE07E}, TXT_NULL, IMAGE_NULL },
    { 0X1F355, {0XE07F}, TXT_NULL, IMAGE_NULL },
    { 0X1F356, {0XE080}, TXT_NULL, IMAGE_NULL },
    { 0X1F357, {0XE081}, TXT_NULL, IMAGE_NULL },
    { 0X1F358, {0XE082}, TXT_NULL, IMAGE_NULL },
    { 0X1F359, {0XE083}, TXT_NULL, IMAGE_NULL },
    { 0X1F35A, {0XE084}, TXT_NULL, IMAGE_NULL },
    { 0X1F35B, {0XE085}, TXT_NULL, IMAGE_NULL },
    { 0X1F35C, {0XE086}, TXT_NULL, IMAGE_NULL },
    { 0X1F35D, {0XE087}, TXT_NULL, IMAGE_NULL },
    { 0X1F35E, {0XE088}, TXT_NULL, IMAGE_NULL },
    { 0X1F35F, {0XE089}, TXT_NULL, IMAGE_NULL },
    { 0X1F360, {0XE08A}, TXT_NULL, IMAGE_NULL },
    { 0X1F361, {0XE08B}, TXT_NULL, IMAGE_NULL },
    { 0X1F362, {0XE08C}, TXT_NULL, IMAGE_NULL },
    { 0X1F363, {0XE08D}, TXT_NULL, IMAGE_NULL },
    { 0X1F364, {0XE08E}, TXT_NULL, IMAGE_NULL },
    { 0X1F365, {0XE08F}, TXT_NULL, IMAGE_NULL },
    { 0X1F366, {0XE090}, TXT_NULL, IMAGE_NULL },
    { 0X1F367, {0XE091}, TXT_NULL, IMAGE_NULL },
    { 0X1F368, {0XE092}, TXT_NULL, IMAGE_NULL },
    { 0X1F369, {0XE093}, TXT_NULL, IMAGE_NULL },
    { 0X1F36A, {0XE094}, TXT_NULL, IMAGE_NULL },
    { 0X1F36B, {0XE095}, TXT_NULL, IMAGE_NULL },
    { 0X1F36C, {0XE096}, TXT_NULL, IMAGE_NULL },
    { 0X1F36D, {0XE097}, TXT_NULL, IMAGE_NULL },
    { 0X1F36E, {0XE098}, TXT_NULL, IMAGE_NULL },
    { 0X1F36F, {0XE099}, TXT_NULL, IMAGE_NULL },
    { 0X1F370, {0XE09A}, TXT_NULL, IMAGE_NULL },
    { 0X1F371, {0XE09B}, TXT_NULL, IMAGE_NULL },
    { 0X1F372, {0XE09C}, TXT_NULL, IMAGE_NULL },
    { 0X1F373, {0XE09D}, TXT_NULL, IMAGE_NULL },
    { 0X1F374, {0XE09E}, TXT_NULL, IMAGE_NULL },
    { 0X1F375, {0XE09F}, TXT_NULL, IMAGE_NULL },
    { 0X1F376, {0XE0A0}, TXT_NULL, IMAGE_NULL },
    { 0X1F377, {0XE0A1}, TXT_NULL, IMAGE_NULL },
    { 0X1F378, {0XE0A2}, TXT_NULL, IMAGE_NULL },
    { 0X1F379, {0XE0A3}, TXT_NULL, IMAGE_NULL },
    { 0X1F37A, {0XE0A4}, TXT_NULL, IMAGE_NULL },
    { 0X1F37B, {0XE0A5}, TXT_NULL, IMAGE_NULL },
    { 0X1F37C, {0XE0A6}, TXT_NULL, IMAGE_NULL },
    { 0X1F380, {0XE0A7}, TXT_NULL, IMAGE_NULL },
    { 0X1F381, {0XE0A8}, TXT_NULL, IMAGE_NULL },
    { 0X1F382, {0XE0A9}, TXT_NULL, IMAGE_NULL },
    { 0X1F383, {0XE0AA}, TXT_NULL, IMAGE_NULL },
    { 0X1F384, {0XE0AB}, TXT_NULL, IMAGE_NULL },
    { 0X1F385, {0XE0AC}, TXT_NULL, IMAGE_NULL },
    { 0X1F386, {0XE0AD}, TXT_NULL, IMAGE_NULL },
    { 0X1F387, {0XE0AE}, TXT_NULL, IMAGE_NULL },
    { 0X1F388, {0XE0AF}, TXT_NULL, IMAGE_NULL },
    { 0X1F389, {0XE0B0}, TXT_NULL, IMAGE_NULL },
    { 0X1F38A, {0XE0B1}, TXT_NULL, IMAGE_NULL },
    { 0X1F38B, {0XE0B2}, TXT_NULL, IMAGE_NULL },
    { 0X1F38C, {0XE0B3}, TXT_NULL, IMAGE_NULL },
    { 0X1F38D, {0XE0B4}, TXT_NULL, IMAGE_NULL },
    { 0X1F38E, {0XE0B5}, TXT_NULL, IMAGE_NULL },
    { 0X1F38F, {0XE0B6}, TXT_NULL, IMAGE_NULL },
    { 0X1F390, {0XE0B7}, TXT_NULL, IMAGE_NULL },
    { 0X1F391, {0XE0B8}, TXT_NULL, IMAGE_NULL },
    { 0X1F392, {0XE0B9}, TXT_NULL, IMAGE_NULL },
    { 0X1F393, {0XE0BA}, TXT_NULL, IMAGE_NULL },
    { 0X1F3A0, {0XE0BB}, TXT_NULL, IMAGE_NULL },
    { 0X1F3A1, {0XE0BC}, TXT_NULL, IMAGE_NULL },
    { 0X1F3A2, {0XE0BD}, TXT_NULL, IMAGE_NULL },
    { 0X1F3A3, {0XE0BE}, TXT_NULL, IMAGE_NULL },
    { 0X1F3A4, {0XE0BF}, TXT_NULL, IMAGE_NULL},
    { 0X1F3A5, {0XE0C0}, TXT_NULL, IMAGE_NULL},
    { 0X1F3A6, {0XE0C1}, TXT_NULL, IMAGE_NULL },
    { 0X1F3A7, {0XE0C2}, TXT_NULL, IMAGE_NULL },
    { 0X1F3A8, {0XE0C3}, TXT_NULL, IMAGE_NULL },
    { 0X1F3A9, {0XE0C4}, TXT_NULL, IMAGE_NULL },
    { 0X1F3AA, {0XE0C5}, TXT_NULL, IMAGE_NULL },
    { 0X1F3AB, {0XE0C6}, TXT_NULL, IMAGE_NULL },
    { 0X1F3AC, {0XE0C7}, TXT_NULL, IMAGE_NULL },
    { 0X1F3AD, {0XE0C8}, TXT_NULL, IMAGE_NULL },
    { 0X1F3AE, {0XE0C9}, TXT_NULL, IMAGE_NULL },
    { 0X1F3AF, {0XE0CA}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B0, {0XE0CB}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B1, {0XE0CC}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B2, {0XE0CD}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B3, {0XE0CE}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B4, {0XE0CF}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B5, {0XE0D0}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B6, {0XE0D1}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B7, {0XE0D2}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B8, {0XE0D3}, TXT_NULL, IMAGE_NULL },
    { 0X1F3B9, {0XE0D4}, TXT_NULL, IMAGE_NULL },
    { 0X1F3BA, {0XE0D5}, TXT_NULL, IMAGE_NULL },
    { 0X1F3BB, {0XE0D6}, TXT_NULL, IMAGE_NULL },
    { 0X1F3BC, {0XE0D7}, TXT_NULL, IMAGE_NULL },
    { 0X1F3BD, {0XE0D8}, TXT_NULL, IMAGE_NULL },
    { 0X1F3BE, {0XE0D9}, TXT_NULL, IMAGE_NULL },
    { 0X1F3BF, {0XE0DA}, TXT_NULL, IMAGE_NULL },
    { 0X1F3C0, {0XE0DB}, TXT_NULL, IMAGE_NULL },
    { 0X1F3C1, {0XE0DC}, TXT_NULL, IMAGE_NULL },
    { 0X1F3C2, {0XE0DD}, TXT_NULL, IMAGE_NULL },
    { 0X1F3C3, {0XE0DE}, TXT_NULL, IMAGE_NULL },
    { 0X1F3C4, {0XE0DF}, TXT_NULL, IMAGE_NULL },
    { 0X1F3C6, {0XE0E0}, TXT_NULL, IMAGE_NULL },
    { 0X1F3C7, {0XE0E1}, TXT_NULL, IMAGE_NULL },
    { 0X1F3C8, {0XE0E2}, TXT_NULL, IMAGE_NULL },
    { 0X1F3C9, {0XE0E3}, TXT_NULL, IMAGE_NULL },
    { 0X1F3CA, {0XE0E4}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E0, {0XE0E5}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E1, {0XE0E6}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E2, {0XE0E7}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E3, {0XE0E8}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E4, {0XE0E9}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E5, {0XE0EA}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E6, {0XE0EB}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E7, {0XE0EC}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E8, {0XE0ED}, TXT_NULL, IMAGE_NULL },
    { 0X1F3E9, {0XE0EE}, TXT_NULL, IMAGE_NULL },
    { 0X1F3EA, {0XE0EF}, TXT_NULL, IMAGE_NULL },
    { 0X1F3EB, {0XE0F0}, TXT_NULL, IMAGE_NULL },
    { 0X1F3EC, {0XE0F1}, TXT_NULL, IMAGE_NULL },
    { 0X1F3ED, {0XE0F2}, TXT_NULL, IMAGE_NULL },
    { 0X1F3EE, {0XE0F3}, TXT_NULL, IMAGE_NULL },
    { 0X1F3EF, {0XE0F4}, TXT_NULL, IMAGE_NULL },
    { 0X1F3F0, {0XE0F5}, TXT_NULL, IMAGE_NULL },
    { 0X1F400, {0XE0F6}, TXT_NULL, IMAGE_NULL },
    { 0X1F401, {0XE0F7}, TXT_NULL, IMAGE_NULL },
    { 0X1F402, {0XE0F8}, TXT_NULL, IMAGE_NULL },
    { 0X1F403, {0XE0F9}, TXT_NULL, IMAGE_NULL },
    { 0X1F404, {0XE0FA}, TXT_NULL, IMAGE_NULL },
    { 0X1F405, {0XE0FB}, TXT_NULL, IMAGE_NULL },
    { 0X1F406, {0XE0FC}, TXT_NULL, IMAGE_NULL },
    { 0X1F407, {0XE0FD}, TXT_NULL, IMAGE_NULL },
    { 0X1F408, {0XE0FE}, TXT_NULL, IMAGE_NULL },
    { 0X1F409, {0XE0FF}, TXT_NULL, IMAGE_NULL },
    { 0X1F40A, {0XE100}, TXT_NULL, IMAGE_NULL },
    { 0X1F40B, {0XE101}, TXT_NULL, IMAGE_NULL },
    { 0X1F40C, {0XE102}, TXT_NULL, IMAGE_NULL },
    { 0X1F40D, {0XE103}, TXT_NULL, IMAGE_NULL },
    { 0X1F40E, {0XE104}, TXT_NULL, IMAGE_NULL },
    { 0X1F40F, {0XE105}, TXT_NULL, IMAGE_NULL },
    { 0X1F410, {0XE106}, TXT_NULL, IMAGE_NULL },
    { 0X1F411, {0XE107}, TXT_NULL, IMAGE_NULL },
    { 0X1F412, {0XE108}, TXT_NULL, IMAGE_NULL },
    { 0X1F413, {0XE109}, TXT_NULL, IMAGE_NULL },
    { 0X1F414, {0XE10A}, TXT_NULL, IMAGE_NULL },
    { 0X1F415, {0XE10B}, TXT_NULL, IMAGE_NULL },
    { 0X1F416, {0XE10C}, TXT_NULL, IMAGE_NULL },
    { 0X1F417, {0XE10D}, TXT_NULL, IMAGE_NULL },
    { 0X1F418, {0XE10E}, TXT_NULL, IMAGE_NULL },
    { 0X1F419, {0XE10F}, TXT_NULL, IMAGE_NULL },
    { 0X1F41A, {0XE110}, TXT_NULL, IMAGE_NULL },
    { 0X1F41B, {0XE111}, TXT_NULL, IMAGE_NULL },
    { 0X1F41C, {0XE112}, TXT_NULL, IMAGE_NULL },
    { 0X1F41D, {0XE113}, TXT_NULL, IMAGE_NULL },
    { 0X1F41E, {0XE114}, TXT_NULL, IMAGE_NULL },
    { 0X1F41F, {0XE115}, TXT_NULL, IMAGE_NULL },
    { 0X1F420, {0XE116}, TXT_NULL, IMAGE_NULL },
    { 0X1F421, {0XE117}, TXT_NULL, IMAGE_NULL },
    { 0X1F422, {0XE118}, TXT_NULL, IMAGE_NULL },
    { 0X1F423, {0XE119}, TXT_NULL, IMAGE_NULL },
    { 0X1F424, {0XE11A}, TXT_NULL, IMAGE_NULL },
    { 0X1F425, {0XE11B}, TXT_NULL, IMAGE_NULL },
    { 0X1F426, {0XE11C}, TXT_NULL, IMAGE_NULL },
    { 0X1F427, {0XE11D}, TXT_NULL, IMAGE_NULL },
    { 0X1F428, {0XE11E}, TXT_NULL, IMAGE_NULL },
    { 0X1F429, {0XE11F}, TXT_NULL, IMAGE_NULL },
    { 0X1F42B, {0XE120}, TXT_NULL, IMAGE_NULL },
    { 0X1F42C, {0XE121}, TXT_NULL, IMAGE_NULL },
    { 0X1F42D, {0XE122}, TXT_NULL, IMAGE_NULL },
    { 0X1F42E, {0XE123}, TXT_NULL, IMAGE_NULL },
    { 0X1F42F, {0XE124}, TXT_NULL, IMAGE_NULL },
    { 0X1F430, {0XE125}, TXT_NULL, IMAGE_NULL },
    { 0X1F431, {0XE126}, TXT_NULL, IMAGE_NULL },
    { 0X1F432, {0XE127}, TXT_NULL, IMAGE_NULL },
    { 0X1F433, {0XE128}, TXT_NULL, IMAGE_NULL },
    { 0X1F434, {0XE129}, TXT_NULL, IMAGE_NULL },
    { 0X1F435, {0XE12A}, TXT_NULL, IMAGE_NULL },
    { 0X1F436, {0XE12B}, TXT_NULL, IMAGE_NULL },
    { 0X1F437, {0XE12C}, TXT_NULL, IMAGE_NULL },
    { 0X1F438, {0XE12D}, TXT_NULL, IMAGE_NULL },
    { 0X1F439, {0XE12E}, TXT_NULL, IMAGE_NULL },
    { 0X1F43A, {0XE12F}, TXT_NULL, IMAGE_NULL },
    { 0X1F43B, {0XE130}, TXT_NULL, IMAGE_NULL },
    { 0X1F43C, {0XE131}, TXT_NULL, IMAGE_NULL },
    { 0X1F43D, {0XE132}, TXT_NULL, IMAGE_NULL },
    { 0X1F43E, {0XE133}, TXT_NULL, IMAGE_NULL },
    { 0X1F440, {0XE134}, TXT_NULL, IMAGE_NULL },
    { 0X1F442, {0XE135}, TXT_NULL, IMAGE_NULL },
    { 0X1F443, {0XE136}, TXT_NULL, IMAGE_NULL },
    { 0X1F444, {0XE137}, TXT_NULL, IMAGE_NULL },
    { 0X1F445, {0XE138}, TXT_NULL, IMAGE_NULL },
    { 0X1F446, {0XE139}, TXT_NULL, IMAGE_NULL },
    { 0X1F447, {0XE13A}, TXT_NULL, IMAGE_NULL },
    { 0X1F448, {0XE13B}, TXT_NULL, IMAGE_NULL },
    { 0X1F449, {0XE13C}, TXT_NULL, IMAGE_NULL },
    { 0X1F44A, {0XE13D}, TXT_NULL, IMAGE_NULL },
    { 0X1F44B, {0XE13E}, TXT_NULL, IMAGE_NULL },
    { 0X1F44C, {0XE13F}, TXT_NULL, IMAGE_NULL },
    { 0X1F44D, {0XE140}, TXT_NULL, IMAGE_NULL },
    { 0X1F44E, {0XE141}, TXT_NULL, IMAGE_NULL },
    { 0X1F44F, {0XE142}, TXT_NULL, IMAGE_NULL },
    { 0X1F450, {0XE143}, TXT_NULL, IMAGE_NULL },
    { 0X1F451, {0XE144}, TXT_NULL, IMAGE_NULL },
    { 0X1F452, {0XE145}, TXT_NULL, IMAGE_NULL },
    { 0X1F453, {0XE146}, TXT_NULL, IMAGE_NULL },
    { 0X1F454, {0XE147}, TXT_NULL, IMAGE_NULL },
    { 0X1F455, {0XE148}, TXT_NULL, IMAGE_NULL },
    { 0X1F456, {0XE149}, TXT_NULL, IMAGE_NULL },
    { 0X1F457, {0XE14A}, TXT_NULL, IMAGE_NULL },
    { 0X1F458, {0XE14B}, TXT_NULL, IMAGE_NULL },
    { 0X1F459, {0XE14C}, TXT_NULL, IMAGE_NULL },
    { 0X1F45A, {0XE14D}, TXT_NULL, IMAGE_NULL },
    { 0X1F45B, {0XE14E}, TXT_NULL, IMAGE_NULL },
    { 0X1F45C, {0XE14F}, TXT_NULL, IMAGE_NULL },
    { 0X1F45D, {0XE150}, TXT_NULL, IMAGE_NULL },
    { 0X1F45E, {0XE151}, TXT_NULL, IMAGE_NULL },
    { 0X1F45F, {0XE152}, TXT_NULL, IMAGE_NULL },
    { 0X1F460, {0XE153}, TXT_NULL, IMAGE_NULL },
    { 0X1F461, {0XE154}, TXT_NULL, IMAGE_NULL },
    { 0X1F462, {0XE155}, TXT_NULL, IMAGE_NULL },
    { 0X1F463, {0XE156}, TXT_NULL, IMAGE_NULL },
    { 0X1F464, {0XE157}, TXT_NULL, IMAGE_NULL },
    { 0X1F465, {0XE158}, TXT_NULL, IMAGE_NULL },
    { 0X1F466, {0XE159}, TXT_NULL, IMAGE_NULL },
    { 0X1F467, {0XE15A}, TXT_NULL, IMAGE_NULL },
    { 0X1F468, {0XE15B}, TXT_NULL, IMAGE_NULL },
    { 0X1F469, {0XE15C}, TXT_NULL, IMAGE_NULL },
    { 0X1F46A, {0XE15D}, TXT_NULL, IMAGE_NULL },
    { 0X1F46B, {0XE15E}, TXT_NULL, IMAGE_NULL },
    { 0X1F46C, {0XE15F}, TXT_NULL, IMAGE_NULL },
    { 0X1F46D, {0XE160}, TXT_NULL, IMAGE_NULL },
    { 0X1F46E, {0XE161}, TXT_NULL, IMAGE_NULL },
    { 0X1F46F, {0XE162}, TXT_NULL, IMAGE_NULL },
    { 0X1F470, {0XE163}, TXT_NULL, IMAGE_NULL },
    { 0X1F471, {0XE164}, TXT_NULL, IMAGE_NULL },
    { 0X1F472, {0XE165}, TXT_NULL, IMAGE_NULL },
    { 0X1F473, {0XE166}, TXT_NULL, IMAGE_NULL },
    { 0X1F474, {0XE167}, TXT_NULL, IMAGE_NULL },
    { 0X1F475, {0XE168}, TXT_NULL, IMAGE_NULL },
    { 0X1F476, {0XE169}, TXT_NULL, IMAGE_NULL },
    { 0X1F477, {0XE16A}, TXT_NULL, IMAGE_NULL },
    { 0X1F478, {0XE16B}, TXT_NULL, IMAGE_NULL },
    { 0X1F479, {0XE16C}, TXT_NULL, IMAGE_NULL },
    { 0X1F47A, {0XE16D}, TXT_NULL, IMAGE_NULL },
    { 0X1F47B, {0XE16E}, TXT_NULL, IMAGE_NULL },
    { 0X1F47C, {0XE16F}, TXT_NULL, IMAGE_NULL },
    { 0X1F47D, {0XE170}, TXT_NULL, IMAGE_NULL },
    { 0X1F47E, {0XE171}, TXT_NULL, IMAGE_NULL },
    { 0X1F47F, {0XE172}, TXT_NULL, IMAGE_NULL },
    { 0X1F480, {0XE173}, TXT_NULL, IMAGE_NULL },
    { 0X1F481, {0XE174}, TXT_NULL, IMAGE_NULL },
    { 0X1F482, {0XE175}, TXT_NULL, IMAGE_NULL },
    { 0X1F483, {0XE176}, TXT_NULL, IMAGE_NULL },
    { 0X1F484, {0XE177}, TXT_NULL, IMAGE_NULL },
    { 0X1F485, {0XE178}, TXT_NULL, IMAGE_NULL },
    { 0X1F486, {0XE179}, TXT_NULL, IMAGE_NULL },
    { 0X1F487, {0XE17A}, TXT_NULL, IMAGE_NULL },
    { 0X1F488, {0XE17B}, TXT_NULL, IMAGE_NULL },
    { 0X1F489, {0XE17C}, TXT_NULL, IMAGE_NULL },
    { 0X1F48A, {0XE17D}, TXT_NULL, IMAGE_NULL },
    { 0X1F48B, {0XE17E}, TXT_NULL, IMAGE_NULL },
    { 0X1F48C, {0XE17F}, TXT_NULL, IMAGE_NULL },
    { 0X1F48D, {0XE180}, TXT_NULL, IMAGE_NULL },
    { 0X1F48E, {0XE181}, TXT_NULL, IMAGE_NULL },
    { 0X1F48F, {0XE182}, TXT_NULL, IMAGE_NULL },
    { 0X1F490, {0XE183}, TXT_NULL, IMAGE_NULL },
    { 0X1F491, {0XE184}, TXT_NULL, IMAGE_NULL },
    { 0X1F492, {0XE185}, TXT_NULL, IMAGE_NULL },
    { 0X1F493, {0XE186}, TXT_NULL, IMAGE_NULL },
    { 0X1F494, {0XE187}, TXT_NULL, IMAGE_NULL },
    { 0X1F495, {0XE188}, TXT_NULL, IMAGE_NULL },
    { 0X1F496, {0XE189}, TXT_NULL, IMAGE_NULL },
    { 0X1F497, {0XE18A}, TXT_NULL, IMAGE_NULL },
    { 0X1F498, {0XE18B}, TXT_NULL, IMAGE_NULL },
    { 0X1F499, {0XE18C}, TXT_NULL, IMAGE_NULL },
    { 0X1F49A, {0XE18D}, TXT_NULL, IMAGE_NULL },
    { 0X1F49B, {0XE18E}, TXT_NULL, IMAGE_NULL },
    { 0X1F49C, {0XE18F}, TXT_NULL, IMAGE_NULL },
    { 0X1F49D, {0XE190}, TXT_NULL, IMAGE_NULL },
    { 0X1F49E, {0XE191}, TXT_NULL, IMAGE_NULL },
    { 0X1F49F, {0XE192}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A0, {0XE193}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A1, {0XE194}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A2, {0XE195}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A3, {0XE196}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A4, {0XE197}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A5, {0XE198}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A6, {0XE199}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A7, {0XE19A}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A8, {0XE19B}, TXT_NULL, IMAGE_NULL },
    { 0X1F4A9, {0XE19C}, TXT_NULL, IMAGE_NULL },
    { 0X1F4AA, {0XE19D}, TXT_NULL, IMAGE_NULL },
    { 0X1F4AB, {0XE19E}, TXT_NULL, IMAGE_NULL },
    { 0X1F4AC, {0XE19F}, TXT_NULL, IMAGE_NULL },
    { 0X1F4AD, {0XE1A0}, TXT_NULL, IMAGE_NULL },
    { 0X1F4AE, {0XE1A1}, TXT_NULL, IMAGE_NULL },
    { 0X1F4AF, {0XE1A2}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B0, {0XE1A3}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B1, {0XE1A4}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B2, {0XE1A5}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B3, {0XE1A6}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B4, {0XE1A7}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B5, {0XE1A8}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B6, {0XE1A9}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B7, {0XE1AA}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B8, {0XE1AB}, TXT_NULL, IMAGE_NULL },
    { 0X1F4B9, {0XE1AC}, TXT_NULL, IMAGE_NULL },
    { 0X1F4BA, {0XE1AD}, TXT_NULL, IMAGE_NULL },
    { 0X1F4BB, {0XE1AE}, TXT_NULL, IMAGE_NULL },
    { 0X1F4BC, {0XE1AF}, TXT_NULL, IMAGE_NULL },
    { 0X1F4BD, {0XE1B0}, TXT_NULL, IMAGE_NULL },
    { 0X1F4BE, {0XE1B1}, TXT_NULL, IMAGE_NULL },
    { 0X1F4BF, {0XE1B2}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C0, {0XE1B3}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C1, {0XE1B4}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C2, {0XE1B5}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C3, {0XE1B6}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C4, {0XE1B7}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C5, {0XE1B8}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C6, {0XE1B9}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C7, {0XE1BA}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C8, {0XE1BB}, TXT_NULL, IMAGE_NULL },
    { 0X1F4C9, {0XE1BC}, TXT_NULL, IMAGE_NULL },
    { 0X1F4CA, {0XE1BD}, TXT_NULL, IMAGE_NULL },
    { 0X1F4CB, {0XE1BE}, TXT_NULL, IMAGE_NULL },
    { 0X1F4CC, {0XE1BF}, TXT_NULL, IMAGE_NULL },
    { 0X1F4CD, {0XE1C0}, TXT_NULL, IMAGE_NULL },
    { 0X1F4CE, {0XE1C1}, TXT_NULL, IMAGE_NULL },
    { 0X1F4CF, {0XE1C2}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D0, {0XE1C3}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D1, {0XE1C4}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D2, {0XE1C5}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D3, {0XE1C6}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D4, {0XE1C7}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D5, {0XE1C8}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D6, {0XE1C9}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D7, {0XE1CA}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D8, {0XE1CB}, TXT_NULL, IMAGE_NULL },
    { 0X1F4D9, {0XE1CC}, TXT_NULL, IMAGE_NULL },
    { 0X1F4DA, {0XE1CD}, TXT_NULL, IMAGE_NULL },
    { 0X1F4DB, {0XE1CE}, TXT_NULL, IMAGE_NULL },
    { 0X1F4DC, {0XE1CF}, TXT_NULL, IMAGE_NULL },
    { 0X1F4DD, {0XE1D0}, TXT_NULL, IMAGE_NULL },
    { 0X1F4DE, {0XE1D1}, TXT_NULL, IMAGE_NULL },
    { 0X1F4DF, {0XE1D2}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E0, {0XE1D3}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E1, {0XE1D4}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E2, {0XE1D5}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E3, {0XE1D6}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E4, {0XE1D7}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E5, {0XE1D8}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E6, {0XE1D9}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E7, {0XE1DA}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E8, {0XE1DB}, TXT_NULL, IMAGE_NULL },
    { 0X1F4E9, {0XE1DC}, TXT_NULL, IMAGE_NULL },
    { 0X1F4EA, {0XE1DD}, TXT_NULL, IMAGE_NULL },
    { 0X1F4EB, {0XE1DE}, TXT_NULL, IMAGE_NULL },
    { 0X1F4EC, {0XE1DF}, TXT_NULL, IMAGE_NULL },
    { 0X1F4ED, {0XE1E0}, TXT_NULL, IMAGE_NULL },
    { 0X1F4EE, {0XE1E1}, TXT_NULL, IMAGE_NULL },
    { 0X1F4EF, {0XE1E2}, TXT_NULL, IMAGE_NULL },
    { 0X1F4F0, {0XE1E3}, TXT_NULL, IMAGE_NULL },
    { 0X1F4F1, {0XE1E4}, TXT_NULL, IMAGE_NULL },
    { 0X1F4F2, {0XE1E5}, TXT_NULL, IMAGE_NULL },
    { 0X1F4F3, {0XE1E6}, TXT_NULL, IMAGE_NULL },
    { 0X1F4F4, {0XE1E7}, TXT_NULL, IMAGE_NULL },
    { 0X1F4F5, {0XE1E8}, TXT_NULL, IMAGE_NULL },
    { 0X1F4F6, {0XE1E9}, TXT_NULL, IMAGE_NULL },
    { 0X1F4F7, {0XE1EA}, TXT_NULL, IMAGE_NULL },
    { 0X1F4F9, {0XE1EB}, TXT_NULL, IMAGE_NULL },
    { 0X1F4FA, {0XE1EC}, TXT_NULL, IMAGE_NULL },
    { 0X1F4FB, {0XE1ED}, TXT_NULL, IMAGE_NULL },
    { 0X1F4FC, {0XE1EE}, TXT_NULL, IMAGE_NULL },
    { 0X1F500, {0XE1EF}, TXT_NULL, IMAGE_NULL },
    { 0X1F501, {0XE1F0}, TXT_NULL, IMAGE_NULL },
    { 0X1F502, {0XE1F1}, TXT_NULL, IMAGE_NULL },
    { 0X1F503, {0XE1F2}, TXT_NULL, IMAGE_NULL },
    { 0X1F504, {0XE1F3}, TXT_NULL, IMAGE_NULL },
    { 0X1F505, {0XE1F4}, TXT_NULL, IMAGE_NULL },
    { 0X1F506, {0XE1F5}, TXT_NULL, IMAGE_NULL },
    { 0X1F507, {0XE1F6}, TXT_NULL, IMAGE_NULL },
    { 0X1F508, {0XE1F7}, TXT_NULL, IMAGE_NULL },
    { 0X1F509, {0XE1F8}, TXT_NULL, IMAGE_NULL },
    { 0X1F50A, {0XE1F9}, TXT_NULL, IMAGE_NULL },
    { 0X1F50B, {0XE1FA}, TXT_NULL, IMAGE_NULL },
    { 0X1F50C, {0XE1FB}, TXT_NULL, IMAGE_NULL },
    { 0X1F50D, {0XE1FC}, TXT_NULL, IMAGE_NULL },
    { 0X1F50E, {0XE1FD}, TXT_NULL, IMAGE_NULL },
    { 0X1F50F, {0XE1FE}, TXT_NULL, IMAGE_NULL },
    { 0X1F510, {0XE1FF}, TXT_NULL, IMAGE_NULL },
    { 0X1F511, {0XE200}, TXT_NULL, IMAGE_NULL },
    { 0X1F512, {0XE201}, TXT_NULL, IMAGE_NULL },
    { 0X1F513, {0XE202}, TXT_NULL, IMAGE_NULL },
    { 0X1F514, {0XE203}, TXT_NULL, IMAGE_NULL },
    { 0X1F515, {0XE204}, TXT_NULL, IMAGE_NULL },
    { 0X1F516, {0XE205}, TXT_NULL, IMAGE_NULL },
    { 0X1F517, {0XE206}, TXT_NULL, IMAGE_NULL },
    { 0X1F518, {0XE207}, TXT_NULL, IMAGE_NULL },
    { 0X1F519, {0XE208}, TXT_NULL, IMAGE_NULL },
    { 0X1F51A, {0XE209}, TXT_NULL, IMAGE_NULL },
    { 0X1F51B, {0XE20A}, TXT_NULL, IMAGE_NULL },
    { 0X1F51C, {0XE20B}, TXT_NULL, IMAGE_NULL },
    { 0X1F51D, {0XE20C}, TXT_NULL, IMAGE_NULL },
    { 0X1F51E, {0XE20D}, TXT_NULL, IMAGE_NULL },
    { 0X1F51F, {0XE20E}, TXT_NULL, IMAGE_NULL },
    { 0X1F520, {0XE20F}, TXT_NULL, IMAGE_NULL },
    { 0X1F521, {0XE210}, TXT_NULL, IMAGE_NULL },
    { 0X1F522, {0XE211}, TXT_NULL, IMAGE_NULL },
    { 0X1F523, {0XE212}, TXT_NULL, IMAGE_NULL },
    { 0X1F524, {0XE213}, TXT_NULL, IMAGE_NULL },
    { 0X1F525, {0XE214}, TXT_NULL, IMAGE_NULL },
    { 0X1F526, {0XE215}, TXT_NULL, IMAGE_NULL },
    { 0X1F527, {0XE216}, TXT_NULL, IMAGE_NULL },
    { 0X1F528, {0XE217}, TXT_NULL, IMAGE_NULL },
    { 0X1F529, {0XE218}, TXT_NULL, IMAGE_NULL },
    { 0X1F52A, {0XE219}, TXT_NULL, IMAGE_NULL },
    { 0X1F52B, {0XE21A}, TXT_NULL, IMAGE_NULL },
    { 0X1F52C, {0XE21B}, TXT_NULL, IMAGE_NULL },
    { 0X1F52D, {0XE21C}, TXT_NULL, IMAGE_NULL },
    { 0X1F52E, {0XE21D}, TXT_NULL, IMAGE_NULL },
    { 0X1F52F, {0XE21E}, TXT_NULL, IMAGE_NULL },
    { 0X1F530, {0XE21F}, TXT_NULL, IMAGE_NULL },
    { 0X1F531, {0XE220}, TXT_NULL, IMAGE_NULL },
    { 0X1F532, {0XE221}, TXT_NULL, IMAGE_NULL },
    { 0X1F533, {0XE222}, TXT_NULL, IMAGE_NULL },
    { 0X1F534, {0XE223}, TXT_NULL, IMAGE_NULL },
    { 0X1F535, {0XE224}, TXT_NULL, IMAGE_NULL },
    { 0X1F536, {0XE225}, TXT_NULL, IMAGE_NULL },
    { 0X1F537, {0XE226}, TXT_NULL, IMAGE_NULL },
    { 0X1F538, {0XE227}, TXT_NULL, IMAGE_NULL },
    { 0X1F539, {0XE228}, TXT_NULL, IMAGE_NULL },
    { 0X1F53A, {0XE229}, TXT_NULL, IMAGE_NULL },
    { 0X1F53B, {0XE22A}, TXT_NULL, IMAGE_NULL },
    { 0X1F53C, {0XE22B}, TXT_NULL, IMAGE_NULL },
    { 0X1F53D, {0XE22C}, TXT_NULL, IMAGE_NULL },
    { 0X1F550, {0XE22D}, TXT_NULL, IMAGE_NULL },
    { 0X1F551, {0XE22E}, TXT_NULL, IMAGE_NULL },
    { 0X1F552, {0XE22F}, TXT_NULL, IMAGE_NULL },
    { 0X1F553, {0XE230}, TXT_NULL, IMAGE_NULL },
    { 0X1F554, {0XE231}, TXT_NULL, IMAGE_NULL },
    { 0X1F555, {0XE232}, TXT_NULL, IMAGE_NULL },
    { 0X1F556, {0XE233}, TXT_NULL, IMAGE_NULL },
    { 0X1F557, {0XE234}, TXT_NULL, IMAGE_NULL },
    { 0X1F558, {0XE235}, TXT_NULL, IMAGE_NULL },
    { 0X1F559, {0XE236}, TXT_NULL, IMAGE_NULL },
    { 0X1F55A, {0XE237}, TXT_NULL, IMAGE_NULL },
    { 0X1F55B, {0XE238}, TXT_NULL, IMAGE_NULL },
    { 0X1F55C, {0XE239}, TXT_NULL, IMAGE_NULL },
    { 0X1F55D, {0XE23A}, TXT_NULL, IMAGE_NULL },
    { 0X1F55E, {0XE23B}, TXT_NULL, IMAGE_NULL },
    { 0X1F55F, {0XE23C}, TXT_NULL, IMAGE_NULL },
    { 0X1F560, {0XE23D}, TXT_NULL, IMAGE_NULL },
    { 0X1F561, {0XE23E}, TXT_NULL, IMAGE_NULL },
    { 0X1F562, {0XE23F}, TXT_NULL, IMAGE_NULL },
    { 0X1F563, {0XE240}, TXT_NULL, IMAGE_NULL },
    { 0X1F564, {0XE241}, TXT_NULL, IMAGE_NULL },
    { 0X1F565, {0XE242}, TXT_NULL, IMAGE_NULL },
    { 0X1F566, {0XE243}, TXT_NULL, IMAGE_NULL },
    { 0X1F567, {0XE244}, TXT_NULL, IMAGE_NULL },
    { 0X1F5FB, {0XE245}, TXT_NULL, IMAGE_NULL },
    { 0X1F5FC, {0XE246}, TXT_NULL, IMAGE_NULL },
    { 0X1F5FD, {0XE247}, TXT_NULL, IMAGE_NULL },
    { 0X1F5FE, {0XE248}, TXT_NULL, IMAGE_NULL },
    { 0X1F5FF, {0XE249}, TXT_NULL, IMAGE_NULL },
    { 0X1F600, {0XE24A}, TXT_NULL, IMAGE_NULL },
    { 0X1F601, {0XE24B}, TXT_NULL, IMAGE_NULL },
    { 0X1F602, {0XE24C}, TXT_NULL, IMAGE_NULL },
    { 0X1F603, {0XE24D}, TXT_NULL, IMAGE_NULL },
    { 0X1F604, {0XE24E}, TXT_NULL, IMAGE_NULL },
    { 0X1F605, {0XE24F}, TXT_NULL, IMAGE_NULL },
    { 0X1F606, {0XE250}, TXT_NULL, IMAGE_NULL },
    { 0X1F607, {0XE251}, TXT_NULL, IMAGE_NULL },
    { 0X1F608, {0XE252}, TXT_NULL, IMAGE_NULL },
    { 0X1F609, {0XE253}, TXT_NULL, IMAGE_NULL },
    { 0X1F60A, {0XE254}, TXT_NULL, IMAGE_NULL },
    { 0X1F60B, {0XE255}, TXT_NULL, IMAGE_NULL },
    { 0X1F60C, {0XE256}, TXT_NULL, IMAGE_NULL },
    { 0X1F60D, {0XE257}, TXT_NULL, IMAGE_NULL },
    { 0X1F60E, {0XE258}, TXT_NULL, IMAGE_NULL },
    { 0X1F60F, {0XE259}, TXT_NULL, IMAGE_NULL },
    { 0X1F610, {0XE25A}, TXT_NULL, IMAGE_NULL },
    { 0X1F611, {0XE25B}, TXT_NULL, IMAGE_NULL },
    { 0X1F612, {0XE25C}, TXT_NULL, IMAGE_NULL },
    { 0X1F613, {0XE25D}, TXT_NULL, IMAGE_NULL },
    { 0X1F614, {0XE25E}, TXT_NULL, IMAGE_NULL },
    { 0X1F615, {0XE25F}, TXT_NULL, IMAGE_NULL },
    { 0X1F616, {0XE260}, TXT_NULL, IMAGE_NULL },
    { 0X1F617, {0XE261}, TXT_NULL, IMAGE_NULL },
    { 0X1F618, {0XE262}, TXT_NULL, IMAGE_NULL },
    { 0X1F619, {0XE263}, TXT_NULL, IMAGE_NULL },
    { 0X1F61A, {0XE264}, TXT_NULL, IMAGE_NULL },
    { 0X1F61B, {0XE265}, TXT_NULL, IMAGE_NULL },
    { 0X1F61C, {0XE266}, TXT_NULL, IMAGE_NULL },
    { 0X1F61D, {0XE267}, TXT_NULL, IMAGE_NULL },
    { 0X1F61E, {0XE268}, TXT_NULL, IMAGE_NULL },
    { 0X1F61F, {0XE269}, TXT_NULL, IMAGE_NULL },
    { 0X1F620, {0XE26A}, TXT_NULL, IMAGE_NULL },
    { 0X1F621, {0XE26B}, TXT_NULL, IMAGE_NULL },
    { 0X1F622, {0XE26C}, TXT_NULL, IMAGE_NULL },
    { 0X1F623, {0XE26D}, TXT_NULL, IMAGE_NULL },
    { 0X1F624, {0XE26E}, TXT_NULL, IMAGE_NULL },
    { 0X1F625, {0XE26F}, TXT_NULL, IMAGE_NULL },
    { 0X1F626, {0XE270}, TXT_NULL, IMAGE_NULL },
    { 0X1F627, {0XE271}, TXT_NULL, IMAGE_NULL },
    { 0X1F628, {0XE272}, TXT_NULL, IMAGE_NULL },
    { 0X1F629, {0XE273}, TXT_NULL, IMAGE_NULL },
    { 0X1F62A, {0XE274}, TXT_NULL, IMAGE_NULL },
    { 0X1F62B, {0XE275}, TXT_NULL, IMAGE_NULL },
    { 0X1F62C, {0XE276}, TXT_NULL, IMAGE_NULL },
    { 0X1F62D, {0XE277}, TXT_NULL, IMAGE_NULL },
    { 0X1F62E, {0XE278}, TXT_NULL, IMAGE_NULL },
    { 0X1F62F, {0XE279}, TXT_NULL, IMAGE_NULL },
    { 0X1F630, {0XE27A}, TXT_NULL, IMAGE_NULL },
    { 0X1F631, {0XE27B}, TXT_NULL, IMAGE_NULL },
    { 0X1F632, {0XE27C}, TXT_NULL, IMAGE_NULL },
    { 0X1F633, {0XE27D}, TXT_NULL, IMAGE_NULL },
    { 0X1F634, {0XE27E}, TXT_NULL, IMAGE_NULL },
    { 0X1F635, {0XE27F}, TXT_NULL, IMAGE_NULL },
    { 0X1F636, {0XE280}, TXT_NULL, IMAGE_NULL },
    { 0X1F637, {0XE281}, TXT_NULL, IMAGE_NULL },
    { 0X1F638, {0XE282}, TXT_NULL, IMAGE_NULL },
    { 0X1F639, {0XE283}, TXT_NULL, IMAGE_NULL },
    { 0X1F63A, {0XE284}, TXT_NULL, IMAGE_NULL },
    { 0X1F63B, {0XE285}, TXT_NULL, IMAGE_NULL },
    { 0X1F63C, {0XE286}, TXT_NULL, IMAGE_NULL },
    { 0X1F63D, {0XE287}, TXT_NULL, IMAGE_NULL },
    { 0X1F63E, {0XE288}, TXT_NULL, IMAGE_NULL },
    { 0X1F63F, {0XE289}, TXT_NULL, IMAGE_NULL },
    { 0X1F640, {0XE28A}, TXT_NULL, IMAGE_NULL },
    { 0X1F645, {0XE28B}, TXT_NULL, IMAGE_NULL },
    { 0X1F646, {0XE28C}, TXT_NULL, IMAGE_NULL },
    { 0X1F647, {0XE28D}, TXT_NULL, IMAGE_NULL },
    { 0X1F648, {0XE28E}, TXT_NULL, IMAGE_NULL },
    { 0X1F649, {0XE28F}, TXT_NULL, IMAGE_NULL },
    { 0X1F64A, {0XE290}, TXT_NULL, IMAGE_NULL },
    { 0X1F64B, {0XE291}, TXT_NULL, IMAGE_NULL },
    { 0X1F64C, {0XE292}, TXT_NULL, IMAGE_NULL },
    { 0X1F64D, {0XE293}, TXT_NULL, IMAGE_NULL },
    { 0X1F64E, {0XE294}, TXT_NULL, IMAGE_NULL },
    { 0X1F64F, {0XE295}, TXT_NULL, IMAGE_NULL },
    { 0X1F680, {0XE296}, TXT_NULL, IMAGE_NULL },
    { 0X1F681, {0XE297}, TXT_NULL, IMAGE_NULL },
    { 0X1F682, {0XE298}, TXT_NULL, IMAGE_NULL },
    { 0X1F683, {0XE299}, TXT_NULL, IMAGE_NULL },
    { 0X1F684, {0XE29A}, TXT_NULL, IMAGE_NULL },
    { 0X1F685, {0XE29B}, TXT_NULL, IMAGE_NULL },
    { 0X1F686, {0XE29C}, TXT_NULL, IMAGE_NULL },
    { 0X1F687, {0XE29D}, TXT_NULL, IMAGE_NULL },
    { 0X1F688, {0XE29E}, TXT_NULL, IMAGE_NULL },
    { 0X1F689, {0XE29F}, TXT_NULL, IMAGE_NULL },
    { 0X1F68A, {0XE2A0}, TXT_NULL, IMAGE_NULL },
    { 0X1F68B, {0XE2A1}, TXT_NULL, IMAGE_NULL },
    { 0X1F68C, {0XE2A2}, TXT_NULL, IMAGE_NULL },
    { 0X1F68D, {0XE2A3}, TXT_NULL, IMAGE_NULL },
    { 0X1F68E, {0XE2A4}, TXT_NULL, IMAGE_NULL },
    { 0X1F68F, {0XE2A5}, TXT_NULL, IMAGE_NULL },
    { 0X1F690, {0XE2A6}, TXT_NULL, IMAGE_NULL },
    { 0X1F691, {0XE2A7}, TXT_NULL, IMAGE_NULL },
    { 0X1F692, {0XE2A8}, TXT_NULL, IMAGE_NULL },
    { 0X1F693, {0XE2A9}, TXT_NULL, IMAGE_NULL },
    { 0X1F694, {0XE2AA}, TXT_NULL, IMAGE_NULL },
    { 0X1F695, {0XE2AB}, TXT_NULL, IMAGE_NULL },
    { 0X1F696, {0XE2AC}, TXT_NULL, IMAGE_NULL },
    { 0X1F697, {0XE2AD}, TXT_NULL, IMAGE_NULL },
    { 0X1F699, {0XE2AE}, TXT_NULL, IMAGE_NULL },
    { 0X1F69A, {0XE2AF}, TXT_NULL, IMAGE_NULL },
    { 0X1F69B, {0XE2B0}, TXT_NULL, IMAGE_NULL },
    { 0X1F69C, {0XE2B1}, TXT_NULL, IMAGE_NULL },
    { 0X1F69D, {0XE2B2}, TXT_NULL, IMAGE_NULL },
    { 0X1F69E, {0XE2B3}, TXT_NULL, IMAGE_NULL },
    { 0X1F69F, {0XE2B4}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A0, {0XE2B5}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A1, {0XE2B6}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A2, {0XE2B7}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A3, {0XE2B8}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A4, {0XE2B9}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A5, {0XE2BA}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A6, {0XE2BB}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A7, {0XE2BC}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A8, {0XE2BD}, TXT_NULL, IMAGE_NULL },
    { 0X1F6A9, {0XE2BE}, TXT_NULL, IMAGE_NULL },
    { 0X1F6AA, {0XE2BF}, TXT_NULL, IMAGE_NULL },
    { 0X1F6AB, {0XE2C0}, TXT_NULL, IMAGE_NULL },
    { 0X1F6AC, {0XE2C1}, TXT_NULL, IMAGE_NULL },
    { 0X1F6AD, {0XE2C2}, TXT_NULL, IMAGE_NULL },
    { 0X1F6AE, {0XE2C3}, TXT_NULL, IMAGE_NULL },
    { 0X1F6AF, {0XE2C4}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B0, {0XE2C5}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B1, {0XE2C6}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B2, {0XE2C7}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B3, {0XE2C8}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B4, {0XE2C9}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B5, {0XE2CA}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B6, {0XE2CB}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B7, {0XE2CC}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B8, {0XE2CD}, TXT_NULL, IMAGE_NULL },
    { 0X1F6B9, {0XE2CE}, TXT_NULL, IMAGE_NULL },
    { 0X1F6BA, {0XE2CF}, TXT_NULL, IMAGE_NULL },
    { 0X1F6BB, {0XE2D0}, TXT_NULL, IMAGE_NULL },
    { 0X1F6BC, {0XE2D1}, TXT_NULL, IMAGE_NULL },
    { 0X1F6BD, {0XE2D2}, TXT_NULL, IMAGE_NULL },
    { 0X1F6BE, {0XE2D3}, TXT_NULL, IMAGE_NULL },
    { 0X1F6BF, {0XE2D4}, TXT_NULL, IMAGE_NULL },
    { 0X1F6C0, {0XE2D5}, TXT_NULL, IMAGE_NULL },
    { 0X1F6C1, {0XE2D6}, TXT_NULL, IMAGE_NULL },
    { 0X1F6C2, {0XE2D7}, TXT_NULL, IMAGE_NULL },
    { 0X1F6C3, {0XE2D8}, TXT_NULL, IMAGE_NULL },
    { 0X1F6C4, {0XE2D9}, TXT_NULL, IMAGE_NULL },
    { 0X1F6C5, {0XE2DA}, TXT_NULL, IMAGE_NULL },
    { 0XFE4E5, {0XE2DB}, TXT_NULL, IMAGE_NULL },
    { 0XFE4E6, {0XE2DC}, TXT_NULL, IMAGE_NULL },
    { 0XFE4E7, {0XE2DD}, TXT_NULL, IMAGE_NULL },
    { 0XFE4E8, {0XE2DE}, TXT_NULL, IMAGE_NULL },
    { 0XFE4E9, {0XE2DF}, TXT_NULL, IMAGE_NULL },
    { 0XFE4EA, {0XE2E0}, TXT_NULL, IMAGE_NULL },
    { 0XFE4EB, {0XE2E1}, TXT_NULL, IMAGE_NULL },
    { 0XFE4EC, {0XE2E2}, TXT_NULL, IMAGE_NULL },
    { 0XFE4ED, {0XE2E3}, TXT_NULL, IMAGE_NULL },
    { 0XFE4EE, {0XE2E4}, TXT_NULL, IMAGE_NULL },
    { 0XFE82C, {0XE2E5}, TXT_NULL, IMAGE_NULL },
    { 0XFE82E, {0XE2E6}, TXT_NULL, IMAGE_NULL },
    { 0XFE82F, {0XE2E7}, TXT_NULL, IMAGE_NULL },
    { 0XFE830, {0XE2E8}, TXT_NULL, IMAGE_NULL },
    { 0XFE831, {0XE2E9}, TXT_NULL, IMAGE_NULL },
    { 0XFE832, {0XE2EA}, TXT_NULL, IMAGE_NULL },
    { 0XFE833, {0XE2EB}, TXT_NULL, IMAGE_NULL },
    { 0XFE834, {0XE2EC}, TXT_NULL, IMAGE_NULL },
    { 0XFE835, {0XE2ED}, TXT_NULL, IMAGE_NULL },
    { 0XFE836, {0XE2EE}, TXT_NULL, IMAGE_NULL },
    { 0XFE837, {0XE2EF}, TXT_NULL, IMAGE_NULL },
};  


typedef struct
{
    //MMI_HANDLE_T im_handle;
    
    GUI_LCD_DEV_INFO lcd_dev_info;

    MMI_WIN_ID_T win_id;
    GUI_RECT_T win_rect;
    GUI_RECT_T title_rect;
    //panel
    GUI_RECT_T rect_emoji;
    uint16 row;
    uint16 col;

    //key list
    MMISMS_EMOJI_COMMON_KEY_T *last_key_ptr;
    MMISMS_EMOJI_COMMON_KEY_T key_pageup;
    MMISMS_EMOJI_COMMON_KEY_T key_pagedown;

    //page tips
    GUI_RECT_T rect_page_tip;

    //color
    GUI_COLOR_T color_bg;
    GUI_COLOR_T color_border;
    GUI_COLOR_T color_font;
    GUI_COLOR_T color_hot;

    GUI_FONT_T font;
    GUI_FONT_T font_min;
    GUI_FONT_T font_label;

    //disp
    uint16 row_cnt;
    uint16 first_row;
    uint16 hot_idx;

    //data
    uint16 per_max_cnt;
    uint16 page;
//    wchar emoji_list[MMISMS_EMOJI_NUM_LIST];
    uint32 emoji_cnt;
} MMISMS_EMOJI_WIN_DATA_T;

typedef enum
{
    MMISMS_EMOJI_HOT_BEGIN,
    MMISMS_EMOJI_HOT_HOLD,
    MMISMS_EMOJI_HOT_HOLD_COL,
    MMISMS_EMOJI_HOT_END
} MMISMS_EMOJI_HOT_TYPE_T;

LOCAL MMISMS_EMOJI_WIN_DATA_T *win_data_ptr = PNULL;

/** -------------------------------------------------------------------------*/
//                          LOCAL FUNCTIONS                                 //
/** -------------------------------------------------------------------------*/
/*****************************************************************************/
//     Description : to handle the message of window which choice the phiz
//    Global resource dependence :
//  Author: Tracy Zhang
//    Note:
/*****************************************************************************/
LOCAL MMI_RESULT_E HandleEmojiListWinMsg(
    MMI_WIN_ID_T        win_id,        //IN:
    MMI_MESSAGE_ID_E    msg_id,        //IN:
    DPARAM                param        //IN:
);
/*****************************************************************************/
//     Description : init smiley
//    Global resource dependence :
//  Author: 
//    Note:
/*****************************************************************************/
LOCAL void  InitEmojiData(MMISMS_EMOJI_WIN_DATA_T *win_data_ptr);
/*==============================================================================
Function Name: GetHotPos
Description: GetHotPos
Author: 
Global resource dependence: NONE
Note: 负行的修正
==============================================================================*/
LOCAL BOOLEAN GetHotPos(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    uint16 *row_ptr,
    uint16 *col_ptr
    );
/*==============================================================================
Function Name: GetSymbRect
Description: 获取指定位置的背景框大小
Author: 
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN GetEmojiRect(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    uint16 row,
    uint16 col,
    GUI_RECT_T *rect_ptr
);
/*==============================================================================
Function Name: MMIIM_SP_SYMB_GetSymbStrPtr
Description: 获取字符串的指针
Author: 
Global resource dependence: NONE
Note: 宽字符，0结尾
==============================================================================*/
wchar const * MMISMS_GetEmojiStrPtr(uint32 index);

/*****************************************************************************/
//     Description : draw phiz data
//    Global resource dependence :
//  Author:
//    Note:
/*****************************************************************************/
LOCAL void DrawEmojiWin(MMISMS_EMOJI_WIN_DATA_T *win_data_ptr);

/*==============================================================================
Function Name: ResetPageFlag
Description: ResetPageFlag
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL void ResetPageFlag(MMISMS_EMOJI_WIN_DATA_T *win_data_ptr);

/*==============================================================================
Function Name: MMISMS_EMOJI_ComKeyDraw
Description: MMISMS_EMOJI_ComKeyDraw
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN MMISMS_EMOJI_ComKeyDraw(
    GUI_LCD_DEV_INFO *lcd_info_ptr,
    MMISMS_EMOJI_COMMON_KEY_T *key_ptr
    );

/*==============================================================================
Function Name: PageDown
Description: PageDown
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN PageDown(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    MMISMS_EMOJI_HOT_TYPE_T hot_type
    );

/*==============================================================================
Function Name: PageUp
Description: PageUp
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN PageUp(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    MMISMS_EMOJI_HOT_TYPE_T hot_type
    );

#if (defined (TOUCH_PANEL_SUPPORT))
/*==============================================================================
Function Name: HandleEmojiWinTpDown
Description: HandleEmojiWinTpDown
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN HandleEmojiWinTpDown(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    DPARAM param
    );

/*==============================================================================
Function Name: HandleEmojiWinTpMove
Description: HandleEmojiWinTpMove
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN HandleEmojiWinTpMove(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    DPARAM param
    );

/*==============================================================================
Function Name: HandleEmojiWinTpUp
Description: HandleEmojiWinTpUp
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN HandleEmojiWinTpUp(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    DPARAM param
    );

/*==============================================================================
Function Name: GetTpPos
Description: GetTpPos
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL int32 GetTpPos(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    DPARAM param
    );

/*==============================================================================
Function Name: MMISMS_Emoji_ComKeyPress
Description: MMISMS_Emoji_ComKeyPress
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN MMISMS_Emoji_ComKeyPress(MMISMS_EMOJI_COMMON_KEY_T *key_ptr);

/*==============================================================================
Function Name: MMISMS_Emoji_ComkeyRelease
Description: MMISMS_Emoji_ComkeyRelease
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN MMISMS_Emoji_ComkeyRelease(MMISMS_EMOJI_COMMON_KEY_T *key_ptr);
#endif

/** -------------------------------------------------------------------------*/
//                          WINTAB DEFINES                                  //
/** -------------------------------------------------------------------------*/

// the phiz list window
WINDOW_TABLE( MMISMS_EMOJILIST_WIN_TAB ) =
{
    //WIN_TITLE( TXT_SMS_EMOJI ),
    WIN_FUNC((uint32) HandleEmojiListWinMsg),
    WIN_ID( MMISMS_EMOJILIST_WIN_ID ),
    WIN_HIDE_STATUS,
#ifdef MMI_PDA_SUPPORT
    WIN_SOFTKEY(TXT_NULL, TXT_NULL, STXT_RETURN),
#else
    //WIN_SOFTKEY(TXT_NULL, STXT_SELECT, TXT_COMMON_COMMON_BACK),
#endif
//    CREATE_ICONLIST_CTRL(GUILIST_TEXTLIST_E, MMISMS_EMOJI_ICONLIST_CTRL_ID),
    END_WIN
};

/** -------------------------------------------------------------------------*/
//                          Function definition                              //
/** -------------------------------------------------------------------------*/
/*****************************************************************************/
//     Description : enter emoji win
//    Global resource dependence :
//  Author:
//    Note:
/*****************************************************************************/
PUBLIC void MMISMS_OpenEmojiWin(void)
{
    MMI_WIN_ID_T win_id = MMISMS_EMOJILIST_WIN_ID;
#ifdef ADULT_WATCH_SUPPORT //bug:1921665
    BOOLEAN sNotInited = FALSE;
    sNotInited = MMIAPIPHONE_GetSimExistedStatus(MN_DUAL_SYS_1);
    if(FALSE == sNotInited)
    {
        MMI_STRING_T no_sim_text = {0};
        wchar temp_arr[20 + 1] = {0};
        no_sim_text.wstr_ptr = temp_arr;
        MMI_GetLabelTextByLang(TXT_SMS_INSERT_SIM, &no_sim_text);
        Adult_WatchCOM_NoteWin_1Icon_1Str_Enter(MMISMS_NOTE_WIN_ID,&no_sim_text,IMAGE_SMS_NO_SIM,PNULL);
        return;
    }
#endif
    win_data_ptr = (MMISMS_EMOJI_WIN_DATA_T*)SCI_ALLOC_APP(sizeof(MMISMS_EMOJI_WIN_DATA_T));
    SCI_MEMSET(win_data_ptr, 0, sizeof(MMISMS_EMOJI_WIN_DATA_T));

    if (MMK_IsOpenWin(win_id))
    {
        MMK_CloseWin(win_id);
    }

    MMK_CreateWin((uint32*)MMISMS_EMOJILIST_WIN_TAB, PNULL);
}

/*==============================================================================
Function Name: GetHotPos
Description: GetHotPos
Author: Lianxiang.Zhou
Global resource dependence: NONE
Note: 负行的修正
==============================================================================*/
LOCAL BOOLEAN GetHotPos(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    uint16 *row_ptr,
    uint16 *col_ptr
    )
{
    int16 hot_idx = 0;

    if (PNULL == win_data_ptr)
    {
        return FALSE;
    }

    hot_idx = win_data_ptr->hot_idx;
    hot_idx -= win_data_ptr->first_row * win_data_ptr->col;

    if (hot_idx < 0)
    {
        //如果是负的，则从-1行还是算，因为没有-0行
        hot_idx -= win_data_ptr->col;
    }

    *row_ptr = hot_idx / win_data_ptr->col;
    *col_ptr = hot_idx % win_data_ptr->col;

    return TRUE;
}
/*==============================================================================
Function Name: GetSymbRect
Description: 获取指定位置的背景框大小
Author: Lianxiang.Zhou
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN GetEmojiRect(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    uint16 row,
    uint16 col,
    GUI_RECT_T *rect_ptr
)
{
    uint16 rect_width = 0;
    uint16 rect_height = 0;
    uint16 unit_width = 0;
    uint16 unit_height = 0;

    if (row >= win_data_ptr->row || col >= win_data_ptr->col)
    {
        return FALSE;
    }

    rect_width = win_data_ptr->rect_emoji.right - win_data_ptr->rect_emoji.left + 1;
    rect_height = win_data_ptr->rect_emoji.bottom - win_data_ptr->rect_emoji.top + 1;
    unit_width = rect_width / win_data_ptr->col;
    unit_height = rect_height / win_data_ptr->row;

    rect_ptr->top = win_data_ptr->rect_emoji.top + unit_height * row;
    rect_ptr->left = win_data_ptr->rect_emoji.left + unit_width * col;
    rect_ptr->bottom = (row == win_data_ptr->row - 1) ?
                       win_data_ptr->rect_emoji.bottom : (rect_ptr->top + unit_height);
    rect_ptr->right = (col == win_data_ptr->col - 1) ?
                      win_data_ptr->rect_emoji.right : (rect_ptr->left + unit_width);

    rect_ptr->top++;
    rect_ptr->left++;
    rect_ptr->bottom--;
    rect_ptr->right--;

    return TRUE;
}
/*==============================================================================
Function Name: MMIIM_SP_SYMB_GetSymbStrPtr
Description: 获取字符串的指针
Author: 
Global resource dependence: NONE
Note: 宽字符，0结尾
==============================================================================*/
wchar const *MMISMS_GetEmojiStrPtr(uint32 index)
{
    wchar const *emoji_str_ptr = NULL;

    emoji_str_ptr = &(s_emoji_image_text_convert_table[index].data);
   
    return emoji_str_ptr;
}

/*==============================================================================
Function Name: MMISMS_EMOJI_ComKeyDraw
Description: MMISMS_EMOJI_ComKeyDraw
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN MMISMS_EMOJI_ComKeyDraw(
    GUI_LCD_DEV_INFO *lcd_info_ptr,
    MMISMS_EMOJI_COMMON_KEY_T *key_ptr
    )
{
    const GUI_COLOR_T bg_color_inactive[4] = {0x9cd3, 0x9cd3, 0x9cd3, 0x9cd3};
    const GUI_COLOR_T bg_color_active[4] = {0x9cd3, 0x528a, 0x0040, 0x0040};
    const GUI_COLOR_T bg_color_press[4] = {0xfc82, 0xfc82, 0xfc82, 0xfc82};
    const GUI_COLOR_T color_font = 0xe71c;
    const GUI_FONT_T font_key = MMI_DEFAULT_NORMAL_FONT;
    GUI_COLOR_T const *bg_color_ptr = PNULL;
    MMI_STRING_T string = {0};
    GUISTR_STYLE_T style = {0};

    //SCI_ASSERT(PNULL != lcd_info_ptr); /*assert verified*/
    //SCI_ASSERT(PNULL != key_ptr); /*assert verified*/
    if(PNULL == lcd_info_ptr || PNULL == key_ptr)
    {
        return  FALSE;
    }

    switch (key_ptr->state)
    {
    case MMISMS_EMOJI_TP_KEY_STATE_INACTIVE:
        bg_color_ptr = bg_color_inactive;
        break;

    case MMISMS_EMOJI_TP_KEY_STATE_ACTIVE:
        bg_color_ptr = bg_color_active;
        break;

    case MMISMS_EMOJI_TP_KEY_STATE_PRESS:
        bg_color_ptr = bg_color_press;
        break;

    default:
        break;
    }

    if (PNULL == bg_color_ptr)
    {
        return FALSE;
    }

    //draw key
    // 1 draw bg
//     rect_draw = key_ptr->rect;
//     rect_draw.bottom += rect_draw.top;
//     rect_draw.bottom /= 2;
//     DrawRectGradient(lcd_info_ptr, &rect_draw, bg_color_ptr[0], bg_color_ptr[1]);
// 
//     rect_draw.top = rect_draw.bottom + 1;
//     rect_draw.bottom = key_ptr->rect.bottom;
//     DrawRectGradient(lcd_info_ptr, &rect_draw, bg_color_ptr[2], bg_color_ptr[3]);

    //draw string=
    string.wstr_ptr = key_ptr->str;
    string.wstr_len = key_ptr->str_len;

    style.align = ALIGN_HVMIDDLE;
    style.font = font_key;
    style.font_color = color_font;

    GUISTR_DrawTextToLCDInRect(lcd_info_ptr,
        &key_ptr->rect,
        &key_ptr->rect,
        &string,
        &style,
        GUISTR_STATE_SINGLE_LINE,
        GUISTR_TEXT_DIR_AUTO);

    return TRUE;
}

/*****************************************************************************/
//     Description : draw phiz data
//    Global resource dependence :
//  Author:
//    Note:
/*****************************************************************************/
LOCAL void DrawEmojiWin(MMISMS_EMOJI_WIN_DATA_T *win_data_ptr)
{   
    GUISTR_STYLE_T tip_style = {0};
    MMI_STRING_T prompt_str = {0};
    MMI_STRING_T tip_info = {0};
    char tip_str[8] = {0};
    wchar tip_wstr[8] = {0}; //tip string, limit is (99/99)
    uint16 unit_width = 0;
    uint16 unit_height = 0;
    uint16 rect_width = 0;
    uint16 rect_height = 0;

    GUI_RECT_T hot_rect = {0};
    int16 hot_row = 0;
    int16 hot_col = 0;
    uint32 symb_first = 0;
    uint32 symb_per_page = 0;
    uint32 symb_idx = 0;
    uint16 symb_row = 0;
    uint16 symb_col = 0;
    uint8 i = 0;
    GUI_RECT_T rect_symb = {0};
    MMI_STRING_T symb_info = {0};
    GUISTR_STYLE_T symb_style = {0};
    uint16 index = 0;

    if (PNULL == win_data_ptr)
    {
        return;
    }

    //draw...
    //draw panel
    LCD_FillRect(&(win_data_ptr->lcd_dev_info),
                 win_data_ptr->win_rect,
                 win_data_ptr->color_bg);

    MMISMS_EMOJI_ComKeyDraw(&win_data_ptr->lcd_dev_info, &win_data_ptr->key_pageup);
    MMISMS_EMOJI_ComKeyDraw(&win_data_ptr->lcd_dev_info, &win_data_ptr->key_pagedown);

    //draw title
    MMI_GetLabelTextByLang(TXT_SMS_EMOJI, &prompt_str);
    tip_style.font = win_data_ptr->font_min;
    tip_style.font_color = win_data_ptr->color_font;
    tip_style.align = ALIGN_LVMIDDLE;
    GUISTR_DrawTextToLCDInRect(&win_data_ptr->lcd_dev_info,
                               &win_data_ptr->title_rect,
                               &win_data_ptr->title_rect,
                               &prompt_str,
                               &tip_style,
                               GUISTR_STATE_NONE,
                               GUISTR_TEXT_DIR_AUTO);

    //draw page tip
    tip_style.align = ALIGN_RVMIDDLE;
    sprintf(tip_str, "(%d/%d)",
        win_data_ptr->first_row / win_data_ptr->row + 1,
        win_data_ptr->row_cnt / win_data_ptr->row + ((win_data_ptr->row_cnt % win_data_ptr->row) ? 1 : 0));
    for (i=0; i<8; i++) tip_wstr[i] = tip_str[i];
    tip_info.wstr_ptr = tip_wstr;
    tip_info.wstr_len = MMIAPICOM_Wstrlen(tip_wstr);
    GUISTR_DrawTextToLCDInRect(&win_data_ptr->lcd_dev_info,
        &win_data_ptr->title_rect,
        &win_data_ptr->title_rect,
        &tip_info,
        &tip_style,
        GUISTR_STATE_NONE,
        GUISTR_TEXT_DIR_AUTO);

    //cal row and column
    win_data_ptr->rect_emoji.bottom = win_data_ptr->rect_emoji.top + MMISMS_EMOJI_HEIGHT * MMISMS_EMOJI_ROW ; //240;
    rect_width = win_data_ptr->rect_emoji.right - win_data_ptr->rect_emoji.left + 1;
    rect_height = win_data_ptr->rect_emoji.bottom - win_data_ptr->rect_emoji.top + 1;
    unit_width = rect_width / win_data_ptr->col;//每个单元格宽度60
    unit_height = rect_height / win_data_ptr->row;

    //hot
    GetHotPos(win_data_ptr, &hot_row, &hot_col);

    //SCI_ASSERT(hot_row >= 0); /*assert verified*/
    if(hot_row < 0)
    {
        return;
    }
    
    hot_rect.top = win_data_ptr->rect_emoji.top + unit_height * hot_row;
    hot_rect.left = win_data_ptr->rect_emoji.left + unit_width * hot_col;
    hot_rect.bottom = (hot_row == win_data_ptr->row - 1) ?
                      win_data_ptr->rect_emoji.bottom : (hot_rect.top + unit_height);
    hot_rect.right = (hot_col == win_data_ptr->col - 1) ?
                     win_data_ptr->rect_emoji.right : (hot_rect.left + unit_width);
    hot_rect.top++;
    hot_rect.left++;
    hot_rect.bottom--;
    hot_rect.right--;

    LCD_FillRect(&(win_data_ptr->lcd_dev_info),
                 hot_rect,
                 win_data_ptr->color_hot);

    //draw symbol
    symb_first = win_data_ptr->first_row * win_data_ptr->col;

    symb_per_page = win_data_ptr->row * win_data_ptr->col;
    symb_style.font = win_data_ptr->font;
    symb_style.font_color = win_data_ptr->color_font;
    symb_style.align = ALIGN_HVMIDDLE;
    //画表情
    
    for (symb_idx = 0; symb_idx < symb_per_page; symb_idx++)
    {
        wchar symbol_wstr[3] = {0};

        //没有符号了，则不画了
        if (symb_first + symb_idx >= win_data_ptr->emoji_cnt)
            break;

        symb_row = symb_idx / win_data_ptr->col;
        symb_col = symb_idx % win_data_ptr->col;
        GetEmojiRect(win_data_ptr, symb_row, symb_col, &rect_symb);

        index = symb_first + symb_idx;
        symb_info.wstr_ptr = symbol_wstr;
        MMIAPICOM_Wstrncpy(symb_info.wstr_ptr, &s_emoji_image_text_convert_table[index].data, 1);
//        MMIAPICOM_Wstrcat(symb_info.wstr_ptr, space);
        symb_info.wstr_len = 1;
        symb_style.font = win_data_ptr->font;
        
        //string
        GUISTR_DrawTextToLCDInRect(&win_data_ptr->lcd_dev_info,
            (const GUI_RECT_T *)&rect_symb,
            (const GUI_RECT_T *)&rect_symb,
            &symb_info,
            &symb_style,
            GUISTR_STATE_NONE,
            GUISTR_TEXT_DIR_AUTO);
    }

   

}
/*****************************************************************************/
//     Description : init phiz data
//    Global resource dependence :
//  Author:
//    Note:
/*****************************************************************************/
LOCAL void  InitEmojiData(MMISMS_EMOJI_WIN_DATA_T *win_data_ptr)
{
    GUI_LCD_DEV_INFO lcd_dev_info = {GUI_MAIN_LCD_ID, GUI_BLOCK_MAIN};
    GUI_RECT_T key_rect = {0};

    //SCI_ASSERT(PNULL != win_data_ptr); /*assert verified*/
    if(PNULL == win_data_ptr)
    {
        return;
    }
    
    win_data_ptr->lcd_dev_info = lcd_dev_info;

    //该窗口无status bar
    win_data_ptr->win_rect = MMITHEME_GetClientRectEx(win_data_ptr->win_id);
    //win_data_ptr->win_rect.top = 0;

    //该窗口有title
    win_data_ptr->title_rect = win_data_ptr->win_rect;
    win_data_ptr->title_rect.bottom = MMITHEME_GetStatusBarHeight() + MMISMS_EMOJI_MARGIN_V;
    
    win_data_ptr->rect_emoji= win_data_ptr->win_rect;
    win_data_ptr->rect_emoji.top = win_data_ptr->title_rect.bottom + MMISMS_EMOJI_TOP_MARGIN;
    win_data_ptr->rect_emoji.bottom = win_data_ptr->rect_emoji.top + MMISMS_EMOJI_HEIGHT * MMISMS_EMOJI_ROW;//240;

    win_data_ptr->row = MMISMS_EMOJI_ROW;
    win_data_ptr->col = MMISMS_EMOJI_COL;

    win_data_ptr->color_bg = GUI_RGB2RGB565(0,0,0);/*lint !e572*/
    win_data_ptr->color_border = GUI_RGB2RGB565(0,0,0);/*lint !e572*/
    win_data_ptr->color_font = GUI_RGB2RGB565(255,255,255);/*lint !e572*/
    win_data_ptr->color_hot = GUI_RGB2RGB565(0xff,0x8c,0x00);

    win_data_ptr->font = MMISMS_EMOJI_FONT;
    win_data_ptr->emoji_cnt = MMISMS_GetEmojiItemNum();
    win_data_ptr->font_min = MMI_DEFAULT_NORMAL_FONT;
    //win_data_ptr->font_label = MMIIM_SP_SYMB_FONT_LABEL;

    win_data_ptr->row_cnt = win_data_ptr->emoji_cnt / win_data_ptr->col;

    if ((win_data_ptr->emoji_cnt % win_data_ptr->col) > 0)
    {
        win_data_ptr->row_cnt += 1;
    }
    win_data_ptr->page = win_data_ptr->emoji_cnt/MMISMS_EMOJI_NUM;// 总共的页数
    win_data_ptr->page += (win_data_ptr->emoji_cnt%MMISMS_EMOJI_NUM==0)?0 :1;

    //空出地方来放按钮
//     win_data_ptr->rect_emoji.top += 7;//MMIIM_SP_SYMB_MARGIN_V;
//     win_data_ptr->rect_emoji.top += 16;//MMIIM_SP_SYMB_KEY_HEIGHT;

    key_rect.top = win_data_ptr->rect_emoji.bottom + MMISMS_EMOJI_MARGIN_V;
    key_rect.bottom = key_rect.top + 20;
    key_rect.left = win_data_ptr->rect_emoji.left;
    key_rect.right = win_data_ptr->rect_emoji.right;

    //page up
    win_data_ptr->key_pageup.rect = key_rect;
    win_data_ptr->key_pageup.rect.right = win_data_ptr->key_pageup.rect.left + 80 - 1;
    win_data_ptr->key_pageup.str[0] = '<';
    win_data_ptr->key_pageup.str[1] = '<';
//    win_data_ptr->key_pageup.str[2] = '[';
//    win_data_ptr->key_pageup.str[3] = '*';
//    win_data_ptr->key_pageup.str[4] = ']';
    win_data_ptr->key_pageup.str_len = 2;
    //page down
    win_data_ptr->key_pagedown.rect = key_rect;
    win_data_ptr->key_pagedown.rect.left = win_data_ptr->key_pagedown.rect.right - 80 + 1;
//    win_data_ptr->key_pagedown.str[0] = '[';
//    win_data_ptr->key_pagedown.str[1] = '#';
//    win_data_ptr->key_pagedown.str[2] = ']';
    win_data_ptr->key_pagedown.str[0] = '>';
    win_data_ptr->key_pagedown.str[1] = '>';
    win_data_ptr->key_pagedown.str_len = 2;

    ResetPageFlag(win_data_ptr);

    //close
    win_data_ptr->rect_page_tip = key_rect;

    return;
}


/*****************************************************************************/
//     Description : to handle the message of window which choice the phiz
//    Global resource dependence :
//  Author: Tracy Zhang
//    Note:
/*****************************************************************************/
LOCAL MMI_RESULT_E HandleEmojiListWinMsg(
    MMI_WIN_ID_T        win_id,        //IN:
    MMI_MESSAGE_ID_E    msg_id,        //IN:
    DPARAM                param        //IN:
)
{
    MMI_RESULT_E res = MMI_RESULT_TRUE;

    int16 hot_row = 0;
    int16 hot_col = 0;
    uint16 cur_index = 0;
    MMI_STRING_T commit_str = {0};
//    MMI_HANDLE_T    ctrl_handle= (MMI_HANDLE_T)MMK_GetWinAddDataPtr(win_id);

    switch (msg_id)
    {
        case MSG_OPEN_WINDOW:
        win_data_ptr->win_id = win_id;
        InitEmojiData(win_data_ptr);
        break;

        case MSG_CLOSE_WINDOW:
            if(PNULL !=win_data_ptr)
            {
                SCI_FREE(win_data_ptr);
            }              
            break;

        case MSG_FULL_PAINT:
            //draw
            DrawEmojiWin(win_data_ptr);
            break;

        case MSG_CTL_MIDSK:
        case MSG_APP_WEB:
             {
                 MMISMS_DEST_ADDR_INFO_T *contactInfo = PNULL;
                 uint16 sim_num = 0;
                 uint16 sim_ok = 0;

                 sim_num = MMIAPIPHONE_GetSimCardOkNum(&sim_ok, 1);
                 if (0 == sim_num)
                 {
                     MMIAPIPHONE_AlertSimNorOKStatus();
                     break;
                 }
                 else
                 {
                     cur_index = win_data_ptr->hot_idx;
                     commit_str.wstr_ptr = MMISMS_GetEmojiStrPtr(cur_index);
                     commit_str.wstr_len = 1;

                     //save current select preset word
                     MMISMS_SetPresetForSend(commit_str.wstr_ptr , commit_str.wstr_len);

                     //send sms
                     contactInfo = MMISMS_GetNumberForSend();
                     MMISMSAPP_SendSmsWithData(MN_DUAL_SYS_1,
                         FALSE,
                         contactInfo,//sms->addr
                         commit_str.wstr_ptr,//freq->data
                         commit_str.wstr_len,
                         PNULL
                         );
                 }

                 MMK_CloseWin(MMISMS_EDITOPTION_WIN_ID);
                 MMK_CloseWin(win_id);
             }
            break;

        case MSG_APP_LEFT:

            if (win_data_ptr->hot_idx > 0)
            {
                win_data_ptr->hot_idx--;

                GetHotPos(win_data_ptr, &hot_row, &hot_col);
                //SCI_ASSERT(hot_row <= win_data_ptr->row); /*assert verified*/
                if(hot_row > win_data_ptr->row)
                {
                    break;
                }

                if(hot_row < 0)
                {
                    PageUp(win_data_ptr, MMISMS_EMOJI_HOT_END);
                }
            }
            else
            {
                win_data_ptr->hot_idx = win_data_ptr->emoji_cnt -1;
                GetHotPos(win_data_ptr, &hot_row, &hot_col);
                PageUp(win_data_ptr, MMISMS_EMOJI_HOT_HOLD);
            }
            DrawEmojiWin(win_data_ptr);
            break;

        case MSG_APP_RIGHT:

            if (win_data_ptr->hot_idx < win_data_ptr->emoji_cnt - 1)
            {
                win_data_ptr->hot_idx++;

                GetHotPos(win_data_ptr, &hot_row, &hot_col);
                //SCI_ASSERT(hot_row <= win_data_ptr->row); /*assert verified*/
                if(hot_row > win_data_ptr->row)
                {
                    break;
                }

                if (hot_row == win_data_ptr->row)
                {
                    PageDown(win_data_ptr, MMISMS_EMOJI_HOT_BEGIN);
                }
            }
            else
            {
                win_data_ptr->hot_idx = 0;
                GetHotPos(win_data_ptr, &hot_row, &hot_col);
                PageDown(win_data_ptr, MMISMS_EMOJI_HOT_HOLD);
            }
            DrawEmojiWin(win_data_ptr);
            break;

        case MSG_APP_UP:

            if (win_data_ptr->hot_idx >= win_data_ptr->col)
            {
                win_data_ptr->hot_idx -= win_data_ptr->col;

                GetHotPos(win_data_ptr, &hot_row, &hot_col);
                //SCI_ASSERT(hot_row <= win_data_ptr->row); /*assert verified*/
                if(hot_row > win_data_ptr->row)
                {
                    break;
                }
                if (hot_row < 0)
                {
                    PageUp(win_data_ptr, MMISMS_EMOJI_HOT_HOLD_COL);
                }
            }
            else
            {
                win_data_ptr->hot_idx += win_data_ptr->emoji_cnt - win_data_ptr->col;
                GetHotPos(win_data_ptr, &hot_row, &hot_col);
                PageUp(win_data_ptr, MMISMS_EMOJI_HOT_HOLD_COL);
            }

            DrawEmojiWin(win_data_ptr);
            break;

        case MSG_APP_DOWN:

            if (win_data_ptr->hot_idx < win_data_ptr->emoji_cnt - win_data_ptr->col)
            {
                win_data_ptr->hot_idx += win_data_ptr->col;
                GetHotPos(win_data_ptr, &hot_row, &hot_col);
                //SCI_ASSERT(hot_row <= win_data_ptr->row); /*assert verified*/
                if(hot_row > win_data_ptr->row)
                {
                    break;
                }

                if (hot_row == win_data_ptr->row)
                {
                    PageDown(win_data_ptr, MMISMS_EMOJI_HOT_HOLD_COL);
                }
            }
            else
            {
                win_data_ptr->hot_idx += win_data_ptr->col - win_data_ptr->emoji_cnt;
                GetHotPos(win_data_ptr, &hot_row, &hot_col);
                PageDown(win_data_ptr, MMISMS_EMOJI_HOT_HOLD_COL);
            }
            DrawEmojiWin(win_data_ptr);
            break;

#ifdef TOUCH_PANEL_SUPPORT //IGNORE9527
        case MSG_TP_PRESS_DOWN:
            //choose hot
            res = HandleEmojiWinTpDown(win_data_ptr, param);
            break;
#endif //TOUCH_PANEL_SUPPORT //IGNORE9527

#ifdef TOUCH_PANEL_SUPPORT //IGNORE9527
        case MSG_TP_PRESS_MOVE:
            res = HandleEmojiWinTpMove(win_data_ptr, param);
            //choose hot
            break;
#endif //TOUCH_PANEL_SUPPORT //IGNORE9527

#ifdef TOUCH_PANEL_SUPPORT //IGNORE9527
        case MSG_TP_PRESS_UP:
            //confirm
            res = HandleEmojiWinTpUp(win_data_ptr, param);
            break;
#endif
        
        case MSG_APP_STAR:

            if (PageUp(win_data_ptr, MMISMS_EMOJI_HOT_HOLD))
            {
                DrawEmojiWin(win_data_ptr);
            }
            break;

        case MSG_APP_HASH:

            if (PageDown(win_data_ptr, MMISMS_EMOJI_HOT_HOLD))
            {
                DrawEmojiWin(win_data_ptr);
            }

            break;

        case MSG_LCD_SWITCH:
            InitEmojiData(win_data_ptr);
            break;
        case MSG_CTL_CANCEL:
        case MSG_APP_CANCEL:
            MMK_CloseWin(win_id);
            break;

        default:
            res = MMI_RESULT_FALSE;
            break;
    }
    
    return res;
}

/*****************************************************************************/
//     Description : MMISMS_GetEmojiItemNum
//    Global resource dependence :
//  Author:
//    Note:
/*****************************************************************************/
PUBLIC uint16 MMISMS_GetEmojiItemNum(void)
{
    uint16 num = 0;

    num = sizeof(s_emoji_image_text_convert_table) / sizeof(MMISMS_EMOJI_INFO_T);
    return num;
}

/*****************************************************************************/
//     Description : ResetPageFlag
//    Global resource dependence :
//  Author:
//    Note:
/*****************************************************************************/
LOCAL void ResetPageFlag(MMISMS_EMOJI_WIN_DATA_T *win_data_ptr)
{
    //SCI_ASSERT(PNULL != win_data_ptr); /*assert verified*/
    if(PNULL == win_data_ptr)
    {
        return;
    }

    //set page up-down state
    win_data_ptr->key_pagedown.state = (win_data_ptr->first_row + win_data_ptr->row < win_data_ptr->row_cnt) ?
MMISMS_EMOJI_TP_KEY_STATE_ACTIVE : MMISMS_EMOJI_TP_KEY_STATE_INACTIVE;

    win_data_ptr->key_pageup.state = (win_data_ptr->first_row > 0) ?
MMISMS_EMOJI_TP_KEY_STATE_ACTIVE : MMISMS_EMOJI_TP_KEY_STATE_INACTIVE;

    return;
}

/*****************************************************************************/
//     Description : PageDown
//    Global resource dependence :
//  Author:
//    Note:
/*****************************************************************************/
LOCAL BOOLEAN PageDown(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    MMISMS_EMOJI_HOT_TYPE_T hot_type
    )
{
    uint16 page_cnt = 0;
    uint16 cur_page = 0;

    //SCI_ASSERT(PNULL != win_data_ptr); /*assert verified*/
    if(PNULL == win_data_ptr)
    {
        return  FALSE;
    }
    
    page_cnt = win_data_ptr->row_cnt / win_data_ptr->row;
    page_cnt += ((win_data_ptr->row_cnt % win_data_ptr->row) ? 1 : 0);

    //0 or 1 page
    if (page_cnt <= 1)
    {
        return FALSE;
    }

    cur_page = win_data_ptr->first_row / win_data_ptr->row;

    if (cur_page + 1 == page_cnt)
    {
        win_data_ptr->first_row = 0;
        cur_page = 0;
        hot_type = MMISMS_EMOJI_HOT_BEGIN;
    }
    else
    {
        win_data_ptr->first_row += win_data_ptr->row;
    }

    switch (hot_type)
    {
    case MMISMS_EMOJI_HOT_BEGIN:
        //set default as end
        win_data_ptr->hot_idx = win_data_ptr->first_row * win_data_ptr->col;
        break;

    case MMISMS_EMOJI_HOT_HOLD:
        win_data_ptr->hot_idx += win_data_ptr->row * win_data_ptr->col;
        break;

    case MMISMS_EMOJI_HOT_HOLD_COL:
        win_data_ptr->hot_idx %= win_data_ptr->col;
        win_data_ptr->hot_idx += win_data_ptr->first_row * win_data_ptr->col;
        break;

    case MMISMS_EMOJI_HOT_END:
    default:
        //set default as end
        win_data_ptr->hot_idx = (win_data_ptr->first_row + win_data_ptr->row) * win_data_ptr->col;
        win_data_ptr->hot_idx -= 1;
        break;
    }

    if (win_data_ptr->hot_idx >= win_data_ptr->emoji_cnt)
    {
        win_data_ptr->hot_idx = win_data_ptr->emoji_cnt - 1;
    }

    ResetPageFlag(win_data_ptr);

    return TRUE;
}

/*****************************************************************************/
//     Description : PageUp
//    Global resource dependence :
//  Author:
//    Note:
/*****************************************************************************/
LOCAL BOOLEAN PageUp(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    MMISMS_EMOJI_HOT_TYPE_T hot_type
    )
{
    uint16 page_cnt = 0;
    uint16 cur_page = 0;
    uint8 count = 0;

    //SCI_ASSERT(PNULL != win_data_ptr); /*assert verified*/
    if(PNULL == win_data_ptr)
    {
        return  FALSE;
    }

    page_cnt = win_data_ptr->row_cnt / win_data_ptr->row;
    page_cnt += ((win_data_ptr->row_cnt % win_data_ptr->row) ? 1 : 0);

    //0 or 1 page
    if (page_cnt <= 1)
    {
        return FALSE;
    }

    cur_page = win_data_ptr->first_row / win_data_ptr->row;

    if (0 == cur_page)
    {
        cur_page = page_cnt;
        count = (win_data_ptr->row_cnt % win_data_ptr->row) ? 1 : 0;
        win_data_ptr->first_row = (page_cnt - 1) * win_data_ptr->row;
//        hot_type = MMISMS_EMOJI_HOT_HOLD_COL;
    }
    else
    {
        win_data_ptr->first_row -= win_data_ptr->row;
    }

    switch (hot_type)
    {
    case MMISMS_EMOJI_HOT_BEGIN:
        //set default as end
        win_data_ptr->hot_idx = win_data_ptr->first_row * win_data_ptr->col;
        break;

    case MMISMS_EMOJI_HOT_HOLD:
        win_data_ptr->hot_idx -= win_data_ptr->row * win_data_ptr->col;
        break;

    case MMISMS_EMOJI_HOT_HOLD_COL:
        win_data_ptr->hot_idx %= win_data_ptr->col;
        win_data_ptr->hot_idx += (win_data_ptr->first_row + win_data_ptr->row - 1) * win_data_ptr->col;
        break;


    case MMISMS_EMOJI_HOT_END:
    default:
        //set default as end
        win_data_ptr->hot_idx = (win_data_ptr->first_row + win_data_ptr->row) * win_data_ptr->col;
        win_data_ptr->hot_idx -= 1;
        break;
    }

    if (win_data_ptr->hot_idx >= win_data_ptr->emoji_cnt)
    {
        win_data_ptr->hot_idx = win_data_ptr->emoji_cnt - 1;
    }

    ResetPageFlag(win_data_ptr);


    return TRUE;
}

/*****************************************************************************/
//     Description : MMISMS_IsContainEmoji
//    Global resource dependence :
//  Author:
//    Note:
/*****************************************************************************/
PUBLIC BOOLEAN MMISMS_IsContainEmoji(
    uint16 *unicode,
    uint32 unicode_length,
    MMISMS_EMOJI_DISPLAY_CONTENT_T * content_ptr
    )
{
    BOOLEAN is_contain = FALSE;
    uint32 i = 0;
    uint16 j = 0;
    UTF16 utf16_high_surrogate = 0;
    unsigned uc = 0;
    uint8 length = 0;
    uint16 total_length = 0;

    if (unicode == NULL)
    {
        SCI_TRACE_LOW("[MMISMS] MMISMS_IsContainEmoji unicode == NULL!");
        return FALSE;
    }

    if(content_ptr == PNULL)
    {
        SCI_TRACE_LOW("[MMISMS] MMISMS_IsContainEmoji content_ptr == PNULL!");
        return FALSE;
    }

    SCI_TRACE_LOW("[MMISMS] MMISMS_IsContainEmoji unicode_length = %d", unicode_length);

    total_length = MMISMS_GetEmojiItemNum();

    for( i = 0; i < unicode_length; i++)
    {
        uint16 ch = unicode[i];
        SCI_TRACE_LOW("[MMISMS] MMISMS_IsContainEmoji ch = 0x%x", ch);

        if (utf16_high_surrogate)
        {
            if (UNICODE_IS_LOW_SURROGATE(ch))
            {
                uc = DECODE_SURROGATE_PAIR(utf16_high_surrogate, ch);
                SCI_TRACE_LOW("[MMISMS] MMISMS_IsContainEmoji uc = 0x%x", uc);

                content_ptr->item[length].code = uc;

                for(j = 0; j < total_length; j++)
                {
                    if(uc == s_emoji_image_text_convert_table[j].code)
                    {
                        is_contain = TRUE;
                        content_ptr->item[length].data = s_emoji_image_text_convert_table[j].data;
                        content_ptr->item[length].image_id = s_emoji_image_text_convert_table[j].image_id;
                        content_ptr->item[length].text_id = s_emoji_image_text_convert_table[j].text_id;
                        break;
                    }
                }

                length++;
                utf16_high_surrogate = 0;
            }
            else
            {
                /* high surrogate without a following low surrogate */
                content_ptr->item[length].code = ch;
                length++;
            }
        }
        else
        {
            if (UNICODE_IS_HIGH_SURROGATE(ch))
            {
                /* save the high surrogate and wait for the low surrogate */
                utf16_high_surrogate = (UTF16)ch;
            }
            else
            {
                if (ch != 0x00 && ch < 0x80)
                {
                    content_ptr->item[length].code = ch;
                    length++;
                }
                else if (ch != 0x00 && ch < 0x800)
                {
                    content_ptr->item[length].code = ch;
                    length++;
                }
                else if (ch >= 0xE000 && ch <= 0XE2EF)
                {
                    content_ptr->item[length].code = ch;
                    length++;
                }
                else if (UNICODE_IS_LOW_SURROGATE(ch))
                {
                    /* low surrogate without a preceding high surrogate */
                }
            }
        }
    }
    content_ptr->length = length;

    SCI_TRACE_LOW("[MMISMS] MMISMS_IsContainEmoji is_contain = %d", is_contain);
    return is_contain;
}

#if (defined (TOUCH_PANEL_SUPPORT))
/*==============================================================================
Function Name: HandleEmojiWinTpDown
Description: HandleEmojiWinTpDown
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN HandleEmojiWinTpDown(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    DPARAM param
    )
{
    int32 tp_pos = 0;
    BOOLEAN is_win_dirty = FALSE;

    //SCI_ASSERT(PNULL != win_data_ptr); /*assert verified*/
    //SCI_ASSERT(PNULL != param); /*assert verified*/
    if(PNULL == win_data_ptr ||PNULL == param )
    {
        return FALSE;
    }

    tp_pos = GetTpPos(win_data_ptr, param);

    if (0 <= tp_pos && tp_pos < (int32)win_data_ptr->emoji_cnt)
    {
        if (win_data_ptr->hot_idx != tp_pos)
        {
            win_data_ptr->hot_idx = tp_pos;
            is_win_dirty = TRUE;
        }
    }
    else if ((win_data_ptr->emoji_cnt + 1) == tp_pos) //page down
    {
        is_win_dirty = MMISMS_Emoji_ComKeyPress(&win_data_ptr->key_pagedown);
        win_data_ptr->last_key_ptr = &win_data_ptr->key_pagedown;
    }
    else if ((win_data_ptr->emoji_cnt + 2) == tp_pos) //page up
    {
        is_win_dirty = MMISMS_Emoji_ComKeyPress(&win_data_ptr->key_pageup);
        win_data_ptr->last_key_ptr = &win_data_ptr->key_pageup;
    }

    if (is_win_dirty)
    {
        DrawEmojiWin(win_data_ptr);
    }


    return TRUE;
}

/*==============================================================================
Function Name: HandleEmojiWinTpMove
Description: HandleEmojiWinTpMove
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN HandleEmojiWinTpMove(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    DPARAM param
    )
{
    int32 tp_pos = 0;
    MMISMS_EMOJI_COMMON_KEY_T *tp_key_ptr = PNULL;
    BOOLEAN is_win_dirty = FALSE;

    //SCI_ASSERT(PNULL != win_data_ptr); /*assert verified*/
    //SCI_ASSERT(PNULL != param); /*assert verified*/
    if(PNULL == win_data_ptr ||PNULL == param )
    {
        return FALSE;
    }

    tp_pos = GetTpPos(win_data_ptr, param);

    if (0 <= tp_pos && tp_pos < (int32)win_data_ptr->emoji_cnt)
    {
        if (win_data_ptr->hot_idx != tp_pos)
        {
            win_data_ptr->hot_idx = tp_pos;
            is_win_dirty = TRUE;
        }
    }
    else if ((win_data_ptr->emoji_cnt + 1) == tp_pos) //page down
    {
        is_win_dirty = MMISMS_Emoji_ComKeyPress(&win_data_ptr->key_pagedown);
        tp_key_ptr = &win_data_ptr->key_pagedown;
    }
    else if ((win_data_ptr->emoji_cnt + 2) == tp_pos) //page up
    {
        is_win_dirty = MMISMS_Emoji_ComKeyPress(&win_data_ptr->key_pageup);
        tp_key_ptr = &win_data_ptr->key_pageup;
    }

    if (win_data_ptr->last_key_ptr != tp_key_ptr && PNULL != win_data_ptr->last_key_ptr)
    {
        is_win_dirty = (is_win_dirty || MMISMS_Emoji_ComkeyRelease(win_data_ptr->last_key_ptr));
    }

    win_data_ptr->last_key_ptr = tp_key_ptr;

    if (is_win_dirty)
    {
        DrawEmojiWin(win_data_ptr);
    }

    return TRUE;
}

/*==============================================================================
Function Name: HandleEmojiWinTpUp
Description: HandleEmojiWinTpUp
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN HandleEmojiWinTpUp(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    DPARAM param
    )
{
    int32 tp_pos = 0;
    BOOLEAN is_win_closed = FALSE;
    BOOLEAN is_win_dirty = FALSE;
    MMI_STRING_T commit_str = {0};
    MMISMS_DEST_ADDR_INFO_T *contactInfo = PNULL;
    uint16 sim_num = 0;
    uint16 sim_ok = 0;

    //SCI_ASSERT(PNULL != win_data_ptr); /*assert verified*/
    //SCI_ASSERT(PNULL != param); /*assert verified*/
    if(PNULL == win_data_ptr ||PNULL == param )
    {
        return FALSE;
    }

    tp_pos = GetTpPos(win_data_ptr, param);

    if (0 <= tp_pos && tp_pos < (int32)win_data_ptr->emoji_cnt)
    {
        sim_num = MMIAPIPHONE_GetSimCardOkNum(&sim_ok, 1);
        if (0 == sim_num)
        {
            MMIAPIPHONE_AlertSimNorOKStatus();
            return FALSE;
        }

        commit_str.wstr_ptr = MMISMS_GetEmojiStrPtr(tp_pos);
        commit_str.wstr_len = 1;

        //save current select preset word
        MMISMS_SetPresetForSend(commit_str.wstr_ptr , commit_str.wstr_len);

        //send sms
        contactInfo = MMISMS_GetNumberForSend();
        MMISMSAPP_SendSmsWithData(MN_DUAL_SYS_1,
            FALSE,
            contactInfo,//sms->addr
            commit_str.wstr_ptr,//freq->data
            commit_str.wstr_len,
            PNULL
            );

        MMK_CloseWin(win_data_ptr->win_id);
        is_win_closed = TRUE;
    }
    else if ((win_data_ptr->emoji_cnt + 1) == tp_pos) //page down
    {
        if (PageDown(win_data_ptr, MMISMS_EMOJI_HOT_HOLD))
        {
            is_win_dirty = TRUE;
        }
    }
    else if ((win_data_ptr->emoji_cnt + 2) == tp_pos) // page up
    {
        if (PageUp(win_data_ptr, MMISMS_EMOJI_HOT_HOLD))
        {
            is_win_dirty = TRUE;
        }
    }

    if (!is_win_closed && PNULL != win_data_ptr->last_key_ptr)
    {
        is_win_dirty = (is_win_dirty || MMISMS_Emoji_ComkeyRelease(win_data_ptr->last_key_ptr));
        win_data_ptr->last_key_ptr = PNULL;
    }


    if (is_win_dirty)
    {
        DrawEmojiWin(win_data_ptr);
    }

    return TRUE;
}

/*==============================================================================
Function Name: GetTpPos
Description: GetTpPos
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL int32 GetTpPos(
    MMISMS_EMOJI_WIN_DATA_T *win_data_ptr,
    DPARAM param
    )
{
    GUI_POINT_T tp_point = {0};
    int32 pos = -1;

    //SCI_ASSERT(PNULL != win_data_ptr); /*assert verified*/
    //SCI_ASSERT(PNULL != param); /*assert verified*/
    if(PNULL == win_data_ptr ||PNULL == param )
    {
        return pos;
    }

    tp_point.x = MMK_GET_TP_X(param);
    tp_point.y = MMK_GET_TP_Y(param);

    //按几率大小排列
    if (GUI_PointIsInRect(tp_point, win_data_ptr->rect_emoji))
    {
        int16 rect_width = win_data_ptr->rect_emoji.right - win_data_ptr->rect_emoji.left + 1;
        int16 rect_height = win_data_ptr->rect_emoji.bottom - win_data_ptr->rect_emoji.top + 1;
        int16 dx = tp_point.x -  win_data_ptr->rect_emoji.left;
        int16 dy = tp_point.y - win_data_ptr->rect_emoji.top;
        int16 col = dx * win_data_ptr->col / rect_width;
        int16 row = dy * win_data_ptr->row / rect_height;

        //SCI_ASSERT(row < win_data_ptr->row); /*assert verified*/
        if(row >= win_data_ptr->row)
        {
            return -1;
        }

        pos = 0;
        pos += row * win_data_ptr->col;
        pos += col;

        //统一处理页面偏移
        pos += win_data_ptr->first_row * win_data_ptr->col;
    }
    else if (GUI_PointIsInRect(tp_point, win_data_ptr->key_pagedown.rect))
    {
        pos = win_data_ptr->emoji_cnt + 1;//page down
    }
    else if (GUI_PointIsInRect(tp_point, win_data_ptr->key_pageup.rect))
    {
        pos = win_data_ptr->emoji_cnt + 2;//page up
    }

    return pos;
}

/*==============================================================================
Function Name: MMISMS_Emoji_ComKeyPress
Description: MMISMS_Emoji_ComKeyPress
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN MMISMS_Emoji_ComKeyPress(MMISMS_EMOJI_COMMON_KEY_T *key_ptr)
{
    BOOLEAN is_changed = FALSE;

    if(MMISMS_EMOJI_TP_KEY_STATE_ACTIVE == (key_ptr)->state)
    {
        key_ptr->state =MMISMS_EMOJI_TP_KEY_STATE_PRESS;
        is_changed = TRUE;
    }

    return is_changed;
}


/*==============================================================================
Function Name: MMISMS_Emoji_ComkeyRelease
Description: MMISMS_Emoji_ComkeyRelease
Author:
Global resource dependence: NONE
Note:
==============================================================================*/
LOCAL BOOLEAN MMISMS_Emoji_ComkeyRelease(MMISMS_EMOJI_COMMON_KEY_T *key_ptr)
{
    BOOLEAN is_changed = FALSE;

    if(MMISMS_EMOJI_TP_KEY_STATE_PRESS == (key_ptr)->state)
    {
        key_ptr->state = MMISMS_EMOJI_TP_KEY_STATE_ACTIVE;
        is_changed = TRUE;
    }

    return is_changed;

}
#endif
