/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define ATP_FLEX_MAJOR_VERSION 2
#define ATP_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define ATP_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define ATP_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define ATP_USE_PROTOS
#define ATP_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define ATP_USE_CONST
#define ATP_USE_PROTOS
#endif

#ifdef ATP_USE_CONST
#define atpconst const
#else
#define atpconst
#endif


#ifdef ATP_USE_PROTOS
#define ATP_PROTO(proto) proto
#else
#define ATP_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define ATP_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define ATP_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN atp_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The ATPSTATE alias is for lex
 * compatibility.
 */
#define ATP_START ((atp_start - 1) / 2)
#define ATPSTATE ATP_START

/* Action number for EOF rule of a given start state. */
#define ATP_STATE_EOF(state) (ATP_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define ATP_NEW_FILE atprestart( atpin )

#define ATP_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define ATP_BUF_SIZE 16384

typedef struct atp_buffer_state *ATP_BUFFER_STATE;

extern int atpleng;
extern FILE *atpin, *atpout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		atpless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the atpless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define atpless(n) \
	do \
		{ \
		/* Undo effects of setting up atptext. */ \
		*atp_cp = atp_hold_char; \
		ATP_RESTORE_ATP_MORE_OFFSET \
		atp_c_buf_p = atp_cp = atp_bp + n - ATP_MORE_ADJ; \
		ATP_DO_BEFORE_ACTION; /* set up atptext again */ \
		} \
	while ( 0 )

#define unput(c) atpunput( c, atptext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int atp_size_t;


struct atp_buffer_state
	{
	FILE *atp_input_file;

	char *atp_ch_buf;		/* input buffer */
	char *atp_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	atp_size_t atp_buf_size;

	/* Number of characters read into atp_ch_buf, not including EOB
	 * characters.
	 */
	int atp_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int atp_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int atp_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int atp_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int atp_fill_buffer;

	int atp_buffer_status;
#define ATP_BUFFER_NEW 0
#define ATP_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as ATP_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via atprestart()), so that the user can continue scanning by
	 * just pointing atpin at a new input file.
	 */
#define ATP_BUFFER_EOF_PENDING 2
	};

static ATP_BUFFER_STATE atp_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define ATP_CURRENT_BUFFER atp_current_buffer


/* atp_hold_char holds the character lost when atptext is formed. */
static char atp_hold_char;

static int atp_n_chars;		/* number of characters read into atp_ch_buf */


int atpleng;

/* Points to current character in buffer. */
static char *atp_c_buf_p = (char *) 0;
static int atp_init = 1;		/* whether we need to initialize */
static int atp_start = 0;	/* start state number */

/* Flag which is used to allow atpwrap()'s to do buffer switches
 * instead of setting up a fresh atpin.  A bit of a hack ...
 */
static int atp_did_buffer_switch_on_eof;

void atprestart ATP_PROTO(( FILE *input_file ));

void atp_switch_to_buffer ATP_PROTO(( ATP_BUFFER_STATE new_buffer ));
void atp_load_buffer_state ATP_PROTO(( void ));
ATP_BUFFER_STATE atp_create_buffer ATP_PROTO(( FILE *file, int size ));
void atp_delete_buffer ATP_PROTO(( ATP_BUFFER_STATE b ));
void atp_init_buffer ATP_PROTO(( ATP_BUFFER_STATE b, FILE *file ));
void atp_flush_buffer ATP_PROTO(( ATP_BUFFER_STATE b ));
#define ATP_FLUSH_BUFFER atp_flush_buffer( atp_current_buffer )

ATP_BUFFER_STATE atp_scan_buffer ATP_PROTO(( char *base, atp_size_t size ));
ATP_BUFFER_STATE atp_scan_string ATP_PROTO(( atpconst char *atp_str ));
ATP_BUFFER_STATE atp_scan_bytes ATP_PROTO(( atpconst char *bytes, int len ));

static void *atp_flex_alloc ATP_PROTO(( atp_size_t ));
static void *atp_flex_realloc ATP_PROTO(( void *, atp_size_t ));
static void atp_flex_free ATP_PROTO(( void * ));

#define atp_new_buffer atp_create_buffer

#define atp_set_interactive(is_interactive) \
	{ \
	if ( ! atp_current_buffer ) \
		atp_current_buffer = atp_create_buffer( atpin, ATP_BUF_SIZE ); \
	atp_current_buffer->atp_is_interactive = is_interactive; \
	}

#define atp_set_bol(at_bol) \
	{ \
	if ( ! atp_current_buffer ) \
		atp_current_buffer = atp_create_buffer( atpin, ATP_BUF_SIZE ); \
	atp_current_buffer->atp_at_bol = at_bol; \
	}

#define ATP_AT_BOL() (atp_current_buffer->atp_at_bol)


#define atpwrap() 1
#define ATP_SKIP_ATPWRAP
typedef unsigned char ATP_CHAR;
FILE *atpin = (FILE *) 0, *atpout = (FILE *) 0;
typedef int atp_state_type;
extern char *atptext;
#define atptext_ptr atptext

static atp_state_type atp_get_previous_state ATP_PROTO(( void ));
static atp_state_type atp_try_NUL_trans ATP_PROTO(( atp_state_type current_state ));
static int atp_get_next_buffer ATP_PROTO(( void ));
static void atp_fatal_error ATP_PROTO(( atpconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up atptext.
 */
#define ATP_DO_BEFORE_ACTION \
	atptext_ptr = atp_bp; \
	atpleng = (int) (atp_cp - atp_bp); \
	atp_hold_char = *atp_cp; \
	*atp_cp = '\0'; \
	atp_c_buf_p = atp_cp;

#define ATP_NUM_RULES 12
#define ATP_END_OF_BUFFER 13
static atpconst short int atp_accept[37] =
    {   0,
        0,    0,    0,    0,    0,    0,   13,    8,    7,    7,
        1,    1,    1,    8,    8,    8,    8,    5,    2,    8,
        8,    7,    8,    8,    7,    1,    1,    0,    4,    5,
        0,    9,    3,   10,    6,    0
    } ;

static atpconst int atp_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,    1,
        1,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,   24,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       25,   26,   27,   28,   29,   30,   31,   31,   31,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   32,   33,   34,   35,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static atpconst int atp_meta[36] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static atpconst short int atp_base[39] =
    {   0,
        0,    0,   34,   67,   41,   51,   77,  166,   38,   53,
       98,    0,   65,  130,   58,   59,   62,   54,  166,   46,
      166,   56,   48,   52,   58,    0,    0,    0,  166,   30,
       30,  166,  166,  166,  166,  166,   41,   37
    } ;

static atpconst short int atp_def[39] =
    {   0,
       36,    1,   37,   37,   38,   38,   36,   36,   36,   36,
       36,   11,   11,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   11,   11,   14,   36,   36,
       36,   36,   36,   36,   36,    0,   36,   36
    } ;

static atpconst short int atp_nxt[202] =
    {   0,
        8,    9,   10,   11,    8,   12,   12,   12,   11,   11,
       12,   12,   11,   11,   11,   13,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   12,   11,
       11,    8,   11,    8,   11,    9,   10,   21,   14,   25,
       25,    8,   22,   10,   35,   15,   30,   15,   16,   17,
       18,   23,   22,   10,   25,   25,   24,   25,   25,   25,
       25,   23,   32,   34,   33,   19,   24,   20,    9,   10,
       30,   14,   32,   31,   30,   27,   36,   36,   15,   36,
       15,   16,   17,   18,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   19,   36,

       20,   26,   36,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   36,
       26,   36,   26,   28,   29,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   36,   28,   36,   28,    7,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36
    } ;

static atpconst short int atp_chk[202] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,   38,    3,    9,
        9,   37,    5,    5,   31,    3,   30,    3,    3,    3,
        3,    5,    6,    6,   10,   10,    5,   22,   22,   25,
       25,    6,   24,   23,   20,    3,    6,    3,    4,    4,
       18,    4,   17,   16,   15,   13,    7,    0,    4,    0,
        4,    4,    4,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    4,    0,

        4,   11,    0,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,    0,
       11,    0,   11,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,    0,   14,    0,   14,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36
    } ;

static atp_state_type atp_last_accepting_state;
static char *atp_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define atpmore() atpmore_used_but_not_detected
#define ATP_MORE_ADJ 0
#define ATP_RESTORE_ATP_MORE_OFFSET
char *atptext;
#define INITIAL 0
#include <stdio.h>
#include <stdlib.h>

#include "atpgen_yacc.h"
#include "atpgen.h"

int last_start;
#define ATC_DEF 1

#define ATC_COMMENT 2


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef ATP_SKIP_ATPWRAP
#ifdef __cplusplus
extern "C" int atpwrap ATP_PROTO(( void ));
#else
extern int atpwrap ATP_PROTO(( void ));
#endif
#endif

#ifndef ATP_NO_UNPUT
static void atpunput ATP_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef atptext_ptr
static void atp_flex_strncpy ATP_PROTO(( char *, atpconst char *, int ));
#endif

#ifdef ATP_NEED_STRLEN
static int atp_flex_strlen ATP_PROTO(( atpconst char * ));
#endif

#ifndef ATP_NO_INPUT
#ifdef __cplusplus
static int atpinput ATP_PROTO(( void ));
#else
static int input ATP_PROTO(( void ));
#endif
#endif

#if ATP_STACK_USED
static int atp_start_stack_ptr = 0;
static int atp_start_stack_depth = 0;
static int *atp_start_stack = 0;
#ifndef ATP_NO_PUSH_STATE
static void atp_push_state ATP_PROTO(( int new_state ));
#endif
#ifndef ATP_NO_POP_STATE
static void atp_pop_state ATP_PROTO(( void ));
#endif
#ifndef ATP_NO_TOP_STATE
static int atp_top_state ATP_PROTO(( void ));
#endif

#else
#define ATP_NO_PUSH_STATE 1
#define ATP_NO_POP_STATE 1
#define ATP_NO_TOP_STATE 1
#endif

#ifdef ATP_MALLOC_DECL
ATP_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef ATP_READ_BUF_SIZE
#define ATP_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( atptext, atpleng, 1, atpout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or ATP_NULL,
 * is returned in "result".
 */
#ifndef ATP_INPUT
#define ATP_INPUT(buf,result,max_size) \
	if ( atp_current_buffer->atp_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( atpin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( atpin ) ) \
			ATP_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, atpin )) == 0) \
		  && ferror( atpin ) ) \
		ATP_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "atpterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef atpterminate
#define atpterminate() return ATP_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef ATP_START_STACK_INCR
#define ATP_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef ATP_FATAL_ERROR
#define ATP_FATAL_ERROR(msg) atp_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef ATP_DECL
#define ATP_DECL int atplex ATP_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after atptext and atpleng
 * have been set up.
 */
#ifndef ATP_USER_ACTION
#define ATP_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef ATP_BREAK
#define ATP_BREAK break;
#endif

#define ATP_RULE_SETUP \
	ATP_USER_ACTION

ATP_DECL
	{
	register atp_state_type atp_current_state;
	register char *atp_cp, *atp_bp;
	register int atp_act;




	if ( atp_init )
		{
		atp_init = 0;

#ifdef ATP_USER_INIT
		ATP_USER_INIT;
#endif

		if ( ! atp_start )
			atp_start = 1;	/* first start state */

		if ( ! atpin )
			atpin = stdin;

		if ( ! atpout )
			atpout = stdout;

		if ( ! atp_current_buffer )
			atp_current_buffer =
				atp_create_buffer( atpin, ATP_BUF_SIZE );

		atp_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		atp_cp = atp_c_buf_p;

		/* Support of atptext. */
		*atp_cp = atp_hold_char;

		/* atp_bp points to the position in atp_ch_buf of the start of
		 * the current run.
		 */
		atp_bp = atp_cp;

		atp_current_state = atp_start;
atp_match:
		do
			{
			register ATP_CHAR atp_c = atp_ec[ATP_SC_TO_UI(*atp_cp)];
			if ( atp_accept[atp_current_state] )
				{
				atp_last_accepting_state = atp_current_state;
				atp_last_accepting_cpos = atp_cp;
				}
			while ( atp_chk[atp_base[atp_current_state] + atp_c] != atp_current_state )
				{
				atp_current_state = (int) atp_def[atp_current_state];
				if ( atp_current_state >= 37 )
					atp_c = atp_meta[(unsigned int) atp_c];
				}
			atp_current_state = atp_nxt[atp_base[atp_current_state] + (unsigned int) atp_c];
			++atp_cp;
			}
		while ( atp_base[atp_current_state] != 166 );

atp_find_action:
		atp_act = atp_accept[atp_current_state];
		if ( atp_act == 0 )
			{ /* have to back up */
			atp_cp = atp_last_accepting_cpos;
			atp_current_state = atp_last_accepting_state;
			atp_act = atp_accept[atp_current_state];
			}

		ATP_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( atp_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of ATP_DO_BEFORE_ACTION */
			*atp_cp = atp_hold_char;
			atp_cp = atp_last_accepting_cpos;
			atp_current_state = atp_last_accepting_state;
			goto atp_find_action;

case 1:
ATP_RULE_SETUP
{ BEGIN(ATC_DEF); atp_store_string_param(); return ATC_DEF_NAME; }
	ATP_BREAK
case 2:
ATP_RULE_SETUP
{ return ATC_DEF_BEGIN; }
	ATP_BREAK
case 3:
ATP_RULE_SETUP
{ BEGIN(INITIAL); return ATC_DEF_END; }
	ATP_BREAK
case 4:
ATP_RULE_SETUP
{ atp_store_string_param(); return ATC_DEF_STRING; }
	ATP_BREAK
case 5:
ATP_RULE_SETUP
{ atp_store_numeric_param(); return ATC_DEF_NUMBER; }
	ATP_BREAK
case 6:
ATP_RULE_SETUP
{ return ATC_DEF_INFINITY; }
	ATP_BREAK
case 7:
ATP_RULE_SETUP
{ }
	ATP_BREAK
case 8:
ATP_RULE_SETUP
{ return atptext[0]; }
	ATP_BREAK
case 9:
ATP_RULE_SETUP
{ last_start = atp_start; BEGIN(ATC_COMMENT); }
	ATP_BREAK
case 10:
ATP_RULE_SETUP
{ atp_start = last_start; }
	ATP_BREAK
case 11:
ATP_RULE_SETUP
{ }
	ATP_BREAK
case 12:
ATP_RULE_SETUP
ECHO;
	ATP_BREAK
case ATP_STATE_EOF(INITIAL):
case ATP_STATE_EOF(ATC_DEF):
case ATP_STATE_EOF(ATC_COMMENT):
	atpterminate();

	case ATP_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int atp_amount_of_matched_text = (int) (atp_cp - atptext_ptr) - 1;

		/* Undo the effects of ATP_DO_BEFORE_ACTION. */
		*atp_cp = atp_hold_char;
		ATP_RESTORE_ATP_MORE_OFFSET

		if ( atp_current_buffer->atp_buffer_status == ATP_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed atpin at a new source and called
			 * atplex().  If so, then we have to assure
			 * consistency between atp_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			atp_n_chars = atp_current_buffer->atp_n_chars;
			atp_current_buffer->atp_input_file = atpin;
			atp_current_buffer->atp_buffer_status = ATP_BUFFER_NORMAL;
			}

		/* Note that here we test for atp_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since atp_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( atp_c_buf_p <= &atp_current_buffer->atp_ch_buf[atp_n_chars] )
			{ /* This was really a NUL. */
			atp_state_type atp_next_state;

			atp_c_buf_p = atptext_ptr + atp_amount_of_matched_text;

			atp_current_state = atp_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * atp_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			atp_next_state = atp_try_NUL_trans( atp_current_state );

			atp_bp = atptext_ptr + ATP_MORE_ADJ;

			if ( atp_next_state )
				{
				/* Consume the NUL. */
				atp_cp = ++atp_c_buf_p;
				atp_current_state = atp_next_state;
				goto atp_match;
				}

			else
				{
				atp_cp = atp_c_buf_p;
				goto atp_find_action;
				}
			}

		else switch ( atp_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				atp_did_buffer_switch_on_eof = 0;

				if ( atpwrap() )
					{
					/* Note: because we've taken care in
					 * atp_get_next_buffer() to have set up
					 * atptext, we can now set up
					 * atp_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * ATP_NULL, it'll still work - another
					 * ATP_NULL will get returned.
					 */
					atp_c_buf_p = atptext_ptr + ATP_MORE_ADJ;

					atp_act = ATP_STATE_EOF(ATP_START);
					goto do_action;
					}

				else
					{
					if ( ! atp_did_buffer_switch_on_eof )
						ATP_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				atp_c_buf_p =
					atptext_ptr + atp_amount_of_matched_text;

				atp_current_state = atp_get_previous_state();

				atp_cp = atp_c_buf_p;
				atp_bp = atptext_ptr + ATP_MORE_ADJ;
				goto atp_match;

			case EOB_ACT_LAST_MATCH:
				atp_c_buf_p =
				&atp_current_buffer->atp_ch_buf[atp_n_chars];

				atp_current_state = atp_get_previous_state();

				atp_cp = atp_c_buf_p;
				atp_bp = atptext_ptr + ATP_MORE_ADJ;
				goto atp_find_action;
			}
		break;
		}

	default:
		ATP_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of atplex */


/* atp_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int atp_get_next_buffer()
	{
	register char *dest = atp_current_buffer->atp_ch_buf;
	register char *source = atptext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( atp_c_buf_p > &atp_current_buffer->atp_ch_buf[atp_n_chars + 1] )
		ATP_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( atp_current_buffer->atp_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( atp_c_buf_p - atptext_ptr - ATP_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (atp_c_buf_p - atptext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( atp_current_buffer->atp_buffer_status == ATP_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		atp_current_buffer->atp_n_chars = atp_n_chars = 0;

	else
		{
		int num_to_read =
			atp_current_buffer->atp_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef ATP_USES_REJECT
			ATP_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			ATP_BUFFER_STATE b = atp_current_buffer;

			int atp_c_buf_p_offset =
				(int) (atp_c_buf_p - b->atp_ch_buf);

			if ( b->atp_is_our_buffer )
				{
				int new_size = b->atp_buf_size * 2;

				if ( new_size <= 0 )
					b->atp_buf_size += b->atp_buf_size / 8;
				else
					b->atp_buf_size *= 2;

				b->atp_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					atp_flex_realloc( (void *) b->atp_ch_buf,
							 b->atp_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->atp_ch_buf = 0;

			if ( ! b->atp_ch_buf )
				ATP_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			atp_c_buf_p = &b->atp_ch_buf[atp_c_buf_p_offset];

			num_to_read = atp_current_buffer->atp_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > ATP_READ_BUF_SIZE )
			num_to_read = ATP_READ_BUF_SIZE;

		/* Read in more data. */
		ATP_INPUT( (&atp_current_buffer->atp_ch_buf[number_to_move]),
			atp_n_chars, num_to_read );

		atp_current_buffer->atp_n_chars = atp_n_chars;
		}

	if ( atp_n_chars == 0 )
		{
		if ( number_to_move == ATP_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			atprestart( atpin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			atp_current_buffer->atp_buffer_status =
				ATP_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	atp_n_chars += number_to_move;
	atp_current_buffer->atp_ch_buf[atp_n_chars] = ATP_END_OF_BUFFER_CHAR;
	atp_current_buffer->atp_ch_buf[atp_n_chars + 1] = ATP_END_OF_BUFFER_CHAR;

	atptext_ptr = &atp_current_buffer->atp_ch_buf[0];

	return ret_val;
	}


/* atp_get_previous_state - get the state just before the EOB char was reached */

static atp_state_type atp_get_previous_state()
	{
	register atp_state_type atp_current_state;
	register char *atp_cp;

	atp_current_state = atp_start;

	for ( atp_cp = atptext_ptr + ATP_MORE_ADJ; atp_cp < atp_c_buf_p; ++atp_cp )
		{
		register ATP_CHAR atp_c = (*atp_cp ? atp_ec[ATP_SC_TO_UI(*atp_cp)] : 1);
		if ( atp_accept[atp_current_state] )
			{
			atp_last_accepting_state = atp_current_state;
			atp_last_accepting_cpos = atp_cp;
			}
		while ( atp_chk[atp_base[atp_current_state] + atp_c] != atp_current_state )
			{
			atp_current_state = (int) atp_def[atp_current_state];
			if ( atp_current_state >= 37 )
				atp_c = atp_meta[(unsigned int) atp_c];
			}
		atp_current_state = atp_nxt[atp_base[atp_current_state] + (unsigned int) atp_c];
		}

	return atp_current_state;
	}


/* atp_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = atp_try_NUL_trans( current_state );
 */

#ifdef ATP_USE_PROTOS
static atp_state_type atp_try_NUL_trans( atp_state_type atp_current_state )
#else
static atp_state_type atp_try_NUL_trans( atp_current_state )
atp_state_type atp_current_state;
#endif
	{
	register int atp_is_jam;
	register char *atp_cp = atp_c_buf_p;

	register ATP_CHAR atp_c = 1;
	if ( atp_accept[atp_current_state] )
		{
		atp_last_accepting_state = atp_current_state;
		atp_last_accepting_cpos = atp_cp;
		}
	while ( atp_chk[atp_base[atp_current_state] + atp_c] != atp_current_state )
		{
		atp_current_state = (int) atp_def[atp_current_state];
		if ( atp_current_state >= 37 )
			atp_c = atp_meta[(unsigned int) atp_c];
		}
	atp_current_state = atp_nxt[atp_base[atp_current_state] + (unsigned int) atp_c];
	atp_is_jam = (atp_current_state == 36);

	return atp_is_jam ? 0 : atp_current_state;
	}


#ifndef ATP_NO_UNPUT
#ifdef ATP_USE_PROTOS
static void atpunput( int c, register char *atp_bp )
#else
static void atpunput( c, atp_bp )
int c;
register char *atp_bp;
#endif
	{
	register char *atp_cp = atp_c_buf_p;

	/* undo effects of setting up atptext */
	*atp_cp = atp_hold_char;

	if ( atp_cp < atp_current_buffer->atp_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = atp_n_chars + 2;
		register char *dest = &atp_current_buffer->atp_ch_buf[
					atp_current_buffer->atp_buf_size + 2];
		register char *source =
				&atp_current_buffer->atp_ch_buf[number_to_move];

		while ( source > atp_current_buffer->atp_ch_buf )
			*--dest = *--source;

		atp_cp += (int) (dest - source);
		atp_bp += (int) (dest - source);
		atp_current_buffer->atp_n_chars =
			atp_n_chars = atp_current_buffer->atp_buf_size;

		if ( atp_cp < atp_current_buffer->atp_ch_buf + 2 )
			ATP_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--atp_cp = (char) c;


	atptext_ptr = atp_bp;
	atp_hold_char = *atp_cp;
	atp_c_buf_p = atp_cp;
	}
#endif	/* ifndef ATP_NO_UNPUT */


#ifdef __cplusplus
static int atpinput()
#else
static int input()
#endif
	{
	int c;

	*atp_c_buf_p = atp_hold_char;

	if ( *atp_c_buf_p == ATP_END_OF_BUFFER_CHAR )
		{
		/* atp_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( atp_c_buf_p < &atp_current_buffer->atp_ch_buf[atp_n_chars] )
			/* This was really a NUL. */
			*atp_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = atp_c_buf_p - atptext_ptr;
			++atp_c_buf_p;

			switch ( atp_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because atp_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					atprestart( atpin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( atpwrap() )
						return EOF;

					if ( ! atp_did_buffer_switch_on_eof )
						ATP_NEW_FILE;
#ifdef __cplusplus
					return atpinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					atp_c_buf_p = atptext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) atp_c_buf_p;	/* cast for 8-bit char's */
	*atp_c_buf_p = '\0';	/* preserve atptext */
	atp_hold_char = *++atp_c_buf_p;


	return c;
	}


#ifdef ATP_USE_PROTOS
void atprestart( FILE *input_file )
#else
void atprestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! atp_current_buffer )
		atp_current_buffer = atp_create_buffer( atpin, ATP_BUF_SIZE );

	atp_init_buffer( atp_current_buffer, input_file );
	atp_load_buffer_state();
	}


#ifdef ATP_USE_PROTOS
void atp_switch_to_buffer( ATP_BUFFER_STATE new_buffer )
#else
void atp_switch_to_buffer( new_buffer )
ATP_BUFFER_STATE new_buffer;
#endif
	{
	if ( atp_current_buffer == new_buffer )
		return;

	if ( atp_current_buffer )
		{
		/* Flush out information for old buffer. */
		*atp_c_buf_p = atp_hold_char;
		atp_current_buffer->atp_buf_pos = atp_c_buf_p;
		atp_current_buffer->atp_n_chars = atp_n_chars;
		}

	atp_current_buffer = new_buffer;
	atp_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (atpwrap()) processing, but the only time this flag
	 * is looked at is after atpwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	atp_did_buffer_switch_on_eof = 1;
	}


#ifdef ATP_USE_PROTOS
void atp_load_buffer_state( void )
#else
void atp_load_buffer_state()
#endif
	{
	atp_n_chars = atp_current_buffer->atp_n_chars;
	atptext_ptr = atp_c_buf_p = atp_current_buffer->atp_buf_pos;
	atpin = atp_current_buffer->atp_input_file;
	atp_hold_char = *atp_c_buf_p;
	}


#ifdef ATP_USE_PROTOS
ATP_BUFFER_STATE atp_create_buffer( FILE *file, int size )
#else
ATP_BUFFER_STATE atp_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	ATP_BUFFER_STATE b;

	b = (ATP_BUFFER_STATE) atp_flex_alloc( sizeof( struct atp_buffer_state ) );
	if ( ! b )
		ATP_FATAL_ERROR( "out of dynamic memory in atp_create_buffer()" );

	b->atp_buf_size = size;

	/* atp_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->atp_ch_buf = (char *) atp_flex_alloc( b->atp_buf_size + 2 );
	if ( ! b->atp_ch_buf )
		ATP_FATAL_ERROR( "out of dynamic memory in atp_create_buffer()" );

	b->atp_is_our_buffer = 1;

	atp_init_buffer( b, file );

	return b;
	}


#ifdef ATP_USE_PROTOS
void atp_delete_buffer( ATP_BUFFER_STATE b )
#else
void atp_delete_buffer( b )
ATP_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == atp_current_buffer )
		atp_current_buffer = (ATP_BUFFER_STATE) 0;

	if ( b->atp_is_our_buffer )
		atp_flex_free( (void *) b->atp_ch_buf );

	atp_flex_free( (void *) b );
	}


#ifndef ATP_ALWAYS_INTERACTIVE
#ifndef ATP_NEVER_INTERACTIVE
extern int isatty ATP_PROTO(( int ));
#endif
#endif

#ifdef ATP_USE_PROTOS
void atp_init_buffer( ATP_BUFFER_STATE b, FILE *file )
#else
void atp_init_buffer( b, file )
ATP_BUFFER_STATE b;
FILE *file;
#endif


	{
	atp_flush_buffer( b );

	b->atp_input_file = file;
	b->atp_fill_buffer = 1;

#if ATP_ALWAYS_INTERACTIVE
	b->atp_is_interactive = 1;
#else
#if ATP_NEVER_INTERACTIVE
	b->atp_is_interactive = 0;
#else
	b->atp_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef ATP_USE_PROTOS
void atp_flush_buffer( ATP_BUFFER_STATE b )
#else
void atp_flush_buffer( b )
ATP_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->atp_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->atp_ch_buf[0] = ATP_END_OF_BUFFER_CHAR;
	b->atp_ch_buf[1] = ATP_END_OF_BUFFER_CHAR;

	b->atp_buf_pos = &b->atp_ch_buf[0];

	b->atp_at_bol = 1;
	b->atp_buffer_status = ATP_BUFFER_NEW;

	if ( b == atp_current_buffer )
		atp_load_buffer_state();
	}


#ifndef ATP_NO_SCAN_BUFFER
#ifdef ATP_USE_PROTOS
ATP_BUFFER_STATE atp_scan_buffer( char *base, atp_size_t size )
#else
ATP_BUFFER_STATE atp_scan_buffer( base, size )
char *base;
atp_size_t size;
#endif
	{
	ATP_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != ATP_END_OF_BUFFER_CHAR ||
	     base[size-1] != ATP_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (ATP_BUFFER_STATE) atp_flex_alloc( sizeof( struct atp_buffer_state ) );
	if ( ! b )
		ATP_FATAL_ERROR( "out of dynamic memory in atp_scan_buffer()" );

	b->atp_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->atp_buf_pos = b->atp_ch_buf = base;
	b->atp_is_our_buffer = 0;
	b->atp_input_file = 0;
	b->atp_n_chars = b->atp_buf_size;
	b->atp_is_interactive = 0;
	b->atp_at_bol = 1;
	b->atp_fill_buffer = 0;
	b->atp_buffer_status = ATP_BUFFER_NEW;

	atp_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef ATP_NO_SCAN_STRING
#ifdef ATP_USE_PROTOS
ATP_BUFFER_STATE atp_scan_string( atpconst char *atp_str )
#else
ATP_BUFFER_STATE atp_scan_string( atp_str )
atpconst char *atp_str;
#endif
	{
	int len;
	for ( len = 0; atp_str[len]; ++len )
		;

	return atp_scan_bytes( atp_str, len );
	}
#endif


#ifndef ATP_NO_SCAN_BYTES
#ifdef ATP_USE_PROTOS
ATP_BUFFER_STATE atp_scan_bytes( atpconst char *bytes, int len )
#else
ATP_BUFFER_STATE atp_scan_bytes( bytes, len )
atpconst char *bytes;
int len;
#endif
	{
	ATP_BUFFER_STATE b;
	char *buf;
	atp_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) atp_flex_alloc( n );
	if ( ! buf )
		ATP_FATAL_ERROR( "out of dynamic memory in atp_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = ATP_END_OF_BUFFER_CHAR;

	b = atp_scan_buffer( buf, n );
	if ( ! b )
		ATP_FATAL_ERROR( "bad buffer in atp_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->atp_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef ATP_NO_PUSH_STATE
#ifdef ATP_USE_PROTOS
static void atp_push_state( int new_state )
#else
static void atp_push_state( new_state )
int new_state;
#endif
	{
	if ( atp_start_stack_ptr >= atp_start_stack_depth )
		{
		atp_size_t new_size;

		atp_start_stack_depth += ATP_START_STACK_INCR;
		new_size = atp_start_stack_depth * sizeof( int );

		if ( ! atp_start_stack )
			atp_start_stack = (int *) atp_flex_alloc( new_size );

		else
			atp_start_stack = (int *) atp_flex_realloc(
					(void *) atp_start_stack, new_size );

		if ( ! atp_start_stack )
			ATP_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	atp_start_stack[atp_start_stack_ptr++] = ATP_START;

	BEGIN(new_state);
	}
#endif


#ifndef ATP_NO_POP_STATE
static void atp_pop_state()
	{
	if ( --atp_start_stack_ptr < 0 )
		ATP_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(atp_start_stack[atp_start_stack_ptr]);
	}
#endif


#ifndef ATP_NO_TOP_STATE
static int atp_top_state()
	{
	return atp_start_stack[atp_start_stack_ptr - 1];
	}
#endif

#ifndef ATP_EXIT_FAILURE
#define ATP_EXIT_FAILURE 2
#endif

#ifdef ATP_USE_PROTOS
static void atp_fatal_error( atpconst char msg[] )
#else
static void atp_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( ATP_EXIT_FAILURE );
	}



/* Redefine atpless() so it works in section 3 code. */

#undef atpless
#define atpless(n) \
	do \
		{ \
		/* Undo effects of setting up atptext. */ \
		atptext[atpleng] = atp_hold_char; \
		atp_c_buf_p = atptext + n; \
		atp_hold_char = *atp_c_buf_p; \
		*atp_c_buf_p = '\0'; \
		atpleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef atptext_ptr
#ifdef ATP_USE_PROTOS
static void atp_flex_strncpy( char *s1, atpconst char *s2, int n )
#else
static void atp_flex_strncpy( s1, s2, n )
char *s1;
atpconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef ATP_NEED_STRLEN
#ifdef ATP_USE_PROTOS
static int atp_flex_strlen( atpconst char *s )
#else
static int atp_flex_strlen( s )
atpconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef ATP_USE_PROTOS
static void *atp_flex_alloc( atp_size_t size )
#else
static void *atp_flex_alloc( size )
atp_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef ATP_USE_PROTOS
static void *atp_flex_realloc( void *ptr, atp_size_t size )
#else
static void *atp_flex_realloc( ptr, size )
void *ptr;
atp_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef ATP_USE_PROTOS
static void atp_flex_free( void *ptr )
#else
static void atp_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if ATP_MAIN
int main()
	{
	atplex();
	return 0;
	}
#endif


