//[[define image infomation
 //contrast
//RES_ADD_IMG(IMAGE_TEST_SHOW_FAIL,"\\MMI_RES_##\\IMAG\\IMAGE_PUBWIN_FAIL.png",IMG_CMP_PNG_ARGB,0)

//[[define string infomation
//RES_ADD_STRING(TXT_KM_FOLDER,"KingMovie")  //case 3: defined but not used
RES_ADD_STRING(TXT_KM,"King movie")
RES_ADD_STRING(TXT_KM_LAST_PLAYED,"Last played")
RES_ADD_STRING(TXT_KM_TYPE_ACTION,"Action")
RES_ADD_STRING(TXT_KM_TYPE_ADVENTURE,"Adventure")
RES_ADD_STRING(TXT_KM_TYPE_ANIMATION,"Animation")
RES_ADD_STRING(TXT_KM_TYPE_COMEDY,"Comedy")
RES_ADD_STRING(TXT_KM_TYPE_DOCUMENTARY,"Documentary")
RES_ADD_STRING(TXT_KM_TYPE_DRAMA,"Drama")
RES_ADD_STRING(TXT_KM_TYPE_FAMILY,"Family&Kids")
RES_ADD_STRING(TXT_KM_TYPE_FANTASY,"Fantasy")
RES_ADD_STRING(TXT_KM_TYPE_HORROR,"Horror")
RES_ADD_STRING(TXT_KM_TYPE_MUSIC,"Music")
RES_ADD_STRING(TXT_KM_TYPE_MYSTERY,"Mystery")
RES_ADD_STRING(TXT_KM_TYPE_PERFORMING,"Performing Arts")
RES_ADD_STRING(TXT_KM_TYPE_ROMANCE,"Romance")
RES_ADD_STRING(TXT_KM_TYPE_SCIFI,"Sci-Fi")
RES_ADD_STRING(TXT_KM_TYPE_SPORTS,"Sports")
RES_ADD_STRING(TXT_KM_TYPE_SUSPENSE,"Suspense")
RES_ADD_STRING(TXT_KM_TYPE_WAR,"War")
RES_ADD_STRING(TXT_KM_TYPE_WESTERN,"Western")
RES_ADD_STRING(TXT_KM_TYPE_OTHER,"Others")
//RES_ADD_STRING(TXT_KM_OPEN,"Open")  //replaced by common ID TXT_COMM_OPEN
RES_ADD_STRING(TXT_KM_UPDATE_LIST,"Update list")
//RES_ADD_STRING(TXT_KM_UPDATING,"Updating...")       //replaced by common ID TXT_COMMON_UPDATING
//RES_ADD_STRING(TXT_KM_PLEASE_WAIT,"Please wait")//case 3:defined but not used
RES_ADD_STRING(TXT_KM_TIME,"Time:")
RES_ADD_STRING(TXT_KM_MINS,"mins")
RES_ADD_STRING(TXT_KM_MOVIE_INFO,"Movie info")
//RES_ADD_STRING(TXT_KM_MOVIE_DELETE_COMFIRM,"Delete this movie?")//case 3:defined but not used
//RES_ADD_STRING(TXT_KM_INFO_FILE_NAME,"File name:")  //replaced by common ID TXT_INPUT_FILE_NAME
RES_ADD_STRING(TXT_KM_INFO_YEAR,"Year:")
RES_ADD_STRING(TXT_KM_INFO_STARRING,"Starring:")
RES_ADD_STRING(TXT_KM_INFO_SYNOPSIS,"Synopsis:")
//RES_ADD_STRING(TXT_KM_INSERT_TCARD_FIRST,"Please insert memory card")    //replaced by common ID TXT_COMMON_INSERT_MEMORYCARD
RES_ADD_STRING(TXT_KM_ALLOC_MEMORY_FAIL,"Alloc memory fail")
//RES_ADD_STRING(TXT_KM_CARD_NO_SPACE,"Disk space insufficient")    //replaced by common ID TXT_NO_DISK_SPACE
