

//[[define image infomation
//]]define image infomation


//[[define anim infomation
//]]define anim infomation


//[[define string infomation
RES_ADD_STRING(TXT_ENG_OK,"OK")
RES_ADD_STRING(TXT_ENG_RETURN,"Return")
RES_ADD_STRING(TXT_ENG_PASS, "Pass")			//MS00193068
RES_ADD_STRING(TXT_ENG_FAIL, "Fail")			//MS00193068
RES_ADD_STRING(TXT_ENG_PHONETEST,"Phone test")			//MS00193068
RES_ADD_STRING(TXT_ENG_VERSION_INFO,"Version info")
RES_ADD_STRING(TXT_ENG_RESET,"Reset")

RES_ADD_STRING(TXT_ENG_UITEST_TITLE,"MMI UI-TEST")
//RES_ADD_STRING(TXT_ENG_UIREADY,"Any key continue")      //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_SHOWVERSION_TITLE,"VERSION")      //case3：defined but not used
RES_ADD_STRING(TXT_ENG_UIRTC_TITLE,"RTC")
RES_ADD_STRING(TXT_ENG_UIVIBRATE_TITLE,"Vibrate")
RES_ADD_STRING(TXT_ENG_UIBACKLIGHT_TITLE,"Backlight")
//RES_ADD_STRING(TXT_ENG_UICAMERA_TITLE,"Camera")      //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_UIHEADSET_TITLE,"Headset")  //replaced by common ID  TXT_COMM_HEADSET
RES_ADD_STRING(TXT_ENG_UILOOPBACK_TITLE,"Loopback")
RES_ADD_STRING(TXT_ENG_UIMELODY_TITLE,"Melody")
RES_ADD_STRING(TXT_ENG_UISD_TITLE,"SD Card")
RES_ADD_STRING(TXT_ENG_PRODUCT,"Product")

//RES_ADD_STRING(TXT_ENG_EDIT,"Edit")
RES_ADD_STRING(TXT_ENG_CLEAR,"Clear")
RES_ADD_STRING(TXT_ENG_LANGUAGE_SET_SUCC,"Language set Success")
//RES_ADD_STRING(TXT_ENG_CANCEL,"Cancel")       //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_SELECT,"Select")       //case3：defined but not used
#ifdef ENG_SUPPORT
RES_ADD_STRING(TXT_ENG_HELP_INFO,"Help Info")
RES_ADD_STRING(TXT_ENG_MEM_PRESS_INFO,"MEM Press Test")
RES_ADD_STRING(TXT_ENG_FLIGHT_MODE,"Flight Mode")
RES_ADD_STRING(TXT_ENG_PASSWORD_SET,"Password Set")
RES_ADD_STRING(TXT_ENG_UDISK_PRESS_INFO,"UDISK Press Test")
RES_ADD_STRING(TXT_ENG_SD_PRESS_INFO,"SD Press Test")
RES_ADD_STRING(TXT_ENG_SIM_PRESS_RUN,"Run")
RES_ADD_STRING(TXT_ENG_SIM_PRESS_STOP,"Stop")
//2022-04-18add
RES_ADD_STRING(TXT_ENG_CSCON_STATUS,"Rat Status")


#ifdef WRE_SUPPORT
RES_ADD_STRING(TXT_ENG_WRE_VERSION_INFO,"WRE Version Info")
#endif
RES_ADD_STRING(TXT_ENG_NET_INFO,"Net info")
RES_ADD_STRING(TXT_ENG_PSCELL_INFO,"acfcn,  relvx   ,S/Ncell")
RES_ADD_STRING(TXT_ENG_PHONE_INFO,"Phone info")
RES_ADD_STRING(TXT_ENG_RESTORE_ENG,"Restore English language")
RES_ADD_STRING(TXT_ENG_PARA_SET,"Para set")
RES_ADD_STRING(TXT_ENG_POWER_KEY,"Power key")
#ifdef DSP_USB_LOG
RES_ADD_STRING(TXT_ENG_DSPCARD_LOG_ENABLE,"dsp card log enable")//xuefangjiang 20110729
#endif
RES_ADD_STRING(TXT_ENG_VOICE_PARAM,"Voice Param")
RES_ADD_STRING(TXT_ENG_LCD_PARAM,"LCD param")
RES_ADD_STRING(TXT_ENG_DEBUG_PARAM,"Debug Param")
RES_ADD_STRING(TXT_ENG_RF_PARAM,"RF param")
RES_ADD_STRING(TXT_ENG_HW_PARAM,"HW param")
RES_ADD_STRING(TXT_ENG_ARM_LOG,"ARM log")
RES_ADD_STRING(TXT_ENG_SLEEP_MODE,"Sleep mode")
RES_ADD_STRING(TXT_ENG_AUTO_POWERON,"Auto power on")
RES_ADD_STRING(TXT_ENG_STANDBY_TIME,"Standby time")
RES_ADD_STRING(TXT_ENG_SHOW_STANDBY_TIME,"Show standby time")
RES_ADD_STRING(TXT_ENG_STANDBY_TIME_SET,"Set standby time")    
RES_ADD_STRING(TXT_ENG_GET_FLASH_INFO,"Get FLASH ID")
RES_ADD_STRING(TXT_ENG_UPDATE_IMEI,"Update IMEI Number")
RES_ADD_STRING(TXT_ENG_DSP_LOG,"DSP log")
//RES_ADD_STRING(TXT_ENG_GPRS,"GPRS") //replaced by common ID TXT_GPRS
RES_ADD_STRING(TXT_ENG_YES,"Yes")
RES_ADD_STRING(TXT_ENG_NO,"No")
//RES_ADD_STRING(TXT_ENG_OPEN,"Open")  //replaced by common ID TXT_OPEN_COMN
//RES_ADD_STRING(TXT_ENG_CLOSE,"Close")  //replaced by common ID TXT_COMM_CLOSE
//RES_ADD_STRING(TXT_ENG_ON,"On")  //replaced by common ID TXT_COMM_ON
//RES_ADD_STRING(TXT_ENG_OFF,"Off") //replaced by common ID TXT_COMM_OFF
RES_ADD_STRING(TXT_ENG_HDSTSDTONE,"Hdst Sidetone")
RES_ADD_STRING(TXT_ENG_C_HDSTSDTONE,"Close Hdst Sidetone")
RES_ADD_STRING(TXT_ENG_EARPHSDTONE,"Earphn Sidetone")
RES_ADD_STRING(TXT_ENG_C_EARPHSDTONE,"Close Earphn Sidetone")
RES_ADD_STRING(TXT_ENG_HDSTDGT,"Handset Dgt")
RES_ADD_STRING(TXT_ENG_HDFREDGT,"Handfree Dgt")
RES_ADD_STRING(TXT_ENG_EARPHDGT,"Earphone Dgt")
RES_ADD_STRING(TXT_ENG_HDSTPGA,"Handset PGA")
RES_ADD_STRING(TXT_ENG_HDFREPGA,"Handfree PGA")
RES_ADD_STRING(TXT_ENG_EARPHPGA,"Earphone PGA")
RES_ADD_STRING(TXT_ENG_HDSTSCL,"Handset Scl")
RES_ADD_STRING(TXT_ENG_HDFRESCL,"Handfree Scl")
RES_ADD_STRING(TXT_ENG_EARPHSCL,"Earphone Scl")
RES_ADD_STRING(TXT_ENG_BRIGHTNESS,"Brightness Test")
RES_ADD_STRING(TXT_ENG_MAINLCD,"Main LCD")
RES_ADD_STRING(TXT_ENG_SUBLCD,"Sub LCD")
RES_ADD_STRING(TXT_ENG_BAND,"Band select")
//RES_ADD_STRING(TXT_ENG_PORTSET,"Port set")
RES_ADD_STRING(TXT_ENG_ASSERTMODE,"Assert Mode")
RES_ADD_STRING(TXT_ENG_ASSERTTARGET,"Assert Target")
RES_ADD_STRING(TXT_ENG_MANUALASSERT,"Manual assert")
RES_ADD_STRING(TXT_ENG_WCNASSERT,"WCN assert")
RES_ADD_STRING(TXT_ENG_FORBIDPLMN,"Forbid PLMN")
RES_ADD_STRING(TXT_ENG_NO_PLMN,"PLMN not found")
RES_ADD_STRING(TXT_ENG_PLMN_SELECT,"PLMN Select")


RES_ADD_STRING(TXT_ENG_ASSERT_RESTART,"Assert restart")
RES_ADD_STRING(TXT_ENG_ASSERT_INFO,"Assert info")
RES_ADD_STRING(TXT_ENG_BAND_PCS,"PCS band")
RES_ADD_STRING(TXT_ENG_BAND_GSM,"GSM band")
RES_ADD_STRING(TXT_ENG_BAND_DCS,"DCS band")
RES_ADD_STRING(TXT_ENG_BAND_DUL,"Dual band")
//RES_ADD_STRING(TXT_ENG_PORT_DATA,"Data mode")
//RES_ADD_STRING(TXT_ENG_PORT_AT,"AT mode")
//RES_ADD_STRING(TXT_ENG_PORT_MIXED,"Mixed mode")
//RES_ADD_STRING(TXT_ENG_DEBUGMODE,"Debug mode") ////replaced by common ID TXT_COMM_DEBUG_MODE
RES_ADD_STRING(TXT_ENG_RELEASEMODE,"Release mode")
RES_ADD_STRING(TXT_ENG_SEND_POWER,"Send power")
RES_ADD_STRING(TXT_ENG_NETLOST,"Net lost")
RES_ADD_STRING(TXT_ENG_TCV,"TCV")
//RES_ADD_STRING(TXT_ENG_AFC,"AFC")
//RES_ADD_STRING(TXT_ENG_PA,"PA")
//RES_ADD_STRING(TXT_ENG_AGC,"AGC")
RES_ADD_STRING(TXT_ENG_ERRRATE,"ERR rate")
//RES_ADD_STRING(TXT_ENG_TITLE,"ENG MODE") //move to common
RES_ADD_STRING(TXT_ENG_RESULT,"Result")
RES_ADD_STRING(TXT_ENG_LAYER1_MONITOR,"Layer1 monitor")
RES_ADD_STRING(TXT_ENG_SENSOR_MODE,"Sensor Mode")
RES_ADD_STRING(TXT_ENG_DEFAULT,"Default")
//RES_ADD_STRING(TXT_ENG_DCD_DEFAULT,"DCD Default")
RES_ADD_STRING(TXT_ENG_DCD_NOTE,"DCD Update Log")
RES_ADD_STRING(TXT_ENG_NET_SET, "Net Setting")
RES_ADD_STRING(TXT_ENG_RGB,"RGB")
RES_ADD_STRING(TXT_ENG_YUV,"YUV")
//RES_ADD_STRING(TXT_ENG_UIKEYBOARD_TITLE,"Keyboard")       //case3：defined but not used
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE,"DV frame fre")
//RES_ADD_STRING(TXT_ENG_WAP_SETTINGS,"Wap settings")         //case3：defined but not used
RES_ADD_STRING(TXT_ENG_UA_AGENT,"User agent")
RES_ADD_STRING(TXT_ENG_UA_PROFILE,"UA profile")
RES_ADD_STRING(TXT_ENG_WAP_LOG,"Wap log")
//RES_ADD_STRING(TXT_ENG_SAS_TEST_MODE,"SAS Test Mode")
RES_ADD_STRING(TXT_ENG_HIDDEN_PARTITION_VISIBLE,"Hidden partition visible")
RES_ADD_STRING(TXT_ENG_CALLFORWARD_QUERY,"Start Call forward query when power on")
RES_ADD_STRING(TXT_ENG_BT_INFO,"Bluetooth info")
RES_ADD_STRING(TXT_EMG_BT_ADDR_INFO,"Address info")
RES_ADD_STRING(TXT_ENG_ENTER_BT_EUT,"Enter EUT mode")
RES_ADD_STRING(TXT_ENG_LEAVE_BT_EUT,"Leave EUT mode")
RES_ADD_STRING(TXT_ENG_BT_SSP_DEBUG,"SSP debug mode")
RES_ADD_STRING(TXT_ENG_BT_BQB_MODE,"Bqb mode")

RES_ADD_STRING(TXT_ENG_ENTER_BT_NOSIGNAL,"BT NOSIGNAL TEST")
RES_ADD_STRING(TXT_ENG_ENTER_BT_NOSIGNAL_TX,"NO SIGNALLING TX")
RES_ADD_STRING(TXT_ENG_ENTER_BT_NOSIGNAL_RX,"NO SIGNALLING RX")
RES_ADD_STRING(TXT_ENG_ENTER_BT_NOSIGNAL_BLE_TX,"NO SIGNALLING BLE TX")
RES_ADD_STRING(TXT_ENG_ENTER_BT_NOSIGNAL_BLE_RX,"NO SIGNALLING BLE RX")
RES_ADD_STRING(TXT_ENG_BT_BLE_TEST,"BLE Test")

RES_ADD_STRING(TXT_ENG_BT_ROLE,"BT Role")
RES_ADD_STRING(TXT_ENG_BT_AUTO,"Auto")
RES_ADD_STRING(TXT_ENG_BT_MASETER,"Master(Phone)")
RES_ADD_STRING(TXT_ENG_BT_SLAVER,"Slaver(Dialer)")

RES_ADD_STRING(TXT_ENG_BT_VISIBLE_SET,"BT Visibilty Set")
RES_ADD_STRING(TXT_ENG_BT_VISIBLE_NONE,"Visible None")
RES_ADD_STRING(TXT_ENG_BT_ONLY_SEARCH_VISIBLE,"Only Search Visible")
RES_ADD_STRING(TXT_ENG_BT_ONLY_CONNECT_VISIBLE,"Only Connect Visible")
RES_ADD_STRING(TXT_ENG_BT_SEARCH_CONNECT_VISIBLE,"Both Search and Connect Visible")
RES_ADD_STRING(TXT_ENG_BT_LOCAL_NAME_SET,"BT Local Name Set")
RES_ADD_STRING(TXT_ENG_BT_NEW_LOCAL_NAME,"New BT Local Name:")


RES_ADD_STRING(TXT_BT_NOSIGNAL_LE_PHY1,"LE1M")
RES_ADD_STRING(TXT_BT_NOSIGNAL_LE_PHY2,"LE2M")
RES_ADD_STRING(TXT_BT_NOSIGNAL_LE_PHY3,"LE Coded S8")
RES_ADD_STRING(TXT_BT_NOSIGNAL_LE_PHY4,"LE Coded S2")
RES_ADD_STRING(TXT_BT_NOSIGNAL_LE_PHY5,"LE Coded")

RES_ADD_STRING(TXT_BT_NOSIGNAL_MOD_INDEX1,"Stable")
RES_ADD_STRING(TXT_BT_NOSIGNAL_MOD_INDEX2,"Standard")

RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_PAYLOAD1,"11111111100000111101")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_PAYLOAD2,"01010101")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_PAYLOAD3,"00001111")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_PAYLOAD4,"PRBS15")

RES_ADD_STRING(TXT_BT_NOSIGNAL_PATTERN1,"00000000")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PATTERN2,"11111111")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PATTERN3,"10101010")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PATTERN4,"PRBS9")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PATTERN5,"11110000")

RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE1,"NULLpkt")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE2,"POLLpkt")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE3,"FHSpkt")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE4,"DM1")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE5,"DH1")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE6,"HV1")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE7,"HV2")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE8,"HV3")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE9,"DV")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE10,"AUX1")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE11,"DM3")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE12,"DH3")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE13,"EV4")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE14,"EV5")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE15,"DM5")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE16,"DH5")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE17,"IDpkt")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE18,"INVAILIDpkt")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE19,"EDR_2DH1")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE20,"EV3")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE21,"EDR_2EV3")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE22,"EDR_3EV3")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE23,"EDR_3DH1")//modify 
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE24,"EDR_AUX1")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE25,"EDR_2DH3")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE26,"EDR_3HD3")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE27,"EDR_2EV5")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE28,"EDR_3EV5")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE29,"EDR_2DH5")
RES_ADD_STRING(TXT_BT_NOSIGNAL_PAC_TYPE30,"EDR_3DH5")

RES_ADD_STRING(TXT_BT_NOSIGNAL_POWER_TYPE0,"0")
RES_ADD_STRING(TXT_BT_NOSIGNAL_POWER_TYPE1,"1")

RES_ADD_STRING(TXT_BT_NOSIGNAL_FIRST,"Close BT first !")
RES_ADD_STRING(TXT_BT_NOSIGNAL_INFO,"RX data")
RES_ADD_STRING(TXT_BT_NOSIGNAL_UPDATE,"Update")
RES_ADD_STRING(TXT_BT_NOSIGNAL_TITLE,"BT NOSIGNAL Test")

//Menu for connectivity to adapt Android
RES_ADD_STRING(TXT_ENG_CONNECTIVITY_ALL_TITLE,"Connectivity")
RES_ADD_STRING(TXT_ENG_CON_FM_TITLE,"Fm Info")
RES_ADD_STRING(TXT_ENG_FM_REG_MODE,"Fm Reg Mode")
RES_ADD_STRING(TXT_ENG_FM_OBSERVE_STATE,"Fm Observe State")
RES_ADD_STRING(TXT_ENG_FM_DATA_CAPTURE,"Fm Data Capture")
RES_ADD_STRING(TXT_ENG_FM_CHANNEL_SET,"Fm Channel Set")
RES_ADD_STRING(TXT_ENG_FM_CHANNEL_SET_EAR,"Fm Play Ear or Extra")
RES_ADD_STRING(TXT_ENG_FM_EAR_ETR_SET,"Set Earphone Status times")
RES_ADD_STRING(TXT_ENG_FM_RDS_BLER_SET,"FM RDS BLER")
RES_ADD_STRING(TXT_ENG_FM_NOISE_SCAN,"FM NOISE SCAN")
RES_ADD_STRING(TXT_ENG_FM_TUNE_MODE,"FM TUNE MODE")
RES_ADD_STRING(TXT_ENG_FM_AUDIO_MODE,"FM AUDIO MODE")
RES_ADD_STRING(TXT_ENG_FM_WRITE,"Write")
RES_ADD_STRING(TXT_ENG_FM_READ,"Read")
RES_ADD_STRING(TXT_ENG_FM_EAR,"Ear")
RES_ADD_STRING(TXT_ENG_FM_EXTRA,"Extra")

//Menu for Telephony to adapt Android
RES_ADD_STRING(TXT_ENG_TELEPHONY_ALL_TITLE,"Telephony")
//Menu for Debug&Log to adapt Android
RES_ADD_STRING(TXT_ENG_DEBUG_LOG_ALL_TITLE,"Debug&Log")
RES_ADD_STRING(TXT_ENG_DEB_GPRS_ATTACH_SERVICE,"Gprs attach service")
RES_ADD_STRING(TXT_ENG_DEB_THERMAL_SWITCH,"Thermal")
RES_ADD_STRING(TXT_ENG_DEB_APR_SET,"APR Set")
RES_ADD_STRING(TXT_ENG_DEB_APR_UPLOAD,"Upload APR.xml")
RES_ADD_STRING(TXT_ENG_DEB_APR_SERVER,"APR Server")
RES_ADD_STRING(TXT_ENG_DEB_APR_SERVER_ANR,"ANR")
RES_ADD_STRING(TXT_ENG_DEB_APR_SERVER_NATIVE_CRASH,"Native crash")
RES_ADD_STRING(TXT_ENG_DEB_APR_SERVER_JAVA_CRASH,"Java crash")
RES_ADD_STRING(TXT_ENG_DEB_APR_SERVER_MODEM_ASSERT,"Modem assert")
RES_ADD_STRING(TXT_ENG_DEB_APR_SERVER_CRASH_CLASS,"Crash class")
RES_ADD_STRING(TXT_ENG_DEB_APR_AUTO_UPLOAD,"Auto Upload APR")
RES_ADD_STRING(TXT_ENG_DEB_APR_DETECT_TIME,"Detect Time")
RES_ADD_STRING(TXT_ENG_DEB_APR_GROUP,"Group")
RES_ADD_STRING(TXT_ENG_DEB_APR_GROUP_CSSLAB,"CSSLAB")
RES_ADD_STRING(TXT_ENG_DEB_APR_GROUP_CSFLAB,"CSFLAB")
RES_ADD_STRING(TXT_ENG_DEB_APR_GROUP_CSFT,"CSFT")
RES_ADD_STRING(TXT_ENG_DEB_APR_GROUP_Beta,"Beta")
RES_ADD_STRING(TXT_ENG_DEB_APR_VIEW_LOG,"View Log")
//Menu for HARDWARE to adapt Android
RES_ADD_STRING(TXT_ENG_HARDWARE_ALL_TITLE,"Hardware")
RES_ADD_STRING(TXT_ENG_HARD_VIBTEST_TITLE,"Vibrate Test")
RES_ADD_STRING(TXT_ENG_CAMERA_LCD_INFO_TITLE,"Camera/Lcd info")
RES_ADD_STRING(TXT_ENG_CAM_POW_TEST_MODE_TITLE,"Camera Power Test Mode")

//end for adapt to Android

RES_ADD_STRING(TXT_ENG_COMMON_SET,"SET")
RES_ADD_STRING(TXT_ENG_COMMON_GET,"GET")

RES_ADD_STRING(TXT_ENG_FM_REG_MODE_ADDR,"reg_addr (w,Hex)")
RES_ADD_STRING(TXT_ENG_FM_REG_MODE_DATA,"reg_data (wr,Hex)")
RES_ADD_STRING(TXT_ENG_FM_DATA_CAPTURE_LEVEL,"Capture Level (Hex)")
RES_ADD_STRING(TXT_ENG_FM_DATA_CAPTURE_NUM,"Capture Num (Hex)")


//Connectivity End

//RES_ADD_STRING(TXT_ENG_BAND_TRIPLE,"Triple band")      //case3：defined but not used
RES_ADD_STRING(TXT_ENG_BAND_QUAD,"Quadruple Band")
//RES_ADD_STRING(TXT_ENG_CHIP_TEST_SETTING,"Setting")      //replaced by common ID STXT_MAIN_SETTING
RES_ADD_STRING(TXT_ENG_POWERON_RUN,"Run when power on")
//RES_ADD_STRING(TXT_ENG_POWERON_NOT_RUN,"Not run when power on")   //case3：defined but not used
RES_ADD_STRING(TXT_ENG_CHIP_TEST,"Chip Test")
//RES_ADD_STRING(TXT_ENG_TIP_MPEG4,"Can't find test.mp4")    //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_TIP_MP3,"Can't find test.mp3")    //case3：defined but not used
//RES_ADD_STRING(STXT_ENG_GPS_TEST,"Test")    //case3：defined but not used
RES_ADD_STRING(TXT_ENG_CARDLOG,"Card Log")
RES_ADD_STRING(TXT_ENG_AUTO_ANSWER_CALL,"Auto Answer Call")
//RES_ADD_STRING(TXT_ENG_GPRS_ATTACH,"GPRS ATTACH")        //case3：defined but not used
RES_ADD_STRING(TXT_ENG_IQ_MODE,"IQ Mode")
//RES_ADD_STRING(TXT_ENG_POWERSWEEP_INFO,"Powersweep Info")
RES_ADD_STRING(TXT_ENG_IQ_DATA,"IQ Data")
//RES_ADD_STRING(TXT_ENG_IQ_DATA_SETTINGS,"Settings")       //replaced by common ID STXT_MAIN_SETTING
RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_SETTINGS,"Mode Settings")
RES_ADD_STRING(TXT_ENG_IQ_DATA_POWER_ON_START,"Power On Start")
//RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_D_SETTINGS,"Traffic IQ")     //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_CUSTOMIZE_SETTINGS,"Mode customized")  //replaced by common ID TXT_EXPORT_LOC_CUSTOM
RES_ADD_STRING(TXT_ENG_IQ_DATA_FORMAT_SETTING,"Format Setting")
RES_ADD_STRING(TXT_ENG_IQ_DATA_CHANNEL_SETTING,"Channel Setting")
RES_ADD_STRING(TXT_ENG_IQ_DATA_TIME_LIMIT,"Time Limit")
RES_ADD_STRING(TXT_ENG_IQ_DATA_FRAME_LENGTH,"Frame Length")
RES_ADD_STRING(TXT_ENG_IQ_DATA_BLOCK_COUNT,"Block Count")
RES_ADD_STRING(TXT_ENG_IQ_DATA_ARFCN,"arfcn")
//RES_ADD_STRING(TXT_ENG_USB_LOG,"USB LOG") //replaced by local ID TXT_COMM_USB_LOG
//RES_ADD_STRING(TXT_ENG_MMS_RESPONCE,"MMS Responce")    //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_MMS_MAX_SIZE,"MMS Max Size")    //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_MMS_300,"300")    //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_MMS_100,"100")      //case3：defined but not used

RES_ADD_STRING(TXT_ENG_START_CHIP_TEST,"Start Chip Test")
RES_ADD_STRING(TXT_ENG_SMSASSERT,"SMS ASSERT")
RES_ADD_STRING(TXT_ENG_IQ_MODE_WARNING,"Cannot Operate Record In IQ Mode")
RES_ADD_STRING(TXT_ENG_IQ_DATA_RECORD_AGAIN,"Format Memory, Record Again?")
RES_ADD_STRING(TXT_ENG_IQ_DATA_STOP_IQ_DATA_WARNING,"Please stop IQ data")
RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_A_SETTINGS,"CCCH IQ")
RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_B_SETTINGS,"Voice Data")
RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_C_SETTINGS,"Search IQ")
RES_ADD_STRING(TXT_ENG_IQ_DATA_ENABLE,"Enable")
RES_ADD_STRING(TXT_ENG_IQ_DATA_DISABLE,"Disable")
RES_ADD_STRING(TXT_ENG_IQ_DATA_CHANNEL_FILE,"File Output")
RES_ADD_STRING(TXT_ENG_IQ_DATA_CHANNEL_ARM_LOG,"ARM Log Output")
RES_ADD_STRING(TXT_ENG_GPS_TEST,"GPS test")
RES_ADD_STRING(TXT_ENG_FULLTEST,"Full phone test")			//MS00193068
RES_ADD_STRING(TXT_ENG_FORCE_CELL,"Froce cell")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_15,"15HZ")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_20,"20HZ")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_25,"25HZ")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_30,"30HZ")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_10,"10HZ")
RES_ADD_STRING(TXT_ENG_DCD_SET, "DCD Setting")
RES_ADD_STRING(TXT_ENG_CONTRAST,"Contrast Set")
RES_ADD_STRING(TXT_ENG_CMMB_RD_TEST, "CMMB R&D test")
RES_ADD_STRING(TXT_ENG_CMMB_DISPLAY,"Display")
RES_ADD_STRING(TXT_ENG_CMCC_TEST_SERVER, "CMCC test server")
//RES_ADD_STRING(TXT_ENG_CARDLOG_OPEN_ERROR, "Card log open fail!")// @cr239352 renwei add
RES_ADD_STRING(TXT_ENG_CARDLOG_OPEN_ERROR_UDISK, "Card log open fail! U Disk is in use!")// @cr239352 renwei add
RES_ADD_STRING(TXT_ENG_CARDLOG_OPEN_ERROR_USBLOG, "Card log open fail! USB log is on!")// @cr239352 renwei add
RES_ADD_STRING(TXT_ENG_CARDLOG_OPEN_ERROR_SDUSBLOG, "Card log open fail! SD USB log is on!")// @cr239352 renwei add

RES_ADD_STRING(TXT_ENG_CARDLOG_FORMAT_CONTINUE,"Card Log Format Continue")
RES_ADD_STRING(TXT_ENG_3RDPARTY_VERSION_INFO,"Third party version info")
RES_ADD_STRING(TXT_ENG_AUDIO_SPEAKER_VOLUME,"Speaker Volume")
RES_ADD_STRING(TXT_ENG_AUDIO_SIDETONE_VOLUME,"Sidetone Volume")
RES_ADD_STRING(TXT_ENG_AUDIO_RECORD,"Record")
RES_ADD_STRING(TXT_ENG_AUDIO_RECEIVER_VOLUME,"Receiver Volume")
RES_ADD_STRING(TXT_ENG_AUDIO_MP4HFTR,"MP4HFTR")
RES_ADD_STRING(TXT_ENG_AUDIO_MP4HFTP,"MP4HFTP")
RES_ADD_STRING(TXT_ENG_AUDIO_MP4HEADSET,"MP4Headset")
RES_ADD_STRING(TXT_ENG_AUDIO_MP3_LOUDSPK,"MP3_LoudSPK")
RES_ADD_STRING(TXT_ENG_AUDIO_MP3_EARPHONE,"MP3_EarPhone")
RES_ADD_STRING(TXT_ENG_AUDIO_MP3_HEADFREE,"MP3_HeadFree")
RES_ADD_STRING(TXT_ENG_AUDIO_MIC_VOLUME,"MIC Volume")
RES_ADD_STRING(TXT_ENG_AUDIO_HANDSFREE,"Handsfree")
RES_ADD_STRING(TXT_ENG_AUDIO_HANDSET,"Handset")
RES_ADD_STRING(TXT_ENG_AUDIO_EAR_VOLUME,"Ear Volume")
RES_ADD_STRING(TXT_ENG_CANCEL_FORCE_CELL,"Cancel forced cell")
RES_ADD_STRING(TXT_ENG_ADC_CALIBRATE_INFO,"Adc Calibrate Info")
RES_ADD_STRING(TXT_ENG_CMMB_TEST,"CMMB TV Test")
RES_ADD_STRING(TXT_ENG_CMMB_INI_FILE_ERROR, "CMMB configuration file error or not exist")
RES_ADD_STRING(TXT_ENG_CMMB_FACTORY_TEST, "CMMB factory test")
RES_ADD_STRING(TXT_ENG_CMMB_SN_NO, "CMMB SN")
RES_ADD_STRING(TXT_ENG_CMMB_FACTORY_HAVE_SIGNAL, "CMMB has signal test")
RES_ADD_STRING(TXT_ENG_CMMB_FACTORY_NO_SIGNAL, "CMMB no signal test")
RES_ADD_STRING(TXT_ENG_CMMB_RF_TEST, "CMMB RF test")
RES_ADD_STRING(TXT_ENG_ITEMTEST,"Item test")	
//RES_ADD_STRING(TXT_ENG_INVALID_ADDRESS,"Invalid address")     //case3：defined but not used

#ifdef PCLINK_SUPPORT
RES_ADD_STRING(TXT_ENG_SUCCESS_NEED_RESET,"Success,you need to reset")
RES_ADD_STRING(TXT_ENG_PCLINK,"PC Link Set")
RES_ADD_STRING(TXT_ENG_PCLINK_ENABLE,"PC Link enable")
RES_ADD_STRING(TXT_ENG_PCLINK_IP,"PC Link IP")
RES_ADD_STRING(TXT_ENG_PCLINK_SNMASK,"PC Link subnet mask")
RES_ADD_STRING(TXT_ENG_PCLINK_DEFGW,"PC Link gateway")
RES_ADD_STRING(TXT_ENG_PCLINK_DNS,"PC Link DNS")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_START,"Ping test start ...")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_OK,"Ping test OK")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_TIMEOUT,"Ping test time-out")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_CANCELED,"Ping test canceled")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_ERROR,"Ping test error")
RES_ADD_STRING(TXT_ENG_PCLINK_TEST,"PC Link test")
RES_ADD_STRING(TXT_ENG_PCLINK_TEST_ADDR,"Test Address")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST,"Ping Test")
#endif

RES_ADD_STRING(TXT_ENG_APP_SET,"App Set")
RES_ADD_STRING(TXT_ENG_DC_PARAM,"DC param")
RES_ADD_STRING(TXT_ENG_DC_PARAM_SCREEN_SIZE,"Screen Size")
RES_ADD_STRING(TXT_ENG_DC_PARAM_SCREEN_SWITCH,"Screen Switch")
RES_ADD_STRING(TXT_ENG_UA_SETTINGS,"UA SETTING")
RES_ADD_STRING(TXT_ENG_DC_PARAM_PREV_SET,"Prev Set")
RES_ADD_STRING(TXT_ENG_DC_PARAM_SENSOR_ANGLE,"Sensor Angle")
#ifdef  CAMERA_SUPPORT
RES_ADD_STRING(TXT_ENG_DC_176_220,"176*220")
RES_ADD_STRING(TXT_ENG_DC_240_320,"240*320")
RES_ADD_STRING(TXT_ENG_DC_220_400,"220*400")
RES_ADD_STRING(TXT_ENG_DC_ACROSS_SCREEN,"Across Screen")
RES_ADD_STRING(TXT_ENG_DC_UPRIGHT_SCREEN,"Upright Screen")
RES_ADD_STRING(TXT_ENG_DC_FULL_SCREEN,"Full Screen")
RES_ADD_STRING(TXT_ENG_DC_FULL_VIEW,"Full View")
#endif
RES_ADD_STRING(TXT_ENG_IQ_MODE_ONOFF,"On/Off")
//RES_ADD_STRING(TXT_ENG_LANGUAGE_SET_SUCC,"Language set Success")
//RES_ADD_STRING(TXT_ENG_LANGUAGE_NOT_EXIST,"Not Exist") //replaced by common ID TXT_COMMON_NOT_EXIST
//RES_ADD_STRING(TXT_ENG_CMMB_IQ_DATA,"IQ data")       //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_CMMB_PLAY,"Play")  //replaced by common ID  TXT_NET_PLAY
//RES_ADD_STRING(TXT_ENG_CMMB_SET,"Setting")        //case3：defined but not used

RES_ADD_STRING(TXT_ENG_AUDIO_SETTING,"Audio set")
//RES_ADD_STRING(TXT_ENG_AUDIO_HEADSET,"Headset") //replaced by common ID TXT_COMM_HEADSET
//RES_ADD_STRING(TXT_ENG_AUDIO_BT,"BT")  //replaced by common ID TXT_NET_UK_BT
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME1,"Vol 1")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME2,"Vol 2")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME3,"Vol 3")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME4,"Vol 4")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME5,"Vol 5")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME6,"Vol 6")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME7,"Vol 7")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME8,"Vol 8")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME9,"Vol 9")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME10,"Vol 10")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME11,"Vol 11")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME12,"Vol 12")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME13,"Vol 13")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME14,"Vol 14")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME15,"Vol 15")

//RES_ADD_STRING(TXT_ENG_PIM_DEBUG_SET,"PIM Debug set")//wangxiaolin 2009.07.07
//RES_ADD_STRING(TXT_ENG_MTV_INPUT_FREQ, "Input FREQ")   //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_CMMB_PLAY_RECORD, "Play record")    //case3：defined but not used

//RES_ADD_STRING(TXT_ENG_MBBMS_GBA,"GBA Test")     //case3：defined but not used
#ifdef DEMOD_HW_SIANO
RES_ADD_STRING(TXT_ENG_MBBMS_LOG,"LOG Control")
RES_ADD_STRING(TXT_ENG_MBBMS_MSK,"MSK Test")
#endif
//RES_ADD_STRING(TXT_ENG_MBBMS_GBA_AND_MSK_TEST,"GBA&&MSK Test")      //case3：defined but not used
#ifdef MBBMS_SUPPORT
RES_ADD_STRING(TXT_ENG_MBBMS_INTERFACE_TEST,"Interface testing")
RES_ADD_STRING(TXT_ENG_MBBMS_SMD_COUNTER,"SMD Counter")
#endif
#ifdef CMMB_SUPPORT
RES_ADD_STRING(TXT_ENG_MTV_LOG,"MTV LOG")
RES_ADD_STRING(TXT_ENG_MTV_LOG_SWITCH,"Switch")
RES_ADD_STRING(TXT_ENG_MTV_LOG_TO_BB_SWITCH,"Log to BB Switch")
RES_ADD_STRING(TXT_ENG_MTV_LOG_STORAGE_SELECT,"Storage Select")
RES_ADD_STRING(TXT_ENG_MTV_LOG_STORAGE_U,"U Disk")
RES_ADD_STRING(TXT_ENG_MTV_LOG_STORAGE_SD,"SD Card")

RES_ADD_STRING(TXT_ENG_MBBMS_AUDIO_SERVICE,"MBBMS audio service")
#endif
//RES_ADD_STRING(TXT_ENG_CMMB_DECODE_TEST, "CMMB Decode test")      //case3：defined but not used
RES_ADD_STRING(TXT_ENG_TCPIP_DEBUG, "Tcpip Debug")

RES_ADD_STRING(TXT_CAP_OUTPUT, "Cap Output")
//#endif  //ENG_SUPPORT
#ifdef MMI_SMS_RETRY_SUPPORT
RES_ADD_STRING(TXT_SMS_RETRY_SET, "SMS Retry set")
#endif

RES_ADD_STRING(TXT_ENG_UA_ON_OR_OFF,"on/off")
RES_ADD_STRING(TXT_ENG_UA_SET,"Set")
RES_ADD_STRING(TXT_ENG_UA_SHOW,"Show")

RES_ADD_STRING(TXT_ENG_PROFILE_SONYERICSSON,"SONYERICSSON")
RES_ADD_STRING(TXT_ENG_PROFILE_NOKIA,"NOKIA")
RES_ADD_STRING(TXT_ENG_ANGLE_0,"0")
RES_ADD_STRING(TXT_ENG_ANGLE_90,"90")
RES_ADD_STRING(TXT_ENG_ANGLE_180,"180")
RES_ADD_STRING(TXT_ENG_ANGLE_270,"270")
RES_ADD_STRING(TXT_ENG_UA_EDIT,"Edit")
RES_ADD_STRING(TXT_ENG_UA_LIST,"List")

RES_ADD_STRING(TXT_ENG_UA_NONE,"None")
RES_ADD_STRING(TXT_ENG_UA_DORADO,"DORADO")
RES_ADD_STRING(TXT_ENG_UA_MTK,"MTK")
RES_ADD_STRING(TXT_ENG_UA_09A,"09A")
RES_ADD_STRING(TXT_ENG_UA_NOKIA,"NOKIA")
RES_ADD_STRING(TXT_ENG_UA_NF,"NF")



RES_ADD_STRING(TXT_ENG_CALL_BARRING,"Call Barring")//MS00186848
RES_ADD_STRING(TXT_ENG_SET_ANGLE,"Set logic Angle")

RES_ADD_STRING(TXT_ENG_SET_LTE_OPERATION_MODE,"LTE operation Mode")
RES_ADD_STRING(TXT_ENG_SET_LTE_PS_2,"PS mode 2 ")
RES_ADD_STRING(TXT_ENG_SET_LTE_CS_PS_1,"CS/PS mode 1")
RES_ADD_STRING(TXT_ENG_SET_LTE_CS_PS_2,"CS/PS mode 2")
RES_ADD_STRING(TXT_ENG_SET_LTE_PS_1,"PS mode 1")

RES_ADD_STRING(TXT_ENG_FORBID_ALL_DATA,"Forbid all gprs data")
RES_ADD_STRING(TXT_ENG_FLOWRATE_INFO,"Statistical Flowrate")

#endif  //ENG_SUPPORT

#ifdef JAVA_SUPPORT_IA
RES_ADD_STRING(TXT_ENG_JAVA_AUTO_TCK_MODE, "JAVA AUTO TCK MODE")
#endif



#ifdef MEDIA_DEMO_SUPPORT
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO,"Media demo")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_DEMO,"Audio demo")
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_DEMO,"Video demo")


RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_AAC_STREAM_DEMO,"Aac stream")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_AMR_STREAM_DEMO,"Amr stream")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_AMR_RECORD_DEMO,"Amr record")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_MP3_STREAM_DEMO,"Mp3 stream")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_WAV_STREAM_DEMO,"Wav stream")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_EXPRESS_DEMO,   "Audio expression")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_CAT_MVOICE_DEMO,"Cat Mvoice")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_MIC_SAMPLE_DEMO,"Mic Sample")


RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_STREAM_LEFT_TRACK,"LTrack")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_STREAM_RIGHT_TRACK,"RTrack")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_STREAM_LEFT_AND_RIGHT,"LRTrack")

RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_RECORD, "Record")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_PLAY,   "Play")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_STOP,   "Stop")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_PAUSE,  "Pause")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_RESUME, "Resume")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_START,  "Start ")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_NEXT,   "NEXT ")

RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_MVCOIE,  "Mvoice ")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_VCOIE,   "Voice ")

RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_CHAT_DEMO, "Video Chat")
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_YUV_DEMO,"YUV Show ") 
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_YUV422_2P,"422_2P")
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_YUV420_2P,"420_2P")
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_YUV420_3P,"420_3P")

RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_EXPRESSION_CARD,"No card or No Demo source LRTrack1.mp3, please check and try again!")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_CAT_MVOICE_CARD,"No card,please check and try again!")
#endif
#ifdef ENG_SUPPORT
//MS00216980 cheney begin
RES_ADD_STRING(TXT_ENG_CMCC_TEST_CONFIG, "CMCC test config")
RES_ADD_STRING(TXT_ENG_CMCC_BUSINESS_SERVER, "CMCC business server")
//MS00216980 cheney end

RES_ADD_STRING(TXT_ENG_VIEWRESULT,"View phone test result")	//MS00193068
//RES_ADD_STRING(TXT_ENG_TEST_BATTERY , "Battery test")    //case3：defined but not used
RES_ADD_STRING(TXT_ENG_TEST_KEY , "Key test"  )
RES_ADD_STRING(TXT_ENG_TEST_MAINLCD, "Main lcd test")

RES_ADD_STRING(TXT_ENG_TEST_SIM, "SIM test")
RES_ADD_STRING(TXT_ENG_TEST_SIM_RESULT, "Test result:")
#ifdef SENSORHUB_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_SENSORHUB, "SensorHub test")
RES_ADD_STRING(TXT_ENG_SENSOR_VERSION, "传感器版本")
RES_ADD_STRING(TXT_ENG_SENSOR_INFO, "Sensor Test")
RES_ADD_STRING(TXT_ENG_SENSOR_FIRMWARE_DL, "应用固件下载")
RES_ADD_STRING(TXT_ENG_SENSOR_PRODUCTTEST_DL, "产测下载")
RES_ADD_STRING(TXT_ENG_SENSOR_HEARTRATE_ID, "心率传感器ID")
RES_ADD_STRING(TXT_ENG_SENSOR_ACC_ID, "加速度传感器ID")
RES_ADD_STRING(TXT_ENG_SENSOR_ACC_CALIBRATION, "加速度校准")
RES_ADD_STRING(TXT_ENG_SENSOR_BLE_BROADCAST, "BLE广播")
#endif

#ifdef ADULT_WATCH_SUPPORT
RES_ADD_STRING(TXT_ENG_OLD_MAINMENU_INFO, "Old MainMenu")
#endif

RES_ADD_STRING(TXT_ENG_PHONE_START_USB_LOG,"Auto USB Port")

RES_ADD_STRING(TXT_ENG_TEST_SIM1, "Test SIM1 reslut:")
RES_ADD_STRING(TXT_ENG_TEST_SIM2, "Test SIM2 reslut:")

RES_ADD_STRING(TXT_ENG_TEST_SIM_RESULT1, "Success!")
RES_ADD_STRING(TXT_ENG_TEST_SIM_RESULT2, "Failed!")

RES_ADD_STRING(TXT_ENG_TEST_RTC , "RTC test")
RES_ADD_STRING(TXT_ENG_TEST_VIBRATER, "Vibrater test" )
RES_ADD_STRING(TXT_ENG_TEST_BACKLIGHT, "Backlight test" )
RES_ADD_STRING(TXT_ENG_TEST_LOOPBACK, "Loopback test" )
RES_ADD_STRING(TXT_ENG_TEST_CAMERA , "Camera test" )
RES_ADD_STRING(TXT_ENG_TEST_VIDEO, "Video test" )
RES_ADD_STRING(TXT_ENG_TEST_BLUETOOTH , "BlueTooth test" )
RES_ADD_STRING(TXT_ENG_TEST_HEADSET , "Headset test" )
RES_ADD_STRING(TXT_ENG_TEST_MELODY , "Melody test")
#ifdef MSDC_CARD_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_SDCARD , "SDcard test" )
#endif
#endif
#ifdef APP_ENG_COMTEST_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_COM , "COM test")
#endif
#ifdef FM_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_FM , "FM test" )
#endif
//RES_ADD_STRING(TXT_ENG_TEST_TVOUT  , "TVOUT test" )    //case3：defined but not used


#ifdef ATV_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_ATV,  "ATV test" )
RES_ADD_STRING(TXT_ATV_CHANNEL,  "ATV Channel" )
RES_ADD_STRING(TXT_ATV_SIGNAL,  "ATV Signal" )
RES_ADD_STRING(TXT_ATV_CHANNEL_EDIT,  "ATV Channel Edit" )
#endif
RES_ADD_STRING(TXT_ENG_TEST_CHARGING,  "Charging Test" )
RES_ADD_STRING(TXT_ENG_TEST_EMCC,  "Emcc Test" )
#ifdef ENG_SUPPORT
RES_ADD_STRING(TXT_ENG_NVCOUNT,"Running NV Counting")		//195273
RES_ADD_STRING(TXT_ENG_BROWSER_LOG,"Browser Log")		//195273
RES_ADD_STRING(TXT_ENG_BROWSER_CHANGE_URL,"Browser Change URL")		//195273
RES_ADD_STRING(TXT_ENG_SCREEN_LOG,"Screen Log")
RES_ADD_STRING(TXT_ENG_UART, "UART")
RES_ADD_STRING(TXT_ENG_USB, "USB")
#endif

#ifdef MMI_AUTOTEST_SUPPORT
RES_ADD_STRING(TXT_ENG_AUTO_TEST_SET,"Auto test set")	
RES_ADD_STRING(TXT_ENG_AT_IMAGE_ID,"image id set")
RES_ADD_STRING(TXT_ENG_AT_TEXT,"text string set")
RES_ADD_STRING(TXT_ENG_AT_WIN_MSG,"window message set")
RES_ADD_STRING(TXT_ENG_AT_TP,"Tp set")
RES_ADD_STRING(TXT_ENG_AT_KEY,"key set")
RES_ADD_STRING(TXT_ENG_AT_MSG,"message set")
RES_ADD_STRING(TXT_ENG_AT_SOFTKEY,"softkey set")
RES_ADD_STRING(TXT_ENG_AT_TITLE,"title set")
RES_ADD_STRING(TXT_ENG_AT_POINTER_STATE,"pointer state set")
RES_ADD_STRING(TXT_ENG_AT_BACKLIGHT,"back light set")
#endif



//MS00202867 rick
#ifdef NANDBOOT_SUPPORT
RES_ADD_STRING(TXT_ENG_XSR_DEBUG, "Xsr Debug")
#endif
//MS00202867 rick


//RES_ADD_STRING(TXT_ENG_DEBUG_PORT_FAIL, "Debug port fail!")    //case3：defined but not used
//RES_ADD_STRING(TXT_ENG_USBLOG_ON, "Usb log on!")      //case3：defined but not used
#ifdef PRINTSCREEN_SUPPORT
RES_ADD_STRING(TXT_ENG_PRINTSCREEN, "PrintScreen")
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_OFF, "Off")
//renwei cr00114478 modify
#ifdef KEYPAD_TYPE_FOUR_KEY_UNIVERSE
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_PRESS_CAMREA_ONLYLCD_MODE, "Press Camrea(Only lcd)")
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_PRESS_CAMREA_LCDANDLAYER_MODE, "Press Camrea(Lcd and layer)")
#else
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_PRESS_ONLYLCD_MODE, "Press Call(Only lcd)")
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_PRESS_LCDANDLAYER_MODE, "Press Call(Lcd and layer)")
#endif
//renwei cr00114478 modify
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_AUTO_MODE, "Auto")
#endif

#ifdef MMISRV_AUDIO_TEST_SUPPORT
RES_ADD_STRING(TXT_ENG_AUDIO_SELF_TEST, "Audio Self Test")
RES_ADD_STRING(TXT_ENG_AUDIO_PLAY, "Audio Play")
#ifdef PRINTSCREEN_SUPPORT
RES_ADD_STRING(TXT_ENG_AUDIO_DISPLAY_INFO, "Display Audio Info")
#endif
#endif
// WLAN
#ifdef MMI_ENG_WIFI_SUPPORT
RES_ADD_STRING(TXT_ENG_WLAN_SET, "WLAN")
RES_ADD_STRING(TXT_ENG_WIFI_LOCATION, "WIFI location")
RES_ADD_STRING(TXT_ENG_WIFI_LOCATION_SCAN, "scan")
RES_ADD_STRING(TXT_ENG_WIFI_LOCATION_GET_POSITION, "get position")
RES_ADD_STRING(TXT_ENG_WLAN_POWER_SAVE, "power save")
RES_ADD_STRING(TXT_ENG_WLAN_ROAMING, "roaming")
RES_ADD_STRING(TXT_ENG_WLAN_PERFORMANCE_MODE, "performance mode")
RES_ADD_STRING(TXT_ENG_WLAN_RADIO_FREQUENCY, "Radio Frequency")
RES_ADD_STRING(TXT_ENG_WLAN_IPERF, "iperf")
RES_ADD_STRING(TXT_ENG_TEST_WIFI,  "WIFI test" )
RES_ADD_STRING(TXT_ENG_MAC,"mac")
RES_ADD_STRING(TXT_ENG_PHY0,"phy0")
RES_ADD_STRING(TXT_ENG_PHY1,"phy1")
RES_ADD_STRING(TXT_ENG_RF,"rf")
RES_ADD_STRING(TXT_ENG_WIFI_INFO,"Wifi Info")
#ifdef MMI_ENG_WIFI_SUPPORT
RES_ADD_STRING(TXT_ENG_WIFI_FLIGHTMODE,"Flight Mode Wifi")
#endif
RES_ADD_STRING(TXT_ENG_WIFI_TX,"TX")
RES_ADD_STRING(TXT_ENG_WIFI_RX,"RX")
RES_ADD_STRING(TXT_ENG_WIFI_REGWR,"REG_WR")
RES_ADD_STRING(TXT_ENG_WIFI_SAVE_MODE,"Power Save Mode")
RES_ADD_STRING(TXT_ENG_WIFI_PACKET_MODE,"Packet Check")
RES_ADD_STRING(TXT_ENG_WIFI_PACKET_SWITCH,"ON/OFF")
RES_ADD_STRING(TXT_ENG_WIFI_PACKET_ITEM,"Threshold(30min)")
RES_ADD_STRING(TXT_ENG_802B,"802.11b")
RES_ADD_STRING(TXT_ENG_G,"g")
RES_ADD_STRING(TXT_ENG_24G,"n_2.4G")
RES_ADD_STRING(TXT_ENG_CHANNEL1,"CH1")
RES_ADD_STRING(TXT_ENG_CHANNEL2,"CH2")
RES_ADD_STRING(TXT_ENG_CHANNEL3,"CH3")
RES_ADD_STRING(TXT_ENG_CHANNEL4,"CH4")
RES_ADD_STRING(TXT_ENG_CHANNEL5,"CH5")
RES_ADD_STRING(TXT_ENG_CHANNEL6,"CH6")
RES_ADD_STRING(TXT_ENG_CHANNEL7,"CH7")
RES_ADD_STRING(TXT_ENG_CHANNEL8,"CH8")
RES_ADD_STRING(TXT_ENG_CHANNEL9,"CH9")
RES_ADD_STRING(TXT_ENG_CHANNEL10,"CH10")
RES_ADD_STRING(TXT_ENG_CHANNEL11,"CH11")
RES_ADD_STRING(TXT_ENG_CHANNEL12,"CH12")
RES_ADD_STRING(TXT_ENG_CHANNEL13,"CH13")
RES_ADD_STRING(TXT_ENG_CHANNEL14,"CH14")
RES_ADD_STRING(TXT_ENG_RATE11B,"11b")
RES_ADD_STRING(TXT_ENG_RATE11G,"11g")
RES_ADD_STRING(TXT_ENG_RATE11N,"11n")
RES_ADD_STRING(TXT_ENG_RATE1M,"1Mbps")
RES_ADD_STRING(TXT_ENG_RATE2M,"2Mbps")
RES_ADD_STRING(TXT_ENG_RATE5M,"5Mbps")
RES_ADD_STRING(TXT_ENG_RATE11M,"11Mbps")
RES_ADD_STRING(TXT_ENG_RATE6M,"6Mbps")
RES_ADD_STRING(TXT_ENG_RATE9M,"9Mbps")
RES_ADD_STRING(TXT_ENG_RATE12M,"12Mbps")
RES_ADD_STRING(TXT_ENG_RATE18M,"18Mbps")
RES_ADD_STRING(TXT_ENG_RATE24M,"24Mbps")
RES_ADD_STRING(TXT_ENG_RATE36M,"36Mbps")
RES_ADD_STRING(TXT_ENG_RATE48M,"48Mbps")
RES_ADD_STRING(TXT_ENG_RATE54M,"54Mbps")
RES_ADD_STRING(TXT_ENG_RATEMCS0,"MCS0")
RES_ADD_STRING(TXT_ENG_RATEMCS1,"MCS1")
RES_ADD_STRING(TXT_ENG_RATEMCS2,"MCS2")
RES_ADD_STRING(TXT_ENG_RATEMCS3,"MCS3")
RES_ADD_STRING(TXT_ENG_RATEMCS4,"MCS4")
RES_ADD_STRING(TXT_ENG_RATEMCS5,"MCS5")
RES_ADD_STRING(TXT_ENG_RATEMCS6,"MCS6")
RES_ADD_STRING(TXT_ENG_RATEMCS7,"MCS7")
RES_ADD_STRING(TXT_ENG_PREAMBLE_NORMAL,"Nomal")
RES_ADD_STRING(TXT_ENG_PREAMBLE_CCK,"CCK short")
RES_ADD_STRING(TXT_ENG_PREAMBLE_MIX,"802.11n Mixed Mode")
RES_ADD_STRING(TXT_ENG_MODE_PKT,"802.11 pkt")
RES_ADD_STRING(TXT_ENG_MODE_WAVE,"sinewave")
RES_ADD_STRING(TXT_ENG_GUARD_INTERVAL_400,"400ns")
RES_ADD_STRING(TXT_ENG_GUARD_INTERVAL_800,"800ns")
RES_ADD_STRING(TXT_ENG_WIFI_IPADDR,"Connected WiFi IP address")
RES_ADD_STRING(TXT_ENG_WIFI_NOT_CONNECT,"Please connect wifi first!")
RES_ADD_STRING(TXT_ENG_IPERF_TCP,"TCP")
RES_ADD_STRING(TXT_ENG_IPERF_UDP,"UDP")
RES_ADD_STRING(TXT_ENG_IPERF_UP,"UP")
RES_ADD_STRING(TXT_ENG_IPERF_DOWN,"DOWN")
#endif
//RES_ADD_STRING(TXT_ENG_AT_ALL_SET, "All settings") // @CR247145 renwei add
RES_ADD_STRING(TXT_ENG_OTA,"OTA update")
RES_ADD_STRING(TXT_ENG_OTA_UPDATE_NOTIFICATION,"OTA update notification")
RES_ADD_STRING(TXT_EN_OTA_UPDATE_WARNING_1, "Low Battery,Not Allow Upgrading")
RES_ADD_STRING(TXT_EN_OTA_UPDATE_WARNING_2, "No SIM Card,Not Allow Upgrading")

#ifdef TF_LOAD_SUPPORT
RES_ADD_STRING(TXT_ENG_TF_UPDATE,"TF update")
RES_ADD_STRING(TXT_ENG_TF_UPDATE_NOTIFICATION,"TF update notification")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_1, "Low Battery")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_2, "Not Allow Upgrading")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_3, "No SD Card")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_4, "No find update file")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_5, "PAC not match")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_6, "tfboot.bin not match")
#endif

#ifdef MMI_DUALMODE_ENABLE
RES_ADD_STRING(TXT_ENG_NETWORK_TYPE,"Network type")
#endif

#ifdef MOTION_SENSOR_TYPE
RES_ADD_STRING(TXT_ENG_NOT_SUPPORT_MOTIONSENSOR,"Can't Support Motion Sensor!")
RES_ADD_STRING(TXT_ENG_TEST_MOTIONSENSOR,"Motion sensor test" )
RES_ADD_STRING(TXT_ENG_MOTIONSENSOR_TITLE,"Motion Sensor")
#endif
RES_ADD_STRING(TXT_ENG_MONKEY_TEST_SET,"Monkey test set")
RES_ADD_STRING(TXT_ENG_SLIENT_ENVIRONMENT, "Silent mode")
RES_ADD_STRING(TXT_ENG_PB_FULL, "Phone book full filled")
RES_ADD_STRING(TXT_ENG_SMS_FULL, "SMS full filled, not implemented yet")
RES_ADD_STRING(TXT_ENG_KEY_LOCK_OFF, "Key lock off")
RES_ADD_STRING(TXT_ENG_DISABLE_FLYMODE_SETTINGS, "Disable flymode settings")


RES_ADD_STRING(TXT_ENG_TEL_SIM_TRACE_TITLE,"SIM Trace")
RES_ADD_STRING(TXT_ENG_TEL_NETWORK_MODE_TITLE,"Network Mode")
RES_ADD_STRING(TXT_ENG_TEL_NETWORK_MODE_MULTI1,"TD_LTE/LTE FDD/W/GSM CSFB Multi-mode")
RES_ADD_STRING(TXT_ENG_TEL_NETWORK_MODE_DUALMODE,"TD-LTE/LTE FDD Dual-mode")
RES_ADD_STRING(TXT_ENG_TEL_NETWORK_MODE_WG_DUALMODE,"WG Dual-mode")
RES_ADD_STRING(TXT_ENG_TEL_NETWORK_MODE_W_SIGNELMODE,"W Single-mode")
RES_ADD_STRING(TXT_ENG_TEL_NETWORK_MODE_GSM_SINGLEMODE,"GSM Single-mode")
RES_ADD_STRING(TXT_ENG_DISABLE_BACKLIGHT_OFF, "Screen alway on")
RES_ADD_STRING(TXT_ENG_BAND_SELECT, "BANDSELECT")
RES_ADD_STRING(TXT_ENG_TEL_BAND_TDD,"LTE TDD MODE ")
RES_ADD_STRING(TXT_ENG_TEL_BAND_TDD34,"TDD_BAND34")
RES_ADD_STRING(TXT_ENG_TEL_BAND_TDD38,"TDD_BAND38")
RES_ADD_STRING(TXT_ENG_TEL_BAND_TDD39,"TDD_BAND39")
RES_ADD_STRING(TXT_ENG_TEL_BAND_TDD40,"TDD_BAND40")
RES_ADD_STRING(TXT_ENG_TEL_BAND_TDD41,"TDD_BAND41")
RES_ADD_STRING(TXT_ENG_TEL_BAND_FDD,"LTE FDD MODE ")
RES_ADD_STRING(TXT_ENG_TEL_BAND_FDD1,"FDD_BAND1")
RES_ADD_STRING(TXT_ENG_TEL_BAND_FDD3,"FDD_BAND3")
RES_ADD_STRING(TXT_ENG_TEL_BAND_FDD5,"FDD_BAND5")
RES_ADD_STRING(TXT_ENG_TEL_BAND_FDD7,"FDD_BAND7")
RES_ADD_STRING(TXT_ENG_TEL_BAND_FDD8,"FDD_BAND8")
RES_ADD_STRING(TXT_ENG_TEL_BAND_FDD20,"FDD_BAND20")
RES_ADD_STRING(TXT_ENG_TEL_BAND_GSM,"GSM MODE ")
RES_ADD_STRING(TXT_ENG_TEL_BAND_GSM1,"GSM900")
RES_ADD_STRING(TXT_ENG_TEL_BAND_GSM2,"DCS1800")
RES_ADD_STRING(TXT_ENG_TEL_BAND_GSM3,"PCS1900")
RES_ADD_STRING(TXT_ENG_TEL_BAND_GSM4,"GSM850")
RES_ADD_STRING(TXT_ENG_TEL_BAND_WCDMA,"WCDMA  MODE ")
RES_ADD_STRING(TXT_ENG_TEL_BAND_WCDMA1,"WCDMA1")
RES_ADD_STRING(TXT_ENG_TEL_BAND_WCDMA2,"WCDMA2")
RES_ADD_STRING(TXT_ENG_TEL_BAND_WCDMA5,"WCDMA5")
RES_ADD_STRING(TXT_ENG_TEL_BAND_WCDMA8,"WCDMA8")
//Netinfo begin
RES_ADD_STRING(TXT_ENG_NW_CAP,"NW cap")
RES_ADD_STRING(TXT_ENG_SERVING_CELL,"Serving cell")
RES_ADD_STRING(TXT_ENG_THE_ADJACENT_CELL ,"The Adjacent Cell")
RES_ADD_STRING(TXT_ENG_BETWEEN_ADJACENT_CELL,"Between Adjacent cell")
RES_ADD_STRING(TXT_ENG_BETWEEN_ADJACENT_CELL_2G,"Between Adjacent cell(2G)")
RES_ADD_STRING(TXT_ENG_OUTFIELD_NETWORK_INFORMATION,"Outfield Network Information")
RES_ADD_STRING(TXT_ENG_NETINFO_STATISTICS,"Netinfo statistics")
RES_ADD_STRING(TXT_ENG_NETINFO_RESELECT,"RESELECT")
RES_ADD_STRING(TXT_ENG_NETINFO_HANDOVER ,"HANDOVER")
RES_ADD_STRING(TXT_ENG_NETINFO_ATTACHTIME,"ATTACHTIME")
RES_ADD_STRING(TXT_ENG_NETINFO_DROPTIMES,"DROPTIMES")
//netinfo end
RES_ADD_STRING(TXT_ENG_TEL_VOLTE_SETTINGS_TITLE,"Volte Settings")
RES_ADD_STRING(TXT_ENG_TEL_VOLTE_IMS_MENU,"IMS MENU")
RES_ADD_STRING(TXT_ENG_TEL_VOLTE_ONOFF,"VOLTE ONOFF")
RES_ADD_STRING(TXT_ENG_TEL_VOLTE_IMS_PDN,"IMS PDN")
RES_ADD_STRING(TXT_ENG_TEL_VOLTE_IPV4,"IPV4")
RES_ADD_STRING(TXT_ENG_TEL_VOLTE_IPV6,"IPV6")
RES_ADD_STRING(TXT_ENG_TEL_VOLTE_IPV4V6,"IPV4V6")
RES_ADD_STRING(TXT_ENG_TEL_VOLTE_PLMN_WHITE_LIST_TITLE,"PLMN White List")
RES_ADD_STRING(TXT_ENG_TEL_VOLTE_PLMN_WHITE_LIST_RELEASED_TITLE,"Released White List")
RES_ADD_STRING(TXT_ENG_TEL_CSFB_GSM,"CSFB2GSM Delay")
RES_ADD_STRING(TXT_ENG_TEL_GRRC_RESI,"GRRC Resident State")
RES_ADD_STRING(TXT_ENG_TEL_CRRC_RAND,"GRRC Random Access State")
RES_ADD_STRING(TXT_ENG_FACTORY_RESET,"Factory Reset")
RES_ADD_STRING(TXT_ENG_INPUT_PHONE_PASSWORD,"please input phone password")
RES_ADD_STRING(TXT_ENG_NORMAL_FACTORY_RESET,"Normal Reset")
RES_ADD_STRING(TXT_ENG_DEEP_FACTORY_RESET,"Deep Reset")
RES_ADD_STRING(TXT_ENG_SMS_CENTER_NUMBER,"SMS Center Number")
RES_ADD_STRING(TXT_ENG_SET_SMS_CENTER_NUMBER,"Set SC Number")
RES_ADD_STRING(TXT_ENG_FAST_DORMANCY,"Fast Dormancy")
RES_ADD_STRING(TXT_ENG_INPUT_TIMES_DORMANCY,"Input times(s)")
RES_ADD_STRING(TXT_ENG_QOS_SWTICH,"Qos Switch")


RES_ADD_STRING(TXT_ENG_FATHER,"father")
RES_ADD_STRING(TXT_ENG_MOTHER,"mother")
RES_ADD_STRING(TXT_ENG_GRANDPA,"grandpa")
RES_ADD_STRING(TXT_ENG_GRANDMA,"gradma")
RES_ADD_STRING(TXT_ENG_TEACHER,"teacher")
RES_ADD_STRING(TXT_ENG_CLASSMATE,"classmate")
#ifdef SCREEN_SHAPE_CIRCULAR
RES_ADD_STRING(TXT_ENG_SISTER,"sister")
RES_ADD_STRING(TXT_ENG_BROTHER,"brother")
#endif

RES_ADD_STRING(TXT_ENG_IMAGE1,"image1")
RES_ADD_STRING(TXT_ENG_IMAGE2,"image2")
RES_ADD_STRING(TXT_ENG_IMAGE3,"image3")
RES_ADD_STRING(TXT_ENG_IMAGE4,"image4")
RES_ADD_STRING(TXT_ENG_IMAGE5,"image5")
RES_ADD_STRING(TXT_ENG_IMAGE6,"image6")
#ifdef SCREEN_SHAPE_CIRCULAR
RES_ADD_STRING(TXT_ENG_IMAGE7,"image7")
RES_ADD_STRING(TXT_ENG_IMAGE8,"image8")
#endif

RES_ADD_STRING(TXT_ENG_ADD_CONTACT,"Add Contact")
RES_ADD_STRING(TXT_ENG_CONTACT_EXIST,"Name exist")

RES_ADD_STRING(TXT_ENG_POWERRESET,"Power Reset")

//]]define string infomation


#ifdef ESIM_SUPPORT_HB
RES_ADD_STRING(TXT_ESIM_INFO,"eSIM Information")
#endif

#if defined TOUCH_PANEL_SUPPORT && !defined TOUCHPANEL_TYPE_MULTITP
RES_ADD_STRING(TXT_ENG_TOUCHSCREEN,"TP Test")
#endif
#if (defined (GPS_SUPPORT) && defined(MMI_ENG_WIFI_SUPPORT))
RES_ADD_STRING(TXT_ENG_GPS_OTA,"GPS OTA Test")  //fixe Bug 1322128 change display string
RES_ADD_STRING(TXT_ENG_GPS_SETUP_DATA_SOCKET,"Setup Socket")
RES_ADD_STRING(TXT_ENG_GPS_RELEASE_DATA_SOCKET,"Release Socket")
#endif
#if defined(GPS_SUPPORT) 
RES_ADD_STRING(TXT_ENG_GPS_TEST_MODULE,"GNSS Test")  //fixe Bug 1322128 change display string
RES_ADD_STRING(TXT_START_GPS_SHORT,"Start")
RES_ADD_STRING(TXT_STOP_GPS_SHORT,"Stop")
RES_ADD_STRING(TXT_START_GPS_FAIL,"Start GPS fail!")

//nmea log
RES_ADD_STRING(TXT_ENG_GPS_NMEA_LOG,"NMEA Log")
RES_ADD_STRING(TXT_ENG_GPS_NMEA_LOG_SAVE,"The NMEA log below is being saved:")
RES_ADD_STRING(TXT_ENG_GPS_NMEA_LOG_SAVE_BG,"Save in BG")
RES_ADD_STRING(TXT_ENG_GPS_NMEA_LOG_SAVE_T_CARD,"Save to Memory Card")
RES_ADD_STRING(TXT_ENG_GPS_NMEA_LOG_SAVE_PHONE,"Save to Phone Memory")
RES_ADD_STRING(TXT_ENG_GPS_NMEA_LOG_OUTPUT_DEFAULT,"Output default")
RES_ADD_STRING(TXT_NMEA_LOG_START,"start")
RES_ADD_STRING(TXT_NMEA_LOG_STOP,"stop")
RES_ADD_STRING(TXT_SATELLITES,"Tracking Test")
RES_ADD_STRING(TXT_RESTART,"Restart")
RES_ADD_STRING(TXT_ENG_SATALITE_INFO,"Location Information")
RES_ADD_STRING(TXT_GPS_REFRESH,"Refresh")

//circle test
RES_ADD_STRING(TXT_GPS_CIRCLE_TEST,"TTFF Test")
RES_ADD_STRING(TXT_CIRCLE_PARAM_SET,"Circle Param Set")
RES_ADD_STRING(TXT_START_MODE_SET,"Start Mode Set")
RES_ADD_STRING(TXT_GNSS_MODE_SET,"GNSS Mode Set")
RES_ADD_STRING(TXT_START_GPS,"Start Gps")
RES_ADD_STRING(TXT_STOP_GPS,"Stop Gps")
RES_ADD_STRING(TXT_SHOW_DETAIL_INFO,"Show Detail Info")
RES_ADD_STRING(TXT_PARAM_SET_IS_ERROR,"Param Error")
RES_ADD_STRING(TXT_CIRCLE_TEST_NOT_FINISH,"Circle test not finish")

//test win
RES_ADD_STRING(TXT_GPSTEST,"GPS Test")
RES_ADD_STRING(TXT_GPSTEST_PARAM_SETTING,"Lati&Longit Setting")
RES_ADD_STRING(TXT_LATITUDE_OPT,"Latitude:(option)")
RES_ADD_STRING(TXT_LONGTITUDE_OPT,"Longitude:(option)")
RES_ADD_STRING(TXT_GPS_ANGLE_ILLEGAL,"Please input a number between -360 and 360!")
RES_ADD_STRING(TXT_RESET_AFTER_GNSS_SET_QUERY,"Reset phone after GNSS mode set")
#endif
RES_ADD_STRING(TXT_ENG_LOGSET,"Log Set")
RES_ADD_STRING(TXT_ENG_LOGSWITCH,"Log Switch")
RES_ADD_STRING(TXT_ENG_LOGTOPC,"Log To PC")
RES_ADD_STRING(TXT_ENG_APLOG,"Ap Log")
RES_ADD_STRING(TXT_ENG_MODEMLOG,"Modem Log")
RES_ADD_STRING(TXT_ENG_WCNLOG,"WCN Log")
RES_ADD_STRING(TXT_ENG_GNSSLOG,"GNSS Log")
RES_ADD_STRING(TXT_ENG_LOGOUTPUT,"Log Output")
RES_ADD_STRING(TXT_ENG_LOGTOPHONE,"Log To SD")//bug1586263
RES_ADD_STRING(TXT_ENG_LOG_CLEAR_ALL,"Clear all logs")
RES_ADD_STRING(TXT_ENG_LOG_UART_LOG,"Uart Log")

RES_ADD_STRING(TXT_ENG_GPRS_TEST,"Gprs Test.")

RES_ADD_STRING(TXT_ENG_MEM_TESTER,"Mem Tester")
RES_ADD_STRING(TXT_ENG_MEM_TESTER_REPORT,"Mem Tester Report")
RES_ADD_STRING(TXT_ENG_MEMTEST_START,"Start")
RES_ADD_STRING(TXT_ENG_MEMTEST_STOP,"Stop")
RES_ADD_STRING(TXT_ENG_MEMTEST_REPORT,"Report")
RES_ADD_STRING(TXT_ENG_MEMTEST_VIDEO,"Video")
RES_ADD_STRING(TXT_ENG_MEMTEST_DURATION,"Test Duration(H)")
RES_ADD_STRING(TXT_ENG_MEMTEST_MIMSIZE,"Memory Size(M)")

RES_ADD_STRING(TXT_ENG_MEMTEST_DURATION_24H,"24")
RES_ADD_STRING(TXT_ENG_MEMTEST_DURATION_36H,"36")
RES_ADD_STRING(TXT_ENG_MEMTEST_DURATION_48H,"48")
RES_ADD_STRING(TXT_ENG_MEMTEST_DURATION_72H,"72")
RES_ADD_STRING(TXT_ENG_MEMTEST_DURATION_96H,"96")
RES_ADD_STRING(TXT_ENG_MEMTEST_DURATION_128H,"128")

RES_ADD_STRING(TXT_ENG_MEMTEST_MIMSIZE_1M,"1")
RES_ADD_STRING(TXT_ENG_MEMTEST_MIMSIZE_2M,"2")
RES_ADD_STRING(TXT_ENG_MEMTEST_MIMSIZE_3M,"3")
RES_ADD_STRING(TXT_ENG_MEMTEST_VIDEO_NAME,"memtest.mp4")

RES_ADD_STRING(TXT_ENG_MP3_PLAY_TEST,"MP3 PLAY Test")
RES_ADD_STRING(TXT_ENG_LIGHT_SLEEP_TEST,"Light Sleep Test")
RES_ADD_STRING(TXT_ENG_STK_TEST,"STK Test")


RES_ADD_STRING(TXT_ENG_BLE_CONNECTED_SUCC,"Connected success")
RES_ADD_STRING(TXT_ENG_BLE_CONNECTED_FAL,"Connected fail")
RES_ADD_STRING(TXT_ENG_BLE_DISCONNECTED_SUCC,"Disconnected success")
RES_ADD_STRING(TXT_ENG_BLE_DISCONNECTED_FAIL,"Disconnected fail")
RES_ADD_STRING(TXT_ENG_BLE_DATA_IND_SUCC,"Sync Data success")
RES_ADD_STRING(TXT_ENG_BLE_DATA_IND_FAIL,"Sync Data fail")

RES_ADD_STRING(TXT_ENG_REGISTER_PS_SERVICE,"Rgister PS Service")

RES_ADD_STRING(TXT_ENG_WCN_TIP_MSG,"Close BT&WIFI")

RES_ADD_STRING(TXT_ENG_MEMCHECK_TEST,"MemCheck Test")

RES_ADD_STRING(TXT_ENG_IMS_NV_PARAM_ID,"IMS NV PARAM ID")//[MS]


RES_ADD_STRING(TXT_ENG_FACTORYITEM_TEST,"Factory item Test")
RES_ADD_STRING(TXT_ENG_SETMODE_TEST,"Set boot mode")
RES_ADD_STRING(TXT_ENG_NORMAL_TEST,"Normal")
RES_ADD_STRING(TXT_ENG_GSMCALI_TEST,"GSMCAL")
RES_ADD_STRING(TXT_ENG_GSMFT_TEST,"GSMFT")
RES_ADD_STRING(TXT_ENG_WCDMACAL_TEST,"WCDMACAL")
RES_ADD_STRING(TXT_ENG_WCDMAFT_TEST,"WCDMAFT")
RES_ADD_STRING(TXT_ENG_TDSCAL_TEST,"TDSCAL")
RES_ADD_STRING(TXT_ENG_TDSFT_TEST,"TDSFT")
RES_ADD_STRING(TXT_ENG_LTECAL_TEST,"LTECAL")
RES_ADD_STRING(TXT_ENG_LTEFT_TEST,"LTEFT")
RES_ADD_STRING(TXT_ENG_NRCAL_TEST,"NRCAL")
RES_ADD_STRING(TXT_ENG_NRFT_TEST,"NRFT")
RES_ADD_STRING(TXT_ENG_NRMMWCAL_TEST,"NRMMWCAL")
RES_ADD_STRING(TXT_ENG_NRMMWFT_TEST,"NRMMWFT")
RES_ADD_STRING(TXT_ENG_C2KCAL_TEST,"C2KCAL")
RES_ADD_STRING(TXT_ENG_C2KFT_TEST,"C2KFT")
RES_ADD_STRING(TXT_ENG_BBAT_TEST,"BBAT")
RES_ADD_STRING(TXT_ENG_NATIVEMMI_TEST,"NATIVEMMI")
RES_ADD_STRING(TXT_ENG_APKMMI_TEST,"APKMMI")
RES_ADD_STRING(TXT_ENG_NBIOTCAL_TEST,"NBIOTCAL")
RES_ADD_STRING(TXT_ENG_NBIOTFT_TEST,"NBIOTFT")
RES_ADD_STRING(TXT_ENG_UPT_TEST,"UPT")

RES_ADD_STRING(TXT_ENG_SETWIFIPARAM_TEST,"Set WIFI param")
RES_ADD_STRING(TXT_ENG_SOCKETCONN_TEST,"Socket Connect")

RES_ADD_STRING(TXT_ENG_CALL_FORWARD_TEST,"Call forward Test")
RES_ADD_STRING(TXT_ENG_BBM_VIEW_TEST,"BBM Test")

RES_ADD_STRING(TXT_ENG_GPRS_POWER_SAVE_MODE_TITLE,"GPRS power save mode")

#ifdef TOUCH_PANEL_SUPPORT
RES_ADD_STRING(TXT_LIST_PRESS_TEST,"List press test")
RES_ADD_STRING(TXT_LIST_NEED_HIGHBAR_IF_CLICK,"Display highBar if click")
RES_ADD_STRING(TXT_LIST_SUPPORT_LEFT_SLIDE,"Display Left slide")
RES_ADD_STRING(TXT_LIST_TEST_TEXT_1,"List item text 1")
RES_ADD_STRING(TXT_LIST_TEST_TEXT_2,"List item text 2")
RES_ADD_STRING(TXT_LIST_CLICK_LEFT_ICON,"You click the left icon")
RES_ADD_STRING(TXT_LIST_CLICK_RIGHT_ICON,"You click the right icon")
#endif

#ifdef AUDIOPLAYER_DEMOAPP_SUPPORT
RES_ADD_STRING(TXT_ENG_AUDIOPLAYER,"AudioPlayer")
#endif
RES_ADD_STRING(TXT_ENG_AUTO_POWERONOFF,"Auto power on/off")

#ifdef GPS_SUPPORT
RES_ADD_STRING(TXT_ENG_HAVE_POSITIONED, "Have positioned")
RES_ADD_STRING(TXT_ENG_NO_POSITION, "No position")
RES_ADD_STRING(TXT_ENG_SATELLITE_NUM, "satellite num")
#endif
#ifdef MMI_RF_AM_SUPPORT
RES_ADD_STRING(TXT_ENG_RF_AM_TEST,"RF Arbitration Test")
RES_ADD_STRING(TXT_ENG_RF_AM_BACKGROUNG_POSITION_MODE,"Background position mode")
RES_ADD_STRING(TXT_ENG_RF_AM_SPORT_MODE,"Sport mode")
RES_ADD_STRING(TXT_ENG_RF_AM_COMMUNICATION_MODE,"Communication mode")
#endif

RES_ADD_STRING(TXT_ENG_SLEEP_ENABLE_PM2, "Enable PM2")
RES_ADD_STRING(TXT_ENG_SLEEP_ENABLE_PM1, "Enable PM1")
RES_ADD_STRING(TXT_ENG_SLEEP_ENABLE_PM0, "Enable PM0")
RES_ADD_STRING(TXT_ENG_NTC_TEST, "NTC Test")

#ifdef ENG_BAND_FREQ_SUPPORT
RES_ADD_STRING(TXT_ENG_BAND_FREQ_SET,"Lock Band & Frequency")
RES_ADD_STRING(TXT_ENG_SET_BAND,"Lock Band")
RES_ADD_STRING(TXT_ENG_SET_FREQ,"Lock Frequency")
RES_ADD_STRING(TXT_ENG_SET_LTE_FREQ,"Lock LTE Frequency")
RES_ADD_STRING(TXT_ENG_SET_GSM_FREQ,"Lock GSM Frequency")

RES_ADD_STRING(TXT_ENG_SET_LTE_BAND,"LTE Band")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND,"GSM Band")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_1,"1")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_2,"2")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_3,"3")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_4,"4")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_5,"5")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_7,"7")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_8,"8")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_12,"12")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_13,"13")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_17,"17")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_20,"20")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_28,"28")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_34,"34")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_38,"38")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_39,"39")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_40,"40")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_41,"41")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_66,"66")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND_1800,"1800")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND_1900,"1900")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND_850,"850")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND_900,"900")
RES_ADD_STRING(TXT_ENG_INVALID_FREQ,"Invalid Frequency")

#endif

//[[define data infomation
//]]define data infomation
