/*****************************************************************************
** File Name:      mmieng_id.h                                                *
** Author:                                                                   *
** Date:           2006/05/17                                                *
** Copyright:      2006 Spreadrum, Incorporated. All Rights Reserved.         *
** Description:    This file is used to describe eng win and control id    *
******************************************************************************
**                         Important Edit History                            *
** --------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                               *
** 2006/10/09     songbin.zeng      Create                                   *
******************************************************************************/

#ifndef _MMIENG_ID_H_
#define _MMIENG_ID_H_ 

/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
#include "sci_types.h"
#include "os_api.h"
#include "mmk_type.h"
#include "mmi_module.h"

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif

/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/


/**--------------------------------------------------------------------------*
 **                         TYPE AND CONSTANT                                *
 **--------------------------------------------------------------------------*/

#define WIN_ID_DEF(win_id)          win_id
// window ID
typedef enum
{
    MMIENG_WIN_ID_START = (MMI_MODULE_ENG << 16),

#include "mmieng_id.def"
    MMIENG_MAX_WIN_ID
}MMIENG_WINDOW_ID_E;

#undef WIN_ID_DEF

// control ID
typedef enum
{
    MMIENG_CTRL_ID_ID_START = MMIENG_MAX_WIN_ID, //(MMI_MODULE_ENG << 16),
    MMIENG_MAINMENU_CTRL_ID,
    MMIENG_FORM_CTRL_ID,
    MMIENG_FORM1_CTRL_ID,
    MMIENG_FORM2_CTRL_ID,
    MMIENG_UITEST_FORM1_CTRL_ID,
    MMIENG_UITEST_FORM2_CTRL_ID,
    MMIENG_UITEST_MENU_CTRL_ID,		//MS00193068
    MMIENG_UITEST_TEXT_CTRL_ID,
    MMIENG_UITEST_TEXTBOX_CTRL_ID,
    MMIENG_UITEST_LISTBOX_CTRL_ID,
    MMIENG_UITEST_EDITBOX_CTRL_ID,
    MMIENG_UITEST_LABEL_CTRL_ID,
    MMIENG_UITEST_LABEL1_CTRL_ID,
    MMIENG_UITEST_LABEL2_CTRL_ID,
    MMIENG_UITEST_LABEL3_CTRL_ID,
    MMIENG_UITEST_LABEL4_CTRL_ID,
    MMIENG_UITEST_LABEL5_CTRL_ID,
    MMIENG_TEXTBOX1_CTRL_ID,
    MMIENG_TEXTBOX2_CTRL_ID,
    MMIENG_TEXTBOX3_CTRL_ID,
    MMIENG_LABEL1_CTRL_ID,
    MMIENG_LABEL2_CTRL_ID,
    MMIENG_LABEL3_CTRL_ID,
    MMIENG_LABEL4_CTRL_ID,
    MMIENG_LABEL5_CTRL_ID,
    MMIENG_LABEL6_CTRL_ID,
    MMIENG_LABEL7_CTRL_ID,
    MMIENG_LABEL8_CTRL_ID,
    MMIENG_LABEL9_CTRL_ID,
    MMIENG_LABEL10_CTRL_ID,
    MMIENG_LABEL11_CTRL_ID,
    MMIENG_LABEL12_CTRL_ID,
    MMIENG_EDITBOX1_CTRL_ID,
    MMIENG_EDITBOX2_CTRL_ID,
    MMIENG_BT_NOSIGNAL_CTRL1_ID,
    MMIENG_BT_NOSIGNAL_CTRL2_ID,
    MMIENG_BT_NOSIGNAL_CTRL3_ID,
    MMIENG_BT_NOSIGNAL_CTRL4_ID,
    MMIENG_BT_NOSIGNAL_CTRL5_ID,
    MMIENG_BT_NOSIGNAL_CTRL6_ID,
    MMIENG_BT_NOSIGNAL_CTRL7_ID,
    MMIENG_BT_NOSIGNAL_CTRL8_ID,
    MMIENG_BT_NOSIGNAL_CTRL9_ID,
    MMIENG_BT_NOSIGNAL_CTRL10_ID,
    
    MMIENG_BT_NOSIGNAL_LABEL_CTRL1_ID,
    MMIENG_BT_NOSIGNAL_LABEL_CTRL2_ID,
    MMIENG_BT_NOSIGNAL_LABEL_CTRL3_ID,
    MMIENG_BT_NOSIGNAL_LABEL_CTRL4_ID,
    MMIENG_BT_NOSIGNAL_LABEL_CTRL5_ID,
    MMIENG_BT_NOSIGNAL_LABEL_CTRL6_ID,
    MMIENG_BT_NOSIGNAL_LABEL_CTRL7_ID,
    MMIENG_BT_NOSIGNAL_LABEL_CTRL8_ID,
    MMIENG_BT_NOSIGNAL_LABEL_CTRL9_ID,
    MMIENG_BT_NOSIGNAL_LABEL_CTRL10_ID,
    
    MMIENG_BT_NOSIGNAL_EDIT_CTRL1_ID,
    MMIENG_BT_NOSIGNAL_EDIT_CTRL2_ID,
    MMIENG_BT_NOSIGNAL_EDIT_CTRL3_ID,
    MMIENG_BT_NOSIGNAL_EDIT_CTRL4_ID,
    MMIENG_BT_NOSIGNAL_EDIT_CTRL5_ID,
    MMIENG_BT_NOSIGNAL_EDIT_CTRL6_ID,
    MMIENG_BT_NOSIGNAL_EDIT_CTRL7_ID,
    MMIENG_BT_NOSIGNAL_EDIT_CTRL8_ID,
    MMIENG_BT_NOSIGNAL_EDIT_CTRL9_ID,
    MMIENG_BT_NOSIGNAL_EDIT_CTRL10_ID,
    MMIENG_BT_NOSIGNAL_INFO_CTRL_ID,
    MMIENG_BT_NOSIGNAL_TESTCTRL_ID,
    
    MMIENG_FM_REG_MODE_FORM_CTRL_ID,
    MMIENG_FM_REG_MODE_PARAM_1_EDIT_CTRL_ID,
    MMIENG_FM_REG_MODE_LABEL_1_CTRL_ID,
    MMIENG_FM_REG_MODE_PARAM_2_EDIT_CTRL_ID,
    MMIENG_FM_REG_MODE_LABEL_2_CTRL_ID,
    MMIENG_FM_DATA_CAPTURE_FORM_CTRL_ID,
    MMIENG_FM_DATA_CAPTURE_LABEL_1_CTRL_ID,
    MMIENG_FM_DATA_CAPTURE_PARAM_1_EDIT_CTRL_ID,
    MMIENG_FM_DATA_CAPTURE_LABEL_2_CTRL_ID,
    MMIENG_FM_DATA_CAPTURE_PARAM_2_EDIT_CTRL_ID,

    MMIENG_COMMON_CTRL1_ID,
    MMIENG_COMMON_CTRL2_ID,
    MMIENG_COMMON_CTRL3_ID,
    MMIENG_COMMON_CTRL4_ID,
    MMIENG_COMMON_CTRL5_ID,
    MMIENG_COMMON_CTRL6_ID,
    MMIENG_COMMON_CTRL7_ID,
    MMIENG_COMMON_CTRL8_ID,
    MMIENG_COMMON_CTRL9_ID,
    MMIENG_COMMON_CTRL10_ID,
    MMIENG_COMMON_CTRL11_ID,

    MMIENG_COMMON_LIST_CTRL1_ID,
    MMIENG_COMMON_LABEL_CTRL1_ID,
    MMIENG_COMMON_LABEL_CTRL2_ID,
    MMIENG_COMMON_LABEL_CTRL3_ID,
    MMIENG_COMMON_LABEL_CTRL4_ID,
    MMIENG_COMMON_LABEL_CTRL5_ID,
    MMIENG_COMMON_LABEL_CTRL6_ID,
    MMIENG_COMMON_LABEL_CTRL7_ID,
    MMIENG_COMMON_LABEL_CTRL8_ID,
    MMIENG_COMMON_LABEL_CTRL9_ID,
    MMIENG_COMMON_LABEL_CTRL10_ID,
    MMIENG_COMMON_LABEL_CTRL11_ID,
    MMIENG_COMMON_LABEL_CTRL12_ID,
    MMIENG_COMMON_LABEL_CTRL13_ID,
    MMIENG_COMMON_LABEL_CTRL14_ID,
        
    MMIENG_COMMON_EDIT_CTRL1_ID,
    MMIENG_COMMON_EDIT_CTRL2_ID,
    MMIENG_COMMON_EDIT_CTRL3_ID,
    MMIENG_COMMON_EDIT_CTRL4_ID,
    MMIENG_COMMON_EDIT_CTRL5_ID,
    MMIENG_COMMON_EDIT_CTRL6_ID,
    MMIENG_COMMON_EDIT_CTRL7_ID,
    MMIENG_COMMON_EDIT_CTRL8_ID,
    MMIENG_COMMON_EDIT_CTRL9_ID,
    MMIENG_COMMON_EDIT_CTRL10_ID,
    MMIENG_COMMON_EDIT_CTRL11_ID,
    MMIENG_NET_INFO_SHOW_CTRL_ID,
    MMIENG_NETINFO_STATISTICS_CTRL_ID,
    MMIENG_VOLTE_LISTBOX_CTRL_ID,

#ifdef ENG_SUPPORT
    MMIENG_TESTSIM_CTRL_ID,
    MMIENG_PRGBOX_CTRL_ID,
    MMIENG_LISTBOX_CTRL_ID,
    MMIENG_MP3_LISTBOX_CTRL_ID,
    MMIENG_UAAGENT_CTRL_ID,
    MMIENG_UAPROFILE_CTRL_ID,
    MMIENG_WAPUA_CTRL_ID,
    MMIENG_BTADDRESS_CTRL_ID,
    MMIENG_WAPUAPROFILE_CTRL_ID,
    MMIENG_CHIP_TEST_MENU_CTRL_ID,
    MMIENG_CHIP_TEST_SETTING_CTRL_ID,
#endif
#ifdef CMMB_SUPPORT
    MMIENG_CMMB_TEST_MENU_CTRL_ID,
    MMIENG_CMMB_RD_TEST_MENU_CTRL_ID,
    MMIENG_CMMB_FACTORY_TEST_MENU_CTRL_ID,
    MMIENG_CMMB_FACTORY_HAVE_SIGNAL_MENU_CTRL_ID,
    MMIENG_CMMB_FACTORY_NO_SIGNAL_MENU_CTRL_ID,
#endif
    //MMIENG_MMS_SETNET_CTRL_ID,
#ifdef ENG_SUPPORT
    MMIENG_IQ_MODE_CTRL_ID,
    MMIENG_IQ_DATA_CTRL_ID,	
    MMIENG_IQ_DATA_MODE_SELECT_CTRL_ID,
    MMIENG_IQ_DATA_MODE_SETTING_CTRL_ID,
    MMIENG_IQ_DATA_MODE_SETTING_FORMAT_CTRL_ID,
    MMIENG_IQ_DATA_MODE_SETTING_TIME_LIMIT_CTRL_ID,
    MMIENG_IQ_DATA_MODE_SETTING_FRAME_LENGTH_CTRL_ID,
    MMIENG_IQ_DATA_MODE_SETTING_BLOCK_COUNT_CTRL_ID,
/*[START] Jerry Liang for IQ MODE 2008/08/01*/        
    MMIENG_IQ_DATA_MODE_SETTING_ARFCN_CTRL_ID,
/*[END] Jerry Liang for IQ MODE 2008/08/01*/            
    MMIENG_IQ_DATA_MODE_SETTING_CHANNEL_CTRL_ID,
#endif
    MMIENG_SHOW_VERSION_CTRL_ID,
    MMIENG_SHOW_SENSOR_VERSION_CTRL_ID,
    MMIENG_SHOW_WRE_VERSION_CTRL_ID,
    MMIENG_3RDPARTY_VERSION_CTRL_ID,
#ifdef PCLINK_SUPPORT
	MMIENG_PCLINK_ENABLE_CTRL_ID,
	MMIENG_PCLINK_INPUT_IPADDR_CTRL_ID,
	MMIENG_PCLINK_INPUT_SNMASK_CTRL_ID,
	MMIENG_PCLINK_INPUT_DEFGW_CTRL_ID,
	MMIENG_PCLINK_INPUT_DNS_CTRL_ID,
	MMIENG_PCLINK_INPUT_TEST_ADDRESS_CTRL_ID,
#endif
#ifdef CMMB_SUPPORT
	MMIENG_CMMB_TEXT_CTRL_ID,
    MMIENG_CMMB_SN_TEXT_CTRL_ID,
    MMIENG_CMMB_LABEL1_CTRL_ID,
    MMIENG_CMMB_LABEL2_CTRL_ID,
    MMIENG_CMMB_LABEL3_CTRL_ID,
    MMIENG_CMMB_LABEL4_CTRL_ID,
    MMIENG_CMMB_LABEL5_CTRL_ID,
    MMIENG_CMMB_LABEL6_CTRL_ID,
#endif
#ifdef ENG_SUPPORT
    MMIENG_GBA_ENABLE_TEST_CTRL_ID,
    MMIENG_LOG_ENABLE_CONTROL_CTRL_ID,
    MMIENG_MSK_ENABLE_TEST_CTRL_ID,
    MMIENG_GBA_AND_MSK_TEST_CTRL_ID,    
    MMIENG_SMD_COUNTER_ENABLE_CTRL_ID,
    MMIENG_AUDIO_SERVICE_ENABLE_CTRL_ID,
    MMIENG_UA_SELECT_LISTBOX_CTRL_ID,
    MMIENG_PROFILE_SELECT_LISTBOX_CTRL_ID,
    MMIENG_UA_SELECT_LIST_NUM_CTRL_ID,
    MMIENG_PROFILE_SELECT_LIST_NUM_CTRL_ID,

	MMIENG_NV_COUNTING_TEXTBOX_CTRL_ID,
    MMIENG_UA_SUB_MENU_CTRL_ID,
    MMIENG_OPTION_MENU_CTRL_ID,
#endif    
#ifdef MMI_ENG_WIFI_SUPPORT
    /*BEGIN WLAN */
    MMIENG_RADIO_FREQUENCY_FORM_CTRL_ID,
    MMIENG_WLAN_POWER_SAVE_SETLIST_CTRL_ID,
    MMIENG_WLAN_POWER_SAVE_FORM_CTRL_ID,
    MMIENG_WLAN_POWER_SAVE_LABEL_CTRL_ID,
    MMIENG_WLAN_ROAMING_SETLIST_CTRL_ID,
    MMIENG_WLAN_ROAMING_FORM_CTRL_ID,
    MMIENG_WLAN_ROAMING_LABEL_CTRL_ID,
    MMIENG_WIFI_TYPE_FORM_CTRL_ID,
    MMIENG_WIFI_ADDR_FORM_CTRL_ID,
    MMIENG_WIFI_VALUE_FORM_CTRL_ID,
    MMIENG_WIFI_LEN_FORM_CTRL_ID,
    MMIENG_WIFI_CNT_FORM_CTRL_ID,
    MMIENG_WIFI_LEVEL_FORM_CTRL_ID,
    MMIENG_WIFI_STANDARD_FORM_CTRL_ID,
    MMIENG_WIFI_CHANNEL_FROM_CTRL_ID,
      MMIENG_WIFI_CHANNEL_DROP_CTRL_ID,
    MMIENG_WIFI_RATE_FROM_CTRL_ID,
      MMIENG_WIFI_RATE_DROP_CTRL_ID,
    MMIENG_WIFI_PREAM_FROM_CTRL_ID,
      MMIENG_WIFI_PREAM_DROP_CTRL_ID,
    MMIENG_WIFI_MODE_FROM_CTRL_ID,
      MMIENG_WIFI_MODE_DROP_CTRL_ID,
    MMIENG_WIFI_GUARD_FROM_CTRL_ID,
      MMIENG_WIFI_GUARD_DROP_CTRL_ID,
    MMIENG_WIFI_TXNUM_FROM_CTRL_ID,
      MMIENG_WIFI_TXNUM_DROP_CTRL_ID,
   MMIENG_WIFI_NUM_FORM_CTRL_ID,
     MMIENG_WIFI_STANDARD_DROP_CTRL_ID,
   MMIENG_WIFI_CHANNEL_FORM_CTRL_ID,

   MMIENG_WIFI_RXOK_FORM_CTRL_ID,
   MMIENG_WIFI_PER_FORM_CTRL_ID,
  //iperf
   MMIENG_WIFI_IPERF_TYPE_FORM_CTRL_ID,
   MMIENG_WIFI_IPERF_TYPE_CTRL_ID,
   MMIENG_WIFI_IPERF_UP_FORM_CTRL_ID,
   MMIENG_WIFI_IPERF_IP_FORM_CTRL_ID,
   MMIENG_WIFI_IPERF_PORT_FORM_CTRL_ID,
   MMIENG_WIFI_IPERF_TIME_FORM_CTRL_ID,
   MMIENG_WIFI_IPERF_RESULT_FORM_CTRL_ID,
    /* END WLAN */
#endif

   MMIENG_AUTO_USB_PORT_CTRL_ID,
    
#ifdef MEDIA_DEMO_SUPPORT
    MMIENG_MEDIA_DEMO_CTRL_ID, 
    MMIENG_MEDIA_VIDEO_DEMO_CTRL_ID,
    MMIENG_MEDIA_AUDIO_DEMO_CTRL_ID, 
#endif
#ifdef ENG_SUPPORT
  MMIENG_VOICE_PARAM_SOFTKEY_CTRL_ID,
#ifdef MMI_PDA_SUPPORT
  MMIENG_SIDETONE_FORM_CTRL_ID,
  MMIENG_SIDETONE_SOFTKEY_CTRL_ID,
#endif
#endif
#ifdef TP_TEST_SUPPORT
  TP_GET_BUTTON_CTRL_ID,
  TP_SET_BUTTON_CTRL_ID,
  TP_TEST_BUTTON_CTRL_ID,
  TP_WIDTH_EDITBOX_CTRL_ID,
  TP_HEIGHT_EDITBOX_CTRL_ID,
  REFERENCE_RESISTOR_EDITBOX_CTRL_ID,
  REFERENCE_VOLTAGE_EDITBOX_CTRL_ID,
  DPOINT_XLIMIT_EDITBOX_CTRL_ID,
  DPOINT_YLIMIT_EDITBOX_CTRL_ID,
  SPOINT_RT_MAX_EDITBOX_CTRL_ID,
  SPOINT_RT_MIN_EDITBOX_CTRL_ID,
  DPOINT_RT_MAX_EDITBOX_CTRL_ID,
  DPOINT_RT_MIN_EDITBOX_CTRL_ID,
  DOUBLE_POINT_EDITBOX_CTRL_ID,
  RESERVED_EDITBOX_CTRL_ID,
#endif
    MMIENG_FORM_NAME_ID,
    MMIENG_FORM_ICON_ID,
    MMIENG_DROP_LIST_ICON_ID,
    MMIENG_FORM_PHONENUM_ID,

    MMIENG_GPRS_TEST_CTRL_ID,
    MMIENG_GPRS_TEST_OK_BUTTON,
    MMIENG_GPRS_TEST_BACK_BUTTON,

    MMIENG_MEM_TESTER_REPROT_ID,
    MMIENG_MEM_FORM_VIDEO_ID,
    MMIENG_MEM_DROPLIST_VIDEO_ID,
    MMIENG_MEM_FORM_PLAY_TIMES_ID,
    MMIENG_MEM_DROPLIST_PLAY_TIMES_ID,
    MMIENG_MEM_FORM_MEMSIZE_ID,
    MMIENG_MEM_DROPLIST_MEMSIZE_ID,
    MMIENG_MEM_FORM_OPERATE_ID,
    MMIENG_MEM_BUTTON_START_ID,
    MMIENG_MEM_BUTTON_STOP_ID,
    MMIENG_MEM_BUTTON_REPORT_ID,

    MMIENG_DROPDOWN_SET_MODE_ID,
    MMIENG_FACTORY_FORM1_CTRL_ID,
    MMIENG_FACTORY_FORM2_CTRL_ID,
    MMIENG_FACTORY_FORM3_CTRL_ID,
    MMIENG_FACTORY_FORM4_CTRL_ID,
    MMIENG_FACTORY_BUTTON_SET_ID,
    MMIENG_FACTORY_BUTTON_CLEAR_ID,
    MMIENG_FACTORY_BUTTON_CONN_ID,
    MMIENG_FLOWRATE_TEXT_CTRL_ID,

#if defined ENG_BAND_FREQ_SUPPORT
    MMIENG_BAND_LISTBOX_CTRL_ID,
    MMIENG_FREQ_LISTBOX_CTRL_ID,
    MMIENG_FREQ_EDIT_CTRL_ID,
    MMIENG_BAND_FREQ_CTRL_ID,
    MMIENG_SET_BAND_CTRL_ID,
#endif
    MMIENG_MAX_CTRL_ID
}MMIENG_CONTROL_ID_E;

/**--------------------------------------------------------------------------*
 **                         FUNCTION DEFINITION                              *
 **--------------------------------------------------------------------------*/
    /*****************************************************************************/
    //  Description : Register acc menu group
    //  Global resource dependence : none
    //  Author: haiyang.hu
    //  Note:
    /*****************************************************************************/
    PUBLIC void MMIENG_RegWinIdNameArr(void);


/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif

#endif
