

//[[define image infomation
#ifdef MMI_TVOUT_ENABLE
#ifdef JPG_DEC_SUPPORT_JPG_HW
RES_ADD_IMG(IMAGE_CONNECTION_TVOUT_BACKGROUND,"\\MMI_RES_##\\IMAG\\IMAGE_CONNECTION_TVOUT_BACKGROUND.jpg",IMG_CMP_JPG_SCI,0)
#else
RES_ADD_IMG(IMAGE_CONNECTION_TVOUT_BACKGROUND,"\\MMI_RES_##\\IMAG\\IMAGE_CONNECTION_TVOUT_BACKGROUND.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#endif
RES_ADD_IMG(IMAGE_CONNECTION_LINK_ITEM_RO,"\\MMI_RES_##\\IMAG\\IMAGE_CONNECTION_LINK_ITEM_RO.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_CONNECTION_LINK_ITEM_RW,"\\MMI_RES_##\\IMAG\\IMAGE_CONNECTION_LINK_ITEM_RW.bmp",IMG_CMP_BMP_16_565_RLE,0)


//]]define image infomation




//[[define anim infomation
//]]define anim infomation


//[[define string infomation
#if 1
//RES_ADD_STRING(TXT_CONNECTION_MANAGER,"Connection manager")       //replaced by common ID TXT_SETTINGS_LINK
#ifdef MMI_TVOUT_ENABLE
RES_ADD_STRING(TXT_CONNECTION_OPEN_TVOUT,"Open TV out")
RES_ADD_STRING(TXT_CONNECTION_TVOUT_SETTING,"TV out setting")
RES_ADD_STRING(TXT_CONNECTION_TVOUT_TITLE,"TV_Out")
#endif
#ifdef MMI_TVOUT_ENABLE
RES_ADD_STRING(TXT_CONNECTION_TVOUT_REMIND,"Press '#' key to quit")
#endif
//RES_ADD_STRING(TXT_CONNECTION_TVOUT_EXIT,"Exit")    //case3: defined but not used
#ifdef MMI_TVOUT_ENABLE
RES_ADD_STRING(TXT_CONNECTION_EXIT_TVOUT,"Exit TV out")
#endif
//RES_ADD_STRING(TXT_CONNECTION_USERID,"Internet Account")            //replaced by common ID TXT_COMMON_WWW_ACCOUNT 

RES_ADD_STRING(TXT_CONNECTION_CMCCWAP,"CMCC WAP")
RES_ADD_STRING(TXT_CONNECTION_CMCCWWW,"CMCC WWW")
RES_ADD_STRING(TXT_CONNECTION_CHINAMOBILEMMS,"CMCC MMS")
#ifdef CMCC_UI_STYLE
RES_ADD_STRING(TXT_CONNECTION_CMWAP,"CMWAP")
RES_ADD_STRING(TXT_CONNECTION_CMNET,"CMNET")
RES_ADD_STRING(TXT_CONNECTION_CMMMS,"CMMMS")
#endif
#if 1 //def DCD_SUPPORT
RES_ADD_STRING(TXT_CONNECTION_CMCCDCD,"CMCC DCD")
#endif
RES_ADD_STRING(TXT_CONNECTION_CUCC_WAP,"CUCC WAP")
RES_ADD_STRING(TXT_CONNECTION_CUCC_MMS,"CUCC MMS")
RES_ADD_STRING(TXT_CONNECTION_CUCC_NET,"CUCC NET")
//RES_ADD_STRING(TXT_CONNECTION_AIRTEL_WAP,"AIRTEL WAP")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_INA_AIRTEL_WAP,"INA_AIRTEL WAP")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_PL_IDEA_WAP,"PL_IDEA WAP")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_SPICE_WAP,"SPICE WAP")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_BSNL_WAP,"BSNL WAP")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_BSNL_MMS,"BSNL MMS")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_IDEA_MMS,"IDEA MMS")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_AIRTEL_MMS,"AIRTEL MMS")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_AIRCEL_WAP,"AIRCEL WAP")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_AIRCEL_MMS,"AIRCEL MMS")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_MTNL_WAP,"MTNL WAP")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_MTNL_MMS,"MTNL MMS")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_TMOBILE,"T-mobile")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_VODAFONE_IN_WAP,"VODAFONE WAP")    //case3: defined but not used
//RES_ADD_STRING(TXT_CONNECTION_VODAFONE_IN_MMS,"VODAFONE MMS")    //case3: defined but not used

//Indonesia
//RES_ADD_STRING(TXT_CONNECTION_XL_GPRS,"XL GPRS")
//RES_ADD_STRING(TXT_CONNECTION_XL_MMS,"XL MMS")
//RES_ADD_STRING(TXT_CONNECTION_INDOSAT_GPRS,"INDOSAT GPRS")
//RES_ADD_STRING(TXT_CONNECTION_INDOSAT_MMS,"INDOSAT MMS")
//RES_ADD_STRING(TXT_CONNECTION_3_GPRS,"3 GPRS")
//RES_ADD_STRING(TXT_CONNECTION_3_MMS,"3 MMS")
//RES_ADD_STRING(TXT_CONNECTION_AXIS_GPRS,"AXIS")
//RES_ADD_STRING(TXT_CONNECTION_AXIS_MMS,"AXIS MMS")
//RES_ADD_STRING(TXT_CONNECTION_TELKOMSEL_GPRS,"Telksomsel WAP")
//RES_ADD_STRING(TXT_CONNECTION_TELKOMSEL_MMS,"Telksomsel MMS")

RES_ADD_STRING(TXT_CONNECTION_LINKLIST,"Link")
//RES_ADD_STRING(TXT_CONNECTION_LINKSETTING,"Link setting")      //replaced by common ID TXT_COMMON_LINKSETTING
//RES_ADD_STRING(TXT_CONNECTION_SECURITYCONNECTSETTING,"Security connect setting")
//RES_ADD_STRING(TXT_CONNECTION_USERNAME,"User name")  //replaced by common ID TXT_COMMON_USERNAME
//RES_ADD_STRING(TXT_CONNECTION_PASSWORD,"Password")  //replaced by common ID TXT_COMMON_PASSWORD
RES_ADD_STRING(TXT_CONNECTION_APN,"Access point")
//RES_ADD_STRING(TXT_CONNECTION_GATEWAY,"Gateway")  //replaced by common ID TXT_COMMON_GATEWAY
RES_ADD_STRING(TXT_CONNECTION_PORT,"Port")
RES_ADD_STRING(TXT_CONNECTION_CHANGENAME,"Rename")
RES_ADD_STRING(TXT_CONNECTION_ACCOUNTNAME,"Account name")
//RES_ADD_STRING(TXT_CONNECTION_HOMEPAGE,"Homepage")  //replaced by common ID TXT_COMMON_HOMEPAGE
RES_ADD_STRING(TXT_CONNECTION_SETHOMEPAGE,"Set homepage")
RES_ADD_STRING(TXT_CONNECTION_DNS,"DNS Adress")
//RES_ADD_STRING(TXT_CONNECTION_NETTYPE,"Net type")    //replaced by common ID  TXT_NETEWORK_TYPE
RES_ADD_STRING(TXT_CONNECTION_NETTYPE_WAP,"WAP")
RES_ADD_STRING(TXT_CONNECTION_NETTYPE_HTTP,"HTTP")
RES_ADD_STRING(TXT_CONNECTION_LISTFULL,"List Full")
//RES_ADD_STRING(TXT_CONNECTION_INQUIREDELETE,"Delete?")    //replaced by common ID TXT_DELETE_QUERY
RES_ADD_STRING(TXT_CONNECTION_HAVENOITEM,"No suitable setting list founded")
//RES_ADD_STRING(TXT_CONNECTION_HAVEDELETE,"Deleted")    //replaced by common ID TXT_DELETED
//RES_ADD_STRING(TXT_CONNECTION_HAVEDONE,"Done")    //replaced by common ID TXT_COMPLETE 
//RES_ADD_STRING(TXT_CONNECTION_SETTING,"Settings")    //case3: defined but not used
RES_ADD_STRING(TXT_CONNECTION_SETTING1,"Account 1")
RES_ADD_STRING(TXT_CONNECTION_SETTING2,"Account 2")
RES_ADD_STRING(TXT_CONNECTION_SETTING3,"Account 3")
RES_ADD_STRING(TXT_CONNECTION_SETTING4,"Account 4")
RES_ADD_STRING(TXT_CONNECTION_SETTING5,"Account 5")
RES_ADD_STRING(TXT_CONNECTION_SETTING6,"Account 6")
RES_ADD_STRING(TXT_CONNECTION_SETTING7,"Account 7")
RES_ADD_STRING(TXT_CONNECTION_SETTING8,"Account 8")
RES_ADD_STRING(TXT_CONNECTION_SETTING9,"Account 9")
RES_ADD_STRING(TXT_CONNECTION_SETTING10,"Account 10")
RES_ADD_STRING(TXT_CONNECTION_SETTING11,"Account 11")
RES_ADD_STRING(TXT_CONNECTION_SETTING12,"Account 12")
RES_ADD_STRING(TXT_CONNECTION_SETTING13,"Account 13")
RES_ADD_STRING(TXT_CONNECTION_SETTING14,"Account 14")
RES_ADD_STRING(TXT_CONNECTION_SETTING15,"Account 15")
RES_ADD_STRING(TXT_CONNECTION_SETTING16,"Account 16")
RES_ADD_STRING(TXT_CONNECTION_SETTING17,"Account 17")
RES_ADD_STRING(TXT_CONNECTION_SETTING18,"Account 18")
RES_ADD_STRING(TXT_CONNECTION_SETTING19,"Account 19")
RES_ADD_STRING(TXT_CONNECTION_SETTING20,"Account 20")
//RES_ADD_STRING(TXT_CONNECTION_NO_ENOUGH_MEMORY,"No enough memory")  //replaced by common ID TXT_COMMON_NO_MEMORY
//RES_ADD_STRING(TXT_CONNECTION_EDIT,"Edit")  //replaced by common ID TXT_EDIT
//RES_ADD_STRING(TXT_CONNECTION_INQUIREEXIT,"Exit?")    //replaced by common ID TXT_EXIT_QUERY
//RES_ADD_STRING(TXT_CONNECTION_APNNULL,"Apn is null")    //case3: defined but not used
RES_ADD_STRING(TXT_CONNECTION_PORT_EMPTY,"port is empty!")
RES_ADD_STRING(TXT_CONNECTION_SETGBUILD,"Create new account")
RES_ADD_STRING(TXT_CONNECTION_ADDSETTINGLINK,"Add a new link setting")
//RES_ADD_STRING(TXT_CONNECTION_REASERCH,"Search ")  //replaced by common ID STXT_SEARCH
//RES_ADD_STRING(TXT_CONNECTION_SETDELETE,"Delete a settinglist")       //replaced by common ID TXT_DELETE
RES_ADD_STRING(TXT_CONNECTION_ADVANCE,"Advance Settings")
RES_ADD_STRING(TXT_CONNECTION_DELETE_FAIL,"Cannot detele, at least one network account!")
RES_ADD_STRING(TXT_CONNECTION_AUTH_TYPE,"Authentication type")
#ifdef IPVERSION_SUPPORT_V4_V6
RES_ADD_STRING(TXT_CONNECTION_IP_TYPE,"IP type")
#endif
//RES_ADD_STRING(CONNECTION_AUTH_NORMAL,"Normal")      //replaced by common ID TXT_COMMON_COMMON_NORMAL
//RES_ADD_STRING(TXT_CONNECTION_AUTH_SECURITY,"Security") //replaced by common ID TXT_COMM_SECURITY
#ifdef DATA_ACCOUNT_IN_TCARD_SUPPORT
RES_ADD_STRING(TXT_CONNECTION_DOWNLOAD_RES,"Download Network Account Resource")
RES_ADD_STRING(TXT_CONNECTION_REFRESH_ACCOUNT,"Update Network Account? ")
RES_ADD_STRING(TXT_CONNECTION_REPLACE_DATA_QUERY,"The original network account data will be replaced,continue? ")
#endif

//RES_ADD_STRING(TXT_CONNECTION_GPRS_SETTINGS,"GPRS settings")  //cr224619

RES_ADD_STRING(TXT_CONNECTION_GPRS_DETACH,"GPRS open when needed")
RES_ADD_STRING(TXT_CONNECTION_GPRS_ALWAYS,"GPRS always open")

RES_ADD_STRING(TXT_GPRS_SERVICE,"GPRS Service")

#ifdef WIFI_SUPPORT
//RES_ADD_STRING(TXT_CONNECTION_WIFI,"WiFi")  //replaced by common ID TXT_WIFI
#endif
#endif
//added by feng.xiao
#ifdef DATA_ROAMING_SUPPORT
RES_ADD_STRING(TXT_CONNECTION_DATA_ROAMING, "Data Roaming")
RES_ADD_STRING(TXT_CONNECTION_DATA_ROAMING_TIP, "Connect to data service when roaming")
RES_ADD_STRING(TXT_CONNECTION_DATA_ROAMING_QUERY, "Connection data roaming query")
RES_ADD_STRING(TXT_CONNECTION_DATA_ROAMING_CUTOFF_QUERY, "Connection data roaming cutoff query")
#endif

#ifdef MMI_GPRS_DATA_SIM_SET
RES_ADD_STRING(TXT_CONNECTION_GPRS_MODE_SETTING,"GPRS mode settings")
RES_ADD_STRING(TXT_CONNECTION_DATA_CARD,"Data card is")
RES_ADD_STRING(TXT_CONNECTION_DATA_CARD_SIM1,"Data card is SIM1")
RES_ADD_STRING(TXT_CONNECTION_DATA_CARD_SIM2,"Data card is SIM2")
RES_ADD_STRING(TXT_CONNECTION_DATA_CARD_SIM3,"Data card is SIM3")
RES_ADD_STRING(TXT_CONNECTION_DATA_CARD_SIM4,"Data card is SIM4")
RES_ADD_STRING(TXT_CONNECTION_DATA_PROMPT_ALWAYS,"Always prompted to select SIM")
#endif

//]]define string infomation


//[[define data infomation
//]]define data infomation
