
#define AAC_BACKGROUND_SUPPORT 
#define AAC_SEEK_SUPPORT 
#define AAC_SUPPORT 
#define ADD_TITLE_IN_ALL_SETTING_MENU 
#define AD_OUTPUT_ADP_SUPPORT 
#define AMR_A2DP_SUPPORT 
#define AMR_BACKGROUND_SUPPORT 
#define AMR_ENABLE 
#define AMR_SEEK_SUPPORT 
#define AMR_SUPPORT 
#define APP_COLUMNS 
#define APP_COLUMNS_3 
#define APP_ITEM_NAME 
#define AP_CP_RAM_SIZE 
#define AP_CP_RAM_SIZE_40X88 
#define ARM_AD_ADP_SUPPORT 
#define ARM_ARCH 
#define ARM_ARCH_V7 
#define ASSERT_LCD_IS_ROUND 
#define ASSERT_TYPE_SUPPORT 
#define ASSERT_TYPE_SUPPORT_ASSERT 
#define ATC_SUPPORT 
#define ATC_SUPPORT_COMPACT 
#define ATV_SUPPORT_NONE 
#define AT_CMD_OP_SUPPORT 
#define AUDDEV_RECORD_SUPPORT 
#define AUDIOPLAYER_DEMOAPP_SUPPORT 
#define AUDIO_CODEC_TYPE 
#define AUDIO_CODEC_TYPE_ES8311 
#define AUDIO_EXTPA_TYPE 
#define AUDIO_EXTPA_TYPE_GPIO 
#define AUDIO_PARAM_ARM 
#define AUDIO_RATE_SUPPORT 
#define AUDIO_STOP_RAMP 
#define AUD_ENCODE_FADE_INOUT 
#define AUTOTEST_DEVICE_SUPPORT 
#define AUTO_DOWNLOAD_SUPPORT 
#define AVI_DEC_SUPPORT 
#define BAIDU_DRIVE_SUPPORT 
#define BAIDU_STORE_U 
#define BATTERY_CHARGE_FULL_REMAIN 
#define BATTERY_CHARGE_FULL_REMAIN_TRUR 
#define BBM_ROLE_SUPPORT_NONE 
#define BB_DRAM_TYPE_NONE 
#define BLUETOOTH_SUPPORT_NONE 
#define BMP_DEC_SUPPORT 
#define BMP_DEC_SUPPORT_BMP_SW 
#define BT_ARM_NXP_ENABLE 
#define BT_BQB_SUPPORT 
#define BT_FIXPIN_SUPPORT 
#define BT_HCI_TRANS 
#define BT_HCI_TRANS_UART 
#define BT_NONSIG_SUPPORT 
#define BT_SCO_OVER 
#define BT_SCO_OVER_UART 
#define BYD_CUSTOM_FM_TUNNING_STEP 
#define BZP_NO_RESOURCE 
#define CALCULATOR_SUPPORT 
#define CAMERA_SENSOR_ANGLE 
#define CAMERA_SENSOR_ANGLE_0 
#define CAMERA_SUPPORT 
#define CAP_TP_SUPPORT 
#define CAP_TP_SUPPORT_BL6133 
#define CHATMODE_ONLY_SUPPORT 
#define CHGMNG_OTP_SUPPORT 
#define CHIP_DSP_NONE 
#define CHIP_ECO_SUPPORT 
#define CHIP_ENDIAN 
#define CHIP_ENDIAN_LITTLE 
#define CHIP_ENDIAN_DEFAULT 
#define CHIP_ENDIAN_DEFAULT_LITTLE 
#define CHIP_MARK_NONE 
#define CHIP_SUBVER 
#define CHIP_SUBVER_AB 
#define CHIP_VER 
#define CHIP_VER_UWS6121E 
#define COAP_SUPPORT 
#define COMPILER 
#define COMPILER_RVCT 
#define CONFIG_ANTIREG_LICENSE_SUPPORT 
#define CONFIG_NV_GEA3_SUPPORT 
#define CONFIG_NV_VOMAS_SUPPORT 
#define CPHS_SUPPORT 
#define CSS_SUPPORT 
#define CUSTOM_UNITCONVERSION_SUPPORT 
#define CVSRCD_ENABLE 
#define CVS_ENABLE 
#define DATA_ROAMING_SUPPORT 
#define DC_FLASH_SUPPORT 
#define DC_WATCH_UI_SUPPORT 
#define DEBUG_VERSION 
#define DELTA_NV_BIN_SUPPORT 
#define DELTA_NV_CONFIG_PATH 
#define DELTA_NV_CONFIG_PATH_UWS6121E_MODEM 
#define DELTA_NV_PATITION_SUPPORT 
#define DEMOD_HW_NONE 
#define DIAG_EX_SUPPORT 
#define DISPLAY_PIXELDEPTH_MAX 
#define DISPLAY_PIXELDEPTH_MAX_16 
#define DRM_SUPPORT 
#define DRM_SUPPORT_V1 
#define DSP_CTRL_PCM 
#define DSP_HW_COMPRESS 
#define DUAL_DSP_ADAPTION 
#define DV_UDISK_SUPPORT 
#define EFS_SPEED_UP 
#define ENG_BAND_FREQ_SUPPORT 
#define ENG_SUPPORT 
#define EQ_EXE_ON_CHIP 
#define EQ_HAS_MULTI_BANDS 
#define EXPRESS_PROCESS_IN_DSP 
#define FDN_SUPPORT 
#define FIH_DRV 
#define FIH_DRV_ZOUK 
#define FLASH_SIZE 
#define FLASH_SIZE_128MBIT 
#define FLASH_TYPE 
#define FLASH_TYPE_SPI 
#define FLV_DEC_SUPPORT 
#define FLYMODE_ECC_SUPPORT 
#define FM_SUPPORT_NONE 
#define FM_VBC 
#define FM_VBC_EQ 
#define FONT_HAN_SIMP_ONLY 
#define FONT_TYPE_SUPPORT 
#define FONT_TYPE_SUPPORT_VECTOR 
#define FOTA_BOOTLOADER_SUPPORT 
#define FOTA_SUPPORT 
#define FOTA_SUPPORT_CMIOT 
#define GIF_DEC_SUPPORT 
#define GIF_DEC_SUPPORT_GIF_SW 
#define GPRSMPDP_SUPPORT 
#define GPRS_SUPPORT 
#define GPS_AGPS_SUPPORT_NONE 
#define GPS_CHIP_VER_NONE 
#define GPS_MODE_NONE 
#define GPS_TRANS_VIA_NONE 
#define GUIF_PRGBOX_AUTOHIDE 
#define GZIP_DEC_SUPPORT 
#define GZIP_DEC_SUPPORT_GZIP_SW 
#define H264_DEC_SUPPORT 
#define HALFRATE_SUPPORT 
#define HAS_MODEM_NV 
#define HOME_LOCATION_INQUIRE_SUPPORT_NONE 
#define HTTP2_SUPPORT 
#define HTTP_SUPPORT 
#define HW_RF_DIFF 
#define ICO_DEC_SUPPORT_NONE 
#define IMEI_OTP_SUPPORT_NONE 
#define IM_ENGINE_NONE 
#define IM_HANDWRITING_NONE 
#define IM_SIMP_CHINESE_SUPPORT 
#define IM_SMART_TYPE_SUPPORT 
#define IM_UDB_SUPPORT 
#define IPVERSION_SUPPORT 
#define IPVERSION_SUPPORT_V4_V6 
#define JAVA_SUPPORT_NONE 
#define JAVA_SUPPORT_TYPE_NONE 
#define JPG_DEC_SUPPORT 
#define JPG_DEC_SUPPORT_JPG_SW 
#define JPG_DEC_TYPE_SUPPORT 
#define JPG_DEC_TYPE_SUPPORT_BASELINE_PROGRESSIVE 
#define JPG_ENC_SUPPORT 
#define JPG_ENC_SUPPORT_JPG_SW 
#define KEYPAD_TYPE 
#define KEYPAD_TYPE_TYPICAL_KEYPAD 
#define KING_MOVIE_SUPPORT_NONE 
#define LAUNCHER_ALL_APP_IN_PAGE 
#define LCD_DATA_WIDTH 
#define LCD_DATA_WIDTH_8BIT 
#define LCD_INSTALL_ANGLE 
#define LCD_INSTALL_ANGLE_0 
#define LCD_ROT_MODE_NONE 
#define LCD_SPI 
#define LCD_SPI_3WIRE_9BIT_2DATA 
#define LEBAO_MUSIC_SUPPORT 
#define LIBLWM2M_SUPPORT 
#define LOW_MEMORY_SUPPORT 
#define LOW_MEMORY_SUPPORT_32X32 
#define MAINLCD_DEV_SIZE 
#define MAINLCD_DEV_SIZE_240X240 
#define MAINLCD_DEV_SIZE_240X284 
#define MAINLCD_LOGIC_ANGLE 
#define MAINLCD_LOGIC_ANGLE_0 
#define MAINLCD_SIZE 
#define MAINLCD_SIZE_240X320 
#define MAINLCM_INTERFACE 
#define MAINLCM_INTERFACE_SPI 
#define MAINMENU_STYLE_DEFAULT_ROUND_CIRCULAR 
#define MAINMENU_STYLE_SUPPORT 
#define MAIN_LCD_DISPLAY_LAYER_NUM 
#define MAIN_LCD_DISPLAY_LAYER_NUM_1 
#define MBEDTLS_SUPPORT 
#define MBEDTLS_VERSION 
#define MBEDTLS_VERSION_V206 
#define MEMORY_DEBUG_SUPPORT 
#define MIC_SAMPLE_SUPPORT 
#define MIDI_A2DP_SUPPORT 
#define MIDI_BACKGROUND_SUPPORT 
#define MIDI_SEEK_SUPPORT

#define MIDI_SUPPORT 
#define MMIBT_HEADSET_AUTHORIZE 
#define MMIDORADO_BOOKMARK_BY_NV 
#define MMI_3DUI_SUPPORT 
#define MMI_COMMON_IDLE_SUPPORT 
#define MMI_DIR 
#define MMI_DIR_MS_MMI_Main 
#define MMI_FUNC_COMPATIBLE_SUPPORT 
#define MMI_GPRS_SWITCH_SUPPORT 
#define MMI_MSTYLE_SUPPORT 
#define MMI_MULTI_GREEN_KEY 
#define MMI_MULTI_GREEN_KEY_SINGLE 
#define MMI_MULTI_SIM_SYS 
#define MMI_MULTI_SIM_SYS_SINGLE 
#define MMI_NOT_SUPPORT_USSD_SS_INCC 
#define MMI_RES_ORIENT 
#define MMI_RES_ORIENT_PORTRAIT 
#define MMI_SMART_IDLE_SUPPORT_NONE 
#define MMI_VER 
#define MMI_VER_MAIN 
#define MMI_VOLTE_SUPPORT 
#define MMS_SMS_IN_1_SUPPORT 
#define MMS_SUPPORT_NONE 
#define MODEM_BIN_FILE 
#define MODEM_BIN_FILE_UWS6121E_MODEM 
#define MODEM_LOG 
#define MODEM_LOG_USB_ZERO_COPY 
#define MODEM_PROJECT_FOLDER 
#define MODEM_PROJECT_FOLDER_UWS6121_cat1bis_volte_nognss 
#define MODEM_SUPPORT 
#define MODEM_SUPPORT_RDA 
#define MOTION_SENSOR_TYPE 
#define MOTION_SENSOR_TYPE_QMA7981_DA215S 
#define MOTION_SENSOR_TYPE_OPTICAL_NONE 
#define MP3_BACKGROUND_SUPPORT 
#define MP3_SEEK_SUPPORT 
#define MP3_SUPPORT 
#define MQTT_SUPPORT 
#define MS_DEVICE_INFO_SUPPORT 
#define MULIT_VARIANT_SUPPORT 
#define MULTI_SIM_SYS 
#define MULTI_SIM_SYS_DUAL 
#define MULTI_SIM_SYS_QUAD_TO_NONE 
#define MV_SUPPORT_NONE 
#define NETFRONT_SUPPORT_NONE 
#define NEW_MEMORY_MM 
#define NOR_BOOTLOADER_SUPPORT 
#define NULL_CODEC_SUPPORT 
#define NV_PRTITION 
#define NV_PRTITION_NORMAL 
#define NXP_RECORD_SHARE_MEMORY 
#define OPERATOR_CUSTOM_NONE 
#define OPERA_MINI_SUPPORT_NONE 
#define OPERA_MOBILE_SUPPORT_NONE 
#define OPTION_MENU_SUPPORT 
#define OSC32K_CLOCK_SELECT 
#define OSC32K_CLOCK_SELECT_DCXO 
#define PBCCH_REMOVE_SUPPORT 
#define PB_SEARCH_SURPPORT_NONE 
#define PDA_UI_DROPDOWN_WIN 
#define PIC_VIEWER_SUPPORT 
#define PIC_ZOOM_SUPPORT 
#define PLATFORM 
#define PLATFORM_UWS6121E 
#define PNG_DEC_SUPPORT 
#define PNG_DEC_SUPPORT_PNG_SW 
#define PNG_ENC_SUPPORT_NONE 
#define POP_MDY_SUPPORT 
#define POWER_ONOFF_5G_STYLE 
#define PPP_USB 
#define PRELOAD_SUPPORT 
#define PRIMUSTEST_SUPPORT 
#define PRODUCT_CONFIG 
#define PRODUCT_CONFIG_uws6121e 
#define QQ_SUPPORT_NONE 
#define QWERTY_KEYPAD_NONE 
#define RECORD_SUPPORT 
#define REF_PCB_VER 
#define REF_PCB_VER_B2 
#define RELEASE_INFO 
#define RF_HW_SELFADAPTIVE_CONFIG_NV_DIR 
#define RF_HW_SELFADAPTIVE_CONFIG_NV_DIR_UWS6121E_MODEM 
#define RF_TYPE 
#define RF_TYPE_SR528 
#define ROTATE_2D_SUPPORT 
#define SBC_DSP_SUPPORT 
#define SBC_DSP_SUPPORT_VERSION1 
#define SCREEN_SHAPE 
#define SCREEN_SHAPE_CIRCULAR 
#define SETUP_WIZARD_SUPPORT 
#define SIM_LANGUAGE_SUPPORT 
#define SIM_PLUG_IN_SUPPORT_NONE 
#define SMART_DUAL_SIM_SUPPORT 
#define SMART_PAGING_SUPPORT 
#define SMSCB_MSG_ID_MAX_NUM_NONE 
#define SMS_CHAT_SUPPORT 
#define SNTP_SUPPORT 
#define SOS_KEYLONGWEB 
#define SOUNDBANK_MODE 
#define SOUNDBANK_MODE_FULL 
#define SOUNDBANK_VER 
#define SOUNDBANK_VER_ARM_256KB 
#define SPECIAL_EFFECT_ICON_SIZE 
#define SPECIAL_EFFECT_ICON_SIZE_48X48 
#define SPI_DATA2_SEL 
#define SPI_DATA2_SEL_DI 
#define SPRD_APP_RELEASE 
#define SPRD_CUSTOMER 
#define SRAM_SIZE 
#define SRAM_SIZE_128MBIT 
#define SSL_SUPPORT 
#define STONE_IMAGE_SUPPORT 
#define STOPWATCH_SUPPORT 
#define STRM_APP_CONFLICT 
#define SUBLCD_DEV_SIZE_NONE 
#define SUBLCD_LOGIC_ANGLE 
#define SUBLCD_LOGIC_ANGLE_0 
#define SUBLCD_SIZE_NONE 
#define SUBLCM_INTERFACE_NONE 
#define SUB_LCD_DISPLAY_LAYER_NUM 
#define SUB_LCD_DISPLAY_LAYER_NUM_0 
#define SYNCTOOL_SUPPORT 
#define TCPIP_SUPPORT 
#define TCXO_DCXO_AUTO_ADAPTATION_SUPPORT 
#define TORCH_SUPPORT 
#define TOUCHPANEL_TYPE 
#define TOUCHPANEL_TYPE_MULTITP 
#define TOUCH_PANEL_CTRL_SUPPORT 
#define TOUCH_PANEL_HWICON_SUPPORT_NONE 
#define TPC_TYPE_NONE 
#define TP_EXCHANGE_NONE 
#define TRACE_TYPE 
#define TRACE_TYPE_ID 
#define TRANS_SAM_SUPPORT 
#define TTS_SUPPORT_NONE 
#define TULING_AI_SUPPORT 
#define TYPE_3GP_SUPPORT_NONE 
#define UAL_AUDIOPLAYER_SUPPORT 
#define UAL_DEVICE_SUPPORT 
#define UAL_KV_SUPPORT 
#define UAL_RF_AM_SUPPORT 
#define UAL_SUPPORT 
#define UAL_TELE_SUPPORT 
#define UAL_WIFI_SUPPORT 
#define UDISK_PC_CONNECT 
#define UI_LAYER_SUPPORT_LOW_MEMORY 
#define UI_MULTILAYER_SUPPORT 
#define UI_P3D_SUPPORT 
#define UMEM_NEW_MECHNISM 
#define UMEM_PRTITION 
#define UMEM_PRTITION_LARGE 
#define UMEM_SUPPORT 
#define UNISOC_VERSION 
#define UPDATE_TIME_SUPPORT 
#define USB_ENTER_CALI_USE_ROM_API 
#define USB_MASS_STORAGE_SUPPORT 
#define USB_PROTOCOL_SUPPORT 
#define USB_PROTOCOL_SUPPORT_USB20 
#define USB_SUPPORT 
#define USB_VCOM_SUPPORT 
#define USE_LZMA_UZIP_BIN 
#define UZONE_SUPPORT_NONE 
#define VECTOR_FONT_SUPPORT 
#define VECTOR_FONT_SUPPORT_DEFAULT 
#define VECTOR_TABLE_ADDR 
#define VECTOR_TABLE_ADDR_HIGH 
#define VIDEO_CALL_AGORA_IN_CAMERA_SCREEN_INCOMMING_ERR 
#define VIDEO_CALL_AGORA_SUPPORT 
#define VIDEO_PLAYER_SUPPORT 
#define VM_SUPPORT 
#define VM_TABLE_CONFIG 
#define VM_TABLE_CONFIG_SMALL 
#define VOICE_PROCESS_NEW 
#define VOIP_SUPPORT 
#define VOLUME_LEVEL 
#define VOLUME_LEVEL_15 
#define W217_UWS6121EG_NOGNSS_PATCH_20231019 
#define W217_W18_DRV_CAMERA_GC6133 
#define W217_W18_DRV_LCD_7789P3_240X284 
#define W217_W18_DRV_TP_6133_SERIES 
#define W217_W18_VIDEO_CALL_AGORA_DIRECTION 
#define WATCH_PANEL_BEAR_DOLL_SUPPORT 
#define WATCH_PANEL_PENGUIN_SUPPORT 
#define WATCH_PANEL_SAILOR_MOON_SUPPORT 
#define WAV_A2DP_SUPPORT 
#define WAV_BACKGROUND_SUPPORT 
#define WAV_SEEK_SUPPORT 
#define WAV_SUPPORT 
#define WF_USE_SINGLELAYER 
#define WIFI_SUPPORT 
#define WIFI_SUPPORT_UNISOC_RX 
#define WIFI_VENDOR_NONE 
#define WORLD_CLOCK_SUPPORT 
#define XML_SUPPORT 
#define XO_MODE 
#define XO_MODE_DCXO 
#define XYSDK_SUPPORT 
#define YOUNGTONE_TTS_LIB 
#define YOUNGTONE_TTS_LIB_MAN 
#define ZDT_APP_SUPPORT

#define ZDT_BH_W9_FEATRUE

#define ZDT_HSENSOR_TYPE_NONE

#define ZDT_HTTP_APP_SUPPORT

#define ZDT_MAINMENU_ADD_CL_REMOVE_ALIPAY

#define ZDT_NET_SUPPORT

#define ZDT_NO_SIM_ICON_GIF

#define ZDT_PCBA_ZW201_SUPPORT

#define ZDT_PICLIST_SAVE_ONLY_NUM

#define ZDT_PLAT_YX_SUPPORT

#define ZDT_PLAT_YX_SUPPORT_FRIEND

#define ZDT_PLAT_YX_SUPPORT_SOS

#define ZDT_PLAT_YX_SUPPORT_VOICE

#define ZDT_PLAT_YX_SUPPORT_YS

#define ZDT_SMS_SUPPORT

#define ZDT_TCP_SUPPORT

#define ZDT_TOOLS_MENU_SUPPORT

#define ZDT_UNBIND_APP_CMD

#define ZDT_VIDEOCHAT_SUPPORT

#define ZDT_W18_COMMON_UI_POWERONOFF_RING

#define ZDT_W18_RESTORE_SET_DEFAULT

#define ZDT_W19_VER_CUSTOM

#define ZDT_W206_FACTORY_KEY_TEST

#define ZDT_W217_FACTORY_WIFI

#define ZDT_WATCH_UI_W217_STYLE_ONE

#define ZDT_WIFI_SUPPORT

#define ZDT_ZFB_SUPPORT

#define ZTE_MENU_SUPPORT

#define ZTE_STOPWATCH_SUPPORT

#define ZTE_SUPPORT

#define ZTE_SUPPORT_240X284

#define _SW_ZDT_PRODUCT_

#define GUILIST_PDASTYLE_SUPPORT

#define GUITAB_PDASTYLE_SUPPORT

#define GUITITLE_PDASTYLE_SUPPORT

#define GUIIM_PDASTYLE_SUPPORT

#define GUIICONLIST_PDASTYLE_SUPPORT

#define GUIPRGBOX_PDASTYLE_SUPPORT

#define GUISECMENU_PDASTYLE_SUPPORT

#define MMIPUBWIN_PDASTYLE_SUPPORT

#define GUIPOPMENU_POP_POP_SUPPORT

#define MMI_OPEN_CHANNEL_SUPPORT

#define MMI_SIM_NODIGITNUM_SUPPORT

#define USB_LOG

#define USB_VUART

#define BROWSER_GZIP_SUPPORT

#define KEY_RING_THROUGH_RECEIVER

#define TP_RING_THROUGH_RECEIVER

#define MMI_SMS_REPLY_PATH_SUPPORT

#define MMI_LDN_SUPPORT

#define MMI_NET_TYPE_SET_DEFAULT

#define MMI_CPHS_SUPPORT

#define MMI_CSP_SUPPORT

#define DRM_SUPPORT_V1

#define DRM_SUPPORT

#define MMI_DRM_SURPORT_FL_TYPE

#define MMI_DRM_SURPORT_CD_TYPE

#define MMI_DRM_SURPORT_SD_TYPE

#define MMI_UPDATE_TIME_SUPPORT

#define MMI_UPDATE_TIME_WHEN_STARTUP

#define MMI_SNTP_SUPPORT

#define MMI_SYNCTOOL_SUPPORT

#define IM_ENGLISH_SUPPORT

#define TOUCH_PANEL_SUPPORT

#define MMI_ASSERT_MODE

#define MMI_UDISK_MEM_ENABLE

#define MMI_DV_UDISK_ENABLE

#define PICVIEW_VIEW_ZOOM

#define PICVIEW_F_VIEW_ZOOM

#define MMI_NETWORK_NAME_SUPPORT

#define MMI_CRSS_SUPPORT

#define MMI_OPTIONMENU_SUPPORT

#define TOUCH_GESTURE_ENABLE

#define MMISRV_SUPPORT

#define MMISRV_AUDIO_SUPPORT

#define MMISRV_AUDIO_TEST_SUPPORT

#define MMI_RESET_PHONE_AUTO_PIN

#define MMISTRM_APP_CONFLICT

#define MMI_SIM_LANGUAGE_SUPPORT

#define MMI_CLEARCODE_33_29

#define BOCA_ROAMING_INDICATION

#define MMI_RF_AM_SUPPORT

#define MMI_FMM_SORT_API_EXT_SUPPORT

#define VIDEOTHUMBNAIL_SUPPORT

#define MMI_RECORD_SUPPORT

#define MMI_IM_PDA_SUPPORT

#define MMI_KEY_LOCK_EFFECT_SUPPORT

#define MMI_KEY_LOCK_EFFECT_TYPE1_SUPPORT

#define MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT

#define GUI_CTRL_SCROLL_KEY

#define SET_3D_STYLE_SUPPORT

#define MATRIX_MAIN_MENU_SUPPORT

#define MMI_AUDIO_PLAYER_SUPPORT

#define MMIAP_SUPPORT

#define CALL_TIMES_SUPPORT

#define MMI_SMS_CHAT_SUPPORT

#define MMISMS_CHATMODE_ONLY_SUPPORT

#define MMI_GPRS_SUPPORT

#define ACCOUNT_AUTO_ADAPT_SUPPORT

#define NET_ICON_UI_STYLE

#define MMISRVAP_SUPPORT

#define MMI_RES_SLIM_SUPPORT

#define MMI_LOW_MEMORY_RESOURCE

#define MMI_LOW_MEMORY_EBOOK

#define MMI_LOW_MEMORY_PIC_EDIT

#define MMI_LOW_MEMORY_RING

#define PB_SUPPORT_LOW_MEMORY

#define MMIPB_MAX_COUNT_200

#define MMI_BATTERY_PERCENT_IN_STATUSBAR

#define PB_SUPPORT_LOW_MEMORY

#define MMIPB_MAX_COUNT_100

#define MMI_PB_NAME_LEN_20_BYTES

#define SMS_SUPPORT_LOW_MEMORY

#define CALENDAR_SUPPORT_LOW_MEMORY

#define MMI_SMS_MAX_NUM_NV_50_ITEMS

#define MMI_ENG_WIFI_SUPPORT

#define TP_TEST_SUPPORT

#define MMI_R8_SUPPORT

#define GUIF_ANIM

#define GUIF_ANIM_ROTATE

#define GUIF_ANIM_ZOOM

#define GUIF_BUTTON

#define GUIF_DROPDOWNLIST

#define GUIF_EDITBOX

#define GUIF_FORM

#define GUIF_FORM_DOCKABLE

#define GUIF_ICONFOLDER

#define GUIF_ICONLIST

#define GUIF_ICONLIST_DELIMITER

#define GUIF_IM

#define GUIF_LABEL

#define GUIF_LIST

#define GUIF_MENU

#define GUIF_MSGBOX

#define GUIF_OWNDRAW

#define GUIF_PRGBOX

#define GUIF_RICHTEXT

#define GUIF_SCROLLKEY

#define GUIF_SETLIST

#define GUIF_SOFTKEY

#define GUIF_STATUSBAR

#define GUIF_STATUSBAR_SCROLL

#define GUIF_TAB

#define GUIF_TEXTBOX

#define GUIF_TIPS

#define GUIF_TITLE

#define GUIF_COMBOX

#define CAMERA_SENSOR_ANGLE_0

#define CAMERA_SCREEN_PORTRAIT

#define BURST_VOICE_EVERY

#define MMIDC_F_PDA_BIT_16

#define MMIDC_F_WORK_MODE

#define MMIDC_DESKTOP_ICON_BAR

#define CAMERA_FRAME_SUPPORT

#define MMIDC_F_FLASH

#define MMIDC_F_VIDEO_352X288

#define MMIDC_F_DV_ZOOM

#define MMIDC_F_DC_ZOOM

#define DC_WATCH_UI_SUPPORT

#define MMI_WIDGET_DIR_KEY_SUPPORT

#define MMIMMS_SMS_IN_1_SUPPORT

#define MMI_MESSAGE_CONTACT_NUM_MATCH_SUPPORT

#define MMISMS_CHATMODE_ONLY_SUPPORT

#define MAIN_MENU_48X48

#define MMIAP_F_RELEASE_BG_AUDIO
