//[[define image infomation
#ifdef GUIF_CLIPBOARD
RES_ADD_IMG(IMAGE_SLIDER_BLOCK,"\\MMI_RES_##\\IMAG\\IMAGE_SLIDER_BLOCK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SLIDER_LEFT_SEL,"\\MMI_RES_##\\IMAG\\IMAGE_SLIDER_LEFT_SEL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SLIDER_RIGHT_SEL,"\\MMI_RES_##\\IMAG\\IMAGE_SLIDER_RIGHT_SEL.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_CLIPBRD_BG,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_CLIPBRD_BG_RIGHT,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_BG_RIGHT.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_CLIPBRD_BG_MIDDLE,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_BG_MIDDLE.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_CLIPBRD_BG_LEFT,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_BG_LEFT.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)

RES_ADD_IMG(IMAGE_CLIPBRD_BG_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_BG_DOWN.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_CLIPBRD_BG_RIGHT_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_BG_RIGHT_DOWN.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_CLIPBRD_BG_MIDDLE_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_BG_MIDDLE_DOWN.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_CLIPBRD_BG_LEFT_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_BG_LEFT_DOWN.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)

#ifdef CLIPBRD_MAGNIFY_SUPPORT
RES_ADD_IMG(IMAGE_CLIPBRD_MAGNIFY_BG,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_MAGNIFY_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLIPBRD_MAGNIFY_MASK,"\\MMI_RES_##\\IMAG\\IMAGE_CLIPBRD_MAGNIFY_MASK.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
//]]define image infomation


//[[define anim infomation

//]]define anim infomation


//[[define string infomation
#if 1
//RES_ADD_STRING(TXT_CLIPBRDMENU_CUT,"Cut")     //replaced by common ID TXT_COMMON_CUT
//RES_ADD_STRING(TXT_CLIPBRDMENU_COPY,"Copy")       //replaced by common ID TXT_COMMON_COPY
RES_ADD_STRING(TXT_CLIPBRDMENU_PASTE,"Paste")
//RES_ADD_STRING(TXT_CLIPBRDMENU_SELECTALL,"Select All")     //replaced by common ID TXT_IKB_SELECT_ALL
RES_ADD_STRING(TXT_CLIPBRD_CONTENT_TOO_LARGE,"Content exceeds limit!")
#endif
//]]define string infomation


//[[define data infomation

//]]define data infomation
