
#ifdef MMI_REFACTOR_SAMPLE

RES_ADD_STRING(TXT_APPSAMPLE_FUNCWINLIST,"FuncWin Sample List")

RES_ADD_STRING(TXT_APPSAMPLE_FUNCWIN_MODEA,"FuncWin MODEA")
RES_ADD_STRING(TXT_APPSAMPLE_FUNCWIN_MODEB,"FuncWin MODEB")
RES_ADD_STRING(TXT_APPSAMPLE_FUNCWIN_MODEC,"FuncWin MODEC")

RES_ADD_STRING(TXT_APPSAMPLE_INPUT_A,"Input A")
RES_ADD_STRING(TXT_APPSAMPLE_INPUT_B,"Input B")
RES_ADD_STRING(TXT_APPSAMPLE_INPUT_C,"Input C")


RES_ADD_STRING(TXT_APPSAMPLE_PUBMENU,"PubMenu Sample")   
RES_ADD_STRING(TXT_APPSAMPLE_EVENT,"Event Sample")    
RES_ADD_STRING(TXT_APPSAMPLE_MAIN,"Sample APP MainWin")    



RES_ADD_STRING(TXT_APPSAMPLE_AGE,"Age")   
RES_ADD_STRING(TXT_APPSAMPLE_SEX,"Sex")
RES_ADD_STRING(TXT_APPSAMPLE_FILTER1,"1st of Age < 10,Sex=MALE")
RES_ADD_STRING(TXT_APPSAMPLE_FILTER2,"2nd of Age > 10,Sex=MALE")
RES_ADD_STRING(TXT_APPSAMPLE_FILTER3,"3rd of all")
RES_ADD_STRING(TXT_APPSAMPLE_ADDAGE,"age ++")
RES_ADD_STRING(TXT_APPSAMPLE_CHANGESEX,"change sex")

#endif
