
//RES_ADD_IMG(FM_PDA_BG,"\\MMI_RES_##\\IMAG\\FM_PDA_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(FM_PDA_ADJ_BUT,"\\MMI_RES_##\\IMAG\\FM_PDA_ADJ_BUT.png",IMG_CMP_PNG_ARGB_RLE,0)

//]]define image infomation
RES_ADD_IMG(IMAGE_QBTHEME_BTN_LEFT,"\\MMI_RES_##\\IMAG\\IMAGE_QBTHEME_BTN_LEFT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_QBTHEME_BTN_LEFT_ON,"\\MMI_RES_##\\IMAG\\IMAGE_QBTHEME_BTN_LEFT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_QBTHEME_BTN_LEFT_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_QBTHEME_BTN_LEFT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_QBTHEME_BTN_RIGHT,"\\MMI_RES_##\\IMAG\\IMAGE_QBTHEME_BTN_RIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_QBTHEME_BTN_RIGHT_ON,"\\MMI_RES_##\\IMAG\\IMAGE_QBTHEME_BTN_RIGHT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_QBTHEME_BTN_RIGHT_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_QBTHEME_BTN_RIGHT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_QBTHEME_MARK,"\\MMI_RES_##\\IMAG\\IMAGE_QBTHEME_MARK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_QBTHEME_BTN_RETURN,"\\MMI_RES_##\\IMAG\\IMAGE_QBTHEME_BTN_RETURN.png",IMG_CMP_PNG_ARGB_RLE,0)

//[[define anim infomation
//]]define anim infomation


//[[define string infomation
RES_ADD_STRING(TXT_QB_THEME_STYLES,"Theme styles")
RES_ADD_STRING(TXT_QB_CHANGE_THEMES,"Change themes")
RES_ADD_STRING(TXT_QB_CURRENT_THEME,"Current theme")
RES_ADD_STRING(TXT_QB_CHANGE_COMPONENTS,"Change theme components")
RES_ADD_STRING(TXT_QB_WALLPAPER,"Home screen wallpaper")
RES_ADD_STRING(TXT_QB_THEME_ICONS,"Icons")
RES_ADD_STRING(TXT_QB_THEME_BORDERS,"Borders")
RES_ADD_STRING(TXT_QB_THEME_FONTS,"Fonts")
RES_ADD_STRING(TXT_QB_THEME_APPLY,"Apply")
RES_ADD_STRING(TXT_QB_SHOW_ICONS,"Show icons")
RES_ADD_STRING(TXT_QB_HIDE_ICONS,"Hide icons")
RES_ADD_STRING(TXT_QB_LOCAL_THEMES,"Local themes")
RES_ADD_STRING(TXT_QB_LOCAL_IMAGES,"Local images")
RES_ADD_STRING(TXT_QB_LOCAL_ICONS,"Local icons")
RES_ADD_STRING(TXT_QB_LOCAL_FONTS,"Local fonts")
RES_ADD_STRING(TXT_QB_LOCAL_BORDERS,"Local borders")
RES_ADD_STRING(TXT_QB_TRANSPARENT,"Transparent")
RES_ADD_STRING(TXT_QB_DOWNLOADS, "Downloads")
RES_ADD_STRING(TXT_QB_SYSTEM_DEFAULT, "System Default")
RES_ADD_STRING(TXT_QB_THEME_DEFAULT, "Theme Default")
//RES_ADD_STRING(TXT_QB_CLASSIC, "Classic")          //replaced by common ID TXT_COMMON_CLASSIC
RES_ADD_STRING(TXT_QB_INSTALL_FAIL, "Install failed")
RES_ADD_STRING(TXT_QB_ALREADY_INSTALL, "Already install")
RES_ADD_STRING(TXT_QB_INSTRALL_SUCC, "Install successed.Apply right now")
RES_ADD_STRING(TXT_QB_LOCAL_THEME_PACK, "Local theme pack")
RES_ADD_STRING(TXT_QB_PACKAGE_ERROR, "Package error")
RES_ADD_STRING(TXT_QB_RESOLUTION_ERROR, "Resolution not match")
RES_ADD_STRING(TXT_QB_USING_NO_REMOVE, "Using Theme,no remove")
RES_ADD_STRING(TXT_QB_INSTALLING, "Installing...")
RES_ADD_STRING(TXT_QB_MORE_THEME, "More Theme")
RES_ADD_STRING(TXT_QB_RETURN_IDLE, "Home")
//RES_ADD_STRING(TXT_QB_ENTER_MAINMENU, "Mainmenu")  //replaced by common ID TXT_COMMON_MAINMENU
RES_ADD_STRING(TXT_QB_DEFAULT_IDLE, "Original System")
RES_ADD_STRING(TXT_QB_THEME_WALLPAPER, "QB wallpapers")
//RES_ADD_STRING(TXT_QB_CUSTOMIZE, "Customize")  //replaced by common ID TXT_EXPORT_LOC_CUSTOM
RES_ADD_STRING(TXT_QB_SWITCHING_THEME, "Switching theme...")

RES_ADD_STRING(TXT_QB_SWITCH_TO_OTHER, "Pls switch to other theme")

//]]define string infomation


//[[define data infomation
//]]define data infomation
