
RES_ADD_STRING(TXT_SETUP_WIZARD_DOWNLOAD_APP,"Download APP")
RES_ADD_STRING(TXT_SETUP_WIZARD_BIND_APP,"Bind APP")
RES_ADD_STRING(TXT_SETUP_WIZARD_NEXT,"Next")
RES_ADD_STRING(TXT_SETUP_WIZARD_BINDED,"Has bind")
RES_ADD_STRING(TXT_SETUP_WIZARD_NEXT_TIPS,"Next tips")
RES_ADD_STRING(TXT_SETUP_WIZARD_BIND_PAY_TIPS,"Bind pay")
RES_ADD_STRING(TXT_SETUP_WIZARD_OK,"OK")
RES_ADD_STRING(TXT_SETUP_WIZARD_NEXT_BIND_PAY,"Next")
RES_ADD_STRING(TXT_SETUP_WIZARD_INSERT_SIM,"≤Â»ÎSIMø®")

RES_ADD_IMG(SETUP_WIZARD_BG,"\\MMI_RES_##\\IMAG\\bg.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_STARTUP_CODE_BG,"\\MMI_RES_##\\IMAG\\start_up_code_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_STARTUP_INSERT_SIM,"\\MMI_RES_##\\IMAG\\start_up_insert_sim.png",IMG_CMP_PNG_ARGB_RLE,0)