#ifndef __EFUSE_H__
#define __EFUSE_H__
#define RDA_EFUSE_SECURITY_CFG_INDEX (22)
#define RDA_EFUSE_UNIQUE_ID_LOW_INDEX (24)
#define RDA_EFUSE_UNIQUE_ID_HIGH_INDEX (26)
#define RDA_SE_CFG_SECURITY_ENABLE_BIT0			(1<<4)
#define RDA_SE_CFG_SECURITY_ENABLE_BIT1			(1<<23)
#define RDA_SE_CFG_SECURITY_ENABLE_BIT2			(1<<25)

#endif /* __EFUSE_H__*/
