//[[define image infomation
#ifndef MMI_VIDEOPLAYER_MINI_FUNCTION
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_IMG(IMAGE_VP_NET_LIST_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_VP_NET_LIST_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_VP_DEFAULT_PIC,"\\MMI_RES_##\\IMAG\\IMAGE_VP_DEFAULT_PIC.png",IMG_CMP_PNG_ARGB_RLE,0)
#if !((defined MMI_VIDEO_PLAYER_MINI_SUPPORT)||(defined MMI_MINI_QVGA_UI_SUPPORT))
RES_ADD_IMG(IMAGE_VP_MY_VIDEO_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_VP_MY_VIDEO_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_VP_VIDEO_LIST_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_VP_VIDEO_LIST_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_VP_MY_VIDEO_FOCUS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_VP_MY_VIDEO_FOCUS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_VP_VIDEO_LIST_FOCUS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_VP_VIDEO_LIST_FOCUS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef MMI_PDA_SUPPORT
//istyle sub directory;
#if defined MMI_ISTYLE_SUPPORT
RES_ADD_IMG(ISTYLE_IMAGE_VP_MY_VIDEO_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_VP_MY_VIDEO_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_VP_VIDEO_LIST_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_VP_VIDEO_LIST_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_VP_MY_VIDEO_FOCUS_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_VP_MY_VIDEO_FOCUS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_VP_VIDEO_LIST_FOCUS_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_VP_VIDEO_LIST_FOCUS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//Optionsmenu_icon sub directory;
RES_ADD_IMG(IMAGE_VP_MENU_HISTORY_PLAY_LIST,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_VP_MENU_HISTORY_PLAY_LIST.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_VP_MENU_LOCAL_PLAY_LIST,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_VP_MENU_LOCAL_PLAY_LIST.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_VP_MENU_OPEN_LOCAL_LIST,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_VP_MENU_OPEN_LOCAL_LIST.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_IMG(IMAGE_VP_MENU_OPEN_NET,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_VP_MENU_OPEN_NET.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_VP_MENU_ADD_VIDEO,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_VP_MENU_ADD_VIDEO.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

RES_ADD_IMG(IMAGE_VP_PROCESSBAR_BG,"\\MMI_RES_##\\IMAG\\IMAGE_VP_PROCESSBAR_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_VP_TITLE_BAR,"\\MMI_RES_##\\IMAG\\IMAGE_VP_TITLE_BAR.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)

#ifndef MMI_VIDEO_PLAYER_MINI_LAYOUT
#if 1//def MMI_LOW_MEMORY_RESOURCE
RES_ADD_IMG(IMAGE_VP_BTN_BG,"\\MMI_RES_##\\IMAG\\IMAGE_VP_BTN_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
#else
RES_ADD_IMG(IMAGE_VP_BTN_BG,"\\MMI_RES_##\\IMAG\\IMAGE_VP_BTN_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#endif
#if 1
//RES_ADD_STRING(TXT_VP_LINK,"Link")  //replaced by common ID TXT_COMMON_CONNECT_COMN
//RES_ADD_STRING(TXT_VP_VIEW,"View")  //replaced by common ID TXT_VIEW
//RES_ADD_STRING(TXT_VP_SETTING,"Setting")         //replaced by common ID STXT_MAIN_SETTING
//RES_ADD_STRING(TXT_VP_OPEN,"Open") //replaced by common ID TXT_COMM_OPEN
//RES_ADD_STRING(TXT_VP_FLOWRATE,"Flowrate")        //replaced by common ID TXT_COMMON_FLOW_STATISTICS
RES_ADD_STRING(TXT_VP_LOCALFILE_VIEW,"Local File")
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_NET_VIEW,"Net File")
#endif
RES_ADD_STRING(TXT_VP_LOCALLIST,"Local List")
#if !defined (KEYPAD_TYPE_COMPACT_KEYPAD) &&! defined (KEYPAD_TYPE_FOUR_KEY_UNIVERSE)
RES_ADD_STRING(TXT_VP_HISTORYLIST,"HistoryList (1)")
#endif
RES_ADD_STRING(TXT_VP_BOOKMARK,"Bookmark (3)")

//RES_ADD_STRING(TXT_VP_SET_REPEAT_MODE,"Repeat Mode Setting")  //replaced by common ID TXT_COMMON_REPEAT
//RES_ADD_STRING(TXT_VP_SET_RANDOM_MODE,"Random Mode Setting")    //replaced by common ID TXT_SET_SHUFFLE
//RES_ADD_STRING(TXT_VP_SET_NET,"Net Setting")    //replaced by common ID  TXT_NETWORK_CONNECT_SET
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_SET_RTCP,"RTCP/RTP")
#endif
//RES_ADD_STRING(TXT_VP_SET_AGENT,"Agent")  //replaced by common TXT_COMM_PROXY
//RES_ADD_STRING(TXT_VP_SET_RESET,"Reset")      //replaced by common ID TXT_COMMON_SET_RESET
//RES_ADD_STRING(TXT_VP_SET_RANDOM_CLOSE,"Close")    //case3: defined but not used 
//RES_ADD_STRING(TXT_VP_SET_RANDOM_OPEN,"Open")    //case3: defined but not used 
//RES_ADD_STRING(TXT_VP_RESET_QUERY,"Is Reset?")    //replaced by common ID TXT_RESET_QUERY
//RES_ADD_STRING(TXT_VP_SET_REPEAT_CLOSE,"Close")    //case3: defined but not used 
//RES_ADD_STRING(TXT_VP_SET_REPEAT_ALL,"All Video Files")     //replaced by common ID TXT_COMMON_SET_REPEAT_ALL
//RES_ADD_STRING(TXT_VP_SET_REPEAT_ONE,"One Video File")  //replaced by common ID TXT_COMM_REPEAT_ONE
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_SET_RTCP_LOWEST_PORT,"RTCP/RTP Lowest Port")
RES_ADD_STRING(TXT_VP_SET_RTCP_HIGHEST_PORT,"RTCP/RTP Highest Port")
#endif
RES_ADD_STRING(TXT_VP_READY,"Initialing")
RES_ADD_STRING(TXT_VP_BUFFRING,"Buffering")
//RES_ADD_STRING(TXT_VP_PLAY_ERROR,"Play Error")  //replaced by common ID TXT_COMM_PLAY_ERROR
RES_ADD_STRING(TXT_VP_PAUSE_ERROR,"Pause Error")
//RES_ADD_STRING(TXT_VP_RESUME_ERROR,"Resume Error")    //case3: defined but not used 
//RES_ADD_STRING(TXT_VP_NOT_SUPPORT,"Not Support")                //replaced by common ID TXT_COMMON_NO_SUPPORT
RES_ADD_STRING(TXT_VP_INTERNAL_SERVER_ERROR,"Internal Server Error")
//RES_ADD_STRING(TXT_VP_BAD_REQUEST,"Bad Request")  //replaced by common ID TXT_COMM_BAD_REQUEST
//RES_ADD_STRING(TXT_VP_UNAUTHORIZED,"Unauthorized")    //replaced by common ID TXT_UNAUTHORIZED
//RES_ADD_STRING(TXT_VP_NOT_FOUND,"Not Fond")    //case3: defined but not used 
RES_ADD_STRING(TXT_VP_PDP_ACTIVE_ERROR,"PDP Active Error")
RES_ADD_STRING(TXT_VP_PDP_DEACTIVE_IND,"PDP Deactive")
RES_ADD_STRING(TXT_VP_SERVER_CLOSE_IND,"Server Close")
//RES_ADD_STRING(TXT_VP_STRM_INIT_ERROR,"Streaming Init Error")    //case3: defined but not used 
RES_ADD_STRING(TXT_VP_DATA_TIMEOUT,"Data Timeout")
//RES_ADD_STRING(TXT_VP_ERROR_OTHER,"Other Error")    //case3: defined but not used 
RES_ADD_STRING(TXT_VP_PAUSED,"Paused")
//RES_ADD_STRING(TXT_VP_SEEK_ERROR,"Seek Error")    //case3: defined but not used 
RES_ADD_STRING(TXT_VP_PLAY_END,"Play End")
RES_ADD_STRING(TXT_VP_STOPPED_BY_USER,"Stopped By User")
RES_ADD_STRING(TXT_VP_LOADING_ERROR,"Loading Error")
#if defined ( MMI_STREAMING_PLAYER_SUPPORT )|| defined ( MMI_VIDEOPLAYER_HISTORYLIST_SUPPORT )
RES_ADD_STRING(TXT_VP_IS_CONTINUE,"Is Continue")
#endif
RES_ADD_STRING(TXT_VP_STOPPING,"Stopping")
//RES_ADD_STRING(TXT_VP_STOP,"Stop")    //replaced by common ID  STXT_STOP
RES_ADD_STRING(TXT_VP_SEEKING,"Seeking")
RES_ADD_STRING(TXT_VP_RESUMING,"Resuming")
RES_ADD_STRING(TXT_VP_PAUSING,"Pausing")
RES_ADD_STRING(TXT_VP_FULLSCREEN,"Full Screen (2)")
//RES_ADD_STRING(TXT_VP_BRIGHTNESS,"Brightness Adjust (5)")    //replaced by common ID TXT_COMMON_COMMON_BRIGHTNESS(5)
RES_ADD_STRING(TXT_VP_SAVE_BOOKMARK,"Save Bookmark (8)")
//RES_ADD_STRING(TXT_VP_SETTING_AS,"Set As")       //replaced by common ID TXT_COMMON_SETTING_AS
RES_ADD_STRING(TXT_VP_FILEATTR,"Detail")
RES_ADD_STRING(TXT_VP_EXIT,"Exit")
//RES_ADD_STRING(TXT_VP_SCREENSAVE,"Screensaver")       //replaced by common ID TXT_COMMON_SCREENSAVE
//RES_ADD_STRING(TXT_VP_VIDEO_WALLPAPER,"Video wallpaper")    //replaced by common ID TXT_VIDEO_WALLPAPER
//RES_ADD_STRING(TXT_VP_POWER_ON_ANIMATION,"Power On Animation")        //replaced by common ID TXT_COMMON_POWER_ON_ANIMATION 
//RES_ADD_STRING(TXT_VP_POWER_OFF_ANIMATION,"Power Off Animation")      //replaced by common ID TXT_COMMON_POWER_OFF_ANIMATION
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_AUTH,"Authentication")
#endif
//RES_ADD_STRING(TXT_VP_USERNAME,"User Name:")  //replaced by common ID TXT_COMMON_USERNAME
//RES_ADD_STRING(TXT_VP_PASSWORD,"Password:")  //replaced by common ID TXT_COMMON_PASSWORD
//RES_ADD_STRING(TXT_VP_BOOKMARK_LIST,"Bookmark List")  //replaced by local common ID TXT_COMMON_FAVORITE
RES_ADD_STRING(TXT_VP_HISTORY_LIST,"History List")
#if !defined (KEYPAD_TYPE_COMPACT_KEYPAD) &&! defined (KEYPAD_TYPE_FOUR_KEY_UNIVERSE)
RES_ADD_STRING(TXT_VP_MUTE,"Mute (*)")
#endif
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_INPUT_NET_URL,"Input URL:")
#endif
//RES_ADD_STRING(TXT_VP_NET_URL,"URL:")  //replaced by common ID TXT_INPUT_URL_ADRESS
//RES_ADD_STRING(TXT_VP_DETAIL_PIXEL,"Pixel:")  //replaced by common ID TXT_COMM_RESOLUTION
//RES_ADD_STRING(TXT_VP_ADD,"Add")  //replaced by common ID STXT_ADD
RES_ADD_STRING(TXT_VP_TOO_MUCH,"Too Much")
//RES_ADD_STRING(TXT_VP_INVALID_URL,"Invalid URL")    //replaced by common ID TXT_INVALID_URL
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_UNDEFINE,"Undefine")
#endif
//RES_ADD_STRING(TXT_VP_MODIFY_BOOKMARK,"Modify")    //replaced by common ID TXT_MODIFY
RES_ADD_STRING(TXT_VP_UPDATE,"Update")
//RES_ADD_STRING(TXT_VP_MARK,"Mark") //replaced by common ID STXT_MARK
//RES_ADD_STRING(TXT_VP_CANCEL_MARK,"Cancel Mark")       //replaced by common ID TXT_CANCEL_MARK
//RES_ADD_STRING(TXT_VP_MARK_ALL,"Mark All")  //replaced by common ID TXT_MARK_ALL
//RES_ADD_STRING(TXT_VP_CANCEL_ALL_MARK,"Cancel All Mark")       //replaced by common ID TXT_CANCEL_MARK_ALL
//RES_ADD_STRING(TXT_VP_UPDATE_ERROR,"Update Error")  //replaced by common ID TXT_UPDATE_FAIL
RES_ADD_STRING(TXT_VP_INIT,"Initing")
//RES_ADD_STRING(TXT_VP_USING_AGENT,"Is Using Agent:")    //replaced by common ID TXT_PROXY_USE_QUERY
//RES_ADD_STRING(TXT_VP_YES,"Yes")    //replaced by common ID TXT_YES
//RES_ADD_STRING(TXT_VP_NO,"No")  //replaced by common ID TXT_COMM_NO
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_AGENT_IP,"Agent IP:")
RES_ADD_STRING(TXT_VP_AGENT_PORT,"Agent Port:")
RES_ADD_STRING(TXT_VP_AGENT_PORT_INVALID,"Invalid Proxy Port")
RES_ADD_STRING(TXT_VP_CMMC_URL,"CMMC URL:")
RES_ADD_STRING(TXT_VP_CMMC_URL_INFO,"CMMC URL INFO")//@andy.he  cr241051 20110627
#endif
//RES_ADD_STRING(TXT_VP_FILE_OPT,"Option")    //replaced by common ID STXT_OPTION
RES_ADD_STRING(TXT_VP_DEL_LOCALLIST,"Delete LocalList")
RES_ADD_STRING(TXT_VP_ADD_VIDEO,"Add Video")
//RES_ADD_STRING(TXT_VP_DETAIL_DATE,"Date:")  //replaced by common ID TXT_COMMON_DATE
//RES_ADD_STRING(TXT_VP_DETAIL_TIME,"Time:")  //replaced by common ID TXT_COMMON_TIME
//RES_ADD_STRING(TXT_VP_UPDATING,"Updating")  //replaced by common ID TXT_COMMON_UPDATING
//RES_ADD_STRING(TXT_VP_LOADING,"Loading")    //replaced by common ID TXT_LOADING
//#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_SAVE_BOOKMARK_TITLE,"Save Bookmark List")
//#endif
RES_ADD_STRING(TXT_VP_NO_FILE,"No File")
//RES_ADD_STRING(TXT_VP_NO_SPACE,"No Space")    //replaced by common ID TXT_NO_DISK_SPACE
#if !defined (KEYPAD_TYPE_COMPACT_KEYPAD) &&! defined (KEYPAD_TYPE_FOUR_KEY_UNIVERSE)
RES_ADD_STRING(TXT_VP_CANCEL_MUTE,"Cancel Mute (*)")
#endif
RES_ADD_STRING(TXT_VP_MY_VIDEO,"My Videos")
RES_ADD_STRING(TXT_VP_CUSTOMIZED_LIST,"Customized List")
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_LOWEST_PORT_INVAILD_NUMBER,"Invalid Lowest Port")
RES_ADD_STRING(TXT_VP_HIGHEST_PORT_INVAILD_NUMBER,"Invalid Highest Port")
#endif
//RES_ADD_STRING(TXT_VP_SET_NET_SIM1,"SIM1 Net Setting")   //replaced by common ID TXT_COMMON_SET_NET_SIM1
//RES_ADD_STRING(TXT_VP_SET_NET_SIM2,"SIM2 Net Setting")   //replaced by common ID TXT_COMMON_SET_NET_SIM2
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_VP_SET_NET_SIM3,"SIM3 Net Setting")   //replaced by common ID TXT_COMMON_SET_NET_SIM3
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_VP_SET_NET_SIM4,"SIM4 Net Setting")    //replaced by common ID TXT_COMMON_SET_NET_SIM4
#endif
RES_ADD_STRING(TXT_VP_BUSY,"Video Player Busy")
RES_ADD_STRING(TXT_VP_SAVE_BOOKMARK_SUCC,"Save Bookmark Successfully")
#ifdef MMI_VIDEO_PLAYER_MINI_LAYOUT//6530 MINI 界面布局 
RES_ADD_STRING(TXT_VP_VIDIO_NOT_SUPPORT_MINI,"Video Not Support")
#else
RES_ADD_STRING(TXT_VP_VIDIO_NOT_SUPPORT,"Video Not Support, Playing")
#endif
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_PORT_INVALID,"Invalid Port")
#endif
//RES_ADD_STRING(TXT_VP_ADDRESS_NOT_NULL,"Address is Null")  //replaced by common ID TXT_COMM_URL_NULL
RES_ADD_STRING(TXT_VP_HALFSCREEN,"Half Screen(2)")
RES_ADD_STRING(TXT_VP_CONNECT_TIMEOUT,"Connect Timeout")

//没有按键
#if defined (KEYPAD_TYPE_COMPACT_KEYPAD) || defined (KEYPAD_TYPE_FOUR_KEY_UNIVERSE)
RES_ADD_STRING(TXT_VP_HALFSCREEN_NO_KEY,"Half Screen")
#endif
//RES_ADD_STRING(TXT_VP_HISTORYLIST_NO_KEY,"HistoryList")     //replaced by common ID TXT_VP_HISTORY_LIST
//RES_ADD_STRING(TXT_VP_BOOKMARK_NO_KEY,"Bookmark")  //replaced by local common ID TXT_COMMON_FAVORITE
#if defined (KEYPAD_TYPE_COMPACT_KEYPAD) || defined (KEYPAD_TYPE_FOUR_KEY_UNIVERSE)
RES_ADD_STRING(TXT_VP_FULLSCREEN_NO_KEY,"Full Screen")
#endif
//RES_ADD_STRING(TXT_VP_BRIGHTNESS_NO_KEY,"Brightness Adjust")    //replaced by common ID TXT_BRIGHT_ADJUST
#if defined (KEYPAD_TYPE_COMPACT_KEYPAD) || defined (KEYPAD_TYPE_FOUR_KEY_UNIVERSE)
RES_ADD_STRING(TXT_VP_SAVE_BOOKMARK_NO_KEY,"Save Bookmark")
#endif
//RES_ADD_STRING(TXT_VP_CANCEL_MUTE_NO_KEY,"Cancel Mute")  //replaced by common ID TXT_TURNOFF_MUTE
//RES_ADD_STRING(TXT_VP_MUTE_NO_KEY,"Mute")  //replaced by common ID TXT_TURNON_MUTE
#ifdef MMI_VIDEOPLAYER_HELP_SUPPORT 
#ifdef MMI_STREAMING_PLAYER_SUPPORT
RES_ADD_STRING(TXT_VP_HELP_CONTENT_NO_KEY,"Help")
#endif
#ifndef MOTION_SENSOR_TYPE 
RES_ADD_STRING(TXT_VP_HELP_CONTENT,"Help")
#endif
//没有流媒体
RES_ADD_STRING(TXT_VP_HELP_CONTENT_1,"Help")

//#ifdef MOTION_SENSOR_TYPE
//带sensor
RES_ADD_STRING(TXT_VP_HELP_CONTENT_SENSOR,"Help")
//#endif

//#ifdef MOTION_SENSOR_TYPE 
//没有流媒体，带sensor
RES_ADD_STRING(TXT_VP_HELP_CONTENT_1_SENSOR,"Help")
//#endif

#ifndef MMI_STREAMING_PLAYER_SUPPORT
//没有流媒体，没有按键
RES_ADD_STRING(TXT_VP_HELP_CONTENT_NO_STREAMING_NO_KEY,"Help")
#endif
#endif

#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_VP_PDA_SCREENSAVE,"Set as Screensaver")  //设为屏保
RES_ADD_STRING(TXT_VP_PDA_VIDEO_WALLPAPER,"Set as video wallpaper")  //设为视频墙纸
RES_ADD_STRING(TXT_VP_PDA_POWER_ON_ANIMATION,"Set as Power On Animation")       //设为开机动画
RES_ADD_STRING(TXT_VP_PDA_POWER_OFF_ANIMATION,"Set as Power Off Animation")     //设为关机动画
#endif
#endif

RES_ADD_STRING(TXT_VP_SET_PLAY_METHOD,"Local Video Playback Mode")
RES_ADD_STRING(TXT_VP_AUDIO_VIDEO_SYN,"Audio Video Syn")
RES_ADD_STRING(TXT_VP_SCREEN_FLOW,"Screen Flow")
#else
RES_ADD_STRING(TXT_VP_DEL_LOCALLIST,"Delete LocalList")
RES_ADD_STRING(TXT_VP_ADD_VIDEO,"Add Video")
#endif
#ifdef MMI_VIDEO_PLAYER_MINI_SUPPORT //6530_MINI
RES_ADD_STRING(TXT_VP_HELP_LOW_MEMORY,"help")
#endif

RES_ADD_STRING(TXT_VP_SINGLE,"Single")
RES_ADD_STRING(TXT_VP_INSTANCE_WATING,"One instance exist,Please wating")

