/******************************************************************************
** File Name:      mmiwww_position.h                                          *
** Author:                                                                    *
** Date:           06/15/2009                                                 *
** Copyright:      2009 Spreadtrum, Incorporated. All Rights Reserved.        *
** Description:    This file is used to describe punctuation for WWW app      *
*******************************************************************************
**                         Important Edit History                             *
** -------------------------------------------------------------------------- *
** DATE           NAME             DESCRIPTION                                *
** 06/2009        wancan.you        Create                                    *
******************************************************************************/
#ifndef _MMIWWW_POSITION_H_
#define _MMIWWW_POSITION_H_

// 通用定义

#if defined (MAINLCD_SIZE_176X220) || defined (MAINLCD_SIZE_128X160)
#define MMIWWW_MARGIN_HORIZONLTAL       (3)
#define MMIWWW_MARGIN_VERTICAL          (2)
#define MMIWWW_LABEL_HEIGHT         (20)
#define MMIWWW_BUTTON_HEIGHT        (20)
#define MMIWWW_BUTTON_WIDTH         (25)
#define MMIWWW_TAB_HEIGHT           (18)
#define MMIWWW_TAB_DISTANCE           (10)
#define MMIWWW_LABEL_WIDTH              (MMI_MAINSCREEN_WIDTH - MMIWWW_BUTTON_WIDTH - MMIWWW_MARGIN_HORIZONLTAL * 3)
#define MMIWWW_LABEL_WIDTH_H            (MMI_MAINSCREEN_HEIGHT - MMIWWW_BUTTON_WIDTH - MMIWWW_MARGIN_HORIZONLTAL * 3)

#define MMIWWW_ADDRESSBAR_LEFT      MMIWWW_MARGIN_HORIZONLTAL
#define MMIWWW_ADDRESSBAR_TOP       (MMI_TITLE_HEIGHT + MMI_STATUSBAR_HEIGHT + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_ADDRESSBAR_TOP_H       (MMI_TITLE_THEME_HEIGHT_H + MMI_STATUSBAR_HEIGHT + 4)
#define MMIWWW_ADDRESSBAR_RIGHT     (MMIWWW_ADDRESSBAR_LEFT + MMIWWW_LABEL_WIDTH - 1)
#define MMIWWW_ADDRESSBAR_RIGHT_H   (MMIWWW_ADDRESSBAR_LEFT + MMIWWW_LABEL_WIDTH_H - 1)
#define MMIWWW_ADDRESSBAR_BOTTOM    (MMIWWW_ADDRESSBAR_TOP + MMIWWW_LABEL_HEIGHT - 1)
#define MMIWWW_ADDRESSBAR_BOTTOM_H  (MMIWWW_ADDRESSBAR_TOP_H + MMIWWW_LABEL_HEIGHT - 1)

#define MMIWWW_LINK_IMAGE_LEFT     (MMIWWW_ADDRESSBAR_RIGHT + MMIWWW_MARGIN_HORIZONLTAL)
#define MMIWWW_LINK_IMAGE_LEFT_H   (MMIWWW_ADDRESSBAR_RIGHT_H + MMIWWW_MARGIN_HORIZONLTAL)
#define MMIWWW_LINK_IMAGE_TOP      (MMIWWW_ADDRESSBAR_TOP)
#define MMIWWW_LINK_IMAGE_TOP_H    (MMIWWW_ADDRESSBAR_TOP_H)
#define MMIWWW_LINK_IMAGE_RIGHT    (MMIWWW_LINK_IMAGE_LEFT + MMIWWW_BUTTON_WIDTH - 1)
#define MMIWWW_LINK_IMAGE_RIGHT_H  (MMIWWW_LINK_IMAGE_LEFT_H + MMIWWW_BUTTON_WIDTH - 1)
#define MMIWWW_LINK_IMAGE_BOTTOM   (MMIWWW_LINK_IMAGE_TOP + MMIWWW_BUTTON_HEIGHT - 1)
#define MMIWWW_LINK_IMAGE_BOTTOM_H   (MMIWWW_LINK_IMAGE_TOP_H + MMIWWW_BUTTON_HEIGHT - 1)

#define MMIWWW_SEARCHBAR_LEFT       (MMIWWW_ADDRESSBAR_LEFT)
#define MMIWWW_SEARCHSBAR_TOP       (MMIWWW_ADDRESSBAR_BOTTOM + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_SEARCHSBAR_TOP_H       (MMIWWW_ADDRESSBAR_BOTTOM_H + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_SEARCHSBAR_RIGHT     (MMIWWW_ADDRESSBAR_RIGHT)
#define MMIWWW_SEARCHSBAR_RIGHT_H   MMIWWW_ADDRESSBAR_RIGHT_H
#define MMIWWW_SEARCHSBAR_BOTTOM    (MMIWWW_SEARCHSBAR_TOP + MMIWWW_LABEL_HEIGHT - 1)
#define MMIWWW_SEARCHSBAR_BOTTOM_H  (MMIWWW_SEARCHSBAR_TOP_H + MMIWWW_LABEL_HEIGHT - 1)

#define MMIWWW_SEARCH_IMAGE_LEFT    (MMIWWW_LINK_IMAGE_LEFT)
#define MMIWWW_SEARCH_IMAGE_LEFT_H    (MMIWWW_LINK_IMAGE_LEFT_H)
#define MMIWWW_SEARCH_IMAGE_TOP     MMIWWW_SEARCHSBAR_TOP
#define MMIWWW_SEARCH_IMAGE_TOP_H   MMIWWW_SEARCHSBAR_TOP_H
#define MMIWWW_SEARCH_IMAGE_RIGHT   (MMIWWW_LINK_IMAGE_RIGHT)
#define MMIWWW_SEARCH_IMAGE_RIGHT_H   (MMIWWW_LINK_IMAGE_RIGHT_H)
#define MMIWWW_SEARCH_IMAGE_BOTTOM  (MMIWWW_SEARCH_IMAGE_TOP + MMIWWW_BUTTON_HEIGHT - 1)
#define MMIWWW_SEARCH_IMAGE_BOTTOM_H  (MMIWWW_SEARCH_IMAGE_TOP_H + MMIWWW_BUTTON_HEIGHT - 1)

#define MMIWWW_TAB_LEFT             (0)
#define MMIWWW_TAB_TOP              (MMIWWW_SEARCHSBAR_BOTTOM + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_TAB_TOP_H            (MMIWWW_SEARCHSBAR_BOTTOM_H + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_TAB_RIGHT            (MMI_MAINSCREEN_WIDTH - 1)
#define MMIWWW_TAB_RIGHT_H          (MMI_MAINSCREEN_HEIGHT - 1)
#define MMIWWW_TAB_BOTTOM           (MMIWWW_TAB_TOP + MMIWWW_TAB_HEIGHT - 1)
#define MMIWWW_TAB_BOTTOM_H         (MMIWWW_TAB_TOP_H + MMIWWW_TAB_HEIGHT - 1)

#define MMIWWW_TAB_LIST_LEFT        (0)
#define MMIWWW_TAB_LIST_TOP         (MMIWWW_TAB_BOTTOM + 1)
#define MMIWWW_TAB_LIST_TOP_H       (MMIWWW_TAB_BOTTOM_H + 1)
#define MMIWWW_TAB_LIST_RIGHT       (MMI_MAINSCREEN_WIDTH - 1)
#define MMIWWW_TAB_LIST_RIGHT_H     (MMI_MAINSCREEN_HEIGHT - 1)
#define MMIWWW_TAB_LIST_BOTTOM      (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - 1)
#define MMIWWW_TAB_LIST_BOTTOM_H    (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - 1)


// 网页窗口四个硬图标的位置信息
#define MMIWWW_PAGE_BUTTON_HEIGHT   20
#define MMIWWW_PAGE_BUTTON_WIDTH   44

#define MMIWWW_PAGE_OPTION_LEFT     0
#define MMIWWW_PAGE_OPTION_LEFT_H   MMIWWW_PAGE_OPTION_LEFT
#define MMIWWW_PAGE_OPTION_TOP      200
#define MMIWWW_PAGE_OPTION_TOP_H    MMIWWW_PAGE_OPTION_TOP
#define MMIWWW_PAGE_OPTION_RIGHT    (MMIWWW_PAGE_BUTTON_WIDTH - 1)
#define MMIWWW_PAGE_OPTION_RIGHT_H  MMIWWW_PAGE_OPTION_RIGHT
#define MMIWWW_PAGE_OPTION_BOTTOM   (MMIWWW_PAGE_OPTION_TOP + MMIWWW_PAGE_BUTTON_HEIGHT - 1)
#define MMIWWW_PAGE_OPTION_BOTTOM_H MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_RELOAD_LEFT     (MMIWWW_PAGE_OPTION_RIGHT + 1)
#define MMIWWW_PAGE_RELOAD_LEFT_H   MMIWWW_PAGE_RELOAD_LEFT
#define MMIWWW_PAGE_RELOAD_TOP      MMIWWW_PAGE_OPTION_TOP
#define MMIWWW_PAGE_RELOAD_RIGHT    (MMIWWW_PAGE_RELOAD_LEFT + MMIWWW_PAGE_BUTTON_WIDTH - 1)
#define MMIWWW_PAGE_RELOAD_RIGHT_H    MMIWWW_PAGE_RELOAD_RIGHT
#define MMIWWW_PAGE_RELOAD_BOTTOM   MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_FULL_LEFT       (MMIWWW_PAGE_RELOAD_RIGHT + 1)
#define MMIWWW_PAGE_FULL_LEFT_H     MMIWWW_PAGE_FULL_LEFT
#define MMIWWW_PAGE_FULL_TOP        MMIWWW_PAGE_OPTION_TOP
#define MMIWWW_PAGE_FULL_RIGHT      (MMIWWW_PAGE_FULL_LEFT + MMIWWW_PAGE_BUTTON_WIDTH - 1)
#define MMIWWW_PAGE_FULL_RIGHT_H    MMIWWW_PAGE_FULL_RIGHT
#define MMIWWW_PAGE_FULL_BOTTOM     MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_PREV_LEFT       (MMIWWW_PAGE_FULL_RIGHT + 1)
#define MMIWWW_PAGE_PREV_LEFT_H     MMIWWW_PAGE_PREV_LEFT
#define MMIWWW_PAGE_PREV_TOP        MMIWWW_PAGE_OPTION_TOP
#define MMIWWW_PAGE_PREV_RIGHT      (MMIWWW_PAGE_PREV_LEFT + MMIWWW_PAGE_BUTTON_WIDTH - 1)
#define MMIWWW_PAGE_PREV_RIGHT_H    MMIWWW_PAGE_PREV_RIGHT
#define MMIWWW_PAGE_PREV_BOTTOM     MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_TITLE_HEIGHT 28

//页面加载进度的动画相关
#define MMIWWW_LOAD_ANIM_WIDTH      24
#define MMIWWW_LOAD_ANIM_HEIGHT     24
#define MMIWWW_LOAD_ANIM_LEFT       6
#define MMIWWW_LOAD_ANIM_TOP        (MMI_STATUSBAR_HEIGHT + 2)
#define MMIWWW_LOAD_ANIM_RIGHT      (MMIWWW_LOAD_ANIM_LEFT + MMIWWW_LOAD_ANIM_WIDTH - 1)
#define MMIWWW_LOAD_ANIM_BOTTOM     (MMIWWW_LOAD_ANIM_TOP + MMIWWW_LOAD_ANIM_HEIGHT - 1)
//页面标题label
#define MMIWWW_LOAD_LABEL_WIDTH 70
#define MMIWWW_CONTROL_MARGIN     5 
#define MMIWWW_LOAD_LABEL_LEFT      (MMIWWW_LOAD_ANIM_RIGHT + MMIWWW_CONTROL_MARGIN)
#define MMIWWW_LOAD_LABEL_TOP       (MMIWWW_LOAD_ANIM_TOP + 2)
#define MMIWWW_LOAD_LABEL_RIGHT     (MMIWWW_LOAD_LABEL_LEFT + MMIWWW_LOAD_LABEL_WIDTH - 1)
#define MMIWWW_LOAD_LABEL_RIGHT_H   MMIWWW_LOAD_LABEL_RIGHT
#define MMIWWW_LOAD_LABEL_BOTTOM    MMIWWW_LOAD_ANIM_BOTTOM
//页面加载进度label
#define MMIWWW_LOAD_PROG_FONT SONG_FONT_12
#define MMIWWW_LOAD_PROG_WIDTH 30
#define MMIWWW_LOAD_PROG_LEFT       (MMIWWW_LOAD_LABEL_RIGHT + 5)
#define MMIWWW_LOAD_PROG_LEFT_H     MMIWWW_LOAD_PROG_LEFT
#define MMIWWW_LOAD_PROG_TOP        MMIWWW_LOAD_LABEL_TOP
#define MMIWWW_LOAD_PROG_RIGHT      (MMIWWW_LOAD_PROG_LEFT + MMIWWW_LOAD_PROG_WIDTH - 1)
#define MMIWWW_LOAD_PROG_RIGHT_H    MMIWWW_LOAD_PROG_RIGHT
#define MMIWWW_LOAD_PROG_BOTTOM     MMIWWW_LOAD_ANIM_BOTTOM
//页面安全浏览图标label
#define MMIWWW_LOAD_SECURE_WIDTH 17
#define MMIWWW_PAGE_SECURE_LEFT     (MMIWWW_LOAD_PROG_RIGHT + 1)
#define MMIWWW_PAGE_SECURE_LEFT_H   MMIWWW_PAGE_SECURE_LEFT
#define MMIWWW_PAGE_SECURE_TOP      MMIWWW_LOAD_PROG_TOP
#define MMIWWW_PAGE_SECURE_RIGHT    (MMIWWW_PAGE_SECURE_LEFT + MMIWWW_LOAD_SECURE_WIDTH - 1)
#define MMIWWW_PAGE_SECURE_RIGHT_H  MMIWWW_PAGE_SECURE_RIGHT
#define MMIWWW_PAGE_SECURE_BOTTOM   MMIWWW_LOAD_ANIM_BOTTOM

//页面切换区域
#define WWW_PAGE_SWITCH_RECT        {0,MMI_STATUSBAR_HEIGHT,MMI_MAINSCREEN_RIGHT_MAX_PIXEL,MMI_STATUSBAR_HEIGHT+MMIWWW_PAGE_TITLE_HEIGHT}
//非全屏时页面区域
#define WWW_PAGE_CLIENT_WIDTH       MMI_MAINSCREEN_WIDTH
//全屏、非全屏时页面rect
#define WWW_NORMAL_DISPLAY_RECT  {0, MMI_STATUSBAR_HEIGHT + MMI_TITLE_HEIGHT, MMI_MAINSCREEN_RIGHT_MAX_PIXEL, MMI_MAINSCREEN_BOTTOM_MAX_PIXEL - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT}

#elif defined MAINLCD_SIZE_240X320

#define MMIWWW_MARGIN_HORIZONLTAL       (6)
#define MMIWWW_MARGIN_VERTICAL          (4)
#define MMIWWW_LABEL_HEIGHT             (24)
#define MMIWWW_BUTTON_HEIGHT            (24)
#define MMIWWW_BUTTON_WIDTH             (39)
#define MMIWWW_TAB_HEIGHT               (26)
#define MMIWWW_TAB_DISTANCE             (18)
#define MMIWWW_LABEL_WIDTH              (MMI_MAINSCREEN_WIDTH - MMIWWW_BUTTON_WIDTH - MMIWWW_MARGIN_HORIZONLTAL * 3)
#define MMIWWW_LABEL_WIDTH_H            (MMI_MAINSCREEN_HEIGHT - MMIWWW_BUTTON_WIDTH - MMIWWW_MARGIN_HORIZONLTAL * 3)

#define MMIWWW_ADDRESSBAR_LEFT      MMIWWW_MARGIN_HORIZONLTAL
#define MMIWWW_ADDRESSBAR_TOP       (MMI_TITLE_HEIGHT + MMI_STATUSBAR_HEIGHT + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_ADDRESSBAR_TOP_H       (MMI_TITLE_THEME_HEIGHT_H + MMI_STATUSBAR_HEIGHT + 4)
#define MMIWWW_ADDRESSBAR_RIGHT     (MMIWWW_ADDRESSBAR_LEFT + MMIWWW_LABEL_WIDTH - 1)
#define MMIWWW_ADDRESSBAR_RIGHT_H   (MMIWWW_ADDRESSBAR_LEFT + MMIWWW_LABEL_WIDTH_H - 1)
#define MMIWWW_ADDRESSBAR_BOTTOM    (MMIWWW_ADDRESSBAR_TOP + MMIWWW_LABEL_HEIGHT - 1)
#define MMIWWW_ADDRESSBAR_BOTTOM_H  (MMIWWW_ADDRESSBAR_TOP_H + MMIWWW_LABEL_HEIGHT - 1)

#define MMIWWW_LINK_IMAGE_LEFT     (MMIWWW_ADDRESSBAR_RIGHT + MMIWWW_MARGIN_HORIZONLTAL)
#define MMIWWW_LINK_IMAGE_LEFT_H   (MMIWWW_ADDRESSBAR_RIGHT_H + MMIWWW_MARGIN_HORIZONLTAL)
#define MMIWWW_LINK_IMAGE_TOP      (MMIWWW_ADDRESSBAR_TOP)
#define MMIWWW_LINK_IMAGE_TOP_H    (MMIWWW_ADDRESSBAR_TOP_H)
#define MMIWWW_LINK_IMAGE_RIGHT    (MMIWWW_LINK_IMAGE_LEFT + MMIWWW_BUTTON_WIDTH - 1)
#define MMIWWW_LINK_IMAGE_RIGHT_H  (MMIWWW_LINK_IMAGE_LEFT_H + MMIWWW_BUTTON_WIDTH - 1)
#define MMIWWW_LINK_IMAGE_BOTTOM   (MMIWWW_LINK_IMAGE_TOP + MMIWWW_BUTTON_HEIGHT - 1)
#define MMIWWW_LINK_IMAGE_BOTTOM_H   (MMIWWW_LINK_IMAGE_TOP_H + MMIWWW_BUTTON_HEIGHT - 1)

#define MMIWWW_SEARCHBAR_LEFT       (MMIWWW_ADDRESSBAR_LEFT)
#define MMIWWW_SEARCHSBAR_TOP       (MMIWWW_ADDRESSBAR_BOTTOM + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_SEARCHSBAR_TOP_H       (MMIWWW_ADDRESSBAR_BOTTOM_H + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_SEARCHSBAR_RIGHT     (MMIWWW_ADDRESSBAR_RIGHT)
#define MMIWWW_SEARCHSBAR_RIGHT_H   MMIWWW_ADDRESSBAR_RIGHT_H
#define MMIWWW_SEARCHSBAR_BOTTOM    (MMIWWW_SEARCHSBAR_TOP + MMIWWW_LABEL_HEIGHT - 1)
#define MMIWWW_SEARCHSBAR_BOTTOM_H  (MMIWWW_SEARCHSBAR_TOP_H + MMIWWW_LABEL_HEIGHT - 1)

#define MMIWWW_SEARCH_IMAGE_LEFT    (MMIWWW_LINK_IMAGE_LEFT)
#define MMIWWW_SEARCH_IMAGE_LEFT_H    (MMIWWW_LINK_IMAGE_LEFT_H)
#define MMIWWW_SEARCH_IMAGE_TOP     MMIWWW_SEARCHSBAR_TOP
#define MMIWWW_SEARCH_IMAGE_TOP_H   MMIWWW_SEARCHSBAR_TOP_H
#define MMIWWW_SEARCH_IMAGE_RIGHT   (MMIWWW_LINK_IMAGE_RIGHT)
#define MMIWWW_SEARCH_IMAGE_RIGHT_H   (MMIWWW_LINK_IMAGE_RIGHT_H)
#define MMIWWW_SEARCH_IMAGE_BOTTOM  (MMIWWW_SEARCH_IMAGE_TOP + MMIWWW_BUTTON_HEIGHT - 1)
#define MMIWWW_SEARCH_IMAGE_BOTTOM_H  (MMIWWW_SEARCH_IMAGE_TOP_H + MMIWWW_BUTTON_HEIGHT - 1)

#define MMIWWW_TAB_LEFT             (0)
#define MMIWWW_TAB_TOP              (MMIWWW_SEARCHSBAR_BOTTOM + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_TAB_TOP_H            (MMIWWW_SEARCHSBAR_BOTTOM_H + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_TAB_RIGHT            (MMI_MAINSCREEN_WIDTH - 1)
#define MMIWWW_TAB_RIGHT_H          (MMI_MAINSCREEN_HEIGHT - 1)
#define MMIWWW_TAB_BOTTOM           (MMIWWW_TAB_TOP + MMIWWW_TAB_HEIGHT - 1)
#define MMIWWW_TAB_BOTTOM_H         (MMIWWW_TAB_TOP_H + MMIWWW_TAB_HEIGHT - 1)

#define MMIWWW_TAB_LIST_LEFT        (0)
#define MMIWWW_TAB_LIST_TOP         (MMIWWW_TAB_BOTTOM + 1)
#define MMIWWW_TAB_LIST_TOP_H       (MMIWWW_TAB_BOTTOM_H + 1)
#define MMIWWW_TAB_LIST_RIGHT       (MMI_MAINSCREEN_WIDTH - 1)
#define MMIWWW_TAB_LIST_RIGHT_H     (MMI_MAINSCREEN_HEIGHT - 1)
#define MMIWWW_TAB_LIST_BOTTOM      (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - 1)
#define MMIWWW_TAB_LIST_BOTTOM_H    (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - 1)

// 网页窗口四个硬图标的位置信息
#define MMIWWW_PAGE_BUTTON_HEIGHT   26

#define MMIWWW_PAGE_OPTION_LEFT     0
#define MMIWWW_PAGE_OPTION_LEFT_H   0
#define MMIWWW_PAGE_OPTION_TOP      MMI_MAINSCREEN_HEIGHT - MMIWWW_PAGE_BUTTON_HEIGHT
#define MMIWWW_PAGE_OPTION_TOP_H    MMI_MAINSCREEN_WIDTH - MMIWWW_PAGE_BUTTON_HEIGHT
#define MMIWWW_PAGE_OPTION_RIGHT    59
#define MMIWWW_PAGE_OPTION_RIGHT_H  79
#define MMIWWW_PAGE_OPTION_BOTTOM   (MMIWWW_PAGE_OPTION_TOP + MMIWWW_PAGE_BUTTON_HEIGHT - 1)
#define MMIWWW_PAGE_OPTION_BOTTOM_H (MMIWWW_PAGE_OPTION_TOP_H + MMIWWW_PAGE_BUTTON_HEIGHT - 1)

#define MMIWWW_PAGE_RELOAD_LEFT     60
#define MMIWWW_PAGE_RELOAD_LEFT_H   80
#define MMIWWW_PAGE_RELOAD_TOP      294
#define MMIWWW_PAGE_RELOAD_RIGHT    119
#define MMIWWW_PAGE_RELOAD_RIGHT_H  159
#define MMIWWW_PAGE_RELOAD_BOTTOM   MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_FULL_LEFT       120
#define MMIWWW_PAGE_FULL_LEFT_H     160
#define MMIWWW_PAGE_FULL_TOP        294
#define MMIWWW_PAGE_FULL_RIGHT      179
#define MMIWWW_PAGE_FULL_RIGHT_H    239
#define MMIWWW_PAGE_FULL_BOTTOM     MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_PREV_LEFT       180
#define MMIWWW_PAGE_PREV_LEFT_H     240
#define MMIWWW_PAGE_PREV_TOP        294
#define MMIWWW_PAGE_PREV_RIGHT      239
#define MMIWWW_PAGE_PREV_RIGHT_H    319
#define MMIWWW_PAGE_PREV_BOTTOM     MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_TITLE_HEIGHT 28

//页面加载进度的动画相关
#define MMIWWW_LOAD_ANIM_WIDTH      21
#define MMIWWW_LOAD_ANIM_HEIGHT     21
#define MMIWWW_LOAD_ANIM_LEFT       6
#define MMIWWW_LOAD_ANIM_TOP        24
#define MMIWWW_LOAD_ANIM_RIGHT      (MMIWWW_LOAD_ANIM_LEFT + MMIWWW_LOAD_ANIM_WIDTH - 1)
#define MMIWWW_LOAD_ANIM_BOTTOM     (MMIWWW_LOAD_ANIM_TOP + MMIWWW_LOAD_ANIM_HEIGHT - 1)
//页面标题label
#define MMIWWW_CONTROL_MARGIN     5 
#define MMIWWW_LOAD_LABEL_LEFT      44//31
#define MMIWWW_LOAD_LABEL_TOP       (MMI_STATUSBAR_HEIGHT + 2)
#define MMIWWW_LOAD_LABEL_RIGHT     160
#define MMIWWW_LOAD_LABEL_RIGHT_H     240
#define MMIWWW_LOAD_LABEL_BOTTOM    MMIWWW_LOAD_ANIM_BOTTOM

//页面加载进度label
#define MMIWWW_LOAD_PROG_FONT MMI_DEFAULT_NORMAL_FONT
#define MMIWWW_LOAD_PROG_LEFT       161
#define MMIWWW_LOAD_PROG_LEFT_H     230
#define MMIWWW_LOAD_PROG_TOP        24
#define MMIWWW_LOAD_PROG_RIGHT      214
#define MMIWWW_LOAD_PROG_RIGHT_H    285
#define MMIWWW_LOAD_PROG_BOTTOM     MMIWWW_LOAD_ANIM_BOTTOM
//页面安全浏览图标lable
#define MMIWWW_PAGE_SECURE_LEFT     (MMIWWW_LOAD_PROG_RIGHT + 1)
#define MMIWWW_PAGE_SECURE_LEFT_H   (MMIWWW_LOAD_PROG_RIGHT_H + 1)
#define MMIWWW_PAGE_SECURE_TOP      24
#define MMIWWW_PAGE_SECURE_RIGHT    239
#define MMIWWW_PAGE_SECURE_RIGHT_H  (MMIWWW_LOAD_PROG_RIGHT_H + 25)
#define MMIWWW_PAGE_SECURE_BOTTOM   MMIWWW_LOAD_ANIM_BOTTOM

//页面切换区域
#define WWW_PAGE_SWITCH_RECT        {0,MMI_STATUSBAR_HEIGHT,MMI_MAINSCREEN_RIGHT_MAX_PIXEL,MMI_STATUSBAR_HEIGHT+MMIWWW_PAGE_TITLE_HEIGHT}
//非全屏时页面区域
#define WWW_PAGE_CLIENT_WIDTH       MMI_MAINSCREEN_WIDTH
//全屏、非全屏时页面rect
#define WWW_NORMAL_DISPLAY_RECT  {0, MMI_STATUSBAR_HEIGHT, MMI_MAINSCREEN_RIGHT_MAX_PIXEL, MMI_MAINSCREEN_BOTTOM_MAX_PIXEL}

#elif defined MAINLCD_SIZE_240X400
#define MMIWWW_MARGIN_HORIZONLTAL       (6)
#define MMIWWW_MARGIN_VERTICAL          (4)
#define MMIWWW_LABEL_HEIGHT         (24)
#define MMIWWW_BUTTON_HEIGHT        (24)
#define MMIWWW_BUTTON_WIDTH         (29)
#define MMIWWW_TAB_HEIGHT           (26)
#define MMIWWW_TAB_DISTANCE           (18)
#define MMIWWW_LABEL_WIDTH              (MMI_MAINSCREEN_WIDTH - MMIWWW_BUTTON_WIDTH - MMIWWW_MARGIN_HORIZONLTAL * 3)
#define MMIWWW_LABEL_WIDTH_H            (MMI_MAINSCREEN_HEIGHT - MMIWWW_BUTTON_WIDTH - MMIWWW_MARGIN_HORIZONLTAL * 3)

#define MMIWWW_ADDRESSBAR_LEFT      MMIWWW_MARGIN_HORIZONLTAL
#define MMIWWW_ADDRESSBAR_TOP       (MMI_TITLE_HEIGHT + MMI_STATUSBAR_HEIGHT + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_ADDRESSBAR_TOP_H       (MMI_TITLE_THEME_HEIGHT_H + MMI_STATUSBAR_HEIGHT + 4)
#define MMIWWW_ADDRESSBAR_RIGHT     (MMIWWW_ADDRESSBAR_LEFT + MMIWWW_LABEL_WIDTH - 1)
#define MMIWWW_ADDRESSBAR_RIGHT_H   (MMIWWW_ADDRESSBAR_LEFT + MMIWWW_LABEL_WIDTH_H - 1)
#define MMIWWW_ADDRESSBAR_BOTTOM    (MMIWWW_ADDRESSBAR_TOP + MMIWWW_LABEL_HEIGHT - 1)
#define MMIWWW_ADDRESSBAR_BOTTOM_H  (MMIWWW_ADDRESSBAR_TOP_H + MMIWWW_LABEL_HEIGHT - 1)

#define MMIWWW_LINK_IMAGE_LEFT     (MMIWWW_ADDRESSBAR_RIGHT + MMIWWW_MARGIN_HORIZONLTAL)
#define MMIWWW_LINK_IMAGE_LEFT_H   (MMIWWW_ADDRESSBAR_RIGHT_H + MMIWWW_MARGIN_HORIZONLTAL)
#define MMIWWW_LINK_IMAGE_TOP      (MMIWWW_ADDRESSBAR_TOP)
#define MMIWWW_LINK_IMAGE_TOP_H    (MMIWWW_ADDRESSBAR_TOP_H)
#define MMIWWW_LINK_IMAGE_RIGHT    (MMIWWW_LINK_IMAGE_LEFT + MMIWWW_BUTTON_WIDTH - 1)
#define MMIWWW_LINK_IMAGE_RIGHT_H  (MMIWWW_LINK_IMAGE_LEFT_H + MMIWWW_BUTTON_WIDTH - 1)
#define MMIWWW_LINK_IMAGE_BOTTOM   (MMIWWW_LINK_IMAGE_TOP + MMIWWW_BUTTON_HEIGHT - 1)
#define MMIWWW_LINK_IMAGE_BOTTOM_H   (MMIWWW_LINK_IMAGE_TOP_H + MMIWWW_BUTTON_HEIGHT - 1)

#define MMIWWW_SEARCHBAR_LEFT       (MMIWWW_ADDRESSBAR_LEFT)
#define MMIWWW_SEARCHSBAR_TOP       (MMIWWW_ADDRESSBAR_BOTTOM + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_SEARCHSBAR_TOP_H       (MMIWWW_ADDRESSBAR_BOTTOM_H + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_SEARCHSBAR_RIGHT     (MMIWWW_ADDRESSBAR_RIGHT)
#define MMIWWW_SEARCHSBAR_RIGHT_H   MMIWWW_ADDRESSBAR_RIGHT_H
#define MMIWWW_SEARCHSBAR_BOTTOM    (MMIWWW_SEARCHSBAR_TOP + MMIWWW_LABEL_HEIGHT - 1)
#define MMIWWW_SEARCHSBAR_BOTTOM_H  (MMIWWW_SEARCHSBAR_TOP_H + MMIWWW_LABEL_HEIGHT - 1)

#define MMIWWW_SEARCH_IMAGE_LEFT    (MMIWWW_LINK_IMAGE_LEFT)
#define MMIWWW_SEARCH_IMAGE_LEFT_H    (MMIWWW_LINK_IMAGE_LEFT_H)
#define MMIWWW_SEARCH_IMAGE_TOP     MMIWWW_SEARCHSBAR_TOP
#define MMIWWW_SEARCH_IMAGE_TOP_H   MMIWWW_SEARCHSBAR_TOP_H
#define MMIWWW_SEARCH_IMAGE_RIGHT   (MMIWWW_LINK_IMAGE_RIGHT)
#define MMIWWW_SEARCH_IMAGE_RIGHT_H   (MMIWWW_LINK_IMAGE_RIGHT_H)
#define MMIWWW_SEARCH_IMAGE_BOTTOM  (MMIWWW_SEARCH_IMAGE_TOP + MMIWWW_BUTTON_HEIGHT - 1)
#define MMIWWW_SEARCH_IMAGE_BOTTOM_H  (MMIWWW_SEARCH_IMAGE_TOP_H + MMIWWW_BUTTON_HEIGHT - 1)

#define MMIWWW_TAB_LEFT             (0)
#define MMIWWW_TAB_TOP              (MMIWWW_SEARCHSBAR_BOTTOM + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_TAB_TOP_H            (MMIWWW_SEARCHSBAR_BOTTOM_H + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_TAB_RIGHT            (MMI_MAINSCREEN_WIDTH - 1)
#define MMIWWW_TAB_RIGHT_H          (MMI_MAINSCREEN_HEIGHT - 1)
#define MMIWWW_TAB_BOTTOM           (MMIWWW_TAB_TOP + MMIWWW_TAB_HEIGHT - 1)
#define MMIWWW_TAB_BOTTOM_H         (MMIWWW_TAB_TOP_H + MMIWWW_TAB_HEIGHT - 1)

#define MMIWWW_TAB_LIST_LEFT        (0)
#define MMIWWW_TAB_LIST_TOP         (MMIWWW_TAB_BOTTOM + 1)
#define MMIWWW_TAB_LIST_TOP_H       (MMIWWW_TAB_BOTTOM_H + 1)
#define MMIWWW_TAB_LIST_RIGHT       (MMI_MAINSCREEN_WIDTH - 1)
#define MMIWWW_TAB_LIST_RIGHT_H     (MMI_MAINSCREEN_HEIGHT - 1)
#define MMIWWW_TAB_LIST_BOTTOM      (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - 1)
#define MMIWWW_TAB_LIST_BOTTOM_H    (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - 1)

// 网页窗口四个硬图标的位置信息
#define MMIWWW_PAGE_BUTTON_HEIGHT   26

#define MMIWWW_PAGE_OPTION_LEFT     0
#define MMIWWW_PAGE_OPTION_LEFT_H   20
#define MMIWWW_PAGE_OPTION_TOP      374
#define MMIWWW_PAGE_OPTION_TOP_H    MMIWWW_PAGE_OPTION_TOP - 160
#define MMIWWW_PAGE_OPTION_RIGHT    59
#define MMIWWW_PAGE_OPTION_RIGHT_H  79
#define MMIWWW_PAGE_OPTION_BOTTOM   (MMIWWW_PAGE_OPTION_TOP + MMIWWW_PAGE_BUTTON_HEIGHT - 1)
#define MMIWWW_PAGE_OPTION_BOTTOM_H MMIWWW_PAGE_OPTION_BOTTOM - 160

#define MMIWWW_PAGE_RELOAD_LEFT     60
#define MMIWWW_PAGE_RELOAD_LEFT_H   120
#define MMIWWW_PAGE_RELOAD_TOP      374
#define MMIWWW_PAGE_RELOAD_RIGHT    119
#define MMIWWW_PAGE_RELOAD_RIGHT_H  179
#define MMIWWW_PAGE_RELOAD_BOTTOM   MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_FULL_LEFT       120
#define MMIWWW_PAGE_FULL_LEFT_H     220
#define MMIWWW_PAGE_FULL_TOP        374
#define MMIWWW_PAGE_FULL_RIGHT      179
#define MMIWWW_PAGE_FULL_RIGHT_H    279
#define MMIWWW_PAGE_FULL_BOTTOM     MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_PREV_LEFT       180
#define MMIWWW_PAGE_PREV_LEFT_H     320
#define MMIWWW_PAGE_PREV_TOP        374
#define MMIWWW_PAGE_PREV_RIGHT      239
#define MMIWWW_PAGE_PREV_RIGHT_H    379
#define MMIWWW_PAGE_PREV_BOTTOM     MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_TITLE_HEIGHT 28

//页面加载进度的动画相关
#define MMIWWW_LOAD_ANIM_WIDTH      21
#define MMIWWW_LOAD_ANIM_HEIGHT     21
#define MMIWWW_LOAD_ANIM_LEFT       6
#define MMIWWW_LOAD_ANIM_TOP        24
#define MMIWWW_LOAD_ANIM_RIGHT      (MMIWWW_LOAD_ANIM_LEFT + MMIWWW_LOAD_ANIM_WIDTH - 1)
#define MMIWWW_LOAD_ANIM_BOTTOM     (MMIWWW_LOAD_ANIM_TOP + MMIWWW_LOAD_ANIM_HEIGHT - 1)
//页面标题label
#define MMIWWW_CONTROL_MARGIN     5 
#define MMIWWW_LOAD_LABEL_LEFT      44//31
#define MMIWWW_LOAD_LABEL_TOP       24
#define MMIWWW_LOAD_LABEL_RIGHT     160
#define MMIWWW_LOAD_LABEL_RIGHT_H   MMIWWW_LOAD_LABEL_RIGHT
#define MMIWWW_LOAD_LABEL_BOTTOM    MMIWWW_LOAD_ANIM_BOTTOM
//页面加载进度label
#define MMIWWW_LOAD_PROG_FONT MMI_DEFAULT_NORMAL_FONT
#define MMIWWW_LOAD_PROG_LEFT       161
#define MMIWWW_LOAD_PROG_LEFT_H     MMIWWW_LOAD_PROG_LEFT
#define MMIWWW_LOAD_PROG_TOP        24
#define MMIWWW_LOAD_PROG_RIGHT      214
#define MMIWWW_LOAD_PROG_RIGHT_H    MMIWWW_LOAD_PROG_RIGHT
#define MMIWWW_LOAD_PROG_BOTTOM     MMIWWW_LOAD_ANIM_BOTTOM

//页面安全浏览图标lable
#define MMIWWW_PAGE_SECURE_LEFT     (MMIWWW_LOAD_PROG_RIGHT + 1)
#define MMIWWW_PAGE_SECURE_LEFT_H   MMIWWW_PAGE_SECURE_LEFT
#define MMIWWW_PAGE_SECURE_TOP      24
#define MMIWWW_PAGE_SECURE_RIGHT    239
#define MMIWWW_PAGE_SECURE_RIGHT_H  MMIWWW_PAGE_SECURE_RIGHT
#define MMIWWW_PAGE_SECURE_BOTTOM   MMIWWW_LOAD_ANIM_BOTTOM
//页面切换区域
#define WWW_PAGE_SWITCH_RECT        {0,MMI_STATUSBAR_HEIGHT,MMI_MAINSCREEN_RIGHT_MAX_PIXEL,MMI_STATUSBAR_HEIGHT+MMIWWW_PAGE_TITLE_HEIGHT}
//非全屏时页面区域
#define WWW_PAGE_CLIENT_WIDTH       MMI_MAINSCREEN_WIDTH
//全屏、非全屏时页面rect
#define WWW_NORMAL_DISPLAY_RECT  {0, MMI_STATUSBAR_HEIGHT, MMI_MAINSCREEN_RIGHT_MAX_PIXEL, MMI_MAINSCREEN_BOTTOM_MAX_PIXEL}

#elif defined MAINLCD_SIZE_320X480

#define MMIWWW_LCD_HEIGHT           (MMI_MAINSCREEN_HEIGHT)
#define MMIWWW_LCD_WIDTH            (MMI_MAINSCREEN_WIDTH)

#define MMIWWW_MARGIN_HORIZONLTAL       (6)
#define MMIWWW_MARGIN_VERTICAL          (4)
#define MMIWWW_LABEL_HEIGHT         (30)
#define MMIWWW_BUTTON_HEIGHT        (34)
#define MMIWWW_BUTTON_WIDTH         (29)
#define MMIWWW_TAB_HEIGHT           (32)
#define MMIWWW_TAB_DISTANCE           (18)
#define MMIWWW_LABEL_WIDTH              (MMI_MAINSCREEN_WIDTH - MMIWWW_BUTTON_WIDTH - MMIWWW_MARGIN_HORIZONLTAL * 3)
#define MMIWWW_LABEL_WIDTH_H            (MMI_MAINSCREEN_HEIGHT - MMIWWW_BUTTON_WIDTH - MMIWWW_MARGIN_HORIZONLTAL * 3)

#define MMIWWW_ADDRESSBAR_LEFT      MMIWWW_MARGIN_HORIZONLTAL
#define MMIWWW_ADDRESSBAR_TOP       (MMI_TITLE_HEIGHT + MMI_STATUSBAR_HEIGHT + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_ADDRESSBAR_TOP_H       (MMI_TITLE_THEME_HEIGHT_H + MMI_STATUSBAR_HEIGHT + 4)
#define MMIWWW_ADDRESSBAR_RIGHT     (MMIWWW_ADDRESSBAR_LEFT + MMIWWW_LABEL_WIDTH - 1)
#define MMIWWW_ADDRESSBAR_RIGHT_H   (MMIWWW_ADDRESSBAR_LEFT + MMIWWW_LABEL_WIDTH_H - 1)
#define MMIWWW_ADDRESSBAR_BOTTOM    (MMIWWW_ADDRESSBAR_TOP + MMIWWW_LABEL_HEIGHT - 1)
#define MMIWWW_ADDRESSBAR_BOTTOM_H  (MMIWWW_ADDRESSBAR_TOP_H + MMIWWW_LABEL_HEIGHT - 1)

#define MMIWWW_LINK_IMAGE_LEFT     (MMIWWW_ADDRESSBAR_RIGHT + MMIWWW_MARGIN_HORIZONLTAL)
#define MMIWWW_LINK_IMAGE_LEFT_H   (MMIWWW_ADDRESSBAR_RIGHT_H + MMIWWW_MARGIN_HORIZONLTAL)
#define MMIWWW_LINK_IMAGE_TOP      (MMIWWW_ADDRESSBAR_TOP)
#define MMIWWW_LINK_IMAGE_TOP_H    (MMIWWW_ADDRESSBAR_TOP_H)
#define MMIWWW_LINK_IMAGE_RIGHT    (MMIWWW_LINK_IMAGE_LEFT + MMIWWW_BUTTON_WIDTH - 1)
#define MMIWWW_LINK_IMAGE_RIGHT_H  (MMIWWW_LINK_IMAGE_LEFT_H + MMIWWW_BUTTON_WIDTH - 1)
#define MMIWWW_LINK_IMAGE_BOTTOM   (MMIWWW_LINK_IMAGE_TOP + MMIWWW_BUTTON_HEIGHT - 1)
#define MMIWWW_LINK_IMAGE_BOTTOM_H   (MMIWWW_LINK_IMAGE_TOP_H + MMIWWW_BUTTON_HEIGHT - 1)

#define MMIWWW_SEARCHBAR_LEFT       (MMIWWW_ADDRESSBAR_LEFT)
#define MMIWWW_SEARCHSBAR_TOP       (MMIWWW_ADDRESSBAR_BOTTOM + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_SEARCHSBAR_TOP_H       (MMIWWW_ADDRESSBAR_BOTTOM_H + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_SEARCHSBAR_RIGHT     (MMIWWW_ADDRESSBAR_RIGHT)
#define MMIWWW_SEARCHSBAR_RIGHT_H   MMIWWW_ADDRESSBAR_RIGHT_H
#define MMIWWW_SEARCHSBAR_BOTTOM    (MMIWWW_SEARCHSBAR_TOP + MMIWWW_LABEL_HEIGHT - 1)
#define MMIWWW_SEARCHSBAR_BOTTOM_H  (MMIWWW_SEARCHSBAR_TOP_H + MMIWWW_LABEL_HEIGHT - 1)

#define MMIWWW_SEARCH_IMAGE_LEFT    (MMIWWW_LINK_IMAGE_LEFT)
#define MMIWWW_SEARCH_IMAGE_LEFT_H    (MMIWWW_LINK_IMAGE_LEFT_H)
#define MMIWWW_SEARCH_IMAGE_TOP     MMIWWW_SEARCHSBAR_TOP
#define MMIWWW_SEARCH_IMAGE_TOP_H   MMIWWW_SEARCHSBAR_TOP_H
#define MMIWWW_SEARCH_IMAGE_RIGHT   (MMIWWW_LINK_IMAGE_RIGHT)
#define MMIWWW_SEARCH_IMAGE_RIGHT_H   (MMIWWW_LINK_IMAGE_RIGHT_H)
#define MMIWWW_SEARCH_IMAGE_BOTTOM  (MMIWWW_SEARCH_IMAGE_TOP + MMIWWW_BUTTON_HEIGHT - 1)
#define MMIWWW_SEARCH_IMAGE_BOTTOM_H  (MMIWWW_SEARCH_IMAGE_TOP_H + MMIWWW_BUTTON_HEIGHT - 1)

#define MMIWWW_TAB_LEFT             (0)
#define MMIWWW_TAB_TOP              (MMIWWW_SEARCHSBAR_BOTTOM + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_TAB_TOP_H            (MMIWWW_SEARCHSBAR_BOTTOM_H + MMIWWW_MARGIN_VERTICAL)
#define MMIWWW_TAB_RIGHT            (MMI_MAINSCREEN_WIDTH - 1)
#define MMIWWW_TAB_RIGHT_H          (MMI_MAINSCREEN_HEIGHT - 1)
#define MMIWWW_TAB_BOTTOM           (MMIWWW_TAB_TOP + MMIWWW_TAB_HEIGHT - 1)
#define MMIWWW_TAB_BOTTOM_H         (MMIWWW_TAB_TOP_H + MMIWWW_TAB_HEIGHT - 1)

#define MMIWWW_TAB_LIST_LEFT        (0)
#define MMIWWW_TAB_LIST_TOP         (MMIWWW_TAB_BOTTOM + 1)
#define MMIWWW_TAB_LIST_TOP_H       (MMIWWW_TAB_BOTTOM_H + 1)
#define MMIWWW_TAB_LIST_RIGHT       (MMI_MAINSCREEN_WIDTH - 1)
#define MMIWWW_TAB_LIST_RIGHT_H     (MMI_MAINSCREEN_HEIGHT - 1)
#define MMIWWW_TAB_LIST_BOTTOM      (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - 1)
#define MMIWWW_TAB_LIST_BOTTOM_H    (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - 1)


// 网页窗口四个硬图标的位置信息
#define MMIWWW_PAGE_BUTTON_HEIGHT   33

#define MMIWWW_PAGE_BUTTON_BG_HEIGHT   (45)
#define MMIWWW_PAGE_BUTTON_BG_TOP   (MMI_MAINSCREEN_BOTTOM_MAX_PIXEL - MMIWWW_PAGE_BUTTON_BG_HEIGHT)

#define MMIWWW_PAGE_OPTION_LEFT     20
#define MMIWWW_PAGE_OPTION_LEFT_H   40
#define MMIWWW_PAGE_OPTION_TOP      440
#define MMIWWW_PAGE_OPTION_TOP_H    MMIWWW_PAGE_OPTION_TOP - 160
#define MMIWWW_PAGE_OPTION_RIGHT    90
#define MMIWWW_PAGE_OPTION_RIGHT_H  110
#define MMIWWW_PAGE_OPTION_BOTTOM   (MMIWWW_PAGE_OPTION_TOP + MMIWWW_PAGE_BUTTON_HEIGHT - 1)
#define MMIWWW_PAGE_OPTION_BOTTOM_H MMIWWW_PAGE_OPTION_BOTTOM - 160

#define MMIWWW_PAGE_RELOAD_LEFT     90
#define MMIWWW_PAGE_RELOAD_LEFT_H   150
#define MMIWWW_PAGE_RELOAD_TOP      MMIWWW_PAGE_OPTION_TOP
#define MMIWWW_PAGE_RELOAD_RIGHT    160
#define MMIWWW_PAGE_RELOAD_RIGHT_H  220
#define MMIWWW_PAGE_RELOAD_BOTTOM   MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_FULL_LEFT       160
#define MMIWWW_PAGE_FULL_LEFT_H     260
#define MMIWWW_PAGE_FULL_TOP        MMIWWW_PAGE_OPTION_TOP
#define MMIWWW_PAGE_FULL_RIGHT      230
#define MMIWWW_PAGE_FULL_RIGHT_H    330
#define MMIWWW_PAGE_FULL_BOTTOM     MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_PREV_LEFT       230
#define MMIWWW_PAGE_PREV_LEFT_H     370
#define MMIWWW_PAGE_PREV_TOP        MMIWWW_PAGE_OPTION_TOP
#define MMIWWW_PAGE_PREV_RIGHT      300
#define MMIWWW_PAGE_PREV_RIGHT_H    440
#define MMIWWW_PAGE_PREV_BOTTOM     MMIWWW_PAGE_OPTION_BOTTOM

#define MMIWWW_PAGE_TITLE_HEIGHT 30

//页面加载进度的动画相关
#define MMIWWW_LOAD_ANIM_WIDTH      23
#define MMIWWW_LOAD_ANIM_HEIGHT     24
#define MMIWWW_LOAD_ANIM_LEFT       14
#define MMIWWW_LOAD_ANIM_TOP        29
#define MMIWWW_LOAD_ANIM_RIGHT      (MMIWWW_LOAD_ANIM_LEFT + MMIWWW_LOAD_ANIM_WIDTH - 1)
#define MMIWWW_LOAD_ANIM_BOTTOM     (MMIWWW_LOAD_ANIM_TOP + MMIWWW_LOAD_ANIM_HEIGHT - 1)
//页面标题label
#define MMIWWW_CONTROL_MARGIN     5 
#define MMIWWW_LOAD_LABEL_LEFT      44//31
#define MMIWWW_LOAD_LABEL_TOP       24
#define MMIWWW_LOAD_LABEL_RIGHT     225
#define MMIWWW_LOAD_LABEL_RIGHT_H   MMIWWW_LOAD_LABEL_RIGHT
#define MMIWWW_LOAD_LABEL_BOTTOM    MMIWWW_LOAD_ANIM_BOTTOM
//页面加载进度label
#define MMIWWW_LOAD_PROG_FONT MMI_DEFAULT_NORMAL_FONT
#define MMIWWW_LOAD_PROG_LEFT       230//180
#define MMIWWW_LOAD_PROG_LEFT_H     MMIWWW_LOAD_PROG_LEFT
#define MMIWWW_LOAD_PROG_TOP        24
#define MMIWWW_LOAD_PROG_RIGHT      273//220
#define MMIWWW_LOAD_PROG_RIGHT_H    MMIWWW_LOAD_PROG_RIGHT
#define MMIWWW_LOAD_PROG_BOTTOM     MMIWWW_LOAD_ANIM_BOTTOM

//页面安全浏览图标lable
#define MMIWWW_PAGE_SECURE_LEFT     (MMIWWW_LOAD_PROG_RIGHT + 1)
#define MMIWWW_PAGE_SECURE_LEFT_H   MMIWWW_PAGE_SECURE_LEFT
#define MMIWWW_PAGE_SECURE_TOP      32
#define MMIWWW_PAGE_SECURE_RIGHT    295
#define MMIWWW_PAGE_SECURE_RIGHT_H  MMIWWW_PAGE_SECURE_RIGHT
#define MMIWWW_PAGE_SECURE_BOTTOM   49

//页面切换区域
#define WWW_PAGE_SWITCH_RECT        {0,MMI_STATUSBAR_HEIGHT,MMI_MAINSCREEN_RIGHT_MAX_PIXEL,MMI_STATUSBAR_HEIGHT+MMIWWW_PAGE_TITLE_HEIGHT}
//非全屏时页面区域
#define WWW_PAGE_CLIENT_WIDTH       MMI_MAINSCREEN_WIDTH
//全屏、非全屏时页面rect
#define WWW_FULL_DISPLAY_RECT    {0, 0, MMI_MAINSCREEN_RIGHT_MAX_PIXEL, MMI_MAINSCREEN_BOTTOM_MAX_PIXEL}
#define WWW_NORMAL_DISPLAY_RECT  {0, MMI_STATUSBAR_HEIGHT, MMI_MAINSCREEN_RIGHT_MAX_PIXEL, MMI_MAINSCREEN_BOTTOM_MAX_PIXEL}

#else
#error
#endif


#endif
