
#ifdef BROWSER_SUPPORT_NETFRONT
//[[define image infomation
RES_ADD_IMG(IMAGE_WWW_PAGE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_SECURE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SECURE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_ADDRESS,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_ADDRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_CMCC,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_CMCC.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_GOOGLE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_GOOGLE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_BAIDU,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_BAIDU.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_YAHOO,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_YAHOO.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_LINK_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_LINK_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_LINK_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_LINK_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_LINK_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_LINK_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_LINK_FOCUSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_LINK_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_SEARCH_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SEARCH_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_SEARCH_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SEARCH_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_SEARCH_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SEARCH_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_SEARCH_FOCUSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SEARCH_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_TAB_BG,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_TAB_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WWW_TAB_FOCUSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_TAB_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_CERT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_CERTIFICATE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_CERT_ITEM,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_CERTIFICATE_ITEM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_CLEAR_CACHE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_CLEAR_CACHE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_COOKIE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_COOKIE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_VIEW_MODE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_VIEW_MODE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_DISPLAY,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_DISPLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_SET_FONT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SET_FONT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_SET_HOMEPAGE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SET_HOMEPAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_SET_CACHE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SET_CACHE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_SET_WEBDATA,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_WEBDATA.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifndef DPHONE_SUPPORT 
RES_ADD_IMG(IMAGE_WWW_POINTER_MODE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_POINTER_MODE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_WWW_RESET,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_RESET.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_ACCOUNT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SET_ACCOUNT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_ACCOUNT1,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SET_ACCOUNT1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_ACCOUNT2,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_SET_ACCOUNT2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_BOOKMARK_CUSTOMIZE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_BOOKMARK_CUSTOMIZE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WWW_BOOKMARK_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_BOOKMARK_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
//web page loading anim
RES_ADD_IMG(IMAGE_WWW_PAGELOADING,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGELOADING.gif",IMG_CMP_GIF_SCI,0)
//web page load pic
RES_ADD_IMG(IMAGE_WWW_PAGELOAD_PIC,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGELOAD_PIC.bmp",IMG_CMP_BMP_16_565_RLE,0)
//web page button image
#if defined(MAINLCD_SIZE_320X480) || defined(MAINLCD_SIZE_240X320)
RES_ADD_IMG(IMAGE_WWW_PAGE_STOP_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_STOP_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_STOP_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_STOP_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_STOP_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_STOP_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_PREV_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_PREV_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_PREV_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_PREV_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_PREV_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_PREV_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_NEXT_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_NEXT_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_NEXT_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_NEXT_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_NEXT_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_NEXT_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_FULL_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_FULL_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_FULL_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_FULL_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_FULL_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_FULL_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_RELOAD_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_RELOAD_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_RELOAD_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_RELOAD_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_RELOAD_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_RELOAD_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_OPTION_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_OPTION_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_OPTION_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_OPTION_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_OPTION_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_OPTION_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_EXIT_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_EXIT_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_EXIT_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_EXIT_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_EXIT_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_EXIT_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_WWW_PAGE_STOP_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_STOP_DEFAULT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_STOP_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_STOP_PRESSED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_STOP_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_STOP_DISABLED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_PREV_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_PREV_DEFAULT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_PREV_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_PREV_PRESSED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_PREV_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_PREV_DISABLED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_NEXT_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_NEXT_DEFAULT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_NEXT_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_NEXT_PRESSED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_NEXT_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_NEXT_DISABLED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_FULL_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_FULL_DEFAULT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_FULL_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_FULL_PRESSED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_FULL_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_FULL_DISABLED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_RELOAD_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_RELOAD_DEFAULT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_RELOAD_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_RELOAD_PRESSED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_RELOAD_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_RELOAD_DISABLED.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMAGE_WWW_PAGE_OPTION_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_OPTION_DEFAULT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_OPTION_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_OPTION_PRESSED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_OPTION_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_OPTION_DISABLED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_EXIT_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_EXIT_DEFAULT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_EXIT_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_EXIT_PRESSED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_EXIT_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_EXIT_DISABLED.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

RES_ADD_IMG(IMAGE_WWW_PAGE_BUTTON_BG,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_BUTTON_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_BUTTON_BG_H,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_BUTTON_BG_H.bmp",IMG_CMP_BMP_16_565_RLE,0)
//web page title bar
//RES_ADD_IMG(IMAGE_WWW_PAGE_1ST_TITLE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_1ST_TITLE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_WWW_PAGE_2ND_TITLE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_2ND_TITLE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_PAGE_DEFAULT_TITLE,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_DEFAULT_TITLE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_WWW_PAGE_1ST_TITLE_H,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_1ST_TITLE_H.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_WWW_PAGE_2ND_TITLE_H,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_2ND_TITLE_H.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMAGE_WWW_PAGE_DEFAULT_TITLE_H,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_PAGE_DEFAULT_TITLE_H.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WWW_TOOLBOX_FULL_DISPLAY,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_TOOLBOX_FULL_DISPLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WWW_TOOLBOX_NORMAL_DISPLAY,"\\MMI_RES_##\\IMAG\\IMAGE_WWW_TOOLBOX_NORMAL_DISPLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image infomation


//[[define anim infomation

//]]define anim infomation


//[[define string infomation
//RES_ADD_STRING(TXT_WWW_TITLE,"Internet")         //replaced by common ID TXT_COMMUNICATION_BROWSER 
//RES_ADD_STRING(TXT_WWW_SUBMENU,"Menu")  //replaced by common ID TXT_COMM_MENU
//RES_ADD_STRING(TXT_WWW_RETURN,"Exit")    //replaced by common ID  STXT_EXIT
RES_ADD_STRING(TXT_WWW_SUBMENU_FORWARD,"Forward")
//RES_ADD_STRING(TXT_WWW_SUBMENU_REFRESH,"Refresh")    //replaced by common ID TXT_REFRESH
RES_ADD_STRING(TXT_WWW_SUBMENU_SWITCH_PAGE,"Web page swtich")
RES_ADD_STRING(TXT_WWW_SUBMENU_NEW_PAGE,"New web page")
//RES_ADD_STRING(TXT_WWW_SUBMENU_BOOKMARK,"Bookmark")  //replaced by common ID TXT_COMMON_BOOKMARKS
RES_ADD_STRING(TXT_WWW_SUBMENU_HISTORY,"History")
//RES_ADD_STRING(TXT_WWW_SUBMENU_EDIT,"Edit") //replaced by common ID TXT_EDIT
//RES_ADD_STRING(TXT_WWW_SUBMENU_SETTING,"Settings")      //replaced by common ID STXT_MAIN_SETTING
//RES_ADD_STRING(TXT_WWW_SUBMENU_EXIT,"Exit")    //replaced by common ID  STXT_EXIT
//RES_ADD_STRING(TXT_WWW_SETTING,"Settings")      //replaced by common ID STXT_MAIN_SETTING
//RES_ADD_STRING(TXT_WWW_SEARCH,"Search")  //replaced by common ID STXT_SEARCH

RES_ADD_STRING(TXT_WWW_RETURN_TO_BROWSER,"Return to web page")
RES_ADD_STRING(TXT_WWW_CHOSE_SEARCH_ENGINE,"Chose search engine")
//RES_ADD_STRING(TXT_WWW_SAVED_PAGE,"Saved web pages")  //replaced by local ID TXT_WWW_PAGE_MEMO
RES_ADD_STRING(TXT_WWW_GOOGLE,"Google")
//RES_ADD_STRING(TXT_WWW_BAIDU,"Baidu") replaced by common ID TXT_MAINMENU_ICON_BAIDU
RES_ADD_STRING(TXT_WWW_YAHOO,"Yahoo")
RES_ADD_STRING(TXT_WWW_CMCC_SEARCH,"CMCC search")

RES_ADD_STRING(TXT_WWW_INPUT_URL,"Input URL")
RES_ADD_STRING(TXT_WWW_INPUT_KEYWORD,"Input keyword")
RES_ADD_STRING(TXT_WWW_INPUT_TITLE,"Input title")

RES_ADD_STRING(TXT_WWW_SEARCH_KEYWORD,"Search keyword")
RES_ADD_STRING(TXT_WWW_ENTER,"In")
RES_ADD_STRING(TXT_WWW_EXIT,"Out")
//Bookmark
//RES_ADD_STRING(TXT_WWW_BOOKMARK,"Bookmark")    //replaced by common ID TXT_BOOKMARK
//RES_ADD_STRING(TXT_WWW_BOOKMARK_DEFAULT_TITLE,"No title")    //replaced by common ID TXT_NO_TITLE 
RES_ADD_STRING(TXT_WWW_BOOKMARK_NEW_BOOKMARK_TITLE,"Add bookmark")
RES_ADD_STRING(TXT_WWW_BOOKMARK_EDIT_BOOKMARK_TITLE,"Edit bookmark")
//RES_ADD_STRING(TXT_WWW_BOOKMARK_SHOW_BOOKMARK_TITLE,"Show address")    //replaced by local common ID TXT_WWW_SHOW_ADDRESS
//RES_ADD_STRING(TXT_WWW_BOOKMARK_URL,"URL:")  //replaced by common ID TXT_COMMON_URL
//RES_ADD_STRING(TXT_WWW_BOOKMARK_TITLE,"Title:")  //replaced by common ID TXT_COMM_TITLE
//RES_ADD_STRING(TXT_WWW_BOOKMARK_SAVE,"Save")  //replaced by common ID STXT_SAVE
RES_ADD_STRING(TXT_WWW_BOOKMARK_FULL,"Bookmark is full,delete first")
RES_ADD_STRING(TXT_WWW_BOOKMARK_EMPTY,"Empty")
//RES_ADD_STRING(TXT_WWW_BOOKMARK_SUBMENU_ADD,"Add")    //replaced by common ID TXT_ADDNEW
//RES_ADD_STRING(TXT_WWW_BOOKMARK_SUBMENU_EDIT,"Edit")    //replaced by common ID TXT_MODIFY
//RES_ADD_STRING(TXT_WWW_BOOKMARK_SUBMENU_DELETE,"Delete")       //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_WWW_BOOKMARK_SUBMENU_DELETE_ALL,"Delete all")   //replaced by common ID TXT_DELALL
//RES_ADD_STRING(TXT_WWW_BOOKMARK_SUBMENU_MOVE,"Move")    //replaced by common ID TXT_MOVE
//RES_ADD_STRING(TXT_WWW_BOOKMARK_SUBMENU_PROPERTY,"Show address")    //replaced by local common ID TXT_WWW_SHOW_ADDRESS
//RES_ADD_STRING(TXT_WWW_BOOKMARK_SAVE_SUCCESS,"Saved")  //replaced by common ID TXT_COMMON_SAVED
RES_ADD_STRING(TXT_COMM_URL_NULL,"URL is empty")
//RES_ADD_STRING(TXT_WWW_BOOKMARK_ADD_FAIL_NO_TITLE,"Title is empty")  //replaced by common ID TXT_COMM_NO_TITLE
//RES_ADD_STRING(TXT_WWW_BOOKMARK_DELETE_SUCCESS,"Deleted")    //replaced by common ID TXT_DELETED
//RES_ADD_STRING(TXT_WWW_BOOKMARK_CONNECT,"Connect")  //replaced by common ID TXT_COMMON_CONNECT_COMN
//RES_ADD_STRING(TXT_WWW_EXIT_WITHOUT_SAVE,"Exit without saving?")  //replaced by common ID TXT_EXIT_WITHOUT_SAVE
RES_ADD_STRING(TXT_WWW_BOOKMARK_ENSURE_DELETE,"Delete current bookmark")
//RES_ADD_STRING(TXT_WWW_BOOKMARK_ENSURE_DELETE_ALL,"Delete all")    //replaced by common ID TXT_DELETE_ALL_QUERY
//RES_ADD_STRING(TXT_WWW_INVALID_URL,"Invalid  URL")  //replaced by common ID TXT_COMMON_URL_INVALID
RES_ADD_STRING(TXT_WWW_IF_SAVE_COOKIE,"Save cookie")

//RES_ADD_STRING(TXT_WWW_HISTORY,"History")       //replaced by common ID TXT_COMMON_HISTORY

//RES_ADD_STRING(TXT_WWW_SET_FONT,"Font setting")  //replaced by common ID TXT_COMMON_FONT_SIZE
//RES_ADD_STRING(TXT_WWW_FONT_BIG,"Big font")  //replaced by common ID TXT_COMM_FONT_BIG
//RES_ADD_STRING(TXT_WWW_FONT_NORMAL,"Normal font")  //replaced by common ID TXT_COMMON_NORMAL
//RES_ADD_STRING(TXT_WWW_FONT_SMALL,"Small font")    //replaced by common ID TXT_FONT_SMALL
//RES_ADD_STRING(TXT_WWW_COOKIE,"Cookies")    //replaced by common ID TXT_COOKIE
RES_ADD_STRING(TXT_WWW_COOKIE_MODE,"Mode")
RES_ADD_STRING(TXT_WWW_CLEAR_COOKIE,"Clear cookie")
RES_ADD_STRING(TXT_WWW_COOKIE_MODE_ACCEPT_ALL, "Accept all")
RES_ADD_STRING(TXT_WWW_COOKIE_MODE_REJECT_ALL, "Reject all")
//RES_ADD_STRING(TXT_WWW_COOKIE_MODE_REQUEST, "Request")    //replaced by common ID TXT_COMMON_PROMPT
//RES_ADD_STRING(TXT_WWW_ENSURE_CLEAR,"Clear")        //replaced by common ID TXT_COMMON_ENSURE_CLEAR
RES_ADD_STRING(TXT_WWW_IS_CLEAR_CACHE,"Clear all caches")
RES_ADD_STRING(TXT_WWW_IS_CLEAR_COOKIES,"Clear all cookies")
RES_ADD_STRING(TXT_WWW_CLEAR_SUCCESS, "Cleared")
RES_ADD_STRING(TXT_WWW_CLEAR_CACHE_SUCCESS, "All caches have been cleared")
RES_ADD_STRING(TXT_WWW_CLEAR_COOKIES_SUCCESS, "All Cookies have been cleared")
//RES_ADD_STRING(TXT_WWW_CLEAR_WEBDATA_SUCCESS, "Delete Successfully")     //replaced by common ID TXT_COMMON_DELETESUCESS
RES_ADD_STRING(TXT_WWW_SET_CACHE,"Cache")
RES_ADD_STRING(TXT_WWW_CACHE_MODE,"Mode")
RES_ADD_STRING(TXT_WWW_IF_USE_DISK_CACHE,"Disk Cache")
//RES_ADD_STRING(TXT_WWW_CLEAR_CACHE,"Clear cache")               //replaced by common ID TXT_COMMON_COMMON_CLEARCACHE
RES_ADD_STRING(TXT_WWW_CLOSE_CACHE,"Close cache")
RES_ADD_STRING(TXT_WWW_NETWORK_PRIORITY,"Network priority")
RES_ADD_STRING(TXT_WWW_CACHE_PRIORITY,"Cache priority")
RES_ADD_STRING(TXT_WWW_ONLY_USE_CACHE,"Use cache only")
//RES_ADD_STRING(TXT_WWW_OPEN,"Open")              //replaced by common ID TXT_COMMON_STARTUP
//RES_ADD_STRING(TXT_WWW_CLOSE,"Close")            //replaced by common ID TXT_COMMON_CLOSE     
RES_ADD_STRING(TXT_WWW_NO_HISTORY,"No history")
RES_ADD_STRING(TXT_COMMON_CONNECT_COMN,"Connect")
//RES_ADD_STRING(TXT_WWW_DELETE,"Delete")      //replaced by common ID TXT_DELETE
RES_ADD_STRING(TXT_WWW_SEND_LINK,"Send linkage")
RES_ADD_STRING(TXT_WWW_MOVE_UP,"Upward")
RES_ADD_STRING(TXT_WWW_MOVE_DOWN,"Downward")
RES_ADD_STRING(TXT_WWW_SHOW_ADDRESS,"Show address")
//RES_ADD_STRING(TXT_WWW_DELETE_CUR,"Delete")      //replaced by common ID TXT_DELETE
RES_ADD_STRING(TXT_WWW_DELETE_CURDAY,"Delete Today's history")
//RES_ADD_STRING(TXT_WWW_DELETE_ALL,"Delete all")        //replaced by common ID TXT_DELALL
RES_ADD_STRING(TXT_WWW_VIA_SMS,"Via SMS")
RES_ADD_STRING(TXT_WWW_VIA_MMS,"Via MMS")
//RES_ADD_STRING(TXT_WWW_ENSURE_DELETE,"Delete")       //replaced by common ID TXT_COMMON_CONFIRM_DELETE
//RES_ADD_STRING(TXT_WWW_HIS_TITLE,"Title:")  //replaced by common ID TXT_COMM_TITLE
//RES_ADD_STRING(TXT_WWW_HIS_URL,"URL:")    //replaced by common ID TXT_COMMON_URL
//RES_ADD_STRING(TXT_WWW_DELETE_SUCCESS,"Deleted")    //replaced by common ID TXT_DELETED
//RES_ADD_STRING(TXT_WWW_SORT,"Sort")           //replaced by common ID TXT_COMMON_SORT
//RES_ADD_STRING(TXT_WWW_DATE,"Date")  //replaced by common ID TXT_DATE
RES_ADD_STRING(TXT_WWW_NAME,"Name")
RES_ADD_STRING(TXT_WWW_CERTIFICATE,"Certification")
RES_ADD_STRING(TXT_WWW_SET_VIEW,"View mode")
RES_ADD_STRING(TXT_WWW_FULL_VIEW,"Full view")
RES_ADD_STRING(TXT_WWW_TEXT_VIEW,"Text view")
RES_ADD_STRING(TXT_WWW_FAST_VIEW,"Fast view")
RES_ADD_STRING(TXT_WWW_SMART_VIEW,"Smart view")
RES_ADD_STRING(TXT_WWW_OWNER_COUNTRY,"Owner country:")
RES_ADD_STRING(TXT_WWW_OWNER_ORGANIZE,"Owner organization:")
RES_ADD_STRING(TXT_WWW_OWNER_UNIT,"Owner company:")
RES_ADD_STRING(TXT_WWW_OWNER_NAME,"Owner name:")
RES_ADD_STRING(TXT_WWW_ISSUER_COUNTRY,"Issuer country:")
RES_ADD_STRING(TXT_WWW_ISSUER_ORGANIZE,"Issuer organization:")
RES_ADD_STRING(TXT_WWW_ISSUER_UNIT,"Issuer company:")
RES_ADD_STRING(TXT_WWW_ISSUER_NAME,"Issuer name:")
RES_ADD_STRING(TXT_WWW_VALID_BEGIN,"Validation begin:")
RES_ADD_STRING(TXT_WWW_VALID_END,"Validation end:")
RES_ADD_STRING(TXT_WWW_SERIAL_NUM,"Serial number:")
RES_ADD_STRING(TXT_WWW_CERT_ATTRIBUTE,"Certification attribution")
//RES_ADD_STRING(TXT_WWW_OPEN_PAGEMEMO,"Open")  //replaced by common ID TXT_COMM_OPEN
//RES_ADD_STRING(TXT_WWW_VIEW_ATTRIBUTE,"View")  //replaced by common ID TXT_VIEW
//RES_ADD_STRING(TXT_WWW_IMPORT_CERT,"Import")  //replaced by common ID TXT_COMMON_IMPORT
RES_ADD_STRING(TXT_WWW_HISTORY_EMPTY,"Empty")
RES_ADD_STRING(TXT_WWW_PAGEMEMO_EMPTY,"Empty")
//RES_ADD_STRING(TXT_WWW_DISPLAY_OPT,"Display option")    //replaced by common ID TXT_DISPLAY_OPTION
RES_ADD_STRING(TXT_WWW_SCRIPT,"Script")
//RES_ADD_STRING(TXT_WWW_ANIMATION,"Animation")  //replaced by common ID TXT_COMM_ANIMAITON
//RES_ADD_STRING(TXT_WWW_PHOTO,"Picture")  //replaced by common ID TXT_COMMON_PIC
RES_ADD_STRING(TXT_WWW_TABLE,"Table")
RES_ADD_STRING(TXT_WWW_POPUPWIN,"Popup win")
RES_ADD_STRING(TXT_WWW_DISPLAY,"Display")
RES_ADD_STRING(TXT_WWW_NODISPLAY,"No display")
RES_ADD_STRING(TXT_WWW_JAVA_SCRIPT,"JavaScript")
RES_ADD_STRING(TXT_WWW_ECMA_SCRIPT,"ECMAScript MP")
RES_ADD_STRING(TXT_WWW_ENABLE,"Enable")
//RES_ADD_STRING(TXT_WWW_DISABLE,"Disable")     //replaced by common ID TXT_COMMON_COMMON_DISABLE
RES_ADD_STRING(TXT_WWW_WEBDATA,"Web data")
RES_ADD_STRING(TXT_WWW_AUTO,"Auto")
RES_ADD_STRING(TXT_WWW_CLEAR_WEBDATA,"Clear web data")
//RES_ADD_STRING(TXT_WWW_DEFAULT_SET,"Settings reset")           //replaced by common ID TXT_COMMON_SET_RESET
//RES_ADD_STRING(TXT_WWW_IS_RESET,"Restored to initial settings")    //replaced by common ID TXT_RESET_QUERY
RES_ADD_STRING(TXT_WWW_RESET_SUCCESS,"Reset")
RES_ADD_STRING(TXT_WWW_IS_DELETE_CUR_HISTORY,"Delete current history")
RES_ADD_STRING(TXT_WWW_IS_DELETE_ALL_HISTORY,"Delete all history")
//RES_ADD_STRING(TXT_WWW_SET_SUCCESS,"Set successfully")         //replaced by common ID TXT_SET_SUCCESS
//RES_ADD_STRING(TXT_WWW_ACCOUNT,"Internet account")               //replaced by common ID TXT_COMMON_WWW_ACCOUNT
RES_ADD_STRING(TXT_WWW_ACCOUNT1,"Sim1 account")
RES_ADD_STRING(TXT_WWW_ACCOUNT2,"Sim2 account")
RES_ADD_STRING(TXT_WWW_PAGEMEMO_FULL,"Pagememo is full,delete first")
RES_ADD_STRING(TXT_WWW_WML_SCRIPT,"WMLScript")
RES_ADD_STRING(TXT_WWW_CHARSET,"Char set")
//RES_ADD_STRING(TXT_WWW_CHARSET_AUTO,"Change automatically")  //replaced by common ID TXT_COMMON_AUTO_SELECT
RES_ADD_STRING(TXT_WWW_CHARSET_US_ASCII,"US_ASCII")
RES_ADD_STRING(TXT_WWW_CHARSET_SHIFT_JIS,"SHIFT_JIS")
RES_ADD_STRING(TXT_WWW_CHARSET_EUC_JP,"EUC_JP")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_2022_JP,"ISO_2022_JP")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_1,"ISO_8859_1")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_15,"ISO_8859_15")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_1252,"WINDOWS_1252")
RES_ADD_STRING(TXT_WWW_CHARSET_EUC_KR,"EUC_KR")
RES_ADD_STRING(TXT_WWW_CHARSET_UHC,"UHC")
RES_ADD_STRING(TXT_WWW_CHARSET_GB2312,"GB2312")
RES_ADD_STRING(TXT_WWW_CHARSET_GBK,"GBK")
RES_ADD_STRING(TXT_WWW_CHARSET_GB18030,"GB18030")
RES_ADD_STRING(TXT_WWW_CHARSET_BIG5,"BIG5")
RES_ADD_STRING(TXT_WWW_CHARSET_BIG5_HKSCS,"BIG5_HKSCS")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_4,"ISO_8859_4")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_1257,"WINDOWS_1257")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_2,"ISO_8859_2")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_1250,"WINDOWS_1250")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_5,"ISO_8859_5")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_1251,"WINDOWS_1251")
RES_ADD_STRING(TXT_WWW_CHARSET_KOI8_R,"KOI8_R")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_7,"ISO_8859_7")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_1253,"WINDOWS_1253")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_10,"ISO_8859_10")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_3,"ISO_8859_3")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_874,"WINDOWS_874")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_9,"ISO_8859_9")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_1254,"WINDOWS_1254")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_6,"ISO_8859_6")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_1256,"WINDOWS_1256")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_8,"ISO_8859_8")
RES_ADD_STRING(TXT_WWW_CHARSET_ISO_8859_8_I,"ISO_8859_8_I")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_1255,"WINDOWS_1255")
RES_ADD_STRING(TXT_WWW_CHARSET_VISCII,"VISCII")
RES_ADD_STRING(TXT_WWW_CHARSET_WINDOWS_1258,"WINDOWS_1258")
RES_ADD_STRING(TXT_WWW_CHARSET_UTF_8,"UTF_8")
RES_ADD_STRING(TXT_WWW_CHARSET_UTF_16BE,"UTF_16BE")
RES_ADD_STRING(TXT_WWW_CHARSET_UTF_16LE,"UTF_16LE")
RES_ADD_STRING(TXT_WWW_CHARSET_UCS_2BE,"UCS_2BE")
RES_ADD_STRING(TXT_WWW_CHARSET_UCS_2LE,"UCS_2LE")
RES_ADD_STRING(TXT_WWW_CHARSET_UCS_4BE,"UCS_4BE")
RES_ADD_STRING(TXT_WWW_CHARSET_UCS_4LE,"UCS_4LE")
RES_ADD_STRING(TXT_WWW_PAGE_ZOOM_PERCENT_150,"150%")
RES_ADD_STRING(TXT_WWW_PAGE_ZOOM_PERCENT_125,"125%")
//RES_ADD_STRING(TXT_WWW_PAGE_ZOOM_PERCENT_100,"100%") //replaced by common ID TXT_COMM_100PERCENT
//RES_ADD_STRING(TXT_WWW_PAGE_ZOOM_PERCENT_75,"75%")  //replaced by common ID TXT_COMM_75PERCENT
//RES_ADD_STRING(TXT_WWW_PAGE_ZOOM_PERCENT_50,"50%")  //replaced by common ID TXT_COMM_50PERCENT
RES_ADD_STRING(TXT_WWW_POINTER_MODE,"Appearence of the pointer")
RES_ADD_STRING(TXT_WWW_POINTER_MODE_NORMAL,"Normal")
RES_ADD_STRING(TXT_WWW_POINTER_MODE_VP,"Virtual Pointer")
RES_ADD_STRING(TXT_WWW_BOOKMARK_QUERY_REPLACE,"Bookmark has existed,replace or not")
RES_ADD_STRING(TXT_WWW_BOOKMARK_EXIST,"Bookmark has existed")

//Browser page
//RES_ADD_STRING(TXT_WWW_ALLOW_NETWORK_ACCESS,"Allow to access network")    //replaced by local common ID TXT_WWW_ALLOW_NET_ACCESS 
RES_ADD_STRING(TXT_WWW_CLOSE_WEBPAGE,"Close current page")
RES_ADD_STRING(TXT_WWW_PAGE_LOADING,"Page loading...")
//RES_ADD_STRING(TXT_WWW_BROWSER_OPEN,"Open") //replaced by common ID TXT_COMM_OPEN
//RES_ADD_STRING(TXT_WWW_BROWSER_OPEN_URL,"Web site")  //replaced by common ID TXT_URL_ADRESS
RES_ADD_STRING(TXT_WWW_PAGE_PILOT,"Pilot")
//RES_ADD_STRING(TXT_WWW_PAGE_FORWARD,"Forward")               //replaced by common ID TXT_COMMON_COMMON_FORWARD
//RES_ADD_STRING(TXT_WWW_PAGE_BACK,"Back")                     //replaced by common ID TXT_COMMON_COMMON_BACK
RES_ADD_STRING(TXT_WWW_PAGE_FULL_DISPLAY,"Full display")
RES_ADD_STRING(TXT_WWW_PAGE_HORIZONTAL_DISPLAY,"H/V Switch")
RES_ADD_STRING(TXT_WWW_PAGE_NAVIGATION,"Web page navigation")
//RES_ADD_STRING(TXT_WWW_PAGE_SEARCH,"Search")  //replaced by common ID TXT_COMM_SEARCH
//RES_ADD_STRING(TXT_WWW_PAGE_COPY,"Copy")          //replaced by common ID TXT_COMMON_COPY
//RES_ADD_STRING(TXT_WWW_START,"Start")       //replaced by common ID TXT_COMMON_START
//RES_ADD_STRING(TXT_WWW_END,"End")        //replaced by common ID TXT_COMMON_COMMON_END
RES_ADD_STRING(TXT_WWW_COPY_NOTIFICATION,"Please chose Start and End point")
RES_ADD_STRING(TXT_WWW_COPY_SUCCESS,"Copied successfully")
RES_ADD_STRING(TXT_WWW_PAGE_PROPERTY,"Page property")
//RES_ADD_STRING(TXT_WWW_DOWNLOAD_MANAGE,"Download manage")    //replaced by common ID TXT_DOWNLOAD_MANAGER
RES_ADD_STRING(TXT_WWW_SAVE_AS,"Save as")
//RES_ADD_STRING(TXT_WWW_WINDOW,"Web page")    //replaced by common ID TXT_WEBPAGE
RES_ADD_STRING(TXT_WWW_NEW_WINDOW,"New web page")
RES_ADD_STRING(TXT_WWW_WINDOW_SWITCH,"Switch web page")
RES_ADD_STRING(TXT_WWW_CLOSE_WINDOW,"Close current page")
RES_ADD_STRING(TXT_WWW_PAGE_ZOOM,"Zoom")
RES_ADD_STRING(TXT_WWW_SAVE_BOOKMARK,"Bookmark")
//RES_ADD_STRING(TXT_WWW_WEBPAGE,"Web page")    //replaced by common ID TXT_WEBPAGE
RES_ADD_STRING(TXT_WWW_PAGE_MEMO,"Saved web pages")
//RES_ADD_STRING(TXT_WWW_BROWSER_EXIT,"Exit borwser")    //replaced by common ID  TXT_EXIT_BROWSER
RES_ADD_STRING(TXT_WWW_NO_MATCH_TEXT,"No matched text")
RES_ADD_STRING(TXT_WWW_PAGE_MIME_TYPE,"MIME type:")
RES_ADD_STRING(TXT_WWW_PAGE_EXIT_FULL_DISPLAY,"Normal display")

RES_ADD_STRING(TXT_WWW_NO_IMAGE,"No Image")
RES_ADD_STRING(TXT_WWW_GET_DATA_FAIL,"Enter picture mode by pressing 1")
RES_ADD_STRING(TXT_WWW_GET_IMAGE_FAIL,"Fail to get image data")

//RES_ADD_STRING(TXT_WWW_FILE_NAME,"File name:")  //replaced by common ID TXT_INPUT_FILE_NAME
//RES_ADD_STRING(TXT_WWW_FILE_SAVE_TO,"Save to:") //replaced by common ID TXT_COMM_FILE_SAVE_TO
RES_ADD_STRING(TXT_WWW_EMPTY_FILE_NAME,"File name is empty")
RES_ADD_STRING(TXT_WWW_EMPTY_PATH_NAME,"Path is empty")
//RES_ADD_STRING(TXT_WWW_FILENAME_REPEAT,"File name has existed")    //replaced by common ID TXT_FILE_EXISTED
RES_ADD_STRING(TXT_WWW_ALLOW_NET_ACCESS,"Allow to access network")
//RES_ADD_STRING(TXT_WWW_DONE,"Set successfully")        //replaced by common ID TXT_SET_SUCCESS
RES_ADD_STRING(TXT_WWW_MAKE_CALL,"Setup call")
RES_ADD_STRING(TXT_WWW_INPUT_EMPTY,"Input no character")

//error notify
//RES_ADD_STRING(TXT_WWW_BROWSER_ERROR_NOMEMORY,"No memory")  //replaced by common ID TXT_COMMON_NO_MEMORY
//RES_ADD_STRING(TXT_WWW_BROWSER_ERROR_NOMEMORY_IMAGE,"No memory")  //replaced by common ID TXT_COMMON_NO_MEMORY
//RES_ADD_STRING(TXT_WWW_BROWSER_ERROR_NOMEMORY_AWS,"No memory")  //replaced by common ID TXT_COMMON_NO_MEMORY
RES_ADD_STRING(TXT_WWW_BROWSER_ERROR_TOOMANY_PANES,"Too many panes，cannot new more")
//RES_ADD_STRING(TXT_WWW_BROWSER_ERROR_TOTAL_SIZEOVER,"Content size over")    //replaced by local common ID TXT_WWW_CONTENT_E_SIZEOVER 
RES_ADD_STRING(TXT_WWW_BROWSER_ERROR_BADURL,"Bad URL")
RES_ADD_STRING(TXT_WWW_BROWSER_ERROR_BADMIMETYPE,"Unsupported MIME type")
RES_ADD_STRING(TXT_WWW_BROWSER_ERROR_MIXEDSECURETYPE,"Unsupported HTTP and HTTPS mixage")
//RES_ADD_STRING(TXT_WWW_BROWSER_ERROR_INPUT_REQUIRED,"Input error")  //replaced by common ID TXT_INPUT_ERROR
//RES_ADD_STRING(TXT_WWW_ERROR_UNKNOWN,"Unkown error")    //replaced by common ID TXT_UNKNOWN_ERROR

//RES_ADD_STRING(TXT_WWW_HTTP_E_DIAL_FAIL,"Dial failed")  //replaced by common ID TXT_DIAL_FAILED
RES_ADD_STRING(TXT_WWW_HTTP_E_DNS_INVAL,"Invalid DNS")
RES_ADD_STRING(TXT_WWW_HTTP_E_DNS_NOSERVER,"No DNS server")
RES_ADD_STRING(TXT_WWW_HTTP_E_DNS_TIMEDOUT,"DNS timeout")
RES_ADD_STRING(TXT_WWW_HTTP_E_DNS_NOTFOUND,"DNS not found")
RES_ADD_STRING(TXT_WWW_HTTP_E_TCP_OPEN,"TCP open failed")
RES_ADD_STRING(TXT_WWW_HTTP_E_TCP_CONNECT,"TCP connection failed")
RES_ADD_STRING(TXT_WWW_HTTP_E_TCP_READ,"TCP read Failed")
RES_ADD_STRING(TXT_WWW_HTTP_E_TCP_WRITE,"TCP write failed")
RES_ADD_STRING(TXT_WWW_HTTP_E_SSL_CONNECT,"SSL connection failed")
RES_ADD_STRING(TXT_WWW_HTTP_E_SSL_HANDSHAKE,"SSL handshake failed")
RES_ADD_STRING(TXT_WWW_HTTP_E_SSL_READ,"SSL read failed")
RES_ADD_STRING(TXT_WWW_HTTP_E_SSL_WRITE,"SSL write failed")
RES_ADD_STRING(TXT_WWW_HTTP_E_REQTIMEDOUT,"HTTP request timeout")
RES_ADD_STRING(TXT_WWW_HTTP_E_RSPTIMEDOUT,"HTTP response timeout")
RES_ADD_STRING(TXT_WWW_HTTP_E_CACHE_NONE,"Cache is empty")
RES_ADD_STRING(TXT_WWW_HTTP_E_CACHE_EXPIRE,"Cache expired")
//RES_ADD_STRING(TXT_WWW_HTTP_E_AUTH_UNKNOWN,"License error")    //replaced by common ID TXT_LICENSE_ERROR
//RES_ADD_STRING(TXT_WWW_HTTP_E_AUTH_NOHEADER,"License error")    //replaced by common ID TXT_LICENSE_ERROR
RES_ADD_STRING(TXT_WWW_HTTP_E_AUTH_FORMAT,"License format error")
RES_ADD_STRING(TXT_WWW_HTTP_E_AUTH_IGNORED,"License ignored")
RES_ADD_STRING(TXT_WWW_HTTP_E_REDIRECT_FORMAT,"Redirection format error")
RES_ADD_STRING(TXT_WWW_HTTP_E_REDIRECT_CANCELED,"Redirction canceled")
RES_ADD_STRING(TXT_WWW_HTTP_E_REDIRECT_IGNORED,"Redirection ignored")
RES_ADD_STRING(TXT_WWW_HTTP_E_REQ_HEADER_SIZEOVER,"HTTP request header size over")
RES_ADD_STRING(TXT_WWW_HTTP_E_REQ_BODY_SIZEOVER,"HTTP request body size over")
RES_ADD_STRING(TXT_WWW_HTTP_E_RSP_HEADER_SIZEOVER,"HTTP response header size over")
RES_ADD_STRING(TXT_WWW_HTTP_E_REQ_TOOMANYCONTINUE,"Too many HTTP requests")
RES_ADD_STRING(TXT_WWW_HTTP_E_TLS_INTOLERANT,"Unsupport TLS")
RES_ADD_STRING(TXT_WWW_HTTP_E_CONTENT_ENCODING,"Content encoding error")
//RES_ADD_STRING(TXT_WWW_TYPE_NOT_SUPPORT,"Nonsupport file type") //replaced by common ID TXT_COMM_TYPE_NOT_SUPPORT
//RES_ADD_STRING(TXT_WWW_SERVER_ERROR,"Server not connected")  //replaced by common ID TXT_COMM_SERVER_ERROR
RES_ADD_STRING(TXT_WWW_MEMORY_ALERT,"The webage is too large, it will be display abnormally")

RES_ADD_STRING(TXT_WWW_CONTENT_E_SIZEOVER,"Content size over")
RES_ADD_STRING(TXT_WWW_CONTENT_E_NO_CONTENT,"No content")
RES_ADD_STRING(TXT_WWW_CONTENT_E_TOOMANYREDIRECT,"Too many redirections")
RES_ADD_STRING(TXT_WWW_CONTENT_E_TOOMANYAUTHN,"Too many error verifications")
RES_ADD_STRING(TXT_WWW_CONTENT_E_BADMIMETYPE,"Bad MIME type")
RES_ADD_STRING(TXT_WWW_SAVE_FAILED,"Cannot Save for web information unloaded")
RES_ADD_STRING(TXT_WWW_REFRESH_FAILED,"Cannot refresh for web information unloaded")
RES_ADD_STRING(TXT_WWW_SAVE_IMAGE_QUERY,"Please chose picture，then save by WEB key")
RES_ADD_STRING(TXT_WWW_CLEAN_INPUT_HISTORY,"Clean input history")
//RES_ADD_STRING(TXT_WWW_CALL,"CALL") //replaced by common ID TXT_COMM_CALL
RES_ADD_STRING(TXT_WWW_SET_LINK_SUCCESS,"Set successfully，It works afer restarting browser")
RES_ADD_STRING(TXT_WWW_FOLDER_UP,"...")
//RES_ADD_STRING(TXT_WWW_FOLDER_ROOT,"\/")
//RES_ADD_STRING(TXT_WWW_BOOKMARK_ADD_BOOKMARK,"Bookmark")  //replaced by common ID TXT_COMMON_BOOKMARKS
RES_ADD_STRING(TXT_WWW_BOOKMARK_ADD_DIR,"Catalog")
RES_ADD_STRING(TXT_WWW_BOOKMARK_MANAGE_MOVE_TO,"Move to catalog")
RES_ADD_STRING(TXT_WWW_BOOKMARK_SAME_PATH,"Same catalog ")
RES_ADD_STRING(TXT_WWW_BOOKMARK_NEW_DIR_TITLE,"New catalog")
RES_ADD_STRING(TXT_WWW_BOOKMARK_EDIT_DIR_TITLE,"Modify catalog")
RES_ADD_STRING(TXT_WWW_BOOKMARK_FAIL_URL,"Invalid URL")
RES_ADD_STRING(TXT_COMMON_FOLDER_FULL,"Catalog Full")
RES_ADD_STRING(TXT_WWW_BOOKMARK_ENSURE_DELETE_DIR,"Delete the catalog")
RES_ADD_STRING(TXT_WWW_BOOKMARK_MOVE_SUCC,"Move Success")
RES_ADD_STRING(TXT_WWW_BOOKMARK_DIR_TITLE,"Catalog name:")
RES_ADD_STRING(TXT_WWW_BOOKMARK_DIR_EXIST,"Catalog has existed")
//RES_ADD_STRING(TXT_WWW_BOOKMARK_INVALID_TITLE,"Invalid Title") //replaced by common ID TXT_COMM_INVALID_TITLE
RES_ADD_STRING(TXT_WWW_OPEN_HOMEPAGE,"Open Homepage")
//RES_ADD_STRING(TXT_WWW_HOMEPAGE,"Homepage")  //replaced by common ID TXT_COMMON_HOMEPAGE
RES_ADD_STRING(TXT_WWW_AS_HOMEPAGE,"As Homepage")
//RES_ADD_STRING(TXT_WWW_SET_HOMEPAGE,"Homepage")  //replaced by common ID TXT_COMMON_HOMEPAGE_SETTING

RES_ADD_STRING(TXT_WWW_PAGEUP,"Pageup")
RES_ADD_STRING(TXT_WWW_PAGEDOWN,"Pagedown")
RES_ADD_STRING(TXT_WWW_ZOOMIN,"Zoom in")
RES_ADD_STRING(TXT_WWW_ZOOMOUT,"Zoom out")
RES_ADD_STRING(TXT_WWW_SWITCH_WINDOW,"Switch window")


//RES_ADD_STRING(TXT_WWW_SELECT_NETWORK,"网络选择")    //replaced by common ID TXT_NETWORK_SELECT 
RES_ADD_STRING(TXT_WWW_SELECT_NETWORK_NOTIFICATION,"WLAN不可用，是否使用移动网？")
RES_ADD_STRING(TXT_WWW_NEVER_NOTIFY,"以后不再提示")
RES_ADD_STRING(TXT_WWW_WINDOW_MANAGER,"Window manager")
RES_ADD_STRING(TXT_WWW_OPEN_SUB_WIN,"Open")
RES_ADD_STRING(TXT_WWW_NEW_SUB_WIN,"New window")
RES_ADD_STRING(TXT_WWW_CLOSE_SUB_WIN,"Close window")
//]]define string infomation


//[[define data infomation
//]]define data infomation
#endif
