/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#ifndef _CP_CLKRST_ASM_ARM_H_
#define _CP_CLKRST_ASM_ARM_H_

//THIS FILE HAS BEEN GENERATED WITH COOLWATCHER. PLEASE EDIT WITH CARE !



//==============================================================================
// cp_clkrst
//------------------------------------------------------------------------------
///
//==============================================================================
#if defined(REG_ADDRESS_FOR_GGE)
#define REG_CLKRST_BASE            0x05081000
#else
#define REG_CLKRST_BASE            0x50081000
#endif

#define REG_CLKRST_CLKSEL             0x00000000
#define REG_CLKRST_CLKSEL_SET         0x00000004
#define REG_CLKRST_CLKSEL_CLR         0x00000008
#define REG_CLKRST_CLKDIV_ZSP         0x0000000C
#define REG_CLKRST_CLKDIV_LTE         0x00000010
#define REG_CLKRST_CLKEN_BB_SYSCTRL    0x00000014
#define REG_CLKRST_CLKEN_BB_SYSCTRL_SET    0x00000018
#define REG_CLKRST_CLKEN_BB_SYSCTRL_CLR    0x0000001C
#define REG_CLKRST_CLKEN_ZSP          0x00000020
#define REG_CLKRST_CLKEN_ZSP_SET      0x00000024
#define REG_CLKRST_CLKEN_ZSP_CLR      0x00000028
#define REG_CLKRST_CLKEN_LTE          0x0000002C
#define REG_CLKRST_CLKEN_LTE_SET      0x00000030
#define REG_CLKRST_CLKEN_LTE_CLR      0x00000034
#define REG_CLKRST_CLKEN_ZSPCORE_MODE    0x00000038
#define REG_CLKRST_CLKEN_ZSP_AXIDMA_MODE    0x0000003C
#define REG_CLKRST_RSTCTRL_BB_SYSCTRL    0x00000040
#define REG_CLKRST_RSTCTRL_BB_SYSCTRL_SET    0x00000044
#define REG_CLKRST_RSTCTRL_BB_SYSCTRL_CLR    0x00000048
#define REG_CLKRST_RSTCTRL_ZSP        0x0000004C
#define REG_CLKRST_RSTCTRL_ZSP_SET    0x00000050
#define REG_CLKRST_RSTCTRL_ZSP_CLR    0x00000054
#define REG_CLKRST_RSTCTRL_LTE        0x00000058
#define REG_CLKRST_RSTCTRL_LTE_SET    0x0000005C
#define REG_CLKRST_RSTCTRL_LTE_CLR    0x00000060
#define REG_CLKRST_ZSP_SOFT_RST       0x00000064
#define REG_CLKRST_LTE_SOFT_RST       0x00000068
#define REG_CLKRST_ZSP_AXILPCNT       0x0000006C
#define REG_CLKRST_ZSP_BUSLPMC        0x00000070
#define REG_CLKRST_ZSP_BUSLPMC_SET    0x00000074
#define REG_CLKRST_ZSP_BUSLPMC_CLR    0x00000078
#define REG_CLKRST_ZSP_BUSFORCELPMC    0x0000007C
#define REG_CLKRST_ZSP_BUSFORCELPMC_SET    0x00000080
#define REG_CLKRST_ZSP_BUSFORCELPMC_CLR    0x00000084
#define REG_CLKRST_CLKEN_MAILBOX_MODE    0x00000088
#define REG_CLKRST_CLKEN_LTE_INTF     0x0000008C
#define REG_CLKRST_CLKEN_LTE_INTF_SET    0x00000090
#define REG_CLKRST_CLKEN_LTE_INTF_CLR    0x00000094
#define REG_CLKRST_LTE_AUTOGATE_MODE    0x00000098
#define REG_CLKRST_LTE_AUTOGATE_EN    0x0000009C
#define REG_CLKRST_LTE_AUTOGATE_EN_SET    0x000000A0
#define REG_CLKRST_LTE_AUTOGATE_EN_CLR    0x000000A4
#define REG_CLKRST_LTE_AUTOGATE_DELAY_NUM    0x000000A8

//CLKSEL
#define CP_CLKRST_RESERVED_0(n)    (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_IDLE_H_SEL(n)    (((n)&3)<<4)
#define CP_CLKRST_ZSP_WD_SEL       (1<<3)
#define CP_CLKRST_BB_SYSCTRL_WD_SEL (1<<2)
#define CP_CLKRST_SLOW_SEL_480M    (1<<1)
#define CP_CLKRST_SLOW_SEL_122M    (1<<0)

//CLKSEL_SET
#define CP_CLKRST_RESERVED_0_X1(n) (((n)&0x7FFFFFF)<<5)
#define CP_CLKRST_CLKSELSET(n)     (((n)&31)<<0)

//CLKSEL_CLR
//#define CP_CLKRST_RESERVED_0_X1(n) (((n)&0x7FFFFFF)<<5)
#define CP_CLKRST_CLKSELCLEAR(n)   (((n)&31)<<0)

//CLKDIV_ZSP
#define CP_CLKRST_RESERVED_0_X2(n) (((n)&0xFFFFFFF)<<4)
#define CP_CLKRST_ZSP_CD(n)        (((n)&15)<<0)

//CLKDIV_LTE
//#define CP_CLKRST_RESERVED_0_X2(n) (((n)&0xFFFFFFF)<<4)
#define CP_CLKRST_LTE_CD(n)        (((n)&15)<<0)

//CLKEN_BB_SYSCTRL
//#define CP_CLKRST_RESERVED_0_X1(n) (((n)&0x7FFFFFF)<<5)
#define CP_CLKRST_CLKEN_CP_WD      (1<<4)
#define CP_CLKRST_CLKEN_IDLE       (1<<3)
#define CP_CLKRST_CLKEN_MAILBOX    (1<<2)
#define CP_CLKRST_CLKEN_PWRCTRL    (1<<1)
#define CP_CLKRST_CLKEN_SYSREG     (1<<0)

//CLKEN_BB_SYSCTRL_SET
//#define CP_CLKRST_RESERVED_0_X1(n) (((n)&0x7FFFFFF)<<5)
#define CP_CLKRST_CLKEN_BB_SYSCTRLSET(n) (((n)&31)<<0)

//CLKEN_BB_SYSCTRL_CLR
//#define CP_CLKRST_RESERVED_0_X1(n) (((n)&0x7FFFFFF)<<5)
#define CP_CLKRST_CLKEN_BB_SYSCTRLCLEAR(n) (((n)&31)<<0)

//CLKEN_ZSP
//#define CP_CLKRST_RESERVED_0(n)  (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_CLKEN_AUD_DFT    (1<<5)
#define CP_CLKRST_CLKEN_WD         (1<<4)
#define CP_CLKRST_CLKEN_BUSMON     (1<<3)
#define CP_CLKRST_CLKEN_ZIRQ       (1<<2)
#define CP_CLKRST_CLKEN_AXIDMA     (1<<1)
#define CP_CLKRST_CLKEN_ZSPCORE    (1<<0)

//CLKEN_ZSP_SET
//#define CP_CLKRST_RESERVED_0(n)  (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_CLKEN_ZSPSET(n)  (((n)&0x3F)<<0)

//CLKEN_ZSP_CLR
//#define CP_CLKRST_RESERVED_0(n)  (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_CLKEN_ZSPCLEAR(n) (((n)&0x3F)<<0)

//CLKEN_LTE
#define CP_CLKRST_RESERVED_0_X3(n) (((n)&0x7FFFF)<<13)
#define CP_CLKRST_CLKEN_RXCAPT     (1<<12)
#define CP_CLKRST_CLKEN_RFAD       (1<<11)
#define CP_CLKRST_CLKEN_DLFFT      (1<<10)
#define CP_CLKRST_CLKEN_CSIRS      (1<<9)
#define CP_CLKRST_CLKEN_PUSCH      (1<<8)
#define CP_CLKRST_CLKEN_ULDFT      (1<<7)
#define CP_CLKRST_CLKEN_OTDOA      (1<<6)
#define CP_CLKRST_CLKEN_IDDET      (1<<5)
#define CP_CLKRST_CLKEN_MEASPWR    (1<<4)
#define CP_CLKRST_CLKEN_LDTC1      (1<<3)
#define CP_CLKRST_CLKEN_LDTC       (1<<2)
#define CP_CLKRST_CLKEN_COEFF      (1<<1)
#define CP_CLKRST_CLKEN_TXRX       (1<<0)

//CLKEN_LTE_SET
//#define CP_CLKRST_RESERVED_0_X3(n) (((n)&0x7FFFF)<<13)
#define CP_CLKRST_CLKEN_LTESET(n)  (((n)&0x1FFF)<<0)

//CLKEN_LTE_CLR
//#define CP_CLKRST_RESERVED_0_X3(n) (((n)&0x7FFFF)<<13)
#define CP_CLKRST_CLKEN_LTECLEAR(n) (((n)&0x1FFF)<<0)

//CLKEN_ZSPCORE_MODE
#define CP_CLKRST_RESERVED_0_X4(n) (((n)&0x7FFFFFFF)<<1)
#define CP_CLKRST_MODE             (1<<0)

//CLKEN_ZSP_AXIDMA_MODE
//#define CP_CLKRST_RESERVED_0_X4(n) (((n)&0x7FFFFFFF)<<1)
//#define CP_CLKRST_MODE           (1<<0)

//RSTCTRL_BB_SYSCTRL
//#define CP_CLKRST_RESERVED_0(n)  (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_RSTCTRL_MONITOR  (1<<5)
#define CP_CLKRST_RSTCTRL_CP_WD    (1<<4)
#define CP_CLKRST_RSTCTRL_IDLE     (1<<3)
#define CP_CLKRST_RSTCTRL_MAILBOX  (1<<2)
#define CP_CLKRST_RSTCTRL_PWRCTRL  (1<<1)
#define CP_CLKRST_RSTCTRL_SYSREG   (1<<0)

//RSTCTRL_BB_SYSCTRL_SET
//#define CP_CLKRST_RESERVED_0(n)  (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_RSTCTRL_BB_SYSCTRLSET(n) (((n)&0x3F)<<0)

//RSTCTRL_BB_SYSCTRL_CLR
//#define CP_CLKRST_RESERVED_0(n)  (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_RSTCTRL_BB_SYSCTRLCLEAR(n) (((n)&0x3F)<<0)

//RSTCTRL_ZSP
//#define CP_CLKRST_RESERVED_0(n)  (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_RSTCTRL_AUD_DFT  (1<<5)
#define CP_CLKRST_RSTCTRL_WD       (1<<4)
#define CP_CLKRST_RSTCTRL_BUSMON   (1<<3)
#define CP_CLKRST_RSTCTRL_ZIRQ     (1<<2)
#define CP_CLKRST_RSTCTRL_AXIDMA   (1<<1)
#define CP_CLKRST_RSTCTRL_ZSPCORE  (1<<0)

//RSTCTRL_ZSP_SET
//#define CP_CLKRST_RESERVED_0(n)  (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_RSTCTRL_ZSPSET(n) (((n)&0x3F)<<0)

//RSTCTRL_ZSP_CLR
//#define CP_CLKRST_RESERVED_0(n)  (((n)&0x3FFFFFF)<<6)
#define CP_CLKRST_RSTCTRL_ZSPCLEAR(n) (((n)&0x3F)<<0)

//RSTCTRL_LTE
#define CP_CLKRST_RESERVED_0_X5(n) (((n)&0x3FFFF)<<14)
#define CP_CLKRST_RSTCTRL_RXCAPT   (1<<13)
#define CP_CLKRST_RSTCTRL_RFAD     (1<<12)
#define CP_CLKRST_RSTCTRL_DLFFT    (1<<11)
#define CP_CLKRST_RSTCTRL_CSIRS    (1<<10)
#define CP_CLKRST_RSTCTRL_PUSCH    (1<<9)
#define CP_CLKRST_RSTCTRL_ULDFT    (1<<8)
#define CP_CLKRST_RSTCTRL_OTDOA    (1<<7)
#define CP_CLKRST_RSTCTRL_IDDET    (1<<6)
#define CP_CLKRST_RSTCTRL_MEASPWR  (1<<5)
#define CP_CLKRST_RSTCTRL_LDTC1    (1<<4)
#define CP_CLKRST_RSTCTRL_LDTC     (1<<3)
#define CP_CLKRST_RSTCTRL_COEFF    (1<<2)
#define CP_CLKRST_RSTCTRL_TXRX_RX  (1<<1)
#define CP_CLKRST_RSTCTRL_TXRX_TX  (1<<0)

//RSTCTRL_LTE_SET
//#define CP_CLKRST_RESERVED_0_X5(n) (((n)&0x3FFFF)<<14)
#define CP_CLKRST_RSTCTRL_LTESET(n) (((n)&0x3FFF)<<0)

//RSTCTRL_LTE_CLR
//#define CP_CLKRST_RESERVED_0_X5(n) (((n)&0x3FFFF)<<14)
#define CP_CLKRST_RSTCTRL_LTECLEAR(n) (((n)&0x3FFF)<<0)

//ZSP_SOFT_RST
//#define CP_CLKRST_RESERVED_0_X4(n) (((n)&0x7FFFFFFF)<<1)
#define CP_CLKRST_ZSP_SOFT_RST_CTRL (1<<0)

//LTE_SOFT_RST
//#define CP_CLKRST_RESERVED_0_X4(n) (((n)&0x7FFFFFFF)<<1)
#define CP_CLKRST_LTE_SOFT_RST_CTRL (1<<0)

//ZSP_AXILPCNT
#define CP_CLKRST_RESERVED_0_X6(n) (((n)&0xFFFF)<<16)
#define CP_CLKRST_CNT(n)           (((n)&0xFFFF)<<0)

//ZSP_BUSLPMC
//#define CP_CLKRST_RESERVED_0_X2(n) (((n)&0xFFFFFFF)<<4)
#define CP_CLKRST_BUSLPMC_ZSPCORE  (1<<3)
#define CP_CLKRST_BUSLPMC_PHY      (1<<2)
#define CP_CLKRST_BUSLPMC_SW2      (1<<1)
#define CP_CLKRST_BUSLPMC_SW1      (1<<0)

//ZSP_BUSLPMC_SET
//#define CP_CLKRST_RESERVED_0_X2(n) (((n)&0xFFFFFFF)<<4)
#define CP_CLKRST_ZSP_BUSLPMCSET(n) (((n)&15)<<0)

//ZSP_BUSLPMC_CLR
//#define CP_CLKRST_RESERVED_0_X2(n) (((n)&0xFFFFFFF)<<4)
#define CP_CLKRST_ZSP_BUSLPMCCLEAR(n) (((n)&15)<<0)

//ZSP_BUSFORCELPMC
//#define CP_CLKRST_RESERVED_0_X2(n) (((n)&0xFFFFFFF)<<4)
#define CP_CLKRST_BUSFORCELPMC_ZSPCORE (1<<3)
#define CP_CLKRST_BUSFORCELPMC_PHY (1<<2)
#define CP_CLKRST_BUSFORCELPMC_SW2 (1<<1)
#define CP_CLKRST_BUSFORCELPMC_SW1 (1<<0)

//ZSP_BUSFORCELPMC_SET
//#define CP_CLKRST_RESERVED_0_X2(n) (((n)&0xFFFFFFF)<<4)
#define CP_CLKRST_ZSP_BUSFORCELPMCSET(n) (((n)&15)<<0)

//ZSP_BUSFORCELPMC_CLR
//#define CP_CLKRST_RESERVED_0_X2(n) (((n)&0xFFFFFFF)<<4)
#define CP_CLKRST_ZSP_BUSFORCELPMCCLEAR(n) (((n)&15)<<0)

//CLKEN_MAILBOX_MODE
//#define CP_CLKRST_RESERVED_0_X4(n) (((n)&0x7FFFFFFF)<<1)
//#define CP_CLKRST_MODE           (1<<0)

//CLKEN_LTE_INTF
//#define CP_CLKRST_RESERVED_0_X3(n) (((n)&0x7FFFF)<<13)
#define CP_CLKRST_CLKEN_RXCAPT_INTF (1<<12)
#define CP_CLKRST_CLKEN_RFAD_INTF  (1<<11)
#define CP_CLKRST_CLKEN_DLFFT_INTF (1<<10)
#define CP_CLKRST_CLKEN_CSIRS_INTF (1<<9)
#define CP_CLKRST_CLKEN_PUSCH_INTF (1<<8)
#define CP_CLKRST_CLKEN_ULDFT_INTF (1<<7)
#define CP_CLKRST_CLKEN_OTDOA_INTF (1<<6)
#define CP_CLKRST_CLKEN_IDDET_INTF (1<<5)
#define CP_CLKRST_CLKEN_MEASPWR_INTF (1<<4)
#define CP_CLKRST_CLKEN_LDTC1_INTF (1<<3)
#define CP_CLKRST_CLKEN_LDTC_INTF  (1<<2)
#define CP_CLKRST_CLKEN_COEFF_INTF (1<<1)
#define CP_CLKRST_CLKEN_TXRX_INTF  (1<<0)

//CLKEN_LTE_INTF_SET
//#define CP_CLKRST_RESERVED_0_X3(n) (((n)&0x7FFFF)<<13)
#define CP_CLKRST_CLKEN_LTE_INTFSET(n) (((n)&0x1FFF)<<0)

//CLKEN_LTE_INTF_CLR
//#define CP_CLKRST_RESERVED_0_X3(n) (((n)&0x7FFFF)<<13)
#define CP_CLKRST_CLKEN_LTE_INTFCLEAR(n) (((n)&0x1FFF)<<0)

//LTE_AUTOGATE_MODE
//#define CP_CLKRST_RESERVED_0_X4(n) (((n)&0x7FFFFFFF)<<1)
//#define CP_CLKRST_MODE           (1<<0)

//LTE_AUTOGATE_EN
#define CP_CLKRST_RESERVED_0_X7(n) (((n)&15)<<28)
#define CP_CLKRST_UPLINK_INTF_AUTOGATE_EN (1<<27)
#define CP_CLKRST_DOWNLINK_INTF_AUTOGATE_EN (1<<26)
#define CP_CLKRST_UPLINK_FUNC_AUTOGATE_EN (1<<25)
#define CP_CLKRST_DOWNLINK_FUNC_AUTOGATE_EN (1<<24)
#define CP_CLKRST_RESERVED_1       (1<<23)
#define CP_CLKRST_RESERVED_2       (1<<22)
#define CP_CLKRST_DLFFT_INTF_AUTOGATE_EN (1<<21)
#define CP_CLKRST_CSIRS_INTF_AUTOGATE_EN (1<<20)
#define CP_CLKRST_PUSCH_INTF_AUTOGATE_EN (1<<19)
#define CP_CLKRST_ULDFT_INTF_AUTOGATE_EN (1<<18)
#define CP_CLKRST_OTDOA_INTF_AUTOGATE_EN (1<<17)
#define CP_CLKRST_IDDET_INTF_AUTOGATE_EN (1<<16)
#define CP_CLKRST_MEASPWR_INTF_AUTOGATE_EN (1<<15)
#define CP_CLKRST_LDTC1_INTF_AUTOGATE_EN (1<<14)
#define CP_CLKRST_LDTC_INTF_AUTOGATE_EN (1<<13)
#define CP_CLKRST_COEFF_INTF_AUTOGATE_EN (1<<12)
#define CP_CLKRST_TXRX_INTF_AUTOGATE_EN (1<<11)
#define CP_CLKRST_DLFFT_FUNC_AUTOGATE_EN (1<<10)
#define CP_CLKRST_CSIRS_FUNC_AUTOGATE_EN (1<<9)
#define CP_CLKRST_PUSCH_FUNC_AUTOGATE_EN (1<<8)
#define CP_CLKRST_ULDFT_FUNC_AUTOGATE_EN (1<<7)
#define CP_CLKRST_OTDOA_FUNC_AUTOGATE_EN (1<<6)
#define CP_CLKRST_IDDET_FUNC_AUTOGATE_EN (1<<5)
#define CP_CLKRST_MEASPWR_FUNC_AUTOGATE_EN (1<<4)
#define CP_CLKRST_LDTC1_FUNC_AUTOGATE_EN (1<<3)
#define CP_CLKRST_LDTC_FUNC_AUTOGATE_EN (1<<2)
#define CP_CLKRST_COEFF_FUNC_AUTOGATE_EN (1<<1)
#define CP_CLKRST_TXRX_FUNC_AUTOGATE_EN (1<<0)

//LTE_AUTOGATE_EN_SET
//#define CP_CLKRST_RESERVED_0_X7(n) (((n)&15)<<28)
#define CP_CLKRST_CLKEN_LTE_INTFSET_X1(n) (((n)&0xFFFFFFF)<<0)

//LTE_AUTOGATE_EN_CLR
//#define CP_CLKRST_RESERVED_0_X7(n) (((n)&15)<<28)
#define CP_CLKRST_CLKEN_LTE_INTFCLEAR_X1(n) (((n)&0xFFFFFFF)<<0)

//LTE_AUTOGATE_DELAY_NUM
#define CP_CLKRST_RESERVED_0_X8(n) (((n)&0xFFFFFF)<<8)
#define CP_CLKRST_DELAYCOUNTERNUMBER(n) (((n)&0xFF)<<0)




#endif
