//[[define image infomation
//RES_ADD_IMG(IMAGE_MAIL_INBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_INBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MAIL_OUTBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_OUTBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MAIL_SENTBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_SENTBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MAIL_DRAFTBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_DRAFTBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_MAIL_READ_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_READ_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_UNREAD_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_UNREAD_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_READ_WITH_ACC_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_READ_WITH_ACC_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_UNREAD_WITH_ACC_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_UNREAD_WITH_ACC_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_SERVER_REJECT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_SERVER_REJECT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_SEND_FAIL_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_SEND_FAIL_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_SENDING_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_SENDING_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_WAIT_SEND_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_WAIT_SEND_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_SENT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_SENT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_SENT_WITH_ACC_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_SENT_WITH_ACC_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_DRAFT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_DRAFT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_DRAFT_WITH_ACC_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_DRAFT_WITH_ACC_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_READ_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_READ_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_UNREAD_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_UNREAD_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_READ_WITH_ACC_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_READ_WITH_ACC_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_UNREAD_WITH_ACC_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_UNREAD_WITH_ACC_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_SERVER_REJECT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_SERVER_REJECT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_SEND_FAIL_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_SEND_FAIL_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_SENDING_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_SENDING_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_WAIT_SEND_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_WAIT_SEND_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_SENT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_SENT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_SENT_WITH_ACC_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_SENT_WITH_ACC_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_DRAFT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_DRAFT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MAIL_LOCK_DRAFT_WITH_ACC_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_LOCK_DRAFT_WITH_ACC_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_MAIL_EDIT_FROM,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_EDIT_FROM.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_MAIL_EDIT_TO,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_EDIT_TO.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_MAIL_EDIT_CC,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_EDIT_CC.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_MAIL_EDIT_BCC,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_EDIT_BCC.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_MAIL_EDIT_SUBJECT,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_EDIT_SUBJECT.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_MAIL_EDIT_CONTENT,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_EDIT_CONTENT.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_MAIL_EDIT_ACCESSORY,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_EDIT_ACCESSORY.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_MAIL_EDIT_TIME,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_EDIT_TIME.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_MAIL_ACCOUNT,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_ACCOUNT.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_MAIL_MENU_MAIN_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MAIL_MAIN_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
    
//]]define image infomation

//[[define anim infomation

//]]define anim infomation

//[[define string infomation
RES_ADD_STRING(TXT_MAIL_PUSHMAIL,"PushEmail")
RES_ADD_STRING(TXT_MAIL_WELCOME,"Welcome use 139 Mail")
RES_ADD_STRING(TXT_MAIL_INTRODUCE,"Introduce")
RES_ADD_STRING(TXT_MAIL_ALERT_APPLY,"If apply 139 mailbox PushEmail function?")
RES_ADD_STRING(TXT_MAIL_GET_INFOMATION,"Now get charge infomaition...")
RES_ADD_STRING(TXT_MAIL_CONFIG_REQUEST,"Config request has send.")
RES_ADD_STRING(TXT_MAIL_CHARGE_INFO,"Please contact 10086 to get charge informaition!")
RES_ADD_STRING(TXT_MAIL_NEW,"New mail")
//RES_ADD_STRING(TXT_MAIL_INBOX,"Inbox")    //replaced by common ID TXT_INBOX
//RES_ADD_STRING(TXT_MAIL_OUTBOX,"Outbox")  //replaced by common ID TXT_COMM_OUTBOX
RES_ADD_STRING(TXT_MAIL_SENTBOX,"Sentbox")
RES_ADD_STRING(TXT_MAIL_DRAFT,"Draft")
//RES_ADD_STRING(TXT_MAIL_SYS_SETTING,"System setting")    //replaced by common ID TXT_SYSTEM_SETTING
//RES_ADD_STRING(TXT_MAIL_HELP,"Help")  //replaced by common ID TXT_HELP
RES_ADD_STRING(TXT_MAIL_HELP_CONTENT,"Help Content")
RES_ADD_STRING(TXT_MAIL_ACCOUNT_SETTING,"Account setting")
RES_ADD_STRING(TXT_MAIL_EDIT_OPTION,"Edit option")
//RES_ADD_STRING(TXT_MAIL_SILENT_TIME,"Silent time")     //replaced by common ID TXT_COMMON_SLIENT_TIME
RES_ADD_STRING(TXT_MAIL_ATTACH_DL_OPTION,"Attach download option")
RES_ADD_STRING(TXT_MAIL_DEL_ALL,"Delete all mails")
//RES_ADD_STRING(TXT_MAIL_RESET,"Reset factory setting")    //replaced by common ID TXT_COMMON_RESTORE_FACTORY_SETTINGS
//RES_ADD_STRING(TXT_MAIL_REPLY,"Reply")  //replaced by common ID TXT_REPLY
RES_ADD_STRING(TXT_MAIL_REPLY_ALL,"Reply all")
//RES_ADD_STRING(TXT_MAIL_FORWARD,"Forward")  //replaced by common ID TXT_COMMON_FORWARD
RES_ADD_STRING(TXT_MAIL_FORWARD_CONTENT,"Forward content")
RES_ADD_STRING(TXT_MAIL_FORWARD_ACC,"Forward accessory")
RES_ADD_STRING(TXT_MAIL_FORWARD_ALL,"Forward all")
//RES_ADD_STRING(TXT_MAIL_DEL,"Delete")               //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_MAIL_MARK,"Mark")  //replaced by common ID STXT_MARK
//RES_ADD_STRING(TXT_MAIL_CANCEL_MARK,"Cancel mark")      //replaced by common ID TXT_CANCEL_MARK
//RES_ADD_STRING(TXT_MAIL_MARK_ALL,"Mark all") replaced by common ID TXT_MARK_ALL
//RES_ADD_STRING(TXT_MAIL_CANCEL_MARK_ALL,"Cancel mark all")     //replaced by common ID TXT_CANCEL_MARK_ALL
RES_ADD_STRING(TXT_MAIL_RECEIVE,"Receive")
//RES_ADD_STRING(TXT_MAIL_RECEIVING,"Receiving")  //replaced by common ID TXT_COMMON_RECEIVING
//RES_ADD_STRING(TXT_MAIL_SEND,"Send")  //replaced by common ID TXT_SEND
RES_ADD_STRING(TXT_MAIL_CANCEL_SEND,"Cancel sending")
//RES_ADD_STRING(TXT_MAIL_RESEND,"Resend")    //replaced by common ID  TXT_RESEND
RES_ADD_STRING(TXT_MAIL_SENDING,"Sending")
//RES_ADD_STRING(TXT_MAIL_SEND_SUCCESS,"Send success")  //replaced by common ID TXT_COMM_SEND_SUCCEED
//RES_ADD_STRING(TXT_MAIL_SEND_FAIL,"Send fail")  //replaced by common ID TXT_COMM_SEND_FAILED
//RES_ADD_STRING(TXT_MAIL_EDIT,"Edit") //replaced by common ID TXT_EDIT
//RES_ADD_STRING(TXT_MAIL_FROM,"From")  //replaced by common ID TXT_COMMON_MAIL_FROM
RES_ADD_STRING(TXT_MAIL_TO,"To")
RES_ADD_STRING(TXT_MAIL_CC,"Cc")
RES_ADD_STRING(TXT_MAIL_BCC,"Bcc")
//RES_ADD_STRING(TXT_MAIL_SUBJECT,"Subject")  //replaced by common ID TXT_COMMON_SUBJECT
RES_ADD_STRING(TXT_MAIL_CONTENT,"Content")
RES_ADD_STRING(TXT_MAIL_READ_ACCESSORY,"Read accessory")
RES_ADD_STRING(TXT_MAIL_ACCESSORY,"Accessory")
RES_ADD_STRING(TXT_MAIL_ACCESSORY_LIST,"Accessory list")
//RES_ADD_STRING(TXT_MAIL_WRITE,"Write mail")    //replaced by common ID TXT_WRITE_MAIL
RES_ADD_STRING(TXT_MAIL_READ,"Read mail")
//RES_ADD_STRING(TXT_MAIL_SAVE,"Save") //replaced by common ID STXT_SAVE
//RES_ADD_STRING(TXT_MAIL_SAVE_AS,"Save as")   //replaced by common ID TXT_COMMON_SAVE_AS
RES_ADD_STRING(TXT_MAIL_SAVE_ALL,"Save all")
//RES_ADD_STRING(TXT_MAIL_CONTACTS,"Contacts")  //replaced by common ID TXT_COMMON_CONTACT
//RES_ADD_STRING(TXT_MAIL_SAVE_CONTACTS,"Save contacts") //replaced by common ID TXT_COMM_SAVE_CONTACT
RES_ADD_STRING(TXT_MAIL_SAVE_TO_NEW,"Save to new")
RES_ADD_STRING(TXT_MAIL_SAVE_TO_EXSIST,"Save to exsist")
RES_ADD_STRING(TXT_MAIL_SEL_GROUP,"Select group")
//RES_ADD_STRING(TXT_MAIL_PHONE,"Phone")    //replaced by common ID TXT_PHONE
//RES_ADD_STRING(TXT_MAIL_SIM,"SIM")  //replaced by common ID TXT_COMM_SIM
//RES_ADD_STRING(TXT_MAIL_SAVING,"Saving,please wait¡­")  //replaced by common ID TXT_PUB_SAVING
//RES_ADD_STRING(TXT_MAIL_SAVED,"Have saved to draftbox")  //replaced by common ID TXT_COMMON_MAIL_SAVED
//RES_ADD_STRING(TXT_MAIL_SAVE_FAIL,"Save fail") //replaced by common TXT_MMI_SAVEFAILED
//RES_ADD_STRING(TXT_MAIL_DOWNLOAD,"Download")  //replaced by common ID TXT_COMMON_DOWNLOAD_COMN
//RES_ADD_STRING(TXT_MAIL_DOWNLOADING,"Downloading,please wait¡­")  //replaced by common ID TXT_COMMON_DOWNLOADING_WAIT
RES_ADD_STRING(TXT_MAIL_DISPLAY_ALL_RECEIVERS,"Display all receivers")
RES_ADD_STRING(TXT_MAIL_HIDE_ALL_RECEIVERS,"Hide all receivers")
//RES_ADD_STRING(TXT_MAIL_YES,"Yes")    //replaced by common ID TXT_YES
//RES_ADD_STRING(TXT_MAIL_NO,"No")  //replaced by common ID TXT_COMM_NO
//RES_ADD_STRING(TXT_MAIL_EMPTY,"Empty")       //replaced by common ID TXT_BLANK
RES_ADD_STRING(TXT_MAIL_MAIL_ITEM,"mail")
RES_ADD_STRING(TXT_MAIL_MAIL_ITEMS,"mails")
RES_ADD_STRING(TXT_MAIL_DEL_CUR_MAIL,"Delete current mail")
RES_ADD_STRING(TXT_MAIL_INVALID_SIZE,"Invalid size")
RES_ADD_STRING(TXT_MAIL_NO_MEMORY,"No memory")
RES_ADD_STRING(TXT_MAIL_FULLSPACE,"Mail is full")
RES_ADD_STRING(TXT_MAIL_ADD_RECVER_FULL,"Add receiver full")
//RES_ADD_STRING(TXT_MAIL_ADD,"Add")  //replaced by common ID STXT_ADD
RES_ADD_STRING(TXT_MAIL_REACH_MAXSIZE_LIMIT,"Reach max size limit")
//RES_ADD_STRING(TXT_MAIL_ADD_FAIL,"Add fail")  //replaced by common ID TXT_ADD_FAIL
RES_ADD_STRING(TXT_MAIL_ADD_RECEIVER,"Please add receiver")
RES_ADD_STRING(TXT_MAIL_MORE,"More")
//RES_ADD_STRING(TXT_MAIL_RECV_FAIL,"Receive fail")        //replaced by common ID TXT_COMMON_RECEIVE_FAIL
RES_ADD_STRING(TXT_MAIL_SET_DEFAULT,"Set default")
RES_ADD_STRING(TXT_MAIL_SET_DEF_ACCOUNT,"Set default account")
RES_ADD_STRING(TXT_MAIL_SYNC_ACCOUNT_SETTING,"Sync account setting")
RES_ADD_STRING(TXT_MAIL_ACCOUNT_NAME,"Account name")
RES_ADD_STRING(TXT_MAIL_ACCOUNT_ADDR,"My address")
//RES_ADD_STRING(TXT_MAIL_ACCOUNT_USER_NAME,"User name")  //replaced by common ID TXT_COMMON_USERNAME
//RES_ADD_STRING(TXT_MAIL_ACCOUNT_PASSWORD,"Account password")  //replaced by common ID TXT_COMMON_PASSWORD
RES_ADD_STRING(TXT_MAIL_EDIT_ACCOUNT,"Edit account")
//RES_ADD_STRING(TXT_MAIL_CONFIRM_DELETE,"Confirm delete")       //replaced by common ID TXT_COMMON_CONFIRM_DELETE
RES_ADD_STRING(TXT_MAIL_INCLUDE_ORIGINAL,"Reply with original content")
//RES_ADD_STRING(TXT_MAIL_SIGN,"Signature")       //replaced by common ID TXT_COMMON_SIGNATURE
RES_ADD_STRING(TXT_MAIL_EDIT_SIGN,"Edit Sign")
//RES_ADD_STRING(TXT_MAIL_START_TIME,"Start time")  //replaced by common ID TXT_START_TIME
RES_ADD_STRING(TXT_MAIL_END_TIME,"End time")
//RES_ADD_STRING(TXT_MAIL_AUTO_DL,"Auto download")  //replaced by common ID TXT_COMMON_AUTO_DOWNLOAD
RES_ADD_STRING(TXT_MAIL_AUTO_FORMAT_CHANGE,"Auto format change")
RES_ADD_STRING(TXT_MAIL_CHANGE_TO_PNG,"Change to PNG")
RES_ADD_STRING(TXT_MAIL_CHANGE_TO_JPG,"Change to JPG")
RES_ADD_STRING(TXT_MAIL_NO_CHANGE,"No change")
RES_ADD_STRING(TXT_MAIL_SIZE_LIMIT,"Size limit")
RES_ADD_STRING(TXT_MAIL_SIZE_100K,"100K")
RES_ADD_STRING(TXT_MAIL_SIZE_200K,"200K")
RES_ADD_STRING(TXT_MAIL_SIZE_300K,"300K")
RES_ADD_STRING(TXT_MAIL_SIZE_400K,"400K")
RES_ADD_STRING(TXT_MAIL_SIZE_500K,"500K")
RES_ADD_STRING(TXT_MAIL_DEL_ALL_LOCAL_MAILS,"Delete all local mails")
RES_ADD_STRING(TXT_MAIL_ACCOUNT_IS_EMPTY,"Account is empty")
//RES_ADD_STRING(TXT_MAIL_ADDR_INVALID,"Address is invalid")  //replaced by common ID TXT_COMMON_MAIL_ADDR_INVALID
RES_ADD_STRING(TXT_MAIL_PART_ADDR_INVALID,"Partly address is invalid")
RES_ADD_STRING(TXT_MAIL_OVERWRITE_EXIST_ACCOUNT,"Overwrite exist account")
RES_ADD_STRING(TXT_MAIL_DEL_EXIST_ACCOUNT,"Delete exist account")
RES_ADD_STRING(TXT_MAIL_GETTING_ACCOUNT_CONFIG,"Getting account config")
//RES_ADD_STRING(TXT_MAIL_WAITING,"Waiting...")  //replaced by common ID TXT_COMMON_WAITING
RES_ADD_STRING(TXT_MAIL_ORIG_CONTENT_TOO_LARGE,"Origianl text too large")
RES_ADD_STRING(TXT_MAIL_INPUT_PASSWORD,"Please input password:")
//RES_ADD_STRING(TXT_MAIL_PASSWORD_ERROR,"Password error")      //replaced by common ID TXT_KL_PSW_WRONG_PSW
//RES_ADD_STRING(TXT_MAIL_INIT_FAIL,"Initialize fail")  //replaced by common ID TXT_COMM_INIT_FAIL
RES_ADD_STRING(TXT_MAIL_NOT_INIT,"Mail is not initialized")
RES_ADD_STRING(TXT_MAIL_LOGOUT,"Logout")
RES_ADD_STRING(TXT_MAIL_LOGOUT_ALERT_SUCCESS,"Logout request have send")
RES_ADD_STRING(TXT_MAIL_LOGOUT_ALERT_FAIL,"Logout request send fail")
//RES_ADD_STRING(TXT_MAIL_EXPAND,"Expand")    //replaced by common ID TXT_EXPAND
RES_ADD_STRING(TXT_MAIL_VIEW_FAIL,"View failed")
RES_ADD_STRING(TXT_MAIL_ACC_TOO_LARGE,"Accessory is too large")
RES_ADD_STRING(TXT_MAIL_DEL_ACC_ALERT,"Delete account with all mail delete meantime")
RES_ADD_STRING(TXT_MAIL_NONE_CMCC_SIMCARD,"None CMCC simcard")
RES_ADD_STRING(TXT_MAIL_RECV_MAIL_WAIT,"Receiving,please wait...")
RES_ADD_STRING(TXT_MAIL_SIM_NOT_READY,"SIM is not ready,please retry later")

//RES_ADD_STRING(TXT_MAIL_EXISTED_FILE,"File is existed!")    //replaced by common ID TXT_FILE_EXISTED
//RES_ADD_STRING(TXT_MAIL_ANSWER_MAIL,"email")    //replaced by common ID TXT_EMAIL
RES_ADD_STRING(TXT_MAIL_MEMORY,"email memory£º")
RES_ADD_STRING(TXT_MAIL_INSUFFICIENT_MEMORY,"Memory insufficient,can not receive mail!")
RES_ADD_STRING(TXT_MAIL_BOX_FULL,"Mail box is full,can not receive mail!")
RES_ADD_STRING(TXT_MAIL_NOT_INTEGRATED,"Content is too large, can't download completely and display")
RES_ADD_STRING(TXT_MAIL_NOT_AVAILABLE,"PushEmail service is not available")
//RES_ADD_STRING(TXT_MAIL_EDIT_EXIT_WITHOUT_SAVE,"Exit without saving")  //replaced by common ID TXT_EXIT_WITHOUT_SAVE
//RES_ADD_STRING(TXT_MAIL_DEL_ALL_IN_CUR_BOX,"Delete all")      //replaced by common ID TXT_DELALL

RES_ADD_STRING(TXT_MAIL_CHECK_SIM_STATE,"Please check the sim card state")
//RES_ADD_STRING(TXT_MAIL_BROWSER,"Browser")     //replaced by common ID TXT_BROWSE
RES_ADD_STRING(TXT_MAIL_GET_ACCOUNT_CONFIG_FAIL,"Get account config fail, please retry later")

//]]define string infomation

//[[define data infomation
//]]define data infomation

