/*****************************************************************************
** File Name:      set_menutable.c                                        *
** Author:                                                                   *
** Date:           2006/09/18                                               *
** Copyright:      2006 Spreadtrum, Incorporated. All Rights Reserved.         *
** Description:    This file is used to handle setting menutable             *
******************************************************************************
**                         Important Edit History                            *
** --------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                               *
** 2006/09/18     kelly.li     Creat                                     *
******************************************************************************/

#define _MMISET_MENUTABLE_C_
/**--------------------------------------------------------------------------*
**                         Include Files                                    *
**--------------------------------------------------------------------------*/
#ifdef WIN32
#include "std_header.h"
#endif
#include "window_parse.h"
//#include "sci_types.h"
#include "mmiset_menutable.h"
#include "guimenu.h"
#include "mmi_text.h"
#include "mmiset_text.h"
#include "mmiset_id.h"
#include "mmiset_image.h"
#include "mmi_module.h"
#include "mmi_common.h"
#include "mmi_nv.h"
#ifdef DM_SUPPORT
#include "mmidm_text.h"
#include "mmidm_image.h"
#endif
#ifdef VT_SUPPORT
#include "mmivt_text.h"
#endif
#ifdef MV_SUPPORT
#include "mmicc_text.h"
#endif
#ifdef VIDEO_PLAYER_SUPPORT
#include "mmivp_text.h"
#endif
#ifdef BROWSER_SUPPORT
#include "browser_manager_text.h"
#endif
#include "mmi_menutable.h"
#ifdef CMCC_UI_STYLE
#include "mmieng_text.h"
#endif

/**--------------------------------------------------------------------------*
**                         MACRO DEFINITION                                 *
**--------------------------------------------------------------------------*/
//#define TIP_NULL 0 

/**--------------------------------------------------------------------------*
**                         STATIC DEFINITION                                *
**--------------------------------------------------------------------------*/


/*---------------------------------------------------------------------------*/
/*                          TYPE AND CONSTANT                                */
/*---------------------------------------------------------------------------*/
//Env Set menu ID start-----@ add by maql @------------------------------------------------------------------------
// Has Been Moved to mmiset_lock_effect.c
// #ifdef MMI_KEY_LOCK_EFFECT_SUPPORT
// const GUIMENU_ITEM_T menu_lock_effect_settype[] = 
// { 
//     #ifdef MMI_KEY_LOCK_EFFECT_TYPE0_SUPPORT  
//     {ID_SET_KEYLOCK_LONG_TP,     TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_KEYLOCK_UNLOCK_TIP,   IMAGE_SET_ICON_SCREEN_LOCK_0,IMAGE_SET_ICON_SCREEN_LOCK_0,0,NULL},
//     #endif
//     #ifdef MMI_KEY_LOCK_EFFECT_TYPE1_SUPPORT  
//     {ID_SET_KEYLOCK_SLIDEDOWN,  TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_LOCK_SLIDEDOWN,IMAGE_SET_ICON_SCREEN_LOCK_1,IMAGE_SET_ICON_SCREEN_LOCK_1,0,NULL},
//     #endif
//     #ifdef MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT  
//     {ID_SET_KEYLOCK_SLIDE_SCROLLKEY,   TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_LOCK_SLIDE_SCROLLKEY,IMAGE_SET_ICON_SCREEN_LOCK_2,IMAGE_SET_ICON_SCREEN_LOCK_2,0,NULL},
//     #endif
//     #ifdef MMI_KEY_LOCK_EFFECT_TYPE3_SUPPORT  
//     {ID_SET_KEYLOCK_SMART_SLIDEDOWN,  TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_LOCK_SMART_SLIDEDOWN,IMAGE_SET_ICON_SCREEN_LOCK_3,IMAGE_SET_ICON_SCREEN_LOCK_3,0,NULL},
//     #endif
//     #ifdef MMI_KEY_LOCK_EFFECT_TYPE4_SUPPORT  
//     {ID_SET_KEYLOCK_SLIDE_IPHONE,   TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_LOCK_SLIDE_IPHONE,IMAGE_SET_ICON_SCREEN_LOCK_4,IMAGE_SET_ICON_SCREEN_LOCK_4,0,NULL},
//     #endif
//     #ifdef MMI_KEY_LOCK_EFFECT_TYPE5_SUPPORT  
//     {ID_SET_KEYLOCK_GRAPHIC,   TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_LOCK_GRAPHIC,IMAGE_SET_ICON_SCREEN_LOCK_5,IMAGE_SET_ICON_SCREEN_LOCK_5,0,NULL},
//     #endif
//     #ifdef MMI_KEY_LOCK_EFFECT_TYPE6_SUPPORT  
//     {ID_SET_KEYLOCK_ICON_RING,     TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_LOCK_ICON_RING,   IMAGE_SET_ICON_SCREEN_LOCK_6,IMAGE_SET_ICON_SCREEN_LOCK_6,0,NULL},
//    #endif 
//    #ifdef MMI_KEY_LOCK_FRUIT_SPLIT_SUPPORT  
//     {ID_SET_KEYLOCK_FRUIT_SPLIT,     TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_LOCK_FRUIT_SPLIT,   IMAGE_SET_ICON_SCREEN_LOCK_FRUIT,IMAGE_SET_ICON_SCREEN_LOCK_FRUIT,0,NULL},
//    #endif 
//    //michael wang kl
//     #ifdef MMI_KEY_LOCK_DOUBLE_CIRCLE_SUPPORT  
//     {ID_SET_KEYLOCK_DOUBLE_CIRCLE,     TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_LOCK_DOUBLE_CIRCLE,   IMAGE_SET_ICON_SCREEN_LOCK_CIRCLE,IMAGE_SET_ICON_SCREEN_LOCK_CIRCLE,0,NULL},
//    #endif 
//    //michael wang
//     };
// #endif
//operation menu of env setting
#ifdef MMI_VIDEOWALLPAPER_SUPPORT
const GUIMENU_ITEM_T menu_set_video_list_opt[] = 
{ 
    {ID_ENVSET_VIDEO_ADD,     TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_VP_ADD_VIDEO,   0,0,0,NULL},
    {ID_ENVSET_VIDEO_DELETE,  TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_VP_DEL_LOCALLIST,0,0,0,NULL},
    {ID_ENVSET_VIDEO_RESET,   TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_RESTORE_FACTORY_SETTINGS,0,0,0,NULL},
};

const GUIMENU_ITEM_T menu_set_video_list_longok_opt[] = 
{ 
    {ID_ENVSET_VIDEO_DELETE,  TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_VP_DEL_LOCALLIST,0,0,0,NULL},
};
#endif
#ifndef MMI_ENVSET_MINI_SUPPORT
const GUIMENU_ITEM_T menu_envset_operation[] = 
{ 
    {ID_ENVSET_ACTIVE,     TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_ACTIVE_OPERATIVE,   0,0,0,NULL},
    {ID_ENVSET_SETTING_OPT,TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_EXPORT_LOC_CUSTOM,0,0,0,NULL},//MENU_ENVSET_SETTING_OPTION},
    {ID_ENVSET_CHANGE_NAME,TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_RENAME,0,0,0,NULL},
#ifdef PLATFORM_SC6600L
    {ID_ENVSET_ENHANCE_RING,TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_ENHANCE_RING,0,0,0,NULL},
#endif
};
#endif
//setting option menu 
const GUIMENU_ITEM_T menu_envset_setting[] =
{
    {ID_ENVSET_CHANGE_NAME,              TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_FINISH},TXT_COMMON_RENAME,IMAGE_NULL,0,0,NULL},
    {ID_SET_RING,						 TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_FINISH},TXT_SET_RING_SET,	IMAGE_NULL, 0, 0, NULL},
    {ID_ENVSET_RING_VOL,                 TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_FINISH},TXT_RING_VOLUME,IMAGE_NULL, 0, 0, NULL},
    {ID_ENVSET_RING_TYPE,                TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_FINISH},TXT_SET_RING_TYPE,IMAGE_NULL, 0, 0, NULL},
    {ID_ENVSET_RING_OTHER,               TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_FINISH},TXT_SET_RING_OTHER,IMAGE_NULL, 0, 0, NULL},
};


//tune up ring volume
//@juan.wu modify delete it for no use @2012-4-18
/*const GUIMENU_ITEM_T menu_envset_ring_vol[] =
{
    {ID_ENVSET_CALL_RING_VOL,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SELECT_CALL,  0, 0, 0, NULL},
    {ID_ENVSET_MSG_RING_VOL,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SELECT_MSG,   0, 0, 0, NULL},
    {ID_ENVSET_COMM_VOL,            TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_VOLUME_COMM,  0, 0, 0, NULL},
#ifndef KEY_RING_THROUGH_RECEIVER
    {ID_ENVSET_KEY_RING_VOL,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_KEY_TONE,     0, 0, 0, NULL},
#endif
#ifdef TOUCH_PANEL_SUPPORT
#ifndef TP_RING_THROUGH_RECEIVER
    {ID_ENVSET_TKEY_RING_VOL,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_TKEY_TONE,     0, 0, 0, NULL},
#endif
#endif
    {ID_ENVSET_ALARM_RING_VOL,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_RING_SELECT_ALARM, 0, 0, 0, NULL},
    {ID_ENVSET_POWER_RING_VOL,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_ENVSET_POWER_RING_TYPE,     0, 0, 0, NULL}
};*/

//Env Set menu ID end----@ add by maql @-----------------------------------------------------------------------------
//select ring
//@juan.wu modify delete it for no use @2012-4-18
/*const GUIMENU_ITEM_T menu_set_ring_select[] =
{
#ifdef MMI_MULTI_SIM_SYS_SINGLE
    {ID_SET_RING_SELECT_CALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SELECT_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_RING_SIM1_SELECT_CALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SIM1_SELECT_CALL, 0, 0, 0, NULL},
    {ID_SET_RING_SIM2_SELECT_CALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SIM2_SELECT_CALL, 0, 0, 0, NULL},
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
    {ID_SET_RING_SIM3_SELECT_CALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SIM3_SELECT_CALL, 0, 0, 0, NULL},
#if defined(MMI_MULTI_SIM_SYS_QUAD)
    {ID_SET_RING_SIM4_SELECT_CALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SIM4_SELECT_CALL, 0, 0, 0, NULL},
#endif
#endif
#endif
    
#ifdef MMI_MULTI_SIM_SYS_SINGLE
    {ID_SET_RING_SELECT_MSG, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SELECT_MSG, 0, 0, 0, NULL},
#else
    {ID_SET_RING_SIM1_SELECT_MSG, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SIM1_SELECT_MSG, 0, 0, 0, NULL},
    {ID_SET_RING_SIM2_SELECT_MSG, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SIM2_SELECT_MSG, 0, 0, 0, NULL},
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
    {ID_SET_RING_SIM3_SELECT_MSG, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SIM3_SELECT_MSG, 0, 0, 0, NULL},
#if defined(MMI_MULTI_SIM_SYS_QUAD)
    {ID_SET_RING_SIM4_SELECT_MSG, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SIM4_SELECT_MSG, 0, 0, 0, NULL},
#endif
#endif
#endif
};*/

//tune up volume
//const GUIMENU_ITEM_T menu_set_ring_volume_opt[] =
//{
//    {ID_SET_RING_VOLUME_CALL, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SELECT_CALL, 0, 0, 0, NULL},
//    {ID_SET_RING_VOLUME_MSG, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_SELECT_MSG, 0, 0, 0, NULL},
//    {ID_SET_RING_VOLUME_COMMUNICATION, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_VOLUME_COMM, 0, 0, 0, NULL},
//    {ID_SET_RING_VOLUME_KEY_TONE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_RING_KEY_TONE, 0, 0, 0, NULL},
//    {ID_SET_RING_VOLUME_POWER, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_ENVSET_POWER_RING_TYPE, 0, 0, 0, NULL},
// };


//menu of phone setting
#ifdef DPHONE_SUPPORT 
const GUIMENU_ITEM_T menu_set_phone[] =
{
    {ID_SET_TIME_DATE,          TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_TIME_DATE,          0,   0, 0, PNULL},
    //+CR224092		
    {ID_SET_LANGUAGE,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_LANGUAGE_SETTINGS,  0,   0, 0, NULL},
	//-CR224092	
#if 0//ndef CMCC_UI_STYLE
    {ID_SET_SHORTCUT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SPEEDKEY_SET,           0,   0, 0, PNULL},
#endif
    {ID_SET_AUTO_POWERONOFF,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_AUTO_POWERONOFF,        0,  0, 0, NULL},
#ifdef DM_SUPPORT
    {ID_SET_DM_SERVICE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DM_SOFTWARE_UPDATE_SERVICE,0,      0, 0, NULL},
#endif
    {ID_SET_RESET_FACTORY,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RESTORE_FACTORY_SETTINGS,      0,      0, 0, NULL},	
    {ID_SET_SECURITY, 			TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMM_SECURITY_SETTING, 0, 0, 0, NULL},
#if defined(MMI_INDIAN_SOS_SUPPORT) && !defined(MMI_PDA_SUPPORT)
    {ID_SETTINGS_SOS,      TIP_NULL,{TXT_COMMON_OK,TXT_NULL,STXT_RETURN},TXT_SETTINGS_SOS, 0,0,0,NULL},
#endif

};
#else
#ifndef MMI_PHONESET_MINI_SUPPORT
const GUIMENU_ITEM_T menu_set_phone[] =
{
    {ID_SETTINGS_PHONE_SETTING,   TIP_NULL,{TXT_COMMON_OK,TXT_NULL,STXT_RETURN},TXT_SET_PHONE,     IMAGE_SECMENU_ICON_SET_PHONE,0,  0,MENU_NULL},
    {ID_SETTINGS_DISPLAY,   TIP_NULL,{TXT_COMMON_OK,TXT_NULL,STXT_RETURN},TXT_SETTINGS_DISPLAY,   IMAGE_SECMENU_ICON_SET_DISPLAY,0,0,MENU_NULL},
    {ID_SETTINGS_SECURITY,  TIP_NULL,{TXT_COMMON_OK,TXT_NULL,STXT_RETURN},TXT_COMM_SECURITY_SETTING,  IMAGE_SECMENU_ICON_SET_SECURITY,0,0,MENU_NULL},
    {ID_SETTINGS_CALL,      TIP_NULL,{TXT_COMMON_OK,TXT_NULL,STXT_RETURN},TXT_SETTINGS_CALL,      IMAGE_SECMENU_ICON_SET_CALL,0,0,MENU_NULL},
// 从主菜单中挪进来
#if defined (MMI_TVOUT_ENABLE) || defined (MMI_GPRS_SUPPORT)
    {ID_SETTINGS_LINK,      TIP_NULL,{TXT_COMMON_OK,TXT_NULL,STXT_RETURN},TXT_SETTINGS_LINK,      IMAGE_SECMENU_ICON_SET_LINK,0,        0,MENU_NULL},
#endif
#ifdef CMCC_UI_STYLE
    {ID_SET_PHONE_VERSION,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_VERSION,      IMAGE_SECMENU_ICON_JAVA_ABOUT,      0, 0, NULL},	
#endif
#if defined(MMI_INDIAN_SOS_SUPPORT) && !defined(MMI_PDA_SUPPORT)
    {ID_SETTINGS_SOS,      TIP_NULL,{TXT_COMMON_OK,TXT_NULL,STXT_RETURN},TXT_SETTINGS_SOS,      IMAGE_SECMENU_ICON_SET_SOS,0,0,MENU_NULL},
#endif
    // end
};
#endif
#endif //zss modify end
#ifndef MMI_GUI_STYLE_MINISCREEN
const GUIMENU_ITEM_T menu_set_phone_setting[] =
{
#if !defined MMI_SECMENU_ICON_DEFAULT
    {ID_SET_TIME_DATE,          TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_TIME_DATE,          IMAGE_SECMENU_ICON_PHONESET_TIMEDATE,   0, 0, PNULL},
    {ID_SET_LANGUAGE,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_LANGUAGE_SETTINGS,           IMAGE_SECMENU_ICON_PHONESET_LANGUAGE,   0, 0, NULL},
#endif
//sogou不支持模糊音，非触摸屏不支持手写，如果两者同时成立时，则导致没有输入法设置项
#if (defined TOUCH_PANEL_SUPPORT || ((!defined IM_ENGINE_SOGOU) && ((defined IM_SIMP_CHINESE_SUPPORT) || (defined IM_TRAD_CHINESE_SUPPORT))))
#if !((defined MAINLCD_DEV_SIZE_320X240) && (defined KEYPAD_TYPE_QWERTY_KEYPAD))
    {ID_SET_INPUT_MODE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_INPUT_MODE,         IMAGE_SECMENU_ICON_PHONESET_IM,         0, 0, NULL},
#endif
#endif

#if !defined CMCC_UI_STYLE && !defined FLASH_SUPPORT
#if !defined MMI_DISABLE_SHORTCUT_SET_SUPPORT && !defined MMI_SECMENU_ICON_DEFAULT
    {ID_SET_SHORTCUT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SPEEDKEY_SET,           IMAGE_SECMENU_ICON_PHONESET_SHORTCUT,   0, 0, PNULL},
#endif
#endif
#if 0//def BIG5_SUPPORT     //目前只和 BIG5 相关
    {ID_SET_TXT_CODE_TYPE,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_CODING_TYPE,            IMAGE_SECMENU_ICON_TXT_CODE_TYPE,   0, 0, NULL},
#endif
#if defined TOUCH_PANEL_SUPPORT && !defined TOUCHPANEL_TYPE_MULTITP
    {ID_SET_COORDINATE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_COORDINATE,         IMAGE_SECMENU_ICON_PHONESET_COORDINATE, 0, 0, NULL},
#endif
#if !defined MMI_SECMENU_ICON_DEFAULT
    {ID_SET_AUTO_POWERONOFF,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_AUTO_POWERONOFF,        IMAGE_SECMENU_ICON_PHONESET_AUTOPOWER,  0, 0, NULL},
#endif
#ifdef LCD_SLIDE_SUPPORT
    {ID_SET_SLIDE_OPERATION,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_SLIDE_OPERATION,    IMAGE_SECMENU_ICON_SET_PHONE, 0, 0, NULL},
#endif
#if defined MMI_POWER_SAVING_MODE_SUPPORT && !defined MMI_SECMENU_ICON_DEFAULT
    {ID_SET_SAVE_ELECTRICITY,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ENERGY_SAVING,   IMAGE_SECMENU_ICON_PHONESET_POWER,      0, 0, NULL},
#else
#if !defined MMI_PHONESET_MINI_SUPPORT && !defined MMI_SECMENU_ICON_DEFAULT
    {ID_SET_POWER_MANAGEMENT,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_POWER_MANAGEMENT,   IMAGE_SECMENU_ICON_PHONESET_POWER,      0, 0, NULL},
#endif
#endif
#ifdef DM_SUPPORT
    {ID_SET_DM_SERVICE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DM_SOFTWARE_UPDATE_SERVICE,IMAGE_DM_SOFTWARE_UPDATE,      0, 0, NULL},
#endif
#if defined (MOTION_SENSOR_TYPE)&& !defined(FLASH_SUPPORT)
	{ID_SET_SENSOR,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_SENSOR_RESPONDENT,IMAGE_SECMENU_ICON_PHONESET_SENSOR_RESPONDENT,      0, 0, NULL},
    {ID_SET_SENSOR_AUTO_ROTATE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_SENSOR_LANDSCAPE,IMAGE_SECMENU_ICON_PHONESET_SENSOR_RESPONDENT,      0, 0, NULL},
#endif

#ifdef BROWSER_SUPPORT
    {ID_SET_SELECT_BROWSER_TYPE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_BM_SET_SELECT_BROWSER,IMAGE_SECMENU_ICON_BROWSER,      0, 0, NULL},
#endif
#if !defined MMI_SECMENU_ICON_DEFAULT
    {ID_SET_RESET_FACTORY,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RESTORE_FACTORY_SETTINGS,      IMAGE_SECMENU_ICON_PHONESET_RESET,      0, 0, NULL},	
#endif
};
#endif
//main menu of setting
//const GUIMENU_ITEM_T menu_setting[] =
//{
//    {ID_SET_PROFILES, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_PROFILES, 0, 0, 0, NULL},
//    {ID_SET_DISPLAY, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_DISPLAY_SET, 0, 0, 0, MENU_SET_DISPLAY_OPT},
//    {ID_SET_TIME_DATE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_TIME_DATE, 0, 0, 0, MENU_SET_TIME_DATE_OPT},
//    {ID_SET_CALL, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SETTINGS_CALL, 0, 0, 0, MENU_SET_CALL_OPT},
//    {ID_SET_SECURITY, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMM_SECURITY_SETTING, 0, 0, 0, NULL},
//    {ID_SET_DIRECTIONKEY, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_SET_DIRECTIONKEY_MAIN, 0, 0, 0, NULL},  
//    {ID_SET_INPUT_MODE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_INPUT_MODE, 0, 0, 0, NULL},
//    {ID_SET_RESET_FACTORY, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_RESTORE_FACTORY_SETTINGS, 0, 0, 0, NULL},	
// };

#if !defined(MMI_MULTI_SIM_SYS_SINGLE)
//const GUIMENU_ITEM_T menu_dualsys_sim_onoff_type[] =
//{
//    {ID_SET_DUALSYS_SIM1_ON , TIP_NULL, {0, 0, 0}, TXT_SIM1_ENABLE, 0, 0, 0, NULL},		
//    {ID_SET_DUALSYS_SIM2_ON, TIP_NULL, {0, 0, 0}, TXT_SIM2_ENABLE, 0, 0, 0, NULL},			
//    {ID_SET_DUALSYS_ALL_SIM_ON, TIP_NULL, {0, 0, 0}, TXT_ALL_SIM_ENABLE, 0, 0, 0, NULL},	
// };


//const GUIMENU_ITEM_T menu_dualsys_sim_active_type[] =
//{
//    {ID_SET_SIM1_ACTIVE , TIP_NULL, {0, 0, 0}, TXT_SIM1_ENABLE, 0, 0, 0, NULL},	
//    {ID_SET_SIM2_ACTIVE, TIP_NULL, {0, 0, 0}, TXT_SIM2_ENABLE, 0, 0, 0, NULL},	
// };

const GUIMENU_ITEM_T menu_set_sim_name[] =
{
    {ID_SET_SIM1_NAME, TIP_NULL, {0, 0, 0}, TXT_SIM1_NAME, 0, 0, 0, NULL},   //BRUCE MODIFY LATER
    {ID_SET_SIM2_NAME, TIP_NULL, {0, 0, 0}, TXT_SIM2_NAME, 0, 0, 0, NULL},
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
    {ID_SET_SIM3_NAME, TIP_NULL, {0, 0, 0}, TXT_SIM3_NAME, 0, 0, 0, NULL},
#if defined(MMI_MULTI_SIM_SYS_QUAD)
    {ID_SET_SIM4_NAME, TIP_NULL, {0, 0, 0}, TXT_SIM4_NAME, 0, 0, 0, NULL},
#endif
#endif
};
#endif


//time and date menu of setting 时间日期设置已经改成了form形式，不需要这样的menu
//@juan.wu modify delete it for no use @2012-4-18
//const GUIMENU_ITEM_T menu_set_time_date_opt[] =
//{
//    {ID_SET_TIME, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_TIME, 0, 0, 0, NULL},
//    {ID_SET_DATE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_DATE, 0, 0, 0, NULL},
//    {ID_SET_TIME_DISPLAY_TYPE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_TIME_DISPLAY_TYPE, 0, 0, 0, NULL},
//    {ID_SET_DATE_DISPLAY_TYPE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_DATE_DISPLAY_TYPE, 0, 0, 0, NULL},
//#if defined(MMI_UPDATE_TIME_SUPPORT)
//    {ID_SET_UPDATE_TIME_SET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_UPDATE_TIME_SET, 0, 0, 0, NULL},
//#endif
//};

#if defined(MMI_UPDATE_TIME_SUPPORT)
#ifdef MMI_GUI_STYLE_TYPICAL
const GUIMENU_ITEM_T menu_set_update_time_opt[] =
{
    {ID_SET_AUTO_UPDATE_TIME, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUTO_UPDATE_TIME, 0, 0, 0, NULL},
    {ID_SET_UPDATE_SYSTEM_TIME, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_UPDATE_SYSTEM_TIME, 0, 0, 0, NULL},
    {ID_SET_UPDATE_TIME_HELP, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_UPDATE_TIME_HELP, 0, 0, 0, NULL},
};
#endif
#endif

//display setting menu of setting
#ifdef DPHONE_SUPPORT
const GUIMENU_ITEM_T menu_set_display_opt[] =
{
    {ID_SET_IDLE_DISPLAY,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_IDLE_DISPLAY,            0,             0, 0, NULL},
    {ID_SET_BACK_LIGHT,             TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_BACK_LIGHT,              0,            0, 0, NULL},
    {ID_SET_KEY_BOARD_LIGHT,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_BOARD_LIGHT,         0,         0, 0, NULL},
};
#else
#if 0//显示设置的菜单已经使用form控件，没有使用menu控件，这里可以删除
//@juan.wu modify delete it for no use @2012-4-18
const GUIMENU_ITEM_T menu_set_display_opt[] =
{
    {ID_SET_WALLPAPER,              TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_SET_WALLPAPER,               IMAGE_SECMENU_ICON_DISSET_WALLPAPER,        0, 0, NULL},
#ifdef MULTI_THEME_SUPPORT
    {ID_SET_THEME,                  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_THEME,                   IMAGE_SECMENU_ICON_DISSET_THEME,            0, 0, NULL},    
#endif 
   // {ID_SET_MENU_ANIMATION,         TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_MENU_ANIMATION,          IMAGE_SECMENU_ICON_DISSET_MAINMENU_ANIM,    0, 0, NULL},
//#ifndef MAIN_MENU_SUPPORT_LOW_MEMORY
#ifndef MMI_DISPLAYSET_MINI_SUPPORT
    {ID_SET_MAINMENU_STYLE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_MAINMENU_STYLE,          IMAGE_SECMENU_ICON_DISSET_MAINMAIN_STYLE,   0, 0, NULL},
#endif
//#endif
#if defined(PDA_UI_MAINMENU_SUPPORT_SELECT_ANIM)
    {ID_SET_MAINMENU_SELECT_STYLE,         TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_MAINMENU_SELECT_STYLE,          IMAGE_SECMENU_ICON_DISSET_MAINMAIN_STYLE,   0, 0, NULL},
#endif

#ifndef CMCC_UI_STYLE
    {ID_SET_IDLE_STYLE,             TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_IDLE_SWITH,              IMAGE_SECMENU_ICON_DISSET_IDLE_STYLE,       0, 0, NULL},
#endif
    {ID_SET_IDLE_DISPLAY,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_IDLE_DISPLAY,            IMAGE_SECMENU_ICON_DISSET_IDLE,             0, 0, NULL},
#ifdef SCREENSAVER_SUPPORT  
    {ID_SET_SCREENSAVER,            TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SCREENSAVER,             IMAGE_SECMENU_ICON_DISSET_SCREENSAVER,      0, 0, NULL},
#endif
    {ID_SET_CONTRAST,               TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_CONTRAST,                IMAGE_SECMENU_ICON_DISSET_CONTRAST,         0, 0, NULL},
    {ID_SET_BACK_LIGHT,             TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_BACK_LIGHT,              IMAGE_SECMENU_ICON_DISSET_LIGHT,            0, 0, NULL},
    {ID_SET_KEY_BOARD_LIGHT,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEY_BOARD_LIGHT,         IMAGE_SECMENU_ICON_DISSET_KEYLIGHT,         0, 0, NULL},
    {ID_SET_ANIMATION,              TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_ANIMATION,  IMAGE_SECMENU_ICON_DISSET_ONOFFANIM,        0, 0, PNULL},
#if defined FONT_TYPE_SUPPORT_VECTOR && defined FILE_FONT_SUPPORT
    {ID_SET_FONT,                   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_FONT,  IMAGE_SECMENU_ICON_DISSET_FONT,        0, 0, PNULL},
#endif
    // {ID_SET_POWER_ON_OFF_ANIMATION, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_POWER_ON_OFF_ANIMATION,  IMAGE_SECMENU_ICON_DISSET_ONOFFANIM,        0, 0, MENU_SET_POWER_ON_OFF_ANIM_OPT},
//#ifdef UI_P3D_SUPPORT   
 //   {ID_SET_3D_OTHER,               TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_3D_STYLE,                IMAGE_SECMENU_ICON_DISSET_3D,               0, 0, PNULL},
//#endif
};
#endif
#endif //zss modify end

#if 0//动画菜单使用了form控件，menu控件可以删除
//@juan.wu modify delete it for no use @2012-4-18
//动画效果
const GUIMENU_ITEM_T menu_set_icon_animation[] =
{
#ifdef UI_P3D_SUPPORT
    {ID_SET_3D_STYLE_WINDOW,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_SET_3D_STYLE_SCREEN,     0, 0, 0, NULL},
    {ID_SET_3D_STYLE_MAINMENU,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_SET_3D_STYLE_MAINMENU,   0, 0, 0, NULL},
#endif
   // {ID_SET_POWER_ON_OFF_ANIMATION, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_POWER_ON_OFF_ANIMATION,  0, 0, 0, MENU_SET_POWER_ON_OFF_ANIM_OPT},
    {ID_SET_POWER_ON_SET,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_ON_ANIMATION,   0, 0, 0, NULL},
    {ID_SET_POWER_OFF_SET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_OFF_ANIMATION,  0, 0, 0, NULL},
#ifdef UI_P3D_SUPPORT
    {ID_SET_3D_OTHER, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_TOOLS_OTHERS,  0, 0, 0, NULL}
#endif
};
#endif
//const GUIMENU_ITEM_T menu_set_animation[] =
//{
//    {ID_SET_MENU_ANIMATION,         TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_MENU_ANIMATION,          0,    0, 0, NULL},
//   // {ID_SET_POWER_ON_OFF_ANIMATION, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_POWER_ON_OFF_ANIMATION,  0, 0, 0, MENU_SET_POWER_ON_OFF_ANIM_OPT},
//    {ID_SET_POWER_ON_SET,  TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_ON_ANIMATION,   0, 0, 0, NULL},
//    {ID_SET_POWER_OFF_SET, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_OFF_ANIMATION,  0, 0, 0, NULL},
//    {ID_SET_3D_OTHER, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},  TXT_TOOLS_OTHERS,  0, 0, 0, NULL}
//};

//power on off setting of display setting menu
//const GUIMENU_ITEM_T menu_set_power_on_off_anim_opt[] =
//{   
//    {ID_SET_POWER_ON_SET,  TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_ON_ANIMATION,   0, 0, 0, NULL},
//    {ID_SET_POWER_OFF_SET, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_OFF_ANIMATION,  0, 0, 0, NULL}
// };

#if 0
//privacy protect menu option
//@juan.wu modify delete it for no use @2012-4-18
const GUIMENU_ITEM_T menu_set_privacy_protect_opt[] =
{   
    {ID_SET_PRIVACY_PROTECT_SET,TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_MAIN_SETTING, 0, 0, 0, NULL},
    {ID_SET_PRIVACY_PROTECT_MODIFY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_MODIFY_CODE, 0, 0, 0, NULL},
};
#endif
//@zhaohui add for fdn
//fdn menu Id 
#if defined (DPHONE_SUPPORT) && defined (FDN_SUPPORT)
const GUIMENU_ITEM_T menu_fdn_set_opt[] = 
{
    {ID_FDN_STATE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_STATE, 0, 0, 0, NULL},//状态
    {ID_FDN_NUM, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FDN_NUM, 0, 0, 0, NULL},//固定号码
};
#endif
//display setting wallpaper menu
//const GUIMENU_ITEM_T menu_set_wallpaper_opt[] =
//{   
//    {ID_SET_PIC_WALLPAPER,TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_PIC_WALLPAPER, 0, 0, 0, NULL},
//    {ID_SET_ANIMATION_WALLPAPER, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_ANIMATION_WALLPAPER, 0, 0, 0, NULL},
// };

//设置主屏和附屏的对比度
//const GUIMENU_ITEM_T menu_set_contrast_opt[] =
//{
//    {ID_SET_MAIN_LCD_CONTRAST, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_MAIN_LCD, 0, 0, 0, NULL},
//    {ID_SET_SUB_LCD_CONTRAST, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_SUB_LCD, 0, 0, 0, NULL},
// };

#ifdef MMI_PREFER_PLMN_SUPPORT
//网络设置的菜单
const GUIMENU_ITEM_T menu_set_network_setting[] =
{
    {ID_SET_NETWORK_SETTING_SEL_MENU, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NETWORK_SELECT, 0, 0, 0, NULL},
    {ID_SET_NETWORK_SETTING_PREFER_MENU, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_PREFER_NETWORK, 0, 0, 0, NULL},	
};

//偏好网络的Options Menu菜单
const GUIMENU_ITEM_T menu_set_prefer_network_options[]=
{
#ifdef MMI_PDA_SUPPORT
    {ID_SET_ADD_PREFER_NETWORK_FROM_LIST, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_PREFER_NETWORK_ADD, 0, 0, 0, NULL},
    {ID_SET_CREATE_PREFER_NETWORK, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NEW, 0, 0, 0, NULL},	
#else
    {ID_SET_ADD_PREFER_NETWORK_FROM_LIST, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_PREFER_NETWORK_ADD, 0, 0, 0, NULL},
    {ID_SET_CREATE_PREFER_NETWORK, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NEW, 0, 0, 0, NULL},	
    {ID_SET_CHANGE_PREFER_NETWORK_PRIORITY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_PREFER_NETWORK_PRIORITY, 0, 0, 0, NULL},
    {ID_SET_DELETE_PREFER_NETWORK, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DELETE, 0, 0, 0, NULL},
#endif
};

#ifdef MMI_PDA_SUPPORT
const GUIMENU_ITEM_T menu_set_prefer_network_longpenok_options[]=
{
    {ID_SET_CHANGE_PREFER_NETWORK_PRIORITY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_PREFER_NETWORK_PRIORITY, 0, 0, 0, NULL},
    {ID_SET_DELETE_PREFER_NETWORK, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DELETE, 0, 0, 0, NULL},
};
#endif

#endif

//call setting menu of setting
#ifdef DPHONE_SUPPORT 
const GUIMENU_ITEM_T menu_set_call_opt[] =
{
#ifdef MMI_DUALSIM_SUPPORT
    {ID_SET_DUAL_SIM_SETTING,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_DUAL_SIM_SETTING,    0, 0, 0, NULL},
#endif
#ifdef MMI_DUALMODE_ENABLE
   {ID_SET_NETSETTING,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NETWORK_SELECT,             0,  0, 0, PNULL},
#else
   {ID_SET_NETWORK,            TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NETWORK_SELECT,             0,  0, 0, NULL},
#endif
    {ID_SET_CALL_DIVERTS,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_CALL_DIVERTS,        0,  0, 0, NULL},
    {ID_SET_CALL_WAITING,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_CALL_WAITING,        0, 0, 0, NULL},
    {ID_SET_CALL_BAR,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_CALL_BAR,            0, 0, 0, NULL},   
    //{ID_SET_HIDE_ID,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_HIDE_ID,             0,    0, 0, NULL},    
//#ifdef MMI_CSP_SUPPORT
    {ID_SET_LINE_SELECT,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_LINE_SELECT,         IMAGE_SECMENU_ICON_CALLSET_LINESEL, 0, 0, NULL},
    {ID_SET_LINE_LOCK,  TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_LINE_LOCK,         IMAGE_NULL, 0, 0, NULL},
//#endif
    //{ID_SET_FLY_MODE,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_FLY_MODE,            0, 0, 0, NULL},
    {ID_SET_OTHER,              TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_TOOLS_OTHERS,            0,  0, 0, MENU_SET_CALL_OTHER_OPT}, //@CR226145 2011.01.24
};
#else
#ifdef MMI_GUI_STYLE_TYPICAL
const GUIMENU_ITEM_T menu_set_call_opt[] =
{
#if !defined(MMI_MULTI_SIM_SYS_SINGLE)
#if defined(MMI_MULTI_SIM_SYS_DUAL)
    {ID_SET_MULTI_SIM_SETTING,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_DUAL_SIM_SETTING,    IMAGE_SECMENU_ICON_CALLSET_DUALSIM, 0, 0, NULL},    
#else
    {ID_SET_MULTI_SIM_SETTING,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_MULTI_SIM_SETTING,    IMAGE_SECMENU_ICON_CALLSET_MULTISIM, 0, 0, NULL},    
#endif
#endif
//#ifdef MMI_DUALMODE_ENABLE
  //  {ID_SET_NETSETTING,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NETWORK_SELECT,             IMAGE_SECMENU_ICON_CALLSET_NETSET,  0, 0, PNULL},
//#else
 //   {ID_SET_NETWORK,            TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NETWORK_SELECT,             IMAGE_SECMENU_ICON_CALLSET_NETSEL,  0, 0, NULL},
//#endif
    {ID_SET_CALL_DIVERTS,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_CALL_DIVERTS,        IMAGE_SECMENU_ICON_CALLSET_DIVERT,  0, 0, NULL},
    {ID_SET_CALL_WAITING,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_CALL_WAITING,        IMAGE_SECMENU_ICON_CALLSET_WAITING, 0, 0, NULL},
    {ID_SET_CALL_BAR,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_CALL_BAR,            IMAGE_SECMENU_ICON_CALLSET_BARRING, 0, 0, NULL},   
#ifdef VT_SUPPORT
    {ID_SET_VIDEOPHONE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOPHONE,          IMAGE_SECMENU_ICON_CALLSET_VIDEOPHONE, 0, 0, NULL},
#endif
//#ifdef MMI_CSP_SUPPORT
     {ID_SET_LINE_SELECT,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_LINE_SELECT,         IMAGE_SECMENU_ICON_CALLSET_LINESEL, 0, 0, NULL},
//#endif
{ID_SET_HIDE_ID,            TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_HIDE_ID,             IMAGE_SECMENU_ICON_CALLSET_HIDE,    0, 0, NULL},
#if defined(MMI_MULTI_SIM_SYS_SINGLE)    
    {ID_SET_FLY_MODE,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_FLY_MODE,            IMAGE_SECMENU_ICON_CALLSET_FLYMODE, 0, 0, NULL},
#endif
    {ID_SET_OTHER,              TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_TOOLS_OTHERS,            IMAGE_SECMENU_ICON_CALLSET_OTHERS,  0, 0, NULL},
};
#endif //zss modify end
#endif

#ifdef DPHONE_SUPPORT 
const GUIMENU_ITEM_T menu_set_call_other_opt[] =
{   
    {ID_SET_IP_CALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_IP_NUMBER, 0, 0, 0, NULL},
#ifndef SUBLCD_SIZE_NONE  //有小屏
    {ID_SET_FLIP_ANSWER, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_FLIP_ANSWER, 0, 0, 0, NULL},
#endif
    {ID_SET_MINUTE_REMINDER, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_CALL_TIME_REMINDER, 0, 0, 0, NULL},
   
    {ID_SET_SPEED_DIAL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SPEED_DIAL,		0, 0, 0, NULL},    
   
#ifdef DPHONE_SUPPORT 
#else
    {ID_SET_CONNECT_PROMPT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_CONNECT_PROMPT, 0, 0, 0, NULL},
#endif 
#ifdef MV_SUPPORT
    {ID_SET_MAGIC_VOICE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CC_MAGICVOICE, 0, 0, 0, NULL},
#endif
    {ID_SET_ANYKEY_REJECT_MODE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_ANYKEY_REJECT_MODE, 0, 0, 0, NULL},	
    {ID_SET_AUTO_REDIAL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUTO_REDAIL, 0, 0, 0, NULL},   
#ifdef TTS_SUPPORT
    {ID_SET_TTS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_CALL_TTS, 0, 0, 0, NULL},
#endif
#ifdef TOUCH_PANEL_SUPPORT
    {ID_SET_DIAL_PANEL_TOUCH_VIBRATE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_DIAL_PANEL_TOUCH_VIBRATE, 0, 0, 0, NULL},
#endif
    
};
#endif

#if !defined(MMI_MULTI_SIM_SYS_SINGLE)
//multi sim menu of setting
const GUIMENU_ITEM_T menu_set_multi_sim_setting[] =
{
//#if defined(MMI_MULTI_SIM_SYS_DUAL)   //CFNRC multi sim? How to design.  
    //{ID_SET_DUAL_SYS_CFNRC, TIP_NULL, {0, 0, 0},TXT_DUAL_SYS_CFNRC, 0, 0, 0, NULL},  //not need.
//#endif
    {ID_SET_MULTISYS_SIM_ONOFF_TYPE, TIP_NULL, {0, 0, 0},TXT_SIM_ENABLE_SEL, 0, 0, 0, NULL},
#if 0
    {ID_SET_MAJORSIM_SELECT, TIP_NULL, {0, 0, 0},TXT_MAJOR_SIM_SEL, 0, 0, 0, MENU_SET_MAJOR_SIM_SEL},
#else
    {ID_SET_ANSWER_USING_ORIGINAL_SIM, TIP_NULL, {0, 0, 0},TXT_SET_REPLY_BY_ORIGINAL_SIM, 0, 0, 0, NULL},
#endif
    {ID_SET_SIM_NAME, TIP_NULL, {0, 0, 0},TXT_SET_SIM_NAME, 0, 0, 0, MENU_SETTING_SIM_NAME},
//#ifdef MMI_MULTI_SIM_SYS_DUAL
    //{ID_SET_DUALSIM_WIZARD, TIP_NULL, {0, 0, 0},TXT_DUAL_SIM_SETTING_WIZARD, 0, 0, 0, NULL},
//#else
    //{ID_SET_DUALSIM_WIZARD, TIP_NULL, {0, 0, 0},TXT_MULTI_SIM_SETTING_WIZARD, 0, 0, 0, NULL},
//#endif
    //{ID_SET_MULTISIM_HELP, TIP_NULL, {0, 0, 0},TXT_SET_HELP, 0, 0, 0, NULL},  //not need.
};

//call diverts menu of setting
const GUIMENU_ITEM_T menu_set_major_sim_sel[] =
{
    {ID_SET_CALL_SIM_SEL, TIP_NULL, {0, 0, 0},TXT_COMM_CALL, 0, 0, 0, NULL},
    {ID_SET_SMS_SIM_SEL, TIP_NULL, {0, 0, 0},TXT_SET_SMS_SIM_SEL, 0, 0, 0, NULL},		
    {ID_SET_MMS_SIM_SEL, TIP_NULL, {0, 0, 0},TXT_MMS, 0, 0, 0, NULL},
    {ID_SET_BROWSER_SIM_SEL, TIP_NULL, {0, 0, 0},TXT_COMMUNICATION_BROWSER, 0, 0, 0, NULL},
    {ID_SET_SPEED_DIAL, TIP_NULL, {0, 0, 0},TXT_COMMON_SPEEDDIAL, 0, 0, 0, NULL},
#ifdef MMI_STREAMING_PLAYER_SUPPORT
    {ID_SET_STREAMING_SIM_SEL, TIP_NULL, {0, 0, 0},TXT_SET_STREAMING, 0, 0, 0, NULL},
#endif
    {ID_SET_ANSWER_USING_ORIGINAL_SIM, TIP_NULL, {0, 0, 0},TXT_SET_REPLY_BY_ORIGINAL_SIM, 0, 0, 0, NULL},
    
};

//call diverts menu of setting
const GUIMENU_ITEM_T menu_set_wizard_major_sim_sel[] =
{
    {ID_SET_CALL_SIM_SEL, TIP_NULL, {STXT_MAIN_SETTING,TXT_NULL,TXT_NEXT_STEP},TXT_COMM_CALL, 0, 0, 0, NULL},
    {ID_SET_SMS_SIM_SEL, TIP_NULL, {STXT_MAIN_SETTING,TXT_NULL,TXT_NEXT_STEP},TXT_SET_SMS_SIM_SEL, 0, 0, 0, NULL},		
    {ID_SET_MMS_SIM_SEL, TIP_NULL, {STXT_MAIN_SETTING,TXT_NULL,TXT_NEXT_STEP},TXT_MMS, 0, 0, 0, NULL},
    {ID_SET_BROWSER_SIM_SEL, TIP_NULL, {STXT_MAIN_SETTING,TXT_NULL,TXT_NEXT_STEP},TXT_COMMUNICATION_BROWSER, 0, 0, 0, NULL},
    {ID_SET_SPEED_DIAL, TIP_NULL, {STXT_MAIN_SETTING,TXT_NULL,TXT_NEXT_STEP},TXT_COMMON_SPEEDDIAL, 0, 0, 0, NULL},
#ifdef MMI_STREAMING_PLAYER_SUPPORT
    {ID_SET_STREAMING_SIM_SEL, TIP_NULL, {0, 0, 0},TXT_SET_STREAMING, 0, 0, 0, NULL},
#endif
    {ID_SET_ANSWER_USING_ORIGINAL_SIM, TIP_NULL, {STXT_MAIN_SETTING,TXT_NULL,TXT_NEXT_STEP},TXT_SET_REPLY_BY_ORIGINAL_SIM, 0, 0, 0, NULL},
};
#endif
//call diverts menu of setting
const GUIMENU_ITEM_T menu_set_call_diverts_opt[] =
{
    {ID_SET_DIVERTS_ALL_CALLS, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_DIVERTS_ALL_CALLS, 0, 0, 0, NULL},
#ifdef MMI_CSP_SUPPORT
    {ID_SET_DIVERTS_ALL_CONDITIONAL, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_DIVERTS_ALL_CONDITIONAL, 0, 0, 0, NULL},
#endif 
    {ID_SET_DIVERTS_WHEN_BUSY, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_DIVERTS_WHEN_BUSY, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_NO_ANSWER, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_DIVERTS_NO_ANSWER, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_NOT_REACHABLE, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_DIVERTS_NOT_REACHABLE, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_CANCEL_ALL, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_DIVERTS_CANCEL_ALL, 0, 0, 0, NULL},
};

//call waitng menu of setting
const GUIMENU_ITEM_T menu_set_call_waiting_opt[] =
{
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
};

//@maggie add begin for cr79064 
//hide id menu of setting
const GUIMENU_ITEM_T menu_set_network[] =
{
    {ID_SET_NETWORK_TYPE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NETWORK_TYPE, 0, 0, 0, NULL},
    {ID_SET_NETWORK_METHOD, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_NETWORK_METHOD, 0, 0, 0, NULL},	
};
//@maggie add end for cr79064 

const GUIMENU_ITEM_T menu_set_network_method[] =
{
    {ID_SET_NETWORK_SEL_AUTO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_AUTO, 0, 0, 0, NULL},
        //{ID_SET_NETWORK_SEL_MANU, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MANUAL, 0, 0, 0, MENU_SET_NETWORK_SEL_MANU},	
    {ID_SET_NETWORK_SEL_MANU, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_MANUAL, 0, 0, 0, NULL},	
};
//const GUIMENU_ITEM_T menu_set_network_type[] =
//{
//    {ID_SET_NETWORK_TYPE_GSM, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_GSM, 0, 0, 0, NULL},
//    {ID_SET_NETWORK_TYPE_TD, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_TDSCDMA, 0, 0, 0, NULL},	
//    {ID_SET_NETWORK_TYPE_DM, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_DM, 0, 0, 0, MENU_SET_NETWORK_TYPE_DM},	
// };
//const GUIMENU_ITEM_T menu_set_network_sel_manu[] =
//{
//    {ID_SET_NETWORK_SEL_MANU_GSM, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_GSM, 0, 0, 0, NULL},
//    {ID_SET_NETWORK_SEL_MANU_TD, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_TDSCDMA, 0, 0, 0, NULL},	
//    {ID_SET_NETWORK_SEL_MANU_DM, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_DM, 0, 0, 0, MENU_SET_NETWORK_SEL_MANU_DM},	
// };
//const GUIMENU_ITEM_T menu_set_network_type_dm[] =
//{
//    {ID_SET_NETWORK_TYPE_GSM_PREFER, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_GSM_PREFER, 0, 0, 0, NULL},
//    {ID_SET_NETWORK_TYPE_TD_PREFER, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_TD_PREFER, 0, 0, 0, NULL},	
// };
//const GUIMENU_ITEM_T menu_set_network_sel_manu_dm[] =
//{
//    {ID_SET_NETWORK_SEL_MANU_GSM_PREFER, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_GSM_PREFER, 0, 0, 0, NULL},
//    {ID_SET_NETWORK_SEL_MANU_TD_PREFER, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_SET_TD_PREFER, 0, 0, 0, NULL},	
// };


//call bar menu of setting
const GUIMENU_ITEM_T menu_set_call_bar_opt[] =
{
    {ID_SET_BAR_ALL_MO_CALLS, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_BAR_ALL_MO_CALLS, 0, 0, 0, NULL},
    {ID_SET_BAR_ALL_MT_CALLS, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_BAR_ALL_MT_CALLS, 0, 0, 0, NULL},
    {ID_SET_BAR_MT_CALLS_ROAM, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_BAR_MT_CALLS_ROAM, 0, 0, 0, NULL},
    {ID_SET_BAR_MO_CALLS_INTL, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_BAR_MO_CALLS_INTL, 0, 0, 0, NULL},
    {ID_SET_BAR_MO_CALLS_INTL_ROAM, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_BAR_MO_CALLS_INTL_ROAM, 0, 0, 0, NULL},
    {ID_SET_BAR_CANCEL_ALL, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_BAR_CANCEL_ALL, 0, 0, 0, NULL},
    {ID_SET_BAR_CHANGE_PW, TIP_NULL, {STXT_SELECT, TXT_NULL, STXT_RETURN},TXT_SET_BAR_CHANGE_PW, 0, 0, 0, NULL},
};

//diverts all call menu of setting
const GUIMENU_ITEM_T menu_set_all_calls_opt[] =
{
#ifdef VT_SUPPORT//@zhaohui modify
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
#endif
};

const GUIMENU_ITEM_T menu_set_divert_calls_opt[] =
{
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
};

const GUIMENU_ITEM_T menu_set_barring_calls_opt[] =
{
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
};


//diverts to number or voice box call menu of setting
const GUIMENU_ITEM_T menu_set_ss_divert_opt[] =
{
    {ID_SET_SS_DIVERT_VOICE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_DIVERT_VOICE, 0, 0, 0, MENU_SET_SS_DIVERT_VOICE_OPT},
    {ID_SET_SS_DIVERT_NUMBER, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_DIVERT_NUMBER, 0, 0, 0, NULL},
};

//diverts when busy menu of setting
const GUIMENU_ITEM_T menu_set_when_busy_opt[] =
{
#ifdef VT_SUPPORT//@zhaohui modify
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
#endif
};

//diverts to voice box call menu of setting
const GUIMENU_ITEM_T menu_set_ss_divert_voice_opt[] = 
{
    {ID_SET_SS_LINE_VMN, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_LINE_NUMBER, 0, 0, 0, NULL},
//#ifdef MMI_CSP_SUPPORT
    {ID_SET_SS_LINE1_VMN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_LINE1_NUMBER, 0, 0, 0, NULL},
    {ID_SET_SS_LINE2_VMN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_LINE2_NUMBER, 0, 0, 0, NULL},
//#endif    
    {ID_SET_SS_FAX_VMN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMM_FAX_NUMBER, 0, 0, 0, NULL},
    {ID_SET_SS_DATA_VMN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_DATA_NUMBER, 0, 0, 0, NULL}
};

//diverts no answer menu of setting
const GUIMENU_ITEM_T menu_set_no_answer_opt[] =
{
#ifdef VT_SUPPORT//@zhaohui modify
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
#endif
};

//diverts not reachable menu of setting
const GUIMENU_ITEM_T menu_set_not_reachable_opt[] =
{
#ifdef VT_SUPPORT//@zhaohui modify
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
#endif
};

//restrict all mo calls menu of setting
const GUIMENU_ITEM_T menu_set_bar_all_mo_calls_opt[] =
{
#ifdef VT_SUPPORT//@zhaohui modify
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
#endif
};

//restrict all mt calls menu of setting
const GUIMENU_ITEM_T menu_set_bar_all_mt_calls_opt[] =
{
#ifdef VT_SUPPORT//@zhaohui modify
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
#endif
};

//restrict all mt calls in roam menu of setting
const GUIMENU_ITEM_T menu_set_bar_all_mt_calls_roam_opt[] =
{
#ifdef VT_SUPPORT//@zhaohui modify
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
#endif
 };

//restrict all mo calls in roam menu of setting
const GUIMENU_ITEM_T menu_set_bar_all_mo_calls_intl_opt[] =
{
#ifdef VT_SUPPORT//@zhaohui modify
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
#endif
 };

//restrict all mo calls international roam menu of setting
const GUIMENU_ITEM_T menu_set_bar_all_mo_calls_intl_roam_opt[] =
{
#ifdef VT_SUPPORT//@zhaohui modify
    {ID_SET_DIVERTS_AUDIO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CALL_AUDIO, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VIDEOCALL, 0, 0, 0, NULL},
    {ID_SET_DIVERTS_AUDIOANDVIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_AUDIOANDVIDEO_CALL, 0, 0, 0, NULL},
#else
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
#endif
 };


//@zhaohui add start
const GUIMENU_ITEM_T menu_set_audio_call_opt[] =
{
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
};

const GUIMENU_ITEM_T menu_set_video_call_opt[] =
{
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
};

const GUIMENU_ITEM_T menu_set_audioandvideo_call_opt[] =
{
    {ID_SET_SS_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_SS_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_SS_QUERY_STATUS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_QUERY_STATUS, 0, 0, 0, NULL},
};

//@zhaohui add end


//set pin1 menu of setting
const GUIMENU_ITEM_T menu_set_pin1_opt[] =
{
    {ID_SET_PIN_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_PIN_MODIFY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_MODIFY, 0, 0, 0, NULL},
    {ID_SET_PIN_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CLOSE, 0, 0, 0, NULL},
};

//set pin2 menu of setting
const GUIMENU_ITEM_T menu_set_pin2_opt[] =
{
    {ID_SET_PIN_MODIFY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_MODIFY, 0, 0, 0, NULL},
};

//set ipnumber option menu of setting
const GUIMENU_ITEM_T menu_set_ipnumber_active_opt[] =
{
    {ID_SET_IPNUMBER_ACTIVE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ACTIVE_OPERATIVE, 0, 0, 0, NULL},
    {ID_SET_IPNUMBER_MODIFY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MODIFY, 0, 0, 0, NULL},    
#if !defined(MMI_PDA_SUPPORT)
    {ID_SET_IPNUMBER_ADD, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_ADD, 0, 0, 0, NULL},    
#endif
    {ID_SET_IPNUMBER_DEL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE, 0, 0, 0, NULL},    
};

//set ipnumber option menu of setting
const GUIMENU_ITEM_T menu_set_ipnumber_deactive_opt[] =
{
    {ID_SET_IPNUMBER_DEACTIVE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_CANCEL, 0, 0, 0, NULL},
    {ID_SET_IPNUMBER_MODIFY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MODIFY, 0, 0, 0, NULL},      
#if !defined(MMI_PDA_SUPPORT)
    {ID_SET_IPNUMBER_ADD, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_ADD, 0, 0, 0, NULL},    
#endif
    {ID_SET_IPNUMBER_DEL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE, 0, 0, 0, NULL},   
};

#if defined(MMI_PDA_SUPPORT)
const GUIMENU_ITEM_T menu_set_ipnumber_add_opt[] =
{
    {ID_SET_IPNUMBER_ADD, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_ADD, 0, 0, 0, NULL},    
};
#endif

//set power on password menu
const GUIMENU_ITEM_T menu_set_poweron_pwd_opt[] =
{
    {ID_SET_PWD_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_OPEN, 0, 0, 0, NULL},
    {ID_SET_PWD_MODIFY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_MODIFY, 0, 0, 0, NULL},
    {ID_SET_PWD_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_CLOSE, 0, 0, 0, NULL},
};

#if defined(MMI_BLACKLIST_SUPPORT)
const GUIMENU_ITEM_T menu_blacklist_set_opt[] = 
{
    {ID_SET_BLACKLIST_LIST, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_BLACKLIST_LIST, 0, 0, 0, NULL},
    {ID_SET_BLACKLIST_SETTING, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_BLACKLIST_SETTING, 0, 0, 0, NULL},
};

#ifdef MMI_PDA_SUPPORT
const GUIMENU_ITEM_T menu_blacklist_opt[] =
{
    {ID_SET_BLACKLIST_NEW, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NEW, 0, 0, 0, NULL},
    {ID_SET_BLACKLIST_CONTACT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_BLACKLIST_CONTACT, 0, 0, 0, NULL},
    {ID_SET_BLACKLIST_DELALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DELALL, 0, 0, 0, NULL},    
};
#else
const GUIMENU_ITEM_T menu_blacklist_opt[] =
{
    {ID_SET_BLACKLIST_NEW, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_NEW, 0, 0, 0, NULL},
    {ID_SET_BLACKLIST_EDIT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_EDIT, 0, 0, 0, NULL},
    {ID_SET_BLACKLIST_DEL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DELETE, 0, 0, 0, NULL},
    {ID_SET_BLACKLIST_CONTACT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_BLACKLIST_CONTACT, 0, 0, 0, NULL},
    {ID_SET_BLACKLIST_DELALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DELALL, 0, 0, 0, NULL},    
};
#endif
#endif//#if defined(MMI_BLACKLIST_SUPPORT)

#ifdef MMI_SIM_LOCK_SUPPORT
const GUIMENU_ITEM_T menu_simlock[] =
{
    {ID_SET_SECURITY_SIM_LOCK_NETWORK, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SIM_LOCK_NETWORK, 0, 0, 0, NULL},
    {ID_SET_SECURITY_SIM_LOCK_NETWORK_SUBSET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SIM_LOCK_NETWORK_SUBSET, 0, 0, 0, NULL},
    {ID_SET_SECURITY_SIM_LOCK_SP, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SIM_LOCK_SP, 0, 0, 0, NULL},
    {ID_SET_SECURITY_SIM_LOCK_CORPORATE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_BLACKLIST_CONTACT, 0, 0, 0, NULL},
    {ID_SET_SECURITY_SIM_LOCK_USER, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SIM_LOCK_USER, 0, 0, 0, NULL},    
};
#endif
#ifdef VT_SUPPORT
//set vt call
const GUIMENU_ITEM_T menu_set_vt_opt[] =
{
    {ID_SET_VT_FALLBACK_HANDLE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VT_FALLBACK_HANDLE, 0, 0, 0, NULL},
    {ID_SET_VT_REPLACE_IMAGE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VT_REPLACE_IMAGE, 0, 0, 0, NULL},
    {ID_SET_VT_SPCIFY_SAVE_PATH, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SPCIFY_SAVE_PATH, 0, 0, 0, NULL},
    {ID_SET_VT_LOCAL_VIDEO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VT_LOCAL_VIDEO, 0, 0, 0, NULL},
    {ID_SET_VT_ONE_TIME_RING, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_VT_ONE_TIME_RING, 0, 0, 0, NULL},

};

const GUIMENU_ITEM_T menu_set_vt_custom_photo_opt[] =
{
    {ID_SET_VT_CUSTOM_PHOTO_MODIFY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_MODIFY, 0, 0, 0, NULL},
    {ID_SET_VT_CUSTOM_PHOTO_DEL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DELETE, 0, 0, 0, NULL},
};
#endif

#ifdef LCD_SLIDE_SUPPORT

//set slide tone menu
const GUIMENU_ITEM_T menu_envset_slide_tone_option[] =
{
    {ID_ENVSET_SLIDE_RING_ON, TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SLIDE_TONE_ENABLE,	0, 0, 0, NULL},
    {ID_ENVSET_SLIDE_RING_OFF, TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SLIDE_TONE_DISABLE,  0, 0, 0, NULL},
};

//slide operation setting
const GUIMENU_ITEM_T menu_set_slide_operation_option[] =
{
    {ID_SET_SLIDE_OPEN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SLIDE_OPEN, 0, 0, 0, NULL},
    {ID_SET_SLIDE_CLOSE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_SLIDE_CLOSE, 0, 0, 0, NULL},
    {ID_SET_KEYLOCK_SWITCH, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_KEYLOCK_SWITCH, 0, 0, 0, NULL},
};

#endif


#ifdef MMI_PDA_SUPPORT
const GUIMENU_ITEM_T menu_longpower_option[] =
{
    {ID_ENVSET_SILENTON, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_ENVSET_SILENTON, IMAGE_ENVSET_SILENTOFF, 0, 0, NULL},
	{ID_ENVSET_SILENTOFF, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_ENVSET_SILENTOFF, IMAGE_ENVSET_SILENTON, 0, 0, NULL},
    {ID_ENVSET_FLYON, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_FLY_MODEON, IMAGE_ENVSET_FLYOFF, 0, 0, NULL},
	{ID_ENVSET_FLYOFF, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_FLY_MODEOFF, IMAGE_ENVSET_FLYON, 0, 0, NULL},
    {ID_POWEROFF, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_POWER_OFF, IMAGE_POWEROFF, 0, 0, NULL},
};

#if defined(MMI_BLACKLIST_SUPPORT)
const GUIMENU_ITEM_T menu_blacklist_item_option[] =
{
    {ID_SET_BLACKLIST_DEL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DELETE, 0, 0, 0, NULL},
};
#endif
#endif

#if defined(MMI_INDIAN_SOS_SUPPORT)
const GUIMENU_ITEM_T menu_sos_set_opt[] = 
{
    {ID_SET_SOS_NUMBER_LIST, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_SOS_NUMBER_LIST, 0, 0, 0, NULL},
    {ID_SET_SOS_MESSAGE_SETTINGS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_SOS_MESSAGE_SETTINGS, 0, 0, 0, NULL},
    {ID_SET_SOS_TYPE_SETTINGS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SET_SOS_SETTINGS, 0, 0, 0, NULL},
    {ID_SET_SOS_INFO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_HELP, 0, 0, 0, NULL},
};

#ifdef MMI_PDA_SUPPORT
const GUIMENU_ITEM_T menu_sos_numberlist_opt[] =
{
    {ID_SET_SOS_NUMBER_CLEAR, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_ENSURE_CLEAR, 0, 0, 0, NULL},
//    {ID_SET_SOS_NUMBER_CLEAR_ALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_ENSURE_CLEAR_ALL, 0, 0, 0, NULL},
    {ID_SET_SOS_NUMBER_CONTACT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_BLACKLIST_CONTACT, 0, 0, 0, NULL},
};
#else
const GUIMENU_ITEM_T menu_sos_numberlist_opt[] =
{
    {ID_SET_SOS_NUMBER_EDIT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_EDIT, 0, 0, 0, NULL},
    {ID_SET_SOS_NUMBER_CLEAR, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_ENSURE_CLEAR, 0, 0, 0, NULL},
 //   {ID_SET_SOS_NUMBER_CLEAR_ALL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_ENSURE_CLEAR_ALL, 0, 0, 0, NULL},
    {ID_SET_SOS_NUMBER_CONTACT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_BLACKLIST_CONTACT, 0, 0, 0, NULL},
};
#endif
#endif//#if defined(MMI_INDIAN_SOS_SUPPORT)

//James li add
const GUIMENU_ITEM_T menu_volume_settings_entry[] =
{
    {ID_SET_MENU_CALL_VOLUME,    		TIP_NULL, {TXT_NULL,TXT_NULL,TXT_NULL},text_call_volume_setting, IMAGE_CALL_VOLUME_ICON, 0, 0, NULL},
    {ID_SET_MENU_RINGTONE_VOLUME,     	TIP_NULL, {TXT_NULL,TXT_NULL,TXT_NULL},text_ringtone_volume_setting, IMAGE_RINGTONE_SET_ICON, 0, 0, NULL},
};
//end

const GUIMENU_ITEM_T settings_menulist_icon[] =
{
	{ID_SETTINGS_CALLRING_SELECT, TIP_NULL,{TXT_NULL,TXT_NULL,TXT_NULL},TXT_RING,	  IMAGE_RINGTONE_SET_ICON,   0,0,MENU_NULL}, 
	{ID_SETTINGS_BACKLIGHT_TIMEOUT, 	TIP_NULL,{TXT_NULL,TXT_NULL,TXT_NULL},TXT_SET_BRIGHT_SCREEN_TIME,	  IMAGE_DISPLAYTIME_SET_ICON,   0,0,MENU_NULL},    
	{ID_SETTINGS_BRIGHTNESS, 	TIP_NULL,{TXT_NULL,TXT_NULL,TXT_NULL},TXT_COMMON_COMMON_BRIGHTNESS,	  IMAGE_BRIGHTNESS_SET_ICON,   0,0,MENU_NULL},
	{ID_SETTINGS_VOLUME, 		TIP_NULL,{TXT_NULL,TXT_NULL,TXT_NULL},text_volume_settings,	  IMAGE_VOLUME_SET_ICON,   0,0,MENU_NULL},	
	{ID_SETTINGS_RESTORE, 		TIP_NULL,{TXT_NULL,TXT_NULL,TXT_NULL},qtn_sett_list_reset_settings_bc,	  IMAGE_RESTORE_ICON,   0,0,MENU_NULL},
	{ID_SETTINGS_POWEROFF, 		TIP_NULL,{TXT_NULL,TXT_NULL,TXT_NULL},text_setting_poweroff,	  IMAGE_POWER_OFF_ICON,   0,0,MENU_NULL},
	{ID_SETTINGS_POWER_RESTART, TIP_NULL,{TXT_NULL,TXT_NULL,TXT_NULL},text_setting_powerrestart,	  IMAGE_RESTART_ICON,   0,0,MENU_NULL},
	{ID_SETTINGS_WATCH_INFO, 	TIP_NULL,{TXT_NULL,TXT_NULL,TXT_NULL},TEXT_WATCH_INFO,	  IMAGE_ABOUT_PHONE_ICON,   0,0,MENU_NULL},
#ifdef FOTA_SUPPORT
      {ID_SETTINGS_PHONE_ABUP_FOTA,TIP_NULL,{TXT_NULL,TXT_NULL,TXT_NULL},TXT_SETTINGS_ABUP_FOTA_CHECK,IMAGE_ABUP_FOTA_SET_ICON,0,0,MENU_NULL},
#endif	
};
//end

#define MENU_DEF(_TABLEID, _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, \
    _ITEMCOUNT) \
_ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, _ITEMCOUNT, 

const GUIMENU_GROUP_T set_menu_table[] = 
{
    {NULL},
#include "mmiset_menutable.def"
};

#undef MENU_DEF
/*****************************************************************************/
// 	Description : Register SET menu group
//	Global resource dependence : none
//  Author: KELLY.LI
//	Note:
/*****************************************************************************/
PUBLIC void MMISET_RegMenuGroup(void)
{
    MMI_RegMenuGroup(MMI_MODULE_SET, set_menu_table);
}

