
//[[define image information
//RES_ADD_IMG(IMAGE_BT_SEARCH_STOP, "\\MMI_RES_##\\IMAG\\IMAGE_BT_SEARCH_STOP.bmp",IMG_CMP_BMP_16_565_RLE,0)

	RES_ADD_IMG(IMAGE_ICON_ALARMCLOCK,"\\MMI_RES_##\\IMAG\\ic_launcher.png", IMG_CMP_PNG_ARGB_RLE,0)

	RES_ADD_IMG(IMAGE_ALARM_MAX,"\\MMI_RES_##\\IMAG\\add_alarm_limit.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_ALERT1,"\\MMI_RES_##\\IMAG\\alarm_alert1.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_ALERT2,"\\MMI_RES_##\\IMAG\\alarm_alert2.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_ALERT3,"\\MMI_RES_##\\IMAG\\alarm_alert3.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_ALERT4,"\\MMI_RES_##\\IMAG\\alarm_alert4.png", IMG_CMP_PNG_ARGB_RLE,0)

	RES_ADD_IMG(IMAGE_ALARM_OFF,"\\MMI_RES_##\\IMAG\\alarm_enable_off.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_ON,"\\MMI_RES_##\\IMAG\\alarm_enable_on.png", IMG_CMP_PNG_ARGB_RLE,0)

	RES_ADD_IMG(IMAGE_BG_BUTTON,"\\MMI_RES_##\\IMAG\\bg_button.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_BG_HEADER,"\\MMI_RES_##\\IMAG\\bg_header.png", IMG_CMP_PNG_ARGB_RLE,0)

	RES_ADD_IMG(IMAGE_TIME_SETTING_ACTIVE,"\\MMI_RES_##\\IMAG\\bg_setting_time_active.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_TIME_SETTING_NEGATIVE,"\\MMI_RES_##\\IMAG\\bg_setting_time_negative.png", IMG_CMP_PNG_ARGB_RLE,0)

	RES_ADD_IMG(IMAGE_ITEM_LIST_BG,"\\MMI_RES_##\\IMAG\\res_list_bg.png", IMG_CMP_PNG_ARGB_RLE,0)


	RES_ADD_IMG(IMAGE_L_BUTTON,"\\MMI_RES_##\\IMAG\\alarm_l.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_R_BUTTON,"\\MMI_RES_##\\IMAG\\alarm_r.png", IMG_CMP_PNG_ARGB_RLE,0)

	RES_ADD_IMG(IMAGE_ALARMCLOCK_ICON,"\\MMI_RES_##\\IMAG\\alarm_icon.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_CONFIRM,"\\MMI_RES_##\\IMAG\\alarm_confirm.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_DELETE,"\\MMI_RES_##\\IMAG\\alarm_delete.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_SELECETED,"\\MMI_RES_##\\IMAG\\alarm_seleceted.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_UNSELECETED,"\\MMI_RES_##\\IMAG\\alarm_unseleceted.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_OPEN,"\\MMI_RES_##\\IMAG\\alarmclock_open.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_ALARM_CLOSE,"\\MMI_RES_##\\IMAG\\alarmclock_close.png", IMG_CMP_PNG_ARGB_RLE,0)
	//]]define image information



	//[[define anim information


	//]]define anim information

	//[[define ring information

	RES_ADD_RING(RING_ALARMCLOCK_SOUND,"\\MMI_RES_##\\RING\\alarm_expire.ogg")

	//]]define ring information



	//[[define string information

	RES_ADD_STRING(TXT_ALARMCLOCK_APP_NAME,"闹钟")
	RES_ADD_STRING(TXT_NO_ALARMCLOCK,"未设置闹钟")
	RES_ADD_STRING(TXT_ADD_ALARMCLOCK,"添加闹钟")
	RES_ADD_STRING(TXT_ALARMCLOCK_SET_TIME,"设置时间")
	RES_ADD_STRING(TXT_ALARMCLOCK_SET_DATE,"设置周期")
	RES_ADD_STRING(TXT_ONLY_ONCE,"仅一次")
	RES_ADD_STRING(TXT_ALARM_TODAY,"今天")
	RES_ADD_STRING(TXT_ALARM_TOMOROOW,"明天")
	RES_ADD_STRING(TXT_ALARMCLOCK_NEXT_PAGE,"下一页")
	RES_ADD_STRING(TXT_SAVE_SET,"保存")
	RES_ADD_STRING(TXT_DAY_ONE,"一")
	RES_ADD_STRING(TXT_DAY_TWO,"二")
	RES_ADD_STRING(TXT_DAY_THREE,"三")
	RES_ADD_STRING(TXT_DAY_FOUR,"四")
	RES_ADD_STRING(TXT_DAY_FIVE,"五")
	RES_ADD_STRING(TXT_DAY_SIX,"六")
	RES_ADD_STRING(TXT_DAY_SEVEN,"日")
	RES_ADD_STRING(TXT_ALARM_WILL_ALART,"闹钟将于")
	RES_ADD_STRING(TXT_ALARM_HOUR,"小时")
	RES_ADD_STRING(TXT_ALARM_MINUTE,"分钟")
	RES_ADD_STRING(TXT_ALARM_ALART,"后响起")
	RES_ADD_STRING(TXT_ALARMC_ONE_MINUTE,"闹钟将于不到1分钟响起")

	RES_ADD_STRING(TXT_ALARMCLOCK_ADD,"新增")
	RES_ADD_STRING(TXT_ALARMCLOCK_LAY,"延迟")
	RES_ADD_STRING(TXT_ALARMCLOCK_CLOSE,"关闭")
	RES_ADD_STRING(TXT_ALARMCLOCK_OPEN,"打开")
	RES_ADD_STRING(TXT_ALARMCLOCK_SETTING,"编辑")
	RES_ADD_STRING(TXT_ALARMCLOCK_DELETE,"删除")
	RES_ADD_STRING(TXT_ALARMCLOCK_RETURN,"返回")

	RES_ADD_STRING(TXT_ALARMCLOCK_REPEAT,"重复")
	RES_ADD_STRING(TXT_ALARMCLOCK_NO_REPEAT,"不重复")

	RES_ADD_STRING(TXT_ALARMCLOCK_SLIDE_CLOSE,"滑动关闭 >>")
	RES_ADD_STRING(TXT_ALARMCLOCK_CLICK_DELAY,"点击延长闹钟")

	RES_ADD_STRING(TXT_DAY_EVERYDAY,"每天")
	RES_ADD_STRING(TXT_DAY_EVERYWEEK,"每个工作日")
	RES_ADD_STRING(TXT_DAY_Monday,"星期一")
	RES_ADD_STRING(TXT_DAY_Tuesday,"星期二")
	RES_ADD_STRING(TXT_DAY_Wednesday,"星期三")
	RES_ADD_STRING(TXT_DAY_Thursday,"星期四")
	RES_ADD_STRING(TXT_DAY_Friday,"星期五")
	RES_ADD_STRING(TXT_DAY_Saturday,"星期六")
	RES_ADD_STRING(TXT_DAY_Sunday,"星期日")

	//]]define string information
