/****************************************************************************
** File Name:      mmieng_menutable.c	                                    *
** Author:         allen				                                    *
** Date:           2004.09.09												*
** Copyright:      2003 Spreadtrum, Incoporated. All Rights Reserved. 		*
** Description:    									               			*
*****************************************************************************
**                         Important Edit History    						*
** -------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION         						*
** 09/2004        allen            Create
** 
****************************************************************************/

#ifdef ENGTD_SUPPORT

#include "guimenu.h"
#include "mmi_common.h"
#include "mmi_modu_main.h"
#include "mmi_nv.h"
#include "mmi_menutable.h"
#include "mmi_text.h"
#include "mmieng_text.h"
#include "mmiengtd_text.h"
#include "mmiengtd_menutable.h"

/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif


/*-------------------------------------------------------------------------*/
/*                         TYPES/CONSTANTS                                 */
/*-------------------------------------------------------------------------*/


const GUIMENU_ITEM_T menu_engtd[] = 
{
    //@yongwei.he 2007-04-11 add dyna eng mode
	{ID_ENG_DINA_ENG_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DYNA_MODE, 0, 0, 0, MENU_NULL},	
//	{ID_ENG_PS_BITRATE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
//	 TXT_ENG_PS_BITRATE, 0, 0, 0, NULL},
	{ID_ENG_SERVICE_TYPE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_SERVICE_TYPE, 0, 0, 0, MENU_NULL},
	{ID_ENG_SMS_PATH , TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_SMS_SERV, 0, 0, 0, MENU_NULL},	



	{ID_ENG_UART0_USEDBY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_UART0USEDBY, 0, 0, 0, MENU_NULL},
 	{ID_ENG_UART0_MIXMODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_UART0MIXMODE, 0, 0, 0, MENU_NULL},

	{ID_ENG_DSP_RESET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_DSP_RESET, 0, 0, 0, MENU_DSP_RESET},//dsp reset
	//{ID_ENG_DRXCYCLE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	// TXT_ENG_DRXCYCLE, 0, 0, 0, MENU_NULL},
    {ID_ENG_DSPSET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_DSP_SETTING, 0, 0, 0, MENU_NULL},
	 {ID_ENG_PICHSETTING, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_PICH_SETTING, 0, 0, 0, MENU_NULL},
	 {ID_ENG_VTSET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_VT_SET, 0, 0, 0, MENU_ENG_VT},
	  {ID_ENG_L1_DSP_PARAM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_L1_DSP_PARAM, 0, 0, 0, MENU_NULL},
	 {ID_ENG_UPLMN_SETTING, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_UPLMN_SETTING, 0, 0, 0, MENU_NULL},
	 {ID_ENG_APN_SETTING, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_APN_SETTING, 0, 0, 0, MENU_NULL},
#ifdef MMI_DUALMODE_ENABLE	 
 //	 {ID_ENG_SUPPORT_GSM_SIM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
//	 TXT_ENG_SUPPORT_GSM_SIM, 0, 0, 0, MENU_NULL},//@zhaohui,cr109170
#endif	 
   //    {ID_ENG_RRM_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	// TXT_ENG_RRM_TEST, 0, 0, 0, MENU_RRM_TEST},
	 /*
	{ID_ENG_NETWORK_SETTING, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_NETWORKSETTING, 0, 0, 0, MENU_NETWORK_SETTING},//Brand
	{ID_ENG_DSP_RESET, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_DSP_RESET, 0, 0, 0, MENU_DSP_RESET},//dsp reset
	{ID_ENG_ASN_SELECT, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_ASNSELECT, 0, 0, 0, MENU_NULL},
	{ID_ENG_DRXCYCLE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_DRXCYCLE, 0, 0, 0, MENU_NULL},
	 //@maggie add begin
	 {ID_ENG_VTSET, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_VT_SET, 0, 0, 0, MENU_ENG_VT},
	 //@maggie add end
	 //@maggie for cr58359 begin
	 {ID_ENG_CHIP_ID, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_CHIP_ID, 0, 0, 0, MENU_NULL},
	 //@maggie for cr58359 end
	//@maggie for cr58510 add begin
	{ID_ENG_ARM_LOG_OUT_PATH, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_ARM_LOG_OUT_PATH, 0, 0, 0, MENU_NULL},
	//@maggie for cr58510 add end
	 //@maggie add begin
    {ID_ENG_DSPSET, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_DSP_SETTING, 0, 0, 0, MENU_NULL},
	 //@maggie add end
    {ID_ENG_LOCKCELL, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_LOCKCELL, 0, 0, 0, MENU_NULL},
	 */

};

const GUIMENU_ITEM_T menu_param_set_td[] = 
{
//@xiefen add begin
	 {ID_ENG_SERVICE_TYPE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_SERVICE_TYPE, 0, 0, 0, MENU_NULL},
	{ID_ENG_GPRS_PROC, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_GPRS_PROC, 0, 0, 0, MENU_GPRS_PROC},
	{ID_ENG_ROAMPARAM, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	     TXT_ENG_ROAMPARAM, 0, 0, 0, MENU_NULL},
	 /* bo.chen 20060211 */
	{ID_ENG_SMS_PATH , TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_SMS_SERV, 0, 0, 0, MENU_NULL},
//	{ID_ENG_PS_BITRATE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},
//	 TXT_ENG_PS_BITRATE, 0, 0, 0, MENU_NULL},
	{ID_ENG_PSCTRL_FLAG, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_PSCTRL_FLAG, 0, 0, 0, MENU_PSDATA_CTRL},
	{ID_ENG_CS64_FLAG, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_CS64_FLAG, 0, 0, 0, MENU_CS64_FLAG},
	{ID_ENG_FDN_FLAG, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_FDN_FLAG, 0, 0, 0, MENU_FDN_FLAG},
	{ID_ENG_BDN_FLAG, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_BDN_FLAG, 0, 0, 0, MENU_BDN_FLAG},
	{ID_ENG_APN_SETTING, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_APN_SETTING, 0, 0, 0, MENU_NULL}
//@xiefen add end
};


const GUIMENU_ITEM_T menu_net_info[] =
{
	{ID_ENG_NETINFOLYONE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_NETINFO_L1, 0, 0, 0, MENU_NETLYONE_INFO},
	{ID_ENG_NETINFOLYTWO, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_NETINFO_L2, 0, 0, 0, MENU_NULL},
	{ID_ENG_NETINFOLYTHREE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_NETINFO_L3, 0, 0, 0, MENU_NETLYTHREE_INFO},
	{ID_ENG_NETINFONAS, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_NETINFO_NAS, 0, 0, 0, MENU_NETNAS_INFO}
	
};

const GUIMENU_ITEM_T menu_netlyone_info[] =
{
	{ID_ENG_LYONETIMESLOT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
	 TXT_ENG_LYONETIMESLOT, 0, 0, 0, MENU_NULL},
	{ID_ENG_LYONEDPCH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_LYONEDPCH, 0, 0, 0, MENU_NULL},
	{ID_ENG_LYONEBLER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_LYONEBLER, 0, 0, 0, MENU_NULL},
	 {ID_ENG_LYONEOTHER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_LYONEOTHER, 0, 0, 0, MENU_NULL}
	
	
};

const GUIMENU_ITEM_T menu_netlythree_info[] =
{
	{ID_ENG_LYTHREESCELL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_LYTHREESCELL, 0, 0, 0, MENU_NULL},
	{ID_ENG_LYTHREENCELL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_LYTHREENCELL, 0, 0, 0, MENU_NULL}
	
	
};

const GUIMENU_ITEM_T menu_netnas_info[] =
{
	{ID_ENG_NASMM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NASMM, 0, 0, 0, MENU_NULL},
	{ID_ENG_NASGMM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NASGMM, 0, 0, 0, MENU_NULL},	
	
};
const GUIMENU_ITEM_T menu_dsp_reset[] = 
{
	{ID_ENG_DSP_RESET_DSP1, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DSP_PRESET_DSP1, 0, 0, 0, MENU_NULL},
	{ID_ENG_DSP_RESET_DSP2, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DSP_RESET_DSP2, 0, 0, 0, MENU_NULL},
	{ID_ENG_DSP_RESET_BOTH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_BOTH, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_network_setting[] = 
{
	{ID_ENG_FREQ, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_FREQ, 0, 0, 0, MENU_NULL},
	{ID_ENG_IMSI, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_IMSI, 0, 0, 0, MENU_NULL},
	{ID_ENG_SIMSIMULATE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SIMSIMULATE, 0, 0, 0, MENU_SIM_SIMULATE},
	{ID_ENG_UART0_USEDBY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_UART0USEDBY, 0, 0, 0, MENU_NULL},
	{ID_ENG_DEEP_SLEEP, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DEEP_SLEEP, 0, 0, 0, MENU_NULL},	 
	{ID_ENG_RF_LOOP, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_RF_LOOP, 0, 0, 0, MENU_RF_LOOP},	 
	{ID_ENG_NETWORK_SETTING_INFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NETWORKSETTING_INFO, 0, 0, 0, MENU_NULL}
};//Brand

const GUIMENU_ITEM_T menu_sim_simulate[] = 
{
	{ID_ENG_SIMSIMULATE_ON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_ON, 0, 0, 0, MENU_NULL},
	{ID_ENG_SIMSIMULATE_OFF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_OFF, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_rf_loop[] = 
{
	{ID_ENG_RF_LOOP_ON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_ON, 0, 0, 0, MENU_NULL},
	{ID_ENG_RF_LOOP_OFF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_OFF, 0, 0, 0, MENU_NULL}
};


const GUIMENU_ITEM_T menu_gprs_proc[] = 
{
	{ID_ENG_GPRS_PROC_ATTACH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_ATTACH, 0, 0, 0, MENU_NULL},
	{ID_ENG_GPRS_PROC_DETACH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DETACH, 0, 0, 0, MENU_NULL}
};

/* bo.chen 20060211*/
const GUIMENU_ITEM_T menu_sms_serv[] = 
{
	{ID_ENG_SMS_CS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SMS_CS, 0, 0, 0, MENU_NULL},
	{ID_ENG_SMS_PS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SMS_PS, 0, 0, 0, MENU_NULL},
	{ID_ENG_SMS_CS_PREFER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SMS_CS_PREFER, 0, 0, 0, MENU_NULL},
	 {ID_ENG_SMS_PS_PERFER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	  TXT_ENG_SMS_PS_PREFER, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_rrm_test[]=
{
    	{ID_ENG_RRM_TEST_ON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_ON, 0, 0, 0, MENU_NULL},
	{ID_ENG_RRM_TEST_OFF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_OFF, 0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_psdata_ctrl[] = 
{
	{ID_ENG_PS_CTRL_ON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_ON, 0, 0, 0, MENU_NULL},
	{ID_ENG_PS_CTRL_OFF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_OFF, 0, 0, 0, MENU_NULL},    
};

const GUIMENU_ITEM_T menu_cs64_flag[] =
{
	{ID_ENG_CS64_ON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_ON, 0, 0, 0, MENU_NULL},
	{ID_ENG_CS64_OFF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_OFF, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_fdn_flag[] =
{
	{ID_ENG_FDN_ENABLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_ON, 0, 0, 0, MENU_NULL},
	{ID_ENG_FDN_DISABLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_OFF, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_bdn_flag[] =
{
	{ID_ENG_BDN_ENABLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_ON, 0, 0, 0, MENU_NULL},
	{ID_ENG_BDN_DISABLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_OFF, 0, 0, 0, MENU_NULL}
};

//@maggie add begin MENU_ENG_VT
const GUIMENU_ITEM_T menu_eng_vt[] =
{
	/*{ID_ENG_VT_AUDIO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AUDIO, 0, 0, 0, MENU_NULL},
	{ID_ENG_VT_VIDEO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_VIDEO, 0, 0, 0, MENU_NULL}*/
	 {ID_ENG_VT_RECORD_VIDEO_TYPE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_REOCRD_AUDIO_TYPE, 0, 0, 0, MENU_NULL},
	{ID_ENG_VT_ANSWERFAST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_VT_DEFAULT_EP, 0, 0, 0, MENU_NULL},
	{ID_ENG_VT_VIDEO_TYPE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_VIDEOTYPE, 0, 0, 0, MENU_NULL},
	{ID_ENG_VT_REQUESTMODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_REQUEST_MODE, 0, 0, 0, MENU_NULL},
	{ID_ENG_VT_ADAPTERLAYER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_ADAPTER_LAYER, 0, 0, 0, MENU_NULL}
};
//@maggie add end

//add by jinju.ma for bug139030
const GUIMENU_ITEM_T menu_mmiengtd_set[] =
{
	{ID_ENG_DSPPARAM_LOG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DSP_PARAM_LOG, 0, 0, 0, MENU_NULL},
	{ID_ENG_DSPPARAM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DSP_PARAM, 0, 0, 0, MENU_NULL}
};

#define MENU_DEF(_TABLEID, _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, \
	_ITEMCOUNT) \
     _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, _ITEMCOUNT, 

const GUIMENU_GROUP_T mmiengtd_menu_table[] = 
{
    {NULL},
    #include "mmiengtd_menutable.def"
};

#undef MENU_DEF

/*****************************************************************************/
// 	Description : Register eng menu group
//	Global resource dependence : none
//  Author: songbin.zeng
//	Note:
/*****************************************************************************/
PUBLIC void MMIENGTD_RegMenuGroup(void)
{
    MMI_RegMenuGroup(MMI_MODULE_ENGTD, mmiengtd_menu_table);
}

#ifdef   __cplusplus
    }
#endif

#endif// ENGTD_SUPPORT
