/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#ifndef _IOMUX_ASM_H_
#define _IOMUX_ASM_H_

//THIS FILE HAS BEEN GENERATED WITH COOLWATCHER. PLEASE EDIT WITH CARE !

//==============================================================================
// iomux
//------------------------------------------------------------------------------
///
//==============================================================================


#define REG_PIN_BASE             (0x51510000)
#define CTL_PIN_BASE                      REG_PIN_BASE

/* registers definitions for controller REG_PIN */
#define REG_PIN_PWR_PAD_CTL_RESERVED        ( CTL_PIN_BASE + 0x0000 )
#define REG_PIN_CTRL_REG0                             ( CTL_PIN_BASE + 0x0004 )
#define REG_PIN_CTRL_REG1          ( CTL_PIN_BASE + 0x0008 )
#define REG_PIN_CTRL_REG2         ( CTL_PIN_BASE + 0x000C )
#define REG_PIN_CTRL_REG3                   ( CTL_PIN_BASE + 0x0010 )
#define REG_PIN_CTRL_REG4                   ( CTL_PIN_BASE + 0x0014 )
#define REG_PIN_CTRL_REG5                   ( CTL_PIN_BASE + 0x0018 )
#define REG_PIN_RFDIG_GPIO_7                   ( CTL_PIN_BASE + 0x001C )
#define REG_PIN_RFDIG_GPIO_6                   ( CTL_PIN_BASE + 0x0020 )
#define REG_PIN_RFDIG_GPIO_5                   ( CTL_PIN_BASE + 0x0024 )
#define REG_PIN_RFDIG_GPIO_4                   ( CTL_PIN_BASE + 0x0028 )
#define REG_PIN_RFDIG_GPIO_3                   ( CTL_PIN_BASE + 0x002C )
#define REG_PIN_RFDIG_GPIO_2                      ( CTL_PIN_BASE + 0x0030 )
#define REG_PIN_RFDIG_GPIO_1                      ( CTL_PIN_BASE + 0x0034 )
#define REG_PIN_RFDIG_GPIO_0                      ( CTL_PIN_BASE + 0x0038 )
#define REG_PIN_KEYIN4                      ( CTL_PIN_BASE + 0x003C )
#define REG_PIN_KEYOUT5                      ( CTL_PIN_BASE + 0x0040 )
#define REG_PIN_KEYIN5                      ( CTL_PIN_BASE + 0x0044 )
#define REG_PIN_KEYOUT4                      ( CTL_PIN_BASE + 0x0048 )
#define REG_PIN_U1RTS                      ( CTL_PIN_BASE + 0x004C )
#define REG_PIN_U1TXD                      ( CTL_PIN_BASE + 0x0050 )
#define REG_PIN_U1RXD                      ( CTL_PIN_BASE + 0x0054 )
#define REG_PIN_U1CTS                     ( CTL_PIN_BASE + 0x0058 )
#define REG_PIN_GPIO0                     ( CTL_PIN_BASE + 0x005C )
#define REG_PIN_GPIO3                     ( CTL_PIN_BASE + 0x0060 )
#define REG_PIN_GPIO2                     ( CTL_PIN_BASE + 0x0064 )
#define REG_PIN_GPIO1                     ( CTL_PIN_BASE + 0x0068 )
#define REG_PIN_GPIO7                     ( CTL_PIN_BASE + 0x006C )
#define REG_PIN_GPIO6                     ( CTL_PIN_BASE + 0x0070 )
#define REG_PIN_GPIO5                     ( CTL_PIN_BASE + 0x0074 )
#define REG_PIN_GPIO4                     ( CTL_PIN_BASE + 0x0078 )
#define REG_PIN_ADI_SDA                     ( CTL_PIN_BASE + 0x007C )
#define REG_PIN_ADI_SCL                    ( CTL_PIN_BASE + 0x0080 )
#define REG_PIN_RESETB                    ( CTL_PIN_BASE + 0x0084 )
#define REG_PIN_OSC_32K                     ( CTL_PIN_BASE + 0x0088 )
#define REG_PIN_PMIC_EXT_INT                    ( CTL_PIN_BASE + 0x008C )
#define REG_PIN_CHIP_PD                     ( CTL_PIN_BASE + 0x0090 )
#define REG_PIN_PTEST                     ( CTL_PIN_BASE + 0x0094 )
#define REG_PIN_CLK26M_PMIC                     ( CTL_PIN_BASE + 0x0098 )
#define REG_PIN_SIM_1_RST                      ( CTL_PIN_BASE + 0x009C )
#define REG_PIN_SIM_1_DIO                      ( CTL_PIN_BASE + 0x00A0 )
#define REG_PIN_SIM_1_CLK                      ( CTL_PIN_BASE + 0x00A4 )
#define REG_PIN_SIM_0_RST                      ( CTL_PIN_BASE + 0x00A8 )
#define REG_PIN_SIM_0_DIO                     ( CTL_PIN_BASE + 0x00AC )
#define REG_PIN_SIM_0_CLK                    ( CTL_PIN_BASE + 0x00B0 )
#define REG_PIN_SW_CLK                      ( CTL_PIN_BASE + 0x00B4 )
#define REG_PIN_SW_DIO                    ( CTL_PIN_BASE + 0x00B8 )
#define REG_PIN_DEBUG_HOST_TX                     ( CTL_PIN_BASE + 0x00BC )
#define REG_PIN_DEBUG_HOST_RX                     ( CTL_PIN_BASE + 0x00C0 )
#define REG_PIN_DEBUG_HOST_CLK                    ( CTL_PIN_BASE + 0x00C4 )
#define REG_PIN_CAMERA_RST_L                     ( CTL_PIN_BASE + 0x00C8 )
#define REG_PIN_SPI_CAMERA_SCK                     ( CTL_PIN_BASE + 0x00CC )
#define REG_PIN_SPI_CAMERA_SI_1                     ( CTL_PIN_BASE + 0x00D0 )
#define REG_PIN_SPI_CAMERA_SI_0                        ( CTL_PIN_BASE + 0x00D4 )
#define REG_PIN_CAMERA_REF_CLK                        ( CTL_PIN_BASE + 0x00D8 )
#define REG_PIN_CAMERA_PWDN                      ( CTL_PIN_BASE + 0x00DC )
#define REG_PIN_I2S_SDAT_I                     ( CTL_PIN_BASE + 0x00E0 )
#define REG_PIN_I2S1_SDAT_O                       ( CTL_PIN_BASE + 0x00E4 )
#define REG_PIN_I2S1_LRCK                       ( CTL_PIN_BASE + 0x00E8 )
#define REG_PIN_I2S1_BCK                 ( CTL_PIN_BASE + 0x00EC )
#define REG_PIN_I2S1_MCLK                    ( CTL_PIN_BASE + 0x00F0 )
#define REG_PIN_I2C_M2_SCL                     ( CTL_PIN_BASE + 0x00F4 )
#define REG_PIN_I2C_M2_SDA                  ( CTL_PIN_BASE + 0x00F8 )
#define REG_PIN_Nand_SEL                    ( CTL_PIN_BASE + 0x00FC )
#define REG_PIN_KEYOUT3                     ( CTL_PIN_BASE + 0x0100 )
#define REG_PIN_KEYOUT2                  ( CTL_PIN_BASE + 0x0104 )
#define REG_PIN_KEYOUT1                    ( CTL_PIN_BASE + 0x0108 )
#define REG_PIN_KEYOUT0                    ( CTL_PIN_BASE + 0x010C )
#define REG_PIN_KEYIN3                  ( CTL_PIN_BASE + 0x0110 )
#define REG_PIN_KEYIN2                    ( CTL_PIN_BASE + 0x0114 )
#define REG_PIN_KEYIN1                    ( CTL_PIN_BASE + 0x0118 )
#define REG_PIN_KEYIN0                  ( CTL_PIN_BASE + 0x011C )
#define REG_PIN_LCD_RSTB                      ( CTL_PIN_BASE + 0x0120 )
#define REG_PIN_LCD_FMARK                      ( CTL_PIN_BASE + 0x0124 )
#define REG_PIN_SPI_LCD_SELECT                     ( CTL_PIN_BASE + 0x0128 )
#define REG_PIN_SPI_LCD_CS                      ( CTL_PIN_BASE + 0x012C )
#define REG_PIN_SPI_LCD_CLK                      ( CTL_PIN_BASE + 0x0130 )
#define REG_PIN_SPI_LCD_SDC                    ( CTL_PIN_BASE + 0x0134 )
#define REG_PIN_SPI_LCD_SIO                   ( CTL_PIN_BASE + 0x0138 )
#define REG_PIN_SDMMC1_RST                     ( CTL_PIN_BASE + 0x013C )
#define REG_PIN_SDMMC1_DATA_7                      ( CTL_PIN_BASE + 0x0140 )
#define REG_PIN_SDMMC1_DATA_6                     ( CTL_PIN_BASE + 0x0144 )
#define REG_PIN_SDMMC1_DATA_5                     ( CTL_PIN_BASE + 0x0148 )
#define REG_PIN_SDMMC1_DATA_4                      ( CTL_PIN_BASE + 0x014C )
#define REG_PIN_SDMMC1_DATA_3                     ( CTL_PIN_BASE + 0x0150 )
#define REG_PIN_SDMMC1_DATA_2                      ( CTL_PIN_BASE + 0x0154 )
#define REG_PIN_SDMMC1_DATA_1                      ( CTL_PIN_BASE + 0x0158 )
#define REG_PIN_SDMMC1_DATA_0                      ( CTL_PIN_BASE + 0x015C )
#define REG_PIN_SDMMC1_CMD                      ( CTL_PIN_BASE + 0x0160 )
#define REG_PIN_SDMMC1_CLK                     ( CTL_PIN_BASE + 0x0164 )
#define REG_PIN_U2RTS                    ( CTL_PIN_BASE + 0x0168 )
#define REG_PIN_U2CTS                    ( CTL_PIN_BASE + 0x016C )
#define REG_PIN_U2TXD                    ( CTL_PIN_BASE + 0x0170 )
#define REG_PIN_U2RXD                     ( CTL_PIN_BASE + 0x0174 )
#define REG_PIN_I2C_M1_SDA                    ( CTL_PIN_BASE + 0x0178 )
#define REG_PIN_I2C_M1_SCL                    ( CTL_PIN_BASE + 0x017C )
#define REG_PIN_GPIO23                      ( CTL_PIN_BASE + 0x0180 )
#define REG_PIN_GPIO22                    ( CTL_PIN_BASE + 0x0184 )
#define REG_PIN_GPIO21                    ( CTL_PIN_BASE + 0x0188 )
#define REG_PIN_GPIO20                    ( CTL_PIN_BASE + 0x018C )
#define REG_PIN_GPIO19                    ( CTL_PIN_BASE + 0x0190 )
#define REG_PIN_GPIO18                     ( CTL_PIN_BASE + 0x0194 )
#define REG_PIN_GPIO17                       ( CTL_PIN_BASE + 0x0198 )
#define REG_PIN_GPIO16                       ( CTL_PIN_BASE + 0x019C )
#define REG_PIN_M_SPI_D_3                       ( CTL_PIN_BASE + 0x01A0 )
#define REG_PIN_M_SPI_D_2                       ( CTL_PIN_BASE + 0x01A4 )
#define REG_PIN_M_SPI_D_1                       ( CTL_PIN_BASE + 0x01A8 )
#define REG_PIN_M_SPI_D_0                       ( CTL_PIN_BASE + 0x01AC )
#define REG_PIN_M_SPI_D_CS                    ( CTL_PIN_BASE + 0x01B0 )
#define REG_PIN_M_SPI_D_CLK                      ( CTL_PIN_BASE + 0x01B4 )
/* registers definitions for controller CTL_PIN MISC_OFFSET */
#define REG_MISC_PIN_RFDIG_GPIO_7                   ( CTL_PIN_BASE + 0x041C )
#define REG_MISC_PIN_RFDIG_GPIO_6                   ( CTL_PIN_BASE + 0x0420 )
#define REG_MISC_PIN_RFDIG_GPIO_5                   ( CTL_PIN_BASE + 0x0424 )
#define REG_MISC_PIN_RFDIG_GPIO_4                   ( CTL_PIN_BASE + 0x0428 )
#define REG_MISC_PIN_RFDIG_GPIO_3                   ( CTL_PIN_BASE + 0x042C )
#define REG_MISC_PIN_RFDIG_GPIO_2                      ( CTL_PIN_BASE + 0x0430 )
#define REG_MISC_PIN_RFDIG_GPIO_1                      ( CTL_PIN_BASE + 0x0434 )
#define REG_MISC_PIN_RFDIG_GPIO_0                      ( CTL_PIN_BASE + 0x0438 )
#define REG_MISC_PIN_KEYIN4                      ( CTL_PIN_BASE + 0x043C )
#define REG_MISC_PIN_KEYOUT5                      ( CTL_PIN_BASE + 0x0440 )
#define REG_MISC_PIN_KEYIN5                      ( CTL_PIN_BASE + 0x0444 )
#define REG_MISC_PIN_KEYOUT4                      ( CTL_PIN_BASE + 0x0448 )
#define REG_MISC_PIN_U1RTS                      ( CTL_PIN_BASE + 0x044C )
#define REG_MISC_PIN_U1TXD                      ( CTL_PIN_BASE + 0x0450 )
#define REG_MISC_PIN_U1RXD                      ( CTL_PIN_BASE + 0x0454 )
#define REG_MISC_PIN_U1CTS                     ( CTL_PIN_BASE + 0x0458 )
#define REG_MISC_PIN_GPIO0                     ( CTL_PIN_BASE + 0x045C )
#define REG_MISC_PIN_GPIO3                     ( CTL_PIN_BASE + 0x0460 )
#define REG_MISC_PIN_GPIO2                     ( CTL_PIN_BASE + 0x0464 )
#define REG_MISC_PIN_GPIO1                     ( CTL_PIN_BASE + 0x0468 )
#define REG_MISC_PIN_GPIO7                     ( CTL_PIN_BASE + 0x046C )
#define REG_MISC_PIN_GPIO6                     ( CTL_PIN_BASE + 0x0470 )
#define REG_MISC_PIN_GPIO5                     ( CTL_PIN_BASE + 0x0474 )
#define REG_MISC_PIN_GPIO4                     ( CTL_PIN_BASE + 0x0478 )
#define REG_MISC_PIN_ADI_SDA                     ( CTL_PIN_BASE + 0x047C )
#define REG_MISC_PIN_ADI_SCL                    ( CTL_PIN_BASE + 0x0480 )
#define REG_MISC_PIN_RESETB                    ( CTL_PIN_BASE + 0x0484 )
#define REG_MISC_PIN_OSC_32K                     ( CTL_PIN_BASE + 0x0488 )
#define REG_MISC_PIN_PMIC_EXT_INT                    ( CTL_PIN_BASE + 0x048C )
#define REG_MISC_PIN_CHIP_PD                     ( CTL_PIN_BASE + 0x0490 )
#define REG_MISC_PIN_PTEST                     ( CTL_PIN_BASE + 0x0494 )
#define REG_MISC_PIN_CLK26M_PMIC                     ( CTL_PIN_BASE + 0x0498 )
#define REG_MISC_PIN_SIM_1_RST                      ( CTL_PIN_BASE + 0x049C )
#define REG_MISC_PIN_SIM_1_DIO                      ( CTL_PIN_BASE + 0x04A0 )
#define REG_MISC_PIN_SIM_1_CLK                      ( CTL_PIN_BASE + 0x04A4 )
#define REG_MISC_PIN_SIM_0_RST                      ( CTL_PIN_BASE + 0x04A8 )
#define REG_MISC_PIN_SIM_0_DIO                     ( CTL_PIN_BASE + 0x04AC )
#define REG_MISC_PIN_SIM_0_CLK                    ( CTL_PIN_BASE + 0x04B0 )
#define REG_MISC_PIN_SW_CLK                      ( CTL_PIN_BASE + 0x04B4 )
#define REG_MISC_PIN_SW_DIO                    ( CTL_PIN_BASE + 0x04B8 )
#define REG_MISC_PIN_DEBUG_HOST_TX                     ( CTL_PIN_BASE + 0x04BC )
#define REG_MISC_PIN_DEBUG_HOST_RX                     ( CTL_PIN_BASE + 0x04C0 )
#define REG_MISC_PIN_DEBUG_HOST_CLK                    ( CTL_PIN_BASE + 0x04C4 )
#define REG_MISC_PIN_CAMERA_RST_L                     ( CTL_PIN_BASE + 0x04C8 )
#define REG_MISC_PIN_SPI_CAMERA_SCK                     ( CTL_PIN_BASE + 0x04CC )
#define REG_MISC_PIN_SPI_CAMERA_SI_1                     ( CTL_PIN_BASE + 0x04D0 )
#define REG_MISC_PIN_SPI_CAMERA_SI_0                        ( CTL_PIN_BASE + 0x04D4 )
#define REG_MISC_PIN_CAMERA_REF_CLK                        ( CTL_PIN_BASE + 0x04D8 )
#define REG_MISC_PIN_CAMERA_PWDN                      ( CTL_PIN_BASE + 0x04DC )
#define REG_MISC_PIN_I2S_SDAT_I                     ( CTL_PIN_BASE + 0x04E0 )
#define REG_MISC_PIN_I2S1_SDAT_O                       ( CTL_PIN_BASE + 0x04E4 )
#define REG_MISC_PIN_I2S1_LRCK                       ( CTL_PIN_BASE + 0x04E8 )
#define REG_MISC_PIN_I2S1_BCK                 ( CTL_PIN_BASE + 0x04EC )
#define REG_MISC_PIN_I2S1_MCLK                    ( CTL_PIN_BASE + 0x04F0 )
#define REG_MISC_PIN_I2C_M2_SCL                     ( CTL_PIN_BASE + 0x04F4 )
#define REG_MISC_PIN_I2C_M2_SDA                  ( CTL_PIN_BASE + 0x04F8 )
#define REG_MISC_PIN_Nand_SEL                    ( CTL_PIN_BASE + 0x04FC )
#define REG_MISC_PIN_KEYOUT3                     ( CTL_PIN_BASE + 0x0500 )
#define REG_MISC_PIN_KEYOUT2                  ( CTL_PIN_BASE + 0x0504 )
#define REG_MISC_PIN_KEYOUT1                    ( CTL_PIN_BASE + 0x0508 )
#define REG_MISC_PIN_KEYOUT0                    ( CTL_PIN_BASE + 0x050C )
#define REG_MISC_PIN_KEYIN3                  ( CTL_PIN_BASE + 0x0510 )
#define REG_MISC_PIN_KEYIN2                    ( CTL_PIN_BASE + 0x0514 )
#define REG_MISC_PIN_KEYIN1                    ( CTL_PIN_BASE + 0x0518 )
#define REG_MISC_PIN_KEYIN0                  ( CTL_PIN_BASE + 0x051C )
#define REG_MISC_PIN_LCD_RSTB                      ( CTL_PIN_BASE + 0x0520 )
#define REG_MISC_PIN_LCD_FMARK                      ( CTL_PIN_BASE + 0x0524 )
#define REG_MISC_PIN_SPI_LCD_SELECT                     ( CTL_PIN_BASE + 0x0528 )
#define REG_MISC_PIN_SPI_LCD_CS                      ( CTL_PIN_BASE + 0x052C )
#define REG_MISC_PIN_SPI_LCD_CLK                      ( CTL_PIN_BASE + 0x0530 )
#define REG_MISC_PIN_SPI_LCD_SDC                    ( CTL_PIN_BASE + 0x0534 )
#define REG_MISC_PIN_SPI_LCD_SIO                   ( CTL_PIN_BASE + 0x0538 )
#define REG_MISC_PIN_SDMMC1_RST                     ( CTL_PIN_BASE + 0x053C )
#define REG_MISC_PIN_SDMMC1_DATA_7                      ( CTL_PIN_BASE + 0x0540 )
#define REG_MISC_PIN_SDMMC1_DATA_6                     ( CTL_PIN_BASE + 0x0544 )
#define REG_MISC_PIN_SDMMC1_DATA_5                     ( CTL_PIN_BASE + 0x0548 )
#define REG_MISC_PIN_SDMMC1_DATA_4                      ( CTL_PIN_BASE + 0x054C )
#define REG_MISC_PIN_SDMMC1_DATA_3                     ( CTL_PIN_BASE + 0x0550 )
#define REG_MISC_PIN_SDMMC1_DATA_2                      ( CTL_PIN_BASE + 0x0554 )
#define REG_MISC_PIN_SDMMC1_DATA_1                      ( CTL_PIN_BASE + 0x0558 )
#define REG_MISC_PIN_SDMMC1_DATA_0                      ( CTL_PIN_BASE + 0x055C )
#define REG_MISC_PIN_SDMMC1_CMD                      ( CTL_PIN_BASE + 0x0560 )
#define REG_MISC_PIN_SDMMC1_CLK                     ( CTL_PIN_BASE + 0x0564 )
#define REG_MISC_PIN_U2RTS                    ( CTL_PIN_BASE + 0x0568 )
#define REG_MISC_PIN_U2CTS                    ( CTL_PIN_BASE + 0x056C )
#define REG_MISC_PIN_U2TXD                    ( CTL_PIN_BASE + 0x0570 )
#define REG_MISC_PIN_U2RXD                     ( CTL_PIN_BASE + 0x0574 )
#define REG_MISC_PIN_I2C_M1_SDA                    ( CTL_PIN_BASE + 0x0578 )
#define REG_MISC_PIN_I2C_M1_SCL                    ( CTL_PIN_BASE + 0x057C )
#define REG_MISC_PIN_GPIO23                      ( CTL_PIN_BASE + 0x0580 )
#define REG_MISC_PIN_GPIO22                    ( CTL_PIN_BASE + 0x0584 )
#define REG_MISC_PIN_GPIO21                    ( CTL_PIN_BASE + 0x0588 )
#define REG_MISC_PIN_GPIO20                    ( CTL_PIN_BASE + 0x058C )
#define REG_MISC_PIN_GPIO19                    ( CTL_PIN_BASE + 0x0590 )
#define REG_MISC_PIN_GPIO18                     ( CTL_PIN_BASE + 0x0594 )
#define REG_MISC_PIN_GPIO17                       ( CTL_PIN_BASE + 0x0598 )
#define REG_MISC_PIN_GPIO16                       ( CTL_PIN_BASE + 0x059C )
#define REG_MISC_PIN_M_SPI_D_3                       ( CTL_PIN_BASE + 0x05A0 )
#define REG_MISC_PIN_M_SPI_D_2                       ( CTL_PIN_BASE + 0x05A4 )
#define REG_MISC_PIN_M_SPI_D_1                       ( CTL_PIN_BASE + 0x05A8 )
#define REG_MISC_PIN_M_SPI_D_0                       ( CTL_PIN_BASE + 0x05AC )
#define REG_MISC_PIN_M_SPI_D_CS                    ( CTL_PIN_BASE + 0x05B0 )
#define REG_MISC_PIN_M_SPI_D_CLK                      ( CTL_PIN_BASE + 0x05B4 )

/* bits definitions for register REG_PIN_XXX/ REG_MISC_PIN_XXX*/
#define BITS_PIN_DS(_x_)       ( ((_x_) << 19) & (BIT_19|BIT_20|BIT_21|BIT_22 ))
#define BIT_PIN_SLP_AP         ( BIT_13 )
//#define BIT_PIN_SLP_WTLCP      ( BIT_15 )
#define BIT_PIN_SLP_CP    ( BIT_14 )
#define BIT_PIN_SLP_ALL  (BIT_13|BIT_14|BIT_15|BIT_16|BIT_17|BIT_18)
#define BIT_PIN_SLP_ALL_CP  BIT_PIN_SLP_CP
#define BIT_PIN_SLP_NONE       (  (~(0x3f << 13)) & (BIT_13|BIT_14|BIT_15|BIT_16|BIT_17|BIT_18))
#define BITS_PIN_SLP(_x_)      ( ((_x_) << 13) & (BIT_13|BIT_14|BIT_15|BIT_16|BIT_17|BIT_18) )
#define BIT_PIN_WPUS           ( BIT_12 )
#define BIT_PIN_SE             ( BIT_11 )
#define BIT_PIN_WPU            ( BIT_7 )
#define BIT_PIN_WPD            ( BIT_6 )
#define BITS_PIN_AF(_x_)       ( ((_x_) << 2) & (BIT_2|BIT_3|BIT_4|BIT_5) )
#define BIT_PIN_SLP_WPU        ( BIT_3 )
#define BIT_PIN_SLP_WPD        ( BIT_2 )
#define BIT_PIN_SLP_IE         ( BIT_1 )
#define BIT_PIN_SLP_OE         ( BIT_0 )
/* vars definitions for controller  CTL_PIN */
#define BIT_PIN_NUL            ( 0 )
#define BIT_PIN_SLP_NUL        ( 0 )
#define BIT_PIN_SLP_Z          ( 0 )
#define BIT_PIN_NULL           ( 0 )




#endif
