#ifndef __QUATSLERPDATA_H__
#define __QUATSLERPDATA_H__

#include "MayaDataType.h" 

#define NEST_CAMERA_POSITION_TOTALFRAME 22

#define NEST_KEY_FRAME_NUM 7

extern const SLERPDATA_T Nest_CameraState[NEST_KEY_FRAME_NUM-1][NEST_CAMERA_POSITION_TOTALFRAME];

#endif