

//[[define image infomation
#if 0
RES_ADD_IMG(IMAGE_CDMA_SMARTCARD,"\\MMI_RES_##\\IMAG\\PWON\\IMAGE_SMARTCARD.gif",IMG_CMP_GIF_SCI,0)
#endif

//xiongkai new ui del mic icon RES_ADD_IMG(IMAGE_AICHAT_MIC,"\\MMI_RES_##\\IMAG\\mic.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_AI_RECORD_ANIM_01,"\\MMI_RES_##\\IMAG\\record_anim\\1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_AI_RECORD_ANIM_02,"\\MMI_RES_##\\IMAG\\record_anim\\2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_AI_RECORD_ANIM_03,"\\MMI_RES_##\\IMAG\\record_anim\\3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_AI_RECORD_ANIM_04,"\\MMI_RES_##\\IMAG\\record_anim\\4.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_AI_VOICE_LEFT_BG,"\\MMI_RES_##\\IMAG\\bg\\left_voice_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_AI_VOICE_RIGHT_BG,"\\MMI_RES_##\\IMAG\\bg\\rihgt_voice_bg.png",IMG_CMP_PNG_ARGB_RLE,0)



//[[define string infomation
RES_ADD_STRING(TXT_AICHAT_TEST,"AICHAT TEST")
RES_ADD_IMG(IMAGE_AI_RECORDING_BG,"\\MMI_RES_##\\IMAG\\recording_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_AI_NO_RECORD_BG,"\\MMI_RES_##\\IMAG\\no_record_bg.png",IMG_CMP_PNG_ARGB_RLE,0)


