/*
 * Copyright (C) 2021 UNISOC Technologies Co.,Ltd. All Rights Reserved
 *
 * Automatically generated by code_generator_unirtos.pm.
 */
#include "sci_types.h"
#include "jerry_bindings.h"
#include "js_audio_event.h"
#include "js_audio.h"
#include "os_api.h"
#include "urjs_art.h"
#define EVENT_TYPE_NAME_LENGTH   (32)
#define EVENT_ERROR_TYPE_LENGTH  (32)
typedef struct _EVENT_NAME{
    AUDIO_EVENT_TYPE_E type;
    char       name[EVENT_TYPE_NAME_LENGTH];
}AUDIO_EVENT_NAME;

const AUDIO_EVENT_NAME s_js_audio_event_name[] = {
	{EVENT_AUDIO_PLAY_CNF, "onPlay"},
	{EVENT_AUDIO_SUSPEND_IND, "onSuspend"},
	{EVENT_AUDIO_RESUME_CNF,"onResume"},
	{EVENT_AUDIO_PLAY_END_IND,"onPlayEnd"},
	{EVENT_AUDIO_PLAY_PROGRESS_IND,"playProgress"},
	{EVENT_AUDIO_PAUSE_IND,"onPause"},
	{EVENT_AUDIO_BEGIN_BUFFER_IND,"beginBuffer"},
	{EVENT_AUDIO_END_BUFFER_IND,"endBuffer"},
    {EVENT_AUDIO_STOP_IND,"onStop"},
    {EVENT_AUDIO_ERROR_IND,"onErr"},
	{EVENT_AUDIO_UNKNOWN, "unknown"}
};

typedef struct _AUDIO_ERROR_NAME{
    AUDIO_ERROR_TYPE_E error_type;
    char error_name[EVENT_ERROR_TYPE_LENGTH];
}AUDIO_ERROR_NAME;

const AUDIO_EVENT_NAME s_js_audio_error_name[] = {
    {EVENT_AUDIO_PARAM_ERROR, "paramError"},
    {EVENT_AUDIO_NO_ENOUGH_MMEMORY, "noMemory"},
    {EVENT_AUDIO_SET_VOLUME_FAIL, "setVolumeFail"},
    {EVENT_AUDIO_SET_ROUTE_FAIL, "setRouteFail"},
    {EVENT_AUDIO_GET_PLAY_PROGRESS_FAIL, "getProgressFail"},
    {EVENT_AUDIO_PLAY_FAIL, "playFail"},
    {EVENT_AUDIO_UNKNOWN_ERROR, "unknownError"},
    {EVENT_AUDIO_CREATE_FAIL, "createFail"},
    {EVENT_AUDIO_NET_ERR, "netError"},
    {EVENT_AUDIO_ERROR_MAX, "unknownError"}};
jerry_value_t makeAudioPlayConformEvent(jerry_value_t object, audio_play_confirm_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioPlayConformEvent");
    }

    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    return object;
}
static jerry_value_t parseAudioEvent(jerry_value_t this_value, audio_play_confirm_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeAudioPlayConformEvent(this_value, p_Event);
}
void js_audio_play_confirm_event(jerry_value_t this_value, audio_play_confirm_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseAudioEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_play_confirm_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
    //jerry_release_value(obj_event);
}
jerry_value_t makeAudioSuspendConformEvent(jerry_value_t object, audio_suspend_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioSuspendEvent");
    }

    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    return object;
}
static jerry_value_t parseAudioSuspendEvent(jerry_value_t this_value, audio_suspend_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeAudioSuspendConformEvent(this_value, p_Event);
}

/*****************************************************************************/
//  Description: suspend conform事件回给JS的函数
//  Parameter: [In] jerry_value_t //JS AUDIO对象
//             [In] audio_suspend_event_t //播放成功的消息及携带的数据
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_suspend_event(jerry_value_t this_value, audio_suspend_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseAudioSuspendEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_suspend_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
   //jerry_release_value(obj_event);

}
jerry_value_t makeAudioResumeConformEvent(jerry_value_t object, audio_resume_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioResumeEvent");
    }

    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    return object;
}
static jerry_value_t parseAudioResumeEvent(jerry_value_t this_value, audio_resume_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeAudioResumeConformEvent(this_value, p_Event);
}

/*****************************************************************************/
//  Description: resume conform事件回给JS的函数
//  Parameter: [In] jerry_value_t //JS AUDIO对象
//             [In] audio_resume_event_t //Resume消息及携带的数据
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_resume_event(jerry_value_t this_value, audio_resume_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseAudioResumeEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_resume_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
    //jerry_release_value(obj_event);
}
jerry_value_t makeAudioPlayEndEvent(jerry_value_t object, audio_play_end_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioPlayEndEvent");
    }

    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    return object;
}
static jerry_value_t parseAudioPlayEndEvent(jerry_value_t this_value, audio_play_end_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeAudioPlayEndEvent(this_value, p_Event);
}
/*****************************************************************************/
//  Description: play end事件回给JS的函数
//  Parameter: [In] jerry_value_t //JS AUDIO对象
//             [In] audio_play_end_event_t //play end消息及携带的数据
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_play_end_event(jerry_value_t this_value, audio_play_end_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseAudioPlayEndEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_play_end_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
    //jerry_release_value(obj_event);

}
jerry_value_t makeAudioPlayProgressEvent(jerry_value_t object, audio_play_progress_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioPlayProgressEvent");
    }

    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    prop_value = jerry_create_number(p_Event->cur_time);
    prop_name = jerry_create_string((const jerry_char_t *)"cur_time");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    prop_value = jerry_create_number(p_Event->total_time);
    prop_name = jerry_create_string((const jerry_char_t *)"total_time");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);
    return object;
}
static jerry_value_t parseAudioPlayProgressEvent(jerry_value_t this_value, audio_play_progress_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeAudioPlayProgressEvent(this_value, p_Event);
}
/*****************************************************************************/
//  Description: play pgress事件回给JS的函数
//  Parameter: [In] jerry_value_t //JS AUDIO对象
//             [In] audio_play_progress_event_t //play progress消息及携带的数据
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_play_progress_event(jerry_value_t this_value, audio_play_progress_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseAudioPlayProgressEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_play_progress_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
    //jerry_release_value(obj_event);
}
jerry_value_t makeAudioPauseEvent(jerry_value_t object, audio_pause_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioPauseEvent");
    }

    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    return object;
}
static jerry_value_t parseAudioPauseEvent(jerry_value_t this_value, audio_pause_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeAudioPauseEvent(this_value, p_Event);
}
/*****************************************************************************/
//  Description: pause事件回给JS的函数
//  Parameter: [In] jerry_value_t //JS AUDIO对象
//             [In] audio_pause_event_t //pause消息及携带的数据
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_pause_event(jerry_value_t this_value, audio_pause_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseAudioPauseEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_pause_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
    //jerry_release_value(obj_event);
}
jerry_value_t makeBeginBufferEvent(jerry_value_t object, audio_begin_buffer_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioBeginBufferEvent");
    }

    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    return object;
}
static jerry_value_t parseBeginBufferEvent(jerry_value_t this_value, audio_begin_buffer_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeBeginBufferEvent(this_value, p_Event);
}
/*****************************************************************************/
//  Description: begin buffer事件回给JS的函数
//  Parameter: [In] jerry_value_t //JS AUDIO对象
//             [In] audio_begin_buffer_event_t //begin buffer消息及携带的数据
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_begin_buffer_event(jerry_value_t this_value, audio_begin_buffer_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseBeginBufferEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_begin_buffer_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
    //jerry_release_value(obj_event);
}
jerry_value_t makeEndBufferEvent(jerry_value_t object, audio_end_buffer_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioEndBufferEvent");
    }

    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    return object;
}
static jerry_value_t parseEndBufferEvent(jerry_value_t this_value, audio_end_buffer_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeEndBufferEvent(this_value, p_Event);
}
/*****************************************************************************/
//  Description: end buffer事件回给JS的函数
//  Parameter: [In] jerry_value_t //JS AUDIO对象
//             [In] audio_end_buffer_event_t //end buffer消息及携带的数据
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_end_buffer_event(jerry_value_t this_value, audio_end_buffer_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseEndBufferEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_end_buffer_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
    //jerry_release_value(obj_event);
}
jerry_value_t makeAudioStopEvent(jerry_value_t object, audio_stop_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioStopEvent");
    }

    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    return object;
}
static jerry_value_t parseAudioStopEvent(jerry_value_t this_value, audio_stop_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeAudioStopEvent(this_value, p_Event);
}
/*****************************************************************************/
//  Description: audio stop事件回给JS的函数
//  Parameter: [In] jerry_value_t //JS AUDIO对象
//             [In] audio_stop_event_t //audio stop消息及携带的数据
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_stop_event(jerry_value_t this_value, audio_stop_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseAudioStopEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_stop_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
    //jerry_release_value(obj_event);
}
jerry_value_t makeAudioErrorEvent(jerry_value_t object, audio_error_event_t* p_Event)
{
    if (object == NULL)
    {
        object = constructObject(object,"AudioErrorEvent");
    }
    jerry_value_t prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_event_name[p_Event->type].name);
    jerry_value_t prop_name = jerry_create_string((const jerry_char_t *)"type");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    prop_value = jerry_create_string((const jerry_char_t *)s_js_audio_error_name[p_Event->err_type].name);
    prop_name = jerry_create_string((const jerry_char_t *)"errtype");
    jerry_release_value(jerry_set_property(object, prop_name, prop_value));
    jerry_release_value(prop_value);
    jerry_release_value(prop_name);

    return object;
}
static jerry_value_t parseAudioErrorEvent(jerry_value_t this_value, audio_error_event_t* p_Event)
{
    if (p_Event == NULL)
    {
        return jerry_create_undefined();
    }
    return makeAudioErrorEvent(this_value, p_Event);
}

/*****************************************************************************/
//  Description: audio error事件回给JS的函数
//  Parameter: [In] jerry_value_t //JS AUDIO对象
//             [In] audio_error_event_t //audio error消息及携带的数据
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_error_event(jerry_value_t this_value, audio_error_event_t* p_Event)
{
    jerry_value_t func_name = jerry_create_string((jerry_char_t*)"AudioEventLoop");
    jerry_value_t event_func = jerry_get_property((jerry_value_t)this_value, func_name);

    jerry_value_t obj_event = parseAudioErrorEvent(this_value,p_Event);
    jerry_value_t call_func = jerry_call_function(event_func, this_value, &obj_event, 1);
    /* Check the call function return value if there is any error */
    if (TRUE == jerry_value_is_error(call_func))
    {
		aloge("js_audio_error_event call function error is %d\n",jerry_get_error_type(call_func));
    }
    jerry_release_value(call_func);
    jerry_release_value(func_name);
    jerry_release_value(event_func);
    //jerry_release_value(obj_event);

}
