#include "paramlistdef.h"
#include "mcpref.h"

#define HELIX_AUDIENCES "\
 32 Kbps Stereo - RA 10 with aacPlus\0\
 48 Kbps Stereo - RA 10 with aacPlus\0\
 64 Kbps Stereo - RA 10 with aacPlus\0\
 96 Kbps Stereo - RA 10 with aacPlus\0\
 128Kbps Stereo - RA 10 with aacPlus\0\
 12k Substream for 28k Dial-up (11/8.5 kbps)\0\
 16k Substream for 28k Dial-up (16/16 kbps)\0\
 28k Dial-up (20/16 kbps)\0\
 56k Dial-up (CBR, 34 kbps)\0\
 64k Single ISDN (44/32 kbps)\0\
 128k Dual ISDN (96/64 kbps)\0\
 150k LAN (128/64 kbps)\0\
 256k DSL or Cable (256/64 kbps)\0\
 350k Download (VBR) (320/96 kbps)\0\
 350k Surround Stereo (320/192)\0\
 General Mobile Streaming (16/16 kbps)\0\
 General Mobile Local Playback (44/32 kbps)\0\
 PocketPC Local Playback (64/32 kbps)\0\
 Lossless Audio\0"

#define _TRUE (void*)1

PARAM_DATA prefParams[]={
	{PT_CATALOG,0,0,0,"Overall", "Overall"},
	{PT_SEPERATOR,PF_NODE,0,0,"General", "General"},
	{PT_ENUM,0,0,0,"Encoder Priority", "EncoderPriority" ,"Idle\0Lowest\0Lower\0Normal\0", (void*)0},
	{PT_STRING,0,0,255,"Media Files Types", "FileTypes", 0,0},
	{PT_BOOL,0,0,0,"Recurse When Adding Directory", "RecurseDir", 0,_TRUE},
	{PT_BOOL,0,0,0,"Save Encoding List on Exit", "SaveList" ,0,_TRUE},
	{PT_BOOL,0,0,0,"Enable Logging to File", "LogFile" ,0,0},
	{PT_FILE,0,0,0,"Log File", "LogFileName" ,0,"mediacoder.log"},
	{PT_BOOL,0,0,0,"Enable built-in HTTP deamon", "EnableHttpd" ,0,0},
	{PT_INT,0,0,0,"HTTP deamon port", "HttpdPort" ,0,(void*)8000},
	{PT_BOOL,0,0,0,"Check for update at startup", "CheckUpdate" ,0,0},

	{PT_SEPERATOR,PF_NODE,0,0,"User Interface", "UI"},
	{PT_BOOL,0,0,0,"Show Console Window", "ConsoleWindow", 0,0},
	{PT_BOOL,0,0,0,"Be more quiet in console window","Quiet",0,0},
	{PT_BOOL,0,0,0,"Show Pop-up Messages", "PopupMessages", 0,_TRUE},
	{PT_ENUM,0,0,0,"Show Statistic Window", "StatsWindow", "Auto\0Always\0Never\0",0},
	{PT_ENUM,0,0,0,"Command Line View", "CommandView", "Audio Command\0Video Command\0Container Command\0Console Output\0",0},
	{PT_BOOL,0,0,0,"Show Splash on Startup", "Splash", 0,_TRUE},
	{PT_INT,0,0,255,"Window Face Alpha Value", "WindowAlphaValue", 0,(void*)255},

	{PT_SEPERATOR,PF_NODE,0,0,"Task", "Task"},
	{PT_DIR,0,0,0,"Output Folder", "OutputFolder", 0,0},
	{PT_DIR,0,0,0,"Working Folder", "WorkingFolder", 0,0},
	{PT_ENUM,0,0,0,"Overwriting Action", "Overwrite", "Ask\0Overwrite\0Back up existed file and overwrite\0Skip\0",0},
	{PT_BOOL,0,0,0,"Keep unfinished file", "KeepUnfinished", 0,0},
	{PT_BOOL,0,0,0,"Keep intermediate files", "KeepIntermediate", 0,0},
	{PT_BOOL,0,0,0,"Delete original files after transcoding", "DeleteOriginal", 0,0},
	{PT_BOOL,PF_NOSAVE,0,0,"Power off when all tasks done", "PowerOffWhenDone", 0,0,0},
	{PT_INT,0,0,0,"Decoder hanging timeout", "Timeout", 0, (void*)10000},

	{PT_SEPERATOR,PF_NODE,0,0,"Tagging & Naming", "TaggingNaming"},
	{PT_BOOL,0,0,0,"Transfer Tags", "Tag", 0,_TRUE},
	{PT_BOOL,0,0,0,"Use formatted output file names", "FormattedFileName", 0,0},
	{PT_STRING,0,0,255,"Output file name format", "NameFormat", 0,"$(Artist) - $(Title)"},
	{PT_BOOL,0,0,0,"Output Directory Structure", "OutputDir", 0, 0},
	{PT_BOOL,0,0,0,"Automatically create unexistent directories", "CreateDir",0,_TRUE},

	{PT_SEPERATOR,PF_NODE,0,0,"Decoding Options", "Decoding"},
	{PT_INT,0,0,0,"Start Time", "StartTime", 0,0},
	{PT_INT,0,0,0,"Duration", "Duration", 0,0},
	{PT_STRING,0,0,7,"Subtitle Language", "SubtitleLang", 0,0},
	{PT_STRING,0,0,7,"Audio Language", "AudioLang", 0,0},
	{PT_INT,0,0,0,"Audio ID", "AudioID", 0,0},
	{PT_INT,0,0,0,"Video ID", "VideoID", 0,0},
	{PT_ENUM,0,0,0,"Number of Playback Channel", "Channel", "Default\0\t2\0\t4\0\t6\0",0},
	{PT_FILE,0,0,0,"External Audio File", "AudioFile", 0,0},
	{PT_INT,0,0,0,"Cache Size (KB)", "CacheSize", 0,0},
	{PT_INT,0,0,0,"Force Sample Rate (0 to disable)", "ForceSampleRate", 0, 0},
	{PT_BOOL,0,0,0,"Force index rebuilding (for AVI)","ForceIndex",0,_TRUE},
	{PT_BOOL,0,0,0,"Using MediaInfo to read information media files", "EnableMediaInfo", 0, _TRUE},

	{PT_SEPERATOR,PF_NODE,0,0,"Audio Options", "Audio"},
	{PT_ENUM,0,0,0,"Audio Source", "Source", 0,0},
	{PT_ENUM,0,0,0,"Audio Encoder", "Encoder",0,(void*)1},
	{PT_BOOL,0,0,0,"Force Intermediate Waveform File", "UseWaveFile", 0,0},
	{PT_STRING,0,0,127,"Disabled Winamp Input Plugins", "DisabledInputPlugins", 0,0},
	{PT_BOOL,0,0,127,"Filter Audio with DSP Plugins", "DspPlugins", 0,0},
	{PT_STRING,0,0,127,"Enabled DSP Plugins", "EnabledDspPlugins", 0,0},
	{PT_BOOL,0,0,0,"Transcode all available tracks in container", "AllTracks",0,0},
	{PT_INT,0,0,0,"Start with audio track ID", "StartAID",0,0},
	{PT_INT,0,-30000,30000,"Audio Delay", "AudioDelay",0,0},

	{PT_SEPERATOR,PF_NODE,0,0,"Video Options", "Video"},
	{PT_ENUM,0,0,0,"Video Encoder", "Encoder", 0,0},
	//@richardguan
#ifndef LANG_ZH
	{PT_ENUM,0,0,0,"Video Compression Format", "Format", "No Video\0MPEG-4\0MJPEG\0",(void*)1},
#else
	{PT_ENUM,0,0,0,"Video Compression Format", "Format", "不输出视频\0MPEG-4\0MJPEG\0",(void*)1},
#endif
    //{PT_ENUM,0,0,0,"Video Compression Format", "Format", "不输出视频\0MPEG-4\0",(void*)1},

	{PT_ENUM,0,0,0,"Encode Mode", "Mode", "Fixed Bit Rate\0Fixed Quality\0Two-Pass\0Three-Pass",0},
	{PT_INT,0,0,8192,"Bitrate", "Bitrate", 0,(void*)200},
	{PT_INT,0,1,100,"Quality", "Quality", 0,(void*)50},
//@ Liu Kai 
	{PT_ENUM,0,0,0,"Output Frame Rate", "FPS", "5\0\t8\0\t10\0\t12\0\t14\0\t15\0\t18\0\t20\0\t22\0\t24\0\t25\0\t30\0",(void*)5},
	{PT_BOOL,0,0,0,"Constant Frame Rate" , "NoSkip" ,0, _TRUE},
	{PT_BOOL,0,0,0,"Auto fit frame rate for video codec profile", "FitFPS", 0, 0},
	{PT_BOOL,0,0,0,"Auto fit frame geometry for video codec profile", "FitGeometry", 0, _TRUE},
	{PT_BOOL,0,0,0,"Auto Video Bitrate Adjustment", "AutoAdjustBitrate", 0,0},

	{PT_SEPERATOR,PF_NODE,0,0,"MEncoder Options", "Audio"},
	{PT_BOOL,0,0,0,"Load MEncoder DLL", "LoadDLL", 0,0},
	{PT_DIR,0,0,0,"MEncoder Path", "MEncoderPath", 0, ".\\codecs\\"},
	{PT_STRING,0,0,127,"Extra MEncoder Options", "MEncoderOptions", 0,0},

	{PT_CATALOG,0,0,0,"Audio Sources", "AudioSources"},
	{PT_SEPERATOR,PF_NODE,0,0,"MPlayer", "MPlayer"},
	{PT_BOOL,0,0,0,"Load MPlayer DLL", "LoadDLL", 0, 0},
	{PT_BOOL,0,0,0,"Bypass Video Decoding", "BypassVideo", 0, _TRUE},
	{PT_DIR,0,0,0,"MPlayer Path", "Path", 0, ".\\codecs\\"},
	{PT_STRING,0,0,127,"Extra MPlayer Options", "Options", 0,0},

	{PT_SEPERATOR,PF_NODE,0,0,"Winamp Input Plugins", "WinampInputPlugins"},
	{PT_DIR,0,0,0,"Plugins Directory", "Directory", 0,".\\plugins\\"},

	{PT_SEPERATOR,PF_NODE,0,0,"Wave/PCM File", "WaveFile"},
	{PT_BOOL,0,0,0,"Treat as raw PCM", "RawPCM", 0,0},

	{PT_CATALOG,0,0,0,"Audio Encoders", "AudioEncoders"},
	{PT_SEPERATOR,PF_NODE,0,0,"Lame", "Lame"},
	{PT_INT,0,0,320,"Bit Rate (ABR/CBR)", "BitRate", 0,(void*)128},
	{PT_INT,0,0,9,"Quantitizer (VBR)", "Quantitizer", 0,(void*)7},
	{PT_INT,0,0,320,"Minimum Allowed Bit Rate (VBR)", "MinBitrate", 0,(void*)32},
	{PT_INT,0,0,320,"Maximum Allowed Bit Rate (VBR)", "MaxBitrate", 0,(void*)320},
	{PT_INT,0,0,9,"Algorithm Quality", "Quality", 0,0},
	{PT_ENUM,0,0,0,"Encoding Mode", "Mode", "VBR\0ABR\0CBR\0",0},
	{PT_ENUM,0,0,0,"Stereo Mode", "Stereo", "Auto\0Stereo\0Joint Stereo\0Dual Channel\0Mono\0",0},
	{PT_ENUM,0,0,0,"ReplayGain", "ReplayGain", "Fast\0Accurate (Slower)\0Disabled\0",0},
	{PT_BOOL,0,0,0,"Keep All Frequencies", "NoFilter", 0,_TRUE},
	{PT_INT,0,0,0,"Low-pass Filter Frequencies (Khz)", "LowPass", 0, 0},
	{PT_INT,0,0,0,"High-pass Filter Frequencies (Khz)", "HighPass", 0, 0},
	{PT_BOOL,0,0,0,"Mark as Copyright", "MarkCopyright", 0,0},
	{PT_BOOL,0,0,0,"Mark as Non-orignal", "MarkNonOriginal", 0,0},
	{PT_BOOL,0,0,0,"Error Protection", "ErrorProtection", 0,0},
	{PT_BOOL,0,0,0,"Disable the Bit Reservoir", "DisableBitReservoir", 0,0},
	{PT_BOOL,0,0,0,"Comply to ISO MPEG Spec", "ISO", 0,0},
	{PT_FILE,0,0,0,"Lame Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\lame.exe"},

	{PT_SEPERATOR,PF_NODE,0,0,"3GPP AAC Plus Encoder", "3GPPAACPlus"},
	{PT_INT,0,10,48,"BitRate", "BitRate", 0, (void*)32},
	{PT_BOOL,0,0,0,"Enable Parametric Stereo", "Parametric", 0, _TRUE},
	{PT_DIR,0,0,0,"3GPP AAC+ Encoder Library Path", "Path", 0, ".\\codecs\\"},

	{PT_SEPERATOR,PF_NODE,0,0,"AMR", "AMR"},
	{PT_ENUM,0,0,0,"Codec", "Codec", "AMR Narrow Band\0AMR Wide Band\0", 0},
	{PT_INT,0,0,9,"Mode", "Mode", 0,(void*)7},
	{PT_BOOL,0,0,8,"Allow DTX", "DTX", 0, 0},
	{PT_FILE,0,0,0,"AMR Encoder Library", "Path", "DLL Files\0*.dll\0",".\\codecs\\libamrnb-2.dll"},

	{PT_SEPERATOR,PF_NODE,0,0,"Ogg/Vorbis", "Vorbis"},
	{PT_ENUM,0,0,0,"Mode", "Mode", "Quality\0Bitrate\0",0},
	{PT_INT,0,0,1000,"Quality", "Quality", 0,(void*)275},
	{PT_INT,0,16,256,"BitRate", "BitRate", 0,(void*)128},
	{PT_INT,0,0,256,"Minimum Bit Rate (kbps)", "MinBitrate", 0,(void*)0},
	{PT_INT,0,0,256,"Maximum Bit Rate (kbps)", "MaxBitrate", 0,(void*)0},
	{PT_INT,0,0,0,"Resample", "Resample", 0,(void*)0},
	{PT_BOOL,0,0,0,"Downmix to mono", "Downmix", 0,0},
	{PT_FILE,0,0,0,"Encoder Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\oggenc.exe"},

	{PT_SEPERATOR,PF_NODE,0,0,"CT AAC+ Encoder", "AACPlus"},
	{PT_INT,0,16,320,"BitRate", "BitRate", 0,(void*)48},
	{PT_ENUM,0,0,0,"Channel Mode", "Mode", "Mono\0Stereo\0Stereo Independent\0Parametric Stereo\0Dual Channel",(void*)3},
	{PT_ENUM,0,0,0,"AAC Type", "Format", "aacPlus\0LC-AAC\0aacPlusHigh\0", 0},
	{PT_ENUM,0,0,0,"AAC Version","AACVer","MPEG-2 AAC\0MPEG-4 AAC\0", (void*)1},
	{PT_BOOL,0,0,0,"Encode as AAC-V1", "AACV1", 0,0},
	{PT_BOOL,0,0,0,"Enable workaround for audio delay issue", "Workaround", 0, 0},
	{PT_FILE,0,0,0,"Encoder Path", "Path", "Dynamic Linking Library\0*.dll\0", 0},

	{PT_SEPERATOR,PF_NODE,0,0,"Nero AAC Encoder", "NeroAAC"},
	{PT_ENUM,0,0,0,"AAC Profile", "Profile", "Low-Complexity\0High-Complexity\0",0,0},
	{PT_ENUM,0,0,0,"Encoding Mode", "Mode", "VBR\0CBR\0",0,0},
	{PT_INT,0,3,10,"VBR Quality", "Quality", 0,(void*)4},
	{PT_INT,0,16,448,"CBR Bit Rate", "BitRate", 0,(void*)128},
	{PT_BOOL,0,0,0,"High Quality Encoding (Slower)", "HQ", 0,_TRUE},
	{PT_BOOL,0,0,0,"Downmix to Mono", "Downmix", 0,0},
	{PT_BOOL,0,0,0,"Create Hint Track for Streaming Server", "HintTrack", 0,0},
	{PT_BOOL,0,0,0,"Enable PNS for Very Low Bit Rate", "PNS", 0,0},
	{PT_DIR,0,0,0,"Nero Plugin Folder", "Path", 0,0},

	{PT_SEPERATOR,PF_NODE,0,0,"Helix Producer", "HelixProducer"},
	{PT_ENUM,0,0,0,"Audience", "Audience", HELIX_AUDIENCES,_TRUE},
	{PT_ENUM,0,0,0,"Content Type","Music\0Voice\0", "Type", 0},
	{PT_DIR,0,0,0,"Helix Producer Path", "Path", 0,".\\codecs\\producer\\producer.exe"},

	{PT_SEPERATOR,PF_NODE,0,0,"Helix MP3 Encoder", "HelixMP3"},
	{PT_ENUM,0,0,0,"Encoding Mode", "Mode", "VBR\0CBR\0",0},
	{PT_INT,0,0,320,"Bit Rate (0 for auto)", "BitRate", 0,(void*)128},
	{PT_INT,0,0,150,"VBR Scale", "Quality", 0,(void*)128},
	{PT_ENUM,0,0,0,"Stereo Mode", "Stereo", "Simple Stereo\0Joint Stereo\0Dual Channel\0Mono\0",0},
	{PT_ENUM,0,0,0,"Number of Subbands (mode-1 only)", "Subbands", "Default\0Auto\0\t4\0\t8\0\t12\0\t16\0",0},
	{PT_ENUM,0,0,0,"Input Filtering", "Filtering", "Auto\0No filtering\0DC blocking filter\0",0},
	{PT_ENUM,0,0,0,"High Frequency Encoding (allows coding >16Khz)", "HighFreq", "Disabled\0Mode-1 Granules\0All Granules\0",0},
	{PT_BOOL,0,0,0,"Using SSE instructions", "SSE", 0,_TRUE},
	{PT_STRING,0,0,127,"Extra Options", "Options", 0,0},
	{PT_FILE,0,0,0,"Encoder Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\hmp3.exe"},

	{PT_SEPERATOR,PF_NODE,0,0,"FAAC", "FAAC"},
	{PT_ENUM,0,0,0,"Mode", "Mode", "Quality\0Bitrate\0",0},
	{PT_INT,0,10,500,"Quality", "Quality", 0,(void*)50},
	{PT_INT,0,16,256,"BitRate", "BitRate", 0,(void*)128},
	{PT_ENUM,0,0,0,"AAC Object Type", "ObjectType", "Low Complexity\0Main\0SSR\0Long Term Prediction\0",0},
	{PT_ENUM,0,0,0,"MPEG Version", "MPEGVer", "MPEG-2\0MPEG-4\0",_TRUE},
	{PT_BOOL,0,0,0,"Temporal Noise Shaping", "TNS", 0,_TRUE},
	{PT_BOOL,0,0,0,"Use Mid/Side Coding", "MidSide", 0,_TRUE},
	{PT_ENUM,0,0,0,"Enable Block Type", "BlockType", "Both\0No Short\0No Long\0",0},
	{PT_FILE,0,0,0,"FAAC Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\faac.exe"},

	{PT_SEPERATOR,PF_NODE,0,0,"iTunesEncode", "iTunesEncode"},
	{PT_BOOL,0,0,0,"Keep Encoded File in iTunes Album", "KeepFile", 0,0},
	{PT_FILE,0,0,0,"Encoder Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\iTunesEncode.exe"},

	{PT_SEPERATOR,PF_NODE,0,0,"Windows Media Audio", "WMA"},
	{PT_ENUM,0,0,0,"Codec", "Codec", "Windows Media Audio 9\0Windows Media Audio 9 Voice\0Windows Media Audio 9 Lossless\0",0},
	{PT_ENUM,0,0,0,"Encoding Mode", "Mode", "One-Pass CBR\0Two-Pass CBR\0Quality-Based VBR\0Bitrate-Based VBR (2-pass)\0Bitrate-Based Peak VBR (2-pass)\0",(void*)2},
	{PT_ENUM,0,0,0,"Quality", "Quality", "Q10\0Q25\0Q50\0Q75\0Q90\0Q100\0",(void*)2},
	{PT_INT,0,0,320,"BitRate", "BitRate", 0,(void*)64},
	{PT_DIR,0,0,0,"Path of Windows Media Encoder", "Path", 0,".\\codecs\\"},

	{PT_SEPERATOR,PF_NODE,0,0,"MusePack", "MusePack"},
	{PT_ENUM,0,0,0,"Profile", "Profile", "Telephone (32~48Kbps)\0Thumb (58~86Kbps)\0Radio (112~152Kbps)\0Standard (142~184Kbps)\0Extreme (168~212Kbps)\0Insane (232~268Kbps)\0Braindead (232~278Kbps)",(void*)3},
	{PT_FILE,0,0,0,"Encoder Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\mppenc.exe"},

	{PT_SEPERATOR,PF_NODE,0,0,"WavPack", "WavPack"},
	{PT_BOOL,0,0,0,"Best Compression", "BestCompression", 0,_TRUE},
	{PT_BOOL,0,0,0,"Enable Hybrid Compression", "Hybrid", 0,0},
	{PT_INT,0,24,9600,"Hybrid Compression Bit Rate (kbps)", "HybridBitrate", 0,(void*)320},
	{PT_BOOL,0,0,0,"Create Correction File", "CorrectionFile", 0,0},
	{PT_INT,0,0,6,"Extra Encode Processing", "ExtraProcessing", 0,0},
	{PT_FILE,0,0,0,"Encoder Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\wavpack.exe"},
	{PT_STRING,0,0,31,"Extra Options", "Options", 0,0},

	{PT_SEPERATOR,PF_NODE,0,0,"Free Lossless Audio Codec", "FLAC",},
	{PT_INT,0,0,8,"Compression Level", "Level", 0,(void*)8},
	{PT_BOOL,0,0,0,"Exhaustive model search", "Exhaustive", 0,0},
	{PT_INT,0,0,32,"Maximum LPC order", "MaxLPC", 0,0},
	{PT_BOOL,0,0,0,"Verify Encoding", "Verify", 0,0},
	{PT_FILE,0,0,0,"Encoder Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\flac.exe"},
	{PT_STRING,0,0,31,"Extra Options", "Options", 0,0},

	{PT_SEPERATOR,PF_NODE,0,0,"Monkey's Audio (APE)", "APE"},
	{PT_INT,0,0,0,"Compression Level", "Level", "Fast\0Normal\0High\0Extra High\0Insane\0",(void*)3},
	{PT_FILE,0,0,0,"MACDLL Path", "Path", 0,".\\codecs\\MACDll.dll"},

	{PT_SEPERATOR,PF_NODE,0,0,"OptimFrog", "OptimFrog"},
	{PT_ENUM,0,0,0,"Optimization", "Optimization", "None\0Fast\0Normal\0High\0Best\0", (void*)4},
	{PT_FILE,0,0,0,"Encoder Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\ofr.exe"},

	{PT_SEPERATOR,PF_NODE,0,0,"Waveform/PCM", "Waveform"},
	{PT_ENUM,0,0,0,"Output Format", "Format", "Waveform File\0Raw PCM File\0", 0},

	{PT_SEPERATOR,PF_NODE,0,0,"Generic CLI Encoder", "CLIEncoder"},
	{PT_BOOL,0,0,0,"Standard input as audio data input", "Stdin", 0,_TRUE},
	{PT_BOOL,0,0,0,"Raw PCM Data (Without wave header)", "RawPCM", 0,_TRUE},
	{PT_STRING,0,0,7,"File Extension Name", "FileExt", 0,"mp3"},
	{PT_STRING,0,0,255,"Command Line", "CommandLine", 0,"lame \"$(SourceFile)\" \"$(DestFile)\""},

	{PT_SEPERATOR,PF_NODE,0,0,"FFMPEG Audio Encoder", "FFMPEG"},
	{PT_ENUM,0,0,0,"Audio Codec", "Codec", "MPEG Layer 2\0MPEG Layer 3\0AC3\0AMR Narrow Band\0AMR Wide Band\0IMA Adaptive PCM\0Sonic\0",0},
	{PT_INT,0,0,1024,"Audio Bit Rate (kbps)", "BitRate", 0,(void*)224},
	{PT_ENUM,0,0,0,"Sample Rate", "SampleRate", "Same as source\0\t8000Hz\0\t11025Hz\0\t16000Hz\0\t22050Hz\0\t24000Hz\0\t32000Hz\0\t44100Hz\0\t48000Hz\0",0},
	{PT_FILE,0,0,0,"FFMPEG Path", "Path", "Executable Files\0*.exe\0",".\\codecs\\ffmpeg.exe"},
	{PT_STRING,0,0,63,"Extra Options", "Options", 0,0},

	{PT_CATALOG,0,0,0,"Video Codecs", "VideoCodecs"},
	{PT_SEPERATOR,PF_NODE,0,0,"Xvid" ,"Xvid",},
	//@Liu Kai
	//{PT_ENUM,0,0,0,"Profile", "Profile", "Unrestricted\0Simple Profile Level 0\0Simple Profile Level 1\0Simple Profile Level 2\0Simple Profile Level 3\0Advanced Simple Profile Level 0\0Advanced Simple Profile Level 1\0Advanced Simple Profile Level 2\0Advanced Simple Profile Level 3\0Advanced Simple Profile Level 4\0Advanced Simple Profile Level 5\0DXN Handheld Profile\0DXN Portable NTSC Profile\0DXN Portable PAL Profile\0DXN Home Theater NTSC Profile\0DXN Home Theater PAL Profile\0DXN HDTV Profile\0",(void*)1},
	{PT_ENUM,0,0,0,"Profile", "Profile", "Unrestricted\0Simple Profile Level 0\0Simple Profile Level 1\0Simple Profile Level 2\0Simple Profile Level 3\0Advanced Simple Profile Level 0\0Advanced Simple Profile Level 1\0Advanced Simple Profile Level 2\0Advanced Simple Profile Level 3\0Advanced Simple Profile Level 4\0Advanced Simple Profile Level 5\0DXN Handheld Profile\0DXN Portable NTSC Profile\0DXN Portable PAL Profile\0DXN Home Theater NTSC Profile\0DXN Home Theater PAL Profile\0DXN HDTV Profile\0",(void*)0},
	{PT_INT,0,0,4,"Maximum B-frames between I/P-frames", "MaxBFrame", 0, 0},
	{PT_INT,0,0,6,"Motion Estimation Quality", "MotionEstimation", 0,(void*)6},
	{PT_BOOL,0,0,0,"Interlaced Video Content", "Interlaced", 0,0},
	{PT_BOOL,0,0,0,"Greyscale", "Greyscale", 0,0},
	{PT_ENUM,0,0,0,"Pixel Precision for Motion Search", "PixelPrecision", "Half Pixel\0Quarter\0",0},
	{PT_BOOL,0,0,0,"Global Motion Compensation", "GlobalMotionCompensation", 0, 0},
	{PT_BOOL,0,0,0,"Trellis Quantization", "Trellis", 0, 0},
	{PT_BOOL,0,0,0,"Optimize for Cartoons", "Cartoon", 0,0},
	{PT_ENUM,0,0,0,"Quantitizer Type", "Quantitizer", "H.263\0MPEG\0",0},
	{PT_BOOL,0,0,0,"Using the Chroma Planes", "ChromaPlanes", 0, 0},
	{PT_BOOL,0,0,0,"Enable a Chroma Optimizer Prefilter", "ChromaOptimizerPrefilter", 0, 0},
	{PT_BOOL,0,0,0,"High Quality AC Coefficient Prediction", "HQAC", 0,0},
	{PT_ENUM,0,0,0,"Motion Search Algorithm", "MotionSearchAlgorithm", "Off\0Mode Decision\0Limited Search\0Medium Search\0Wide Search\0",(void*)4},
	{PT_BOOL,0,0,0,"Frame Packed", "FramePacked", 0,0},
	{PT_INT,0,1,4,"Threads", "Threads", 0, (void*)1},
	{PT_STRING,0,0,63,"Extra Options","Options", 0,0},

	{PT_SEPERATOR,PF_NODE,0,0,"X264", "X264"},
	{PT_ENUM,0,0,0,"Turbo Mode", "TurboMode", "Disabled\0Reduce subq\0Reduce subq and frameref to 1\0",_TRUE},
	{PT_ENUM,0,0,0,"Fullpixel motion estimation algorithm", "me", "Diamond search, radius 1 (fast)\0Hexagon search, radius 2\0Uneven multi-hexagon search\0Exhaustive search (very slow)\0",(void*)2},
	{PT_INT,0,4,64,"Motion search radius", "me_range", 0,(void*)24},
	{PT_INT,0,1,6,"Subpel refinement quality", "subq", 0,(void*)6},
	{PT_INT,0,0,16,"Maximum B frames between I and P frames", "bframes", 0,(void*)3},
	{PT_INT,0,0,51,"P frame Quantitizer", "qp_constant", 0,(void*)26},
	{PT_INT,0,0,0,"Maximum interval between IDR-frames", "keyint", 0, (void*)250},
	{PT_INT,0,0,0,"Minimum interval between IDR-frames", "keyint_min", 0, (void*)25},
	{PT_INT,0,1,16,"Frames used as predictors in B and P frames", "frameref", 0, (void*)1},
	{PT_INT,0,1,51,"Minimum quantizer", "qp_min", 0, (void*)10},
	{PT_INT,0,1,51,"Maximum quantizer", "qp_max", 0, (void*)51},
	{PT_INT,0,1,50,"Quantizer step", "qp_step", 0, (void*)2},
	{PT_INT,0,0,100,"Quantizer compression", "qcomp", 0, (void*)60},
	{PT_INT,0,1,4,"Threads", "Threads", 0, (void*)1},
	{PT_STRING,0,0,63,"Extra Options", "Options", 0,0},

	{PT_SEPERATOR,PF_NODE,0,0,"FFMPEG", "FFMPEG"},
	{PT_ENUM,0,0,0,"Target Type", "TargetType", "Custom\0vcd\0pal-vcd\0ntsc-vcd\0svcd\0pal-svcd\0ntsc-svcd\0dvd\0pal-dvd\0ntsc-dvd\0dv\0",0},
	{PT_ENUM,0,0,0,"Macroblock decision algorithm", "MB", "Use mbcmp\0Select the MB mode which needs the fewest bits\0Select the MB mode which has the best rate distortion\0",_TRUE},
	{PT_BOOL,0,0,0,"Allow 4 motion vectors per macroblock", "Allow4MV", 0,0},
	{PT_BOOL,0,0,0,"Overlapped block motion compensation", "Overlapped", 0,0},
	{PT_BOOL,0,0,0,"Use quarter pel motion compensation", "QuarterPel", 0,0},
	{PT_INT,0,-99,6,"Diamond type & size for motion estimation", "DiamondTypeSize", 0,_TRUE},
	{PT_BOOL,0,0,0,"Trellis searched quantization", "Trellis", 0,_TRUE},
	{PT_INT,0,0,600,"Noise reduction", "NoiseReduction", 0,0},
	{PT_ENUM,0,0,0,"Quantizer noise shaping", "QNS", "Disabled\0Only lower the absolute value of coefficients\0Only change coefficients before the last non-zero coefficient + 1\0Try all\0",0},
	{PT_BOOL,0,0,0,"Activate high quality settings", "HQ", 0, 0},
	{PT_ENUM,0,0,0,"Force Aspect Ratio", "Aspect", "None\0\t4/3\0\t16/9\0\t2/1\0", 0},
	{PT_INT,0,0,300,"Maximum interval between keyframes in frames", "KeyInt", 0, (void*)250},
	{PT_INT,0,0,8000,"Minimum bitrate in kbit/sec (0 for unlimited)", "MinRate", 0, 0},
	{PT_INT,0,0,16000,"Maximum bitrate in kbit/sec (0 for unlimited)", "MaxRate", 0, 0},
	{PT_BOOL,0,0,0,"Using PSP preset", "PSP", 0, 0},
	{PT_STRING,0,0,63,"Extra Options", "Options", 0,0},

	{PT_CATALOG,0,0,0,"Container", "Container"},
	{PT_ENUM,0,0,0,"Container Format", "Format", 0, (void*)1},
	{PT_SEPERATOR,PF_NODE,0,0,"Matroska Options", "Matroska"},
	{PT_FILE,0,0,0,"Path", "Path", 0,".\\tools\\mkvmerge.exe"},
	{PT_STRING,0,0,127,"Extra Matroska Options", "Options", 0,0},
	{PT_SEPERATOR,PF_NODE,0,0,"MP4Box Options", "MP4Box"},
	{PT_BOOL,0,0,0,"Packed bitstream when importing raw ASP", "Packed", 0,0},
	{PT_BOOL,0,0,0,"Forces backward compatible AAC-SBR", "SBR", 0,0},
	{PT_BOOL,0,0,0,"Forces non-backward compatible AAC-SBR", "XSBR", 0,0},
	{PT_BOOL,0,0,0,"Keeps all MPEG-4 Systems info", "KeepAllInfo", 0,0},
	{PT_BOOL,0,0,0,"Forces MPEG-4 sample descriptions (3GPP2)", "SampleDesc", 0,0},
	{PT_BOOL,0,0,0,"Rewrites the file as an ISMA 1.0 AV file", "ISMA", 0,0},
	{PT_BOOL,0,0,0,"Rewrites as 3GPP(2) file", "Writet3GP", 0,0},
	{PT_FILE,0,0,0,"Path", "Path", 0,".\\tools\\mp4box.exe"},
	{PT_STRING,0,0,127,"Extra MP4Box Options", "Options", 0,0},
	{PT_SEPERATOR,PF_NODE,0,0,"MPEG Options", "MPEG"},
	{PT_ENUM,0,0,0,"Format", "Format", "MPEG-1\0MPEG-2\0PAL VCD\0NTSC VCD\0PAL SVCD\0NTSC SVCD\0PAL DVD\0NTSC DVD\0",0},
	{PT_SEPERATOR,PF_NODE,0,0,"LAVF Options", "LAVF"},
	{PT_ENUM,0,0,0,"Format", "Format", "MPEG\0ASF\0AVI\0MP4\0RealMedia\0QuickTime MOV\0Flash Video\0Sony Digital Video",0},
	{PT_SEPERATOR,PF_NODE,0,0,"PMP Muxer Options", "PMPMuxer"},
	{PT_FILE,0,0,0,"Path", "Path", 0,".\\tools\\pmp_muxer.exe"},

	{PT_CATALOG,0,0,0,"Audio Filters", "AudioFilters"},
#ifndef LANG_ZH //@richardguan
	{PT_ENUM,0,0,0,"Stereo Downmix", "DownMix", "Disabled\0Left Channel\0Right Channel\0Average\0",(void*)0},
#else
	{PT_ENUM,0,0,0,"Stereo Downmix", "DownMix", "不改变\0左声道\0右声道\0左右平均\0",(void*)0},
#endif
	{PT_BOOL,PF_NODE,0,0,"Shibatch Sample Rate Converter", "Shibatch", 0,0},
	{PT_BOOL,0,0,0,"Two-Pass Mode", "TwoPass", 0, _TRUE},
	{PT_ENUM,0,0,0,"Output Sampling Frequency", "SamplingRate", "Same as source\0\t8000Hz\0\t11025Hz\0\t16000Hz\0\t22050Hz\0\t24000Hz\0\t32000Hz\0\t44100Hz\0\t48000Hz\0",0},
	{PT_ENUM,0,0,0,"Output Quantization Bit Depth", "Bits", "Same as source\0\t16-bit", 0, 0},
	{PT_BOOL,0,0,0,"Normalization", "Normalization",0,_TRUE},
	{PT_ENUM,0,0,0,"Dithering", "Dithering", "Default\0No Dither\0No Noise Shaping\0Triangular Spectral Shape\0ATH based noise shaping\0Dither Amplitude < Type 3\0",0},
	{PT_FILE,0,0,0,"Path","Path",0,".\\tools\\ssrc.exe"},
	{PT_SEPERATOR,PF_NODE,0,0,"--- MPlayer Audio Filters ---", 0, 0,0},
	{PT_SEPERATOR,PF_NODE,0,0,"Resampling", "Resampling", 0,0},
	{PT_INT,0,8000,48000,"Output Sampling Frequency (0 for original)", "SamplingRate",0,0},
	{PT_BOOL,0,0,0,"High Precious Resampling", "HighPrecious", 0,_TRUE},
	{PT_ENUM,0,0,0,"Resampling Method", "Method", "Linear Interpolation\0Polyphase Filterbank (integer)\0Polyphase Filterbank (float point)\0",0},
	{PT_BOOL,PF_NODE,0,0,"Equalizer", "Equalizer", 0,0},
	{PT_INT,0,-12,12,"31.25 Hz", "EQ31.25Hz", 0,0},
	{PT_INT,0,-12,12,"62.5 Hz", "EQ62.5Hz", 0,0},
	{PT_INT,0,-12,12,"125 Hz", "EQ125Hz", 0,0},
	{PT_INT,0,-12,12,"250 Hz", "EQ250Hz", 0,0},
	{PT_INT,0,-12,12,"500 Hz", "EQ500Hz", 0,0},
	{PT_INT,0,-12,12,"1000 Hz", "EQ1Khz", 0,0},
	{PT_INT,0,-12,12,"2000 Hz", "EQ2Khz", 0,0},
	{PT_INT,0,-12,12,"4000 Hz", "EQ4Khz", 0,0},
	{PT_INT,0,-12,12,"8000 Hz", "EQ8Khz", 0,0},
	{PT_INT,0,-12,12,"16000 Hz", "EQ16Khz", 0,0},
	{PT_BOOL,PF_NODE,0,0,"Channels", "Channels", 0,0},
	{PT_INT,0,1,6,"Number of channels", "ChannelNum", 0,(void*)2},
	{PT_ENUM,0,0,0,"Source of Channel 0", "Channel0Source", "None\0Channel 0\0Channel 1\0Channel 2\0Channel 3\0Channel 4\0Channel 5\0",_TRUE},
	{PT_ENUM,0,0,0,"Source of Channel 1", "Channel1Source", "None\0Channel 0\0Channel 1\0Channel 2\0Channel 3\0Channel 4\0Channel 5\0",(void*)2},
	{PT_ENUM,0,0,0,"Source of Channel 2", "Channel2Source", "None\0Channel 0\0Channel 1\0Channel 2\0Channel 3\0Channel 4\0Channel 5\0",0},
	{PT_ENUM,0,0,0,"Source of Channel 3", "Channel3Source", "None\0Channel 0\0Channel 1\0Channel 2\0Channel 3\0Channel 4\0Channel 5\0",0},
	{PT_ENUM,0,0,0,"Source of Channel 4", "Channel4Source", "None\0Channel 0\0Channel 1\0Channel 2\0Channel 3\0Channel 4\0Channel 5\0",0},
	{PT_ENUM,0,0,0,"Source of Channel 5", "Channel5Source", "None\0Channel 0\0Channel 1\0Channel 2\0Channel 3\0Channel 4\0Channel 5\0",0},
	{PT_SEPERATOR,PF_NODE,0,0,"Volume", "Volume", 0,0},
	{PT_FLOAT,0,-200,60,"Desired Gain in dB", "Gain", 0,0},
	{PT_BOOL,0,0,0,"Enable Soft-clipping", "Clipping", 0,_TRUE},
	{PT_BOOL,PF_NODE,0,0,"Surround", "Surround", 0,0},
	{PT_FLOAT,0,0,1000,"Delay time in ms for the rear speakers", "RearDelay", 0,(void*)20},
	{PT_BOOL,PF_NODE,0,0,"Delay", "Delay", 0,0},
	{PT_FLOAT,0,0,1000,"Delay of Channel 0", "Channel0Delay", 0,0},
	{PT_FLOAT,0,0,1000,"Delay of Channel 1", "Channel1Delay", 0,0},
	{PT_FLOAT,0,0,1000,"Delay of Channel 2", "Channel2Delay", 0,0},
	{PT_FLOAT,0,0,1000,"Delay of Channel 3", "Channel3Delay", 0,0},
	{PT_FLOAT,0,0,1000,"Delay of Channel 4", "Channel4Delay", 0,0},
	{PT_FLOAT,0,0,1000,"Delay of Channel 5", "Channel5Delay", 0,0},
	{PT_BOOL,PF_NODE,0,0,"Extra Stereo", "ExtraStereo", 0,0},
	{PT_FLOAT,0,-1,10,"Difference Coefficient", "DiffCo", 0,0},
	{PT_BOOL,PF_NODE,0,0,"Volume Normalization", "Normalization", 0,0},
	{PT_BOOL,PF_NODE,0,0,"Compressor/Expander", "CompressorExpander", 0,0},
	{PT_BOOL,PF_NODE,0,0,"LADSPA", "LADSPA", 0,0},
	{PT_FILE,0,0,0,"LADSPA Plugin Library File", "LibFile", 0,0},
	{PT_STRING,0,0,63,"Label of the filter within the library", "FilterLabel", 0,0},
	{PT_FLOAT,0,0,0,"Control", "Control", 0,(void*)4},
	{PT_STRING,PF_NODE,0,64,"Extra Options", "Options", 0,0},

	{PT_CATALOG,0,0,0,"Video Filters", "VideoFilters"},
	{PT_ENUM,PF_NODE,0,0,"Post-Processing", "PostProcessing", "Disabled\0Default\0Fast\0Chorminace Only\0Luminance Only\0Auto\0Full\0",0},
	{PT_BOOL,0,0,0,"Deblocking", "Debloking", 0, 0},
	{PT_BOOL,0,0,0,"Deringing", "Deringing", 0, 0},
	{PT_BOOL,0,0,0,"Auto Brightness/Contrast", "AutoBrightnessContrast", 0, 0},
	{PT_BOOL,0,0,0,"Linear Blend Deinterlacer", "Deinterlacer", 0,0},
	{PT_BOOL,0,0,0,"Temporal Denoiser", "Denoiser", 0,0},
	{PT_BOOL,PF_NODE,0,0,"Scaling", "Scaling", 0,0},
//#ifndef LANG_ZH @richardguan
//@ Liu Kai 
	//{PT_ENUM,0,0,0,"Scale to Preset Size", "PresetSize", "Original\0\t352x288\0\t320x240\0\t220x176\0\t208x176\0\t176x144\0\t160x128\0\t160x96\0\t128x96\0\t128x64\0",(void*)5},
	{PT_ENUM,0,0,0,"Scale to Preset Size", "PresetSize", "\t320x240\0\t220x176\0\t176x144\0\t160x128\0\t240x400\0",(void*)1},
//#else
//	{PT_ENUM,0,0,0,"Scale to Preset Size", "PresetSize", "不改变\0\t352x288\0\t320x240\0\t220x176\0\t208x176\0\t176x144\0\t160x128\0\t160x96\0\t128x96\0\t128x64\0",(void*)3},
//#endif
	{PT_INT,0,0,0,"Width (0 for original)", "Width", 0,0},
	{PT_INT,0,0,0,"Height (0 for original)", "Height", 0,0},
	{PT_BOOL,0,0,0,"Interlaced Scaling", "Interlaced", 0,0},
	{PT_ENUM,0,0,0,"Chroma Skipping", "ChromaSkipping", "Use all available input lines for chroma\0Use only every 2. input line for chroma\0Use only every 4. input line for chroma\0Use only every 8. input line for chroma\0",0,0},
	{PT_ENUM,0,0,0,"Scale Algorithm", "Algorith", "Default\0VirtualDub's \"Precise Bicubic\"\0Catmull-Rom Spline\0Mitchell-Netravali Spline\0Cubic B-Spline\0", 0},
	{PT_BOOL,0,0,0,"Auto crop to keep aspect ratio", "AutoCrop", 0, 0},
	{PT_BOOL,PF_NODE,0,0,"Expanding", "Expanding", 0,0},
	{PT_INT,0,0,0,"Width", "Width", 0,0},
	{PT_INT,0,0,0,"Height", "Height", 0,0},
	{PT_INT,0,0,0,"X Position", "XPos", 0,0},
	{PT_INT,0,0,0,"Y Position", "YPos", 0,0},
	{PT_BOOL,0,0,0,"OSD/Subtitle Rendering", "OSD", 0,_TRUE},
	{PT_ENUM,0,0,0,"Force Aspect Ratio", "ForceAspect", "Disabled\0\t4:3\0\t16:9\0\t2:1\0",0},
	{PT_BOOL,PF_NODE,0,0,"Cropping", "Cropping", 0,0},
	{PT_INT,0,0,0,"Left (0 for center)", "Left", 0,0},
	{PT_INT,0,0,0,"Top (0 for center)", "Top", 0,0},
	{PT_INT,0,0,0,"Width (0 for original)", "Width", 0,0},
	{PT_INT,0,0,0,"Height (0 for original)", "Height", 0,0},
	{PT_BOOL,PF_NODE,0,0,"Crop Detect", "CropDetect", 0,0},
	{PT_INT,0,0,255,"Limit", "Limit", 0,(void*)24},
	{PT_INT,0,0,64,"Round", "Round", 0,(void*)16},
#ifndef LANG_ZH //@richardguan
	{PT_ENUM,PF_NODE,0,0,"Rotating","Rotation","Disabled\0CW + flip\0CW\0CCW \0CCW + flip\0",0},
#else
	{PT_ENUM,PF_NODE,0,0,"Rotating","Rotation","不改变\0顺时针+翻转\0顺时针\0逆时针\0逆时针+翻转\0",0},
#endif
	{PT_ENUM,PF_NODE,0,0,"De-Noise 3D", "Denoise3D", "Disabled\0Normal\0High Quality\0",0},
	{PT_INT,0,0,0,"Spatial Luma Strength", "Luma", 0,(void*)4},
	{PT_INT,0,0,0,"Spatial Chroma Strength", "Chroma", 0,(void*)3},
	{PT_INT,0,0,0,"Temporal Strength", "Temporal", 0,(void*)6},
	{PT_BOOL,PF_NODE,0,0,"Deinterlace", "Deinterlace", 0,0},
	{PT_BOOL,PF_NODE,0,0,"Screenshot", "Screenshot", 0, 0},
	{PT_SEPERATOR,PF_NODE,0,0,"Misc", "Misc", 0,0},
	{PT_STRING,0,0,64,"Extra Options", "Options", 0,0},
	{0},
};

PARAM_DESC prefInfo[] = {
	{PI_OVERALL, "Overall settings"},
	{PI_PAGE_ADEC, "Settings of audio sources"},
	{PI_PAGE_AENC, "Settings of audio encoders"},
	{PI_AF, "Audio filters allow you to modify the audio stream and its properties. (Appliable with MPlayer source only)"},
	{PI_VF, "Video filters allow you to modify the video stream and its properties."},
	{PI_DEST_DIR, "All encoded files will be put in this folder"},
	{PI_TEMP_DIR, "All temporary files will be created in this folder"},
	{PI_FILE_TYPES, "Types of files to include when adding a folder"},
	{PI_ME_OPTS, "Extra options to pass to MEncoder"},
	{PI_AUTO_BITRATE, "Automatically adjust bitrate by the collected statistics on the video"},
	{PI_XVID_MQ, "This option controls the motion estimation subsystem. The higher the value, the more precise the estimation should be (default: 6). The more precise the motion estimation is, the more bits can be saved. Precision is gained at the expense of CPU time so decrease this setting if you need realtime encoding."},
	{PI_XVID_INTERLACE, "Encode the fields of interlaced video material. Turn this option on for interlaced content."},
	{PI_XVID_GREY, "Make XviD discard chroma planes so the encoded video is greyscale only. Note that this does not speed up encoding, it just prevents chroma data from being written in the last stage of encoding."},
	{PI_XVID_QPEL, "MPEG-4 uses a half pixel precision for its motion search by default. The standard proposes a mode where encoders are allowed to use quarter pixel precision. This option usually results in a sharper image. Unfortunately it has a great impact on bitrate and sometimes the higher bitrate use will prevent it from giving a better image quality at a fixed bitrate. It's better to test with and without this option and see whether it is worth activating."},
	{PI_XVID_GMC, "Enable Global Motion Compensation, which makes XviD generate special frames (GMC-frames) which are well suited for Pan/Zoom/ Rotating images. Whether or not the use of this option will save bits is highly dependent on the source material."},
	{PI_XVID_TRELLIS, "Trellis Quantization is a kind of adaptive quantization method that saves bits by modifying quantized coefficients to make them more compressible by the entropy encoder. Its impact on quality is good, and if VHQ uses too much CPU for you, this setting can be a good alternative to save a few bits (and gain quality at fixed bitrate) at a lesser cost than with VHQ."},
	{PI_XVID_CARTOON, "Activate this if your encoded sequence is an anime/cartoon. It modifies some XviD internal thresholds so XviD takes better decisions on frame types and motion vectors for flat looking cartoons."},
	{PI_XVID_QUANTTYPE, "Sets the type of quantizer to use. For high bitrates, you will find that MPEG quantization preserves more detail. For low bitrates, the smoothing of H.263 will give you less block noise. When using custom matrices, MPEG quantization must be used."},
	{PI_XVID_CM, "The usual motion estimation algorithm uses only the luminance information to find the best motion vector. However for some video material, using the chroma planes can help find better vectors. This setting toggles the use of chroma planes for motion estimation."},
	{PI_XVID_CO, "Enable a chroma optimizer prefilter. It will do some extra magic on color information to minimize the stepped-stairs effect on edges. It will improve quality at the cost of encoding speed. It reduces PSNR by nature, as the mathematical deviation to the original picture will get bigger, but the subjective image quality will raise. Since it works with color information, you might want to turn it off when encoding in greyscale."},
	{PI_XVID_HQAC, "Activates High Quality AC coefficient prediction from neighbor blocks."},
	{PI_XVID_VHQ, "The motion search algorithm is based on a search in the usual color domain and tries to find a motion vector that minimizes the difference between the reference frame and the encoded frame. With this setting activated, XviD will also use the frequency domain (DCT) to search for a motion vector that minimizes not only the spatial difference but also the encoding length of the block. (Fastest to slowest)"},
	{PI_XVID_EXTRAOPTS, "Extra options to pass to Xvid codec"},
	{PI_MP_OPTS, "Extra options to pass to MPlayer"},
	{PI_TAGGING_NAMING, "Options of file naming and tagging"},
	{PI_RESAMPLE, "Changes the sample rate of the audio stream."},
	{PI_RESAMPLE_FREQ, "Output sample frequency in Hz"},
	{PI_RESAMPLE_HI, "Allow or disallow the output frequency to differ slightly from the frequency specified. This improves speed."},
	{PI_RESAMPLE_METHOD, "Selects which resampling method to use."},
	{PI_EQ, "10 octave band graphic equalizer, implemented using 10 IIR band pass filters. This means that it works regardless of what type of audio is being played back. The center frequencies for the 10 bands are listed below."},
	{PI_CHANNELS, "Can be used for adding, removing, routing and copying audio channels."},
	{PI_SURROUND, "Decoder for matrix encoded surround sound like Dolby Surround. Many files with 2 channel audio actually contain matrixed surround sound. Requires a sound card supporting at least 4 channels."},
	{PI_DELAY, "Delays the sound to the loudspeakers such that the sound from the different channels arrives at the listening position simultaneously. It is only useful if you have more than 2 loudspeakers."},
	{PI_XSTEREO, "(Linearly) increases the difference between left and right channels which adds some sort of 'live' effect to playback."},
	{PI_VOLNORM, "Maximizes the volume without distorting the sound."},
	{PI_LADSPA, "Load a LADSPA (Linux Audio Developer’s Simple Plugin API) plugin. This filter is reentrant, so multiple LADSPA plugins can be used at once."},
	{PI_COMP, "Compressor/expander filter usable for microphone input. Prevents artifacts on very loud sound and raises the volume on very low sound."},
	{PI_VOL, "Software volume control. Use this filter with caution since it can reduce the signal to noise ratio of the sound."},
	{PI_VOL_SOFTCLIP, "Soft-clipping can make the sound more smooth if very high volume levels are used. Enable this option if the dynamic range of the loudspeakers is very low."},
	{PI_VOL_GAIN, "Sets the desired gain in dB for all channels in the stream from -200dB to +60dB, where -200dB mutes the sound completely and +60dB equals a gain of 1000."},
	{PI_SURROUND_DELAY, "Delay time in ms for the rear speakers (0 to 1000). This delay should be set as follows: If d1 is the distance from the listening position to the front speakers and d2 is the distance from the listening position to the rear speakers, then the delay d should be set to 15ms if d1 <= d2 and to 15 + 5*(d1-d2) if d1 > d2."},
	{PI_XSTEREO_CO, "Sets the difference coefficient. 0.0 means mono sound (average of both channels), with 1.0 sound will be unchanged, with -1.0 left and right channels will be swapped."},
	{PI_LADSPA_FILE, "Specifies the LADSPA plugin library file. If LADSPA_PATH is set, it searches for the specified file. If it is not set, you must supply a fully specified pathname."},
	{PI_LADSPA_LABEL,"Specifies the filter within the library. Some libraries contain only one filter, but others contain many of them. Entering ’help’ here, will list all available filters within the specified library, which eliminates the use of ’listplugins’ from the LADSPA SDK."},
	{PI_LADSPA_CTRL, "Controls are zero or more floating point values that determine the behaviour of the loaded plugin (for example delay, threshold or gain). In verbose mode (add ??v to the MPlayer command line), all available controls and their valid ranges are printed. This eliminates the use of ’analyseplugin’ from the LADSPA SDK."},
	{PI_264_QP, "This selects the quantizer to use for P-frames. 20-40 is a useful range. Lower values result in better fidelity, but higher bitrates. 0 is lossless. Note that quantization in H.264 works differently from MPEG-1/2/4: H.264's quantization parameter (QP) is on a logarithmic scale. The mapping is ap- proximately H264QP = 12 + 6*log2(MPEGQP). For example, MPEG at QP=2 is equivalent to H.264 at QP=18."},
	{PI_264_TURBO, "Fast first pass mode. During the first pass of a two or more pass encode it is possible to gain speed by disabling some options with negligible or even no impact on the final pass output quality. Level 1 can increase first pass speed up to 2x with no change in the global PSNR of the final pass com- pared to a full quality first pass. Level 2 can increase first pass speed up to 4x with about +/- 0.05dB change in the global PSNR of the final pass compared to a full quality first pass."},
	{PI_264_SUBQ, "Adjust subpel refinement quality. This parameter controls quality versus speed tradeoffs involved in the motion estimation decision process. subq=5 can compress up to 10% better than subq=1. From fastest to slowest."},
	{PI_264_KEYINT, "Sets maximum interval between IDR-frames. Larger values save bits, thus improve quali- ty, at the cost of seeking precision. Unlike MPEG-1/2/4, H.264 does not suffer from DCT drift with large values of keyint."},
	{PI_264_KEYINTMIN, "Sets minimum interval between IDR-frames. If scenecuts appear within this interval, they are still encoded as I-frames, but do not start a new GOP. In H.264, I-frames do not neces- sarily bound a closed GOP because it is allowable for a P-frame to be predicted from more frames than just the one frame before it (also see frameref). Therefore, I-frames are not necessarily seekable. IDR-frames restrict subsequent P-frames from refer- ring to any frame prior to the IDR-frame."},
	{PI_264_FRAMEREF, "Number of previous frames used as predictors in B- and P-frames. This is effective in anime, but in live-action material the improvements usually drop off very rapidly above 6 or so reference frames. This has no effect on decoding speed, but does increase the memory needed for decoding. Some decoders can only handle a maximum of 15 reference frames."},
	{PI_264_QPSTEP, "Maximum value by which the quantizer may be incremented/decremented between frames"},
	{PI_264_QCOMP, "Quantizer compression. A lower value makes the bitrate more constant, while a higher value makes the quantization parameter more constant."},
	{PI_DEINTERLACE, "Experimental 'stateless' inverse telecine filter."},
	{PI_CROP, "Crops the given part of the image and discards the rest. Useful to remove black bands from widescreen movies."},
	{PI_CROPDETECT, "Calculates necessary cropping parameters."},
	{PI_SCALE, "Scales the image with the software scaler (slow) and performs a YUV<->RGB colorspace conversion"},
	{PI_PP, "Enables the specified chain of postprocessing sub-filters. "},
	{PI_DEN, "This filter aims to reduce image noise producing smooth images and making still images really still (This should enhance compressibility)."},
	{PI_PAGE_VCODEC, "Settings of video codecs"},
	{PI_LAME, "LAME is an LGPL MP3 encoder. The Open source development model allowed to improve its quality and speed since 1999. It is now an highly evolved MP3 encoder, with quality and speed able to rival state of the art commercial encoders."},
	{PI_OGG, "Ogg Vorbis is a completely open, patent-free, professional audio encoding and streaming technology with all the benefits of Open Source."},
	{PI_AACP, "Coding Technology's AAC+V2 encoder featuring Parametric Stereo"},
	{PI_HLX, "Helix DNA Producer"},
	{PI_FAAC, "The Free AAC Encoder"},
	{PI_FLAC, "Free Lossless Audio Codec"},
	{PI_WV, "WavPack is a completely open audio compression format providing lossless, high-quality lossy, and a unique hybrid compression mode."},
	{PI_APE, "Monkey's Audio is a fast and easy way to compress digital music."},
	{PI_CLI, "This allows you to use any generic CLI encoder that reads PCM data from stdin."},
	{PI_FF_AUDIO, "Use the audio encoders provided by FFMPEG."},
	{PI_264, "x264 is a free library for encoding H264/AVC video streams."},
	{PI_XVID, "Xvid is an open source MPEG4 based video codec"},
	{PI_FF_VIDEO, "FFmpeg is a complete solution to record, convert and stream audio and video. It includes libavcodec, the leading audio/video codec library."},
	{PI_GENERAL, "Options that control the generic behaviors of MediaCoder"},
	{PI_BATCH, "Options related with batch tasking"},
	{PI_AUDIO_OPTS, "Generic audio encoding related options"},
	{PI_VIDEO_OPTS, "Generic video encoding related options"},
	{PI_CONTAINER_OPTS, "Container related options"},
	{PI_DECODE, "Generic audio/video decoding related options"},
	{PI_MP, "MPlayer can decode many formats of audio files. What makes it different is that it can decode audio stream within video files."},
	{PI_WA, "As long as a Winamp plugin for a certain audio format is available, this format can be decoded."},
	{PI_WAVE, "Reading PCM data directly from a waveform file."},
	{PI_NAME_FORMAT, "Variable expression: $(variable name)\r\nAvailable variables: Artist, Title, Album, Track, Genre, Year, Comment, NowYear, NowMonth, NowDay, NowWeekDay, NowHour, NowMin, NowSec, SampleRate, SampleRateKhz, SampleBits, ChannelNum, DestFile, DestDir, SourceFile, SourceFileName, TempFile, SourceFile, AudioFiles."},
	{PI_STARTPOS, "The time (seconds) to starting transcoding from."},
	{PI_ENDPOS, "The amount of time (seconds) to transcode."},
	{PI_OVERWRITE, "The action to take when the target file already exists"},
	{PI_KEEP_UNFINISH, "Enable this to keep partially transcoded files"},
	{PI_KEEP_TEMP, "Enable this to keep all intermediate files created in the temporary directory."},
	{PI_DEL_ORIGINAL, "Enable this to automatically delete the original file after it is transcoded. Use with caution!"},
	{PI_POWEROFF, "Enable this to power down your PC after all tasks are done."},
	{PI_TAG, "Enable this to add tags for the target files"},
	{PI_FORMATTED_NAME, "Enable this to use formatted string as file name"},
	{PI_KEEP_DIR, "Enable this keep the directory structure of the source files"},
	{PI_XVID_THREADS, "Split each frame into slices and encode them in parallel. This has a slight penalty to compression."},
	{0,0}
};
