//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mccore_zh.rc
//
#define IDS_LAME_PATH                   2
#define IDCANCEL2                       3
#define IDC_PLAY                        3
#define IDS_OGG_PATH                    3
#define IDC_COPY                        3
#define IDC_SKIP                        4
#define IDS_FAAC_PATH                   4
#define IDCANCEL3                       4
#define IDC_REFRESH                     4
#define IDS_DEST_DIR                    5
#define IDC_PLAY2                       5
#define IDC_PREF                        5
#define IDS_WORK_DIR                    6
#define IDS_FILE_TYPES                  7
#define IDS_MENC_OPTS                   8
#define IDS_AUTO_BITRATE                9
#define IDS_XVID_MQ                     10
#define IDS_XVID_INTERLACE              11
#define IDS_XVID_GREY                   12
#define IDS_XVID_QPEL                   13
#define IDS_XVID_GMC                    14
#define IDS_XVID_TRELLIS                15
#define IDS_XVID_CARTOON                16
#define IDS_XVID_QUANTTYPE              17
#define IDS_XVID_CM                     18
#define IDS_XVID_CO                     19
#define IDS_XVID_HQAC                   20
#define IDS_XVID_VHQ                    21
#define IDS_XVID_EXTRAOPTS              22
#define IDS_MP_OPTS                     23
#define IDS_XVID_OPTS                   24
#define IDS_RESAMPLE_FREQ               25
#define IDS_RESAMPLE_HI                 26
#define IDS_RESAMPLE                    27
#define IDS_EQ                          28
#define IDS_CHANNELS                    29
#define IDS_SURROUND                    30
#define IDS_DELAY                       31
#define IDS_XSTEREO                     32
#define IDS_VOLNORM                     33
#define IDS_LADSPA                      34
#define IDS_COMP                        35
#define IDS_VOLUME                      36
#define IDS_STRING199                   80
#define IDS_STRING83                    80
#define IDD_DIALOG1                     101
#define IDD_OGG                         105
#define IDI_MAIN                        106
#define IDD_PARAM                       113
#define IDS_MP_PATH                     114
#define IDS_ME_PATH                     115
#define IDB_BITMAP1                     115
#define IDB_LOGO                        115
#define IDB_SPLASH                      115
#define IDD_DIALOG2                     147
#define IDD_WINAMP_CFG                  152
#define IDD_DIALOG3                     154
#define IDD_DIALOG4                     167
#define IDB_STOPPLAY                    183
#define IDB_ADDFILE                     184
#define IDB_ADDFOLDER                   185
#define IDB_ADDTRACK                    186
#define IDB_CLEAR                       187
#define IDB_PLAY                        188
#define IDB_PREF                        189
#define IDB_REMOVE                      190
#define IDB_BITMAP10                    191
#define IDB_SKIP                        191
#define IDB_START                       192
#define IDB_STOP                        193
#define IDD_DIALOG5                     201
#define IDC_LIST1                       1001
#define IDC_LIST                        1001
#define IDC_TRACK                       1001
#define IDS_ERROR_DECODE_AUDIO          1001
#define IDC_ADDFILE                     1002
#define IDS_AUDIO_STREAM_UNSUPPORTED    1002
#define IDC_ADDFILE2                    1003
#define IDC_ADDDIR                      1003
#define IDS_STRING1003                  1003
#define IDC_CHAPTERS                    1003
#define IDS_NOT_STANDALONE_ENCODER      1003
#define IDC_SLIDER_AUDIO                1004
#define IDS_STRING1004                  1004
#define IDC_ADDFILE4                    1004
#define IDS_ERROR_VIDEO_TRANSCODE       1004
#define IDC_SLIDER_VIDEO                1005
#define IDS_STRING1005                  1005
#define IDS_TRANSCODE_DONE              1005
#define IDC_SLIDER_AUDIO2               1006
#define IDC_SLIDER_SPEED                1006
#define IDS_STRING1006                  1006
#define IDS_INCOMPATIBLE_AV             1006
#define IDC_EDIT_AUDIO                  1007
#define IDC_AUDIO_BITRATE               1007
#define IDS_STRING1007                  1007
#define IDS_TRANSCODE_FAIL              1007
#define IDC_EDIT_VIDEO                  1008
#define IDC_VIDEO_BITRATE               1008
#define IDS_STRING1008                  1008
#define IDS_TRANSCODE_INTERRUPTED       1008
#define IDC_AUDIO_MIN                   1009
#define IDS_STRING1009                  1009
#define IDS_CANNOT_MUX_AUDIO            1009
#define IDC_AUDIO_MAX                   1010
#define IDS_ERROR_PS                    1010
#define IDC_VIDEO_MIN                   1011
#define IDS_UNSUPPORTED_MODE            1011
#define IDC_VIDEO_MAX                   1012
#define IDS_STRING1012                  1012
#define IDS_ERROR_MUX                   1012
#define IDC_AUDIO_MIN2                  1013
#define IDS_ERROR_MUXER                 1013
#define IDS_INVALID_VIDEO               1014
#define IDS_INVALID_FILE                1014
#define IDC_PROGRESS                    1015
#define IDS_STRING1015                  1015
#define IDS_ERROR_NAMED_PIPE            1015
#define IDC_AUDIO_MAX2                  1016
#define IDS_ENCODER_FAIL                1016
#define IDC_EDIT_AUDIO2                 1017
#define IDC_AUDIO_QUALITY               1017
#define IDS_SOURCE_FAIL                 1017
#define IDC_OPT_FIXRATE                 1018
#define IDS_LOADED                      1018
#define IDC_OPT_FIXQUANT                1019
#define IDS_UNLOADED                    1019
#define IDC_OPT_TWOPASS                 1020
#define IDS_APPLY_SETTINGS              1020
#define IDC_CODECS                      1021
#define IDS_ERROR_START                 1021
#define IDC_VIDEO_OPTIONS               1022
#define IDC_OPT_THREEPASS               1022
#define IDS_LOAD_AUDIO_ENCODER          1022
#define IDC_CMDLINE                     1023
#define IDS_LOAD_AUDIO_SOURCE           1023
#define IDC_ADDFILE3                    1024
#define IDC_REMOVE                      1024
#define IDS_SCAN_PLUGINS                1024
#define IDC_PROGRESS2                   1025
#define IDC_PROGRESSALL                 1025
#define IDC_WRAP                        1025
#define IDS_LOADING                     1025
#define IDC_OUTPUT_FOLDER               1026
#define IDS_ERROR_LOADING               1026
#define IDC_SETOUTPUT                   1027
#define IDS_EXTRACTING_WAVE             1027
#define IDC_CLEAR                       1028
#define IDS_STOPPED                     1028
#define IDC_OVERWRITE                   1029
#define IDS_FOUND_MATCH_PLUGIN          1029
#define IDC_STAT_POS                    1030
#define IDS_START_JOB                   1030
#define IDC_STAT_FRAME                  1031
#define IDS_FINISH_JOB                  1031
#define IDC_STAT_VB                     1032
#define IDS_OVERWRITE_CONFIRM           1032
#define IDC_STAT_AB                     1033
#define IDS_OVERWRITE_KEEP              1033
#define IDC_STAT_ESTTIME                1034
#define IDS_ERROR_DELETE                1034
#define IDC_STAT_ESTSIZE                1035
#define IDS_EXTRACT_WAVE                1035
#define IDC_STAT_SYNC                   1036
#define IDS_AMR_ERR_NOT_MATCH           1036
#define IDS_MP_NEED_UPDATE              1036
#define IDC_STAT_ELAPSED                1037
#define IDS_ERROR_AUDIO                 1037
#define IDC_STAT_FPS                    1038
#define IDS_FILE_NOT_FOUND              1038
#define IDC_STAT_TOTALTIME              1039
#define IDS_INCORRECT_VERSION           1039
#define IDC_STAT_TOTAL_FILES            1040
#define IDS_INCORRECT_SETTINGS          1040
#define IDC_STAT_ENCODED_FILES          1041
#define IDS_FAIL_START_FE               1041
#define IDC_STAT_ERROR_FILES            1042
#define IDS_ERROR_CREATE_PIPE           1042
#define IDC_STAT_SKIPPED_FILES          1043
#define IDS_WAIT_PROCESS                1043
#define IDC_STAT_ENCODED_KB             1044
#define IDS_UNLOADING_DLL               1044
#define IDS_LOADING_DLL                 1045
#define IDC_RATE_MODE                   1046
#define IDC_POWEROFF                    1046
#define IDS_SET_FRAME_SIZE              1046
#define IDC_TEMP_FOLDER                 1047
#define IDS_INCOMPATIBLE_INPUT          1047
#define IDC_STEREO_MODE                 1048
#define IDC_TAB_AUDIO                   1048
#define IDS_INVALID_SAMPLE_RATE         1048
#define IDC_OPT_BITRATE                 1049
#define IDC_TAB                         1049
#define IDS_RUNNING                     1049
#define IDC_QUALITY                     1050
#define IDC_OPT_QUALITY                 1050
#define IDC_SETTEMP                     1050
#define IDC_TAB_VIEW                    1050
#define IDS_INVALID_BITRATE             1050
#define IDC_BITRATE                     1051
#define IDC_LC                          1051
#define IDS_CT_INFO                     1051
#define IDC_TB_BITRATE                  1052
#define IDC_OPT_QUALITY3                1052
#define IDC_HE                          1052
#define IDC_MPEG2                       1054
#define IDC_MPEG4                       1055
#define IDC_EXTAUDIO                    1059
#define IDC_EXIT                        1059
#define IDC_ADDTRACK                    1059
#define IDC_NOHEADER                    1060
#define IDC_SPLIT                       1061
#define IDC_FORMAT                      1062
#define IDC_KEEP_STEREO                 1062
#define IDC_SPLIT_LEFT                  1064
#define IDC_SPLIT_RIGHT                 1065
#define IDC_ADD                         1065
#define IDC_SPLIT_LEFT2                 1065
#define IDC_CHECK1                      1066
#define IDC_CROPPING                    1066
#define IDC_USEV1                       1066
#define IDC_STDIN                       1066
#define IDC_VERIFY                      1066
#define IDC_VIDEO                       1066
#define IDC_HYBRID                      1066
#define IDC_DOWNMIX                     1066
#define IDC_CROP_X1                     1067
#define IDC_CROP_X                      1067
#define IDC_RAWPCM                      1067
#define IDC_CROP_X2                     1068
#define IDC_CROP_W                      1068
#define IDC_RAWPCM2                     1068
#define IDC_SHOWCONSOLE                 1068
#define IDC_CROP_X3                     1069
#define IDC_CROP_Y                      1069
#define IDC_EDIT2                       1070
#define IDC_EXTRA_OPTIONS               1070
#define IDC_EXTNAME                     1070
#define IDC_DISCINFO                    1070
#define IDC_CROP_X4                     1071
#define IDC_CROP_H                      1071
#define IDC_COMBO1                      1072
#define IDC_OBJTYPE                     1072
#define IDC_ENCODER                     1072
#define IDC_MODE                        1072
#define IDC_TYPE                        1072
#define IDC_CROP_DETECT                 1073
#define IDC_CDROMS                      1073
#define IDC_THRESHOLD                   1074
#define IDC_ENCODER2                    1074
#define IDC_DECODER                     1074
#define IDC_MODE2                       1074
#define IDC_CODEC                       1074
#define IDC_ROUND                       1075
#define IDC_VARLIST                     1076
#define IDC_RESIZE_W                    1076
#define IDC_EDIT                        1077
#define IDC_RESIZE_W2                   1077
#define IDC_RESIZE_H                    1077
#define IDC_BROWSE                      1078
#define IDC_VALUE                       1079
#define IDC_VALUE_FRAME                 1080
#define IDC_REVERT                      1082
#define IDC_APPLY                       1083
#define IDC_SLIDER1                     1084
#define IDC_SLIDER                      1084
#define IDC_LEVEL                       1084
#define IDC_INFO                        1085
#define IDC_NOOPTION                    1086
#define IDC_TREE1                       1087
#define IDC_TREE                        1087
#define IDC_PROFILE                     1088
#define IDC_MUSIC                       1089
#define IDC_MUSIC2                      1090
#define IDC_VOICE                       1090
#define IDC_EDIT1                       1090
#define IDC_DELAY                       1090
#define IDC_CMD                         1090
#define IDC_URL                         1090
#define IDC_IVTC                        1091
#define IDC_CHAPTER                     1091
#define IDC_URL2                        1091
#define IDC_EDIT3                       1091
#define IDC_DECOPTS                     1092
#define IDC_EDIT4                       1092
#define IDC_DECOPTS2                    1093
#define IDC_ENCOPT                      1093
#define IDC_BEST                        1093
#define IDC_ENCOPTS                     1093
#define IDC_EDIT5                       1093
#define IDC_CORRECTION                  1094
#define IDC_EDIT6                       1094
#define IDC_EDIT7                       1095
#define IDC_LIST2                       1096
#define IDC_FILELIST                    1096
#define IDC_EDIT8                       1096
#define IDC_TRANSCODE                   1097
#define IDC_EDIT9                       1097
#define IDC_VBR                         1098
#define IDC_EDIT10                      1098
#define IDC_CBR                         1099
#define IDC_EDIT11                      1099
#define IDC_PNS                         1100
#define IDC_EDIT12                      1100
#define IDC_CHECK3                      1101
#define IDC_HINT                        1101
#define IDC_LEVEL_TEXT                  1101
#define IDC_EDIT13                      1101
#define IDC_EDIT14                      1102
#define IDC_BUTTON1                     1103
#define IDC_FREEDB                      1104
#define IDC_QUERY                       1104
#define IDC_BAR_UPPER                   1118
#define IDM_EXIT                        40005
#define IDM_ENCODE                      40006
#define IDM_VERSION                     40009
#define IDM_SETOUTPUT                   40010
#define IDM_ADDFILE                     40011
#define IDM_ADDFOLDER                   40012
#define IDM_PLAY                        40014
#define IDM_ENCODEAUDIO                 40016
#define IDM_PLAY_ENCODED                40018
#define ID_PLAYBACK_AUDIO               40020
#define IDM_STOP_ENCODE                 40027
#define IDM_LEFT_CHANNEL                40028
#define IDM_STEREO                      40029
#define IDM_RIGHT_CHANNEL               40030
#define IDM_SHOW_CONSOLE                40032
#define IDM_SWITCH_AUDIO                40034
#define IDM_LEFT25_RIGHT75              40035
#define IDM_LEFT50_RIGHT50              40036
#define IDM_LEFT75_RIGHT25              40037
#define ID_PLAYBACK_CONTROL             40038
#define IDM_INC_VOL                     40044
#define IDM_DEC_VOL                     40045
#define IDM_MUTE                        40046
#define IDM_PAUSE                       40047
#define IDM_FULLSCREEN                  40048
#define ID_Menu                         40049
#define IDM_ONTOP                       40051
#define IDM_PREFERENCE                  40061
#define IDM_SPLASH                      40063
#define IDM_STOP                        40065
#define ID_PLAYBACK_WINAMPDSPPLUGIN     40066
#define ID_Menu40068                    40068
#define IDM_WA_CONFIG                   40069
#define IDM_ADDTRACK                    40071
#define IDM_LOAD_PRESET                 40074
#define IDM_SAVE_PRESET                 40075
#define IDM_REVERT_ALL                  40082
#define ID_Menu40084                    40084
#define IDM_CONSOLE                     40085
#define IDM_TOGGLE_STATS                40089
#define IDM_CHECKFORUPDATE              40092
#define IDM_LOADQUEUE                   40094
#define IDM_SAVEQUEUE                   40095
#define IDM_FILE_DETAIL                 40096
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         40097
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
