

//[[define image infomation

/////////////////////////////////////////////////////////////////////////////////
//主菜单图标资源
/////////////////////////////////////////////////////////////////////////////////

//冒泡网游
RES_ADD_IMG(IMG_MRAPP_MAINMENU_NETGAME,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_NETGAME.png",IMG_CMP_PNG_ARGB,0)

//冒泡游戏
RES_ADD_IMG(IMG_MRAPP_MAINMENU_MAOPAO,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_MAOPAO.png",IMG_CMP_PNG_ARGB,0)

//冒泡书城
RES_ADD_IMG(IMG_MRAPP_MAINMENU_SKYREAD,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_MAOPAO_BOOK.png",IMG_CMP_PNG_ARGB,0)

//网络时钟
RES_ADD_IMG(IMG_MRAPP_MAINMENU_CLOCK,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_CLOCK.png",IMG_CMP_PNG_ARGB,0)

//开心网
RES_ADD_IMG(IMG_MRAPP_MAINMENU_KAIXIN,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_KAIXIN.png",IMG_CMP_PNG_ARGB,0)

//QQ
RES_ADD_IMG(IMG_MRAPP_MAINMENU_QQ,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_QQ.png",IMG_CMP_PNG_ARGB,0)

//MSN
RES_ADD_IMG(IMG_MRAPP_MAINMENU_MSN,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_MSN.png",IMG_CMP_PNG_ARGB,0)

//MRP Store
RES_ADD_IMG(IMG_MRAPP_MRPSTORE,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_MRPSTORE.png",IMG_CMP_PNG_ARGB,0)

//SKYBUDDY
RES_ADD_IMG(IMG_MRAPP_SKYBUDDY,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_SKYBUDDY.png",IMG_CMP_PNG_ARGB,0)

//Fetion
RES_ADD_IMG(IMG_MRAPP_MAINMENU_FETION,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_FETION.png",IMG_CMP_PNG_ARGB,0)

//新浪微博
RES_ADD_IMG(IMG_MRAPP_MAINMENU_SINA,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_SINA.png",IMG_CMP_PNG_ARGB,0)


/////////////////////////////////////////////////////////////////////////////////
//后台运行图标资源
/////////////////////////////////////////////////////////////////////////////////

//曲奇后台运行
RES_ADD_IMG(IMG_MRAPP_ONLINE,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_ONLINE.png",IMG_CMP_PNG_ARGB,0)

RES_ADD_IMG(IMG_MRAPP_OFFLINE,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_OFFLINE.png",IMG_CMP_PNG_ARGB,0)

RES_ADD_IMG(IMG_MRAPP_HIDE,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_HIDE.png",IMG_CMP_PNG_ARGB,0)

RES_ADD_IMG(IMG_MRAPP_AWAY,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_AWAY.png",IMG_CMP_PNG_ARGB,0)

//QQ后台运行
RES_ADD_IMG(IMG_MRAPP_QQONLINE,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_QQ_ONLINE.png",IMG_CMP_PNG_ARGB,0)

RES_ADD_IMG(IMG_MRAPP_QQOFFLINE,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_QQ_OFFLINE.png",IMG_CMP_PNG_ARGB,0)

RES_ADD_IMG(IMG_MRAPP_QQHIDE,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_QQ_HIDE.png",IMG_CMP_PNG_ARGB,0)

RES_ADD_IMG(IMG_MRAPP_QQAWAY,"\\MMI_RES_##\\IMAG\\IMAGE_MRAPP_QQ_AWAY.png",IMG_CMP_PNG_ARGB,0)

//按钮资源图标
RES_ADD_IMG(IMAGE_ISTYLE_TITLE_OK,"\\MMI_RES_##\\IMAG\\Title\\IMAGE_ISTYLE_TITLE_OK.png",IMG_CMP_PNG_SABM_RLE | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_ISTYLE_TITLE_OK_DOWN,"\\MMI_RES_##\\IMAG\\Title\\IMAGE_ISTYLE_TITLE_OK_DOWN.png",IMG_CMP_PNG_SABM_RLE | SABM_CEN_STRETCH,0)
//]]define image infomation

//[[define anim infomation
//RES_ADD_ANIM(IMAGE_SMS_SENDING_ANIM,"\\MMI_RES_##\\ANIM\\IMAGE_SMS_SENDING_ANIM",AT_COMPRESS_STREAM,75,0x000000)
//]]define anim infomation


//[[define string infomation
RES_ADD_STRING(TXT_MRAPP_NETGAME,"冒泡网游")
RES_ADD_STRING(TXT_MRAPP_QIPAI,"冒泡棋牌")
RES_ADD_STRING(TXT_MRAPP_DDZ,"斗地主")
RES_ADD_STRING(TXT_MRAPP_GAMEC,"冒泡娱乐中心")
RES_ADD_STRING(TXT_MRAPP_BOOKS,"冒泡书城")
RES_ADD_STRING(TXT_MRAPP_FARM,"冒泡农场")
RES_ADD_STRING(TXT_MRAPP_KAIXIN,"开心网")
RES_ADD_STRING(TXT_MRAPP_CLOCK,"网络时钟")
RES_ADD_STRING(TXT_MRAPP_TOOL,"实用工具")
RES_ADD_STRING(TXT_MRAPP_CHDICT,"新华字典")
RES_ADD_STRING(TXT_MRAPP_ENDICT,"英汉字典")
RES_ADD_STRING(TXT_MRAPP_TIANQI,"天气助手")
RES_ADD_STRING(TXT_MRAPP_NESGAME,"NES游戏")
RES_ADD_STRING(TXT_MRAPP_QQ,"QQ")
RES_ADD_STRING(TXT_MRAPP_MSN,"MSN")
RES_ADD_STRING(TXT_MRAPP_FETION,"飞信")
RES_ADD_STRING(TXT_MRAPP_XLWB,"新浪微博")
RES_ADD_STRING(TXT_MRAPP_CAT,"给力猫")
RES_ADD_STRING(TXT_MRAPP_MRPSTORE,"MRP Store")
RES_ADD_STRING(TXT_MRAPP_SKYBUDDY,"SkyBuddy")
RES_ADD_STRING(TXT_MRAPP_FBOOK,"Facebook")
RES_ADD_STRING(TXT_MRAPP_SKYPE,"Skype")
RES_ADD_STRING(TXT_MRAPP_YAHOO,"Yahoo Message")
RES_ADD_STRING(TXT_MRAPP_TWITTER,"Twitter")

//]]define string infomation

//[[define data infomation
//RES_ADD_DATA(R_ACC_MPLOC1,"\\MMI_RES_##\\DATA\\R_ACC_MPLOC1")
//]]define data infomation
