
#ifdef EBOOK_SUPPORT
//[[define image infomation
RES_ADD_IMG(IMAGE_EBOOK_BOOKMARK_LIST,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_BOOKMARK_LIST.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMIEBOOK_BOOKSHELF_SUPPORT
RES_ADD_IMG(IMAGE_EBOOK_BOOK1,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_BOOK1.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifndef MMI_LOW_MEMORY_EBOOK
RES_ADD_IMG(IMAGE_EBOOK_BOOK2,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_BOOK2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_BOOK3,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_BOOK3.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_EBOOK_LOCAL,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_LOCAL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_BOOKCASE_BG,   "\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_BOOKCASE_BG.jpg",     IMG_CMP_JPG_SCI,0)
RES_ADD_IMG(IMAGE_EBOOK_BOOKCASE_BORAD, "\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_BOOKCASE_BOARD.png", IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef MMIEBOOK_OSDMENU_SUPPORT
RES_ADD_IMG(IMAGE_EBOOK_OSD_UP,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_OSD_UP.png",IMG_CMP_PNG_SABM_RLE | SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_EBOOK_OSD_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_OSD_DOWN.png",IMG_CMP_PNG_SABM_RLE | SABM_HOR_STRETCH,0)
//RES_ADD_IMG(IMAGE_EBOOK_FONT_SIZE,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_FONT_SIZE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_EBOOK_BG,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_FONT_COLOR,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_FONT_COLOR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_MORE,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MORE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifndef MMI_LOW_MEMORY_EBOOK
RES_ADD_IMG(IMAGE_EBOOK_COLOR_BG1,   "\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_BG1.bmp",     IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_COLOR_BG2,   "\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_BG2.bmp",     IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_COLOR_BG3,   "\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_BG3.bmp",     IMG_CMP_BMP_16_565_RLE,0)
#endif
    
RES_ADD_IMG(IMAGE_EBOOK_COLOR_BGICON1,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_BGICON1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_COLOR_BGICON2,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_BGICON2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_COLOR_BGICON3,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_BGICON3.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifndef MMI_LOW_MEMORY_EBOOK
RES_ADD_IMG(IMAGE_EBOOK_COLOR_BGICON4,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_BGICON4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_COLOR_BGICON5,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_BGICON5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_COLOR_BGICON6,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_BGICON6.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_EBOOK_COLOR_SELECT,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_COLOR_SELECT.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef MMI_PDA_SUPPORT
#ifdef MMIEBOOK_BOOKSHELF_SUPPORT
RES_ADD_IMG(IMAGE_ISTYLE_EBOOK_TITLE_RETURN,"\\MMI_RES_##\\IMAG\\IMAGE_ISTYLE_EBOOK_TITLE_RETURN.png",IMG_CMP_PNG_SABM_RLE | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_ISTYLE_EBOOK_TITLE_RETURN_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_ISTYLE_EBOOK_TITLE_RETURN_DOWN.png",IMG_CMP_PNG_SABM_RLE | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_ISTYLE_EBOOK_TITLE_MENU,"\\MMI_RES_##\\IMAG\\IMAGE_ISTYLE_EBOOK_TITLE_MENU.png",IMG_CMP_PNG_SABM_RLE | SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_ISTYLE_EBOOK_TITLE_MENU_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_ISTYLE_EBOOK_TITLE_MENU_DOWN.png",IMG_CMP_PNG_SABM_RLE | SABM_HOR_STRETCH,0)
#endif

RES_ADD_IMG(IMAGE_EBOOK_MENU_ICON_ADD_BOOKMARK,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MENU_ICON_ADD_BOOKMARK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_MENU_ICON_VIEW_BOOKMARK,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MENU_ICON_VIEW_BOOKMARK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_MENU_ICON_AUTO_BROWSE,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MENU_ICON_AUTO_BROWSE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_MENU_ICON_BACKLIGHT_ALYWAS_ON_ACITEVED,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MENU_ICON_BACKLIGHT_ALYWAS_ON_ACITEVED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_MENU_ICON_BACKLIGHT_ALYWAS_ON_DEACITEVED,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MENU_ICON_BACKLIGHT_ALYWAS_ON_DEACITEVED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_MENU_ICON_JUMP_TO_PERCENT,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MENU_ICON_JUMP_TO_PERCENT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_MENU_ICON_READ_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MENU_ICON_READ_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_MENU_ICON_READ_ON,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MENU_ICON_READ_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EBOOK_MENU_ICON_DAY_NIGHT_MODE,"\\MMI_RES_##\\IMAG\\IMAGE_EBOOK_MENU_ICON_DAY_NIGHT_MODE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif


//]]define image infomation


//[[define anim infomation
//]]define anim infomation


//[[define string infomation
//#if 0
#if 1
//RES_ADD_STRING(TXT_EBOOK_EBOOK,"Ebook")  //replaced by common ID TXT_COMM_EBOOK
RES_ADD_STRING(TXT_EBOOK_SEE_BOOKMARK,"See bookmark")
//RES_ADD_STRING(TXT_EBOOK_READ,"Read")    //replaced by common ID TXT_READ
//RES_ADD_STRING(TXT_EBOOK_DETAIL,"Detail")    //replaced by common ID STXT_DETAIL
//RES_ADD_STRING(TXT_EBOOK_ADD_BOOKMARK,"Add bookmark")    //replaced by common ID TXT__ADD_BOOKMARK
RES_ADD_STRING(TXT_EBOOK_JUMP_FIRST_PAGE,"Jump first page")
RES_ADD_STRING(TXT_EBOOK_JUMP_LAST_PAGE,"Jump last page")
//RES_ADD_STRING(TXT_EBOOK_JUMP_PAGE,"Jump page")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_BOOKMARK,"Mark:")     //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_PAGE,"Page:")        //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_TXT_EMPTY,"Ebook empty")
//RES_ADD_STRING(TXT_EBOOK_BOOKMARK_FULL,"Bookmark full")  //replaced by common ID TXT_COMON_BOOKMARK_FULL
//RES_ADD_STRING(TXT_EBOOK_INPUT_PAGE_NUM,"page")    //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_BOOKMARK_EMPTY,"Bookmark empty")
//RES_ADD_STRING(TXT_EBOOK_OPTION,"Opt")    //replaced by common ID STXT_OPTION
//RES_ADD_STRING(TXT_EBOOK_BOOKMARK_OPT,"Bookmark")  //replaced by common ID TXT_COMMON_BOOKMARKS
//RES_ADD_STRING(TXT_EBOOK_BUSY,"Ebook busy")    //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_MEM_NO_SPACE,"Save Info need 400K memory space")
//RES_ADD_STRING(TXT_EBOOK_RENAME,"Rename")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_NAMEREPEATED,"Name repeated")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_NAMEINVALID,"Name invalid")     //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_BACKLIGHT_TURN_OFF,"Turn off backlight always on(*)")
RES_ADD_STRING(TXT_EBOOK_BACKLIGHT_TURN_ON,"Turn on backlight always on(*)")
RES_ADD_STRING(TXT_EBOOK_HAVE_BACKLIGHT_TURN_ON,"Have turn on backlight always on")
RES_ADD_STRING(TXT_EBOOK_HAVE_BACKLIGHT_TURN_OFF,"Have turn off backlight always on")
//RES_ADD_STRING(TXT_EBOOK_TTS_READ_START,"Read")     //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_TTS_READ_STOP,"Stop")      //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_FILE_SIZE_ABOVE_5M,"Ebook file size greater than 500MB")
//RES_ADD_STRING(TXT_EBOOK_FILE_SIZE_ZERO,"Ebook file size is zero")    //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_INFO_SAVE_FAIL,"Failed to add bookmark,please check the storage space or directory is full!")
RES_ADD_STRING(TXT_EBOOK_FILE_INFO_NOT_SAVED,"The current reading positon is not saved,please check the storage space or directory is full!")
//RES_ADD_STRING(TXT_EBOOK_FILE_READ_WRITE_ERROR,"File reading or writing error!")      //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_OPENING_WAITING,"Ebook opening ...")
//RES_ADD_STRING(TXT_EBOOK_OPEN_FROM_EBOOK,"pls open form ebook directory")     //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_FILESIZE_TOOBIG,"Too big,can only open part")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_BROWSEPAGE_METHED,"Browse page methed")   //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_FULL_PAGE,"Full page")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_RESERVE_LASTLINE,"Reserve last line")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_COLOR,"color")    //replaced by common ID TXT_COLOR
//RES_ADD_STRING(TXT_EBOOK_FONT_COLOR,"font color")  //replaced by common ID TXT_COMMON_FONT_COLOR
RES_ADD_STRING(TXT_EBOOK_BACK_COLOR,"back color")
//RES_ADD_STRING(TXT_EBOOK_PREVIEW,"preview")    //replaced by common ID STXT_PREVIEW 
//RES_ADD_STRING(TXT_EBOOK_FREE_COMMUNICATE,"Free communicate")  //replaced by common ID TXT_FREEDOM_COMMUNICATION
//RES_ADD_STRING(TXT_EBOOK_ADD,"Add ebook")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_UPDATE_LIST,"Update list")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_MARK,"Mark")  //replaced by common ID STXT_MARK
//RES_ADD_STRING(TXT_EBOOK_EMPTY_LIST,"<Empty list>")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_NO_SPACE_FOR_LIST,"No space for add ")   //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_FILE_NOT_EXIST,"Ebook file is not exist")
//RES_ADD_STRING(TXT_EBOOK_MARKALL,"Mark all")  //replaced by common ID TXT_MARK_ALL
//RES_ADD_STRING(TXT_EBOOK_CANCEL_MARK,"Cancel mark")       //replaced by common ID TXT_CANCEL_MARK
//RES_ADD_STRING(TXT_EBOOK_CANCEL_ALLMARK,"Cancel all mark")   //replaced by common ID TXT_CANCEL_MARK_ALL
//RES_ADD_STRING(TXT_EBOOK_DETAIL_DATE,"Date:")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_DETAIL_TIME,"Time:")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_CLEAR,"Clear")      //replaced by common ID TXT_COMMON_CLEAR
RES_ADD_STRING(TXT_EBOOK_LATEST_BOOKS,"Latest Books")
//RES_ADD_STRING(TXT_EBOOK_OPEN_FAILED,"Ebook open failed")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_CODING_TYPE,"Coding type")  //replaced by common ID TXT_CODING_TYPE
//RES_ADD_STRING(TXT_EBOOK_GB,"GB(Simplified Chinese)")   //replaced by common ID TXT_CODING_TYPE_GB
//RES_ADD_STRING(TXT_EBOOK_BIG5,"Big5(Traditional Chinese)") //replaced by common ID TXT_CODING_TYPE_BIG5
//RES_ADD_STRING(TXT_EBOOK_FONT_SIZE,"Font size")  //replaced by common ID TXT_COMMON_FONT_SIZE
//RES_ADD_STRING(TXT_EBOOK_FONT_BIG,"Big")  //replaced by common ID TXT_COMM_FONT_BIG
//RES_ADD_STRING(TXT_EBOOK_FONT_NORMAL,"Medium")  //replaced by common ID TXT_COMMON_NORMAL
//RES_ADD_STRING(TXT_EBOOK_FONT_SMALL,"Small")    //replaced by common ID TXT_FONT_SMALL
RES_ADD_STRING(TXT_EBOOK_JUMP_TO_BEGIN,"Jump to begin")
RES_ADD_STRING(TXT_EBOOK_JUMP_TO_END,"Jump to end")
RES_ADD_STRING(TXT_EBOOK_JUMP_TO_PERCENT,"Jump to percent")
//RES_ADD_STRING(TXT_EBOOK_MORE,"More")      //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_FILE_NOT_SUPPORT,"File not support,open failed")
//RES_ADD_STRING(TXT_EBOOK_MMS_SEND,"MMS send")  //replaced by common ID TXT_COMM_MMS_SEND
RES_ADD_STRING(TXT_EBOOK_FULL_SCREEN_OFF,"Close full screen(#)")
RES_ADD_STRING(TXT_EBOOK_FULL_SCREEN_ON,"Open full screen(#)")
//RES_ADD_STRING(TXT_EBOOK_HAVE_FULL_SCREEN_OFF,"OFF ")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_EBOOK_HAVE_FULL_SCREEN_ON,"ON")    //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_AUTO_READ,"Auto read")
RES_ADD_STRING(TXT_EBOOK_TURN_PAGE_5S,"5S/page")
RES_ADD_STRING(TXT_EBOOK_TURN_PAGE_15S,"15S/page")
RES_ADD_STRING(TXT_EBOOK_TURN_PAGE_30S,"30S/page")
RES_ADD_STRING(TXT_EBOOK_TURN_PAGE_60S,"60S/page")
//RES_ADD_STRING(TXT_EBOOK_FILE_PARSING_WAITING,"File parsing,please wait!")        //case3£ºdefined but not used
RES_ADD_STRING(TXT_EBOOK_LOCAL_FILE,"Local file")
RES_ADD_STRING(TXT_EBOOK_OPEN_TTS,"Open voice Read")
RES_ADD_STRING(TXT_EBOOK_STOP_TTS,"Stop voice Read")
RES_ADD_STRING(TXT_EBOOK_PDA_BACKLIGHT_TURN_OFF,"Turn off backlight always on")
RES_ADD_STRING(TXT_EBOOK_PDA_BACKLIGHT_TURN_ON,"Turn on backlight always on")
//RES_ADD_STRING(TXT_EBOOK_ADVANCE_OPT, "Advanced")      //replaced by common ID TXT_COMMON_HIGHQUALITY  
RES_ADD_STRING(TXT_EBOOK_DAY_NIGHT_MODE, "Day/Night mode")
RES_ADD_STRING(TXT_EBOOK_DAY_MODE, "Day mode")
RES_ADD_STRING(TXT_EBOOK_NIGHT_MODE, "Night mode")
RES_ADD_STRING(TXT_EBOOK_JUMP_TO_PERCENT_WARNING, "Please input 0-100")
#endif
#endif
//]]define string infomation


//[[define data infomation
//]]define data infomation
