//[[define image infomation
#ifdef MMI_MEMO_SUPPORT
#ifndef MMI_MEMO_MINI_SUPPORT  //#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_MEMO_MAIN_BG,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_MAIN_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_MEMO_MAIN_TITLE_BG,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_MAIN_TITLE_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
//RES_ADD_IMG(IMAGE_MEMO_MAIN_TITLE_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_MAIN_TITLE_BUTTON.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_MEMO_MAIN_ARROW,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_MAIN_ARROW.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_MEMO_PREV,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_PREV.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MEMO_PREV_GRAY,"\\MMI_RES_##\\IMAG\\\IMAGE_MEMO_PREV_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MEMO_PREV_FOCUS,"\\MMI_RES_##\\IMAG\\\IMAGE_MEMO_PREV_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_MEMO_NEXT,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_NEXT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MEMO_NEXT_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_NEXT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MEMO_NEXT_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_NEXT_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)

//RES_ADD_IMG(IMAGE_MEMO_MSG,"\\MMI_RES_##\\IMAG\\\IMAGE_MEMO_MSG.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MEMO_MSG_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_MSG_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MEMO_MSG_FOCUS,"\\MMI_RES_##\\IMAG\\\IMAGE_MEMO_MSG_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_MEMO_DEL,"\\MMI_RES_##\\IMAG\\\IMAGE_MEMO_DEL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MEMO_DEL_GRAY,"\\MMI_RES_##\\IMAG\\\IMAGE_MEMO_DEL_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MEMO_DEL_FOCUS,"\\MMI_RES_##\\IMAG\\\IMAGE_MEMO_DEL_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_MEMO_TITLE_ADD_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_TITLE_ADD_BUTTON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MEMO_TITLE_ADD_BUTTON_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_TITLE_ADD_BUTTON_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_MEMO_TITLE_LEFT_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_TITLE_LEFT_BUTTON.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_MEMO_TITLE_LEFT_BUTTON_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_TITLE_LEFT_BUTTON_FOCUS.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_MEMO_TITLE_RIGHT_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_TITLE_RIGHT_BUTTON.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_MEMO_TITLE_RIGHT_BUTTON_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MEMO_TITLE_RIGHT_BUTTON_FOCUS.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
#endif
//]]define image infomation

//[[define anim infomation

//]]define anim infomation




//[[define string infomation
//RES_ADD_STRING(TXT_NOTEPAD_NEW,"New")    //replaced by common ID TXT_NEW
//]]define string infomation





//[[define data infomation

//]]define data infomation
#endif

