/******************************************************************************
 ** File Name:      sim_msgtable.h                                            *
 ** Author:         Raislin.Kong                                              *
 ** Date:           11/27/2001                                                *
 ** Copyright:      Copyright 2001-2010 by Spreadtrum Communications,Inc.     *
 **                 All Rights Reserved.                                      *
 **                 This software is supplied under the terms of a license    *
 **                 agreement or non-disclosure agreement with Spreadtrum.    *
 **                 Passing on and copying of this document,and communication *
 **                 of its contents is not permitted without prior written    *
 **                 authorization.                                            *
 ** Description:                                                     		  *
 ******************************************************************************

 ******************************************************************************
 **                        Edit History                                       *
 ** --------------------------------------------------------------------------*
 ** Date           Name             Description                               *
 **---------------------------------------------------------------------------*
 ** 11/27/2001     Raislin.Kong      create                                   *
 ******************************************************************************/

{SIM_START_UP_REQ                        , TEXT("SIM_START_UP_REQ")}, 
{SIM_READ_T_FILE_REQ                     , TEXT("SIM_READ_T_FILE_REQ")}, 
{SIM_READ_R_FILE_REQ                     , TEXT("SIM_READ_R_FILE_REQ")}, 
{SIM_UPDATE_T_FILE_REQ                   , TEXT("SIM_UPDATE_T_FILE_REQ")}, 
{SIM_UPDATE_R_FILE_REQ                   , TEXT("SIM_UPDATE_R_FILE_REQ")}, 
{SIM_UPDATE_LANGUAGE_REQ                 , TEXT("SIM_UPDATE_LANGUAGE_REQ")}, 
{SIM_INCREASE_FILE_REQ                   , TEXT("SIM_INCREASE_FILE_REQ")}, 
{SIM_INITIALIZE_REQ                      , TEXT("SIM_INITIALIZE_REQ")}, 
{SIM_UPDATE_CCP_REQ                      , TEXT("SIM_UPDATE_CCP_REQ")}, 
{SIM_READ_CCP_REQ                        , TEXT("SIM_READ_CCP_REQ")}, 
{SIM_ERASE_CCP_REQ                     , TEXT("SIM_ERASE_CCP_REQ")}, 
{SIM_GET_FREE_EXT_INFO_REQ               , TEXT("SIM_GET_FREE_EXT_INFO_REQ")}, 
{SIM_UPDATE_DN_REQ                       , TEXT("SIM_UPDATE_DN_REQ")}, 
{SIM_READ_DN_REQ                         , TEXT("SIM_READ_DN_REQ")}, 
{SIM_ERASE_DN_REQ                      , TEXT("SIM_ERASE_DN_REQ")}, 
{SIM_ERASE_LND_ALL_REQ               , TEXT("SIM_ERASE_LND_ALL_REQ")}, 
{SIM_PURGE_DN_REQ                        , TEXT("SIM_PURGE_DN_REQ")}, 
{SIM_FDN_SERVICE_REQ                     , TEXT("SIM_FDN_SERVICE_REQ")}, 
{SIM_BDN_SERVICE_REQ                     , TEXT("SIM_BDN_SERVICE_REQ")}, 
{SIM_SESSION_TERMINATION_REQ             , TEXT("SIM_SESSION_TERMINATION_REQ")}, 
{SIM_CHV_REQ                             , TEXT("SIM_CHV_REQ")}, 
{SIM_GSM_ALGORITHMS_REQ                  , TEXT("SIM_GSM_ALGORITHMS_REQ")}, 
{SIM_RESPONSE_IND                        , TEXT("SIM_RESPONSE_IND")}, 
{SIM_INT_IND                             , TEXT("SIM_INT_IND")}, 
{SIM_CARD_INSERTED_IND                   , TEXT("SIM_CARD_INSERTED_IND")}, 
{SIM_GET_RECORD_EF_INFO_REQ              , TEXT("SIM_GET_RECORD_EF_INFO_REQ")}, 
{SIM_SMS_GET_SMS_NUM_REQ                 , TEXT("SIM_SMS_GET_SMS_NUM_REQ")}, 
{SIM_SMS_READ_PARAM_REQ                  , TEXT("SIM_SMS_READ_PARAM_REQ")}, 
{SIM_SMS_READ_SMS_REQ                    , TEXT("SIM_SMS_READ_SMS_REQ")}, 
{SIM_SMS_WRITE_SMS_REQ                   , TEXT("SIM_SMS_WRITE_SMS_REQ")}, 
{SIM_SMS_REPLACE_SMS_REQ                 , TEXT("SIM_SMS_REPLACE_SMS_REQ")}, 
{SIM_SMS_EDIT_SMS_REQ                    , TEXT("SIM_SMS_EDIT_SMS_REQ")}, 
{SIM_SMS_UPDATE_SMS_STATUS_REQ           , TEXT("SIM_SMS_UPDATE_SMS_STATUS_REQ")}, 
{SIM_SMS_READ_STATUS_REPORT_REQ          , TEXT("SIM_SMS_READ_STATUS_REPORT_REQ")}, 
{SIM_SMS_WRITE_STATUS_REPORT_REQ         , TEXT("SIM_SMS_WRITE_STATUS_REPORT_REQ")}, 
{SIM_SMS_READ_SMSS_REQ                   , TEXT("SIM_SMS_READ_SMSS_REQ")}, 
{SIM_SMS_WRITE_SMSS_REQ                  , TEXT("SIM_SMS_WRITE_SMSS_REQ")}, 
{SIM_SMS_WRITE_PARAM_REQ                 , TEXT("SIM_SMS_WRITE_PARAM_REQ")}, 
{SIM_GET_SPN_REQ                         , TEXT("SIM_GET_SPN_REQ")}, 
{SIM_READ_ECC_REQ                        , TEXT("SIM_READ_ECC_REQ")}, 
{SIM_READ_LP_REQ                         , TEXT("SIM_READ_LP_REQ")}, 
{SIM_UPDATE_LP_REQ                       , TEXT("SIM_UPDATE_LP_REQ")}, 
{SIM_READ_AD_REQ                         , TEXT("SIM_READ_AD_REQ")}, 
{SIM_READ_SST_REQ                        , TEXT("SIM_READ_SST_REQ")}, 
{SIM_READ_PHASE_REQ                      , TEXT("SIM_READ_PHASE_REQ")}, 
{SIM_READ_ELP_REQ                        , TEXT("SIM_READ_ELP_REQ")}, 
{SIM_UPDATE_ELP_REQ                      , TEXT("SIM_UPDATE_ELP_REQ")}, 
{SIM_READ_IMSI_REQ                       , TEXT("SIM_READ_IMSI_REQ")}, 
{SIM_READ_ACC_REQ                        , TEXT("SIM_READ_ACC_REQ")}, 
{SIM_READ_HPLMN_REQ                      , TEXT("SIM_READ_HPLMN_REQ")}, 
{SIM_READ_LOCI_REQ                       , TEXT("SIM_READ_LOCI_REQ")}, 
{SIM_UPDATE_LOCI_REQ                     , TEXT("SIM_UPDATE_LOCI_REQ")}, 
{SIM_READ_KC_REQ                         , TEXT("SIM_READ_KC_REQ")}, 
{SIM_UPDATE_KC_REQ                       , TEXT("SIM_UPDATE_KC_REQ")}, 
{SIM_READ_BCCH_REQ                       , TEXT("SIM_READ_BCCH_REQ")}, 
{SIM_UPDATE_BCCH_REQ                     , TEXT("SIM_UPDATE_BCCH_REQ")}, 
{SIM_READ_FPLMN_REQ                      , TEXT("SIM_READ_FPLMN_REQ")}, 
{SIM_UPDATE_FPLMN_REQ                    , TEXT("SIM_UPDATE_FPLMN_REQ")}, 
{SIM_READ_PLMNSEL_REQ                    , TEXT("SIM_READ_PLMNSEL_REQ")}, 
{SIM_UPDATE_PLMNSEL_REQ                  , TEXT("SIM_UPDATE_PLMNSEL_REQ")}, 
{SIM_READ_CBMI_REQ                       , TEXT("SIM_READ_CBMI_REQ")}, 
{SIM_UPDATE_CBMI_REQ                     , TEXT("SIM_UPDATE_CBMI_REQ")}, 
{SIM_READ_GID1_REQ                       , TEXT("SIM_READ_GID1_REQ")}, 
{SIM_READ_GID2_REQ                       , TEXT("SIM_READ_GID2_REQ")}, 
{SIM_READ_VGCS_REQ                       , TEXT("SIM_READ_VGCS_REQ")}, 
{SIM_READ_VGCSS_REQ                      , TEXT("SIM_READ_VGCSS_REQ")}, 
{SIM_READ_VBS_REQ                        , TEXT("SIM_READ_VBS_REQ")}, 
{SIM_READ_VBSS_REQ                       , TEXT("SIM_READ_VBSS_REQ")}, 
{SIM_READ_EMLPP_REQ                      , TEXT("SIM_READ_EMLPP_REQ")}, 
{SIM_READ_AAEM_REQ                       , TEXT("SIM_READ_AAEM_REQ")}, 
{SIM_UPDATE_AAEM_REQ                     , TEXT("SIM_UPDATE_AAEM_REQ")}, 
{SIM_READ_CBMIR_REQ                      , TEXT("SIM_READ_CBMIR_REQ")}, 
{SIM_UPDATE_CBMIR_REQ                    , TEXT("SIM_UPDATE_CBMIR_REQ")}, 
{SIM_READ_DCK_REQ                        , TEXT("SIM_READ_DCK_REQ")}, 
{SIM_READ_NIA_REQ                        , TEXT("SIM_READ_NIA_REQ")}, 
{SIM_AOC_READ_ACM_REQ                    , TEXT("SIM_AOC_READ_ACM_REQ")}, 
{SIM_AOC_INIT_ACM_REQ                    , TEXT("SIM_AOC_INIT_ACM_REQ")}, 
{SIM_AOC_INCREASE_ACM_REQ                , TEXT("SIM_AOC_INCREASE_ACM_REQ")}, 
{SIM_AOC_READ_ACMMAX_REQ                 , TEXT("SIM_AOC_READ_ACMMAX_REQ")}, 
{SIM_AOC_UPDATE_ACMMAX_REQ               , TEXT("SIM_AOC_UPDATE_ACMMAX_REQ")}, 
{SIM_AOC_READ_PUCT_REQ                   , TEXT("SIM_AOC_READ_PUCT_REQ")}, 
{SIM_AOC_UPDATE_PUCT_REQ                 , TEXT("SIM_AOC_UPDATE_PUCT_REQ")}, 
{SIM_CLOCK_STOP_IND                      , TEXT("SIM_CLOCK_STOP_IND")}, 
{SIM_QUERY_CARD_STATUS_REQ               , TEXT("SIM_QUERY_CARD_STATUS_REQ")}, 
{SIM_GET_FILE_INFO_REQ                   , TEXT("SIM_GET_FILE_INFO_REQ")}, 
{SIM_PC_EXIST_IND                        , TEXT("SIM_PC_EXIST_IND")}, 
{SIM_DPHOEN_REFRESH_TIMEOUT_IND          , TEXT("SIM_DPHOEN_REFRESH_TIMEOUT_IND")}, 
{SIM_GET_ACCESS_INFO_REQ                 , TEXT("SIM_GET_ACCESS_INFO_REQ")}, 
{SIM_POWER_OFF_REQ                       , TEXT("SIM_POWER_OFF_REQ")}, 
{SIM_DPHONE_REFRESH_REQ                  , TEXT("SIM_DPHONE_REFRESH_REQ")}, 
{SIM_PRESENT_CHECK_IND                   , TEXT("SIM_PRESENT_CHECK_IND")}, 
{SIM_SET_ARM_CLK_REQ                     , TEXT("SIM_SET_ARM_CLK_REQ")}, 
{SIM_INIT_ENCRYPT_REQ                    , TEXT("SIM_INIT_ENCRYPT_REQ")}, 
{SIM_SWITCH_CHECK_CARD_PRES_REQ          , TEXT("SIM_SWITCH_CHECK_CARD_PRES_REQ")}, 
{SIMATDUM_ACTIVE_REQ                     , TEXT("SIMATDUM_ACTIVE_REQ")}, 
{SIMAT_TERMINAL_PROFILE_REQ              , TEXT("SIMAT_TERMINAL_PROFILE_REQ")},
{SIMAT_ENVELOPE_REQ                      , TEXT("SIMAT_ENVELOPE_REQ")},
{SIMAT_TERMINAL_RESPONSE_REQ             , TEXT("SIMAT_TERMINAL_RESPONSE_REQ")},
{SIM_SIG_CRSM_REQ                        , TEXT("SIM_SIG_CRSM_REQ")},
