
RES_ADD_STRING(TXT_VIDEO_CALL_ACTIVE,"Video calling")
RES_ADD_STRING(TXT_VIDEO_CALL_INCOM,"Video call")
RES_ADD_STRING(TXT_VIDEO_CALL,"Video call")
RES_ADD_STRING(TXT_VIDEO_CALL_DURATIONS,"Video call durations")
RES_ADD_STRING(TXT_VIDEO_CALL_CONTACT_EMPTY,"No contact")
RES_ADD_STRING(TXT_PLS_CALL_WAIT,"Please wait")
RES_ADD_STRING(TXT_VIDEO_CALL_CONTACT_TITLE,"Video Contact List")
RES_ADD_STRING(TXT_VIDEO_CALL_CONNECT_TIMEOUT,"Connect timeout")
RES_ADD_STRING(TXT_VIDEO_CALL_REJECT,"Reject")
RES_ADD_STRING(TXT_VIDEO_CALL_REMOTE_HANGUP,"Hangup")
RES_ADD_STRING(TXT_VIDEO_CALL_ACCEPT_TIMEOUT,"Accept timeout")


