#ifdef MET_MEX_SUPPORT

//[[define image infomation
RES_ADD_IMG( IMG_MET_MEX, "\\MMI_RES_##\\IMAG\\IMAGE_MEX_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )

#if defined(MET_MEX_TB_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_TB, "\\MMI_RES_##\\IMAG\\TB\\IMAGE_MEX_TB_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif

#if defined(MET_MEX_ZT_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_ZT, "\\MMI_RES_##\\IMAG\\ZT\\IMAGE_MEX_ZT_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif

#if defined(MET_MEX_FRUITNINJA_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_FRUITNINJA, "\\MMI_RES_##\\IMAG\\IMAGE_MEX_FRUIT\\IMAGE_MEX_FRUIT_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif

#if defined(MET_MEX_MSN_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_MSN, "\\MMI_RES_##\\IMAG\\MSN\\IMAGE_MEX_MSN_ICON16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_MSN_AWAY, "\\MMI_RES_##\\IMAG\\MSN\\IMAGE_MEX_AWAY.png", IMG_CMP_PNG_ARGB, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_MSN_IDLE, "\\MMI_RES_##\\IMAG\\MSN\\IMAGE_MEX_IDLE.png", IMG_CMP_PNG_ARGB, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_MSN_ONLINE, "\\MMI_RES_##\\IMAG\\MSN\\IMAGE_MEX_ONLINE.png", IMG_CMP_PNG_ARGB, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_MSN_MSG, "\\MMI_RES_##\\IMAG\\MSN\\IMAGE_MEX_MSG.png", IMG_CMP_PNG_ARGB, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_MSN_BUSY, "\\MMI_RES_##\\IMAG\\MSN\\IMAGE_MEX_BUSY.png", IMG_CMP_PNG_ARGB, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_MSN_OFFLINE, "\\MMI_RES_##\\IMAG\\MSN\\IMAGE_MEX_OFFLINE.png", IMG_CMP_PNG_ARGB, 0 )
#endif

#if defined(MET_MEX_FETION_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_FETION, "\\MMI_RES_##\\IMAG\\FETION\\IMAGE_MEX_FETION_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_FETION_AWAY, "\\MMI_RES_##\\IMAG\\FETION\\IMAGE_MEX_AWAY.gif", IMG_CMP_GIF_SCI, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_FETION_HIDE, "\\MMI_RES_##\\IMAG\\FETION\\IMAGE_MEX_HIDE.gif", IMG_CMP_GIF_SCI, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_FETION_ONLINE, "\\MMI_RES_##\\IMAG\\FETION\\IMAGE_MEX_ONLINE.gif", IMG_CMP_GIF_SCI, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_FETION_MSG, "\\MMI_RES_##\\IMAG\\FETION\\IMAGE_MEX_MSG.gif", IMG_CMP_GIF_SCI, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_FETION_BUSY, "\\MMI_RES_##\\IMAG\\FETION\\IMAGE_MEX_BUSY.gif", IMG_CMP_GIF_SCI, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_FETION_OFFLINE, "\\MMI_RES_##\\IMAG\\FETION\\IMAGE_MEX_OFFLINE.gif", IMG_CMP_GIF_SCI, 0 )
#endif

#if defined(MET_MEX_AB_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_AB, "\\MMI_RES_##\\IMAG\\AB\\IMAGE_MEX_AB_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif
#if defined(MET_MEX_QQ_SUPPORT)||defined(MET_MEX_DOUBLE_QQ_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_ICON_QQ_AWAY, "\\MMI_RES_##\\IMAG\\QQ\\IMAGE_MEX_IDLE_TITLE_ICON_QQ_AWAY.png", IMG_CMP_PNG_ARGB, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_QQ_HIDE, "\\MMI_RES_##\\IMAG\\QQ\\IMAGE_MEX_IDLE_TITLE_ICON_QQ_HIDE.png", IMG_CMP_PNG_ARGB, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_QQ_ONLINE, "\\MMI_RES_##\\IMAG\\QQ\\IMAGE_MEX_IDLE_TITLE_ICON_QQ_ONLINE.png", IMG_CMP_PNG_ARGB, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_QQ_MSG, "\\MMI_RES_##\\IMAG\\QQ\\IMAGE_MEX_IDLE_TITLE_ICON_QQ_MSG.png", IMG_CMP_PNG_ARGB, 0 )
RES_ADD_IMG( IMG_MET_MEX_ICON_QQ_OFFLINE, "\\MMI_RES_##\\IMAG\\QQ\\IMAGE_MEX_IDLE_TITLE_ICON_QQ_OFFLINE.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_AQ_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_AQ, "\\MMI_RES_##\\IMAG\\AQ\\IMAGE_MEX_AQ_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif
#if defined(MET_MEX_WEIBO_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_WEIBO, "\\MMI_RES_##\\IMAG\\WEIBO\\IMAGE_MEX_WEIBO_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif
#if defined(MET_MEX_WEATHER_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_WEATHER, "\\MMI_RES_##\\IMAG\\WEATHER\\IMAGE_MEX_WEATHER_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif
#if defined(MET_MEX_WOMIVIDEO_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_WOMIVIDEO, "\\MMI_RES_##\\IMAG\\WOMIVIDEO\\IMAGE_MEX_WOMIVIDEO_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif

#if defined(MET_MEX_TOMCAT_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_TOMCAT, "\\MMI_RES_##\\IMAG\\TOMCAT\\IMAGE_MEX_TOMCAT_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif
#if defined(MET_MEX_CQZ_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_CQZ, "\\MMI_RES_##\\IMAG\\CQZ\\IMAGE_MEX_CQZ_ICON_16X16.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_JSCB_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_JSCB, "\\MMI_RES_##\\IMAG\\JSCB\\IMAGE_MEX_JSCB_ICON_16X16.bmp", IMG_CMP_BMP_16_565_RLE, 0 )
#endif
//]]define image infomation
#if defined MAIN_MENU_48X48
#ifdef MET_MEX_MERIG_SUPPORT
#ifndef MEX_G7_UI_SUPPORT
RES_ADD_IMG( IMG_MET_MEX_A, "\\MMI_RES_##\\IMAG\\IMAGE_MEX_ICON_48X48.png", IMG_CMP_PNG_ARGB_RLE, 0 )
#endif
#endif
#if defined(MET_MEX_TB_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_TB_A, "\\MMI_RES_##\\IMAG\\TB\\IMAGE_MEX_TB_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_ZT_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_ZT_A, "\\MMI_RES_##\\IMAG\\ZT\\IMAGE_MEX_ZT_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_FRUITNINJA_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_FRUITNINJA_A, "\\MMI_RES_##\\IMAG\\FRUIT\\IMAGE_MEX_FRUIT_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_MSN_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_MSN_A, "\\MMI_RES_##\\IMAG\\MSN\\IMAGE_MEX_MSN_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_FETION_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_FETION_A, "\\MMI_RES_##\\IMAG\\FETION\\IMAGE_MEX_FETION_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_AB_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_AB_A, "\\MMI_RES_##\\IMAG\\AB\\IMAGE_MEX_AB_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_QQ_SUPPORT)||defined(MET_MEX_DOUBLE_QQ_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_ICON_QQ_ONLINE_A, "\\MMI_RES_##\\IMAG\\QQ\\IMAGE_MEX_IDLE_TITLE_ICON_QQ_ONLINE_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_AQ_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_AQ_A, "\\MMI_RES_##\\IMAG\\AQ\\IMAGE_MEX_AQ_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_WEIBO_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_WEIBO_A, "\\MMI_RES_##\\IMAG\\WEIBO\\IMAGE_MEX_WEIBO_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_WEATHER_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_WEATHER_A, "\\MMI_RES_##\\IMAG\\WEATHER\\IMAGE_MEX_WEATHER_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_WOMIVIDEO_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_WOMIVIDEO_A, "\\MMI_RES_##\\IMAG\\WOMIVIDEO\\IMAGE_MEX_WOMIVIDEO_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_TOMCAT_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_TOMCAT_A, "\\MMI_RES_##\\IMAG\\TOMCAT\\IMAGE_MEX_TOMCAT_ICON_48X48.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_CQZ_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_CQZ_A, "\\MMI_RES_##\\IMAG\\CQZ\\IMAGE_MEX_CQZ_ICON_48X48.png", IMG_CMP_PNG_ARGB_RLE, 0 )
#endif
#if defined(MET_MEX_JSCB_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_JSCB_A, "\\MMI_RES_##\\IMAG\\JSCB\\IMAGE_MEX_JSCB_ICON_36X36.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#else
#ifdef MET_MEX_MERIG_SUPPORT
#ifndef MEX_G7_UI_SUPPORT
RES_ADD_IMG( IMG_MET_MEX_A, "\\MMI_RES_##\\IMAG\\IMAGE_MEX_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#endif
#if defined(MET_MEX_TB_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_TB_A, "\\MMI_RES_##\\IMAG\\TB\\IMAGE_MEX_TB_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_ZT_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_ZT_A, "\\MMI_RES_##\\IMAG\\ZT\\IMAGE_MEX_ZT_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_FRUITNINJA_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_FRUITNINJA_A, "\\MMI_RES_##\\IMAG\\FRUIT\\IMAGE_MEX_FRUIT_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_MSN_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_MSN_A, "\\MMI_RES_##\\IMAG\\MSN\\IMAGE_MEX_MSN_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_FETION_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_FETION_A, "\\MMI_RES_##\\IMAG\\FETION\\IMAGE_MEX_FETION_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_AB_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_AB_A, "\\MMI_RES_##\\IMAG\\AB\\IMAGE_MEX_AB_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_QQ_SUPPORT)||defined(MET_MEX_DOUBLE_QQ_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_ICON_QQ_ONLINE_A, "\\MMI_RES_##\\IMAG\\QQ\\IMAGE_MEX_IDLE_TITLE_ICON_QQ_ONLINE_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_AQ_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_AQ_A, "\\MMI_RES_##\\IMAG\\AQ\\IMAGE_MEX_AQ_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_WEIBO_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_WEIBO_A, "\\MMI_RES_##\\IMAG\\WEIBO\\IMAGE_MEX_WEIBO_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_WEATHER_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_WEATHER_A, "\\MMI_RES_##\\IMAG\\WEATHER\\IMAGE_MEX_WEATHER_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_WOMIVIDEO_SUPPORT)
RES_ADD_IMG( IMG_MET_MEX_WOMIVIDEO_A, "\\MMI_RES_##\\IMAG\\WOMIVIDEO\\IMAGE_MEX_WOMIVIDEO_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_TOMCAT_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_TOMCAT_A, "\\MMI_RES_##\\IMAG\\TOMCAT\\IMAGE_MEX_TOMCAT_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_CQZ_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_CQZ_A, "\\MMI_RES_##\\IMAG\\CQZ\\IMAGE_MEX_CQZ_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#if defined(MET_MEX_JSCB_SUPPORT) 
RES_ADD_IMG( IMG_MET_MEX_JSCB_A, "\\MMI_RES_##\\IMAG\\JSCB\\IMAGE_MEX_JSCB_ICON_60X60.png", IMG_CMP_PNG_ARGB, 0 )
#endif
#endif
//[[define anim infomation
//]]define anim infomation


//[[define string infomation
RES_ADD_STRING( TXT_MET_MEX, "Merig3G" )
RES_ADD_STRING( TXT_MET_MEX_PLATFORM_TITLE,"Mex Platform Info")
RES_ADD_STRING( TXT_MET_MEX_OPEN,"Open")
RES_ADD_STRING( TXT_MET_MEX_CLOSE,"Close")
RES_ADD_STRING( TXT_MEX_PLT_ENG_TITLE,"Mex Platform Engineer Mode")
RES_ADD_STRING( TXT_MEX_PLT_ENG_LOG_LABEL,"Log")
RES_ADD_STRING( TXT_MEX_PLT_ENG_VENDER_LABEL,"Vender")
RES_ADD_STRING( TXT_MEX_PLT_ENG_PHONEUA_LABEL,"PhoneUA")
RES_ADD_STRING( TXT_MEX_PLT_ENG_WIDTH_LABEL,"Width")
RES_ADD_STRING( TXT_MEX_PLT_ENG_HEIGHT_LABEL,"Height")
RES_ADD_STRING( TXT_MET_MEX_QUIT_MSG,"You are about to quit Merig 3g, are you sure?")
RES_ADD_STRING( TXT_MET_MEX_SMS_RECEIVE,"SMS Receive")
RES_ADD_STRING( TXT_MET_MEX_MEM_INIT_ERR,"Failed to initialize memory!")
RES_ADD_STRING( TXT_MET_MEX_FLASH_FILE_ERR,"Failed to prepare flash files!")
RES_ADD_STRING( TXT_MET_MEX_TINY_STAT_ERR,"Failed to start TinyManager!")
RES_ADD_STRING( TXT_MET_MEX_NOCARD_OR_NOTSUPPORT,"Memory card not existing or not support!")
RES_ADD_STRING( TXT_MET_MEX_FOLDER_NOT_EXIST,"Folder doesn't exist!")
RES_ADD_STRING( TXT_MET_MEX_CONFLICT,"Conflict with Merig 3g , Abort!")
RES_ADD_STRING( TXT_MET_MEX_PROMPT,"Quit Merig 3g?") 
RES_ADD_STRING( TXT_MET_MEX_QQ_CONFLICT, "Conflict with qq,Abort!")
RES_ADD_STRING( TXT_MET_MEX_MSN_CONFLICT, "Conflict with msn,Abort!")
RES_ADD_STRING( TXT_MET_MEX_FETION_CONFLICT, "Conflict with fetion,Abort!")
RES_ADD_STRING( TXT_MET_MEX_QQ, "QQ")
RES_ADD_STRING( TXT_MET_MEX_TB, "I love MicFeng")
RES_ADD_STRING( TXT_MET_MEX_ZT, "Green ZT")
RES_ADD_STRING( TXT_MET_MEX_MSN, "MSN")
RES_ADD_STRING( TXT_MET_MEX_FETION, "FETION")
RES_ADD_STRING( TXT_MET_MEX_AQ, "Area Inquire")
RES_ADD_STRING( TXT_MET_MEX_AB, "AngryBirds")
RES_ADD_STRING( TXT_MET_MEX_WEIBO, "Sina MicroBlog" )
RES_ADD_STRING( TXT_MET_MEX_WEATHER, "Weather Forecast" )
RES_ADD_STRING( TXT_MET_MEX_WOMIVIDEO, "Video Chat" )
RES_ADD_STRING( TXT_MET_MEX_TOMCAT, "Tom Cat" )
RES_ADD_STRING( TXT_MET_MEX_FAUI_IDLE_SETTING, "Idle Setting" )
RES_ADD_STRING( TXT_MET_MEX_FAUI_REBOOT, "Please reboot phone to make the setting available" )
RES_ADD_STRING( TXT_MET_MEX_FRUITNINJA, "Fruit Ninja" )
RES_ADD_STRING( TXT_MET_MEX_CQZ, "cqz" )
RES_ADD_STRING( TXT_MET_MEX_JSCB, "jscb" )

//]]define string infomation


//[[define data infomation
//]]define data infomation
RES_ADD_STRING( TXT_MEX_APP_NAME, "App Name" )
RES_ADD_STRING( TXT_MEX_APP_NUMBER, "App Number" )
RES_ADD_STRING( TXT_MEX_APP_START_TEST, "Start Test" )
RES_ADD_STRING( TXT_MEX_SECONDMENU_TITLE, "Game")
RES_ADD_STRING( TXT_MEX_SECONDMENU_START, "Start")
RES_ADD_STRING( TXT_MEX_SECONDMENU_MERIG3G, "Merig3G")
RES_ADD_STRING( TXT_MEX_SECONDMENU_ABOUT, "About")
#endif // MET_MEX_SUPPORT

