/******************************************************************************
 ** File Name:      oscfg.c                                                   *
 ** Author:         Benjamin.Wang                                             *
 ** DATE:           11/08/2006                                                *
 ** Copyright:      2006 Spreadtrum, Incorporated. All Rights Reserved.       *
 ** Description:    This file defines most of system's static tasks.          *
 ******************************************************************************

 ******************************************************************************
 **                        Edit History                                       *
 ** ------------------------------------------------------------------------- *
 ** DATE           NAME             DESCRIPTION                               *
 ** 11/08/2006     Benjamin.Wang    Create.                                   *
 ******************************************************************************/

/**---------------------------------------------------------------------------*
 **                         Dependencies                                      *
 **---------------------------------------------------------------------------*/
#include "os_api.h"
#include "priority_base.h"
/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef   __cplusplus
    extern   "C" 
    {
#endif                 


const uint32 kal_priority_map_g[] = /*lint -esym(765,kal_priority_map_g)*/
{
//SCI_BASE_PRI(0),              /* SCI_PRIORITY_KERNEL */
	SCI_BASE_PRI(1),              /* KAL_HEIGHEST_PRIORITY */
	SCI_BASE_PRI(2),              /* KAL_PRIORITY_ONE */
	SCI_BASE_PRI(3),              /* KAL_PRIORITY_TWO */
	SCI_BASE_PRI(4),              /* KAL_PRIORITY_THREE */
	SCI_BASE_PRI(5),              /* KAL_PRIORITY_FOUR == SCI_PRIORITY_TIME_CRITICAL */
	SCI_BASE_PRI(6),              /* KAL_PRIORITY_FIVE */
	SCI_BASE_PRI(7),              /* KAL_PRIORITY_SIX */
	SCI_BASE_PRI(8),              /* KAL_PRIORITY_SEVEN */
	SCI_BASE_PRI(9),              /* KAL_PRIORITY_EIGHT */
	SCI_BASE_PRI(10),             /* KAL_PRIORITY_NINE == SCI_PRIORITY_HIGHEST */
	SCI_BASE_PRI(11),             /* KAL_PRIORITY_TEN */
	                    					/* 15 == SCI_PRIORITY_ABOVE_NORMAL */
	SCI_BASE_PRI(18),             /* KAL_PRIORITY_ELEVEN */
	SCI_BASE_PRI(19),             /* KAL_PRIORITY_TWELVE */
	SCI_BASE_PRI(20),             /* KAL_PRIORITY_THIRTEEN == SCI_PRIORITY_NORMAL */
	SCI_BASE_PRI(21),             /* KAL_PRIORITY_FOURTEEN */
	SCI_BASE_PRI(22),             /* KAL_PRIORITY_FIFTEEN */
	SCI_BASE_PRI(25),             /* KAL_PRIORITY_SIXTEEN == SCI_PRIORITY_BELOW_NORMAL */
	SCI_BASE_PRI(28),             /* KAL_PRIORITY_SEVENTEEN == SCI_PRIORITY_LOWEST */
	SCI_BASE_PRI(30),             /* KAL_PRIORITY_EIGHTEEN */
	SCI_BASE_PRI(31)              /* KAL_LOWEST_PRIORITY == SCI_PRIORITY_IDLE */
};

enum
{
    PRI_HEIGHEST_PRIORITY_OFFSET    =  1,
    PRI_PRIORITY_ONE_OFFSET         =  2,
    PRI_PRIORITY_TWO_OFFSET         =  3,
    PRI_PRIORITY_THREE_OFFSET       =  4,
    PRI_PRIORITY_FOUR_OFFSET        =  5,
    PRI_PRIORITY_FIVE_OFFSET        =  6,
    PRI_PRIORITY_SIX_OFFSET         =  7,
    PRI_PRIORITY_SEVEN_OFFSET       =  8,
    PRI_PRIORITYIGHT_OFFSET         =  9,
    PRI_PRIORITY_NINE_OFFSET        =  10,
    PRI_PRIORITY_TEN_OFFSET         =  11,
    PRI_PRIORITYLEVEN_OFFSET        =  18,
    PRI_PRIORITY_TWELVE_OFFSET      =  19,
    PRI_PRIORITY_THIRTEEN_OFFSET    =  20,
    PRI_PRIORITY_FOURTEEN_OFFSET    =  21,
    PRI_PRIORITY_FIFTEEN_OFFSET     =  22,
    PRI_PRIORITY_SIXTEEN_OFFSET     =  25,
    PRI_PRIORITY_SEVENTEEN_OFFSET   =  28,
    PRI_PRIORITYIGHTEEN_OFFSET      =  30,
    PRI_LOWEST_PRIORITY_OFFSET      =  31,    
    PRI_BASE_LAYER1_OFFSET          =  3,    
    PRI_TESTPSTOL1_OFFSET           =  10,
    PRI_TESTDSPTOL1_OFFSET          =  10,
    PRI_BASE_CALIBRATION_OFFSET     =  10,
    PRI_TDD_CALIBRATION1_OFFSET     =  10,
    PRI_TDD_CALIBRATION2_OFFSET     =  10,
    PRI_MUX_RECV_TASK1_OFFSET       =  11,
    PRI_MUX_RECV_TASK2_OFFSET       =  11,
    PRI_BASE_RRA_OFFSET             =  14,
    PRI_BASE_DLR_OFFSET             =  14,
    PRI_BASE_MAC_OFFSET             =  14,
    PRI_BASE_RLC_OFFSET             =  14,
    PRI_BASE_DLC_OFFSET             =  14,
    PRI_BASE_RRC_OFFSET             =  15,
    PRI_BASE_LLMAIN_OFFSET          =  15,
    PRI_BASE_LLENTITY_OFFSET        =  15,
    PRI_L1C_DUMP_MEM_OFFSET         =  15,
    PRI_CM_OFFSET                   =  16,
    PRI_DIAG_OFFSET                 =  16,
    PRI_BASE_PROCESSMM_OFFSET       =  16,
    PRI_BASE_GMM_OFFSET             =  16,
    PRI_BASE_RLROUTER_OFFSET        =  18,
    PRI_BASE_CMROUTER_OFFSET        =  18,
    PRI_BASE_CCENTITY_OFFSET        =  18,
    PRI_BASE_SMSCMENTITY_OFFSET     =  18,
    PRI_BASE_RLENTITY_OFFSET        =  18,
    PRI_BASE_SSENTITY_OFFSET        =  18,
    PRI_BASE_SCT_OFFSET             =  18,
    PRI_BASE_SMMAIN_OFFSET          =  18,
    PRI_BASE_SMENTITY_OFFSET        =  18,    
    PRI_BASE_SNDCPMAIN_OFFSET       =  18,
    PRI_BASE_SNDCPENTITY_OFFSET     =  18,
    PRI_BASE_SIMAT_DUM_OFFSET       =  20,
    PRI_PSDummy_TASK_OFFSET         =  20,
    PRI_BASE_SIM_OFFSET             =  22,
    PRI_BASE_NVSMS_OFFSET           =  22,
    PRI_BASE_MN_OFFSET              =  22,
    PRI_BASE_ATC_TASK_OFFSET        =  25,
    PRI_CPANEL_TASK_OFFSET          =  25,
    PRI_CSVTRX_TASK_OFFSET          =  27,
    PRI_CSVTTX_TASK_OFFSET          =  27,
    PRI_LOG_SAVE_TASK_OFFSET        =  30,
    PRI_SIM_WIN_DUMMY_TASK_OFFSET   =  31,
    PRI_DUMMY_RRC_TASK_OFFSET       =  15,
    PRI_DEFAULT_OFFSET              =  18,
    MAX_BASE_PRIORITY_OFFSET        = MAX_BASE_PRI_NUM
};

                                                                                      
//Base Task                                                                           
SCI_DEFINE_TASK_PRI(PRI_HEIGHEST_PRIORITY 	, SCI_BASE_PRI(PRI_HEIGHEST_PRIORITY_OFFSET ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_ONE 		, SCI_BASE_PRI(PRI_PRIORITY_ONE_OFFSET      ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_TWO 		, SCI_BASE_PRI(PRI_PRIORITY_TWO_OFFSET      ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_THREE 		, SCI_BASE_PRI(PRI_PRIORITY_THREE_OFFSET    ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_FOUR 		, SCI_BASE_PRI(PRI_PRIORITY_FOUR_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_FIVE 		, SCI_BASE_PRI(PRI_PRIORITY_FIVE_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_SIX 		, SCI_BASE_PRI(PRI_PRIORITY_SIX_OFFSET      ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_SEVEN 		, SCI_BASE_PRI(PRI_PRIORITY_SEVEN_OFFSET    ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITYIGHT 		, SCI_BASE_PRI(PRI_PRIORITYIGHT_OFFSET      ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_NINE 		, SCI_BASE_PRI(PRI_PRIORITY_NINE_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_TEN 		, SCI_BASE_PRI(PRI_PRIORITY_TEN_OFFSET      ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITYLEVEN 		, SCI_BASE_PRI(PRI_PRIORITYLEVEN_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_TWELVE 	, SCI_BASE_PRI(PRI_PRIORITY_TWELVE_OFFSET   ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_THIRTEEN 	, SCI_BASE_PRI(PRI_PRIORITY_THIRTEEN_OFFSET ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_FOURTEEN 	, SCI_BASE_PRI(PRI_PRIORITY_FOURTEEN_OFFSET ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_FIFTEEN 	, SCI_BASE_PRI(PRI_PRIORITY_FIFTEEN_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_SIXTEEN 	, SCI_BASE_PRI(PRI_PRIORITY_SIXTEEN_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_PRIORITY_SEVENTEEN 	, SCI_BASE_PRI(PRI_PRIORITY_SEVENTEEN_OFFSET));
SCI_DEFINE_TASK_PRI(PRI_PRIORITYIGHTEEN 	, SCI_BASE_PRI(PRI_PRIORITYIGHTEEN_OFFSET   ));
SCI_DEFINE_TASK_PRI(PRI_LOWEST_PRIORITY 	, SCI_BASE_PRI(PRI_LOWEST_PRIORITY_OFFSET   ));
SCI_DEFINE_TASK_PRI(PRI_BASE_LAYER1 		, SCI_BASE_PRI(PRI_BASE_LAYER1_OFFSET       ));
SCI_DEFINE_TASK_PRI(PRI_BASE_DLC 			, SCI_BASE_PRI(PRI_BASE_DLC_OFFSET          ));
SCI_DEFINE_TASK_PRI(PRI_BASE_LLENTITY 		, SCI_BASE_PRI(PRI_BASE_LLENTITY_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_TESTPSTOL1 			, SCI_BASE_PRI(PRI_TESTPSTOL1_OFFSET        ));
SCI_DEFINE_TASK_PRI(PRI_TESTDSPTOL1 		, SCI_BASE_PRI(PRI_TESTDSPTOL1_OFFSET       ));
SCI_DEFINE_TASK_PRI(PRI_BASE_CALIBRATION 	, SCI_BASE_PRI(PRI_BASE_CALIBRATION_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_TDD_CALIBRATION1	, SCI_BASE_PRI(PRI_TDD_CALIBRATION1_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_TDD_CALIBRATION2	, SCI_BASE_PRI(PRI_TDD_CALIBRATION2_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_MUX_RECV_TASK1 		, SCI_BASE_PRI(PRI_MUX_RECV_TASK1_OFFSET    ));
SCI_DEFINE_TASK_PRI(PRI_MUX_RECV_TASK2 		, SCI_BASE_PRI(PRI_MUX_RECV_TASK2_OFFSET    ));
SCI_DEFINE_TASK_PRI(PRI_BASE_RRA   		    , SCI_BASE_PRI(PRI_BASE_RRA_OFFSET          ));
SCI_DEFINE_TASK_PRI(PRI_BASE_DLR 			, SCI_BASE_PRI(PRI_BASE_DLR_OFFSET          ));
SCI_DEFINE_TASK_PRI(PRI_BASE_MAC 			, SCI_BASE_PRI(PRI_BASE_MAC_OFFSET          ));
SCI_DEFINE_TASK_PRI(PRI_BASE_RLC 			, SCI_BASE_PRI(PRI_BASE_RLC_OFFSET          ));
SCI_DEFINE_TASK_PRI(PRI_BASE_RRC 			, SCI_BASE_PRI(PRI_BASE_RRC_OFFSET          ));
SCI_DEFINE_TASK_PRI(PRI_BASE_LLMAIN 		, SCI_BASE_PRI(PRI_BASE_LLMAIN_OFFSET            ));
SCI_DEFINE_TASK_PRI(PRI_L1C_DUMP_MEM 		, SCI_BASE_PRI(PRI_L1C_DUMP_MEM_OFFSET      ));
SCI_DEFINE_TASK_PRI(PRI_CM   				, SCI_BASE_PRI(PRI_CM_OFFSET                ));
SCI_DEFINE_TASK_PRI(PRI_DIAG 				, SCI_BASE_PRI(PRI_DIAG_OFFSET              ));
SCI_DEFINE_TASK_PRI(PRI_BASE_PROCESSMM 	    , SCI_BASE_PRI(PRI_BASE_PROCESSMM_OFFSET    ));
SCI_DEFINE_TASK_PRI(PRI_BASE_GMM 			, SCI_BASE_PRI(PRI_BASE_GMM_OFFSET          ));
SCI_DEFINE_TASK_PRI(PRI_BASE_RLROUTER 		, SCI_BASE_PRI(PRI_BASE_RLROUTER_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_BASE_CMROUTER 		, SCI_BASE_PRI(PRI_BASE_CMROUTER_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_BASE_CCENTITY 		, SCI_BASE_PRI(PRI_BASE_CCENTITY_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_BASE_SMSCMENTITY 	, SCI_BASE_PRI(PRI_BASE_SMSCMENTITY_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_BASE_RLENTITY 		, SCI_BASE_PRI(PRI_BASE_RLENTITY_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_BASE_SSENTITY 		, SCI_BASE_PRI(PRI_BASE_SSENTITY_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_BASE_SCT 			, SCI_BASE_PRI(PRI_BASE_SCT_OFFSET          ));
SCI_DEFINE_TASK_PRI(PRI_BASE_SMMAIN 		, SCI_BASE_PRI(PRI_BASE_SMMAIN_OFFSET       ));
SCI_DEFINE_TASK_PRI(PRI_BASE_SMENTITY 		, SCI_BASE_PRI(PRI_BASE_SMENTITY_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_BASE_SNDCPMAIN 		, SCI_BASE_PRI(PRI_BASE_SNDCPMAIN_OFFSET    ));
SCI_DEFINE_TASK_PRI(PRI_BASE_SNDCPENTITY 	, SCI_BASE_PRI(PRI_BASE_SNDCPENTITY_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_BASE_SIMAT_DUM   	, SCI_BASE_PRI(PRI_BASE_SIMAT_DUM_OFFSET    ));
SCI_DEFINE_TASK_PRI(PRI_PSDummy_TASK 		, SCI_BASE_PRI(PRI_PSDummy_TASK_OFFSET      ));
SCI_DEFINE_TASK_PRI(PRI_BASE_SIM 			, SCI_BASE_PRI(PRI_BASE_SIM_OFFSET          ));
SCI_DEFINE_TASK_PRI(PRI_BASE_NVSMS 			, SCI_BASE_PRI(PRI_BASE_NVSMS_OFFSET        ));
SCI_DEFINE_TASK_PRI(PRI_BASE_MN  			, SCI_BASE_PRI(PRI_BASE_MN_OFFSET           ));
SCI_DEFINE_TASK_PRI(PRI_BASE_ATC_TASK  		, SCI_BASE_PRI(PRI_BASE_ATC_TASK_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_CPANEL_TASK    		, SCI_BASE_PRI(PRI_CPANEL_TASK_OFFSET       ));
SCI_DEFINE_TASK_PRI(PRI_CSVTRX_TASK 		, SCI_BASE_PRI(PRI_CSVTRX_TASK_OFFSET       ));
SCI_DEFINE_TASK_PRI(PRI_CSVTTX_TASK 		, SCI_BASE_PRI(PRI_CSVTTX_TASK_OFFSET       ));
SCI_DEFINE_TASK_PRI(PRI_LOG_SAVE_TASK  		, SCI_SYSTEM_PRI(PRI_LOG_SAVE_TASK_OFFSET     ));
SCI_DEFINE_TASK_PRI(PRI_SIM_WIN_DUMMY_TASK 	, SCI_BASE_PRI(PRI_SIM_WIN_DUMMY_TASK_OFFSET));
SCI_DEFINE_TASK_PRI(PRI_DUMMY_RRC_TASK 		, SCI_BASE_PRI(PRI_DUMMY_RRC_TASK_OFFSET    ));
SCI_DEFINE_TASK_PRI(PRI_DEFAULT 	    	, SCI_BASE_PRI(PRI_DEFAULT_OFFSET           ));

/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif 

//End of oscfg.c
