/******************************************************************************
 ** File Name:      pinmap_cfg.c                                              *
 ** Author:         Sunny.Fei                                                 *
 ** DATE:           2011.01.12                                                *
 ** Copyright:      2011 Spreadtrum, Incoporated. All Rights Reserved.        *
 ** Description:                                                              *
 **                                                                           *
 **                                                                           *
 ******************************************************************************
 **---------------------------------------------------------------------------*
 **                         Dependencies                                      *
 **---------------------------------------------------------------------------*/
#include "arm_reg.h"/*lint -esym(766, chip_drv\export\inc\outdated\arm_reg.h)*/
#include "../../../../../chip_drv/chip_module/pin/uws6121e/pinmap.h"
#include "sc_reg.h"/*lint -esym(766, chip_drv\export\inc\outdated\sc_reg.h)*/
#include "../../../../../chip_drv/chip_plf/uws6121e/global_macros.h"
#include "pinmap_drvapi.h"

/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef   __cplusplus
    extern   "C"
    {
#endif

/**---------------------------------------------------------------------------*
 **                         Data                                              *
 **---------------------------------------------------------------------------*/
 const PM_PINFUNC_T pm_func[]=
{
//| Pin Register                                  | IO | Func Select|
//analog_reg pin                                | drv strength | wps | pu/pd  | dslp_en  | slp_pu/slp_pd  | slp_ie/slp_oe
  //{REG_PIN_RFDIG_GPIO_7,					BITS_PIN_AF(0)},
  //{REG_MISC_PIN_RFDIG_GPIO_7,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  //{REG_PIN_RFDIG_GPIO_6,					BITS_PIN_AF(0)},
  //{REG_MISC_PIN_RFDIG_GPIO_6,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  //{REG_PIN_RFDIG_GPIO_5,					BITS_PIN_AF(0)},
  //{REG_MISC_PIN_RFDIG_GPIO_5,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  //{REG_PIN_RFDIG_GPIO_4,					BITS_PIN_AF(0)},
  //{REG_MISC_PIN_RFDIG_GPIO_4,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  //{REG_PIN_RFDIG_GPIO_3,					BITS_PIN_AF(0)},
  //{REG_MISC_PIN_RFDIG_GPIO_3,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  //{REG_PIN_RFDIG_GPIO_2,					BITS_PIN_AF(0)},
  //{REG_MISC_PIN_RFDIG_GPIO_2,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  //{REG_PIN_RFDIG_GPIO_1,					BITS_PIN_AF(0)},
  //{REG_MISC_PIN_RFDIG_GPIO_1,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  //{REG_PIN_RFDIG_GPIO_0,					BITS_PIN_AF(0)},
  //{REG_MISC_PIN_RFDIG_GPIO_0,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},

#ifdef ZDT_PCBA_ZW201_SUPPORT
  {REG_PIN_KEYIN4,					BITS_PIN_AF(1)},//GPIO8- NULL
  {REG_MISC_PIN_KEYIN4,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_KEYOUT5,					BITS_PIN_AF(1)},//GPIO11-AUDIO_EN
  {REG_MISC_PIN_KEYOUT5,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},// codec power en
  {REG_PIN_KEYIN5,					BITS_PIN_AF(1)},//GPIO9-EN_MIC
  {REG_MISC_PIN_KEYIN5,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  {REG_PIN_KEYOUT4,					BITS_PIN_AF(1)},//GPIO10-RST_HRM
  {REG_MISC_PIN_KEYOUT4,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},	//check this pin		BIT_PIN_WPD
#else
#ifdef HW_6121_pre_w217
  {REG_PIN_KEYIN4,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYIN4,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_KEYOUT5,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_KEYOUT5,			BITS_PIN_DS(1)|BIT_PIN_WPUS|BIT_PIN_WPU|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},	// codec power en
  {REG_PIN_KEYIN5,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYIN5,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_KEYOUT4,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYOUT4,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
#else
  {REG_PIN_KEYIN4,					BITS_PIN_AF(1)},//GPIO8-AG_INT0-customer
  {REG_MISC_PIN_KEYIN4,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_KEYOUT5,					BITS_PIN_AF(1)},//GPIO11-AUDIO_EN
  {REG_MISC_PIN_KEYOUT5,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},// codec power en
  {REG_PIN_KEYIN5,					BITS_PIN_AF(1)},//GPIO9-EN_MIC
  {REG_MISC_PIN_KEYIN5,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  {REG_PIN_KEYOUT4,					BITS_PIN_AF(1)},//GPIO10-RST_HRM
  {REG_MISC_PIN_KEYOUT4,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},	//check this pin		BIT_PIN_WPD
#endif
#endif
#ifdef ZDT_PCBA_ZW201_SUPPORT
  {REG_PIN_U1RTS,                         BITS_PIN_AF(1)},
  {REG_MISC_PIN_U1RTS,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},	//GPIO 15 BLE RESET
  {REG_PIN_U1TXD,                         BITS_PIN_AF(1)},
  {REG_MISC_PIN_U1TXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},	//GPIO 13 SUB CAMERA RST
  {REG_PIN_U1RXD,                         BITS_PIN_AF(1)},
  {REG_MISC_PIN_U1RXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_IE},	//GPIO 12  CTP_INT
  {REG_PIN_U1CTS,                         BITS_PIN_AF(1)},
  {REG_MISC_PIN_U1CTS,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},	//GPIO 14  NULL
#else
  {REG_PIN_U1RTS,                         BITS_PIN_AF(4)},
  {REG_MISC_PIN_U1RTS,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},	//check this pin
  {REG_PIN_U1TXD,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_U1TXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},	//check this pin
  {REG_PIN_U1RXD,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_U1RXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},	//check this pin
  {REG_PIN_U1CTS,                         BITS_PIN_AF(1)},
  {REG_MISC_PIN_U1CTS,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},	//check this pin		BIT_PIN_WPD
#endif
#ifdef ZDT_PCBA_ZW201_SUPPORT
  {REG_PIN_GPIO0,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO0,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE |BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},//GPIO 0 LED R EN
  {REG_PIN_GPIO3,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO3,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_IE}, //GPIO 3 AG-INT1
  {REG_PIN_GPIO2,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO2,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_IE},//GPIO 2 AG-INT0
  {REG_PIN_GPIO1,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO1,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},//GPIO 1 LED G EN
  {REG_PIN_GPIO7,                         BITS_PIN_AF(2)},//I2C2_SDA
  {REG_MISC_PIN_GPIO7,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z}, // I2C2 For HRS
  {REG_PIN_GPIO6,                         BITS_PIN_AF(2)},//I2C2_SCL
  {REG_MISC_PIN_GPIO6,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z}, // I2C2 For HRS
  {REG_PIN_GPIO5,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO5,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},//GPIO 5 Main Camera Reset
  {REG_PIN_GPIO4,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO4,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_NONE|BIT_PIN_WPU|BIT_PIN_SLP_IE}, //GPIO 4 HALL_INT_customer_change
#else
#ifdef HW_6121_pre_w217
  {REG_PIN_GPIO0,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO0,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO3,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO3,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO2,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO2,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO1,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO1,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO7,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO7,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO6,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO6,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO5,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO5,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO4,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO4,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
#else
  {REG_PIN_GPIO0,                         BITS_PIN_AF(7)},//UART2_RXD
  {REG_MISC_PIN_GPIO0,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_ALL|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},//check this pin
  {REG_PIN_GPIO3,                         BITS_PIN_AF(0)},//GPIO-VDD2V8_EN
  {REG_MISC_PIN_GPIO3,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_AP|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_GPIO2,                         BITS_PIN_AF(7)},//UART2_CTS
  {REG_MISC_PIN_GPIO2,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_ALL|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},//check this pin
  {REG_PIN_GPIO1,                         BITS_PIN_AF(7)},//UART2_TXD
  {REG_MISC_PIN_GPIO1,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_ALL|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},//check this pin
  {REG_PIN_GPIO7,                         BITS_PIN_AF(2)},//I2C2_SDA
  {REG_MISC_PIN_GPIO7,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO6,                         BITS_PIN_AF(2)},//I2C2_SCL
  {REG_MISC_PIN_GPIO6,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO5,                         BITS_PIN_AF(0)},//RST_HRM_customer_change
  {REG_MISC_PIN_GPIO5,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},//check this pin
#ifdef SIM_PLUG_IN_SUPPORT
  {REG_PIN_GPIO4,                         BITS_PIN_AF(0)},//HALL_INT_customer_change
  {REG_MISC_PIN_GPIO4,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_NONE|BIT_PIN_WPU|BIT_PIN_SLP_IE},
#else
  {REG_PIN_GPIO4,                         BITS_PIN_AF(0)},//NC
  {REG_MISC_PIN_GPIO4,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_WPD|BIT_PIN_SLP_Z},	//DO MOVE
#endif
#endif
#endif

  {REG_PIN_ADI_SDA,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_ADI_SDA,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_ALL|BIT_PIN_SLP_NUL|BIT_PIN_SLP_IE|BIT_PIN_SLP_OE},//DO MOVE
  {REG_PIN_ADI_SCL,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_ADI_SCL,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_ALL|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},//DO MOVE
  {REG_PIN_RESETB,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_RESETB,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},//DO MOVE
  {REG_PIN_OSC_32K,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_OSC_32K,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_IE},//DO MOVE
  {REG_PIN_PMIC_EXT_INT,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_PMIC_EXT_INT,           BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_IE},//DO MOVE
  {REG_PIN_CHIP_PD,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_CHIP_PD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_ALL|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},//DO MOVE
  {REG_PIN_PTEST,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_PTEST,                    BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},//DO MOVE    //GND
  {REG_PIN_CLK26M_PMIC,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_CLK26M_PMIC,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},//DO MOVE
  {REG_PIN_SIM_1_RST,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_SIM_1_RST,                    BITS_PIN_DS(3)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_SIM_1_DIO,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_SIM_1_DIO,                    BITS_PIN_DS(3)|BIT_PIN_WPUS|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  {REG_PIN_SIM_1_CLK,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_SIM_1_CLK,                    BITS_PIN_DS(3)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_SIM_0_RST,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_SIM_0_RST,                    BITS_PIN_DS(3)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_SIM_0_DIO,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_SIM_0_DIO,                    BITS_PIN_DS(3)|BIT_PIN_WPUS|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  {REG_PIN_SIM_0_CLK,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_SIM_0_CLK,                    BITS_PIN_DS(3)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_SW_CLK,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_SW_CLK,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},//MTCK
  {REG_PIN_SW_DIO,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_SW_DIO,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},//MTMS
  {REG_PIN_DEBUG_HOST_TX,                      BITS_PIN_AF(1)},
  {REG_MISC_PIN_DEBUG_HOST_TX,                  BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_DEBUG_HOST_RX,                      BITS_PIN_AF(1)},
  {REG_MISC_PIN_DEBUG_HOST_RX,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPU|BIT_PIN_SLP_IE},
  {REG_PIN_DEBUG_HOST_CLK,                      BITS_PIN_AF(1)},
  {REG_MISC_PIN_DEBUG_HOST_CLK,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_IE},
#ifdef HW_6121_pre_w217
  {REG_PIN_CAMERA_RST_L,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_CAMERA_RST_L,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
#else
  {REG_PIN_CAMERA_RST_L,						BITS_PIN_AF(3)},
  {REG_MISC_PIN_CAMERA_RST_L, 				BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
#endif
  {REG_PIN_SPI_CAMERA_SCK,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_SPI_CAMERA_SCK,                BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_SPI_CAMERA_SI_1,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_SPI_CAMERA_SI_1,                BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_SPI_CAMERA_SI_0,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_SPI_CAMERA_SI_0,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_CAMERA_REF_CLK,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_CAMERA_REF_CLK,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_CAMERA_PWDN,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_CAMERA_PWDN,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_I2S_SDAT_I,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_I2S_SDAT_I,                 BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_I2S1_SDAT_O,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_I2S1_SDAT_O,                 BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_I2S1_LRCK,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_I2S1_LRCK,                 BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_I2S1_BCK,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_I2S1_BCK,                 BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_I2S1_MCLK,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_I2S1_MCLK,                 BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},

#ifdef ZDT_PCBA_ZW201_SUPPORT
  {REG_PIN_I2C_M2_SCL,                      BITS_PIN_AF(2)},
  {REG_MISC_PIN_I2C_M2_SCL,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},//GPIO 42 FLASH LED EN
  {REG_PIN_I2C_M2_SDA,                      BITS_PIN_AF(2)},
  {REG_MISC_PIN_I2C_M2_SDA,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},//GPIO 43 TP RST
#else
#ifdef HW_6121_pre_w217
  {REG_PIN_I2C_M2_SCL,                      BITS_PIN_AF(0)},
#else
  {REG_PIN_I2C_M2_SCL,                      BITS_PIN_AF(2)},//gpio42-CTP_INT
#endif

#ifdef HW_6121_pre_w217
  {REG_MISC_PIN_I2C_M2_SCL,                 BITS_PIN_DS(1)|BIT_PIN_WPUS|BIT_PIN_WPU|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPU|BIT_PIN_SLP_Z},
#else
  {REG_MISC_PIN_I2C_M2_SCL,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPU|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPU|BIT_PIN_SLP_IE},//BIT_PIN_WPU:change
#endif

#ifdef HW_6121_pre_w217
  {REG_PIN_I2C_M2_SDA,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_I2C_M2_SDA,                 BITS_PIN_DS(1)|BIT_PIN_WPUS|BIT_PIN_WPU|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPU|BIT_PIN_SLP_Z},
#else
  {REG_PIN_I2C_M2_SDA,                      BITS_PIN_AF(2)},//gpio43-CTP_RST
  {REG_MISC_PIN_I2C_M2_SDA,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
#endif
#endif

  {REG_PIN_Nand_SEL,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_Nand_SEL,                 BITS_PIN_DS(3)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},

#ifdef ZDT_PCBA_ZW201_SUPPORT
  {REG_PIN_KEYOUT3,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYOUT3,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_KEYOUT2,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYOUT2,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_KEYOUT1,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYOUT1,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_KEYIN3,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYIN3,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_KEYIN2,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYIN2,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_KEYIN1,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYIN1,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
#else
#ifdef HW_6121_pre_w217
  {REG_PIN_KEYOUT3,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYOUT3,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_KEYOUT2,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYOUT2,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_KEYOUT1,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYOUT1,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_KEYIN3,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYIN3,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_KEYIN2,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYIN2,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_KEYIN1,					BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYIN1,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  #else
  {REG_PIN_KEYOUT3,					BITS_PIN_AF(1)},//GPIO35-EN_TP
  {REG_MISC_PIN_KEYOUT3,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},	//DO MOVE
  {REG_PIN_KEYOUT2,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_KEYOUT2,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_KEYOUT1,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_KEYOUT1,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_KEYIN3,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_KEYIN3,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_KEYIN2,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_KEYIN2,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_KEYIN1,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_KEYIN1,			BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
#endif
#endif

  {REG_PIN_KEYIN0,							BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYIN0,					BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  {REG_PIN_KEYOUT0,							BITS_PIN_AF(0)},
  {REG_MISC_PIN_KEYOUT0,					BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_Z},
  {REG_PIN_LCD_RSTB,							BITS_PIN_AF(0)},
  {REG_MISC_PIN_LCD_RSTB,				BITS_PIN_DS(3)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_LCD_FMARK,						BITS_PIN_AF(0)},
  {REG_MISC_PIN_LCD_FMARK,				BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_IE},
  {REG_PIN_SPI_LCD_SELECT,					BITS_PIN_AF(2)},
#ifdef HW_6121_pre_w217
  {REG_MISC_PIN_SPI_LCD_SELECT,         	BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
#else
  {REG_MISC_PIN_SPI_LCD_SELECT,		BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z}, // audio codec en
#endif
  {REG_PIN_SPI_LCD_CS,						BITS_PIN_AF(0)},
  {REG_MISC_PIN_SPI_LCD_CS,				BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_SPI_LCD_CLK,						BITS_PIN_AF(0)},
  {REG_MISC_PIN_SPI_LCD_CLK,				BITS_PIN_DS(2)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SPI_LCD_SDC,						BITS_PIN_AF(0)},
  {REG_MISC_PIN_SPI_LCD_SDC,				BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SPI_LCD_SIO,						BITS_PIN_AF(0)},
  {REG_MISC_PIN_SPI_LCD_SIO,				BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_RST,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_RST,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_DATA_7,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_DATA_7,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_DATA_6,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_DATA_6,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_DATA_5,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_DATA_5,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_DATA_4,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_DATA_4,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_DATA_3,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_DATA_3,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_DATA_2,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_DATA_2,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_DATA_1,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_DATA_1,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_DATA_0,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_DATA_0,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_CMD,						BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_CMD,				BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_SDMMC1_CLK,					BITS_PIN_AF(1)},
  {REG_MISC_PIN_SDMMC1_CLK,			BITS_PIN_DS(0)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
#ifdef ZDT_PCBA_ZW201_SUPPORT
  {REG_PIN_U2RTS,                         				BITS_PIN_AF(1)},
  {REG_MISC_PIN_U2RTS,                    		BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z}, // GPIO 34  LED9 EN
  {REG_PIN_U2CTS,                         				BITS_PIN_AF(1)},
  {REG_MISC_PIN_U2CTS,                    		BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z}, //GPIO 33  NFC PVDD EN
  {REG_PIN_U2TXD,                         BITS_PIN_AF(3)},
  {REG_MISC_PIN_U2TXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z}, //GPIO 31 NULL
  {REG_PIN_U2RXD,                         BITS_PIN_AF(3)},
  {REG_MISC_PIN_U2RXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z}, //GPIO 32 NULL
#else
  {REG_PIN_U2RTS,                         				BITS_PIN_AF(1)},
  {REG_MISC_PIN_U2RTS,                    		BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_U2CTS,                         				BITS_PIN_AF(1)},
  {REG_MISC_PIN_U2CTS,                    		BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
//#ifdef HW_6121_pre_w217
#if 1
  {REG_PIN_U2TXD,                         BITS_PIN_AF(3)},
  {REG_MISC_PIN_U2TXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_U2RXD,                         BITS_PIN_AF(3)},
  {REG_MISC_PIN_U2RXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
#else
  {REG_PIN_U2TXD,                         BITS_PIN_AF(3)},
  {REG_MISC_PIN_U2TXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_U2RXD,                         BITS_PIN_AF(3)},
  {REG_MISC_PIN_U2RXD,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
#endif
#endif
  {REG_PIN_I2C_M1_SDA,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_I2C_M1_SDA,                 BITS_PIN_DS(1)|BIT_PIN_WPUS|BIT_PIN_WPU|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPU|BIT_PIN_SLP_Z},
  {REG_PIN_I2C_M1_SCL,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_I2C_M1_SCL,                 BITS_PIN_DS(1)|BIT_PIN_WPUS|BIT_PIN_WPU|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPU|BIT_PIN_SLP_Z},

#ifdef ZDT_PCBA_ZW201_SUPPORT
  {REG_PIN_GPIO23,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO23,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},  // GPIO 23 LED 7 EN
  {REG_PIN_GPIO22,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO22,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},  // GPIO 22 LED 6 EN
  {REG_PIN_GPIO21,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO21,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_IE},   // GPIO 21  HRS INT
  {REG_PIN_GPIO20,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO20,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},  // GPIO 20 HRS POWER EN
  {REG_PIN_GPIO19,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO19,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},   // GPIO 19 HRS PDN
  {REG_PIN_GPIO18,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO18,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_OE},  // GPIO 18 MUTE
#else
#ifdef MULTI_FLASH_SUPPORT
  {REG_PIN_GPIO23,                      BITS_PIN_AF(1)},
  {REG_MISC_PIN_GPIO23,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO22,                      BITS_PIN_AF(1)},
  {REG_MISC_PIN_GPIO22,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO21,                      BITS_PIN_AF(1)},
  {REG_MISC_PIN_GPIO21,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO20,                      BITS_PIN_AF(1)},
  {REG_MISC_PIN_GPIO20,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO19,                      BITS_PIN_AF(1)},
  {REG_MISC_PIN_GPIO19,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_GPIO18,                      BITS_PIN_AF(1)},
  {REG_MISC_PIN_GPIO18,                 BITS_PIN_DS(2)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
#else
  {REG_PIN_GPIO23,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO23,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO22,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO22,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO21,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO21,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO20,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO20,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO19,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO19,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_GPIO18,                      BITS_PIN_AF(0)},
  {REG_MISC_PIN_GPIO18,                 BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPD|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
#endif
#endif

#ifdef HW_6121_pre_w217
  {REG_PIN_GPIO17,                         BITS_PIN_AF(1)},
  {REG_MISC_PIN_GPIO17,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_WPUS|BIT_PIN_SLP_AP|BIT_PIN_SLP_WPU|BIT_PIN_SLP_IE},
  {REG_PIN_GPIO16,                         BITS_PIN_AF(1)},
#else
  {REG_PIN_GPIO17,                         BITS_PIN_AF(3)},//I2C3_SDA
  {REG_MISC_PIN_GPIO17,  BITS_PIN_DS(3)|BIT_PIN_WPU|BIT_PIN_WPUS|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPU|BIT_PIN_SLP_Z},
  {REG_PIN_GPIO16,                         BITS_PIN_AF(3)},//I2C3_SCK
#endif
 // {REG_MISC_PIN_GPIO16,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_AP|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_MISC_PIN_GPIO16,  BITS_PIN_DS(3)|BIT_PIN_WPU|BIT_PIN_WPUS|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPU|BIT_PIN_SLP_Z},

  {REG_PIN_M_SPI_D_3,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_M_SPI_D_3,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_M_SPI_D_2,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_M_SPI_D_2,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_M_SPI_D_1,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_M_SPI_D_1,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_M_SPI_D_0,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_M_SPI_D_0,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_WPD|BIT_PIN_SLP_Z},
  {REG_PIN_M_SPI_D_CS,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_M_SPI_D_CS,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {REG_PIN_M_SPI_D_CLK,                         BITS_PIN_AF(0)},
  {REG_MISC_PIN_M_SPI_D_CLK,                    BITS_PIN_DS(1)|BIT_PIN_NULL|BIT_PIN_NUL|BIT_PIN_SLP_NONE|BIT_PIN_SLP_NUL|BIT_PIN_SLP_OE},
  {0xffffffff, 0xffffffFF}
};

const PM_GPIO_CTL_T  pm_gpio_default_map[]=
{
	{35, 	 1, 		 	PM_OUTPUT, 	  	PM_INVALID_INT    },
#ifdef ZDT_PCBA_ZW201_SUPPORT
	{0,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // LED R EN
	{1,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // LED G EN
	{2,      	0xFFFF,    	PM_INPUT,     	PM_LEVEL    },           // AG-INT0
	{3,      	0xFFFF,    	PM_INPUT,     	PM_LEVEL    },           // AG-INT1
	{4,        	0xFFFF,     	PM_INPUT,         	PM_LEVEL},              // HALL INT
	{5,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // Main Camera Reset
	{8,      	 0xFFFF,    	PM_INPUT,     	PM_LEVEL    },          //NULL
	{9,      	1,    		PM_OUTPUT,     	PM_INVALID_INT    }, // EN MICBIAS
	{10,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // RST HRM
	{11, 	 1, 		 	PM_OUTPUT, 	  	PM_INVALID_INT    }, // AUDIO PA EN
	{12,        0xFFFF,        PM_INPUT,         	PM_LEVEL},  // TP INT
	{13,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // SUB Camera RST
	{14,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, //  NULL
	{15,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // BLE RESET
	{18,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // MUTE
	{19,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // HRS PWD
	{20,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // HRS POWER EN
	{21,      	0xFFFF,    		PM_INPUT,     PM_LEVEL}, // HRS INT
	{22,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // LED6 EN
	{23,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // LED7 EN
	{42,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // FLASH LED EN
	{43,        0,          	PM_OUTPUT,         PM_INVALID_INT},    // TP RST
	{31,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // NULL
	{32,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, //  NULL
	{33,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // PVDD EN
	{34,      	0,    		PM_OUTPUT,     	PM_INVALID_INT    }, // LED9 EN
#else
#ifdef SIM_PLUG_IN_SUPPORT
	{4,        	 0xFFFF,  	PM_INPUT,         	PM_LEVEL},
#endif
	{11, 	 1, 		 	PM_OUTPUT, 	  	PM_INVALID_INT    },
	{42,        0xFFFF,        PM_INPUT,         	PM_FALLING_EDGE},
	{43,        0,          	PM_OUTPUT,         PM_INVALID_INT},
	{3,      	 1,         		PM_OUTPUT,    	PM_INVALID_INT    },    //G-sensor VDD2.8_EN
	{8,      	 0xFFFF,    	PM_INPUT,     	PM_LEVEL    },          //G-sensor INT
#ifdef HW_6121_pre_w217
#else
	{9,      	1,    		PM_OUTPUT,     	PM_INVALID_INT    },
#endif
#endif
	{0xffff,  0, 	       	PM_INVALID_DIR, 	  PM_INVALID_INT    }
};

/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif

// End of pinmap_cfg.c
