/*
 * Copyright (C) 2021 UNISOC Technologies Co.,Ltd. All Rights Reserved
 *
 * Automatically generated by code_generator_unirtos.pm.
 */

#include "jerry_bindings.h"
#include "jerry_kv.h"
#include "ual_kv.h"

#define KV_VALUE_MAX_LEN  128 //128 is max value len

DECLARE_HANDLER(js_kv_get_value)
{
    JERRY_CHECK_ARGS(1, string);

    jerry_string_t key = JERRY_GET_ARG(0, string);
    JS_DEBUG_LOG("KV getvalue, key is %s\n", jerry_string_data(&key));

    uint8 buffer_len  = KV_VALUE_MAX_LEN;
    char* buffer = jerry_buffer_allocate(buffer_len);

    if(NULL != buffer)
    {
        ual_kv_result_e ret = ual_kv_get_value(jerry_string_data(&key), buffer, &buffer_len);

        JS_DEBUG_LOG("KV getvalue ret(%d)! \n", ret);
        if (UAL_KV_RESULT_SUCCESS == ret)
        {
            jerry_string_t contents = jerry_string_create_with_buffer(buffer, strlen(buffer));
            jerry_value_t ret_val = jerry_jval_create_string(&contents);
            jerry_buffer_release(buffer);
            jerry_string_destroy(&key);
            return ret_val;
        }
        else if(UAL_KV_RESULT_KEY_NOT_EXIST == ret)
        {
            jerry_buffer_release(buffer);
            jerry_string_destroy(&key);
            return jerry_create_string((jerry_char_t*)"");
        }
        else
        {
            jerry_buffer_release(buffer);
            JS_DEBUG_LOG("KV getvalue other error! \n");
        }
    }
    jerry_string_destroy(&key);
    JS_DEBUG_LOG("KV %s failed! \n", __func__);
    return jerry_create_undefined();
}

DECLARE_HANDLER(js_kv_set_value)
{
    JERRY_CHECK_ARGS(2, string, string);

    jerry_string_t key = JERRY_GET_ARG(0, string);
    JS_DEBUG_LOG("KV setvalue, key is %s\n", jerry_string_data(&key));

    jerry_string_t value = JERRY_GET_ARG(1, string);
    JS_DEBUG_LOG("KV setvalue, value is %s\n", jerry_string_data(&key));

    ual_kv_result_e ret = ual_kv_set_value(jerry_string_data(&key), jerry_string_data(&value));
    JS_DEBUG_LOG("KV setvalue ret(%d)! \n", ret);

    jerry_string_destroy(&key);
    jerry_string_destroy(&value);
    return jerry_create_number(ret);
}

DECLARE_HANDLER(js_kv_delete_value)
{
    JERRY_CHECK_ARGS(1, string);

    jerry_string_t key = JERRY_GET_ARG(0, string);
    JS_DEBUG_LOG("KV deletevalue, key is %s\n", jerry_string_data(&key));

    ual_kv_result_e ret = ual_kv_delete_value(jerry_string_data(&key));
    JS_DEBUG_LOG("KV deletevalue ret(%d)! \n", ret);

    jerry_string_destroy(&key);

    return jerry_create_number(ret);
}
void js_register_kv_functions()
{
    REGISTER_HANDLER(js_kv_get_value);
    REGISTER_HANDLER(js_kv_set_value);
    REGISTER_HANDLER(js_kv_delete_value);
};