

//[[define image infomation
#if defined (PIC_PREVIEW_U200_SUPPORT) || defined(BAIDU_DRIVE_SUPPORT)
RES_ADD_IMG(IMAGE_PICVIEW_OPTION,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_OPTION.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#if defined( PICVIEW_VIEW_ZOOM) || defined(PIC_PREVIEW_U200_SUPPORT) || defined(BAIDU_DRIVE_SUPPORT)
//RES_ADD_IMG(IMAGE_PICVIEW_PLAY,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_PLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_RETURN,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_RETURN.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef PICVIEW_VIEW_ZOOM
RES_ADD_IMG(IMAGE_PICVIEW_ZOOM_IN,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_ZOOM_IN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_ZOOM_IN_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_ZOOM_IN_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_ZOOM_OUT,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_ZOOM_OUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_ZOOM_OUT_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_ZOOM_OUT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#if defined ( PIC_VIEWER_SUPPORT )
#ifndef MMI_PICVIEW_MINI_SUPPORT
RES_ADD_IMG(IMAGE_PICVIEW_CHANGE_FOLDER,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_CHANGE_FOLDER.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#ifdef PIC_PREVIEW_U200_SUPPORT
#ifdef PIC_EDITOR_SUPPORT
RES_ADD_IMG(IMAGE_PICVIEW_EDIT_IMAGE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_EDIT_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_IMG(IMAGE_PICVIEW_ZOOM,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_ZOOM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_SLIDEPLAY_ICON,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_SLIDEPLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PICVIEW_FOLDER_DEFAULT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_FOLDER_DEFAULT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PICVIEW_FOLDER_LIST_TITLE_BG,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_FOLDER_LIST_TITLE_BG.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
//RES_ADD_IMG(IMAGE_PICVIEW_CAMERA_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_CAMERA_BUTTON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PICVIEW_CAMERA_BUTTON_SELECTED,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_CAMERA_BUTTON_SELECTED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#if defined ( PIC_VIEWER_SUPPORT )
#ifdef PIC_PREVIEW_U200_SUPPORT
RES_ADD_IMG(IMAGE_PICVIEW_FOLDER_LIST_BG,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_FOLDER_LIST_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#endif
#ifdef PIC_PREVIEW_U200_SUPPORT
#ifdef PIC_GLIDE_SUPPORT
RES_ADD_IMG(IMAGE_DECODE_ON,"\\MMI_RES_##\\IMAG\\IMAGE_DECODE_ON.gif",IMG_CMP_GIF_SCI,0)
#endif
#endif
//]]define image infomation
#if defined ( PIC_VIEWER_SUPPORT )
RES_ADD_IMG(IMAGE_PICVIEW_OSD_BG,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_OSD_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
#endif
#ifdef PIC_PREVIEW_U200_SUPPORT
RES_ADD_IMG(IMAGE_PICVIEW_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_BUTTON.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_PICVIEW_CAMERA,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_CAMERA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_SET,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_SET.png",IMG_CMP_PNG_ARGB_RLE,0)  

RES_ADD_IMG(IMAGE_PICVIEW_MARK_DEFAULT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_MARK_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_PICVIEW_PLAY_DEFAULT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_PLAY_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_DELETE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_DELETE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifndef PIC_PREVIEW_U200_SUPPORT
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG(IMAGE_PICVIEW_CAMERA_FOLDER,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_CAMERA.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
RES_ADD_IMG(IMAGE_PICVIEW_FOLDER_DEFAULT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_FOLDER_DEFAULT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_PIC_ERROR_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_PIC_ERROR_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_GUI_STYLE_MINISCREEN
RES_ADD_IMG(IMAGE_PICVIEW_TIME_BG, "\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_TIME_BG.png", IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH, 0)
RES_ADD_IMG(IMAGE_PICVIEW_TITLE_OSD_BG, "\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_OSD_BG.png", IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH, 0)
#endif

//[[define anim infomation
//]]define anim infomation

#if 1
//[[define string infomation
//RES_ADD_STRING(TXT_PICVIEW_SHORT,"Pictures")    //case3: defined but not used
//RES_ADD_STRING(TXT_PICVIEW_NO_PIC,"No picture")    //case3: defined but not used
//RES_ADD_STRING(TXT_PICVIEW_PREVIEW,"Preview")    //case3: defined but not used
#if defined ( PIC_VIEWER_SUPPORT )
#ifndef MMI_PICVIEW_MINI_SUPPORT
RES_ADD_STRING(TXT_PICVIEW_CHANGE_FOLDER,"Change folder")
#endif
#endif
//RES_ADD_STRING(TXT_PICVIEW_SEND,"Send")
//RES_ADD_STRING(TXT_PICVIEW_WALLPAPER,"Wallpaper")          //replaced by common ID TXT_COMMON_SETAS_WALLPAPER
//RES_ADD_STRING(TXT_PICVIEW_ZOOM,"Zoom")    //replaced by common ID TXT_ZOOM
//RES_ADD_STRING(TXT_PICVIEW_MARK,"Mark")  //replaced by common ID STXT_MARK
//RES_ADD_STRING(TXT_PICVIEW_DELETE,"Delete")        //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_PICVIEW_RENAME,"Rename")  //replaced by common ID TXT_COMMON_RENAME
//RES_ADD_STRING(TXT_PICVIEW_DETAIL,"Detail")    //replaced by common ID STXT_DETAIL
//RES_ADD_STRING(TXT_PICVIEW_MMS,"MMS") //replaced by common ID TXT_MMS
//RES_ADD_STRING(TXT_PICVIEW_BT,"Blue tooth")        //replaced by common ID TXT_BLUETOOTH
#ifdef SNS_SUPPORT 
//RES_ADD_STRING(TXT_PICVIEW_TO_SNS,"Share to Sinaweibo")    //case3: defined but not used
#endif
//RES_ADD_STRING(TXT_PICVIEW_MARK_CANCEL,"Cancel mark")     //replaced by common ID TXT_CANCEL_MARK
//RES_ADD_STRING(TXT_PICVIEW_MARK_ALL,"Mark all")  //replaced by common ID TXT_MARK_ALL
//RES_ADD_STRING(TXT_PICVIEW_MARK_ALL_CANCEL,"Cancel all mark")      //replaced by common ID TXT_CANCEL_MARK_ALL
#if defined ( PIC_VIEWER_SUPPORT ) 
RES_ADD_STRING(TXT_PICVIEW_SLIDE_PREVIEW,"Slide play")
#ifndef MMI_RES_LOW_COST
RES_ADD_STRING(TXT_PICVIEW_SLIDE_SET,"Slide setting")
//RES_ADD_STRING(TXT_PICVIEW_PLAY,"Play")    //case3: defined but not used
RES_ADD_STRING(TXT_PICVIEW_VIEW,"View")
#endif
//RES_ADD_STRING(TXT_PICVIEW_VIEW_LIST,"List")     //replaced by common ID TXT_COMMON_LIST
RES_ADD_STRING(TXT_PICVIEW_VIEW_ICONLIST,"Thumbnail")
//RES_ADD_STRING(TXT_PICVIEW_EFFECT,"Select effect")    //replaced by common ID TXT_EFFECT
//RES_ADD_STRING(TXT_PICVIEW_EFFECT_NONE,"None")    //replaced by common ID TXT_NONE
#ifndef MMI_RES_LOW_COST
RES_ADD_STRING(TXT_PICVIEW_EFFECT_ENLARGE,"Box enlarge")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_GRID,"Grid extend")
//RES_ADD_STRING(TXT_PICVIEW_EFFECT_WHIRL,"Whirl extend")    //case3: defined but not used
RES_ADD_STRING(TXT_PICVIEW_EFFECT_RIGHTWARD,"Rightward extend")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_LEFTWARD,"Leftward extend")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_UPWARD,"Upward extend")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_DOWNWARD,"Downward extend")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_ORDER,"Order effect")
#endif
RES_ADD_STRING(TXT_PICVIEW_NOPHOTO,"No Photo!")
#if (!defined MMI_RES_LOW_COST||defined SLIDESHOW_WALLPAPER_SUPPORT)
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME,"Slide time")
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_16S,"16s")
#endif
#endif
#ifdef EFFECT_RIPPLE_SUPPORT  
RES_ADD_STRING(TXT_PICVIEW_EFFECT_RIPPLE,"Ripple effect")
#endif
#ifdef SLIDESHOW_WALLPAPER_SUPPORT
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_4S,"4s")//replaced by common ID TXT_COMM_2_SECONDS
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_6S,"6s")  //replaced by common ID TXT_COMM_3_SECONDS
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_8S,"8s")  //replaced by common ID TXT_COMM_6_SECONDS
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_10S,"10s") //replaced by common ID TXT_COMM_10_SECONDS
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_20S,"20s")  //replaced by common ID TXT_COMM_20_SECONDS
#endif
//RES_ADD_STRING(TXT_PICVIEW_FILE_NAME,"File name:")  //replaced by common ID TXT_INPUT_FILE_NAME
//RES_ADD_STRING(TXT_PICVIEW_DATE,"Date:")  //replaced by common ID TXT_COMMON_DATE
//RES_ADD_STRING(TXT_PICVIEW_TIME,"Time:")  //replaced by common ID TXT_COMMON_TIME
//RES_ADD_STRING(TXT_PICVIEW_SIZE,"Size:")  //replaced by common ID TXT_DETAIL_SIZE
//RES_ADD_STRING(TXT_PICVIEW_LOCATION,"Location:")    //replaced by common ID TXT_LOCATION   
//RES_ADD_STRING(TXT_PICVIEW_RESOLUTION,"Resolution:")  //replaced by common ID TXT_COMM_RESOLUTION
//RES_ADD_STRING(TXT_PICVIEW_FOLDER_NAME,"Folder name:")    //case3: defined but not used

#ifdef PIC_PREVIEW_U200_SUPPORT
RES_ADD_STRING(TXT_PICVIEW_VIEW_SETTING,"View setting")
//RES_ADD_STRING(TXT_PICVIEW_MMS_SEND,"Send by MMS")    //case3: defined but not used
//RES_ADD_STRING(TXT_PICVIEW_BT_SEND,"Send by BT")    //case3: defined but not used
#endif
RES_ADD_STRING(TXT_DC_MY_PICTURE,"My picture")

//RES_ADD_STRING(TXT_ZERO_SIZE_FILE_ALARM,"The size of this file is 0 !")
//RES_ADD_STRING(TXT_PICVIEW_TAKE_PHOTO,"Take Photo")      //replaced by common ID TXT_COMMON_CAPTURE
#if defined ( PIC_VIEWER_SUPPORT ) 
RES_ADD_STRING(TXT_PICVIEW_SHARE,"Share")
#ifdef MMIPB_ADD_EXIST_CONTACT_SUPPORT
RES_ADD_STRING(TXT_PICVIEW_PB,"Set as Phone Book icon")
#endif
#if defined (TOUCH_GESTURE_ENABLE) && defined(PICVIEW_F_VIEW_ZOOM)
RES_ADD_STRING(TXT_PICVIEW_ZOOM_INMAX,"Zoom in to the max!")
RES_ADD_STRING(TXT_PICVIEW_ZOOM_OUTMIN,"Zoom out to the min!")
#endif
#endif
//]]define string infomation
#ifdef MMI_GUI_STYLE_MINISCREEN
RES_ADD_STRING(TXT_PICVIEW_TITLE,"My Photos")
#endif
#endif

//[[define data infomation
//]]define data infomation
RES_ADD_STRING(TXT_GALLERY_PAUSE_BUTTON, "Pause")
RES_ADD_STRING(TXT_GALLERY_PLAY_BUTTON, "Play")
RES_ADD_STRING(TXT_GALLERY_DEL_BUTTON, "Delete")
RES_ADD_STRING(TXT_GALLERY_DELWIN_TITLE, "Delete?")
RES_ADD_STRING(TXT_GALLERY_NO_FILE, "No Photos or Videos")
RES_ADD_STRING(TXT_GALLERY, "Gallery")
RES_ADD_STRING(TXT_GALLERY_CANCEL, "Cancel")
RES_ADD_STRING(TXT_GALLERY_NO_PHOTOS, "No Photos")

RES_ADD_IMG(res_gallery_pic_button_bg,"\\MMI_RES_##\\IMAG\\res_gallery_pic_button_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_vp_button_bg,"\\MMI_RES_##\\IMAG\\res_gallery_vp_button_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_blank,"\\MMI_RES_##\\IMAG\\res_gallery_blank.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_ic_delete,"\\MMI_RES_##\\IMAG\\res_gallery_ic_delete.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_ic_cancel,"\\MMI_RES_##\\IMAG\\res_gallery_ic_cancel.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined( ADULT_WATCH_SUPPORT) 
RES_ADD_STRING(TXT_GALLERY_DELETED, "Deleted")
RES_ADD_IMG(res_aw_gallery_ic_down,"\\MMI_RES_##\\IMAG\\res_aw_gallery_ic_down.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_aw_gallery_ic_up,"\\MMI_RES_##\\IMAG\\res_aw_gallery_ic_up.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_ic_play,"\\MMI_RES_##\\IMAG\\res_aw_gallery_ic_play.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_ic_pause,"\\MMI_RES_##\\IMAG\\res_aw_gallery_ic_pause.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
#if defined(SCREEN_SHAPE_CIRCULAR)
RES_ADD_IMG(res_gallery_ic_play,"\\MMI_RES_##\\IMAG\\res_gallery_ic_play.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_ic_pause,"\\MMI_RES_##\\IMAG\\res_gallery_ic_pause.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_ic_confirm,"\\MMI_RES_##\\IMAG\\res_gallery_ic_confirm.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_ic_option,"\\MMI_RES_##\\IMAG\\res_gallery_option.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_gallery_mark_delete,"\\MMI_RES_##\\IMAG\\res_gallery_mark_delete.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#if defined(BAIDU_DRIVE_SUPPORT)
RES_ADD_IMG(res_aw_gallery_ic_cloud , "\\MMI_RES_##\\IMAG\\res_aw_gallery_ic_cloud.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

//#ifdef ZTE_WATCH
RES_ADD_IMG(res_zte_gallery_back, "\\MMI_RES_##\\IMAG\\res_gallery_back.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_zte_gallery_set, "\\MMI_RES_##\\IMAG\\res_gallery_set.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_zte_gallery_del, "\\MMI_RES_##\\IMAG\\res_gallery_del.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_zte_gallery_can, "\\MMI_RES_##\\IMAG\\res_gallery_can.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_zte_gallery_none, "\\MMI_RES_##\\IMAG\\res_gallery_none.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_zte_gallery_sel, "\\MMI_RES_##\\IMAG\\res_gallery_sel.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(res_zte_gallery_unsel, "\\MMI_RES_##\\IMAG\\res_gallery_unsel.png",IMG_CMP_PNG_ARGB_RLE,0)
//#endif
