
//[[define image infomation
//RES_ADD_IMG(IMAGE_MYDOC_MOVIE_SD_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MYDOC_MOVIE_SD_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_MYDOC_MOVIE_UDISK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MYDOC_MOVIE_UDISK_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_MYDOC_MUSIC_SD_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MYDOC_MUSIC_SD_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_MYDOC_MUSIC_UDISK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MYDOC_MUSIC_UDISK_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_MYDOC_PIC_SD_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MYDOC_PIC_SD_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
// RES_ADD_IMG(IMAGE_MYDOC_PIC_UDISK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_MYDOC_PIC_UDISK_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)

#ifdef ATV_SUPPORT
#ifdef MMI_ATV_MINI_SUPPORT  //6530_MINI
RES_ADD_IMG(IMAGE_ATV_BTN_BG,"\\MMI_RES_##\\IMAG\\IMAGE_ATV_BTN_BG.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
#endif
#endif


RES_ADD_IMG(IMAGE_COMMON_BTN_BG,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_BG.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
#ifdef TOUCH_PANEL_SUPPORT
RES_ADD_IMG(IMAGE_COMMON_BTN_EQ,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_EQ_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_COMMON_BTN_EQ_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_EQ_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG(IMAGE_COMMON_BTN_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_FULLSCREEN_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_FULLSCREEN_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_FULLSCREEN,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_FULLSCREEN_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_COMMON_BTN_FULLSCREEN_OFF_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_FULLSCREEN_OFF_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_FULLSCREEN_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_FULLSCREEN_OFF_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_LIST,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_LIST_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
///////RES_ADD_IMG(IMAGE_COMMON_BTN_LIST_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_LIST_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
//////RES_ADD_IMG(IMAGE_COMMON_BTN_OPTION,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_OPTION_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_COMMON_BTN_OPTION_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_OPTION_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG(IMAGE_COMMON_BTN_PRESS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_TITLE_BTN_PRESS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_TITLE_BTN_PRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_REPEAT_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_REPEAT_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_REPEAT_OFF_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_REPEAT_OFF_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_RECORD,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_RECORD_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
//////RES_ADD_IMG(IMAGE_COMMON_RECORD_TIP,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_RECORD_TIP.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#ifdef RECORD_SUPPORT
RES_ADD_IMG(IMAGE_COMMON_RECORD_BG,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_RECORD_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
//////RES_ADD_IMG(IMAGE_COMMON_BTN_RETURN,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_RETURN_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG(IMAGE_COMMON_BTN_SHUFFLE_OFF_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_SHUFFLE_OFF_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_SHUFFLE_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_SHUFFLE_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
//////RES_ADD_IMG(IMAGE_COMMON_MODE_BTN_PRESS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_MODE_BTN_PRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_MODE_BTN_BG,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_MODE_BTN_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_PLAYER_BTN_VOL,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_VOL_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_PLAYER_BTN_VOL_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_VOL_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_PLAYER_BTN_VOL_MUTE,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_VOL_MUTE_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_PLAYER_BTN_VOL_MUTE_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_VOL_MUTE_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_LIST_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_LIST_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAGE_COMMON_PLAYER_BTN_VOL_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_VOL_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_PLAYER_BTN_VOL_MUTE_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_VOL_MUTE_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_PROCESSBAR_BG,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_PROCESSBAR_BG.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMG_DC_SWITCH_SENSOR,"\\MMI_RES_##\\IMAG\\sensor\\IMG_DC_SWITCH_SENSOR.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_SWITCH_SENSOR_FOCUS,"\\MMI_RES_##\\IMAG\\sensor\\IMG_DC_SWITCH_SENSOR_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

#endif
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG(IMAGE_COMMON_BTN_LIST_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_LIST_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_COMMON_BTN_OPTION,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_OPTION_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_COMMON_RECORD_TIP,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_RECORD_TIP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_RETURN,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_RETURN_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifndef MMI_RES_LOW_COST 
RES_ADD_IMG(IMAGE_COMMON_MODE_BTN_PRESS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_MODE_BTN_PRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_COMMON_BTN_NEXT,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_NEXT_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_NEXT_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_NEXT_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_PAUSE,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PAUSE_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_PAUSE_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PAUSE_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_PLAY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PLAY_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_PLAY_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PLAY_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_PREV,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PREV_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_PREV_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PREV_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_REPEAT_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_REPEAT_OFF_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_REPEAT_ON,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_REPEAT_ON_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_COMMON_BTN_REPEAT_ONE_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_REPEAT_ONE_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_REPEAT_ONE,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_REPEAT_ONE_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef TOUCHPANEL_TYPE
RES_ADD_IMG(IMAGE_COMMON_BTN_RECORD_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_RECORD_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//RES_ADD_IMG(IMAGE_COMMON_RECORD_PAUSE_TIP,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_RECORD_PAUSE_TIP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_SHUFFLE_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_SHUFFLE_OFF_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_SHUFFLE_ON,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_SHUFFLE_ON_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_STOP,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_STOP_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_STOP_GREY,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_STOP_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_COMMON_MODE_BTN_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_MODE_BTN_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_PLAYER_PROCESS_GROOVE,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_PLAYER_PROCESS_GROOVE.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_COMMON_PLAYER_PROCESS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_PLAYER_PROCESS.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_COMMON_PLAYER_PROCESS_SLIDE,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_PLAYER_PROCESS_SLIDE.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined(MAINLCD_SIZE_320X480) || (defined(MMI_RES_LOW_COST) && !defined(LOW_MEMORY_SUPPORT_16X16))
RES_ADD_IMG(IMAGE_COMMON_PROCESS_GROOVE_1,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_PROCESS_GROOVE_1.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_COMMON_PROCESS_GROOVE_1,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_PROCESS_GROOVE_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

//#ifdef MMI_PDA_SUPPORT
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG(IMAGE_COMMON_BTN_PREV_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PREV_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_PLAY_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PLAY_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_PAUSE_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_PAUSE_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_STOP_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_STOP_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_NEXT_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_NEXT_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_REPEAT_ON_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_REPEAT_ON_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_REPEAT_OFF_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_REPEAT_OFF_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_REPEAT_ONE_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_REPEAT_ONE_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_SHUFFLE_ON_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_SHUFFLE_ON_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_SHUFFLE_OFF_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_SHUFFLE_OFF_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef TOUCH_PANEL_SUPPORT
RES_ADD_IMG(IMAGE_COMMON_BTN_RECORD_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_RECORD_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_FULLSCREEN_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_FULLSCREEN_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_FULLSCREEN_OFF_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_FULLSCREEN_OFF_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_OPTION_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_OPTION_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_BTN_RETURN_FOCUS,"\\MMI_RES_##\\IMAG\\IMAGE_MULTIM_BTN_RETURN_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//Frame
#ifdef CAMERA_FRAME_SUPPORT        
RES_ADD_IMG(IMAGE_COMMON_FRAME_01,"\\\\MMI_RES_##\\IMAG\\Frame\\IMAGE_COMMON_FRAME_01.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_FRAME_02,"\\\\MMI_RES_##\\IMAG\\Frame\\IMAGE_COMMON_FRAME_02.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_FRAME_03,"\\\\MMI_RES_##\\IMAG\\Frame\\IMAGE_COMMON_FRAME_03.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_COMMON_FRAME_04,"\\\\MMI_RES_##\\IMAG\\Frame\\IMAGE_COMMON_FRAME_04.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

//camera pda
#if defined(MMIDC_DESKTOP_PDA)
#if defined(MMIDC_F_PDA_BIT_16)
    RES_ADD_IMG(IMG_SEEKBAR_SCALE,"\\MMI_RES_##\\IMAG\\seekbar\\IMG_SEEKBAR_SCALE.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_BG,"\\MMI_RES_##\\IMAG\\seekbar\\IMG_SEEKBAR_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_FRAME,"\\MMI_RES_##\\IMAG\\seekbar\\IMG_SEEKBAR_FRAME.bmp",IMG_CMP_BMP_16_565_RLE,0)   
#else
    RES_ADD_IMG(IMG_SEEKBAR_SCALE,"\\MMI_RES_##\\IMAG\\seekbar\\IMG_SEEKBAR_SCALE.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_MARK,"\\MMI_RES_##\\IMAG\\seekbar\\IMG_SEEKBAR_MARK.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_BG,"\\MMI_RES_##\\IMAG\\seekbar\\IMG_SEEKBAR_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_FRAME,"\\MMI_RES_##\\IMAG\\seekbar\\IMG_SEEKBAR_FRAME.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

// 2 sensors
RES_ADD_STRING(TXT_SWITCH_SENSOR,"Switch sensor")
RES_ADD_STRING(TXT_PREPOSITIVE_SENSOR,"Prepositive sensor")
RES_ADD_STRING(TXT_POSTPOSITIVE_SENSOR,"Postpositive sensor")


// end 2 sensors


//]]define image infomation

//[[define image tag infomation
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_BG,"IMAGE_COMMON_BTN_BG")   
#ifdef TOUCH_PANEL_SUPPORT
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_EQ,"IMAGE_COMMON_BTN_EQ")  

RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_EQ_GREY,"IMAGE_COMMON_BTN_EQ_GREY")  
#endif
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_FOCUS,"IMAGE_COMMON_BTN_FOCUS")  
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_FULLSCREEN_GRAY,"IMAGE_COMMON_BTN_FULLSCREEN_GRAY")  
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_FULLSCREEN,"IMAGE_COMMON_BTN_FULLSCREEN")   
//RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_FULLSCREEN_OFF_GRAY,"IMAGE_COMMON_BTN_FULLSCREEN_OFF_GRAY")  
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_FULLSCREEN_OFF,"IMAGE_COMMON_BTN_FULLSCREEN_OFF")   
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_LIST,"IMAGE_COMMON_BTN_LIST")   
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_OPTION_GREY,"IMAGE_COMMON_BTN_OPTION_GREY")
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_LIST_GREY,"IMAGE_COMMON_BTN_LIST_GREY") 
#endif 
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_NEXT,"IMAGE_COMMON_BTN_NEXT")      
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_NEXT_GREY,"IMAGE_COMMON_BTN_NEXT_GREY") 
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_OPTION,"IMAGE_COMMON_BTN_OPTION")    
  
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PAUSE,"IMAGE_COMMON_BTN_PAUSE")      
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PAUSE_GREY,"IMAGE_COMMON_BTN_PAUSE_GREY") 
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PLAY,"IMAGE_COMMON_BTN_PLAY")       
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PLAY_GREY,"IMAGE_COMMON_BTN_PLAY_GREY")  
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PRESS,"IMAGE_COMMON_BTN_PRESS")   
RES_ADD_IMG_TAG(IMAGE_COMMON_TITLE_BTN_PRESS,"IMAGE_COMMON_TITLE_BTN_PRESS") 
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_REPEAT_GREY,"IMAGE_COMMON_BTN_REPEAT_GREY") 
#endif
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PREV,"IMAGE_COMMON_BTN_PREV")        
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PREV_GREY,"IMAGE_COMMON_BTN_PREV_GREY")   

RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_REPEAT_OFF,"IMAGE_COMMON_BTN_REPEAT_OFF")  
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_REPEAT_ON,"IMAGE_COMMON_BTN_REPEAT_ON")   
//RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_REPEAT_ONE_GREY,"IMAGE_COMMON_BTN_REPEAT_ONE_GREY")  
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_REPEAT_ONE,"IMAGE_COMMON_BTN_REPEAT_ONE")
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_RECORD,"IMAGE_COMMON_BTN_RECORD")  
#endif
#ifdef RECORD_SUPPORT
RES_ADD_IMG_TAG(IMAGE_COMMON_RECORD_BG,"IMAGE_COMMON_RECORD_BG")
#endif
#ifdef TOUCHPANEL_TYPE
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_RECORD_GREY,"IMAGE_COMMON_BTN_RECORD_GREY")
#endif
RES_ADD_IMG_TAG(IMAGE_COMMON_RECORD_TIP,"IMAGE_COMMON_RECORD_TIP")  
//RES_ADD_IMG_TAG(IMAGE_COMMON_RECORD_PAUSE_TIP,"IMAGE_COMMON_RECORD_PAUSE_TIP")


RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_RETURN,"IMAGE_COMMON_BTN_RETURN")     
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_SHUFFLE_GREY,"IMAGE_COMMON_BTN_SHUFFLE_GREY") 
RES_ADD_IMG_TAG(IMAGE_COMMON_PLAYER_BTN_VOL_GREY,"IMAGE_COMMON_PLAYER_BTN_VOL_GREY")
RES_ADD_IMG_TAG(IMAGE_COMMON_PLAYER_BTN_VOL_MUTE_GREY,"IMAGE_COMMON_PLAYER_BTN_VOL_MUTE_GREY")
RES_ADD_IMG_TAG(IMAGE_COMMON_MODE_BTN_BG,"IMAGE_COMMON_MODE_BTN_BG")
RES_ADD_IMG_TAG(IMAGE_COMMON_PLAYER_BTN_VOL,"IMAGE_COMMON_PLAYER_BTN_VOL") 
RES_ADD_IMG_TAG(IMAGE_COMMON_PLAYER_BTN_VOL_MUTE,"IMAGE_COMMON_PLAYER_BTN_VOL_MUTE")
#endif
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_SHUFFLE_OFF,"IMAGE_COMMON_BTN_SHUFFLE_OFF")  
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_SHUFFLE_ON,"IMAGE_COMMON_BTN_SHUFFLE_ON")   
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_STOP,"IMAGE_COMMON_BTN_STOP")       
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_STOP_GREY,"IMAGE_COMMON_BTN_STOP_GREY")  
//RES_ADD_IMG_TAG(IMAGE_COMMON_MODE_BTN_FOCUS,"IMAGE_COMMON_MODE_BTN_FOCUS") 
#ifndef MMI_RES_LOW_COST  
RES_ADD_IMG_TAG(IMAGE_COMMON_MODE_BTN_PRESS,"IMAGE_COMMON_MODE_BTN_PRESS")
#endif   
      
  
RES_ADD_IMG_TAG(IMAGE_COMMON_PLAYER_PROCESS_GROOVE,"IMAGE_COMMON_PLAYER_PROCESS_GROOVE")     
RES_ADD_IMG_TAG(IMAGE_COMMON_PLAYER_PROCESS,"IMAGE_COMMON_PLAYER_PROCESS")      
RES_ADD_IMG_TAG(IMAGE_COMMON_PLAYER_PROCESS_SLIDE,"IMAGE_COMMON_PLAYER_PROCESS_SLIDE") 
#ifdef MAINLCD_SIZE_320X480
RES_ADD_IMG_TAG(IMAGE_COMMON_PROCESS_GROOVE_1,"IMAGE_COMMON_PROCESS_GROOVE_1")     
#else
RES_ADD_IMG_TAG(IMAGE_COMMON_PROCESS_GROOVE_1,"IMAGE_COMMON_PROCESS_GROOVE_1")     
#endif  

#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_LIST_FOCUS,"IMAGE_COMMON_BTN_LIST_FOCUS")  
RES_ADD_IMG_TAG(IMAGE_COMMON_PLAYER_BTN_VOL_FOCUS,"IMAGE_COMMON_PLAYER_BTN_VOL_FOCUS")   
RES_ADD_IMG_TAG(IMAGE_COMMON_PLAYER_BTN_VOL_MUTE_FOCUS,"IMAGE_COMMON_PLAYER_BTN_VOL_MUTE_FOCUS")
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PREV_FOCUS,"IMAGE_COMMON_BTN_PREV_FOCUS")  
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PLAY_FOCUS,"IMAGE_COMMON_BTN_PLAY_FOCUS")
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_PAUSE_FOCUS,"IMAGE_COMMON_BTN_PAUSE_FOCUS")
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_STOP_FOCUS,"IMAGE_COMMON_BTN_STOP_FOCUS")     
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_NEXT_FOCUS,"IMAGE_COMMON_BTN_NEXT_FOCUS")
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_REPEAT_ON_FOCUS,"IMAGE_COMMON_BTN_REPEAT_ON_FOCUS")
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_REPEAT_OFF_FOCUS,"IMAGE_COMMON_BTN_REPEAT_OFF_FOCUS")
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_REPEAT_ONE_FOCUS,"IMAGE_COMMON_BTN_REPEAT_ONE_FOCUS")
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_SHUFFLE_ON_FOCUS,"IMAGE_COMMON_BTN_SHUFFLE_ON_FOCUS")
RES_ADD_IMG_TAG(IMAGE_COMMON_BTN_SHUFFLE_OFF_FOCUS,"IMAGE_COMMON_BTN_SHUFFLE_OFF_FOCUS")     
#endif
//]]define image tag infomation

//[[define anim infomation
//]]define anim infomation


//[[define string infomation
#if 1
//RES_ADD_STRING(TXT_MULTIM_DELETE,"Delete")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_SEND,"Send")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_DETAIL,"Details")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_WALLPAPER,"Set as wallpaper")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_RENAME,"Rename")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_DELETEALL,"Delete all")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_SAVE,"Save")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_PICTURE_OPTION,"Picture option")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_MUSIC_OPTION,"Ringtone option")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_DOWNLOAD_SAVEPATH_MUSIC,"Ringtone")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_DOWNLOAD_SAVEPATH_PICTURE,"Picture")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_COPY,"Copy")    //case3£ºdefined but not used    
//RES_ADD_STRING(TXT_MULTIM_COPY_ALL,"Copy all")    //case3£ºdefined but not used    
//RES_ADD_STRING(TXT_MULTIM_SAVE_DISK,"Save disk")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_COPY_ALL_UDISK_TO_SDCARD,"From udisk to sdcard")    //case3£ºdefined but not used    
//RES_ADD_STRING(TXT_MULTIM_COPY_ALL_SDCARD_TO_UDISK,"From sdcard to udisk")    //case3£ºdefined but not used    
//RES_ADD_STRING(TXT_MULTIM_NOPICTURE,"No picture")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_NOMUSIC,"No ring")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_COMPLETED,"Done")    //case3£ºdefined but not used       
//RES_ADD_STRING(TXT_MULTIM_NAMEREPEATED,"File name repeated")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_NAMEINVALID,"File name invalid")    //replaced by common ID TXT_DC_NAMEINVALID
//RES_ADD_STRING(TXT_MULTIM_MEMORYFULL,"Memory is full")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_NUM_LIMITED,"Number is full")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_PHOTO,"Photo:")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_PICTURE,"Picture:")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_RING,"Ring:")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_MP3_MEMORY,"Mp3:")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_FM,"FM radio")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_VIDEO,"Video:")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_RECORD,"Record:")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_RECORD_INCALL,"Leav:")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_TRUE_MPEG4_MEMORY,"Media player:")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_SURE,"Sure")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_PROMPT_FAIL,"Fail")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_PROMPT_REPEAT,"Repeat")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_DETAIL_MEMORY_SIZE,"Size:")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_DETAIL_FORMAT,"Format:")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_DETAIL_TYPE,"Type:")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_FILESYSTEM_ERROR,"Open file fail")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_FINISHED,"Finished")    //case3£ºdefined but not used
RES_ADD_STRING(TXT_MULTIM_READ_FAIL,"Read file fail")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_NO_EXIST,"No exist")    //replaced by common ID TXT_COM_FILE_NO_EXIST
//RES_ADD_STRING(TXT_MULTIM_HAND_EXISTED,"Hand existed")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_NO_FILE,"Folder is empty")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_COPY_ERROR_CONTINUE,"Error!GO on?")    //case3£ºdefined but not used    
//RES_ADD_STRING(TXT_MULTIM_COPY_REPEAT_CONTINUE,"File repeat!Go on?")    //case3£ºdefined but not used    
//RES_ADD_STRING(TXT_MULTIM_TOO_MANY_FILES,"List is full")    //case3£ºdefined but not used 
RES_ADD_STRING(TXT_MULTIM_PICTOO_LARGE,"Pic too large")
//RES_ADD_STRING(TXT_MULTIM_INPUTNAME,"File name")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_DETAIL_PIXEL,"Resolution:")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_DETAIL_SIZE,"Size:")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_DETAIL_DATE,"Date:")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_DETAIL_LOCATION,"Location:")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_NO_SUPPORT,"Not support")      //replaced by common ID TXT_COMMON_NO_SUPPORT
//RES_ADD_STRING(TXT_MULTIM_PLAY,"Play")  //replaced by common ID TXT_COMMON_PLAY
//RES_ADD_STRING(TXT_MULTIM_STOP,"Stop")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_EMPTY_CONTENT,"Empty")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_INVALID_PIC,"Invalid picture")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_INVALID_AUDIO,"Invalid audio")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_OPERAT_INTERRUPT,"Operation interrupt")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_COPY_REPEAT_REPLACE,"File repeat! Replace?")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_COPY_REPLACE,"Replace?")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_MULTIM_NO_MOVIE,"No movie")    //case3£ºdefined but not used 
//RES_ADD_STRING(TXT_MULTIM_NO_WAV_RECORD,"No record")    //case3£ºdefined but not used 
#endif
//]]define string infomation


//[[define data infomation
//]]define data infomation
