

//[[define image infomation
RES_ADD_IMG(IMG_UZONE_ICON_MP3,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_ICON_AP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_ICON_FM,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_ICON_FM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_ICON_IMAGEVIEWER,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_ICON_PICTURE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_ICON_VIDEOPLAYER,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_ICON_VP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_ICON_ATV,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_ICON_ATV.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_ICON_CAMERA,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_ICON_CAMERA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_ICON_RECORD,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_ICON_RECORD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_ICON_KINGMOVIE,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_ICON_KINGMOVIE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_ICON_EBOOK,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_ICON_EBOOK.png",IMG_CMP_PNG_ARGB_RLE,0)


RES_ADD_IMG(IMG_UZONE_GLASS_BG,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_BG.jpg",IMG_CMP_JPG_SCI,0)
RES_ADD_IMG(IMG_UZONE_GLASS,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_GLASS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_GLASS_FOCUS,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_GLASS_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR1_1,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR1_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR1_2,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR1_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR1_3,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR1_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR1_4,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR1_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR1_5,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR1_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR2_1,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR2_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR2_2,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR2_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR2_3,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR2_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR2_4,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR2_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_UZONE_STAR2_5,"\\MMI_RES_##\\IMAG\\IMAG_UZONE_STAR2_5.png",IMG_CMP_PNG_ARGB_RLE,0)

//]]define image infomation



//[[define anim infomation
//]]define anim infomation


//[[define string infomation
RES_ADD_STRING(STXT_UZONE_MP3,"AudioPlayer")
RES_ADD_STRING(STXT_UZONE_FM,"FM")
//RES_ADD_STRING(STXT_UZONE_IMAGEVIEWER,"ImageViewer") //replaced by TXT_COMMON_PIC
//RES_ADD_STRING(STXT_UZONE_VIDEOPLAYER,"VideoPlayer")  //replaced by common ID TXT_COMMON_VIDEOPLAYER
RES_ADD_STRING(STXT_UZONE_ATV,"ATV")
//RES_ADD_STRING(STXT_UZONE_CAMERA,"Camera")    //replaced by common ID TXT_ENTERTAIMENT_CAMERA
RES_ADD_STRING(STXT_UZONE_RECORD,"Record")
RES_ADD_STRING(STXT_UZONE_KINGMOVIE,"KingMovie")
//RES_ADD_STRING(STXT_UZONE_EBOOK,"Ebook")  //replaced by common ID TXT_COMM_EBOOK
RES_ADD_STRING(STXT_UZONE_OPEN_FAIL,"Open Uzone fail")

//]]define string infomation


//[[define data infomation
//]]define data infomation

