//[[define image infomation
//RES_ADD_IMG(IMAGE_DCD_DEFAULT_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_DEFAULT_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_UPDATING,"\\MMI_RES_##\\ANIM\\IMAGE_DCD_UPDATING.gif",IMG_CMP_GIF_SCI,0)
//RES_ADD_IMG(IMAGE_DCD_IDLE_TAB_BGD_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_IDLE_TAB_BGD_IMAGE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_IDLE_LIST_BGD_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_IDLE_LIST_BGD_IMAGE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_TAB_CUR_BGD_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_TAB_CUR_BGD_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_TAB_FOCUS_BGD_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_TAB_FOCUS_BGD_IMAGE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_NOT_READ_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_NOT_READ_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image infomation

//[[define string infomation
RES_ADD_STRING(TXT_CS_SERVICE_GUIDE,"service guide")
RES_ADD_STRING(TXT_CS_E100,"e100")
RES_ADD_STRING(TXT_CS_HOT_LINE,"e100")
RES_ADD_STRING(TXT_CS_SMS_OFFICE,"e100")
RES_ADD_STRING(TXT_CS_ABOUT_E100,"e100")
RES_ADD_STRING(TXT_CS_CUSTMER_MANAGER,"Update Channel")
RES_ADD_STRING(TXT_CS_MY_MONERNET,"Add Channel")
RES_ADD_STRING(TXT_CS_SERVICE_SETTING,"Delete Channel")
RES_ADD_STRING(TXT_CS_SERVICE_HOTLINE,"Help")
RES_ADD_STRING(TXT_CS_MANAGER_NUMBER,"Send by sms")

RES_ADD_STRING(TXT_CS_SERVICE_GUIDE_DETAIL,"guide detail")

RES_ADD_STRING(TXT_CS_ABOUT_E100_DETAIL,"guide detail")

RES_ADD_STRING(TXT_CS_POCKET_BUSINESS_HALL,"Pocket business hall")
//]]define data infomation
