/******************************************************************************
 ** File Name:      oscfg.c                                                   *
 ** Author:         Benjamin.Wang                                             *
 ** DATE:           11/08/2006                                                *
 ** Copyright:      2006 Spreadtrum, Incorporated. All Rights Reserved.       *
 ** Description:    This file defines most of system's static tasks.          *
 ******************************************************************************

 ******************************************************************************
 **                        Edit History                                       *
 ** ------------------------------------------------------------------------- *
 ** DATE           NAME             DESCRIPTION                               *
 ** 11/08/2006     Benjamin.Wang    Create.                                   *
 ******************************************************************************/

/**---------------------------------------------------------------------------*
 **                         Dependencies                                      *
 **---------------------------------------------------------------------------*/
#include "os_api.h"
#include "priority_app.h"
/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef   __cplusplus
    extern   "C" 
    {
#endif

enum
{
    PRI_WRE_KERNEL_TASK_OFFSET			 = 0, 
    PRI_WRE_CRITICAL_TASK_OFFSET		 = 5, 
    PRI_WRE_HIGHEST_TASK_OFFSET			 = 10,
    PRI_WRE_ABOVE_NORMAL_TASK_OFFSET	 = 15,
    PRI_WRE_NORMAL_TASK_OFFSET			 = 20,
    PRI_WRE_BELOW_NORMAL_TASK_OFFSET	 = 25,
    PRI_WRE_LOWEST_TASK_OFFSET			 = 28,
    PRI_WRE_IDLE_TASK_OFFSET			 = 31,
    PRI_MTHREAD_KERNEL_OFFSET			 = 0, 
    PRI_MTHREAD_CRITICAL_OFFSET			 = 10,
    PRI_MTHREAD_HIGHEST_OFFSET			 = 15,
    PRI_MTHREAD_ABOVE_NORMAL_OFFSET		 = 18,
    PRI_MTEKVIDEOENC_TASK_OFFSET		 = 18,
    PRI_MTV_FAKE_TASK_OFFSET			 = 20,
    PRI_MTHREAD_NORMAL_OFFSET			 = 20,
    PRI_HQR_TASK_OFFSET					 = 20,
    PRI_MTHREAD_BELOW_NORMAL_OFFSET		 = 25,
    PRI_MTV_REALTIME_TASK_OFFSET		 = 26,
    PRI_MTV_NORMAL_TASK_OFFSET			 = 28,
    PRI_MTHREAD_LOWEST_OFFSET			 = 28,
    PRI_MV_SOCKET_TASK_OFFSET			 = 28,
    PRI_FTCP_THROUGHUP_TASK_OFFSET		 = 28,
    PRI_AJAVACOMM_TASK_OFFSET			 = 29,
    PRI_MAIL_MAIN_TASK_OFFSET			 = 29,
    PRI_USER_THREAD_TASK_OFFSET			 = 29,
    PRI_MMITTS_TASK_OFFSET				 = 30,
    PRI_JAVA_SIGDISPATCH_OFFSET			 = 30,
    PRI_DM_TASK_OFFSET					 = 30,
    PRI_APP_FILE_TASK_OFFSET			 = 30,
    PRI_APP_IKB_OFFSET                   = 31,
    PRI_MV_TASK_OFFSET					 = 30,
    PRI_ASYN_TASK_OFFSET_PRIORITY_OFFSET = 30,
    PRI_HTTP_TASK_OFFSET				 = 30,
    PRI_INNO_LPM_TASK_OFFSET			 = 30,
    PRI_JAVA_SIGDISPATCH_TASK_OFFSET	 = 30,
    PRI_EMAIL_APP_TASK_OFFSET		 = 30,
    PRI_EBOOK_TASK_OFFSET			 = 31,
    PRI_EBOOK_SEGTAB_TASK_OFFSET	 = 31,
    PRI_MTHREAD_IDLE_OFFSET				 = 31,
    PRI_AJAVAKVE_TASK_OFFSET			 = 31,
    PRI_JVM_TASK_OFFSET					 = 31,
    PRI_MAIL_PARSE_TASK_OFFSET_PRIO_OFFSET = 31,
    PRI_JBED_TASK_OFFSET				 = 31,
    PRI_MODEM_THROUGHUP_TASK_OFFSET		 = 31,
    PRI_GPS_TASK_OFFSET					 = 26,
    PRI_GPS_OS_TASK_OFFSET				 = 28,
    PRI_OCR_TASK_OFFSET					 = 31,
    PRI_MWINSOCK_TASK_OFFSET			 = 26,
    PRI_EXT_VT_MW_TASK_OFFSET		 = 29,
    PRI_MMIJAVA_TASK_HIGH_OFFSET		 = 26,
    PRI_MMIJAVA_TASK_LOW_OFFSET			 = 31,
    PRI_CACL_TASK_OFFSET				 = 30,
    PRI_APP_PB_OFFSET                           =31,
    MAX_APP_PRIORITY_OFFSET              =  MAX_APP_PRI_NUM
};

//Define APP Task
SCI_DEFINE_TASK_PRI(PRI_WRE_KERNEL_TASK					, SCI_APP_PRI(PRI_WRE_KERNEL_TASK_OFFSET		));
SCI_DEFINE_TASK_PRI(PRI_WRE_CRITICAL_TASK				, SCI_APP_PRI(PRI_WRE_CRITICAL_TASK_OFFSET	    ));
SCI_DEFINE_TASK_PRI(PRI_WRE_HIGHEST_TASK				, SCI_APP_PRI(PRI_WRE_HIGHEST_TASK_OFFSET	    ));
SCI_DEFINE_TASK_PRI(PRI_WRE_ABOVE_NORMAL_TASK		    , SCI_APP_PRI(PRI_WRE_ABOVE_NORMAL_TASK_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_WRE_NORMAL_TASK					, SCI_APP_PRI(PRI_WRE_NORMAL_TASK_OFFSET		));
SCI_DEFINE_TASK_PRI(PRI_WRE_BELOW_NORMAL_TASK		    , SCI_APP_PRI(PRI_WRE_BELOW_NORMAL_TASK_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_WRE_LOWEST_TASK					, SCI_APP_PRI(PRI_WRE_LOWEST_TASK_OFFSET		));
SCI_DEFINE_TASK_PRI(PRI_WRE_IDLE_TASK					, SCI_APP_PRI(PRI_WRE_IDLE_TASK_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_MTHREAD_KERNEL					, SCI_APP_PRI(PRI_MTHREAD_KERNEL_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_MTHREAD_CRITICAL				, SCI_APP_PRI(PRI_MTHREAD_CRITICAL_OFFSET	    ));                
SCI_DEFINE_TASK_PRI(PRI_MTHREAD_HIGHEST					, SCI_APP_PRI(PRI_MTHREAD_HIGHEST_OFFSET		));        
SCI_DEFINE_TASK_PRI(PRI_MTHREAD_ABOVE_NORMAL		    , SCI_APP_PRI(PRI_MTHREAD_ABOVE_NORMAL_OFFSET   ));
SCI_DEFINE_TASK_PRI(PRI_MTEKVIDEOENC_TASK				, SCI_APP_PRI(PRI_MTEKVIDEOENC_TASK_OFFSET	    ));
SCI_DEFINE_TASK_PRI(PRI_MTV_FAKE_TASK					, SCI_APP_PRI(PRI_MTV_FAKE_TASK_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_MTHREAD_NORMAL					, SCI_APP_PRI(PRI_MTHREAD_NORMAL_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_HQR_TASK						, SCI_APP_PRI(PRI_HQR_TASK_OFFSET			    ));
SCI_DEFINE_TASK_PRI(PRI_MTHREAD_BELOW_NORMAL		    , SCI_APP_PRI(PRI_MTHREAD_BELOW_NORMAL_OFFSET   ));
SCI_DEFINE_TASK_PRI(PRI_MTV_REALTIME_TASK				, SCI_APP_PRI(PRI_MTV_REALTIME_TASK_OFFSET	    ));
SCI_DEFINE_TASK_PRI(PRI_MTV_NORMAL_TASK					, SCI_APP_PRI(PRI_MTV_NORMAL_TASK_OFFSET		));
SCI_DEFINE_TASK_PRI(PRI_MTHREAD_LOWEST					, SCI_APP_PRI(PRI_MTHREAD_LOWEST_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_MV_SOCKET_TASK					, SCI_APP_PRI(PRI_MV_SOCKET_TASK_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_FTCP_THROUGHUP_TASK			    , SCI_APP_PRI(PRI_FTCP_THROUGHUP_TASK_OFFSET    ));
SCI_DEFINE_TASK_PRI(PRI_AJAVACOMM_TASK					, SCI_APP_PRI(PRI_AJAVACOMM_TASK_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_MAIL_MAIN_TASK					, SCI_APP_PRI(PRI_MAIL_MAIN_TASK_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_USER_THREAD_TASK				, SCI_APP_PRI(PRI_USER_THREAD_TASK_OFFSET	    ));
SCI_DEFINE_TASK_PRI(PRI_MMITTS_TASK						, SCI_APP_PRI(PRI_MMITTS_TASK_OFFSET			));
SCI_DEFINE_TASK_PRI(PRI_JAVA_SIGDISPATCH				, SCI_APP_PRI(PRI_JAVA_SIGDISPATCH_OFFSET	    ));
SCI_DEFINE_TASK_PRI(PRI_DM_TASK							, SCI_APP_PRI(PRI_DM_TASK_OFFSET				));
SCI_DEFINE_TASK_PRI(PRI_APP_FILE_TASK					, SCI_APP_PRI(PRI_APP_FILE_TASK_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_APP_IKB_TASK                    , SCI_APP_PRI(PRI_APP_IKB_OFFSET                ));
SCI_DEFINE_TASK_PRI(PRI_MV_TASK							, SCI_APP_PRI(PRI_MV_TASK_OFFSET				));
SCI_DEFINE_TASK_PRI(PRI_ASYN_TASK_PRIORITY			    , SCI_APP_PRI(PRI_ASYN_TASK_OFFSET_PRIORITY_OFFSET));
SCI_DEFINE_TASK_PRI(PRI_HTTP_TASK						, SCI_APP_PRI(PRI_HTTP_TASK_OFFSET			    ));
SCI_DEFINE_TASK_PRI(PRI_INNO_LPM_TASK					, SCI_APP_PRI(PRI_INNO_LPM_TASK_OFFSET		    ));	 
SCI_DEFINE_TASK_PRI(PRI_JAVA_SIGDISPATCH_TASK		    , SCI_APP_PRI(PRI_JAVA_SIGDISPATCH_TASK_OFFSET  ));
SCI_DEFINE_TASK_PRI(PRI_EMAIL_APP_TASK				, SCI_APP_PRI(PRI_EMAIL_APP_TASK_OFFSET));
SCI_DEFINE_TASK_PRI(PRI_EBOOK_TASK					, SCI_APP_PRI(PRI_EBOOK_TASK_OFFSET	));
SCI_DEFINE_TASK_PRI(PRI_EBOOK_SEGTAB_TASK			, SCI_APP_PRI(PRI_EBOOK_SEGTAB_TASK_OFFSET));	 
SCI_DEFINE_TASK_PRI(PRI_MTHREAD_IDLE					, SCI_APP_PRI(PRI_MTHREAD_IDLE_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_AJAVAKVE_TASK					, SCI_APP_PRI(PRI_AJAVAKVE_TASK_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_JVM_TASK						, SCI_APP_PRI(PRI_JVM_TASK_OFFSET			    ));
SCI_DEFINE_TASK_PRI(PRI_MAIL_PARSE_TASK_PRIO		    , SCI_APP_PRI(PRI_MAIL_PARSE_TASK_OFFSET_PRIO_OFFSET));
SCI_DEFINE_TASK_PRI(PRI_JBED_TASK						, SCI_APP_PRI(PRI_JBED_TASK_OFFSET			    ));
SCI_DEFINE_TASK_PRI(PRI_MODEM_THROUGHUP_TASK		    , SCI_APP_PRI(PRI_MODEM_THROUGHUP_TASK_OFFSET   ));
SCI_DEFINE_TASK_PRI(PRI_GPS_TASK						, SCI_APP_PRI(PRI_GPS_TASK_OFFSET			    ));
SCI_DEFINE_TASK_PRI(PRI_GPS_OS_TASK						, SCI_APP_PRI(PRI_GPS_OS_TASK_OFFSET			));
SCI_DEFINE_TASK_PRI(PRI_OCR_TASK						, SCI_APP_PRI(PRI_OCR_TASK_OFFSET			    ));
SCI_DEFINE_TASK_PRI(PRI_CACL_TASK						, SCI_APP_PRI(PRI_CACL_TASK_OFFSET			    ));
SCI_DEFINE_TASK_PRI(PRI_MWINSOCK_TASK					, SCI_APP_PRI(PRI_MWINSOCK_TASK_OFFSET		    ));
SCI_DEFINE_TASK_PRI(PRI_EXT_VT_MW_TASK				, SCI_APP_PRI(PRI_EXT_VT_MW_TASK_OFFSET));
SCI_DEFINE_TASK_PRI(PRI_MMIJAVA_TASK_HIGH				, SCI_APP_PRI(PRI_MMIJAVA_TASK_HIGH_OFFSET	    ));
SCI_DEFINE_TASK_PRI(PRI_MMIJAVA_TASK_LOW				, SCI_APP_PRI(PRI_MMIJAVA_TASK_LOW_OFFSET	    ));
SCI_DEFINE_TASK_PRI(PRI_APP_PB_TASK                                  , SCI_APP_PRI(PRI_APP_PB_OFFSET ));

/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif 

//End of oscfg.c
