
//[[define image infomation
//]]define image infomation
RES_ADD_IMG(IMAGE_IKB_TAB_BACKUP_SELECT,"\\MMI_RES_##\\IMAG\\IMAGE_IKB_TAB_BACKUP_SELECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_IKB_TAB_BACKUP_RELEASED,"\\MMI_RES_##\\IMAG\\IMAGE_IKB_TAB_BACKUP_RELEASED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_IKB_TAB_RESTORE_RELEASED,"\\MMI_RES_##\\IMAG\\IMAGE_IKB_TAB_RESTORE_RELEASED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_IKB_TAB_RESTORE_SELECT,"\\MMI_RES_##\\IMAG\\IMAGE_IKB_TAB_RESTORE_SELECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_IKB_TAB_SETTING_SELECT,"\\MMI_RES_##\\IMAG\\IMAGE_IKB_TAB_SETTING_SELECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_IKB_TAB_SETTING_RELEASED,"\\MMI_RES_##\\IMAG\\IMAGE_IKB_TAB_SETTING_RELEASED.png",IMG_CMP_PNG_ARGB_RLE,0)


//[[define anim infomation
//]]define anim infomation


//[[define data infomation
//]]define data infomation
