
#ifndef _INC_LOGELPROPERTY_H
#define _INC_LOGELPROPERTY_H



// this is the flay to indicate the time 
#define LOGEL_TIMER_ID      0xFFFF0001
// this is the flay to indicate the layer one
#define LOGEL_LAYERONE_ID   0xFFFF0002
// this is the flay to indicate logel information
#define LOGEL_INFO_ID       0xFFFF0003



//parser
typedef enum
{
//parser
	PROPERTY_VERSION,
	PROPERTY_ENDIAN,
	PROPERTY_ALIGNMENT,
	PROPERTY_MESSAGE_NAME,
	PROPERTY_MESSAGE_ID,
	PROPERTY_TASK_NAME,
	PROPERTY_TASK_ID,
	PROPERTY_TASK_NAME_BY_INDEX,
	PROPERTY_TASK_ID_BY_INDEX,
	PROPERTY_TASK_SIZE,	
	PROPERTY_LAYER1_NAME,
	
	PROPERTY_ENUMID_TO_STRING,
	PROPERTY_STRING_TO_ENUMID,

	PROPERTY_AUTO_SCROLLDOWN,

	PROPERTY_SAVE_FILE_NAME,

	PROPERTY_FILTER_PAGE,
	PROPERTY_CONFIG_PAGE,

	PROPERTY_WORK_MODE,
	PROPERTY_RECORD_MODE,

	PROPERTY_LOGVIEW_ITEM,
	PROPERTY_MESSAGE_SHOWING_COLOR,

	PROPERTY_SPECIAL_WINDOWS,

	PROPERTY_SUPPORT_MESSAGE_TYPE
}ENUM_PROPERTY_ID;

#endif