/*****************************************************************************
** File Name:      mmiwlan_id.h                                              *
** Author:         li.li                                                     *
** Date:           2009/11/18                                                *
** Copyright:      2006 Spreadtrum, Incoporated. All Rights Reserved.        *
** Description:    This file is used to describe wifi manager window         *
******************************************************************************
**                         Important Edit History                            *
** --------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                               *
** 2009/11/18     li.li          Create                                      *
******************************************************************************/

#ifndef _MMIWLAN_ID_H_
#define _MMIWLAN_ID_H_ 

/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
#include "sci_types.h"
#include "os_api.h"
#include "mmk_type.h"
#include "mmi_module.h"

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif

/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/


/**--------------------------------------------------------------------------*
 **                         TYPE AND CONSTANT                                *
 **--------------------------------------------------------------------------*/
 
#define WIN_ID_DEF(win_id)          win_id
 
// window ID
typedef enum
{
    MMIWIFI_WIN_ID_START = (MMI_MODULE_WIFI << 16),

#include "mmiwlan_id.def"

    MMIWIFI_MAX_WIN_ID
}MMIWIFI_WINDOW_ID_E;

#undef WIN_ID_DEF

// control ID
typedef enum
{
    MMIWIFI_CTRL_ID_START = MMIWIFI_MAX_WIN_ID, //(MMI_MODULE_WIFI << 16),
    MMIWIFI_MAIN_CTRL_ID,
    MMIWIFI_STATIC_IP_CTRL_ID,
    MMIWIFI_LIST_CTRL_ID,
    MMIWIFI_MENU_CTRL_ID,
    MMIWIFI_DETAIL_CTRL_ID,
    MMIWIFI_HELP_TEXT_CTRL_ID,
    MMIWIFI_SET_MENU_CTRL_ID,
    MMIWIFI_SET_SSID_CTRL_ID,
    MMIWIFI_SET_NETWORK_STATE_CTRL_ID,
    MMIWIFI_SET_NETWORK_TYPE_CTRL_ID,
    MMIWIFI_SET_AUTH_TYPE_CTRL_ID,
    MMIWIFI_WEPKEY_INDEX_LABEL_CTRL_ID,
    MMIWIFI_WEPKET_BIT_LABEL_CTRL_ID,
    MMIWIFI_WEPKEY_STYLE_LABEL_CTRL_ID,
    MMIWIFI_WEPKEY_LABEL_CTRL_ID,
    MMIWIFI_WEPKEY_DATA_LABEL_CTRL_ID,
    MMIWIFI_WEPKEY_STYLE_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_WEPKEY_BIT_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_WEPKEY_INDEX_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_IP_SET_CTRL_ID,
    MMIWIFI_IP_ADDRESS_CTRL_ID,
    MMIWIFI_GATEWAY_CTRL_ID,
    MMIWIFI_SUBMASK_CTRL_ID,
    MMIWIFI_DNS1_CTRL_ID,
    MMIWIFI_DNS2_CTRL_ID,
    MMIWIFI_WPAAUTH_CTRL_ID,
    MMIWIFI_PRESHARE_KEY_CTRL_ID,
    MMIWIFI_PRESHARE_KEY_INPUT_CTRL_ID,
    MMIWIFI_WPA_EAP_CTRL_ID,
    MMIWIFI_WPA_EAP_TLS_CTRL_ID,
    MMIWIFI_WPA_EAP_TTLS_CTRL_ID,
    MMIWIFI_SET_SAVE_SETTING_CTRL_ID,
    MMIWIFI_WPAEAP_TTLS_PAP_CTRL_ID,
    MMIWIFI_SET_USERNAME_CTRL_ID,
    MMIWIFI_SET_PASSWORD_CTRL_ID,
    MMIWIFI_WPAEAP_TTLS_CHAP_CTRL_ID,
    MMIWIFI_WPAEAP_TTLS_MSCHAP_CTRL_ID,
    MMIWIFI_WPAEAP_TTLS_MSCHAP2_CTRL_ID,
    MMIWIFI_WPA_EAP_PEAP_CTRL_ID,
    MMIWIFI_WPAEAP_PEAP_GTC_CTRL_ID,
    MMIWIFI_WPAEAP_PEAP_MSCHAP2_CTRL_ID,
    MMIWIFI_WPAEAP_LEAP_CTRL_ID,
    MMIWIFI_WPA_EAP_FAST_CTRL_ID,
    MMIWIFI_SET_IP_CTRL_ID,
    MMIWIFI_WEP_BIT_SETTING_CTRL_ID,
    MMIWIFI_WEP_64BIT_DATA_CTRL_ID,
    MMIWIFI_WEP_128BIT_DATA_CTRL_ID,
    MMIWIFI_TLS_LABEL_CTRL_ID,
    MMIWIFI_TLS_PATH_LABEL_CTRL_ID,
    MMIWIFI_FAST_LABEL_CTRL_ID,
    MMIWIFI_FAST_PATH_LABEL_CTRL_ID,
    MMIWIFI_WEPKEY_MODE_LABEL_CTRL_ID,
    MMIWIFI_WEPKEY_BIT_LABEL_CTRL_ID,
    MMIWIFI_WEPKEY_MODE_DROPDOWNLIST_CTRL_ID,
/* BEGIN: Added by George.Liu 01526, 2010/7/23   PN:MergeToMw1029forCustom */
    MMIWIFI_WEP_BIT_SETTING_FORMCTRL_ID,
    MMIWIFI_WEP_64BIT_FORMCTRL_ID,
    MMIWIFI_WEP_128BIT_FORMCTRL_ID,
    MMIWIFI_WPA_EAP_TLS_FORMCTRL_ID,
    MMIWIFI_WPA_EAP_FAST_FORMCTRL_ID,    
/* END:   Added by George.Liu 01526, 2010/7/23   PN:MergeToMw1029forCustom */
    MMIWIFI_WLAN_SETTING_FORMCTRL_ID,
    MMIWIFI_WLAN_LABEL_CTRL_ID,
    MMIWIFI_WLAN_ON_OFF_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_AUTO_CONNECT_LABEL_CTRL_ID,
    MMIWIFI_AUTO_CONNECT_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_SEARCH_WLAN_LABEL_CTRL_ID,
    MMIWIFI_SEARCH_PERIOD_DROPDOWNLIST_CTRL_ID,
    
    MMIWIFI_GPRSTOWLAN_RESELECT_LABEL_CTRL_ID,
    MMIWIFI_GPRSTOWLAN_RESELECT_DROPDOWNLIST_CTRL_ID,

    MMIWIFI_AP_RESELECT_LABEL_CTRL_ID,
    MMIWIFI_AP_RESELECT_DROPDOWNLIST_CTRL_ID,

    MMIWIFI_NO_WLAN_INQUIRE_LABEL_CTRL_ID,
    MMIWIFI_NO_WLAN_INQUIRE_DROPDOWNLIST_CTRL_ID,

    MMIWIFI_WLAN_SETTING_ONOFF_FORMCTRL_ID,
    MMIWIFI_WLAN_SETTING_AUTO_CONNECT_FORMCTRL_ID,
    MMIWIFI_WLAN_SETTING_SEARCH_WLAN_FORMCTRL_ID,
    MMIWIFI_WLAN_SETTING_ATTRIBUTE_FORMCTRL_ID,
    MMIWIFI_WLAN_SETTING_PROXY_SETTING_FORMCTRL_ID,
    MMIWIFI_WLAN_SETTING_GPRSTOWLAN_RESELECT_FORMCTRL_ID,
    MMIWIFI_WLAN_SETTING_AP_RESELECT_FORMCTRL_ID,
    MMIWIFI_WLAN_SETTING_INQUIRE_SETTING_FORMCTRL_ID,  
    
    MMIWIFI_OWN_ATTRIBUTE_LABEL_CTRL_ID,
    MMIWIFI_PROXY_SETTING_LABEL_CTRL_ID,

    MMIWIFI_OWN_ATTRIBUTE_FORMCTRL_ID,
    MMIWIFI_IP_TYPE_LABEL_CTRL_ID,
    MMIWIFI_IP_TYPE_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_IP_LABEL_CTRL_ID,
    MMIWIFI_IP_DATA_EDIT_CTRL_ID,
    MMIWIFI_MAC_LABEL_CTRL_ID,
    MMIWIFI_MAC_DATA_LABEL_CTRL_ID,
    MMIWIFI_GATEWAY_LABEL_CTRL_ID,
    MMIWIFI_GATEWAY_DATA_EDIT_CTRL_ID,
    MMIWIFI_SUBMASK_LABEL_CTRL_ID,
    MMIWIFI_SUBMASK_DATA_EDIT_CTRL_ID,
    MMIWIFI_DNS1_LABEL_CTRL_ID,
    MMIWIFI_DNS1_DATA_EDIT_CTRL_ID,
    MMIWIFI_DNS2_LABEL_CTRL_ID,
    MMIWIFI_DNS2_DATA_EDIT_CTRL_ID,

    MMIWIFI_PROXY_SETTING_FORMCTRL_ID,
    MMIWIFI_PROXY_QUERY_LABEL_CTRL_ID,
    MMIWIFI_PROXY_QUERY_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_PROXY_IP_LABEL_CTRL_ID,
    MMIWIFI_PROXY_IP_DATA_EDIT_CTRL_ID,
    MMIWIFI_PROXY_PORT_LABEL_CTRL_ID,
    MMIWIFI_PROXY_PORT_EDIT_CTRL_ID,
    MMIWIFI_PROXY_NAME_LABEL_CTRL_ID,
    MMIWIFI_PROXY_NAME_EDIT_CTRL_ID,
    MMIWIFI_PROXY_PASSWORD_LABEL_CTRL_ID,
    MMIWIFI_PROXY_PASSWORD_EDIT_CTRL_ID,
    MMIWIFI_PROXY_REJECTLIST_LABEL_CTRL_ID,
    MMIWIFI_LIST_REJECT_LIST_CTRL_ID,
    MMIWIFI_REJECTLIST_POP_MENU_CTRL_ID,
    
    MMIWIFI_PROXY_REJECTLIST_FORMCTRL_ID,
    MMIWIFI_PROXY_REJECTLIST_EDIT_LABEL_CTRL_ID,
    MMIWIFI_PROXY_REJECTLIST_NEW_EDIT_CTRL_ID,
    
    MMIWIFI_MAC_CTRL_ID,
    MMIWIFI_TRUSTED_LIST_POP_MENU_CTRL_ID,
    
    MMIWIFI_WEP_KEY_FORMCTRL_ID,
    MMIWIFI_WEP_KEY_LABEL_CTRL_ID,
    MMIWIFI_WEP_KEY_EDIT_CTRL_ID,

    MMIWIFI_SPECTIFY_SEARCH_SSID_FORMCTRL_ID,
    MMIWIFI_SPECTIFY_SEARCH_SSID_LABEL_CTRL_ID,
    MMIWIFI_SPECTIFY_SEARCH_SSID_EDIT_CTRL_ID,
    
    MMIWIFI_TAB_MAIN_CTRL_ID,
    MMIWIFI_LIST_TRUSTED_CTRL_ID,
    MMIWIFI_MENU_DEF_AP_SET_CTRL_ID,

    MMIWIFI_MOD_PERSONAL_INFO_FORM_CTRL_ID,
    MMIWIFI_LABELT_USER_NAME_CTRL_ID,
    MMIWIFI_EDIT_USER_NAME_CTRL_ID,
    MMIWIFI_LABELT_PASSWORD_CTRL_ID,
    MMIWIFI_EDIT_PASSWORD_CTRL_ID,
    MMIWIFI_LABELT_RE_PASSWORD_CTRL_ID,
    MMIWIFI_EDIT_RE_PASSWORD_CTRL_ID,
    MMIWIFI_LIST_AUTO_CONNECT_CTRL_ID,

    MMIWIFI_EDIT_AP_FORMCTRL_ID,
    MMIWIFI_CHILD_FORM_SSID_CTRL_ID,
    MMIWIFI_CHILD_FORM_NETWORK_STATE_CTRL_ID,
    MMIWIFI_CHILD_FORM_NETWORK_TYPE_CTRL_ID,
    MMIWIFI_CHILD_FORM_AUTH_TYPE_CTRL_ID,
    MMIWIFI_CHILD_FORM_AUTH_SETTING_CTRL_ID,
    MMIWIFI_CHILD_FORM_CONNECT_STATE_CTRL_ID,
    MMIWIFI_EDIT_SSID_LABEL_CTRL_ID,
    MMIWIFI_EDIT_SSID_DATA_EDIT_CTRL_ID,
    MMIWIFI_EDIT_NETWORK_STATE_LABEL_CTRL_ID,
    MMIWIFI_EDIT_NETWORK_STATE_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_EDIT_NETWORK_TYPE_LABEL_CTRL_ID,
    MMIWIFI_EDIT_NETWORK_TYPE_DATA_LABEL_CTRL_ID,
    MMIWIFI_EDIT_AUTH_TYPE_LABEL_CTRL_ID,
    MMIWIFI_EDIT_AUTH_TYPE_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_EDIT_AUTH_SETTING_LABEL_CTRL_ID,
    MMIWIFI_EDIT_CONNECT_STATE_LABEL_CTRL_ID,
    MMIWIFI_EDIT_CONNECT_STATE_DROPDOWNLIST_CTRL_ID,

    MMIWIFI_EDIT_WEP_FORMCTRL_ID,
    MMIWIFI_CHILD_FORM_MODEL_CTRL_ID,
    MMIWIFI_CHILD_FORM_KEY_INDEX_CTRL_ID,
    MMIWIFI_CHILD_FORM_ENCRYPT_CTRL_ID,
    MMIWIFI_CHILD_FORM_STATE_CTRL_ID,
    MMIWIFI_CHILD_FORM_KEY_CTRL_ID,
    MMIWIFI_EDIT_WEP_KEY_OPEN_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WEP_KEY_OPEN_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_EDIT_WEP_KEY_INDEX_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WEP_KEY_INDEX_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_EDIT_WEP_ENCRYPT_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WEP_ENCRYPT_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_EDIT_WEP_KEY_STATE_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WEP_KEY_STATE_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_EDIT_WEP_KEY_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WEP_KEY_EDIT_CTRL_ID,
    
    MMIWIFI_EDIT_WPA_WPA2_FORMCTRL_ID,
    MMIWIFI_CHILD_FORM_PRESHAREKEY_STATE_CTRL_ID,
    MMIWIFI_CHILD_FORM_PRESHAREKEY_PASSWORD_CTRL_ID,
    MMIWIFI_EDIT_WPA_WPA2_PRESHAREKEY_STATE_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WPA_WPA2_PRESHAREKEY_STATE_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_EDIT_WPA_WPA2_PRESHAREKEY_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WPA_WPA2_PRESHAREKEY_EDIT_CTRL_ID,
    
    MMIWIFI_EDIT_WAPI_LABEL_ID,
    MMIWIFI_EDIT_WAPI_LISTBOX_ID,

    MMIWIFI_EDIT_WAPI_PSK_FORMCTRL_ID,
    MMIWIFI_CHILD_WAPI_STATE_CTRL_ID,
    MMIWIFI_CHILD_FORM_WAPI_PASSWORD_CTRL_ID,

    MMIWIFI_EDIT_WAPI_PRESHAREKEY_STATE_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WAPI_PRESHAREKEY_STATE_DROPDOWNLIST_CTRL_ID,
    MMIWIFI_EDIT_WAPI_PRESHAREKEY_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WAPI_PRESHAREKEY_EDIT_CTRL_ID,

    MMIWIFI_EDIT_WAPI_CERTIFICATE_FORMCTRL_ID,
    MMIWIFI_CHILD_FORM_CLIENT_CTRL_ID,
    MMIWIFI_CHILD_FORM_PARENT_CTRL_ID,
    MMIWIFI_CHILD_FORM_UNINSTALL_CTRL_ID,
    MMIWIFI_EDIT_WAPI_CLIENT_CERTIFICATE_TEXT_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WAPI_CLIENT_CERTIFICATE_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WAPI_PARENT_CERTIFICATE_TEXT_LABEL_CTRL_ID,
    MMIWIFI_EDIT_WAPI_PARENT_CERTIFICATE_LBAEL_CTRL_ID,
    MMIWIFI_LABEL_WAPI_UNINSTALL_CTRL_ID,

    MMIWIFI_WLAN_PORTAL_FORM_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_USER_NAME_LABEL_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_USER_NAME_EDIT_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_PASSOWRD_LABEL_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_PASSOWRD_EDIT_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_REMEBER_PASSWORD_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_AUTO_LOGIN_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_ACTIVE_SERVICE_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_SUBSCRIBE_SERVICE_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_NOTIFICATION_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_MODIFY_PASSWORD_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_UPDATE_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_CHILD_RESET_PASSWORD_CTRL_ID,

    MMIWIFI_WLAN_PASSWORD_MODIFY_FORM_CTRL_ID,
    MMIWIFI_CHILD_FORM_ORIGINAL_PASSWORD_CTRL_ID,
    MMIWIFI_CHILD_FORM_NEW_PASSWORD_CTRL_ID,
    MMIWIFI_CHILD_FORM_CONFIRM_NEW_PASSWORD_CTRL_ID,
    MMIWIFI_WLAN_PASSWORD_CHILD_OLDPASSOWRD_LABEL_CTRL_ID,
    MMIWIFI_WLAN_PASSWORD_CHILD_OLDPASSOWRD_EDIT_CTRL_ID,
    MMIWIFI_WLAN_PASSWORD_CHILD_NEWPASSOWRD_LABEL_CTRL_ID,
    MMIWIFI_WLAN_PASSWORD_CHILD_NEWPASSOWRD_EDIT_CTRL_ID,
    
    MMIWIFI_WLAN_PASSWORD_CHILD_NEWPASSOWRD_CONFIRM_LABEL_CTRL_ID,
    MMIWIFI_WLAN_PASSWORD_CHILD_NEWPASSOWRD_CONFIRM_EDIT_CTRL_ID,
    
    MMIWIFI_WLAN_PORTAL_CHILD_HELP_CTRL_ID,

    MMIWIFI_WLAN_PORTAL_USER_NAME_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_PASSWORD_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_REMEMBER_PASSWORD_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_AUTO_LOGIN_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_ACTIVE_SERVICE_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_SUBSCRIBE_SERVICE_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_NOTIFICATION_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_MODIFY_PASSWORD_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_UPDATE_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_RESET_PASSWORD_FORMCTRL_ID,
    MMIWIFI_WLAN_PORTAL_HELP_FORMCTRL_ID,

    MMIWIFI_WLAN_PORTAL_STATUS_CTRL_ID,
    MMIWIFI_WLAN_PORTAL_HELP_CTRL_ID,
    MMIWIFI_WLAN_COM_SELECT_SIM_MENU_CTRL_ID,
    MMIWIFI_SELECT_AP_LIST_CTRL_ID,
    MMIWLAN_PORTAL_LOGIN_FORM_CTRL_ID,
    MMIWLAN_PORTAL_LOGIN_NOTIFICATION_LABEL_CTRL_ID,
    MMIWLAN_PORTAL_LOGIN_NEVER_NOTIFY_LABEL_CTRL_ID,

    MMIWIFI_CHILD_FORM_STATIC_IP_CTRL_ID,
    MMIWIFI_CHILD_FORM_IP_ADDRESS_CTRL_ID,
    MMIWIFI_CHILD_FORM_MAC_CTRL_ID,
    MMIWIFI_CHILD_FORM_DNS1_CTRL_ID,
    MMIWIFI_CHILD_FORM_DNS2_CTRL_ID,
    MMIWIFI_CHILD_FORM_MASK_CTRL_ID,
    MMIWIFI_CHILD_FORM_GATEWAY_CTRL_ID,

    MMIWIFI_CHILD_FORM_PROXY_CTRL_ID,
    MMIWIFI_CHILD_FORM_PROXY_IP_CTRL_ID,
    MMIWIFI_CHILD_FORM_PROXY_PORT_TRL_ID,
    MMIWIFI_CHILD_FORM_PROXY_USER_CTRL_ID,
    MMIWIFI_CHILD_FORM_PROXY_PASSWORD_CTRL_ID,
    MMIWIFI_CHILD_FORM_PROXY_REJECTLIST_CTRL_ID,

#ifndef MMI_GUI_STYLE_TYPICAL
    MMIWIFI_LIST_SETTING_CTRL_ID,
    MMIWIFI_MENU_SEARCH_CTRL_ID,
    MMIWIFI_MENU_WPA_STATE_CTRL_ID,
    MMIWIFI_MENU_AP_NETWORK_STATE_CTRL_ID,
    MMIWIFI_MENU_AP_AUTH_TYPE_CTRL_ID,
    MMIWIFI_MENU_AP_CONNECT_STATE_CTRL_ID,
    MMIWIFI_MENU_WAPI_STATE_CTRL_ID,
    MMIWIFI_MENU_WEP_STATE_CTRL_ID,
    MMIWIFI_MENU_WEP_ENCYPT_CTRL_ID,
    MMIWIFI_MENU_WEP_MODE_CTRL_ID,
    MMIWIFI_MENU_WEP_KEY_INDEX_CTRL_ID,
    MMIWIFI_MENU_AP_EDIT_WEP_STATE_CTRL_ID,
    MMIWIFI_MENU_AP_EDIT_WEP_ENCYPT_CTRL_ID,
    MMIWIFI_MENU_AP_EDIT_WEP_MODE_CTRL_ID,
    MMIWIFI_MENU_AP_EDIT_WEP_KEY_INDEX_CTRL_ID,
    MMIWIFI_MENU_GPRS_TO_WLAN_CTRL_ID,
    MMIWIFI_MENU_RELECT_AP_SET_CTRL_ID,
    MMIWIFI_MENU_PROMPT_NO_WLAN_CTRL_ID,
    MMIWIFI_CHILD_FORM_LIST_IP_TYPE_CTRL_ID,
    MMIWIFI_LIST_IP_TYPE_CTRL_ID,
    MMIWIFI_LIST_PROXY_CTRL_ID,
    MMIWIFI_MENU_REJECT_POPUPAUTO_ID,
    MMIWIFI_MENU_AP_LIST_POPUPAUTO_ID,
    MMIWIFI_MENU_AP_TRUST_LIST_POPUPAUTO_ID,
    MMIWLAN_LIST_PORTAL_MAIN_CTRL_ID,
    MMIWLAN_FORM_ACCOUNT_CTRL_ID,
    MMIWLAN_CHILD_FORM_USER_CTRL_ID,
    MMIWLAN_CHILD_FORM_PASSWORD_CTRL_ID,
    MMIWLAN_LABEL_PORTAL_USER_CTRL_ID,
    MMIWLAN_LABEL_PORTAL_PASSWORD_CTRL_ID,
    MMIWLAN_EDIT_PORTAL_USER_CTRL_ID,
    MMIWLAN_EDIT_PORTAL_PASSWORD_CTRL_ID,
    MMIWLAN_LIST_WPA_STATE_CTRL_ID,
    MMIWLAN_LIST_WAPI_STATE_CTRL_ID,
    MMIWLAN_LIST_WEP_STATE_CTRL_ID,
    MMIWLAN_LIST_AP_EDIT_CTRL_ID,
    MMIWIFI_FORM_AP_EDIT_WAPI_ID,
#endif // MMI_GUI_STYLE_TYPICAL

#ifdef WLAN_EAP_SUPPORT
    MMIWIFI_CHILD_FORM_EAP_SIM_INDEX_CTRL_ID,
    MMIWIFI_EDIT_EAP_SIM_INDEX_LABEL_CTRL_ID,
    MMIWIFI_MENU_AP_EAP_SIM_INDEX_CTRL_ID,
    MMIWIFI_MENU_EAP_TYPE_CTRL_ID,
	MMIWIFI_FORM_EAP_ACCOUNT_CTRL_ID,
	MMIWIFI_CHILD_FORM_EAP_USER_CTRL_ID,
	MMIWIFI_CHILD_FORM_EAP_PASSWORD_CTRL_ID,
	MMIWIFI_LABEL_EAP_USER_CTRL_ID,
	MMIWIFI_LABEL_EAP_PASSWORD_CTRL_ID,
	MMIWIFI_EDIT_EAP_USER_CTRL_ID,
	MMIWIFI_EDIT_EAP_PASSWORD_CTRL_ID,
#endif // WLAN_EAP_SUPPORT

    MMIWIFI_COM_SELECT_SIM_CTRL_ID,

    MMIWIFI_MAIN_LIST_CTRL_ID,
    MMIWIFI_PASSWORD_EDIT_CTRL_ID,
    MMIWIFI_PASSWORD_OK_BTN_CTRL_ID,
    MMIWIFI_PASSWORD_CANCEL_BTN_CTRL_ID,

    MMIWIFI_MAX_CTRL_ID
}MMIWIFI_CONTROL_ID_E;

/**--------------------------------------------------------------------------*
 **                         FUNCTION DEFINITION                              *
 **--------------------------------------------------------------------------*/
/*****************************************************************************/
//     Description : Register wifi menu group
//    Global resource dependence : none
//  Author: li.li
//    Note:
/*****************************************************************************/
PUBLIC void MMIWIFI_RegMenuGroup(void);

/*****************************************************************************/
//     Description : Register wifi win id
//    Global resource dependence : none
//  Author: li.li
//    Note:
/*****************************************************************************/
PUBLIC void MMIWIFI_RegWinIdNameArr(void);

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif

#endif //_MMIWIFI_ID_H_
