
RES_ADD_IMG(IMAGE_WIFI_ENCRYPT,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_ENCRYPT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_RSSI0,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_RSSI0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_RSSI1,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_RSSI1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_RSSI2,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_RSSI2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_RSSI3,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_RSSI3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_RSSI4,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_RSSI4.png",IMG_CMP_PNG_ARGB_RLE,0)

//RES_ADD_IMG(IMAGE_WIFI_CONNECT_RSSI0,"\\MMI_RES_##\\IMAG\\StatusbarIcon\\wifi\\IMAGE_IDLE_TITLE_ICON_WIFI1.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIFI_CONNECT_RSSI1,"\\MMI_RES_##\\IMAG\\StatusbarIcon\\wifi\\IMAGE_IDLE_TITLE_ICON_WIFI2.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIFI_CONNECT_RSSI2,"\\MMI_RES_##\\IMAG\\StatusbarIcon\\wifi\\IMAGE_IDLE_TITLE_ICON_WIFI3.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIFI_CONNECT_RSSI3,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_CONNECT_RSSI3.png",IMG_CMP_PNG_ARGB_RLE,0)

//RES_ADD_IMG(IMAGE_WIFI_CONNECT_ENCRYPT_RSSI0,"\\MMI_RES_##\\IMAG\\StatusbarIcon\\wifi\\IMAGE_IDLE_TITLE_ICON_WIFI1_CONNECT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIFI_CONNECT_ENCRYPT_RSSI1,"\\MMI_RES_##\\IMAG\\StatusbarIcon\\wifi\\IMAGE_IDLE_TITLE_ICON_WIFI2_CONNECT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIFI_CONNECT_ENCRYPT_RSSI2,"\\MMI_RES_##\\IMAG\\StatusbarIcon\\wifi\\IMAGE_IDLE_TITLE_ICON_WIFI3_CONNECT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIFI_CONNECT_ENCRYPT_RSSI3,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_CONNECT_ENCRYPT_RSSI3.png",IMG_CMP_PNG_ARGB_RLE,0)

/* BEGIN: Modified by George.Liu 01526, 2010/7/20   PN:C59282 MS00189474*/
RES_ADD_IMG(IMAGE_WIFI_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_CONNECT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_CONNECT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_CONNECT_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_CONNECT_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
/* END:   Modified by George.Liu 01526, 2010/7/20   PN:C59282 MS00189474*/

RES_ADD_IMG(IMAGE_WIFI_AP_CONNECTED,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_AP_CONNECTED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_AP_DISCONNECTED,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_AP_DISCONNECTED.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WLANLIST_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WLANLIST_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_TRUSTLIST_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_TRUSTLIST_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WLAN_SETTINGS_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WLAN_SETTINGS_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WLANLIST_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WLANLIST_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_TRUSTLIST_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_TRUSTLIST_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WLAN_SETTINGS_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WLAN_SETTINGS_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIFI_AP_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_LOCK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIFI_AP_OPENSYS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WIFI_OPENSYS.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(ISTYLE_IMAGE_WLANLIST_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_WLANLIST_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_TRUSTLIST_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_TRUSTLIST_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_WLAN_SETTINGS_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_WLAN_SETTINGS_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(ISTYLE_IMAGE_WLANLIST_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_WLANLIST_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_TRUSTLIST_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_TRUSTLIST_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_WLAN_SETTINGS_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_WLAN_SETTINGS_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_ANIM(ANIM_WIFI_WAITING,"\\MMI_RES_##\\ANIM\\ANIM_WIFI_WAITING",AT_COMPRESS_STREAM,75,0x000000)

RES_ADD_STRING(TXT_WIFI_OPEN,"Open")
RES_ADD_STRING(TXT_WIFI_CLOSE,"Close")

//RES_ADD_STRING(TXT_WIFI_CONNECT,"Connect")  //replaced by common ID TXT_COMMON_CONNECT_COMN
//RES_ADD_STRING(TXT_WIFI_EDIT,"Edit") //replaced by common ID TXT_EDIT
//RES_ADD_STRING(TXT_WIFI_SCAN,"Search")  //replaced by common ID STXT_SEARCH
//RES_ADD_STRING(TXT_WIFI_NEW,"New")    //replaced by common ID TXT_NEW
//RES_ADD_STRING(TXT_WIFI_DELETE,"Delete")    //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_WIFI_CLEAR,"Clear")     //replaced by common ID TXT_COMMON_CLEAR
//RES_ADD_STRING(TXT_WIFI_HELP,"Help")  //replaced by common ID TXT_HELP
//RES_ADD_STRING(TXT_WIFI_DISCONNECT,"Disconnect")  //replaced by common ID  TXT_COMM_DISCONNECT
//RES_ADD_STRING(TXT_WIFI_NETWORK,"WiFi Network")
//RES_ADD_STRING(TXT_WIFI_NETWORK_LIST,"WiFi Network List")  //replaced by common ID TXT_COMM_LIST
RES_ADD_STRING(TXT_WIFI_OPEN_ALERT,"The WiFi Is Not Open, Open It?")
//RES_ADD_STRING(TXT_WIFI_SCANING,"Scaning WiFi Network")    //replaced by common ID TXT_SCANING_WLAN 
//RES_ADD_STRING(TXT_WIFI_CONNECTED,"Has Connected")  //replaced by common ID TXT_COMMON_CONNECTED
//RES_ADD_STRING(TXT_WIFI_DISCONNECTED,"Has Not Connected")  //replaced by common ID TXT_DISCONNECTED
//RES_ADD_STRING(TXT_WIFI_DETAIL,"Detail")    //replaced by common ID STXT_DETAIL
//RES_ADD_STRING(TXT_WIFI_WIFI,"WiFi")  //replaced by common ID TXT_WIFI

RES_ADD_STRING(TXT_WIFI_CONNECTING,"Connecting...")

RES_ADD_STRING(TXT_WIFI_SSID,"SSID")
RES_ADD_STRING(TXT_WIFI_NETWORK_STATE,"Network State")
//RES_ADD_STRING(TXT_WIFI_NETWORK_TYPE,"WiFi Network Type")  //replaced by common ID TXT_WIFI_NETWORK_TYPE
//RES_ADD_STRING(TXT_WIFI_AUTH_TYPE,"WiFi Auth Type")  //replaced by common ID TXT_COMM_SECURITY_TYPE
//RES_ADD_STRING(TXT_WIFI_AUTH_SETTING,"WiFi Auth Setting")  //replaced by common ID TXT_COMM_AUTH_SETTING
RES_ADD_STRING(TXT_WIFI_IP_SETTING,"WiFi IP Setting")
RES_ADD_STRING(TXT_WIFI_SAVE_SETTING,"Save Setting")
RES_ADD_STRING(TXT_WIFI_IS_DELETE,"Delete The Selected Network?")
RES_ADD_STRING(TXT_WIFI_IS_CLEAR,"Clear The Network?")

//RES_ADD_STRING(TXT_WIFI_DELETE_SUCC,"Delete Successfully")       //replaced by common ID TXT_COMMON_DELETESUCESS
//RES_ADD_STRING(TXT_WIFI_DELETE_FAIL,"Delete Failed")  //replaced by common ID TXT_COMMON_DEL_FAIL
RES_ADD_STRING(TXT_WIFI_CLEAR_SUCC,"Clear Successfully")
RES_ADD_STRING(TXT_WIFI_CLEAR_FAIL,"Clear Failed")
RES_ADD_STRING(TXT_WIFI_SSID_EMPTY,"Invalid SSID")
RES_ADD_STRING(TXT_WIFI_NETWORK_STATE_OPEN,"Open")
//RES_ADD_STRING(TXT_WIFI_NETWORK_STATE_HIDE,"Hide")    //replaced by common ID TXT_HIDE

RES_ADD_STRING(TXT_WIFI_NETWORK_TYPE_INFRASTRUCTURE,"Insfrastructure")
RES_ADD_STRING(TXT_WIFI_NETWORK_TYPE_ADHOC,"Special")

RES_ADD_STRING(TXT_WIFI_AUTH_TYPE_OPENSYS,"Open System")
RES_ADD_STRING(TXT_WIFI_AUTH_TYPE_WEP,"WEP")
RES_ADD_STRING(TXT_WIFI_AUTH_TYPE_WPA,"WPA")
RES_ADD_STRING(TXT_WIFI_AUTH_TYPE_WPA2,"WPA2")
RES_ADD_STRING(TXT_WIFI_AUTH_TYPE_WPA_WPA2,"WPA/WPA2")
RES_ADD_STRING(TXT_WIFI_AUTH_TYPE_WPA2_PSK_SHA256,"WPA2-PSK-SHA256")
RES_ADD_STRING(TXT_WIFI_AUTH_TYPE_WPA3_SAE,"WPA3-SAE")
RES_ADD_STRING(TXT_WIFI_AUTH_TYPE_WPA2_WPA3_SAE,"WPA2-PSK/WPA3-SAE")
RES_ADD_STRING(TXT_WIFI_HELP_SEARCH,"Search: search the WiFi that can be used;")
//RES_ADD_STRING(TXT_WIFI_WEPAUTH,"WEP Auth Setting")
RES_ADD_STRING(TXT_WIFI_IP_AUTO,"Auto")
RES_ADD_STRING(TXT_WIFI_IP_SELFDEF,"Self Define")
//RES_ADD_STRING(TXT_WIFI_IP_ADDRESS,"Ip Address")  replaced by common ID TXT_COMM_WIFI_IP_ADDRESS
//RES_ADD_STRING(TXT_WIFI_GATEWAY,"Gateway")  //replaced by common ID TXT_COMMON_GATEWAY
RES_ADD_STRING(TXT_WIFI_DNS1,"DNS1")
RES_ADD_STRING(TXT_WIFI_DNS2,"DNS2")
RES_ADD_STRING(TXT_WIFI_SUBMASK,"Submask")
RES_ADD_STRING(TXT_WIFI_AP_FORGET,"Forget")



RES_ADD_STRING(TXT_WIFI_WPAAUTH_PSK,"Preshare Key")
RES_ADD_STRING(TXT_WIFI_WPAAUTH_EAP,"EAP")
RES_ADD_STRING(TXT_WIFI_WPAAUTH,"WPA Auth Setting")
RES_ADD_STRING(TXT_WIFI_WPA2AUTH,"WPA2 Auth Setting")

RES_ADD_STRING(TXT_WIFI_SAVE_SETTING_TEMP,"Save Temporarily")
RES_ADD_STRING(TXT_WIFI_SAVE_SETTING_FOREVER,"Save Forever")
RES_ADD_STRING(TXT_WIFI_USERNAME_EMPTY,"User Name Is Empty, Can not Save")
RES_ADD_STRING(TXT_WIFI_PASSWORD_EMPTY,"Password Is Empty, Can not Save")

//RES_ADD_STRING(TXT_WIFI_AUTH_USERNAME,"User Name")  //replaced by common ID TXT_COMMON_USERNAME

//RES_ADD_STRING(TXT_WIFI_AUTH_PASSWORD,"Password")  //replaced by common ID TXT_COMMON_PASSWORD

RES_ADD_STRING(TXT_WIFI_WPA_EAP_PEAP,"Peal Protocol")

RES_ADD_STRING(TXT_WIFI_PRESHARE_KEY_INPUT,"Preshare Key Input")
RES_ADD_STRING(TXT_WIFI_WPA_EAP,"EAP Setting")
RES_ADD_STRING(TXT_WIFI_WPAEAP_TLS,"TLS")
RES_ADD_STRING(TXT_WIFI_WPAEAP_FAST,"FAST")
RES_ADD_STRING(TXT_WIFI_WPA_EAP_TTLS,"TTLS Protocol")
RES_ADD_STRING(TXT_WIFI_WPAEAP_TTLS_PAP,"PAP")
RES_ADD_STRING(TXT_WIFI_WPAEAP_TTLS_CHAP,"CHAP")
RES_ADD_STRING(TXT_WIFI_WPAEAP_TTLS_MSCHAP,"MS-CHAP")
//RES_ADD_STRING(TXT_WIFI_WPAEAP_TTLS_MSCHAP2,"MS-CHAP-V2") ////replaced by common id TXT_COMM_MSCHAP2
//RES_ADD_STRING(TXT_WIFI_WPAEAP_PEAP_GTC,"GTC")  //replaced by common id TXT_COMM_GTC
//RES_ADD_STRING(TXT_WIFI_WPAEAP_PEAP_MSCHAP2,"MS-CHAP-V2") //replaced by common id TXT_COMM_MSCHAP2
RES_ADD_STRING(TXT_WIFI_WPAEAP_LEAP,"LEAP")
RES_ADD_STRING(TXT_WIFI_KEY_EMPTY,"The Key Is Empty, Can not Save!")
//RES_ADD_STRING(TXT_WIFI_WPA_EAP_PEAP_GTC,"GTC")  //replaced by common id TXT_COMM_GTC
//RES_ADD_STRING(TXT_WIFI_WPA_EAP_PEAP_MSCHAP2,"MS-CHAP-V2")   //replaced by common id TXT_COMM_MSCHAP2
//RES_ADD_STRING(TXT_WIFI_WPAEAP_SIM,"SIM")  //replaced by common id TXT_COMM_SIM

RES_ADD_STRING(TXT_WIFI_WPAEAP_AKA,"AKA")
RES_ADD_STRING(TXT_WIFI_WPAEAP_TTLS,"TTLS")
RES_ADD_STRING(TXT_WIFI_WPAEAP_PEAP,"PEAP")
RES_ADD_STRING(TXT_WIFI_WEP_INDEX1,"Key1")
RES_ADD_STRING(TXT_WIFI_WEP_INDEX2,"Key2")
RES_ADD_STRING(TXT_WIFI_WEP_INDEX3,"Key3")
RES_ADD_STRING(TXT_WIFI_WEP_INDEX4,"Key4")
RES_ADD_STRING(TXT_WIFI_WEP_BIT64,"64 Bit")

RES_ADD_STRING(TXT_WIFI_WEP_BIT128,"128 Bit")
RES_ADD_STRING(TXT_WIFI_WEP_KEY_ASCII,"ASCII")

RES_ADD_STRING(TXT_WIFI_WEP_KEY_HEX,"HEX")
RES_ADD_STRING(TXT_WIFI_WPA_EAP_TLS_PATH,"TLS Certificate Path")
RES_ADD_STRING(TXT_WIFI_WPA_EAP_PAC_PATH,"PAC Path")
//RES_ADD_STRING(TXT_WIFI_HAS_OPEN,"WiFi Has Opened")  //replaced by common iD TXT_COMM_HAS_OPEN

//RES_ADD_STRING(TXT_WIFI_HAS_CLOSE,"WiFi Has Closed")  //replaced by common iD TXT_COMM_HAS_CLOSE
RES_ADD_STRING(TXT_WIFI_STATIC_IP,"Static Ip Setting")
RES_ADD_STRING(TXT_WIFI_BIT_SETTING,"WEP Encrypt")
RES_ADD_STRING(TXT_WEP_KEY_INDEX,"WEP Key Index")
RES_ADD_STRING(TXT_WEP_KEY_STYLE,"WEP Key Format")
//RES_ADD_STRING(TXT_WEP_KEY_LABEL,"WEP Key")  //replaced by common ID TXT_COMM_WEP_KEY

RES_ADD_STRING(TXT_WIFI_DETAIL_NETWORK,"SSID:")
RES_ADD_STRING(TXT_WIFI_DETAIL_RSSI,"Signal:")

//RES_ADD_STRING(TXT_WIFI_DETAIL_RSSI_NONE,"None ")    //replaced by common ID TXT_NONE
RES_ADD_STRING(TXT_WIFI_DETAIL_RSSI_WEAK,"Weak ")
RES_ADD_STRING(TXT_WIFI_DETAIL_RSSI_STRONG,"Strong ")

//RES_ADD_STRING(TXT_WIFI_DETAIL_MODE,"WiFi Network Type:")  //replaced by common ID TXT_DETAIL_MODE
RES_ADD_STRING(TXT_WIFI_DETAIL_CRED,"WiFi Auth Type:")
RES_ADD_STRING(TXT_WIFI_DETAIL_RATE,"Rate:")
RES_ADD_STRING(TXT_WIFI_IS_DELETE_CONNECTED,"The WiFi Is Connected, This Option Will Disconnect The WiFi!")
RES_ADD_STRING(TXT_WIFI_SELECT_PATH,"Select Path")
RES_ADD_STRING(TXT_WIFI_KEY_HEX_INPUT,"Please Input Hex, 0-9, a-f, A-F")
RES_ADD_STRING(TXT_WIFI_SET_FINISH,"Setting Finished")
RES_ADD_STRING(TXT_WIFI_SSID_INVALID,"SSID Invalid, Can not Save!")
//RES_ADD_STRING(TXT_WIFI_FINISHED,"Finished!")    //replaced by common ID TXT_COMPLETE 
//RES_ADD_STRING(TXT_WIFI_OPEN_FAIL,"Open Failed!")  //replaced by common ID TXT_COMM_OPEN_FAIL
//RES_ADD_STRING(TXT_WIFI_CLOSE_FAIL,"Close Failed!")               //replaced by common ID TXT_WIFI_WLAN_COMMON_CLOSE_FAIL    
//RES_ADD_STRING(TXT_WIFI_CONNECT_FAIL,"WiFi Connect Failed!")      //replaced by common ID TXT_COMMON_LINK_FAILED 
RES_ADD_STRING(TXT_WIFI_CONNECT_SUCC,"WiFi Connect Successfully!")
RES_ADD_STRING(TXT_WIFI_DHCPING,"Dhcping...")

RES_ADD_STRING(TXT_WIFI_DHCP_FAIL,"Dhcp Failed!")
RES_ADD_STRING(TXT_WIFI_DHCP_SUCC,"Dhcp Successfully!")
RES_ADD_STRING(TXT_WIFI_DISCONNECT_FAIL,"Disconnect Failed!")
RES_ADD_STRING(TXT_WIFI_DETAIL_BSSID,"BSSID:")
RES_ADD_STRING(TXT_WIFI_DETAIL_CHANNEL,"Channel:")

RES_ADD_STRING(TXT_WIFI_DETAIL_IP,"IP:")
RES_ADD_STRING(TXT_WIFI_DETAIL_SUBMASK,"Submask:")
RES_ADD_STRING(TXT_WIFI_DETAIL_GATEWAY,"Gateway:")
RES_ADD_STRING(TXT_WIFI_DETAIL_DNS1,"DNS1:")
RES_ADD_STRING(TXT_WIFI_DETAIL_DNS2,"DNS2:")

//RES_ADD_STRING(TXT_WIFI_KEY_INVALID,"Key Invalid!")      //replaced by common ID TXT_PASSWORD_INVALID
//RES_ADD_STRING(TXT_WIFI_SAVE_FAILED,"Save Failed!") //replaced by common ID TXT_MMI_SAVEFAILED


RES_ADD_STRING(TXT_WIFI_WEP_KEY_OPEN_MODE,"Open")
RES_ADD_STRING(TXT_WIFI_WEP_KEY_SHARE_MODE,"Share")
//RES_ADD_STRING(TXT_WEP_KEY_MODE,"Mode:")  //replaced by common ID TXT_DETAIL_MODE 
//RES_ADD_STRING(TXT_WEP_KEY_TYPE,"Type:")  //replaced by common ID TXT_TYPE
RES_ADD_STRING(TXT_WIFI_SAVE_FULL,"The Max Number Of WiFi Is 20, Can Not Save!")
RES_ADD_STRING(TXT_WIFI_CONNECT_BUSY,"The Network is Busy, Please Wait...")

RES_ADD_STRING(TXT_WIFI_KEY_INPUT_10,"Please Input 10 Characters!")
RES_ADD_STRING(TXT_WIFI_KEY_INPUT_5,"Please Input 5 Characters!")
RES_ADD_STRING(TXT_WIFI_KEY_INPUT_26,"Please Input 26 Characters!")
RES_ADD_STRING(TXT_WIFI_KEY_INPUT_13,"Please Input 13 Characters!")
//RES_ADD_STRING(TXT_WIFI_OPENING,"WiFi Is Opening, Please Wait…")    //replaced by common ID TXT_OPENING_WLAN


//RES_ADD_STRING(TXT_WIFI_LIST_NUM_FULL,"The List Number Is 20, Can Not Display The WiFi That Searched!")  //replaced by common ID TXT_COMMON_LIST_NUM_FULL


RES_ADD_STRING(TXT_WIFI_HELP_DETAIL,"Detail: display the detail of the selected WiFi")
RES_ADD_STRING(TXT_WIFI_HELP_EDIT,"Edit: edit the selected WiFi")
RES_ADD_STRING(TXT_WIFI_HELP_NEW,"New: create a new WiFi")
RES_ADD_STRING(TXT_WIFI_HELP_DELETE,"Delete: delete the selected WiFi")
RES_ADD_STRING(TXT_WIFI_HELP_CLEAR,"Clear: clear all of the WiFi")

RES_ADD_STRING(TXT_WIFI_KEY_RANGE_OUT,"The key len should be 8-63")

/* Need Add in xls file*/
RES_ADD_STRING(TXT_WIFI_KEY_RANGE_OUT_1,"The key len should be 16-126")
RES_ADD_STRING(TXT_WIFI_WPA_HEX_RANGE_OUT,"The key len should be 8-64")
//RES_ADD_STRING(TXT_WIFI_WEBBROWSER,"Browser")        //case3：defined but not used
//RES_ADD_STRING(TXT_WIFI_REFRESH,"Refresh")    //replaced by common ID TXT_REFRESH
RES_ADD_STRING(TXT_WIFI_SPECTIFY_SEARCH_SSID,"Search specified SSID")
RES_ADD_STRING(TXT_WIFI_DEFAULT_AP_SETTING,"Default AP Settings")
RES_ADD_STRING(TXT_WIFI_ADD_APN,"Add new AP")
RES_ADD_STRING(TXT_WIFI_CHANGE_PRIORITY_HIGH,"Priority increase")
RES_ADD_STRING(TXT_WIFI_CHANGE_PRIORITY_LOW,"Priority decrease")
//RES_ADD_STRING(TXT_WIFI_WEP_KEY,"WEP Key")  //replaced by common id TXT_COMM_WEP_KEY
RES_ADD_STRING(TXT_WIFI_INPUT_SSID,"Please Inut SSID")
//RES_ADD_STRING(TXT_WIFI_SEARCHING,"Searching, please waiting")       //case3：defined but not used

//RES_ADD_STRING(TXT_WIFI_WLAN_ACTIVE_QUERY,"WLAN is disable, enable now?")        //case3：defined but not used
RES_ADD_STRING(TXT_WIFI_WLAN_SETTING,"WLAN settings")
RES_ADD_STRING(TXT_WIFI_WLAN,"WLAN")
RES_ADD_STRING(TXT_SET_WIFI_WLAN,"WLAN")
RES_ADD_STRING(TXT_WIFI_SEARCH_WLAN,"Auto searching")
RES_ADD_STRING(TXT_WIFI_OWN_ATTRIBUTE,"Owner attribute")
//RES_ADD_STRING(TXT_WIFI_PROXY,"Proxy settings")  //replaced by common ID TXT_COMM_PROXY
//RES_ADD_STRING(TXT_WIFI_ENABLE,"Enable")               //replaced by common ID TXT_COMMON_ENABLE_ON
//RES_ADD_STRING(TXT_WIFI_DISABLE,"Disable")             //replaced by common ID TXT_CLOSE
RES_ADD_STRING(TXT_WIFI_PER_1_MIN,"Per one minuter")
RES_ADD_STRING(TXT_WIFI_PER_2_MIN,"Per two minuters")
RES_ADD_STRING(TXT_WIFI_PER_5_MIN,"Per five minuters")
RES_ADD_STRING(TXT_WIFI_PER_10_MIN,"Per ten minuters")
//RES_ADD_STRING(TXT_WIFI_IP_TYPE,"IP type")  //replaced bu common ID  TXT_COMM_WIFI_IP_ADDRESS
//RES_ADD_STRING(TXT_WIFI_IP,"IP")         //case3：defined but not used
RES_ADD_STRING(TXT_WIFI_MAC,"MAC")
RES_ADD_STRING(TXT_WIFI_PROXY_IP,"Proxy Ip address")
RES_ADD_STRING(TXT_WIFI_PROXY_PORT,"Proxy Port")
//RES_ADD_STRING(TXT_WIFI_PROXY_USE,"whether use proxy?")    //replaced by common ID TXT_PROXY_USE_QUERY
//RES_ADD_STRING(TXT_WIFI_PROXY_NO,"Donot use")  //replaced by common ID TXT_COMM_PROXY_OFF
//RES_ADD_STRING(TXT_WIFI_PROXY_YES,"use")    //replaced by common ID TXT_PROXY_ON
//RES_ADD_STRING(TXT_WIFI_PROXY_PASSWORD,"Password")  //replaced by common ID TXT_COMMON_PASSWORD
//RES_ADD_STRING(TXT_WIFI_PROXY_USERNAME,"Username")  //replaced by common ID TXT_COMMON_USERNAME
RES_ADD_STRING(TXT_WIFI_PROXY_REJECTLIST,"Reject list")
//RES_ADD_STRING(TXT_WIFI_ADD,"Add")  //replaced by common ID STXT_ADD
RES_ADD_STRING(TXT_WIFI_TRUSTED_LIST,"Trustful list")
//RES_ADD_STRING(TXT_WIFI_LIST,"WLAN list")  //replaced by common ID TXT_COMM_LIST
//RES_ADD_STRING(TXT_WIFI_DEF_AP_SETTING,"Default AP Settings")          //replaced by local ID TXT_WIFI_DEFAULT_AP_SETTING
RES_ADD_STRING(TXT_WIFI_DEACTIVE_SERVICE,"Service Deactive")
RES_ADD_STRING(TXT_WIFI_PERSONAL_INFO_SETTING,"Personal info settings")
RES_ADD_STRING(TXT_WIFI_AUTO_CONNECTING_SETTING,"Auto connecting settings")
RES_ADD_STRING(TXT_WIFI_ORIGINAL_USER_NAME,"Please input old username")
RES_ADD_STRING(TXT_WIFI_ORIGINAL_PASSWORD,"Please input old password")
RES_ADD_STRING(TXT_WIFI_NEW_USER_NAME,"Please input new username")
RES_ADD_STRING(TXT_WIFI_NEW_PASSWORD,"Please input new password")
RES_ADD_STRING(TXT_WIFI_CONFIRM_NEW_PASSWORD,"Please input new password again")
RES_ADD_STRING(TXT_WIFI_SAVE_OK,"Save complete, and will be effective next connecting")
RES_ADD_STRING(TXT_WIFI_INVALID_ACCOUNT,"Username or password incorrect")
//RES_ADD_STRING(TXT_WIFI_INVALID_PASSWORD,"Different passwords")     //replaced by common ID TXT_MSGBOX_PWD_CONFLICT   
//RES_ADD_STRING(TXT_WIFI_AUTO_CONNECT_ON,"Enable")         //replaced by common ID TXT_COMMON_ENABLE_ON
//RES_ADD_STRING(TXT_WIFI_AUTO_CONNECT_OFF,"Disable")      //replaced by common ID TXT_CLOSE
RES_ADD_STRING(TXT_WIFI_AUTO_CONNECT_ON_SUCCESSFULLY,"Actived")
RES_ADD_STRING(TXT_WIFI_AUTO_CONNECT_OFF_SUCCESSFULLY,"Deactived")
RES_ADD_STRING(TXT_WIFI_QUERY_ACTIVE_SERVICE,"Actived WLAN service?")
RES_ADD_STRING(TXT_WIFI_ACTIVING_SERVICE,"Activing")
//RES_ADD_STRING(TXT_WIFI_ACTIVE_SERVICE_SUCCESSFULLY,"WLAN service actived")     //case3：defined but not used
//RES_ADD_STRING(TXT_WIFI_ACTIVE_SERVICE_NAME,"Username:")      //case3：defined but not used
//RES_ADD_STRING(TXT_WIFI_ACTIVE_SERVICE_PASSWORD,"Password:")      //case3：defined but not used

RES_ADD_STRING(TXT_WIFI_CONNECT_STATE_SETTING,"Connecting state")
RES_ADD_STRING(TXT_WIFI_AUTH_TYPE_WAPI,"WAPI")
//RES_ADD_STRING(TXT_WIFI_CONNECT_STATE_AUTO,"Audo")  //replaced by common ID TXT_AUTO
//RES_ADD_STRING(TXT_WIFI_CONNECT_STATE_MANUAL,"Manual")    //replaced by common ID TXT_MANUAL
RES_ADD_STRING(TXT_WIFI_WPAAUTH_PSK_STATE,"WPA Auth PSK type")
RES_ADD_STRING(TXT_WIFI_WAPI_SETTING,"WAPI Settings")
RES_ADD_STRING(TXT_WIFI_CERTIFICATE,"WAPI Certificate")
RES_ADD_STRING(TXT_WIFI_WAPI_CLIENT_CERTIFICATE,"WAPI client certificate")
RES_ADD_STRING(TXT_WIFI_WAPI_PARENT_CERTIFICATE,"WAPI parent certificate")
//RES_ADD_STRING(TXT_WIFI_WEP_KEY_INVALID,"Invalid WEP jey")       //case3：defined but not used
RES_ADD_STRING(TXT_WIFI_PROFILE_EXISTED,"AP existed")
RES_ADD_STRING(TXT_WIFI_WLAN_AUTO_CONNECT,"Auto conneting")
//RES_ADD_STRING(TXT_WIFI_AUTO_SEARCH_ON,"Enable")            //replaced by common ID TXT_COMMON_ENABLE_ON
//RES_ADD_STRING(TXT_WIFI_AUTO_SEARCH_OFF,"Disable")          //replaced by common ID TXT_CLOSE
//RES_ADD_STRING(TXT_WIFI_CLIENT_CERTIFICATE_INVALID,"Invalid client certificate")        //case3：defined but not used
//RES_ADD_STRING(TXT_WIFI_PARENT_CERTIFICATE_INVALID,"Invalid parent certificate")      //case3：defined but not used
RES_ADD_STRING(TXT_WIFI_CERTIFICATE_INVALID,"Invalid certificate")
RES_ADD_STRING(TXT_WIFI_TRUSTED_LIST_FULL,"Trustful list full")
//RES_ADD_STRING(TXT_WIFI_SURE_DELETE,"Detele?")     //replaced by common ID TXT_COMMON_CONFIRM_DELETE
//RES_ADD_STRING(TXT_WIFI_SURE_CLEAR,"Clear?")     //replaced by common ID TXT_COMMON_ENSURE_CLEAR
RES_ADD_STRING(TXT_WIFI_INPUT_NETNAME,"Please input name")
RES_ADD_STRING(TXT_WIFI_NETNAME_EXISTED,"Name existed")
RES_ADD_STRING(TXT_WIFI_REJECTLIST_FULL,"Reject list full")
//RES_ADD_STRING(TXT_WIFI_MAC_ADDRESS,"MAC address:")         //case3：defined but not used
RES_ADD_STRING(TXT_WLAN_UNINSTALL,"Uninstall")
RES_ADD_STRING(TXT_WLAN_UNINSTALL_QUERY,"Uninstall?")
RES_ADD_STRING(TXT_WLAN_UNINSTALL_SUCC,"Unistalled")
RES_ADD_STRING(TXT_WLAN_SCAN_FAIL,"network not found")
//RES_ADD_STRING(TXT_WLAN_NETWORK_TYPE,"WLAN Network Type")  //replaced by common ID TXT_COMM_NETWORK_TYPE

//RES_ADD_STRING(TXT_WLAN_AUTH_TYPE,"WLAN Auth Type")  //replaced by common ID TXT_COMM_SECURITY_TYPE
//RES_ADD_STRING(TXT_WLAN_AUTH_SETTING,"WLAN Auth Setting")  //replaced by common ID TXT_COMM_AUTH_SETTING
//RES_ADD_STRING(TXT_WLAN_HAS_OPEN,"WLAN Has Opened")  //replaced by common ID TXT_COMM_HAS_OPEN
//RES_ADD_STRING(TXT_WLAN_HAS_CLOSE,"WLAN Has Closed")  //replaced by common ID TXT_COMM_HAS_CLOSE
//RES_ADD_STRING(TXT_WLAN_OPENING,"WLAN Is Opening, Please Wait…")    //replaced by common ID TXT_OPENING_WLAN
//RES_ADD_STRING(TXT_WLAN_SCANING,"Scaning WLAN Network")    //replaced by common ID TXT_SCANING_WLAN 
//RES_ADD_STRING(TXT_WLAN_OPEN_FAIL,"Open Failed!")  //replaced by common ID TXT_COMM_OPEN_FAIL
//RES_ADD_STRING(TXT_WLAN_CLOSE_FAIL,"Close Failed!")       //replaced by common ID TXT_WIFI_WLAN_COMMON_CLOSE_FAIL
RES_ADD_STRING(TXT_WLAN_IS_DELETE_CONNECTED,"The WLAN Is Connected, This Option WLAN Disconnect The WLAN!")
//RES_ADD_STRING(TXT_WLAN_DETAIL_MODE,"WLAN Network Type:")  //replaced by common ID TXT_DETAIL_MODE
//RES_ADD_STRING(TXT_WLAN_LIST_NUM_FULL,"List full, can't display the searched WLAN! ")  //replaced by common ID TXT_COMMON_LIST_NUM_FULL
RES_ADD_STRING(TXT_WLAN_AUTH_SETTING_EMPTY,"Auth setting not complete")

RES_ADD_STRING(TXT_WLAN_PORTAL,"CMCC WLAN")
//RES_ADD_STRING(TXT_WLAN_LOGIN,"Login")  //replaced by common ID TXT_COMM_LOGIN
RES_ADD_STRING(TXT_WLAN_OFFLINE,"Offline")
RES_ADD_STRING(TXT_WLAN_REMEMBER_PASSWORD,"Remember password")
//RES_ADD_STRING(TXT_WLAN_AUTO_LOGIN,"Auto login")  //replaced by local common ID TXT_WLAN_AUTO_CERTIFICATE
RES_ADD_STRING(TXT_WLAN_PORTAL_ALERT_INPUT,"Please input user name and password")
RES_ADD_STRING(TXT_WLAN_PORTAL_LOGINING,"Login now, waiting please")
RES_ADD_STRING(TXT_WLAN_PORTAL_LOGOUTING,"Offline now, waiting please")
RES_ADD_STRING(TXT_WLAN_PORTAL_STATUS,"Your state:")
RES_ADD_STRING(TXT_WLAN_PORTAL_STATUS_CONNECTED,"-Connected-")
//RES_ADD_STRING(TXT_WLAN_PORTAL_STATUS_DISCONNECTED,"-Disconnected-")      //case3：defined but not used
RES_ADD_STRING(TXT_WLAN_PORTAL_INLINE_TIME,"Online time:")
RES_ADD_STRING(TXT_WLAN_PORTAL_INLINE_DESCRIPTION,"Online time just for information, please call 10086 for more information.")
RES_ADD_STRING(TXT_WLAN_PORTAL_DISCONNECT_QUERY,"Offline will disconnect network, whether offline")
RES_ADD_STRING(TXT_WLAN_PORTAL_HELP,"WLAN instruction:\n\
WLAN active:\n\
Please write short message \"KTWLAN\" send to 10086, will active WLAN.\n\
\n\
Password forget:\n\
If forget Password, please write short message \"CZWLANMM\" to 10086, will reset password.\n\
\n\
User login:\n\
On user login window, please input user and password, then press Login button.\n\
\n\
User login option:\n\
Remember password:if select, will remember login password.\n\
Auto login:if select, when handset connect CMCC WLAN, will auto login.\n\
\n\
Offline:\n\
Press offline button, will disconnect CMCC WLAN connection.\n\
\n\
Hide:\n\
Press hide button, will hide user login window.")
//RES_ADD_STRING(TXT_WLAN_PORTAL_OPEN_WLAN_FAIL,"WLAN open fail")  //replaced by common ID TXT_COMM_OPEN_FAIL
RES_ADD_STRING(TXT_WLAN_PORTAL_FIND_CMCC_AP_FAIL,"CMCC AP not exist")
RES_ADD_STRING(TXT_WLAN_PORTAL_FIND_CMCC_CONNECT_FAIL,"CMCC AP connect fail")
RES_ADD_STRING(TXT_WLAN_PORTAL_SUCCESS,"Login success")
RES_ADD_STRING(TXT_WLAN_PORTAL_USER_ERROR,"User not register")
//RES_ADD_STRING(TXT_WLAN_PORTAL_USER_ABNORMAL_STATE,"User in abnormal state")      //case3：defined but not used
RES_ADD_STRING(TXT_WLAN_PORTAL_PWD_ERROR,"Password error")
//RES_ADD_STRING(TXT_WLAN_PORTAL_IP_NOT_MATCH,"Your IP is not match")        //case3：defined but not used
//RES_ADD_STRING(TXT_WLAN_PORTAL_AC_NOT_MATCH,"AC name is not match")        //case3：defined but not used
//RES_ADD_STRING(TXT_WLAN_PORTAL_PORTAL_REJECT,"Login reject")       //case3：defined but not used
//RES_ADD_STRING(TXT_WLAN_PORTAL_PORTALING,"The user is portal now")       //case3：defined but not used
//RES_ADD_STRING(TXT_WLAN_PORTAL_USER_CONFLICT,"User name confilct")     //case3：defined but not used
//RES_ADD_STRING(TXT_WLAN_PORTAL_UNPORTAL_EXPIRED,"Unportal expired")     //case3：defined but not used
RES_ADD_STRING(TXT_WLAN_PORTAL_FAILED_OTHER,"Login fail, please call 10086 for more information")
RES_ADD_STRING(TXT_WLAN_PORTAL_OFFLINE_SUCCESS,"Offline success")
//RES_ADD_STRING(TXT_WLAN_PORTAL_OFFLINE_AUTO_OFFLINE,"Auto offline, because of exceeding time remain")       //case3：defined but not used
//RES_ADD_STRING(TXT_WLAN_PORTAL_OFFLINE_REJECT,"Offline reject")       //case3：defined but not used
//RES_ADD_STRING(TXT_WLAN_PORTAL_DISCONNECTED,"WLAN disconnect")       //replaced by common ID TXT_COMMON_LINK_DISCONNECTED
RES_ADD_STRING(TXT_WLAN_PORTAL_HAS_PORTALED,"The handset has login, donot need login again")
RES_ADD_STRING(TXT_WIFI_ACTIVE_SERVICE,"Activce")
RES_ADD_STRING(TXT_WIFI_ACTIVE_SERVICE_HELP,"WLAN active:\n\
Please write short message \"KTWLAN\" send to 10086, will active WLAN.")
RES_ADD_STRING(TXT_WIFI_SUBSCRIBE,"Subscribe")
RES_ADD_STRING(TXT_WIFI_SUBSCRIBE_SERVICE_HELP,"WLAN Subscribe:\n\
Please Connect 10086 to subscribe")
RES_ADD_STRING(TXT_WIFI_MODIFY_PASSWORD_HELP,"WLAN Modify password:\n\
please send short message \"CZWLANMM\" to 10086")
RES_ADD_STRING(TXT_WIFI_LOGIN_NOTIFICATION,"Auto login notification")
RES_ADD_STRING(TXT_WIFI_LOGIN_QUERY,"将要接入收费WLAN网络是否继续")
RES_ADD_STRING(TXT_WLAN_PORTAL_SMS_REPLY,"Please check reply SMS")
RES_ADD_STRING(TXT_WLAN_RESET_PASSWORD,"Password reset")
RES_ADD_STRING(TXT_WLAN_ACCOUNT_OPERATION,"Operation on WLAN account of crrent sim,continue?")
RES_ADD_STRING(TXT_WLAN_GPRSTOWLAN_RESELCT,"GPRS->WLAN reselect")
RES_ADD_STRING(TXT_WLAN_AUTO_RESELCT,"Auto reselect")
RES_ADD_STRING(TXT_WLAN_MANUAL_RESELCT,"Manual reselect")
RES_ADD_STRING(TXT_WLAN_ALWAYS_INQUIRY,"Alaways inquiry")

RES_ADD_STRING(TXT_WLAN_AP_RESELCT,"Different AP auto reselect")
RES_ADD_STRING(TXT_WLAN_NO_WLAN_USEGPRS,"Use GPRS when WLAN is not avaible")

RES_ADD_STRING(TXT_WLAN_SELECT_AP,"Select access point")
RES_ADD_STRING(TXT_WLAN_FIND_WLAN_NOTIFY_HEAD,"WLAN signal found")
RES_ADD_STRING(TXT_WLAN_CHANGE_TO_CHINAMOBILE_NET,"WLAN network has been disconnected, whether to use the mobile network?")
RES_ADD_STRING(TXT_WLAN_FIND_WLAN_NOTIFY_TAIL,", use WLAN network? It maybe will interrupt some data services.")
RES_ADD_STRING(TXT_WLAN_UPDATE,"Update")
RES_ADD_STRING(TXT_WLAN_UPDATE_FAIL,"Upgrade file doesn't exist or invalid format")
RES_ADD_STRING(TXT_WLAN_UPDATE_SUCCESS,"Updated")
RES_ADD_STRING(TXT_WLAN_UPDATE_UPDATED,"Upgraded verison is lower than current vision")

RES_ADD_STRING(TXT_WLAN_SWITCH,"WLAN Switch")
RES_ADD_STRING(TXT_WLAN_LOGIN_CHAEGE_QUERY,"Connect WLAN network")
RES_ADD_STRING(TXT_WLAN_LOGIN_NEVER_NOTIFY,"Auto login without notification")
RES_ADD_STRING(TXT_WLAN_AUTO_CERTIFICATE,"CMCC WLAN auto certificate")
//RES_ADD_STRING(TXT_WLAN_RESET,"恢复默认设置")  //replaced by common ID TXT_RESET_DEFAULT
RES_ADD_STRING(TXT_WLAN_PORTAL_ACCOUNT,"Save username/password")
RES_ADD_STRING(TXT_WLAN_AP_STATUS,"Status:")
//RES_ADD_STRING(TXT_WLAN_CONNECTED,"已连接")  //replaced by common ID TXT_COMMON_CONNECTED
//RES_ADD_STRING(TXT_WLAN_UNCONNECTED,"未连接")  //replaced by common ID TXT_DISCONNECTED

RES_ADD_STRING(TXT_WLAN_ADD_AP,"Add WLAN network")
RES_ADD_STRING(TXT_WLAN_FORGET_AP,"Unsave")
//RES_ADD_STRING(TXT_WLAN_WEP_KEY_RANGE,"Please Input 5 or 13 Characters")      //case3：defined but not used
RES_ADD_STRING(TXT_WLAN_INVALID_PROXY,"Please Input Proxy Address")
RES_ADD_STRING(TXT_WIFI_NOT_IN_RANGE,"Not In Range")


RES_ADD_STRING(TXT_QUIT_WIFI,"Wifi has opened, Pls quit")

#ifdef WLAN_EAP_SUPPORT
RES_ADD_STRING(TXT_WLAN_EAP_SIM,"802.1x EAP")
RES_ADD_STRING(TXT_WLAN_EAP_METHOD,"EAP Method")
RES_ADD_STRING(TXT_WLAN_SIM,"SIM")
#endif
#ifdef ADULT_WATCH_SUPPORT
RES_ADD_STRING(TXT_WLAN_CONNECT_NETWORK,"Connect network?")
RES_ADD_STRING(TXT_WLAN_DISCONNECT_NETWORK,"Disconnect network?")
#endif
