//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DspLogger.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW_KEYINFO            101
#define IDD_GRAPH_GRAPH_PROP_PAGE       102
#define IDD_GRAPH_AXIS_PROP_PAGE        103
#define ID_INDICATOR_STATE              104
#define IDD_GRAPH_GRAPHICS_PROPS        105
#define IDC_TP_CHART_WND                106
#define IDR_MAINFRAME                   128
#define IDR_DSPLOGTYPE                  129
#define IDR_CHART                       130
#define IDR_FIND                        131
#define IDD_GRAPH_CHANGE_TITLE          132
#define IDI_RSSI                        133
#define IDD_TESTPOINT                   134
#define IDD_SETCOM_DLG                  135
#define IDR_LIST_POP                    136
#define IDD_DLG_FIND_TP                 137
#define IDD_DLG_TP_ADDR_DESC            138
#define IDD_DLG_ADDR_SAMPLE             139
#define IDD_DLG_GOTO_ITEM               140
#define IDD_DLG_ADD_ADDR_DESC           141
#define IDD_DIALOG_MARK                 142
#define IDD_DIALOG_TACKLE               143
#define IDD_DIALOG_EXPORT               144
#define IDD_DLG_CHART                   145
#define IDD_DLG_FIND                    146
#define IDD_DLG_CHART_CTRL              147
#define IDC_CUR_ARROW                   148
#define IDD_DIALOG_FIND_TESTPOINT       149
#define IDD_DIALOG_MONITOR              150
#define IDD_DIALOG_FILTERCTRL           151
#define IDD_DIALOG_MASK                 152
#define IDD_DIALOG_FORMULA              153
#define IDR_FILTER                      154
#define IDD_DLG_REPLAY_SETTING          155
#define IDD_EDT_BTN_DLG                 156
#define IDR_MEM_FIR                     157
#define IDR_MEM_SEC                     158
#define IDR_MEM_THI                     159
#define IDD_DLG_PLAYBACK_ORG            160
#define IDD_DLG_SAVE_SETTING            161
#define IDR_KEYINFO                     206
#define IDD_DIALOG_IMPORT               212
#define IDC_GRAPH_TITLE                 1002
#define IDC_GRAPH_CH_TITLE              1003
#define IDC_GRAPH_CH_COLOR              1004
#define IDC_TITLE_STRING                1005
#define IDC_X1                          1006
#define IDC_X2                          1007
#define IDC_Y1                          1008
#define IDC_Y2                          1009
#define IDC_TESTPT_LIST                 1010
#define IDC_GEN_GRAPH_PROPS_AXIS        1011
#define IDC_XTITLE                      1012
#define IDC_XUOM                        1013
#define IDC_GRAPH_CHOICE                1014
#define IDC_YTITLE                      1015
#define IDC_YUOM                        1016
#define IDC_GRAPH_HIDESHOW              1017
#define IDC_EDIT_INDEX                  1018
#define IDC_GRAPH_POINTMARKS            1019
#define IDC_EDIT_MARK                   1020
#define IDC_EDIT_FILTER                 1021
#define IDC_GRAPH_MOUSECOORDS           1022
#define IDC_EDIT_FROM                   1023
#define IDC_XAXIS_PRECISION             1024
#define IDC_EDIT_LOG_PATH               1025
#define IDC_GRAPHS_SHOWALL              1026
#define IDC_YAXIS_PRECISION             1027
#define IDC_EDIT_SRC                    1028
#define IDC_EDIT_COUNT                  1030
#define IDC_EDIT_DES                    1031
#define IDC_RADIO_UP                    1032
#define IDC_RADIO_UNSIGNED              1033
#define IDC_RADIO_CUR_FILE              1034
#define IDC_RADIO_DOWN                  1035
#define IDC_RADIO_SIGNED                1036
#define IDC_RADIO_CHOOSE_FILE           1037
#define IDC_BUTTON_LOAD                 1038
#define IDC_EDIT_DESC                   1039
#define IDC_BUTTON_SEARCH               1039
#define IDC_BUTTON_BROWSE               1040
#define IDC_BUTTON_BROWSE_SRC           1041
#define IDC_EDIT_EXPORT_FROM            1042
#define IDC_EDIT_EXPORT_TO              1043
#define IDC_COMBO_BAUDRATE              1044
#define IDC_COMBO_PORT                  1045
#define IDC_EDIT_ADDR                   1046
#define IDC_COMBO_ENDIAN                1046
#define IDC_EDIT_DATA                   1047
#define IDC_COMBO_ADDR                  1048
#define IDC_COMBO_DATA                  1049
#define IDC_LIST_DESC                   1050
#define IDC_BUTTON_ADD                  1051
#define IDC_BUTTON_SAVE                 1052
#define IDC_BUTTON_DEL                  1053
#define IDC_LIST_ITEM                   1054
#define IDC_BUTTON_ADD2                 1055
#define IDC_BUTTON_MODIFY               1056
#define IDC_BUTTON_DEL2                 1057
#define IDC_STATIC_CHART                1058
#define IDC_SLIDER_VERT                 1059
#define IDC_SLIDER_HORZ                 1060
#define IDC_LIST_MARKS                  1061
#define IDC_COMBO_SAMPLE_ADDR           1062
#define IDC_RADIO_BYTIME                1063
#define IDC_RADIO_BYINDEX               1064
#define IDC_STATIC_FILTER_STRING        1065
#define IDC_RADIO_BACKWARD              1066
#define IDC_RADIO_FORWARD               1067
#define IDC_BUTTON_BROWSE_DES           1068
#define IDC_RADIO_ALL                   1069
#define IDC_RADIO_RECENT                1070
#define IDC_RADIO_CURRENT               1071
#define IDC_RADIO_RANGE                 1072
#define IDC_STATIC_VERSION              1073
#define IDC_STATIC_BUILD                1074
#define IDC_BTN_COLOR                   1075
#define IDC_STC_COLOR                   1076
#define IDC_CMB_ADDR                    1077
#define IDC_EDT_ADDR                    1078
#define IDC_CMB_DATA                    1079
#define IDC_EDT_DATA                    1080
#define IDC_LST_INFO                    1081
#define IDC_BTN_ADD                     1082
#define IDC_BTN_DEL                     1083
#define IDC_BTN_FIND                    1084
#define IDC_EDT_NUM                     1085
#define IDC_SPN_NUM                     1086
#define IDC_SLIDER_H                    1087
#define IDC_SLIDER_V                    1088
#define IDC_RDO_UNSIGNED                1089
#define IDC_RDO_SIGNED                  1090
#define IDC_RDO_BYTIME                  1091
#define IDC_RDO_BYIDX                   1092
#define IDC_LST_FIND                    1093
#define IDC_CHECK_DRAWTP                1094
#define IDC_CHECK_DRAWTOGETHER          1095
#define IDC_BUTTON_RESET                1096
#define IDC_BUTTON_STARTORSTOP          1097
#define IDC_BUTTON_REMOVE               1098
#define IDC_BUTTON_INCREASE             1099
#define IDC_BUTTON_DECREASE             1100
#define IDC_EDIT_TIMERANGE              1101
#define IDC_BUTTON_YDECREASE            1102
#define IDC_BUTTON_YINCREASE            1103
#define IDC_EDIT_YRANGE                 1104
#define IDC_BUTTON_MONITOR              1105
#define IDC_CHECK_TESTPOINT             1106
#define IDC_CHECK_TRACEMOUSE            1107
#define IDC_BUTTON_UPDATALIST           1108
#define IDC_BUTTON_SHOWLIST             1109
#define IDC_EDIT_TPNUM                  1110
#define IDC_SPIN_TPNUM                  1111
#define IDC_RADIO_SAVEALL               1112
#define IDC_RADIO_SAVERCT               1113
#define IDC_EDIT_LOGNAME                1114
#define IDC_CHECK_USESAMEY              1115
#define IDC_BUTTON_CLEAR                1116
#define IDC_BUTTON_TEST                 1117
#define IDC_RADIO_MODE1                 1118
#define IDC_RADIO_MODE2                 1119
#define IDC_LIST_MODE1                  1120
#define IDC_LIST_MATHFML                1121
#define IDC_LIST_MODE2                  1122
#define IDC_EDIT_FORMULA                1123
#define IDC_EDIT_MASK1                  1124
#define IDC_EDIT_FML                    1125
#define IDC_EDIT_MASK2                  1126
#define IDC_RADIO_16                    1127
#define IDC_RADIO_32                    1128
#define IDC_BUTTON_AUTO                 1129
#define IDC_BUTTON_EXPORT               1130
#define IDC_SPIN_SPACE                  1131
#define IDC_EDIT_SPACE                  1132
#define IDC_CHECK_MASK                  1133
#define IDC_EDIT_MASK                   1134
#define IDC_CHECK_MULT                  1135
#define IDC_EDIT_MULT                   1136
#define IDC_BUTTON_HIDE                 1137
#define IDC_BUTTON_FITPAGE              1138
#define IDC_BUTTON_FITHEIGHT            1139
#define IDC_BUTTON_WIDTH                1140
#define IDC_EDIT_STARTPOS               1141
#define IDC_BUTTON_START                1142
#define IDC_BUTTON_CLEARGRAPH           1143
#define IDC_RADIO_POINT                 1144
#define IDC_RADIO_DRAG                  1145
#define IDC_RADIO_ZOOM                  1146
#define IDC_CMB_EXPORT_TO               1147
#define IDC_CHECK_AUTOSCROLL            1148
#define IDC_RADIO_UART                  1149
#define IDC_RADIO_SOCKET                1150
#define IDC_IPADDRESS                   1151
#define IDC_EDIT_PORT                   1152
#define IDC_EDT_CURVE_NUM               1153
#define IDC_BUTTON_CHANGE               1154
#define IDC_EDT_REPLAY_FROM             1155
#define IDC_EDT_REPLAY_TO               1156
#define IDC_EDT_TEXT                    1157
#define IDC_EDT_ADDR_LEFT               1158
#define IDC_EDT_ADDR_RIGHT              1159
#define IDC_EDT_DATA_LEFT               1160
#define IDC_EDT_DATA_RIGHT              1161
#define IDC_CHECK_DUALITY               1162
#define IDC_EDIT_FRAME_HEAD             1163
#define IDC_EDIT_BAUDRATE               1164
#define IDC_GENERATE_TP_TIME            1165
#define IDC_EDT_ORG_PATH                1166
#define IDC_GENERATE_ORG_FILE           1167
#define IDC_EDT_TP_DIRECTORY            1168
#define IDC_STATIC_PORMPT               1169
#define IDC_BTN_BROWSE_ORG              1170
#define IDC_BTN_BROWSE_TP               1171
#define IDC_CHECK_DESC                  1172
#define IDC_EDT_DESC                    1173
#define IDC_COMBO_MATCH                 1232
#define IDC_LIST_GSM_INFO               1234
#define IDC_LIST_TD_INFO                1236
#define IDC_STC_CONS_DIAG               1238
#define IDC_STC_CHANNEL_IMPULE          1239
#define IDC_STC_IMPULSE                 1241
#define IDC_BTN_IMPULSE                 1242
#define IDC_STC_CONST                   1243
#define IDC_RADIO_LOG                   1243
#define IDC_BTN_CONST                   1244
#define IDC_RADIO_ORG                   1244
#define IDC_RADIO_GENERATE_TP_TIME_BY_D0A0 1244
#define IDC_RADIO_GENERATE_TP_TIME_BY_TOOL 1245
#define IDC_RADIO_GENERATE_TP_TIME_BY_PHONE 1246
#define IDC_EDIT_IMPORT_PATH            1246
#define IDC_BUTTON_IMPORT_BROWSE        1247
#define IDC_CHECK_CONVERT_TIME          1248
#define IDC_RDO_COMMON                  1249
#define IDC_RDO_LTE                     1250
#define IDC_RDO_TG                      1251
#define IDC_RDO_WCDMA                   1252
#define IDC_CHK_DESCRIPTION             1253
#define IDC_EDT_SEARCH_DESC             1254
#define IDC_CHK_UNFILTER_ADDRESS        1255
#define IDC_RDO_AGDSP                   1256
#define IDC_LST_CUSTOMIZE_CHART         1257
#define ID_RSSI_PAUSE                   32771
#define ID_RSSI_RESET                   32772
#define ID_RSSI_HISTOGRAM               32773
#define ID_RSSI_HEX_RSSI                32774
#define ID_RSSI_RELATIVE_TIME           32775
#define ID_CONNECT_DSP                  32827
#define ID_DISCONNECT_DSP               32828
#define ID_CLEAR                        32830
#define ID_SETTINGS                     32832
#define ID_AUTO_SCROLL                  32833
#define ID_FIND_TP                      32835
#define ID_FIND_NEXT_TP                 32836
#define ID_FIND_NEXT_TP_R               32837
#define ID_START                        32838
#define ID_EDIT_ADDR_DESC               32839
#define ID_TP_ADDR_CHART                32840
#define ID_STOP                         32851
#define ID_PAUSE                        32852
#define ID_FILE_EXPORT                  32853
#define ID_SHOW_ALL                     32854
#define ID_ACT_CONNECT                  32855
#define ID_FILTER                       32857
#define ID_SHOW_FIND                    32858
#define ID_FIND_CLOSE                   32859
#define ID_FILE_CONVERT                 32860
#define ID_SHOW_CHART_CTRL              32861
#define ID_MARK_MARK                    32867
#define ID_FILE_SAVETP                  32869
#define ID_FILTER_TP                    32870
#define IDR_EXIT                        32872
#define IDR_CHARTCTRL                   32873
#define ID_PLAYBACK_ORG                 32874
#define ID_KEYINFO                      32875
#define ID_TP_FIND                      41001
#define ID_TP_FIND_UP                   41002
#define ID_TP_FIND_DOWN                 41003
#define ID_GOTO_ITEM                    41004
#define ID_UNMARK_ITEM                  41005
#define ID_MARK_ITEM                    41006
#define ID_MARK_UNMARK_ITEM             41007
#define ID_NEXT_MARK                    41008
#define ID_PRE_MARK                     41009
#define ID_REMOVE_ALL_MARKS             41010
#define ID_GOTO_MARK                    41011
#define ID_FILE_OPEN2                   57608
#define ID_INDICATOR_MEM                59142
#define ID_INDICATOR_DUMP               59143
#define ID_CONTENT_BAR                  61447
#define IDS_CONNECT_FAILED              61448
#define IDS_EMPTY_BUFFER                61449
#define IDS_BUFSIZE_ERROR               61450
#define IDS_FAILED_SEND_CMD             61451
#define IDS_NOT_FOUND                   61452
#define IDS_CANT_CLOSE                  61453
#define IDS_REMOVE_ITEM                 61454
#define IDS_TP_ADDR_DESC_DUPLICATE      61455
#define IDS_EXPORT_FILE_FAIL            61456
#define IDS_ACCESS_LOG_PATH_FAIL        61458
#define IDS_SOCKET_FAILED               61459

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         1258
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
