/*****************************************************************************
** File Name:      mmipb_id.h                                                *
** Author:                                                                   *
** Date:           2006/09/26                                                *
** Copyright:      2006 Spreadtrum, Incorporated. All Rights Reserved.        *
** Description:    This file is used to describe pb win and control id       *
******************************************************************************
**                         Important Edit History                            *
** --------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                               *
** 2006/09/26     kelly.li        Create                                    *
******************************************************************************/

#ifndef _MMIPB_ID_H_
#define _MMIPB_ID_H_ 

/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
#include "sci_types.h"
#include "os_api.h"
#include "mmk_type.h"
#include "mmi_module.h"

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif

/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/


/**--------------------------------------------------------------------------*
 **                         TYPE AND CONSTANT                                *
 **--------------------------------------------------------------------------*/

#define WIN_ID_DEF(win_id)          win_id
// window ID
typedef enum
{
    MMI_PB_WIN_ID_START = (MMI_MODULE_PB << 16),

#include "mmipb_id.def"


    MMIPB_MAX_WIN_ID
}MMIPB_WINDOW_ID_E;

#undef WIN_ID_DEF

// control ID
typedef enum
{
    MMIPB_CTRL_ID_START = MMIPB_MAX_WIN_ID, //(MMI_MODULE_PB << 16),
    //PHONEBOOK
    MMIPB_MEMBER_OPT_CTRL_ID,				//member option
    MMIPB_ADD_OPT_CTRL_ID,           //copy option
	
	MMIPB_GROUP_ENTRY_LIST_CTRL_ID,	
	MMIPB_GROUP_ENTRY_ADD_CTRL_ID,
    MMIPB_SEARCH_OPERATE_MENU_CTRL_ID,		//
  
    MMIPB_CONTACT_SEARCH_WIN_FORM_ID,
    MMIPB_CHILD_CONTACT_SEARCH_WIN_FORM_ID,
    MMIPB_CHILD_CONTACT_SEARCH_EDIT_FORM_ID,
    MMIPB_ENTRY_SEARCH_BUTTON_CTRL_ID,
    MMIPB_CONTACT_SEARCH_EDITBOX_CTRL_ID,
    MMIPB_CHILD_SELECT_TITLE_CTRL_ID,
    MMIPB_CHILD_SELECT_BUTTON_CTRL_ID,
    MMIPB_ENTRY_LISTBOX_CTRL_ID,

    MMIPB_SINGLE_GROUP_CONTACT_SEARCH_WIN_FORM_ID,
    MMIPB_SINGLE_GROUP_ENTRY_LISTBOX_CTRL_ID,
    MMIPB_CHILD_SINGLE_GROUP_CONTACT_SEARCH_WIN_FORM_ID,
    MMIPB_CHILD_SINGLE_GROUP_CONTACT_SEARCH_EDIT_FORM_ID,
    MMIPB_SINGLE_GROUP_ENTRY_SEARCH_BUTTON_CTRL_ID,
    MMIPB_SINGLE_GROUP_CONTACT_SEARCH_EDITBOX_CTRL_ID,
    MMIPB_CHILD_SINGLE_GROUP_SELECT_TITLE_CTRL_ID,
    MMIPB_CHILD_SINGLE_GROUP_SELECT_BUTTON_CTRL_ID,


    MMIPB_NAME_SEARCH_CONTACT_SEARCH_WIN_FORM_ID,
    MMIPB_CHILD_NAME_SEARCH_CONTACT_SEARCH_EDIT_FORM_ID,
    MMIPB_NAME_SEARCH_ENTRY_SEARCH_BUTTON_CTRL_ID,
    MMIPB_NAME_SEARC_CONTACT_SEARCH_EDITBOX_CTRL_ID,
    MMIPB_CHILD_NAME_SEARC_TITLE_CTRL_ID,

    MMIPB_EDITBOX_MORE_SWITCH_FORM_ID,
    MMIPB_EDITBOX_MORE_SWITCH_LIST_ID,
    //@maggie add begin for 6800A PB
    MMIPB_SEARCH_BUTTON0_CTRL_ID,
    MMIPB_SEARCH_BUTTON1_CTRL_ID,
    MMIPB_SEARCH_BUTTON2_CTRL_ID,
    MMIPB_SEARCH_BUTTON3_CTRL_ID,
    MMIPB_SEARCH_BUTTON4_CTRL_ID,
    MMIPB_SEARCH_BUTTON5_CTRL_ID,
    MMIPB_SEARCH_BUTTON6_CTRL_ID,
    MMIPB_SEARCH_BUTTON7_CTRL_ID,
	MMIPB_SEARCH_BUTTON8_CTRL_ID,
    MMIPB_SEARCH_BUTTON9_CTRL_ID,

    //@maggie add end   for 6800A PB
    MMIPB_EDITBOX_CTRL_ID,
  /*  
    MMIPB_ADD_IN_SIM_NAME_EDITBOX_CTRL_ID,
    MMIPB_ADD_IN_SIM_PHONE_EDITBOX_CTRL_ID,
    MMIPB_ADD_IN_NV_GROUP_LISTBOX_CTRL_ID,    // add group name in nv entry
    MMIPB_ADD_IN_NV_NAME_EDITBOX_CTRL_ID,
    MMIPB_ADD_IN_NV_PHONE_EDITBOX_CTRL_ID,
    MMIPB_ADD_IN_NV_MAIL_EDITBOX_CTRL_ID,
    MMIPB_ADD_IN_NV_CUSTOM_MEMO_EDITBOX_CTRL_ID,
    MMIPB_ADD_IN_NV_ORG_EDITBOX_CTRL_ID,
    MMIPB_ADD_IN_NV_COMPANY_EDITBOX_CTRL_ID,
    MMIPB_ADD_IN_NV_WORKADR_EDITBOX_CTRL_ID,  
*/
	//Rush Search
	MMIPB_RUSH_SEARCH_LABEL_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_1_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_2_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_3_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_4_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_5_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_6_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_7_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_8_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_9_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_10_CTRL_ID,
	MMIPB_RUSH_SEARCH_LABEL_11_CTRL_ID,
	MMIPB_ENTRY_ALL_LISTBOX_CTRL_ID,
	MMIPB_ENTRY_ONE_LISTBOX_CTRL_ID,
    MMIPB_ENTRY_DETAIL_LISTBOX_CTRL_ID,
    MMIPB_ENTRY_DETAIL_TEXTBOX_CTRL_ID,
    
    MMIPB_SELECT_NUM_TYPE_LISTBOX_CTRL_ID,
    MMIPB_COPY_OR_NOT_MSGBOX_CTRL_ID,
    
    MMIPB_USED_SPACE_LISTBOX_CTRL_ID,

    //MSISDN
    MMIPB_MSISDN_LISTBOX_CTRL_ID,
    MMIPB_MSISDN_DETAIL_LISTBOX_CTRL_ID,
    MMIPB_MSISDN_NAME_EDITBOX_CTRL_ID,
    MMIPB_MSISDN_PHONE_EDITBOX_CTRL_ID,

    // 分组管理
    MMIPB_GROUP_SETTING_MENU_CTRL_ID,
    MMIPB_GROUP_MANAGE_LISTBOX_CTRL_ID,
    MMIPB_GROUP_MEMBER_LIST_LISTBOX_CTRL_ID,
    MMIPB_GROUP_MEMBER_OPERATE_MENU_CTRL_ID,
    MMIPB_GROUP_MEMBER_ADD_NAME_LIST_LISTBOX_CTRL_ID,
    MMIPB_GROUP_NAME_LISTBOX_CTRL_ID,
    MMIPB_GROUP_ICON_LISTBOX_CTRL_ID,
   // MMIPB_GROUP_RING_LISTBOX_CTRL_ID,
    
    MMIPB_GROUP_NAME_EDITBOX_CTRL_ID,

    // GROUP LIST CTRL FOR SMS
    MMIPB_GROUP_LIST_FOR_SMS_LISTBOX_CTRL_ID,
    MMIPB_SELECT_NUM_TYPE_FOR_SMS_LISTBOX_CTRL_ID,

    // ENTRY LIST CTRL FOR CALLLOG
    MMIPB_ENTRY_LIST_FOR_CALLLOG_LISTBOX_CTRL_ID,

    MMIPB_OPERATE_SELECT_FORM_CTRL_ID,
    MMIPB_CHILD_TITLE_OPERATE_SELECT_FORM_CTRL_ID,
    MMIPB_CHILD_SEARCH_OPERATE_SELECT_FORM_CTRL_ID,
    MMIPB_SEARCH_BUTTON_CTRL_ID,
    MMIPB_OPERATE_SEL_SEARCH_EDITBOX_CTRL_ID,
    MMIPB_SELECT_ALL_BUTTON_CTRL_ID,
    MMIPB_TITLE_CTRL_ID,
    MMIPB_OK_BUTTON_CTRL_ID,
    MMIPB_CANCEL_BUTTON_CTRL_ID,
    
    MMIPB_OPERATE_SEL_LISTBOX_CTRL_ID,
    MMIPB_ENTRY_LIST_EX_FORM_CTRL_ID,
    MMIPB_CHILD_ENTRY_LIST_EX_FORM_CTRL_ID,
    MMIPB_ENTRY_EX_SEARCH_EDITBOX_CTRL_ID,
    MMIPB_ENTRY_EX_SEARCH_BUTTON_CTRL_ID,
    MMIPB_ENTRY_LIST_FOR_EX_LISTBOX_CTRL_ID,
    MMIPB_SELECT_NUM_TYPE_FOR_CALLLOG_LISTBOX_CTRL_ID,

    // 存储容量
    MMIPB_MEMDETAIL_LABEL1_CTRL_ID,
    MMIPB_MEMDETAIL_LABEL2_CTRL_ID,
    MMIPB_MEMDETAIL_LABEL3_CTRL_ID,    
    MMIPB_MEMDETAIL_LABEL4_CTRL_ID,    
    MMIPB_MEMDETAIL_LABEL5_CTRL_ID,    
    MMIPB_MEMDETAIL_LABEL6_CTRL_ID, 
    MMIPB_MEMDETAIL_LABEL7_CTRL_ID,    
    MMIPB_MEMDETAIL_LABEL8_CTRL_ID,    
    MMIPB_MEMDETAIL_LABEL9_CTRL_ID,
    MMIPB_MEMDETAIL_LABEL10_CTRL_ID,
    MMIPB_MEMDETAIL_FORM_CTRL_ID,
    MMIPB_MEMDETAIL_ANIM1_CTRL_ID,
    MMIPB_MEMDETAIL_ANIM2_CTRL_ID,
    MMIPB_MEMDETAIL_ANIM3_CTRL_ID,
    MMIPB_MEMDETAIL_ANIM4_CTRL_ID,
    MMIPB_MEMDETAIL_ANIM5_CTRL_ID,
 

    //发送菜单窗口menu id
    MMIPB_SEND_MENU_WIN_MENU_CTRL_ID,    

    //复制菜单窗口menu id
    MMIPB_COPY_MENU_WIN_MENU_CTRL_ID,    

    //alert info
    MMIPB_ALERT_INFO_MSGBOX_CTRL_ID,

    //WAITING PS RESPONSE
    MMIPB_WAITING_MSGBOX_CTRL_ID,
    //END PHONEBOOK

//@zhaohui add for fdn start
    MMIPB_FDN_LIST_CTRL_ID,
    MMIPB_FDN_OPTION_CTRL_ID,
    MMIPB_FDN_ADD_CTRL_ID,
    MMIPB_FDN_DETAIL_CTRL_ID,

   // Tab ctl IDs {
   MMIPB_SEARCH_LIST_TAB_CTRL_ID,
   MMIPB_SEARCH_ANIM_CTRL_ID,
   MMIPB_ADD_IN_NV_RICHTEXT_CTRL_ID,
   MMIPB_ADD_IN_SIM_RICHTEXT_CTRL_ID,
   MMIPB_SEARCH_NAME_EDITBOX_CTRL_ID,
   
#ifdef ASP_SUPPORT
   MMIPB_ASP_SET_PLAYFILE_CTRL_ID,
#endif
   //Tab ctl IDs }
   //Form
   MMIPB_EDITBOX_FORM_ID,
   MMIPB_NAME_FORM_ID,
   MMIPB_NAME_SUB_FORM_ID,
  // MMIPB_NAME_PHOTO_SUB_FORM_ID,
   MMIPB_NAME_EDIT_SUB_FORM_ID,
   MMIPB_NAME_EDIT_SUB_UP_FORM_ID,
   MMIPB_NAME_EDIT_SUB_DOWN_FORM_ID,
   MMIPB_EDITBOX_NUMBER_FORM_ID,

   
   MMIPB_FORM_NUM1_ID,
   MMIPB_FORM_NUM2_ID,
   MMIPB_FORM_NUM3_ID,
   MMIPB_FORM_NUM4_ID,
   MMIPB_FORM_NUM5_ID,
   MMIPB_FORM_NUM1_SUB_ID,
   MMIPB_FORM_NUM2_SUB_ID,
   MMIPB_FORM_NUM3_SUB_ID,
   MMIPB_FORM_NUM4_SUB_ID,
   MMIPB_FORM_NUM5_SUB_ID,
   
   MMIPB_EMAIL_FORM_ID,

   MMIPB_EMAIL_SUB_FORM_ID,

   MMIPB_IM_FORM_ID,
   MMIPB_IM_SUB_FORM_ID,
   MMIPB_IM_LABEL_ID,
   MMIPB_IM_EDIT_ID,
   MMIPB_ALIAS_FORM_ID,
   MMIPB_ASP_FORM_ID,
   MMIPB_PHOTO_FORM_ID,
   MMIPB_RING_FORM_ID,
   MMIPB_GROUP_FORM_ID,
   MMIPB_MEMO_FORM_ID,
  
   MMIPB_COM_FORM_ID,
   MMIPB_COM_SUB_FORM_ID,
   MMIPB_COM_EDIT_FORM_ID,
    
    MMIPB_ALIAS_SUB_FORM_ID,
   MMIPB_ASP_SUB_FORM_ID,
    MMIPB_PHOTO_SUB_FORM_ID,
   MMIPB_RING_SUB_FORM_ID,
   MMIPB_GROUP_SUB_FORM_ID,
   MMIPB_MEMO_SUB_FORM_ID,
   MMIPB_TITLE_SUB_FORM_ID,
  
    MMIPB_ADDR_FORM_ID,
    MMIPB_ADDR_SUB_FORM_ID,
   MMIPB_LABEL_ADDRESS_ID,

   //label
    MMIPB_LABEL_NAME_ID,
   MMIPB_LABEL_ALIAS_ID,
   MMIPB_NUM1_LABEL_ID,
   MMIPB_NUM2_LABEL_ID,
   MMIPB_NUM3_LABEL_ID,
   MMIPB_NUM4_LABEL_ID,
   MMIPB_NUM5_LABEL_ID,

    MMIPB_NUM1_LABEL_FORM_ID,
    MMIPB_NUM2_LABEL_FORM_ID,
    #ifndef PB_SUPPORT_LOW_MEMORY													
    MMIPB_NUM3_LABEL_FORM_ID,
    MMIPB_NUM4_LABEL_FORM_ID,
    MMIPB_NUM5_LABEL_FORM_ID,
    #endif

   
   MMIPB_LABEL_EMAIL_ID,  
  
   MMIPB_LABEL_PHOTO_ID, 
   MMIPB_LABEL_RING_ID,  
   MMIPB_LABEL_ASP_ID,
   MMIPB_LABEL_GROUP_ID,
   MMIPB_LABEL_MEMO_ID, 
   
   MMIPB_LABEL_COM_NAME_ID,
   
   
       MMIPB_SELECT_NUMBER_LISTBOX_CTRL_ID,
    MMIPB_ANIM_PHOTO_ID,
   MMIPB_BUTTON_PHOTO_ID, 
   MMIPB_BUTTON_RING_ID,  
   MMIPB_BUTTON_ASP_ID,
   MMIPB_BUTTON_GROUP_ID,
   MMIPB_BUTTON_MEMO_ID, 
   MMIPB_BUTTON_TITLE_ID,
   MMIPB_BUTTON_COM_NAME_ID,
   MMIPB_BUTTON_COM_ADDRESS_ID,

 MMIPB_NUM1_DEL_BUTTON_ID,
        MMIPB_NUM2_DEL_BUTTON_ID,
   												
        MMIPB_NUM3_DEL_BUTTON_ID,
        MMIPB_NUM4_DEL_BUTTON_ID,
        MMIPB_NUM5_DEL_BUTTON_ID,

 //   MMIPB_BUTTON_EMAIL_DELETE_ID,
   //edit
   MMIPB_EDITBOX_NAME_ID,
   MMIPB_EDITBOX_ALIAS_ID,
   MMIPB_EDITBOX_NUM1_ID,
   MMIPB_EDITBOX_NUM2_ID,
   MMIPB_EDITBOX_NUM3_ID,
   MMIPB_EDITBOX_NUM4_ID,
   MMIPB_EDITBOX_NUM5_ID,
   
   MMIPB_EDITBOX_EMAIL_ID,
  
   
   MMIPB_LABEL_ASP_EDIT_ID,  
   MMIPB_LABEL_GROUP_EDIT_ID,
   
   MMIPB_LABEL_RING_EDIT_ID,
   
   MMIPB_EDITBOX_MEMO_ID, 
   MMIPB_EDITBOX_TITLE_ID,
   MMIPB_EDITBOX_COM_NAME_ID,
   MMIPB_EDITBOX_ADDRESS_ID,

    MMIPB_STORAGE_SELECT_OPT_CTRL_ID,
    MMIPB_ADD_ENTRY_SOFTKEY_CTRL_ID,


//#ifdef MMI_PDA_SUPPORT   
    
   MMIPB_MORE_OPT_CTRL_ID,
   MMIPB_CONTACT_OPT_CTRL_ID,
   MMIPB_GROUP_OPT_CTRL_ID,
   MMIPB_ALL_MORE_OPT_CTRL_ID,
   MMIPB_PDA_CONTACT_DISPLAY_OPT_CTRL_ID,
   MMIPB_SEARCH_PDA_EDITBOX_CTRL_ID,
   MMIPB_SEARCH_WIN_FROM_ID,
   MMIPB_ALL_CONTACT_SEARCH_WIN_FORM_ID,
   MMIPB_ALL_CONTACT_SEARCH_EDITBOX_CTRL_ID,
   MMIPB_MOSTUSED_CONTACT_SEARCH_WIN_FORM_ID,
   MMIPB_MOSTUSED_CONTACT_DROPDOWNLIST_CTRL_ID,
   MMIPB_CHILD_MOSTUSED_SELECT_TITLE_CTRL_ID,
   MMIPB_CHILD_MOSTUSED_SELECT_BUTTON_CTRL_ID,
   MMIPB_MOSTUSED_CONTACT_SEARCH_EDITBOX_CTRL_ID, 
   MMIPB_CHILD_ALL_CONTACT_SEARCH_WIN_FORM_ID,
   MMIPB_CHILD_ALL_CONTACT_SEARCH_EDIT_FORM_ID,
   MMIPB_ALL_SEARCH_ADD_BUTTON_CTRL_ID,
   MMIPB_CHILD_MOSTUSED_CONTACT_SEARCH_WIN_FORM_ID,
   MMIPB_MOSTUSED_SEARCH_ADD_BUTTON_CTRL_ID,
   MMIPB_MOSTUSED_SEARCH_BUTTON_CTRL_ID,
   MMIPB_ALL_SEARCH_BUTTON_CTRL_ID,
   MMIPB_CHILD_ALL_SELECT_TITLE_CTRL_ID,
   MMIPB_CHILD_ALL_SELECT_BUTTON_CTRL_ID,
   MMIPB_ALL_ENTRY_LISTBOX_CTRL_ID,
   MMIPB_MOSTUSED_ENTRY_LISTBOX_CTRL_ID,  
   MMIPB_ENTRY_DETAIL_FORM_CTRL_ID,
   MMIPB_CHILD_DETAIL_FORM_CTRL_ID,
   MMIPB_CHILD_DETAIL_BUTTON_FORM_CTRL_ID,
   MMIPB_ENTRY_DETAIL_PICTURE_CTRL_ID,
   MMIPB_ENTRY_DETAIL_NAME_CTRL_ID,
   MMIPB_ENTRY_DETAIL_FAVORITE_CTRL_ID,
   MMIPB_ENTRY_DETAIL_EDIT_CTRL_ID,
   MMIPB_ENTRY_DETAIL_LIST_CTRL_ID,
   MMIPB_ENTRY_DETAIL_SMS_BUTTON_ID,
   MMIPB_ENTRY_DETAIL_ADD_BUTTON_ID,
   
   MMIPB_FDN_NEW_OPTION_CTRL_ID,
   MMIPB_ENTRY_SEARCH_LISTBOX_CTRL_ID,
   MMIPB_NUMBER_LIST_CTRL_ID,
   MMIPB_GROUP_CONTACT_SEARCH_WIN_FORM_ID,
   MMIPB_CHILD_GROUP_CONTACT_SEARCH_WIN_FORM_ID,
   MMIPB_CHILD_GROUP_CONTACT_SEARCH_EDIT_FORM_ID,
   MMIPB_GROUP_CONTACT_SEARCH_EDITBOX_CTRL_ID,
   MMIPB_CHILD_GROUP_SELECT_TITLE_CTRL_ID,
   MMIPB_CHILD_GROUP_SELECT_BUTTON_CTRL_ID,
   MMIPB_GROUP_SEARCH_BUTTON_CTRL_ID,
   MMIPB_GROUP_ENTRY_LISTBOX_CTRL_ID,
   MMI_ENTRY_LIST_SOFTKEY_CTRL_ID,
   MMI_ENTRY_LIST_MOSTUSE_SOFTKEY_CTRL_ID,
   MMIPB_DETAIL_SUBMENU_OPT_CTRL_ID,
   MMIPB_MOSTUSED_TOOLBAR_LISTBOX_CTRL_ID,
   MMIPB_GROUP_TOOLBAR_LISTBOX_CTRL_ID,
   MMIPB_MODIFY_GROUP_NAME_EDITBOX_FORM_ID,
   MMIPB_MODIFY_GROUP_NAME_SOFTKEY_CTRL_ID,
   MMIPB_GROUP_LIST_WIN_FORM_ID,
   MMIPB_CHILD_GROUP_LIST_WIN_FORM_ID,
   MMIPB_GROUP_LIST_TEXT_CTRL_ID,
   MMIPB_GROUP_LIST_ADD_BUTTON_CTRL_ID,
   MMIPB_GROUP_LIST_LISTBOX_CTRL_ID,
   MMIPB_SET_MENU_CTRL_ID,
   MMIPB_SET_SAVE_POS_LIST_CTRL_ID,
   MMIPB_SET_DISPLAY_OPTION_LIST_CTRL_ID,
   MMIPB_SET_DISPLAY_PERIOD_LIST_CTRL_ID,
   MMIPB_SET_UPDATE_PERIOD_LIST_CTRL_ID,
   MMIPB_SET_ACCOUNT_LIST_CTRL_ID,   
   // MMIPB_MOSTUSED_CONTACT_DROPDOWNLIST_CTRL_ID,   
   MMIPB_SOFTKEY_CTRL_ID,
   MMIPB_SELECT_ALL_CTRL_ID,
//#endif
   //#ifndef PB_SUPPORT_LOW_MEMORY 
    MMIPB_URL_FORM_ID,
    MMIPB_URL_SUB_FORM_ID,
    MMIPB_URL_LABEL_ID,
    MMIPB_URL_EDITBOX_ID,   
    
   MMIPB_BIRTHDAY_FORM_ID,
   MMIPB_BIRTHDAY_SUB_FORM_ID,
   MMIPB_BIRTHDAY_EDIT_ID, 
   MMIPB_BIRTHDAY_LABEL_ID,
   MMIPB_BUTTON_BIRTHDAY_DELETE_ID,
    MMIPB_SET_BIRTHDAY_FORM_ID,
    MMIPB_SET_BIRTHDAY_DATEEDITBOX_CTRL_ID,
    
   MMIPB_COMEMORATE_FORM_ID,
   MMIPB_COMEMORATE_SUB_FORM_ID,
   MMIPB_COMEMORATE_EDITBOX_ID, 
   MMIPB_COMEMORATE_LABEL_ID,
   MMIPB_BUTTON_COMEMORATE_DELETE_ID,
   //#endif
   MMIPB_TOOLBAR_LISTBOX_CTRL_ID,
   MMIPB_DETAIL_TOOLBAR_LISTBOX_CTRL_ID,
  MMIPB_ADD_TO_GROUP_LISTBOX_CTRL_ID,
   MMIPB_EDIT_BEFORE_DIAL_LISTBOX_CTRL_ID,
   MMIPB_SET_DEFAULT_NUMBER_LISTBOX_CTRL_ID,


   MMIPB_ADD_NEW_GROUP_FORM_ID,
   MMIPB_ADD_NEW_GROUP_NAME_FORM_ID,
   MMIPB_ADD_NEW_GROUP_NAME_LABEL_CTRL_ID,
   MMIPB_ADD_NEW_GROUP_EDITBOX_CTRL_ID,
   MMIPB_ADD_NEW_GROUP_SOFTKEY_CTRL_ID,
   MMIPB_ADD_NEW_GROUP_LISTBOX_CTRL_ID,
   MMIBT_EDIT_GROUP_NAME_EDITBOX_CTRL_ID,

   MMIPB_EDIT_NUMBER_TYPE_LISTBOX_CTRL_ID,
    MMIPB_EDIT_IM_TYPE_LISTBOX_CTRL_ID, 

    //详情
   MMIPB_DETAIL_MAIN_TAB_CTRL_ID,
   MMIPB_DETAILS_CALLLOG_LIST_TAB_CTRL_ID,
   MMIPB_DETAILS_MESSAGE_LIST_TAB_CTRL_ID,
   MMIPB_DETAILS_MESSAGE_LIST_CTRL_ID,
   
    MMIPB_DETAILMSG_SELECT_LIST_CTRL_ID,
    MMIPB_DETAILMSG_SELECT_FORM_CTRL_ID,
    MMIPB_DETAILMSG_SELECT_TITLE_FORM_CTRL_ID,
    MMIPB_DETAILMSG_SELECT_TITLE_LABEL_CTRL_ID,
    MMIPB_DETAILMSG_SELECT_TITLE_BUTTON_CTRL_ID,

   MMIPB_SNS_ACTIVEINFO_LIST_CTRL_ID,
   MMIPB_COPY_SELECT_LIST_CTRL_ID,
   MMIPB_COPY_LOCATION_LIST_CTRL_ID,
   

   MMIPB_MOSTUSED_DETAIL_FORM_CTRL_ID,
   MMIPB_MOSTUSED_DETAIL_TITLE_FORM_CTRL_ID,
   MMIPB_MOSTUSED_DETAIL_PHOTO_CTRL_ID,
   MMIPB_MOSTUSED_DETAIL_LABEL_CTRL_ID,
   MMIPB_MOSTUSED_DETAIL_BTN_FORM_CTRL_ID,
   MMIPB_MOSTUSED_DETAI_BTN_CALL_CTRL_ID,
   MMIPB_MOSTUSED_DETAI_BTN_IPCALL_CTRL_ID,
   MMIPB_MOSTUSED_DETAI_MSG_CTRL_ID,
   MMIPB_MOSTUSED_DETAI_BTN_DEL_CTRL_ID,
   MMIPB_MOSTUSED_DETAIL_LIST_FORM_CTRL_ID,
   MMIPB_MOSTUSED_DETAIL_LIST_CTRL_ID,
#ifdef  BT_PBAP_SUPPORT
   MMIPB_BT_CONTACT_SEARCH_WIN_FORM_ID,
   MMIPB_BT_ENTRY_LISTBOX_CTRL_ID, 
   MMIPB_CHILD_BT_CONTACT_SEARCH_WIN_FORM_ID,
   MMIPB_CHILD_BT_CONTACT_SEARCH_EDIT_FORM_ID,
   MMIPB_BT_ENTRY_SEARCH_BUTTON_CTRL_ID,
   MMIPB_BT_CONTACT_SEARCH_EDITBOX_CTRL_ID,
   MMIPB_BT_TOOLBAR_LISTBOX_CTRL_ID,
   MMIPB_CHILD_BT_SELECT_TITLE_CTRL_ID,
   MMIPB_CHILD_BT_SELECT_BUTTON_CTRL_ID,
#endif

//===========================================================================//
//                              For watch                                    //
//===========================================================================//
   WATCHPB_MAINMENU_LIST_CTRL_ID,
   WATCHPB_CONTACT_LIST_CTRL_ID,

   MMIPB_MAX_CTRL_ID
}PB_CONTROL_ID_E;

/**--------------------------------------------------------------------------*
 **                         FUNCTION DEFINITION                              *
 **--------------------------------------------------------------------------*/
    /*****************************************************************************/
    //  Description : Register acc menu group
    //  Global resource dependence : none
    //  Author: haiyang.hu
    //  Note:
    /*****************************************************************************/
    PUBLIC void MMIPB_RegWinIdNameArr(void);


/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif

#endif //_MMISET_ID_H_
