#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_PB_DELETE,"\\MMI_RES_##\\IMAG\\IMAGE_PB_DELETE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef TOUCH_PANEL_SUPPORT
#ifdef MMIPB_GROUP_MANAGE_SUPPORT
RES_ADD_IMG(IMG_PB_MANAGE_GROUP_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MANAGE_GROUP_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_PB_MORE_CLOSE,"\\MMI_RES_##\\IMAG\\IMAGE_PB_MORE_CLOSE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PB_MORE_OPEN,"\\MMI_RES_##\\IMAG\\IMAGE_PB_MORE_OPEN.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//[[define image infomation


#ifdef MONOCHROME_LCD_SUPPORT
#ifndef PB_SUPPORT_LOW_MEMORY
RES_ADD_IMG(IMAGE_PHONEBOOK_MEMO,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_MEMO.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_DUTY,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_DUTY.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_COMPANY,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_COMPANY.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_COM_ADDRESS,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_COM_ADDRESS.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_COMPANY_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_COMPANY_NUMBER.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_FAX_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_FAX_NUMBER.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_PHONE_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_PHONE_NUMBER.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#else
#ifndef PB_SUPPORT_LOW_MEMORY
RES_ADD_IMG(IMAGE_PHONEBOOK_MEMO,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_MEMO.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_DUTY,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_DUTY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_COMPANY,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_COMPANY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_COM_ADDRESS,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_COM_ADDRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_COMPANY_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_COMPANY_NUMBER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_FAX_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_FAX_NUMBER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_PHONE_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_PHONE_NUMBER.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

#ifdef CMCC_UI_STYLE
RES_ADD_IMG(IMAGE_PHONEBOOK_ADDRESS,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_ADDRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

RES_ADD_STRING(TXT_FDN_FULL,"FDN full")    //case3: defined but not used
#ifdef MONOCHROME_LCD_SUPPORT
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP1,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP1.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP2,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP2.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP3,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP3.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP4,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP4.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP5,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP5.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP6,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP6.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP7,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP7.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP8,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP8.bmp",IMG_CMP_BMP_16_565_RLE,0)
#else
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP1,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP2,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP3,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP4,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP4.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP5,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP5.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP6,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP6.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP7,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP7.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP8,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP8.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef SNS_SUPPORT
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_SINA,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_SINA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_TWITTER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_TWITTER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_FACEBOOK,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_FACEBOOK.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_OWNDEF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_OWNDEF.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMIPB_MOST_USED_SUPPORT 
RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_MOSTUSED,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_MOSTUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(MMIPB_CONTACT_ADD,"\\MMI_RES_##\\IMAG\\MMIPB_CONTACT_ADD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIPB_CONTACT_ADD_PRESSED,"\\MMI_RES_##\\IMAG\\MMIPB_CONTACT_ADD_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_PB_DIAL_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_DIAL_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PB_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMIPB_MAIL_SUPPORT
RES_ADD_IMG(IMAGE_PB_EMAIL_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_EMAIL_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_BUSINESS,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_BUSINESS.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_COLLEAGUE,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_COLLEAGUE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_FAMILY,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_FAMILY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_FRIEND,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_FRIEND.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_SCHOOLMATE,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_SCHOOLMATE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_SIM,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_SIM.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP_VIP,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP_VIP.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef SNS_SUPPORT
RES_ADD_IMG(IMAGE_PHONEBOOK_FACEBOOK,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_FACEBOOK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_SINA,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SINA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_TWITTER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TWITTER.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IAMGE_PB_DEFAULT_PHOTO,"\\MMI_RES_##\\IMAG\\IAMGE_PB_DEFAULT_PHOTO.png",IMG_CMP_PNG_ARGB_RLE,0)

#if !defined(MMI_MULTI_SIM_SYS_SINGLE) 
RES_ADD_IMG(IMAGE_PHONEBOOK_SIM1,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SIM1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_SIM2,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SIM2.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_IMG(IMAGE_PHONEBOOK_SIM3,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SIM3.png",IMG_CMP_PNG_ARGB_RLE,0)

#if defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_IMG(IMAGE_PHONEBOOK_SIM4,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SIM4.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#endif

#ifdef MONOCHROME_LCD_SUPPORT
RES_ADD_IMG(IMAGE_PHONEBOOK_HOME_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_HOME_NUMBER.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_MAIL_ADDRESS,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_MAIL_ADDRESS.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_MIDI,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_MIDI.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_NAME,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_NAME.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_PHONE,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_PHONE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_SELECT_GROUP,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SELECT_GROUP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_SELF_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SELF_NUMBER.bmp",IMG_CMP_BMP_16_565_RLE,0)
#ifdef MMI_MULTI_SIM_SYS_SINGLE
RES_ADD_IMG(IMAGE_PHONEBOOK_SIM,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SIM.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#else
RES_ADD_IMG(IMAGE_PHONEBOOK_HOME_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_HOME_NUMBER.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMIPB_MAIL_SUPPORT
RES_ADD_IMG(IMAGE_PHONEBOOK_MAIL_ADDRESS,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_MAIL_ADDRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_PHONEBOOK_MIDI,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_MIDI.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_NAME,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_NAME.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_PHONE,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_PHONE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_SELECT_GROUP,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SELECT_GROUP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_SELF_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SELF_NUMBER.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_MULTI_SIM_SYS_SINGLE
RES_ADD_IMG(IMAGE_PHONEBOOK_SIM,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SIM.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

//RES_ADD_IMG(IMAGE_PHONEBOOK_PICTURE,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_PICTURE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_MOBILE_NUMBER,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_MOBILE.png",IMG_CMP_PNG_ARGB_RLE,0)

#if 0
RES_ADD_IMG(IMAGE_PHONEBOOK_0_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_0_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_0_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_0_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_1_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_1_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_1_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_1_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_A_C_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_A_C_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_A_C_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_A_C_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_D_F_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_D_F_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_D_F_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_D_F_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_G_I_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_G_I_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_G_I_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_G_I_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_J_L_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_J_L_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_J_L_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_J_L_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_M_O_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_M_O_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_M_O_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_M_O_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_P_S_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_P_S_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_P_S_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_P_S_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_T_V_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_T_V_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_T_V_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_T_V_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_W_Z_PR,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_W_Z_PR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_W_Z_UN,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_W_Z_UN.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef ASP_SUPPORT
RES_ADD_IMG(IMAGE_PHONEBOOK_ASP_RING,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_ASP_RING.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_ALL_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_ALL_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMIPB_MOST_USED_SUPPORT
RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_MOSTUSED_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_MOSTUSED_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_MOSTUSED_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_MOSTUSED_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP1_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP1_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP2_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP2_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP3_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP3_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP4_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP4_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP5_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP5_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP6_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP6_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP7_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP7_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP8_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP8_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_1_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_1_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_2_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_2_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_MENU_SEARCH_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_SEARCH_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMG_PB_MOSTUSED_CONTACT_ICON_OFF,"\\MMI_RES_##\\IMAG\\IMG_PB_MOSTUSED_CONTACT_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_MOSTUSED_CONTACT_ICON_ON,"\\MMI_RES_##\\IMAG\\IMG_PB_MOSTUSED_CONTACT_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_ALL_CONTACT_ICON_ON,"\\MMI_RES_##\\IMAG\\IMG_PB_ALL_CONTACT_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_ALL_CONTACT_ICON_OFF,"\\MMI_RES_##\\IMAG\\IMG_PB_ALL_CONTACT_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_CALLLOG_ICON_ON,"\\MMI_RES_##\\IMAG\\IMG_PB_CALLLOG_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_CALLLOG_ICON_OFF,"\\MMI_RES_##\\IMAG\\IMG_PB_CALLLOG_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_DIAL_ICON_ON,"\\MMI_RES_##\\IMAG\\IMG_PB_DIAL_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_DIAL_ICON_OFF,"\\MMI_RES_##\\IMAG\\IMG_PB_DIAL_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined MMI_ISTYLE_SUPPORT
RES_ADD_IMG(ISTYLE_IMG_PB_MOSTUSED_CONTACT_ICON_OFF,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMG_PB_MOSTUSED_CONTACT_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_PB_MOSTUSED_CONTACT_ICON_ON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMG_PB_MOSTUSED_CONTACT_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_PB_ALL_CONTACT_ICON_ON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMG_PB_ALL_CONTACT_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_PB_ALL_CONTACT_ICON_OFF,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMG_PB_ALL_CONTACT_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_PB_CALLLOG_ICON_ON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMG_PB_CALLLOG_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_PB_CALLLOG_ICON_OFF,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMG_PB_CALLLOG_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_PB_DIAL_ICON_ON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMG_PB_DIAL_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_PB_DIAL_ICON_OFF,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMG_PB_DIAL_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_IMG(IMG_PB_MENU_NEW_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_NEW_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_MENU_MARK_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_MARK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

//RES_ADD_IMG(IMG_PB_MENU_MORE_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_MORE_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_QUICK_CONTACT_ICON ,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_QUICK_CONTACT_ICON .png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_GROUP_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_GROUP_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_VCARD_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_VCARD_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_COPY_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_COPY_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_MENU_EDIT_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_EDIT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//#if defined(MMI_SPEEDDIAL_SUPPORT) 
//RES_ADD_IMG(IMG_PB_MENU_SPEEDDIAL_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_SPEEDDIAL_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//#endif
//#if defined(MMI_BLACKLIST_SUPPORT)
//RES_ADD_IMG(IMG_PB_MENU_BLACKLIST_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_BLACKLIST_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//#endif
RES_ADD_IMG(IMG_PB_MENU_IMPORT_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_IMPORT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_EXPORT_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_EXPORT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMIEMAIL_SUPPORT
RES_ADD_IMG(IMG_PB_MENU_MMS_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_MMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_IMG(IMG_PB_MENU_COPY_PHONE_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_COPY_PHONE_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_COPY_SIM1_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_COPY_SIM1_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_COPY_SIM2_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_COPY_SIM2_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_COPY_SIM3_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_COPY_SIM3_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_COPY_SIM4_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_COPY_SIM4_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_CONTACT_VIEW,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_CONTACT_VIEW.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_PB_MENU_PHONE_NUM,"\\MMI_RES_##\\IMAG\\IMG_PB_MENU_PHONE_NUM.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMG_PB_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMG_PB_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_FAVBRATE_ICON_ON,"\\MMI_RES_##\\IMAG\\IMG_PB_FAVBRATE_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_PB_FAVBRATE_ICON_OFF,"\\MMI_RES_##\\IMAG\\IMG_PB_FAVBRATE_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

#endif
//#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_3_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_3_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//#if defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_4_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_4_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//#endif
//#endif
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_UNCLASS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_UNCLASS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_ALL_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_ALL_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP1_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP1_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP2_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP2_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP3_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP3_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP4_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP4_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP5_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP5_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP6_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP6_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP7_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP7_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_GROUP8_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_GROUP8_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_1_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_1_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_2_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_2_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifndef MMI_RES_LOW_COST
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_3_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_3_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_4_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_4_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#endif
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_SIM_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_SIM_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TAB_UNCLASS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TAB_UNCLASS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PHONEBOOK_SNE,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SNE.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef TOUCH_PANEL_SUPPORT
RES_ADD_IMG(IMAGE_PHONEBOOK_TOOLBAR_ADD,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TOOLBAR_ADD.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifndef MMI_RES_LOW_COST
//RES_ADD_IMG(IMAGE_PHONEBOOK_TOOLBAR_DIAL,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TOOLBAR_DIAL.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_IMG(IMAGE_PHONEBOOK_TOOLBAR_SMS,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TOOLBAR_SMS.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TOOLBAR_ADD_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TOOLBAR_ADD_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TOOLBAR_DIAL_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TOOLBAR_DIAL_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_TOOLBAR_SMS_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_TOOLBAR_SMS_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_PB_EDIT_CONTACT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_EDIT_CONTACT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_PB_LIST_NV_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_NV_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#if !defined(MMI_MULTI_SIM_SYS_SINGLE)
RES_ADD_IMG(IMAGE_PB_LIST_SIM1_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_SIM1_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PB_LIST_SIM2_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_SIM2_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_IMG(IMAGE_PB_LIST_SIM3_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_SIM3_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef MMI_MULTI_SIM_SYS_QUAD
RES_ADD_IMG(IMAGE_PB_LIST_SIM4_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_SIM4_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#else
RES_ADD_IMG(IMAGE_PB_LIST_SIM_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_SIM_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)    
#endif

#ifdef SNS_SUPPORT
RES_ADD_IMG(IMAGE_PB_LIST_SINA_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_SINA_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PB_LIST_TWITTER_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_TWITTER_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PB_LIST_FACEBOOK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_FACEBOOK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef TCARD_PB_SUPPORT
RES_ADD_IMG(IAMGE_PB_TCARD_PHOTO,"\\MMI_RES_##\\IMAG\\IAMGE_PB_TCARD_PHOTO.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PB_LIST_TCARD_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PB_LIST_TCARD_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//RES_ADD_IMG(IMAGE_PHONEBOOK_SEARCH_PIC,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_SEARCH_PIC.bmp",IMG_CMP_BMP_16_565_RAW,0)

//]]define image infomation

//[[define anim infomation
//]]define anim infomation
//[[define string infomation
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_PB_FAVOURITE,"favourite")
#endif
#ifdef MMIPB_MOST_USED_SUPPORT
RES_ADD_STRING(TXT_PB_ADD_FAVOURITE,"add to favourite")
RES_ADD_STRING(TXT_PB_REMOVE_FAVOURITE,"remove from favourite")
#endif
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_PB_RECENT_USED,"recent used")
RES_ADD_STRING(TXT_PB_USER_GROUP_NAME,"group name")
RES_ADD_STRING(TXT_PB_USER_GROUP_NAME_DEFAULT,"name")
#endif
#ifdef MMIPB_GROUP_MANAGE_SUPPORT
RES_ADD_STRING(TXT_PB_MANAGE_GROUP_MEMBER,"Manage member")
#endif
//RES_ADD_STRING(TXT_PB_SEARCH_CONTACT,"Search Contact")
//RES_ADD_STRING(TXT_PB_SINA_GROUP,"SINA")    //replaced by common ID TXT_MAINMENU_ICON_SINA
//RES_ADD_STRING(TXT_PB_TWITTER_GROUP,"TWITTER")  //replaced by common ID TXT_COMMON_TIWTTER
//RES_ADD_STRING(TXT_PB_FACEBOOK_GROUP,"FACEBOOK")  //replaced by common ID TXT_COMMON_FACEBOOK
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_PB_NO_MATCHED,"No Matched Contact")
#endif
//RES_ADD_STRING(TXT_PB_IMPORT_FAIL,"Import Fail")
//RES_ADD_STRING(TXT_PB_EXPORT_FAIL,"Export Fail")
//RES_ADD_STRING(TXT_PB_COPY_FAIL,"Copy Fail")
RES_ADD_STRING(TXT_PB_INPUT_SEARCH_TEXT,"Pls Input Search String")
#ifdef MMI_PDA_SUPPORT //ping.gao modify for non-pda compile error
RES_ADD_STRING(TXT_PB_SELECT_ALL,"Select all")
#endif
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_PB_NO_FAVOURITE,"No Favourite")
#endif
//RES_ADD_STRING(TXT_PB_ITEM_DETAIL_SIGN,"Sign")         //replaced by common ID TXT_COMMON_SIGNATURE
#ifdef MMI_VCARD_SUPPORT
RES_ADD_STRING(TXT_PB_IS_EXPORTING,"Exporting contact")
RES_ADD_STRING(TXT_PB_IS_IMPORTING,"IMPORTING contact")
#endif
#if defined(MMI_SPEEDDIAL_SUPPORT)
RES_ADD_STRING(TXT_PB_SET_SPEEDDIAL_NUM,"Set SpeedDial Number")
#endif
RES_ADD_STRING(TXT_PB_IS_SAVE_CONTACT,"Save Contact")
//RES_ADD_STRING(TXT_PB_FIND,"Search")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_ADD,"New")    //replaced by common ID TXT_NEW
//RES_ADD_STRING(TXT_PB_ERASE_ALL,"Delete all")      //replaced by common ID TXT_DELALL
RES_ADD_STRING(TXT_PB_ERASE_MULTI,"Multi Delete")
//RES_ADD_STRING(TXT_PB_COPY_ALL,"Copy all")
//RES_ADD_STRING(TXT_PB_SETTING,"Settings")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_GROUP_MANAGE,"Groups")
#if defined (MMIPB_SIMDN_SUPPORT)
RES_ADD_STRING(TXT_PB_MSISDN,"Own number")  //merge ID TXT_PB_SET_LOCAL_NUMBER
RES_ADD_STRING(TXT_PB_SDN,"SDN number")
RES_ADD_STRING(TXT_PB_SDN_NOT_SUPPORT,"not support SDN")
#endif
//RES_ADD_STRING(TXT_PB_USED_SPACE,"Memory status")   //replaced by common ID TXT_COMMON_DETAIL_MEMORY
//RES_ADD_STRING(TXT_PB_ERASE_SIM_ALL,"SIM all")
//RES_ADD_STRING(TXT_PB_ERASE_NV_ALL,"Phone all")    //replaced by common ID TXT_PHONE
//RES_ADD_STRING(TXT_PB_COPY_ALL_TO_NV,"SIM to phone")
//RES_ADD_STRING(TXT_PB_COPY_ALL_TO_SIM,"Phone to SIM")
//RES_ADD_STRING(TXT_PB_MOVE_ALL_TO_NV,"From SIM to ME")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_MOVE_ALL_TO_SIM,"From ME to SIM")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_ADD_IN_SIM,"SIM")  //replaced by common ID TXT_COMM_SIM
//RES_ADD_STRING(TXT_PB_ADD_IN_NV,"Phone")    //replaced by common ID TXT_PHONE
#if defined(MMI_SPEEDDIAL_SUPPORT) 
//RES_ADD_STRING(TXT_PB_SETTING_SPEEDKEY,"Speed dial setting")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SET_QUICK_DIAL_SUBSTR,"Set Quick dial number")     //replaced by common ID TXT_COMMON_SPEEDDIAL
#endif
//RES_ADD_STRING(TXT_PB_SETTING_MTFW,"Rejected numbers")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SETTING_GROUP,"Operate")  //replaced by common ID TXT_OPERATE
//RES_ADD_STRING(TXT_PB_SETTING_GROUP_MEMBER,"Group members")
//RES_ADD_STRING(TXT_PB_SETTING_GROUP_DELETE,"Delete")
//RES_ADD_STRING(TXT_PB_GROUP_MEMBER_ERASE,"Delete name")
//RES_ADD_STRING(TXT_PB_GROUP_MEMBER_ADD,"Add name")
//RES_ADD_STRING(TXT_PB_SEARCH_OPERATE,"Operate")  //replaced by common ID TXT_OPERATE
//RES_ADD_STRING(TXT_PB_SEARCH_OPERATE_CALL,"Call")
//RES_ADD_STRING(TXT_PB_SEARCH_OPERATE_MODIFY,"Modify")    //replaced by common ID TXT_MODIFY
//RES_ADD_STRING(TXT_PB_SEARCH_OPERATE_COPY,"Copy")      //replaced by common ID TXT_COMMON_COPY
//RES_ADD_STRING(TXT_PB_SEARCH_OPERATE_MOVE,"Move")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SEARCH_OPERATE_ERASE,"Erase")     //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_PB_SEARCH_OPERATE_MTFW,"Set as rejected")
//RES_ADD_STRING(TXT_PB_SEARCH_OPERATE_SEND_SMS,"Send SMS")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SEARCH_OPERATE_SEND_PHONE,"Send phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_ADD_NEW_GROUP,"Add new group")
//RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_0,"Ungrouped")    //case3: defined but not used
RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_1,"Family")
RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_2,"Friends")
RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_3,"Colleagues")
RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_4,"Classmates")
//RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_5,"Other 1")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_6,"Other 2")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_7,"Other 3")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_8,"Other 4")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_DEFAULT_GROUP_9,"Other 5")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_NAME,"Name")  //replaced by common ID TXT_NAME
RES_ADD_STRING(TXT_PB_PHONE,"Phone")    
//RES_ADD_STRING(TXT_PB_MAIL,"Mail")    //replaced by common ID TXT_EMAIL_BOX
//RES_ADD_STRING(TXT_PB_NUM_TYPE_PRIVATE,"Mobile phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_NUM_TYPE_HOME,"Home phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_NUM_TYPE_OFFICE,"Office phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SPACE_NAME,"<Name>")   //replaced by common ID TXT_NAME
//RES_ADD_STRING(TXT_PB_SPACE_PHONE,"<Number>")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SPACE_MAIL,"<Mail>")    //replaced by common ID TXT_EMAIL_BOX
RES_ADD_STRING(TXT_PB_COPY_OR_NOT,"Copy")
//RES_ADD_STRING(TXT_PB_MOVE_OR_NOT,"Move")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_ERASE_OR_NOT,"Delete")         //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_PB_NO_MATCH_ENTRY,"No match entry")    //case3: defined but not used
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_PB_NO_ENTRY,"No entry")
#endif
//RES_ADD_STRING(TXT_PB_NO_PHONE,"Empty number")        //replaced by common ID TXT_CL_EMPTY_NUM
//RES_ADD_STRING(TXT_PB_NO_MSISDN,"No msisdn")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SUCCESS,"Success")  //replaced by common ID TXT_SUCCESS
//RES_ADD_STRING(TXT_PB_FAILURE,"Failure")    //replaced by common ID TXT_ERROR
//RES_ADD_STRING(TXT_PB_ERROR,"Error")  //replaced by common ID TXT_COMM_ERROR
//RES_ADD_STRING(TXT_PB_COPYED,"Copied")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_INSUFFICIENT_SPACE,"Insufficient space")  //replaced by common ID TXT_NO_SPACE
RES_ADD_STRING(TXT_PB_SIM_FULL,"SIM full")
RES_ADD_STRING(TXT_PB_NV_FULL,"Phone full")
RES_ADD_STRING(TXT_PB_SIM1_FULL,"SIM1 full")
RES_ADD_STRING(TXT_PB_SIM2_FULL,"SIM2 full")
RES_ADD_STRING(TXT_PB_SIM3_FULL,"SIM3 full")
RES_ADD_STRING(TXT_PB_SIM4_FULL,"SIM4 full")

//RES_ADD_STRING(TXT_PDA_PB_COPY_FROM_NV_TO_SIM,"Copy To Sim")
//RES_ADD_STRING(TXT_PB_PLEASE_INPUT_PHONE,"Please input phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_BY_NAME,"By name")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SAME_NAME,"Same name")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_PLEASE_INPUT_GROUP,"Please input group")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_GROUP_NUMBER_FULL,"Group number full")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_GROUP_LIST,"Select group list")    //case3: defined but not used

//RES_ADD_STRING(TXT_PB_ENTRY_LIST,"Entry list")
//RES_ADD_STRING(TXT_PB_SELECT_PHONE,"Select phone")    //replaced by local common ID TXT_PB_SELECT_NUMBER
RES_ADD_STRING(TXT_PB_NEW_CONTACT,"New Contact")
RES_ADD_STRING(TXT_PB_EDIT_CONTACT,"Edit Contact")
//RES_ADD_STRING(TXT_PB_COPY_TO_SIM,"Copy to sim")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPYALL_TO_SIM,"Copy all to sim")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPY_TO_PHONE,"Copy to phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPYALL_TO_PHONE,"Copy all to phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_GROUP_ALL,"ALL")      //replaced by common ID TXT_COMMON_ALL
//RES_ADD_STRING(TXT_PB_GROUP_SIM,"SIM")  //replaced by common ID TXT_COMM_SIM
#if defined(MMI_BLACKLIST_SUPPORT)
//RES_ADD_STRING(TXT_PB_GROUP_BLACKLIST,"Blacklist")                 //replaced by common ID TXT_SET_BLACKLIST
#endif
//RES_ADD_STRING(TXT_PB_MENU_CHANGE_GROUP,"Change group")
//RES_ADD_STRING(TXT_PB_ITEM_DETAIL_NAME,"Name")  //replaced by common ID TXT_NAME
RES_ADD_STRING(TXT_PB_ITEM_DETAIL_MOBILE_PHONE,"Mobile phone")
RES_ADD_STRING(TXT_PB_ITEM_DETAIL_HOME_PHONE,"Home phone")
RES_ADD_STRING(TXT_PB_ITEM_DETAIL_OFFICE_PHONE,"Office Phone")
RES_ADD_STRING(TXT_PB_ITEM_DETAIL_EMAIL,"Email")
//RES_ADD_STRING(TXT_PB_ITEM_DETAIL_CUSTOM_IMAGE,"Image")  //replaced by common ID TXT_COMMON_PIC
//RES_ADD_STRING(TXT_PB_ITEM_DETAIL_CUSTOM_RING,"Ring")  //replaced by common ID TXT_RING
//RES_ADD_STRING(TXT_PB_ITEM_DETAIL_CUSTOM_MEMO,"Memo")  //replaced by common ID TXT_MEMO
//RES_ADD_STRING(TXT_PB_SEARCH,"Search")   //replaced by common ID TXT_COMM_SEARCH
RES_ADD_STRING(TXT_PB_VIEW,"Phonebook view")
//RES_ADD_STRING(TXT_PB_INVALID_PHONE,"Invalid number")    //replaced by common ID TXT_CC_INVALID_NUM

//RES_ADD_STRING(TXT_PB_WRITE_MESSAGE,"Write message")  //replaced by common ID TXT_COMMON_WRITE_MESSAGE

RES_ADD_STRING(TXT_PB_MODIFY_PHOTO,"Modify Photo")
RES_ADD_STRING(TXT_PB_ITEM_DETAIL_CUSTOM_SELECT_GROUP,"Select group")

RES_ADD_STRING(TXT_PB_ORG,"Org")
RES_ADD_STRING(TXT_PB_ITEM_DETAIL_ORG,"Org")
RES_ADD_STRING(TXT_PB_ITEM_DETAIL_COMPANY,"Company")
RES_ADD_STRING(TXT_PB_ITEM_ADRRESS,"Adrress")
//RES_ADD_STRING(TXT_SEND_BY_BT,"By bluetooth")          //replaced by common ID TXT_BLUETOOTH
//RES_ADD_STRING(TXT_SEND_BY_SMS,"By SMS")  //replaced by common ID TXT_SMS
#ifdef MMI_VCARD_SUPPORT
RES_ADD_STRING(TXT_SEND_BY_EMAIL,"Email")
#endif

//RES_ADD_STRING(TXT_PB_PLEASE_CLOSE_FDN,"Please close fdn")  //replaced by common ID TXT_FDN_ACTIVATED
#if defined (MMIPB_SIMDN_SUPPORT) || defined(FDN_SUPPORT)
RES_ADD_STRING(TXT_PB_FDN_NUM,"FDN Number")
#endif
RES_ADD_STRING(TXT_PB_PHONE_NUMBER,"Phone Number")
RES_ADD_STRING(TXT_PB_FAX_NUMBER,"Fax Number")
//RES_ADD_STRING(TXT_PB_COPY_FROM_SIM_TO_NV,"Copy From SIM  To Phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPY_FROM_SIM1_TO_NV,"Copy From SIM1 To Phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPY_FROM_SIM2_TO_NV,"Copy From SIM2 To Phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPY_FROM_SIM3_TO_NV,"Copy From SIM3 To Phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPY_FROM_SIM4_TO_NV,"Copy From SIM4 To Phone")    //case3: defined but not used
RES_ADD_STRING(TXT_PB_COPY_FROM_NV_TO_SIM1,"Copy From To SIM1")
RES_ADD_STRING(TXT_PB_COPY_FROM_NV_TO_SIM2,"Copy To SIM2")
RES_ADD_STRING(TXT_PB_COPY_FROM_NV_TO_SIM3,"Copy To SIM3")
RES_ADD_STRING(TXT_PB_COPY_FROM_NV_TO_SIM4,"Copy To SIM4")

RES_ADD_STRING(TXT_PB_COPY_FROM_LOCATION,"Copy From") 
RES_ADD_STRING(TXT_PB_COPY_TO_LOCATION,"Copy To")
RES_ADD_STRING(TXT_PB_SET_PHONE,"phone")
RES_ADD_STRING(TXT_PB_SET_SIM,"sim")
RES_ADD_STRING(TXT_PB_CANT_SELECT_SAME_LOCATION,"Can not select same location")
//RES_ADD_STRING(TXT_PB_COPYALL_FROM_SIM_TO_NV,"Copy All From SIM To Phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPYALL_FROM_SIM1_TO_NV,"Copy All From SIM1 To Phone")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPYALL_FROM_SIM2_TO_NV,"Copy All From SIM2 To Phone")    //case3: defined but not used
//#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_PB_COPYALL_FROM_SIM3_TO_NV,"Copy All From SIM3 To Phone")    //case3: defined but not used
//#endif
//#if defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_PB_COPYALL_FROM_SIM4_TO_NV,"Copy All From SIM4 To Phone")    //case3: defined but not used
//#endif
//RES_ADD_STRING(TXT_PB_COPYALL_FROMNV_TO_SIM1,"Copy All To SIM1")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_COPYALL_FROMNV_TO_SIM2,"Copy All To SIM2")    //case3: defined but not used
//#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_PB_COPYALL_FROMNV_TO_SIM3,"Copy All To SIM3")    //case3: defined but not used
//#endif
//#if defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_PB_COPYALL_FROMNV_TO_SIM4,"Copy All To SIM4")    //case3: defined but not used
//#endif
//RES_ADD_STRING(TXT_PB_DELETE_ALL_SIM1,"Delete All SIM1")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_DELETE_ALL_SIM2,"Delete All SIM2")    //case3: defined but not used
//#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_PB_DELETE_ALL_SIM3,"Delete All SIM3")    //case3: defined but not used
//#endif
//#if defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_PB_DELETE_ALL_SIM4,"Delete All SIM4")    //case3: defined but not used
//#endif

RES_ADD_STRING(TXT_PB_NOT_READY,"Phonebook not Ready!")
//RES_ADD_STRING(TXT_PB_CC_CONNECT,"Call Connecting...")    //case3: defined but not used
#ifdef MMI_VCARD_SUPPORT
RES_ADD_STRING(TXT_PB_SEND_VCARD,"Send VCard")
#endif
//RES_ADD_STRING(TXT_PB_DAIL_DIRECT,"Dial Directly")    //case3: defined but not used
//RES_ADD_STRING(TXT_DELETE_ONE,"Delete One")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_FDN_FULL,"FDN Full")    //case3: defined but not used
#if defined(MMIPB_MOST_USED_SUPPORT) || defined(BT_PBAP_SUPPORT)
RES_ADD_STRING(TXT_PB_DELETE_ALL_OR_NOT,"Delete All or Not?")
#endif
//RES_ADD_STRING(TXT_PB_OPTION_OTHERS,"Others")          //replaced by common ID TXT_TOOLS_OTHERS


RES_ADD_STRING(TXT_PB_UNCLASS_GROUP,"Unclassed group")
//RES_ADD_STRING(TXT_PB_LIST_MODE_SINGLE,"single line")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_TIPS_MODE_DOUBLE,"double line")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_INSUFFICIENT_SPACE_COPY,"Insufficient Space")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_PART_OF_RECORD_COPY,"Insufficient Space.Part of records have been copyed")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_NO_ADN_PHONE,"Mobile Number not Exist")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_ADD_FAILED,"Add Failed")  //replaced by common ID TXT_ADD_FAIL
//RES_ADD_STRING(TXT_SEND_WRITE_SMS,"SMS")  //replaced by common ID TXT_SMS
#if defined ( MMIPB_ADD_EXIST_CONTACT_SUPPORT )
RES_ADD_STRING(TXT_PB_OVERWRITE_OR_NOT,"Is Overwrite or not")
#endif
#ifdef USB_VUART
RES_ADD_STRING(TXT_PB_SIM_ERROR,"SIM Card is broken or not Exist")
#endif
//load all vcard
//RES_ADD_STRING(TXT_PB_SIM1_TO_SDCARD,"Sim1 to card")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SIM2_TO_SDCARD,"Sim2 to card")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_PHONE_TO_SDCARD,"Phone to card")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SDCARD_TO_PHONE,"Card to phone")    //case3: defined but not used
#if defined ( MMI_VCARD_SUPPORT ) ||defined( MMI_VCALENDAR_SUPPORT )
RES_ADD_STRING(TXT_PB_FOLDER_EMPTY,"Vcard folder empty")
#endif
//RES_ADD_STRING(TXT_PB_SIM_TO_SDCARD,"Sim to card")    //case3: defined but not used
RES_ADD_STRING(TXT_PB_ITEM_DETAIL_ALIAS,"Alias")
//RES_ADD_STRING(TXT_PB_ALIAS_UPDATE_FAIL,"Alias update fail")    //case3: defined but not used

//RES_ADD_STRING(TXT_PB_EXPORT,"Export")  //replaced by common ID TXT_COMM_EXPORT
//RES_ADD_STRING(TXT_PB_EXPORT_ALL,"Export all")
//RES_ADD_STRING(TXT_PB_EXIT_QUERY,"Exit withour save?")
RES_ADD_STRING(TXT_PB_GROUP,"Group")
#ifdef MMIPB_MOST_USED_SUPPORT
RES_ADD_STRING(TXT_PB_MOSTUSED_GROUP,"Useful group")
#endif
RES_ADD_STRING(TXT_PB_CONTACT_EMPTY,"Please input content")
//RES_ADD_STRING(TXT_PB_NAME_NUMBER_NOEXIST,"Name and mobile name must exist one")    //case3: defined but not used

//RES_ADD_STRING(TXT_PB_STRING_LEN_LARGE,"Name too long")    //case3: defined but not used
RES_ADD_STRING(TXT_NO_PHONE,"No number")

#ifdef TOUCH_PANEL_SUPPORT            
RES_ADD_STRING(TXT_PB_SIM_NO_PHOTO,"Sim Contact Can not Set Photo")
#endif

RES_ADD_STRING(TXT_PB_SELECT_NUMBER,"Select Number")

RES_ADD_STRING(TXT_ADD_TO_CONTACT,"Add to Contact")
RES_ADD_STRING(TXT_ADD_TO_NEW_CONTACT,"Add to New Contact")
#ifdef MMIPB_ADD_EXIST_CONTACT_SUPPORT
RES_ADD_STRING(TXT_ADD_TO_EXIST_CONTACT,"Add to Exist Contact")
#endif

#ifndef PB_SUPPORT_LOW_MEMORY
RES_ADD_STRING(TXT_PB_URL,"URL")
RES_ADD_STRING(TXT_PB_BIRTHDAY,"Birthday")
#endif
//RES_ADD_STRING(TXT_PB_COMEMORATE,"Comemorate Day")
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_PB_SPACE_NO_NAME,"<No Name>")
#endif
RES_ADD_STRING(TXT_SIM_NO_CONTACT_CAN_NOT_COPY,"No Contact in Sim,Can not copy")
RES_ADD_STRING(TXT_NO_PHONE_CONTACT_CAN_NOT_COPY,"No Contact in Phone,Can not copy")
//RES_ADD_STRING(TXT_NO_PHONE_CONTACT_CAN_NOT_EXPORT,"No Phone Contact,Can not Export")
#if defined ( MMI_VCARD_SUPPORT )
RES_ADD_STRING(TXT_NO_UDISK_OR_SD,"No Udisk Or Card")
#endif
RES_ADD_STRING(TXT_PB_PHOTO_SELECT,"Select from album")
RES_ADD_STRING(TXT_PB_PHOTO_SHOT,"Take photo")              
RES_ADD_STRING(TXT_PB_PHOTO_DEFAULT,"Default icon")

//RES_ADD_STRING(TXT_PB_EDIT_PHOTO,"Edit Photo")
RES_ADD_STRING(TXT_PB_CONTACT_PHOTO,"Contact Photo")
RES_ADD_STRING(TXT_PB_DELETE_CONTACT,"Delete Contact")
RES_ADD_STRING(TXT_PB_COPY_CONTACT,"Copy Contact")
RES_ADD_STRING(TXT_PB_ADD_FAVOURITE_CONTACT,"Add Favourite Contact")
RES_ADD_STRING(TXT_PB_RING_SELECT,"Select from sound files")

RES_ADD_STRING(TXT_PB_MOBLIE,"Mobile")
RES_ADD_STRING(TXT_PB_RING_PHONE,"Phone ringtones")
RES_ADD_STRING(TXT_PB_RING_DEFAULT,"Default ringtones")
//RES_ADD_STRING(TXT_PB_MOBLE,"Mobile")    //case3: defined but not used
RES_ADD_STRING(TXT_PB_HOME,"Home")
RES_ADD_STRING(TXT_PB_WORK,"Work")
//
RES_ADD_STRING(TXT_EDIT_NUMBER_BEFORE_DIAL,"Edit number Before Dial")
#ifdef MMIPB_MOST_USED_SUPPORT
RES_ADD_STRING(TXT_PB_ADD_TO_FAVORITE,"Add to Favorite")
RES_ADD_STRING(TXT_PB_REMOVE_FAVORITE,"Remove Favorite")
RES_ADD_STRING(TXT_PB_REMOVE_FAVOURITE_CONTACT,"Remove Favourite Contact")
#endif
#ifdef MMIPB_GROUP_MANAGE_SUPPORT
RES_ADD_STRING(TXT_PB_NEW_GROUP,"New Group")
RES_ADD_STRING(TXT_PB_DELETE_GROUP,"Delete Group")
RES_ADD_STRING(TXT_PB_REMOVE_FROM_MEMBER,"Remove from group")
RES_ADD_STRING(TXT_PB_SETTING_GROUP_MODIFY,"Edit Group")
RES_ADD_STRING(TXT_PB_SETTING_GROUP_RING,"Group ringtone")
RES_ADD_STRING(TXT_PB_SETTING_GROUP_NAME_EDIT,"Edit Group Name")
RES_ADD_STRING(TXT_PB_USER_GROUP_REACH_MAX,"user group reach max number")


#endif
RES_ADD_STRING(TXT_PB_WRITE_GROUP_MESSAGE,"Write group message")
RES_ADD_STRING(TXT_PB_ADD_TO_GROUP,"Add To Group")
//RES_ADD_STRING(TXT_PB_ACCOUNT,"Account")    //replaced by common ID TXT_ACCOUNT

RES_ADD_STRING(TXT_PB_INSTANTMSG,"Instant Message")
//RES_ADD_STRING(TXT_PB_QQ,"QQ")  //replaced by common ID  TXT_COMM_QQ
#ifdef MMIPB_IM_MESSAGE_SUPPORT
RES_ADD_STRING(TXT_PB_MSN,"MSN")
RES_ADD_STRING(TXT_PB_GOOGLE_TALK,"Google Talk")
RES_ADD_STRING(TXT_PB_YAHOO,"Yahoo")
RES_ADD_STRING(TXT_PB_SKYPE,"Skype")
RES_ADD_STRING(TXT_PB_AIM,"AIM")
#endif

RES_ADD_STRING(TXT_PB_IMPORT_EXPORT,"Import&Export")
RES_ADD_STRING(TXT_PB_IMPORT_SIM1,"Copy From SIM1")
RES_ADD_STRING(TXT_PB_IMPORT_SIM2,"Copy From SIM2")
RES_ADD_STRING(TXT_PB_IMPORT_SIM3,"Copy From SIM3")
RES_ADD_STRING(TXT_PB_IMPORT_SIM4,"Copy From SIM4")
//RES_ADD_STRING(TXT_PB_IMPORT_UDISK,"Import From Udisk")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_EXPORT_UDISK,"Export To Udisk")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_IMPORT_SD,"Import From T Card")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_EXPORT_SD,"Export To T Card")    //case3: defined but not used

RES_ADD_STRING(TXT_PB_IMPORT_CONTACT,"Import Contact")
RES_ADD_STRING(TXT_PB_EXPORT_CONTACT,"Export Contact")

//RES_ADD_STRING(TXT_PB_SELECT_VCARD_FILE,"Select Vcard File")

RES_ADD_STRING(TXT_PB_INFORMATION_LOST,"Some Information May Lost,Continue?")

RES_ADD_STRING(TXT_PDA_PB_COPY_FROM_NV_TO_SIM1,"copy to sim1")
RES_ADD_STRING(TXT_PDA_PB_COPY_FROM_NV_TO_SIM2,"copy to sim2")
#if (defined MMI_MULTI_SIM_SYS_TRI || defined MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_PDA_PB_COPY_FROM_NV_TO_SIM3,"copy to sim3")
#endif
#ifdef MMI_MULTI_SIM_SYS_QUAD
RES_ADD_STRING(TXT_PDA_PB_COPY_FROM_NV_TO_SIM4,"copy to sim4")
#endif
RES_ADD_STRING(TXT_PDA_PB_COPY_FROM_NV_TO_PHONE,"copy to phone")

//RES_ADD_STRING(TXT_PB_FAVOURITE,"Favorite")
//RES_ADD_STRING(TXT_PB_RECENT_USED,"recent used")
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_PB_SELECT_NUMBER_TYPE_LABEL,"Select Number Type Label")
RES_ADD_STRING(TXT_PB_SELECT_IM_TYPE_LABEL,"Select Im Type Label")
#endif

//]]widget pb text id//Jonathan
#if (defined MMIWIDGET_SUPPORT) || (defined MMI_GRID_IDLE_SUPPORT)
RES_ADD_STRING(TXT_WIDGET_PB_ADDTO_FAVORITE_LIST_QUERY,"add to widget pb quick contacts list")
//RES_ADD_STRING(TXT_WIDGET_PB_FAVORITE,"Favorites")
RES_ADD_STRING(TXT_WIDGET_PB_ADD_TO_FAVORITE,"Add to quick contacts ")
//RES_ADD_STRING(TXT_WIDGET_PB_REMOVE_FROM_FAVORITE,"remove from quick contacts")    //case3: defined but not used
//RES_ADD_STRING(TXT_WIDGET_PB_QUICK_CONTACT,"quick contact")      //replaced by common ID TXT_COMMON_PB         
RES_ADD_STRING(TXT_WIDGET_PB_QUICK_CONTACT_HAS_EXIST,"the quick contact exists!")
#endif

#ifdef PIM_SUPPORT
RES_ADD_STRING(TXT_PIM_UPDATE_ENTER_PB_PROMPT,"Pim updating")
#endif

//RES_ADD_STRING(TXT_PB_SET,"Set")      //replaced by common ID STXT_MAIN_SETTING

#if defined( SNS_SUPPORT )&&defined(MMI_PDA_SUPPORT)    
RES_ADD_STRING(TXT_PB_SET_ACCOUNT_SUBSTR,"Set sns account")
#endif
//RES_ADD_STRING(TXT_PB_SET_SAVE_POSTION,"Save postion")    //replaced by common ID TXT_PRIOR_STORE_MEDIUM
//RES_ADD_STRING(TXT_PB_SET_DISPLAY_OPTION,"Display option")    //replaced by common ID TXT_DISPLAY_OPTION
#ifdef MMI_PDA_SUPPORT //ping.gao modify for non-pda compile error
RES_ADD_STRING(TXT_PB_SET_DISPLAY_OPTION_SUBSTR,"Select contact display")
//RES_ADD_STRING(TXT_PB_SET_TCARD,"Tcard")
//RES_ADD_STRING(TXT_PB_SET_ALWAYS_QUERY,"Always query")   //replaced by common ID TXT_COMMON_ASK_EVERYTIME
RES_ADD_STRING(TXT_PB_SET_DISPLAY_PERIOD,"Display period")
RES_ADD_STRING(TXT_PB_SET_DISPLAY_PERIOD_1DAY,"1 day")
RES_ADD_STRING(TXT_PB_SET_DISPLAY_PERIOD_3DAY,"3 day")
RES_ADD_STRING(TXT_PB_SET_DISPLAY_PERIOD_7DAY,"7 day")
RES_ADD_STRING(TXT_PB_SET_DISPLAY_PERIOD_30DAY,"30 day")
RES_ADD_STRING(TXT_PB_SET_QUICK_DIAL,"Quick dial number")
//RES_ADD_STRING(TXT_PB_SET_LOCAL_NUMBER," Local number") //replaced by local ID TXT_PB_MSISDN
RES_ADD_STRING(TXT_PB_SET_LOCAL_NUMBER_SUBSTR,"Set local number")  
RES_ADD_STRING(TXT_PB_SET_SERVICE_NUM,"Service number")
RES_ADD_STRING(TXT_PB_SET_SERVICE_NUM_SUBSTR,"Check or dial service num")
//RES_ADD_STRING(TXT_PB_SET_UPDATE_PERIOD,"Auto update")  //replaced by common ID TXT_COMMON_AUTO_UPDATE
RES_ADD_STRING(TXT_PB_SET_UPDATE_PERIOD_NONE,"None")
RES_ADD_STRING(TXT_PB_SET_UPDATE_PERIOD_30MIN,"Every 30 minute")
RES_ADD_STRING(TXT_PB_SET_UPDATE_PERIOD_1HOUR,"Every  hour")
RES_ADD_STRING(TXT_PB_SET_UPDATE_PERIOD_4HOUR,"Every 4 hours")
RES_ADD_STRING(TXT_PB_SET_UPDATE_PERIOD_8HOUR,"Every 8 hours")
#endif
//RES_ADD_STRING(TXT_PB_SET_UPDATE_PERIOD_1DAY,"Every day")         //replaced by common ID TXT_ALARM_MODE_EVERYDAY    
//RES_ADD_STRING(TXT_PB_SET_DATA_TRANSFER,"Data transfer")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SET_NET_CONNECT,"Net connect")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SET_NET_WLAN,"Wlan")    //case3: defined but not used
//RES_ADD_STRING(TXT_PB_SET_MANAGE_ACCOUNT,"Manage account")    //case3: defined but not used
RES_ADD_STRING(TXT_PB_SET_SNS_ADD,"Add account")

//PB detail
#ifdef MMI_PDA_SUPPORT //ping.gao modify for non-pda compile error
RES_ADD_STRING(TXT_PB_DETAIL_BASICDATA,"Basic data")
#endif
//RES_ADD_STRING(TXT_PB_DETAIL_CALLLOG,"Call log")    //replaced by common ID  STXT_MAIN_CL
#ifdef MMI_PDA_SUPPORT //ping.gao modify for non-pda compile error
RES_ADD_STRING(TXT_PB_DETAIL_MESSAGE,"Message")
#endif
//RES_ADD_STRING(TXT_PB_FAVOURITE_CONTACT_ADDED,"Favourite contact added")    //case3: defined but not used
//RES_ADD_STRING(TXT_EMAIL,"Email")    //replaced by common ID TXT_EMAIL 

#ifdef MMIPB_MOST_USED_SUPPORT    
RES_ADD_STRING(TXT_PB_FAVOURITE_CONTACT_REMOVED,"Favourite contact removed")
#endif
//RES_ADD_STRING(TXT_PB_CONTACT_DELETED,"Contact deleted")    //case3: defined but not used

//RES_ADD_STRING(TXT_PB_GROUP_RING,"Group Ring")
//RES_ADD_STRING(TXT_PB_ADD_GROUP_MEMBER,"Add group member")
RES_ADD_STRING(TXT_PB_OUT_OF_MAX_NUM,"Out Of Max Num")
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_PB_NEXT_STEP,"Next Setp")
#endif

//[[define image tag infomation
 #ifndef PB_SUPPORT_LOW_MEMORY
#ifdef CMCC_UI_STYLE
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_ADDRESS,"IMAGE_PHONEBOOK_ADDRESS")
#endif

RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_MEMO,"IMAGE_PHONEBOOK_MEMO")          
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_DUTY,"IMAGE_PHONEBOOK_DUTY")          
#endif
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_COMPANY,"IMAGE_PHONEBOOK_COMPANY")       
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_COM_ADDRESS,"IMAGE_PHONEBOOK_COM_ADDRESS")
#ifndef PB_SUPPORT_LOW_MEMORY
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_COMPANY_NUMBER,"IMAGE_PHONEBOOK_COMPANY_NUMBER")
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_FAX_NUMBER,"IMAGE_PHONEBOOK_FAX_NUMBER")  
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_PHONE_NUMBER,"IMAGE_PHONEBOOK_PHONE_NUMBER")  
#endif

//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP,"IMAGE_PHONEBOOK_GROUP")         
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP1,"IMAGE_PHONEBOOK_GROUP1")        
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP2,"IMAGE_PHONEBOOK_GROUP2")        
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP3,"IMAGE_PHONEBOOK_GROUP3")        
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP4,"IMAGE_PHONEBOOK_GROUP4")        
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP5,"IMAGE_PHONEBOOK_GROUP5")        
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP6,"IMAGE_PHONEBOOK_GROUP6")        
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP7,"IMAGE_PHONEBOOK_GROUP7")        
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP8,"IMAGE_PHONEBOOK_GROUP8")  
#ifdef MMIPB_MOST_USED_SUPPORT  
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP_MOSTUSED,"IMAGE_PHONEBOOK_GROUP_MOSTUSED")      
#endif   
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP_BUSINESS,"IMAGE_PHONEBOOK_GROUP_BUSINESS")
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP_COLLEAGUE,"IMAGE_PHONEBOOK_GROUP_COLLEAGUE")  
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP_FAMILY,"IMAGE_PHONEBOOK_GROUP_FAMILY")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP_FRIEND,"IMAGE_PHONEBOOK_GROUP_FRIEND")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP_SCHOOLMATE,"IMAGE_PHONEBOOK_GROUP_SCHOOLMATE") 
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP_SIM,"IMAGE_PHONEBOOK_GROUP_SIM")        
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP_VIP,"IMAGE_PHONEBOOK_GROUP_VIP")        
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_HOME_NUMBER,"IMAGE_PHONEBOOK_HOME_NUMBER")      
#ifdef MMIPB_MAIL_SUPPORT
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_MAIL_ADDRESS,"IMAGE_PHONEBOOK_MAIL_ADDRESS")     
#endif
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_MIDI,"IMAGE_PHONEBOOK_MIDI")        
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_NAME,"IMAGE_PHONEBOOK_NAME")        
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_PHONE,"IMAGE_PHONEBOOK_PHONE")       
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_PICTURE,"IMAGE_PHONEBOOK_PICTURE")     
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_SELECT_GROUP,"IMAGE_PHONEBOOK_SELECT_GROUP")
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_SELF_NUMBER,"IMAGE_PHONEBOOK_SELF_NUMBER") 
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_MOBILE_NUMBER,"IMAGE_PHONEBOOK_MOBILE_NUMBER")  

#ifdef MMI_MULTI_SIM_SYS_SINGLE
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_SIM,"IMAGE_PHONEBOOK_SIM")          
#endif
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_GROUP_UNCLASS,"IMAGE_PHONEBOOK_GROUP_UNCLASS")
#ifdef ASP_SUPPORT
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_ASP_RING,"IMAGE_PHONEBOOK_ASP_RING")     
#endif
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_ALL_OFF,"IMAGE_PHONEBOOK_TAB_ALL_OFF")  
#ifdef MMIPB_MOST_USED_SUPPORT
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_MOSTUSED_OFF,"IMAGE_PHONEBOOK_TAB_MOSTUSED_OFF") 
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_MOSTUSED_ON,"IMAGE_PHONEBOOK_TAB_MOSTUSED_ON")  
#endif
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP_ON,"IMAGE_PHONEBOOK_TAB_GROUP_ON")     
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP_OFF,"IMAGE_PHONEBOOK_TAB_GROUP_OFF")    
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP1_OFF,"IMAGE_PHONEBOOK_TAB_GROUP1_OFF")   
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP2_OFF,"IMAGE_PHONEBOOK_TAB_GROUP2_OFF")    
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP3_OFF,"IMAGE_PHONEBOOK_TAB_GROUP3_OFF")    
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP4_OFF,"IMAGE_PHONEBOOK_TAB_GROUP4_OFF")    
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP5_OFF,"IMAGE_PHONEBOOK_TAB_GROUP5_OFF")    
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP6_OFF,"IMAGE_PHONEBOOK_TAB_GROUP6_OFF")    
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP7_OFF,"IMAGE_PHONEBOOK_TAB_GROUP7_OFF")    
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP8_OFF,"IMAGE_PHONEBOOK_TAB_GROUP8_OFF")    
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_SIM_1_OFF,"IMAGE_PHONEBOOK_TAB_SIM_1_OFF")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_SIM_2_OFF,"IMAGE_PHONEBOOK_TAB_SIM_2_OFF")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_SIM_OFF,"IMAGE_PHONEBOOK_TAB_SIM_OFF")       
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_UNCLASS_OFF,"IMAGE_PHONEBOOK_TAB_UNCLASS_OFF")   

RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_ALL_ON,"IMAGE_PHONEBOOK_TAB_ALL_ON")        
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP1_ON,"IMAGE_PHONEBOOK_TAB_GROUP1_ON")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP2_ON,"IMAGE_PHONEBOOK_TAB_GROUP2_ON")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP3_ON,"IMAGE_PHONEBOOK_TAB_GROUP3_ON")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP4_ON,"IMAGE_PHONEBOOK_TAB_GROUP4_ON")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP5_ON,"IMAGE_PHONEBOOK_TAB_GROUP5_ON")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP6_ON,"IMAGE_PHONEBOOK_TAB_GROUP6_ON")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP7_ON,"IMAGE_PHONEBOOK_TAB_GROUP7_ON")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_GROUP8_ON,"IMAGE_PHONEBOOK_TAB_GROUP8_ON")     
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_SIM_1_ON,"IMAGE_PHONEBOOK_TAB_SIM_1_ON")      
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_SIM_2_ON,"IMAGE_PHONEBOOK_TAB_SIM_2_ON")      
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_SIM_ON,"IMAGE_PHONEBOOK_TAB_SIM_ON")        
//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_TAB_UNCLASS_ON,"IMAGE_PHONEBOOK_TAB_UNCLASS_ON")    
RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_SNE,"IMAGE_PHONEBOOK_SNE")        

//RES_ADD_IMG_TAG(IMAGE_PHONEBOOK_SEARCH_PIC,"IMAGE_PHONEBOOK_SEARCH_PIC") 

#ifdef MMI_PDA_SUPPORT //ping.gao modify for non-pda compile error
RES_ADD_STRING(TXT_PB_SNS_ACTIVITY,"Activity")
#endif
#ifdef  SNS_SUPPORT
RES_ADD_STRING(TXT_PB_SNS_UPDATE,"Sns Contact Update")
RES_ADD_STRING(TXT_PB_SNS_ACCOUNT_NOT_LOGIN,"Sns Account Is Not LogIn")
#endif
RES_ADD_STRING(TXT_PB_NO_SIM,"No Sim Card")
RES_ADD_STRING(TXT_PB_FULL_CAN_NOT_ADD_CONTACT,"Space is Full,Can not Add Contact")
RES_ADD_STRING(TXT_PB_CURRENT_STORAGE_FULL_SELECT_ANOTHER,"Current Storage Is Full,Please Select Another")
#ifdef MMIPB_GROUP_MANAGE_SUPPORT
RES_ADD_STRING(TXT_PB_GROUP_NAME_NOT_LEGAL, "Name is not legal")
RES_ADD_STRING(TXT_PB_GROUP_NAME_EXIST,"This name already existed")
#endif

RES_ADD_STRING(TXT_PB_SIM_CONTACT_EMPTY,"Name or mobile number can't be empty")

#ifdef BT_PBAP_SUPPORT
RES_ADD_STRING(TXT_PB_BT,"Bt")
RES_ADD_IMG(IMAGE_BT_CONTACT_TAB_ON,"\\MMI_RES_##\\IMAG\\IMAGE_BT_CONTACT_TAB_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_BT_CONTACT_TAB_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_BT_CONTACT_TAB_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//================================================================================================================================//
//                                                        For watch                                                               //
//================================================================================================================================//

//contacts portrait
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_BROTHER,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_brother.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_FATHER,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_father.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_GRANDFATHER,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_grandfather.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_GRANDMA,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_grandma.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_GRANDMOTHER,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_grandmother.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_GRANDPA,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_grandpa.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_MOTHER,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_mother.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_SISTER,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_sister.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_STRANGER,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_stranger.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_TEACHER,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_teacher.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef SCREEN_SHAPE_CIRCULAR
RES_ADD_IMG(IAMGE_CONTACT_PORTRAIT_CLASSMATE,"\\MMI_RES_##\\IMAG\\contact portrait\\res_contact_portrait_classmate.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_STRING(TXT_PB_CALL_LOG ,"Call Log")
RES_ADD_STRING(TXT_PB_EMERGENCY ,"Emergency Call")

//================================================================================================================================//
//                                                        For watch                                                               //
//================================================================================================================================//

//]]define data infomation
