/*
 * Copyright (C) 2021 UNISOC Technologies Co.,Ltd. All Rights Reserved
 *
 * Automatically generated by code_generator_unirtos.pm.
 */
#ifndef __JERRY_AUDIO_H__
#define __JERRY_AUDIO_H__

#include "sci_types.h"
#include "jerry_bindings.h"

#ifdef __cplusplus
extern "C" {
#endif
#if 0
typedef enum _AUDIO_EVENT_TYPE{
    EVENT_AUDIO_PLAY_CNF,

    EVENT_AUDIO_UNKNOWN
}AUDIO_EVENT_TYPE_E;

typedef struct _AudioEvent{
    AUDIO_EVENT_TYPE_E type;
    //data «∑Ò–Ë“™
}AudioPlayConformEvent;
int js_audio_play_conform(jerry_value_t this_value, AudioPlayConformEvent* p_Event);
#endif
void js_register_audio_functions(void);
uint8 js_is_audio_exist(void);



#ifdef __cplusplus
}
#endif

#endif // __JERRY_AUDIO_H__
