/*
 * Copyright (C) 2021 UNISOC Technologies Co.,Ltd. All Rights Reserved
 *
 * Automatically generated by code_generator_unirtos.pm.
 */
#ifndef __JERRY_AUDIO_EVENT_H__
#define __JERRY_AUDIO_EVENT_H__

#ifdef __cplusplus
extern "C" {
#endif

typedef enum _AUDIO_EVENT_TYPE
{
    EVENT_AUDIO_PLAY_CNF,
    EVENT_AUDIO_SUSPEND_IND,
    EVENT_AUDIO_RESUME_CNF,
    EVENT_AUDIO_PLAY_END_IND,
    EVENT_AUDIO_PLAY_PROGRESS_IND,
    EVENT_AUDIO_PAUSE_IND,
    EVENT_AUDIO_BEGIN_BUFFER_IND,
    EVENT_AUDIO_END_BUFFER_IND,
    EVENT_AUDIO_STOP_IND,
    EVENT_AUDIO_ERROR_IND,
    EVENT_AUDIO_UNKNOWN
}AUDIO_EVENT_TYPE_E;

typedef enum _AUDIO_ERROR_TYPE
{
    EVENT_AUDIO_PARAM_ERROR,
    EVENT_AUDIO_NO_ENOUGH_MMEMORY,
    EVENT_AUDIO_SET_VOLUME_FAIL,
    EVENT_AUDIO_SET_ROUTE_FAIL,
    EVENT_AUDIO_GET_PLAY_PROGRESS_FAIL,
    EVENT_AUDIO_PLAY_FAIL,
    EVENT_AUDIO_UNKNOWN_ERROR,
    EVENT_AUDIO_CREATE_FAIL,
    EVENT_AUDIO_NET_ERR,
    EVENT_AUDIO_ERROR_MAX,
}AUDIO_ERROR_TYPE_E;

typedef struct _AudioPlayConfirmEvent
{
    AUDIO_EVENT_TYPE_E type;
}audio_play_confirm_event_t;

typedef struct _AudioSuspendEvent
{
    AUDIO_EVENT_TYPE_E type;
}audio_suspend_event_t;

typedef struct _AudioResumeEvent
{
    AUDIO_EVENT_TYPE_E type;
}audio_resume_event_t;

typedef struct _AudioResumeConfirmEvent
{
    AUDIO_EVENT_TYPE_E type;
}audio_resume_confirm_event_t;

typedef struct _AudioPlayEndEvent
{
    AUDIO_EVENT_TYPE_E type;
}audio_play_end_event_t;

typedef struct _AudioPlayProgressEvent
{
    AUDIO_EVENT_TYPE_E type;
    uint32 cur_time;
    uint32 total_time;
}audio_play_progress_event_t;

typedef struct _AudioPauseEvent
{
    AUDIO_EVENT_TYPE_E type;
}audio_pause_event_t;

typedef struct _AudioBeginBufferEvent
{
    AUDIO_EVENT_TYPE_E type;
}audio_begin_buffer_event_t;

typedef struct _AudioEndBufferEvent
{
    AUDIO_EVENT_TYPE_E type;
}audio_end_buffer_event_t;

typedef struct _AudioStopEvent
{
    AUDIO_EVENT_TYPE_E type;
}audio_stop_event_t;

typedef struct _AudioErrorEvent
{
    AUDIO_EVENT_TYPE_E type;
    AUDIO_ERROR_TYPE_E err_type;
}audio_error_event_t;
/*****************************************************************************/
//  Description: play conformÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_play_confirm_event_t //²¥·Å³É¹¦µÄÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] ual_audioplayer_err_e //½Ó¿Úµ÷ÓÃ½á¹û
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_play_confirm_event(jerry_value_t this_value, audio_play_confirm_event_t* p_Event);
/*****************************************************************************/
//  Description: suspend conformÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_suspend_event_t //±»¹ÒÆðµÄÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_suspend_event(jerry_value_t this_value, audio_suspend_event_t* p_Event);

/*****************************************************************************/
//  Description: resume conformÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_resume_event_t //ResumeÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_resume_event(jerry_value_t this_value, audio_resume_event_t* p_Event);
/*****************************************************************************/
//  Description: play endÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_play_end_event_t //play endÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_play_end_event(jerry_value_t this_value, audio_play_end_event_t* p_Event);
/*****************************************************************************/
//  Description: play pgressÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_play_progress_event_t //play progressÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_play_progress_event(jerry_value_t this_value, audio_play_progress_event_t* p_Event);
/*****************************************************************************/
//  Description: pauseÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_pause_event_t //pauseÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_pause_event(jerry_value_t this_value, audio_pause_event_t* p_Event);
/*****************************************************************************/
//  Description: begin bufferÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_begin_buffer_event_t //begin bufferÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_begin_buffer_event(jerry_value_t this_value, audio_begin_buffer_event_t* p_Event);
/*****************************************************************************/
//  Description: end bufferÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_end_buffer_event_t //end bufferÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_end_buffer_event(jerry_value_t this_value, audio_end_buffer_event_t* p_Event);

/*****************************************************************************/
//  Description: audio stopÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_stop_event_t //audio stopÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_stop_event(jerry_value_t this_value, audio_stop_event_t* p_Event);
/*****************************************************************************/
//  Description: audio errorÊÂ¼þ»Ø¸øJSµÄº¯Êý
//  Parameter: [In] jerry_value_t //JS AUDIO¶ÔÏó
//             [In] audio_error_event_t //audio errorÏûÏ¢¼°Ð¯´øµÄÊý¾Ý
//             [Out] None
//             [Return] None
//  Author: changli.jiang
//  Note:
/*****************************************************************************/
void js_audio_error_event(jerry_value_t this_value, audio_error_event_t* p_Event);
#ifdef __cplusplus
}
#endif

#endif // __JERRY_AUDIO_H__
