/*****************************************************************************
** File Name:      mmimtv_position.h                                         *
** Author:                                                                   *
** Date:           02/01/2009                                                *
** Copyright:      2009 Spreadtrum, Incoporated. All Rights Reserved.         *
** Description:                                                              *
******************************************************************************
**                         Important Edit History                            *
** --------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                               *
** 09/2007       AOKE.HU              Create
******************************************************************************/
#ifdef CMMB_SUPPORT
#ifndef _MMIMTV_POSITION_H_
#define _MMIMTV_POSITION_H_

/**---------------------------------------------------------------------------*
 **                         Dependencies                                      *
 **---------------------------------------------------------------------------*/
#include "mmi_position.h"
#include "guitab.h"

//#define MMIMTV_SOFTKEY_ON_BOTTOM     //»Ìº¸‘⁄œ¬£®º¸≈Ã‘⁄œ¬£©£¨»Ìº¸‘⁄”“£®º¸≈Ã‘⁄”“£©
#ifdef MAINLCD_SIZE_128X160      //176*220
#define MMIMTV_LCD_HEIGHT       128
#define MMIMTV_LCD_WIDTH        160

#define MMIMTV_VOL_MUTE_OFFSET_Y    12
#define MMIMTV_VOL_OFFSET_Y         31
#define MMIMTV_BRI_OFFSET_X         16
#elif MAINLCD_SIZE_176X220      //176*220
#define MMIMTV_LCD_HEIGHT       176
#define MMIMTV_LCD_WIDTH        220

#define MMIMTV_VOL_MUTE_OFFSET_Y    12
#define MMIMTV_VOL_OFFSET_Y         31
#define MMIMTV_BRI_OFFSET_X         16

#elif defined MAINLCD_SIZE_240X320    //240*320
#define MMIMTV_LCD_HEIGHT       240
#define MMIMTV_LCD_WIDTH        320

#define MMIMTV_VOL_MUTE_OFFSET_Y    12
#define MMIMTV_VOL_OFFSET_Y         31
#define MMIMTV_BRI_OFFSET_X         16

//added by lxf for dphone
#elif defined MAINLCD_SIZE_64X128
#define MMIMTV_LCD_HEIGHT       240
#define MMIMTV_LCD_WIDTH        320

#define MMIMTV_VOL_MUTE_OFFSET_Y    12
#define MMIMTV_VOL_OFFSET_Y         31
#define MMIMTV_BRI_OFFSET_X         16

#elif defined MAINLCD_SIZE_240X400  //240*400
#define MMIMTV_LCD_HEIGHT       240
#define MMIMTV_LCD_WIDTH        400

#define MMIMTV_VOL_MUTE_OFFSET_Y    12
#define MMIMTV_VOL_OFFSET_Y         31
#define MMIMTV_BRI_OFFSET_X         16

#elif defined MAINLCD_SIZE_320X480 
#define MMIMTV_LCD_HEIGHT       320
#define MMIMTV_LCD_WIDTH        480

#define MMIMTV_VOL_MUTE_OFFSET_Y    28
#define MMIMTV_VOL_OFFSET_Y         67
#define MMIMTV_BRI_OFFSET_X         35

#else
#error
#endif

#define MTV_MENU_WIDTH              MIN(MMIMTV_LCD_WIDTH*3/4, MMIMTV_LCD_HEIGHT)
#define MMIMTV_SOFTKEY_HEIGHT       25
#define MMIMTV_SOFTKEY_WIDTH        40
#define MTV_TITLE_HEIGHT            32

#define MTV_OSD_LEFT                ((MMIMTV_LCD_WIDTH - MMIMTV_SOFTKEY_WIDTH - MTV_MENU_WIDTH) / 2)
#define MTV_OSD_TOP                 (MTV_TITLE_HEIGHT * 2 + MMI_STATUSBAR_HEIGHT)
#define MTV_OSD_RIGHT               (MTV_OSD_LEFT + MTV_MENU_WIDTH - 1)
#define MTV_OSD_BOTTOM              (MMIMTV_LCD_HEIGHT - MTV_TITLE_HEIGHT)

#define MTV_MSGBOX_LEFT             MTV_OSD_LEFT
#define MTV_MSGBOX_TOP              (MMIMTV_LCD_HEIGHT/4) //((MMIMTV_LCD_HEIGHT - 95) / 2)
#define MTV_MSGBOX_RIGHT            (MTV_MSGBOX_LEFT + MTV_MENU_WIDTH - 1)
#define MTV_MSGBOX_BOTTOM           (MTV_MSGBOX_TOP + MMIMTV_LCD_HEIGHT/2)

//common
#define MMIMTV_BOTTOM_MAX_PIXEL                 (MMIMTV_LCD_HEIGHT-1)
#define MMIMTV_RIGHT_MAX_PIXEL                  (MMIMTV_LCD_WIDTH-1)

#define MMIMTV_UP_SOFTKEY_LEFT                  (MMIMTV_RIGHT_MAX_PIXEL-MMIMTV_SOFTKEY_WIDTH)
#define MMIMTV_UP_SOFTKEY_TOP                   (MMIMTV_BOTTOM_MAX_PIXEL-MMIMTV_SOFTKEY_HEIGHT)
#define MMIMTV_UP_SOFTKEY_RIGHT                 MMIMTV_RIGHT_MAX_PIXEL
#define MMIMTV_UP_SOFTKEY_BOTTOM                MMIMTV_BOTTOM_MAX_PIXEL

#define MMIMTV_DOWN_SOFTKEY_LEFT                (MMIMTV_RIGHT_MAX_PIXEL-MMIMTV_SOFTKEY_WIDTH)
#define MMIMTV_DOWN_SOFTKEY_TOP                 0
#define MMIMTV_DOWN_SOFTKEY_RIGHT               MMIMTV_RIGHT_MAX_PIXEL
#define MMIMTV_DOWN_SOFTKEY_BOTTOM              MMIMTV_SOFTKEY_HEIGHT



//#define MMIMTV_PROGRESS_WIDTH                   112
//#define MMIMTV_PROGRESS_HEIGHT                  15
//#define MMIMTV_PROGRESS_LEFT                    ((MMIMTV_LCD_WIDTH - MMIMTV_SOFTKEY_WIDTH - MMIMTV_PROGRESS_WIDTH) / 2)
//#define MMIMTV_PROGRESS_TOP                     (MMIMTV_LCD_HEIGHT * 5 / 6)
//#define MMIMTV_PROGRESS_RIGHT                   (MMIMTV_PROGRESS_LEFT + MMIMTV_PROGRESS_WIDTH)
//#define MMIMTV_PROGRESS_BOTTOM                  (MMIMTV_PROGRESS_TOP + MMIMTV_PROGRESS_HEIGHT)
//#define MMIMTV_PROGRESS_BAR_LEFT                (MMIMTV_PROGRESS_LEFT + 16)
//#define MMIMTV_PROGRESS_BAR_TOP                 (MMIMTV_PROGRESS_TOP + 3)

//volume progress
//#define MMIMTV_VOLUME_PROGRESS_WIDTH            15
//#define MMIMTV_VOLUME_PROGRESS_HEIGHT           112
//#define MMIMTV_VOLUME_PROGRESS_LEFT             9
//#define MMIMTV_VOLUME_PROGRESS_TOP              (MTV_OSD_TOP + (MTV_OSD_BOTTOM - MTV_OSD_TOP - MMIMTV_VOLUME_PROGRESS_HEIGHT) / 2)
//#define MMIMTV_VOLUME_PROGRESS_RIGHT            (MMIMTV_VOLUME_PROGRESS_LEFT + MMIMTV_VOLUME_PROGRESS_WIDTH)
//#define MMIMTV_VOLUME_PROGRESS_BOTTOM           (MMIMTV_VOLUME_PROGRESS_TOP + MMIMTV_VOLUME_PROGRESS_HEIGHT)
//#define MMIMTV_VOLUME_PROGRESS_BAR_LEFT         (MMIMTV_VOLUME_PROGRESS_LEFT + 3)
//#define MMIMTV_VOLUME_PROGRESS_BAR_TOP          (MMIMTV_VOLUME_PROGRESS_TOP + 31)
////mute icon
//#define MMIMTV_MUTE_PROGRESS_BG_TOP             (MMIMTV_VOLUME_PROGRESS_TOP + 12)
//increase/decrease icon height
#define MMIMTV_INCREASE_ICON_WIDTH              12

#define MMIMTV_EDITBOX_HEIGHT                   24
#define MMIMTV_TITLE_STRING_OFFSET              8
#define MMIMTV_ITEM_MAX_INDEX                   5

#define MMIMTV_WATCH_TIME_TIP_LEFT              20
#define MMIMTV_WATCH_TIME_TIP_HEIGHT            20

#define MMIMTV_ICONSTART_X                      (MMIMTV_LCD_WIDTH - 37)
#define MMIMTV_ICONSTART_Y                      55

#define MMIMTV_PUBWIN_ICON_WIDTH                54
#define MMIMTV_FONT_HALF_HEIGHT                 8
#define MMIMTV_PUBWIN_ICON_MARGIN               6
#define MMIMTV_PUBWIN_ICON_LEFT                 (MTV_MSGBOX_LEFT + MMIMTV_PUBWIN_ICON_MARGIN)
#define MMIMTV_PUBWIN_ICON_TOP                  MTV_MSGBOX_TOP 
#define MMIMTV_PUBWIN_POINTS_NUMBER             6

#define MTV_MSGBOX_TEXT_RECT                    {MTV_MSGBOX_LEFT+MMIMTV_PUBWIN_ICON_WIDTH,MTV_MSGBOX_TOP+2,MTV_MSGBOX_RIGHT-2,MTV_MSGBOX_BOTTOM-2}

#define MMIMTV_LEFT_ARROW_LEFT                  (MTV_OSD_LEFT)
#define MMIMTV_LEFT_ARROW_TOP                   (MTV_OSD_TOP - MTV_TITLE_HEIGHT)
#define MMIMTV_LEFT_ARROW_RIGHT                 (MMIMTV_LEFT_ARROW_LEFT + 32)
#define MMIMTV_LEFT_ARROW_BOTTOM                (MTV_OSD_TOP - MTV_TITLE_HEIGHT + 32)
#define MMIMTV_RIGHT_ARROW_LEFT                 (MTV_OSD_RIGHT - 32)
#define MMIMTV_RIGHT_ARROW_TOP                  MMIMTV_LEFT_ARROW_TOP
#define MMIMTV_RIGHT_ARROW_RIGHT                (MTV_OSD_RIGHT)
#define MMIMTV_RIGHT_ARROW_BOTTOM               (MTV_OSD_TOP - MTV_TITLE_HEIGHT + 32)

//service number arrow
#define MMIMTV_SERVICE_LEFT_ARROW_LEFT          2
#define MMIMTV_SERVICE_LEFT_ARROW_TOP           (3 + MMIMTV_STATUS_BAR_BOTTOM)
#define MMIMTV_SERVICE_LEFT_ARROW_RIGHT         13
#define MMIMTV_SERVICE_LEFT_ARROW_BOTTOM        (17 + MMIMTV_STATUS_BAR_BOTTOM)
#define MMIMTV_SERVICE_RIGHT_ARROW_LEFT         61
#define MMIMTV_SERVICE_RIGHT_ARROW_TOP          MMIMTV_SERVICE_LEFT_ARROW_TOP
#define MMIMTV_SERVICE_RIGHT_ARROW_RIGHT        (MMIMTV_SERVICE_RIGHT_ARROW_LEFT + 11)
#define MMIMTV_SERVICE_RIGHT_ARROW_BOTTOM       MMIMTV_SERVICE_LEFT_ARROW_BOTTOM
#define MMIMTV_SERVICE_TEXT_LEFT                (MMIMTV_SERVICE_LEFT_ARROW_RIGHT + 4)
#define MMIMTV_SERVICE_TEXT_TOP                 MMIMTV_SERVICE_LEFT_ARROW_TOP
#define MMIMTV_SERVICE_TEXT_RIGHT               MMIMTV_SERVICE_RIGHT_ARROW_LEFT
#define MMIMTV_SERVICE_TEXT_BOTTOM              (MMIMTV_SERVICE_LEFT_ARROW_TOP + 16)

#define MMIMTV_RECORD_FILE_NAME_LEFT            (MMIMTV_SERVICE_LEFT_ARROW_RIGHT + 2)
#define MMIMTV_RECORD_FILE_NAME_TOP             (20+1)
#define MMIMTV_RECORD_FILE_NAME_RIGHT           (MMIMTV_RECORD_FILE_NAME_LEFT + MTV_MENU_WIDTH -1)
#define MMIMTV_RECORD_FILE_NAME_BOTTOM          (MMIMTV_RECORD_FILE_NAME_TOP+15)

//record play progress
#define MMIMTV_RECORD_PLAY_BAR_WIDTH                (70 + 130 + 70)
#define MMIMTV_RECORD_PLAY_BAR_TOP                  224
#define MMIMTV_RECORD_PLAY_PROGRESS_GROOVE_WIDTH    126
#define MMIMTV_RECORD_PLAY_PROGRESS_GROOVE_HEITHT   12
#define MMIMTV_RECORD_PLAY_PROGRESS_WIDTH           124
#define MMIMTV_RECORD_PLAY_PROGRESS_HEITHT          6
#define MMIMTV_RECORD_PALY_PROGRESS_SLIDE_WIDTH     12
#define MMIMTV_RECORD_PLAY_PROGRESS_SLIDE_HEIGHT    12
#define MMIMTV_RECORD_PLAY_PROGRESS_GROOVE_LEFT     (((MMIMTV_LCD_WIDTH - MMIMTV_RECORD_PLAY_BAR_WIDTH -MMIMTV_SOFTKEY_WIDTH) / 2) + 70)
#define MMIMTV_RECORD_PLAY_PROGRESS_GROOVE_TOP      (MMIMTV_RECORD_PLAY_BAR_TOP + 2)
#define MMIMTV_RECORD_PLAY_PROGRESS_LEFT            (MMIMTV_RECORD_PLAY_PROGRESS_GROOVE_LEFT + 1)
#define MMIMTV_RECORD_PLAY_PROGRESS_TOP             (MMIMTV_RECORD_PLAY_PROGRESS_GROOVE_TOP + 3)

//record play time
#define MMIMTV_RECORD_PLAY_TIME_LEFT            ((MMIMTV_LCD_WIDTH - MMIMTV_RECORD_PLAY_BAR_WIDTH -MMIMTV_SOFTKEY_WIDTH) / 2)
#define MMIMTV_RECORD_PLAY_TIME_TOP             MMIMTV_RECORD_PLAY_BAR_TOP
#define MMIMTV_RECORD_PLAY_TIME_RIGHT           (MMIMTV_RECORD_PLAY_TIME_LEFT + 70)
#define MMIMTV_RECORD_PLAY_TIME_BOTTOM          (MMIMTV_RECORD_PLAY_TIME_TOP + 14)

#define MMIMTV_RECORD_TOTAL_TIME_LEFT           (MMIMTV_RECORD_PLAY_TIME_LEFT + MMIMTV_RECORD_PLAY_BAR_WIDTH - 70)
#define MMIMTV_RECORD_TOTAL_TIME_TOP            MMIMTV_RECORD_PLAY_BAR_TOP
#define MMIMTV_RECORD_TOTAL_TIME_RIGHT          (MMIMTV_RECORD_TOTAL_TIME_LEFT + 70)
#define MMIMTV_RECORD_TOTAL_TIME_BOTTOM         (MMIMTV_RECORD_TOTAL_TIME_TOP + 14)

#define MMIMTV_STATUS_BAR_TOP                   1
#define MMIMTV_STATUS_BAR_BOTTOM                MMI_STATUSBAR_HEIGHT

#define MMIMTV_RECORD_TIME_LEFT                 (MMIMTV_LCD_WIDTH - 170)
#define MMIMTV_RECORD_TIME_WIDTH                110
#define MMIMTV_REC_TEXT_WIDTH                   20

#define MMIMTV_SERVICE_SHORTCUT_KEY_LEFT        5
#define MMIMTV_SERVICE_SHORTCUT_KEY_TOP         20
#define MMIMTV_SERVICE_SHORTCUT_KEY_RIGHT       45
#define MMIMTV_SERVICE_SHORTCUT_KEY_BOTTOM      50

//MBBMS Main Interface
#define MMIMBBMS_FULLSCREEN_CLIENT_LEFT         0
#define MMIMBBMS_FULLSCREEN_CLIENT_TOP          (MMI_STATUSBAR_HEIGHT+MMI_TITLE_HEIGHT+MMI_TAB_CHILD_WINDOW_TOP)
#define MMIMBBMS_FULLSCREEN_CLIENT_RIGHT        MMI_MAINSCREEN_RIGHT_MAX_PIXEL
#define MMIMBBMS_FULLSCREEN_CLIENT_BOTTOM       (MMI_MAINSCREEN_BOTTOM_MAX_PIXEL - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT)

//MBBMS play connecting
#define MMIMBBMS_PLAY_CONNECT_STARTUP_LEFT		(MTV_MSGBOX_LEFT + (MTV_MSGBOX_RIGHT - MTV_MSGBOX_LEFT - 48) / 2)
#define MMIMBBMS_PLAY_CONNECT_STARTUP_TOP		(MTV_MSGBOX_TOP + 20)
#define MMIMBBMS_PLAY_CONNECT_PROGRESS_LEFT		(MTV_MSGBOX_LEFT + (MTV_MSGBOX_RIGHT - MTV_MSGBOX_LEFT - 126) / 2)
#define MMIMBBMS_PLAY_CONNECT_PROGRESS_TOP		(MTV_MSGBOX_BOTTOM - 10)

//welcome words
#define MMIMBBMS_WELCOME_WORDS_TOP		        (MMIMBBMS_PLAY_CONNECT_PROGRESS_TOP + 15)
#define MMIMBBMS_WELCOME_WORDS_BOTTOM		    (MMIMBBMS_WELCOME_WORDS_TOP + 20)

//cmmb logo
#define MMIMTV_CMMB_LOGO_LEFT                   (MTV_OSD_LEFT + 1)
#define MMIMTV_CMMB_LOGO_TOP                    (MTV_OSD_TOP - MTV_TITLE_HEIGHT + 2)
#define MMIMTV_CMMB_LOGO_WIDTH                  56

#define MMIMBBMS_TAB_ITEM_SPACE                 3
#define MMIMBBMS_MAINTAB_ITEM_SPACE             10


#define MMIMBBMS_CONTENT_LBUTTON_WIDTH     35
#define MMIMBBMS_CONTENT_LBUTTON_HEIGHT    29

#define MMIMBBMS_CONTENT_LBUTTON_TOP        (MMI_CLIENT_RECT_BOTTOM - MMIMBBMS_CONTENT_LBUTTON_HEIGHT-1)
#define MMIMBBMS_CONTENT_RBUTTON_LEFT       (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMIMBBMS_CONTENT_LBUTTON_WIDTH+1)

#define MMIMBBMS_CONTENT_LABEL_LEFT        (MMIMBBMS_CONTENT_LBUTTON_WIDTH)
#define MMIMBBMS_CONTENT_LABEL_RIGHT       (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMIMBBMS_CONTENT_LBUTTON_WIDTH-1)

#define MMIMBBMS_DETAIL_IMAGE_WIDTH        60

//switch play tab for mbbms2.0
#define MMIMTV_SWITCH_TAB_LEFT                  0
#define MMIMTV_SWITCH_TAB_TOP                   MTV_OSD_BOTTOM
#define MMIMTV_SWITCH_TAB_RIGHT                 (MMIMTV_LCD_WIDTH -1)
#define MMIMTV_SWITCH_TAB_BOTTOM                (MMIMTV_LCD_HEIGHT -1)

//for update win
//#define MMIMBBMS_UPDATE_SELECT_LABEL_LEFT   0        
//#define MMIMBBMS_UPDATE_SELECT_LABEL_RIGHT   MMI_MAINSCREEN_RIGHT_MAX_PIXEL
//#define MMIMBBMS_UPDATE_SELECT_LABEL_TOP   (MMI_STATUSBAR_HEIGHT+MMI_TITLE_HEIGHT)
//#define MMIMBBMS_UPDATE_SELECT_LABEL_BOTTOM   (MMIMBBMS_UPDATE_SELECT_LABEL_TOP+MMI_LIST_ITEM_HEIGHT)

//#define MMIMBBMS_UPDATE_LIST_LEFT   0
//#define MMIMBBMS_UPDATE_LIST_RIGHT MMI_MAINSCREEN_RIGHT_MAX_PIXEL
//#define MMIMBBMS_UPDATE_LIST_TOP (MMIMBBMS_UPDATE_SELECT_LABEL_BOTTOM+1)
//#define MMIMBBMS_UPDATE_LIST_BOTTOM   (MMI_MAINSCREEN_BOTTOM_MAX_PIXEL - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT)

//#define MMIMBBMS_UPDATE_IPNUT_CITY_PROMPT_LABEL_LEFT   MMIMBBMS_LABEL_LEFT        
//#define MMIMBBMS_UPDATE_IPNUT_CITY_PROMPT_LABEL_RIGHT   (MMI_MAINSCREEN_RIGHT_MAX_PIXEL-5)
//#define MMIMBBMS_UPDATE_IPNUT_CITY_PROMPT_LABEL_TOP   (MMI_STATUSBAR_HEIGHT+MMI_TITLE_HEIGHT)
//#define MMIMBBMS_UPDATE_IPNUT_CITY_PROMPT_LABEL_BOTTOM   MMIMBBMS_LABEL_BOTTOM5

//#define MMIMBBMS_UPDATE_CITY_NAME_LABEL_LEFT   MMIMBBMS_LABEL_LEFT
//#define MMIMBBMS_UPDATE_CITY_NAME_LABEL_RIGHT (MMI_MAINSCREEN_RIGHT_MAX_PIXEL-5)
//#define MMIMBBMS_UPDATE_CITY_NAME_LABEL_TOP MMIMBBMS_LABLE_TOP6
//#define MMIMBBMS_UPDATE_CITY_NAME_LABEL_BOTTOM   (MMIMBBMS_UPDATE_CITY_NAME_LABEL_TOP + 20)


#endif
#endif
