/******************************************************************************
 ** File Name:      sci_log_sim.h                                             *
 ** Author:         Raislin.Kong                                              *
 ** Date:           2003.2                                                    *
 ** Copyright:      Copyright 2001-2010 by Spreadtrum Communications,Inc.     *
 **                 All Rights Reserved.                                      *
 **                 This software is supplied under the terms of a license    *
 **                 agreement or non-disclosure agreement with Spreadtrum.    *
 **                 Passing on and copying of this document,and communication *
 **                 of its contents is not permitted without prior written    *
 **                 authorization.                                            *
 ** Description:                                                              *
 ******************************************************************************

 ******************************************************************************
 **                        Edit History                                       *
 ** --------------------------------------------------------------------------*
 ** Date           Name             Description                               *
 **---------------------------------------------------------------------------*
 ** 2003.2         Raislin.Kong     Create                                    *
 ******************************************************************************/
typedef enum
{
    SIM_SIG_START_UP_REQ = END_SDL_SIM_SIGNAL,
    SIM_SIG_READ_T_FILE_REQ,
    SIM_SIG_READ_R_FILE_REQ,
    SIM_SIG_UPDATE_T_FILE_REQ,
    SIM_SIG_UPDATE_R_FILE_REQ,
    SIM_SIG_INCREASE_FILE_REQ,
    SIM_SIG_INITIALIZE_REQ,
    SIM_SIG_UPDATE_CCP_REQ,
    SIM_SIG_READ_CCP_REQ,
    SIM_SIG_ERASE_CCP_REQ,
    SIM_SIG_UPDATE_DN_REQ,
    SIM_SIG_READ_DN_REQ,
    SIM_SIG_ERASE_DN_REQ,
    SIM_SIG_PURGE_DN_REQ,
    SIM_SIG_FDN_SERVICE_REQ,
    SIM_SIG_BDN_SERVICE_REQ,
    SIM_SIG_SESSION_TERMINATION_REQ,
    SIM_SIG_CHV_REQ,
    SIM_SIG_GSM_ALGORITHMS_REQ,
    SIM_SIG_RESPONSE_IND,
    SIM_SIG_INT_IND,
    SIM_SIG_CARD_INSERTED_IND,
    SIM_SIG_GET_RECORD_EF_INFO_REQ,
    SIM_SIG_SMS_READ_SMS_STATUS_REQ   ,
    SIM_SIG_SMS_READ_PARAM_REQ ,
    SIM_SIG_SMS_READ_SMS_REQ   ,
    SIM_SIG_SMS_WRITE_SMS_REQ  ,
    SIM_SIG_SMS_UPDATE_SMS_STATUS_REQ  ,
    SIM_SIG_SMS_READ_STATUS_REPORT_REQ ,
    SIM_SIG_SMS_WRITE_STATUS_REPORT_REQ,
    SIM_SIG_SMS_READ_TP_MR_REQ ,
    SIM_SIG_SMS_WRITE_TP_MR_REQ,
    SIM_SIG_SMS_WRITE_PARAM_REQ,
    SIM_SIG_GET_SPN_REQ ,
    SIM_SIG_READ_ECC_REQ,
    SIM_SIG_READ_LP_REQ,
    SIM_SIG_UPDATE_LP_REQ,
    SIM_SIG_READ_AD_REQ,
    SIM_SIG_READ_SST_REQ,
    SIM_SIG_READ_PHASE_REQ,
    SIM_SIG_READ_ELP_REQ,
    SIM_SIG_UPDATE_ELP_REQ,
    SIM_SIG_READ_IMSI_REQ,
    SIM_SIG_READ_ACC_REQ,
    SIM_SIG_READ_HPLMN_REQ,
    SIM_SIG_READ_LOCI_REQ,
    SIM_SIG_UPDATE_LOCI_REQ,
    SIM_SIG_READ_KC_REQ,
    SIM_SIG_UPDATE_KC_REQ,
    SIM_SIG_READ_BCCH_REQ,
    SIM_SIG_UPDATE_BCCH_REQ,
    SIM_SIG_READ_FPLMN_REQ,
    SIM_SIG_UPDATE_FPLMN_REQ,
    SIM_SIG_READ_PLMNSEL_REQ,
    SIM_SIG_UPDATE_PLMNSEL_REQ,
    SIM_SIG_READ_CBMI_REQ,
    SIM_SIG_UPDATE_CBMI_REQ,
    SIM_SIG_READ_GID1_REQ,
    SIM_SIG_READ_GID2_REQ,
    SIM_SIG_READ_VGCS_REQ,
    SIM_SIG_READ_VGCSS_REQ,
    SIM_SIG_READ_VBS_REQ,
    SIM_SIG_READ_VBSS_REQ,
    SIM_SIG_READ_EMLPP_REQ,
    SIM_SIG_READ_AAEM_REQ,
    SIM_SIG_UPDATE_AAEM_REQ,
    SIM_SIG_READ_CBMIR_REQ,
    SIM_SIG_UPDATE_CBMIR_REQ,
    SIM_SIG_READ_DCK_REQ,
    SIM_SIG_READ_NIA_REQ,
    SIM_SIG_AOC_READ_ACM_REQ,
    SIM_SIG_AOC_INIT_ACM_REQ,
    SIM_SIG_AOC_INCREASE_ACM_REQ,
    SIM_SIG_AOC_READ_ACMMAX_REQ,
    SIM_SIG_AOC_UPDATE_ACMMAX_REQ,
    SIM_SIG_AOC_READ_PUCT_REQ,
    SIM_SIG_AOC_UPDATE_PUCT_REQ,
    SIM_SIG_CLOCK_STOP_IND,
    SIM_SIG_QUERY_CARD_STATUS_REQ,
    SIM_SIG_GET_FILE_INFO_REQ,
    SIM_SIG_PC_EXIST_IND,
    SIM_SIG_GET_ACCESS_INFO_REQ,
    SIM_SIG_POWER_OFF_REQ,
    SIM_SIG_PRESENT_CHECK_IND,
    SIM_SIG_READ_T_FILE_CNF = END_SDL_MN_SIGNAL + 2,
    SIM_SIG_READ_R_FILE_CNF,
    SIM_SIG_UPDATE_T_FILE_CNF,
    SIM_SIG_UPDATE_R_FILE_CNF,
    SIM_SIG_INCREASE_FILE_CNF,
    SIM_SIG_INITIALIZE_CNF,
    SIM_SIG_UPDATE_CCP_CNF,
    SIM_SIG_READ_CCP_CNF,
    SIM_SIG_ERASE_CCP_CNF,
    SIM_SIG_UPDATE_DN_CNF,
    SIM_SIG_READ_DN_CNF,
    SIM_SIG_ERASE_DN_CNF,
    SIM_SIG_PURGE_DN_CNF,
    SIM_SIG_FDN_SERVICE_CNF,
    SIM_SIG_BDN_SERVICE_CNF,
    SIM_SIG_SESSION_TERMINATION_CNF,
    SIM_SIG_CHV_CNF,
    SIM_SIG_GSM_ALGORITHMS_CNF,
    SIM_SIG_CARD_PRESENT_IND,
    SIM_SIG_CARD_REMOVE_IND,
    SIM_SIG_GET_RECORD_EF_INFO_CNF,
    SIM_SIG_SMS_READ_SMS_STATUS_CNF,
    SIM_SIG_SMS_READ_PARAM_CNF,
    SIM_SIG_SMS_READ_SMS_CNF,
    SIM_SIG_SMS_WRITE_SMS_CNF,
    SIM_SIG_SMS_UPDATE_SMS_STATUS_CNF,
    SIM_SIG_SMS_READ_STATUS_REPORT_CNF,
    SIM_SIG_SMS_WRITE_STATUS_REPORT_CNF,
    SIM_SIG_SMS_READ_TP_MR_CNF,
    SIM_SIG_SMS_WRITE_TP_MR_CNF,
    SIM_SIG_SMS_WRITE_PARAM_CNF,
    SIM_SIG_GET_SPN_CNF ,
    SIM_SIG_READ_ECC_CNF,
    SIM_SIG_READ_LP_CNF,
    SIM_SIG_UPDATE_LP_CNF,
    SIM_SIG_READ_AD_CNF,
    SIM_SIG_READ_SST_CNF,
    SIM_SIG_READ_PHASE_CNF,
    SIM_SIG_READ_ELP_CNF,
    SIM_SIG_UPDATE_ELP_CNF,
    SIM_SIG_READ_IMSI_CNF,
    SIM_SIG_READ_ACC_CNF,
    SIM_SIG_READ_HPLMN_CNF,
    SIM_SIG_READ_LOCI_CNF,
    SIM_SIG_UPDATE_LOCI_CNF,
    SIM_SIG_READ_KC_CNF,
    SIM_SIG_UPDATE_KC_CNF,
    SIM_SIG_READ_BCCH_CNF,
    SIM_SIG_UPDATE_BCCH_CNF,
    SIM_SIG_READ_FPLMN_CNF,
    SIM_SIG_UPDATE_FPLMN_CNF,
    SIM_SIG_READ_PLMNSEL_CNF,
    SIM_SIG_UPDATE_PLMNSEL_CNF,
    SIM_SIG_READ_CBMI_CNF,
    SIM_SIG_UPDATE_CBMI_CNF,
    SIM_SIG_READ_GID1_CNF,
    SIM_SIG_READ_GID2_CNF,
    SIM_SIG_READ_VGCS_CNF,
    SIM_SIG_READ_VGCSS_CNF,
    SIM_SIG_READ_VBS_CNF,
    SIM_SIG_READ_VBSS_CNF,
    SIM_SIG_READ_EMLPP_CNF,
    SIM_SIG_READ_AAEM_CNF,
    SIM_SIG_UPDATE_AAEM_CNF,
    SIM_SIG_READ_CBMIR_CNF,
    SIM_SIG_UPDATE_CBMIR_CNF,
    SIM_SIG_READ_DCK_CNF,
    SIM_SIG_READ_NIA_CNF,
    SIM_SIG_AOC_READ_ACM_CNF,
    SIM_SIG_AOC_INIT_ACM_CNF,
    SIM_SIG_AOC_INCREASE_ACM_CNF,
    SIM_SIG_AOC_READ_ACMMAX_CNF,
    SIM_SIG_AOC_UPDATE_ACMMAX_CNF,
    SIM_SIG_AOC_READ_PUCT_CNF,
    SIM_SIG_AOC_UPDATE_PUCT_CNF,
    SIM_SIG_QUERY_CARD_STATUS_CNF,
    SIM_SIG_GET_FILE_INFO_CNF,
    SIM_SIG_GET_ACCESS_INFO_CNF,
    SIM_SIG_SERIOUS_ERROR_IND
} SIM_LOG_SIGNAL_CODE_T;