#Preprocessor
#MCFLAG_OPT = --gnu
MCFLAG_OPT = -DSQLITE_SYSTEM_MALLOC
MCFLAG_OPT += -DSQLITE_THREADSAFE=1
MCFLAG_OPT += -DSQLITE_OS_OTHER=1
MCFLAG_OPT += -DSQLITE_MUTEX_APPDEF=1
MCFLAG_OPT += -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1
MCFLAG_OPT += -DSQLITE_DEFAULT_AUTOVACUUM=1
MCFLAG_OPT += -DSQLITE_TEMP_STORE=3
MCFLAG_OPT += -DSQLITE_ENABLE_FTS3
MCFLAG_OPT += -DSQLITE_ENABLE_FTS3_BACKWARDS
#MCFLAG_OPT += -DSQLITE_OMIT_WAL
#MCFLAG_OPT += -DSQLITE_OMIT_LOAD_EXTENSION=1

#Directory
#Local Dir inc
MINCPATH = external
MINCPATH += external/libc
MINCPATH += RTOS/export/inc
MINCPATH += MS_Ref/export/inc
MINCPATH += common/export/inc/trace_id
MINCPATH += $(MMI_DIR)/source/mmi_gui/include
MINCPATH += $(MMI_DIR)/source/mmi_ctrl/include

#Local Dir src
MSRCPATH = external/sqlite

SOURCES  = sqlite3.c