#ifndef _MMIDROPDOWN_POSITION_240X400_H_ /*perl robot add*/
#define _MMIDROPDOWN_POSITION_240X400_H_ /*perl robot add*/
//****************************************Shortcut***********************************//
#include "mmi_position.h"
#include "mmidropdownwin_export.h"
#include "mmi_signal_ext.h"

#define MMIDROPDOWN_SCROLLKEY_HEIGHT  24//32//20 //滑动栏的高度
#define MMIDROPDOWN_PAGEBUTTON_HEIGHT  31//50//20 //page button的高度
#define MMIDROPDOWN_PAGEBUTTON_SPLIT_WIDTH  4 //TAB分割线宽度
#define MMIDROPDOWN_SHORTCUT_HEIGHT  49//62//20 //page button的高度

//#define MMIDROPDOWN_SHORTCUT_WIDTH_V                   64
//#define MMIDROPDOWN_SHORTCUT_WIDTH_H                   96

//shortcut
#define MMIDROPDOWN_SHORTCUT_RECT_V            {0, MMI_STATUSBAR_HEIGHT, (MMI_MAINSCREEN_WIDTH-1), (MMI_STATUSBAR_HEIGHT+MMIDROPDOWN_SHORTCUT_HEIGHT-1)}
#define MMIDROPDOWN_SHORTCUT_RECT_H            {0, MMI_STATUSBAR_HEIGHT, (MMI_MAINSCREEN_HEIGHT-1), (MMI_STATUSBAR_HEIGHT+MMIDROPDOWN_SHORTCUT_HEIGHT-1)}
#define MMIDROPDOWN_SHORTCUT_ICON_Y_OFFSET     2//10
#define MMIDROPDOWN_SHORTCUT_BAR_Y_OFFSET      40//50
//#define MMIDROPDOWN_SHORTCUT_RECT_H            {0, MMIDROPDOWN_SHORTCUT_WIFI_TOP, MMIDROPDOWN_SHORTCUT_WIFI_RIGHT_H, MMIDROPDOWN_SHORTCUT_WIFI_BOTTOM}

#define MMIDROPDOWN_SHORTCUT_BOTTOM			(MMI_STATUSBAR_HEIGHT + MMIDROPDOWN_SHORTCUT_HEIGHT/*75*/)

/*

//WIFI
#define MMIDROPDOWN_SHORTCUT_WIFI_LEFT_V                   0
#define MMIDROPDOWN_SHORTCUT_WIFI_LEFT_H                   0
#define MMIDROPDOWN_SHORTCUT_WIFI_TOP                     MMI_STATUSBAR_HEIGHT
#define MMIDROPDOWN_SHORTCUT_WIFI_RIGHT_V			MMIDROPDOWN_SHORTCUT_WIDTH_V
#define MMIDROPDOWN_SHORTCUT_WIFI_RIGHT_H			MMIDROPDOWN_SHORTCUT_WIDTH_H
#define MMIDROPDOWN_SHORTCUT_WIFI_BOTTOM			(MMI_STATUSBAR_HEIGHT + 75)
#define MMIDROPDOWN_SHORTCUT_WIFI_RECT_V            {MMIDROPDOWN_SHORTCUT_WIFI_LEFT_V, MMIDROPDOWN_SHORTCUT_WIFI_TOP, MMIDROPDOWN_SHORTCUT_WIFI_RIGHT_V, MMIDROPDOWN_SHORTCUT_WIFI_BOTTOM}
#define MMIDROPDOWN_SHORTCUT_WIFI_RECT_H            {MMIDROPDOWN_SHORTCUT_WIFI_LEFT_H, MMIDROPDOWN_SHORTCUT_WIFI_TOP, MMIDROPDOWN_SHORTCUT_WIFI_RIGHT_H, MMIDROPDOWN_SHORTCUT_WIFI_BOTTOM}

//BT
#define MMIDROPDOWN_SHORTCUT_BT_LEFT_V                 MMIDROPDOWN_SHORTCUT_WIFI_RIGHT_V
#define MMIDROPDOWN_SHORTCUT_BT_LEFT_H                 MMIDROPDOWN_SHORTCUT_WIFI_RIGHT_H
#define MMIDROPDOWN_SHORTCUT_BT_TOP                  MMIDROPDOWN_SHORTCUT_WIFI_TOP
#define MMIDROPDOWN_SHORTCUT_BT_RIGHT_V			(MMIDROPDOWN_SHORTCUT_BT_LEFT_V+MMIDROPDOWN_SHORTCUT_WIDTH_V)
#define MMIDROPDOWN_SHORTCUT_BT_RIGHT_H			(MMIDROPDOWN_SHORTCUT_BT_LEFT_H+MMIDROPDOWN_SHORTCUT_WIDTH_H)
#define MMIDROPDOWN_SHORTCUT_BT_BOTTOM		MMIDROPDOWN_SHORTCUT_WIFI_BOTTOM
#define MMIDROPDOWN_SHORTCUT_BT_RECT_V            {MMIDROPDOWN_SHORTCUT_BT_LEFT_V, MMIDROPDOWN_SHORTCUT_BT_TOP, MMIDROPDOWN_SHORTCUT_BT_RIGHT_V, MMIDROPDOWN_SHORTCUT_BT_BOTTOM}
#define MMIDROPDOWN_SHORTCUT_BT_RECT_H            {MMIDROPDOWN_SHORTCUT_BT_LEFT_H, MMIDROPDOWN_SHORTCUT_BT_TOP, MMIDROPDOWN_SHORTCUT_BT_RIGHT_H, MMIDROPDOWN_SHORTCUT_BT_BOTTOM}

//FLYMODE
#define MMIDROPDOWN_SHORTCUT_FLYMODE_LEFT_V                 MMIDROPDOWN_SHORTCUT_BT_RIGHT_V
#define MMIDROPDOWN_SHORTCUT_FLYMODE_LEFT_H                 MMIDROPDOWN_SHORTCUT_BT_RIGHT_H
#define MMIDROPDOWN_SHORTCUT_FLYMODE_TOP                  MMIDROPDOWN_SHORTCUT_WIFI_TOP
#define MMIDROPDOWN_SHORTCUT_FLYMODE_RIGHT_V			(MMIDROPDOWN_SHORTCUT_FLYMODE_LEFT_V+MMIDROPDOWN_SHORTCUT_WIDTH_V)
#define MMIDROPDOWN_SHORTCUT_FLYMODE_RIGHT_H			(MMIDROPDOWN_SHORTCUT_FLYMODE_LEFT_H+MMIDROPDOWN_SHORTCUT_WIDTH_H)
#define MMIDROPDOWN_SHORTCUT_FLYMODE_BOTTOM		MMIDROPDOWN_SHORTCUT_WIFI_BOTTOM
#define MMIDROPDOWN_SHORTCUT_FLYMODE_RECT_V            {MMIDROPDOWN_SHORTCUT_FLYMODE_LEFT_V, MMIDROPDOWN_SHORTCUT_FLYMODE_TOP, MMIDROPDOWN_SHORTCUT_FLYMODE_RIGHT_V, MMIDROPDOWN_SHORTCUT_FLYMODE_BOTTOM}
#define MMIDROPDOWN_SHORTCUT_FLYMODE_RECT_H            {MMIDROPDOWN_SHORTCUT_FLYMODE_LEFT_H, MMIDROPDOWN_SHORTCUT_FLYMODE_TOP, MMIDROPDOWN_SHORTCUT_FLYMODE_RIGHT_H, MMIDROPDOWN_SHORTCUT_FLYMODE_BOTTOM}

//SILENT
#define MMIDROPDOWN_SHORTCUT_SILENT_LEFT_V                 MMIDROPDOWN_SHORTCUT_FLYMODE_RIGHT_V
#define MMIDROPDOWN_SHORTCUT_SILENT_LEFT_H                 MMIDROPDOWN_SHORTCUT_FLYMODE_RIGHT_H
#define MMIDROPDOWN_SHORTCUT_SILENT_TOP                  MMIDROPDOWN_SHORTCUT_WIFI_TOP
#define MMIDROPDOWN_SHORTCUT_SILENT_RIGHT_V			(MMIDROPDOWN_SHORTCUT_SILENT_LEFT_V+MMIDROPDOWN_SHORTCUT_WIDTH_V)
#define MMIDROPDOWN_SHORTCUT_SILENT_RIGHT_H			(MMIDROPDOWN_SHORTCUT_SILENT_LEFT_H+MMIDROPDOWN_SHORTCUT_WIDTH_H)
#define MMIDROPDOWN_SHORTCUT_SILENT_BOTTOM		MMIDROPDOWN_SHORTCUT_WIFI_BOTTOM
#define MMIDROPDOWN_SHORTCUT_SILENT_RECT_V            {MMIDROPDOWN_SHORTCUT_SILENT_LEFT_V, MMIDROPDOWN_SHORTCUT_SILENT_TOP, MMIDROPDOWN_SHORTCUT_SILENT_RIGHT_V, MMIDROPDOWN_SHORTCUT_SILENT_BOTTOM}
#define MMIDROPDOWN_SHORTCUT_SILENT_RECT_H            {MMIDROPDOWN_SHORTCUT_SILENT_LEFT_H, MMIDROPDOWN_SHORTCUT_SILENT_TOP, MMIDROPDOWN_SHORTCUT_SILENT_RIGHT_H, MMIDROPDOWN_SHORTCUT_SILENT_BOTTOM}

//BACKLIGHT
#define MMIDROPDOWN_SHORTCUT_BACKLIGHT_LEFT_V                 MMIDROPDOWN_SHORTCUT_SILENT_RIGHT_V
#define MMIDROPDOWN_SHORTCUT_BACKLIGHT_LEFT_H                 MMIDROPDOWN_SHORTCUT_SILENT_RIGHT_H
#define MMIDROPDOWN_SHORTCUT_BACKLIGHT_TOP                  MMIDROPDOWN_SHORTCUT_WIFI_TOP
#define MMIDROPDOWN_SHORTCUT_BACKLIGHT_RIGHT_V			(MMIDROPDOWN_SHORTCUT_BACKLIGHT_LEFT_V+MMIDROPDOWN_SHORTCUT_WIDTH_V)
#define MMIDROPDOWN_SHORTCUT_BACKLIGHT_RIGHT_H			(MMIDROPDOWN_SHORTCUT_BACKLIGHT_LEFT_H+MMIDROPDOWN_SHORTCUT_WIDTH_H)
#define MMIDROPDOWN_SHORTCUT_BACKLIGHT_BOTTOM		MMIDROPDOWN_SHORTCUT_WIFI_BOTTOM
#define MMIDROPDOWN_SHORTCUT_BACKLIGHT_RECT_V            {MMIDROPDOWN_SHORTCUT_BACKLIGHT_LEFT_V, MMIDROPDOWN_SHORTCUT_BACKLIGHT_TOP, MMIDROPDOWN_SHORTCUT_BACKLIGHT_RIGHT_V, MMIDROPDOWN_SHORTCUT_BACKLIGHT_BOTTOM}
#define MMIDROPDOWN_SHORTCUT_BACKLIGHT_RECT_H            {MMIDROPDOWN_SHORTCUT_BACKLIGHT_LEFT_H, MMIDROPDOWN_SHORTCUT_BACKLIGHT_TOP, MMIDROPDOWN_SHORTCUT_BACKLIGHT_RIGHT_H, MMIDROPDOWN_SHORTCUT_BACKLIGHT_BOTTOM}
*/

//NETWORK
#define MMIDROPDOWN_NETWORK_HEIGHT                 20
#define MMIDROPDOWN_NETWORK_TOP                  (MMIDROPDOWN_SHORTCUT_BOTTOM/*MMIDROPDOWN_SHORTCUT_WIFI_BOTTOM*/ + 5)
#define MMIDROPDOWN_NETWORK_BOTTOM		(MMIDROPDOWN_NETWORK_TOP + MMIDROPDOWN_NETWORK_HEIGHT)
//---v
#define MMIDROPDOWN_NETWORK_MARGIN_V                 10
#define MMIDROPDOWN_NETWORK_LEFT_V                 MMIDROPDOWN_NETWORK_MARGIN_V//10
#define MMIDROPDOWN_NETWORK_RIGHT_V			(MMI_MAINSCREEN_RIGHT_MAX_PIXEL-MMIDROPDOWN_NETWORK_MARGIN_V)//310
#define MMIDROPDOWN_NETWORK_RECT_V            {MMIDROPDOWN_NETWORK_LEFT_V, MMIDROPDOWN_NETWORK_TOP, MMIDROPDOWN_NETWORK_RIGHT_V, MMIDROPDOWN_NETWORK_BOTTOM}
//---h
#define MMIDROPDOWN_NETWORK_MARGIN_H                 15
#define MMIDROPDOWN_NETWORK_LEFT_H                 MMIDROPDOWN_NETWORK_MARGIN_H//15
#define MMIDROPDOWN_NETWORK_RIGHT_H			(MMI_MAINSCREEN_BOTTOM_MAX_PIXEL-MMIDROPDOWN_NETWORK_MARGIN_H)//465
#define MMIDROPDOWN_NETWORK_RECT_H            {MMIDROPDOWN_NETWORK_LEFT_H, MMIDROPDOWN_NETWORK_TOP, MMIDROPDOWN_NETWORK_RIGHT_H, MMIDROPDOWN_NETWORK_BOTTOM}

//notify title
#define MMIDROPDOWN_NOTIFY_TITLE_HEIGHT         25//20
#define MMIDROPDOWN_NOTIFY_TITLE_LEFT           0
//---v
#define MMIDROPDOWN_NOTIFY_TITLE_TOP_V            (MMIDROPDOWN_NETWORK_TOP + MMIDROPDOWN_NETWORK_HEIGHT*MMI_DUAL_SYS_MAX)
#define MMIDROPDOWN_NOTIFY_TITLE_BOTTOM_V         (MMIDROPDOWN_NOTIFY_TITLE_TOP_V + MMIDROPDOWN_NOTIFY_TITLE_HEIGHT - 1)
#define MMIDROPDOWN_NOTIFY_TITLE_RIGHT_V        MMI_MAINSCREEN_RIGHT_MAX_PIXEL//320
#define MMIDROPDOWN_NOTIFY_TITLE_RECT_V         {MMIDROPDOWN_NOTIFY_TITLE_LEFT, MMIDROPDOWN_NOTIFY_TITLE_TOP_V, MMIDROPDOWN_NOTIFY_TITLE_RIGHT_V, MMIDROPDOWN_NOTIFY_TITLE_BOTTOM_V}
//---h
#define MMIDROPDOWN_NOTIFY_TITLE_TOP_H            (MMIDROPDOWN_NETWORK_TOP + MMIDROPDOWN_NETWORK_HEIGHT*(MMI_DUAL_SYS_MAX+1)/2)
#define MMIDROPDOWN_NOTIFY_TITLE_BOTTOM_H         (MMIDROPDOWN_NOTIFY_TITLE_TOP_H + MMIDROPDOWN_NOTIFY_TITLE_HEIGHT - 1)
#define MMIDROPDOWN_NOTIFY_TITLE_RIGHT_H        MMI_MAINSCREEN_BOTTOM_MAX_PIXEL//480
#define MMIDROPDOWN_NOTIFY_TITLE_RECT_H         {MMIDROPDOWN_NOTIFY_TITLE_LEFT, MMIDROPDOWN_NOTIFY_TITLE_TOP_H, MMIDROPDOWN_NOTIFY_TITLE_RIGHT_H, MMIDROPDOWN_NOTIFY_TITLE_BOTTOM_H}


//LIST
#define MMIDROPDOWN_LIST_LEFT                 0
#define MMIDROPDOWN_LIST_RIGHT_V			MMI_MAINSCREEN_RIGHT_MAX_PIXEL//320
#define MMIDROPDOWN_LIST_RIGHT_H			MMI_MAINSCREEN_BOTTOM_MAX_PIXEL//480
#define MMIDROPDOWN_LIST_BOTTOM_V		(MMI_MAINSCREEN_BOTTOM_MAX_PIXEL/*480*/ - MMIDROPDOWN_SCROLLKEY_HEIGHT - MMIDROPDOWN_PAGEBUTTON_HEIGHT)
#define MMIDROPDOWN_LIST_BOTTOM_H		(MMI_MAINSCREEN_RIGHT_MAX_PIXEL/*320*/ - MMIDROPDOWN_SCROLLKEY_HEIGHT - MMIDROPDOWN_PAGEBUTTON_HEIGHT)

//notify list
#define MMIDROPDOWN_NOTIFY_LIST_TOP_V          (MMIDROPDOWN_NETWORK_TOP + MMIDROPDOWN_NETWORK_HEIGHT*MMI_DUAL_SYS_MAX + MMIDROPDOWN_NOTIFY_TITLE_HEIGHT)
#define MMIDROPDOWN_NOTIFY_LIST_TOP_H          (MMIDROPDOWN_NETWORK_TOP + MMIDROPDOWN_NETWORK_HEIGHT*(MMI_DUAL_SYS_MAX+1)/2 + MMIDROPDOWN_NOTIFY_TITLE_HEIGHT)
#define MMIDROPDOWN_NOTIFY_LIST_RECT_V          {MMIDROPDOWN_LIST_LEFT, MMIDROPDOWN_NOTIFY_LIST_TOP_V, MMIDROPDOWN_LIST_RIGHT_V, MMIDROPDOWN_LIST_BOTTOM_V}
#define MMIDROPDOWN_NOTIFY_LIST_RECT_H          {MMIDROPDOWN_LIST_LEFT, MMIDROPDOWN_NOTIFY_LIST_TOP_H, MMIDROPDOWN_LIST_RIGHT_H, MMIDROPDOWN_LIST_BOTTOM_H}
//runnning list
#ifdef MMI_PDA_SUPPORT
#define MMIDROPDOWN_RUNNING_LIST_TOP         MMI_STATUSBAR_HEIGHT +8
#else
#define MMIDROPDOWN_RUNNING_LIST_TOP         MMI_STATUSBAR_HEIGHT
#endif
#define MMIDROPDOWN_RUNNING_LIST_RECT_V        {MMIDROPDOWN_LIST_LEFT, MMIDROPDOWN_RUNNING_LIST_TOP, MMIDROPDOWN_LIST_RIGHT_V, MMIDROPDOWN_LIST_BOTTOM_V}
#define MMIDROPDOWN_RUNNING_LIST_RECT_H        {MMIDROPDOWN_LIST_LEFT, MMIDROPDOWN_RUNNING_LIST_TOP, MMIDROPDOWN_LIST_RIGHT_H, MMIDROPDOWN_LIST_BOTTOM_H}


#endif  /*perl robot add*/

