/*****************************************************************************
** File Name:      mmibrowser_id.h                                           *
** Author:          li.li                                                    *
** Date:           23/06/2009                                                *
** Copyright:      2007 Spreadtrum, Incorporated. All Rights Reserved.       *
** Description:    This file is used to describe the browser id              *
*****************************************************************************/
#ifndef MMIBROWSER_ID_H_
#define MMIBROWSER_ID_H_

/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
#include "mmibrowser_wintable.h"

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif

/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
/*                          TYPE AND CONSTANT                                */
/*---------------------------------------------------------------------------*/
typedef enum
{
    MMIBROWSER_CONTROL_ID=MMIBROWSER_WINDOW_ID_NUMBER,
    MMIBROWSER_LABEL_ADDRESS_CTRL_ID,
    MMIBROWSER_TOOLBAR_1_BUTTON_CTRL_ID,
    MMIBROWSER_TOOLBAR_2_BUTTON_CTRL_ID,
    MMIBROWSER_TOOLBAR_3_BUTTON_CTRL_ID,
    MMIBROWSER_TOOLBAR_4_BUTTON_CTRL_ID,
    MMIBROWSER_TOOLBAR_5_BUTTON_CTRL_ID,

    MMIBROWSER_MENU_CTRL_ID,
    MMIBROWSER_EDIT_ADDRESS_CTRL_ID,
    MMIBROWSER_HISTORY_LIST_CTRL_ID,
    MMIBROWSER_MENU_HISTORY_CTRL_ID,
    MMIBROWSER_RICHTEXT_HIS_DETAIL_CTRL_ID,
    MMIBROWSER_RICHTEXT_AUTH_CTRL_ID,
    MMIBROWSER_LIST_BOOKMARK_CTRL_ID,
    MMIBROWSER_BOOKMARK_CTRL_ID,
    MMIBROWSER_BOOKMARK_EDIT_CTRL_ID,//form control
    MMIBROWSER_BK_EDIT_FORM1_CTRL_ID,
    MMIBROWSER_BK_EDIT_FORM2_CTRL_ID,
    MMIBROWSER_BK_EDIT_FORM3_CTRL_ID,   //path
    MMIBROWSER_BK_EDIT_LABEL1_CTRL_ID,
    MMIBROWSER_BK_EDIT_LABEL2_CTRL_ID,
    MMIBROWSER_BK_EDIT_LABEL3_CTRL_ID,  //storage path
    MMIBROWSER_BK_EDIT_FORM3_SETLIST_CTRL_ID,  //storage path
    
    MMIBROWSER_SNAPSHOT_LIST_CTRL_ID,
    MMIBROWSER_SNAPSHOT_SAVE_FILE_CTRL_ID,
    MMIBROWSER_SNAPSHOT_SAVE_MEDIAFILE_CTRL_ID,
    MMIBROWSER_FILE_DETAIL_CTRL_ID,
    MMIBROWSER_SNAPSHOT_CTRL_ID,
    MMIBROWSER_COM_SELECT_SIM_CTRL_ID,
    MMIBROWSER_ANIMATE_CONNECTING_CTRL_ID,
    BRW_SELECT_CTRL_ID,
    BRW_EDITBOX_CTRL_ID,
    MMIBROWSER_EDIT_USERNAME_CTRL_ID,
    MMIBROWSER_EDIT_PWD_CTRL_ID,
    MMIBROWSER_SNAPSHOT_EDIT_FILENAME_CTRL_ID,
    MMIBROWSER_SNAPSHOT_DETAIL_CTRL_ID,
    MMIBROWSER_BOOKMARK_EDIT_TITLE_CTRL_ID,
    MMIBROWSER_BOOKMARK_EDIT_URL_CTRL_ID,
    MMIBROWSER_BOOKMARK_EDIT_PATH_CTRL_ID,
    MMIBROWSER_BOOKMARK_DETAIL_CTRL_ID,
    MMIBROWSER_BOOKMARK_DETAIL_OPTION_CTRL_ID,
        
    MMIBROWSER_SAVE_MEDIAFILE_CTRL_ID,
    MMIBROWSER_SAVE_MEDIAFILE_FORM1_CTRL_ID,
    MMIBROWSER_SAVE_MEDIAFILE_LABEL1_CTRL_ID,
    MMIBROWSER_SAVE_MEDIAFILE_EDITBOX_CTRL_ID,
    MMIBROWSER_SAVE_MEDIAFILE_FORM2_CTRL_ID,
    MMIBROWSER_SAVE_MEDIAFILE_LABEL2_CTRL_ID,
    MMIBROWSER_SAVE_MEDIAFILE_PATH_LABEL_CTRL_ID,
    MMIBROWSER_SAVE_MEDIAFILE_PATH_DROPDOWNLIST_CTRL_ID,
    MMIBROWSER_INPUT_FILE_NAME_CTRL_ID,
    
    MMIBROWSER_DOWNLOAD_FORM_CTRL_ID,
    MMIBROWSER_DOWNLOAD_LABEL1_CTRL_ID,
    MMIBROWSER_DOWNLOAD_LABEL2_CTRL_ID,
    MMIBROWSER_DOWNLOAD_LABEL3_CTRL_ID,
    MMIBROWSER_DOWNLOAD_PROGRESS_CTRL_ID,
    
    MMIBROWSER_LAST_SENT_NAME_CTRL_ID,
    MMIBROWSER_LAST_SENT_COUNT_CTRL_ID,
    MMIBROWSER_LAST_RECV_NAME_CTRL_ID,
    MMIBROWSER_LAST_RECV_COUNT_CTRL_ID,
    MMIBROWSER_TOTAL_SENT_NAME_CTRL_ID,
    MMIBROWSER_TOTAL_SENT_COUNT_CTRL_ID,
    MMIBROWSER_TOTAL_RECV_NAME_CTRL_ID,
    MMIBROWSER_TOTAL_RECV_COUNT_CTRL_ID,
    MMIBROWSER_PRGBOX_CTRL_ID,

#ifdef MMI_GUI_STYLE_TYPICAL
    MMIBROWSER_SETTING_FORM_CTRL_ID,
    MMIBROWSER_SETTING_SIM1_FORM_CTRL_ID,
    MMIBROWSER_SETTING_SIM1_TITLE_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_SIM2_FORM_CTRL_ID,
    MMIBROWSER_SETTING_SIM2_TITLE_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_SIM3_FORM_CTRL_ID,
    MMIBROWSER_SETTING_SIM3_TITLE_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_SIM4_TITLE_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_SIM4_FORM_CTRL_ID,
    MMIBROWSER_SETTING_SIM1_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_SIM2_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_SIM3_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_SIM4_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_IMAGE_FORM_CTRL_ID,
    MMIBROWSER_SETTING_IMAGE_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_IMAGE_DROPDOWNLIST_CTRL_ID,
    MMIBROWSER_SETTING_COOKIE_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_COOKIE_DROPDOWNLIST_CTRL_ID,
    MMIBROWSER_SETTING_CACHE_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_CACHE_DROPDOWNLIST_CTRL_ID,
    //MMIBROWSER_SETTING_WARNING_LABEL_CTRL_ID,
    //MMIBROWSER_SETTING_WARNING_DROPDOWNLIST_CTRL_ID,
    MMIBROWSER_SETTING_GOOGLE_FORM_CTRL_ID,
    MMIBROWSER_SETTING_GOOGLE_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_GOOGLE_DROPDOWNLIST_CTRL_ID,
    MMIBROWSER_SETTING_FONT_FORM_CTRL_ID,
    MMIBROWSER_SETTING_FONT_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_FONT_DROPDOWNLIST_CTRL_ID,
    MMIBROWSER_SETTING_DEFAULT_FORM_CTRL_ID,
    MMIBROWSER_SETTING_DEFAULT_LABEL_CTRL_ID,
    //MMIBROWSER_SETTING_PRGBOX_CTRL_ID,
    MMIBROWSER_SETTING_CLEAR_FORM_CTRL_ID,
    MMIBROWSER_SETTING_CLEAR_LABEL_CTRL_ID,

    MMIBROWSER_SETTING_HOME_TYPE_FORM_CTRL_ID,
    MMIBROWSER_SETTING_HOME_TYPE_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_HOME_TYPE_DROPDOWNLIST_CTRL_ID,
    MMIBROWSER_SETTING_HOME_FORM_CTRL_ID,
    MMIBROWSER_SETTING_HOME_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_HOME_CONTENT_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_HOME_EDIT_CTRL_ID,
#else
    MMIBROWSER_SETTING_LIST_CTRL_ID,
    MMIBROWSER_SETTING_HOMEPAGE_TYRE_MENU_CTRL_ID,
    MMIBROWSER_SETTING_FONT_MENU_CTRL_ID,
    MMIBROWSER_SETTING_EDIT_HOMEPAGE_CTRL_ID,
    MMIBROWSER_SETTING_CLEAR_OPT_CTRL_ID,
#endif    
    MMIBROWSER_BUTTON_FORM_CTRL_ID,

    MMIBROWSER_SNAPSHOT_SAVE_FILE_FORM_CTRL_ID,
    MMIBROWSER_SNAPSHOT_SAVE_F_FORM1_CTRL_ID,
    MMIBROWSER_SNAPSHOT_SAVE_F_FORM2_CTRL_ID,
    MMIBROWSER_SNAPSHOT_SAVE_F_LABEL1_CTRL_ID,
    MMIBROWSER_SNAPSHOT_SAVE_F_EDIT_CTRL_ID,
    MMIBROWSER_SNAPSHOT_SAVE_F_LABEL2_CTRL_ID,
    MMIBROWSER_SNAPSHOT_SAVE_F_DROPDOWN_CTRL_ID,

    //MMIBROWSER_MENU_CC_SELECT_CTRL_ID,
#ifdef OMADL_SUPPORT
    MMIBROWSER_OMADL_QUERY_RICHTEXT_CTRL_ID,
#endif

#ifdef BROWSER_SEARCH_SUPPORT
    MMIBROWSER_EDIT_SEARCH_CTRL_ID,
    MMIBROWSER_SEARCH_MAIN_FORM_CTRL_ID,
    MMIBROWSER_SEARCH_MAIN_FORM1_CTRL_ID,
    MMIBROWSER_SEARCH_MAIN_LIST_CTRL_ID,
    MMIBROWSER_SEARCH_MAIN_EDIT_CTRL_ID,
    MMIBROWSER_SEARCH_MAIN_BUTTON_CTRL_ID,
    MMIBROWSER_SEARCH_MAIN_LOG_CTRL_ID,
#endif /*BROWSER_SEARCH_SUPPORT*/

    MMIBROWSER_START_PAGE_FORM_CTRL_ID,
    MMIBROWSER_START_PAGE_FORM1_CTRL_ID,
    MMIBROWSER_START_PAGE_LIST_CTRL_ID,
    MMIBROWSER_START_PAGE_LABEL11_CTRL_ID,
    MMIBROWSER_START_PAGE_LABEL12_CTRL_ID,

#ifdef MMIDORADO_INPUT_HISTORY_SUPPORT
    MMIBROWSER_URL_INPUT_FORM_CTRL_ID,
    MMIBROWSER_URL_INPUT_CHILD_FORM_CTRL_ID,
    MMIBROWSER_URL_INPUT_LINK_CHILD_CTRL_ID,
    MMIBROWSER_URL_INPUT_LIST_CHILD_CTRL_ID,
#endif
    MMIBROWSER_URL_INPUT_CHILD_CTRL_ID,

#ifdef MMI_PDA_SUPPORT
    MMIBROWSER_SETTING_ACCOUNT_MENU_CTRL_ID,

    MMIBROWSER_BOOKMARK_POPUP_MENU_CTRL_ID,
    MMIBROWSER_HISTORY_POPUP_MENU_CTRL_ID,
    MMIBROWSER_PAGEMEMO_POPUP_MENU_CTRL_ID,
    MMIBROWSER_SNAPSHOT_SAVE_FILE_SETLIST_CTRL_ID,
    MMIBROWSER_BOOKMARK_FORM_CTRL_ID,
    MMIBROWSER_BOOKMARK_SOFTKEY_CTRL_ID,
    MMIBROWSER_PAGEMEMO_FORM_CTRL_ID,
    
    MMIBROWSER_START_PAGE_FORM2_CTRL_ID,
    MMIBROWSER_START_PAGE_FORM21_CTRL_ID,
    MMIBROWSER_START_PAGE_FORM22_CTRL_ID,
    MMIBROWSER_START_PAGE_FORM23_CTRL_ID,
    MMIBROWSER_START_PAGE_FORM24_CTRL_ID,
    MMIBROWSER_START_PAGE_BUTTON1_CTRL_ID,
    MMIBROWSER_START_PAGE_BUTTON2_CTRL_ID,
    MMIBROWSER_START_PAGE_BUTTON3_CTRL_ID,
    MMIBROWSER_START_PAGE_BUTTON4_CTRL_ID,
    MMIBROWSER_START_PAGE_LABEL1_CTRL_ID,
    MMIBROWSER_START_PAGE_LABEL2_CTRL_ID,
    MMIBROWSER_START_PAGE_LABEL3_CTRL_ID,
    MMIBROWSER_START_PAGE_LABEL4_CTRL_ID,
    
#endif /* MMI_PDA_SUPPORT */
    MMIBROWSER_START_PAGE_BUTTON5_CTRL_ID,

    MMIBROWSER_BK_AND_HISTORY_TAB_CTRL_ID,
    MMIBROWSER_START_PAGE_ICONLIST1_CTRL_ID,
    //MMIBROWSER_START_PAGE_ICONLIST2_CTRL_ID,

    MMIBROWSER_PROMPT_FORM_CTRL_ID,
    MMIBROWSER_PROMPT_LABEL_CTRL_ID,
    MMIBROWSER_PROMPT_EDIT_CTRL_ID,
    
#ifdef MMIDORADO_MY_NAV_SUPPORT
    MMIBROWSER_MY_NAV_EDIT_CTRL_ID,//form control
    MMIBROWSER_MY_NAV_EDIT_FORM1_CTRL_ID,
    MMIBROWSER_MY_NAV_EDIT_FORM2_CTRL_ID,
    MMIBROWSER_MY_NAV_EDIT_LABEL1_CTRL_ID,
    MMIBROWSER_MY_NAV_EDIT_LABEL2_CTRL_ID,
    MMIBROWSER_MY_NAV_EDIT_TITLE_CTRL_ID,
    MMIBROWSER_MY_NAV_EDIT_URL_CTRL_ID,
    MMIBROWSER_MY_NAV_POPUP_MENU_CTRL_ID,
    MMIBROWSER_MY_NAV_DETAIL_CTRL_ID,
#endif

#ifdef MMIDORADO_BGSOUND_SUPPORT
    MMIBROWSER_SETTING_BGSOUND_FORM_CTRL_ID,
    MMIBROWSER_SETTING_BGSOUND_LABEL_CTRL_ID,
    MMIBROWSER_SETTING_BGSOUND_DROPDOWNLIST_CTRL_ID,
#endif

#ifdef DYNAMIC_MAINMENU_SUPPORT
    MMIBROWSER_ADD2MAIN_EDIT_CTRL_ID,//form control
    MMIBROWSER_ADD2MAIN_EDIT_FORM1_CTRL_ID,
    MMIBROWSER_ADD2MAIN_EDIT_FORM2_CTRL_ID,
    MMIBROWSER_ADD2MAIN_EDIT_LABEL1_CTRL_ID,
    MMIBROWSER_ADD2MAIN_EDIT_LABEL2_CTRL_ID,
    MMIBROWSER_ADD2MAIN_EDIT_TITLE_CTRL_ID,
    MMIBROWSER_ADD2MAIN_EDIT_URL_CTRL_ID,
#endif

#ifdef MMIDORADO_FIX_HMTL_SUPPORT
    MMIBROWSER_FIX_HTML_LABEL_CTRL_ID,
#endif
    
    MMIBROWSER_SAVE_IMAGE_LIST_CTRL_ID,
    MMIBROWSER_SAVE_IMAGE_MENU_CTRL_ID,
    MMIBROWSER_SAVE_IMAGE_DETAIL_CTRL_ID,
    MMIBROWSER_SAVE_IMAGE_PREVIEW_ANIM_CTRL_ID,
    MMIBROWSER_SAVE_IMAGE_OPTION_BUTTON_CTRL_ID,
    MMIBROWSER_SAVE_IMAGE_RETURN_BUTTON_CTRL_ID,
    

#ifdef MMI_SSL_CERT_SUPPORT
	MMIBRW_LISTBOX_CERTIFICATE_CTRL_ID,
    MMIBRW_RICHTEXT_CERTIFICATE_ATTRIBUTE_CTRL_ID,
#endif

    MMIBROWSER_CONTROL_ID_NUMBER
}MMIBROWSER_CONTROL_ID_E;

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif

#endif
