/*****************************************************************************
** File Name:      mmifmm_menutable.c                                        *
** Author:                                                                   *
** Date:           06/04/2007                                                *
** Copyright:      2004 Spreadtrum, Incorporated. All Rights Reserved.       *
** Description:    This file is used to describe file manager module         *
*****************************************************************************
**                         Important Edit History                            *
** --------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                               *
** 04/2007        robert.lu          Create                                  *
******************************************************************************/

#define _MMIFMM_MENUTABLE_C_

/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
 #ifdef WIN32
#include "std_header.h"
#endif
#include "window_parse.h"
#include "guimenu.h"
#include "mmifmm_menutable.h"
#include "mmi_common.h"
#include "mmi_nv.h"
#include "mmifmm_text.h"
#include "mmi_text.h"
#include "mmimultim_text.h"
#ifdef DRM_SUPPORT
#include "mmidrm_text.h"
#endif
#ifdef MMI_VCALENDAR_SUPPORT
#include "Mmialarm_text.h"
#endif
#ifdef MMI_PDA_SUPPORT
#include "mmipb_image.h"
#include "mmifmm_image.h"
#endif
#ifdef MMIPB_ADD_EXIST_CONTACT_SUPPORT
#include "mmipb_text.h"
#endif
#include "mmifmm_export.h"
#ifdef MMI_AUDIO_PLAYER_SUPPORT
#include "mmimp3_text.h"
#endif
#ifdef MMI_AUDIO_PLAYER_SUPPORT
#include "mmiacc_event.h" //pclint
#include "mmialarm_text.h"
#endif
/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/
#define TIP_NULL    0

/**--------------------------------------------------------------------------*
 **                         LOCAL DEFINITION                                 *
 **--------------------------------------------------------------------------*/
//normal 
const GUIMENU_ITEM_T menu_fmm_normal_list_opt[] =
{
#ifdef MMI_PDA_SUPPORT 
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
#else
        {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     0, 0, 0, NULL},
#endif
#ifndef MMI_PDA_SUPPORT    
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE,             0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_DETAIL,            0, 0, 0, NULL},
#ifndef MMI_GUI_STYLE_MINISCREEN 
    {ID_FMM_EDIT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_EDIT,               0, 0, 0, MENU_FMM_LIST_EDIT_OPT},
#else
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#endif
#endif 
#ifdef MMI_PDA_SUPPORT    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         IMAGE_COMMON_OPTMENU_SEARCH, IMAGE_COMMON_OPTMENU_SEARCH, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           IMAGE_COMMON_OPTMENU_SORT, IMAGE_COMMON_OPTMENU_SORT, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           IMG_PB_MENU_MARK_ICON , IMG_PB_MENU_MARK_ICON , 0, NULL},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else
//fixed by liyan.zhu for bugzilla 2760 2012-05-22 fmm search support
#ifdef MMI_FMM_SEARCH_SUPPORT
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         0, 0, 0, NULL},
#endif
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, MENU_FMM_MARK_OPT},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif
};

const GUIMENU_ITEM_T menu_fmm_normal_file_list_opt[] =
{
#ifdef MMI_PDA_SUPPORT 
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
#else
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     0, 0, 0, NULL},
#endif
#ifndef MMI_PDA_SUPPORT 
#if defined (MMS_SUPPORT) && defined (BLUETOOTH_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           0, 0, 0, MENU_FMM_SEND_OPT},
#elif defined (MMS_SUPPORT)
    {ID_FMM_MMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MMS,           0, 0, 0, NULL},
#elif defined (BLUETOOTH_SUPPORT)
    {ID_FMM_BLUETOOTH,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_BLUETOOTH,           0, 0, 0, NULL},
#endif
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE,             0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_DETAIL,            0, 0, 0, NULL},
#ifndef MMI_GUI_STYLE_MINISCREEN 
    {ID_FMM_EDIT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_EDIT,               0, 0, 0, MENU_FMM_LIST_EDIT_OPT},
#else
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#endif
#endif
#ifdef MMI_PDA_SUPPORT    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         IMAGE_COMMON_OPTMENU_SEARCH, IMAGE_COMMON_OPTMENU_SEARCH, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           IMAGE_COMMON_OPTMENU_SORT, IMAGE_COMMON_OPTMENU_SORT, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           IMG_PB_MENU_MARK_ICON , IMG_PB_MENU_MARK_ICON , 0, NULL},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else
//fixed by liyan.zhu for bugzilla 2760 2012-05-22 fmm search support
#ifdef MMI_FMM_SEARCH_SUPPORT
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         0, 0, 0, NULL},
#endif
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, MENU_FMM_MARK_OPT},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif

};
#ifndef MMI_GUI_STYLE_MINISCREEN
const GUIMENU_ITEM_T menu_fmm_list_edit_opt[] =
{
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#ifdef MMI_FMM_MOVE_SUPPORT
    {ID_FMM_MOVE,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_CUT,           0, 0, 0, NULL}
#endif
};
#endif
const GUIMENU_ITEM_T menu_fmm_mark_opt[] =
{
    {ID_FMM_SUB_MARK,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, NULL},
    {ID_FMM_CANCEL_MARK,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_CANCEL_MARK,    0, 0, 0, NULL},
    {ID_FMM_MARK_ALL,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MARK_ALL,       0, 0, 0, NULL},
    {ID_FMM_CANCEL_ALL_MARK,TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_CANCEL_MARK_ALL,0, 0, 0, NULL}
};


//picture 
const GUIMENU_ITEM_T menu_fmm_picture_list_opt[] =
{
#ifdef MMI_PDA_SUPPORT 
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
#else
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     0, 0, 0, NULL},
#endif
#ifndef MMI_PDA_SUPPORT 
    {ID_FMM_PREVIEW,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_PREVIEW,           0, 0, 0, NULL},
#if defined (MMS_SUPPORT) && defined (BLUETOOTH_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           0, 0, 0, MENU_FMM_SEND_OPT},
#elif defined (MMS_SUPPORT)
    {ID_FMM_MMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MMS,           0, 0, 0, NULL},
#elif defined (BLUETOOTH_SUPPORT)
    {ID_FMM_BLUETOOTH,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_BLUETOOTH,           0, 0, 0, NULL},
#endif
#if ((!defined FLASH_SUPPORT)||(defined MMIPB_ADD_EXIST_CONTACT_SUPPORT)||(defined SCREENSAVER_SUPPORT)||(!defined MMI_DISPLAYSET_MINI_SUPPORT))
    {ID_FMM_PIC_MANAGER,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SETTING_AS,           0, 0, 0, MENU_FMM_PIC_MANAGE_OPT},
#endif
	//fixed by liyan.zhu for CR NEWMS00207041
	//{ID_FMM_WALLPAPER,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_SETAS_WALLPAPER,   0, 0, 0, NULL},
	//fixed by liyan.zhu for CR NEWMS00217352
//#ifndef MMI_DISPLAYSET_MINI_SUPPORT
//	{ID_FMM_POWER_ON_SET,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_ON_ANIMATION,   0, 0, 0, NULL},
 //   {ID_FMM_POWER_OFF_SET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_OFF_ANIMATION,  0, 0, 0, NULL},
//#endif
	{ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE,            0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_DETAIL,            0, 0, 0, NULL},
#ifndef MMI_GUI_STYLE_MINISCREEN 
    {ID_FMM_EDIT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_EDIT,               0, 0, 0, MENU_FMM_LIST_EDIT_OPT},
#else
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#endif
#endif
#ifdef MMI_PDA_SUPPORT    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         IMAGE_COMMON_OPTMENU_SEARCH, IMAGE_COMMON_OPTMENU_SEARCH, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           IMAGE_COMMON_OPTMENU_SORT, IMAGE_COMMON_OPTMENU_SORT, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           IMG_PB_MENU_MARK_ICON , IMG_PB_MENU_MARK_ICON , 0, NULL},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else
//fixed by liyan.zhu for bugzilla 2760 2012-05-22 fmm search support
#ifdef MMI_FMM_SEARCH_SUPPORT
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         0, 0, 0, NULL},
#endif
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, MENU_FMM_MARK_OPT},
    //fixed by liyan.zhu for bugzilla 2760 memory opt
#if 0
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif
#endif
};

//music 
#if 1
const GUIMENU_ITEM_T menu_fmm_music_list_opt[] =
{
#ifdef MMI_PDA_SUPPORT 
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
#else
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     0, 0, 0, NULL},
#endif
#ifndef MMI_PDA_SUPPORT 
#ifdef MMI_AUDIO_PLAYER_SUPPORT
    {ID_FMM_MUSIC_MANAGER,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MP3_SET_RING,           0, 0, 0, MENU_FMM_MUSIC_MANAGE_OPT},
#endif
    
#if defined (MMS_SUPPORT) && defined (BLUETOOTH_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           0, 0, 0, MENU_FMM_SEND_OPT},
#elif defined (MMS_SUPPORT)
    {ID_FMM_MMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MMS,           0, 0, 0, NULL},
#elif defined (BLUETOOTH_SUPPORT)
    {ID_FMM_BLUETOOTH,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_BLUETOOTH,           0, 0, 0, NULL},
#endif
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE,             0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_DETAIL,            0, 0, 0, NULL},
#ifndef MMI_GUI_STYLE_MINISCREEN 
    {ID_FMM_EDIT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_EDIT,               0, 0, 0, MENU_FMM_LIST_EDIT_OPT},
#else
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#endif
#endif
#ifdef MMI_PDA_SUPPORT    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         IMAGE_COMMON_OPTMENU_SEARCH, IMAGE_COMMON_OPTMENU_SEARCH, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           IMAGE_COMMON_OPTMENU_SORT, IMAGE_COMMON_OPTMENU_SORT, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           IMG_PB_MENU_MARK_ICON , IMG_PB_MENU_MARK_ICON , 0, NULL},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else
//fixed by liyan.zhu for bugzilla 2760 2012-05-22 fmm search support
#ifdef MMI_FMM_SEARCH_SUPPORT
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         0, 0, 0, NULL},
#endif
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, MENU_FMM_MARK_OPT}, 
    //fixed by liyan.zhu for bugzilla 2760 memory opt
#if 0
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif
#endif
};
#else
const GUIMENU_ITEM_T menu_fmm_music_list_opt[] =
{
#ifdef MMI_PDA_SUPPORT 
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
#else
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     0, 0, 0, NULL},
#endif    
#ifndef MMI_PDA_SUPPORT 
    {ID_FMM_RING,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SET_CALL_RING,           0, 0, 0, NULL},
#if defined (MMS_SUPPORT) && defined (BLUETOOTH_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           0, 0, 0, MENU_FMM_SEND_OPT},
#elif defined (MMS_SUPPORT)
    {ID_FMM_MMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MMS,           0, 0, 0, NULL},
#elif defined (BLUETOOTH_SUPPORT)
    {ID_FMM_BLUETOOTH,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_BLUETOOTH,           0, 0, 0, NULL},
#endif
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE,             0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_DETAIL,            0, 0, 0, NULL},
#ifndef MMI_GUI_STYLE_MINISCREEN 
    {ID_FMM_EDIT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_EDIT,               0, 0, 0, MENU_FMM_LIST_EDIT_OPT},
#else
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#endif
#endif
#ifdef MMI_PDA_SUPPORT    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         IMAGE_COMMON_OPTMENU_SEARCH, IMAGE_COMMON_OPTMENU_SEARCH, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           IMAGE_COMMON_OPTMENU_SORT, IMAGE_COMMON_OPTMENU_SORT, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           IMG_PB_MENU_MARK_ICON , IMG_PB_MENU_MARK_ICON , 0, NULL},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else
//fixed by liyan.zhu for bugzilla 2760 2012-05-22 fmm search support
#ifdef MMI_FMM_SEARCH_SUPPORT
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         0, 0, 0, NULL},
#endif
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, MENU_FMM_MARK_OPT}, 
    //fixed by liyan.zhu for bugzilla 2760 memory opt
#if 0
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif
#endif
};
#endif

//movie 
const GUIMENU_ITEM_T menu_fmm_movie_list_opt[] =
{
#ifdef MMI_PDA_SUPPORT 
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
#else
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     0, 0, 0, NULL},
#endif
#ifndef MMI_PDA_SUPPORT
	//将图片、视频的set as等统一
#if ((defined SCREENSAVER_SUPPORT)||(!defined MMI_DISPLAYSET_MINI_SUPPORT)||(defined MMI_VIDEOWALLPAPER_SUPPORT))
    {ID_FMM_MANAGER,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SETTING_AS,           0, 0, 0, MENU_FMM_MANAGE_OPT},
#endif
#if defined (MMS_SUPPORT) && defined (BLUETOOTH_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           0, 0, 0, MENU_FMM_SEND_OPT},
#elif defined (MMS_SUPPORT)
    {ID_FMM_MMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MMS,           0, 0, 0, NULL},
#elif defined (BLUETOOTH_SUPPORT)
    {ID_FMM_BLUETOOTH,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_BLUETOOTH,           0, 0, 0, NULL},
#endif
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE,             0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_DETAIL,            0, 0, 0, NULL},
#ifndef MMI_GUI_STYLE_MINISCREEN 
    {ID_FMM_EDIT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_EDIT,               0, 0, 0, MENU_FMM_LIST_EDIT_OPT},
#else
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#endif
#endif
#ifdef MMI_PDA_SUPPORT    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         IMAGE_COMMON_OPTMENU_SEARCH, IMAGE_COMMON_OPTMENU_SEARCH, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           IMAGE_COMMON_OPTMENU_SORT, IMAGE_COMMON_OPTMENU_SORT, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           IMG_PB_MENU_MARK_ICON , IMG_PB_MENU_MARK_ICON , 0, NULL},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else
//fixed by liyan.zhu for bugzilla 2760 2012-05-22 fmm search support
#ifdef MMI_FMM_SEARCH_SUPPORT
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         0, 0, 0, NULL},
#endif
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, MENU_FMM_MARK_OPT},
    //fixed by liyan.zhu for bugzilla 2760 memory opt
#if 0
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif
#endif
};

//manage option 
#if ((defined SCREENSAVER_SUPPORT)||(!defined MMI_DISPLAYSET_MINI_SUPPORT)||(defined MMI_VIDEOWALLPAPER_SUPPORT))
const GUIMENU_ITEM_T menu_fmm_manage_opt[] =
{
#ifdef SCREENSAVER_SUPPORT
    {ID_FMM_SCEENSAVE,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},    TXT_COMMON_SCREENSAVE,0, 0, 0, NULL},
#endif
#ifndef MMI_DISPLAYSET_MINI_SUPPORT
    {ID_FMM_POWER_ON_SET,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_ON_ANIMATION,   0, 0, 0, NULL},
	{ID_FMM_POWER_OFF_SET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_OFF_ANIMATION,  0, 0, 0, NULL},
#endif
#ifdef MMI_VIDEOWALLPAPER_SUPPORT
    {ID_FMM_VIDEO_WALLPAPER,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_VIDEO_WALLPAPER,0, 0, 0, NULL},
#endif
};
#endif
#if ((!defined FLASH_SUPPORT)||(defined MMIPB_ADD_EXIST_CONTACT_SUPPORT)||(defined SCREENSAVER_SUPPORT)||(!defined MMI_DISPLAYSET_MINI_SUPPORT))
const GUIMENU_ITEM_T menu_fmm_pic_manage_opt[] =
{
#ifndef FLASH_SUPPORT
    {ID_FMM_WALLPAPER,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SET_WALLPAPER_LIST_PREFIX,   0, 0, 0, NULL},
#endif
#ifdef MMIPB_ADD_EXIST_CONTACT_SUPPORT
    {ID_FMM_PB,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_PB_CONTACT_PHOTO,   0, 0, 0, NULL},    
#endif
#ifdef SCREENSAVER_SUPPORT
    {ID_FMM_SCEENSAVE,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},    TXT_COMMON_SCREENSAVE,0, 0, 0, NULL},
#endif
#ifndef MMI_DISPLAYSET_MINI_SUPPORT
    {ID_FMM_POWER_ON_SET,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_ON_ANIMATION,   0, 0, 0, NULL},
    {ID_FMM_POWER_OFF_SET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_OFF_ANIMATION,  0, 0, 0, NULL},
#endif
};
#endif
#ifdef MMI_AUDIO_PLAYER_SUPPORT
const GUIMENU_ITEM_T menu_fmm_music_manage_opt[] =
{
#ifndef MMI_MULTI_SIM_SYS_SINGLE
	//多卡相对于单卡，设置call ring 的对象不一样!!!
    {ID_FMM_RING,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SET_CALL_RING,           0, 0, 0, MENU_FMM_SIM_SELECT_OPT},
#else
		// 相对于单卡，仅此一项差别
    {ID_FMM_RING,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SET_CALL_RING,           0, 0, 0, NULL},
#endif
	{ID_FMM_SET_ALARM_RING,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MP3_SET_ALARM_RING,           0, 0, 0, MENU_FMM_ALARM_SELECT_OPT},
};
#endif
//sort option 
const GUIMENU_ITEM_T menu_fmm_sort_opt[] =
{
    {ID_FMM_NAME,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_NAME,0, 0, 0, NULL},
    {ID_FMM_DATE,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_TIME,0, 0, 0, NULL},
    {ID_FMM_SIZE,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_SIZE,0, 0, 0, NULL},
    {ID_FMM_TYPE,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_TYPE,0, 0, 0, NULL}
};

//picture preview option 
const GUIMENU_ITEM_T menu_fmm_picture_preview_opt[] =
{
#ifdef MMI_PDA_SUPPORT
#if defined (MMS_SUPPORT) && defined (BLUETOOTH_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           IMAGE_COMMON_OPTMENU_SEND, IMAGE_COMMON_OPTMENU_SEND, 0, MENU_FMM_SEND_OPT},
#elif defined (MMS_SUPPORT)
    {ID_FMM_MMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MMS,           IMAGE_COMMON_OPTMENU_SEND, IMAGE_COMMON_OPTMENU_SEND, 0, NULL},
#elif defined (BLUETOOTH_SUPPORT)
    {ID_FMM_BLUETOOTH,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_BLUETOOTH,           IMAGE_COMMON_OPTMENU_SEND, IMAGE_COMMON_OPTMENU_SEND, 0, NULL},
#endif
    {ID_FMM_WALLPAPER,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_SETAS_WALLPAPER,   IMAGE_COMMON_OPTMENU_SET_WALLPAPER, IMAGE_COMMON_OPTMENU_SET_WALLPAPER, 0, NULL},
#ifdef MMIPB_ADD_EXIST_CONTACT_SUPPORT
    {ID_FMM_PB,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_FMM_PHOTO_SET_PB,   0, 0, 0, NULL},    
#endif
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_RENAME,      IMAGE_COMMON_OPTMENU_RENAME, IMAGE_COMMON_OPTMENU_RENAME, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_DETAIL,         IMAGE_COMMON_OPTMENU_DETAIL, IMAGE_COMMON_OPTMENU_DETAIL, 0, NULL},
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DELETE,         IMAGE_COMMON_OPTMENU_DELETE, IMAGE_COMMON_OPTMENU_DELETE, 0, NULL},
    {ID_FMM_POWER_ON_SET,  TIP_NULL,  {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_ON_ANIMATION,   0, 0, 0, NULL},
    {ID_FMM_POWER_OFF_SET, TIP_NULL,  {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_OFF_ANIMATION,  0, 0, 0, NULL},

#else
#if defined (MMS_SUPPORT) && defined (BLUETOOTH_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           0, 0, 0, MENU_FMM_SEND_OPT},
#elif defined (MMS_SUPPORT)
    {ID_FMM_MMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MMS,           0, 0, 0, NULL},
#elif defined (BLUETOOTH_SUPPORT)
    {ID_FMM_BLUETOOTH,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_BLUETOOTH,           0, 0, 0, NULL},
#endif
#if ((!defined FLASH_SUPPORT)||(defined MMIPB_ADD_EXIST_CONTACT_SUPPORT)||(defined SCREENSAVER_SUPPORT)||(!defined MMI_DISPLAYSET_MINI_SUPPORT))
    {ID_FMM_PIC_MANAGER,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SETTING_AS,           0, 0, 0, MENU_FMM_PIC_MANAGE_OPT},
#endif
//#ifndef FLASH_SUPPORT
//    {ID_FMM_WALLPAPER,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_SETAS_WALLPAPER,   0, 0, 0, NULL},
//#endif
//#ifdef MMIPB_ADD_EXIST_CONTACT_SUPPORT
//    {ID_FMM_PB,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_FMM_PHOTO_SET_PB,   0, 0, 0, NULL},    
//#endif
	//fixed by liyan.zhu for CR NEWMS00217352
//#ifndef MMI_DISPLAYSET_MINI_SUPPORT
//    {ID_FMM_POWER_ON_SET,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_ON_ANIMATION,   0, 0, 0, NULL},
//    {ID_FMM_POWER_OFF_SET, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_POWER_OFF_ANIMATION,  0, 0, 0, NULL},
//#endif
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_RENAME,      0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_DETAIL,         0, 0, 0, NULL},
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DELETE,         0, 0, 0, NULL},
#endif
};

//send option
#if defined (MMS_SUPPORT) && defined (BLUETOOTH_SUPPORT)
const GUIMENU_ITEM_T menu_fmm_send_opt[] =
{	
#ifdef MMS_SUPPORT
    {ID_FMM_MMS,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_MMS,         0, 0, 0, NULL},
#endif
#ifdef BLUETOOTH_SUPPORT
    {ID_FMM_BLUETOOTH,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_BLUETOOTH,   0, 0, 0, NULL},
#endif
};
#endif
#if defined MMI_VCARD_SUPPORT
//send vcard option
const GUIMENU_ITEM_T menu_fmm_send_vcard_opt[] =
{
    {ID_FMM_SMS,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SMS,     0, 0, 0, NULL},
#ifdef MMS_SUPPORT
    {ID_FMM_MMS,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_MMS,         0, 0, 0, NULL},
#endif
#ifdef BLUETOOTH_SUPPORT
    {ID_FMM_BLUETOOTH,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_BLUETOOTH,   0, 0, 0, NULL},
#endif
};
#endif
#ifdef MMI_VCALENDAR_SUPPORT
//send vcalendar option
const GUIMENU_ITEM_T menu_fmm_send_vcalendar_opt[] =
{
    {ID_FMM_VCALENDAR_SMS,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_SMS,     0, 0, 0, NULL},
#ifdef MMS_SUPPORT
    {ID_FMM_MMS,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_MMS,         0, 0, 0, NULL},
#endif
#ifdef BLUETOOTH_SUPPORT
    {ID_FMM_BLUETOOTH,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_BLUETOOTH,   0, 0, 0, NULL},
#endif
//#ifdef PUSH_EMAIL_SUPPORT
//    {ID_FMM_EMAIL,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},   TXT_MAIL_ANSWER_MAIL,   0, 0, 0, MENU_NULL},
//#endif
};
#endif
// empty folder option
const GUIMENU_ITEM_T menu_fmm_empty_folder_opt[] =
{
#ifdef MMI_PDA_SUPPORT
    {ID_FMM_NEW_FOLDER, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_FMM_NEW_FOLDER,  IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
    //{ID_FMM_SORT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_SORT_MANNER,0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,           IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else
    {ID_FMM_NEW_FOLDER, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_FMM_NEW_FOLDER,  0, 0, 0, NULL},
    //{ID_FMM_SORT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_SORT_MANNER,0, 0, 0, MENU_FMM_SORT_OPT},
    //fixed by liyan.zhu for bugzilla 2760 memory opt
#if 0
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,           0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif
#endif
};

const GUIMENU_ITEM_T menu_fmm_other_list_opt[] =
{
#ifdef MMI_PDA_SUPPORT 
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
#else
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     0, 0, 0, NULL},
#endif
#ifndef MMI_PDA_SUPPORT 
#if defined (MMS_SUPPORT) && defined (BLUETOOTH_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           0, 0, 0, MENU_FMM_SEND_OPT},
#elif defined (MMS_SUPPORT)
    {ID_FMM_MMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_MMS,           0, 0, 0, NULL},
#elif defined (BLUETOOTH_SUPPORT)
    {ID_FMM_BLUETOOTH,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_BLUETOOTH,           0, 0, 0, NULL},
#endif
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE,             0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_DETAIL,            0, 0, 0, NULL},
#ifndef MMI_GUI_STYLE_MINISCREEN 
    {ID_FMM_EDIT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_EDIT,               0, 0, 0, MENU_FMM_LIST_EDIT_OPT},
#else
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#endif
#endif
#ifdef MMI_PDA_SUPPORT    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         IMAGE_COMMON_OPTMENU_SEARCH, IMAGE_COMMON_OPTMENU_SEARCH, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           IMAGE_COMMON_OPTMENU_SORT, IMAGE_COMMON_OPTMENU_SORT, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           IMG_PB_MENU_MARK_ICON , IMG_PB_MENU_MARK_ICON , 0, NULL},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else
//fixed by liyan.zhu for bugzilla 2760 2012-05-22 fmm search support
#ifdef MMI_FMM_SEARCH_SUPPORT
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         0, 0, 0, NULL},
#endif
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, MENU_FMM_MARK_OPT},
//fixed by liyan.zhu for bugzilla 2760 memory opt
#if 0 
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif
#endif
};
#if defined MMI_VCARD_SUPPORT
const GUIMENU_ITEM_T menu_fmm_vcard_list_opt[] =
{
#ifdef MMI_PDA_SUPPORT 
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
#else
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     0, 0, 0, NULL},
#endif
#ifndef MMI_PDA_SUPPORT 
#if defined (MMS_SUPPORT) || defined (BLUETOOTH_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           0, 0, 0, MENU_FMM_SEND_VCARD_OPT},
#else
    {ID_FMM_SMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SMS,           0, 0, 0, NULL},
#endif
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE,             0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_DETAIL,            0, 0, 0, NULL},
#ifndef MMI_GUI_STYLE_MINISCREEN 
    {ID_FMM_EDIT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_EDIT,               0, 0, 0, MENU_FMM_LIST_EDIT_OPT},
#else
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#endif
#endif
#ifdef MMI_PDA_SUPPORT    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         IMAGE_COMMON_OPTMENU_SEARCH, IMAGE_COMMON_OPTMENU_SEARCH, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           IMAGE_COMMON_OPTMENU_SORT, IMAGE_COMMON_OPTMENU_SORT, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           IMG_PB_MENU_MARK_ICON , IMG_PB_MENU_MARK_ICON , 0, NULL},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         0, 0, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, MENU_FMM_MARK_OPT},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif
};
#endif
#ifdef MMI_VCALENDAR_SUPPORT
const GUIMENU_ITEM_T menu_fmm_vcalendar_list_opt[] =
{
#ifdef MMI_PDA_SUPPORT 
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     IMG_FMM_NEW_FOLDER_MENU_ICON, IMG_FMM_NEW_FOLDER_MENU_ICON, 0, NULL},
#else
    {ID_FMM_NEW_FOLDER,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_FMM_NEW_FOLDER,     0, 0, 0, NULL},
#endif
#ifndef MMI_PDA_SUPPORT 
    {ID_FMM_SAVE_VCALENDAR,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SAVE_CALENDAR,             0, 0, 0, NULL},
#if defined (MMS_SUPPORT) || defined (BLUETOOTH_SUPPORT) //|| defined (PUSH_EMAIL_SUPPORT)
    {ID_FMM_SEND,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SEND,           0, 0, 0, MENU_FMM_SEND_VCALENDAR_OPT},
#else
    {ID_FMM_VCALENDAR_SMS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SMS,           0, 0, 0, NULL},
#endif
    {ID_FMM_DELETE,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DELETE,             0, 0, 0, NULL},
    {ID_FMM_DETAIL,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_DETAIL,            0, 0, 0, NULL},
#ifndef MMI_GUI_STYLE_MINISCREEN 
    {ID_FMM_EDIT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_EDIT,               0, 0, 0, MENU_FMM_LIST_EDIT_OPT},
#else
    {ID_FMM_RENAME,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_RENAME,         0, 0, 0, NULL},
    {ID_FMM_COPY,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#endif
#endif   
#ifdef MMI_PDA_SUPPORT    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         IMAGE_COMMON_OPTMENU_SEARCH, IMAGE_COMMON_OPTMENU_SEARCH, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           IMAGE_COMMON_OPTMENU_SORT, IMAGE_COMMON_OPTMENU_SORT, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           IMG_PB_MENU_MARK_ICON , IMG_PB_MENU_MARK_ICON , 0, NULL},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  IMAGE_COMMON_OPTMENU_CAPACITY, IMAGE_COMMON_OPTMENU_CAPACITY, 0, MENU_FMM_MEMORY_OPT},
#else    
    {ID_FMM_SEARCH,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMM_SEARCH,         0, 0, 0, NULL},
    {ID_FMM_SORT,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SORT,           0, 0, 0, MENU_FMM_SORT_OPT},
    {ID_FMM_MARK_OPT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_MARK,           0, 0, 0, MENU_FMM_MARK_OPT},
    {ID_FMM_MEMORY_OPT,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_DETAIL_MEMORY,  0, 0, 0, MENU_FMM_MEMORY_OPT},
#endif
};
#endif
#ifdef MMI_AUDIO_PLAYER_SUPPORT
const GUIMENU_ITEM_T menu_fmm_sim_select_opt[] =
{    
    {ID_FMM_SIM1_RING, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SIM_SEL_SIM1,  0, 0, 0, NULL},
    {ID_FMM_SIM2_RING, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SIM_SEL_SIM2,     0, 0, 0, NULL},
    #if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
    {ID_FMM_SIM3_RING, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SIM_SEL_SIM3,     0, 0, 0, NULL},
    #endif
    #if defined(MMI_MULTI_SIM_SYS_QUAD)
    {ID_FMM_SIM4_RING, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_SIM_SEL_SIM4,     0, 0, 0, NULL}
    #endif
};
const GUIMENU_ITEM_T menu_fmm_alarm_select_opt[] = 
{
	{ID_FMM_ALARM1_RING, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK1,     0, 0, 0, NULL},
	{ID_FMM_ALARM1_RING+1, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK2,     0, 0, 0, NULL},
	{ID_FMM_ALARM1_RING+2, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK3,     0, 0, 0, NULL},
#if (ALM_ALARM_NUM > 3)//ndef MMI_ALARM_MINI_LOW_COST
    {ID_FMM_ALARM1_RING+3, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK4,     0, 0, 0, NULL},
	{ID_FMM_ALARM1_RING+4, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK5,     0, 0, 0, NULL},
#if (ALM_ALARM_NUM > 5) //#ifndef ALARM_SUPPORT_LOW_MEMORY
    {ID_FMM_ALARM1_RING+5, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK6,     0, 0, 0, NULL},
	{ID_FMM_ALARM1_RING+6, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK7,     0, 0, 0, NULL},
	{ID_FMM_ALARM1_RING+7, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK8,     0, 0, 0, NULL},
	{ID_FMM_ALARM1_RING+8, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK9,     0, 0, 0, NULL},
	{ID_FMM_ALARM1_RING+9, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_ALARM_CLOCK10,     0, 0, 0, NULL},
#endif
#endif
};
#endif
const GUIMENU_ITEM_T   menu_fmm_select_movie_opt[] =
{
    {ID_FMM_MOVIE_OPT_PLAY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_PLAY, 0, 0, 0, NULL},
    {ID_FMM_MOVIE_OPT_SELECT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, STXT_SELECT, 0, 0, 0, NULL},
};

const GUIMENU_ITEM_T menu_fmm_memory_opt[] =
{
#if defined(NANDBOOT_SUPPORT) || defined(MMI_UDISK_MEM_ENABLE)
    {ID_FMM_UDISK_MEMORY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},   TXT_COMMON_UDISK_MEMORY,  0, 0, 0, NULL},
#endif
#ifndef DUAL_TCARD_SUPPORT
    {ID_FMM_UDISK_MEMORY + 1, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_SD_MEMORY, 0, 0, 0, NULL},
#else
    {ID_FMM_UDISK_MEMORY + 1, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_SD0_MEMORY, 0, 0, 0, NULL},
    {ID_FMM_UDISK_MEMORY + 2, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_SD1_MEMORY, 0, 0, 0, NULL},
#endif
#if defined(NANDBOOT_SUPPORT) || defined(MMI_UDISK_MEM_ENABLE)
   {ID_FMM_UDISK_FORMAT, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},   TXT_COMMON_UDISK_FORMAT,  0, 0, 0, NULL},
 #endif
 #ifndef DUAL_TCARD_SUPPORT
    {ID_FMM_UDISK_FORMAT + 1, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_SD_FORMAT, 0, 0, 0, NULL},
#else
    {ID_FMM_UDISK_FORMAT + 1, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_SD0_FORMAT, 0, 0, 0, NULL},
    {ID_FMM_UDISK_FORMAT + 2, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},  TXT_COMMON_SD1_FORMAT, 0, 0, 0, NULL},
#endif
#ifndef DUAL_TCARD_SUPPORT
    {ID_FMM_MEMCARD_RENAME,TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SD_RENAME, 0, 0, 0, NULL}
#else
    {ID_FMM_MEMCARD_RENAME,TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SD0_RENAME, 0, 0, 0, NULL},
    {ID_FMM_MEMCARD1_RENAME,TIP_NULL,{TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_SD1_RENAME, 0, 0, 0, NULL}
#endif
};

#ifdef DRM_SUPPORT
const GUIMENU_ITEM_T menu_fmm_drm_download_opt[] =
{
    {ID_FMM_DRM_DOWNLOAD, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DRM_DOWNLOAD_RIGHTS, 0, 0, 0, NULL},
//    {ID_FMM_DRM_DOWNLOAD_MORE, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_DRM_DOWNLOAD_MORE_RIGHTS, 0, 0, 0, NULL},
};
#endif

#ifdef MMI_PDA_SUPPORT
const GUIMENU_ITEM_T  menu_fmm_mark_list_opt[] = 
{
    {ID_FMM_COPY,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_COPY,           0, 0, 0, NULL},
#ifdef MMI_FMM_MOVE_SUPPORT
    {ID_FMM_MOVE,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN}, TXT_COMMON_CUT,           0, 0, 0, NULL}
#endif
};
#endif

/*---------------------------------------------------------------------------*/
/*                          TYPE AND CONSTANT                                */
/*---------------------------------------------------------------------------*/
#define MENU_DEF(_TABLEID, _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, \
    _ITEMCOUNT) \
    _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, _ITEMCOUNT, 

const GUIMENU_GROUP_T fmm_menu_table[] = 
{
    {NULL},
    #include "mmifmm_menutable.def"
};


#undef MENU_DEF
/**--------------------------------------------------------------------------*
 **                         EXTERNAL DECLARE                                 *
 **--------------------------------------------------------------------------*/

/**--------------------------------------------------------------------------*
 **                         GLOBAL DEFINITION                                *
 **--------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                          LOCAL FUNCTION DECLARE                           */
/*---------------------------------------------------------------------------*/

/**--------------------------------------------------------------------------*
 **                         FUNCTION DEFINITION                              *
 **--------------------------------------------------------------------------*/
/*****************************************************************************/
//  Description : register fmm menu group
//  Global resource dependence : none
//  Author: robert
//  Note:
/*****************************************************************************/
PUBLIC void MMIFMM_RegMenuGroup(void)
{
    MMI_RegMenuGroup(MMI_MODULE_FMM, fmm_menu_table);
}
