

//[[define image infomation
#ifdef  CAMERA_SUPPORT

#ifdef DC_WATCH_UI_SUPPORT
RES_ADD_IMG(IMG_DC_WATCH_OPEN_GALLERY ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_open_gallery.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_DC_WATCH_SWITCH_TO_DV,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_switch_to_video.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_DC_WATCH_SWITCH_TO_DC ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_switch_to_photo.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_DC_WATCH_CAPTURE_IMAGE ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_capture.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_DC_WATCH_START_RECORD ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_record.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_DC_WATCH_CANCEL ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_cancel.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_DC_WATCH_CONFIRM,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_confirm.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined(SCREEN_SHAPE_CIRCULAR) 
RES_ADD_IMG(IMG_DC_WATCH_CONFIRM_GRAY,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_confirm_gray.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMG_DC_WATCH_STOP_RECORD ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_stop_record.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_DC_WATCH_PAUSE_PLAY ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_pause.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_DC_WATCH_PLAY ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_play.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_DC_WATCH_RECORDING_INDICATOR ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_indicator_recording.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_DC_WATCH_WAIT ,"\\MMI_RES_##\\IMAG\\WATCH\\res_camera_ic_waiting.png",IMG_CMP_PNG_ARGB_RLE,0)

#endif

#if !defined(MMIDC_DESKTOP_PDA)

RES_ADD_IMG(IMG_DC_PHOTO_TIP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_PHOTO_TIP.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_VIDEO_TIP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_VIDEO_TIP.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_WAIT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_WAIT.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_RECORD,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_RECORD.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMG_DC_BMP_MASK,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_BMP_MASK.bmp",IMG_CMP_BMP_16_565_RLE,0)

#if defined MMIDC_MINI_DISPLAY_STYLE || defined MMIDC_MINI_3264_STYLE 
RES_ADD_IMG(IMG_DC_SOFTKEY_CAPTURE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SOFTKEY_CAPTURE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_SOFTKEY_PAUSE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SOFTKEY_PAUSE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_SOFTKEY_RECORD,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SOFTKEY_RECORD.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_SOFTKEY_SEND,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SOFTKEY_SEND.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_SOFTKEY_PLAY,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SOFTKEY_PLAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

#if !defined MMIDC_MINI_DISPLAY_STYLE || defined MMIDC_ADD_SPECIAL_EFFECT
RES_ADD_IMG(IMG_DC_MENU_DOWN,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_MENU_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_MENU_UP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_MENU_UP.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

#ifndef MMIDC_MINI_RESOURCE_SIZE
RES_ADD_IMG(IMG_DC_ADJUST_1,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ADJUST_1.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_ADJUST_2,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ADJUST_2.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_ADJUST_3,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ADJUST_3.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_ADJUST_4,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ADJUST_4.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_ADJUST_5,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ADJUST_5.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_ADJUST_6,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ADJUST_6.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_BIRGHTNESS_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_BIRGHTNESS_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_BRIGHTNESS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_BRIGHTNESS.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_BRIGHTNESS_ADJUST,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_BRIGHTNESS_ADJUST.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_CONTRAST,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_CONTRAST.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_CONTRAST_ADJUST,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_CONTRAST_ADJUST.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_CONTRAST_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_CONTRAST_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

#ifdef MMIDC_F_FLASH
RES_ADD_IMG(IMG_DC_FLASH,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_FLASH.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_FLASH_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_FLASH_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

//RES_ADD_IMG(IMG_DC_DECREASE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_DECREASE.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_EC_ADJUST,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_EC_ADJUST.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_EFFECT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_EFFECT.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_EFFECT_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_EFFECT_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_ENVIRONMENT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ENVIRONMENT.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_ENVIRONMENT_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ENVIRONMENT_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_EXPOSAL_COMPENSATE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_EXPOSAL_COMPENSATE.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_EXPOSAL_COMPENSATE_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_EXPOSAL_COMPENSATE_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMG_DC_FOCUS_BAR,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_FOCUS_BAR.bmp",IMG_CMP_BMP_16_565_RLE,0)

#ifdef CAMERA_FRAME_SUPPORT
RES_ADD_IMG(IMG_DC_FRAME,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_FRAME.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_FRAME_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_FRAME_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

//RES_ADD_IMG(IMG_DC_INCREASE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_INCREASE.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMG_DC_ISO,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ISO.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMG_DC_ISO_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ISO_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_LEFT_ARROW,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_LEFT_ARROW.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMG_DC_MENU_BACKGROUND,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_MENU_BACKGROUND.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_MULTISHOT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_MULTISHOT.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_MULTISHOT_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_MULTISHOT_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_MULTISHOT_TIP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_MULTISHOT_TIP.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMG_DC_PANORAMA,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_PANORAMA.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMG_DC_PANORAMA_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_PANORAMA_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

//需要增加全景拍照宏控制
RES_ADD_IMG(IMG_DC_PANORAMA_TIP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_PANORAMA_TIP.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMG_DC_PAUSE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_PAUSE.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_PHOTO_MODE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_PHOTO_MODE.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_PHOTO_MODE_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_PHOTO_MODE_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_RIGHT_ARROW,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_RIGHT_ARROW.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMG_DC_SELECT_ICON,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SELECT_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMG_DC_SELECTED_ICON,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SELECTED_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_SELF_DELAY,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SELF_DELAY.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_SELF_DELAY_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SELF_DELAY_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_SIZE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SIZE.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_SIZE_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_SIZE_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_WHITE_BALANCE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_WHITE_BALANCE.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_WHITE_BALANCE_FOCUS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_WHITE_BALANCE_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMG_DC_LEFT_SETTING_ARROW,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_LEFT_SETTING_ARROW.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMG_DC_RIGHT_SETTING_ARROW,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_RIGHT_SETTING_ARROW.bmp",IMG_CMP_BMP_16_565_RLE,0)


//RES_ADD_IMG(IMG_DC_WAIT_ROTATE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_WAIT_ROTATE.bmp",IMG_CMP_BMP_16_565_RLE,0)

#ifdef MMIDC_DESKTOP_ICON_BAR
//brightness
//#ifdef TOUCH_PANEL_SUPPORT 
RES_ADD_IMG(IMG_DC_ICON_BRIGHTNESS_BG,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_BRIGHTNESS_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#else
//RES_ADD_IMG(IMG_DC_ICON_NOTP_BRIGHTNESS_BG,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_NOTP_BRIGHTNESS_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#endif
//RES_ADD_IMG(IMG_DC_ICON_LEFT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_LEFT.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMG_DC_ICON_GRAY_LEFT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_GRAY_LEFT.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMG_DC_ICON_FOCUS_LEFT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_FOCUS_LEFT.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMG_DC_ICON_RIGHT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_RIGHT.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMG_DC_ICON_GRAY_RIGHT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_GRAY_RIGHT.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMG_DC_ICON_FOCUS_RIGHT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_FOCUS_RIGHT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_BRIGHT_UP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_BRIGHT_UP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_GRAY_BRIGHT_UP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_GRAY_BRIGHT_UP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_FOCUS_BRIGHT_UP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_FOCUS_BRIGHT_UP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_BRIGHT_DOWN,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_BRIGHT_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_GRAY_BRIGHT_DOWN,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_GRAY_BRIGHT_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_FOCUS_BRIGHT_DOWN,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_FOCUS_BRIGHT_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)


//zoom or contrast
//#ifdef TOUCH_PANEL_SUPPORT 
RES_ADD_IMG(IMG_DC_ICON_ZOOM_BG,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_ZOOM_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#else
//RES_ADD_IMG(IMG_DC_ICON_NOTP_ZOOM_BG,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_NOTP_ZOOM_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#endif
//#ifdef TOUCH_PANEL_SUPPORT 
RES_ADD_IMG(IMG_DC_ICON_CONTRAST_BG,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_CONTRAST_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#else
//RES_ADD_IMG(IMG_DC_ICON_NOTP_CONTRAST_BG,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_NOTP_CONTRAST_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#endif
RES_ADD_IMG(IMG_DC_ICON_UP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_UP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_GRAY_UP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_GRAY_UP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_FOCUS_UP,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_FOCUS_UP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_DOWN,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_GRAY_DOWN,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_GRAY_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_FOCUS_DOWN,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_FOCUS_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)

//photo, video
RES_ADD_IMG(IMG_DC_ICON_PHOTO,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_PHOTO.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_VIDEO,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_VIDEO.bmp",IMG_CMP_BMP_16_565_RLE,0)

//sensor
RES_ADD_IMG(IMG_DC_ICON_SENSOR_REAR,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_SENSOR_REAR.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_SENSOR_FRONT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_SENSOR_FRONT.bmp",IMG_CMP_BMP_16_565_RLE,0)


//size
RES_ADD_IMG(IMG_DC_ICON_SIZE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_SIZE.bmp",IMG_CMP_BMP_16_565_RLE,0)

//effect
RES_ADD_IMG(IMG_DC_ICON_EF_NORMAL,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_EF_NORMAL.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_EF_BLACKWHITE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_EF_BLACKWHITE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_EF_RED,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_EF_RED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_EF_GREEN,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_EF_GREEN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_EF_BLUE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_EF_BLUE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_EF_YELLOW,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_EF_YELLOW.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_EF_NEGATIVE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_EF_NEGATIVE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_EF_CANVAS,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_EF_CANVAS.bmp",IMG_CMP_BMP_16_565_RLE,0)

//night
RES_ADD_IMG(IMG_DC_ICON_NIGHT_OFF,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_NIGHT_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_NIGHT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_NIGHT.bmp",IMG_CMP_BMP_16_565_RLE,0)

//white balance
RES_ADD_IMG(IMG_DC_ICON_WB_AUTO,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_WB_AUTO.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_WB_INCANDESCENCE,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_WB_INCANDESCENCE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_WB_FLUORESCENT,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_WB_FLUORESCENT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_WB_SUN,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_WB_SUN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_WB_CLOUDY,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_WB_CLOUDY.bmp",IMG_CMP_BMP_16_565_RLE,0)

//delay
RES_ADD_IMG(IMG_DC_ICON_10S,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_10S.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_3S,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_3S.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_DELAY_OFF,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_DELAY_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)

//multi shot
RES_ADD_IMG(IMG_DC_ICON_NO_MULTI,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_NO_MULTI.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_3_MULTI,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_3_MULTI.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_ICON_6_MULTI,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_ICON_6_MULTI.bmp",IMG_CMP_BMP_16_565_RLE,0)

#endif //MMIDC_DESKTOP_ICON_BAR


//RES_ADD_IMG(IMG_DC_BMP_MASK,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_BMP_MASK.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_TITLE_BG,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_TITLE_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMG_DC_UP_ARROW,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_UP_ARROW.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMG_DC_DOWN_ARROW,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_DOWN_ARROW.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif //MMIDC_MINI_RESOURCE_SIZE
#endif //#if !defined(MMIDC_DESKTOP_PDA)

#ifdef   CMMB_SUPPORT
//used by MTV
RES_ADD_IMG(IMG_DC_PNG_MASK,"\\MMI_RES_##\\IMAG\\DC OSD\\IMG_DC_BMP_MASK.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
#endif

//PDA PIC
#if defined(MMIDC_DESKTOP_PDA)

#if defined(MMIDC_F_PDA_BIT_16)
    RES_ADD_IMG(IMG_ICONLIST_SHADOW,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_SHADOW.bmp",IMG_CMP_BMP_16_565_RLE,0)
    
    RES_ADD_IMG(IMG_ICONLIST_EXPAND_IN,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_EXPAND_IN.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EXPAND_OUT,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_EXPAND_OUT.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_PHOTO.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_PHOTO_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_PHOTO_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_VIDEO,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_VIDEO.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_VIDEO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_VIDEO_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_VIDEO_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_VIDEO_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO_ATTRIBUTE,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_PHOTO_ATTRIBUTE.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO_ATTRIBUTE_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_PHOTO_ATTRIBUTE_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_WB,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_WB.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_WB_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_WB_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_WB_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_WB_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EFFECT,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_EFFECT.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EFFECT_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_EFFECT_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_SETTINGS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_SETTINGS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_SETTINGS_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_SETTINGS_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    
#if defined (MMIDC_F_U_CAMERA)
    RES_ADD_IMG(IMG_BTN_UCAMERA,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_CAMEFX.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_UCAMERA_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_CAMEFX_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_UCAMERA_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_CAMEFX_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
    RES_ADD_IMG(IMG_BTN_PHOTO,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PHOTO.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PHOTO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PHOTO_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PHOTO_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PHOTO_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_VIDEO.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_VIDEO_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_VIDEO_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_ZOOM,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_ZOOM.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_ZOOM_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_ZOOM_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_ZOOM_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_ZOOM_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_SENSOR_FRONT,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_SENSOR_FRONT.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_SENSOR_FRONT_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_SENSOR_FRONT_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_SENSOR_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_SENSOR_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PREVIEW_IMG.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PREVIEW_IMG_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PREVIEW_IMG_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICON_RECORD_TIP,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICON_RECORD_TIP.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_PIC_PROPERTY_BG,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_PIC_PROPERTY_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_DV_PIC_PROPERTY_BG,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_DV_PIC_PROPERTY_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_CONTRAST_ICON,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_CONTRAST_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BRIGHTNESS_ICON,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BRIGHTNESS_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_EC_ICON,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_EC_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)

    RES_ADD_IMG(IMG_BTN_PHOTO_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_BTN_PHOTO.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PHOTO_FOCUS_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_BTN_PHOTO_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PHOTO_GRAY_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_BTN_PHOTO_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_BTN_VIDEO.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_FOCUS_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_BTN_VIDEO_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_GRAY_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_BTN_VIDEO_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)

    
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_VIDEO,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PREVIEW_IMG_VIDEO.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_VIDEO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PREVIEW_IMG_VIDEO_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_VIDEO_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PREVIEW_IMG_VIDEO_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    
    RES_ADD_IMG(IMG_BTN_SAVE,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_SAVE.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_CANCEL,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_CANCEL.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_SEND,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_SEND.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_DELETE,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_DELETE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//    RES_ADD_IMG(IMG_BTN_EDIT,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_EDIT.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_STOP,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_STOP.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PAUSE,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PAUSE.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_PLAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_PLAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_RESUME,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_RESUME.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_BAR_BG,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_BAR_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_LEFT,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_ARROW_LEFT.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_LEFT_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_ARROW_LEFT_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_LEFT_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_ARROW_LEFT_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_RIGHT,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_ARROW_RIGHT.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_RIGHT_GRAY,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_ARROW_RIGHT_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_RIGHT_FOCUS,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_ARROW_RIGHT_FOCUS.bmp",IMG_CMP_BMP_16_565_RLE,0)
    
    RES_ADD_IMG(IMG_DC_WAIT,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICON_WAIT.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_OPTION,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_OPTION.bmp",IMG_CMP_BMP_16_565_RLE,0)

    RES_ADD_IMG(IMG_BTN_OK,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_OK.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_BTN_EXIT,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_BTN_EXIT.bmp",IMG_CMP_BMP_16_565_RLE,0)


    #if 0
    #if defined(MMIDC_F_CAPTURE_ANIM) || defined(MMIDC_F_PREVIEW_ANIM)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        //RES_ADD_IMG(IMG_PREVIEW_ANIM_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\2.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_2_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\3_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_2_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\3_2.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_3_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\4_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_3_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\4_2.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_4_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\5_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_4_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\5_2.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_5_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\6_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_5_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\6_2.bmp",IMG_CMP_BMP_16_565_RLE,0)
    
    
        RES_ADD_IMG(IMG_PREVIEW_ANIM_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        //RES_ADD_IMG(IMG_PREVIEW_ANIM_2,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\2.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_2_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\3_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_2_2_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\3_2.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_3_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\4_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_3_2_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\4_2.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_4_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\5_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_4_2_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\5_2.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_5_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\6_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_5_2_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\6_2.bmp",IMG_CMP_BMP_16_565_RLE,0)
        
    #endif //end #if defined(MMI_CAMERA_F_CAPTURE_ANIM)
    #endif
    
    //vertical screen resource
    RES_ADD_IMG(IMG_SEEKBAR_SCALE_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_SEEKBAR_SCALE.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_BG_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_SEEKBAR_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_FRAME_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_SEEKBAR_FRAME.bmp",IMG_CMP_BMP_16_565_RLE,0)
    
    RES_ADD_IMG(IMG_ICONLIST_SHADOW_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_ICONLIST_SHADOW.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EXPAND_IN_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_ICONLIST_EXPAND_IN.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EXPAND_OUT_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_ICONLIST_EXPAND_OUT.bmp",IMG_CMP_BMP_16_565_RLE,0)
    
    RES_ADD_IMG(IMG_BTN_BAR_BG_V,"\\MMI_RES_##\\IMAG\\PDA_BMP_V\\IMG_BTN_BAR_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
    
#else
    RES_ADD_IMG(IMG_ICONLIST_BG,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_ICON_FOCUS_BG,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_ICON_FOCUS_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_TEXT_BG,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_TEXT_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
    RES_ADD_IMG(IMG_ICONLIST_SHADOW,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_SHADOW.png",IMG_CMP_PNG_ARGB_RLE,0)
//    RES_ADD_IMG(IMG_ICONLIST_SPLIT_LINE,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_SPLIT_LINE.png",IMG_CMP_PNG_ARGB_RLE,0)

    RES_ADD_IMG(IMG_ICONLIST_EXPAND_IN,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_EXPAND_IN.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EXPAND_OUT,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_EXPAND_OUT.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_PHOTO.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_PHOTO_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_PHOTO_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_VIDEO,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_VIDEO.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_VIDEO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_VIDEO_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_VIDEO_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_VIDEO_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO_ATTRIBUTE,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_PHOTO_ATTRIBUTE.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_PHOTO_ATTRIBUTE_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_PHOTO_ATTRIBUTE_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_WB,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_WB.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_WB_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_WB_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_WB_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_WB_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EFFECT,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_EFFECT.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EFFECT_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_EFFECT_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_SETTINGS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_SETTINGS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_SETTINGS_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICONLIST_SETTINGS_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)

#if defined (MMIDC_F_U_CAMERA)
    RES_ADD_IMG(IMG_BTN_UCAMERA,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_CAMEFX.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_UCAMERA_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_CAMEFX_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_UCAMERA_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_CAMEFX_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
    RES_ADD_IMG(IMG_BTN_PHOTO,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PHOTO.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PHOTO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PHOTO_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PHOTO_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PHOTO_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_VIDEO.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_VIDEO_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_VIDEO_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_ZOOM,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ZOOM.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_ZOOM_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ZOOM_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_ZOOM_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ZOOM_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_SENSOR_FRONT,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_SENSOR_FRONT.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_SENSOR_FRONT_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_SENSOR_FRONT_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_SENSOR_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_SENSOR_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PREVIEW_IMG.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PREVIEW_IMG_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PREVIEW_IMG_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICON_RECORD_TIP,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICON_RECORD_TIP.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_PIC_PROPERTY_BG,"\\MMI_RES_##\\IMAG\\PDA\\IMG_PIC_PROPERTY_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_DV_PIC_PROPERTY_BG,"\\MMI_RES_##\\IMAG\\PDA\\IMG_DV_PIC_PROPERTY_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_CONTRAST_ICON,"\\MMI_RES_##\\IMAG\\PDA\\IMG_CONTRAST_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BRIGHTNESS_ICON,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BRIGHTNESS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_EC_ICON,"\\MMI_RES_##\\IMAG\\PDA\\IMG_EC_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

    RES_ADD_IMG(IMG_BTN_PHOTO_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_BTN_PHOTO.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PHOTO_FOCUS_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_BTN_PHOTO_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PHOTO_GRAY_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_BTN_PHOTO_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_BTN_VIDEO.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_FOCUS_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_BTN_VIDEO_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_VIDEO_GRAY_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_BTN_VIDEO_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)


    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_VIDEO,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PREVIEW_IMG_VIDEO.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_VIDEO_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PREVIEW_IMG_VIDEO_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PREVIEW_IMG_VIDEO_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PREVIEW_IMG_VIDEO_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)

    RES_ADD_IMG(IMG_BTN_SAVE,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_SAVE.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_CANCEL,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_CANCEL.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_SEND,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_SEND.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_DELETE,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_DELETE.png",IMG_CMP_PNG_ARGB_RLE,0)
//    RES_ADD_IMG(IMG_BTN_EDIT,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_EDIT.png",IMG_CMP_PNG_ARGB_RLE,0)
//    RES_ADD_IMG(IMG_BTN_ASWALLPAPER,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ASWALLPAPER.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_STOP,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_STOP.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PAUSE,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PAUSE.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_PLAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_PLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_RESUME,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_RESUME.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_BG,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_BG_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_BG_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_BAR_BG,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_BAR_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_VER_STRETCH,0)
    RES_ADD_IMG(IMG_BTN_ARROW_LEFT,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ARROW_LEFT.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_LEFT_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ARROW_LEFT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_LEFT_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ARROW_LEFT_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_RIGHT,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ARROW_RIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_RIGHT_GRAY,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ARROW_RIGHT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_ARROW_RIGHT_FOCUS,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_ARROW_RIGHT_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)

    RES_ADD_IMG(IMG_DC_WAIT,"\\MMI_RES_##\\IMAG\\PDA\\IMG_ICON_WAIT.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_OPTION,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_OPTION.png",IMG_CMP_PNG_ARGB_RLE,0)

    RES_ADD_IMG(IMG_BTN_OK,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_OK.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_BTN_EXIT,"\\MMI_RES_##\\IMAG\\PDA\\IMG_BTN_EXIT.png",IMG_CMP_PNG_ARGB_RLE,0)


    #if defined(MMIDC_F_CAPTURE_ANIM) || defined(MMIDC_F_PREVIEW_ANIM)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\1.png",IMG_CMP_PNG_ARGB_RLE,0)
        //RES_ADD_IMG(IMG_PREVIEW_ANIM_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\2.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_2_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\3_1.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_2_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\3_2.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_3_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\4_1.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_3_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\4_2.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_4_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\5_1.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_4_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\5_2.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_5_1,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\6_1.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_5_2,"\\MMI_RES_##\\ANIM\\ANIM_PREVIEW_ANIM\\6_2.png",IMG_CMP_PNG_ARGB_RLE,0)


        RES_ADD_IMG(IMG_PREVIEW_ANIM_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\1.png",IMG_CMP_PNG_ARGB_RLE,0)
        //RES_ADD_IMG(IMG_PREVIEW_ANIM_2,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\2.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_2_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\3_1.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_2_2_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\3_2.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_3_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\4_1.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_3_2_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\4_2.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_4_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\5_1.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_4_2_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\5_2.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_5_1_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\6_1.png",IMG_CMP_PNG_ARGB_RLE,0)
        RES_ADD_IMG(IMG_PREVIEW_ANIM_5_2_V,"\\MMI_RES_##\\IMAG\\PDA_V\\ANIM_PREVIEW_ANIM\\6_2.png",IMG_CMP_PNG_ARGB_RLE,0)
        
    #endif //end #if defined(MMI_CAMERA_F_CAPTURE_ANIM)

    //vertical screen resource
    RES_ADD_IMG(IMG_SEEKBAR_SCALE_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_SEEKBAR_SCALE.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_MARK_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_SEEKBAR_MARK.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_BG_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_SEEKBAR_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_SEEKBAR_FRAME_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_SEEKBAR_FRAME.png",IMG_CMP_PNG_ARGB_RLE,0)

    RES_ADD_IMG(IMG_ICONLIST_SHADOW_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_ICONLIST_SHADOW.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EXPAND_IN_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_ICONLIST_EXPAND_IN.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EXPAND_OUT_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_ICONLIST_EXPAND_OUT.png",IMG_CMP_PNG_ARGB_RLE,0)

    RES_ADD_IMG(IMG_BTN_BAR_BG_V,"\\MMI_RES_##\\IMAG\\PDA_V\\IMG_BTN_BAR_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)

    //end vertical screen resource
    #endif //end #if defined(MMIDC_F_PDA_BIT_16)
#endif //end defined(MMIDC_DESKTOP_PDA)

#if defined (MMIDC_F_U_CAMERA)
/*
#if defined(MMIDC_F_PDA_BIT_16)
    RES_ADD_IMG(IMG_ICONLIST_EFFECT_NONE,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_EFFECT_NONE.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EFFECT_NINONE,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_EFFECT_NINONE.bmp",IMG_CMP_BMP_16_565_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EFFECT_SMILE,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMG_ICONLIST_EFFECT_SMILE.bmp",IMG_CMP_BMP_16_565_RLE,0)
#else //defined(MMIDC_F_PDA_BIT_16)
*/
    RES_ADD_IMG(IMG_ICONLIST_EFFECT_NONE,"\\MMI_RES_##\\IMAG\\PDA\\IMAGE_CAMEFX_NORMAL.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EFFECT_NINONE,"\\MMI_RES_##\\IMAG\\PDA\\IMAGE_CAMEFX_FOURINONE.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_ICONLIST_EFFECT_SMILE,"\\MMI_RES_##\\IMAG\\PDA\\IMAGE_CAMEFX_IMGPROC.png",IMG_CMP_PNG_ARGB_RLE,0)
    RES_ADD_IMG(IMG_NINONE_PREVIEW,"\\MMI_RES_##\\IMAG\\PDA_BMP\\IMAGE_CAMEFX_FOURINONE_PREVIEW.bmp",IMG_CMP_BMP_16_565_RLE,0)

//#endif //defined(MMIDC_F_PDA_BIT_16)
#endif //defined (MMIDC_F_U_CAMERA)

#endif  //#ifdef CAMERA_SUPPORT

//]]define image infomation



//[[define anim infomation

//]]define anim infomation


#if 1
#ifdef  CAMERA_SUPPORT

//[[define string infomation
//RES_ADD_STRING(TXT_DC_SHOOT,"Shoot")          //replaced by common ID TXT_COMMON_CAPTURE

//RES_ADD_STRING(TXT_DC_SIZE,"Size")  //replaced by common ID TXT_COMM_SIZE

RES_ADD_STRING(TXT_DC_SHUTTERVOICE,"Shutter")

RES_ADD_STRING(TXT_DC_EFFECT,"Effect")

RES_ADD_STRING(TXT_DC_QUALITY,"Quality")

RES_ADD_STRING(TXT_DC_CIRCLE,"Frame")

RES_ADD_STRING(TXT_DC_MODE,"Camera Mode")

//RES_ADD_STRING(TXT_DC_LIGHTENESS,"Light")      //replaced by common ID TXT_COMMON_COMMON_BRIGHTNESS

//RES_ADD_STRING(TXT_DC_CONTRAST,"Contrast")  //replaced by common ID TXT_COMM_CONTRAST

RES_ADD_STRING(TXT_DC_SELF_SHOT,"Delay")

RES_ADD_STRING(TXT_DC_MULTI_SHOT,"Burst")

//RES_ADD_STRING(TXT_DC_ZOOM,"Zoom")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_MODE_NORMAL,"Normal")//case3：defined but not used

RES_ADD_STRING(TXT_DC_MODE_BANDW,"B&W")

RES_ADD_STRING(TXT_DC_MODE_BLUE,"Blue")

RES_ADD_STRING(TXT_DC_MODE_GREEN,"Green")

RES_ADD_STRING(TXT_DC_MODE_YELLOW,"Yellow")

RES_ADD_STRING(TXT_DC_MODE_RED,"Red")

RES_ADD_STRING(TXT_DC_MODE_CANVAS,"Canvas")

//RES_ADD_STRING(TXT_DC_MODE_NEGATIVE,"Negative")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_HIGHQUALITY,"Advanced")           //replaced by common ID TXT_COMMON_HIGHQUALITY

//RES_ADD_STRING(TXT_DC_NORMALQUALITY,"Normal")           //replaced by common ID TXT_COMMON_COMMON_NORMAL

//RES_ADD_STRING(TXT_DC_ACTIVE,"Active")  //replaced by common ID TXT_ACTIVE_OPERATIVE

//RES_ADD_STRING(TXT_DC_DEACTIVE,"Deactive")              //replaced by common ID TXT_CLOSE 

//RES_ADD_STRING(TXT_DC_NIGHT,"Night")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_MENU,"Menu")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_OPTION,"Option")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_OPT_WALLPAPER,"Set as wallpaper")         //replaced by common ID TXT_COMMON_SETAS_WALLPAPER 

//RES_ADD_STRING(TXT_DC_DISPLAY_SETTINGS,"Tip Setting")//case3：defined but not used
#ifdef CAMERA_FRAME_SUPPORT
RES_ADD_STRING(TXT_DC_CIRCLE1,"Frame1")

RES_ADD_STRING(TXT_DC_CIRCLE2,"Frame2")

RES_ADD_STRING(TXT_DC_CIRCLE3,"Frame3")

RES_ADD_STRING(TXT_DC_NO_CIRCLE,"No Frame")
#endif
RES_ADD_STRING(TXT_DC_3_MULTI_SHOT,"3 photos")

RES_ADD_STRING(TXT_DC_6_MULTI_SHOT,"6 photos")

//RES_ADD_STRING(TXT_DC_9_MULTI_SHOT,"9 photos")

//RES_ADD_STRING(TXT_DC_INDOOR,"Indoor")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_OUTDOOR,"Outdoor")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_ADVANCE,"Advance")

RES_ADD_STRING(TXT_DC_BRIEF,"Brief")

//RES_ADD_STRING(TXT_DC_SEND,"Send")  //replaced by common ID TXT_SEND

//RES_ADD_STRING(TXT_DC_PHOTO_DIRECTORY,"My Photo")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_ROOM_COUNT,"Space state")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_SELF_SHOT_SECOND,"Self shot, left")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_SHOTTING,"Shotting......")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_SHOT_DONE,"done")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_FULL_SCREEN,"Full screen review")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_SHOT_CONTINUE,"Continue")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_3S,"3s")   //replaced by common ID TXT_COMM_3_SECOND

//RES_ADD_STRING(TXT_DC_10S,"10s")  //replaced by common ID TXT_COMM_10_SECOND

//RES_ADD_STRING(TXT_DC_SAVING,"Saving")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_FORBID,"Forbidden")     //replaced by common ID TXT_COMMON_COMMON_DISABLE

//RES_ADD_STRING(TXT_DC_TAKE_PHOTO,"Digital camera")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_VIDEO,"Digital video")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_CAMERA,"Camera")//case3：defined but not used

#ifdef PIC_PREVIEW_U200_SUPPORT
RES_ADD_STRING(TXT_DC_MY_PICTURE,"My picture")
#endif

//RES_ADD_STRING(TXT_DC_MY_VIDEO,"My video")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_STORE_STATUS,"Store status")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_UDISK,"Udisk")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_SD,"SD")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_PHOTO_USED_MEMORY,"Photo used")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_VIDEO_USED_MEMORY,"Video used")//case3：defined but not used

//RES_ADD_STRING(TXT_FREE_MEMORY,"Free")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_MINIATURE_VIEW,"Miniature")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_DELETE,"Delete")      //replaced by common ID TXT_DELETE

//RES_ADD_STRING(TXT_DC_UP_DOWN,"Up-down")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_DOWN_UP,"Down-up")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_LEFT_RIGHT,"Left-right")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_RIGHT_LEFT,"Right-left")

//RES_ADD_STRING(TXT_DC_PANORAMA,"Panorama")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_SHOT_AND_MOSAIC,"Shotting and Combining...")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_PROCESS,"Capture Process")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_BURSTSHOTTING,"Burst shotting......")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_SEND_BY_MMS,"MMS")  //replaced by common ID TXT_MMS

//RES_ADD_STRING(TXT_DC_SEND_BY_BT,"Blue tooth")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_RELIEVOS,"Relievos")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_STORE_MEDIUM,"Store")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_SAVESUCC,"Save Sucess")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_SAVEFAILED,"Save Failed")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_CAMERA_MODE,"Mode")//case3：defined but not used

RES_ADD_STRING(TXT_DC_SWITCH_PHOTO,"DC Mode")

RES_ADD_STRING(TXT_DC_SWITCH_VIDEO,"DV Mode")

//RES_ADD_STRING(TXT_DC_GRADE_0,"-3")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_GRADE_1,"-2")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_GRADE_2,"-1")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_GRADE_3,"0")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_GRADE_4,"1")//case3：defined but not used

RES_ADD_STRING(TXT_DC_AUTO_SAVE,"Auto Save")

//RES_ADD_STRING(TXT_DC_REVIEW_AFTER_CAPTURE,"Review after Capture")//case3：defined but not used

RES_ADD_STRING(TXT_DC_SHOW_SETTING,"Tip Setting")

//RES_ADD_STRING(TXT_DC_HELP,"Help")  //replaced by common ID  TXT_HELP

//RES_ADD_STRING(TXT_DC_GRADE_5,"2")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_GRADE_6,"3")//case3：defined but not used

RES_ADD_STRING(TXT_DC_CAPTURE_FAILED,"Capture Failed")

//RES_ADD_STRING(TXT_DC_NO_SPACE,"Space is not enough") //removed, @robert.wang, 09-10-28,cr157920

RES_ADD_STRING(TXT_DC_CORUSCATE,"Avoid Coruscate")

RES_ADD_STRING(TXT_DC_50HZ,"50HZ")

RES_ADD_STRING(TXT_DC_60HZ,"60HZ")

//RES_ADD_STRING(TXT_DV_SIZE,"Image size")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_EFFECT,"Image effect")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_QUALITY,"Image quality")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_MODE_NORMAL,"Normal")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_MODE_BANDW,"B&W")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_MODE_BLUE,"Blue")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_MODE_GREEN,"Green")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_MODE_YELLOW,"Yellow")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_MODE_RED,"Red")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_MODE_CANVAS,"Canvas")//case3：defined but not used

RES_ADD_STRING(TXT_DV_MODE_NEGATIVE,"Negative")

//RES_ADD_STRING(TXT_DV_NORMALQUALITY,"Normal")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_ACTIVE,"Active")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_DEACTIVE,"Deactive")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_NIGHT,"Night")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_MENU,"Menu")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_DISPLAY_SETTINGS,"Display settings")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_INDOOR,"Indoor")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_OUTDOOR,"Outdoor")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_ADVANCE,"Advance")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_BRIEF,"Brief")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_ROOM_COUNT,"Room")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_SAVING,"Saving......")//case3：defined but not used

RES_ADD_STRING(TXT_DV_SHOOT,"Shoot")

//RES_ADD_STRING(TXT_DV_STOP,"Stop")    //replaced by common ID  STXT_STOP

//RES_ADD_STRING(TXT_DV_LIGHTENESS,"Lighteness")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_PAUSE,"Pause")    //replaced by common ID  TXT_PAUSE

//RES_ADD_STRING(TXT_DV_RESUME,"Resume")      //replaced by common ID TXT_COMMON_COMMON_CONTINUE

//RES_ADD_STRING(TXT_DV_AUDIO,"Audio")    //replaced by common ID TXT_AUDIO

//RES_ADD_STRING(TXT_DV_VIDEO_TYPE,"Type")//case3：defined but not used

RES_ADD_STRING(TXT_DV_TYPE_MP4,"Mp4")

#if defined ( AVI_ENC_SUPPORT ) ||defined( MMIDC_DESKTOP_PDA )
RES_ADD_STRING(TXT_DV_TYPE_AVI,"Avi")
#endif

RES_ADD_STRING(TXT_DV_TYPE_3GP,"3gp")

//RES_ADD_STRING(TXT_DV_RECORD_PAUSE,"Pause")//case3：defined but not used

RES_ADD_STRING(TXT_DV_RECORD_DIRECTORY,"My Video")

//RES_ADD_STRING(TXT_DV_OPEN_FAIL,"DV operation fail")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_RECORD_ERROR,"Record error")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_INSUFFICIENT_SPACE,"Insufficient space")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_MODE,"Environment")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_NO_FILE,"No video files")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_READY,"Ready")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_PLAY,"Play")  //replaced by common ID TXT_COMMON_PLAY

//RES_ADD_STRING(TXT_DV_DEL,"Delete")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_SEND,"Send")//case3：defined but not used

RES_ADD_STRING(TXT_DV_SHOOT_NEW,"Shoot again")

//RES_ADD_STRING(TXT_DV_OPTION,"Option")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_RETURN,"Return")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_VIDEO_MANAGER,"Record directory")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_DELETE_SUCCESS,"Delete success")//case3：defined but not used

//RES_ADD_STRING(TXT_DELETE_FAILE,"Delete failed")  //replaced by common ID TXT_COMMON_DEL_FAIL

//RES_ADD_STRING(TXT_DV_TYPE_MJPG,"Mjpg")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_SAVE_ASK_REVIEW,"Save success, review it now?")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_STORE_MEDIUM,"Store Medium")  //replaced by common ID STXT_STORE_MEDIUM

//RES_ADD_STRING(TXT_DV_MODE_RELIEVOS,"Relievos")//case3：defined but not used

//RES_ADD_STRING(TXT_DV_CANCELING,"Canceling...")//case3：defined but not used
RES_ADD_STRING(TXT_DC_PIC,"Store Photos")

RES_ADD_STRING(TXT_DC_EXPOSAL,"Exposal Compensate")

RES_ADD_STRING(TXT_DC_WHITE_BALANCE,"White Balance")

//RES_ADD_STRING(TXT_DC_AUTO,"Auto")  //replaced by common ID TXT_AUTO

RES_ADD_STRING(TXT_DC_SUN,"Sun Light")

RES_ADD_STRING(TXT_DC_CLOUDY,"Cloudy")

RES_ADD_STRING(TXT_DC_INCANDESCENCE,"Incandesce")

RES_ADD_STRING(TXT_DC_FLUORESCENT,"Fluoresce")

#ifdef MMIDC_F_FLASH
RES_ADD_STRING(TXT_DC_FLASH,"Flash")
#endif

//RES_ADD_STRING(TXT_DC_EC_M20,"-2.0")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_EC_M15,"-1.5")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_EC_M10,"-1.0")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_EC_M05,"-0.5")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_EC_00,"0.0")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_EC_05,"+0.5")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_EC_10,"+1.0")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_EC_15,"+1.5")//case3：defined but not used

//RES_ADD_STRING(TXT_DC_EC_20,"+2.0")//case3：defined but not used
#ifdef CAMERA_FRAME_SUPPORT
RES_ADD_STRING(TXT_DC_CIRCLE4,"Frame4")
#endif
//RES_ADD_STRING(TXT_DC_ENVIRONMENT,"Environment")    //replaced by common ID TXT_NIGHT_MODE

#ifndef MMIDC_MINI_RESOURCE_SIZE
RES_ADD_STRING(TXT_DC_HELP_CONTENT,"The OSD menu will appear when pressing left key or right key in the preview, then you could adjust all parameter, and also camera will zoom in or zoom out if you press down key or up key, of course the function should be support by sensor. Pressing OK key or capture key, camera will capture.")
#endif

//RES_ADD_STRING(TXT_DC_PATH_IS_TOO_LONG, "Save path is too long!")//case3：defined but not used

RES_ADD_STRING(TXT_DC_FILE_CREATED_FAIL, "File Created Fail")   //added, @robert.wang, 09-9-5, cr149292
#if defined ENG_SUPPORT && defined CAMERA_SUPPORT
RES_ADD_STRING(TXT_SENSOR_0, "0")

RES_ADD_STRING(TXT_SENSOR_90, "90")   //added, @robert.wang, 09-9-5, cr149292

RES_ADD_STRING(TXT_SENSOR_180, "180")

RES_ADD_STRING(TXT_SENSOR_270, "270")

RES_ADD_STRING(TXT_SENSOR_MIRROR, "Mirror")

RES_ADD_STRING(TXT_SENSOR_FLIP, "Flip")
#endif
RES_ADD_STRING(TXT_PHOTO_DATE, "Photo Timestamp")
#if defined(MMIDC_DESKTOP_PDA)
RES_ADD_STRING(TXT_DC_IMAGE_PROPERTY, "Image property")
#endif

#ifdef MMIDC_DESKTOP_ICON_BAR
    RES_ADD_STRING(TXT_MORE_OPTION, "More Option")
    RES_ADD_STRING(TXT_DC_SHORTCUT_HELP_CONTENT, "Shortcut help")

    #if defined (MMIDC_F_U_CAMERA)
    RES_ADD_STRING(TXT_DC_UCAMERA_HELP_CONTENT, "ucamera help")
    #endif
#endif

#if defined(MMIDC_F_U_CAMERA)
//RES_ADD_STRING(TXT_DC_UCAMERA_OPEN_FAIL, "UCamera Open fail!")//case3：defined but not used
RES_ADD_STRING(TXT_EFFECT_SELECT, "Select effect")
RES_ADD_STRING(TXT_EFFECT_NONE, "Normal Camera")
RES_ADD_STRING(TXT_EFFECT_NINONE, "Four in one")
RES_ADD_STRING(TXT_EFFECT_SMILE, "Smile auto capture")
RES_ADD_STRING(TXT_EFFECT_LOMO, "Lomo")
RES_ADD_STRING(TXT_EFFECT_HDR, "HDR")
RES_ADD_STRING(TXT_EFFECT_FISH, "Fish Eye")
RES_ADD_STRING(TXT_EFFECT_INFRARED, "Infrared")
RES_ADD_STRING(TXT_EFFECT_XRAY, "X ray")
RES_ADD_STRING(TXT_EFFECT_PENCIL, "Pencil sketch")
RES_ADD_STRING(TXT_EFFECT_EXPOSAL, "Exposal")
RES_ADD_STRING(TXT_EFFECT_NEGATIVE, "Negative")
#endif //#if defined(MMIDC_F_U_CAMERA)

#ifdef WRE_SUPPORT
RES_ADD_STRING(TXT_DC_EXIT_BACKGROUND_WRE, "Wre is background running, Pls quit it")
#endif
//]]define string infomation
#endif

#if defined(SCREEN_SHAPE_CIRCULAR)
RES_ADD_STRING(TXT_CAMERA_NO_SPACE, "Storage is full")
#endif


//[[define data infomation

//]]define data infomation

#endif

