



//[[define image infomation

//]]define image infomation





//[[define anim infomation

//]]define anim infomation





//[[define string infomation

RES_ADD_STRING(TXT_ENG_NETWORKSETTING,"Network Setting")

RES_ADD_STRING(TXT_ENG_DSP_RESET,"Dsp Reset")

RES_ADD_STRING(TXT_ENG_NETINFO_L1,"L1 info")

RES_ADD_STRING(TXT_ENG_NETINFO_L2,"L2 info")

RES_ADD_STRING(TXT_ENG_NETINFO_L3,"L3 info")

RES_ADD_STRING(TXT_ENG_NETINFO_NAS,"NAS info")

RES_ADD_STRING(TXT_ENG_LYONETIMESLOT,"Timeslot iscp")

RES_ADD_STRING(TXT_ENG_LYONEDPCH,"Dpch rscp")

RES_ADD_STRING(TXT_ENG_LYONEOTHER,"Other")

RES_ADD_STRING(TXT_ENG_LYONEBLER,"Bler list")

RES_ADD_STRING(TXT_ENG_LYTHREESCELL,"Scell info")

RES_ADD_STRING(TXT_ENG_LYTHREENCELL,"Ncell Info")

RES_ADD_STRING(TXT_ENG_NASMM,"MM Info")

RES_ADD_STRING(TXT_ENG_NASGMM,"GMM info")

RES_ADD_STRING(TXT_ENG_DSP_PRESET_DSP1,"Dsp1")

RES_ADD_STRING(TXT_ENG_DSP_RESET_DSP2,"Dsp2")

//RES_ADD_STRING(TXT_ENG_DSP_RESET_BOTH,"Both")  //replaced by common ID TXT_ENG_BOTH

RES_ADD_STRING(TXT_ENG_FREQ,"Frequency")

RES_ADD_STRING(TXT_ENG_IMSI,"IMSI")

RES_ADD_STRING(TXT_ENG_SIMSIMULATE,"Sim simulate")

//RES_ADD_STRING(TXT_ENG_UART1_USEDBY,"UART1 Used By")     //case3£ºdefined but not used

RES_ADD_STRING(TXT_ENG_DEEP_SLEEP,"Deep Sleep")

RES_ADD_STRING(TXT_ENG_RF_LOOP,"RF Loop")

RES_ADD_STRING(TXT_ENG_NETWORKSETTING_INFO,"Network Setting Info")

//RES_ADD_STRING(TXT_ENG_UART1_USEDBY_ARMREF,"ARM Ref")    //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_UART1_USEDBY_DSP1,"Dsp1")    //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_UART1_USEDBY_CYPS,"CYPS")      //case3£ºdefined but not used

RES_ADD_STRING(TXT_ENG_SERVICE_TYPE,"Service Type")

RES_ADD_STRING(TXT_ENG_GPRS_PROC,"GPRS Proc")

RES_ADD_STRING(TXT_ENG_PS_BITRATE,"Ps Bitrate(UL/DL)")

RES_ADD_STRING(TXT_ENG_GSM_ONLY,"GSM Only")

RES_ADD_STRING(TXT_ENG_GPRS_ONLY,"GPRS Only")

RES_ADD_STRING(TXT_ENG_GSM_GPRS,"GSM and GPRS")

RES_ADD_STRING(TXT_ENG_ATTACH,"Attach")

RES_ADD_STRING(TXT_ENG_DETACH,"Detach")

//RES_ADD_STRING(TXT_ENG_PS_BITRATE_8,"8k/8k")        //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_PS_BITRATE_16,"16k/16k")         //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_PS_BITRATE_32,"16k/32k")        //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_PS_BITRATE_64,"64k/64k")      //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_PS_BITRATE_128,"64k/128k")      //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_PS_BITRATE_384,"64k/384k")      //case3£ºdefined but not used

RES_ADD_STRING(TXT_ENG_CS64_FLAG,"CS64")

//RES_ADD_STRING(TXT_ENG_CS64_ON,"On") //replaced by common ID TXT_COMM_ON

//RES_ADD_STRING(TXT_ENG_CS64_OFF,"Off")// replaced by common ID TXT_COMM_OFF

RES_ADD_STRING(TXT_ENG_FDN_FLAG,"FDN")

RES_ADD_STRING(TXT_ENG_BDN_FLAG,"BDN")

RES_ADD_STRING(TXT_ENG_APN_SETTING,"APN")

RES_ADD_STRING(TXT_ENG_SMS_PATH,"SMS Path")

RES_ADD_STRING(TXT_ENG_SMS_SERV,"sms serv")

RES_ADD_STRING(TXT_ENG_SMS_CS,"cs only")

RES_ADD_STRING(TXT_ENG_SMS_PS,"ps only")

RES_ADD_STRING(TXT_ENG_SMS_CS_PREFER,"cs prefer")

RES_ADD_STRING(TXT_ENG_SMS_PS_PREFER,"ps prefer")

RES_ADD_STRING(TXT_ENG_PSCTRL_FLAG,"PSD Ctrl")

//RES_ADD_STRING(TXT_ENG_PSCTRL_ON,"On")//replaced by common ID TXT_COMM_ON

//RES_ADD_STRING(TXT_ENG_PSCTRL_OFF,"Off") //replaced by common ID TXT_COMM_OFF

RES_ADD_STRING(TXT_ENG_ASNSELECT,"ASN.1 Version Select")

RES_ADD_STRING(TXT_ENG_ASN1_490,"ASN.1 490")

RES_ADD_STRING(TXT_ENG_ASN1_4h0,"ASN.1 4h0")

RES_ADD_STRING(TXT_ENG_UpPCH_SHIFTING,"UpPCH SHIFTING")

RES_ADD_STRING(TXT_ENG_DRXCYCLE,"DRX Cycle")

RES_ADD_STRING(TXT_ENG_VT_SET,"VT Setting")

RES_ADD_STRING(TXT_ENG_AUDIO,"AUDIO Setting")

RES_ADD_STRING(TXT_ENG_VIDEO,"VIDEO Setting")

RES_ADD_STRING(TXT_ENG_CHIP_ID,"chip ID")

RES_ADD_STRING(TXT_ENG_ARM_LOG_OUT_PATH,"ArmLogOutPath")

RES_ADD_STRING(TXT_ENG_OUTPUT_TO_UART,"Output To Uart")

RES_ADD_STRING(TXT_ENG_OUTPUT_TO_FFS,"Output To FFS")

RES_ADD_STRING(TXT_ENG_BOTH,"Both")

RES_ADD_STRING(TXT_ENG_DSP_SETTING,"DSP Setting")

//RES_ADD_STRING(TXT_ENG_CMD_TYPE,"CMD TYPE")       //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_PARAM1,"PARAM1")       //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_PARAM2,"PARAM2")      //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_PARAM3,"PARAM3")     //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_PARAM4,"PARAM4")     //case3£ºdefined but not used

RES_ADD_STRING(TXT_ENG_ARMREFDEBUG,"ARM Ref Debug")

RES_ADD_STRING(TXT_ENG_ARMREFPS,"ARM Ref PS")

RES_ADD_STRING(TXT_ENG_UART0USEDBY,"UART0 Used By")

RES_ADD_STRING(TXT_ENG_ROAMPARAM,"Roam Param")

//RES_ADD_STRING(TXT_ENG_UARTBAUDRATE,"UART Baudrate")       //case3£ºdefined but not used

RES_ADD_STRING(TXT_ENG_UART0BAUDRATE,"COM_DATA Baudrate")

RES_ADD_STRING(TXT_ENG_UART1BAUDRATE,"COM_DEBUG Baudrate")

RES_ADD_STRING(TXT_ENG_BAUD_115200,"115200")

RES_ADD_STRING(TXT_ENG_BAUD_460800,"460800")

RES_ADD_STRING(TXT_ENG_LOCKCELL,"Lock cell")

//RES_ADD_STRING(TXT_ENG_WRONG,"Error")       //case3£ºdefined but not used

RES_ADD_STRING(TXT_ENG_DYNA_MODE,"dyna eng mode")

RES_ADD_STRING(TXT_ENG_EDIT,"Edit")

//RES_ADD_STRING(TXT_ENG_UART1_USEDBY_DEFAULT,"default")        //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_UART1_USEDBY_PS,"ps")    //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_UART1_USEDBY_DSPLOG,"dsplog")       //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_UART0_USEDBY_PS,"ps")     //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_UART0_USEDBY_ARMLOG,"armlog")      //case3£ºdefined but not used

RES_ADD_STRING(TXT_ENG_PICH_SETTING,"PICH setting")

RES_ADD_STRING(TXT_ENG_REOCRD_AUDIO_TYPE,"Record audio type")

RES_ADD_STRING(TXT_ENG_REOCRD_AUDIO_TYPE_MIXED,"Record mixed audio")

RES_ADD_STRING(TXT_ENG_REOCRD_AUDIO_TYPE_REMOTE,"Record remote audio")

RES_ADD_STRING(TXT_ENG_REOCRD_AUDIO_TYPE_LOCAL,"Record local audio")

RES_ADD_STRING(TXT_ENG_SET_VT_DEFAULT_EP,"Set default EP")

RES_ADD_STRING(TXT_ENG_ENABLE,"enable")

RES_ADD_STRING(TXT_ENG_DISABLE,"disable")

RES_ADD_STRING(TXT_ENG_L1_DSP_PARAM,"Layer1 DSP Param")
RES_ADD_STRING(TXT_ENG_DSP_PARAM_LOG,"DSP Param Log")
RES_ADD_STRING(TXT_ENG_DSP_PARAM,"DSP Param")

//RES_ADD_STRING(TXT_ENG_UPLMN_SETTING,"UPLMN Setting")  //replaced by common ID TXT_COMM_UPLMN_SETTING

RES_ADD_STRING(TXT_ENG_SUPPORT_GSM_SIM,"Support gsm sim")

RES_ADD_STRING(TXT_ENG_UART0MIXMODE,"UART0 Mix Mode")
  RES_ADD_STRING(TXT_ENG_RRM_TEST,"RRM TEST")

  RES_ADD_STRING(TXT_ENG_VIDEOTYPE,"Video Type")
  RES_ADD_STRING(TXT_ENG_H263_P,"H263 Prefer")
  RES_ADD_STRING(TXT_ENG_MPEG4_P,"MPEG4 Prefer")
  RES_ADD_STRING(TXT_ENG_H263_O,"H263 Only")
  RES_ADD_STRING(TXT_ENG_MPEG4_O,"MPEG4 Only")
RES_ADD_STRING(TXT_ENG_REQUEST_MODE,"Request mode")
RES_ADD_STRING(TXT_ENG_ADAPTER_LAYER,"Adapte layer settings")

//]]define string infomation





//[[define data infomation

//]]define data infomation

