/****************************************************************************
** File Name:      mmiwww_menutab.c                                            *
** Author:                                                                    *
** Date:           06/15/2009                                                *
** Copyright:      2004 Spreadtrum, Incorporated. All Rights Reserved.        *
** Description:    This file is used to describe the window for WWW Browser            *
*****************************************************************************
**                         Important Edit History                            *
** -------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                                *
** 06/2009        jiaoyou.wu       Create
** 
****************************************************************************/
#define _MMICC_MENUTABLE_C_

/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
#ifdef WIN32
#include "std_header.h"
#endif
#include "guimenu.h"
#include "mmiwww_image.h"
#include "mmi_menutable.h"
#include "mmiwww_text.h"
#include "mmi_common.h"
#include "mmi_nv.h"
#include "mmiwww_menutab.h"

#ifdef BROWSER_SUPPORT_NETFRONT
/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/

/**--------------------------------------------------------------------------*
 **                         STATIC DEFINITION                                *
 **--------------------------------------------------------------------------*/


/*---------------------------------------------------------------------------*/
/*                          TYPE AND CONSTANT                                */
/*---------------------------------------------------------------------------*/

//mainmenu opt when web is open
const GUIMENU_ITEM_T menu_www_mainmenu_opt1[] =
{
    {ID_WWW_HOMPAGE,                    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_OPEN_HOMEPAGE,     0, 0, 0, MENU_NULL},
//    {ID_WWW_WINDOW_MANAGER,             TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_WINDOW_MANAGER,       0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SEARCH_ENGINE,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CHOSE_SEARCH_ENGINE,     0, 0, 0, MENU_WWW_SEARCH_ENGINE_SEL},    
    {ID_WWW_SUBMENU_SAVED_PAGE,         TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_MEMO,              0, 0, 0, MENU_NULL},    
    {ID_WWW_DOWNLOAD_MANAGE,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DOWNLOAD_MANAGE,         0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SETTING,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SETTING,                 0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_CLEAN_INPUT_HISTORY,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CLEAN_INPUT_HISTORY,     0, 0, 0, MENU_NULL},
    {ID_WWW_MINIMIZE,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MINIMIZE,            0, 0, 0, MENU_NULL},
    {ID_WWW_EXIT,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BROWSER_EXIT,            0, 0, 0, MENU_NULL},

};

//mainmenu opt when web is Not open
const GUIMENU_ITEM_T menu_www_mainmenu_opt2[] =
{
    {ID_WWW_HOMPAGE,                    TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_OPEN_HOMEPAGE,     0, 0, 0, MENU_NULL},
    {ID_WWW_WINDOW_MANAGER,             TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_WINDOW_MANAGER,       0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SEARCH_ENGINE,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CHOSE_SEARCH_ENGINE,     0, 0, 0, MENU_WWW_SEARCH_ENGINE_SEL},    
    {ID_WWW_SUBMENU_SAVED_PAGE,         TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_MEMO,              0, 0, 0, MENU_NULL},    
    {ID_WWW_DOWNLOAD_MANAGE,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DOWNLOAD_MANAGE,         0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SETTING,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SETTING,                 0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_CLEAN_INPUT_HISTORY,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CLEAN_INPUT_HISTORY,     0, 0, 0, MENU_NULL},
    {ID_WWW_MINIMIZE,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MINIMIZE,            0, 0, 0, MENU_NULL},
    {ID_WWW_EXIT,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BROWSER_EXIT,            0, 0, 0, MENU_NULL},
};

//set child menu
const GUIMENU_ITEM_T menu_www_engine_selection[] =
{
    {ID_WWW_ENGINE_CMCC,   TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CMCC_SEARCH,   0, 0, 0, MENU_NULL},
    {ID_WWW_ENGINE_BAIDU,   TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MAINMENU_ICON_BAIDU,   0, 0, 0, MENU_NULL},
#ifdef MMIWWW_ENGINE_CUSTOMIZED
    {ID_WWW_ENGINE_GOOGLE,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_GOOGLE,  0, 0, 0, MENU_NULL},
    {ID_WWW_ENGINE_YAHOO,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_YAHOO,   0, 0, 0, MENU_NULL},
#endif
};

//bookmark otp when web is open
const GUIMENU_ITEM_T menu_www_bookmark_opt1[] =
{
    {ID_WWW_HOMPAGE,                    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_OPEN_HOMEPAGE,     0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_ADD,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_ADD,            0, 0, 0, MENU_WWW_BOOKMARK_ADD_SUB},
    {ID_WWW_BOOKMARK_SUBMENU_EDIT,          TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_EDIT,           0, 0, 0, MENU_NULL},
    //{ID_WWW_BOOKMARK_SUBMENU_MOVE_UP,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_MOVE_UP,                         0, 0, 0, MENU_NULL},
    //{ID_WWW_BOOKMARK_SUBMENU_MOVE_DOWN,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_MOVE_DOWN,                       0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_DELETE,        TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_DELETE,         0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_DELETE_ALL,    TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_DELETE_ALL,     0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_MOVE_TO,        TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_MANAGE_MOVE_TO,         0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_PROPERTY,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_PROPERTY,       0, 0, 0, MENU_NULL},
    {ID_WWW_OPT_SEND_LINK,                  TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SEND_LINK,                       0, 0, 0, MENU_WWW_SEND_OPT},
    {ID_WWW_SUBMENU_SAVED_PAGE,             TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_MEMO,                      0, 0, 0, MENU_NULL},    
    {ID_WWW_DOWNLOAD_MANAGE,                TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DOWNLOAD_MANAGE,                 0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SETTING,                TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SETTING,                         0, 0, 0, MENU_NULL},
    {ID_WWW_MINIMIZE,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MINIMIZE,            0, 0, 0, MENU_NULL},
    {ID_WWW_EXIT,                           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BROWSER_EXIT,                    0, 0, 0, MENU_NULL},
};

//bookmark otp when web is Not open
const GUIMENU_ITEM_T menu_www_bookmark_opt2[] =
{
    {ID_WWW_HOMPAGE,                        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_OPEN_HOMEPAGE,     0, 0, 0, MENU_NULL},
    {ID_WWW_WINDOW_MANAGER,             TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_WINDOW_MANAGER,       0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_ADD,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_ADD,            0, 0, 0, MENU_WWW_BOOKMARK_ADD_SUB},
    {ID_WWW_BOOKMARK_SUBMENU_EDIT,          TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_EDIT,           0, 0, 0, MENU_NULL},
    //{ID_WWW_BOOKMARK_SUBMENU_MOVE_UP,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_MOVE_UP,                         0, 0, 0, MENU_NULL},
    //{ID_WWW_BOOKMARK_SUBMENU_MOVE_DOWN,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_MOVE_DOWN,                       0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_DELETE,        TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_DELETE,         0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_DELETE_ALL,    TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_DELETE_ALL,     0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_MOVE_TO,        TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_MANAGE_MOVE_TO,         0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_PROPERTY,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_PROPERTY,       0, 0, 0, MENU_NULL},
    {ID_WWW_OPT_SEND_LINK,                  TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SEND_LINK,                       0, 0, 0, MENU_WWW_SEND_OPT},
    {ID_WWW_SUBMENU_SAVED_PAGE,             TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_MEMO,                      0, 0, 0, MENU_NULL},    
    {ID_WWW_DOWNLOAD_MANAGE,                TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DOWNLOAD_MANAGE,                 0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SETTING,                TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SETTING,                         0, 0, 0, MENU_NULL},
    {ID_WWW_MINIMIZE,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MINIMIZE,            0, 0, 0, MENU_NULL},
    {ID_WWW_EXIT,                           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BROWSER_EXIT,                    0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_www_bookmark_add_sub[] =
{
    {ID_WWW_BOOKMARK_SUBMENU_ADD_FILE,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_BOOKMARKS,         0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_ADD_FOLDER,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_ADD_DIR,         0, 0, 0, MENU_NULL},
};

// sub menu of bookmark detail
const GUIMENU_ITEM_T menu_www_bookmark_detail_submenu[] =
{
    {ID_WWW_BOOKMARK_SUBMENU_DETAIL_EDIT,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_EDIT,         0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK_SUBMENU_DETAIL_DELETE,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK_SUBMENU_DELETE,       0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_www_setopt[] =
{
    {ID_WWW_SETMENU_VIEWMODE,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SET_VIEW,         IMAGE_WWW_VIEW_MODE, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_DISPALAYOPT,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DISPLAY_OPT,         IMAGE_WWW_DISPLAY, 0, 0, /*MENU_WWW_DISPLAY_SET*/MENU_NULL},
#ifdef MMIWWW_SETTINGS_USE_FONT
    {ID_WWW_SETMENU_SETFONT,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_FONT_SIZE,         IMAGE_WWW_SET_FONT, 0, 0, MENU_NULL},
#endif
    {ID_WWW_SETMENU_SETCOOKIE,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COOKIE,         IMAGE_WWW_COOKIE, 0, 0, /*MENU_WWW_COOKIE_OPT*/MENU_NULL},
    {ID_WWW_SETMENU_SETCACHE,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SET_CACHE,         IMAGE_WWW_SET_CACHE, 0, 0, /*MENU_WWW_CACHE_OPT*/MENU_NULL},
    {ID_WWW_SETMENU_CERTIFICATE,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CERTIFICATE,         IMAGE_WWW_CERT, 0, 0, MENU_NULL},
#ifdef MMIWWW_SETTINGS_USE_WEBDATA
    {ID_WWW_SETMENU_WEBDATA,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_WEBDATA,         IMAGE_WWW_SET_WEBDATA, 0, 0, /*MENU_WWW_WEBDATA_OPT*/MENU_NULL},
#endif
#ifndef MMI_MULTI_SIM_SYS_SINGLE
    {ID_WWW_SETMENU_ACCOUNT1,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_ACCOUNT1,         IMAGE_WWW_ACCOUNT1, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_ACCOUNT2,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_ACCOUNT2,         IMAGE_WWW_ACCOUNT2, 0, 0, MENU_NULL},
#else
    {ID_WWW_SETMENU_ACCOUNT,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_ACCOUNT,         IMAGE_WWW_ACCOUNT, 0, 0, MENU_NULL},
#endif
    {ID_WWW_SETMENU_CHARSET,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CHARSET,           IMAGE_WWW_SET_FONT, 0, 0, MENU_NULL},
#ifndef CMCC_UI_STYLE
    {ID_WWW_SETMENU_HOMEPAGE,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_HOMEPAGE_SETTING,           IMAGE_WWW_SET_HOMEPAGE, 0, 0, MENU_NULL},
#endif
#ifndef DPHONE_SUPPORT 
    {ID_WWW_SETMENU_POINTER_MODE,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_POINTER_MODE,           IMAGE_WWW_POINTER_MODE, 0, 0, MENU_NULL},
#endif
    {ID_WWW_SETMENU_DEFAULTSET,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DEFAULT_SET,         IMAGE_WWW_RESET, 0, 0, MENU_NULL},
};

/*const GUIMENU_ITEM_T menu_www_webdataopt[] =
{
    {ID_WWW_SETMENU_AUTOWEBDATA,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_AUTO,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_CLEARWEBDATA,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CLEAR_WEBDATA,         0, 0, 0, MENU_NULL},
};*/

/*const GUIMENU_ITEM_T menu_www_displayset[] =
{
    {ID_WWW_SETMENU_SCRIPT,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SCRIPT,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_ANIMATION,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMM_ANIMATION,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_PHOTO,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PHOTO,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_TABLE,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_TABLE,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_BGMUSIC,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BGMUSIC,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_POPUPWIN,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_POPUPWIN,         0, 0, 0, MENU_NULL},
};*/    

const GUIMENU_ITEM_T menu_www_displayopt[] =
{
    {ID_WWW_SETMENU_OPT_DISPLAY,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DISPLAY,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_OPT_NODISPLAY,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_NODISPLAY,         0, 0, 0, MENU_NULL},
};

/*const GUIMENU_ITEM_T menu_www_cookieopt[] =
{
    {ID_WWW_SETMENU_COOKIEMODE,        TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_COOKIE_MODE,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_CLEARCOOKIE,        TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CLEAR_COOKIE,         0, 0, 0, MENU_NULL},
};*/

/*const GUIMENU_ITEM_T menu_www_cacheopt[] = 
{
    {ID_WWW_SETMENU_CACHEMODE,        TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CACHE_MODE,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_IF_USE_DISK_CACHE,        TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_IF_USE_DISK_CACHE,         0, 0, 0, MENU_NULL},
    {ID_WWW_SETMENU_CLEAR_CACHE,        TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CLEAR_CACHE,         IMAGE_WWW_CLEAR_CACHE, 0, 0, MENU_NULL},
};*/

//history otp when web is open
const GUIMENU_ITEM_T menu_www_history_opt1[] =
{
    {ID_WWW_HOMPAGE,                    TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_OPEN_HOMEPAGE,     0, 0, 0, MENU_NULL},
    {ID_WWW_DELETE_OPT_DELETE_CUR,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DELETE_CUR,      0, 0, 0, MENU_NULL},
    {ID_WWW_DELETE_OPT_DELETE_CURDAY,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DELETE_CURDAY,      0, 0, 0, MENU_NULL},
    {ID_WWW_DELETE_OPT_DELETE_ALL,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DELETE_ALL,      0, 0, 0, MENU_NULL},
    {ID_WWW_OPT_SHOW_ADDRESS,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SHOW_ADDRESS,    0, 0, 0, MENU_NULL},
    {ID_WWW_OPT_SEND_LINK,              TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SEND_LINK,       0, 0, 0, MENU_WWW_SEND_OPT},
    {ID_WWW_SUBMENU_SAVED_PAGE,         TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_MEMO,      0, 0, 0, MENU_NULL},    
    {ID_WWW_DOWNLOAD_MANAGE,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DOWNLOAD_MANAGE, 0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SETTING,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SETTING,         0, 0, 0, MENU_NULL},
    {ID_WWW_MINIMIZE,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MINIMIZE,            0, 0, 0, MENU_NULL},
    {ID_WWW_EXIT,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BROWSER_EXIT,    0, 0, 0, MENU_NULL},
};

//history otp when web is Not open
const GUIMENU_ITEM_T menu_www_history_opt2[] =
{
    {ID_WWW_HOMPAGE,                    TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_OPEN_HOMEPAGE,     0, 0, 0, MENU_NULL},
    {ID_WWW_WINDOW_MANAGER,             TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_WINDOW_MANAGER,       0, 0, 0, MENU_NULL},
    {ID_WWW_DELETE_OPT_DELETE_CUR,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DELETE_CUR,      0, 0, 0, MENU_NULL},
    {ID_WWW_DELETE_OPT_DELETE_CURDAY,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DELETE_CURDAY,      0, 0, 0, MENU_NULL},
    {ID_WWW_DELETE_OPT_DELETE_ALL,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DELETE_ALL,      0, 0, 0, MENU_NULL},
    {ID_WWW_OPT_SHOW_ADDRESS,           TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SHOW_ADDRESS,    0, 0, 0, MENU_NULL},
    {ID_WWW_OPT_SEND_LINK,              TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SEND_LINK,       0, 0, 0, MENU_WWW_SEND_OPT},
    {ID_WWW_SUBMENU_SAVED_PAGE,         TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_MEMO,      0, 0, 0, MENU_NULL},    
    {ID_WWW_DOWNLOAD_MANAGE,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DOWNLOAD_MANAGE, 0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SETTING,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SETTING,         0, 0, 0, MENU_NULL},
    {ID_WWW_MINIMIZE,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MINIMIZE,            0, 0, 0, MENU_NULL},
    {ID_WWW_EXIT,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BROWSER_EXIT,    0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_www_pagememo_opt[] =
{
#ifdef MMIWWW_PAGEMEMO_USE_SORT
    {ID_WWW_OPT_SORT,                   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SORT,         0, 0, 0, MENU_WWW_SORT_OPT},
#endif
    {ID_WWW_DELETE_OPT_DELETE_CUR,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DELETE_CUR,      0, 0, 0, MENU_NULL},
    {ID_WWW_DELETE_OPT_DELETE_ALL,      TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DELETE_ALL,      0, 0, 0, MENU_NULL},
    {ID_WWW_OPT_SEND_LINK,              TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SEND_LINK,         0, 0, 0, MENU_WWW_SEND_OPT},
    {ID_WWW_OPT_SHOW_ADDRESS,           TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SHOW_ADDRESS,         0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_www_sort_opt[] =
{
    {ID_WWW_OPT_SORT_BY_DATE,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_DATE,         0, 0, 0, MENU_NULL},
    {ID_WWW_OPT_SORT_BY_NAME,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_NAME,         0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_www_send_opt[] =
{
    {ID_WWW_SEND_OPT_VIA_SMS,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_VIA_SMS,         0, 0, 0, MENU_NULL},
    {ID_WWW_SEND_OPT_VIA_MMS,        TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_VIA_MMS,         0, 0, 0, MENU_NULL},
};

//set www page option menu 
const GUIMENU_ITEM_T menu_www_page_option[] =
{
    {ID_WWW_PAGE_OPEN,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMM_OPEN,    0, 0, 0, MENU_WWW_PAGE_OPEN},
    {ID_WWW_PAGE_PILOT,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_PILOT,      0, 0, 0, MENU_WWW_PAGE_PILOT},
    {ID_WWW_PAGE_TOOL,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MAINMENU_ICON_TOOLS, 0, 0, 0, MENU_WWW_PAGE_TOOL},
    {ID_WWW_PAGE_WINDOW,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_WINDOW,          0, 0, 0, MENU_WWW_PAGE_WINDOW},
    {ID_WWW_PAGE_ZOOM,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_ZOOM,       0, 0, 0, MENU_WWW_PAGE_ZOOM},
    {ID_WWW_PAGE_SAVE,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},STXT_SAVE,   0, 0, 0, MENU_WWW_PAGE_SAVE},
    {ID_WWW_PAGE_MEMO,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_MEMO,       0, 0, 0, MENU_NULL},
    {ID_WWW_DOWNLOAD_MANAGE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DOWNLOAD_MANAGE, 0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SETTING, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},STXT_MAIN_SETTING,       0, 0, 0, MENU_NULL},
    {ID_WWW_MINIMIZE,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MINIMIZE,            0, 0, 0, MENU_NULL},
    {ID_WWW_EXIT,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BROWSER_EXIT,    0, 0, 0, MENU_NULL}
};

//set www page option menu 
const GUIMENU_ITEM_T menu_www_page_full_option[] =
{
    {ID_WWW_PAGE_OPEN,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMM_OPEN,    0, 0, 0, MENU_WWW_PAGE_OPEN},
    {ID_WWW_PAGE_PILOT,      TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_PILOT,      0, 0, 0, MENU_WWW_PAGE_FULL_PILOT},
    {ID_WWW_PAGE_TOOL,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MAINMENU_ICON_TOOLS, 0, 0, 0, MENU_WWW_PAGE_TOOL},
    {ID_WWW_PAGE_WINDOW,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_WINDOW,          0, 0, 0, MENU_WWW_PAGE_WINDOW},
    {ID_WWW_PAGE_ZOOM,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_ZOOM,       0, 0, 0, MENU_WWW_PAGE_ZOOM},
    {ID_WWW_PAGE_SAVE,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},STXT_SAVE,   0, 0, 0, MENU_WWW_PAGE_SAVE},
    {ID_WWW_PAGE_MEMO,       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_MEMO,       0, 0, 0, MENU_NULL},
    {ID_WWW_DOWNLOAD_MANAGE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_DOWNLOAD_MANAGE,         0, 0, 0, MENU_NULL},
    {ID_WWW_SUBMENU_SETTING, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},STXT_MAIN_SETTING,       0, 0, 0, MENU_NULL},
    {ID_WWW_MINIMIZE,                       TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_MINIMIZE,            0, 0, 0, MENU_NULL},
    {ID_WWW_EXIT,            TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BROWSER_EXIT,    0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_www_page_open[] =
{
    {ID_WWW_HOMPAGE,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_HOMEPAGE,     0, 0, 0, MENU_NULL},
    {ID_WWW_OPEN_URL, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_URL_ADRESS, 0, 0, 0, MENU_NULL},
    {ID_WWW_SEARCH,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},STXT_SEARCH,           0, 0, 0, MENU_NULL},
    {ID_WWW_BOOKMARK, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_BOOKMARK,         0, 0, 0, MENU_NULL},
    {ID_WWW_HISTORY,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_HISTORY,          0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_www_page_pilot[] =
{
    {ID_WWW_PAGE_REFRESH,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SUBMENU_REFRESH,   0, 0, 0, MENU_NULL},
    {ID_WWW_PAGE_FORWARD,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_FORWARD,      0, 0, 0, MENU_NULL},
    {ID_WWW_PAGE_BACK,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_BACK,         0, 0, 0, MENU_NULL},
    {ID_WWW_FULL_DISPLAY,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_FULL_DISPLAY, 0, 0, 0, MENU_NULL},
#ifndef MOTION_SENSOR_TYPE
    {ID_WWW_HORIZONTAL_DISPLAY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_HORIZONTAL_DISPLAY, 0, 0, 0, MENU_NULL}
#endif /* MOTION_SENSOR_TYPE */
    //{ID_WWW_PAGE_NAVIGATION, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_NAVIGATION,   0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_www_page_full_pilot[] =
{
    {ID_WWW_PAGE_REFRESH,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SUBMENU_REFRESH,   0, 0, 0, MENU_NULL},
    {ID_WWW_PAGE_FORWARD,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_FORWARD,      0, 0, 0, MENU_NULL},
    {ID_WWW_PAGE_BACK,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_BACK,         0, 0, 0, MENU_NULL},
    {ID_WWW_FULL_DISPLAY,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_EXIT_FULL_DISPLAY, 0, 0, 0, MENU_NULL},
#ifndef MOTION_SENSOR_TYPE
    {ID_WWW_HORIZONTAL_DISPLAY, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_HORIZONTAL_DISPLAY, 0, 0, 0, MENU_NULL}
#endif /* MOTION_SENSOR_TYPE */
    //{ID_WWW_PAGE_NAVIGATION, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_NAVIGATION,   0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_www_page_tool[] =
{
    {ID_WWW_PAGE_SEARCH,     TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMM_SEARCH,     0, 0, 0, MENU_NULL},
#ifdef TOUCH_PANEL_SUPPORT
    {ID_WWW_PAGE_COPY,     TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_COPY,     0, 0, 0, MENU_NULL},
#endif /* TOUCH_PANEL_SUPPORT */
    {ID_WWW_PAGE_PROPERTY,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_PROPERTY,   0, 0, 0, MENU_NULL},
//    {ID_WWW_DOWNLOAD_MANAGE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_DOWNLOAD_MANAGE, 0, 0, 0, MENU_NULL},
    {ID_WWW_MESSAGE, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMMUNICATION_MESSAGE, 0, 0, 0, MENU_NULL},
    {ID_WWW_CALL, TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMM_CALL, 0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_www_page_window[] =
{
    {ID_WWW_NEW_WINDOW,    TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_NEW_WINDOW,    0, 0, 0, MENU_NULL},
    {ID_WWW_WINDOW_MANAGER,TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_WINDOW_MANAGER,       0, 0, 0, MENU_NULL},
    {ID_WWW_CLOSE_WINDOW,  TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CLOSE_WINDOW,  0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_www_page_zoom[] =
{
    {ID_WWW_PAGE_ZOOM_PERCENT_50,   TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMM_50PERCENT,    0, 0, 0, MENU_NULL},
    {ID_WWW_PAGE_ZOOM_PERCENT_75,   TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMM_75PERCENT,    0, 0, 0, MENU_NULL},
    {ID_WWW_PAGE_ZOOM_PERCENT_100,  TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_COMM_100PERCENT,   0, 0, 0, MENU_NULL},
    {ID_WWW_PAGE_ZOOM_PERCENT_125,  TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_ZOOM_PERCENT_125,   0, 0, 0, MENU_NULL},
    {ID_WWW_PAGE_ZOOM_PERCENT_150,  TIP_NULL, {STXT_OK, TXT_NULL, STXT_RETURN},TXT_WWW_PAGE_ZOOM_PERCENT_150,   0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_www_page_save[] =
{
#ifndef CMCC_UI_STYLE
    {ID_WWW_AS_HOMEPAGE,   TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_AS_HOMEPAGE,         0, 0, 0, MENU_NULL},
#endif
    {ID_WWW_SAVE_BOOKMARK, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_SAVE_BOOKMARK, 0, 0, 0, MENU_NULL},
    {ID_WWW_WEBPAGE,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_WEBPAGE,       0, 0, 0, MENU_NULL},
    {ID_WWW_SAVE_AS,         TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_COMMON_PIC,         0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_www_window_manager[] =
{
    {ID_WWW_NEW_SUB_WIN, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_NEW_SUB_WIN, 0, 0, 0, MENU_NULL},
    {ID_WWW_CLOSE_SUB_WIN,       TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},TXT_WWW_CLOSE_SUB_WIN,       0, 0, 0, MENU_NULL},
};

#define MENU_DEF(_TABLEID, _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, \
     _ITEMCOUNT) \
     _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, _ITEMCOUNT, 

const GUIMENU_GROUP_T mmiwww_menu_table[] = 
{
    {NULL},
    #include "mmiwww_menutab.def"
};

#undef MENU_DEF

/*****************************************************************************/
// 	Description : Register WWW menu group
//	Global resource dependence : none
//  Author: bruce.chi
//	Note:
/*****************************************************************************/
PUBLIC void MMIWWW_RegMenuGroup(void)
{
    MMI_RegMenuGroup(MMI_MODULE_WWW, mmiwww_menu_table);
}
#endif //#ifdef BROWSER_SUPPORT_NETFRONT
