/*****************************************************************************
** File Name:      mmisms_menutable.h                                        *
** Author:         Tracy Zhang                                               *
** Date:           2006/10/19                                                *
** Copyright:      2006 Spreadtrum, Incorporated. All Rights Reserved.       *
** Description:    This file is used to describe sms menu id                 *
******************************************************************************
**                         Important Edit History                            *
** --------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                               *
** 2006/10/19     Tracy Zhang        Create                                  *
******************************************************************************/

#ifndef _MMISMS_MENUTABLE_H_
#define _MMISMS_MENUTABLE_H_

#include "mmi_module.h"

/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif

/*-------------------------------------------------------------------------*/
/*                         TYPES/CONSTANTS                                 */
/*-------------------------------------------------------------------------*/
//Menu ID
typedef enum
{
    MMISMS_MENU_MENU_START = (MMI_MODULE_SMS << 16),
    
    // SMS main menu id
    MMISMS_MENU_WRITE_ID_ITEM_ID,
    MMISMS_MENU_OUTBOX_ID_ITEM_ID,
    MMISMS_MENU_INBOX_ID_ITEM_ID,
    MMISMS_MENU_SENTBOX_ID_ITEM_ID,
    MMISMS_MENU_DRAFTBOX_ID_ITEM_ID,
    MMISMS_MENU_FREQWORD_ID_ITEM_ID,
#if defined(MMI_SMSCB_SUPPORT)
    MMISMS_MENU_BROADCAST_ID,             //小区广播菜单项ID号
#endif
    MMISMS_MENU_VOICEMAIL,                //语音信箱
    MMISMS_MENU_SETTING_ID_ITEM_ID,
    MMISMS_MENU_DELALL_MSG_ITEM_ID,
    MMISMS_MENU_MEMSTATE_ID_ITEM_ID,
    MMISMS_MENU_MMSSEARCH_ID_ITEM_ID,
    MMISMS_MENU_SMS_SETTING_ID_ITEM_ID,
    MMISMS_MENU_MMS_SETTING_ID_ITEM_ID,
    MMISMS_MENU_BROWSER_SETTING_ID_ITEM_ID,
    MMISMS_MENU_BROADCAST_SETTING_ITEM_ID,
    MMISMS_MENU_FONT_SIZE_SETTING_ITEM_ID,

    MMISMS_MENU_WRITE_ITEM_ID,
    MMISMS_MENU_MTBOX_ITEM_ID,
    MMISMS_MENU_MOBOX_ITEM_ID,
    MMISMS_MENU_DELBOX_ITEM_ID,
    MMISMS_MENU_CB_ITEM_ID,
    MMISMS_MENU_VOICEMAIL_ITEM_ID,
    MMISMS_MENU_SETTING_ITEM_ID,
    MMISMS_MENU_SPACE_ITEM_ID,
    
    MMISMS_MENU_NEW_SMS_ITEM_ID,
    MMISMS_MENU_NEW_MMS_ITEM_ID,
#ifdef 	MMIMMS_SMS_IN_1_SUPPORT
    MMISMS_MENU_NEW_MESSAGE_ITEM_ID,
    MMISMS_MENU_INSERT_ELEMENT,
    MMISMS_MENU_INSERT_SUBJECT,
    MMISMS_MENU_INSERT_PIC,
    MMISMS_MENU_INSERT_TXT,
    MMISMS_MENU_INSERT_AUDIO,
    MMISMS_MENU_INSERT_VIDEO,
    MMISMS_MENU_INSERT_NEXTPAGE,
    MMISMS_MENU_INSERT_PREPAGE,

    MMISMS_MENU_INSERT_TAKE_PIC,
    MMISMS_MENU_INSERT_TAKE_AUDIO,
    MMISMS_MENU_INSERT_TAKE_VIDEO,

    MMISMS_MENU_INSERT_ATTACH,
    MMISMS_MENU_INSERT_ATTACH_VCARD,
    MMISMS_MENU_INSERT_ATTACH_OTHER,
    MMISMS_MENU_INSERT_PHIZ,
    MMISMS_MENU_INSERT_EMOJI,
    MMISMS_MENU_INSERT_CONTACT_INFO,
#endif
    MMISMS_MENU_DELBOX_MT_ITEM_ID,
    MMISMS_MENU_DELBOX_MO_ITEM_ID,
    MMISMS_MENU_DELBOX_ALL_ITEM_ID,
    //delete same num in MT BOX
    MMISMS_MENU_DELBOX_SAMENUM_ITEM_ID,

    MMISMS_MENU_WRITE_OPT_ITEM_ID,

    MMISMS_MENU_SIM1_SEND_ITEM_ID,
    MMISMS_MENU_SIM2_SEND_ITEM_ID,

#ifdef MMI_SMS_SYN_SUPPORT
    MMISMS_MENU_BT_SEND_ITEM_ID,
#else
#if defined(BT_DIALER_SUPPORT) && defined(BT_MAP_SUPPORT)
    MMISMS_MENU_BT_SEND_ITEM_ID,
#endif
#endif

    MMISMS_MENU_SAVE_ITEM_ID,
    MMISMS_MENU_SAVE_AS_DRAFT_ITEM_ID,
    MMISMS_MENU_SAVE_SEND_ITEM_ID,
    MMISMS_MENU_ADD_PHIZ_ITEM_ID,
    MMISMS_MENU_ADD_EMOJI_ITEM_ID,
#if defined(IM_ENGINE_SOGOU) && defined(IM_SIMP_CHINESE_SUPPORT)
	MMISMS_MENU_INPUTMETHOD_SETTING_ITEM_ID,
#endif
    MMISMS_MENU_OPT_FREQWORD_ITEM_ID,
    MMISMS_MENU_ADD_CONTACTINFO_ITEM_ID,
#ifdef DPHONE_SUPPORT 
    MMISMS_MENU_OPEN_ITEM_ID,
#endif  
//    MMISMS_MENU_OPEN_ITEM_ID,
    MMISMS_MENU_ANSWER_ITEM_ID,
    MMISMS_MENU_ANSWER_MMS_ITEM_ID,
    MMISMS_MENU_DEL_ITEM_ID,
#ifdef SNS_SUPPORT
    MMISMS_MENU_SHARE_TO_SINA_ID,
    MMISMS_MENU_SHARE_TO_FACEBOOK_ID,
    MMISMS_MENU_SHARE_TO_TIWTTER_ID,
#endif
    MMISMS_MENU_DETAIL_ITEM_ID,
    MMISMS_MENU_FORWARD_ITEM_ID,
#ifdef DPHONE_SUPPORT 
    MMISMS_MENU_USE_NUM_ITEM_ID,
#endif
    MMISMS_MENU_AUDIOCALL_ITEM_ID,
    MMISMS_MENU_VIDEOCALL_ITEM_ID,
    MMISMS_MENU_CALL_ITEM_ID,
    MMISMS_MENU_EDIT_ITEM_ID,
    MMISMS_MENU_RESEND_ITEM_ID,
    MMISMS_MENU_LOCK_ITEM_ID,
    MMISMS_MENU_UNLOCK_ITEM_ID,
    MMISMS_MENU_MOVE_ITEM_ID,
    MMISMS_MENU_COPY_ITEM_ID,
    MMISMS_MENU_MARK_ITEM_ID,
    MMISMS_MENU_OPT_MARK_ITEM_ID,
    MMISMS_MENU_SORT_ITEM_ID,
    MMISMS_MENU_ANSWER_SMS_ITEM_ID,
    MMISMS_MENU_DIAL_ITEM_ID,
#ifdef BT_DIALER_SUPPORT
    MMISMS_MENU_SIM_DIAL_ITEM_ID,
    MMISMS_MENU_BT_DIAL_ITEM_ID,
#endif
    MMISMS_MENU_IPDIAL_ITEM_ID,
    MMISMS_MENU_CANCEL_MARK_ITEM_ID,
    MMISMS_MENU_MARKALL_ITEM_ID,
    MMISMS_MENU_CANCLE_MARKALL_ITEM_ID,
    MMISMS_MENU_TIME_SORT_ITEM_ID,
    MMISMS_MENU_NAME_SORT_ITEM_ID,
    MMISMS_MENU_SUBJECT_SORT_ITEM_ID,
    MMISMS_MENU_TYPE_SORT_ITEM_ID,
    MMISMS_MENU_MARK_NUM_ITEM_ID,
    MMISMS_MENU_CANCEL_MARK_NUM_ITEM_ID,
#ifndef MMI_MULTI_SIM_SYS_SINGLE
    MMISMS_MENU_SETTING_SIM1_SC_ITEM_ID,
    MMISMS_MENU_SETTING_SIM2_SC_ITEM_ID,
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
    MMISMS_MENU_SETTING_SIM3_SC_ITEM_ID,
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
    MMISMS_MENU_SETTING_SIM4_SC_ITEM_ID,
#endif
    MMISMS_MENU_MARK_SIM1_SMS_ITEM_ID,
    MMISMS_MENU_MARK_SIM2_SMS_ITEM_ID,
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
    MMISMS_MENU_MARK_SIM3_SMS_ITEM_ID,
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
    MMISMS_MENU_MARK_SIM4_SMS_ITEM_ID,
#endif
    MMISMS_SIM_SELECT1,
    MMISMS_SIM_SELECT2,
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
    MMISMS_SIM_SELECT3,
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
    MMISMS_SIM_SELECT4,
#endif
#else
    MMISMS_MENU_MARK_SIM_SMS_ITEM_ID,
    MMISMS_MENU_SETTING_SC_ITEM_ID,
#endif

#ifndef MMI_MULTI_SIM_SYS_SINGLE
    MMISMS_MENU_SETTING_SIM1_PARAM_ITEM_ID,
    MMISMS_MENU_SETTING_SIM2_PARAM_ITEM_ID,
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
    MMISMS_MENU_SETTING_SIM3_PARAM_ITEM_ID,
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
    MMISMS_MENU_SETTING_SIM4_PARAM_ITEM_ID,
#endif
#else
    MMISMS_MENU_SETTING_PARAM_ITEM_ID,
#endif

    MMISMS_MENU_SETTING_PARAM_EDIT_ID,

#ifdef TTS_SUPPORT
    MMISMS_MENU_SETTING_TTS_ITEM_ID,
    MMISMS_MENU_SETTING_TTS_OPEN_CLOSE_ID,
    MMISMS_MENU_SETTING_TTS_VOL_ID,
    MMISMS_MENU_TTS_READ_ID,
#endif

    MMISMS_MENU_SETTING_VP_ITEM_ID,
    MMISMS_MENU_SETTING_SAVE_POS_ITEM_ID,
    MMISMS_MENU_SETTING_STATUS_ITEM_ID,
    MMISMS_MENU_SETTING_CONCATENATED_SMS_ID,
    MMISMS_MENU_SETTING_ALPHABET_MANAGEMENT_ID,
    MMISMS_MENU_SETTING_STATUS_REPORT_ITEM_ID,
    MMISMS_MENU_SETTING_REPLY_PATH_ITEM_ID,
    MMISMS_MENU_SETTING_SR_ITEM_ID,
    MMISMS_MENU_SETTING_PERFERRED_CONNECTION_ITEM_ID,
    MMISMS_MENU_SETTING_SIM_MODENAME_ITEM_ID,
    MMISMS_MENU_SETTING_SIM_SENDTYPE_ITEM_ID,
    MMISMS_MENU_SETTING_SIM_SC_ITEM_ID,
    MMISMS_MENU_NUM_DEL_ITEM_ID,
    MMISMS_MENU_NUM_EDIT_ITEM_ID,
    MMISMS_MENU_VM_CALLVM_ITEM_ID,
    MMISMS_MENU_VM_SETVM_ITEM_ID,
    MMISMS_MENU_CB_ENABLE_ITEM_ID,
    MMISMS_MENU_CB_CHANNEL_ITEM_ID,
    MMISMS_MENU_CB_LANGUAGE_ITEM_ID,
    MMISMS_MENU_CBCHANNEL_ADD_ITEM_ID,
    MMISMS_MENU_CBCHANNEL_LIST_ITEM_ID,
    MMISMS_MENU_EXTRACT_SEND_SMS_ITEM_ID,
    MMISMS_MENU_EXTRACT_SEND_MMS_ITEM_ID,
#ifdef MMIEMAIL_SUPPORT
	MMISMS_MENU_EXTRACT_SEND_EMAIL_ITEM_ID,
#endif
    MMISMS_MENU_EXTRACT_ADDTOPB_ITEM_ID,
    MMISMS_MENU_ADDNUMTOPB_ITEM_ID,
    MMISMS_MENU_EXACT_URL_BROWSE_ITEM_ID,
    MMISMS_MENU_EXTRACT_URL_ADDTOBOOKBARK_ITEM_ID,
    MMISMS_MENU_EXTRACT_ITEM_ID,
    MMISMS_MENU_SET_EXTRACT_ITEM_ID,
    MMISMS_MENU_CANCEL_EXTRACT_ITEM_ID,
    MMISMS_MENU_EXTRACT_ADDTOPB_NEW_ITEM_ID,
    MMISMS_MENU_EXTRACT_ADDTOPB_EXIST_ITEM_ID,
#if defined(MMI_BLACKLIST_SUPPORT)
    MMISMS_MENU_EXTRACT_ADDTO_BLACKLIST_ITEM_ID,
#endif
   // MMISMS_MENU_IPCALL_ITEM_ID,   
    // SMSCB main menu id
    MMISMS_MENUCB_READ_ITEM_ID,                //阅读小区广播菜单项ID号
    MMISMS_MENUCB_STARTUP_ITEM_ID,            //启动小区广播菜单项ID号
    MMISMS_MENUCB_CHANNEL_ITEM_ID,            //设置小区广播信道菜单项ID号
    MMISMS_MENUCB_LANGUAGE_ITEM_ID,            //设置小区广播语言菜单项ID号

    MMISMS_MENUCB_CHANNEL_ADD_ITEM_ID,        //添加小区广播信道菜单项ID号
    MMISMS_MENUCB_CHANNEL_LIST_ITEM_ID,        //小区广播信道列表菜单项ID号

    MMISMS_MENUCB_CHANNEL_SWITCH_ITEM_ID,    //开关小区广播信道菜单项ID号
    MMISMS_MENUCB_CHANNEL_EDIT_ITEM_ID,        //编辑小区广播信道菜单项ID号
    MMISMS_MENUCB_CHANNEL_DELETE_ITEM_ID,    //删除小区广播信道菜单项ID号
    MMISMS_MENUCB_CHANNEL_CHECK_ITEM_ID,        //查看小区广播信道菜单项ID号

#ifdef MMI_ETWS_SUPPORT
    MMISMS_MENUCB_DIAL_ITEM_ID,
    MMISMS_MENUCB_ANSWER_SMS_ITEM_ID,
#endif

#ifdef MMI_CSP_SUPPORT
    MMISMS_MENU_LINE1_VMN_ITEM_ID,
    MMISMS_MENU_LINE2_VMN_ITEM_ID,
#endif
    MMISMS_MENU_LINE_VMN_ITEM_ID,
    MMISMS_MENU_FAX_VMN_ITEM_ID,
    MMISMS_MENU_DATA_VMN_ITEM_ID,

#ifdef SMS_EXTRACT_URLORST_SUPPORT   //No Use Menu
    MMISMS_MENU_EXTRACT_URL,
    MMISMS_MENU_EXTRACT_STADDR,
#endif    
    ID_SMS_CONNECT_URLORST,
    MMISMS_URL_OPEN_LINK_ITEM_ID,
    MMISMS_URL_SET_HOMEPAGE_ITEM_ID,
    MMISMS_URL_ADDTO_BOOKMARK_ITEM_ID,

#if defined (MMI_SMS_SECURITYBOX_SUPPORT)
    MMISMS_MENU_SECURITY_ID_ITEM_ID,
    MMISMS_MENU_BOX_SECURITY_ITEM_ID,
#endif
    MMISMS_MENU_BOX_PREVIEW_ITEM_ID,
    MMISMS_MENU_BOX_MOVETOSIM_ITEM_ID,
    MMISMS_MENU_BOX_MOVETOME_ITEM_ID,
    MMISMS_MENU_BOX_COPYTOSIM_ITEM_ID,
    MMISMS_MENU_BOX_COPYTOME_ITEM_ID,
    MMISMS_MENU_MODIFY_KEY_ITEM_ID,

    /* search result list opt menu ID */
    MMISMS_MENU_SEARCH_OPEN_ID,
#if defined(MMI_SMS_EXPORT_SUPPORT)
    MMISMS_MENU_EXPORT_ITEM_ID,
    MMISMS_MENU_SETTING_EXPORT_ITEM_ID,
#endif

#if defined(MMI_SMS_FONT_SETTING_SUPPORT)
    MMISMS_MENU_SET_FONT_ITEM_ID,
    MMISMS_MENU_BIG_FONT_ITEM_ID,
    MMISMS_MENU_NORMAL_FONT_ITEM_ID,
    MMISMS_MENU_SMALL_FONT_ITEM_ID,
#endif

    MMISMS_MENU_EXIT_ITEM_ID,

#ifdef PUSH_EMAIL_3_IN_1_SUPPORT//3 in 1 support
    MMISMS_MENU_MAIL_SETTING_ITEM_ID,
    MMISMS_MENU_NEW_MAIL_ITEM_ID,
    MMISMS_MENU_ANSWER_MAIL_ITEM_ID,    
#endif//PUSH_EMAIL_3_IN_1_SUPPORT
#ifdef MMI_SMS_CHAT_SUPPORT
    MMISMS_MENU_CHAT_ID_ITEM_ID,
    MMISMS_MENU_NEW_CHAT_ITEM_ID,
    MMISMS_MENU_CHAT_OPT_MARK_ITEM_ID,
    MMISMS_MENU_CHAT_CANCEL_MARK_ITEM_ID,
#endif    
#ifdef MMI_TIMERMSG_SUPPORT
    MMISMS_MENU_TIMER_MESSAGE_ITEM_ID,
    MMISMS_MENU_ON_ITEM_ID,
    MMISMS_MENU_OFF_ITEM_ID,
#endif	

#ifndef MMI_GUI_STYLE_TYPICAL
   MMISMS_MENU_BROADCAST_FOWARD_ITEM_ID,
   MMISMS_MENU_BROADCAST_DELETE_ITEM_ID,
#endif

#ifdef MMISMS_CHATMODE_ONLY_SUPPORT
    MMISMS_MENU_PUSH_MSG_ID_ITEM_ID,
    MMISMS_MENU_DEL_PUSH_ITEM_ID,
    MMISMS_MENU_PUSH_MSG_MARK_ID,
#endif

    MMISMS_MENU_MENU_MAX_ITEM_ID
}MMISMS_ID_MENU_E;


#define MENU_DEF(_TABLEID, _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, \
    _ITEMCOUNT) \
     _TABLEID,

typedef enum
{
    MMISMS_MENU_LABEL_START = (MMI_MODULE_SMS << 16),

    #include "mmisms_menutable.def"

    MMISMS_MENUTABLE_MAX
} MMISMS_MENU_LABEL_E;

#undef MENU_DEF


/*****************************************************************************/
//     Description : Register SMS menu group
//    Global resource dependence : none
//  Author: Tracy Zhang
//    Note:
/*****************************************************************************/
PUBLIC void MMISMS_RegMenuGroup(void);

/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif
/*-------------------------------------------------------------------------*/

#endif //_MMISMS_MENUTABLE_H_

