

//[[define image infomation
#ifdef MONOCHROME_LCD_SUPPORT 
#ifdef MMISMS_PORTRAIT_SUPPORT
RES_ADD_IMG(IMAGE_SMS_DRAFT_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_DRAFT_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
#endif
RES_ADD_IMG(IMAGE_SMS_SIM_SEND_FAIL_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_SEND_FAIL_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_SMS_SIM_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_READ_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_SMS_SIM_NOT_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_NOT_READ_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_SMS_SIM_DRAFT_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_DRAFT_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_SMS_SEND_SUCCESS_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SEND_SUCCESS_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_SMS_SEND_SIM_SUCCESS_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SEND_SIM_SUCCESS_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_SMS_SEND_FAIL_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SEND_FAIL_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_SMS_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_READ_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
RES_ADD_IMG(IMAGE_SMS_NOT_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_NOT_READ_SMS_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
//RES_ADD_IMG(IMAGE_SMS_MEMORY_STK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_MEMORY_STK_ICON.bmp",IMG_CMP_BMP_16_565_RAW,0)
#else
#ifdef MMISMS_PORTRAIT_SUPPORT
RES_ADD_IMG(IMAGE_SMS_DRAFT_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_DRAFT_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_SMS_SIM_SEND_FAIL_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_SEND_FAIL_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SIM_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_READ_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SIM_NOT_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_NOT_READ_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SIM_DRAFT_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_DRAFT_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SEND_SUCCESS_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SEND_SUCCESS_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SEND_SIM_SUCCESS_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SEND_SIM_SUCCESS_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SEND_FAIL_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SEND_FAIL_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_READ_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_NOT_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_NOT_READ_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SMS_MEMORY_STK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_MEMORY_STK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_SMS_MMS_NOTIFY_NEW_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_MMS_NOTIFY_NEW_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_MMSOTA_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_MMSOTA_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_MMSOTA_READED_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_MMSOTA_READED_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_NOT_READ_MMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_NOT_READ_MMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG(IMAGE_SMS_READ_SMS_MMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_READ_SMS_MMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_NOT_READ_SMS_MMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_NOT_READ_SMS_MMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_SMS_READ_MMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_READ_MMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_WAPOTA_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_WAPOTA_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_TITLE_ICON_FULL_MESSAGE,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_TITLE_ICON_FULL_MESSAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_WAPOTA_READED_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_WAPOTA_READED_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_WAPPUSH_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_WAPPUSH_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_WAPPUSH_READED_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_WAPPUSH_READED_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_DRAFT_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_DRAFT_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_SIM_DRAFT_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_SIM_DRAFT_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_MMS_NOTIFY_NEW_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_MMS_NOTIFY_NEW_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_MMSOTA_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_MMSOTA_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_MMSOTA_READED_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_MMSOTA_READED_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_NOT_READ_MMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_NOT_READ_MMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_NOT_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_NOT_READ_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_READ_MMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_READ_MMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_READ_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_SEND_FAIL_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_SEND_FAIL_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_SEND_SIM_SUCCESS_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_SEND_SIM_SUCCESS_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_SEND_SUCCESS_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_SEND_SUCCESS_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_SIM_NOT_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_SIM_NOT_READ_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_SIM_READ_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_SIM_READ_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_SIM_SEND_FAIL_SMS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_SIM_SEND_FAIL_SMS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_WAPOTA_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_WAPOTA_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_WAPOTA_READED_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_WAPOTA_READED_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_WAPPUSH_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_WAPPUSH_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_LOCK_WAPPUSH_READED_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_LOCK_WAPPUSH_READED_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_INBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_INBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG(IMAGE_SMS_CHATBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

RES_ADD_IMG(IMAGE_SMS_DRAFTBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_DRAFTBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_INBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_INBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG(IMAGE_SMS_CHATBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#if defined MMI_PDA_SUPPORT && defined MMI_ISTYLE_SUPPORT
RES_ADD_IMG(ISTYLE_IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_SMS_INBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_INBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG(ISTYLE_IMAGE_SMS_CHATBOX_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_CHATBOX_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

RES_ADD_IMG(ISTYLE_IMAGE_SMS_DRAFTBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_DRAFTBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_SMS_INBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_INBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG(ISTYLE_IMAGE_SMS_CHATBOX_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SMS_CHATBOX_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#if defined(MMI_SMS_EXPORT_SUPPORT)
RES_ADD_IMG(IMAGE_SMS_FOLDER_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_FOLDER_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_FOLDER_ICON_DISABLED,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_FOLDER_ICON_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)

#endif
#ifndef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_SMS_EDIT_TO,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_EDIT_TO.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMI_TIMERMSG_SUPPORT
RES_ADD_IMG(IMAGE_SMS_TIMER_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_TIMER_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_TIMER_SIM_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_TIMER_SIM_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_TIMER_SIM_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_TIMER_SIM_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_TIMER_ME_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_TIMER_ME_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_TIMER_ME_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_TIMER_ME_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMI_SMSCB_SUPPORT
#ifndef MMI_MULTI_SIM_SYS_SINGLE
RES_ADD_IMG(IMAGE_CB_SMS_CARD1_ON,"\\MMI_RES_##\\IMAG\\IMAGE_CB_SMS_CARD1_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CB_SMS_CARD1_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_CB_SMS_CARD1_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CB_SMS_CARD2_ON,"\\MMI_RES_##\\IMAG\\IMAGE_CB_SMS_CARD2_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CB_SMS_CARD2_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_CB_SMS_CARD2_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_IMG(IMAGE_CB_SMS_CARD3_ON,"\\MMI_RES_##\\IMAG\\IMAGE_CB_SMS_CARD3_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CB_SMS_CARD3_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_CB_SMS_CARD3_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_IMG(IMAGE_CB_SMS_CARD4_ON,"\\MMI_RES_##\\IMAG\\IMAGE_CB_SMS_CARD4_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CB_SMS_CARD4_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_CB_SMS_CARD4_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#endif

#if defined MMI_PDA_SUPPORT && defined MMI_ISTYLE_SUPPORT
#ifndef MMI_MULTI_SIM_SYS_SINGLE
RES_ADD_IMG(ISTYLE_IMAGE_CB_SMS_CARD1_ON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_CB_SMS_CARD1_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_CB_SMS_CARD1_OFF,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_CB_SMS_CARD1_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_CB_SMS_CARD2_ON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_CB_SMS_CARD2_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_CB_SMS_CARD2_OFF,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_CB_SMS_CARD2_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_IMG(ISTYLE_IMAGE_CB_SMS_CARD3_ON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_CB_SMS_CARD3_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_CB_SMS_CARD3_OFF,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_CB_SMS_CARD3_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_IMG(ISTYLE_IMAGE_CB_SMS_CARD4_ON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_CB_SMS_CARD4_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_CB_SMS_CARD4_OFF,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_CB_SMS_CARD4_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#endif

#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG(IMAGE_SMS_CHATBOX_BG_MO_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_BG_MO_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHATBOX_BG_MT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_BG_MT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHATBOX_BG_MO_FOCUS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_BG_MO_FOCUS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHATBOX_BG_MT_FOCUS_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_BG_MT_FOCUS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

#if defined MMI_PDA_SUPPORT && defined MMI_ISTYLE_SUPPORT
RES_ADD_IMG(IMAGE_SMS_CHATBOX_BG_MO_ICON_ISTYLE,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_BG_MO_ICON_ISTYLE.png",IMG_CMP_PNG_SABM | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_SMS_CHATBOX_BG_MT_ICON_ISTYLE,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_BG_MT_ICON_ISTYLE.png",IMG_CMP_PNG_SABM | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_SMS_CHATBOX_BG_MO_FOCUS_ICON_ISTYLE,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_BG_MO_FOCUS_ICON_ISTYLE.png",IMG_CMP_PNG_SABM | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_SMS_CHATBOX_BG_MT_FOCUS_ICON_ISTYLE,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_BG_MT_FOCUS_ICON_ISTYLE.png",IMG_CMP_PNG_SABM | SABM_CEN_STRETCH,0)
#endif

//RES_ADD_IMG(IMAGE_SMS_CHATBOX_MT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_MT_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
//RES_ADD_IMG(IMAGE_SMS_CHATBOX_MO_SUCC_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_MO_SUCC_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHATBOX_MO_FAIL_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_MO_FAIL_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHATBOX_MO_SENDING_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_MO_SENDING_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHATBOX_MO_TIMERMSG_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHATBOX_MO_TIMERMSG_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHAT_LOCK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHAT_LOCK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

RES_ADD_IMG(IMAGE_SMS_CHAT_DEFAULT,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CHAT_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image infomation
#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_SMS_READ_SMS_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_READ_SMS_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_STOP_READ_SMS_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_STOP_READ_SMS_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_REPLY_SMS_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_REPLY_SMS_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_REPLY_GRAY_SMS_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_REPLY_GRAY_SMS_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_DELETE_SMS_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_DELETE_SMS_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_DELETE_GRAY_SMS_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_DELETE_GRAY_SMS_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SMS_FORWARD_SMS_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_FORWARD_SMS_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_FORWARD_GARY_SMS_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_FORWARD_GARY_SMS_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_CANCEL_MARKALL,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_CANCEL_MARKALL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_CHANGE_PASSWORD,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_CHANGE_PASSWORD.png",IMG_CMP_PNG_ARGB_RLE,0)
//#if 0
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_CHAT_MODE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_CHAT_MODE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_DRAFT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_DRAFT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_EXIT_NOSAVE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_EXIT_NOSAVE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_IPCALL,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_IPCALL.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_MARK,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_MARK.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_MMS_REPLEY,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_MMS_REPLEY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_ORIGINAL_MODE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_ORIGINAL_MODE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SAVE_CONTACT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SAVE_CONTACT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SECURITY,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SECURITY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SMS_MOVETO_SECURITY,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SMS_MOVETO_SECURITY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SMSTIMER_CLOSE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SMSTIMER_CLOSE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_VIDEO_CALL,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_VIDEO_CALL.png",IMG_CMP_PNG_ARGB_RLE,0)
//#endif
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_DETAIL,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_DETAIL.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined(MMI_SMS_FONT_SETTING_SUPPORT)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_FONT_SIZE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_FONT_SIZE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_FORWARD,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_FORWARD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_INSERT_CONTACT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_INSERT_CONTACT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_INSERT_PHIZ,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_INSERT_PHIZ.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_INSERT_TEMPLATE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_INSERT_TEMPLATE.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef STREAMING_SUPPORT_NEXTREAMING
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_INSERT_VCARD,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_INSERT_VCARD.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_MARKALL,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_MARKALL.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SMS_MOVE_SUPPORT
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_MOVE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_MOVE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SAVE_DRAFT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SAVE_DRAFT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SAVE_FILE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SAVE_FILE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SECURITY,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SECURITY.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SMS_COPY_SUPPORT
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SMS_COPY,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SMS_COPY.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#if defined(MMI_SMS_EXPORT_SUPPORT)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SMS_EXPORT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SMS_EXPORT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SMS_LOCK,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SMS_LOCK.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SMS_MOVETO_SECURITY,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SMS_MOVETO_SECURITY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SMS_TIMER,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SMS_TIMER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SMS_TYPESET,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SMS_TYPESET.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_SMSTIMER_CLOSE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_SMSTIMER_CLOSE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_VIDEO_CALL,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_VIDEO_CALL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_VOICECALL,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_VOICECALL.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SMS_CALL_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_CALL_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SAVE_SMS_PDA,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SAVE_SMS_PDA.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifndef MMI_MULTI_SIM_SYS_SINGLE
RES_ADD_IMG(IMAGE_SMS_SIM_CARD1,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_CARD1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SIM_CARD2,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_CARD2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SIM_CARD3,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_CARD3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_SIM_CARD4,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_CARD4.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_SMS_SIM_CARD,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_SIM_CARD.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMI_SMS_SIM_PHONE_DIFF_ICON
RES_ADD_IMG(IMAGE_SMS_ME_CARD1,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_ME_CARD1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_ME_CARD2,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_ME_CARD2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_ME_CARD3,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_ME_CARD3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_ME_CARD4,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_ME_CARD4.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifndef MMI_GUI_STYLE_TYPICAL
RES_ADD_IMG(IMAGE_SETTING_SMS_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SETTING_SMS_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_SMS_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SETTING_SMS_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SETTING_PUSH_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SETTING_PUSH_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_PUSH_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SETTING_PUSH_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SETTING_MMS_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SETTING_MMS_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_MMS_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SETTING_MMS_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef MMI_ISTYLE_SUPPORT
RES_ADD_IMG(ISTYLE_IMAGE_SETTING_SMS_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SETTING_SMS_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_SETTING_SMS_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SETTING_SMS_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(ISTYLE_IMAGE_SETTING_PUSH_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SETTING_PUSH_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_SETTING_PUSH_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SETTING_PUSH_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SMS_FONT_SETTING_SUPPORT
RES_ADD_IMG(ISTYLE_IMAGE_OTHERS_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_OTHERS_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(ISTYLE_IMAGE_OTHERS_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_OTHERS_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(ISTYLE_IMAGE_SETTING_MMS_TAB_ON_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SETTING_MMS_TAB_ON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMAGE_SETTING_MMS_TAB_OFF_ICON,"\\MMI_RES_##\\IMAG\\istyle\\ISTYLE_IMAGE_SETTING_MMS_TAB_OFF_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_SMS_WRITE_SMS_ADD_CONTACT_DISABLE_BG,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_WRITE_SMS_ADD_CONTACT_DISABLE_BG.png",IMG_CMP_PNG_ARGB_RLE | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_SMS_WRITE_SMS_ADD_CONTACT_BG,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_WRITE_SMS_ADD_CONTACT_BG.png",IMG_CMP_PNG_ARGB_RLE | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_SMS_WRITE_SMS_ADD_CONTACT_PRESSED_BG,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_WRITE_SMS_ADD_CONTACT_PRESSED_BG.png",IMG_CMP_PNG_ARGB_RLE | SABM_CEN_STRETCH,0)

RES_ADD_IMG(IMAGE_SMS_WRITE_SMS_ADD_CONTACT,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_WRITE_SMS_ADD_CONTACT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_BUTTON_DISABLE,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_BUTTON_DISABLE.png",IMG_CMP_PNG_SABM_RLE | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_SMS_BUTTON_NORMAL,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_BUTTON_NORMAL.png",IMG_CMP_PNG_SABM_RLE |SABM_CEN_STRETCH ,0)
RES_ADD_IMG(IMAGE_SMS_BUTTON_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_BUTTON_PRESSED.png",IMG_CMP_PNG_SABM_RLE | SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_SMS_BUTTON_FORM_BG,"\\MMI_RES_##\\IMAG\\IMAGE_SMS_BUTTON_FORM_BG.png",IMG_CMP_PNG_SABM_RLE | SABM_CEN_STRETCH,0)
#endif

//WATCH
RES_ADD_IMG(IMAGE_SMS_MAIN_DETAIL,"\\MMI_RES_##\\IMAG\\watch\\res_message_ic_details.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_MAIN_PRESET,"\\MMI_RES_##\\IMAG\\watch\\res_message_ic_preset.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_PRESET_SENT,"\\MMI_RES_##\\IMAG\\watch\\res_message_ic_sent.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHAT_REPLY,"\\MMI_RES_##\\IMAG\\watch\\res_message_btn_reply.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHAT_REPLY_BG,"\\MMI_RES_##\\IMAG\\watch\\res_message_reply_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHAT_EMOJI_BG,"\\MMI_RES_##\\IMAG\\watch\\res_message_emoji_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHAT_SENT,"\\MMI_RES_##\\IMAG\\watch\\res_message_bg_send.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHAT_SENTFAIL,"\\MMI_RES_##\\IMAG\\watch\\res_message_bg_fail.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_CHAT_RECEIVE,"\\MMI_RES_##\\IMAG\\watch\\res_message_bg_receive.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_MESSAGE_NONE,"\\MMI_RES_##\\IMAG\\watch\\res_message_bg_nonemessage.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_PRESET_NONE,"\\MMI_RES_##\\IMAG\\watch\\res_message_bg_nonepreset.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_NOTE_BG,"\\MMI_RES_##\\IMAG\\watch\\res_button_03.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_MESSAGE_DELETE,"\\MMI_RES_##\\IMAG\\watch\\res_sms_ic_delete.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SMS_MESSAGE_BACK,"\\MMI_RES_##\\IMAG\\watch\\res_sms_ic_back.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef ADULT_WATCH_SUPPORT
RES_ADD_IMG(IMAGE_SMS_NO_SIM,"\\MMI_RES_##\\IMAG\\watch\\res_aw_message_ic_no_sim.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMIMMS_SMS_IN_1_SUPPORT
RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_INSERT_THEME,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_INSERT_THEME.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_INSERT_CARBON_COPY,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_MESSAGE_OPTMENU_INSERT_CARBON_COPY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WRITESMS_FORM_BG,"\\MMI_RES_##\\IMAG\\IMAGE_WRITESMS_FORM_BG.png",IMG_CMP_PNG_SABM_RLE | SABM_CEN_STRETCH,0)
//RES_ADD_IMG(IMAGE_MESSAGE_OPTMENU_CB,"\\MMI_RES_##\\IMAG\\IMAGE_MESSAGE_OPTMENU_CB.png",IMG_CMP_PNG_ARGB_RLE ,0)
#endif

//RES_ADD_IMG(IMAGE_IDLE_TITLE_ICON_MESSAGE_SEND,"\\MMI_RES_##\\IMAG\\IMAGE_IDLE_TITLE_ICON_MESSAGE_SEND.png",IMG_CMP_PNG_ARGB_RLE,0)
//[[define anim infomation
//RES_ADD_ANIM(IMAGE_SMS_SENDING_ANIM,"\\MMI_RES_##\\ANIM\\IMAGE_SMS_SENDING_ANIM",AT_COMPRESS_STREAM,75,0x000000)
//]]define anim infomation
//[[define image tag infomation
#ifdef MMISMS_PORTRAIT_SUPPORT
RES_ADD_IMG_TAG(IMAGE_SMS_DRAFT_SMS_ICON,"IMAGE_SMS_DRAFT_SMS_ICON")   
#endif
//RES_ADD_IMG_TAG(IMAGE_SMS_MEMORY_STK_ICON,"IMAGE_SMS_MEMORY_STK_ICON")      
RES_ADD_IMG_TAG(IMAGE_SMS_MMS_NOTIFY_NEW_ICON,"IMAGE_SMS_MMS_NOTIFY_NEW_ICON")  
RES_ADD_IMG_TAG(IMAGE_SMS_MMSOTA_ICON,"IMAGE_SMS_MMSOTA_ICON")          
RES_ADD_IMG_TAG(IMAGE_SMS_MMSOTA_READED_ICON,"IMAGE_SMS_MMSOTA_READED_ICON")   
RES_ADD_IMG_TAG(IMAGE_SMS_NOT_READ_MMS_ICON,"IMAGE_SMS_NOT_READ_MMS_ICON")    
RES_ADD_IMG_TAG(IMAGE_SMS_NOT_READ_SMS_ICON,"IMAGE_SMS_NOT_READ_SMS_ICON")    
RES_ADD_IMG_TAG(IMAGE_SMS_READ_MMS_ICON,"IMAGE_SMS_READ_MMS_ICON")        
RES_ADD_IMG_TAG(IMAGE_SMS_READ_SMS_ICON,"IMAGE_SMS_READ_SMS_ICON")        
RES_ADD_IMG_TAG(IMAGE_SMS_SEND_FAIL_SMS_ICON,"IMAGE_SMS_SEND_FAIL_SMS_ICON")   
RES_ADD_IMG_TAG(IMAGE_SMS_SEND_SIM_SUCCESS_SMS_ICON,"IMAGE_SMS_SEND_SIM_SUCCESS_SMS_ICON")   
RES_ADD_IMG_TAG(IMAGE_SMS_SEND_SUCCESS_SMS_ICON,"IMAGE_SMS_SEND_SUCCESS_SMS_ICON")       
RES_ADD_IMG_TAG(IMAGE_SMS_SIM_DRAFT_SMS_ICON,"IMAGE_SMS_SIM_DRAFT_SMS_ICON")          
RES_ADD_IMG_TAG(IMAGE_SMS_SIM_NOT_READ_SMS_ICON,"IMAGE_SMS_SIM_NOT_READ_SMS_ICON")       
RES_ADD_IMG_TAG(IMAGE_SMS_SIM_READ_SMS_ICON,"IMAGE_SMS_SIM_READ_SMS_ICON")           
RES_ADD_IMG_TAG(IMAGE_SMS_SIM_SEND_FAIL_SMS_ICON,"IMAGE_SMS_SIM_SEND_FAIL_SMS_ICON")      
RES_ADD_IMG_TAG(IMAGE_SMS_WAPOTA_ICON,"IMAGE_SMS_WAPOTA_ICON")
RES_ADD_IMG_TAG(IMAGE_SMS_TITLE_ICON_FULL_MESSAGE,"IMAGE_SMS_TITLE_ICON_FULL_MESSAGE")
RES_ADD_IMG_TAG(IMAGE_SMS_WAPOTA_READED_ICON,"IMAGE_SMS_WAPOTA_READED_ICON")     
RES_ADD_IMG_TAG(IMAGE_SMS_WAPPUSH_ICON,"IMAGE_SMS_WAPPUSH_ICON")           
RES_ADD_IMG_TAG(IMAGE_SMS_WAPPUSH_READED_ICON,"IMAGE_SMS_WAPPUSH_READED_ICON")    
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_DRAFT_SMS_ICON,"IMAGE_SMS_LOCK_DRAFT_SMS_ICON")    
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_SIM_DRAFT_SMS_ICON,"IMAGE_SMS_LOCK_SIM_DRAFT_SMS_ICON")
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_MMS_NOTIFY_NEW_ICON,"IMAGE_SMS_LOCK_MMS_NOTIFY_NEW_ICON") 
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_MMSOTA_ICON,"IMAGE_SMS_LOCK_MMSOTA_ICON")         
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_MMSOTA_READED_ICON,"IMAGE_SMS_LOCK_MMSOTA_READED_ICON")  
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_NOT_READ_MMS_ICON,"IMAGE_SMS_LOCK_NOT_READ_MMS_ICON")   
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_NOT_READ_SMS_ICON,"IMAGE_SMS_LOCK_NOT_READ_SMS_ICON")   
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_READ_MMS_ICON,"IMAGE_SMS_LOCK_READ_MMS_ICON")       
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_READ_SMS_ICON,"IMAGE_SMS_LOCK_READ_SMS_ICON")       
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_SEND_FAIL_SMS_ICON,"IMAGE_SMS_LOCK_SEND_FAIL_SMS_ICON")  
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_SEND_SIM_SUCCESS_SMS_ICON,"IMAGE_SMS_LOCK_SEND_SIM_SUCCESS_SMS_ICON") 
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_SEND_SUCCESS_SMS_ICON,"IMAGE_SMS_LOCK_SEND_SUCCESS_SMS_ICON")     
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_SIM_NOT_READ_SMS_ICON,"IMAGE_SMS_LOCK_SIM_NOT_READ_SMS_ICON")     
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_SIM_READ_SMS_ICON,"IMAGE_SMS_LOCK_SIM_READ_SMS_ICON")         
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_SIM_SEND_FAIL_SMS_ICON,"IMAGE_SMS_LOCK_SIM_SEND_FAIL_SMS_ICON")    
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_WAPOTA_ICON,"IMAGE_SMS_LOCK_WAPOTA_ICON")               
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_WAPOTA_READED_ICON,"IMAGE_SMS_LOCK_WAPOTA_READED_ICON")        
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_WAPPUSH_ICON,"IMAGE_SMS_LOCK_WAPPUSH_ICON")              
RES_ADD_IMG_TAG(IMAGE_SMS_LOCK_WAPPUSH_READED_ICON,"IMAGE_SMS_LOCK_WAPPUSH_READED_ICON")       

RES_ADD_IMG_TAG(IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON,"IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON")          
RES_ADD_IMG_TAG(IMAGE_SMS_INBOX_TAB_OFF_ICON,"IMAGE_SMS_INBOX_TAB_OFF_ICON")             
RES_ADD_IMG_TAG(IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON,"IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON")       
RES_ADD_IMG_TAG(IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON,"IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON")       
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG_TAG(IMAGE_SMS_CHATBOX_TAB_OFF_ICON,"IMAGE_SMS_CHATBOX_TAB_OFF_ICON")   
#endif

RES_ADD_IMG_TAG(IMAGE_SMS_DRAFTBOX_TAB_ON_ICON,"IMAGE_SMS_DRAFTBOX_TAB_ON_ICON")           
RES_ADD_IMG_TAG(IMAGE_SMS_INBOX_TAB_ON_ICON,"IMAGE_SMS_INBOX_TAB_ON_ICON")            
RES_ADD_IMG_TAG(IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON,"IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON")      
RES_ADD_IMG_TAG(IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON,"IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON")      
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG_TAG(IMAGE_SMS_CHATBOX_TAB_ON_ICON,"IMAGE_SMS_CHATBOX_TAB_ON_ICON")      
#endif

#if defined MMI_PDA_SUPPORT && defined MMI_ISTYLE_SUPPORT
RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON,"ISTYLE_IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON")          
RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_INBOX_TAB_OFF_ICON,"ISTYLE_IMAGE_SMS_INBOX_TAB_OFF_ICON")             
RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON,"ISTYLE_IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON")       
RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON,"ISTYLE_IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON")       
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_CHATBOX_TAB_OFF_ICON,"ISTYLE_IMAGE_SMS_CHATBOX_TAB_OFF_ICON")   
#endif

RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_DRAFTBOX_TAB_ON_ICON,"ISTYLE_IMAGE_SMS_DRAFTBOX_TAB_ON_ICON")           
RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_INBOX_TAB_ON_ICON,"ISTYLE_IMAGE_SMS_INBOX_TAB_ON_ICON")            
RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON,"ISTYLE_IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON")      
RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON,"ISTYLE_IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON")      
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_IMG_TAG(ISTYLE_IMAGE_SMS_CHATBOX_TAB_ON_ICON,"ISTYLE_IMAGE_SMS_CHATBOX_TAB_ON_ICON")      
#endif
#endif

#ifndef MMI_MULTI_SIM_SYS_SINGLE
RES_ADD_IMG_TAG(IMAGE_SMS_SIM_CARD1,"IMAGE_SMS_SIM_CARD1")
RES_ADD_IMG_TAG(IMAGE_SMS_SIM_CARD2,"IMAGE_SMS_SIM_CARD2")
RES_ADD_IMG_TAG(IMAGE_SMS_SIM_CARD3,"IMAGE_SMS_SIM_CARD3")
RES_ADD_IMG_TAG(IMAGE_SMS_SIM_CARD4,"IMAGE_SMS_SIM_CARD4")
#else
RES_ADD_IMG_TAG(IMAGE_SMS_SIM_CARD,"IMAGE_SMS_SIM_CARD")
#endif
#if defined(MMI_SMS_EXPORT_SUPPORT)
RES_ADD_IMG_TAG(IMAGE_SMS_FOLDER_ICON,"IMAGE_SMS_FOLDER_ICON")
RES_ADD_IMG_TAG(IMAGE_SMS_FOLDER_ICON_DISABLED,"IMAGE_SMS_FOLDER_ICON_DISABLED")     

#endif
#ifndef MMI_PDA_SUPPORT
RES_ADD_IMG_TAG(IMAGE_SMS_EDIT_TO,"IMAGE_SMS_EDIT_TO")
#endif
#ifdef MMI_TIMERMSG_SUPPORT
RES_ADD_IMG_TAG(IMAGE_SMS_TIMER_ICON,"IMAGE_SMS_TIMER_ICON")
RES_ADD_IMG_TAG(IMAGE_SMS_TIMER_SIM_ICON,"IMAGE_SMS_TIMER_SIM_ICON")
RES_ADD_IMG_TAG(IMAGE_SMS_TIMER_SIM_LOCK_ICON,"IMAGE_SMS_TIMER_SIM_LOCK_ICON")
RES_ADD_IMG_TAG(IMAGE_SMS_TIMER_ME_ICON,"IMAGE_SMS_TIMER_ME_ICON")
RES_ADD_IMG_TAG(IMAGE_SMS_TIMER_ME_LOCK_ICON,"IMAGE_SMS_TIMER_ME_LOCK_ICON")
#endif
//]]define image tag infomation
#if 1

#ifdef MMI_SMS_SYN_SUPPORT
RES_ADD_STRING(TXT_BT_SEND, "Bt Send")
RES_ADD_STRING(TXT_SMS_EMPTY_CONTENT, "Empty content")
#else
#if defined(BT_DIALER_SUPPORT) && defined(BT_MAP_SUPPORT)
RES_ADD_STRING(TXT_BT_SEND, "Bt Send")
RES_ADD_STRING(TXT_SMS_EMPTY_CONTENT, "Empty content")
RES_ADD_STRING(TXT_SMS_SEND_SIM1, "SIM1 send")
#endif
#endif

RES_ADD_STRING(TXT_SMS_SIM_BOX,"SMS SIMBOX")

#ifdef MMISEARCH_SUPPORT_ONLYMMS
RES_ADD_STRING(TXT_SMS_MMS_SEARCH,"Search MMS")
#endif
RES_ADD_STRING(TXT_SMS_FIX_SIM_SEND,"SMS Fixed_Sim Sending Setting")
RES_ADD_STRING(TXT_SMS_FIX_SIM_SEND_ONOFF,"SMS Fixed_Sim Sending Switch")
//[[define string infomation
//RES_ADD_STRING(TXT_SMS_MENU,"Message")//case 3:defined but not used
RES_ADD_STRING(TXT_SMS_WRITE,"Write message")
//RES_ADD_STRING(TXT_SMS_SENDMORE_BYGROUP,"Send by group")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SENDMORE_BYUSER,"Customized")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SR_ENABLE,"Activate")             //replaced by common ID TXT_COMMON_ENABLE_ON
//RES_ADD_STRING(TXT_SMS_SR_DISABLE,"Deactivate")          //replaced by common ID TXT_CLOSE
//RES_ADD_STRING(TXT_SMS_CB_READ,"Read")    //replaced by common ID TXT_READ
#if defined(MMI_SMSCB_SUPPORT)
//RES_ADD_STRING(TXT_SMS_CB_STARTUP,"Startup")//case 3:defined but not used
RES_ADD_STRING(TXT_SMS_CB_CHANNEL,"Channel")
//RES_ADD_STRING(TXT_SMS_CB_LANGUAGE,"Language")    //replaced by common ID TXT_SELECT_LANGUAGE


//RES_ADD_STRING(TXT_SMS_CB_ENABLE,"Activate")              //replaced by common ID TXT_COMMON_ENABLE_ON
//RES_ADD_STRING(TXT_SMS_CB_DISABLE,"Deactivate")                   //replaced by common ID TXT_CLOSE
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_ADD,"Channel")    //replaced by common ID TXT_ADD_CHANNEL
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_LIST,"List channel")       //replaced by common TXT_COMMON_COMMON_CHANNEL_LIST
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_ADD_SUCC,"Add Success")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_ADD_FAIL,"Add Fail")//case 3:defined but not used 
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_EDIT_SUCC,"Edit Success")//case 3:defined but not used 
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_EDIT_FAIL,"Edit Fail")//case 3:defined but not used 
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_DELETE_SUCC,"Delete success")     //replaced by common ID TXT_COMMON_DELETESUCESS
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_DELETE_FAIL,"Delete fail")  //replaced by common ID TXT_COMMON_DEL_FAIL
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_LIST_OPT,"List option")
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_INDEX,"Channel index")
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_NAME,"Channel name")
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_ENABLE,"Enable channel")
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_DISABLE,"Disable channel")
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_SWITCH,"Channel switch")//case 3:defined but not used 
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_EDIT,"Edit channel")
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_DELETE,"Delete channel")     //replaced by common ID TXT_COMMON_DELETE_CHANNEL
//RES_ADD_STRING(TXT_SMS_CB_CHANNEL_CHECK,"Check channel")//case 3:defined but not used 
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_INDEX_EMPTY,"Channel index empty")
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_INDEX_TOOBIG,"Channel index too big")
//RES_ADD_STRING(TXT_SMS_CB_SETTING_SUCC,"Setting success")         //replaced by common ID TXT_SET_SUCCESS
//RES_ADD_STRING(TXT_SMS_CB_SETTING_FAIL,"Setting failure")         //replaced by common ID TXT_COMMON_SETTING_FAIL
RES_ADD_STRING(TXT_SMS_CB_TURN_ON_SUCC,"Activate success")
RES_ADD_STRING(TXT_SMS_CB_TURN_ON_FAIL,"Activate failure")
RES_ADD_STRING(TXT_SMS_CB_TURN_OFF_SUCC,"Deactivate success")
RES_ADD_STRING(TXT_SMS_CB_TURN_OFF_FAIL,"Deactivate failure")
RES_ADD_STRING(TXT_SMS_CB_LANG_GERMAN,"German")
//RES_ADD_STRING(TXT_SMS_CB_LANG_ENGLISH,"English")    //replaced by common ID TXT_LANG_ENGLISH
RES_ADD_STRING(TXT_SMS_CB_LANG_ITALIAN,"Italian")
RES_ADD_STRING(TXT_SMS_CB_LANG_FRENCH,"French")
//RES_ADD_STRING(TXT_SMS_CB_LANG_CHINESE,"Chinese")  //replaced by common ID TXT_COMMON_LANG_CHINESE
RES_ADD_STRING(TXT_SMS_CB_LANG_SPANISH,"Spanish")
RES_ADD_STRING(TXT_SMS_CB_LANG_DUTCH,"Dutch")
RES_ADD_STRING(TXT_SMS_CB_LANG_SWEDISH,"Swedish")
RES_ADD_STRING(TXT_SMS_CB_LANG_DANISH,"Danish")
RES_ADD_STRING(TXT_SMS_CB_LANG_PORTUGUESE,"Portuguese")
RES_ADD_STRING(TXT_SMS_CB_LANG_FINNISH,"Finnish")
RES_ADD_STRING(TXT_SMS_CB_LANG_NORWEGIAN,"Norwegian")
RES_ADD_STRING(TXT_SMS_CB_LANG_GREEK,"Greek")
RES_ADD_STRING(TXT_SMS_CB_LANG_TURKISH,"Turkish")
RES_ADD_STRING(TXT_SMS_CB_LANG_HUNGARIAN,"Hungarian")
RES_ADD_STRING(TXT_SMS_CB_LANG_POLISH,"Polish")
RES_ADD_STRING(TXT_SMS_CB_LANG_CZECH,"Czech")
RES_ADD_STRING(TXT_SMS_CB_LANG_HEBREW,"Hebrew")
RES_ADD_STRING(TXT_SMS_CB_LANG_ARABIC,"Arabic")
RES_ADD_STRING(TXT_SMS_CB_LANG_RUSSIAN,"Russian")
RES_ADD_STRING(TXT_SMS_CB_LANG_ICELANDIC,"Icelandic")
RES_ADD_STRING(TXT_SMS_CB_LANG_UNSPECIFIED,"Unspecified")
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_INDEX_REPEAT,"Channle index repeat")
RES_ADD_STRING(TXT_SMS_CB_MSG_LIST,"Cell broadcast list")
RES_ADD_STRING(TXT_SMS_CB_RECEIVE_NEW,"New cell broadcast")
RES_ADD_STRING(TXT_SMS_CB_LIST_EMPTY,"Message is empty")
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_LIST_EMPTY,"Channel list is empty")
RES_ADD_STRING(TXT_SMS_CB_CHANNEL_LIST_FULL,"Channel list is full")
RES_ADD_STRING(TXT_SMS_CB_SETTING,"Broadcast Setting")
RES_ADD_STRING(TXT_SMS_CB_LANG_ALL,"All language")
#ifdef MMI_ETWS_SUPPORT
RES_ADD_STRING(TXT_SMS_CB_ETWS_MSG,"ETWS alert message")
#endif
#ifndef MMI_MULTI_SIM_SYS_SINGLE
RES_ADD_STRING(TXT_SMS_CB_SET_CARD1,"SIM1 settings")
RES_ADD_STRING(TXT_SMS_CB_SET_CARD2,"SIM2 settings")
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SMS_CB_SET_CARD3,"SIM3 settings")
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SMS_CB_SET_CARD4,"SIM4 settings")
#endif
#endif
RES_ADD_STRING(TXT_SMS_CB_ONOFF,"CB ON/OFF")
#ifdef  MMI_GUI_STYLE_TYPICAL
RES_ADD_STRING(TXT_SMS_CB_DETAIL,"Task details")    //replaced by common ID STXT_DETAIL
#endif
#endif//#if defined(MMI_SMSCB_SUPPORT)
//RES_ADD_STRING(TXT_SMS_NUM_DEL,"Delete")       //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_SMS_NUM_EDIT,"Edit") //replaced by common ID TXT_EDIT
//RES_ADD_STRING(TXT_SMS_VM_CALLVM,"Retrieve message")
//RES_ADD_STRING(TXT_SMS_VM_SETVM,"Number settings")
//RES_ADD_STRING(TXT_SMS_VOICEMAIL,"Voicemail")  //replaced by common ID TXT_VOICEMAIL
#ifdef MMI_SMS_VOICE_MAIL_SUPPORT
RES_ADD_STRING(TXT_SMS_VOICEMAIL_EMPTY,"Voice mail empty")
#endif
RES_ADD_STRING(TXT_SMS_FREQWORD,"Template settings")
RES_ADD_STRING(TXT_SMS_INSERT_WORD,"Insert template")
RES_ADD_STRING(TXT_SMS_SETTING,"Setting")
//RES_ADD_STRING(TXT_SMS_SPACE,"Memory")// case 3:defined but not used
RES_ADD_STRING(TXT_SMS_WRITE_OPT,"Option")
//RES_ADD_STRING(TXT_SMS_SEND,"Send")  //replaced by common ID TXT_SEND
//RES_ADD_STRING(TXT_SMS_SENDMORE,"Multiple send")// case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SAVE,"Save")  //replaced by common ID STXT_SAVE
RES_ADD_STRING(TXT_SMS_SAVE_SEND,"Send and save")
//RES_ADD_STRING(TXT_SMS_ANSWER,"Reply")  //replaced by common ID TXT_REPLY
//RES_ADD_STRING(TXT_SMS_DEL,"Delete")      //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_SMS_FORWARD,"Forward")  //replaced by common ID TXT_COMMON_FORWARD
#ifdef DPHONE_SUPPORT 
RES_ADD_STRING(TXT_SMS_USE_NUM,"Extract number")
#endif
//RES_ADD_STRING(TXT_SMS_CALL,"Call")
//RES_ADD_STRING(TXT_SMS_EDIT,"Edit") //repaced by common ID TXT_EDIT
RES_ADD_STRING(TXT_SMS_SETTING_SC,"Message center number")
//RES_ADD_STRING(TXT_SMS_SETTING_SC_TITLE,"Center number")    //replaced by local common ID TXT_SMS_SETTING_SC
RES_ADD_STRING(TXT_SMS_SETTING_VP,"Message validity period")
//RES_ADD_STRING(TXT_SMS_SETTING_VP_TITLE,"Validity period")    //replaced by local common ID TXT_SMS_SETTING_VP
//RES_ADD_STRING(TXT_SMS_SETTING_SR,"Status report")// case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_INPUTNUM,"Input number")    //replaced by common ID TXT_INPUTNUM
//RES_ADD_STRING(TXT_SMS_OPTION,"Option")    //replaced by common ID STXT_OPTION
RES_ADD_STRING(TXT_SMS_READ_SMS,"Read message")
//RES_ADD_STRING(TXT_SMS_INSERT_PROMPT,"**No.0 Message had been lost**")// case 3:defined but not used
RES_ADD_STRING(TXT_SMS_AUTO_SAVE,"Save sent messages")
RES_ADD_STRING(TXT_SMS_RESEND,"Resend")
//RES_ADD_STRING(TXT_SMS_BEYOND_LEN,"Beyond the max length") //replaced by common ID TXT_COMMON_BEYOND_LEN
//RES_ADD_STRING(TXT_SMS_NUMOPT_INPUTNUM,"<Input Number>")// case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_NUMOPT_SELECTPB,"<Phonebook>")// case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_NUMOPT_SEND,"<Send>")// case 3:defined but not used
RES_ADD_STRING(TXT_SMS_VP_1HOUR,"1 hour")  //replaced by common ID TXT_COMM_1_HOUR, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_VP_6HOUR,"6 hours")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_VP_24HOUR,"24 hours")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_VP_72HOUR,"72 hours")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_VP_1WEEK,"1 week")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_VP_MAX,"Maximum")// case 3:defined but not used, but later find it was used in ++mode
//RES_ADD_STRING(TXT_SMS_PROMPT_SENDING,"Sending")    //replaced by common ID TXT_SENDING
//RES_ADD_STRING(TXT_SMS_PROMPT_SAVING,"Saving")  //replaced by common ID TXT_PUB_SAVING
//RES_ADD_STRING(TXT_SMS_PROMPT_SUCC,"Succeed")  //replaced by common ID TXT_SUCCESS
//RES_ADD_STRING(TXT_SMS_PROMPT_FAIL,"Fail")    //replaced by common ID TXT_ERROR
//RES_ADD_STRING(TXT_SMS_PROMPT_NO_SPACE,"No space")  //replaced by common ID TXT_NO_SPACE
//RES_ADD_STRING(TXT_SMS_PROMPT_DEL,"Delete")           //replaced by common ID TXT_DELETE
RES_ADD_STRING(TXT_SMS_STATUSREPORT,"Status Report")
RES_ADD_STRING(TXT_SMS_BOX_EMPTY,"Box empty")
RES_ADD_STRING(TXT_SMS_EMPTY_WORD,"<Empty>")
//RES_ADD_STRING(TXT_SMS_EMPTY_CONTENT,"Empty")// case 3:defined but not used
RES_ADD_STRING(TXT_SMS_NO_SC,"No Service Center")
RES_ADD_STRING(TXT_SMS_NO_SERVICE,"No Service")

//RES_ADD_STRING(TXT_SMS_READ_MSG,"Read message")// case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_EMPTY_LIST,"Empty List")          //replaced by common ID TXT_COMMON_COMMON_EMPTY_LIST
RES_ADD_STRING(TXT_SMS_NEW_MSG,"New message")
RES_ADD_STRING(TXT_SMS_NEW_BT_MSG,"New bt message")
#ifdef MMI_SMS_SYN_SUPPORT
//RES_ADD_STRING(TXT_SMS_SYN_MSG,"/100(maxnum)")
RES_ADD_STRING(TXT_SMS_SYNC_FINISHED,"syn completed")
RES_ADD_STRING(TXT_SMS_SYN_MSG_EMPETY,"Inbox Is Not Have Sms")
#endif
#ifdef BT_DIALER_SUPPORT
RES_ADD_STRING(TXT_SMS_BT_SENTBOX,"BT Sentbox")
#endif
//RES_ADD_STRING(TXT_SMS_EMPTY_NUM,"Empty number")        //replaced by common ID TXT_COMMON_EMPTY_NUM
RES_ADD_STRING(TXT_SMS_FULL_LIST,"Full List")
RES_ADD_STRING(TXT_SMS_READ_ERR,"Message had been deleted!")
RES_ADD_STRING(TXT_SMS_SR_SUCC,"Received")

//////////////////////////////////////////////////
RES_ADD_STRING(TXT_SMS_SR_NO_CONF,"No confirm")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SR_REPLACE,"Replace")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SR_DELAY,"Send later")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SR_FAIL,"Fail")
RES_ADD_STRING(TXT_SMS_SR_INVAILD,"Invaild")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_MEMORY,"Memory detail")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_MEMORY_SIM,"SIM")  //replaced by common ID  TXT_COMM_SIM, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_MEMORY_PHONE,"Phone")    //replaced by common ID TXT_PHONE, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_MEMORY_FULL,"No space")          //replaced by common ID TXT_DC_NOEMPTYSPACE, but later find it was used in ++mode
/////////////////////////////////////////////////////

RES_ADD_STRING(TXT_SMS_DEFAULT_WORD1,"Please call me!")
RES_ADD_STRING(TXT_SMS_DEFAULT_WORD2,"Where are you now?")
RES_ADD_STRING(TXT_SMS_DEFAULT_WORD3,"Thank you!")
RES_ADD_STRING(TXT_SMS_DEFAULT_WORD4,"Wait a minute!")
RES_ADD_STRING(TXT_SMS_DEFAULT_WORD5,"I am business today!")
//RES_ADD_STRING(TXT_SMS_PIECE_SAVED_IN_SIM,"SIM")  //replaced by common id TXT_COMM_SIM
//RES_ADD_STRING(TXT_SMS_PIECE_SAVED_IN_NV,"PHONE")    //replaced by common ID TXT_PHONE
//RES_ADD_STRING(TXT_SMS_WRITE_MESSAGE,"Write messages")  //replaced by common ID TXT_COMMON_WRITE_MESSAGE
//RES_ADD_STRING(TXT_SMS_ANSWER_MMS,"Reply MMS")  //replaced by common ID TXT_MMS
RES_ADD_STRING(TXT_SMS_SMILE,"(Smile)")
RES_ADD_STRING(TXT_SMS_LAUGH,"(Laugh)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SIMPER,"(Simper)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_BLUSH,"(Blush)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_OGLE,"(Ogle)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_ECSTASY,"(Ecstasy)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_DEVAEYES,"(Deva eyes)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_DRUNK,"(Drunk)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_GRIEF,"(Grief)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SURPRISE,"(Surprise)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_WORDINESS,"(Wordiness)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_VACANCY,"(Vacancy)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_BERK,"(Berk)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_HEARTBREAK,"(Heartbreak)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SICKNESS,"(Sickness)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SNIFFLE,"(Sniffle)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_MISERY,"(Misery)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_HELPLESS,"(Helpless)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_COMEDOWN,"(Comedown)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_FATIGUE,"(Fatigue)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_FURY,"(Fury)")// case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_ADD_PHIZ,"Add Phiz")
RES_ADD_STRING(TXT_SMS_PHIZ,"Phiz")
RES_ADD_STRING(TXT_SMS_ADD_CONTACTINFO,"Contact Info")
//RES_ADD_STRING(TXT_SMS_SELECT_CONTACT,"Select Contact")// case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SELECT_GROUP,"Select Group")// case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SELECT_TEL_RECORD,"Select Tel Record")// case 3:defined but not used
RES_ADD_STRING(TXT_SMS_NOT_SAVE,"Not Save")
RES_ADD_STRING(TXT_SMS_PROMPT,"Prompt")
//RES_ADD_STRING(TXT_SMS_OPEN,"Open")  //replaced by common ID TXT_COMM_OPEN
RES_ADD_STRING(TXT_SMS_DETAIL,"Detail")
RES_ADD_STRING(TXT_SMS_PRESET, "Preset Message")
//RES_ADD_STRING(TXT_SMS_EMPTY,"Empty")     //replaced by common ID TXT_BLANK
RES_ADD_STRING(TXT_SMS_QUERY_CONTINUE,"No space, continue")
//RES_ADD_STRING(TXT_SMS_INBOX,"Inbox")    //replaced by common ID TXT_INBOX
RES_ADD_STRING(TXT_SMS_SENTBOX,"Sentbox")
//RES_ADD_STRING(TXT_SMS_OUTBOX,"Outbox")  //replaced by common ID TXT_COMM_OUTBOX
//RES_ADD_STRING(TXT_SMS_DRAFTBOX,"Draftbox") //replaced by common ID TXT_COMM_DRAFT
RES_ADD_STRING(TXT_SMS_MESSAGESPACE,"Message Memory")
//RES_ADD_STRING(TXT_SMS_LINE1_NUMBER,"Line 1 number")    //replaced by common ID TXT_LINE1_NUMBER
//RES_ADD_STRING(TXT_SMS_LINE2_NUMBER,"Line 2 number")    //replaced by common ID TXT_LINE2_NUMBER
//RES_ADD_STRING(TXT_SMS_FAX_NUMBER,"Fax number")   //replaced by common ID TXT_COMM_FAX_NUMBER
#if defined ( MMI_SMS_VOICE_MAIL_SUPPORT )
RES_ADD_STRING(TXT_SMS_DATA_NUMBER,"Data number")
#endif
//RES_ADD_STRING(TXT_SMS_SEARCH_OPERATE,"Operate")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SETTING_SMS,"SMS settings")  //replaced by common ID TXT_MESSAGE_SETTING_SMS
#if defined(MMI_VCARD_SUPPORT) || defined(MMI_VCALENDAR_SUPPORT)
RES_ADD_STRING(TXT_SMS_RECEIVE_VCARD_MSG,"Receive Vcard")
#endif
#ifdef SMS_EXTRACT_URLORST_SUPPORT   //No Use Menu
RES_ADD_STRING(TXT_SMS_EXTRACT_URL,"Extract URL")
//RES_ADD_STRING(TXT_SMS_EXTRACT_STADDR,"Extract ST Addr")    //replaced by common ID TXT_EXTRACT_STADDR
RES_ADD_STRING(TXT_SMS_NO_URL,"No URL")
RES_ADD_STRING(TXT_SMS_NO_STADDR,"No ST Addr")
//RES_ADD_STRING(TXT_SMS_CONNECT_URLORST,"Connect")  //replaced by common ID TXT_COMMON_CONNECT_COMN
#endif
//RES_ADD_STRING(TXT_SMS_RECEIVER_OPTION,"Receiver Option")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_RECEIVER,"Receiver")  //replaced by common ID TXT_COMMON_RECIPIENT
RES_ADD_STRING(TXT_SMS_EXCEED_MAX_NUM,"Exceed Max Num")
//RES_ADD_STRING(TXT_SMS_SIM1_SEND,"SIM1 Send")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SIM2_SEND,"SIM2 Send")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SIM3_SEND,"SIM3 Send")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SIM4_SEND,"SIM4 Send")//case 3:defined but not used
RES_ADD_STRING(TXT_SMS_SETTING_SIM1_SC,"SIM1 Msg Center")
RES_ADD_STRING(TXT_SMS_SETTING_SIM2_SC,"SIM2 Msg Center")
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SMS_SETTING_SIM3_SC,"SIM1 Msg Center")
RES_ADD_STRING(TXT_SMS_SIM3_STORAGE_SMS,"SIM3 Storage SMS")
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SMS_SETTING_SIM4_SC,"SIM2 Msg Center")
RES_ADD_STRING(TXT_SMS_SIM4_STORAGE_SMS,"SIM4 Storage SMS")
#endif
//Add by huangfengming for cr149701
#ifdef MMI_SMS_VOICE_MAIL_SUPPORT
RES_ADD_STRING(TXT_SMS_SIM_VOICEMAIL_EMPTY,"Unset SIM Vmail Number")
RES_ADD_STRING(TXT_SMS1_VOICEMAIL_EMPTY,"Unset SIM1 Vmail Number")
RES_ADD_STRING(TXT_SMS2_VOICEMAIL_EMPTY,"Unset SIM2 Vmail Number")//case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS3_VOICEMAIL_EMPTY,"Unset SIM3 Vmail Number")//case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS4_VOICEMAIL_EMPTY,"Unset SIM4 Vmail Number")//case 3:defined but not used, but later find it was used in ++mode
#endif
RES_ADD_STRING(TXT_SMS_LOCK,"Lock")
RES_ADD_STRING(TXT_SMS_MARK,"Mark") //replaced by common ID STXT_MARK, but later find it was used in ++mode
//RES_ADD_STRING(TXT_SMS_SORT,"Sort")       //replaced by common ID TXT_COMMON_SORT
//RES_ADD_STRING(TXT_SMS_ANSWER_SMS,"Answer SMS")  //replaced by common ID TXT_SMS
//RES_ADD_STRING(TXT_SMS_DIAL,"Dial")
//RES_ADD_STRING(TXT_SMS_IPDIAL,"IP dial")
//RES_ADD_STRING(TXT_SMS_CANCEL_MARK,"Unmark")       //replaced by common ID TXT_CANCEL_MARK
//RES_ADD_STRING(TXT_SMS_MARKALL,"Mark all") //replaced by common ID TXT_MARK_ALL
//RES_ADD_STRING(TXT_SMS_CANCEL_MARKALL,"Unmark all")    //replaced by common ID TXT_CANCEL_MARK_ALL
//RES_ADD_STRING(TXT_SMS_TIME_SORT,"Time")  //replaced by common ID TXT_TIME
//RES_ADD_STRING(TXT_SMS_NAME_SORT,"Name")  //replaced by common ID TXT_COMMON_CONTACT
//RES_ADD_STRING(TXT_SMS_SUBJECT_SORT,"Subject")  //replaced by common ID TXT_COMMON_SUBJECT
//RES_ADD_STRING(TXT_SMS_TYPE_SORT,"Type")  //replaced by common ID TXT_COMMON_TYPE
//RES_ADD_STRING(TXT_SMS_SETTING_MMS,"MMS Setting")// case 3: defined but not used
RES_ADD_STRING(TXT_SMS_SC_NOT_IN_FDN,"SMS SC not in FDN list")
RES_ADD_STRING(TXT_SMS_SEND_ONLY,"Send only")
//RES_ADD_STRING(TXT_SMS_SENDOPTION,"Send Option")  //replaced by common ID TXT_COMM_SEND_OPTION
RES_ADD_STRING(TXT_SMS_DELETE_MESSAGE,"Delete Message")
RES_ADD_STRING(TXT_SMS_DELALL_MESSAGE,"Delete  All Message")
RES_ADD_STRING(TXT_SMS_MESSAGE_ITEM,"message")
//RES_ADD_STRING(TXT_SMS_DETAIL_SIM,"SIM:")// case 3: defined but not used
RES_ADD_STRING(TXT_SMS_SMS_SPACE,"SMS Memory:")
RES_ADD_STRING(TXT_SMS_MEM_FULL_ALERT_USER,"SMS memory full")
RES_ADD_STRING(TXT_SMS_MEM_FULL_ALERT_ALL,"SMS mem full")
RES_ADD_STRING(TXT_SMS_UNLOCK,"Unlock")
//RES_ADD_STRING(TXT_SMS_QUERY_RESEND,"item send fail,")
//RES_ADD_STRING(TXT_SMS_QUERY_RESEND2,"resend?")
RES_ADD_STRING(TXT_SMS_INVALID_NUMBER,"Invalid number")
#if !defined(MMI_MULTI_SIM_SYS_DUAL)&&!defined(MMI_MULTI_SIM_SYS_TRI)&&!defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SMS_SIM_STORAGE_SMS,"SIM Storage SMS")
#endif
RES_ADD_STRING(TXT_SMS_SIM1_STORAGE_SMS,"SIM1 Storage SMS")
RES_ADD_STRING(TXT_SMS_SIM2_STORAGE_SMS,"SIM2 Storage SMS")
RES_ADD_STRING(TXT_SMS_MESSAGE_ITEMS,"messages")
RES_ADD_STRING(TXT_SMS_NEW_MSGS,"New messages")
RES_ADD_STRING(TXT_SMS_NEW_SMS,"New SMS")
RES_ADD_STRING(TXT_SMS_NEW_MMS,"New MMS")
#ifdef MMI_GUI_STYLE_TYPICAL
RES_ADD_STRING(TXT_SMS_PREFERRED_CONNECTION,"Preferred connection")
//RES_ADD_STRING(TXT_SMS_PREFERRED_GSM,"GSM Preferred")  //replaced by common ID TXT_COMM_GSM_PREFER
RES_ADD_STRING(TXT_SMS_PREFERRED_GPRS,"GPRS Preferred")
RES_ADD_STRING(TXT_SMS_PREFERRED_GSM_ONLY,"GSM Only")
RES_ADD_STRING(TXT_SMS_PREFERRED_GPRS_ONLY,"GPRS Only")
#endif
RES_ADD_STRING(TXT_SMS_UNLOADED_SMS," Unloaded SMS:")
//RES_ADD_STRING(TXT_SMS_INSERT_PROMPT_HEAD,"**No.")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_INSERT_PROMPT_TAIL," Message had been lost**")//case 3:defined but not used
#ifdef CMCC_UI_STYLE        
RES_ADD_STRING(TXT_SMS_OPEN_LINK," Open link")//case 3:defined but not used
#endif
//RES_ADD_STRING(TXT_SMS_SET_HOMEPAGE," Set homepage")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SET_BOOKMARK," Add to bookmark")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SEND_SUCCEED," Send Successfully")  //replaced by common ID  TXT_COMM_SEND_SUCCEED
//RES_ADD_STRING(TXT_SMS_MESSAGE_SETTINGS," Setting")           //replaced by common ID STXT_MAIN_SETTING
#ifdef BROWSER_SUPPORT
RES_ADD_STRING(TXT_SMS_BROWSER_INFO," Brower Info")
#endif
//RES_ADD_STRING(TXT_SET_BROWSER_OPEN," Brower Open")              //replaced by common ID TXT_COMMON_OPEN
//RES_ADD_STRING(TXT_SET_BROWSER_CLOSE," Brower Close")               //replaced by common ID TXT_COMMON_CLOSE   
RES_ADD_STRING(TXT_SMS_MARKNUM," Mark num all")
RES_ADD_STRING(TXT_SMS_CANCEL_MARKNUM," Cancel mark num all")
//RES_ADD_STRING(TXT_SMS_EXTRACT_NUMBER," Extract number")  //replaced by common ID TXT_COMMON_NUMBER
//RES_ADD_STRING(TXT_SMS_EXTRACT_EMAIL," Extract mail")    //replaced by common ID TXT_EMAIL_BOX
//RES_ADD_STRING(TXT_SMS_EXTRACT_NUM_CALL," Call ")
//RES_ADD_STRING(TXT_SMS_EXTRACT_DIAL_IPCALL," IP Call ")
//RES_ADD_STRING(TXT_SMS_ECTRACT_URL_BROWSE," Browse ")     //replaced by common ID TXT_BROWSE
//RES_ADD_STRING(TXT_SMS_EXTRACT_URL_ADD_TO_BOOKMARK," Add to Bookmark ")    //replaced by common ID TXT_ADDTO_BOOKMARK
//RES_ADD_STRING(TXT_SMS_MMS_EDIT_WIN_IN_USED," Add to Bookmark ")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_EXTRACT_URL_ADRESS,"Extract URL")  //replaced by common ID TXT_URL_ADRESS
#ifdef MMI_GUI_STYLE_TYPICAL
RES_ADD_STRING(TXT_SMS_PREVIEW_EXTRACT_OPEN_OR_CLOSE,"Extract URL")   //replaced by common ID TXT_COMMON_CONTENT_EXTRACT
#endif
//RES_ADD_STRING(TXT_SMS_EXTRACT_ON,"ON")         //replaced by common ID TXT_COMMON_ENABLE_ON
//RES_ADD_STRING(TXT_SMS_EXTRACT_OFF,"OFF")                 //replaced by common ID TXT_CLOSE
//RES_ADD_STRING(TXT_SMS_EXTRACT_CALL_SENDER,"Call Sender")      //replaced by common ID TXT_CALL_SENDER
RES_ADD_STRING(TXT_SMS_TOO_LONG_MSG,"Msg is too long,some part lost!")
RES_ADD_STRING(TXT_SMS_ME_MEM_FULL_ALERT_USER,"NV SMS memory full")
RES_ADD_STRING(TXT_SMS_SIM1_MEM_FULL_ALERT_USER,"SIM1 SMS memory full")
RES_ADD_STRING(TXT_SMS_SIM2_MEM_FULL_ALERT_USER,"SIM2 SMS memory full")//case 3:defined but not used, but later find it was used in ++mode
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SMS_SIM3_MEM_FULL_ALERT_USER,"SIM3 SMS memory full")//case 3:defined but not used, but later find it was used in ++mode
#endif
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SMS_SIM4_MEM_FULL_ALERT_USER,"SIM4 SMS memory full")//case 3:defined but not used, but later find it was used in ++mode
#endif
#ifdef MMI_MULTI_SIM_SYS_SINGLE            
RES_ADD_STRING(TXT_SMS_SIM_MEM_FULL_ALERT_USER,"SIM SMS memory full")
#endif
//RES_ADD_STRING(TXT_SMS_BUSY,"System busy, please try later")
//RES_ADD_STRING(TXT_SMS_MOVE,"Move")    //replaced by common ID TXT_MOVE, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_PREVIEW,"Preview Mail")
//RES_ADD_STRING(TXT_SMS_MODIFY_KEY,"Modify Key")    //replaced by common ID TXT_COMMON_MODIFY_PASSWORD
#if defined (MMI_SMS_SECURITYBOX_SUPPORT)
RES_ADD_STRING(TXT_SMS_SECURITY,"Security Mail")
RES_ADD_STRING(MMISMS_INPUT_SECURITY_PASSWORD,"Input Securitybox pwd(1-8)")
RES_ADD_STRING(TXT_SMS_INPUT_NEW_SECURITY_PWD,"Input new pwd(1-8)")
RES_ADD_STRING(TXT_SMS_INPUT_NEW_PWD_CNF,"Input pwd cnf(1-8)")
RES_ADD_STRING(TXT_SMS_MOVE_TO_SECURITY,"Move to security box")
#endif
#if defined(MMI_SMS_EXPORT_SUPPORT)
RES_ADD_STRING(TXT_SMS_EXPORT,"Export SMS")
RES_ADD_STRING(TXT_SMS_EXPORT_INBOX,"INBOX SMS")
RES_ADD_STRING(TXT_SMS_EXPORT_OUTBOX,"OUTBOX SMS")
RES_ADD_STRING(TXT_SMS_EXPORT_DRAFTBOX,"DRAFTBOX SMS")
RES_ADD_STRING(TXT_SMS_EXPORT_SENTBOX,"SENTBOX SMS")
RES_ADD_STRING(TXT_SMS_EXPORT_ALLBOX,"ALLBOX SMS")
RES_ADD_STRING(TXT_SMS_EXPORT_SECLECT_BOX,"Select Export Box")
//RES_ADD_STRING(STXT_EXPORT,"Export") //replaced by common ID TXT_COMM_EXPORT
RES_ADD_STRING(TXT_EXPORT_SETTING_LOC,"Path")
//RES_ADD_STRING(TXT_EXPORT_LOC_SEL,"Select")    //replaced by common ID TXT_SPECIFY
RES_ADD_STRING(TXT_NO_SMS_EXPORT,"No SMS export")
RES_ADD_STRING(TXT_SMS_EXPORT_ALL_QUERY,"Including Securitybox SMS,also export?")
#if defined (MMI_SMS_SECURITYBOX_SUPPORT)
RES_ADD_STRING(TXT_SMS_EXPORT_SECURITYBOX,"SECURITYBOX SMS")
#endif
#ifdef CHATMODE_ONLY_SUPPORT
RES_ADD_STRING(TXT_SMS_EXPORT_CHATBOX,"Chat BOX SMS")
#endif
#endif
//RES_ADD_STRING(TXT_SMS_FLIENAME_INVALID,"Invalid Filename")  //case3:defined but not used
RES_ADD_STRING(TXT_SMS_SAMENUM_DEL,"Delete Same Number")
//RES_ADD_STRING(TXT_SMS_EDIT_EXIT_WITHOUT_SAVE,"Exit without saving")//case 3:defined but not used
//RES_ADD_STRING(TXT_SMS_SAVE_AS_DRAFT,"Save as draft")//replaced by common ID TXT_COMM_SAVE_AS_DRAFT
#if defined(MMI_SMS_FONT_SETTING_SUPPORT)
//RES_ADD_STRING(TXT_SMS_SET_FONT,"Font")  //replaced by common ID TXT_COMMON_FONT_SIZE
//RES_ADD_STRING(TXT_SMS_FONT_BIG,"Big font")  //replaced by common ID TXT_COMM_FONT_BIG
//RES_ADD_STRING(TXT_SMS_FONT_NORMAL,"Normal font")  //replaced by common ID TXT_COMMON_NORMAL
//RES_ADD_STRING(TXT_SMS_FONT_SMALL,"Small font")    //replaced by common ID TXT_FONT_SMALL
#endif
#ifdef SNS_SUPPORT
//RES_ADD_STRING(TXT_SMS_SHARE_TO_SNS,"Share to sns")//case 3:defined but not used
#endif
//for msg del all 11/02/21
#if defined(MMI_SMS_DELALL_SUPPORT)
RES_ADD_STRING(TXT_SMS_MSG_DELALL,"Delete all message")
//RES_ADD_STRING(TXT_SMS_MSG_DEL,"Delete")       //replaced by common ID 
RES_ADD_STRING(TXT_SMS_MSG_DEL_ALLBOXMSG,"All box message")
//RES_ADD_STRING(TXT_SMS_MSG_DEL_PUSH_MSG,"Wap push message")  //replaced by common ID TXT_COMM_PUSH_MSG
RES_ADD_STRING(TXT_SMS_MSG_DEL_OTA_MSG,"Ota message")
RES_ADD_STRING(TXT_SMS_MSG_DEL_MMSDOWNLOAD,"Message Download")
RES_ADD_STRING(TXT_SMS_MSG_DEL_CLEARBOX,"Clear box")
RES_ADD_STRING(TXT_SMS_MSG_DEL_CLEARMSG,"Clear message")
#endif

RES_ADD_STRING(TXT_SMS_MSG_DEL_LOCKED,"Message locked")
RES_ADD_STRING(TXT_SMS_ASKSAVE_DRAFT,"Save as draft?")

#ifdef MMI_SMS_MOVE_SUPPORT
RES_ADD_STRING(TXT_SMS_NO_MSG_MOVE,"No message move")
#endif

#ifdef MMI_SMS_COPY_SUPPORT
RES_ADD_STRING(TXT_SMS_NO_MSG_COPY,"No message copy")
#endif

RES_ADD_STRING(TXT_SMS_LOST_PROMPT,"(......)")
#ifdef MMI_SMS_CHAT_SUPPORT
RES_ADD_STRING(TXT_SMS_CHAT_MODE,"Chat mode")
RES_ADD_STRING(TXT_SMS_CHAT,"Chat")
RES_ADD_STRING(TXT_SMS_NEW_CHAT,"New chat")
#ifdef BT_DIALER_SUPPORT
RES_ADD_STRING(TXT_SMS_BT_CHAT,"BT Chat")
#endif
#endif

#ifdef SMS_AUTO_SIGNATURE_SUPPORT
//RES_ADD_STRING(TXT_SMS_AUTO_SIGNATURE_CONTENT, "Signature")     //replaced by common ID TXT_COMMON_SIGNATURE
#endif

#ifndef MMI_DUALMODE_ENABLE
RES_ADD_STRING(TXT_SMS_CANCEL_SENDING_SUCCESS,"Cancel Successfully")
#endif
#ifdef MMI_VCALENDAR_SUPPORT
RES_ADD_STRING(TXT_SMS_RECEIVE_VCALENDAR_MSG,"Receive Vcalendar")
#endif
#ifdef MMI_TIMERMSG_SUPPORT
RES_ADD_STRING(TXT_SMS_TIMER_MESSAGE,"Timer SMS")
//RES_ADD_STRING(TXT_SMS_TIMER,"Timer")//case 3:defined but not used
RES_ADD_STRING(TXT_SMS_TIMER_SETTINGS,"Timer settings")
RES_ADD_STRING(TXT_TIMERMSG_START, "Saved in outbox for timer sending")
RES_ADD_STRING(TXT_TIMERMSG_SEND_TIME,"Send time")
RES_ADD_STRING(TXT_TIMERMSG_FULL,"Timer SMS exceeded")
RES_ADD_STRING(TXT_SMS_OPEN_TIMER_MESSAGE,"Open Timer SMS")
RES_ADD_STRING(TXT_SMS_CLOSE_TIMER_MESSAGE,"Close Timer SMS")
#endif

#ifndef MMI_GUI_STYLE_TYPICAL
RES_ADD_STRING(TXT_CMSBRW_ACCEPTPUSHMSGSETTING,"Accept push")
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_SMS_READ,"Read message")
#endif
//RES_ADD_STRING(TXT_SMS_SAVE_CONTACT,"Save contacts")  //replaced by common ID TXT_COMM_SAVE_CONTACT
//RES_ADD_STRING(TXT_SMS_WRITE_SMS,"Write SMS")  //replaced by common ID TXT_COMMON_WRITE_SMS
#endif

RES_ADD_STRING(TXT_SMS_UPDATED,"Message updated")
RES_ADD_STRING(TXT_SMS_SENDING_CAN_NOT_DELETE,"Sending sms can not be deleted")
#ifdef MMISMS_CHATMODE_ONLY_SUPPORT
RES_ADD_STRING(TXT_SMS_PUSH_MESSAGE,"Push Message")
#endif
RES_ADD_STRING(TXT_SMS_PUSH_IVALID_CFG, "Invalid push configuration, has been discarded")

#ifdef MMI_SMS_CONCATENATED_SETTING_SUPPORT
RES_ADD_STRING(TXT_SMS_CONCATENATED_SMS,"Concatenated SMS")
#endif
#ifdef MMI_SMS_ALPHABET_SETTING_SUPPORT
RES_ADD_STRING(TXT_SMS_ALPHABET_MANAGEMENT,"Alphabet management")
RES_ADD_STRING(TXT_SMS_ALPHABET_GSM_ALPHABET,"GSM alphabet")
RES_ADD_STRING(TXT_SMS_ALPHABET_8BIT,"8bit")
RES_ADD_STRING(TXT_SMS_ALPHABET_UCS2,"UCS2")
#endif
#ifdef MMI_SMS_REPLY_PATH_SUPPORT
RES_ADD_STRING(TXT_SMS_REPLY_PATH,"Reply path")
RES_ADD_STRING(TXT_SMS_SETTING_STATUS,"Status settings")
#endif
#ifdef MMI_SMS_MULTI_PARAM_SUPPORT
RES_ADD_STRING(TXT_SMS_SIM_SET,"SIM settings")
RES_ADD_STRING(TXT_SMS_SIM1_SET,"SIM1 settings")
RES_ADD_STRING(TXT_SMS_SIM2_SET,"SIM2 settings")
RES_ADD_STRING(TXT_SMS_SIM3_SET,"SIM3 settings")
RES_ADD_STRING(TXT_SMS_SIM4_SET,"SIM4 settings")
RES_ADD_STRING(TXT_SMS_SIM_MODE1,"Mode1")
RES_ADD_STRING(TXT_SMS_SIM_MODE2,"Mode2")
RES_ADD_STRING(TXT_SMS_SIM_MODE3,"Mode3")
RES_ADD_STRING(TXT_SMS_SIM_MODE4,"Mode4")
RES_ADD_STRING(TXT_SMS_SIM_MODE5,"Mode5")
RES_ADD_STRING(TXT_SMS_SIM_MODE6,"Mode6")
RES_ADD_STRING(TXT_SMS_SIM_MODE7,"Mode7")
RES_ADD_STRING(TXT_SMS_SIM_MODE8,"Mode8")
RES_ADD_STRING(TXT_SMS_SIM_MODE9,"Mode9")
RES_ADD_STRING(TXT_SMS_SIM_MODE10,"Mode10")//case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SIM_MODE_NAME,"Mode name")
RES_ADD_STRING(TXT_SMS_SIM_SEND_MODE,"Send mode")
RES_ADD_STRING(TXT_SMS_SIM_SEND_MODE_TEXT,"Text")    //replaced by common ID TXT_TEXT, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SIM_SEND_MODE_VOICE,"Voice")//case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SIM_SEND_MODE_PAGER,"Pager")//case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SIM_SEND_MODE_EMAIL,"Email")//case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SIM_SEND_MODE_ERMES,"Ermes")//case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SIM_SEND_MODE_X400,"X400")//case 3:defined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_SMS_SIM_SEND_MODE_FAX,"Fax")//case 3:defined but not used, but later find it was used in ++mode
#endif
#ifdef MMI_CONCATENATED_SMS_SEND_QUERY_SUPPORT
RES_ADD_STRING(TXT_SMS_SEND_QUERY_HEADR,"This message will be sent as")
RES_ADD_STRING(TXT_SMS_SEND_QUERY_TAIL," separate messages")
#endif
#endif
RES_ADD_STRING(TXT_SMS_SERVICE_LOADING_OPERATION, "Service loading operation")

RES_ADD_STRING(qtn_cb_list_emergency_alert , "Extreme Alerts")
RES_ADD_STRING(qtn_cb_chl_warn_note , "Warning Notification")
RES_ADD_STRING(qtn_cb_chl_info , "Informational")
RES_ADD_STRING(qtn_cb_chl_public_assistance , "Apply for Public assistance")
RES_ADD_STRING(qtn_cb_chl_test , "Test")
RES_ADD_STRING(qtn_cb_chl_exercise , "Exercise")
RES_ADD_STRING(qtn_cb_list_cb_msg , "CB message")
RES_ADD_STRING(qtn_cb_list_ro_cb_msg , "RO-Alert")
RES_ADD_STRING(qtn_outlook_folder_inbox , "Inbox")
RES_ADD_STRING(qtn_cb_chal_title_presidential_alert , "Presidential Alert")
RES_ADD_STRING(qtn_cb_chl_extr_alert, "Extreme Alert")
RES_ADD_STRING(qtn_cb_chal_title_severe_alert, "Severe Alert")
RES_ADD_STRING(qtn_cb_chal_title_org_alert, "Orange Alert")
RES_ADD_STRING(qtn_cb_chal_title_exercise_alert, "Exercise Alert")
RES_ADD_STRING(qtn_cb_item_ro_alert, "RO-Alert")
RES_ADD_STRING(qtn_smstx_list_inbox, "Inbox")
RES_ADD_STRING(qtn_cb_softkey_disable,"Stop using")
RES_ADD_STRING(qtn_cb_softkey_enable,"Use")
RES_ADD_STRING(qtn_cb_settings,"Broadcast settings")
RES_ADD_STRING(TXT_SMS_CB_LIST_NO_NETWORK, "Network Init Failed")
RES_ADD_STRING(qtn_msg_list_call_num_rv,"Call number")
RES_ADD_STRING(text_number_send_sms,"Send message")
RES_ADD_STRING(qtn_cb_message,"Cell broadcast message")

RES_ADD_STRING(TXT_SMS_INSERT_EMOJI, "Insert Emoji")
RES_ADD_STRING(TXT_SMS_EMOJI, "Emoji")
//]]define string infomation
//[[define data infomation
//]]define data infomation
