//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ResOver.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RESOVER_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDB_BMP_FLAG                    129
#define IDB_BMP_BKG                     131
#define IDR_RING                        132
#define IDD_DLG_STAT                    133
#define IDD_DLG_NETWORK_ACCOUNT         134
#define IDD_DLG_BOOKMARK                138
#define IDD_DLG_MULIT_VARIANT           139
#define IDC_BTN_LOAD                    1000
#define IDC_BTN_SAVE                    1001
#define IDC_BTN_HELP                    1002
#define IDC_LST_RES                     1003
#define IDC_CMB_RES_TYPE                1004
#define IDC_BTN_REPLACE                 1005
#define IDC_STC_ITEM_INFO               1006
#define IDC_STC_PREVIEW                 1007
#define IDC_STC_RES_INFO                1008
#define IDC_CMB_THEME                   1009
#define IDC_BTN_UNDO                    1010
#define IDC_LST_STAT                    1010
#define IDC_EDT_MCC                     1011
#define IDC_BTN_LOAD_THM_DIR            1011
#define IDC_EDT_MNC                     1012
#define IDC_BTN_EXPORT_THM_DIR          1012
#define IDC_BTN_IMP_STR                 1013
#define IDC_EDT_UIORDER                 1013
#define IDC_EDT_PORT                    1014
#define IDC_BTN_EXP_STR                 1014
#define IDC_IP_GATEWAY                  1016
#define IDC_CMB_ACCESS_TYPE             1017
#define IDC_CMB_ACCESS_OPTION           1018
#define IDC_CMB_ACCOUNT_TYPE            1020
#define IDC_IP_DNS1                     1021
#define IDC_IP_DNS2                     1022
#define IDC_EDT_HOMEPAGE                1023
#define IDC_EDT_APN                     1024
#define IDC_EDT_USERNAME                1025
#define IDC_EDT_PASSWORD                1026
#define IDC_RDO_PAP                     1027
#define IDC_RDO_CHAP                    1028
#define IDC_RDO_CHAP2                   1029
#define IDC_RDO_NONE                    1029
#define IDC_EDT_SETTING_NAME            1030
#define IDC_BTN_PREV                    1031
#define IDC_BTN_NEXT                    1032
#define IDC_RDO_PAPCHAP                 1034
#define IDC_CHK_ACTIVE                  1036
#define IDC_STC_POS                     1037
#define IDC_STC_USED                    1038
#define IDC_BTN_IMPORT                  1039
#define IDC_BTN_EXPORT                  1040
#define IDC_DBS_CHK_STATE1              1042
#define IDC_DBS_EDT_NAME1               1043
#define IDC_DBS_EDT_URL1                1044
#define IDC_DBS_CHK_STATE2              1045
#define IDC_EDT_VOICEMAIL_2             1045
#define IDC_DBS_EDT_NAME2               1046
#define IDC_EDT_VOICEMAIL_3             1046
#define IDC_DBS_EDT_URL2                1047
#define IDC_EDT_VOICEMAIL_4             1047
#define IDC_DBS_CHK_STATE3              1048
#define IDC_EDT_VOICEMAIL_5             1048
#define IDC_DBS_EDT_NAME3               1049
#define IDC_EDT_VOICEMAIL_6             1049
#define IDC_DBS_EDT_URL3                1050
#define IDC_EDT_VOICEMAIL_7             1050
#define IDC_DBS_CHK_STATE4              1051
#define IDC_EDT_VOICEMAIL_8             1051
#define IDC_DBS_EDT_NAME4               1052
#define IDC_EDT_VOICEMAIL_9             1052
#define IDC_DBS_EDT_URL4                1053
#define IDC_EDT_VOICEMAIL_10            1053
#define IDC_DBS_CHK_STATE5              1054
#define IDC_DBS_EDT_NAME5               1055
#define IDC_DBS_EDT_URL5                1056
#define IDC_DBS_CHK_STATE6              1057
#define IDC_DBS_EDT_NAME6               1058
#define IDC_DBS_EDT_URL6                1059
#define IDC_DBS_CHK_STATE7              1060
#define IDC_DBS_EDT_NAME7               1061
#define IDC_DBS_EDT_URL7                1062
#define IDC_DBS_CHK_STATE8              1063
#define IDC_DBS_EDT_NAME8               1064
#define IDC_DBS_EDT_URL8                1065
#define IDC_EDT_ECALL_2                 1065
#define IDC_DBS_CHK_STATE9              1066
#define IDC_EDT_ECALL_3                 1066
#define IDC_DBS_EDT_NAME9               1067
#define IDC_EDT_ECALL_4                 1067
#define IDC_DBS_EDT_URL9                1068
#define IDC_EDT_ECALL_5                 1068
#define IDC_DBS_CHK_STATE10             1069
#define IDC_EDT_ECALL_6                 1069
#define IDC_DBS_EDT_NAME10              1070
#define IDC_EDT_ECALL_7                 1070
#define IDC_DBS_EDT_URL10               1071
#define IDC_EDT_ECALL_8                 1071
#define IDC_DBS_BTN_PREV                1072
#define IDC_EDT_ECALL_9                 1072
#define IDC_DBS_STC_POS                 1073
#define IDC_EDT_ECALL_10                1073
#define IDC_DBS_BTN_NEXT                1074
#define IDC_MVS_BTN_PREV                1074
#define IDC_DBS_STC_USED                1075
#define IDC_MVS_BTN_NEXT                1075
#define IDC_DBS_BTN_IMPORT              1076
#define IDC_MVS_STC_POS                 1076
#define IDC_DBS_BTN_EXPORT              1077
#define IDC_BTN_INSERT_HEAD             1078
#define IDC_MVS_BTN_IMPORT              1078
#define IDC_BTN_INSERT_BEFORE           1079
#define IDC_MVS_BTN_EXPORT              1079
#define IDC_BTN_INSERT_AFTER            1080
#define IDC_BTN_INSERT_TAIL             1081
#define IDC_EDIT_PAGENUM                1082
#define IDC_BTN_IST_NTAC                1083
#define IDC_BTN_GO                      1084
#define IDC_BTC_EDT_NTAC                1085
#define IDC_BTN_EDT_BKMK                1086
#define IDC_PROG                        1087
#define IDC_EDT_SPN                     1088
#define IDC_BTC_EDT_MTVA                1088
#define IDC_EDT_VOICEMAIL_1             1089
#define IDC_EDT_ECALL_1                 1090
#define IDC_MVS_EDT_MCC                 1091
#define IDC_MVS_EDT_MNC                 1092
#define IDC_MVS_EDT_URL                 1093
#define IDC_BMK_EDT_MCC                 1094
#define IDC_BMK_EDT_MCC1                1094
#define IDC_BMK_EDT_MNC                 1095
#define IDC_BMK_EDT_MNC1                1095
#define IDC_BMK_EDT_MCC2                1096
#define IDC_BMK_EDT_MNC2                1097
#define IDC_BMK_EDT_MCC3                1098
#define IDC_BMK_EDT_MNC3                1099
#define IDC_COMBO1                      1099
#define IDC_IP_TYPE                     1099
#define IDC_BMK_EDT_MCC4                1100
#define IDC_BMK_EDT_MNC4                1101
#define IDC_CHECK_VISIBLE               1101
#define IDC_BMK_EDT_MCC5                1102
#define IDC_CHECK2                      1102
#define IDC_CHECK_ROAMING               1102
#define IDC_BMK_EDT_MNC5                1103
#define IDC_COMBO_ROAMING_PROTOCOL      1103
#define IDC_BMK_EDT_MCC6                1104
#define IDC_COMBO3                      1104
#define IDC_COMBO_MVNO_TYPE             1104
#define IDC_BMK_EDT_MNC6                1105
#define IDC_BMK_EDT_MCC7                1106
#define IDC_BMK_EDT_MNC7                1107
#define IDC_BMK_EDT_MCC8                1108
#define IDC_BMK_EDT_MNC8                1109
#define IDC_BMK_EDT_MCC9                1110
#define IDC_BMK_EDT_MNC9                1111
#define IDC_BMK_EDT_MCC10               1112
#define IDC_BMK_EDT_MNC10               1113

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
