

//[[define image infomation

/////////////////////////////////////////////////////////////////////////////////
//主菜单图标资源
/////////////////////////////////////////////////////////////////////////////////
#ifdef HERO_APP_TALKCAT_OPEN
//TALKCAT
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_TALKCAT,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_TALKCAT.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_SKIRT_OPEN
//SKIRT
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_SKIRT,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_SKIRT.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_BIRD_OPEN
//BIRD
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_BIRD,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_BIRD.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_FRUIT_OPEN
//FRUIT
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_FRUIT,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_FRUIT.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_BYDR_OPEN
//捕鱼达人
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_BYDR,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_BYDR.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_POPS_OPEN
//Pop star
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_POPS,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_POPS.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_RAXC_OPEN
//Pop star
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_RAXC,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_RAXC.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_DODGE_OPEN
//Pop star
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_DODGE,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_DODGE.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_PVZ_OPEN
//植物大战僵尸
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_PVZ,"\\MMI_RES_##\\IMAG\\PVZ.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_GXLZJ_OPEN
//枭龙战机
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_XLZJ,"\\MMI_RES_##\\IMAG\\xlzj.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_READER_OPEN
//电子书
//RES_ADD_IMG(IMG_HERO_APP_MAINMENU_READER,"\\MMI_RES_##\\IMAG\\img_defualt.bmp",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_WEATHER_OPEN
//天气预报
//RES_ADD_IMG(IMG_HERO_APP_MAINMENU_WEATHER,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_TWITTER.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_SUDOKU_OPEN
//数独
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_SUDOKU,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_SHUDU.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_STONE_OPEN
//stone
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_STONE,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_RSTONE.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_NEWS_OPEN
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_NEWS,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_YAHOO.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_BROWSER_OPEN
//RES_ADD_IMG(IMG_HERO_APP_MAINMENU_BROWSER,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_TWITTER.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_FACETALK_OPEN
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_FACETALK,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_FACETALK.png",IMG_CMP_PNG_ARGB,0)
#endif

#ifdef HERO_APP_OLALA_OPEN
RES_ADD_IMG(IMG_HERO_APP_MAINMENU_OLALA,"\\MMI_RES_##\\IMAG\\IMAGE_HERO_APP_OLALA.png",IMG_CMP_PNG_ARGB,0)
#endif

/////////////////////////////////////////////////////////////////////////////////
//后台运行图标资源
/////////////////////////////////////////////////////////////////////////////////

//RES_ADD_IMG(IMG_HERO_APP_ONLINE,"\\MMI_RES_##\\IMAG\\img_defualt.bmp",IMG_CMP_PNG_ARGB,0)

//RES_ADD_IMG(IMG_HERO_APP_OFFLINE,"\\MMI_RES_##\\IMAG\\img_defualt.bmp",IMG_CMP_PNG_ARGB,0)

//RES_ADD_IMG(IMG_HERO_APP_HIDE,"\\MMI_RES_##\\IMAG\\img_defualt.bmp",IMG_CMP_PNG_ARGB,0)

//RES_ADD_IMG(IMG_HERO_APP_AWAY,"\\MMI_RES_##\\IMAG\\img_defualt.bmp",IMG_CMP_PNG_ARGB,0)

//]]define image infomation

//[[define anim infomation
//RES_ADD_ANIM(IMAGE_SMS_SENDING_ANIM,"\\MMI_RES_##\\ANIM\\IMAGE_SMS_SENDING_ANIM",AT_COMPRESS_STREAM,75,0x000000)
//]]define anim infomation


//[[define string infomation
RES_ADD_STRING(TXT_HERO_APP_TALKCAT,"TalkCat")
RES_ADD_STRING(TXT_HERO_APP_SKIRT,"Skirt")
RES_ADD_STRING(TXT_HERO_APP_BIRD,"AngryBird")
RES_ADD_STRING(TXT_HERO_APP_FRUIT,"FruitNinja")
RES_ADD_STRING(TXT_HERO_APP_BYDR,"FishingJoy")
RES_ADD_STRING(TXT_HERO_APP_PVZ,"PVZ")
RES_ADD_STRING(TXT_HERO_APP_XLZJ,"XLZJ")
RES_ADD_STRING(TXT_HERO_APP_STONE,"Stone")
RES_ADD_STRING(TXT_HERO_APP_SUDOKU,"Sudoku")
RES_ADD_STRING(TXT_HERO_APP_NEWS,"News")
RES_ADD_STRING(TXT_HERO_APP_POPS,"PopStar")
RES_ADD_STRING(TXT_HERO_APP_RAXC,"PopPet")
RES_ADD_STRING(TXT_HERO_APP_DODGE,"Dodge")
RES_ADD_STRING(TXT_HERO_APP_OLALA,"Olala")
RES_ADD_STRING(TXT_HERO_APP_BROWSER,"浏览器")
RES_ADD_STRING(TXT_HERO_APP_SMART,"语音助手")
RES_ADD_STRING(TXT_HERO_APP_TIPS,"Tips")
RES_ADD_STRING(TXT_HERO_SMART_HELP,"按住OK键录入语音，松掉OK键完成录音，语音助手就能实现您所说的功能。比如您可以说“打开相机”、“今天天气如何”、“下午三点提醒我”、“打电话给小明”、“给我讲个笑话”、“我在哪里”等，您还可以通过上下方向键调节音量大小，通过菜单")
RES_ADD_STRING(TXT_HERO_APP_READER,"电子书")
RES_ADD_STRING(TXT_HERO_APP_WEATHER,"天气预报")
RES_ADD_STRING(TXT_HERO_APP_TIME,"网络对时")
RES_ADD_STRING(TXT_HERO_APP_HMGS,"号码归属地")
#if defined(HERO_APP_WSTORE_OPEN)
RES_ADD_STRING(TXT_HERO_APP_WSTORE,"应用商城")
RES_ADD_STRING(TXT_HERO_APP_WSTORE_MANAGE,"应用管理")
#endif
#ifdef HERO_APP_SHORTCUT_SUPPORT
RES_ADD_STRING(TXT_HERO_APP_EMPTY,"Empty")
#endif
RES_ADD_STRING(TXT_HERO_APP_NES,"Nes")

#ifdef HERO_ENGINE_FAMILY_SUPPORT
RES_ADD_STRING(TXT_HERO_APP_FAMILY,"小沐家园")
RES_ADD_STRING(TXT_HERO_FAMILY_NEWMSG,"您的小沐聊天有一条新消息")
#endif

RES_ADD_STRING(TXT_HERO_TTS,"语音王")
RES_ADD_STRING(TXT_HERO_TTS_SET_VOLUME,"设置音量")
RES_ADD_STRING(TXT_HERO_TTS_VOLUME_1,"音量1")
RES_ADD_STRING(TXT_HERO_TTS_VOLUME_2,"音量2")
RES_ADD_STRING(TXT_HERO_TTS_VOLUME_3,"音量3")
RES_ADD_STRING(TXT_HERO_TTS_VOLUME_4,"音量4")
RES_ADD_STRING(TXT_HERO_TTS_VOLUME_5,"音量5")
RES_ADD_STRING(TXT_HERO_TTS_VOLUME_6,"音量6")
RES_ADD_STRING(TXT_HERO_TTS_VOLUME_7,"音量7")
RES_ADD_STRING(TXT_HERO_TTS_VOLUME_8,"音量8")
RES_ADD_STRING(TXT_HERO_TTS_VOLUME_9,"音量9")
RES_ADD_STRING(TXT_HERO_TTS_SET_PHB,"电话本朗读")
RES_ADD_STRING(TXT_HERO_TTS_SET_SMS,"短信息朗读")
RES_ADD_STRING(TXT_HERO_TTS_SET_DIAL,"按键报号")
RES_ADD_STRING(TXT_HERO_TTS_SET_AKEY_TIME,"一键报时")
RES_ADD_STRING(TXT_HERO_TTS_SET_AKEY_TIME_MENU,"一键报时说明")
RES_ADD_STRING(TXT_HERO_TTS_SET_7_AKEY_TIME_HELP,"待机界面长按7键即可启动一键报时功能。")
RES_ADD_STRING(TXT_HERO_TTS_SET_8_AKEY_TIME_HELP,"待机界面长按8键即可启动一键报时功能。")
RES_ADD_STRING(TXT_HERO_TTS_SET_9_AKEY_TIME_HELP,"待机界面长按9键即可启动一键报时功能。")
RES_ADD_STRING(TXT_HERO_TTS_SET_0_AKEY_TIME_HELP,"待机界面长按0键即可启动一键报时功能。")
RES_ADD_STRING(TXT_HERO_TTS_SET_STAR_AKEY_TIME_HELP,"待机界面长按*键即可启动一键报时功能。")
RES_ADD_STRING(TXT_HERO_TTS_SET_AUTO_TIME,"整点报时")
RES_ADD_STRING(TXT_HERO_TTS_SET_NEW_SMS,"新短信提醒")
RES_ADD_STRING(TXT_HERO_TTS_SET_INCOMING,"来电报号")
RES_ADD_STRING(TXT_HERO_TTS_SET_MENU,"菜单朗读")
RES_ADD_STRING(TXT_HERO_TTS_SET_AUTO_TIME_QUANTUM_MODE,"时间段控制")
RES_ADD_STRING(TXT_HERO_TTS_SET_AUTO_TIME_MODE_WHOLE_DAY,"全天模式")
RES_ADD_STRING(TXT_HERO_TTS_SET_AUTO_TIME_MODE_DAY,"白天模式(8:00-18:00)")
RES_ADD_STRING(TXT_HERO_TTS_SET_AUTO_TIME_MODE_NIGHT,"夜晚模式(18:00-23:00)")
RES_ADD_STRING(TXT_HERO_TTS_SET_AUTO_TIME_MODE_CUSTOM,"自定义模式")
RES_ADD_STRING(TXT_HERO_TTS_SET_AUTO_TIME_START_TIME,"开始时间(24时制)")
RES_ADD_STRING(TXT_HERO_TTS_SET_AUTO_TIME_END_TIME,"结束时间(24时制)")
RES_ADD_STRING(TXT_HERO_TTS_SET_CHARGE,"充电器插拔提醒")
RES_ADD_STRING(TXT_HERO_TTS_SET_LOW_POWER,"低电量提醒")
RES_ADD_STRING(TXT_HERO_TTS_SET_LOCK_SCREEN,"解锁屏提醒")
RES_ADD_STRING(TXT_HERO_TTS_SET_AKEY_POWER_LEVEL,"一键报电量")
RES_ADD_STRING(TXT_HERO_TTS_SET_AKEY_POWER_LEVEL_MENU,"一键报电量说明")
RES_ADD_STRING(TXT_HERO_TTS_SET_INCOMING_1,"播报一次")
RES_ADD_STRING(TXT_HERO_TTS_SET_INCOMING_5,"播报五次")
RES_ADD_STRING(TXT_HERO_TTS_SET_INCOMING_999,"重复播报")
RES_ADD_STRING(TXT_HERO_TTS_SET_INCOMING_0,"关闭播报")
RES_ADD_STRING(TXT_HERO_TTS_SET_STAR_AKEY_POWER_LEVEL_HELP,"待机界面长按*键即可启动一键报电量功能。")
RES_ADD_STRING(TXT_HERO_TTS_SET_9_AKEY_POWER_LEVEL_HELP,"待机界面长按9键即可启动一键报电量功能。")
RES_ADD_STRING(TXT_HERO_TTS_SET_AKEY_POWER_LEVEL_TEXT,"您的手机剩余电量，百分之")
RES_ADD_STRING(TXT_HERO_TTS_SET_AKEY_POWER_LEVEL_TEXT_90,"您的手机电量充足，请放心使用，祝您愉快")
RES_ADD_STRING(TXT_HERO_TTS_SET_AKEY_POWER_LEVEL_TEXT_20,"您的手机电量不足，请尽快充电，以保持手机畅通")
RES_ADD_STRING(TXT_HERO_TTS_CHARGE_CONNECT,"充电器已连接")
RES_ADD_STRING(TXT_HERO_TTS_CHARGE_REMOVE,"充电器已移除")
RES_ADD_STRING(TXT_HERO_TTS_CHARGE_USB_CONNECT,"USB已连接")
RES_ADD_STRING(TXT_HERO_TTS_CHARGE_USB_REMOVE,"USB已移除")
RES_ADD_STRING(TXT_HERO_TTS_CHARGE_WARNING,"电池电量低，请及时充电")
RES_ADD_STRING(TXT_HERO_TTS_CHARGE_END,"充电完成")
RES_ADD_STRING(TXT_HERO_TTS_CHARGE_OVER_VOLTAGE,"充电电压过大")
RES_ADD_STRING(TXT_HERO_TTS_LOCK_SCREEN_LOCKED,"已上锁")
RES_ADD_STRING(TXT_HERO_TTS_LOCK_SCREEN_UNLOCKED,"已解锁")
RES_ADD_STRING(TXT_HERO_TTS_INCOMING_CALL_STRING," 给您来电 ，。")

RES_ADD_STRING(TXT_HERO_SHOW_FACTORY_INFO, "Version Info")
#ifdef HERO_ENGINE_FM_SUPPORT
RES_ADD_STRING(TXT_HERO_APP_FM, "网络FM")
#endif
#ifdef HERO_ENGINE_STVIDEO_SUPPORT
RES_ADD_STRING(TXT_HERO_APP_STVIDEO, "短视频")
#endif
//]]define string infomation

//[[define data infomation
//RES_ADD_DATA(R_ACC_MPLOC1,"\\MMI_RES_##\\DATA\\R_ACC_MPLOC1")
//]]define data infomation
