/*
 * Copyright (C) 2021 UNISOC Technologies Co.,Ltd. All Rights Reserved
 *
 * Automatically generated by code_generator_unirtos.pm.
*/

#include "sci_types.h"
#include "os_api.h"
#include "mmk_app.h"
#include "mmk_type.h"
#include "caf.h"
#include "ctrlbutton_export.h"
#include "guianim.h"
#include "ctrlbase.h"
#include "urjs_art.h"

#include "mmi_image.h"

#include "watchface_image.h"

#include "watchface_ctrl_adapter.h"
#include "ctrlwf_export.h"

uint32 js_native_watchface_image_create(uint32 this_value, uint32 win_handle, double center_x, double center_y, char* img_path, double scale){
    WATCHFACE_RATIO_POSITION_T position = {0};
    WATCHFACE_CTRL_PARAM_T     ctrl_param = {0};
    position.ratio_x = center_x;
    position.ratio_y = center_y;
    char path[MAX_PATH] = {0};

    if (-1 == js_jee_get_native_path(img_path, path, sizeof(path) - 1))
    {
        aloge("invalidate path: %s", img_path);
        return -1;
    }
    ctrl_param.center_position.ratio_x = position.ratio_x;
    ctrl_param.center_position.ratio_y = position.ratio_y;
    ctrl_param.scale = scale;
    ctrl_param.p_image_list[0] = path;
    return WATCHFACE_Img_Create(win_handle, &ctrl_param);}

void js_native_watchface_image_destory(uint32 handle){
    WATCHFACE_Img_Destory(handle);
}
