
#ifdef JPG_DEC_SUPPORT_JPG_HW
#define IMAGE_RTMP_JPG_FMT   IMG_CMP_JPG_SCI
#else
#define IMAGE_RTMP_JPG_FMT   IMG_CMP_JPG_STD
#endif

//[[define image information
RES_ADD_STRING(TXT_RTMP_PLAYING,"Playing")

//RES_ADD_IMG(IMAGE_RTMP_BTN_DEFAULT, "\\MMI_RES_##\\IMAG\\btn_default.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RTMP_BTN_ANIM_1, "\\MMI_RES_##\\IMAG\\playing1.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RTMP_BTN_ANIM_2, "\\MMI_RES_##\\IMAG\\playing2.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RTMP_BTN_ANIM_3, "\\MMI_RES_##\\IMAG\\playing3.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RTMP_BTN_ANIM_4, "\\MMI_RES_##\\IMAG\\playing4.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RTMP_BTN_ANIM_5, "\\MMI_RES_##\\IMAG\\playing5.png", IMG_CMP_PNG_ARGB_RLE, 0)
//]]define image information


