
//[[define image information
	//RES_ADD_IMG(IMAGE_BT_SEARCH_STOP, "\\MMI_RES_##\\IMAG\\IMAGE_BT_SEARCH_STOP.bmp",IMG_CMP_BMP_16_565_RLE,0)

	RES_ADD_IMG(IMAGE_PEDOMETER_COUNT,"\\MMI_RES_##\\IMAG\\pedometer_count.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_PEDOMETER_BG,"\\MMI_RES_##\\IMAG\\pedometer_count_bg.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_PEDOMETER_WEEK_BG,"\\MMI_RES_##\\IMAG\\pedometer_week_bg.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_PEDOMETER_WEEK_SPLIT,"\\MMI_RES_##\\IMAG\\pedometer_week_split.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_PEDOMETER_TOTAL,"\\MMI_RES_##\\IMAG\\pedometer_week_total.png", IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMAGE_PEDOMETER_ROUND,"\\MMI_RES_##\\IMAG\\pedometer_round.png", IMG_CMP_PNG_ARGB_RLE,0)
//]]define image information



//[[define anim information


//]]define anim information


//[[define string information


	RES_ADD_STRING(TXT_PEDOMETER_APP_NAME,"计步")
	RES_ADD_STRING(TXT_PEDOMETER_EXERCISE_TODAY,"今日运动")
	RES_ADD_STRING(TXT_PEDOMETER_STEP,"步")
	RES_ADD_STRING(TXT_PEDOMETER_DISTANCE,"距离(千米)")
	RES_ADD_STRING(TXT_PEDOMETER_CALORIES,"热量(大卡)")

	RES_ADD_STRING(TXT_PEDOMETER_STEP_WEEK,"周步数统计")
	RES_ADD_STRING(TXT_PEDOMETER_STEP_LIST,"好友排行榜")
	RES_ADD_STRING(TXT_PEDOMETER_ME,"我")
	RES_ADD_STRING(TXT_PEDOMETER_NO_FIREND,"还没有好友哦")
	RES_ADD_STRING(TXT_PEDOMETER_NO_NET,"网络未连接")
	RES_ADD_STRING(TXT_PEDOMETER_LOADING_DATA,"正在加载..")
	RES_ADD_STRING(TXT_PEDOMETER_VALUE_DATA_NONE,"0.00")

	RES_ADD_STRING(TXT_PEDOMETER_COUNT,"当前步数")
	RES_ADD_STRING(TXT_PEDOMETER_TARGET,"目标: %N")
	RES_ADD_STRING(TXT_PEDOMETER_KAL,"公里")
	RES_ADD_STRING(TXT_PEDOMETER_CAL,"千卡")
	RES_ADD_STRING(TXT_PEDOMETER_WEEK_STEP,"本周计步")
	RES_ADD_STRING(TXT_PEDOMETER_1,"一")
	RES_ADD_STRING(TXT_PEDOMETER_2,"二")
	RES_ADD_STRING(TXT_PEDOMETER_3,"三")
	RES_ADD_STRING(TXT_PEDOMETER_4,"四")
	RES_ADD_STRING(TXT_PEDOMETER_5,"五")
	RES_ADD_STRING(TXT_PEDOMETER_6,"六")
	RES_ADD_STRING(TXT_PEDOMETER_7,"日")

//]]define string information