#ifndef __PRIORITY_SYSTEM_H__
#define __PRIORITY_SYSTEM_H__

#include "os_api.h"
#include "priority_kernel.h"

DECLARE_PRIORITY(PRI_DIAG)
#define  PRI_DIAG                         SCI_TASK_PRI(PRI_DIAG)

DECLARE_PRIORITY(PRI_EFS)
#define  PRI_EFS                         SCI_TASK_PRI(PRI_EFS)

DECLARE_PRIORITY(PRI_KPDSVR)
#define  PRI_KPDSVR                   SCI_TASK_PRI(PRI_KPDSVR)

DECLARE_PRIORITY(PRI_TIMESVR)
#define  PRI_TIMESVR                  SCI_TASK_PRI(PRI_TIMESVR)

DECLARE_PRIORITY(PRI_AUDIO)
#define  PRI_AUDIO                    SCI_TASK_PRI(PRI_AUDIO)

DECLARE_PRIORITY(PRI_TP)
#define  PRI_TP                          SCI_TASK_PRI(PRI_TP)

DECLARE_PRIORITY(PRI_BT_SBC)
#define  PRI_BT_SBC                   SCI_TASK_PRI(PRI_BT_SBC)

DECLARE_PRIORITY(PRI_BT_TASK)
#define  PRI_BT_TASK                  SCI_TASK_PRI(PRI_BT_TASK)

DECLARE_PRIORITY(PRI_FFS)
#define  PRI_FFS                      SCI_TASK_PRI(PRI_FFS)

DECLARE_PRIORITY(PRI_RECORD)
#define  PRI_RECORD                   SCI_TASK_PRI(PRI_RECORD)

DECLARE_PRIORITY(PRI_BT_FTP)
#define  PRI_BT_FTP                   SCI_TASK_PRI(PRI_BT_FTP)

DECLARE_PRIORITY(PRI_BT_TIMEOUT)
#define  PRI_BT_TIMEOUT              SCI_TASK_PRI(PRI_BT_TIMEOUT)

DECLARE_PRIORITY(PRI_DV_DISPLAY)                                      
#define	 PRI_DV_DISPLAY               SCI_TASK_PRI(PRI_DV_DISPLAY)

DECLARE_PRIORITY(PRI_DV_AUDIO)
#define	 PRI_DV_AUDIO                 SCI_TASK_PRI(PRI_DV_AUDIO)

DECLARE_PRIORITY(PRI_DV_DEMUX)
#define	 PRI_DV_DEMUX                 SCI_TASK_PRI(PRI_DV_DEMUX)

DECLARE_PRIORITY(PRI_DV_VIDEO)
#define	 PRI_DV_VIDEO                 SCI_TASK_PRI(PRI_DV_VIDEO)

DECLARE_PRIORITY(PRI_DV_MUX)
#define	 PRI_DV_MUX                   SCI_TASK_PRI(PRI_DV_MUX)

DECLARE_PRIORITY(PRI_SCM)                                     
#define	 PRI_SCM                       SCI_TASK_PRI(PRI_SCM)

DECLARE_PRIORITY(PRI_SMCODEC)                                      
#define  PRI_SMCODEC                  SCI_TASK_PRI(PRI_SMCODEC)

DECLARE_PRIORITY(PRI_UCOM_MAIN)         
#define  PRI_UCOM_MAIN                SCI_TASK_PRI(PRI_UCOM_MAIN)

DECLARE_PRIORITY(PRI_UMEM_HANDLE)
#define  PRI_UMEM_HANDLE              SCI_TASK_PRI(PRI_UMEM_HANDLE)

DECLARE_PRIORITY(PRI_UMEM_GARBAGECOLLECT)
#define  PRI_UMEM_GARBAGECOLLECT      SCI_TASK_PRI(PRI_UMEM_GARBAGECOLLECT)

DECLARE_PRIORITY(PRI_USB_VBUS)
#define  PRI_USB_VBUS                 SCI_TASK_PRI(PRI_USB_VBUS)

DECLARE_PRIORITY(PRI_USB_SERVICE)
#define  PRI_USB_SERVICE              SCI_TASK_PRI(PRI_USB_SERVICE)

DECLARE_PRIORITY(PRI_STL_COMPACTION)         
#define  PRI_STL_COMPACTION           SCI_TASK_PRI(PRI_STL_COMPACTION)

DECLARE_PRIORITY(PRI_GPIO_INDEXXT)         
#define  PRI_GPIO_INDEXXT            SCI_TASK_PRI(PRI_GPIO_INDEXXT)

DECLARE_PRIORITY(PRI_AUDIO_CODEC_LOW)                                      
#define  PRI_AUDIO_CODEC_LOW          SCI_TASK_PRI(PRI_AUDIO_CODEC_LOW)

DECLARE_PRIORITY(PRI_AUDIO_CODEC_HIGH)
#define  PRI_AUDIO_CODEC_HIGH        SCI_TASK_PRI(PRI_AUDIO_CODEC_HIGH)

DECLARE_PRIORITY(PRI_WIFI_PRIO_1) 
DECLARE_PRIORITY(PRI_WIFI_PRIO_2) 
DECLARE_PRIORITY(PRI_WIFI_PRIO_3) 
DECLARE_PRIORITY(PRI_WIFI_PRIO_4) 
#define  PRI_WIFI_PRIO(_X_)           SCI_TASK_PRI(PRI_WIFI_PRIO_##_X_)

DECLARE_PRIORITY(PRI_BMP_TASK)                                      
#define  PRI_BMP_TASK                SCI_TASK_PRI(PRI_BMP_TASK)

DECLARE_PRIORITY(PRI_DCAMERA_TASK)                                      
#define  PRI_DCAMERA_TASK             SCI_TASK_PRI(PRI_DCAMERA_TASK)

DECLARE_PRIORITY(PRI_FMARK_TASK)                                      
#define  PRI_FMARK_TASK               SCI_TASK_PRI(PRI_FMARK_TASK)

DECLARE_PRIORITY(PRI_GIF_DECODE_TASK)                                      
#define  PRI_GIF_DECODE_TASK          SCI_TASK_PRI(PRI_GIF_DECODE_TASK)

DECLARE_PRIORITY(PRI_VT_MIDDLEWARE_TASK)                                      
#define  PRI_VT_MIDDLEWARE_TASK      SCI_TASK_PRI(PRI_VT_MIDDLEWARE_TASK)

DECLARE_PRIORITY(PRI_VT_LOOP_TASK)         
#define  PRI_VT_LOOP_TASK             SCI_TASK_PRI(PRI_VT_LOOP_TASK)

DECLARE_PRIORITY(PRI_UPCC_MAIN_TASK)                                      
#define  PRI_UPCC_MAIN_TASK          SCI_TASK_PRI(PRI_UPCC_MAIN_TASK)

DECLARE_PRIORITY(PRI_UPCC_DRV_TASK)                                      
#define  PRI_UPCC_DRV_TASK           SCI_TASK_PRI(PRI_UPCC_DRV_TASK)

DECLARE_PRIORITY(PRI_UBOT_MAIN)
        
#define  PRI_UBOT_MAIN               SCI_TASK_PRI(PRI_UBOT_MAIN)

DECLARE_PRIORITY(PRI_APP)        
#define  PRI_APP                 SCI_TASK_PRI(PRI_APP)
                                      
DECLARE_PRIORITY(PRI_APP_TASK)        
#define  PRI_APP_TASK                 SCI_TASK_PRI(PRI_APP_TASK)
//Auto demo task 
#ifdef AUTODEMO_SUPPORT
DECLARE_PRIORITY(PRI_AUTODEMO_TASK)        
#define  PRI_AUTODEMO_TASK                 SCI_TASK_PRI(PRI_AUTODEMO_TASK)
#endif

DECLARE_PRIORITY(PRI_APP_INIT_TASK)                                      
#define  PRI_APP_INIT_TASK           SCI_TASK_PRI(PRI_APP_INIT_TASK)

DECLARE_PRIORITY(PRI_UCOM_ORG_TASK)         
#define  PRI_UCOM_ORG_TASK           SCI_TASK_PRI(PRI_UCOM_ORG_TASK)

DECLARE_PRIORITY(PRI_UCOM_DES_TASK)
#define  PRI_UCOM_DES_TASK            SCI_TASK_PRI(PRI_UCOM_DES_TASK)

DECLARE_PRIORITY(PRI_CPU_MONITOR)         
#define  PRI_CPU_MONITOR              SCI_TASK_PRI(PRI_CPU_MONITOR)

DECLARE_PRIORITY(PRI_ISP_SERVICE_TASK)         
#define  PRI_ISP_SERVICE_TASK        SCI_TASK_PRI(PRI_ISP_SERVICE_TASK)

DECLARE_PRIORITY(PRI_IMG_PROC_CTRL_TASK)         
#define  PRI_IMG_PROC_CTRL_TASK        SCI_TASK_PRI(PRI_IMG_PROC_CTRL_TASK)

DECLARE_PRIORITY(PRI_IMG_PROC_PROCESS_TASK)         
#define  PRI_IMG_PROC_PROCESS_TASK        SCI_TASK_PRI(PRI_IMG_PROC_PROCESS_TASK)

DECLARE_PRIORITY(PRI_SYSTEM_KERNEL)         
#define  PRI_SYSTEM_KERNEL            SCI_TASK_PRI(PRI_SYSTEM_KERNEL)

DECLARE_PRIORITY(PRI_IMG_DEC)
#define  PRI_IMG_DEC                       SCI_TASK_PRI(PRI_IMG_DEC)

DECLARE_PRIORITY(PRI_IMG_DEC_TASK)
#define  PRI_IMG_DEC_TASK              SCI_TASK_PRI(PRI_IMG_DEC_TASK)

DECLARE_PRIORITY(PRI_IMG_SCALE_TASK)
#define  PRI_IMG_SCALE_TASK         SCI_TASK_PRI(PRI_IMG_SCALE_TASK)

DECLARE_PRIORITY(PRI_IMG_DEC_CONFIG)
#define  PRI_IMG_DEC_CONFIG         SCI_TASK_PRI(PRI_IMG_DEC_CONFIG)

DECLARE_PRIORITY(PRI_IMG_JPEG_DEC_TASK)
#define  PRI_IMG_JPEG_DEC_TASK      SCI_TASK_PRI(PRI_IMG_JPEG_DEC_TASK)

DECLARE_PRIORITY(PRI_JPEG_TASK)
#define  PRI_JPEG_TASK                    SCI_TASK_PRI(PRI_JPEG_TASK)

DECLARE_PRIORITY(PRI_JPEG_TASK_HW_DEFAULT)
#define  PRI_JPEG_TASK_HW_DEFAULT            SCI_TASK_PRI(PRI_JPEG_TASK_HW_DEFAULT)

DECLARE_PRIORITY(PRI_VOICE_UPLINK_TASK)
#define  PRI_VOICE_UPLINK_TASK         SCI_TASK_PRI(PRI_VOICE_UPLINK_TASK)

DECLARE_PRIORITY(PRI_VOICE_DOWNLINK_TASK)
#define  PRI_VOICE_DOWNLINK_TASK         SCI_TASK_PRI(PRI_VOICE_DOWNLINK_TASK)

DECLARE_PRIORITY(PRI_VOICE_RECORD_DEBUG_DATA_TASK)
#define  PRI_VOICE_RECORD_DEBUG_DATA_TASK       SCI_TASK_PRI(PRI_VOICE_RECORD_DEBUG_DATA_TASK)

DECLARE_PRIORITY(PRI_MICRO_USB)
#define  PRI_MICRO_USB                SCI_TASK_PRI(PRI_MICRO_USB)

DECLARE_PRIORITY(PRI_CARDLOG_TASK_PRIO)
#define  PRI_CARDLOG_TASK_PRIO       SCI_TASK_PRI(PRI_CARDLOG_TASK_PRIO)

DECLARE_PRIORITY(PRI_CDROM_BIND_TASK)
#define  PRI_CDROM_BIND_TASK         SCI_TASK_PRI(PRI_CDROM_BIND_TASK)

DECLARE_PRIORITY(PRI_CHGMNG_SRV_TASK)
#define  PRI_CHGMNG_SRV_TASK        SCI_TASK_PRI(PRI_CHGMNG_SRV_TASK)

DECLARE_PRIORITY(PRI_CODEC_DRV_TASK)
#define  PRI_CODEC_DRV_TASK                SCI_TASK_PRI(PRI_CODEC_DRV_TASK)

DECLARE_PRIORITY(PRI_AUDIO_HAL_TASK)
#define  PRI_AUDIO_HAL_TASK                SCI_TASK_PRI(PRI_AUDIO_HAL_TASK)


DECLARE_PRIORITY(PRI_DSP_LOG_TASK)
#define  PRI_DSP_LOG_TASK           SCI_TASK_PRI(PRI_DSP_LOG_TASK)

DECLARE_PRIORITY(PRI_BT_LOG_TASK)
#define  PRI_BT_LOG_TASK           SCI_TASK_PRI(PRI_BT_LOG_TASK)

DECLARE_PRIORITY(PRI_DBAT_TASK)
#define  PRI_DBAT_TASK              SCI_TASK_PRI(PRI_DBAT_TASK)

//#define  PRI_CHNG_FREQ_TASK         SCI_SYSTEM_PRI(PRI_CHNG_FREQ_TASK_INDEX)

DECLARE_PRIORITY(PRI_AGPS_INTERFACE_TASK)
#define  PRI_AGPS_INTERFACE_TASK                 SCI_TASK_PRI(PRI_AGPS_INTERFACE_TASK)

DECLARE_PRIORITY(PRI_GPS_INTERFACE_TASK)
#define  PRI_GPS_INTERFACE_TASK                 SCI_TASK_PRI(PRI_GPS_INTERFACE_TASK)

DECLARE_PRIORITY(PRI_GPS_TASK)
#define  PRI_GPS_TASK                SCI_TASK_PRI(PRI_GPS_TASK)

DECLARE_PRIORITY(PRI_GPS_LOG_TASK)
#define  PRI_GPS_LOG_TASK                SCI_TASK_PRI(PRI_GPS_LOG_TASK)

DECLARE_PRIORITY(PRI_NMEA_TASK)
#define  PRI_NMEA_TASK               SCI_TASK_PRI(PRI_NMEA_TASK)


DECLARE_PRIORITY(PRI_IRAM_TESER_TASK)
#define  PRI_IRAM_TESER_TASK         SCI_TASK_PRI(PRI_IRAM_TESER_TASK)


DECLARE_PRIORITY(PRI_MV_SCHED_TASK)
#define  PRI_MV_SCHED_TASK          SCI_TASK_PRI(PRI_MV_SCHED_TASK)


DECLARE_PRIORITY(PRI_DM_TASK)
#define   PRI_DM_TASK                SCI_TASK_PRI(PRI_DM_TASK)


DECLARE_PRIORITY(PRI_WIFITEST_TASK)
#define PRI_WIFITEST_TASK            SCI_TASK_PRI(PRI_WIFITEST_TASK)

DECLARE_PRIORITY(PRI_WIFI_TEST_TASK)
#define PRI_WIFI_TEST_TASK           SCI_TASK_PRI(PRI_WIFI_TEST_TASK)

DECLARE_PRIORITY(PRI_WIFISUPP_TASK)
#define PRI_WIFISUPP_TASK            SCI_TASK_PRI(PRI_WIFISUPP_TASK)

DECLARE_PRIORITY(PRI_CSR_FW_TASK)
#define PRI_CSR_FW_TASK              SCI_TASK_PRI(PRI_CSR_FW_TASK)

DECLARE_PRIORITY(PRI_CSR_WIFI_BH_TASK)
#define PRI_CSR_WIFI_BH_TASK         SCI_TASK_PRI(PRI_CSR_WIFI_BH_TASK)

DECLARE_PRIORITY(PRI_RTL_HIGH_TASK)
#define PRI_RTL_HIGH_TASK            SCI_TASK_PRI(PRI_RTL_HIGH_TASK)

DECLARE_PRIORITY(PRI_RTL_NORMAL_TASK)
#define PRI_RTL_NORMAL_TASK          SCI_TASK_PRI(PRI_RTL_NORMAL_TASK)



DECLARE_PRIORITY(PRI_NET_PRIORITY)
#define PRI_NET_PRIORITY             SCI_TASK_PRI(PRI_NET_PRIORITY)

DECLARE_PRIORITY(PRI_NETMGR_TASK)
#define PRI_NETMGR_TASK              SCI_TASK_PRI(PRI_NETMGR_TASK)

DECLARE_PRIORITY(PRI_STRM_TASK)
#define PRI_STRM_TASK                SCI_TASK_PRI(PRI_STRM_TASK)

DECLARE_PRIORITY(PRI_RTP_TASK)
#define PRI_RTP_TASK                SCI_TASK_PRI(PRI_RTP_TASK)

DECLARE_PRIORITY(PRI_STRMTEST_RTP_SERVER_TASK)
#define PRI_STRMTEST_RTP_SERVER_TASK  SCI_TASK_PRI(PRI_STRMTEST_RTP_SERVER_TASK)

DECLARE_PRIORITY(PRI_STRMTEST_REF_TASK)
#define PRI_STRMTEST_REF_TASK        SCI_TASK_PRI(PRI_STRMTEST_REF_TASK)

DECLARE_PRIORITY(PRI_STRMTEST_APP_TASK)
#define PRI_STRMTEST_APP_TASK        SCI_TASK_PRI(PRI_STRMTEST_APP_TASK)

DECLARE_PRIORITY(PRI_DM_TASK)
#define PRI_DM_TASK                  SCI_TASK_PRI(PRI_DM_TASK)

DECLARE_PRIORITY(PRI_ODM_TASK)
#define PRI_ODM_TASK                SCI_TASK_PRI(PRI_ODM_TASK)

DECLARE_PRIORITY(PRI_ODM_UT_TASK)
#define PRI_ODM_UT_TASK             SCI_TASK_PRI(PRI_ODM_UT_TASK)

DECLARE_PRIORITY(PRI_NETMGR_TESTAPP_TASK)
#define PRI_NETMGR_TESTAPP_TASK      SCI_TASK_PRI(PRI_NETMGR_TESTAPP_TASK)

DECLARE_PRIORITY(PRI_PUA_UT_DRIVE_TASK)
#define PRI_PUA_UT_DRIVE_TASK        SCI_TASK_PRI(PRI_PUA_UT_DRIVE_TASK)

DECLARE_PRIORITY(PRI_PUA_UT_TASK)
#define PRI_PUA_UT_TASK              SCI_TASK_PRI(PRI_PUA_UT_TASK)

DECLARE_PRIORITY(PRI_PUA_TASK)
#define PRI_PUA_TASK                 SCI_TASK_PRI(PRI_PUA_TASK)

DECLARE_PRIORITY(PRI_POC_TASK)
#define PRI_POC_TASK                SCI_TASK_PRI(PRI_POC_TASK)

DECLARE_PRIORITY(PRI_WSP_TASK)
#define PRI_WSP_TASK                 SCI_TASK_PRI(PRI_WSP_TASK)

DECLARE_PRIORITY(PRI_CSR_THREAD_HIGHEST)
#define PRI_CSR_THREAD_HIGHEST       SCI_TASK_PRI(PRI_CSR_THREAD_HIGHEST)

DECLARE_PRIORITY(PRI_CSR_THREAD_HIGH)
#define PRI_CSR_THREAD_HIGH      SCI_TASK_PRI(PRI_CSR_THREAD_HIGH)

DECLARE_PRIORITY(PRI_CSR_THREAD_NORMAL)
#define PRI_CSR_THREAD_NORMAL       SCI_TASK_PRI(PRI_CSR_THREAD_NORMAL)

DECLARE_PRIORITY(PRI_CSR_THREAD_LOW)
#define PRI_CSR_THREAD_LOW           SCI_TASK_PRI(PRI_CSR_THREAD_LOW)

DECLARE_PRIORITY(PRI_CSR_THREAD_LOWEST)
#define PRI_CSR_THREAD_LOWEST        SCI_TASK_PRI(PRI_CSR_THREAD_LOWEST)

DECLARE_PRIORITY(PRI_ARM9SHM_TASK)
#define PRI_ARM9SHM_TASK            SCI_TASK_PRI(PRI_ARM9SHM_TASK)

DECLARE_PRIORITY(PRI_SMCODEC_TASK)
#define PRI_SMCODEC_TASK            SCI_TASK_PRI(PRI_SMCODEC_TASK)

DECLARE_PRIORITY(PRI_SIP_MGR_TASK)
#define PRI_SIP_MGR_TASK             SCI_TASK_PRI(PRI_SIP_MGR_TASK)

DECLARE_PRIORITY(PRI_SHUTTLE_TASK)
#define PRI_SHUTTLE_TASK             SCI_TASK_PRI(PRI_SHUTTLE_TASK)

DECLARE_PRIORITY(PRI_SIANO_SPI_TASK)
#define PRI_SIANO_SPI_TASK           SCI_TASK_PRI(PRI_SIANO_SPI_TASK)

DECLARE_PRIORITY(PRI_AUD_DSP_TASK)
#define PRI_AUD_DSP_TASK             SCI_TASK_PRI(PRI_AUD_DSP_TASK)

DECLARE_PRIORITY(PRI_CAFSOUND_TASK)
#define PRI_CAFSOUND_TASK          SCI_TASK_PRI(PRI_CAFSOUND_TASK)

DECLARE_PRIORITY(PRI_CATMV_TASK)
#define PRI_CATMV_TASK               SCI_TASK_PRI(PRI_CATMV_TASK)

DECLARE_PRIORITY(PRI_IPERF_TASK_HIGH)
#define PRI_IPERF_TASK_HIGH          SCI_TASK_PRI(PRI_IPERF_TASK_HIGH)

DECLARE_PRIORITY(PRI_IPERF_TASK_NORMAL)
#define PRI_IPERF_TASK_NORMAL        SCI_TASK_PRI(PRI_IPERF_TASK_NORMAL)

DECLARE_PRIORITY(PRI_IPERF_TASK_LOW)
#define PRI_IPERF_TASK_LOW           SCI_TASK_PRI(PRI_IPERF_TASK_LOW)


DECLARE_PRIORITY(PRI_DCAM_TASK)
#define PRI_DCAM_TASK                SCI_TASK_PRI(PRI_DCAM_TASK)

DECLARE_PRIORITY(PRI_DSP_CODEC_UPLOAD_TASK)
#define PRI_DSP_CODEC_UPLOAD_TASK   SCI_TASK_PRI(PRI_DSP_CODEC_UPLOAD_TASK)

DECLARE_PRIORITY(PRI_SUB_AMR_TASK)    
#define PRI_SUB_AMR_TASK             SCI_TASK_PRI(PRI_SUB_AMR_TASK)

DECLARE_PRIORITY(PRI_LCD_TASK)
#define PRI_LCD_TASK                 SCI_TASK_PRI(PRI_LCD_TASK)

DECLARE_PRIORITY(PRI_ATHR_MBOX_PING_TASK)
#define PRI_ATHR_MBOX_PING_TASK     SCI_TASK_PRI(PRI_ATHR_MBOX_PING_TASK)

DECLARE_PRIORITY(PRI_MSENSOR_TASK)
#define PRI_MSENSOR_TASK             SCI_TASK_PRI(PRI_MSENSOR_TASK)

DECLARE_PRIORITY(PRI_MTP_MAIN_HANDLER_TASK)
#define PRI_MTP_MAIN_HANDLER_TASK    SCI_TASK_PRI(PRI_MTP_MAIN_HANDLER_TASK)

DECLARE_PRIORITY(PRI_PNGDEC_TASK)
#define PRI_PNGDEC_TASK              SCI_TASK_PRI(PRI_PNGDEC_TASK)


DECLARE_PRIORITY(PRI_SFS_DISK_C_TASK)
#define PRI_SFS_DISK_C_TASK              SCI_TASK_PRI(PRI_SFS_DISK_C_TASK)

DECLARE_PRIORITY(PRI_SFS_DISK_D_TASK)
#define PRI_SFS_DISK_D_TASK              SCI_TASK_PRI(PRI_SFS_DISK_D_TASK)

DECLARE_PRIORITY(PRI_SFS_DISK_E_TASK)
#define PRI_SFS_DISK_E_TASK              SCI_TASK_PRI(PRI_SFS_DISK_E_TASK)

DECLARE_PRIORITY(PRI_SFS_DISK_F_TASK)
#define PRI_SFS_DISK_F_TASK              SCI_TASK_PRI(PRI_SFS_DISK_F_TASK)



DECLARE_PRIORITY(PRI_DRM_DH_TASK)
#define PRI_DRM_DH_TASK             SCI_TASK_PRI(PRI_DRM_DH_TASK)

DECLARE_PRIORITY(PRI_DRM_IO_TASK)
#define PRI_DRM_IO_TASK             SCI_TASK_PRI(PRI_DRM_IO_TASK)


DECLARE_PRIORITY(PRI_DUA_TASK)
#define PRI_DUA_TASK               SCI_TASK_PRI(PRI_DUA_TASK)

#endif /*__PRIORITY_SYSTEM_H__*/
