/****************************************************************************
** File Name:      mmi_id.h                                               *
** Author:                                                                 *
** Date:           04/11/2003                                              *
** Copyright:      2003 Spreadtrum, Incoporated. All Rights Reserved.       *
** Description:    This file is used to describe the data struct of        *
**                 system, applicaiton, window and control                 *
****************************************************************************
**                         Important Edit History                          *
** ------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                             *
** 11/2003        Great.Tian        Create
** 
****************************************************************************/
#ifndef  _MMI_ID_H_    
#define  _MMI_ID_H_  

 

/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef __cplusplus
   extern   "C"
   {
#endif

/**-------------------------------------------------------------------------*
 **                         Include Files                                   *
 **------------------------------------------------------------------------*/
#include "sci_types.h" 




#define WIN_ID_DEF(win_id)          win_id
#ifdef JAVASCRIPT_ECO_ENVIRONMENT_SUPPORT
#define JS_WIN_ID_NUM_MAX    (32)
#define JS_CTRL_ID_NUM_MAX   (128)
#endif
// window ID
// 命名规则: 模块名 + 窗口名 + WIN_ID  ,  eg: CC_DIALING_WIN_ID (CC部分呼叫窗口ID)
typedef enum
{
    BEGIN_WIN_ID,                   // begin

#include "mmi_id.def"
#ifdef JAVASCRIPT_ECO_ENVIRONMENT_SUPPORT
JS_WIN_GAP,
	JS_WIN_BEGIN_ID=(JS_WIN_GAP+64),
	JS_WIN_END_ID = JS_WIN_BEGIN_ID+JS_WIN_ID_NUM_MAX,

	WIN_ID_DEF(MMI_PERMISSION_RUNTIME_WIN_ID),
	WIN_ID_DEF(MMI_PERMISSION_INSTALL_WIN_ID),
#endif
    TOTAL_WINDOW_ID_NUMBER          // 窗口ID的总数目
}MMI_COMMON_WINDOW_ID_E;

#undef WIN_ID_DEF

// control ID
// 命名规则: 控件所属的窗口名 + 控件名 + CTRL_ID, eg: IDLEWIN_TEXTBOX_CTRL_ID (IDLE窗口下text控件ID)
typedef enum
{
    BEGIN_CTRL_ID = TOTAL_WINDOW_ID_NUMBER,// begin

    MMIIDLE_WALLPAPER_ANIM_CTRL_ID, 
      
	IDLEWIN_TEXTBOX_CTRL_ID,        // idle窗口下Text控件的ID 
    IDLEWIN_SOFTICON_CTRL_ID,       // idle窗口下的softicon的ID
    IDLEWIN_STATUSBAR_CTRL_ID,      // idle窗口下的statusbar控件的ID
    FUNCDIALINGWIN_STATUSBAR_CTRL_ID, // funcdialing窗口下的statusbar控件的ID
	MAINMENUWIN_MENU_CTRL_ID,       // MainMenu窗口下的Menu控件ID
	MAINMENUWIN_SECOND_MENU_CTRL_ID,
	MAINMENUWIN_SECOND_LIST_CTRL_ID,//二级菜单list控件ID
#ifdef QBTHEME_SUPPORT
    MAINMENUWIN_SETIDLESTYLE_MENU_CTRL_ID, //设置主菜单风格menu控件ID
#endif
    //pubwin
    MMIPUB_TEXT_CTRL_ID,
    MMIPUB_WAIT_ANIM_CTRL_ID,       //Wait anim control

    //for pda
    MMIPUB_LEFT_BUTTON_CTRL_ID,
    MMIPUB_MIDDLE_BUTTON_CTRL_ID,
    MMIPUB_RIGHT_BUTTON_CTRL_ID,
    MMIPUB_LIST_CTRL_ID,
    MMIPUB_FORM_CTRL_ID,
    MMIPUB_EDIT_CTRL_ID,
    MMIPUB_MENU_CTRL_ID,
    MMIPUB_LANDSCAPE_FORM_CTRL_ID,
    MMIPUB_LANDSCAPE_EDIT_CTRL_ID,
    MMIPUB_LANDSCAPE_BUTTON_CTRL_ID,

    MMIIDLE_DIAL_EDIT_CTRL_ID,      // Dialing窗口中的Editor控件ID
    MMIIDLE_DIAL_LISTBOX_CTRL_ID, //Dialing窗口中的listbox控件ID
    
#ifdef TOUCH_PANEL_SUPPORT
    MMIIDLE_DIAL_KEYPAD_BUTTON_CTRL_ID, //Dialing窗口中的KEYPAD BUTTON控件ID

    MMIIDLE_DIAL_KEY1_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEY2_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEY3_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEY4_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEY5_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEY6_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEY7_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEY8_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEY9_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEYSTAR_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEY0_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_KEYHASH_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_SAVE_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_CALL_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_IP_CALL_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_VIDEO_CALL_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_DEL_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_SMS_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_PB_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_CL_BUTTON_CTRL_ID,

    MMIIDLE_DIAL_FUNC_FORM_CTRL_ID, //include  MMIIDLE_DIAL_FUNC_TOP_LINE_CTRL_ID MMIIDLE_DIAL_FUNC_CHILD_FORM_CTRL_ID or sms pb calllog
    
    MMIIDLE_DIAL_FORM_CTRL_ID, //include MMIIDLE_DIAL_INPUT_EDIT_FORM_CTRL_ID, MMIIDLE_DIAL_INPUT_NUM_FORM_CTRL_ID
    MMIIDLE_DIAL_INPUT_EDIT_FORM_CTRL_ID,
    MMIIDLE_DIAL_INPUT_NUM_FORM_CTRL_ID, //include MMIIDLE_DIAL_INPUT_NUM0_FORM_CTRL_ID MMIIDLE_DIAL_INPUT_NUM1_FORM_CTRL_ID MMIIDLE_DIAL_INPUT_NUM2_FORM_CTRL_ID MMIIDLE_DIAL_INPUT_NUM3_FORM_CTRL_ID
#ifdef MMI_ISTYLE_SUPPORT    

    MMIIDLE_DIAL_MATCH_NUM_ARROW_CTRL_ID,
#endif
    MMIIDLE_DIAL_EDIT_SHADOW_CTRL_ID,

    MMIIDLE_DIAL_INPUT_ROW_LINE0_CTRL_ID, 
    MMIIDLE_DIAL_INPUT_ROW_LINE1_CTRL_ID, 
    MMIIDLE_DIAL_INPUT_ROW_LINE2_CTRL_ID, 
    MMIIDLE_DIAL_INPUT_ROW_LINE3_CTRL_ID, 
    MMIIDLE_DIAL_INPUT_ROW_LINE4_CTRL_ID, 
    MMIIDLE_DIAL_INPUT_ROW_LINE5_CTRL_ID, 
    MMIIDLE_DIAL_INPUT_COLUMN_LINE0_CTRL_ID, 
    MMIIDLE_DIAL_INPUT_COLUMN_LINE1_CTRL_ID, 
    MMIIDLE_DIAL_INPUT_COLUMN_LINE2_CTRL_ID, 
    MMIIDLE_DIAL_FUNC_COLUMN_LINE0_CTRL_ID, 
    MMIIDLE_DIAL_FUNC_COLUMN_LINE1_CTRL_ID, 
    MMIIDLE_DIAL_FUNC_COLUMN_LINE2_CTRL_ID, 
    MMIIDLE_DIAL_DIAL_PANEL_COLUMN_LINE_H_CTRL_ID,
    
    MMIIDLE_DIAL_INPUT_NUM_FORM0_CTRL_ID, //'1','2','3',
    MMIIDLE_DIAL_INPUT_NUM_FORM1_CTRL_ID,//'4','5','6',
    MMIIDLE_DIAL_INPUT_NUM_FORM2_CTRL_ID,//'7','8','9',
    MMIIDLE_DIAL_INPUT_NUM_FORM3_CTRL_ID,//'*','0','#',
    
    MMIIDLE_DIAL_FUNC_TOP_LINE_CTRL_ID,
    MMIIDLE_DIAL_FUNC_CHILD_FORM_CTRL_ID,
    MMIIDLE_DIAL_FUNC_HIDE_BUTTON_CTRL_ID,
    MMIIDLE_DIAL_FUNC_SHOW_BUTTON_CTRL_ID,
/*
    MMIIDLE_DIAL_TOOLBAR_BUTTON_CTRL_ID,// for ver window
    MMIIDLE_DIAL_TOOLBAR_FORM_BUTTON_CTRL_ID,  //for horz window
    MMIIDLE_DIAL_TOOLBAR_BUTTON_FORM_CTRL_ID, //for horz window
    MMIIDLE_DIAL_TOOLBAR_CTRL_ID,
*/
#endif
    MMIIDLE_DIAL_EDIT_BOX_LINE_CTRL_ID,
    MMIIDLE_DIAL_POPMENU_CTRL_ID,   
#ifdef BT_DIALER_SUPPORT
    MMIIDLE_DIAL_GREEN_POPMENU_CTRL_ID,
#endif
    
    MMIIDLE_DIAL_LIST_MENU_CTRL_ID,
    MMIIDLE_ANIM_CTRL_ID,

#ifdef SCREENSAVER_SUPPORT       
	MMIIDLESS_ANIM_CTRL_ID,	        //Screen saver 窗口动画控件ID
#endif
    MMI_CHARGE_ANIM_CTRL_ID,	        //充电窗口动画控件ID
    //FDN control ID add by louis.wei
    FDN_PIN2_PASSWORD_CTRL_ID,      // the password for PIN2 in FDN
    FDN_PIN2_TEXT_CTRL_ID,          // the prompt for Input PIN2
    FDN_ADD_NAME_TEXT_CTRL_ID,      // the text control for prompt
    FDN_ADD_NAME_EDIT_CTRL_ID,      // the text control of FDN ADD Window
    FDN_ADD_NUM_TEXT_CTRL_ID,       //  the edit control of FDN ADD Window
    FDN_ADD_NUM_EDIT_CTRL_ID,       // the text control of FDN ADD Window
    FDNLIST_LISTBOX_CTRL_ID,        //  the edit control of FDN ADD Window
    FDNMENU_MENU_CTRL_ID,           //  the menu control of FDN MENU Window

    // 用于开机
    PHONE_STARTUP_NORMAL_ANIMATEBOX_CTRL_ID,        // PHONE下的正常开机ANIMATE控件
    PHONE_STARTUP_ALARM_ANIMATEBOX_CTRL_ID,         // PHONE下的闹铃开机ANIMATE控件
    PHONE_STARTUP_CHARGE_ANIMATEBOX_CTRL_ID,        // PHONE下的充电开机ANIMATE控件
    
    PHONE_POWER_OFF_ANIMATEBOX_CTRL_ID,             // PHONE下的关机ANIMATE控件
    PHONE_EMERGENCY_CALL_PHONENUMEDITBOX_CTRL_ID,   // PHONE下紧急呼叫的phonenumber editbox控件
    
    PHONE_NETWORK_SEARCH_ANIM_CTRL_ID,              // PHONE下的搜索网络ANIMATE控件
    PHONE_NETWORK_SEARCH_LABEL_CTRL_ID,             // PHONE下的搜索网络LABEL控件

    PHONE_SIM_ERROR_LABEL_CTRL_ID,                  // PHONE下NO sim or sim error的LABEL控件
    PHONE_CHR_WARNING_MSGBOX_CTRL_ID,               // PHONE下电量低msgbox控件
    PHONE_PUK_EDITBOX_CTRL_ID,                      // PHONE下的PUK EDITBOX控件
    PHONE_PIN_EDITBOX_CTRL_ID,                      // PHONE下的PIN EDITBOX控件
    PHONE_NEW_PIN_EDITBOX_CTRL_ID,                  // PHONE下的new PIN EDITBOX控件
    PHONE_NEW_PIN_AGAIN_EDITBOX_CTRL_ID,            // PHONE下的confirm new PIN EDITBOX控件

    MMI_PIN_INPUT_EDITBOX_CTRL_ID,                  // 输入PIN的Editbox控件
    MMI_PUK_INPUT_EDITBOX_CTRL_ID,                  // 输入PUK的Editbox控件
    MMI_NEW_PIN_INPUT_EDITBOX_CTRL_ID,              // 输入New PIN的Editbox控件
    MMI_NEW_PIN_AGAIN_INPUT_EDITBOX_CTRL_ID,        // 输入New PIN again的Editbox控件
    MMIPHONE_PIN_REMAIN_LABEL_CTRL_ID,
    MMIPHONE_PUK_REMAIN_LABEL_CTRL_ID,
    MMIPHONE_PIN_INPUT_REMAIN_LABEL_CTRL_ID,
    MMIPHONE_PUK_INPUT_REMAIN_LABEL_CTRL_ID,
#ifdef MMI_SIM_LOCK_SUPPORT
    MMIPHONE_SIM_LOCK_PASSWORD_LABEL_CTRL_ID,
    PHONE_SIM_LOCK_PASSWORD_EDITBOX_CTRL_ID,
    MMIPHONE_SIM_LOCK_INPUT_REMAIN_LABEL_CTRL_ID,
    MMI_SIM_LOCK_PASSWORD_EDITBOX_CTRL_ID,
    MMI_SIM_LOCK_SOS_EDITBOX_CTRL_ID,
#endif    

    MMIPHONE_DISPLAY_IMEI_CTRL_ID,                  // No sim or sim error,显示imei的Label控件
    MMIPHONE_DISPLAY_BTRYCAP_FORM_ID,
    MMIPHONE_DISPLAY_BTRYCAP_LABEL_ID,               // 显示电池电量LABEL
    MMIPHONE_DISPLAY_BTRYCAP_IMAGE_ID,               // 显示百分比图
#ifdef MMI_DUAL_BATTERY_SUPPORT
    MMIPHONE_DISPLAY_BTRYCAP_MAIN_FORM_ID,
    MMIPHONE_DISPLAY_BTRYCAP_AUX_FORM_ID,
    MMIPHONE_DISPLAY_BTRYCAP_AUX_LABEL_ID,               // 显示副电池电量LABEL
    MMIPHONE_DISPLAY_BTRYCAP_AUX_IMAGE_ID,               // 显示副电池百分比图
#endif
    
	PHONE_CHARGE_STARTUP_ANIM_CTRL_ID,				//关机充电CTRL ID

	MMIMAIN_MSGBOX_CTRL_ID,

	//MSD START
	MMIMSD_INIT_INPUT_PSW_PASSWORD_CTRL_ID,
	MMIMSD_SETUP_INPUT_PSW_EDITBOX_CTRL_ID,
	MMIMSD_SETUP_INPUT_INFO_TEL_EDITBOX_CTRL_ID,
	MMIMSD_CLOSE_INPUT_PSW_EDITBOX_CTRL_ID,
	MMIMSD_MODPSW_INPUT_OLD_PSW_EDITBOX_CTRL_ID,
	MMIMSD_MODPSW_INPUT_NEW_PSW_EDITBOX_CTRL_ID,
	MMIMSD_MODPSW_INPUT_PSW_AGAIN_EDITBOX_CTRL_ID,
	MMIMSD_MODINF_INPUT_PSW_EDITBOX_CTRL_ID,
	MMIMSD_MODINF_INPUT_INFO_TEL_EDITBOX_CTRL_ID,	
	//MSD END
	
    MMI_SDCARD_MANAGE_CTRL_ID,                    //多媒体下SD卡管理控件

	MMIMSG_MAIN_MENU_CTRL_ID,		//信息主菜单

    MMIMAIN_PHONENUM_DTMF_CTRL_ID,//插入W,P,N

    MMIMAIN_DIAL_SIM__CTRL_ID,
    
	MMIKL_CLOCK_DISP_CTRL_ID,
    MMIKL_EMERGENCY_NUMBER_CTRL_ID,
	MMIKL_KEYLOCK_CUE_CTRL_ID,		//锁屏提示语
    MENU_POPUP_CTRL_ID,             //弹出菜单控件ID

	MMICOMMON_SOFTKEY_CTRL_ID,
    MMICOMMON_BUTTON_SOFTKEY_LEFT_CTRL_ID,
    MMICOMMON_BUTTON_SOFTKEY_MIDDLE_CTRL_ID,
    MMICOMMON_BUTTON_SOFTKEY_RIGHT_CTRL_ID,
    	
    MMICOMMON_STATUSBAR_CTRL_ID,
	MMICOMMON_TITLE_CTRL_ID,
    MMICOMMON_TIPS_CTRL_ID,

    MMIAPPLET_MANAGER_BOTTON_ID,
    MMIAPPLET_MANAGER_LIST_ID,
#ifdef MMI_TASK_MANAGER
#ifdef CMCC_UI_STYLE
    MMIAPPLET_MANAGER_OPTION_ID,
#endif
#endif

    MAIN_MAINMENU_OPT_CTRL_ID,
    MAIN_MAINMENU_MOVEOPT_CTRL_ID,
    MAIN_MAINMENU_HELP_CTRL_ID,
    MMIKL_MAIN_ANIM_BG_ID,
    MMIKL_CLOCK_ANIM_ID,
    MMIKL_PRESS_ANIM_BG_ID,
    MMIKL_PRESS_BOTTON_ID,
    MMIKL_PRESS_ANIM_CALL_ID,
    MMIKL_PRESS_ANIM_MESSAGE_ID,
    MMIKL_PRESS_ANIM_EVENT_ID,    
    
#ifdef MOBILE_VIDEO_SUPPORT    
    MMI_EDITCTRL_ID,
#endif
    MMISETLIST_LIST_CTRL_ID,
#ifdef MMI_AZAN_SUPPORT
	MMIAZAN_CHOOSE_OPT_CTRL_ID,
	MMIAZAN_SET_COUNTRY_CTRL_ID,
	MMIAZAN_SET_CITY_CTRL_ID,
	MMIAZAN_SET_ALARM_CTRL_ID,
	MMIAZAN_SET_CALCULATION_METHOD_CTRL_ID,
	MMI_AZAN_COUNTRY_LABLE_CTRL_ID,
	MMI_AZAN_CITY_LABLE_CTRL_ID,
	MMI_AZAN_TIME_LABLE_CTRL_ID,
	
	MMI_AZAN_MAIN_FORM_CTRL_ID,
	
	MMI_AZAN_MAIN_PRAY_TIMES_LABLE_CTRL_ID,
	MMI_AZAN_MAIN_COUNTRY_LABLE_CTRL_ID,
	MMI_AZAN_MAIN_CITY_LABLE_CTRL_ID,
	MMI_AZAN_MAIN_ANIM_CTRL_ID,
	
	MMI_AZAN_MAIN_FAJR_FORM_CTRL_ID,
	MMI_AZAN_MAIN_FAJR_LABLE_CTRL_ID,
	MMI_AZAN_MAIN_FAJR_TIME_LABLE_CTRL_ID,

	MMI_AZAN_MAIN_SYURUK_FORM_CTRL_ID,
	MMI_AZAN_MAIN_SYURUK_LABLE_CTRL_ID,
	MMI_AZAN_MAIN_SYURUK_TIME_LABLE_CTRL_ID,
	
	MMI_AZAN_MAIN_ZUHR_FORM_CTRL_ID,
	MMI_AZAN_MAIN_ZUHR_LABLE_CTRL_ID,
	MMI_AZAN_MAIN_ZUHR_TIME_LABLE_CTRL_ID,

	MMI_AZAN_MAIN_ASR_FORM_CTRL_ID,
	MMI_AZAN_MAIN_ASR_LABLE_CTRL_ID,
	MMI_AZAN_MAIN_ASR_TIME_LABLE_CTRL_ID,

	MMI_AZAN_MAIN_MAG_FORM_CTRL_ID,
	MMI_AZAN_MAIN_MAG_LABLE_CTRL_ID,
	MMI_AZAN_MAIN_MAG_TIME_LABLE_CTRL_ID,
	
	MMI_AZAN_MAIN_ISHA_FORM_CTRL_ID,
	MMI_AZAN_MAIN_ISHA_LABLE_CTRL_ID,
	MMI_AZAN_MAIN_ISHA_TIME_LABLE_CTRL_ID,

	MMI_AZAN_ALARM_FORM_CTRL_ID,
	MMI_AZAN_ALARM_CHILD_FORM_CTRL_ID,
#endif
#ifdef WRE_SUPPORT
    WRE_CTRL_ID_IM,                 //中间件平台输入法控件
#endif
#if defined(GUIF_SCROLLKEY) || defined(MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT)
       MMICOMMON_SCROLLKEY_CTRL_ID,
#endif       
#ifdef MMI_KEY_LOCK_EFFECT_SUPPORT
        MMIKL_BUTTON_SOFTKEY_LEFT_CTRL_ID,
        MMIKL_BUTTON_SOFTKEY_RIGHT_CTRL_ID,
    #ifdef MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT

        MMIKL_DATE_WEEK_LABEL_ID,
        MMIKL_INFO_AREA_FORM_ID,
        MMIKL_INFO_AREA_BATTERY_FORM_ID,
        MMIKL_INFO_AREA_CALL_FORM_ID,
        MMIKL_INFO_AREA_MESSAGE_FORM_ID,
        MMIKL_INFO_AREA_EVENT_FORM_ID,
        MMIKL_INFO_AREA_BATTERY_TEXT_ID,	
        MMIKL_INFO_AREA_CALL_TEXT_ID,
        MMIKL_INFO_AREA_MESSAGE_TEXT_ID,
        MMIKL_INFO_AREA_EVENT_TEXT_ID,
        MMIKL_INFO_AREA_BATTERY_ICON_ID,	
        MMIKL_INFO_AREA_CALL_ICON_ID,
        MMIKL_INFO_AREA_MESSAGE_ICON_ID,
        MMIKL_INFO_AREA_EVENT_ICON_ID,	
    #endif

    #ifdef MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT
        MMIKL_PATTERN_UNLCOK_ANIM_CTRL_ID,
    #endif
#endif

#ifdef LIVE_WALLPAPER_FRAMEWORK_SUPPORT
    MMI_LIVEWALLPAPER_PREVIEW_SET_BUTTON_CTRL_ID,
    MMI_LIVEWALLPAPER_PREVIEW_CANCEL_BUTTON_CTRL_ID,
    MMI_LIVEWALLPAPER_PREVIEW_OPTION_BUTTON_CTRL_ID,
#endif

#ifndef MMI_MULTI_SIM_SYS_SINGLE
    MAIN_SIM_SELECT_CTRL_ID,
#endif

    //Extract
    MMI_EXTRACT_NUMBER_POP_CTRL_ID,
    MMI_EXTRACT_URL_POP_CTRL_ID,
    MMI_EXTRACT_EMAIL_POP_CTRL_ID,

    MMISEARCH_EDITBOX_ID,
    MMISEARCH_LIST_ID,
#ifdef MMI_ISTYLE_SUPPORT
    MMISEARCH_ISTYLE_DELETEBUTTON_ID,
#endif

    MMIIDLE_STK_IDLE_TEXT_CTRL_ID,
    #ifdef SLIDESHOW_WALLPAPER_SUPPORT
    MMILIVEWALLPAPER_ANIM_CTRL_ID,
    #endif
    MMIDEMO_LIST_CTRL_ID,

//===========================================================================//
//                              For watch                                    //
//===========================================================================//
    //QUERYWIN
    WATCH_COMMON_QUERYWIN_TEXTBOX_CTRL_ID,
    WATCH_COMMON_QUERYWIN_TEXTBOX2_CTRL_ID,
    WATCH_COMMON_QUERYWIN_BTN_1BTN_CTRL_ID,
    WATCH_COMMON_QUERYWIN_LEFTBTN_2BTN_CTRL_ID,
    WATCH_COMMON_QUERYWIN_RIGHTBTN_2BTN_CTRL_ID,
#ifdef SCREEN_SHAPE_CIRCULAR
    ADULT_WATCH_COMMON_QUERYWIN_BTN_1BTN_CTRL_ID,
    ADULT_WATCH_COMMON_QUERYWIN_TEXTBOX_CTRL_ID,
    ADULT_WATCH_COMMON_QUERYWIN_LEFTBTN_2BTN_CTRL_ID,
    ADULT_WATCH_COMMON_QUERYWIN_RIGHTBTN_2BTN_CTRL_ID,
#endif
    //NOTEWIN
    WATCH_COMMON_NOTEWIN_PIC_LABEL_CTRL_ID,
    WATCH_COMMON_NOTEWIN_TIP_TEXTBOX_CTRL_ID,

    //WAITINGWIN
    WATCH_COMMON_WAITINGWIN_PIC_LABEL_CTRL_ID,
    WATCH_COMMON_WAITINGWIN_TIP_TEXTBOX_CTRL_ID,
#ifdef ADULT_WATCH_SUPPORT
    ADULT_WATCH_COMMON_WAITINGWIN_PIC_ANIM_CTRL_ID,
#endif

//===========================================================================//
//                              For watch                                    //
//===========================================================================//

    WATCH_EDITPAD_TIP_LABEL_CTRL_ID,
    WATCH_EDITPAD_EDITBOX_PIN_CTRL_ID,
    WATCH_EDITPAD_EDITBOX_PUK_CTRL_ID,
    WATCH_EDITPAD_EDITBOX_NEW_PIN_CTRL_ID,
    WATCH_EDITPAD_EDITBOX_AGAIN_PIN_CTRL_ID,
    //Editpad button
    WATCH_EDITPAD_NUM1_BUTTON_CTRL_ID,
    WATCH_EDITPAD_NUM2_BUTTON_CTRL_ID,
    WATCH_EDITPAD_NUM3_BUTTON_CTRL_ID,
    WATCH_EDITPAD_NUM4_BUTTON_CTRL_ID,
    WATCH_EDITPAD_NUM5_BUTTON_CTRL_ID,
    WATCH_EDITPAD_NUM6_BUTTON_CTRL_ID,
    WATCH_EDITPAD_NUM7_BUTTON_CTRL_ID,
    WATCH_EDITPAD_NUM8_BUTTON_CTRL_ID,
    WATCH_EDITPAD_NUM9_BUTTON_CTRL_ID,
    WATCH_EDITPAD_NUM0_BUTTON_CTRL_ID,
    WATCH_EDITPAD_OK_BUTTON_CTRL_ID,
    WATCH_EDITPAD_CLEAN_BUTTON_CTRL_ID,
//===========================================================================//
//                              For watch                                    //
//===========================================================================//

    LAUNCHER_CHARGE_STATE_CTRL_ID,
    LAUNCHER_CHARGE_VALUE_CTRL_ID,
    LAUNCHER_CHARGE_IMAGE_CTRL_ID,
    LAUNCHER_CHARGE_IMAGE_FULL_CTRL_ID,

    LAUNCHER_CHARGETIP_STATE_CTRL_ID,
    LAUNCHER_CHARGETIP_VALUE_CTRL_ID,
    LAUNCHER_CHARGETIP_IMAGE_CTRL_ID,
    LAUNCHER_CHARGETIP_IMAGE_FULL_CTRL_ID,

    LAUNCHER_BATTERYLOW_IMAGE_CTRL_ID,
    LAUNCHER_BATTERYLOW_TIP_CTRL_ID,
    LAUNCHER_BATTERYLOW_CONFIRM_CTRL_ID,

    WATCH_SHUTDOWN_BG_CTRL_ID,
    WATCH_SHUTDOWN_OFF_BTN_CTRL_ID,
    WATCH_SHUTDOWN_OFF_TIP_CTRL_ID,
    WATCH_SHUTDOWN_RESET_CTRL_ID,
    WATCH_SHUTDOWN_FLYMODE_CTRL_ID,
    WATCH_SHUTDOWN_SOS_BG_CTRL_ID,
    WATCH_SHUTDOWN_SOS_TIP_CTRL_ID,
    WATCH_SHUTDOWN_SOS_CTRL_ID,
#ifdef SCREEN_SHAPE_CIRCULAR
    WATCH_SHUTDOWN_RESET_BG_CTRL_ID,
    WATCH_SHUTDOWN_RESET_TIP_CTRL_ID,
    WATCH_SHUTDOWN_FLYMODE_BG_CTRL_ID,
    WATCH_SHUTDOWN_FLYMODE_TIP_CTRL_ID,
#endif
#ifdef ADULT_WATCH_SUPPORT
    MAINMENUWIN_LIST_MENU_CTRL_ID,
#endif

#if defined(JAVASCRIPT_ECO_ENVIRONMENT_SUPPORT) || defined(APP_STORE_SUPPORT) || defined(DYNAMIC_WATCHFACE_SUPPORT)
    MMIEXTRA_MAIN_LIST_CTRL_ID,  //idle->extra
#endif

#ifdef ADULT_WATCH_SUPPORT
    ADULT_WATCH_SHUTDOWN_EMERG_ICON_CTRL_ID,
    ADULT_WATCH_SHUTDOWN_EMERG_TXT_CTRL_ID,
    ADULT_WATCH_SHUTDOWN_RESET_BTN_CTRL_ID,
    ADULT_WATCH_SHUTDOWN_OFF_BTN_CTRL_ID,
    ADULT_WATCH_SHUTDOWN_CANCEL_TXT_CTRL_ID,
#endif
//===========================================================================//
//                              For watch face                               //
//===========================================================================//
    WATCH_FACE_BEGIN_CTRL_ID,
    WATCH_FACE_END_CTRL_ID = WATCH_FACE_BEGIN_CTRL_ID + 100, // ???100???
    WATCH_FACE_SET_LIST_CTRL_ID,
    WATCH_FACE_MTF_DIAL_CTRL_LIST_ID,
    WATCH_FACE_USB_TIPS_CTRL_ID,
#ifdef APP_STORE_SUPPORT
    APPSTORE_HOME_LIST_CTRL_ID,
#endif

#ifdef JAVASCRIPT_ECO_ENVIRONMENT_SUPPORT
    // for js ctrl pool
    JS_CTRL_BEGIN_ID,
    JS_CTRL_END_ID = JS_CTRL_BEGIN_ID + JS_CTRL_ID_NUM_MAX,
    // for permission pub win: ctrl id
    MMI_PERMISSION_ALLOW_AWALYS_CTRL_ID,
    MMI_PERMISSION_ALLOW_ONCE_CTRL_ID,
    MMI_PERMISSION_ALLOW_FROBBID_CTRL_ID,
    MMI_PERMISSION_CONTENT_CTRL_ID,
    MMI_PERMISSION_NAME_CTRL_ID,
    MMI_PERMISSION_INSTALL_YES_CTRL_ID,
    MMI_PERMISSION_INSTALL_NO_CTRL_ID,
    MMI_PERMISSION_INSTALL_CONTENT_CTRL_ID,
#endif
#ifdef _SW_ZDT_PRODUCT_
    MMIWATCHIDLE_BG_ID,
    MMIWATCHIDLE_ANIM_CTRL_ID,
    IMAGE_WATCHIDLE_ANIM_2D_1,
    IMAGE_WATCHIDLE_ANIM_3D_1,
	
    IMAGE_SAMPLE_ANIM_CTRL_ID_1,
    IMAGE_SAMPLE_ANIM_CTRL_ID_2,
    IMAGE_SAMPLE_ANIM_CTRL_ID_3,
    IMAGE_SAMPLE_ANIM_CTRL_ID_4,
    IMAGE_SAMPLE_ANIM_CTRL_ID_5,
    IMAGE_SAMPLE_ANIM_CTRL_ID_6,
    IMAGE_SAMPLE_ANIM_CTRL_ID_7,
    IMAGE_SAMPLE_ANIM_CTRL_ID_8,
    IMAGE_SAMPLE_ANIM_CTRL_ID_9,

#endif

	TOTAL_CONTROL_ID_NUMBER         // 控件ID的总数目

}MMI_COMMON_CTRL_ID_T;


/*****************************************************************************/
// 	Description : Register acc menu group
//	Global resource dependence : none
//  Author: haiyang.hu
//	Note:
/*****************************************************************************/
PUBLIC void MMICOMMON_RegWinIdNameArr(void);
/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef   __cplusplus
   }
#endif
#endif
