//***********************************bar***********************************************//
//shortcut数据
//每个shortcut item间隔
#define MMIWIDGET_SHORTCUT_INTERVAL         10//29
//快捷背景图片与LCD顶上间距
#define MMIWIDGET_SHORTCUT_TOP_GAP          20

//快捷拖动预留的间距
#define MMIWIDGET_SHORTCUT_BG_ITEM_SPACE         10

//***********************************************digital clock **********************************//
#define MMIWIDGET_CLOCK_TIME_TOP            16
#define MMIWIDGET_CLOCK_DATE_BOTTOM         30
#define MMIWIDGET_CLOCK_WEEK_BOTTOM         13

//aclock time rect.
#define MMIWIDGET_ACLOCK_RECT_LEFT            74
#define MMIWIDGET_ACLOCK_RECT_TOP             0
#define MMIWIDGET_ACLOCK_RECT_RIGHT           246
#define MMIWIDGET_ACLOCK_RECT_BOTTOM          172
#define MMIWIDGET_ACLOCK_RECT                 {MMIWIDGET_ACLOCK_RECT_LEFT, MMIWIDGET_ACLOCK_RECT_TOP, MMIWIDGET_ACLOCK_RECT_RIGHT, MMIWIDGET_ACLOCK_RECT_BOTTOM}

//***********************************mp3*****************************************//
#ifndef MMI_GRID_IDLE_SUPPORT
//mp3名字区域
#define MMIWIDGET_MP3_MP3NAME_RECT_LEFT            14
#define MMIWIDGET_MP3_MP3NAME_RECT_TOP              12
#define MMIWIDGET_MP3_MP3NAME_RECT_RIGHT           167
#define MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM         32
#define MMIWIDGET_MP3_MP3NAME_RECT              {MMIWIDGET_MP3_MP3NAME_RECT_LEFT, MMIWIDGET_MP3_MP3NAME_RECT_TOP, MMIWIDGET_MP3_MP3NAME_RECT_RIGHT, MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM}
//后退按钮
#define MMIWIDGET_MP3_LBUTTON_LEFT            17
#define MMIWIDGET_MP3_LBUTTON_TOP             44
#define MMIWIDGET_MP3_LBUTTON_RIGHT           (MMIWIDGET_MP3_LBUTTON_LEFT+25-1)
#define MMIWIDGET_MP3_LBUTTON_BOTTOM         (MMIWIDGET_MP3_LBUTTON_TOP+25-1)
#define MMIWIDGET_MP3_LBUTTON_RECT            {MMIWIDGET_MP3_LBUTTON_LEFT, MMIWIDGET_MP3_LBUTTON_TOP, MMIWIDGET_MP3_LBUTTON_RIGHT, MMIWIDGET_MP3_LBUTTON_BOTTOM}

//播放按钮
#define MMIWIDGET_MP3_ENTRYPLAY_LEFT              57
#define MMIWIDGET_MP3_ENTRYPLAY_TOP                44 
#define MMIWIDGET_MP3_ENTRYPLAY_RIGHT           (MMIWIDGET_MP3_ENTRYPLAY_LEFT + 25 -1)
#define MMIWIDGET_MP3_ENTRYPLAY_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAY_TOP +25-1)
#define    MMIWIDGET_MP3_ENTRYPLAY_RECT    {MMIWIDGET_MP3_ENTRYPLAY_LEFT,MMIWIDGET_MP3_ENTRYPLAY_TOP,MMIWIDGET_MP3_ENTRYPLAY_RIGHT,MMIWIDGET_MP3_ENTRYPLAY_BOTTOM}
//前进按钮
#define MMIWIDGET_MP3_RBUTTON_LEFT              97
#define MMIWIDGET_MP3_RBUTTON_TOP                44
#define MMIWIDGET_MP3_RBUTTON_RIGHT           (MMIWIDGET_MP3_RBUTTON_LEFT +25 -1)
#define MMIWIDGET_MP3_RBUTTON_BOTTOM         (MMIWIDGET_MP3_RBUTTON_TOP+25-1)
#define MMIWIDGET_MP3_RBUTTON_RECT            {MMIWIDGET_MP3_RBUTTON_LEFT, MMIWIDGET_MP3_RBUTTON_TOP, MMIWIDGET_MP3_RBUTTON_RIGHT, MMIWIDGET_MP3_RBUTTON_BOTTOM}



//进入mp3播放器按钮
#define MMIWIDGET_MP3_ENTRYPLAYER_LEFT              137
#define MMIWIDGET_MP3_ENTRYPLAYER_TOP                44 
#define MMIWIDGET_MP3_ENTRYPLAYER_RIGHT           (MMIWIDGET_MP3_ENTRYPLAYER_LEFT + 25 -1)
#define MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAYER_TOP +25-1)
#define    MMIWIDGET_MP3_ENTRYPLAYER_RECT    {MMIWIDGET_MP3_ENTRYPLAYER_LEFT,MMIWIDGET_MP3_ENTRYPLAYER_TOP,MMIWIDGET_MP3_ENTRYPLAYER_RIGHT,MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM}


#define MMIWIDGET_MP3_CHANGEPANEL_LEFT            167
#define MMIWIDGET_MP3_CHANGEPANEL_TOP             16
#define MMIWIDGET_MP3_CHANGEPANEL_RIGHT          (MMIWIDGET_MP3_CHANGEPANEL_LEFT +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_BOTTOM      (MMIWIDGET_MP3_CHANGEPANEL_TOP +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_RECT          {MMIWIDGET_MP3_CHANGEPANEL_LEFT, MMIWIDGET_MP3_CHANGEPANEL_TOP, MMIWIDGET_MP3_CHANGEPANEL_RIGHT, MMIWIDGET_MP3_CHANGEPANEL_BOTTOM}

#define   MMIWIDGET_MP3_PROGRESS_RECT        {17,35,17+140-1,35+1}

#define   MMIWIDGET_MP3_PROGRESS_WIDTH              140

#define MMIWIDGET_MP3_VOL_IMAGE_LEFT            12
#define MMIWIDGET_MP3_VOL_IMAGE_TOP             28
#define MMIWIDGET_MP3_VOL_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_IMAGE_LEFT +15 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_IMAGE_TOP +18 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_RECT          {MMIWIDGET_MP3_VOL_IMAGE_LEFT, MMIWIDGET_MP3_VOL_IMAGE_TOP, MMIWIDGET_MP3_VOL_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_DEC_LEFT            13
#define MMIWIDGET_MP3_VOL_DEC_TOP             48
#define MMIWIDGET_MP3_VOL_DEC_RIGHT          (MMIWIDGET_MP3_VOL_DEC_LEFT +24 -1)
#define MMIWIDGET_MP3_VOL_DEC_BOTTOM      (MMIWIDGET_MP3_VOL_DEC_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_DEC_RECT          {MMIWIDGET_MP3_VOL_DEC_LEFT, MMIWIDGET_MP3_VOL_DEC_TOP, MMIWIDGET_MP3_VOL_DEC_RIGHT, MMIWIDGET_MP3_VOL_DEC_BOTTOM}

#define MMIWIDGET_MP3_VOL_ADD_LEFT            144
#define MMIWIDGET_MP3_VOL_ADD_TOP             48
#define MMIWIDGET_MP3_VOL_ADD_RIGHT          (MMIWIDGET_MP3_VOL_ADD_LEFT +23 -1)
#define MMIWIDGET_MP3_VOL_ADD_BOTTOM      (MMIWIDGET_MP3_VOL_ADD_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_ADD_RECT          {MMIWIDGET_MP3_VOL_ADD_LEFT, MMIWIDGET_MP3_VOL_ADD_TOP, MMIWIDGET_MP3_VOL_ADD_RIGHT, MMIWIDGET_MP3_VOL_ADD_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT            37
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP             48
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT+107-1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_LEFT            44
#define MMIWIDGET_MP3_VOL_PROGRESS_TOP             54
#define MMIWIDGET_MP3_VOL_PROGRESS_RIGHT          137
#define MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_TOP +6 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_TOP, MMIWIDGET_MP3_VOL_PROGRESS_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM}

#else
#ifdef BAR_PHONE_WIDGET
//mp3名字区域
#define MMIWIDGET_MP3_MP3NAME_RECT_LEFT            38
#define MMIWIDGET_MP3_MP3NAME_RECT_TOP              29
#define MMIWIDGET_MP3_MP3NAME_RECT_RIGHT           (MMIWIDGET_MP3_MP3NAME_RECT_LEFT + 162)
#define MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM         (MMIWIDGET_MP3_MP3NAME_RECT_TOP + 20)
#define MMIWIDGET_MP3_MP3NAME_RECT              {MMIWIDGET_MP3_MP3NAME_RECT_LEFT, MMIWIDGET_MP3_MP3NAME_RECT_TOP, MMIWIDGET_MP3_MP3NAME_RECT_RIGHT, MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM}

#define MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT            20
#define MMIWIDGET_MP3_MP3ALBUM_RECT_TOP              37
#define MMIWIDGET_MP3_MP3ALBUM_RECT_RIGHT           (MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT + 170)
#define MMIWIDGET_MP3_MP3ALBUM_RECT_BOTTOM         (MMIWIDGET_MP3_MP3ALBUM_RECT_TOP + 14)
#define MMIWIDGET_MP3_MP3ALBUM_RECT              {MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT, MMIWIDGET_MP3_MP3ALBUM_RECT_TOP, MMIWIDGET_MP3_MP3ALBUM_RECT_RIGHT, MMIWIDGET_MP3_MP3ALBUM_RECT_BOTTOM}

#define MMIWIDGET_MP3_MP3TIME_RECT_LEFT            38
#define MMIWIDGET_MP3_MP3TIME_RECT_TOP              67
#define MMIWIDGET_MP3_MP3TIME_RECT_RIGHT           (MMIWIDGET_MP3_MP3TIME_RECT_LEFT + 162)
#define MMIWIDGET_MP3_MP3TIME_RECT_BOTTOM         (MMIWIDGET_MP3_MP3TIME_RECT_TOP + 12)
#define MMIWIDGET_MP3_MP3TIME_RECT              {MMIWIDGET_MP3_MP3TIME_RECT_LEFT, MMIWIDGET_MP3_MP3TIME_RECT_TOP, MMIWIDGET_MP3_MP3TIME_RECT_RIGHT, MMIWIDGET_MP3_MP3TIME_RECT_BOTTOM}

#define   MMIWIDGET_MP3_PROGRESS_RECT        {38,54,38+162-1,54+6}
#define   MMIWIDGET_MP3_PROGRESS_WIDTH       162
#define   MMIWIDGET_MP3_PROGRESS_HEIGHT      6

#define MMIWIDGET_MP3_BUTTON_WIDTH            14
#define MMIWIDGET_MP3_BUTTON_HEIGHT           8

//后退按钮
#define MMIWIDGET_MP3_LBUTTON_LEFT            248
#define MMIWIDGET_MP3_LBUTTON_TOP             23
#define MMIWIDGET_MP3_LBUTTON_RIGHT           (MMIWIDGET_MP3_LBUTTON_LEFT+MMIWIDGET_MP3_BUTTON_WIDTH-1)
#define MMIWIDGET_MP3_LBUTTON_BOTTOM         (MMIWIDGET_MP3_LBUTTON_TOP+MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define MMIWIDGET_MP3_LBUTTON_RECT            {MMIWIDGET_MP3_LBUTTON_LEFT, MMIWIDGET_MP3_LBUTTON_TOP, MMIWIDGET_MP3_LBUTTON_RIGHT, MMIWIDGET_MP3_LBUTTON_BOTTOM}

//播放按钮
#define MMIWIDGET_MP3_ENTRYPLAY_LEFT              238
#define MMIWIDGET_MP3_ENTRYPLAY_TOP               40
#define MMIWIDGET_MP3_ENTRYPLAY_RIGHT           (MMIWIDGET_MP3_ENTRYPLAY_LEFT + 34 -1)
#define MMIWIDGET_MP3_ENTRYPLAY_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAY_TOP +34 -1)
#define    MMIWIDGET_MP3_ENTRYPLAY_RECT    {MMIWIDGET_MP3_ENTRYPLAY_LEFT,MMIWIDGET_MP3_ENTRYPLAY_TOP,MMIWIDGET_MP3_ENTRYPLAY_RIGHT,MMIWIDGET_MP3_ENTRYPLAY_BOTTOM}
//前进按钮
#define MMIWIDGET_MP3_RBUTTON_LEFT              248
#define MMIWIDGET_MP3_RBUTTON_TOP               83
#define MMIWIDGET_MP3_RBUTTON_RIGHT           (MMIWIDGET_MP3_RBUTTON_LEFT +MMIWIDGET_MP3_BUTTON_WIDTH -1)
#define MMIWIDGET_MP3_RBUTTON_BOTTOM         (MMIWIDGET_MP3_RBUTTON_TOP+MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define MMIWIDGET_MP3_RBUTTON_RECT            {MMIWIDGET_MP3_RBUTTON_LEFT, MMIWIDGET_MP3_RBUTTON_TOP, MMIWIDGET_MP3_RBUTTON_RIGHT, MMIWIDGET_MP3_RBUTTON_BOTTOM}



//进入mp3播放器按钮
#define MMIWIDGET_MP3_ENTRYPLAYER_LEFT              10
#define MMIWIDGET_MP3_ENTRYPLAYER_TOP                10 
#define MMIWIDGET_MP3_ENTRYPLAYER_RIGHT           231
#define MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM          148
#define    MMIWIDGET_MP3_ENTRYPLAYER_RECT    {MMIWIDGET_MP3_ENTRYPLAYER_LEFT,MMIWIDGET_MP3_ENTRYPLAYER_TOP,MMIWIDGET_MP3_ENTRYPLAYER_RIGHT,MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM}

#else
//mp3名字区域
#define MMIWIDGET_MP3_MP3NAME_RECT_LEFT            21
#define MMIWIDGET_MP3_MP3NAME_RECT_TOP              16
#define MMIWIDGET_MP3_MP3NAME_RECT_RIGHT           (MMIWIDGET_MP3_MP3NAME_RECT_LEFT + 218)
#define MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM         (MMIWIDGET_MP3_MP3NAME_RECT_TOP + 24)
#define MMIWIDGET_MP3_MP3NAME_RECT              {MMIWIDGET_MP3_MP3NAME_RECT_LEFT, MMIWIDGET_MP3_MP3NAME_RECT_TOP, MMIWIDGET_MP3_MP3NAME_RECT_RIGHT, MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM}

#define MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT            MMIWIDGET_MP3_MP3NAME_RECT_LEFT
#define MMIWIDGET_MP3_MP3ALBUM_RECT_TOP              (16 + 48)
#define MMIWIDGET_MP3_MP3ALBUM_RECT_RIGHT           (MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT + 218)
#define MMIWIDGET_MP3_MP3ALBUM_RECT_BOTTOM         (MMIWIDGET_MP3_MP3ALBUM_RECT_TOP + 24)
#define MMIWIDGET_MP3_MP3ALBUM_RECT              {MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT, MMIWIDGET_MP3_MP3ALBUM_RECT_TOP, MMIWIDGET_MP3_MP3ALBUM_RECT_RIGHT, MMIWIDGET_MP3_MP3ALBUM_RECT_BOTTOM}

#define MMIWIDGET_MP3_MP3TIME_RECT_LEFT            MMIWIDGET_MP3_MP3NAME_RECT_LEFT
#define MMIWIDGET_MP3_MP3TIME_RECT_TOP              (16 + 80)
#define MMIWIDGET_MP3_MP3TIME_RECT_RIGHT           (MMIWIDGET_MP3_MP3TIME_RECT_LEFT + 218)
#define MMIWIDGET_MP3_MP3TIME_RECT_BOTTOM         (MMIWIDGET_MP3_MP3TIME_RECT_TOP + 24)
#define MMIWIDGET_MP3_MP3TIME_RECT              {MMIWIDGET_MP3_MP3TIME_RECT_LEFT, MMIWIDGET_MP3_MP3TIME_RECT_TOP, MMIWIDGET_MP3_MP3TIME_RECT_RIGHT, MMIWIDGET_MP3_MP3TIME_RECT_BOTTOM}

#define   MMIWIDGET_MP3_PROGRESS_WIDTH       218
#define   MMIWIDGET_MP3_PROGRESS_HEIGHT      12
#define   MMIWIDGET_MP3_PROGRESS_RECT        {MMIWIDGET_MP3_MP3NAME_RECT_LEFT,121,\
                                            31+MMIWIDGET_MP3_PROGRESS_WIDTH-1,\
                                            121+MMIWIDGET_MP3_PROGRESS_HEIGHT}

#define MMIWIDGET_MP3_BUTTON_WIDTH            24
#define MMIWIDGET_MP3_BUTTON_HEIGHT           24
#define MMIWIDGET_MP3_BUTTON_INTERVAL_Y       24

//后退按钮
#define MMIWIDGET_MP3_LBUTTON_LEFT            258
#define MMIWIDGET_MP3_LBUTTON_TOP             16
#define MMIWIDGET_MP3_LBUTTON_RIGHT           (MMIWIDGET_MP3_LBUTTON_LEFT+MMIWIDGET_MP3_BUTTON_WIDTH-1)
#define MMIWIDGET_MP3_LBUTTON_BOTTOM         (MMIWIDGET_MP3_LBUTTON_TOP+MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define MMIWIDGET_MP3_LBUTTON_RECT            {MMIWIDGET_MP3_LBUTTON_LEFT, MMIWIDGET_MP3_LBUTTON_TOP, MMIWIDGET_MP3_LBUTTON_RIGHT, MMIWIDGET_MP3_LBUTTON_BOTTOM}

//播放按钮
#define MMIWIDGET_MP3_ENTRYPLAY_LEFT              MMIWIDGET_MP3_LBUTTON_LEFT
#define MMIWIDGET_MP3_ENTRYPLAY_TOP               (MMIWIDGET_MP3_LBUTTON_BOTTOM + MMIWIDGET_MP3_BUTTON_INTERVAL_Y)
#define MMIWIDGET_MP3_ENTRYPLAY_RIGHT           (MMIWIDGET_MP3_ENTRYPLAY_LEFT + MMIWIDGET_MP3_BUTTON_WIDTH -1)
#define MMIWIDGET_MP3_ENTRYPLAY_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAY_TOP +MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define    MMIWIDGET_MP3_ENTRYPLAY_RECT    {MMIWIDGET_MP3_ENTRYPLAY_LEFT,MMIWIDGET_MP3_ENTRYPLAY_TOP,MMIWIDGET_MP3_ENTRYPLAY_RIGHT,MMIWIDGET_MP3_ENTRYPLAY_BOTTOM}
//前进按钮
#define MMIWIDGET_MP3_RBUTTON_LEFT              MMIWIDGET_MP3_LBUTTON_LEFT
#define MMIWIDGET_MP3_RBUTTON_TOP               (MMIWIDGET_MP3_ENTRYPLAY_BOTTOM + MMIWIDGET_MP3_BUTTON_INTERVAL_Y)
#define MMIWIDGET_MP3_RBUTTON_RIGHT           (MMIWIDGET_MP3_RBUTTON_LEFT +MMIWIDGET_MP3_BUTTON_WIDTH -1)
#define MMIWIDGET_MP3_RBUTTON_BOTTOM         (MMIWIDGET_MP3_RBUTTON_TOP+MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define MMIWIDGET_MP3_RBUTTON_RECT            {MMIWIDGET_MP3_RBUTTON_LEFT, MMIWIDGET_MP3_RBUTTON_TOP, MMIWIDGET_MP3_RBUTTON_RIGHT, MMIWIDGET_MP3_RBUTTON_BOTTOM}



//进入mp3播放器按钮
#define MMIWIDGET_MP3_ENTRYPLAYER_LEFT              10
#define MMIWIDGET_MP3_ENTRYPLAYER_TOP                10 
#define MMIWIDGET_MP3_ENTRYPLAYER_RIGHT           231
#define MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM          148
#define    MMIWIDGET_MP3_ENTRYPLAYER_RECT    {MMIWIDGET_MP3_ENTRYPLAYER_LEFT,MMIWIDGET_MP3_ENTRYPLAYER_TOP,MMIWIDGET_MP3_ENTRYPLAYER_RIGHT,MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM}
#endif

#define MMIWIDGET_MP3_CHANGEPANEL_LEFT            167
#define MMIWIDGET_MP3_CHANGEPANEL_TOP             16
#define MMIWIDGET_MP3_CHANGEPANEL_RIGHT          (MMIWIDGET_MP3_CHANGEPANEL_LEFT +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_BOTTOM      (MMIWIDGET_MP3_CHANGEPANEL_TOP +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_RECT          {MMIWIDGET_MP3_CHANGEPANEL_LEFT, MMIWIDGET_MP3_CHANGEPANEL_TOP, MMIWIDGET_MP3_CHANGEPANEL_RIGHT, MMIWIDGET_MP3_CHANGEPANEL_BOTTOM}

//#define   MMIWIDGET_MP3_PROGRESS_RECT        {1,174,1+252-8,174+1}

//#define   MMIWIDGET_MP3_PROGRESS_WIDTH              244

#define MMIWIDGET_MP3_VOL_IMAGE_LEFT            12
#define MMIWIDGET_MP3_VOL_IMAGE_TOP             28
#define MMIWIDGET_MP3_VOL_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_IMAGE_LEFT +15 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_IMAGE_TOP +18 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_RECT          {MMIWIDGET_MP3_VOL_IMAGE_LEFT, MMIWIDGET_MP3_VOL_IMAGE_TOP, MMIWIDGET_MP3_VOL_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_DEC_LEFT            13
#define MMIWIDGET_MP3_VOL_DEC_TOP             48
#define MMIWIDGET_MP3_VOL_DEC_RIGHT          (MMIWIDGET_MP3_VOL_DEC_LEFT +24 -1)
#define MMIWIDGET_MP3_VOL_DEC_BOTTOM      (MMIWIDGET_MP3_VOL_DEC_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_DEC_RECT          {MMIWIDGET_MP3_VOL_DEC_LEFT, MMIWIDGET_MP3_VOL_DEC_TOP, MMIWIDGET_MP3_VOL_DEC_RIGHT, MMIWIDGET_MP3_VOL_DEC_BOTTOM}

#define MMIWIDGET_MP3_VOL_ADD_LEFT            144
#define MMIWIDGET_MP3_VOL_ADD_TOP             48
#define MMIWIDGET_MP3_VOL_ADD_RIGHT          (MMIWIDGET_MP3_VOL_ADD_LEFT +23 -1)
#define MMIWIDGET_MP3_VOL_ADD_BOTTOM      (MMIWIDGET_MP3_VOL_ADD_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_ADD_RECT          {MMIWIDGET_MP3_VOL_ADD_LEFT, MMIWIDGET_MP3_VOL_ADD_TOP, MMIWIDGET_MP3_VOL_ADD_RIGHT, MMIWIDGET_MP3_VOL_ADD_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT            37
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP             48
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT+107-1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_LEFT            44
#define MMIWIDGET_MP3_VOL_PROGRESS_TOP             54
#define MMIWIDGET_MP3_VOL_PROGRESS_RIGHT          137
#define MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_TOP +6 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_TOP, MMIWIDGET_MP3_VOL_PROGRESS_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM}

#define MMIWIDGET_MP3_COVER_RECT_LEFT          14
#define MMIWIDGET_MP3_COVER_RECT_TOP           10
#define MMIWIDGET_MP3_COVER_RECT_RIGHT         240
#define MMIWIDGET_MP3_COVER_RECT_BOTTOM        232
#define MMIWIDGET_MP3_COVER_RECT              {MMIWIDGET_MP3_COVER_RECT_LEFT, MMIWIDGET_MP3_COVER_RECT_TOP, MMIWIDGET_MP3_COVER_RECT_RIGHT, MMIWIDGET_MP3_COVER_RECT_BOTTOM}

#define MMIWIDGET_MP3_PANEL_RECT_LEFT            0
#define MMIWIDGET_MP3_PANEL_RECT_TOP              149
#define MMIWIDGET_MP3_PANEL_RECT_RIGHT           252
#define MMIWIDGET_MP3_PANEL_RECT_BOTTOM         224
#define MMIWIDGET_MP3_PANEL_RECT              {MMIWIDGET_MP3_PANEL_RECT_LEFT, MMIWIDGET_MP3_PANEL_RECT_TOP, MMIWIDGET_MP3_PANEL_RECT_RIGHT, MMIWIDGET_MP3_PANEL_RECT_BOTTOM}

#endif


//*****************************************PB*********************************************************//
//中央大图宽高
#define MMIWIDGET_PB_WIDGET_BIG_WIDTH         92
#define MMIWIDGET_PB_WIDGET_BIG_HEIGHT        92
//边上小图宽高
#define MMIWIDGET_PB_WIDGET_SMALL_WIDTH       45
#define MMIWIDGET_PB_WIDGET_SMALL_HEIGHT      45
//各pb widget区域
#define MMIWIDGET_PB_WIDGET_1_2_LEFT          8//17
#define MMIWIDGET_PB_WIDGET_3_4_LEFT          164//178
#define MMIWIDGET_PB_WIDGET_1_3_TOP           8//106
#define MMIWIDGET_PB_WIDGET_2_4_TOP           58//154

#define MMIWIDGET_PB_WIDGET_0_LEFT            62//71
#define MMIWIDGET_PB_WIDGET_0_TOP             12//101
#define MMIWIDGET_PB_WIDGET_0_RIGHT       (MMIWIDGET_PB_WIDGET_0_LEFT+MMIWIDGET_PB_WIDGET_BIG_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_0_BOTTOM      (MMIWIDGET_PB_WIDGET_0_TOP+MMIWIDGET_PB_WIDGET_BIG_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_0_RECT      {MMIWIDGET_PB_WIDGET_0_LEFT, MMIWIDGET_PB_WIDGET_0_TOP, MMIWIDGET_PB_WIDGET_0_RIGHT, MMIWIDGET_PB_WIDGET_0_BOTTOM}

#define MMIWIDGET_PB_WIDGET_1_LEFT        MMIWIDGET_PB_WIDGET_1_2_LEFT
#define MMIWIDGET_PB_WIDGET_1_TOP         MMIWIDGET_PB_WIDGET_1_3_TOP
#define MMIWIDGET_PB_WIDGET_1_RIGHT       (MMIWIDGET_PB_WIDGET_1_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_1_BOTTOM      (MMIWIDGET_PB_WIDGET_1_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_1_RECT      {MMIWIDGET_PB_WIDGET_1_LEFT, MMIWIDGET_PB_WIDGET_1_TOP, MMIWIDGET_PB_WIDGET_1_RIGHT, MMIWIDGET_PB_WIDGET_1_BOTTOM}

#define MMIWIDGET_PB_WIDGET_2_LEFT        MMIWIDGET_PB_WIDGET_1_2_LEFT
#define MMIWIDGET_PB_WIDGET_2_TOP         MMIWIDGET_PB_WIDGET_2_4_TOP
#define MMIWIDGET_PB_WIDGET_2_RIGHT       (MMIWIDGET_PB_WIDGET_2_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_2_BOTTOM      (MMIWIDGET_PB_WIDGET_2_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_2_RECT      {MMIWIDGET_PB_WIDGET_2_LEFT, MMIWIDGET_PB_WIDGET_2_TOP, MMIWIDGET_PB_WIDGET_2_RIGHT, MMIWIDGET_PB_WIDGET_2_BOTTOM}

#define MMIWIDGET_PB_WIDGET_3_LEFT        MMIWIDGET_PB_WIDGET_3_4_LEFT
#define MMIWIDGET_PB_WIDGET_3_TOP         MMIWIDGET_PB_WIDGET_1_3_TOP
#define MMIWIDGET_PB_WIDGET_3_RIGHT       (MMIWIDGET_PB_WIDGET_3_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_3_BOTTOM      (MMIWIDGET_PB_WIDGET_3_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_3_RECT      {MMIWIDGET_PB_WIDGET_3_LEFT, MMIWIDGET_PB_WIDGET_3_TOP, MMIWIDGET_PB_WIDGET_3_RIGHT, MMIWIDGET_PB_WIDGET_3_BOTTOM}

#define MMIWIDGET_PB_WIDGET_4_LEFT        MMIWIDGET_PB_WIDGET_3_4_LEFT
#define MMIWIDGET_PB_WIDGET_4_TOP         MMIWIDGET_PB_WIDGET_2_4_TOP
#define MMIWIDGET_PB_WIDGET_4_RIGHT       (MMIWIDGET_PB_WIDGET_4_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_4_BOTTOM      (MMIWIDGET_PB_WIDGET_4_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_4_RECT      {MMIWIDGET_PB_WIDGET_4_LEFT, MMIWIDGET_PB_WIDGET_4_TOP, MMIWIDGET_PB_WIDGET_4_RIGHT, MMIWIDGET_PB_WIDGET_4_BOTTOM}

#define MMIWIDGET_PB_WIDGET_CALL_LEFT  		59
#define MMIWIDGET_PB_WIDGET_CALL_TOP		114
#define MMIWIDGET_PB_WIDGET_CALL_RIGHT		103
#define MMIWIDGET_PB_WIDGET_CALL_BOTTOM	142
#define MMIWIDGET_PB_WIDGET_CALL_RECT      {MMIWIDGET_PB_WIDGET_CALL_LEFT, MMIWIDGET_PB_WIDGET_CALL_TOP, MMIWIDGET_PB_WIDGET_CALL_RIGHT, MMIWIDGET_PB_WIDGET_CALL_BOTTOM}

#define MMIWIDGET_PB_WIDGET_SMS_LEFT  		113
#define MMIWIDGET_PB_WIDGET_SMS_TOP			114
#define MMIWIDGET_PB_WIDGET_SMS_RIGHT		147
#define MMIWIDGET_PB_WIDGET_SMS_BOTTOM		142
#define MMIWIDGET_PB_WIDGET_SMS_RECT      {MMIWIDGET_PB_WIDGET_SMS_LEFT, MMIWIDGET_PB_WIDGET_SMS_TOP, MMIWIDGET_PB_WIDGET_SMS_RIGHT, MMIWIDGET_PB_WIDGET_SMS_BOTTOM}

//*****************************************shortcut menu ****************************************8//
#define    MMIWIDGET_SHORTCUT_MENU_ICON_START_X       5

#define    MMIWIDGET_SHORTCUT_MENU_ICON_START_Y       10 

#define    MMIWIDGET_SHORTCUT_MENU_ICON_INTERVAL       5 

#define    MMIWIDGET_SHORTCUT_MENU_EMPTY_RECT     {0,0,0,0}
//默认左键头的区域
#define    MMIWIDGET_SHORTCUT_MENU_PAGE_BUTTON   {170,19,170+24,19+24}
//**************************************************calendar *****************************************************//
#define MMIWIDGET_CALENDAR_LINE_WIDTH      25
#define MMIWIDGET_CALENDAR_LINE_HEIGHT     12
#define MMIWIDGET_CALENDAR_LINE_GAP  10

#define MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT   72
#define MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT+ MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM6_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT + MMIWIDGET_CALENDAR_LINE_WIDTH-1)

#define  MMIWIDGET_CALENDAR_MONTH_LINE0_TOP   84
#define  MMIWIDGET_CALENDAR_MONTH_LINE1_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE0_TOP+ MMIWIDGET_CALENDAR_LINE_HEIGHT +MMIWIDGET_CALENDAR_LINE_GAP -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE2_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE1_TOP + MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE3_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE2_TOP+ MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE4_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE3_TOP + MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE5_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE4_TOP + MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP -1)

#define MMIWIDGET_CALENDAR_WEEK_TOP    66

#define MMIWIDGET_CALENDAR_MONTH_LEFT   38 
#define MMIWIDGET_CALENDAR_MONTH_TOP    41
#define MMIWIDGET_CALENDAR_MONTH_RIGHT  (MMIWIDGET_CALENDAR_MONTH_LEFT + 154 -1)
#define MMIWIDGET_CALENDAR_MONTH_BOTTOM (MMIWIDGET_CALENDAR_MONTH_TOP + 18 -1)
#define MMIWIDGET_CALENDAR_MONTH_RECT {MMIWIDGET_CALENDAR_MONTH_LEFT,MMIWIDGET_CALENDAR_MONTH_TOP,MMIWIDGET_CALENDAR_MONTH_RIGHT,MMIWIDGET_CALENDAR_MONTH_BOTTOM}

#define MMIWIDGET_CALENDAR_YEAR_LEFT   198 
#define MMIWIDGET_CALENDAR_YEAR_TOP    37
#define MMIWIDGET_CALENDAR_YEAR_RIGHT  (MMIWIDGET_CALENDAR_YEAR_LEFT + 41 -1)
#define MMIWIDGET_CALENDAR_YEAR_BOTTOM (MMIWIDGET_CALENDAR_YEAR_TOP + 11 -1)
#define MMIWIDGET_CALENDAR_YEAR_RECT {MMIWIDGET_CALENDAR_YEAR_LEFT,MMIWIDGET_CALENDAR_YEAR_TOP,MMIWIDGET_CALENDAR_YEAR_RIGHT,MMIWIDGET_CALENDAR_YEAR_BOTTOM}

#define MMIWIDGET_CALENDAR_DAY_LEFT   33 
#define MMIWIDGET_CALENDAR_DAY_TOP    67
#define MMIWIDGET_CALENDAR_DAY_RIGHT  (MMIWIDGET_CALENDAR_DAY_LEFT + 33 -1)
#define MMIWIDGET_CALENDAR_DAY_BOTTOM (MMIWIDGET_CALENDAR_DAY_TOP + 33 -1)
#define MMIWIDGET_CALENDAR_DAY_RECT {MMIWIDGET_CALENDAR_DAY_LEFT,MMIWIDGET_CALENDAR_DAY_TOP,MMIWIDGET_CALENDAR_DAY_RIGHT,MMIWIDGET_CALENDAR_DAY_BOTTOM}

#define MMIWIDGET_CALENDAR_LINE_WIDTH_H      25
#define MMIWIDGET_CALENDAR_LINE_HEIGHT_H     12
#define MMIWIDGET_CALENDAR_LINE_GAP_H  10

#define MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT_H   52
#define MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT_H+MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT_H+MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT_H+MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT_H+MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT_H+ MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM6_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT_H + MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)

#define  MMIWIDGET_CALENDAR_MONTH_LINE0_TOP_H   72
#define  MMIWIDGET_CALENDAR_MONTH_LINE1_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE0_TOP_H+ MMIWIDGET_CALENDAR_LINE_HEIGHT_H +MMIWIDGET_CALENDAR_LINE_GAP_H -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE2_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE1_TOP_H + MMIWIDGET_CALENDAR_LINE_HEIGHT_H+MMIWIDGET_CALENDAR_LINE_GAP_H -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE3_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE2_TOP_H+ MMIWIDGET_CALENDAR_LINE_HEIGHT_H+MMIWIDGET_CALENDAR_LINE_GAP_H -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE4_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE3_TOP_H + MMIWIDGET_CALENDAR_LINE_HEIGHT_H+MMIWIDGET_CALENDAR_LINE_GAP_H -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE5_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE4_TOP_H + MMIWIDGET_CALENDAR_LINE_HEIGHT_H+MMIWIDGET_CALENDAR_LINE_GAP_H -1)

#define MMIWIDGET_CALENDAR_WEEK_TOP_H    55

#define MMIWIDGET_CALENDAR_MONTH_LEFT_H   22 
#define MMIWIDGET_CALENDAR_MONTH_TOP_H    29
#define MMIWIDGET_CALENDAR_MONTH_RIGHT_H  (MMIWIDGET_CALENDAR_MONTH_LEFT_H + 145 -1)
#define MMIWIDGET_CALENDAR_MONTH_BOTTOM_H (MMIWIDGET_CALENDAR_MONTH_TOP_H + 18 -1)
#define MMIWIDGET_CALENDAR_MONTH_RECT_H {MMIWIDGET_CALENDAR_MONTH_LEFT_H,MMIWIDGET_CALENDAR_MONTH_TOP_H,MMIWIDGET_CALENDAR_MONTH_RIGHT_H,MMIWIDGET_CALENDAR_MONTH_BOTTOM_H}

#define MMIWIDGET_CALENDAR_YEAR_LEFT_H   177 
#define MMIWIDGET_CALENDAR_YEAR_TOP_H    29
#define MMIWIDGET_CALENDAR_YEAR_RIGHT_H  (MMIWIDGET_CALENDAR_YEAR_LEFT_H + 40 -1)
#define MMIWIDGET_CALENDAR_YEAR_BOTTOM_H (MMIWIDGET_CALENDAR_YEAR_TOP_H + 11 -1)
#define MMIWIDGET_CALENDAR_YEAR_RECT_H {MMIWIDGET_CALENDAR_YEAR_LEFT_H,MMIWIDGET_CALENDAR_YEAR_TOP_H,MMIWIDGET_CALENDAR_YEAR_RIGHT_H,MMIWIDGET_CALENDAR_YEAR_BOTTOM_H}

#define MMIWIDGET_CALENDAR_DAY_LEFT_H   21 
#define MMIWIDGET_CALENDAR_DAY_TOP_H    55
#define MMIWIDGET_CALENDAR_DAY_RIGHT_H  (MMIWIDGET_CALENDAR_DAY_LEFT_H + 24 -1)
#define MMIWIDGET_CALENDAR_DAY_BOTTOM_H (MMIWIDGET_CALENDAR_DAY_TOP_H + 24 -1)
#define MMIWIDGET_CALENDAR_DAY_RECT_H {MMIWIDGET_CALENDAR_DAY_LEFT_H,MMIWIDGET_CALENDAR_DAY_TOP_H,MMIWIDGET_CALENDAR_DAY_RIGHT_H,MMIWIDGET_CALENDAR_DAY_BOTTOM_H}

//*****************************memo   ******************************************************//
#define   MMIWIDGET_MEMO_TOP_GAP                       25

#define   MMIWIDGET_MEMO_BOTTOM_GAP                20

#define   MMIWIDGET_MEMO_LEFT_GAP                     20

#define   MMIWIDGET_MEMO_RIGHT_GAP                   10

#define   MMIWIDGET_MEMO_LINE_SPACE                   2

//***********************************network name  *****************************************//

#define   MMIWIDGET_NETWORK_SIM1_SIM2_INTERVAL    6

#define   MMIWIDGET_NETWORK_TOP_SPACE                     7

#ifdef MMI_GRID_IDLE_SUPPORT
#define MMIWIDGET_NETWORK_WIDGET_SIM1_LEFT  		0
#define MMIWIDGET_NETWORK_WIDGET_SIM1_TOP			0
#define MMIWIDGET_NETWORK_WIDGET_SIM1_RIGHT		    142
#define MMIWIDGET_NETWORK_WIDGET_SIM1_BOTTOM		82
#define MMIWIDGET_NETWORK_WIDGET_SIM1_RECT      {MMIWIDGET_NETWORK_WIDGET_SIM1_LEFT, MMIWIDGET_NETWORK_WIDGET_SIM1_TOP, MMIWIDGET_NETWORK_WIDGET_SIM1_RIGHT, MMIWIDGET_NETWORK_WIDGET_SIM1_BOTTOM}

#define MMIWIDGET_NETWORK_WIDGET_SIM2_LEFT  		150
#define MMIWIDGET_NETWORK_WIDGET_SIM2_TOP			0
#define MMIWIDGET_NETWORK_WIDGET_SIM2_RIGHT		    292
#define MMIWIDGET_NETWORK_WIDGET_SIM2_BOTTOM		82
#define MMIWIDGET_NETWORK_WIDGET_SIM2_RECT      {MMIWIDGET_NETWORK_WIDGET_SIM2_LEFT, MMIWIDGET_NETWORK_WIDGET_SIM2_TOP, MMIWIDGET_NETWORK_WIDGET_SIM2_RIGHT, MMIWIDGET_NETWORK_WIDGET_SIM2_BOTTOM}

#define MMIWIDGET_NETWORK_WIDGET_SIM3_LEFT  		0
#define MMIWIDGET_NETWORK_WIDGET_SIM3_TOP			90
#define MMIWIDGET_NETWORK_WIDGET_SIM3_RIGHT		    142
#define MMIWIDGET_NETWORK_WIDGET_SIM3_BOTTOM		173
#define MMIWIDGET_NETWORK_WIDGET_SIM3_RECT      {MMIWIDGET_NETWORK_WIDGET_SIM3_LEFT, MMIWIDGET_NETWORK_WIDGET_SIM3_TOP, MMIWIDGET_NETWORK_WIDGET_SIM3_RIGHT, MMIWIDGET_NETWORK_WIDGET_SIM3_BOTTOM}

#define MMIWIDGET_NETWORK_WIDGET_SIM4_LEFT  		150
#define MMIWIDGET_NETWORK_WIDGET_SIM4_TOP			90
#define MMIWIDGET_NETWORK_WIDGET_SIM4_RIGHT		    292
#define MMIWIDGET_NETWORK_WIDGET_SIM4_BOTTOM		173
#define MMIWIDGET_NETWORK_WIDGET_SIM4_RECT      {MMIWIDGET_NETWORK_WIDGET_SIM4_LEFT, MMIWIDGET_NETWORK_WIDGET_SIM4_TOP, MMIWIDGET_NETWORK_WIDGET_SIM4_RIGHT, MMIWIDGET_NETWORK_WIDGET_SIM4_BOTTOM}
#endif
//custom word

//   *********************new sms      **********************************//
#define    MMIWIDGET_NEWSMS_OEPN_RECT             {14,130,14+67-1,130+41-1}

#define    MMIWIDGET_NEWSMS_CANCEL_RECT         {81,130,81+67-1,130+41-1}

//行间距
#define  MMIWIDGET_NEWSMS_LINE_SPACE          4

//上间距
#define  MMIWIDGET_NEWSMS_TOP_SPACE          25
//左间距
#define  MMIWIDGET_NEWSMS_LEFT_SPACE          25
//段间距
#define  MMIWIDGET_NEWSMS_SENTENCE_SPACE          20
//右间距
#define    MMIWIDGET_NEWSMS_RIGHT_GAP                   3
//****************************FM   *************************************//

#ifdef BAR_PHONE_WIDGET 
//后退按钮
#define MMIWIDGET_FM_LBUTTON_LEFT           248
#define MMIWIDGET_FM_LBUTTON_TOP            25
#define MMIWIDGET_FM_LBUTTON_RIGHT			(MMIWIDGET_FM_LBUTTON_LEFT + 14 - 1)
#define MMIWIDGET_FM_LBUTTON_BOTTOM			(MMIWIDGET_FM_LBUTTON_TOP + 8 - 1)
#define MMIWIDGET_FM_LBUTTON_RECT           {MMIWIDGET_FM_LBUTTON_LEFT, MMIWIDGET_FM_LBUTTON_TOP, MMIWIDGET_FM_LBUTTON_RIGHT, MMIWIDGET_FM_LBUTTON_BOTTOM}

//前进按钮
#define MMIWIDGET_FM_RBUTTON_LEFT           248
#define MMIWIDGET_FM_RBUTTON_TOP            79
#define MMIWIDGET_FM_RBUTTON_RIGHT          (MMIWIDGET_FM_RBUTTON_LEFT + 14 - 1)
#define MMIWIDGET_FM_RBUTTON_BOTTOM			(MMIWIDGET_FM_RBUTTON_TOP + 8 - 1)
#define MMIWIDGET_FM_RBUTTON_RECT           {MMIWIDGET_FM_RBUTTON_LEFT, MMIWIDGET_FM_RBUTTON_TOP, MMIWIDGET_FM_RBUTTON_RIGHT, MMIWIDGET_FM_RBUTTON_BOTTOM}

//fm名字区域
#define MMIWIDGET_FM_NAME_RECT_LEFT           48
#define MMIWIDGET_FM_NAME_RECT_TOP            45
#define MMIWIDGET_FM_NAME_RECT_RIGHT          (MMIWIDGET_FM_NAME_RECT_LEFT + 144 - 1)
#define MMIWIDGET_FM_NAME_RECT_BOTTOM         (MMIWIDGET_FM_NAME_RECT_TOP + 21 - 1)
#define MMIWIDGET_FM_NAME_RECT                {MMIWIDGET_FM_NAME_RECT_LEFT, MMIWIDGET_FM_NAME_RECT_TOP, MMIWIDGET_FM_NAME_RECT_RIGHT, MMIWIDGET_FM_NAME_RECT_BOTTOM}

//播放按钮
#define MMIWIDGET_FM_PLAYBUTTON_LEFT           238
#define MMIWIDGET_FM_PLAYBUTTON_TOP            40
#define MMIWIDGET_FM_PLAYBUTTON_RIGHT		   (MMIWIDGET_FM_PLAYBUTTON_LEFT + 34 - 1)
#define MMIWIDGET_FM_PLAYBUTTON_BOTTOM		   (MMIWIDGET_FM_PLAYBUTTON_TOP + 34 - 1)
#define MMIWIDGET_FM_PLAYBUTTON_RECT           {MMIWIDGET_FM_PLAYBUTTON_LEFT, MMIWIDGET_FM_PLAYBUTTON_TOP, MMIWIDGET_FM_PLAYBUTTON_RIGHT, MMIWIDGET_FM_PLAYBUTTON_BOTTOM}
#else

//后退按钮
#define MMIWIDGET_FM_LBUTTON_LEFT           20
#define MMIWIDGET_FM_LBUTTON_TOP            10
#define MMIWIDGET_FM_LBUTTON_RIGHT			(MMIWIDGET_FM_LBUTTON_LEFT + 20 - 1)
#define MMIWIDGET_FM_LBUTTON_BOTTOM			(MMIWIDGET_FM_LBUTTON_TOP + 30 - 1)
#define MMIWIDGET_FM_LBUTTON_RECT           {MMIWIDGET_FM_LBUTTON_LEFT, MMIWIDGET_FM_LBUTTON_TOP, MMIWIDGET_FM_LBUTTON_RIGHT, MMIWIDGET_FM_LBUTTON_BOTTOM}

//前进按钮
#define MMIWIDGET_FM_RBUTTON_LEFT           204
#define MMIWIDGET_FM_RBUTTON_TOP            10
#define MMIWIDGET_FM_RBUTTON_RIGHT          (MMIWIDGET_FM_RBUTTON_LEFT + 20 - 1)
#define MMIWIDGET_FM_RBUTTON_BOTTOM			(MMIWIDGET_FM_RBUTTON_TOP + 30 - 1)
#define MMIWIDGET_FM_RBUTTON_RECT           {MMIWIDGET_FM_RBUTTON_LEFT, MMIWIDGET_FM_RBUTTON_TOP, MMIWIDGET_FM_RBUTTON_RIGHT, MMIWIDGET_FM_RBUTTON_BOTTOM}

//fm名字区域
#define MMIWIDGET_FM_NAME_RECT_LEFT           50
#define MMIWIDGET_FM_NAME_RECT_TOP            10
#define MMIWIDGET_FM_NAME_RECT_RIGHT          (MMIWIDGET_FM_NAME_RECT_LEFT + 170 - 1)
#define MMIWIDGET_FM_NAME_RECT_BOTTOM         (MMIWIDGET_FM_NAME_RECT_TOP + 30 - 1)
#define MMIWIDGET_FM_NAME_RECT                {MMIWIDGET_FM_NAME_RECT_LEFT, MMIWIDGET_FM_NAME_RECT_TOP, MMIWIDGET_FM_NAME_RECT_RIGHT, MMIWIDGET_FM_NAME_RECT_BOTTOM}

//播放按钮
#define MMIWIDGET_FM_PLAYBUTTON_LEFT           242
#define MMIWIDGET_FM_PLAYBUTTON_TOP            11
#define MMIWIDGET_FM_PLAYBUTTON_RIGHT		   (MMIWIDGET_FM_PLAYBUTTON_LEFT + 38- 1)
#define MMIWIDGET_FM_PLAYBUTTON_BOTTOM		   (MMIWIDGET_FM_PLAYBUTTON_TOP + 38 - 1)
#define MMIWIDGET_FM_PLAYBUTTON_RECT           {MMIWIDGET_FM_PLAYBUTTON_LEFT, MMIWIDGET_FM_PLAYBUTTON_TOP, MMIWIDGET_FM_PLAYBUTTON_RIGHT, MMIWIDGET_FM_PLAYBUTTON_BOTTOM}
#endif

//**************************************CALL LOG****************************************//
#define MMIWIDGET_CALLLOG_OEPN_RECT           {14,130,14+67-1,130+41-1}

#define MMIWIDGET_CALLLOG_CANCEL_RECT       {81,130,81+67-1,130+41-1}

//行间距
#define  MMIWIDGET_CALLLOG_LINE_SPACE          4

//上间距
#define  MMIWIDGET_CALLLOG_TOP_SPACE          25
//左间距
#define  MMIWIDGET_CALLLOG_LEFT_SPACE          25
//段间距
#define  MMIWIDGET_CALLLOG_SENTENCE_SPACE          20

//**************************************Auto Answer Log********************************//

#define MMIWIDGET_AUTOANSWER_LOG_OEPN_RECT           {14,130,14+67-1,130+41-1}

#define MMIWIDGET_AUTOANSWER_LOG_CANCEL_RECT       {81,130,81+67-1,130+41-1}

//行间距
#define  MMIWIDGET_AUTOANSWER_LOG_LINE_SPACE          4

//上间距
#define  MMIWIDGET_AUTOANSWER_LOG_TOP_SPACE          25
//左间距
#define  MMIWIDGET_AUTOANSWER_LOG_LEFT_SPACE          25
//段间距
#define  MMIWIDGET_AUTOANSWER_LOG_SENTENCE_SPACE          20

//****************************************page widget***********************************//
#define MMITHEME_WIDGET_TITLE_ICON_RECT        {110, 410, 200,421}
#define MMITHEME_WIDGET_TITLE_ICON_H_SPC      18
//以下是横屏位置
#define MMITHEME_H_WIDGET_TITLE_ICON_RECT       {180, 250, 270, 261}
#define MMITHEME_H_WIDGET_TITLE_ICON_H_SPC 18

//****************************************Shortcut set***********************************//
//WIFI
#define MMIWIDGET_SHORTCUT_SET_WIFI_LEFT                   22
#define MMIWIDGET_SHORTCUT_SET_WIFI_TOP                    9
#define MMIWIDGET_SHORTCUT_SET_WIFI_RIGHT			 MMIWIDGET_SHORTCUT_SET_WIFI_LEFT + 32
#define MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM			 MMIWIDGET_SHORTCUT_SET_WIFI_TOP + 32
#define MMIWIDGET_SHORTCUT_SET_WIFI_RECT            {MMIWIDGET_SHORTCUT_SET_WIFI_LEFT, MMIWIDGET_SHORTCUT_SET_WIFI_TOP, MMIWIDGET_SHORTCUT_SET_WIFI_RIGHT, MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM}
//BT
#define MMIWIDGET_SHORTCUT_SET_BT_LEFT                 MMIWIDGET_SHORTCUT_SET_WIFI_RIGHT + 23
#define MMIWIDGET_SHORTCUT_SET_BT_TOP                  MMIWIDGET_SHORTCUT_SET_WIFI_TOP
#define MMIWIDGET_SHORTCUT_SET_BT_RIGHT			MMIWIDGET_SHORTCUT_SET_BT_LEFT + 32
#define MMIWIDGET_SHORTCUT_SET_BT_BOTTOM		MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM
#define MMIWIDGET_SHORTCUT_SET_BT_RECT            {MMIWIDGET_SHORTCUT_SET_BT_LEFT, MMIWIDGET_SHORTCUT_SET_BT_TOP, MMIWIDGET_SHORTCUT_SET_BT_RIGHT, MMIWIDGET_SHORTCUT_SET_BT_BOTTOM}
//BACKLIGHT
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_LEFT                 MMIWIDGET_SHORTCUT_SET_BT_RIGHT + 23
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_TOP                  MMIWIDGET_SHORTCUT_SET_WIFI_TOP
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RIGHT			MMIWIDGET_SHORTCUT_SET_BACKLIGHT_LEFT + 32
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_BOTTOM		MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RECT            {MMIWIDGET_SHORTCUT_SET_BACKLIGHT_LEFT, MMIWIDGET_SHORTCUT_SET_BACKLIGHT_TOP, MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RIGHT, MMIWIDGET_SHORTCUT_SET_BACKLIGHT_BOTTOM}
//VOLUME
#define MMIWIDGET_SHORTCUT_SET_SILENT_LEFT                 MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RIGHT + 23
#define MMIWIDGET_SHORTCUT_SET_SILENT_TOP                  MMIWIDGET_SHORTCUT_SET_WIFI_TOP
#define MMIWIDGET_SHORTCUT_SET_SILENT_RIGHT			MMIWIDGET_SHORTCUT_SET_SILENT_LEFT + 32
#define MMIWIDGET_SHORTCUT_SET_SILENT_BOTTOM		MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM
#define MMIWIDGET_SHORTCUT_SET_SILENT_RECT            {MMIWIDGET_SHORTCUT_SET_SILENT_LEFT, MMIWIDGET_SHORTCUT_SET_SILENT_TOP, MMIWIDGET_SHORTCUT_SET_SILENT_RIGHT, MMIWIDGET_SHORTCUT_SET_SILENT_BOTTOM}

#ifdef MMI_POWER_SAVING_MODE_SUPPORT
#define MMIWIDGET_PWR_SAV_11_LEFT                 22
#define MMIWIDGET_PWR_SAV_11_TOP                  28
#define MMIWIDGET_PWR_SAV_11_NAME_LEFT            0
#define MMIWIDGET_PWR_SAV_11_NAME_TOP             76
#define MMIWIDGET_PWR_SAV_11_HL_LEFT              0
#define MMIWIDGET_PWR_SAV_11_HL_TOP               97

#define MMIWIDGET_PWR_SAV_12_LEFT                 102
#define MMIWIDGET_PWR_SAV_12_TOP                  28
#define MMIWIDGET_PWR_SAV_12_NAME_LEFT            80
#define MMIWIDGET_PWR_SAV_12_NAME_TOP             76
#define MMIWIDGET_PWR_SAV_12_HL_LEFT              80
#define MMIWIDGET_PWR_SAV_12_HL_TOP               97

#define MMIWIDGET_PWR_SAV_13_LEFT                 182
#define MMIWIDGET_PWR_SAV_13_TOP                  28
#define MMIWIDGET_PWR_SAV_13_NAME_LEFT            160
#define MMIWIDGET_PWR_SAV_13_NAME_TOP             76
#define MMIWIDGET_PWR_SAV_13_HL_LEFT              160
#define MMIWIDGET_PWR_SAV_13_HL_TOP               97

#define MMIWIDGET_PWR_SAV_14_LEFT                 262
#define MMIWIDGET_PWR_SAV_14_TOP                  28
#define MMIWIDGET_PWR_SAV_14_NAME_LEFT            240
#define MMIWIDGET_PWR_SAV_14_NAME_TOP             76
#define MMIWIDGET_PWR_SAV_14_HL_LEFT              240
#define MMIWIDGET_PWR_SAV_14_HL_TOP               97

#define MMIWIDGET_PWR_SAV_21_LEFT                 22
#define MMIWIDGET_PWR_SAV_21_TOP                  133
#define MMIWIDGET_PWR_SAV_21_NAME_LEFT            0
#define MMIWIDGET_PWR_SAV_21_NAME_TOP              181
#define MMIWIDGET_PWR_SAV_21_HL_LEFT              0
#define MMIWIDGET_PWR_SAV_21_HL_TOP               202

#define MMIWIDGET_PWR_SAV_22_LEFT                 102
#define MMIWIDGET_PWR_SAV_22_TOP                  133
#define MMIWIDGET_PWR_SAV_22_NAME_LEFT            80
#define MMIWIDGET_PWR_SAV_22_NAME_TOP             181
#define MMIWIDGET_PWR_SAV_22_HL_LEFT              80
#define MMIWIDGET_PWR_SAV_22_HL_TOP               202

#define MMIWIDGET_PWR_SAV_23_LEFT                 182
#define MMIWIDGET_PWR_SAV_23_TOP                  133
#define MMIWIDGET_PWR_SAV_23_NAME_LEFT            160
#define MMIWIDGET_PWR_SAV_23_NAME_TOP             181
#define MMIWIDGET_PWR_SAV_23_HL_LEFT              160
#define MMIWIDGET_PWR_SAV_23_HL_TOP               202

#define MMIWIDGET_PWR_SAV_24_LEFT                 262
#define MMIWIDGET_PWR_SAV_24_TOP                  133
#define MMIWIDGET_PWR_SAV_24_NAME_LEFT            240
#define MMIWIDGET_PWR_SAV_24_NAME_TOP             181
#define MMIWIDGET_PWR_SAV_24_HL_LEFT              240
#define MMIWIDGET_PWR_SAV_24_HL_TOP               202
#endif
//**************************************ALARM******************************************//
#ifndef MMI_GRID_IDLE_SUPPORT
//alarm
#define MMIWIDGET_ALARM_BUTTON_RECT          {120, 14, 180, 34}
#define MMIWIDGET_ALARM_NAME_RECT            {23,17, 110, 23+30-1}
#define MMIWIDGET_ALARM_LARR_RECT            {7, 32, 17, 47}
#define MMIWIDGET_ALARM_RARR_RECT            {183, 32, 193, 47}
#define MMIWIDGET_ALARM_INDIC_RECT           {38, 80, 162, 99}
#else
//alarm
#define MMIWIDGET_ALARM_BUTTON_RECT          {194, 27, 274, 54}//{191, 25, 270, 49}
#define MMIWIDGET_ALARM_NAME_RECT            {194,63, 274, 81}
#define MMIWIDGET_ALARM_LARR_RECT            {7, 32, 17, 47}
#define MMIWIDGET_ALARM_RARR_RECT            {183, 32, 193, 47}
#define MMIWIDGET_ALARM_INDIC_RECT1           {32, 98, 67, 133}
#define MMIWIDGET_ALARM_INDIC_RECT2           {125, 98, 162, 133}
#define MMIWIDGET_ALARM_INDIC_RECT3           {218, 98, 255, 133}
#define MMIWIDGET_ALARM_INDIC_RECT4           {32, 150, 67, 188}
#define MMIWIDGET_ALARM_INDIC_RECT5           {125, 150, 162, 188}
#define MMIWIDGET_ALARM_INDIC_RECT6           {218, 150, 255, 188}
#define MMIWIDGET_ALARM_INDIC_RECT           {10, 90, 288, 197}
#define MMIWIDGET_ALARM_TIME_RECT             {0, 0, 150, 86}
#endif
//****************************************Search***********************************//

#define MMIWIDGET_SEARCH_TYPE_LEFT                 15

#define MMIWIDGET_SEARCH_EDIT_LEFT                 63

#ifdef MMI_SAM_THEME
#define MMIWIDGET_SAM_SEARCH_EDIT_LEFT             71
#define MMIWIDGET_SAM_SEARCH_EDIT_LEFT             70
#endif
//****************************************DCD***********************************//

#define     MMIWIDGET_DCD_ITEM_PREVIEW_LINE_SPACE          10


#define     MMIWIDGET_DCD_WIN_ANIM_TOP               36
#define     MMIWIDGET_DCD_WIN_ANIM_BOTTOM     	   88
#define     MMIWIDGET_DCD_WIN_ANIM_LEFT              15
#define     MMIWIDGET_DCD_WIN_ANIM_RIGHT            55  

#define     MMIWIDGET_DCD_WIN_TEXT_TOP                36
#define     MMIWIDGET_DCD_WIN_TEXT_BOTTOM          88  
#define     MMIWIDGET_DCD_WIN_TEXT_LEFT       		(MMIWIDGET_DCD_WIN_ANIM_RIGHT+ MMIWIDGET_DCD_ITEM_PREVIEW_LINE_SPACE)      
#define     MMIWIDGET_DCD_WIN_TEXT_RIGHT            225


#define     MMIWIDGET_DCD_WIN_LEFT_IDC_TOP                8
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_BOTTOM           26
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_LEFT               12
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_RIGHT              30
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_RECT              {MMIWIDGET_DCD_WIN_LEFT_IDC_LEFT,MMIWIDGET_DCD_WIN_LEFT_IDC_TOP,MMIWIDGET_DCD_WIN_LEFT_IDC_RIGHT,MMIWIDGET_DCD_WIN_LEFT_IDC_BOTTOM}

#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_TOP                8
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_BOTTOM           26
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_LEFT               208
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_RIGHT              226
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_RECT              {MMIWIDGET_DCD_WIN_RIGHT_IDC_LEFT,MMIWIDGET_DCD_WIN_RIGHT_IDC_TOP,MMIWIDGET_DCD_WIN_RIGHT_IDC_RIGHT,MMIWIDGET_DCD_WIN_RIGHT_IDC_BOTTOM}

#define     MMIWIDGET_DCD_TAB_ANIM_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM_BOTTOM          25 
#define     MMIWIDGET_DCD_TAB_ANIM_LEFT               53
#define     MMIWIDGET_DCD_TAB_ANIM_RIGHT             73
#define     MMIWIDGET_DCD_TAB_ANIM_0_RECT              {MMIWIDGET_DCD_TAB_ANIM_LEFT,MMIWIDGET_DCD_TAB_ANIM_TOP,MMIWIDGET_DCD_TAB_ANIM_RIGHT,MMIWIDGET_DCD_TAB_ANIM_BOTTOM}

#define     MMIWIDGET_DCD_TAB_ANIM1_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM1_BOTTOM          25  
#define     MMIWIDGET_DCD_TAB_ANIM1_LEFT              90
#define     MMIWIDGET_DCD_TAB_ANIM1_RIGHT            110
#define     MMIWIDGET_DCD_TAB_ANIM_1_RECT              {MMIWIDGET_DCD_TAB_ANIM1_LEFT,MMIWIDGET_DCD_TAB_ANIM1_TOP,MMIWIDGET_DCD_TAB_ANIM1_RIGHT,MMIWIDGET_DCD_TAB_ANIM1_BOTTOM}


#define     MMIWIDGET_DCD_TAB_ANIM2_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM2_BOTTOM          25 
#define     MMIWIDGET_DCD_TAB_ANIM2_LEFT               127
#define     MMIWIDGET_DCD_TAB_ANIM2_RIGHT            147
#define     MMIWIDGET_DCD_TAB_ANIM_2_RECT              {MMIWIDGET_DCD_TAB_ANIM2_LEFT,MMIWIDGET_DCD_TAB_ANIM2_TOP,MMIWIDGET_DCD_TAB_ANIM2_RIGHT,MMIWIDGET_DCD_TAB_ANIM2_BOTTOM}

#define     MMIWIDGET_DCD_TAB_ANIM3_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM3_BOTTOM          25 
#define     MMIWIDGET_DCD_TAB_ANIM3_LEFT               164
#define     MMIWIDGET_DCD_TAB_ANIM3_RIGHT             184
#define     MMIWIDGET_DCD_TAB_ANIM_3_RECT              {MMIWIDGET_DCD_TAB_ANIM3_LEFT,MMIWIDGET_DCD_TAB_ANIM3_TOP,MMIWIDGET_DCD_TAB_ANIM3_RIGHT,MMIWIDGET_DCD_TAB_ANIM3_BOTTOM}

#define     MMIWIDGET_DCD_OPENMAINWIN_RECT		{15,36,225,90}


//***********************************************dual clock **********************************//
#define MMIWIDGET_DUAL_CLOCK_TIME1_TOP        21
#define MMIWIDGET_DUAL_CLOCK_TIME1_BOTTOM     (MMIWIDGET_DUAL_CLOCK_TIME1_TOP + 24 -1)
#define MMIWIDGET_DUAL_CLOCK_TIME1_LEFT       23
#define MMIWIDGET_DUAL_CLOCK_TIME1_RIGHT      (MMIWIDGET_DUAL_CLOCK_TIME1_LEFT + 100 -1)
#define MMIWIDGET_DUAL_CLOCK_TIME1_RECT       {MMIWIDGET_DUAL_CLOCK_TIME1_LEFT, MMIWIDGET_DUAL_CLOCK_TIME1_TOP, MMIWIDGET_DUAL_CLOCK_TIME1_RIGHT, MMIWIDGET_DUAL_CLOCK_TIME1_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_CITY1_TOP        25
#define MMIWIDGET_DUAL_CLOCK_CITY1_BOTTOM     (MMIWIDGET_DUAL_CLOCK_CITY1_TOP + 24 -1)
#define MMIWIDGET_DUAL_CLOCK_CITY1_LEFT       120
#define MMIWIDGET_DUAL_CLOCK_CITY1_RIGHT      (MMIWIDGET_DUAL_CLOCK_CITY1_LEFT + 118 -1)
#define MMIWIDGET_DUAL_CLOCK_CITY1_RECT       {MMIWIDGET_DUAL_CLOCK_CITY1_LEFT, MMIWIDGET_DUAL_CLOCK_CITY1_TOP, MMIWIDGET_DUAL_CLOCK_CITY1_RIGHT, MMIWIDGET_DUAL_CLOCK_CITY1_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_TIME2_TOP        75
#define MMIWIDGET_DUAL_CLOCK_TIME2_BOTTOM     (MMIWIDGET_DUAL_CLOCK_TIME2_TOP + 24 -1)
#define MMIWIDGET_DUAL_CLOCK_TIME2_LEFT       23
#define MMIWIDGET_DUAL_CLOCK_TIME2_RIGHT      (MMIWIDGET_DUAL_CLOCK_TIME2_LEFT + 100 -1)
#define MMIWIDGET_DUAL_CLOCK_TIME2_RECT       {MMIWIDGET_DUAL_CLOCK_TIME2_LEFT, MMIWIDGET_DUAL_CLOCK_TIME2_TOP, MMIWIDGET_DUAL_CLOCK_TIME2_RIGHT, MMIWIDGET_DUAL_CLOCK_TIME2_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_CITY2_TOP        75
#define MMIWIDGET_DUAL_CLOCK_CITY2_BOTTOM     (MMIWIDGET_DUAL_CLOCK_CITY2_TOP + 24 -1)
#define MMIWIDGET_DUAL_CLOCK_CITY2_LEFT       120
#define MMIWIDGET_DUAL_CLOCK_CITY2_RIGHT      (MMIWIDGET_DUAL_CLOCK_CITY2_LEFT + 118 -1)
#define MMIWIDGET_DUAL_CLOCK_CITY2_RECT       {MMIWIDGET_DUAL_CLOCK_CITY2_LEFT, MMIWIDGET_DUAL_CLOCK_CITY2_TOP, MMIWIDGET_DUAL_CLOCK_CITY2_RIGHT, MMIWIDGET_DUAL_CLOCK_CITY2_BOTTOM}

#ifdef MMI_SAM_THEME
#define MMIWIDGET_DUAL_SAM_CLOCK_TIME1_TOP        35
#define MMIWIDGET_DUAL_SAM_CLOCK_TIME1_BOTTOM     (MMIWIDGET_DUAL_SAM_CLOCK_TIME1_TOP + 64 -1)
#define MMIWIDGET_DUAL_SAM_CLOCK_TIME1_LEFT       5
#define MMIWIDGET_DUAL_SAM_CLOCK_TIME1_RIGHT      (MMIWIDGET_DUAL_SAM_CLOCK_TIME1_LEFT + 150 -1)
#define MMIWIDGET_DUAL_SAM_CLOCK_TIME1_RECT       {MMIWIDGET_DUAL_SAM_CLOCK_TIME1_LEFT, MMIWIDGET_DUAL_SAM_CLOCK_TIME1_TOP, MMIWIDGET_DUAL_SAM_CLOCK_TIME1_RIGHT, MMIWIDGET_DUAL_SAM_CLOCK_TIME1_BOTTOM}

#define MMIWIDGET_DUAL_SAM_CLOCK_CITY1_TOP        13
#define MMIWIDGET_DUAL_SAM_CLOCK_CITY1_BOTTOM     (MMIWIDGET_DUAL_SAM_CLOCK_CITY1_TOP + 24 -1)
#define MMIWIDGET_DUAL_SAM_CLOCK_CITY1_LEFT       11
#define MMIWIDGET_DUAL_SAM_CLOCK_CITY1_RIGHT      (MMIWIDGET_DUAL_SAM_CLOCK_CITY1_LEFT + 118 -1)
#define MMIWIDGET_DUAL_SAM_CLOCK_CITY1_RECT       {MMIWIDGET_DUAL_SAM_CLOCK_CITY1_LEFT, MMIWIDGET_DUAL_SAM_CLOCK_CITY1_TOP, MMIWIDGET_DUAL_SAM_CLOCK_CITY1_RIGHT, MMIWIDGET_DUAL_SAM_CLOCK_CITY1_BOTTOM}

#define MMIWIDGET_DUAL_SAM_CLOCK_TIME2_TOP        132
#define MMIWIDGET_DUAL_SAM_CLOCK_TIME2_BOTTOM     (MMIWIDGET_DUAL_SAM_CLOCK_TIME2_TOP + 64 -1)
#define MMIWIDGET_DUAL_SAM_CLOCK_TIME2_LEFT       5
#define MMIWIDGET_DUAL_SAM_CLOCK_TIME2_RIGHT      (MMIWIDGET_DUAL_SAM_CLOCK_TIME2_LEFT + 150 -1)
#define MMIWIDGET_DUAL_SAM_CLOCK_TIME2_RECT       {MMIWIDGET_DUAL_SAM_CLOCK_TIME2_LEFT, MMIWIDGET_DUAL_SAM_CLOCK_TIME2_TOP, MMIWIDGET_DUAL_SAM_CLOCK_TIME2_RIGHT, MMIWIDGET_DUAL_SAM_CLOCK_TIME2_BOTTOM}

#define MMIWIDGET_DUAL_SAM_CLOCK_CITY2_TOP        109
#define MMIWIDGET_DUAL_SAM_CLOCK_CITY2_BOTTOM     (MMIWIDGET_DUAL_SAM_CLOCK_CITY2_TOP + 24 -1)
#define MMIWIDGET_DUAL_SAM_CLOCK_CITY2_LEFT       13
#define MMIWIDGET_DUAL_SAM_CLOCK_CITY2_RIGHT      (MMIWIDGET_DUAL_SAM_CLOCK_CITY2_LEFT + 118 -1)
#define MMIWIDGET_DUAL_SAM_CLOCK_CITY2_RECT       {MMIWIDGET_DUAL_SAM_CLOCK_CITY2_LEFT, MMIWIDGET_DUAL_SAM_CLOCK_CITY2_TOP, MMIWIDGET_DUAL_SAM_CLOCK_CITY2_RIGHT, MMIWIDGET_DUAL_SAM_CLOCK_CITY2_BOTTOM}
#endif

//***********************************************dual aclock **********************************//
//left aclock rect.
#define MMIWIDGET_LACLOCK_RECT_LEFT            0
#define MMIWIDGET_LACLOCK_RECT_TOP             0

//right aclock rect.
#define MMIWIDGET_RACLOCK_RECT_LEFT            130
#define MMIWIDGET_RACLOCK_RECT_TOP             0

//left aclock city rect.
#define MMIWIDGET_LACLOCK_CITY_RECT_LEFT       15
#define MMIWIDGET_LACLOCK_CITY_RECT_RIGHT      (MMIWIDGET_LACLOCK_CITY_RECT_LEFT + 81 -1)
#define MMIWIDGET_LACLOCK_CITY_RECT_TOP        111
#define MMIWIDGET_LACLOCK_CITY_RECT_BOTTOM     (MMIWIDGET_LACLOCK_CITY_RECT_TOP + 21 -1)
#define MMIWIDGET_LACLOCK_CITY_RECT            {MMIWIDGET_LACLOCK_CITY_RECT_LEFT, MMIWIDGET_LACLOCK_CITY_RECT_TOP, MMIWIDGET_LACLOCK_CITY_RECT_RIGHT, MMIWIDGET_LACLOCK_CITY_RECT_BOTTOM}

//right aclock city rect.
#define MMIWIDGET_RACLOCK_CITY_RECT_LEFT       145
#define MMIWIDGET_RACLOCK_CITY_RECT_RIGHT      (MMIWIDGET_RACLOCK_CITY_RECT_LEFT + 81 -1)
#define MMIWIDGET_RACLOCK_CITY_RECT_TOP        111
#define MMIWIDGET_RACLOCK_CITY_RECT_BOTTOM     (MMIWIDGET_RACLOCK_CITY_RECT_TOP + 21 -1)
#define MMIWIDGET_RACLOCK_CITY_RECT            {MMIWIDGET_RACLOCK_CITY_RECT_LEFT, MMIWIDGET_RACLOCK_CITY_RECT_TOP, MMIWIDGET_RACLOCK_CITY_RECT_RIGHT, MMIWIDGET_RACLOCK_CITY_RECT_BOTTOM}

#ifdef MMI_SAM_THEME
//left aclock rect.
#define MMIWIDGET_SAM_LACLOCK_RECT_LEFT            20
#define MMIWIDGET_SAM_LACLOCK_RECT_TOP             24

//right aclock rect.
#define MMIWIDGET_SAM_RACLOCK_RECT_LEFT            176
#define MMIWIDGET_SAM_RACLOCK_RECT_TOP             24

//left aclock city rect.
#define MMIWIDGET_SAM_LACLOCK_CITY_RECT_LEFT       0
#define MMIWIDGET_SAM_LACLOCK_CITY_RECT_RIGHT      156
#define MMIWIDGET_SAM_LACLOCK_CITY_RECT_TOP        161
#define MMIWIDGET_SAM_LACLOCK_CITY_RECT_BOTTOM     203
#define MMIWIDGET_SAM_LACLOCK_CITY_RECT            {MMIWIDGET_SAM_LACLOCK_CITY_RECT_LEFT, MMIWIDGET_SAM_LACLOCK_CITY_RECT_TOP, MMIWIDGET_SAM_LACLOCK_CITY_RECT_RIGHT, MMIWIDGET_SAM_LACLOCK_CITY_RECT_BOTTOM}

//right aclock city rect.
#define MMIWIDGET_SAM_RACLOCK_CITY_RECT_LEFT       157
#define MMIWIDGET_SAM_RACLOCK_CITY_RECT_RIGHT      312
#define MMIWIDGET_SAM_RACLOCK_CITY_RECT_TOP        161
#define MMIWIDGET_SAM_RACLOCK_CITY_RECT_BOTTOM     203
#define MMIWIDGET_SAM_RACLOCK_CITY_RECT            {MMIWIDGET_SAM_RACLOCK_CITY_RECT_LEFT, MMIWIDGET_SAM_RACLOCK_CITY_RECT_TOP, MMIWIDGET_SAM_RACLOCK_CITY_RECT_RIGHT, MMIWIDGET_SAM_RACLOCK_CITY_RECT_BOTTOM}
#endif

#define MMIGRID_IDLE_SOFTKEY_HEIGHT            60
#define MMIGRID_IDLE_RECYCLE_HEIGHT            40

#if MMI_GRID_PAGE_NUM > 5
#define MMI_IDLE_GRID_THUMB_WIDTH              80
#define MMI_IDLE_GRID_THUMB_HEIGHT             120
#define MMI_IDLE_GRID_THUMB1_RECT              {53, 30, 132, 149}
#define MMI_IDLE_GRID_THUMB2_RECT              {185, 30, 264, 149}
#define MMI_IDLE_GRID_THUMB3_RECT              {20, 180, 99, 299}
#define MMI_IDLE_GRID_THUMB4_RECT              {120, 180, 199, 299}
#define MMI_IDLE_GRID_THUMB5_RECT              {220, 180, 299, 299}
#define MMI_IDLE_GRID_THUMB6_RECT              {53, 330, 132, 449}
#define MMI_IDLE_GRID_THUMB7_RECT              {185, 330, 264, 449}
#elif MMI_GRID_PAGE_NUM > 3
#define MMI_IDLE_GRID_THUMB_WIDTH              96
#define MMI_IDLE_GRID_THUMB_HEIGHT             144
#define MMI_IDLE_GRID_THUMB1_RECT              {42, 64, 137, 207}
#define MMI_IDLE_GRID_THUMB2_RECT              {179, 64, 274, 207}
#define MMI_IDLE_GRID_THUMB3_RECT              {8, 272, 103, 415}
#define MMI_IDLE_GRID_THUMB4_RECT              {111, 272, 206, 415}
#define MMI_IDLE_GRID_THUMB5_RECT              {214, 272, 309, 415}
#else
#define MMI_IDLE_GRID_THUMB_WIDTH              140
#define MMI_IDLE_GRID_THUMB_HEIGHT             210
#define MMI_IDLE_GRID_THUMB1_RECT              {13, 30, 153, 240}
#define MMI_IDLE_GRID_THUMB2_RECT              {166, 30, 306, 240}
#define MMI_IDLE_GRID_THUMB3_RECT              {90, 255, 230, 465}
#endif

#define MMI_GRID_SK_CALL_RECT                  {5, 430, 105, 479}
#define MMI_GRID_SK_MENU_RECT                  {110, 430, 210, 479}
#define MMI_GRID_SK_PB_RECT                    {215, 430, 315, 479}

#if MMI_GRID_PAGE_NUM > 5
#define MMI_GRID_PAGE_TITLE_RECT               {76, 425, 244, 428}
#elif MMI_GRID_PAGE_NUM > 3
#define MMI_GRID_PAGE_TITLE_RECT               {100, 425, 219, 428}
#else
#define MMI_GRID_PAGE_TITLE_RECT               {124, 425, 195, 428}
#endif

#ifdef MMI_GRID_IDLE_SUPPORT
//pb area.
#define MMI_GRID_PB_ADD_RECT                   {8, 124, 134, 161}
#define MMI_GRID_PB_IMG_RECT                   {8, 8, 134, 105}
#define MMI_GRID_PB_NAME_RECT                  {8, 106, 134, 123}
#define MMI_GRID_PB_CALL_RECT                  {8, 124, 70, 161}
#define MMI_GRID_PB_SMS_RECT                   {72, 124, 134, 161}

//image viewer area.
#ifdef BAR_PHONE_WIDGET 
#define MMI_GRID_IMGVIEWER_IMG_RECT            {29, 19, 219, 303}
#define MMI_GRID_IMGVIEWER_IMG_ADD_RECT        {97, 100, 142, 145}
#define MMI_GRID_IMGVIEWER_IMG_RECT_H            {19, 29, 303, 219}
#define MMI_GRID_IMGVIEWER_IMG_ADD_RECT_H        {97, 100, 142, 145}
#else
#define MMI_GRID_IMGVIEWER_IMG_RECT            {25, 21, 215, 163}
#define MMI_GRID_IMGVIEWER_IMG_ADD_RECT        {97, 70, 142, 115} 
#endif
#endif

#ifdef MMI_GRID_IDLE_SUPPORT
//***********************************************Net Search **********************************//
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT_LEFT       259
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT_TOP        13
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT_RIGHT      297
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT_BOTTOM     61
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT            {MMIWIDGET_NET_SEARCH_BUTTON_RECT_LEFT, MMIWIDGET_NET_SEARCH_BUTTON_RECT_TOP, MMIWIDGET_NET_SEARCH_BUTTON_RECT_RIGHT, MMIWIDGET_NET_SEARCH_BUTTON_RECT_BOTTOM}

#define MMIWIDGET_NET_SEARCH_STRING_RECT_LEFT       24
#define MMIWIDGET_NET_SEARCH_STRING_RECT_TOP        22
#define MMIWIDGET_NET_SEARCH_STRING_RECT_RIGHT      239
#define MMIWIDGET_NET_SEARCH_STRING_RECT_BOTTOM     42
#define MMIWIDGET_NET_SEARCH_STRING_RECT            {MMIWIDGET_NET_SEARCH_STRING_RECT_LEFT, MMIWIDGET_NET_SEARCH_STRING_RECT_TOP, MMIWIDGET_NET_SEARCH_STRING_RECT_RIGHT, MMIWIDGET_NET_SEARCH_STRING_RECT_BOTTOM}
#endif
#ifdef MMI_GRID_IDLE_SUPPORT
//***********************************************counted time **********************************//
#define MMIWIDGET_COUNTEDTIME_BUTTON_LEFT           55
#define MMIWIDGET_COUNTEDTIME_BUTTON_TOP            170
#define MMIWIDGET_COUNTEDTIME_BUTTON_RIGHT          240
#define MMIWIDGET_COUNTEDTIME_BUTTON_BOTTOM         211
#define MMIWIDGET_COUNTEDTIME_BUTTON_RECT           {MMIWIDGET_COUNTEDTIME_BUTTON_LEFT, MMIWIDGET_COUNTEDTIME_BUTTON_TOP, MMIWIDGET_COUNTEDTIME_BUTTON_RIGHT, MMIWIDGET_COUNTEDTIME_BUTTON_BOTTOM}

#define MMIWIDGET_COUNTEDTIME_EDIT_LEFT             13
#define MMIWIDGET_COUNTEDTIME_EDIT_TOP              11
#define MMIWIDGET_COUNTEDTIME_EDIT_RIGHT            285
#define MMIWIDGET_COUNTEDTIME_EDIT_BOTTOM           167
#define MMIWIDGET_COUNTEDTIME_EDIT_RECT             {MMIWIDGET_COUNTEDTIME_EDIT_LEFT, MMIWIDGET_COUNTEDTIME_EDIT_TOP, MMIWIDGET_COUNTEDTIME_EDIT_RIGHT, MMIWIDGET_COUNTEDTIME_EDIT_BOTTOM}
#endif
#ifdef SNS_SUPPORT
#define MMI_SNS_MOVE_X            40
#define MMI_SNS_MOVE_Y            15
#define MMI_SNS_MOVE_Y2           5

#define MMI_SNS_TIME_FONT         SONG_FONT_16

#define MMIWIDGET_SNS_LOGIN_WIDTH    298
#define MMIWIDGET_SNS_LOGIN_HEIGHT   144

#define MMIWIDGET_SNS_BG_HEIGHT      192
#define MMIWIDGET_SNS_BG_WIDTH       298

#define MMIWIDGET_SNS_BG2_HEIGHT     142
#define MMIWIDGET_SNS_BG2_WIDTH      298

#define MMIWIDGET_SNS_VIRTUE_HEIGHT  44
#define MMIWIDGET_SNS_VIRTUE_WIDTH   298


#define MMIWIDGET_SNS_IMG_LEFT       10      
#define MMIWIDGET_SNS_IMG_TOP        10

#define MMIWIDGET_SNS_NAME_LEFT      12
#define MMIWIDGET_SNS_NAME_TOP       12
#define MMIWIDGET_SNS_NAME_WIDTH     200
#define MMIWIDGET_SNS_NAME_HEIGHT    18

#define MMIWIDGET_SNS_FLAG_LEFT      220
#define MMIWIDGET_SNS_FLAG_TOP       12+3
#define MMIWIDGET_SNS_FLAG_WIDTH     80
#define MMIWIDGET_SNS_FLAG_HEIGHT    16

#define MMIWIDGET_SNS_TIME_LEFT      12
#define MMIWIDGET_SNS_TIME_TOP       112+5+5
#define MMIWIDGET_SNS_TIME_WIDTH     200
#define MMIWIDGET_SNS_TIME_HEIGHT    16

#define MMIWIDGET_SNS_TEXT_LEFT      12
#define MMIWIDGET_SNS_TEXT_TOP       43-3
#define MMIWIDGET_SNS_TEXT_WIDTH     274
#define MMIWIDGET_SNS_TEXT_HEIGHT    70+5+3

#define MMIWIDGET_SNS_ADD_LEFT       134
#define MMIWIDGET_SNS_ADD_TOP        147
#define MMIWIDGET_SNS_ADD_WIDTH      31
#define MMIWIDGET_SNS_ADD_HEIGHT     31

#ifdef SNS_PULLING_SUPPORT
#define MMIWIDGET_SNS_SYNC_LEFT       165 //134+31
#define MMIWIDGET_SNS_SYNC_TOP        147 
#define MMIWIDGET_SNS_SYNC_WIDTH      31
#define MMIWIDGET_SNS_SYNC_HEIGHT     31

#define MMIWIDGET_SNS_SETTING_LEFT    196 //134+31+31
#define MMIWIDGET_SNS_SETTING_TOP     147 
#define MMIWIDGET_SNS_SETTING_WIDTH   31
#define MMIWIDGET_SNS_SETTING_HEIGHT  31
#endif //SNS_PULLING_SUPPORT

#define MMIWIDGET_SNS_LOG_LEFT       22
#define MMIWIDGET_SNS_LOG_TOP        86
#define MMIWIDGET_SNS_LOG_WIDTH      253
#define MMIWIDGET_SNS_LOG_HEIGHT     40

#define MMIWIDGET_SNS_LOG_FLAG_LEFT  22
#define MMIWIDGET_SNS_LOG_FLAG_TOP   13

#define MMI_SNS_IMG_NAME_RECT  {MMIWIDGET_SNS_NAME_LEFT, MMIWIDGET_SNS_NAME_TOP, MMIWIDGET_SNS_NAME_LEFT+MMIWIDGET_SNS_NAME_WIDTH , MMIWIDGET_SNS_NAME_TOP+MMIWIDGET_SNS_NAME_HEIGHT}
#define MMI_SNS_IMG_FALG_RECT  {MMIWIDGET_SNS_FLAG_LEFT, MMIWIDGET_SNS_FLAG_TOP, MMIWIDGET_SNS_FLAG_LEFT+MMIWIDGET_SNS_FLAG_WIDTH , MMIWIDGET_SNS_FLAG_TOP+MMIWIDGET_SNS_FLAG_HEIGHT}
#define MMI_SNS_IMG_TEXT_RECT  {MMIWIDGET_SNS_TEXT_LEFT, MMIWIDGET_SNS_TEXT_TOP, MMIWIDGET_SNS_TEXT_LEFT+MMIWIDGET_SNS_TEXT_WIDTH , MMIWIDGET_SNS_TEXT_TOP+MMIWIDGET_SNS_TEXT_HEIGHT}
#define MMI_SNS_IMG_TIME_RECT  {MMIWIDGET_SNS_TIME_LEFT, MMIWIDGET_SNS_TIME_TOP, MMIWIDGET_SNS_TIME_LEFT+MMIWIDGET_SNS_TIME_WIDTH , MMIWIDGET_SNS_TIME_TOP+MMIWIDGET_SNS_TIME_HEIGHT}


#define MMIWIDGET_SNS_IMG_RIGHT      MMIWIDGET_SNS_IMG_LEFT + MMIWIDGET_SNS_BG_WIDTH     
#define MMIWIDGET_SNS_IMG_BUTTOM     MMIWIDGET_SNS_IMG_TOP + MMIWIDGET_SNS_BG_HEIGHT

#define MMI_SNS_IMG_LOG_BG_RECT  {MMIWIDGET_SNS_IMG_LEFT, MMIWIDGET_SNS_IMG_TOP, MMIWIDGET_SNS_IMG_LEFT+ MMIWIDGET_SNS_LOGIN_WIDTH , MMIWIDGET_SNS_IMG_TOP + MMIWIDGET_SNS_LOGIN_HEIGHT}
#define MMI_SNS_IMG_LOG_RECT     {MMIWIDGET_SNS_LOG_LEFT, MMIWIDGET_SNS_LOG_TOP, MMIWIDGET_SNS_LOG_LEFT+ MMIWIDGET_SNS_LOG_WIDTH , MMIWIDGET_SNS_LOG_TOP + MMIWIDGET_SNS_LOG_HEIGHT}

#define MMI_SNS_IMG_BG_RECT      {MMIWIDGET_SNS_IMG_LEFT, MMIWIDGET_SNS_IMG_TOP, MMIWIDGET_SNS_IMG_RIGHT , MMIWIDGET_SNS_IMG_BUTTOM}
#define MMI_SNS_IMG_ADD_RECT     {MMIWIDGET_SNS_ADD_LEFT, MMIWIDGET_SNS_ADD_TOP, MMIWIDGET_SNS_ADD_LEFT + MMIWIDGET_SNS_ADD_WIDTH , MMIWIDGET_SNS_ADD_TOP+MMIWIDGET_SNS_ADD_HEIGHT}

#ifdef SNS_PULLING_SUPPORT
#define MMI_SNS_IMG_SYNC_RECT     {MMIWIDGET_SNS_SYNC_LEFT, MMIWIDGET_SNS_SYNC_TOP, MMIWIDGET_SNS_SYNC_LEFT + MMIWIDGET_SNS_SYNC_WIDTH , MMIWIDGET_SNS_SYNC_TOP+MMIWIDGET_SNS_SYNC_HEIGHT}
#define MMI_SNS_IMG_SETTING_RECT  {MMIWIDGET_SNS_SETTING_LEFT, MMIWIDGET_SNS_SETTING_TOP, MMIWIDGET_SNS_SETTING_LEFT + MMIWIDGET_SNS_SETTING_WIDTH , MMIWIDGET_SNS_SETTING_TOP+MMIWIDGET_SNS_SETTING_HEIGHT}
#endif //SNS_PULLING_SUPPORT

#endif
