//***********************************bar***********************************************//
//shortcut数据
//每个shortcut item间隔
#define MMIWIDGET_SHORTCUT_INTERVAL         10//29
//快捷背景图片与LCD顶上间距
#define MMIWIDGET_SHORTCUT_TOP_GAP          20
//快捷拖动预留的间距
#define MMIWIDGET_SHORTCUT_BG_ITEM_SPACE         10

//***********************************************digital clock **********************************//
#define MMIWIDGET_CLOCK_TIME_TOP            16
#define MMIWIDGET_CLOCK_DATE_BOTTOM         30
#define MMIWIDGET_CLOCK_WEEK_BOTTOM         13

//aclock time rect.
#define MMIWIDGET_ACLOCK_RECT_LEFT            0
#define MMIWIDGET_ACLOCK_RECT_TOP             0
#define MMIWIDGET_ACLOCK_RECT_RIGHT           156
#define MMIWIDGET_ACLOCK_RECT_BOTTOM          156
#define MMIWIDGET_ACLOCK_RECT                 {MMIWIDGET_ACLOCK_RECT_LEFT, MMIWIDGET_ACLOCK_RECT_TOP, MMIWIDGET_ACLOCK_RECT_RIGHT, MMIWIDGET_ACLOCK_RECT_BOTTOM}

//***********************************mp3*****************************************//
#ifndef MMI_GRID_IDLE_SUPPORT
//mp3名字区域
#define MMIWIDGET_MP3_MP3NAME_RECT_LEFT            14
#define MMIWIDGET_MP3_MP3NAME_RECT_TOP              12
#define MMIWIDGET_MP3_MP3NAME_RECT_RIGHT           167
#define MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM         32
#define MMIWIDGET_MP3_MP3NAME_RECT              {MMIWIDGET_MP3_MP3NAME_RECT_LEFT, MMIWIDGET_MP3_MP3NAME_RECT_TOP, MMIWIDGET_MP3_MP3NAME_RECT_RIGHT, MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM}
//后退按钮
#define MMIWIDGET_MP3_LBUTTON_LEFT            17
#define MMIWIDGET_MP3_LBUTTON_TOP             44
#define MMIWIDGET_MP3_LBUTTON_RIGHT           (MMIWIDGET_MP3_LBUTTON_LEFT+25-1)
#define MMIWIDGET_MP3_LBUTTON_BOTTOM         (MMIWIDGET_MP3_LBUTTON_TOP+25-1)
#define MMIWIDGET_MP3_LBUTTON_RECT            {MMIWIDGET_MP3_LBUTTON_LEFT, MMIWIDGET_MP3_LBUTTON_TOP, MMIWIDGET_MP3_LBUTTON_RIGHT, MMIWIDGET_MP3_LBUTTON_BOTTOM}

//播放按钮
#define MMIWIDGET_MP3_ENTRYPLAY_LEFT              57
#define MMIWIDGET_MP3_ENTRYPLAY_TOP                44 
#define MMIWIDGET_MP3_ENTRYPLAY_RIGHT           (MMIWIDGET_MP3_ENTRYPLAY_LEFT + 25 -1)
#define MMIWIDGET_MP3_ENTRYPLAY_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAY_TOP +25-1)
#define    MMIWIDGET_MP3_ENTRYPLAY_RECT    {MMIWIDGET_MP3_ENTRYPLAY_LEFT,MMIWIDGET_MP3_ENTRYPLAY_TOP,MMIWIDGET_MP3_ENTRYPLAY_RIGHT,MMIWIDGET_MP3_ENTRYPLAY_BOTTOM}
//前进按钮
#define MMIWIDGET_MP3_RBUTTON_LEFT              97
#define MMIWIDGET_MP3_RBUTTON_TOP                44
#define MMIWIDGET_MP3_RBUTTON_RIGHT           (MMIWIDGET_MP3_RBUTTON_LEFT +25 -1)
#define MMIWIDGET_MP3_RBUTTON_BOTTOM         (MMIWIDGET_MP3_RBUTTON_TOP+25-1)
#define MMIWIDGET_MP3_RBUTTON_RECT            {MMIWIDGET_MP3_RBUTTON_LEFT, MMIWIDGET_MP3_RBUTTON_TOP, MMIWIDGET_MP3_RBUTTON_RIGHT, MMIWIDGET_MP3_RBUTTON_BOTTOM}



//进入mp3播放器按钮
#define MMIWIDGET_MP3_ENTRYPLAYER_LEFT              137
#define MMIWIDGET_MP3_ENTRYPLAYER_TOP                44 
#define MMIWIDGET_MP3_ENTRYPLAYER_RIGHT           (MMIWIDGET_MP3_ENTRYPLAYER_LEFT + 25 -1)
#define MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAYER_TOP +25-1)
#define    MMIWIDGET_MP3_ENTRYPLAYER_RECT    {MMIWIDGET_MP3_ENTRYPLAYER_LEFT,MMIWIDGET_MP3_ENTRYPLAYER_TOP,MMIWIDGET_MP3_ENTRYPLAYER_RIGHT,MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM}

#define MMIWIDGET_MP3_CHANGEPANEL_LEFT            167
#define MMIWIDGET_MP3_CHANGEPANEL_TOP             16
#define MMIWIDGET_MP3_CHANGEPANEL_RIGHT          (MMIWIDGET_MP3_CHANGEPANEL_LEFT +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_BOTTOM      (MMIWIDGET_MP3_CHANGEPANEL_TOP +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_RECT          {MMIWIDGET_MP3_CHANGEPANEL_LEFT, MMIWIDGET_MP3_CHANGEPANEL_TOP, MMIWIDGET_MP3_CHANGEPANEL_RIGHT, MMIWIDGET_MP3_CHANGEPANEL_BOTTOM}

#define   MMIWIDGET_MP3_PROGRESS_RECT        {17,35,17+140-1,35+1}

#define   MMIWIDGET_MP3_PROGRESS_WIDTH              140

#define MMIWIDGET_MP3_VOL_IMAGE_LEFT            12
#define MMIWIDGET_MP3_VOL_IMAGE_TOP             28
#define MMIWIDGET_MP3_VOL_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_IMAGE_LEFT +15 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_IMAGE_TOP +18 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_RECT          {MMIWIDGET_MP3_VOL_IMAGE_LEFT, MMIWIDGET_MP3_VOL_IMAGE_TOP, MMIWIDGET_MP3_VOL_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_DEC_LEFT            13
#define MMIWIDGET_MP3_VOL_DEC_TOP             48
#define MMIWIDGET_MP3_VOL_DEC_RIGHT          (MMIWIDGET_MP3_VOL_DEC_LEFT +24 -1)
#define MMIWIDGET_MP3_VOL_DEC_BOTTOM      (MMIWIDGET_MP3_VOL_DEC_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_DEC_RECT          {MMIWIDGET_MP3_VOL_DEC_LEFT, MMIWIDGET_MP3_VOL_DEC_TOP, MMIWIDGET_MP3_VOL_DEC_RIGHT, MMIWIDGET_MP3_VOL_DEC_BOTTOM}

#define MMIWIDGET_MP3_VOL_ADD_LEFT            144
#define MMIWIDGET_MP3_VOL_ADD_TOP             48
#define MMIWIDGET_MP3_VOL_ADD_RIGHT          (MMIWIDGET_MP3_VOL_ADD_LEFT +23 -1)
#define MMIWIDGET_MP3_VOL_ADD_BOTTOM      (MMIWIDGET_MP3_VOL_ADD_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_ADD_RECT          {MMIWIDGET_MP3_VOL_ADD_LEFT, MMIWIDGET_MP3_VOL_ADD_TOP, MMIWIDGET_MP3_VOL_ADD_RIGHT, MMIWIDGET_MP3_VOL_ADD_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT            37
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP             48
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT+107-1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_LEFT            44
#define MMIWIDGET_MP3_VOL_PROGRESS_TOP             54
#define MMIWIDGET_MP3_VOL_PROGRESS_RIGHT          137
#define MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_TOP +6 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_TOP, MMIWIDGET_MP3_VOL_PROGRESS_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM}

#else
#ifdef BAR_PHONE_WIDGET
//mp3名字区域
#define MMIWIDGET_MP3_MP3NAME_RECT_LEFT            29
#define MMIWIDGET_MP3_MP3NAME_RECT_TOP              19
#define MMIWIDGET_MP3_MP3NAME_RECT_RIGHT           (MMIWIDGET_MP3_MP3NAME_RECT_LEFT + 121)
#define MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM         (MMIWIDGET_MP3_MP3NAME_RECT_TOP + 16)
#define MMIWIDGET_MP3_MP3NAME_RECT              {MMIWIDGET_MP3_MP3NAME_RECT_LEFT, MMIWIDGET_MP3_MP3NAME_RECT_TOP, MMIWIDGET_MP3_MP3NAME_RECT_RIGHT, MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM}

#define MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT            20
#define MMIWIDGET_MP3_MP3ALBUM_RECT_TOP              37
#define MMIWIDGET_MP3_MP3ALBUM_RECT_RIGHT           (MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT + 135)
#define MMIWIDGET_MP3_MP3ALBUM_RECT_BOTTOM         (MMIWIDGET_MP3_MP3ALBUM_RECT_TOP + 14)
#define MMIWIDGET_MP3_MP3ALBUM_RECT              {MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT, MMIWIDGET_MP3_MP3ALBUM_RECT_TOP, MMIWIDGET_MP3_MP3ALBUM_RECT_RIGHT, MMIWIDGET_MP3_MP3ALBUM_RECT_BOTTOM}

#define MMIWIDGET_MP3_MP3TIME_RECT_LEFT            29
#define MMIWIDGET_MP3_MP3TIME_RECT_TOP              51
#define MMIWIDGET_MP3_MP3TIME_RECT_RIGHT           (MMIWIDGET_MP3_MP3TIME_RECT_LEFT + 121)
#define MMIWIDGET_MP3_MP3TIME_RECT_BOTTOM         (MMIWIDGET_MP3_MP3TIME_RECT_TOP + 11)
#define MMIWIDGET_MP3_MP3TIME_RECT              {MMIWIDGET_MP3_MP3TIME_RECT_LEFT, MMIWIDGET_MP3_MP3TIME_RECT_TOP, MMIWIDGET_MP3_MP3TIME_RECT_RIGHT, MMIWIDGET_MP3_MP3TIME_RECT_BOTTOM}

#define   MMIWIDGET_MP3_PROGRESS_RECT        {29,41,29+121-1,41+4}
#define   MMIWIDGET_MP3_PROGRESS_WIDTH       121
#define   MMIWIDGET_MP3_PROGRESS_HEIGHT      4

#define MMIWIDGET_MP3_BUTTON_WIDTH            12
#define MMIWIDGET_MP3_BUTTON_HEIGHT           10

//后退按钮
#define MMIWIDGET_MP3_LBUTTON_LEFT            185
#define MMIWIDGET_MP3_LBUTTON_TOP             17
#define MMIWIDGET_MP3_LBUTTON_RIGHT           (MMIWIDGET_MP3_LBUTTON_LEFT+MMIWIDGET_MP3_BUTTON_WIDTH-1)
#define MMIWIDGET_MP3_LBUTTON_BOTTOM         (MMIWIDGET_MP3_LBUTTON_TOP+MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define MMIWIDGET_MP3_LBUTTON_RECT            {MMIWIDGET_MP3_LBUTTON_LEFT, MMIWIDGET_MP3_LBUTTON_TOP, MMIWIDGET_MP3_LBUTTON_RIGHT, MMIWIDGET_MP3_LBUTTON_BOTTOM}

//播放按钮
#define MMIWIDGET_MP3_ENTRYPLAY_LEFT              178
#define MMIWIDGET_MP3_ENTRYPLAY_TOP               30
#define MMIWIDGET_MP3_ENTRYPLAY_RIGHT           (MMIWIDGET_MP3_ENTRYPLAY_LEFT + 26 -1)
#define MMIWIDGET_MP3_ENTRYPLAY_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAY_TOP +26-1)
#define    MMIWIDGET_MP3_ENTRYPLAY_RECT    {MMIWIDGET_MP3_ENTRYPLAY_LEFT,MMIWIDGET_MP3_ENTRYPLAY_TOP,MMIWIDGET_MP3_ENTRYPLAY_RIGHT,MMIWIDGET_MP3_ENTRYPLAY_BOTTOM}
//前进按钮
#define MMIWIDGET_MP3_RBUTTON_LEFT              185
#define MMIWIDGET_MP3_RBUTTON_TOP               59
#define MMIWIDGET_MP3_RBUTTON_RIGHT           (MMIWIDGET_MP3_RBUTTON_LEFT +MMIWIDGET_MP3_BUTTON_WIDTH -1)
#define MMIWIDGET_MP3_RBUTTON_BOTTOM         (MMIWIDGET_MP3_RBUTTON_TOP+MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define MMIWIDGET_MP3_RBUTTON_RECT            {MMIWIDGET_MP3_RBUTTON_LEFT, MMIWIDGET_MP3_RBUTTON_TOP, MMIWIDGET_MP3_RBUTTON_RIGHT, MMIWIDGET_MP3_RBUTTON_BOTTOM}

#else
//mp3名字区域
#define MMIWIDGET_MP3_MP3NAME_RECT_LEFT            20
#define MMIWIDGET_MP3_MP3NAME_RECT_TOP              14
#define MMIWIDGET_MP3_MP3NAME_RECT_RIGHT           (MMIWIDGET_MP3_MP3NAME_RECT_LEFT + 170)
#define MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM         (MMIWIDGET_MP3_MP3NAME_RECT_TOP + 16)
#define MMIWIDGET_MP3_MP3NAME_RECT              {MMIWIDGET_MP3_MP3NAME_RECT_LEFT, MMIWIDGET_MP3_MP3NAME_RECT_TOP, MMIWIDGET_MP3_MP3NAME_RECT_RIGHT, MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM}

#define MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT            20
#define MMIWIDGET_MP3_MP3ALBUM_RECT_TOP              37
#define MMIWIDGET_MP3_MP3ALBUM_RECT_RIGHT           (MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT + 170)
#define MMIWIDGET_MP3_MP3ALBUM_RECT_BOTTOM         (MMIWIDGET_MP3_MP3ALBUM_RECT_TOP + 14)
#define MMIWIDGET_MP3_MP3ALBUM_RECT              {MMIWIDGET_MP3_MP3ALBUM_RECT_LEFT, MMIWIDGET_MP3_MP3ALBUM_RECT_TOP, MMIWIDGET_MP3_MP3ALBUM_RECT_RIGHT, MMIWIDGET_MP3_MP3ALBUM_RECT_BOTTOM}

#define MMIWIDGET_MP3_MP3TIME_RECT_LEFT            20
#define MMIWIDGET_MP3_MP3TIME_RECT_TOP              61
#define MMIWIDGET_MP3_MP3TIME_RECT_RIGHT           (MMIWIDGET_MP3_MP3TIME_RECT_LEFT + 170)
#define MMIWIDGET_MP3_MP3TIME_RECT_BOTTOM         (MMIWIDGET_MP3_MP3TIME_RECT_TOP + 12)
#define MMIWIDGET_MP3_MP3TIME_RECT              {MMIWIDGET_MP3_MP3TIME_RECT_LEFT, MMIWIDGET_MP3_MP3TIME_RECT_TOP, MMIWIDGET_MP3_MP3TIME_RECT_RIGHT, MMIWIDGET_MP3_MP3TIME_RECT_BOTTOM}

#define   MMIWIDGET_MP3_PROGRESS_RECT        {20,79,20+170-1,79+8}
#define   MMIWIDGET_MP3_PROGRESS_WIDTH       170
#define   MMIWIDGET_MP3_PROGRESS_HEIGHT      7

#define MMIWIDGET_MP3_BUTTON_WIDTH            20
#define MMIWIDGET_MP3_BUTTON_HEIGHT           20
#define MMIWIDGET_MP3_BUTTON_INTERVAL_Y       12

//后退按钮
#define MMIWIDGET_MP3_LBUTTON_LEFT            205
#define MMIWIDGET_MP3_LBUTTON_TOP             8
#define MMIWIDGET_MP3_LBUTTON_RIGHT           (MMIWIDGET_MP3_LBUTTON_LEFT+MMIWIDGET_MP3_BUTTON_WIDTH-1)
#define MMIWIDGET_MP3_LBUTTON_BOTTOM         (MMIWIDGET_MP3_LBUTTON_TOP+MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define MMIWIDGET_MP3_LBUTTON_RECT            {MMIWIDGET_MP3_LBUTTON_LEFT, MMIWIDGET_MP3_LBUTTON_TOP, MMIWIDGET_MP3_LBUTTON_RIGHT, MMIWIDGET_MP3_LBUTTON_BOTTOM}

//播放按钮
#define MMIWIDGET_MP3_ENTRYPLAY_LEFT              MMIWIDGET_MP3_LBUTTON_LEFT
#define MMIWIDGET_MP3_ENTRYPLAY_TOP               (MMIWIDGET_MP3_LBUTTON_BOTTOM + MMIWIDGET_MP3_BUTTON_INTERVAL_Y)
#define MMIWIDGET_MP3_ENTRYPLAY_RIGHT           (MMIWIDGET_MP3_ENTRYPLAY_LEFT + MMIWIDGET_MP3_BUTTON_WIDTH -1)
#define MMIWIDGET_MP3_ENTRYPLAY_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAY_TOP +MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define    MMIWIDGET_MP3_ENTRYPLAY_RECT    {MMIWIDGET_MP3_ENTRYPLAY_LEFT,MMIWIDGET_MP3_ENTRYPLAY_TOP,MMIWIDGET_MP3_ENTRYPLAY_RIGHT,MMIWIDGET_MP3_ENTRYPLAY_BOTTOM}
//前进按钮
#define MMIWIDGET_MP3_RBUTTON_LEFT              MMIWIDGET_MP3_LBUTTON_LEFT
#define MMIWIDGET_MP3_RBUTTON_TOP               (MMIWIDGET_MP3_ENTRYPLAY_BOTTOM + MMIWIDGET_MP3_BUTTON_INTERVAL_Y)
#define MMIWIDGET_MP3_RBUTTON_RIGHT           (MMIWIDGET_MP3_RBUTTON_LEFT +MMIWIDGET_MP3_BUTTON_WIDTH -1)
#define MMIWIDGET_MP3_RBUTTON_BOTTOM         (MMIWIDGET_MP3_RBUTTON_TOP+MMIWIDGET_MP3_BUTTON_HEIGHT-1)
#define MMIWIDGET_MP3_RBUTTON_RECT            {MMIWIDGET_MP3_RBUTTON_LEFT, MMIWIDGET_MP3_RBUTTON_TOP, MMIWIDGET_MP3_RBUTTON_RIGHT, MMIWIDGET_MP3_RBUTTON_BOTTOM}
#endif

//进入mp3播放器按钮
#define MMIWIDGET_MP3_ENTRYPLAYER_LEFT              13
#define MMIWIDGET_MP3_ENTRYPLAYER_TOP                10 
#define MMIWIDGET_MP3_ENTRYPLAYER_RIGHT           204
#define MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM          126
#define    MMIWIDGET_MP3_ENTRYPLAYER_RECT    {MMIWIDGET_MP3_ENTRYPLAYER_LEFT,MMIWIDGET_MP3_ENTRYPLAYER_TOP,MMIWIDGET_MP3_ENTRYPLAYER_RIGHT,MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM}


#define MMIWIDGET_MP3_CHANGEPANEL_LEFT            167
#define MMIWIDGET_MP3_CHANGEPANEL_TOP             16
#define MMIWIDGET_MP3_CHANGEPANEL_RIGHT          (MMIWIDGET_MP3_CHANGEPANEL_LEFT +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_BOTTOM      (MMIWIDGET_MP3_CHANGEPANEL_TOP +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_RECT          {MMIWIDGET_MP3_CHANGEPANEL_LEFT, MMIWIDGET_MP3_CHANGEPANEL_TOP, MMIWIDGET_MP3_CHANGEPANEL_RIGHT, MMIWIDGET_MP3_CHANGEPANEL_BOTTOM}

#define MMIWIDGET_MP3_VOL_IMAGE_LEFT            12
#define MMIWIDGET_MP3_VOL_IMAGE_TOP             28
#define MMIWIDGET_MP3_VOL_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_IMAGE_LEFT +15 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_IMAGE_TOP +18 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_RECT          {MMIWIDGET_MP3_VOL_IMAGE_LEFT, MMIWIDGET_MP3_VOL_IMAGE_TOP, MMIWIDGET_MP3_VOL_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_DEC_LEFT            13
#define MMIWIDGET_MP3_VOL_DEC_TOP             48
#define MMIWIDGET_MP3_VOL_DEC_RIGHT          (MMIWIDGET_MP3_VOL_DEC_LEFT +24 -1)
#define MMIWIDGET_MP3_VOL_DEC_BOTTOM      (MMIWIDGET_MP3_VOL_DEC_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_DEC_RECT          {MMIWIDGET_MP3_VOL_DEC_LEFT, MMIWIDGET_MP3_VOL_DEC_TOP, MMIWIDGET_MP3_VOL_DEC_RIGHT, MMIWIDGET_MP3_VOL_DEC_BOTTOM}

#define MMIWIDGET_MP3_VOL_ADD_LEFT            144
#define MMIWIDGET_MP3_VOL_ADD_TOP             48
#define MMIWIDGET_MP3_VOL_ADD_RIGHT          (MMIWIDGET_MP3_VOL_ADD_LEFT +23 -1)
#define MMIWIDGET_MP3_VOL_ADD_BOTTOM      (MMIWIDGET_MP3_VOL_ADD_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_ADD_RECT          {MMIWIDGET_MP3_VOL_ADD_LEFT, MMIWIDGET_MP3_VOL_ADD_TOP, MMIWIDGET_MP3_VOL_ADD_RIGHT, MMIWIDGET_MP3_VOL_ADD_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT            37
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP             48
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT+107-1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_LEFT            44
#define MMIWIDGET_MP3_VOL_PROGRESS_TOP             54
#define MMIWIDGET_MP3_VOL_PROGRESS_RIGHT          137
#define MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_TOP +6 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_TOP, MMIWIDGET_MP3_VOL_PROGRESS_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM}

#define MMIWIDGET_MP3_COVER_RECT_LEFT            14
#define MMIWIDGET_MP3_COVER_RECT_TOP              9
#define MMIWIDGET_MP3_COVER_RECT_RIGHT           202 //205
#define MMIWIDGET_MP3_COVER_RECT_BOTTOM         197 //126
#define MMIWIDGET_MP3_COVER_RECT              {MMIWIDGET_MP3_COVER_RECT_LEFT, MMIWIDGET_MP3_COVER_RECT_TOP, MMIWIDGET_MP3_COVER_RECT_RIGHT, MMIWIDGET_MP3_COVER_RECT_BOTTOM}

#define MMIWIDGET_MP3_PANEL_RECT_LEFT            0
#define MMIWIDGET_MP3_PANEL_RECT_TOP              127
#define MMIWIDGET_MP3_PANEL_RECT_RIGHT           215
#define MMIWIDGET_MP3_PANEL_RECT_BOTTOM         191
#define MMIWIDGET_MP3_PANEL_RECT              {MMIWIDGET_MP3_PANEL_RECT_LEFT, MMIWIDGET_MP3_PANEL_RECT_TOP, MMIWIDGET_MP3_PANEL_RECT_RIGHT, MMIWIDGET_MP3_PANEL_RECT_BOTTOM}

#endif


//*****************************************PB*********************************************************//
//中央大图宽高
#define MMIWIDGET_PB_WIDGET_BIG_WIDTH         92
#define MMIWIDGET_PB_WIDGET_BIG_HEIGHT        92
//边上小图宽高
#define MMIWIDGET_PB_WIDGET_SMALL_WIDTH       45
#define MMIWIDGET_PB_WIDGET_SMALL_HEIGHT      45
//各pb widget区域
#define MMIWIDGET_PB_WIDGET_1_2_LEFT          8//17
#define MMIWIDGET_PB_WIDGET_3_4_LEFT          164//178
#define MMIWIDGET_PB_WIDGET_1_3_TOP           8//106
#define MMIWIDGET_PB_WIDGET_2_4_TOP           58//154

#define MMIWIDGET_PB_WIDGET_0_LEFT            62//71
#define MMIWIDGET_PB_WIDGET_0_TOP             12//101
#define MMIWIDGET_PB_WIDGET_0_RIGHT       (MMIWIDGET_PB_WIDGET_0_LEFT+MMIWIDGET_PB_WIDGET_BIG_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_0_BOTTOM      (MMIWIDGET_PB_WIDGET_0_TOP+MMIWIDGET_PB_WIDGET_BIG_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_0_RECT      {MMIWIDGET_PB_WIDGET_0_LEFT, MMIWIDGET_PB_WIDGET_0_TOP, MMIWIDGET_PB_WIDGET_0_RIGHT, MMIWIDGET_PB_WIDGET_0_BOTTOM}

#define MMIWIDGET_PB_WIDGET_1_LEFT        MMIWIDGET_PB_WIDGET_1_2_LEFT
#define MMIWIDGET_PB_WIDGET_1_TOP         MMIWIDGET_PB_WIDGET_1_3_TOP
#define MMIWIDGET_PB_WIDGET_1_RIGHT       (MMIWIDGET_PB_WIDGET_1_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_1_BOTTOM      (MMIWIDGET_PB_WIDGET_1_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_1_RECT      {MMIWIDGET_PB_WIDGET_1_LEFT, MMIWIDGET_PB_WIDGET_1_TOP, MMIWIDGET_PB_WIDGET_1_RIGHT, MMIWIDGET_PB_WIDGET_1_BOTTOM}

#define MMIWIDGET_PB_WIDGET_2_LEFT        MMIWIDGET_PB_WIDGET_1_2_LEFT
#define MMIWIDGET_PB_WIDGET_2_TOP         MMIWIDGET_PB_WIDGET_2_4_TOP
#define MMIWIDGET_PB_WIDGET_2_RIGHT       (MMIWIDGET_PB_WIDGET_2_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_2_BOTTOM      (MMIWIDGET_PB_WIDGET_2_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_2_RECT      {MMIWIDGET_PB_WIDGET_2_LEFT, MMIWIDGET_PB_WIDGET_2_TOP, MMIWIDGET_PB_WIDGET_2_RIGHT, MMIWIDGET_PB_WIDGET_2_BOTTOM}

#define MMIWIDGET_PB_WIDGET_3_LEFT        MMIWIDGET_PB_WIDGET_3_4_LEFT
#define MMIWIDGET_PB_WIDGET_3_TOP         MMIWIDGET_PB_WIDGET_1_3_TOP
#define MMIWIDGET_PB_WIDGET_3_RIGHT       (MMIWIDGET_PB_WIDGET_3_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_3_BOTTOM      (MMIWIDGET_PB_WIDGET_3_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_3_RECT      {MMIWIDGET_PB_WIDGET_3_LEFT, MMIWIDGET_PB_WIDGET_3_TOP, MMIWIDGET_PB_WIDGET_3_RIGHT, MMIWIDGET_PB_WIDGET_3_BOTTOM}

#define MMIWIDGET_PB_WIDGET_4_LEFT        MMIWIDGET_PB_WIDGET_3_4_LEFT
#define MMIWIDGET_PB_WIDGET_4_TOP         MMIWIDGET_PB_WIDGET_2_4_TOP
#define MMIWIDGET_PB_WIDGET_4_RIGHT       (MMIWIDGET_PB_WIDGET_4_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_4_BOTTOM      (MMIWIDGET_PB_WIDGET_4_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_4_RECT      {MMIWIDGET_PB_WIDGET_4_LEFT, MMIWIDGET_PB_WIDGET_4_TOP, MMIWIDGET_PB_WIDGET_4_RIGHT, MMIWIDGET_PB_WIDGET_4_BOTTOM}

#define MMIWIDGET_PB_WIDGET_CALL_LEFT  		59
#define MMIWIDGET_PB_WIDGET_CALL_TOP		114
#define MMIWIDGET_PB_WIDGET_CALL_RIGHT		103
#define MMIWIDGET_PB_WIDGET_CALL_BOTTOM	142
#define MMIWIDGET_PB_WIDGET_CALL_RECT      {MMIWIDGET_PB_WIDGET_CALL_LEFT, MMIWIDGET_PB_WIDGET_CALL_TOP, MMIWIDGET_PB_WIDGET_CALL_RIGHT, MMIWIDGET_PB_WIDGET_CALL_BOTTOM}

#define MMIWIDGET_PB_WIDGET_SMS_LEFT  		113
#define MMIWIDGET_PB_WIDGET_SMS_TOP			114
#define MMIWIDGET_PB_WIDGET_SMS_RIGHT		147
#define MMIWIDGET_PB_WIDGET_SMS_BOTTOM		142
#define MMIWIDGET_PB_WIDGET_SMS_RECT      {MMIWIDGET_PB_WIDGET_SMS_LEFT, MMIWIDGET_PB_WIDGET_SMS_TOP, MMIWIDGET_PB_WIDGET_SMS_RIGHT, MMIWIDGET_PB_WIDGET_SMS_BOTTOM}

//*****************************************shortcut menu ****************************************8//
#define    MMIWIDGET_SHORTCUT_MENU_ICON_START_X       5

#define    MMIWIDGET_SHORTCUT_MENU_ICON_START_Y       10 

#define    MMIWIDGET_SHORTCUT_MENU_ICON_INTERVAL       5 

#define    MMIWIDGET_SHORTCUT_MENU_EMPTY_RECT     {0,0,0,0}
//默认左键头的区域
#define    MMIWIDGET_SHORTCUT_MENU_PAGE_BUTTON   {170,19,170+24,19+24}
//**************************************************calendar *****************************************************//
#define MMIWIDGET_CALENDAR_LINE_WIDTH      25
#define MMIWIDGET_CALENDAR_LINE_HEIGHT     12
#define MMIWIDGET_CALENDAR_LINE_GAP  10

#define MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT   52
#define MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT+ MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM6_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT + MMIWIDGET_CALENDAR_LINE_WIDTH-1)

#define  MMIWIDGET_CALENDAR_MONTH_LINE0_TOP   72
#define  MMIWIDGET_CALENDAR_MONTH_LINE1_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE0_TOP+ MMIWIDGET_CALENDAR_LINE_HEIGHT +MMIWIDGET_CALENDAR_LINE_GAP -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE2_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE1_TOP + MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE3_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE2_TOP+ MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE4_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE3_TOP + MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE5_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE4_TOP + MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP -1)

#define MMIWIDGET_CALENDAR_WEEK_TOP    55

#define MMIWIDGET_CALENDAR_MONTH_LEFT   22 
#define MMIWIDGET_CALENDAR_MONTH_TOP    29
#define MMIWIDGET_CALENDAR_MONTH_RIGHT  (MMIWIDGET_CALENDAR_MONTH_LEFT + 145 -1)
#define MMIWIDGET_CALENDAR_MONTH_BOTTOM (MMIWIDGET_CALENDAR_MONTH_TOP + 18 -1)
#define MMIWIDGET_CALENDAR_MONTH_RECT {MMIWIDGET_CALENDAR_MONTH_LEFT,MMIWIDGET_CALENDAR_MONTH_TOP,MMIWIDGET_CALENDAR_MONTH_RIGHT,MMIWIDGET_CALENDAR_MONTH_BOTTOM}

#define MMIWIDGET_CALENDAR_YEAR_LEFT   177 
#define MMIWIDGET_CALENDAR_YEAR_TOP    29
#define MMIWIDGET_CALENDAR_YEAR_RIGHT  (MMIWIDGET_CALENDAR_YEAR_LEFT + 40 -1)
#define MMIWIDGET_CALENDAR_YEAR_BOTTOM (MMIWIDGET_CALENDAR_YEAR_TOP + 11 -1)
#define MMIWIDGET_CALENDAR_YEAR_RECT {MMIWIDGET_CALENDAR_YEAR_LEFT,MMIWIDGET_CALENDAR_YEAR_TOP,MMIWIDGET_CALENDAR_YEAR_RIGHT,MMIWIDGET_CALENDAR_YEAR_BOTTOM}

#define MMIWIDGET_CALENDAR_DAY_LEFT   21 
#define MMIWIDGET_CALENDAR_DAY_TOP    55
#define MMIWIDGET_CALENDAR_DAY_RIGHT  (MMIWIDGET_CALENDAR_DAY_LEFT + 24 -1)
#define MMIWIDGET_CALENDAR_DAY_BOTTOM (MMIWIDGET_CALENDAR_DAY_TOP + 24 -1)
#define MMIWIDGET_CALENDAR_DAY_RECT {MMIWIDGET_CALENDAR_DAY_LEFT,MMIWIDGET_CALENDAR_DAY_TOP,MMIWIDGET_CALENDAR_DAY_RIGHT,MMIWIDGET_CALENDAR_DAY_BOTTOM}

#define MMIWIDGET_CALENDAR_LINE_WIDTH_H      25
#define MMIWIDGET_CALENDAR_LINE_GAP_H         7
#define MMIWIDGET_CALENDAR_LINE_HEIGHT_H     12

#define MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT_H   52
#define MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT_H+MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT_H+MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT_H+MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT_H+MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT_H+ MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM6_LEFT_H   (MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT_H + MMIWIDGET_CALENDAR_LINE_WIDTH_H-1)

#define  MMIWIDGET_CALENDAR_MONTH_LINE0_TOP_H   65
#define  MMIWIDGET_CALENDAR_MONTH_LINE1_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE0_TOP_H+ MMIWIDGET_CALENDAR_LINE_HEIGHT_H +MMIWIDGET_CALENDAR_LINE_GAP_H -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE2_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE1_TOP_H + MMIWIDGET_CALENDAR_LINE_HEIGHT_H+MMIWIDGET_CALENDAR_LINE_GAP_H -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE3_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE2_TOP_H+ MMIWIDGET_CALENDAR_LINE_HEIGHT_H+MMIWIDGET_CALENDAR_LINE_GAP_H -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE4_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE3_TOP_H + MMIWIDGET_CALENDAR_LINE_HEIGHT_H+MMIWIDGET_CALENDAR_LINE_GAP_H -1)
#define  MMIWIDGET_CALENDAR_MONTH_LINE5_TOP_H   (MMIWIDGET_CALENDAR_MONTH_LINE4_TOP_H + MMIWIDGET_CALENDAR_LINE_HEIGHT_H+MMIWIDGET_CALENDAR_LINE_GAP_H -1)

#define MMIWIDGET_CALENDAR_WEEK_TOP_H    46

#define MMIWIDGET_CALENDAR_MONTH_LEFT_H   22 
#define MMIWIDGET_CALENDAR_MONTH_TOP_H    25
#define MMIWIDGET_CALENDAR_MONTH_RIGHT_H  (MMIWIDGET_CALENDAR_MONTH_LEFT_H + 145 -1)
#define MMIWIDGET_CALENDAR_MONTH_BOTTOM_H (MMIWIDGET_CALENDAR_MONTH_TOP_H + 18 -1)
#define MMIWIDGET_CALENDAR_MONTH_RECT_H {MMIWIDGET_CALENDAR_MONTH_LEFT_H,MMIWIDGET_CALENDAR_MONTH_TOP_H,MMIWIDGET_CALENDAR_MONTH_RIGHT_H,MMIWIDGET_CALENDAR_MONTH_BOTTOM_H}

#define MMIWIDGET_CALENDAR_YEAR_LEFT_H   177 
#define MMIWIDGET_CALENDAR_YEAR_TOP_H    25
#define MMIWIDGET_CALENDAR_YEAR_RIGHT_H  (MMIWIDGET_CALENDAR_YEAR_LEFT_H + 40 -1)
#define MMIWIDGET_CALENDAR_YEAR_BOTTOM_H (MMIWIDGET_CALENDAR_YEAR_TOP_H + 11 -1)
#define MMIWIDGET_CALENDAR_YEAR_RECT_H {MMIWIDGET_CALENDAR_YEAR_LEFT_H,MMIWIDGET_CALENDAR_YEAR_TOP_H,MMIWIDGET_CALENDAR_YEAR_RIGHT_H,MMIWIDGET_CALENDAR_YEAR_BOTTOM_H}

#define MMIWIDGET_CALENDAR_DAY_LEFT_H   21 
#define MMIWIDGET_CALENDAR_DAY_TOP_H    45
#define MMIWIDGET_CALENDAR_DAY_RIGHT_H  (MMIWIDGET_CALENDAR_DAY_LEFT_H + 24 -1)
#define MMIWIDGET_CALENDAR_DAY_BOTTOM_H (MMIWIDGET_CALENDAR_DAY_TOP_H + 20 -1)
#define MMIWIDGET_CALENDAR_DAY_RECT_H {MMIWIDGET_CALENDAR_DAY_LEFT_H,MMIWIDGET_CALENDAR_DAY_TOP_H,MMIWIDGET_CALENDAR_DAY_RIGHT_H,MMIWIDGET_CALENDAR_DAY_BOTTOM_H}

//*****************************memo   ******************************************************//
#define   MMIWIDGET_MEMO_TOP_GAP                       25

#define   MMIWIDGET_MEMO_BOTTOM_GAP                20

#define   MMIWIDGET_MEMO_LEFT_GAP                     20

#define   MMIWIDGET_MEMO_RIGHT_GAP                   10

#define   MMIWIDGET_MEMO_LINE_SPACE                   2

//***********************************network name  *****************************************//

#define   MMIWIDGET_NETWORK_SIM1_SIM2_INTERVAL    6

#define   MMIWIDGET_NETWORK_TOP_SPACE                    7

#define MMIWIDGET_NETWORK_WIDGET_SIM1_LEFT  		0
#define MMIWIDGET_NETWORK_WIDGET_SIM1_TOP			0
#define MMIWIDGET_NETWORK_WIDGET_SIM1_RIGHT		    107
#define MMIWIDGET_NETWORK_WIDGET_SIM1_BOTTOM		62
#define MMIWIDGET_NETWORK_WIDGET_SIM1_RECT      {MMIWIDGET_NETWORK_WIDGET_SIM1_LEFT, MMIWIDGET_NETWORK_WIDGET_SIM1_TOP, MMIWIDGET_NETWORK_WIDGET_SIM1_RIGHT, MMIWIDGET_NETWORK_WIDGET_SIM1_BOTTOM}

#define MMIWIDGET_NETWORK_WIDGET_SIM2_LEFT  		113
#define MMIWIDGET_NETWORK_WIDGET_SIM2_TOP			0
#define MMIWIDGET_NETWORK_WIDGET_SIM2_RIGHT		    220
#define MMIWIDGET_NETWORK_WIDGET_SIM2_BOTTOM		62
#define MMIWIDGET_NETWORK_WIDGET_SIM2_RECT      {MMIWIDGET_NETWORK_WIDGET_SIM2_LEFT, MMIWIDGET_NETWORK_WIDGET_SIM2_TOP, MMIWIDGET_NETWORK_WIDGET_SIM2_RIGHT, MMIWIDGET_NETWORK_WIDGET_SIM2_BOTTOM}

#define MMIWIDGET_NETWORK_WIDGET_SIM3_LEFT  		0
#define MMIWIDGET_NETWORK_WIDGET_SIM3_TOP			68
#define MMIWIDGET_NETWORK_WIDGET_SIM3_RIGHT		    107
#define MMIWIDGET_NETWORK_WIDGET_SIM3_BOTTOM		130
#define MMIWIDGET_NETWORK_WIDGET_SIM3_RECT      {MMIWIDGET_NETWORK_WIDGET_SIM3_LEFT, MMIWIDGET_NETWORK_WIDGET_SIM3_TOP, MMIWIDGET_NETWORK_WIDGET_SIM3_RIGHT, MMIWIDGET_NETWORK_WIDGET_SIM3_BOTTOM}

#define MMIWIDGET_NETWORK_WIDGET_SIM4_LEFT  		113
#define MMIWIDGET_NETWORK_WIDGET_SIM4_TOP			68
#define MMIWIDGET_NETWORK_WIDGET_SIM4_RIGHT		    220
#define MMIWIDGET_NETWORK_WIDGET_SIM4_BOTTOM		130
#define MMIWIDGET_NETWORK_WIDGET_SIM4_RECT      {MMIWIDGET_NETWORK_WIDGET_SIM4_LEFT, MMIWIDGET_NETWORK_WIDGET_SIM4_TOP, MMIWIDGET_NETWORK_WIDGET_SIM4_RIGHT, MMIWIDGET_NETWORK_WIDGET_SIM4_BOTTOM}
//custom word

//   *********************new sms      **********************************//
#define    MMIWIDGET_NEWSMS_OEPN_RECT             {14,130,14+67-1,130+41-1}

#define    MMIWIDGET_NEWSMS_CANCEL_RECT         {81,130,81+67-1,130+41-1}

//行间距
#define  MMIWIDGET_NEWSMS_LINE_SPACE          4

//上间距
#define  MMIWIDGET_NEWSMS_TOP_SPACE          25
//左间距
#define  MMIWIDGET_NEWSMS_LEFT_SPACE          25
//段间距
#define  MMIWIDGET_NEWSMS_SENTENCE_SPACE          20
//右间距
#define    MMIWIDGET_NEWSMS_RIGHT_GAP                   3
//****************************FM   *************************************//
#ifdef BAR_PHONE_WIDGET 
//后退按钮
#define MMIWIDGET_FM_LBUTTON_LEFT           186
#define MMIWIDGET_FM_LBUTTON_TOP            17
#define MMIWIDGET_FM_LBUTTON_RIGHT			(MMIWIDGET_FM_LBUTTON_LEFT + 12 - 1)
#define MMIWIDGET_FM_LBUTTON_BOTTOM			(MMIWIDGET_FM_LBUTTON_TOP + 10 - 1)
#define MMIWIDGET_FM_LBUTTON_RECT           {MMIWIDGET_FM_LBUTTON_LEFT, MMIWIDGET_FM_LBUTTON_TOP, MMIWIDGET_FM_LBUTTON_RIGHT, MMIWIDGET_FM_LBUTTON_BOTTOM}

//前进按钮
#define MMIWIDGET_FM_RBUTTON_LEFT           186
#define MMIWIDGET_FM_RBUTTON_TOP            59
#define MMIWIDGET_FM_RBUTTON_RIGHT          (MMIWIDGET_FM_RBUTTON_LEFT + 12 - 1)
#define MMIWIDGET_FM_RBUTTON_BOTTOM			(MMIWIDGET_FM_RBUTTON_TOP + 10 - 1)
#define MMIWIDGET_FM_RBUTTON_RECT           {MMIWIDGET_FM_RBUTTON_LEFT, MMIWIDGET_FM_RBUTTON_TOP, MMIWIDGET_FM_RBUTTON_RIGHT, MMIWIDGET_FM_RBUTTON_BOTTOM}

//fm名字区域
#define MMIWIDGET_FM_NAME_RECT_LEFT           36
#define MMIWIDGET_FM_NAME_RECT_TOP            34
#define MMIWIDGET_FM_NAME_RECT_RIGHT          (MMIWIDGET_FM_NAME_RECT_LEFT + 108 - 1)
#define MMIWIDGET_FM_NAME_RECT_BOTTOM         (MMIWIDGET_FM_NAME_RECT_TOP + 16 - 1)
#define MMIWIDGET_FM_NAME_RECT                {MMIWIDGET_FM_NAME_RECT_LEFT, MMIWIDGET_FM_NAME_RECT_TOP, MMIWIDGET_FM_NAME_RECT_RIGHT, MMIWIDGET_FM_NAME_RECT_BOTTOM}

//播放按钮
#define MMIWIDGET_FM_PLAYBUTTON_LEFT           177
#define MMIWIDGET_FM_PLAYBUTTON_TOP            30
#define MMIWIDGET_FM_PLAYBUTTON_RIGHT		   (MMIWIDGET_FM_PLAYBUTTON_LEFT + 29 - 1)
#define MMIWIDGET_FM_PLAYBUTTON_BOTTOM		   (MMIWIDGET_FM_PLAYBUTTON_TOP + 29 - 1)
#define MMIWIDGET_FM_PLAYBUTTON_RECT           {MMIWIDGET_FM_PLAYBUTTON_LEFT, MMIWIDGET_FM_PLAYBUTTON_TOP, MMIWIDGET_FM_PLAYBUTTON_RIGHT, MMIWIDGET_FM_PLAYBUTTON_BOTTOM}
#else
//后退按钮
#define MMIWIDGET_FM_LBUTTON_LEFT           15//20
#define MMIWIDGET_FM_LBUTTON_TOP            10//15
#define MMIWIDGET_FM_LBUTTON_RIGHT			(MMIWIDGET_FM_LBUTTON_LEFT + 25-1)//15 - 1)
#define MMIWIDGET_FM_LBUTTON_BOTTOM			(MMIWIDGET_FM_LBUTTON_TOP + 25-1)//15 - 1)
#define MMIWIDGET_FM_LBUTTON_RECT           {MMIWIDGET_FM_LBUTTON_LEFT, MMIWIDGET_FM_LBUTTON_TOP, MMIWIDGET_FM_LBUTTON_RIGHT, MMIWIDGET_FM_LBUTTON_BOTTOM}

//前进按钮
#define MMIWIDGET_FM_RBUTTON_LEFT           161//166
#define MMIWIDGET_FM_RBUTTON_TOP            10//15
#define MMIWIDGET_FM_RBUTTON_RIGHT          (MMIWIDGET_FM_RBUTTON_LEFT + 25-1)//15 - 1)
#define MMIWIDGET_FM_RBUTTON_BOTTOM			(MMIWIDGET_FM_RBUTTON_TOP + 25-1)//15 - 1)
#define MMIWIDGET_FM_RBUTTON_RECT           {MMIWIDGET_FM_RBUTTON_LEFT, MMIWIDGET_FM_RBUTTON_TOP, MMIWIDGET_FM_RBUTTON_RIGHT, MMIWIDGET_FM_RBUTTON_BOTTOM}

//fm名字区域
#define MMIWIDGET_FM_NAME_RECT_LEFT           39
#define MMIWIDGET_FM_NAME_RECT_TOP            15
#define MMIWIDGET_FM_NAME_RECT_RIGHT          (MMIWIDGET_FM_NAME_RECT_LEFT + 123 - 1)
#define MMIWIDGET_FM_NAME_RECT_BOTTOM         (MMIWIDGET_FM_NAME_RECT_TOP + 15 - 1)
#define MMIWIDGET_FM_NAME_RECT                {MMIWIDGET_FM_NAME_RECT_LEFT, MMIWIDGET_FM_NAME_RECT_TOP, MMIWIDGET_FM_NAME_RECT_RIGHT, MMIWIDGET_FM_NAME_RECT_BOTTOM}

//播放按钮
#define MMIWIDGET_FM_PLAYBUTTON_LEFT           195
#define MMIWIDGET_FM_PLAYBUTTON_TOP            8
#define MMIWIDGET_FM_PLAYBUTTON_RIGHT		   (MMIWIDGET_FM_PLAYBUTTON_LEFT + 29 - 1)
#define MMIWIDGET_FM_PLAYBUTTON_BOTTOM		   (MMIWIDGET_FM_PLAYBUTTON_TOP + 29 - 1)
#define MMIWIDGET_FM_PLAYBUTTON_RECT           {MMIWIDGET_FM_PLAYBUTTON_LEFT, MMIWIDGET_FM_PLAYBUTTON_TOP, MMIWIDGET_FM_PLAYBUTTON_RIGHT, MMIWIDGET_FM_PLAYBUTTON_BOTTOM}
#endif

//**************************************CALL LOG****************************************//
#define MMIWIDGET_CALLLOG_OEPN_RECT           {14,130,14+67-1,130+41-1}

#define MMIWIDGET_CALLLOG_CANCEL_RECT       {81,130,81+67-1,130+41-1}

//行间距
#define  MMIWIDGET_CALLLOG_LINE_SPACE          4

//上间距
#define  MMIWIDGET_CALLLOG_TOP_SPACE          25
//左间距
#define  MMIWIDGET_CALLLOG_LEFT_SPACE          25
//段间距
#define  MMIWIDGET_CALLLOG_SENTENCE_SPACE          20

//**************************************Auto Answer Log********************************//

#define MMIWIDGET_AUTOANSWER_LOG_OEPN_RECT           {14,130,14+67-1,130+41-1}

#define MMIWIDGET_AUTOANSWER_LOG_CANCEL_RECT       {81,130,81+67-1,130+41-1}

//行间距
#define  MMIWIDGET_AUTOANSWER_LOG_LINE_SPACE          4

//上间距
#define  MMIWIDGET_AUTOANSWER_LOG_TOP_SPACE          25
//左间距
#define  MMIWIDGET_AUTOANSWER_LOG_LEFT_SPACE          25
//段间距
#define  MMIWIDGET_AUTOANSWER_LOG_SENTENCE_SPACE          20

//****************************************page widget***********************************//
#define MMITHEME_WIDGET_TITLE_ICON_RECT      {83, 348, 158, 359}
#define MMITHEME_WIDGET_TITLE_ICON_H_SPC      18
//以下是横屏位置
#define MMITHEME_H_WIDGET_TITLE_ICON_RECT    {163, 188, 237, 199}
#define MMITHEME_H_WIDGET_TITLE_ICON_H_SPC 18

//****************************************Shortcut set***********************************//
//WIFI
#define MMIWIDGET_SHORTCUT_SET_WIFI_LEFT                   22
#define MMIWIDGET_SHORTCUT_SET_WIFI_TOP                    9
#define MMIWIDGET_SHORTCUT_SET_WIFI_RIGHT			 MMIWIDGET_SHORTCUT_SET_WIFI_LEFT + 32
#define MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM			 MMIWIDGET_SHORTCUT_SET_WIFI_TOP + 32
#define MMIWIDGET_SHORTCUT_SET_WIFI_RECT            {MMIWIDGET_SHORTCUT_SET_WIFI_LEFT, MMIWIDGET_SHORTCUT_SET_WIFI_TOP, MMIWIDGET_SHORTCUT_SET_WIFI_RIGHT, MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM}
//BT
#define MMIWIDGET_SHORTCUT_SET_BT_LEFT                 MMIWIDGET_SHORTCUT_SET_WIFI_RIGHT + 23
#define MMIWIDGET_SHORTCUT_SET_BT_TOP                  MMIWIDGET_SHORTCUT_SET_WIFI_TOP
#define MMIWIDGET_SHORTCUT_SET_BT_RIGHT			MMIWIDGET_SHORTCUT_SET_BT_LEFT + 32
#define MMIWIDGET_SHORTCUT_SET_BT_BOTTOM		MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM
#define MMIWIDGET_SHORTCUT_SET_BT_RECT            {MMIWIDGET_SHORTCUT_SET_BT_LEFT, MMIWIDGET_SHORTCUT_SET_BT_TOP, MMIWIDGET_SHORTCUT_SET_BT_RIGHT, MMIWIDGET_SHORTCUT_SET_BT_BOTTOM}
//BACKLIGHT
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_LEFT                 MMIWIDGET_SHORTCUT_SET_BT_RIGHT + 23
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_TOP                  MMIWIDGET_SHORTCUT_SET_WIFI_TOP
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RIGHT			MMIWIDGET_SHORTCUT_SET_BACKLIGHT_LEFT + 32
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_BOTTOM		MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RECT            {MMIWIDGET_SHORTCUT_SET_BACKLIGHT_LEFT, MMIWIDGET_SHORTCUT_SET_BACKLIGHT_TOP, MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RIGHT, MMIWIDGET_SHORTCUT_SET_BACKLIGHT_BOTTOM}
//VOLUME
#define MMIWIDGET_SHORTCUT_SET_SILENT_LEFT                 MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RIGHT + 23
#define MMIWIDGET_SHORTCUT_SET_SILENT_TOP                  MMIWIDGET_SHORTCUT_SET_WIFI_TOP
#define MMIWIDGET_SHORTCUT_SET_SILENT_RIGHT			MMIWIDGET_SHORTCUT_SET_SILENT_LEFT + 32
#define MMIWIDGET_SHORTCUT_SET_SILENT_BOTTOM		MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM
#define MMIWIDGET_SHORTCUT_SET_SILENT_RECT            {MMIWIDGET_SHORTCUT_SET_SILENT_LEFT, MMIWIDGET_SHORTCUT_SET_SILENT_TOP, MMIWIDGET_SHORTCUT_SET_SILENT_RIGHT, MMIWIDGET_SHORTCUT_SET_SILENT_BOTTOM}

//**************************************ALARM******************************************//
#ifndef MMI_GRID_IDLE_SUPPORT
//alarm
#define MMIWIDGET_ALARM_BUTTON_RECT          {120, 14, 180, 34}
#define MMIWIDGET_ALARM_NAME_RECT            {23,17, 110, 23+30-1}
#define MMIWIDGET_ALARM_LARR_RECT            {7, 32, 17, 47}
#define MMIWIDGET_ALARM_RARR_RECT            {183, 32, 193, 47}
#define MMIWIDGET_ALARM_INDIC_RECT           {38, 80, 162, 99}
#else
//alarm
#define MMIWIDGET_ALARM_BUTTON_RECT          {143,16, 213,40}//{191, 25, 270, 49}
#define MMIWIDGET_ALARM_NAME_RECT            {194,63, 274, 81}
#define MMIWIDGET_ALARM_LARR_RECT            {7, 32, 17, 47}
#define MMIWIDGET_ALARM_RARR_RECT            {183, 32, 193, 47}
#define MMIWIDGET_ALARM_INDIC_RECT1           {27,76, 51,101}
#define MMIWIDGET_ALARM_INDIC_RECT2           {99,76, 123,101}
#define MMIWIDGET_ALARM_INDIC_RECT3           {171,76,195,101}
#define MMIWIDGET_ALARM_INDIC_RECT4           {27,117,51,144}
#define MMIWIDGET_ALARM_INDIC_RECT5           {99, 117, 123, 144}
#define MMIWIDGET_ALARM_INDIC_RECT6           {171,117,195,144}
#define MMIWIDGET_ALARM_INDIC_RECT           {6, 66, 225, 155}
#define MMIWIDGET_ALARM_TIME_RECT             {0, 0, 120, 64}
#endif
//****************************************Search***********************************//

#define MMIWIDGET_SEARCH_TYPE_LEFT                   10

#define MMIWIDGET_SEARCH_EDIT_LEFT                 50
//****************************************DCD***********************************//

#define     MMIWIDGET_DCD_ITEM_PREVIEW_LINE_SPACE          10


#define     MMIWIDGET_DCD_WIN_ANIM_TOP               36
#define     MMIWIDGET_DCD_WIN_ANIM_BOTTOM     	   88
#define     MMIWIDGET_DCD_WIN_ANIM_LEFT              15
#define     MMIWIDGET_DCD_WIN_ANIM_RIGHT            55  

#define     MMIWIDGET_DCD_WIN_TEXT_TOP                36
#define     MMIWIDGET_DCD_WIN_TEXT_BOTTOM          88  
#define     MMIWIDGET_DCD_WIN_TEXT_LEFT       		(MMIWIDGET_DCD_WIN_ANIM_RIGHT+ MMIWIDGET_DCD_ITEM_PREVIEW_LINE_SPACE)      
#define     MMIWIDGET_DCD_WIN_TEXT_RIGHT            225


#define     MMIWIDGET_DCD_WIN_LEFT_IDC_TOP                8
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_BOTTOM           26
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_LEFT               12
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_RIGHT              30
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_RECT              {MMIWIDGET_DCD_WIN_LEFT_IDC_LEFT,MMIWIDGET_DCD_WIN_LEFT_IDC_TOP,MMIWIDGET_DCD_WIN_LEFT_IDC_RIGHT,MMIWIDGET_DCD_WIN_LEFT_IDC_BOTTOM}

#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_TOP                8
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_BOTTOM           26
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_LEFT               208
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_RIGHT              226
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_RECT              {MMIWIDGET_DCD_WIN_RIGHT_IDC_LEFT,MMIWIDGET_DCD_WIN_RIGHT_IDC_TOP,MMIWIDGET_DCD_WIN_RIGHT_IDC_RIGHT,MMIWIDGET_DCD_WIN_RIGHT_IDC_BOTTOM}

#define     MMIWIDGET_DCD_TAB_ANIM_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM_BOTTOM          25 
#define     MMIWIDGET_DCD_TAB_ANIM_LEFT               53
#define     MMIWIDGET_DCD_TAB_ANIM_RIGHT             73
#define     MMIWIDGET_DCD_TAB_ANIM_0_RECT              {MMIWIDGET_DCD_TAB_ANIM_LEFT,MMIWIDGET_DCD_TAB_ANIM_TOP,MMIWIDGET_DCD_TAB_ANIM_RIGHT,MMIWIDGET_DCD_TAB_ANIM_BOTTOM}

#define     MMIWIDGET_DCD_TAB_ANIM1_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM1_BOTTOM          25  
#define     MMIWIDGET_DCD_TAB_ANIM1_LEFT              90
#define     MMIWIDGET_DCD_TAB_ANIM1_RIGHT            110
#define     MMIWIDGET_DCD_TAB_ANIM_1_RECT              {MMIWIDGET_DCD_TAB_ANIM1_LEFT,MMIWIDGET_DCD_TAB_ANIM1_TOP,MMIWIDGET_DCD_TAB_ANIM1_RIGHT,MMIWIDGET_DCD_TAB_ANIM1_BOTTOM}


#define     MMIWIDGET_DCD_TAB_ANIM2_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM2_BOTTOM          25 
#define     MMIWIDGET_DCD_TAB_ANIM2_LEFT               127
#define     MMIWIDGET_DCD_TAB_ANIM2_RIGHT            147
#define     MMIWIDGET_DCD_TAB_ANIM_2_RECT              {MMIWIDGET_DCD_TAB_ANIM2_LEFT,MMIWIDGET_DCD_TAB_ANIM2_TOP,MMIWIDGET_DCD_TAB_ANIM2_RIGHT,MMIWIDGET_DCD_TAB_ANIM2_BOTTOM}

#define     MMIWIDGET_DCD_TAB_ANIM3_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM3_BOTTOM          25 
#define     MMIWIDGET_DCD_TAB_ANIM3_LEFT               164
#define     MMIWIDGET_DCD_TAB_ANIM3_RIGHT             184
#define     MMIWIDGET_DCD_TAB_ANIM_3_RECT              {MMIWIDGET_DCD_TAB_ANIM3_LEFT,MMIWIDGET_DCD_TAB_ANIM3_TOP,MMIWIDGET_DCD_TAB_ANIM3_RIGHT,MMIWIDGET_DCD_TAB_ANIM3_BOTTOM}

#define     MMIWIDGET_DCD_OPENMAINWIN_RECT		{15,36,225,90}


//***********************************************dual clock **********************************//
#define MMIWIDGET_DUAL_CLOCK_TIME1_TOP        23
#define MMIWIDGET_DUAL_CLOCK_TIME1_BOTTOM     (MMIWIDGET_DUAL_CLOCK_TIME1_TOP + 18 -1)
#define MMIWIDGET_DUAL_CLOCK_TIME1_LEFT       23
#define MMIWIDGET_DUAL_CLOCK_TIME1_RIGHT      (MMIWIDGET_DUAL_CLOCK_TIME1_LEFT + 68 -1)
#define MMIWIDGET_DUAL_CLOCK_TIME1_RECT       {MMIWIDGET_DUAL_CLOCK_TIME1_LEFT, MMIWIDGET_DUAL_CLOCK_TIME1_TOP, MMIWIDGET_DUAL_CLOCK_TIME1_RIGHT, MMIWIDGET_DUAL_CLOCK_TIME1_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_CITY1_TOP        27
#define MMIWIDGET_DUAL_CLOCK_CITY1_BOTTOM     (MMIWIDGET_DUAL_CLOCK_CITY1_TOP + 16 -1)
#define MMIWIDGET_DUAL_CLOCK_CITY1_LEFT       100
#define MMIWIDGET_DUAL_CLOCK_CITY1_RIGHT      (MMIWIDGET_DUAL_CLOCK_CITY1_LEFT + 118 -1)
#define MMIWIDGET_DUAL_CLOCK_CITY1_RECT       {MMIWIDGET_DUAL_CLOCK_CITY1_LEFT, MMIWIDGET_DUAL_CLOCK_CITY1_TOP, MMIWIDGET_DUAL_CLOCK_CITY1_RIGHT, MMIWIDGET_DUAL_CLOCK_CITY1_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_TIME2_TOP        69
#define MMIWIDGET_DUAL_CLOCK_TIME2_BOTTOM     (MMIWIDGET_DUAL_CLOCK_TIME2_TOP + 18 -1)
#define MMIWIDGET_DUAL_CLOCK_TIME2_LEFT       23
#define MMIWIDGET_DUAL_CLOCK_TIME2_RIGHT      (MMIWIDGET_DUAL_CLOCK_TIME2_LEFT + 68 -1)
#define MMIWIDGET_DUAL_CLOCK_TIME2_RECT       {MMIWIDGET_DUAL_CLOCK_TIME2_LEFT, MMIWIDGET_DUAL_CLOCK_TIME2_TOP, MMIWIDGET_DUAL_CLOCK_TIME2_RIGHT, MMIWIDGET_DUAL_CLOCK_TIME2_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_CITY2_TOP        73
#define MMIWIDGET_DUAL_CLOCK_CITY2_BOTTOM     (MMIWIDGET_DUAL_CLOCK_CITY2_TOP + 16 -1)
#define MMIWIDGET_DUAL_CLOCK_CITY2_LEFT       100
#define MMIWIDGET_DUAL_CLOCK_CITY2_RIGHT      (MMIWIDGET_DUAL_CLOCK_CITY2_LEFT + 118 -1)
#define MMIWIDGET_DUAL_CLOCK_CITY2_RECT       {MMIWIDGET_DUAL_CLOCK_CITY2_LEFT, MMIWIDGET_DUAL_CLOCK_CITY2_TOP, MMIWIDGET_DUAL_CLOCK_CITY2_RIGHT, MMIWIDGET_DUAL_CLOCK_CITY2_BOTTOM}

//***********************************************dual aclock **********************************//
//left aclock rect.
#define MMIWIDGET_LACLOCK_RECT_LEFT            0
#define MMIWIDGET_LACLOCK_RECT_TOP             0

//right aclock rect.
#define MMIWIDGET_RACLOCK_RECT_LEFT            130
#define MMIWIDGET_RACLOCK_RECT_TOP             0

//left aclock city rect.
#define MMIWIDGET_LACLOCK_CITY_RECT_LEFT       15
#define MMIWIDGET_LACLOCK_CITY_RECT_RIGHT      (MMIWIDGET_LACLOCK_CITY_RECT_LEFT + 81 -1)
#define MMIWIDGET_LACLOCK_CITY_RECT_TOP        111
#define MMIWIDGET_LACLOCK_CITY_RECT_BOTTOM     (MMIWIDGET_LACLOCK_CITY_RECT_TOP + 21 -1)
#define MMIWIDGET_LACLOCK_CITY_RECT            {MMIWIDGET_LACLOCK_CITY_RECT_LEFT, MMIWIDGET_LACLOCK_CITY_RECT_TOP, MMIWIDGET_LACLOCK_CITY_RECT_RIGHT, MMIWIDGET_LACLOCK_CITY_RECT_BOTTOM}

//right aclock city rect.
#define MMIWIDGET_RACLOCK_CITY_RECT_LEFT       145
#define MMIWIDGET_RACLOCK_CITY_RECT_RIGHT      (MMIWIDGET_RACLOCK_CITY_RECT_LEFT + 81 -1)
#define MMIWIDGET_RACLOCK_CITY_RECT_TOP        111
#define MMIWIDGET_RACLOCK_CITY_RECT_BOTTOM     (MMIWIDGET_RACLOCK_CITY_RECT_TOP + 21 -1)
#define MMIWIDGET_RACLOCK_CITY_RECT            {MMIWIDGET_RACLOCK_CITY_RECT_LEFT, MMIWIDGET_RACLOCK_CITY_RECT_TOP, MMIWIDGET_RACLOCK_CITY_RECT_RIGHT, MMIWIDGET_RACLOCK_CITY_RECT_BOTTOM}

#define MMIGRID_IDLE_SOFTKEY_HEIGHT            50
#define MMIGRID_IDLE_RECYCLE_HEIGHT            30

#if MMI_GRID_PAGE_NUM > 5
#define MMI_IDLE_GRID_THUMB_WIDTH              60
#define MMI_IDLE_GRID_THUMB_HEIGHT             100
#define MMI_IDLE_GRID_THUMB1_RECT              {40,  40,  99,  139}
#define MMI_IDLE_GRID_THUMB2_RECT              {139, 40,  198, 139}
#define MMI_IDLE_GRID_THUMB3_RECT              {15,  159, 74,  258}
#define MMI_IDLE_GRID_THUMB4_RECT              {90, 159, 149, 258}
#define MMI_IDLE_GRID_THUMB5_RECT              {165, 159, 224, 258}
#define MMI_IDLE_GRID_THUMB6_RECT              {40,  278, 99,  377}
#define MMI_IDLE_GRID_THUMB7_RECT              {139, 278, 198, 377}
#elif MMI_GRID_PAGE_NUM > 3
#define MMI_IDLE_GRID_THUMB_WIDTH              72
#define MMI_IDLE_GRID_THUMB_HEIGHT             120
#define MMI_IDLE_GRID_THUMB1_RECT              {32,  65,   103,  184}
#define MMI_IDLE_GRID_THUMB2_RECT              {135, 65,   206,  184}
#define MMI_IDLE_GRID_THUMB3_RECT              {6,   229,  77,   348}
#define MMI_IDLE_GRID_THUMB4_RECT              {83,  229,  154,  348}
#define MMI_IDLE_GRID_THUMB5_RECT              {160, 229,  232,  348}
#else
#define MMI_IDLE_GRID_THUMB_WIDTH              96//140
#define MMI_IDLE_GRID_THUMB_HEIGHT             160//210
#define MMI_IDLE_GRID_THUMB1_RECT              {16, 30, 111, 189}//{13, 30, 153, 240}
#define MMI_IDLE_GRID_THUMB2_RECT              {127, 30, 222, 189}//{166, 30, 306, 240}
#define MMI_IDLE_GRID_THUMB3_RECT              {74, 209, 169, 368}
#endif

#define MMI_GRID_SK_CALL_RECT                  {5, 430, 105, 479}
#define MMI_GRID_SK_MENU_RECT                  {110, 430, 210, 479}
#define MMI_GRID_SK_PB_RECT                    {215, 430, 315, 479}

#if MMI_GRID_PAGE_NUM > 5
#define MMI_GRID_PAGE_TITLE_RECT               {53, 350, 186, 353}
#elif MMI_GRID_PAGE_NUM > 3
#define MMI_GRID_PAGE_TITLE_RECT               {100, 425, 219, 428}
#else
#define MMI_GRID_PAGE_TITLE_RECT               {124, 425, 195, 428}
#endif

#ifdef MMI_GRID_IDLE_SUPPORT
//pb area.
#define MMI_GRID_PB_ADD_RECT                   {6, 95, 105, 125}
#define MMI_GRID_PB_IMG_RECT                   {6, 6, 105, 75}
#define MMI_GRID_PB_NAME_RECT                  {6, 76, 105, 96}
#define MMI_GRID_PB_CALL_RECT                  {6, 95, 54, 125}
#define MMI_GRID_PB_SMS_RECT                   {56, 95, 105, 125}

#ifdef BAR_PHONE_WIDGET
//image viewer area.
#define MMI_GRID_IMGVIEWER_IMG_RECT            {51, 14, 191, 251}
#define MMI_GRID_IMGVIEWER_IMG_ADD_RECT        {97, 70, 142, 115}
#define MMI_GRID_IMGVIEWER_IMG_RECT_H            {14, 20, 251, 162}
#define MMI_GRID_IMGVIEWER_IMG_ADD_RECT_H        {97, 100, 142, 145}
#else
//image viewer area.
#define MMI_GRID_IMGVIEWER_IMG_RECT            {25, 21, 215, 163}
#define MMI_GRID_IMGVIEWER_IMG_ADD_RECT        {97, 70, 142, 115} 
#endif
#endif

#ifdef MMI_GRID_IDLE_SUPPORT
//***********************************************Net Search **********************************//
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT_LEFT       195
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT_TOP        5
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT_RIGHT      227
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT_BOTTOM     37
#define MMIWIDGET_NET_SEARCH_BUTTON_RECT            {MMIWIDGET_NET_SEARCH_BUTTON_RECT_LEFT, MMIWIDGET_NET_SEARCH_BUTTON_RECT_TOP, MMIWIDGET_NET_SEARCH_BUTTON_RECT_RIGHT, MMIWIDGET_NET_SEARCH_BUTTON_RECT_BOTTOM}

#define MMIWIDGET_NET_SEARCH_STRING_RECT_LEFT       17
#define MMIWIDGET_NET_SEARCH_STRING_RECT_TOP        13
#define MMIWIDGET_NET_SEARCH_STRING_RECT_RIGHT      189
#define MMIWIDGET_NET_SEARCH_STRING_RECT_BOTTOM     32
#define MMIWIDGET_NET_SEARCH_STRING_RECT            {MMIWIDGET_NET_SEARCH_STRING_RECT_LEFT, MMIWIDGET_NET_SEARCH_STRING_RECT_TOP, MMIWIDGET_NET_SEARCH_STRING_RECT_RIGHT, MMIWIDGET_NET_SEARCH_STRING_RECT_BOTTOM}
#endif
#ifdef MMI_GRID_IDLE_SUPPORT
//***********************************************counted time **********************************//
#define MMIWIDGET_COUNTEDTIME_BUTTON_LEFT              36
#define MMIWIDGET_COUNTEDTIME_BUTTON_TOP               149
#define MMIWIDGET_COUNTEDTIME_BUTTON_RIGHT             191
#define MMIWIDGET_COUNTEDTIME_BUTTON_BOTTOM            183
#define MMIWIDGET_COUNTEDTIME_BUTTON_RECT              {MMIWIDGET_COUNTEDTIME_BUTTON_LEFT, MMIWIDGET_COUNTEDTIME_BUTTON_TOP, MMIWIDGET_COUNTEDTIME_BUTTON_RIGHT, MMIWIDGET_COUNTEDTIME_BUTTON_BOTTOM}

#define MMIWIDGET_COUNTEDTIME_EDIT_LEFT              9
#define MMIWIDGET_COUNTEDTIME_EDIT_TOP               9
#define MMIWIDGET_COUNTEDTIME_EDIT_RIGHT             222
#define MMIWIDGET_COUNTEDTIME_EDIT_BOTTOM            145
#define MMIWIDGET_COUNTEDTIME_EDIT_RECT              {MMIWIDGET_COUNTEDTIME_EDIT_LEFT, MMIWIDGET_COUNTEDTIME_EDIT_TOP, MMIWIDGET_COUNTEDTIME_EDIT_RIGHT, MMIWIDGET_COUNTEDTIME_EDIT_BOTTOM}
#endif
#ifdef SNS_SUPPORT
#define MMI_SNS_MOVE_X            15*2
#define MMI_SNS_MOVE_Y            10
#define MMI_SNS_MOVE_Y2           5
#define MMI_SNS_TIME_FONT         SONG_FONT_14
#define MMIWIDGET_SNS_LOGIN_HEIGHT   112
#define MMIWIDGET_SNS_LOGIN_WIDTH    230

#define MMIWIDGET_SNS_BG_HEIGHT      192
#define MMIWIDGET_SNS_BG_WIDTH       230

#define MMIWIDGET_SNS_BG2_HEIGHT      150
#define MMIWIDGET_SNS_BG2_WIDTH       230

#define MMIWIDGET_SNS_VIRTUE_HEIGHT      43
#define MMIWIDGET_SNS_VIRTUE_WIDTH       230


#define MMIWIDGET_SNS_IMG_LEFT       10      
#define MMIWIDGET_SNS_IMG_TOP        10

#define MMIWIDGET_SNS_NAME_LEFT      11
#define MMIWIDGET_SNS_NAME_TOP       11
#define MMIWIDGET_SNS_NAME_WIDTH     100 +30
#define MMIWIDGET_SNS_NAME_HEIGHT    18

#define MMIWIDGET_SNS_FLAG_LEFT      118 +30
#define MMIWIDGET_SNS_FLAG_TOP       15 -3
#define MMIWIDGET_SNS_FLAG_WIDTH     100
#define MMIWIDGET_SNS_FLAG_HEIGHT    14

#define MMIWIDGET_SNS_TIME_LEFT      11
#define MMIWIDGET_SNS_TIME_TOP       124+5+2
#define MMIWIDGET_SNS_TIME_WIDTH     208
#define MMIWIDGET_SNS_TIME_HEIGHT    14

#define MMIWIDGET_SNS_TEXT_LEFT      11
#define MMIWIDGET_SNS_TEXT_TOP       42-6
#define MMIWIDGET_SNS_TEXT_WIDTH     208
#define MMIWIDGET_SNS_TEXT_HEIGHT    82+5+7

#define MMIWIDGET_SNS_ADD_LEFT       96
#define MMIWIDGET_SNS_ADD_TOP        127+25
#define MMIWIDGET_SNS_ADD_WIDTH      37
#define MMIWIDGET_SNS_ADD_HEIGHT     42

#ifdef SNS_PULLING_SUPPORT
#define MMIWIDGET_SNS_SYNC_LEFT       133 //96+37
#define MMIWIDGET_SNS_SYNC_TOP        152 //127+25
#define MMIWIDGET_SNS_SYNC_WIDTH      37
#define MMIWIDGET_SNS_SYNC_HEIGHT     42

#define MMIWIDGET_SNS_SETTING_LEFT    170 //96+37+37
#define MMIWIDGET_SNS_SETTING_TOP     152 //127+25
#define MMIWIDGET_SNS_SETTING_WIDTH   37
#define MMIWIDGET_SNS_SETTING_HEIGHT  42
#endif //SNS_PULLING_SUPPORT

#define MMIWIDGET_SNS_LOG_LEFT       15
#define MMIWIDGET_SNS_LOG_TOP        66
#define MMIWIDGET_SNS_LOG_WIDTH      200
#define MMIWIDGET_SNS_LOG_HEIGHT     30

#define MMIWIDGET_SNS_LOG_FLAG_LEFT  15
#define MMIWIDGET_SNS_LOG_FLAG_TOP   12

#define MMI_SNS_IMG_NAME_RECT  {MMIWIDGET_SNS_NAME_LEFT, MMIWIDGET_SNS_NAME_TOP, MMIWIDGET_SNS_NAME_LEFT+MMIWIDGET_SNS_NAME_WIDTH , MMIWIDGET_SNS_NAME_TOP+MMIWIDGET_SNS_NAME_HEIGHT}
#define MMI_SNS_IMG_FALG_RECT  {MMIWIDGET_SNS_FLAG_LEFT, MMIWIDGET_SNS_FLAG_TOP, MMIWIDGET_SNS_FLAG_LEFT+MMIWIDGET_SNS_FLAG_WIDTH , MMIWIDGET_SNS_FLAG_TOP+MMIWIDGET_SNS_FLAG_HEIGHT}
#define MMI_SNS_IMG_TEXT_RECT  {MMIWIDGET_SNS_TEXT_LEFT, MMIWIDGET_SNS_TEXT_TOP, MMIWIDGET_SNS_TEXT_LEFT+MMIWIDGET_SNS_TEXT_WIDTH , MMIWIDGET_SNS_TEXT_TOP+MMIWIDGET_SNS_TEXT_HEIGHT}
#define MMI_SNS_IMG_TIME_RECT  {MMIWIDGET_SNS_TIME_LEFT, MMIWIDGET_SNS_TIME_TOP, MMIWIDGET_SNS_TIME_LEFT+MMIWIDGET_SNS_TIME_WIDTH , MMIWIDGET_SNS_TIME_TOP+MMIWIDGET_SNS_TIME_HEIGHT}


#define MMIWIDGET_SNS_IMG_RIGHT      MMIWIDGET_SNS_IMG_LEFT + MMIWIDGET_SNS_BG_WIDTH     
#define MMIWIDGET_SNS_IMG_BUTTOM     MMIWIDGET_SNS_IMG_TOP + MMIWIDGET_SNS_BG_HEIGHT

#define MMI_SNS_IMG_LOG_BG_RECT  {MMIWIDGET_SNS_IMG_LEFT, MMIWIDGET_SNS_IMG_TOP, MMIWIDGET_SNS_IMG_LEFT+ MMIWIDGET_SNS_LOGIN_WIDTH , MMIWIDGET_SNS_IMG_TOP + MMIWIDGET_SNS_LOGIN_HEIGHT}
#define MMI_SNS_IMG_LOG_RECT     {MMIWIDGET_SNS_LOG_LEFT, MMIWIDGET_SNS_LOG_TOP, MMIWIDGET_SNS_LOG_LEFT+ MMIWIDGET_SNS_LOG_WIDTH , MMIWIDGET_SNS_LOG_TOP + MMIWIDGET_SNS_LOG_HEIGHT}

#define MMI_SNS_IMG_BG_RECT      {MMIWIDGET_SNS_IMG_LEFT, MMIWIDGET_SNS_IMG_TOP, MMIWIDGET_SNS_IMG_RIGHT , MMIWIDGET_SNS_IMG_BUTTOM}
#define MMI_SNS_IMG_ADD_RECT     {MMIWIDGET_SNS_ADD_LEFT, MMIWIDGET_SNS_ADD_TOP, MMIWIDGET_SNS_ADD_LEFT + MMIWIDGET_SNS_ADD_WIDTH , MMIWIDGET_SNS_ADD_TOP+MMIWIDGET_SNS_ADD_HEIGHT}

#ifdef SNS_PULLING_SUPPORT
#define MMI_SNS_IMG_SYNC_RECT     {MMIWIDGET_SNS_SYNC_LEFT, MMIWIDGET_SNS_SYNC_TOP, MMIWIDGET_SNS_SYNC_LEFT + MMIWIDGET_SNS_SYNC_WIDTH , MMIWIDGET_SNS_SYNC_TOP+MMIWIDGET_SNS_SYNC_HEIGHT}
#define MMI_SNS_IMG_SETTING_RECT  {MMIWIDGET_SNS_SETTING_LEFT, MMIWIDGET_SNS_SETTING_TOP, MMIWIDGET_SNS_SETTING_LEFT + MMIWIDGET_SNS_SETTING_WIDTH , MMIWIDGET_SNS_SETTING_TOP+MMIWIDGET_SNS_SETTING_HEIGHT}
#endif //SNS_PULLING_SUPPORT

#endif
