//***********************************bar***********************************************//
//shortcut数据
//每个shortcut item间隔
#define MMIWIDGET_SHORTCUT_INTERVAL         10//29
//快捷背景图片与LCD顶上间距
#define MMIWIDGET_SHORTCUT_TOP_GAP          20
//快捷拖动预留的间距
#define MMIWIDGET_SHORTCUT_BG_ITEM_SPACE         10

//***********************************************digital clock **********************************//
#define MMIWIDGET_CLOCK_TIME_TOP            16
#define MMIWIDGET_CLOCK_DATE_BOTTOM         30
#define MMIWIDGET_CLOCK_WEEK_BOTTOM         13

//aclock time rect.
#define MMIWIDGET_ACLOCK_RECT_LEFT            0
#define MMIWIDGET_ACLOCK_RECT_TOP             0
#define MMIWIDGET_ACLOCK_RECT_RIGHT           100
#define MMIWIDGET_ACLOCK_RECT_BOTTOM          100
#define MMIWIDGET_ACLOCK_RECT                 {MMIWIDGET_ACLOCK_RECT_LEFT, MMIWIDGET_ACLOCK_RECT_TOP, MMIWIDGET_ACLOCK_RECT_RIGHT, MMIWIDGET_ACLOCK_RECT_BOTTOM}

//***********************************mp3*****************************************//
//mp3名字区域
#define MMIWIDGET_MP3_MP3NAME_RECT_LEFT            14
#define MMIWIDGET_MP3_MP3NAME_RECT_TOP              12
#define MMIWIDGET_MP3_MP3NAME_RECT_RIGHT           127
#define MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM         32
#define MMIWIDGET_MP3_MP3NAME_RECT              {MMIWIDGET_MP3_MP3NAME_RECT_LEFT, MMIWIDGET_MP3_MP3NAME_RECT_TOP, MMIWIDGET_MP3_MP3NAME_RECT_RIGHT, MMIWIDGET_MP3_MP3NAME_RECT_BOTTOM}
//后退按钮
#define MMIWIDGET_MP3_LBUTTON_LEFT            17
#define MMIWIDGET_MP3_LBUTTON_TOP             44
#define MMIWIDGET_MP3_LBUTTON_RIGHT           (MMIWIDGET_MP3_LBUTTON_LEFT+25-1)
#define MMIWIDGET_MP3_LBUTTON_BOTTOM         (MMIWIDGET_MP3_LBUTTON_TOP+25-1)
#define MMIWIDGET_MP3_LBUTTON_RECT            {MMIWIDGET_MP3_LBUTTON_LEFT, MMIWIDGET_MP3_LBUTTON_TOP, MMIWIDGET_MP3_LBUTTON_RIGHT, MMIWIDGET_MP3_LBUTTON_BOTTOM}

//播放按钮
#define MMIWIDGET_MP3_ENTRYPLAY_LEFT              57
#define MMIWIDGET_MP3_ENTRYPLAY_TOP                44 
#define MMIWIDGET_MP3_ENTRYPLAY_RIGHT           (MMIWIDGET_MP3_ENTRYPLAY_LEFT + 25 -1)
#define MMIWIDGET_MP3_ENTRYPLAY_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAY_TOP +25-1)
#define    MMIWIDGET_MP3_ENTRYPLAY_RECT    {MMIWIDGET_MP3_ENTRYPLAY_LEFT,MMIWIDGET_MP3_ENTRYPLAY_TOP,MMIWIDGET_MP3_ENTRYPLAY_RIGHT,MMIWIDGET_MP3_ENTRYPLAY_BOTTOM}
//前进按钮
#define MMIWIDGET_MP3_RBUTTON_LEFT              67
#define MMIWIDGET_MP3_RBUTTON_TOP               34
#define MMIWIDGET_MP3_RBUTTON_RIGHT           (MMIWIDGET_MP3_RBUTTON_LEFT +25 -1)
#define MMIWIDGET_MP3_RBUTTON_BOTTOM         (MMIWIDGET_MP3_RBUTTON_TOP+25-1)
#define MMIWIDGET_MP3_RBUTTON_RECT            {MMIWIDGET_MP3_RBUTTON_LEFT, MMIWIDGET_MP3_RBUTTON_TOP, MMIWIDGET_MP3_RBUTTON_RIGHT, MMIWIDGET_MP3_RBUTTON_BOTTOM}



//进入mp3播放器按钮
#define MMIWIDGET_MP3_ENTRYPLAYER_LEFT              90
#define MMIWIDGET_MP3_ENTRYPLAYER_TOP                34 
#define MMIWIDGET_MP3_ENTRYPLAYER_RIGHT           (MMIWIDGET_MP3_ENTRYPLAYER_LEFT + 25 -1)
#define MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM          (MMIWIDGET_MP3_ENTRYPLAYER_TOP +25-1)
#define    MMIWIDGET_MP3_ENTRYPLAYER_RECT    {MMIWIDGET_MP3_ENTRYPLAYER_LEFT,MMIWIDGET_MP3_ENTRYPLAYER_TOP,MMIWIDGET_MP3_ENTRYPLAYER_RIGHT,MMIWIDGET_MP3_ENTRYPLAYER_BOTTOM}

#define MMIWIDGET_MP3_CHANGEPANEL_LEFT            90
#define MMIWIDGET_MP3_CHANGEPANEL_TOP             16
#define MMIWIDGET_MP3_CHANGEPANEL_RIGHT          (MMIWIDGET_MP3_CHANGEPANEL_LEFT +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_BOTTOM      (MMIWIDGET_MP3_CHANGEPANEL_TOP +46 -1)
#define MMIWIDGET_MP3_CHANGEPANEL_RECT          {MMIWIDGET_MP3_CHANGEPANEL_LEFT, MMIWIDGET_MP3_CHANGEPANEL_TOP, MMIWIDGET_MP3_CHANGEPANEL_RIGHT, MMIWIDGET_MP3_CHANGEPANEL_BOTTOM}

#define   MMIWIDGET_MP3_PROGRESS_RECT        {17,35,17+140-1,35+1}

#define   MMIWIDGET_MP3_PROGRESS_WIDTH              140

#define MMIWIDGET_MP3_VOL_IMAGE_LEFT            12
#define MMIWIDGET_MP3_VOL_IMAGE_TOP             28
#define MMIWIDGET_MP3_VOL_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_IMAGE_LEFT +15 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_IMAGE_TOP +18 -1)
#define MMIWIDGET_MP3_VOL_IMAGE_RECT          {MMIWIDGET_MP3_VOL_IMAGE_LEFT, MMIWIDGET_MP3_VOL_IMAGE_TOP, MMIWIDGET_MP3_VOL_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_DEC_LEFT            13
#define MMIWIDGET_MP3_VOL_DEC_TOP             38
#define MMIWIDGET_MP3_VOL_DEC_RIGHT          (MMIWIDGET_MP3_VOL_DEC_LEFT +24 -1)
#define MMIWIDGET_MP3_VOL_DEC_BOTTOM      (MMIWIDGET_MP3_VOL_DEC_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_DEC_RECT          {MMIWIDGET_MP3_VOL_DEC_LEFT, MMIWIDGET_MP3_VOL_DEC_TOP, MMIWIDGET_MP3_VOL_DEC_RIGHT, MMIWIDGET_MP3_VOL_DEC_BOTTOM}

#define MMIWIDGET_MP3_VOL_ADD_LEFT            80
#define MMIWIDGET_MP3_VOL_ADD_TOP             38
#define MMIWIDGET_MP3_VOL_ADD_RIGHT          (MMIWIDGET_MP3_VOL_ADD_LEFT +23 -1)
#define MMIWIDGET_MP3_VOL_ADD_BOTTOM      (MMIWIDGET_MP3_VOL_ADD_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_ADD_RECT          {MMIWIDGET_MP3_VOL_ADD_LEFT, MMIWIDGET_MP3_VOL_ADD_TOP, MMIWIDGET_MP3_VOL_ADD_RIGHT, MMIWIDGET_MP3_VOL_ADD_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT            37
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP             38
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT          (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT+107-1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP +19 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_TOP, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_IMAGE_BOTTOM}

#define MMIWIDGET_MP3_VOL_PROGRESS_LEFT            34
#define MMIWIDGET_MP3_VOL_PROGRESS_TOP             34
#define MMIWIDGET_MP3_VOL_PROGRESS_RIGHT          80
#define MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM      (MMIWIDGET_MP3_VOL_PROGRESS_TOP +6 -1)
#define MMIWIDGET_MP3_VOL_PROGRESS_RECT          {MMIWIDGET_MP3_VOL_PROGRESS_LEFT, MMIWIDGET_MP3_VOL_PROGRESS_TOP, MMIWIDGET_MP3_VOL_PROGRESS_RIGHT, MMIWIDGET_MP3_VOL_PROGRESS_BOTTOM}

//*****************************************PB*********************************************************//
//中央大图宽高
#define MMIWIDGET_PB_WIDGET_BIG_WIDTH         62
#define MMIWIDGET_PB_WIDGET_BIG_HEIGHT        62
//边上小图宽高
#define MMIWIDGET_PB_WIDGET_SMALL_WIDTH       35
#define MMIWIDGET_PB_WIDGET_SMALL_HEIGHT      35
//各pb widget区域
#define MMIWIDGET_PB_WIDGET_1_2_LEFT          8//17
#define MMIWIDGET_PB_WIDGET_3_4_LEFT          84//178
#define MMIWIDGET_PB_WIDGET_1_3_TOP           8//106
#define MMIWIDGET_PB_WIDGET_2_4_TOP           58//154

#define MMIWIDGET_PB_WIDGET_0_LEFT            32//71
#define MMIWIDGET_PB_WIDGET_0_TOP             12//101
#define MMIWIDGET_PB_WIDGET_0_RIGHT       (MMIWIDGET_PB_WIDGET_0_LEFT+MMIWIDGET_PB_WIDGET_BIG_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_0_BOTTOM      (MMIWIDGET_PB_WIDGET_0_TOP+MMIWIDGET_PB_WIDGET_BIG_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_0_RECT      {MMIWIDGET_PB_WIDGET_0_LEFT, MMIWIDGET_PB_WIDGET_0_TOP, MMIWIDGET_PB_WIDGET_0_RIGHT, MMIWIDGET_PB_WIDGET_0_BOTTOM}

#define MMIWIDGET_PB_WIDGET_1_LEFT        MMIWIDGET_PB_WIDGET_1_2_LEFT
#define MMIWIDGET_PB_WIDGET_1_TOP         MMIWIDGET_PB_WIDGET_1_3_TOP
#define MMIWIDGET_PB_WIDGET_1_RIGHT       (MMIWIDGET_PB_WIDGET_1_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_1_BOTTOM      (MMIWIDGET_PB_WIDGET_1_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_1_RECT      {MMIWIDGET_PB_WIDGET_1_LEFT, MMIWIDGET_PB_WIDGET_1_TOP, MMIWIDGET_PB_WIDGET_1_RIGHT, MMIWIDGET_PB_WIDGET_1_BOTTOM}

#define MMIWIDGET_PB_WIDGET_2_LEFT        MMIWIDGET_PB_WIDGET_1_2_LEFT
#define MMIWIDGET_PB_WIDGET_2_TOP         MMIWIDGET_PB_WIDGET_2_4_TOP
#define MMIWIDGET_PB_WIDGET_2_RIGHT       (MMIWIDGET_PB_WIDGET_2_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_2_BOTTOM      (MMIWIDGET_PB_WIDGET_2_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_2_RECT      {MMIWIDGET_PB_WIDGET_2_LEFT, MMIWIDGET_PB_WIDGET_2_TOP, MMIWIDGET_PB_WIDGET_2_RIGHT, MMIWIDGET_PB_WIDGET_2_BOTTOM}

#define MMIWIDGET_PB_WIDGET_3_LEFT        MMIWIDGET_PB_WIDGET_3_4_LEFT
#define MMIWIDGET_PB_WIDGET_3_TOP         MMIWIDGET_PB_WIDGET_1_3_TOP
#define MMIWIDGET_PB_WIDGET_3_RIGHT       (MMIWIDGET_PB_WIDGET_3_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_3_BOTTOM      (MMIWIDGET_PB_WIDGET_3_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_3_RECT      {MMIWIDGET_PB_WIDGET_3_LEFT, MMIWIDGET_PB_WIDGET_3_TOP, MMIWIDGET_PB_WIDGET_3_RIGHT, MMIWIDGET_PB_WIDGET_3_BOTTOM}

#define MMIWIDGET_PB_WIDGET_4_LEFT        MMIWIDGET_PB_WIDGET_3_4_LEFT
#define MMIWIDGET_PB_WIDGET_4_TOP         MMIWIDGET_PB_WIDGET_2_4_TOP
#define MMIWIDGET_PB_WIDGET_4_RIGHT       (MMIWIDGET_PB_WIDGET_4_LEFT+MMIWIDGET_PB_WIDGET_SMALL_WIDTH-1)
#define MMIWIDGET_PB_WIDGET_4_BOTTOM      (MMIWIDGET_PB_WIDGET_4_TOP+MMIWIDGET_PB_WIDGET_SMALL_HEIGHT-1)
#define MMIWIDGET_PB_WIDGET_4_RECT      {MMIWIDGET_PB_WIDGET_4_LEFT, MMIWIDGET_PB_WIDGET_4_TOP, MMIWIDGET_PB_WIDGET_4_RIGHT, MMIWIDGET_PB_WIDGET_4_BOTTOM}

#define MMIWIDGET_PB_WIDGET_CALL_LEFT  		59
#define MMIWIDGET_PB_WIDGET_CALL_TOP		84
#define MMIWIDGET_PB_WIDGET_CALL_RIGHT		73
#define MMIWIDGET_PB_WIDGET_CALL_BOTTOM	    102
#define MMIWIDGET_PB_WIDGET_CALL_RECT      {MMIWIDGET_PB_WIDGET_CALL_LEFT, MMIWIDGET_PB_WIDGET_CALL_TOP, MMIWIDGET_PB_WIDGET_CALL_RIGHT, MMIWIDGET_PB_WIDGET_CALL_BOTTOM}

#define MMIWIDGET_PB_WIDGET_SMS_LEFT  		83
#define MMIWIDGET_PB_WIDGET_SMS_TOP			84
#define MMIWIDGET_PB_WIDGET_SMS_RIGHT		97
#define MMIWIDGET_PB_WIDGET_SMS_BOTTOM		102
#define MMIWIDGET_PB_WIDGET_SMS_RECT      {MMIWIDGET_PB_WIDGET_SMS_LEFT, MMIWIDGET_PB_WIDGET_SMS_TOP, MMIWIDGET_PB_WIDGET_SMS_RIGHT, MMIWIDGET_PB_WIDGET_SMS_BOTTOM}

//*****************************************shortcut menu ****************************************8//
#define    MMIWIDGET_SHORTCUT_MENU_ICON_START_X       5

#define    MMIWIDGET_SHORTCUT_MENU_ICON_START_Y       10 

#define    MMIWIDGET_SHORTCUT_MENU_ICON_INTERVAL       5 

#define    MMIWIDGET_SHORTCUT_MENU_EMPTY_RECT     {0,0,0,0}
//默认左键头的区域
#define    MMIWIDGET_SHORTCUT_MENU_PAGE_BUTTON   {120,19,120+24,19+24}
//**************************************************calendar *****************************************************//
//month of date
#define MMIWIDGET_CALENDAR_LINE_WIDTH      24
#define MMIWIDGET_CALENDAR_LINE_HEIGHT     20

#define   MMIWIDGET_CALENDAR_LINE_GAP         1

#define   MMIWIDGET_CALENDAR_BG_IMAGE_WIDTH         118

#define MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT   4
#define MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM0_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM1_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM2_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM3_LEFT+MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM4_LEFT+ MMIWIDGET_CALENDAR_LINE_WIDTH-1)
#define MMIWIDGET_CALENDAR_MONTH_ITEM6_LEFT   (MMIWIDGET_CALENDAR_MONTH_ITEM5_LEFT + MMIWIDGET_CALENDAR_LINE_WIDTH-1)


#define  MMIWIDGET_CALENDAR_MONTH_LINE0_TOP   34
#define  MMIWIDGET_CALENDAR_MONTH_LINE1_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE0_TOP+ MMIWIDGET_CALENDAR_LINE_HEIGHT +MMIWIDGET_CALENDAR_LINE_GAP)
#define  MMIWIDGET_CALENDAR_MONTH_LINE2_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE1_TOP + MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP)
#define  MMIWIDGET_CALENDAR_MONTH_LINE3_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE2_TOP+ MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP)
#define  MMIWIDGET_CALENDAR_MONTH_LINE4_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE3_TOP + MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP)
#define  MMIWIDGET_CALENDAR_MONTH_LINE5_TOP   (MMIWIDGET_CALENDAR_MONTH_LINE4_TOP + MMIWIDGET_CALENDAR_LINE_HEIGHT+MMIWIDGET_CALENDAR_LINE_GAP)

#define MMIWIDGET_CALENDAR_YEAR_MONTH_TITLE_RECT   {7,10,MMIWIDGET_CALENDAR_BG_IMAGE_WIDTH,25}  
//*****************************memo   ******************************************************//
#define   MMIWIDGET_MEMO_TOP_GAP                       25

#define   MMIWIDGET_MEMO_BOTTOM_GAP                20

#define   MMIWIDGET_MEMO_LEFT_GAP                     20

#define   MMIWIDGET_MEMO_RIGHT_GAP                   10

#define   MMIWIDGET_MEMO_LINE_SPACE                   2

//***********************************network name  *****************************************//

#define   MMIWIDGET_NETWORK_SIM1_SIM2_INTERVAL    6

#define   MMIWIDGET_NETWORK_TOP_SPACE                    7
//custom word

//   *********************new sms      **********************************//
#define    MMIWIDGET_NEWSMS_OEPN_RECT             {14,130,14+67-1,130+41-1}

#define    MMIWIDGET_NEWSMS_CANCEL_RECT         {81,130,81+67-1,130+41-1}

//行间距
#define  MMIWIDGET_NEWSMS_LINE_SPACE          4

//上间距
#define  MMIWIDGET_NEWSMS_TOP_SPACE          25
//左间距
#define  MMIWIDGET_NEWSMS_LEFT_SPACE          25
//段间距
#define  MMIWIDGET_NEWSMS_SENTENCE_SPACE          20
//右间距
#define    MMIWIDGET_NEWSMS_RIGHT_GAP                   3
//****************************FM   *************************************//
//后退按钮
#define MMIWIDGET_FM_LBUTTON_LEFT           8
#define MMIWIDGET_FM_LBUTTON_TOP            67
#define MMIWIDGET_FM_LBUTTON_RIGHT			(MMIWIDGET_FM_LBUTTON_LEFT + 29 - 1)
#define MMIWIDGET_FM_LBUTTON_BOTTOM			(MMIWIDGET_FM_LBUTTON_TOP + 29 - 1)
#define MMIWIDGET_FM_LBUTTON_RECT           {MMIWIDGET_FM_LBUTTON_LEFT, MMIWIDGET_FM_LBUTTON_TOP, MMIWIDGET_FM_LBUTTON_RIGHT, MMIWIDGET_FM_LBUTTON_BOTTOM}

//前进按钮
#define MMIWIDGET_FM_RBUTTON_LEFT           47
#define MMIWIDGET_FM_RBUTTON_TOP            67
#define MMIWIDGET_FM_RBUTTON_RIGHT          (MMIWIDGET_FM_RBUTTON_LEFT + 29 - 1)
#define MMIWIDGET_FM_RBUTTON_BOTTOM			(MMIWIDGET_FM_RBUTTON_TOP + 29 - 1)
#define MMIWIDGET_FM_RBUTTON_RECT           {MMIWIDGET_FM_RBUTTON_LEFT, MMIWIDGET_FM_RBUTTON_TOP, MMIWIDGET_FM_RBUTTON_RIGHT, MMIWIDGET_FM_RBUTTON_BOTTOM}

//fm名字区域
#define MMIWIDGET_FM_NAME_RECT_LEFT           9
#define MMIWIDGET_FM_NAME_RECT_TOP            9
#define MMIWIDGET_FM_NAME_RECT_RIGHT          (MMIWIDGET_FM_NAME_RECT_LEFT + 168 - 1)
#define MMIWIDGET_FM_NAME_RECT_BOTTOM         (20 + 36 - 1)
#define MMIWIDGET_FM_NAME_RECT                {MMIWIDGET_FM_NAME_RECT_LEFT, MMIWIDGET_FM_NAME_RECT_TOP, MMIWIDGET_FM_NAME_RECT_RIGHT, MMIWIDGET_FM_NAME_RECT_BOTTOM}

//播放按钮
#define MMIWIDGET_FM_PLAYBUTTON_LEFT           130
#define MMIWIDGET_FM_PLAYBUTTON_TOP            60
#define MMIWIDGET_FM_PLAYBUTTON_RIGHT		   (MMIWIDGET_FM_PLAYBUTTON_LEFT + 46 - 1)
#define MMIWIDGET_FM_PLAYBUTTON_BOTTOM		   (MMIWIDGET_FM_PLAYBUTTON_TOP + 46 - 1)
#define MMIWIDGET_FM_PLAYBUTTON_RECT           {MMIWIDGET_FM_PLAYBUTTON_LEFT, MMIWIDGET_FM_PLAYBUTTON_TOP, MMIWIDGET_FM_PLAYBUTTON_RIGHT, MMIWIDGET_FM_PLAYBUTTON_BOTTOM}

// 游标区域
#define MMIWIDGET_FM_CURSOR_Y                   20
#define MMIWIDGET_FM_CURSOR_X_START             15
#define MMIWIDGET_FM_CURSOR_X_END               155

//**************************************CALL LOG****************************************//
#define MMIWIDGET_CALLLOG_OEPN_RECT           {14,130,14+67-1,130+41-1}

#define MMIWIDGET_CALLLOG_CANCEL_RECT       {81,130,81+67-1,130+41-1}

//行间距
#define  MMIWIDGET_CALLLOG_LINE_SPACE          4

//上间距
#define  MMIWIDGET_CALLLOG_TOP_SPACE          25
//左间距
#define  MMIWIDGET_CALLLOG_LEFT_SPACE          25
//段间距
#define  MMIWIDGET_CALLLOG_SENTENCE_SPACE          20

//**************************************Auto Answer Log********************************//

#define MMIWIDGET_AUTOANSWER_LOG_OEPN_RECT           {14,130,14+67-1,130+41-1}

#define MMIWIDGET_AUTOANSWER_LOG_CANCEL_RECT       {81,130,81+67-1,130+41-1}

//行间距
#define  MMIWIDGET_AUTOANSWER_LOG_LINE_SPACE          4

//上间距
#define  MMIWIDGET_AUTOANSWER_LOG_TOP_SPACE          25
//左间距
#define  MMIWIDGET_AUTOANSWER_LOG_LEFT_SPACE          25
//段间距
#define  MMIWIDGET_AUTOANSWER_LOG_SENTENCE_SPACE          20

//****************************************page widget***********************************//
#define MMITHEME_WIDGET_TITLE_ICON_RECT      {83, 266, 158, 271}
#define MMITHEME_WIDGET_TITLE_ICON_H_SPC      18
//以下是横屏位置
#define MMITHEME_H_WIDGET_TITLE_ICON_RECT {124, 192, 199, 203}
#define MMITHEME_H_WIDGET_TITLE_ICON_H_SPC 18

//****************************************Shortcut set***********************************//
//WIFI
#define MMIWIDGET_SHORTCUT_SET_WIFI_LEFT                   0
#define MMIWIDGET_SHORTCUT_SET_WIFI_TOP                     0
#define MMIWIDGET_SHORTCUT_SET_WIFI_RIGHT			50
#define MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM			40
#define MMIWIDGET_SHORTCUT_SET_WIFI_RECT            {MMIWIDGET_SHORTCUT_SET_WIFI_LEFT, MMIWIDGET_SHORTCUT_SET_WIFI_TOP, MMIWIDGET_SHORTCUT_SET_WIFI_RIGHT, MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM}
//BT
#define MMIWIDGET_SHORTCUT_SET_BT_LEFT                 MMIWIDGET_SHORTCUT_SET_WIFI_RIGHT+1
#define MMIWIDGET_SHORTCUT_SET_BT_TOP                  MMIWIDGET_SHORTCUT_SET_WIFI_TOP
#define MMIWIDGET_SHORTCUT_SET_BT_RIGHT			MMIWIDGET_SHORTCUT_SET_BT_LEFT+50
#define MMIWIDGET_SHORTCUT_SET_BT_BOTTOM		MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM
#define MMIWIDGET_SHORTCUT_SET_BT_RECT            {MMIWIDGET_SHORTCUT_SET_BT_LEFT, MMIWIDGET_SHORTCUT_SET_BT_TOP, MMIWIDGET_SHORTCUT_SET_BT_RIGHT, MMIWIDGET_SHORTCUT_SET_BT_BOTTOM}
//BACKLIGHT
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_LEFT                 MMIWIDGET_SHORTCUT_SET_BT_RIGHT+1
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_TOP                  MMIWIDGET_SHORTCUT_SET_WIFI_TOP
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RIGHT			MMIWIDGET_SHORTCUT_SET_BACKLIGHT_LEFT+50
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_BOTTOM		MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM
#define MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RECT            {MMIWIDGET_SHORTCUT_SET_BACKLIGHT_LEFT, MMIWIDGET_SHORTCUT_SET_BACKLIGHT_TOP, MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RIGHT, MMIWIDGET_SHORTCUT_SET_BACKLIGHT_BOTTOM}
//VOLUME
#define MMIWIDGET_SHORTCUT_SET_SILENT_LEFT                 MMIWIDGET_SHORTCUT_SET_BACKLIGHT_RIGHT+1
#define MMIWIDGET_SHORTCUT_SET_SILENT_TOP                  MMIWIDGET_SHORTCUT_SET_WIFI_TOP
#define MMIWIDGET_SHORTCUT_SET_SILENT_RIGHT			MMIWIDGET_SHORTCUT_SET_SILENT_LEFT+50
#define MMIWIDGET_SHORTCUT_SET_SILENT_BOTTOM		MMIWIDGET_SHORTCUT_SET_WIFI_BOTTOM
#define MMIWIDGET_SHORTCUT_SET_SILENT_RECT            {MMIWIDGET_SHORTCUT_SET_SILENT_LEFT, MMIWIDGET_SHORTCUT_SET_SILENT_TOP, MMIWIDGET_SHORTCUT_SET_SILENT_RIGHT, MMIWIDGET_SHORTCUT_SET_SILENT_BOTTOM}
//**************************************ALARM******************************************//
//alarm
#define MMIWIDGET_ALARM_BUTTON_RECT          {120, 14, 180, 34}
#define MMIWIDGET_ALARM_NAME_RECT            {23,17, 110, 23+30-1}
#define MMIWIDGET_ALARM_LARR_RECT            {7, 32, 17, 47}
#define MMIWIDGET_ALARM_RARR_RECT            {183, 32, 193, 47}
#define MMIWIDGET_ALARM_INDIC_RECT           {38, 80, 162, 99}
//****************************************Search***********************************//

#define MMIWIDGET_SEARCH_TYPE_LEFT                   10

#define MMIWIDGET_SEARCH_EDIT_LEFT                 50

//****************************************DCD***********************************//

#define     MMIWIDGET_DCD_ITEM_PREVIEW_LINE_SPACE          10


#define     MMIWIDGET_DCD_WIN_ANIM_TOP               36
#define     MMIWIDGET_DCD_WIN_ANIM_BOTTOM     	   88
#define     MMIWIDGET_DCD_WIN_ANIM_LEFT              15
#define     MMIWIDGET_DCD_WIN_ANIM_RIGHT            55  

#define     MMIWIDGET_DCD_WIN_TEXT_TOP                36
#define     MMIWIDGET_DCD_WIN_TEXT_BOTTOM          88  
#define     MMIWIDGET_DCD_WIN_TEXT_LEFT       		(MMIWIDGET_DCD_WIN_ANIM_RIGHT+ MMIWIDGET_DCD_ITEM_PREVIEW_LINE_SPACE)      
#define     MMIWIDGET_DCD_WIN_TEXT_RIGHT            225


#define     MMIWIDGET_DCD_WIN_LEFT_IDC_TOP                8
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_BOTTOM           26
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_LEFT               12
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_RIGHT              30
#define     MMIWIDGET_DCD_WIN_LEFT_IDC_RECT              {MMIWIDGET_DCD_WIN_LEFT_IDC_LEFT,MMIWIDGET_DCD_WIN_LEFT_IDC_TOP,MMIWIDGET_DCD_WIN_LEFT_IDC_RIGHT,MMIWIDGET_DCD_WIN_LEFT_IDC_BOTTOM}

#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_TOP                8
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_BOTTOM           26
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_LEFT               208
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_RIGHT              226
#define     MMIWIDGET_DCD_WIN_RIGHT_IDC_RECT              {MMIWIDGET_DCD_WIN_RIGHT_IDC_LEFT,MMIWIDGET_DCD_WIN_RIGHT_IDC_TOP,MMIWIDGET_DCD_WIN_RIGHT_IDC_RIGHT,MMIWIDGET_DCD_WIN_RIGHT_IDC_BOTTOM}

#define     MMIWIDGET_DCD_TAB_ANIM_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM_BOTTOM          25 
#define     MMIWIDGET_DCD_TAB_ANIM_LEFT               53
#define     MMIWIDGET_DCD_TAB_ANIM_RIGHT             73
#define     MMIWIDGET_DCD_TAB_ANIM_0_RECT              {MMIWIDGET_DCD_TAB_ANIM_LEFT,MMIWIDGET_DCD_TAB_ANIM_TOP,MMIWIDGET_DCD_TAB_ANIM_RIGHT,MMIWIDGET_DCD_TAB_ANIM_BOTTOM}

#define     MMIWIDGET_DCD_TAB_ANIM1_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM1_BOTTOM          25  
#define     MMIWIDGET_DCD_TAB_ANIM1_LEFT              90
#define     MMIWIDGET_DCD_TAB_ANIM1_RIGHT            110
#define     MMIWIDGET_DCD_TAB_ANIM_1_RECT              {MMIWIDGET_DCD_TAB_ANIM1_LEFT,MMIWIDGET_DCD_TAB_ANIM1_TOP,MMIWIDGET_DCD_TAB_ANIM1_RIGHT,MMIWIDGET_DCD_TAB_ANIM1_BOTTOM}


#define     MMIWIDGET_DCD_TAB_ANIM2_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM2_BOTTOM          25 
#define     MMIWIDGET_DCD_TAB_ANIM2_LEFT               127
#define     MMIWIDGET_DCD_TAB_ANIM2_RIGHT            147
#define     MMIWIDGET_DCD_TAB_ANIM_2_RECT              {MMIWIDGET_DCD_TAB_ANIM2_LEFT,MMIWIDGET_DCD_TAB_ANIM2_TOP,MMIWIDGET_DCD_TAB_ANIM2_RIGHT,MMIWIDGET_DCD_TAB_ANIM2_BOTTOM}

#define     MMIWIDGET_DCD_TAB_ANIM3_TOP                5
#define     MMIWIDGET_DCD_TAB_ANIM3_BOTTOM          25 
#define     MMIWIDGET_DCD_TAB_ANIM3_LEFT               164
#define     MMIWIDGET_DCD_TAB_ANIM3_RIGHT             184
#define     MMIWIDGET_DCD_TAB_ANIM_3_RECT              {MMIWIDGET_DCD_TAB_ANIM3_LEFT,MMIWIDGET_DCD_TAB_ANIM3_TOP,MMIWIDGET_DCD_TAB_ANIM3_RIGHT,MMIWIDGET_DCD_TAB_ANIM3_BOTTOM}

#define     MMIWIDGET_DCD_OPENMAINWIN_RECT		{15,36,225,90}


//***********************************************dual clock **********************************//
#define MMIWIDGET_DUAL_CLOCK_TIME1_TOP        15
#define MMIWIDGET_DUAL_CLOCK_TIME1_LEFT       0
#define MMIWIDGET_DUAL_CLOCK_TIME1_RIGHT      180
#define MMIWIDGET_DUAL_CLOCK_TIME1_BOTTOM     47
#define MMIWIDGET_DUAL_CLOCK_TIME1_RECT       {MMIWIDGET_DUAL_CLOCK_TIME1_LEFT, MMIWIDGET_DUAL_CLOCK_TIME1_TOP, MMIWIDGET_DUAL_CLOCK_TIME1_RIGHT, MMIWIDGET_DUAL_CLOCK_TIME1_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_CITY1_TOP        55
#define MMIWIDGET_DUAL_CLOCK_CITY1_LEFT       0
#define MMIWIDGET_DUAL_CLOCK_CITY1_RIGHT      180
#define MMIWIDGET_DUAL_CLOCK_CITY1_BOTTOM     67
#define MMIWIDGET_DUAL_CLOCK_CITY1_RECT       {MMIWIDGET_DUAL_CLOCK_CITY1_LEFT, MMIWIDGET_DUAL_CLOCK_CITY1_TOP, MMIWIDGET_DUAL_CLOCK_CITY1_RIGHT, MMIWIDGET_DUAL_CLOCK_CITY1_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_TIME2_TOP        90
#define MMIWIDGET_DUAL_CLOCK_TIME2_LEFT       0
#define MMIWIDGET_DUAL_CLOCK_TIME2_RIGHT      180
#define MMIWIDGET_DUAL_CLOCK_TIME2_BOTTOM     122
#define MMIWIDGET_DUAL_CLOCK_TIME2_RECT       {MMIWIDGET_DUAL_CLOCK_TIME2_LEFT, MMIWIDGET_DUAL_CLOCK_TIME2_TOP, MMIWIDGET_DUAL_CLOCK_TIME2_RIGHT, MMIWIDGET_DUAL_CLOCK_TIME2_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_CITY2_TOP        130
#define MMIWIDGET_DUAL_CLOCK_CITY2_LEFT       0
#define MMIWIDGET_DUAL_CLOCK_CITY2_RIGHT      180
#define MMIWIDGET_DUAL_CLOCK_CITY2_BOTTOM     142
#define MMIWIDGET_DUAL_CLOCK_CITY2_RECT       {MMIWIDGET_DUAL_CLOCK_CITY2_LEFT, MMIWIDGET_DUAL_CLOCK_CITY2_TOP, MMIWIDGET_DUAL_CLOCK_CITY2_RIGHT, MMIWIDGET_DUAL_CLOCK_CITY2_BOTTOM}

#define MMIWIDGET_DUAL_CLOCK_TOP              7
#define MMIWIDGET_DUAL_CLOCK_LEFT             8
#define MMIWIDGET_DUAL_CLOCK_RIGHT            168
#define MMIWIDGET_DUAL_CLOCK_BOTTOM           156
#define MMIWIDGET_DUAL_CLOCK_RECT             {MMIWIDGET_DUAL_CLOCK_LEFT, MMIWIDGET_DUAL_CLOCK_TOP, MMIWIDGET_DUAL_CLOCK_RIGHT, MMIWIDGET_DUAL_CLOCK_BOTTOM}

//***********************************************dual aclock **********************************//
#define MMIWIDGET_DUAL_ACLOCK_RECT_LEFT       6
#define MMIWIDGET_DUAL_ACLOCK_RECT_TOP        10
#define MMIWIDGET_DUAL_ACLOCK_RECT_RIGHT      231 
#define MMIWIDGET_DUAL_ACLOCK_RECT_BOTTOM     102
#define MMIWIDGET_DUAL_ACLOCK_RECT            {MMIWIDGET_DUAL_ACLOCK_RECT_LEFT, MMIWIDGET_DUAL_ACLOCK_RECT_TOP, MMIWIDGET_DUAL_ACLOCK_RECT_RIGHT, MMIWIDGET_DUAL_ACLOCK_RECT_BOTTOM}

//left aclock rect.
#define MMIWIDGET_LACLOCK_RECT_LEFT            11
#define MMIWIDGET_LACLOCK_RECT_TOP             0
#define MMIWIDGET_LACLOCK_RECT_RIGHT           120
#define MMIWIDGET_LACLOCK_RECT_BOTTOM          109
#define MMIWIDGET_LACLOCK_RECT                 {MMIWIDGET_LACLOCK_RECT_LEFT, MMIWIDGET_LACLOCK_RECT_TOP, MMIWIDGET_LACLOCK_RECT_RIGHT, MMIWIDGET_LACLOCK_RECT_BOTTOM}

//right aclock rect.
#define MMIWIDGET_RACLOCK_RECT_LEFT            119
#define MMIWIDGET_RACLOCK_RECT_TOP             0
#define MMIWIDGET_RACLOCK_RECT_RIGHT           218
#define MMIWIDGET_RACLOCK_RECT_BOTTOM          109
#define MMIWIDGET_RACLOCK_RECT                 {MMIWIDGET_RACLOCK_RECT_LEFT, MMIWIDGET_RACLOCK_RECT_TOP, MMIWIDGET_RACLOCK_RECT_RIGHT, MMIWIDGET_RACLOCK_RECT_BOTTOM}

//left aclock city rect.
#define MMIWIDGET_LACLOCK_CITY_RECT_LEFT       11
#define MMIWIDGET_LACLOCK_CITY_RECT_TOP        109
#define MMIWIDGET_LACLOCK_CITY_RECT_RIGHT      120
#define MMIWIDGET_LACLOCK_CITY_RECT_BOTTOM     121
#define MMIWIDGET_LACLOCK_CITY_RECT            {MMIWIDGET_LACLOCK_CITY_RECT_LEFT, MMIWIDGET_LACLOCK_CITY_RECT_TOP, MMIWIDGET_LACLOCK_CITY_RECT_RIGHT, MMIWIDGET_LACLOCK_CITY_RECT_BOTTOM}

//right aclock city rect.
#define MMIWIDGET_RACLOCK_CITY_RECT_LEFT       119
#define MMIWIDGET_RACLOCK_CITY_RECT_TOP        109
#define MMIWIDGET_RACLOCK_CITY_RECT_RIGHT      218
#define MMIWIDGET_RACLOCK_CITY_RECT_BOTTOM     121
#define MMIWIDGET_RACLOCK_CITY_RECT            {MMIWIDGET_RACLOCK_CITY_RECT_LEFT, MMIWIDGET_RACLOCK_CITY_RECT_TOP, MMIWIDGET_RACLOCK_CITY_RECT_RIGHT, MMIWIDGET_RACLOCK_CITY_RECT_BOTTOM}

#define MMIGRID_IDLE_SOFTKEY_HEIGHT            50
#define MMIGRID_IDLE_RECYCLE_HEIGHT            30

#if MMI_GRID_PAGE_NUM > 5
#define MMI_IDLE_GRID_THUMB_WIDTH              60
#define MMI_IDLE_GRID_THUMB_HEIGHT             80
#define MMI_IDLE_GRID_THUMB1_RECT              {40,  35,  99,  114}
#define MMI_IDLE_GRID_THUMB2_RECT              {139, 35,  198, 114}
#define MMI_IDLE_GRID_THUMB3_RECT              {15,  129, 74,  208}
#define MMI_IDLE_GRID_THUMB4_RECT              {90, 129, 149, 208}
#define MMI_IDLE_GRID_THUMB5_RECT              {165, 129, 224, 208}
#define MMI_IDLE_GRID_THUMB6_RECT              {40,  223,  99, 302}
#define MMI_IDLE_GRID_THUMB7_RECT              {139,  233, 198, 302}
#elif MMI_GRID_PAGE_NUM > 3
#define MMI_IDLE_GRID_THUMB_WIDTH              80
#define MMI_IDLE_GRID_THUMB_HEIGHT             96
#define MMI_IDLE_GRID_THUMB1_RECT              {32,  75,  103, 195}
#define MMI_IDLE_GRID_THUMB2_RECT              {135, 75,  206, 195}
#define MMI_IDLE_GRID_THUMB3_RECT              {6,   75,  77,  195}
#define MMI_IDLE_GRID_THUMB4_RECT              {83,  245, 154, 365}
#define MMI_IDLE_GRID_THUMB5_RECT              {160, 245, 232, 365}
#else
#define MMI_IDLE_GRID_THUMB_WIDTH              96
#define MMI_IDLE_GRID_THUMB_HEIGHT             128
#define MMI_IDLE_GRID_THUMB1_RECT              {16,  30,  111, 240}
#define MMI_IDLE_GRID_THUMB2_RECT              {127, 30,  222, 240}
#define MMI_IDLE_GRID_THUMB3_RECT              {74,  255, 169, 465}
#endif

