#ifdef MMIWIDGET_SUPPORT
//bar
RES_ADD_IMG(IMAGE_WIDGET_BAR_BG,"\\MMI_RES_##\\IMAG\\Bar\\IMAGE_WIDGET_BAR_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_H_BAR_BG,"\\MMI_RES_##\\IMAG\\Bar\\IMAGE_WIDGET_H_BAR_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_BAR_BUTTON_CLOSE_OFF,"\\MMI_RES_##\\IMAG\\Bar\\IMAGE_WIDGET_BAR_BUTTON_CLOSE_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_BAR_BUTTON_CLOSE_ON,"\\MMI_RES_##\\IMAG\\Bar\\IMAGE_WIDGET_BAR_BUTTON_CLOSE_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_BAR_BUTTON_OPEN_OFF,"\\MMI_RES_##\\IMAG\\Bar\\IMAGE_WIDGET_BAR_BUTTON_OPEN_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_BAR_BUTTON_OPEN_ON,"\\MMI_RES_##\\IMAG\\Bar\\IMAGE_WIDGET_BAR_BUTTON_OPEN_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//digital clock
#ifdef MMI_WIDGET_DUAL_CLOCK
RES_ADD_IMG(IMAGE_WIDGET_DIGITALCLOCK,"\\MMI_RES_##\\IMAG\\Digitalclock\\IMAGE_WIDGET_DIGITALCLOCK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DIGITALCLOCK_SHORTCUT,"\\MMI_RES_##\\IMAG\\Digitalclock\\IMAGE_WIDGET_DIGITALCLOCK_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef MMI_WIDGET_DUAL_CLOCK
RES_ADD_IMG(IMAGE_WIDGET_DUALCLOCK_BG,"\\MMI_RES_##\\IMAG\\dual_clock\\IMAGE_WIDGET_DUALCLOCK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_CLOCK_SHORTCUT,"\\MMI_RES_##\\IMAG\\dual_clock\\IMAGE_WIDGET_DUALCLOCK_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SAM_THEME
RES_ADD_IMG(IMAGE_WIDGET_SAM_DUALCLOCK_BG,"\\MMI_RES_##\\IMAG\\sam_dual_clock\\IMAGE_WIDGET_DUALCLOCK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

//mp3
#ifdef MMIWIDGET_SUPPORT 
RES_ADD_IMG(IMAGE_WIDGET_MP3_CHANGE_PANEL_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_CHANGE_PANEL_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_CHANGE_PANEL_ON,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_CHANGE_PANEL_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_VOL,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_VOL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_VOL_SILENCE,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_VOL_SILENCE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_VOL_ADD_ON,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_VOL_ADD_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_VOL_ADD_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_VOL_ADD_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_VOL_DEC_ON,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_VOL_DEC_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_VOL_DEC_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_VOL_DEC_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_ENTER_PLAYER_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_ENTER_PLAYER_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_ENTER_PLAYER_ON,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_ENTER_PLAYER_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMI_GRID_MP3
#ifdef BAR_PHONE_WIDGET

RES_ADD_IMG(IMAGE_WIDGET_MP3_SHORTCUT,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)

#if !defined MMIWIDGET_MP3_SE
RES_ADD_IMG(IMAGE_WIDGET_MP3_BG,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_NEXT_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_NEXT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_NEXT_ON,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_NEXT_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PLAY_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_PLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PLAY_ON,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_PLAY_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PAUSE_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_PAUSE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PAUSE_ON,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_PAUSE_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PREV_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_PREV.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PREV_ON,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_PREV_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SCROLLBAR_BOLL,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MUSIC_PROGRESS.png",IMG_CMP_PNG_ARGB_RLE,0)

#else   //defined MMIWIDGET_MP3_SE IMAGE_WIDGET_MP3_BG IMAGE_WIDGET_MP3_SE_CI_COVER
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_COVERBG_FRAME,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_CI_COVER_FRAME.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_COVERBG,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_CI_COVER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_BG,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_CI_COVER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_PIB,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_PIB.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_PIF_PAUSE,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_PIF_PAUSE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_PIF_PLAY,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_PIF_PLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_POBD,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_POBD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_POBU,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_POBU.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_POFD,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_POFD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_POFU,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_POFU.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_SLIDER_BG,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_SLIDER_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_SLIDER_LIGHT,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_SLIDER_LIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_SLIDER_POINT,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_SLIDER_POINT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_LOADING_BG,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_LOADING_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_LOADING_ROT,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_LOADING_ROT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SE_NOTE,"\\MMI_RES_##\\IMAG\\Mp3\\barphone\\IMAGE_WIDGET_MP3_SE_NOTE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#else
RES_ADD_IMG(IMAGE_WIDGET_MP3_BG,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_NEXT_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_NEXT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_NEXT_ON,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_NEXT_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PLAY_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_PLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PLAY_ON,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_PLAY_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PAUSE_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_PAUSE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PAUSE_ON,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_PAUSE_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PREV_OFF,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_PREV.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_PREV_ON,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_PREV_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SHORTCUT,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MP3_SCROLLBAR_BOLL,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MUSIC_PROGRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_MP3_VOL_PROGRESS_BG,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_VOL_PROGRESS_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_MP3_VOL_PROGRESS_FILL,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_VOL_PROGRESS_FILL.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
//RES_ADD_IMG(IMAGE_WIDGET_MP3_COVERBG,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_COVERBG.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_MP3_PANEL_BG,"\\MMI_RES_##\\IMAG\\Mp3\\IMAGE_WIDGET_MP3_PANEL_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

#ifdef MMIWIDGET_SUPPORT
//PB
RES_ADD_IMG(IMAGE_WIDGET_PB_LIST_ICON,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_LIST_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_ANIM_DEFAULT_0,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_ANIM_DEFAULT_0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_ANIM_EMPTY_0,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_ANIM_EMPTY_0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_ANIM_DEFAULT,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_ANIM_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_ANIM_EMPTY,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_ANIM_EMPTY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_BG,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_PB_DEFAULT_FACE,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_DEFAULT_FACE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_DIAL_OFF,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_DIAL_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_DIAL_ON,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_DIAL_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_SENDSMS_OFF,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_SENDSMS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_SENDSMS_ON,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_SENDSMS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_SHORTCUT,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//shortcut menu 
#ifdef MMI_WIDGET_SHORTCUT_MENU
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_MENU_BG,"\\MMI_RES_##\\IMAG\\Shortcut_menu\\IMAGE_WIDGET_SHORTCUT_MENU_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_MENU_SHORTCUT,"\\MMI_RES_##\\IMAG\\Shortcut_menu\\IMAGE_WIDGET_SHORTCUT_MENU_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_MENU_LAST_PAGE_ON,"\\MMI_RES_##\\IMAG\\Shortcut_menu\\IMAGE_WIDGET_SHORTCUT_MENU_LAST_PAGE_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_MENU_LAST_PAGE_OFF,"\\MMI_RES_##\\IMAG\\Shortcut_menu\\IMAGE_WIDGET_SHORTCUT_MENU_LAST_PAGE_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_MENU_NEXT_PAGE_ON,"\\MMI_RES_##\\IMAG\\Shortcut_menu\\IMAGE_WIDGET_SHORTCUT_MENU_NEXT_PAGE_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_MENU_NEXT_PAGE_OFF,"\\MMI_RES_##\\IMAG\\Shortcut_menu\\IMAGE_WIDGET_SHORTCUT_MENU_NEXT_PAGE_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

//calendar 
#ifdef MMI_GRID_CALENDAR
RES_ADD_IMG(IMAGE_WIDGET_CALENDAR_BG,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_WIDGET_CALENDAR_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_CALENDAR_SHORTCUT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_WIDGET_CALENDAR_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_CALENDAR_SCHE,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_WIDGET_CALENDAR_SCHE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif


//memo 
#ifdef MMI_WIDGET_MEMO 
//RES_ADD_IMG(IMAGE_WIDGET_MEMO_BG,"\\MMI_RES_##\\IMAG\\Memo\\IMAGE_WIDGET_MEMO_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_MEMO_SHORTCUT,"\\MMI_RES_##\\IMAG\\Memo\\IMAGE_WIDGET_MEMO_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NOTE_BG,"\\MMI_RES_##\\IMAG\\Memo\\IMAGE_WIDGET_NOTE_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_GRID_IDLE_SUPPORT
RES_ADD_IMG(IMAGE_WIDGET_MEMO_EDIT_ICON,"\\MMI_RES_##\\IMAG\\Memo\\IMAGE_WIDGET_MEMO_EDIT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
//network name
#ifdef MMI_WIDGET_NETWORK
//RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NAME_BG,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NAME_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NAME_BG_SINGLE,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NAME_BG_SINGLE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NAME_BG_DUAL,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NAME_BG_DUAL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NAME_BG_TRI,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NAME_BG_TRI.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NAME_BG_QUAD,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NAME_BG_QUAD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NAME_SHORTCUT,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NAME_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_GRID_IDLE_SUPPORT
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NUM_1,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NUM_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NUM_2,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NUM_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NUM_3,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NUM_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_NUM_4,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_NUM_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_YELLOW,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_GRAY,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined MMI_MULTI_SIM_SYS_SINGLE
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_BG,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_1SIM_NETWORK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#elif defined MMI_MULTI_SIM_SYS_DUAL
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_BG,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_2SIM_NETWORK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_WIDGET_NETWORK_BG,"\\MMI_RES_##\\IMAG\\Network_name\\IMAGE_WIDGET_NETWORK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#endif

//custom word
#ifdef MMIWIDGET_SUPPORT
RES_ADD_IMG(IMAGE_WIDGET_CUSTOM_WORD_BG,"\\MMI_RES_##\\IMAG\\Custom_word\\IMAGE_WIDGET_CUSTOM_WORD_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_CUSTOM_WORD_SHORTCUT,"\\MMI_RES_##\\IMAG\\Custom_word\\IMAGE_WIDGET_CUSTOM_WORD_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)

//new sms
RES_ADD_IMG(IMAGE_WIDGET_NEWSMS_BG,"\\MMI_RES_##\\IMAG\\Newsms\\IMAGE_WIDGET_NEWSMS_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NEWSMS_SHORTCUT,"\\MMI_RES_##\\IMAG\\Newsms\\IMAGE_WIDGET_NEWSMS_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_NEWSMS_LEFT_BUTTON_ON,"\\MMI_RES_##\\IMAG\\NEWSMS\\IMAGE_WIDGET_NEWSMS_LEFT_BUTTON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NEWSMS_LEFT_BUTTON_OFF,"\\MMI_RES_##\\IMAG\\NEWSMS\\IMAGE_WIDGET_NEWSMS_LEFT_BUTTON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NEWSMS_RIGHT_BUTTON_ON,"\\MMI_RES_##\\IMAG\\NEWSMS\\IMAGE_WIDGET_NEWSMS_RIGHT_BUTTON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NEWSMS_RIGHT_BUTTON_OFF,"\\MMI_RES_##\\IMAG\\NEWSMS\\IMAGE_WIDGET_NEWSMS_RIGHT_BUTTON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

//CALL LOG
RES_ADD_IMG(IMAGE_WIDGET_CALLLOG_BG,"\\MMI_RES_##\\IMAG\\CALLLOG\\IMAGE_WIDGET_CALLLOG_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_CALLLOG_SHORTCUT,"\\MMI_RES_##\\IMAG\\CALLLOG\\IMAGE_WIDGET_CALLLOG_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_CALLLOG_LEFT_BUTTON_ON,"\\MMI_RES_##\\IMAG\\CALLLOG\\IMAGE_WIDGET_CALLLOG_LEFT_BUTTON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_CALLLOG_LEFT_BUTTON_OFF,"\\MMI_RES_##\\IMAG\\CALLLOG\\IMAGE_WIDGET_CALLLOG_LEFT_BUTTON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_CALLLOG_RIGHT_BUTTON_ON,"\\MMI_RES_##\\IMAG\\CALLLOG\\IMAGE_WIDGET_CALLLOG_RIGHT_BUTTON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_CALLLOG_RIGHT_BUTTON_OFF,"\\MMI_RES_##\\IMAG\\CALLLOG\\IMAGE_WIDGET_CALLLOG_RIGHT_BUTTON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

#endif

//FM 
#ifdef MMI_WIDGET_FM
#ifndef BAR_PHONE_WIDGET 
RES_ADD_IMG(IMAGE_WIDGET_FM_SHORTCUT,"\\MMI_RES_##\\IMAG\\FM\\IMAGE_WIDGET_FM_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_BG,"\\MMI_RES_##\\IMAG\\FM\\IMAGE_WIDGET_FM_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_PLAY_OFF,"\\MMI_RES_##\\IMAG\\FM\\IMAGE_WIDGET_FM_PLAY_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_PLAY_ON,"\\MMI_RES_##\\IMAG\\FM\\IMAGE_WIDGET_FM_PLAY_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_PAUSE_OFF,"\\MMI_RES_##\\IMAG\\FM\\IMAGE_WIDGET_FM_PAUSE_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_PAUSE_ON,"\\MMI_RES_##\\IMAG\\FM\\IMAGE_WIDGET_FM_PAUSE_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_WIDGET_FM_PREV_ON,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_PREV_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_PREV_OFF,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_PREV.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_NEXT_ON,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_NEXT_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_NEXT_OFF,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_NEXT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_PLAY,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_PLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_PAUSE,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_PAUSE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_BG,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_SHORTCUT,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_PLAY_ON,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_PLAY_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_FM_PAUSE_ON,"\\MMI_RES_##\\IMAG\\FM\\barphone\\IMAGE_WIDGET_FM_PAUSE_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

//ALARM
#ifdef MMIWIDGET_SUPPORT
RES_ADD_IMG(IMAGE_WIDGET_ALARM_LEFT,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_LEFT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_LEFT_GRAY,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_LEFT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_RIGHT,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_RIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_RIGHT_GRAY,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_RIGHT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_1,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_2,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_3,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_4,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_5,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_6,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_OFF_FOCUS,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_OFF_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_ON_FOCUS,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_ON_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef MMI_WIDGET_ALARM
RES_ADD_IMG(IMAGE_WIDGET_ALARM_SHORTCUT,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_BG,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_ALARM_OFF_BG,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_OFF_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_ALARM_ON_BG,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_ON_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_OFF,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_ON,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_ALARM_SLIDER,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_SLIDER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_ALARM,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_ALARM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_LINE,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_LINE.png",IMG_CMP_PNG_ARGB_RLE,0)

#if 0   //def MMI_GRID_IDLE_SUPPORT
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER0,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER1,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER2,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER3,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER4,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER5,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER6,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER7,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER7.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER8,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER8.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_NUMBER9,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_NUMBER9.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_DOT,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_DOT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ALARM_SELECT_BG,"\\MMI_RES_##\\IMAG\\ALARM\\IMAGE_WIDGET_ALARM_SELECT_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

//SHORTCUT SET
#ifdef MMI_WIDGET_SHORTCUT_SET
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_BG,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_ON,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_OFF,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_SHORTCUT,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_VOL,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_VOL.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef WIFI_SUPPORT
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_WIFI,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_WIFI.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_BLUETOOTH,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_BLUETOOTH.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_REDKEYLOCK,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_REDKEYLOCK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_FLYMODE,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_FLYMODE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_BACKLIGHT_1,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_BACKLIGHT_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_BACKLIGHT_2,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_BACKLIGHT_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_BACKLIGHT_3,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_BACKLIGHT_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_EARPHONE,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_EARPHONE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SHORTCUT_SET_BT_EARPHONE,"\\MMI_RES_##\\IMAG\\Shortcut_set\\IMAGE_WIDGET_SHORTCUT_SET_BT_EARPHONE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMI_SAM_THEME
#ifdef MMI_POWER_SAVING_MODE_SUPPORT
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BG,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BG.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef WIFI_SUPPORT
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_WIFI_ON,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_WIFI_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_WIFI_OFF,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_WIFI_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BAT_ON,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BAT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BAT_OFF,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BAT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef BLUETOOTH_SUPPORT
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BT_ON,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BT_OFF,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BGDATA_ON,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BGDATA_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BGDATA_OFF,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BGDATA_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_SS_ON,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_SS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_SS_OFF,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_SS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BRIGHT_1,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BRIGHT_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BRIGHT_2,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BRIGHT_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BRIGHT_3,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BRIGHT_3.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BL_ON,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BL_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_BL_OFF,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_BL_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_ALERT_ON,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_ALERT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_ALERT_OFF,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_ALERT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_SET_ON,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_SET_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_SET_OFF,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_SET_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_ITEM_ON,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_ITEM_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PWRSAV_ITEM_OFF,"\\MMI_RES_##\\IMAG\\sam_pwr_saving\\IMAGE_WIDGET_PWRSAV_ITEM_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

//DCD image
#ifdef MMI_ENABLE_DCD
RES_ADD_IMG(IMAGE_WIDGET_DCD_BG,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_SHORTCUT,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_RIGHT,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_RIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_RIGHT_GRAY,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_RIGHT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_RIGHT_SELECT,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_RIGHT_SELECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_LEFT,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_LEFT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_LEFT_GRAY,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_LEFT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_LEFT_SELECT,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_LEFT_SELECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_TITLE_DEFAULT,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_TITLE_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_DEFAULT,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DCD_TITLE_FOCUS,"\\MMI_RES_##\\IMAG\\Dcd\\IMAGE_WIDGET_DCD_TITLE_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMIWIDGET_SUPPORT
//elve shortcut icon.
RES_ADD_IMG(IMAGE_WIDGET_ELVE_SHORTCUT,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)

//elve normal pic.
RES_ADD_IMG(IMAGE_WIDGET_ELVE_NOR_0,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_NORMAL_0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_NOR_1,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_NORMAL_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_NOR_2,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_NORMAL_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_NOR_3,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_NORMAL_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_NOR_4,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_NORMAL_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_NOR_5,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_NORMAL_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_NOR_6,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_NORMAL_6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_NOR_7,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_NORMAL_7.png",IMG_CMP_PNG_ARGB_RLE,0)

//elve moveing pic.
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_0,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_1,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_2,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_3,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_4,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_5,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_6,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_7,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_7.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_8,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_8.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_9,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_9.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_10,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_10.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_11,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_11.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_12,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_12.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_13,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_13.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_14,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_14.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_15,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_15.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_16,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_16.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_17,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_17.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_18,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_18.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_19,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_19.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_20,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_20.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_21,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_21.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_22,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_22.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_23,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_23.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_24,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_24.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_25,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_25.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_26,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_26.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_27,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_27.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_28,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_28.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_29,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_29.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_30,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_30.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_MOV_31,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_MOVING_31.png",IMG_CMP_PNG_ARGB_RLE,0)

//elve click down pic.
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_0,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_1,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_2,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_3,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_4,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_5,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_6,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_7,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_7.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_8,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_8.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_9,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_9.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_10,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_10.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_11,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_11.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ELVE_CLK_12,"\\MMI_RES_##\\IMAG\\ELVE\\IMAGE_WIDGET_ELVE_CLICK_12.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//search
#ifdef MMI_WIDGET_SEARCH
RES_ADD_IMG(IMAGE_WIDGET_SEARCH_BG,"\\MMI_RES_##\\IMAG\\Search\\IMAGE_WIDGET_SEARCH_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SEARCH_SHORTCUT,"\\MMI_RES_##\\IMAG\\Search\\IMAGE_WIDGET_SEARCH_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SEARCH_HIGHLIGHT,"\\MMI_RES_##\\IMAG\\Search\\IMAGE_WIDGET_SEARCH_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SAM_THEME
RES_ADD_IMG(IMAGE_WIDGET_SAM_SEARCH_BG,"\\MMI_RES_##\\IMAG\\sam_search\\IMAGE_WIDGET_SEARCH_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SAM_SEARCH_ICON,"\\MMI_RES_##\\IMAG\\sam_search\\IMAGE_WIDGET_SEARCH_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SAM_SEARCH_HL,"\\MMI_RES_##\\IMAG\\sam_search\\IMAGE_WIDGET_SEARCH_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

//dual aclock
#ifdef MMI_WIDGET_DUAL_ACLOCK
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_BG,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_SHORTCUT,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK1,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_HOUR1,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_HOUR_HAND1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_MIN1,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_MIN_HAND1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_SEC1,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_SEC_HAND1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_CENTER1,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_CENTER1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK2,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_HOUR2,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_HOUR_HAND2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_MIN2,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_MIN_HAND2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_SEC2,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_SEC_HAND2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_CENTER2,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_CENTER2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_DUAL_ACLOCK_TIME_BG,"\\MMI_RES_##\\IMAG\\dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_TIME_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SAM_THEME
RES_ADD_IMG(IMAGE_WIDGET_SAM_DUAL_ACLOCK_BG,"\\MMI_RES_##\\IMAG\\sam_dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SAM_DUAL_ACLOCK_HOUR1,"\\MMI_RES_##\\IMAG\\sam_dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_HOUR_HAND.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SAM_DUAL_ACLOCK_MIN1,"\\MMI_RES_##\\IMAG\\sam_dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_MIN_HAND.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SAM_DUAL_ACLOCK_SEC1,"\\MMI_RES_##\\IMAG\\sam_dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_SEC_HAND.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SAM_DUAL_ACLOCK_CENTER1,"\\MMI_RES_##\\IMAG\\sam_dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK_CENTER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SAM_DUAL_ACLOCK1,"\\MMI_RES_##\\IMAG\\sam_dual_aclock\\IMAGE_WIDGET_DUAL_ACLOCK.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

#ifdef WEATHER_SUPPORT
#if (defined MMIWIDGET_SUPPORT) || (defined MMI_GRID_IDLE_SUPPORT)
//weather
#ifdef MMI_WIDGET_WEATHER2
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_TWO_HIGHLIGHT,"\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_HIGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_TWO_SHORTCUT,"\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_TWO_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_TWO_BG,"\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_TWO_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_NO_B,"\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_NO_B.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_NO_S,"\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_NO_S.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_CHANGE_B, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_CHANGE_B.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_CHANGE_S, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_CHANGE_S.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_CLEAR_B, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_CLEAR_B.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_CLEAR_S, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_CLEAR_S.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_CLOUDY_B, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_CLOUDY_B.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_CLOUDY_S, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_CLOUDY_S.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_FOG_B, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_FOG_B.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_FOG_S, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_FOG_S.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ICE_B, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_ICE_B.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ICE_S, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_ICE_S.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_RAIN_B, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_RAIN_B.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_RAIN_S, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_RAIN_S.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SNOW_B, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_SNOW_B.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SNOW_S, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_SNOW_S.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_THUNDER_B, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_THUNDER_B.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_THUNDER_S, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_THUNDER_S.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ADD_B, "\\MMI_RES_##\\IMAG\\Weather2\\IMAGE_WIDGET_WEATHER_ADD_B.png", IMG_CMP_PNG_ARGB_RLE, 0)
#endif

#ifdef BAR_PHONE_WIDGET
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SHORTCUT,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_BG,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_BG.png",IMG_CMP_PNG_ARGB_RLE,0)


#ifdef MMIWIDGET_WEATHER_SE
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_BG,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_BG_SE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_BIG_TEMPERATURE,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_BIG_TEMPERATURE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_CITY_CHANGE,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_CITY_CHANGE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_DIVIDE_BAR,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_DEVIDE_BAR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_FIRST_DAY,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_FIRST_DAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_SECOND_DAY,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_SECOND_DAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_THIRD_DAY,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_THIRD_DAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_GLOW,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_GLOW.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_DOWN_TEMPERATURE,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_DOWN_TEMPERATURE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_UP_TEMPERATURE,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_UP_TEMPERATURE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_SUN,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_SUN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_SUN_BG,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_SUN_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_WEATHER_CHANGE,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_WEATHER_CHANGE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_CLOUD1,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_CLOUD1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_CLOUD2,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_CLOUD2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_CLOUD_LEFT,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_CLOUD_LEFT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_CLOUD_RIGHT,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_CLOUD_RIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_FOG,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_FOG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_LIGHT1,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_LIGHT1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_LIGHT2,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_LIGHT2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_NONE,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_NA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_RAIN,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_RAIN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_SNOW_BIG,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_SNOW_BIG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SE_SNOW_SMALL,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_SNOW_SMALL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_FORCAST_BG,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_FORCAST_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_CITY_CHANGE_BG,"\\MMI_RES_##\\IMAG\\Weather\\barphone\\IMAGE_WIDGET_WEATHER_CITY_CHANGE_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#else
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_SHORTCUT,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_WEATHER_CLOUD,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_CLOUD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_BG,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

RES_ADD_IMG(IMAGE_WIDGET_WEATHER_0,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_1,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_2,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_3,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_4,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_5,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_6,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_7,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_7.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_8,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_8.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_9,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_9.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_COLON_W,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_COLON_W.png",IMG_CMP_PNG_ARGB_RLE,0)

//RES_ADD_IMG(IMAGE_WIDGET_WEATHER_BG_EMPTY,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_BG_EMPTY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B0,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B1,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B2,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B3,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B4,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B5,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B6,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B7,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B7.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B8,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B8.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_B9,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_B9.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_COLON_B,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_COLON_B.png",IMG_CMP_PNG_ARGB_RLE,0)

//RES_ADD_IMG(IMAGE_WIDGET_WEATHER_BT_PRESS_S,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_BT_PRESS_S.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_WEATHER_BT_PRESS_L,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_BT_PRESS_L.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_HIGHLIGHT_S,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_HIGHLIGHT_S.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_HIGHLIGHT_L,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_HIGHLIGHT_L.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef MMIWIDGET_WEATHER_ANIM
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_SUNNY1,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_SUNNY1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_SUNNY2,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_SUNNY2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_SUNNY3,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_SUNNY3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_SUNNY4,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_SUNNY4.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_MOSTLY_CLOUDY1,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_MOSTLY_CLOUDY1.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_SNOW1,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_SNOW1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_SNOW2,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_SNOW2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_SNOW3,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_SNOW3.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_CLOUDY1,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_CLOUDY1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_CLOUDY2,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_CLOUDY2.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_RAIN1,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_RAIN1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_RAIN2,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_RAIN2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_RAIN3,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_RAIN3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_RAIN4,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_RAIN4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_RAIN5,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_RAIN5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_ANIM_RAIN6,"\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_ANIM_RAIN6.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef PDA_WEATHER_TIME_SE
RES_ADD_IMG(IMAGE_WIDGET_WEATHER_TIME_BG,     "\\MMI_RES_##\\IMAG\\Weather\\IMAGE_WIDGET_WEATHER_TIME_BG.png",     IMG_CMP_PNG_ARGB_RLE,0)
#endif //PDA_WEATHER_TIME_SE

#endif //gird || widget
#endif //wearther

#ifdef MMI_WIDGET_ACLOCK
//aclock
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_SHORTCUT,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_ACLOCK_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_BG1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_HOUR,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_HOUR1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_MIN,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_M1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_SEC_HAND,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_S1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_CENTER,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_POINT1.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMIWIDGET_ACLOCK_SE
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_SURFACE_UP,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_SURFACE_UP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_CAP,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_CAP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_HOUR,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_HOUR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_MIN,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_MIN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_SECOND,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_SECOND.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_SHADOW_HOUR,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_SHADOW_HOUR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_SHADOW_MIN,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_SHADOW_MIN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_SHADOW_SENCOND,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_SHADOW_SENCOND.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_SURFACE_DOWN,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_SURFACE_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)
#if 0
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_ARROW_UP,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_ARROW_UP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MMIWIDGET_ACLOCK_SE_ARROW_DOWN,"\\MMI_RES_##\\IMAG\\AClock\\barphone\\MMIWIDGET_ACLOCK_SE_ARROW_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#else

RES_ADD_IMG(IMAGE_WIDGET_ACLOCK2,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_BG2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_HOUR2,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_HOUR2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_MIN2,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_M2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_SEC_HAND2,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_S2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_CENTER2,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_POINT2.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_ACLOCK3,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_BG3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_HOUR3,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_HOUR3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_MIN3,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_M3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_SEC_HAND3,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_S3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_CENTER3,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_CLOCK_POINT3.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_DAY,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_ACLOCK_DAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_ACLOCK_NIGHT,"\\MMI_RES_##\\IMAG\\Aclock\\IMAGE_WIDGET_ACLOCK_NIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif


#ifdef MMI_GRID_IDLE_SUPPORT


#ifdef MMI_GRID_CONTACT
//grid pb.
RES_ADD_IMG(IMAGE_GRID_PB_BG,"\\MMI_RES_##\\IMAG\\grid_pb\\IMG_GRID_PB_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PB_ADD,"\\MMI_RES_##\\IMAG\\grid_pb\\IMG_GRID_PB_ADD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PB_ADD_HL,"\\MMI_RES_##\\IMAG\\grid_pb\\IMG_GRID_PB_ADD_HL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PB_NAME,"\\MMI_RES_##\\IMAG\\grid_pb\\IMG_GRID_PB_NAME.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PB_SMS,"\\MMI_RES_##\\IMAG\\grid_pb\\IMG_GRID_PB_SMS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PB_SMS_HL,"\\MMI_RES_##\\IMAG\\grid_pb\\IMG_GRID_PB_SMS_HL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PB_CALL,"\\MMI_RES_##\\IMAG\\grid_pb\\IMG_GRID_PB_CALL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PB_CALL_HL,"\\MMI_RES_##\\IMAG\\grid_pb\\IMG_GRID_PB_CALL_HL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_PB_SHORTCUT,"\\MMI_RES_##\\IMAG\\Pb\\IMAGE_WIDGET_PB_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//image viewer.
#ifdef MMI_GRID_IMG_VIEWER

RES_ADD_IMG(IMAGE_GRID_IMGVIEWER_BG,"\\MMI_RES_##\\IMAG\\ImageViewer\\IMAGE_WIDGET_IMGVIEWER_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_IMGVIEWER_NEXT,"\\MMI_RES_##\\IMAG\\ImageViewer\\IMAGE_WIDGET_IMGVIEWER_NEXT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_IMGVIEWER_ADD,"\\MMI_RES_##\\IMAG\\ImageViewer\\IMAGE_WIDGET_IMGVIEWER_ADD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_IMGVIEWER_SHORTCUT,"\\MMI_RES_##\\IMAG\\ImageViewer\\IMAGE_WIDGET_IMGVIEWER_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SAM_THEME
RES_ADD_IMG(IMAGE_GRID_SAM_IMGVIEWER_BG,"\\MMI_RES_##\\IMAG\\sam_image\\IMAGE_WIDGET_IMGVIEWER_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#ifdef MMI_WIDGET_NETSEARCH
//net search.
RES_ADD_IMG(IMAGE_WIDGET_NETSEARCH_BG,"\\MMI_RES_##\\IMAG\\NetSearch\\IMAGE_WIDGET_NETSEARCH_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETSEARCH_OFF,"\\MMI_RES_##\\IMAG\\NetSearch\\IMAGE_WIDGET_NETSEARCH_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETSEARCH_ON,"\\MMI_RES_##\\IMAG\\NetSearch\\IMAGE_WIDGET_NETSEARCH_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_NETSEARCH_SHORTCUT,"\\MMI_RES_##\\IMAG\\NetSearch\\IMAGE_WIDGET_NETSEARCH_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//counted time.
#ifdef MMI_GRID_COUNTEDTIME
RES_ADD_IMG(IMAGE_WIDGET_COUNTEDTIME__SHORTCUT,"\\MMI_RES_##\\IMAG\\Countedtime\\IMAGE_WIDGET_COUNTEDTIME__SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_COUNTEDTIME_BG,"\\MMI_RES_##\\IMAG\\Countedtime\\IMAGE_WIDGET_COUNTEDTIME_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_COUNTEDTIME_BUTTON_OFF,"\\MMI_RES_##\\IMAG\\Countedtime\\IMAGE_WIDGET_COUNTEDTIME_BUTTON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_COUNTEDTIME_BUTTON_ON,"\\MMI_RES_##\\IMAG\\Countedtime\\IMAGE_WIDGET_COUNTEDTIME_BUTTON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//speed dial.
#ifdef MMI_WIDGET_SPEED_DIAL
RES_ADD_IMG(IMAGE_WIDGET_SPEED_DIAL_SHORTCUT,"\\MMI_RES_##\\IMAG\\SpeedDial\\barphone\\IMAGE_WIDGET_SPEED_DIAL_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SPEED_DIAL_BG,"\\MMI_RES_##\\IMAG\\SpeedDial\\barphone\\IMAGE_WIDGET_SPEED_DIAL_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_SPEED_DIAL_SE,"\\MMI_RES_##\\IMAG\\SpeedDial\\IMAGE_WIDGET_SPEED_DIAL_SE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WIDGET_SPEED_DIAL_BUTTON_ON,"\\MMI_RES_##\\IMAG\\SpeedDial\\IMAGE_WIDGET_SPEED_DIAL_BUTTON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif //speed dial


//grid idle softkey.
RES_ADD_IMG(IMAGE_IDLE_RECYLE_OPEN,"\\MMI_RES_##\\IMAG\\grid_softkey\\idle_recycle_open.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_IDLE_DELETE,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_IDLE_DELETE.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef MMI_SAM_THEME
//grid idle softkey.
RES_ADD_IMG(IMAGE_SAM_IDLE_RECYLE_NORMAL,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_SAM_RECYCLE_NOR.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
#endif

#ifdef MAINLCD_SIZE_320X480
#define IMAGE_IDLE_SOFTKEY_BG IMAGE_NULL
#define IMAGE_IDLE_SOFTKEY_BG_HIGHLIGHT IMAGE_NULL
#define IMAGE_IDLE_RECYLE_NORMAL IMAGE_NULL
#else
RES_ADD_IMG(IMAGE_IDLE_RECYLE_NORMAL,"\\MMI_RES_##\\IMAG\\grid_softkey\\idle_recycle_normal.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_IDLE_SOFTKEY_BG,"\\MMI_RES_##\\IMAG\\grid_softkey\\idle_softkey_bg.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_IDLE_SOFTKEY_BG_HIGHLIGHT,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_IDLE_BG_HIGHLIGHT.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
#endif
#ifdef  MAIN_MENU_48X48
RES_ADD_IMG(IMAGE_IDLE_SOFTKEY_MENU,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_IDLE_MENU.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_IDLE_SOFTKEY_MENU,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_IDLE_MENU_BIG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_IDLE_WIDGETS_ADD,"\\MMI_RES_##\\IMAG\\menu\\idle_widgets_add.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_IDLE_SHORTCUTS_ADD,"\\MMI_RES_##\\IMAG\\menu\\idle_shortcuts_add.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_IDLE_GAME_WALLPAPER_SET,"\\MMI_RES_##\\IMAG\\menu\\idle_game_wallpaper_set.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_IDLE_FILM_WALLPAPER_SET,"\\MMI_RES_##\\IMAG\\menu\\idle_film_wallpaper_set.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_GRID_PAGE_IDX,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_GRID_PAGE_IDX.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PAGE_IDX_HL_1,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_GRID_PAGE_IDX_HL_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PAGE_IDX_HL_2,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_GRID_PAGE_IDX_HL_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PAGE_IDX_HL_3,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_GRID_PAGE_IDX_HL_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PAGE_IDX_HL_4,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_GRID_PAGE_IDX_HL_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PAGE_IDX_HL_5,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_GRID_PAGE_IDX_HL_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PAGE_IDX_HL_6,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_GRID_PAGE_IDX_HL_6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GRID_PAGE_IDX_HL_7,"\\MMI_RES_##\\IMAG\\grid_softkey\\IMAGE_GRID_PAGE_IDX_HL_7.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef QBTHEME_SUPPORT
RES_ADD_IMG(IMAGE_QBTHEME_DOCKBAR_ADD_ICON,"\\MMI_RES_##\\IMAG\\QBTHEME\\IMAGE_QBTHEME_DOCKBAR_ADD_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_QBTHEME_DOCKBAR_DELETE_ICON,"\\MMI_RES_##\\IMAG\\QBTHEME\\IMAGE_QBTHEME_DOCKBAR_DELETE_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)

//RES_ADD_STRING(TXT_WIDGET_SHORTCUT,"Shortcut")      //replaced by local TXT_WIDGET_ADD_SHORT
RES_ADD_STRING(TXT_WIDGET_WIDGET,"Widget")
RES_ADD_STRING(TXT_QB_NO_MORE_ROOM_ON_WIDGET_SCREEN,"No more room on this screen")
#endif

#ifdef SCH_ASSISTANT_WIDGET
RES_ADD_IMG(IMAGE_WIDGET_SCHEDULE_ASSISTANT,"\\MMI_RES_##\\IMAG\\schedule\\IMAGE_WIDGET_SCHEDULE_ASSISTANT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SCHEDULE_BG,"\\MMI_RES_##\\IMAG\\schedule\\IMAGE_WIDGET_SCHEDULE_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SCHEDULE_TEXT_BG,"\\MMI_RES_##\\IMAG\\schedule\\IMAGE_WIDGET_SCHEDULE_TEXT_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SCHEDULE_SHORTCUT,"\\MMI_RES_##\\IMAG\\schedule\\IMAGE_WIDGET_SCHEDULE_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_ANIM(ANIM_WIDGET_SCHEDULE_ASSISTANT,"\\MMI_RES_##\\ANIM\\ANIM_WIDGET_SCHEDULE",ANIM_CMP_PNG_ARGB,0,0x000000)
#endif

#ifdef MMI_WIDGET_TIME
RES_ADD_IMG(IMAGE_WIDGET_TIME_0,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_1,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_2,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_3,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_4,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_5,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_6,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_7,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_7.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_8,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_8.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_9,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_9.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_BG,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_L,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_L.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_R,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_R.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_ZHOU,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_ZHOU.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_TIME_ICON_SHORTCUT,"\\MMI_RES_##\\IMAG\\time\\IMAGE_WIDGET_TIME_ICON_SHORTCUT.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SAM_THEME
RES_ADD_IMG(IMAGE_WIDGET_SAM_TIME_BG,"\\MMI_RES_##\\IMAG\\sam_time\\IMAGE_WIDGET_TIME_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
//#if 0
#if 1
//string

#ifdef WEATHER_SUPPORT
#if (defined MMIWIDGET_SUPPORT) || (defined MMI_GRID_IDLE_SUPPORT)
//weather
//RES_ADD_STRING(TXT_WIDGET_WEATHER_SUNDAY,"SUN.")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_WIDGET_WEATHER_MONDAY,"MON.")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_WIDGET_WEATHER_TUESDAY,"TUE.")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_WIDGET_WEATHER_WEDNESDAY,"WED.")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_WIDGET_WEATHER_THURSDAY,"THU.")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_WIDGET_WEATHER_FRIDAY,"FRI.")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_WIDGET_WEATHER_SATURDAY,"SAT.")    //case3£ºdefined but not used

//RES_ADD_STRING(TXT_WIDGET_WEATHER_SHORTCUT,"Shortcut")    //replaced by local ID TXT_WIDGET_ADD_SHORT  
RES_ADD_STRING(TXT_WIDGET_WEATHER_CHANGE_CITY,"Change city")
RES_ADD_STRING(TXT_WIDGET_WEATHER_UPDATE_WEATHER,"Update weather")

RES_ADD_STRING(TXT_WIDGET_WEATHER_BG_IMG_TYPE,"Bg Img Type")
//RES_ADD_STRING(TXT_WIDGET_WEATHER_TEXT_COLOUR,"Text Colour")  //replaced by common ID TXT_COMMON_FONT_COLOR
RES_ADD_STRING(TXT_WIDGET_WEATHER_TEXT_COLOUR_WHITE,"White")
RES_ADD_STRING(TXT_WIDGET_WEATHER_TEXT_COLOUR_BLACK,"Black")

//RES_ADD_STRING(TXT_WIDGET_WEATHER_UPDATING,"Updating, Please waiting.")  //replaced by common ID TXT_COMMON_UPDATING
RES_ADD_STRING(TXT_WIDGET_WEATHER_NET_ERROR,"Net error, Please try later.")
RES_ADD_STRING(TXT_WIDGET_WEATHER_SWITCH_CITY,"Switching, Please waiting.")

RES_ADD_STRING(TXT_WIDGET_WEATHER_PLEASE_ADD_CITY,"Please add city.")
RES_ADD_STRING(TXT_WIDGET_WEATHER_ONE_CITY_NO_SWITCH,"Only one city, Can't switch.")
#endif
RES_ADD_STRING(TXT_WIDGET_WEATHER_SHORTCUT_SETTING,"Shortcut Setting")
RES_ADD_STRING(TXT_WIDGET_WEATHER_BG_TEXTCOLOUR_SETTING,"BgImg & TextColour Setting")
#endif

RES_ADD_STRING(TXT_WIDGET_EDIT_MEMO,"Edit content")
RES_ADD_STRING(TXT_WIDGET_MAX_ACTIVE_NUM,"The running widget num reaches maxium!")
//RES_ADD_STRING(TXT_IDLE_PHONE,"Phone")      //case3£ºdefined but not used
RES_ADD_STRING(TXT_WIDGET_ADD_WIDGET,"Widgets")
RES_ADD_STRING(TXT_WIDGET_ADD_SHORT,"Shortcuts")
RES_ADD_STRING(TXT_WIDGET_SET_WALLPAPER,"WallPaper")

RES_ADD_STRING(TXT_WIDGET_SET_TITLE,"Add to Desktop")
//RES_ADD_STRING(TXT_WIDGET_PHONE,"Phone")          //case3£ºdefined but not used
#ifdef MMI_GRID_MP3
RES_ADD_STRING(TXT_WIDGET_MP3,"Mp3")
#endif
RES_ADD_STRING(TXT_WIDGET_CLOCK,"Digital Clock")
//RES_ADD_STRING(TXT_WIDGET_PB,"Favorites")      //replaced by common ID TXT_COMMON_PB
RES_ADD_STRING(TXT_WIDGET_MEMO,"Memo")
RES_ADD_STRING(TXT_WIDGET_SHORTCUT_MENU,"Short Menu")
//RES_ADD_STRING(TXT_WIDGET_CALENDAR,"Calendar")       //replaced by common ID TXT_TOOLS_CALENDAR
#ifdef MMI_WIDGET_NETWORK
RES_ADD_STRING(TXT_WIDGET_NETWORK,"Network Name")
#endif
#ifdef MMIWIDGET_SUPPORT
RES_ADD_STRING(TXT_WIDGET_CUSTOM_WORD,"Custom Word")
#endif
RES_ADD_STRING(TXT_WIDGET_NEWSMS,"New Message")
RES_ADD_STRING(TXT_WIDGET_FM,"FM")
RES_ADD_STRING(TXT_WIDGET_CALLLOG,"Call Log")
RES_ADD_STRING(TXT_WIDGET_ASP,"Auto Answer Machine")
RES_ADD_STRING(TXT_WIDGET_SHORTCUT_SET,"ShortcutSet")

#ifdef MMI_WIDGET_ACLOCK
RES_ADD_STRING(TXT_WIDGET_ACLOCK,"Analog clock1")
RES_ADD_STRING(TXT_WIDGET_ACLOCK2,"Analog clock2")
RES_ADD_STRING(TXT_WIDGET_ACLOCK3,"Analog clock3")
#endif

RES_ADD_STRING(TXT_WIDGET_ELVE,"Elve")
#ifdef MMI_WIDGET_SEARCH
//RES_ADD_STRING(TXT_WIDGET_SEARCH,"Search")      //case3£ºdefined but not used
#endif
RES_ADD_STRING(TXT_WIDGET_DCD,"DCD")
RES_ADD_STRING(TXT_WIDGET_DUAL_CLOCK,"Dual Digital Clock")
RES_ADD_STRING(TXT_WIDGET_DUAL_ACLOCK,"Dual Analog Clock")
//RES_ADD_STRING(TXT_WIDGET_ALARM,"Alarm")        //replaced by common ID TXT_ALARM_CLOCK
RES_ADD_STRING(TXT_WIDGET_WEATHER,"Weather")

#ifdef SCH_ASSISTANT_WIDGET
RES_ADD_STRING(TXT_WIDGET_SCHEDULE,"Schedule Assistant")
#endif

#ifdef MMI_WIDGET_TIME
RES_ADD_STRING(TXT_WIDGET_TIME,"time")
#endif

#ifdef MMI_GRID_IDLE_SUPPORT
//RES_ADD_STRING(TXT_WIDGET_IMGVIEWER,"Image Viewer")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_GRID_MENU_ADD,"Add")          //case3£ºdefined but not used
//RES_ADD_STRING(TXT_GRID_MENU_WALLPAPER,"Wallpaper")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_GRID_MENU_SEARCH,"Search")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_GRID_MENU_NOTIFY,"Notify")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_GRID_MENU_SETTING,"Setting")    //case3£ºdefined but not used
#ifdef MMI_WIDGET_NETSEARCH
//RES_ADD_STRING(TXT_WIDGET_NETSEARCH,"Net Search")    //replaced by common ID  TXT_NETWORK_SEARCHING
//RES_ADD_STRING(TXT_WIDGET_NETSEARCH_CONTENT,"Search")  //replaced by common ID STXT_SEARCH
#endif
//RES_ADD_STRING(TXT_WIDGET_COUNTEDTIME_START,"START")       //replaced by common ID TXT_COMMON_START
//RES_ADD_STRING(TXT_WIDGET_COUNTEDTIME_STOP,"STOP")    //replaced by common ID  STXT_STOP
//RES_ADD_STRING(TXT_WIDGET_COUNTEDTIME,"Countedtime")  //replaced by common ID TXT_TOOLS_COUNTEDTIME
RES_ADD_STRING(TXT_WIDGET_COUNTEDTIME_INPUT,"Please edit time")
#endif

#if defined MMI_GRID_CALENDAR
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_JAN,"Jan")    //replaced by common ID  TXT_IDLE_SHORT_JAN,but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_FEB,"Feb")         //case3£ºdefined but not used,but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_MAR,"Mar")        //case3£ºdefined but not used,but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_APR,"Apr")        //case3£ºdefined but not used,but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_MAY,"May")      //case3£ºdefined but not used,but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_JUN,"Jun")       //case3£ºdefined but not used,but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_JUL,"Jul")         //case3£ºdefined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_AUG,"Aug")       //case3£ºdefined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_SEP,"Sep")        //case3£ºdefined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_OCT,"Oct")        //case3£ºdefined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_NOV,"Nov")      //case3£ºdefined but not used, but later find it was used in ++mode
RES_ADD_STRING(TXT_IDLE_SHORTCUT_OH_TIME_DEC,"Dec")     //case3£ºdefined but not used, but later find it was used in ++mode
#endif

#ifdef SNS_PULLING_SUPPORT
RES_ADD_STRING(TXT_WIDGET_MANUAL,"Manual")
RES_ADD_STRING(TXT_WIDGET_5_MIN,"5 Minutes")
RES_ADD_STRING(TXT_WIDGET_15_MIN,"15 Minutes")
RES_ADD_STRING(TXT_WIDGET_30_MIN,"30 Minutes")
RES_ADD_STRING(TXT_WIDGET_60_MIN,"60 Minutes")
RES_ADD_STRING(TXT_WIDGET_BUSY,"System busy, please try later")
RES_ADD_STRING(TXT_WIDGET_SETTING,"Setting")

RES_ADD_IMG(IMAGE_WIDGET_SNS_SYNC,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_SYNC.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_WIDGET_SNS_SYNC_HIGHT,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_SYNC_HIGHT.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_WIDGET_SNS_SETTING,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_SETTING.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_WIDGET_SNS_SETTING_HIGHT,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_SETTING_HIGHT.png",IMG_CMP_PNG_ARGB,0)

#endif //SNS_PULLING_SUPPORT

#ifdef SNS_SUPPORT

//RES_ADD_STRING(TXT_WIDGET_LOGIN,"LogIn")  //replaced by common ID TXT_COMM_LOGIN
//RES_ADD_STRING(TXT_WIDGET_LOADING,"Loading...")    //replaced by common ID TXT_LOADING
RES_ADD_STRING(TXT_WIDGET_SINA,"Sinaweibo")
//RES_ADD_STRING(TXT_WIDGET_FACEBOOK,"Fecebook")  //replaced by common ID TXT_COMMON_FACEBOOK
//RES_ADD_STRING(TXT_WIDGET_TIWTTER,"Tiwtter")  //replaced by common ID TXT_COMMON_TIWTTER
//RES_ADD_STRING(TXT_WIDGET_WAITING,"waiting please")  //replaced by common ID TXT_COMMON_WAITING
//RES_ADD_STRING(TXT_WIDGET_WHETHER_INSTALL,"No App, wheter Install now")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_WIDGET_SNS_EMPTY,"Empty")     //replaced by common ID TXT_BLANK

RES_ADD_IMG(IMAGE_ICON_SINA_VIRTUE_UP,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_ICON_SINA_VIRTUE_UP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ICON_SINA_VIRTUE_DOWN,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_ICON_SINA_VIRTUE_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_ICON_SINA_BLOG,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_ICON_SINA_BLOG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGETL_SNS_FACEBOOK,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGETL_SNS_FACEBOOK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGETL_SNS_TWITTER,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGETL_SNS_TWITTER.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_SNS_LOGIN_BG,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_LOGIN_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SNS_BG1,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_BG1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SNS_BG2,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_BG2.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_SNS_SINA,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_SINA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SNS_FACEBOOK,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_FACEBOOK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SNS_TWITTER,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_TWITTER.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_WIDGET_SNS_ADD,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_ADD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SNS_ADD_HIGHT,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_ADD_HIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WIDGET_SNS_BGHLIGHT,"\\MMI_RES_##\\IMAG\\sns\\IMAGE_WIDGET_SNS_BGHLIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif


#ifdef BAR_PHONE_WIDGET 
#ifdef MMI_WIDGET_SPEED_DIAL
RES_ADD_STRING(TXT_WIDGET_SPEED_DIAL,"Speed dialing")
RES_ADD_STRING(TXT_WIDGET_SPEED_DIAL_TIP,"Long press to dial")
#endif

RES_ADD_STRING(TXT_IDLE_BUSINESS_MODE,"Business")
RES_ADD_STRING(TXT_IDLE_SHORTCUT_MODE,"Shortcut")
#endif
RES_ADD_STRING(TXT_NO_ALBUM,"No Album Information")
RES_ADD_STRING(TXT_IDLE_OUT_OF_MEMORY,"Out of Memory!")

#ifdef MMI_SAM_THEME
#ifdef MMI_POWER_SAVING_MODE_SUPPORT
RES_ADD_STRING(TXT_WIDGET_PWRSAV_WIFI,"WIFI")
RES_ADD_STRING(TXT_WIDGET_PWRSAV_BGDATA,"BG Data")
RES_ADD_STRING(TXT_WIDGET_PWRSAV_ALERT_SETTING,"Alert")
RES_ADD_STRING(TXT_WIDGET_PWRSAV_BT,"BT")
RES_ADD_STRING(TXT_WIDGET_PWRSAV_SS,"Scr Saver")
RES_ADD_STRING(TXT_WIDGET_PWRSAV_KEYLIGHT,"Key Light")
RES_ADD_STRING(TXT_WIDGET_PWRSAV_BRIGHT,"Bright")
RES_ADD_STRING(TXT_WIDGET_PWRSAV_BATTERY,"Bat Disp")
#endif
#endif
