/**---------------------------------------------------------------------------**
 ** Copyright:    2014 Spreadtrum, Incoporated. All Rights Reserved.          **
 ** Description:  Automately generated by perl script                         **
------------------------------------------------------------------------------**/


/**---------------------------------------------------------------------------**
 **                    Edit    History                                        **
 ** ------------------------------------------------------------------------  **
 ** DATE          NAME               DESCRIPTION                              **
 ** 2014/01/13    BaseBand_Driver    Create by Trout3 APB Control             **
 **                                  Register.xls                             **
------------------------------------------------------------------------------**/


#ifndef _APB_REG_H
#define _APB_REG_H


#define    REG_APB_RST                          ( CTL_BASE_GLOABL + 0x0000 )
#define    REG_MCU_SOFT_RST                     ( CTL_BASE_GLOABL + 0x0004 )
#define    REG_APB_EB                           ( CTL_BASE_GLOABL + 0x00a8 )
#define    REG_APB_EB1                          ( CTL_BASE_GLOABL + 0x00aC )
#define    REG_APB_CLK_CTL0                     ( CTL_BASE_GLOABL + 0x0020 )
#define    REG_APB_CLK_CTL1                     ( CTL_BASE_GLOABL + 0x0024 )
#define    REG_APB_SLP_CTL0                     ( CTL_BASE_GLOABL + 0x0030 )
#define    REG_APB_INT_STS0                     ( CTL_BASE_GLOABL + 0x0034 )
#define    REG_APB_INT_SET_CLR0                 ( CTL_BASE_GLOABL + 0x0160 )
#define    REG_WIFI_BUF_BASE                    ( CTL_BASE_GLOABL + 0x003C )
#define    REG_CLK_TOP_CTRL0                    ( CTL_BASE_GLOABL + 0x0040 )
#define    REG_CLK_TOP_CTRL1                    ( CTL_BASE_GLOABL + 0x0044 )
#define    REG_FPGADEBUG                        ( CTL_BASE_GLOABL + 0x0048 )
#define    REG_APB_BT_DAC_CTR0                  ( CTL_BASE_GLOABL + 0x0050 )
#define    REG_APB_BT_DAC_CTR1                  ( CTL_BASE_GLOABL + 0x0054 )
#define    REG_APB_BT_DAC_CTR2                  ( CTL_BASE_GLOABL + 0x0058 )
#define    REG_APB_BT_DAC_STS0                  ( CTL_BASE_GLOABL + 0x005C )
#define    REG_APB_BT_DAC_STS1                  ( CTL_BASE_GLOABL + 0x0060 )
#define    REG_APB_BT_ADC_CTR0                  ( CTL_BASE_GLOABL + 0x0064 )
#define    REG_APB_BT_ADC_CTR1                  ( CTL_BASE_GLOABL + 0x0068 )
#define    REG_APB_BT_ADC_CTR2                  ( CTL_BASE_GLOABL + 0x006C )
#define    REG_WIFI_SYS0                        ( CTL_BASE_GLOABL + 0x0070 )
#define    REG_WIFI_SYS1                        ( CTL_BASE_GLOABL + 0x0074 )
#define    REG_APB_WIFI_ADC_CTR0                ( CTL_BASE_GLOABL + 0x0078 )
#define    REG_APB_WIFI_ADC_CTR1                ( CTL_BASE_GLOABL + 0x007C )
#define    REG_ARM7_RDATA_FROM_ARM9             ( CTL_BASE_GLOABL + 0x0080 )
#define    REG_ARM7_WDATA_TO_ARM9               ( CTL_BASE_GLOABL + 0x0084 )
#define    REG_CP2_BB_CTRL                      ( CTL_BASE_GLOABL + 0x0088 )
#define    REG_WIFI_BT_CFG0                     ( CTL_BASE_GLOABL + 0x0090 )
#define    REG_WIFI_BT_CFG1                     ( CTL_BASE_GLOABL + 0x0094 )
#define    REG_WIFI_BT_CFG2                     ( CTL_BASE_GLOABL + 0x0098 )
#define    REG_WIFI_BT_CFG3                     ( CTL_BASE_GLOABL + 0x009C )
#define    REG_WIFI_DFT_CTRTL0                  ( CTL_BASE_GLOABL + 0x00A0 )
#define    REG_WIFI_DFT_CTRTL1                  ( CTL_BASE_GLOABL + 0x00A4 )
#define    REG_WIFI_DFT_CTRTL2                  ( CTL_BASE_GLOABL + 0x00A8 )
#define    REG_WB_ADA_CTRTL0                    ( CTL_BASE_GLOABL + 0x00B0 )
#define    REG_WB_ADA_CTRTL1                    ( CTL_BASE_GLOABL + 0x00B4 )
#define    REG_WB_ADA_CTRTL2                    ( CTL_BASE_GLOABL + 0x00B8 )
#define    REG_WB_ADA_CTRTL3                    ( CTL_BASE_GLOABL + 0x00BC )
#define    REG_WB_ADA_RESULT0                   ( CTL_BASE_GLOABL + 0x00C0 )
#define    REG_WB_ADA_RESULT1                   ( CTL_BASE_GLOABL + 0x00C4 )
#define    REG_WB_ADA_RESULT2                   ( CTL_BASE_GLOABL + 0x00C8 )
#define    REG_WB_ADA_RESULT3                   ( CTL_BASE_GLOABL + 0x00CC )
#define    REG_WB_DBG_RESULT0                   ( CTL_BASE_GLOABL + 0x00D0 )
#define    REG_WB_DBG_RESULT1                   ( CTL_BASE_GLOABL + 0x00D4 )
#define    REG_WB_DAC_DBG_DAT                   ( CTL_BASE_GLOABL + 0x00D8 )
#define    REG_BT_FUNC_DBG                      ( CTL_BASE_GLOABL + 0x00DC )
#define    REG_APB_ARCH_PORT                    ( CTL_BASE_GLOABL + 0x0100 )
#define    REG_RF_PARA_WIFI0                    ( CTL_BASE_GLOABL + 0x0104 )
#define    REG_RF_PARA_WIFI1                    ( CTL_BASE_GLOABL + 0x0108 )
#define    REG_RF_PARA_WIFI2                    ( CTL_BASE_GLOABL + 0x010C )
#define    REG_RF_PARA_WIFI3                    ( CTL_BASE_GLOABL + 0x0110 )
#define    REG_RF_PARA_WIFI4                    ( CTL_BASE_GLOABL + 0x0114 )
#define    REG_RF_PARA_WIFI5                    ( CTL_BASE_GLOABL + 0x0118 )
#define    REG_RF_PARA_WIFI6                    ( CTL_BASE_GLOABL + 0x011C )
#define    REG_RF_PARA_WIFI7                    ( CTL_BASE_GLOABL + 0x0120 )
#define    REG_RF_PARA_WIFI8                    ( CTL_BASE_GLOABL + 0x0124 )
#define    REG_RF_PARA_WIFI9                    ( CTL_BASE_GLOABL + 0x0128 )
#define    REG_RF_PARA_WIFI10                   ( CTL_BASE_GLOABL + 0x012C )
#define    REG_RF_PARA_WIFI11                   ( CTL_BASE_GLOABL + 0x0130 )
#define    REG_RF_PARA_BT0                      ( CTL_BASE_GLOABL + 0x0134 )
#define    REG_RF_PARA_BT1                      ( CTL_BASE_GLOABL + 0x0138 )
#define    REG_RF_PARA_BT2                      ( CTL_BASE_GLOABL + 0x013C )
#define    REG_RF_PARA_BT3                      ( CTL_BASE_GLOABL + 0x0140 )
#define    REG_RF_PARA_BT4                      ( CTL_BASE_GLOABL + 0x0144 )
#define    REG_RF_PARA_BT5                      ( CTL_BASE_GLOABL + 0x0148 )
#define    REG_RF_PARA_BT6                      ( CTL_BASE_GLOABL + 0x014C )
#define    REG_RF_PARA_BT7                      ( CTL_BASE_GLOABL + 0x0150 )
#define    REG_RF_PARA_BT8                      ( CTL_BASE_GLOABL + 0x0154 )
#define    REG_RF_PARA_BT9                      ( CTL_BASE_GLOABL + 0x0158 )
#define    REG_RF_PARA_BT10                     ( CTL_BASE_GLOABL + 0x015C )
//#define    REG_RF_PARA_BT11                     ( CTL_BASE_GLOABL + 0x0160 )
//#define    REG_APB_INT_SET_CLR0                 ( CTL_BASE_GLOABL + 0x0160 )
#define    REG_RF_PARA_NUM                      ( CTL_BASE_GLOABL + 0x0164 )
#define    REG_WIFI_TIME_SET                    ( CTL_BASE_GLOABL + 0x0168 )
#define    REG_BT_TIME_SET                      ( CTL_BASE_GLOABL + 0x016C )
#define    REG_WIFI_ACT_CTRL                    ( CTL_BASE_GLOABL + 0x0170 )
#define    REG_BT_ACT_CTRL                      ( CTL_BASE_GLOABL + 0x0174 )
#define    REG_SWITCH_MODE_CTRL                 ( CTL_BASE_GLOABL + 0x0178 )
#define    REG_SWITCH_PROTECT_CTRL              ( CTL_BASE_GLOABL + 0x017C )
#define    REG_RF_MASTER_CTRL                   ( CTL_BASE_GLOABL + 0x0180 )
#define    REG_APB_MISC_CTL                     ( CTL_BASE_GLOABL + 0x0200 )
#define    REG_APB_MISC_CTL1                    ( CTL_BASE_GLOABL + 0x0204 )


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_RST                                         **
 ** Register Offset     : 0x0000                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_PHY_SOFT_RST                               (BIT_(20))
#define    BIT_APB_MAC_SOFT_RST                               (BIT_(19))
#define    BIT_APB_GPIO_SOFT_RST                              (BIT_(18))
#define    BIT_APB_ADI_SOFT_RST                               (BIT_(17))
#define    BIT_APB_VBC_SOFT_RST                               (BIT_(16))
#define    BIT_APB_AUD_SOFT_RST                               (BIT_(15))
#define    BIT_APB_VPU_SOFT_RST                               (BIT_(14))
#define    BIT_APB_FM_SOFT_RST                                (BIT_(13))
#define    BIT_APB_RCB_SOFT_RST                               (BIT_(12))
#define    BIT_APB_WIFI_SOFT_RST                              (BIT_(11))
#define    BIT_APB_IIS_SOFT_RST                               (BIT_(10))
#define    BIT_APB_EIC_SOFT_RST                               (BIT_(9))
#define    BIT_APB_BT_SOFT_RST                                (BIT_(8))
#define    BIT_APB_WDG_SOFT_RST                               (BIT_(7))
#define    BIT_APB_TMR1_SOFT_RST                              (BIT_(6))
#define    BIT_APB_TMR0_SOFT_RST                              (BIT_(5))
#define    BIT_APB_SYST_SOFT_RST                              (BIT_(4))
#define    BIT_APB_UART1_SOFT_RST                             (BIT_(3))
#define    BIT_APB_UART0_SOFT_RST                             (BIT_(2))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_MCU_SOFT_RST                                    **
 ** Register Offset     : 0x0004                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_MCU_SOFT_RST_SET                           (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_EB                                          **
 ** Register Offset     : 0x0018                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
//#define    BIT_APB_PIN_EB                                     (BIT_(29))
#define    BIT_APB_EFUSE_EB                                   (BIT_(28))
#define    BIT_APB_TMR4_RTC_EB                                (BIT_(27))
#define    BIT_APB_TMR3_RTC_EB                                (BIT_(26))
#define    BIT_APB_TMR9_EB                                    (BIT_(25))
#define    BIT_APB_TMR8_EB                                    (BIT_(24))
#define    BIT_APB_TMR7_EB                                    (BIT_(23))
#define    BIT_APB_TMR6_EB                                    (BIT_(22))
//#define    BIT_APB_TMR5_EB                                    (BIT_(21))
#define    BIT_APB_TMR4_EB                                    (BIT_(20))
#define    BIT_APB_TMR3_EB                                    (BIT_(19))
#define    BIT_APB_TMR2_EB                                    (BIT_(18))
#define    BIT_APB_GPIO_EB                                    (BIT_(17))
#define    BIT_APB_FM_EB                                      (BIT_(29))
#define    BIT_APB_WIFI_EB                                    (BIT_(15))
#define    BIT_APB_IIS_EB                                     (BIT_(14))
#define    BIT_APB_EIC_RTCDV5_EB                              (BIT_(13))
#define    BIT_APB_EIC_EB                                     (BIT_(12))
//#define    BIT_APB_BT_RTC_EB                                  (BIT_(11))
//#define    BIT_APB_TMR1_RTC_EB                                (BIT_(10))
//#define    BIT_APB_TMR0_RTC_EB                                (BIT_(9))
#define    BIT_APB_SYST_RTC_EB                                (BIT_(21))
#define    BIT_APB_WDG_RTC_EB                                 (BIT_(7))
#define    BIT_APB_BT_EB                                      (BIT_(6))
#define    BIT_APB_WDG_EB                                     (BIT_(5))
#define    BIT_APB_TMR1_EB                                    (BIT_(4))
#define    BIT_APB_TMR0_EB                                    (BIT_(3))
#define    BIT_APB_SYST_EB                                    (BIT_(9))
#define    BIT_APB_UART1_EB                                   (BIT_(11))
#define    BIT_APB_UART0_EB                                   (BIT_(10))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_EB1                                         **
 ** Register Offset     : 0x001C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_ARCH_RTC_EB                                (BIT_(1))
#define    BIT_APB_ARCH_EB                                    (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_CLK_CTL0                                    **
 ** Register Offset     : 0x0020                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_CLK_WTDAC_CTRL(x)                          (((x) & 0xFFF) << 20)
#define    BIT_GET_APB_CLK_WTDAC_CTRL(x)                      (((x) >> 20)& 0xFFF )
#define    BIT_APB_CLK_BT_26M_SRC_SEL                         (BIT_(19))
#define    BIT_APB_CLK_BT_DA_SEL(x)                           (((x) & 0x3) << 17)
#define    BIT_GET_APB_CLK_BT_DA_SEL(x)                       (((x) >> 17)& 0x3 )
#define    BIT_APB_CLK_BT_AD_SEL(x)                           (((x) & 0x3) << 15)
#define    BIT_GET_APB_CLK_BT_AD_SEL(x)                       (((x) >> 15)& 0x3 )
#define    BIT_APB_CLK_UART0_SEL(x)                           (((x) & 0x3) << 13)
#define    BIT_GET_APB_CLK_UART0_SEL(x)                       (((x) >> 13)& 0x3 )
#define    BIT_APB_CLK_BT_26M_SEL                             (BIT_(12))
#define    BIT_APB_CLK_BT_24M_SEL                             (BIT_(11))
#define    BIT_APB_CLK_IIS_SEL(x)                             (((x) & 0x3) << 9)
#define    BIT_GET_APB_CLK_IIS_SEL(x)                         (((x) >> 9)& 0x3 )
#define    BIT_APB_CLK_VPU_SEL(x)                             (((x) & 0x3) << 7)
#define    BIT_GET_APB_CLK_VPU_SEL(x)                         (((x) >> 7)& 0x3 )
#define    BIT_APB_CLK_UART1_SEL(x)                           (((x) & 0x3) << 5)
#define    BIT_GET_APB_CLK_UART1_SEL(x)                       (((x) >> 5)& 0x3 )
#define    BIT_APB_CLK_WIFI_120M_EN                           (BIT_(4))
#define    BIT_APB_CLK_WIFI_26M_EN                            (BIT_(3))
#define    BIT_APB_CLK_WIFI_80M_EN                            (BIT_(2))
#define    BIT_APB_CLK_WIFI_44M_EN                            (BIT_(1))
#define    BIT_APB_CLK_WIFI_40M_EN                            (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_CLK_CTL1                                    **
 ** Register Offset     : 0x0024                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_CLK_IIS_DIV(x)                             ((x) & 0x7)
#define    BIT_GET_APB_CLK_IIS_DIV(x)                         ((x) & 0x7)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_SLP_CTL0                                    **
 ** Register Offset     : 0x0030                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_FORCE_ON                                   (BIT_(2))
#define    BIT_APB_FORCE_SLEEP                                (BIT_(1))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_INT_STS0                                    **
 ** Register Offset     : 0x0034                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_ARM9_FRQ                                   (BIT_(3))
#define    BIT_APB_ARM9_IRQ                                   (BIT_(2))
#define    BIT_APB_ARM7_MCU_FRQ                               (BIT_(1))
#define    BIT_APB_ARM7_MCU_IRQ                               (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_INT_SET_CLR0                                **
 ** Register Offset     : 0x0038                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_ARM9_FRQ_CLR                               (BIT_(3))
#define    BIT_APB_ARM9_IRQ_CLR                               (BIT_(2))
#define    BIT_APB_ARM7_MCU_FRQ_SET                           (BIT_(1))
#define    BIT_APB_ARM7_MCU_IRQ_SET                           (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_BUF_BASE                                   **
 ** Register Offset     : 0x003C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_BUF_BASE(x)                           (x)
#define    BIT_GET_APB_WIFI_BUF_BASE(x)                       (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_CLK_TOP_CTRL0                                   **
 ** Register Offset     : 0x0040                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_CLK_TOP_CTRL0(x)                           (x)
#define    BIT_GET_APB_CLK_TOP_CTRL0(x)                       (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_CLK_TOP_CTRL1                                   **
 ** Register Offset     : 0x0044                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_CLK_TOP_CTRL1(x)                           (x)
#define    BIT_GET_APB_CLK_TOP_CTRL1(x)                       (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_FPGADEBUG                                       **
 ** Register Offset     : 0x0048                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_FPGADEBUG(x)                               (x)
#define    BIT_GET_APB_FPGADEBUG(x)                           (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_BT_DAC_CTR0                                 **
 ** Register Offset     : 0x0050                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_DAC_BG_CTR(x)                           (((x) & 0x3) << 30)
#define    BIT_GET_APB_BT_DAC_BG_CTR(x)                       (((x) >> 30)& 0x3 )
#define    BIT_APB_BT_DAC_EN_ADC                              (BIT_(26))
#define    BIT_APB_BT_DAC_CLK_SEL                             (BIT_(25))
#define    BIT_APB_BT_DAC_EN_MIDRANGE                         (BIT_(24))
#define    BIT_APB_BT_DAC_Q_DC(x)                             (((x) & 0xFFF) << 12)
#define    BIT_GET_APB_BT_DAC_Q_DC(x)                         (((x) >> 12)& 0xFFF )
#define    BIT_APB_BT_DAC_I_DC(x)                             ((x) & 0xFFF)
#define    BIT_GET_APB_BT_DAC_I_DC(x)                         ((x) & 0xFFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_BT_DAC_CTR1                                 **
 ** Register Offset     : 0x0054                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_DAC_SEL(x)                              (((x) & 0x3) << 29)
#define    BIT_GET_APB_BT_DAC_SEL(x)                          (((x) >> 29)& 0x3 )
#define    BIT_APB_BT_DAC_BOOSTI_EN                           (BIT_(28))
#define    BIT_APB_BT_DAC_CFG(x)                              (((x) & 0x7) << 25)
#define    BIT_GET_APB_BT_DAC_CFG(x)                          (((x) >> 25)& 0x7 )
#define    BIT_APB_BT_DAC_CAL_CLK_SEL                         (BIT_(24))
#define    BIT_APB_BT_DAC_PD                                  (BIT_(23))
#define    BIT_APB_BT_DAC_WADDR_OVR(x)                        (((x) & 0xF) << 19)
#define    BIT_GET_APB_BT_DAC_WADDR_OVR(x)                    (((x) >> 19)& 0xF )
#define    BIT_APB_BT_DAC_WLE_OVR                             (BIT_(18))
#define    BIT_APB_BT_DAC_WD_OVR(x)                           (((x) & 0xFFFF) << 2)
#define    BIT_GET_APB_BT_DAC_WD_OVR(x)                       (((x) >> 2)& 0xFFFF )
#define    BIT_APB_BT_DAC_W_OVR_I_QN                          (BIT_(1))
#define    BIT_APB_BT_DAC_W_OVR_EN                            (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_BT_DAC_CTR2                                 **
 ** Register Offset     : 0x0058                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BB_BG_EN                                   (BIT_(21))
#define    BIT_APB_BB_LDO_EN                                  (BIT_(20))
#define    BIT_APB_BT_DAC_OVR_EN_CAL                          (BIT_(19))
#define    BIT_APB_BT_DAC_EN_OOSCAL                           (BIT_(18))
#define    BIT_APB_BT_DAC_IQ_SWAP                             (BIT_(17))
#define    BIT_APB_BT_DAC_CAL_START                           (BIT_(16))
#define    BIT_APB_BT_DAC_OFFSETI(x)                          (((x) & 0xFF) << 8)
#define    BIT_GET_APB_BT_DAC_OFFSETI(x)                      (((x) >> 8)& 0xFF )
#define    BIT_APB_BT_DAC_OFFSETQ(x)                          ((x) & 0xFF)
#define    BIT_GET_APB_BT_DAC_OFFSETQ(x)                      ((x) & 0xFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_BT_DAC_STS0                                 **
 ** Register Offset     : 0x005C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_DAC_WTI(x)                              (((x) & 0xFFFF) << 16)
#define    BIT_GET_APB_BT_DAC_WTI(x)                          (((x) >> 16)& 0xFFFF )
#define    BIT_APB_BT_DAC_WTQ(x)                              ((x) & 0xFFFF)
#define    BIT_GET_APB_BT_DAC_WTQ(x)                          ((x) & 0xFFFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_BT_DAC_STS1                                 **
 ** Register Offset     : 0x0060                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_DAC_DA_STATE(x)                         (((x) & 0x3) << 17)
#define    BIT_GET_APB_BT_DAC_DA_STATE(x)                     (((x) >> 17)& 0x3 )
#define    BIT_APB_BT_DAC_DONE                                (BIT_(16))
#define    BIT_APB_BT_DAC_WQ_OVR(x)                           ((x) & 0xFFFF)
#define    BIT_GET_APB_BT_DAC_WQ_OVR(x)                       ((x) & 0xFFFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_BT_ADC_CTR0                                 **
 ** Register Offset     : 0x0064                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_ADC_SARSPD(x)                           (((x) & 0x3) << 25)
#define    BIT_GET_APB_BT_ADC_SARSPD(x)                       (((x) >> 25)& 0x3 )
#define    BIT_APB_BT_ADC_CMPSPD(x)                           (((x) & 0x3) << 23)
#define    BIT_GET_APB_BT_ADC_CMPSPD(x)                       (((x) >> 23)& 0x3 )
#define    BIT_APB_BT_ADC_ADJ(x)                              (((x) & 0xFFFF) << 7)
#define    BIT_GET_APB_BT_ADC_ADJ(x)                          (((x) >> 7)& 0xFFFF )
#define    BIT_APB_BT_ADC_REFBIAS(x)                          (((x) & 0x7) << 4)
#define    BIT_GET_APB_BT_ADC_REFBIAS(x)                      (((x) >> 4)& 0x7 )
#define    BIT_APB_BT_ADC_CMPBIAS(x)                          (((x) & 0x3) << 2)
#define    BIT_GET_APB_BT_ADC_CMPBIAS(x)                      (((x) >> 2)& 0x3 )
#define    BIT_APB_BT_ADC_MODE                                (BIT_(1))
#define    BIT_APB_BT_ADC_EN                                  (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_BT_ADC_CTR1                                 **
 ** Register Offset     : 0x0068                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_ADC_CAL                                 (BIT_(18))
#define    BIT_APB_BT_ADC_DUTY(x)                             (((x) & 0x7) << 15)
#define    BIT_GET_APB_BT_ADC_DUTY(x)                         (((x) >> 15)& 0x7 )
#define    BIT_APB_BT_ADC_DLL_D(x)                            (((x) & 0x3F) << 9)
#define    BIT_GET_APB_BT_ADC_DLL_D(x)                        (((x) >> 9)& 0x3F )
#define    BIT_APB_BT_ADC_DLL_RD                              (BIT_(8))
#define    BIT_APB_BT_ADC_DLL_SUG                             (BIT_(7))
#define    BIT_APB_BT_ADC_DLL_SET(x)                          (((x) & 0x3F) << 1)
#define    BIT_GET_APB_BT_ADC_DLL_SET(x)                      (((x) >> 1)& 0x3F )
#define    BIT_APB_BT_ADC_DLL_OVR                             (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_BT_ADC_CTR2                                 **
 ** Register Offset     : 0x006C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_PTA_SL(x)                               (((x) & 0x1F) << 5)
#define    BIT_GET_APB_BT_PTA_SL(x)                           (((x) >> 5)& 0x1F )
#define    BIT_APB_BT_CTRL                                    (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_SYS0                                       **
 ** Register Offset     : 0x0070                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFIMAB_CTRL(x)                            (((x) & 0x3FF) << 10)
#define    BIT_GET_APB_WIFIMAB_CTRL(x)                        (((x) >> 10)& 0x3FF )
#define    BIT_APB_WIFISAB_CTRL(x)                            ((x) & 0x3FF)
#define    BIT_GET_APB_WIFISAB_CTRL(x)                        ((x) & 0x3FF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_SYS1                                       **
 ** Register Offset     : 0x0074                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFIMAB_STS(x)                             (((x) & 0x3FFF) << 14)
#define    BIT_GET_APB_WIFIMAB_STS(x)                         (((x) >> 14)& 0x3FFF )
#define    BIT_APB_WIFISAB_STS(x)                             ((x) & 0x3FFF)
#define    BIT_GET_APB_WIFISAB_STS(x)                         ((x) & 0x3FFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_WIFI_ADC_CTR0                               **
 ** Register Offset     : 0x0078                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_ADC_SARSPD(x)                         (((x) & 0x3) << 25)
#define    BIT_GET_APB_WIFI_ADC_SARSPD(x)                     (((x) >> 25)& 0x3 )
#define    BIT_APB_WIFI_ADC_CMPSPD(x)                         (((x) & 0x3) << 23)
#define    BIT_GET_APB_WIFI_ADC_CMPSPD(x)                     (((x) >> 23)& 0x3 )
#define    BIT_APB_WIFI_ADC_ADJ(x)                            (((x) & 0xFFFF) << 7)
#define    BIT_GET_APB_WIFI_ADC_ADJ(x)                        (((x) >> 7)& 0xFFFF )
#define    BIT_APB_WIFI_ADC_REFBIAS(x)                        (((x) & 0x7) << 4)
#define    BIT_GET_APB_WIFI_ADC_REFBIAS(x)                    (((x) >> 4)& 0x7 )
#define    BIT_APB_WIFI_ADC_CMPBIAS(x)                        (((x) & 0x3) << 2)
#define    BIT_GET_APB_WIFI_ADC_CMPBIAS(x)                    (((x) >> 2)& 0x3 )
#define    BIT_APB_WIFI_ADC_MODE                              (BIT_(1))
#define    BIT_APB_WIFI_ADC_EN                                (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_WIFI_ADC_CTR1                               **
 ** Register Offset     : 0x007C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_ADC_CAL                               (BIT_(18))
#define    BIT_APB_WIFI_ADC_DUTY(x)                           (((x) & 0x7) << 15)
#define    BIT_GET_APB_WIFI_ADC_DUTY(x)                       (((x) >> 15)& 0x7 )
#define    BIT_APB_WIFI_ADC_DLL_D(x)                          (((x) & 0x3F) << 9)
#define    BIT_GET_APB_WIFI_ADC_DLL_D(x)                      (((x) >> 9)& 0x3F )
#define    BIT_APB_WIFI_ADC_DLL_RD                            (BIT_(8))
#define    BIT_APB_WIFI_ADC_DLL_SUG                           (BIT_(7))
#define    BIT_APB_WIFI_ADC_DLL_SET(x)                        (((x) & 0x3F) << 1)
#define    BIT_GET_APB_WIFI_ADC_DLL_SET(x)                    (((x) >> 1)& 0x3F )
#define    BIT_APB_WIFI_ADC_DLL_OVR                           (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_ARM7_RDATA_FROM_ARM9                            **
 ** Register Offset     : 0x0080                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_ARM7_RDATA_FROM_ARM9(x)                    (x)
#define    BIT_GET_APB_ARM7_RDATA_FROM_ARM9(x)                (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_ARM7_WDATA_TO_ARM9                              **
 ** Register Offset     : 0x0084                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_ARM7_WDATA_TO_ARM9(x)                      (x)
#define    BIT_GET_APB_ARM7_WDATA_TO_ARM9(x)                  (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_CP2_BB_CTRL                                     **
 ** Register Offset     : 0x0088                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BB_LOCAL_CTRL(x)                           ((x) & 0xFFFF)
#define    BIT_GET_APB_BB_LOCAL_CTRL(x)                       ((x) & 0xFFFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_BT_CFG0                                    **
 ** Register Offset     : 0x0090                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_BT_CFG0(x)                            (x)
#define    BIT_GET_APB_WIFI_BT_CFG0(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_BT_CFG1                                    **
 ** Register Offset     : 0x0094                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_BT_CFG1(x)                            (x)
#define    BIT_GET_APB_WIFI_BT_CFG1(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_BT_CFG2                                    **
 ** Register Offset     : 0x0098                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_BT_CFG2(x)                            (x)
#define    BIT_GET_APB_WIFI_BT_CFG2(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_BT_CFG3                                    **
 ** Register Offset     : 0x009C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_BT_CFG3(x)                            (x)
#define    BIT_GET_APB_WIFI_BT_CFG3(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_DFT_CTRTL0                                 **
 ** Register Offset     : 0x00A0                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_DFT_CTRTL0(x)                         (x)
#define    BIT_GET_APB_WIFI_DFT_CTRTL0(x)                     (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_DFT_CTRTL1                                 **
 ** Register Offset     : 0x00A4                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_DFT_CTRTL1(x)                         (x)
#define    BIT_GET_APB_WIFI_DFT_CTRTL1(x)                     (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_DFT_CTRTL2                                 **
 ** Register Offset     : 0x00A8                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_DFT_CTRTL2(x)                         (x)
#define    BIT_GET_APB_WIFI_DFT_CTRTL2(x)                     (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_ADA_CTRTL0                                   **
 ** Register Offset     : 0x00B0                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_ADA_CTRTL0(x)                           (x)
#define    BIT_GET_APB_WB_ADA_CTRTL0(x)                       (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_ADA_CTRTL1                                   **
 ** Register Offset     : 0x00B4                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_ADA_CTRTL1(x)                           (x)
#define    BIT_GET_APB_WB_ADA_CTRTL1(x)                       (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_ADA_CTRTL2                                   **
 ** Register Offset     : 0x00B8                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_ADA_CTRTL2(x)                           (x)
#define    BIT_GET_APB_WB_ADA_CTRTL2(x)                       (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_ADA_CTRTL3                                   **
 ** Register Offset     : 0x00BC                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_ADA_CTRTL3(x)                           (x)
#define    BIT_GET_APB_WB_ADA_CTRTL3(x)                       (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_ADA_RESULT0                                  **
 ** Register Offset     : 0x00C0                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_ADA_RESULT0(x)                          (x)
#define    BIT_GET_APB_WB_ADA_RESULT0(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_ADA_RESULT1                                  **
 ** Register Offset     : 0x00C4                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_ADA_RESULT1(x)                          (x)
#define    BIT_GET_APB_WB_ADA_RESULT1(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_ADA_RESULT2                                  **
 ** Register Offset     : 0x00C8                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_ADA_RESULT2(x)                          (x)
#define    BIT_GET_APB_WB_ADA_RESULT2(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_ADA_RESULT3                                  **
 ** Register Offset     : 0x00CC                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_ADA_RESULT3(x)                          (x)
#define    BIT_GET_APB_WB_ADA_RESULT3(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_DBG_RESULT0                                  **
 ** Register Offset     : 0x00D0                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_DBG_RESULT0(x)                          (x)
#define    BIT_GET_APB_WB_DBG_RESULT0(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_DBG_RESULT1                                  **
 ** Register Offset     : 0x00D4                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WB_DBG_RESULT1(x)                          (x)
#define    BIT_GET_APB_WB_DBG_RESULT1(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WB_DAC_DBG_DAT                                  **
 ** Register Offset     : 0x00D8                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WBDAC_IQ_TEST_DAT(x)                       (x)
#define    BIT_GET_APB_WBDAC_IQ_TEST_DAT(x)                   (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_BT_FUNC_DBG                                     **
 ** Register Offset     : 0x00DC                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_FUNC_DBG(x)                             (x)
#define    BIT_GET_APB_BT_FUNC_DBG(x)                         (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_ARCH_PORT                                   **
 ** Register Offset     : 0x0100                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_MCU_PROT_GLB                               (BIT_(16))
#define    BIT_APB_MCU_PROT_CHECK(x)                          ((x) & 0xFFFF)
#define    BIT_GET_APB_MCU_PROT_CHECK(x)                      ((x) & 0xFFFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI0                                   **
 ** Register Offset     : 0x0104                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_0(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_0(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI1                                   **
 ** Register Offset     : 0x0108                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_1(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_1(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI2                                   **
 ** Register Offset     : 0x010C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_2(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_2(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI3                                   **
 ** Register Offset     : 0x0110                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_3(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_3(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI4                                   **
 ** Register Offset     : 0x0114                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_4(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_4(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI5                                   **
 ** Register Offset     : 0x0118                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_5(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_5(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI6                                   **
 ** Register Offset     : 0x011C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_6(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_6(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI7                                   **
 ** Register Offset     : 0x0120                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_7(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_7(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI8                                   **
 ** Register Offset     : 0x0124                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_8(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_8(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI9                                   **
 ** Register Offset     : 0x0128                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_9(x)                          (x)
#define    BIT_GET_APB_RF_PARA_WIFI_9(x)                      (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI10                                  **
 ** Register Offset     : 0x012C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_10(x)                         (x)
#define    BIT_GET_APB_RF_PARA_WIFI_10(x)                     (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_WIFI11                                  **
 ** Register Offset     : 0x0130                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_WIFI_11(x)                         (x)
#define    BIT_GET_APB_RF_PARA_WIFI_11(x)                     (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT0                                     **
 ** Register Offset     : 0x0134                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_0(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_0(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT1                                     **
 ** Register Offset     : 0x0138                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_1(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_1(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT2                                     **
 ** Register Offset     : 0x013C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_2(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_2(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT3                                     **
 ** Register Offset     : 0x0140                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_3(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_3(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT4                                     **
 ** Register Offset     : 0x0144                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_4(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_4(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT5                                     **
 ** Register Offset     : 0x0148                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_5(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_5(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT6                                     **
 ** Register Offset     : 0x014C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_6(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_6(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT7                                     **
 ** Register Offset     : 0x0150                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_7(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_7(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT8                                     **
 ** Register Offset     : 0x0154                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_8(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_8(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT9                                     **
 ** Register Offset     : 0x0158                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_9(x)                            (x)
#define    BIT_GET_APB_RF_PARA_BT_9(x)                        (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT10                                    **
 ** Register Offset     : 0x015C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_10(x)                           (x)
#define    BIT_GET_APB_RF_PARA_BT_10(x)                       (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_BT11                                    **
 ** Register Offset     : 0x0160                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_RF_PARA_BT_11(x)                           (x)
#define    BIT_GET_APB_RF_PARA_BT_11(x)                       (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_PARA_NUM                                     **
 ** Register Offset     : 0x0164                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_SWITCH_PARA_NUM(x)                         ((x) & 0xFF)
#define    BIT_GET_APB_SWITCH_PARA_NUM(x)                     ((x) & 0xFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_TIME_SET                                   **
 ** Register Offset     : 0x0168                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_TIME_ARRANGE(x)                       (x)
#define    BIT_GET_APB_WIFI_TIME_ARRANGE(x)                   (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_BT_TIME_SET                                     **
 ** Register Offset     : 0x016C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_TIME_ARRANGE(x)                         (x)
#define    BIT_GET_APB_BT_TIME_ARRANGE(x)                     (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_WIFI_ACT_CTRL                                   **
 ** Register Offset     : 0x0170                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_COST_ACTIVE(x)                        (((x) & 0xFF) << 8)
#define    BIT_GET_APB_WIFI_COST_ACTIVE(x)                    (((x) >> 8)& 0xFF )
#define    BIT_APB_WIFI_COST_PRIORITY(x)                      ((x) & 0xFF)
#define    BIT_GET_APB_WIFI_COST_PRIORITY(x)                  ((x) & 0xFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_BT_ACT_CTRL                                     **
 ** Register Offset     : 0x0174                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_BT_COST_ACTIVE(x)                          (((x) & 0xFF) << 8)
#define    BIT_GET_APB_BT_COST_ACTIVE(x)                      (((x) >> 8)& 0xFF )
#define    BIT_APB_BT_COST_PRIORITY(x)                        ((x) & 0xFF)
#define    BIT_GET_APB_BT_COST_PRIORITY(x)                    ((x) & 0xFF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_SWITCH_MODE_CTRL                                **
 ** Register Offset     : 0x0178                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_PROTECT_EN                            (BIT_(5))
#define    BIT_APB_AUTO_ABORT_EN                              (BIT_(4))
#define    BIT_APB_TEST_EN                                    (BIT_(3))
#define    BIT_APB_TEST_WIFI_SEL                              (BIT_(2))
#define    BIT_APB_TEST_WIFI_ABORT                            (BIT_(1))
#define    BIT_APB_TEST_BT_ABORT                              (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_SWITCH_PROTECT_CTRL                             **
 ** Register Offset     : 0x017C                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_WIFI_PROTECT_TIME(x)                       (x)
#define    BIT_GET_APB_WIFI_PROTECT_TIME(x)                   (x)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_RF_MASTER_CTRL                                  **
 ** Register Offset     : 0x0180                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_SPI_SEL                                    (BIT_(6))
#define    BIT_APB_SPI_MODE(x)                                (((x) & 0x3) << 4)
#define    BIT_GET_APB_SPI_MODE(x)                            (((x) >> 4)& 0x3 )
#define    BIT_APB_SPI_HBIT_WIDTH(x)                          ((x) & 0xF)
#define    BIT_GET_APB_SPI_HBIT_WIDTH(x)                      ((x) & 0xF)


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_MISC_CTL                                    **
 ** Register Offset     : 0x0200                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_FPGA_SPI_SEL                               (BIT_(16))
#define    BIT_APB_TEST_DBG_MODE3                             (BIT_(10))
#define    BIT_APB_TEST_DBG_MODE2                             (BIT_(9))
#define    BIT_APB_TEST_DBG_MODE1                             (BIT_(8))
#define    BIT_APB_TEST_DBG_MODE0                             (BIT_(7))
#define    BIT_APB_BT_MAHB_SLEEP_EN                           (BIT_(6))
#define    BIT_APB_DSP2BT_IND                                 (BIT_(5))
#define    BIT_APB_ROM_CLK_FORCE_EN                           (BIT_(4))
#define    BIT_APB_ARM7_JTAG_EN                               (BIT_(3))
#define    BIT_APB_ARM7_CACHE_SIZE(x)                         (((x) & 0x3) << 1)
#define    BIT_GET_APB_ARM7_CACHE_SIZE(x)                     (((x) >> 1)& 0x3 )
#define    BIT_APB_ARM7_CACHE_EN                              (BIT_(0))


/**---------------------------------------------------------------------------**
 ** Register Name       : REG_APB_MISC_CTL1                                   **
 ** Register Offset     : 0x0204                                              **
 ** Description         :                                                     **
------------------------------------------------------------------------------**/
#define    BIT_APB_ARM7_HWRST1_REG(x)                         ((x) & 0xFF)
#define    BIT_GET_APB_ARM7_HWRST1_REG(x)                     ((x) & 0xFF)


#endif //_APB_REG_H
