#define RF_CTRL_REG_BASE 0

#define    DEBUG_32K_CONTROL_DOMAIN                ((RF_CTRL_REG_BASE + 0x0000) /4 )
#define    REG_32K_CONTROL_DOMAIN                  ((RF_CTRL_REG_BASE + 0x0004) /4 )
#define    LDO_ADDABBVCO_CTRL0                     ((RF_CTRL_REG_BASE + 0x0008) /4 )
#define    DEBUG_FM_CTRL_DEBUG0                    ((RF_CTRL_REG_BASE + 0x000c) /4 )
#define    REG_FM_CTRL_DEBUG0                      ((RF_CTRL_REG_BASE + 0x0010) /4 )
#define    DEBUG_FM_CTRL_DEBUG1                    ((RF_CTRL_REG_BASE + 0x0014) /4 )
#define    REG_FM_CTRL_DEBUG1                      ((RF_CTRL_REG_BASE + 0x0018) /4 )
#define    DEBUG_FM_FC_DEBUG                       ((RF_CTRL_REG_BASE + 0x001c) /4 )
#define    REG_FM_FC_DEBUG                         ((RF_CTRL_REG_BASE + 0x0020) /4 )
#define    DEBUG_FM_CTRL_DEBUG2                    ((RF_CTRL_REG_BASE + 0x0024) /4 )
#define    REG_FM_CTRL_DEBUG2                      ((RF_CTRL_REG_BASE + 0x0028) /4 )
#define    FM_LNA_OVERLOAD                         ((RF_CTRL_REG_BASE + 0x002c) /4 )
#define    FM_SX_AFC_ERR_MIN                       ((RF_CTRL_REG_BASE + 0x0030) /4 )
#define    FM_SX_STATE                             ((RF_CTRL_REG_BASE + 0x0034) /4 )
#define    FM_SX_VCO_VAL                           ((RF_CTRL_REG_BASE + 0x0038) /4 )
#define    FM_SX_CP_CUR                            ((RF_CTRL_REG_BASE + 0x003c) /4 )
#define    REG_FM_RC_DCOC_CAL                      ((RF_CTRL_REG_BASE + 0x0040) /4 )
#define    S0_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x0044) /4 )
#define    S1_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x0048) /4 )
#define    S2_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x004c) /4 )
#define    S3_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x0050) /4 )
#define    S4_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x0054) /4 )
#define    S5_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x0058) /4 )
#define    S6_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x005c) /4 )
#define    S7_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x0060) /4 )
#define    S8_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x0064) /4 )
#define    S9_FM_RC_DCOC_CAL                       ((RF_CTRL_REG_BASE + 0x0068) /4 )
#define    S10_FM_RC_DCOC_CAL                      ((RF_CTRL_REG_BASE + 0x006c) /4 )
#define    S11_FM_RC_DCOC_CAL                      ((RF_CTRL_REG_BASE + 0x0070) /4 )
#define    FM_RX_TIADCOC_CTRL0                     ((RF_CTRL_REG_BASE + 0x0074) /4 )
#define    FM_RX_PGA_CBANK_CTRL0                   ((RF_CTRL_REG_BASE + 0x0078) /4 )
#define    FM_RX_GAIN_CTRL0                        ((RF_CTRL_REG_BASE + 0x007c) /4 )
#define    FM_SX_DIVN_CTRL0                        ((RF_CTRL_REG_BASE + 0x0080) /4 )
#define    FM_SX_DIVNFRAC_CTRLH                    ((RF_CTRL_REG_BASE + 0x0084) /4 )
#define    FM_SX_DIVNFRAC_CTRLL                    ((RF_CTRL_REG_BASE + 0x0088) /4 )
#define    FM_SX_LODIV_CTRL0                       ((RF_CTRL_REG_BASE + 0x008c) /4 )
#define    FM_SX_LDO_CTRL0                         ((RF_CTRL_REG_BASE + 0x0090) /4 )
#define    FM_SX_DSMPFD_CTRL0                      ((RF_CTRL_REG_BASE + 0x0094) /4 )
#define    FM_SX_CP_CTRL0                          ((RF_CTRL_REG_BASE + 0x0098) /4 )
#define    FM_SX_LPF_CTRL0                         ((RF_CTRL_REG_BASE + 0x009c) /4 )
#define    FM_SX_VCO_CTRL0                         ((RF_CTRL_REG_BASE + 0x00a0) /4 )
#define    FM_SX_AFC_START                         ((RF_CTRL_REG_BASE + 0x00a4) /4 )
#define    FM_SX_AFC_CTRL0                         ((RF_CTRL_REG_BASE + 0x00a8) /4 )
#define    FM_SX_VCOCAP_CTRL0                      ((RF_CTRL_REG_BASE + 0x00ac) /4 )
#define    FM_SX_VCOCAP_CTRL1                      ((RF_CTRL_REG_BASE + 0x00b0) /4 )
#define    FM_SX_PK_CTRL0                          ((RF_CTRL_REG_BASE + 0x00b4) /4 )
#define    FM_RX_RF_CTRL0                          ((RF_CTRL_REG_BASE + 0x00b8) /4 )
#define    FM_RX_RF_CTRL1                          ((RF_CTRL_REG_BASE + 0x00bc) /4 )
#define    FM_RX_RF_CTRL2                          ((RF_CTRL_REG_BASE + 0x00c0) /4 )
#define    FM_RX_RF_CTRL3                          ((RF_CTRL_REG_BASE + 0x00c4) /4 )
#define    DEBUG_FM_ADC_DEBUG                      ((RF_CTRL_REG_BASE + 0x00c8) /4 )
#define    REG_FM_ADC_DEBUG                        ((RF_CTRL_REG_BASE + 0x00cc) /4 )
#define    POLAR_FM_ADC_DEBUG                      ((RF_CTRL_REG_BASE + 0x00d0) /4 )
#define    FM_ADC_DATI                             ((RF_CTRL_REG_BASE + 0x00d4) /4 )
#define    FM_ADC_DATQ                             ((RF_CTRL_REG_BASE + 0x00d8) /4 )
#define    FM_ADC_CTRL0                            ((RF_CTRL_REG_BASE + 0x00dc) /4 )
#define    FM_ADC_CTRL1                            ((RF_CTRL_REG_BASE + 0x00e0) /4 )
#define    MARLIN_RFTOP_RESERVED_CTRL0             ((RF_CTRL_REG_BASE + 0x00e4) /4 )
#define    MARLIN_RFTOP_RESERVED_CTRL1             ((RF_CTRL_REG_BASE + 0x00e8) /4 )
#define    MARLIN_RFTOP_RESERVED_CTRL2             ((RF_CTRL_REG_BASE + 0x00ec) /4 )
#define    AD_MARLIN_RFTOP_RESERVED                ((RF_CTRL_REG_BASE + 0x00f0) /4 )
#define    TEST_PIN_DEBUG                          ((RF_CTRL_REG_BASE + 0x00f4) /4 )
#define    RF_TRST_CTRL0                           ((RF_CTRL_REG_BASE + 0x00f8) /4 )
#define    REG_RF_FM_OTHERS_CTRL0                  ((RF_CTRL_REG_BASE + 0x00fc) /4 )
#define    RF_FM_OTHERS_CTRL0                      ((RF_CTRL_REG_BASE + 0x0100) /4 )
#define    RF_FM_OTHERS_CTRL1                      ((RF_CTRL_REG_BASE + 0x0104) /4 )
#define    RF_SOFT_RST                             ((RF_CTRL_REG_BASE + 0x0108) /4 )
#define    RF_HW_RST_CTRL                          ((RF_CTRL_REG_BASE + 0x010c) /4 )
#define    FM_MODE                                 ((RF_CTRL_REG_BASE + 0x0110) /4 )
#define    S0_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x0114) /4 )
#define    S1_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x0118) /4 )
#define    S2_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x011c) /4 )
#define    S3_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x0120) /4 )
#define    S4_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x0124) /4 )
#define    S5_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x0128) /4 )
#define    S6_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x012c) /4 )
#define    S7_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x0130) /4 )
#define    S8_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x0134) /4 )
#define    S9_FM_DECODE_CFG0                       ((RF_CTRL_REG_BASE + 0x0138) /4 )
#define    S10_FM_DECODE_CFG0                      ((RF_CTRL_REG_BASE + 0x013c) /4 )
#define    S11_FM_DECODE_CFG0                      ((RF_CTRL_REG_BASE + 0x0140) /4 )
#define    S0_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x0144) /4 )
#define    S1_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x0148) /4 )
#define    S2_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x014c) /4 )
#define    S3_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x0150) /4 )
#define    S4_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x0154) /4 )
#define    S5_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x0158) /4 )
#define    S6_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x015c) /4 )
#define    S7_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x0160) /4 )
#define    S8_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x0164) /4 )
#define    S9_FM_DECODE_CFG1                       ((RF_CTRL_REG_BASE + 0x0168) /4 )
#define    S10_FM_DECODE_CFG1                      ((RF_CTRL_REG_BASE + 0x016c) /4 )
#define    S11_FM_DECODE_CFG1                      ((RF_CTRL_REG_BASE + 0x0170) /4 )
#define    FM_CHARGE_TIME0                         ((RF_CTRL_REG_BASE + 0x0174) /4 )
#define    FM_CHARGE_TIME1                         ((RF_CTRL_REG_BASE + 0x0178) /4 )
#define    FM_CHARGE_TIME2                         ((RF_CTRL_REG_BASE + 0x017c) /4 )
#define    FM_CHARGE_TIME3                         ((RF_CTRL_REG_BASE + 0x0180) /4 )
#define    FM_CHARGE_TIME4                         ((RF_CTRL_REG_BASE + 0x0184) /4 )
#define    FM_CHARGE_TIME5                         ((RF_CTRL_REG_BASE + 0x0188) /4 )
#define    FM_CHARGE_TIME6                         ((RF_CTRL_REG_BASE + 0x018c) /4 )
#define    ADA_CLK_CFG                             ((RF_CTRL_REG_BASE + 0x0190) /4 )
#define    ADC_DAT_FORMAT                          ((RF_CTRL_REG_BASE + 0x0194) /4 )
#define    ADA_DAT_MINUS_EN                        ((RF_CTRL_REG_BASE + 0x0198) /4 )
#define    OW_CFG                                  ((RF_CTRL_REG_BASE + 0x019c) /4 )
#define    OW_ACTION                               ((RF_CTRL_REG_BASE + 0x01a0) /4 )
#define    FM_ADC_CFG                              ((RF_CTRL_REG_BASE + 0x01a4) /4 )
#define    FM_ADC_PD_DI                            ((RF_CTRL_REG_BASE + 0x01a8) /4 )
#define    FM_ADC_PD_DQ                            ((RF_CTRL_REG_BASE + 0x01ac) /4 )
#define    FM_DCOC_MODE                            ((RF_CTRL_REG_BASE + 0x01b0) /4 )
#define    FM_RX_DI_RD                             ((RF_CTRL_REG_BASE + 0x01b4) /4 )
#define    FM_RX_DQ_RD                             ((RF_CTRL_REG_BASE + 0x01b8) /4 )
#define    S0_RF_REG_RESERVED                      ((RF_CTRL_REG_BASE + 0x01bc) /4 )
#define    S1_RF_REG_RESERVED                      ((RF_CTRL_REG_BASE + 0x01c0) /4 )
#define    S2_RF_REG_RESERVED                      ((RF_CTRL_REG_BASE + 0x01c4) /4 )
#define    S3_RF_REG_RESERVED                      ((RF_CTRL_REG_BASE + 0x01c8) /4 )
#define    S4_RF_REG_RESERVED                      ((RF_CTRL_REG_BASE + 0x01cc) /4 )
#define    S5_RF_REG_RESERVED                      ((RF_CTRL_REG_BASE + 0x01d0) /4 )
#define    S6_RF_REG_RESERVED                      ((RF_CTRL_REG_BASE + 0x01d4) /4 )
#define    S7_RF_REG_RESERVED                      ((RF_CTRL_REG_BASE + 0x01d8) /4 )


#define 	WB_MANUAL_EN   					(BIT_15)
#define 	WB_SEL_MANUAL_EN   				(BIT_9)
#define 	DA_ISM_SX_AFC_STARTL2H			(BIT_15)
#define 	DA_ISM_SX_AFC_RESETN			(BIT_14)
#define 	DA_ISM_SX_DSM_RESETN			(BIT_13)

#define 	DA_ISM_RX_GLNA					(BIT_15)
#define 	DA_ISM_RX_ABB_GC_BQ				(BIT_14)
#define 	DA_WF_RX_ABB_GC_1rd				(BIT_13)

#define 	DEBUG_DA_ISM_RX_ABB_DCOC_DAC_I	(BIT_14)
#define 	DEBUG_DA_ISM_RX_ABB_DCOC_DAC_Q	(BIT_13)

#define 	debug_DA_ISM_TXDAC_GC			(BIT_15)
#define 	debug_DA_ISM_TXGM_GC			(BIT_14)
#define 	debug_DA_ISM_TXMOD_GC			(BIT_13)

#define 	debug_DA_ISM_ADC_EN				(BIT_15)
#define 	debug_DA_ISMADCCLK_EN			(BIT_14)
#define 	debug_DA_ISM_ADC_RSTN			(BIT_13)
#define 	debug_DA_WF_ADCCLK_SEL120ML 	(BIT_12)

#define 	debug_DA_ISM_RSSIADC_EN			(BIT_15)
#define 	debug_DA_ISMRSSIADCCLK_EN		(BIT_14)
#define 	debug_DA_ISM_RSSIADC_RSTN		(BIT_13)

#define 	debug_DA_ISM_DAC_EN				(BIT_15)
#define 	debug_DA_ISM_TXBIAS_EN			(BIT_14)
#define 	debug_DA_ISMDACCLK_EN			(BIT_13)
#define 	debug_DA_ISM_DAC_WIFI_BT_SEL	(BIT_12)
#define 	debug_DA_ISM_DAC_RSTN			(BIT_11)

#define 	debug_DA_FM_SHORTANT_H			(BIT_15)
#define 	debug_DA_FM_SX_DSM_RESETN		(BIT_14)
#define 	debug_DA_FM_SX_AFC_RESETN		(BIT_13)

#define 	FM_CAL_RC_MODE					(BIT_15)
#define 	DEBUG_DA_FM_PGA_DCOCI			(BIT_14)
#define 	DEBUG_DA_FM_PGA_DCOCQ			(BIT_13)

#define 	debug_DA_FM_ADC_EN				(BIT_15)
#define 	debug_DA_FMADCCLK_EN			(BIT_14)
#define 	debug_DA_FM_ADC_RSTN			(BIT_13)

#define 	reg_DA_FM_ADC_EN				(BIT_15)
#define 	reg_DA_FMADCCLK_EN				(BIT_14)
#define 	reg_DA_FM_ADC_RSTN				(BIT_13)

#define 	reg_DA_FM_SHORTANT_H			(BIT_15)
#define 	reg_DA_FM_SX_DSM_RESETN			(BIT_14)
#define 	reg_DA_FM_SX_AFC_RESETN			(BIT_13)

#define 	RG_FM_SX_AFC_START				(BIT_15)
