/******************************************************************************
 ** File Name:      app_msgtable.h                                        	  *
 ** Author:         Sun Yu                                                 	  *
 ** Date:           2010-05-26                                                *
 ** Copyright:      Copyright 2001-2010 by Spreadtrum Communications,Inc.     *
 **                 All Rights Reserved.                                      *
 **                 This software is supplied under the terms of a license    *
 **                 agreement or non-disclosure agreement with Spreadtrum.    *
 **                 Passing on and copying of this document,and communication *
 **                 of its contents is not permitted without prior written    *
 **                 authorization.                                            *
 ** Description:    This is a initial version.                                *
 ******************************************************************************

 ******************************************************************************
 **                        Edit History                                       *
 ** --------------------------------------------------------------------------*
 ** DATE           NAME             Description:                              *
 **---------------------------------------------------------------------------*
 ** 26/5/2010      Sun Yu           create                                    *
 ******************************************************************************/

{APP_MN_NETWORK_STATUS_IND               , TEXT("APP_MN_NETWORK_STATUS_IND")}, 
{APP_MN_NETWORK_INFO_IND                 , TEXT("APP_MN_NETWORK_INFO_IND")}, 
{APP_MN_PLMN_LIST_CNF                    , TEXT("APP_MN_PLMN_LIST_CNF")}, 
{APP_MN_PLMN_SELECT_CNF                  , TEXT("APP_MN_PLMN_SELECT_CNF")},
{APP_MN_PLMN_READ_CNF                    , TEXT("APP_MN_PLMN_READ_CNF")}, 
{APP_MN_PLMN_WRITE_CNF                   , TEXT("APP_MN_PLMN_WRITE_CNF")}, 
//#ifdef PRODUCT_DM
{APP_MN_AT_TRACE_IND                     , TEXT("APP_MN_AT_TRACE_IND")}, 
{APP_MN_CURRENT_RAT_IND                  , TEXT("APP_MN_CURRENT_RAT_IND")}, 
//#endif
{APP_MN_TD_NCELL_INFO_IND                , TEXT("APP_MN_TD_NCELL_INFO_IND")}, 
{APP_MN_SIM_GET_PIN_IND                  , TEXT("APP_MN_SIM_GET_PIN_IND")}, 
{APP_MN_SIM_READY_IND                    , TEXT("APP_MN_SIM_READY_IND")}, 
{APP_MN_SIM_NOT_READY_IND                , TEXT("APP_MN_SIM_NOT_READY_IND")}, 
{APP_MN_SIM_PIN_FUNC_CNF                 , TEXT("APP_MN_SIM_PIN_FUNC_CNF")}, 
{APP_MN_SCELL_RSSI_IND                   , TEXT("APP_MN_SCELL_RSSI_IND")}, 
{APP_MN_MS_POWERING_OFF_IND              , TEXT("APP_MN_MS_POWERING_OFF_IND")}, 
{APP_MN_DEACTIVE_PS_CNF                  , TEXT("APP_MN_DEACTIVE_PS_CNF")}, 
//#ifdef PRODUCT_DM
{APP_MN_SIM_POWER_ON_CNF                  , TEXT("APP_MN_SIM_POWER_ON_CNF")}, 
{APP_MN_SIM_PIN_CHECK_IND                  , TEXT("APP_MN_SIM_PIN_CHECK_IND")}, 
{APP_MN_SIM_POWER_OFF_CNF                  , TEXT("APP_MN_SIM_POWER_OFF_CNF")}, 
{APP_MN_PS_POWER_ON_CNF                  , TEXT("APP_MN_PS_POWER_ON_CNF")}, 
{APP_MN_PS_POWER_OFF_CNF                  , TEXT("APP_MN_PS_POWER_OFF_CNF")},
//#endif 
{APP_MN_NCELL_RSSI_CNF                   , TEXT("APP_MN_NCELL_RSSI_CNF")}, 
{APP_MN_AOC_MODIFIED_IND                 , TEXT("APP_MN_AOC_MODIFIED_IND")}, 
{APP_MN_FDN_SERVICE_IND                  , TEXT("APP_MN_FDN_SERVICE_IND")}, 
{APP_MN_GPRS_ATTACH_RESULT               , TEXT("APP_MN_GPRS_ATTACH_RESULT")}, 
{APP_MN_GPRS_DETACH_RESULT               , TEXT("APP_MN_GPRS_DETACH_RESULT")}, 
{APP_MN_DETACH_GSM_CNF                   , TEXT("APP_MN_DETACH_GSM_CNF")}, 
{APP_MN_PUCT_INFO_CNF                    , TEXT("APP_MN_PUCT_INFO_CNF")}, 
{APP_MN_PS_READY_IND                     , TEXT("APP_MN_PS_READY_IND")}, 
{APP_MN_SET_PREF_MODE_CNF                , TEXT("APP_MN_SET_PREF_MODE_CNF")}, 
{APP_MN_SET_BAND_CNF                     , TEXT("APP_MN_SET_BAND_CNF")}, 
{APP_MN_SET_SERVICE_TYPE_CNF             , TEXT("APP_MN_SET_SERVICE_TYPE_CNF")}, 
{APP_MN_SET_ROAM_MODE_CNF                , TEXT("APP_MN_SET_ROAM_MODE_CNF")}, 
{APP_MN_DISPLAY_PLMN_IND                 , TEXT("APP_MN_DISPLAY_PLMN_IND")}, 

{APP_MN_NETNAME_READY_IND                , TEXT("APP_MN_NETNAME_READY_IND")}, 

{APP_MN_MSISDN_UPDATE_CNF                , TEXT("APP_MN_MSISDN_UPDATE_CNF")}, 
{APP_MN_ADN_UPDATE_CNF                   , TEXT("APP_MN_ADN_UPDATE_CNF")}, 
{APP_MN_FDN_UPDATE_CNF                   , TEXT("APP_MN_FDN_UPDATE_CNF")}, 
{APP_MN_LND_UPDATE_CNF                   , TEXT("APP_MN_LND_UPDATE_CNF")},
{APP_MN_GET_FREE_EXT_INFO_CNF            , TEXT("APP_MN_GET_FREE_EXT_INFO_CNF")}, 

{APP_MN_CRSM_CNF                         , TEXT("APP_MN_CRSM_CNF")}, 
{APP_MN_SIM_RECORD_NUM_CNF               , TEXT("APP_MN_SIM_RECORD_NUM_CNF")}, 
{APP_MN_SIM_RECORD_READ_CNF              , TEXT("APP_MN_SIM_RECORD_READ_CNF")}, 
{APP_MN_SIM_BINARY_READ_CNF              , TEXT("APP_MN_SIM_BINARY_READ_CNF")}, 
{APP_MN_SIM_BINARY_UPDATE_CNF            , TEXT("APP_MN_SIM_BINARY_UPDATE_CNF")}, 

{APP_MN_LND_READY_IND                     , TEXT("APP_MN_LND_READY_IND")}, 
{APP_MN_CALL_READY_IND                   , TEXT("APP_MN_CALL_READY_IND")}, 
{APP_MN_CALL_START_IND                   , TEXT("APP_MN_CALL_START_IND")}, 
{APP_MN_ALERTING_IND                     , TEXT("APP_MN_ALERTING_IND")}, 
{APP_MN_SETUP_COMPLETE_IND               , TEXT("APP_MN_SETUP_COMPLETE_IND")}, 
{APP_MN_SETUP_COMPLETE_CNF               , TEXT("APP_MN_SETUP_COMPLETE_CNF")}, 
{APP_MN_CALL_DISCONNECTED_IND            , TEXT("APP_MN_CALL_DISCONNECTED_IND")}, 
{APP_MN_CALL_ERR_IND                     , TEXT("APP_MN_CALL_ERR_IND")}, 
{APP_MN_SETUP_IND                        , TEXT("APP_MN_SETUP_IND")}, 
{APP_MN_START_DTMF_CNF                   , TEXT("APP_MN_START_DTMF_CNF")}, 
{APP_MN_STOP_DTMF_CNF                    , TEXT("APP_MN_STOP_DTMF_CNF")}, 
{APP_MN_CALL_HELD_CNF                    , TEXT("APP_MN_CALL_HELD_CNF")}, 
{APP_MN_CALL_HELD_IND                    , TEXT("APP_MN_CALL_HELD_IND")}, 
{APP_MN_CALL_HOLDING_IND                 , TEXT("APP_MN_CALL_HOLDING_IND")}, 
{APP_MN_CALL_RETRIEVED_CNF               , TEXT("APP_MN_CALL_RETRIEVED_CNF")}, 
{APP_MN_CALL_RETRIEVED_IND               , TEXT("APP_MN_CALL_RETRIEVED_IND")}, 
{APP_MN_CALL_RETRIEVING_IND              , TEXT("APP_MN_CALL_RETRIEVING_IND")}, 
{APP_MN_BUILDING_MPTY_IND                , TEXT("APP_MN_BUILDING_MPTY_IND")}, 
{APP_MN_SPLITTING_MPTY_IND               , TEXT("APP_MN_SPLITTING_MPTY_IND")}, 
{APP_MN_CALL_SWAP_IND                    , TEXT("APP_MN_CALL_SWAP_IND")}, 
{APP_MN_CALL_SWAP_CNF                    , TEXT("APP_MN_CALL_SWAP_CNF")}, 
{APP_MN_CALL_WAIT_IND                    , TEXT("APP_MN_CALL_WAIT_IND")}, 
{APP_MN_CALL_NOTIFY_IND                  , TEXT("APP_MN_CALL_NOTIFY_IND")}, 
{APP_MN_CALL_MODIFY_CNF                  , TEXT("APP_MN_CALL_MODIFY_CNF")}, 
{APP_MN_CALL_MODIFY_IND                  , TEXT("APP_MN_CALL_MODIFY_IND")}, 
{APP_MN_CALL_BARRED_IND                  , TEXT("APP_MN_CALL_BARRED_IND")}, 
{APP_MN_BUILD_MPTY_CNF                   , TEXT("APP_MN_BUILD_MPTY_CNF")}, 
{APP_MN_BUILD_MPTY_IND                   , TEXT("APP_MN_BUILD_MPTY_IND")}, 
{APP_MN_SPLIT_MPTY_CNF                   , TEXT("APP_MN_SPLIT_MPTY_CNF")}, 
{APP_MN_ACMMAX_IND                       , TEXT("APP_MN_ACMMAX_IND")}, 
{APP_MN_TMPTY_EXP_IND                    , TEXT("APP_MN_TMPTY_EXP_IND")}, 
{APP_MN_SYNC_IND                         , TEXT("APP_MN_SYNC_IND")}, 
{APP_MN_PROGRESS_IND                     , TEXT("APP_MN_PROGRESS_IND")}, 
{APP_MN_USER_TO_USER_IND                 , TEXT("APP_MN_USER_TO_USER_IND")}, 
{APP_MN_DISCONNECTING_IND                , TEXT("APP_MN_DISCONNECTING_IND")}, 
{APP_MN_CALL_FORWARD_IND                 , TEXT("APP_MN_CALL_FORWARD_IND")}, 
{APP_MN_FORWARD_STATUS_IND               , TEXT("APP_MN_FORWARD_STATUS_IND")}, 
{APP_MN_CONNECTING_IND                   , TEXT("APP_MN_CONNECTING_IND")}, 
{APP_MN_DISC_INFO_IND                    , TEXT("APP_MN_DISC_INFO_IND")}, 
/* +ccbs */
{APP_MN_CCBS_ACTIVATE_IND                , TEXT("APP_MN_CCBS_ACTIVATE_IND")}, 
{APP_MN_CCBS_RECALL_IND                  , TEXT("APP_MN_CCBS_RECALL_IND")}, 
{APP_MN_CCBS_ERASE_CNF                   , TEXT("APP_MN_CCBS_ERASE_CNF")}, 
/* -ccbs */
//#ifdef PRODUCT_DM
/* +cr135327 */
{APP_MN_CLIR_SUPP_REJ_IND                    , TEXT("APP_MN_CLIR_SUPP_REJ_IND")}, 
{APP_MN_CALL_DEFLECT_IND                    , TEXT("APP_MN_CALL_DEFLECT_IND")}, 
/* -cr135327 */
//#endif
{APP_MN_MTACT_RESPOND_MODE_CNF           , TEXT("APP_MN_MTACT_RESPOND_MODE_CNF")}, 
{APP_MN_ACTIVATE_PDP_CONTEXT_CNF         , TEXT("APP_MN_ACTIVATE_PDP_CONTEXT_CNF")}, 
{APP_MN_SET_QOS_CNF                      , TEXT("APP_MN_SET_QOS_CNF")}, 
{APP_MN_SET_MIN_QOS_CNF                  , TEXT("APP_MN_SET_MIN_QOS_CNF")}, 
{APP_MN_SET_PDP_CONTEXT_CNF              , TEXT("APP_MN_SET_PDP_CONTEXT_CNF")}, 
{APP_MN_DEACTIVATE_PDP_CONTEXT_CNF       , TEXT("APP_MN_DEACTIVATE_PDP_CONTEXT_CNF")}, 
{APP_MN_DELETE_PDP_CONTEXT_CNF           , TEXT("APP_MN_DELETE_PDP_CONTEXT_CNF")}, 
{APP_MN_DELETE_MIN_QOS_CNF               , TEXT("APP_MN_DELETE_MIN_QOS_CNF")}, 
{APP_MN_DELETE_QOS_CNF                   , TEXT("APP_MN_DELETE_QOS_CNF")}, 
{APP_MN_PUSH_GPRS_DATA_CNF               , TEXT("APP_MN_PUSH_GPRS_DATA_CNF")}, 
{APP_MN_DEACTIVATE_PDP_CONTEXT_IND       , TEXT("APP_MN_DEACTIVATE_PDP_CONTEXT_IND")}, 
{APP_MN_SMS_READY_IND                    , TEXT("APP_MN_SMS_READY_IND")}, 
{APP_MN_SMS_MEM_FULL_IND                 , TEXT("APP_MN_SMS_MEM_FULL_IND")}, 
#ifdef GSM_CUSTOMER_AFP_SUPPORT
{APP_MN_SMS_MEM_FULL_IND_EX              , TEXT("APP_MN_SMS_MEM_FULL_IND_EX")}, 
#endif
{APP_MN_SMS_MEM_OVER_FLOW_IND            , TEXT("APP_MN_SMS_MEM_OVER_FLOW_IND")},
{APP_MN_READ_SMS_CNF                     , TEXT("APP_MN_READ_SMS_CNF")}, 
{APP_MN_UPDATE_SMS_STATE_CNF             , TEXT("APP_MN_UPDATE_SMS_STATE_CNF")}, 
{APP_MN_READ_SMS_STATUS_REPORT_CNF       , TEXT("APP_MN_READ_SMS_STATUS_REPORT_CNF")}, 
{APP_MN_SEND_SMS_CNF                     , TEXT("APP_MN_SEND_SMS_CNF")}, 
{APP_MN_WRITE_SMS_CNF                    , TEXT("APP_MN_WRITE_SMS_CNF")}, 
{APP_MN_EDIT_SMS_CNF                     , TEXT("APP_MN_EDIT_SMS_CNF")}, 
{APP_MN_SMS_IND                          , TEXT("APP_MN_SMS_IND")}, 
{APP_MN_SMS_STATUS_REPORT_IND            , TEXT("APP_MN_SMS_STATUS_REPORT_IND")}, 
{APP_MN_READ_SMS_PARAM_CNF               , TEXT("APP_MN_READ_SMS_PARAM_CNF")}, 
{APP_MN_WRITE_SMS_PARAM_CNF              , TEXT("APP_MN_WRITE_SMS_PARAM_CNF")}, 
{APP_MN_DELETE_ALL_SMS_CNF               , TEXT("APP_MN_DELETE_ALL_SMS_CNF")}, 
{APP_MN_SET_ASSERT_SMS_DESTADDR_CNF      , TEXT("APP_MN_SET_ASSERT_SMS_DESTADDR_CNF")}, 
{APP_MN_SET_SMS_RECEIVE_FUNC_CNF         , TEXT("APP_MN_SET_SMS_RECEIVE_FUNC_CNF")}, 
{APP_MN_SMSCB_MSG_IND                    , TEXT("APP_MN_SMSCB_MSG_IND")}, 
{APP_MN_SMSCB_MACRO_MSG_IND              , TEXT("APP_MN_SMSCB_MACRO_MSG_IND")}, 
{APP_MN_SMSCB_REJ_IND                    , TEXT("APP_MN_SMSCB_REJ_IND")}, 
{APP_MN_SMSCB_MSG_PAGES_IND              , TEXT("APP_MN_SMSCB_MSG_PAGES_IND")},
/* +cr250176 */
{APP_MN_SMSCB_SET_PARAM_CNF                    , TEXT("APP_MN_SMSCB_SET_PARAM_CNF")}, 
{APP_MN_SMSCB_GET_PARAM_CNF                    , TEXT("APP_MN_SMSCB_GET_PARAM_CNF")}, 
{APP_MN_TDPS_SMSCB_MSG_IND                    , TEXT("APP_MN_TDPS_SMSCB_MSG_IND")}, /* cr250176_NEW */
/* -cr250176 */
{APP_MN_GET_PASSWORD_IND                 , TEXT("APP_MN_GET_PASSWORD_IND")}, 
{APP_MN_USSD_IND                         , TEXT("APP_MN_USSD_IND")}, 
{APP_MN_USSD_NOTIFY_IND                  , TEXT("APP_MN_USSD_NOTIFY_IND")}, 
{APP_MN_RELEASE_SS_IND                   , TEXT("APP_MN_RELEASE_SS_IND")}, 
{APP_MN_BEGIN_REGISTER_SS                , TEXT("APP_MN_BEGIN_REGISTER_SS")}, 
{APP_MN_BEGIN_ERASE_SS                   , TEXT("APP_MN_BEGIN_ERASE_SS")}, 
{APP_MN_BEGIN_ACTIVATE_SS                , TEXT("APP_MN_BEGIN_ACTIVATE_SS")}, 
{APP_MN_BEGIN_DEACTIVATE_SS              , TEXT("APP_MN_BEGIN_DEACTIVATE_SS")}, 
{APP_MN_BEGIN_INTERROGATE_SS             , TEXT("APP_MN_BEGIN_INTERROGATE_SS")}, 
{APP_MN_BEGIN_REGISTER_PASSWORD          , TEXT("APP_MN_BEGIN_REGISTER_PASSWORD")}, 
{APP_MN_BEGIN_USSD_SERVICE               , TEXT("APP_MN_BEGIN_USSD_SERVICE")}, 
{APP_MN_REGISTER_SS_CNF                  , TEXT("APP_MN_REGISTER_SS_CNF")}, 
{APP_MN_ERASE_SS_CNF                     , TEXT("APP_MN_ERASE_SS_CNF")}, 
{APP_MN_ACTIVATE_SS_CNF                  , TEXT("APP_MN_ACTIVATE_SS_CNF")}, 
{APP_MN_DEACTIVATE_SS_CNF                , TEXT("APP_MN_DEACTIVATE_SS_CNF")}, 
{APP_MN_INTERROGATE_CNF                  , TEXT("APP_MN_INTERROGATE_CNF")}, 
{APP_MN_REGISTER_PASSWORD_CNF            , TEXT("APP_MN_REGISTER_PASSWORD_CNF")}, 
{APP_MN_SS_BUSYING_IND                   , TEXT("APP_MN_SS_BUSYING_IND")}, 
{APP_MN_USSD_SERVICE_CNF                 , TEXT("APP_MN_USSD_SERVICE_CNF")}, 
{SIMAT_SETUP_EVENT_LIST_REQ              , TEXT("SIMAT_SETUP_EVENT_LIST_REQ")}, 
{APP_MN_SIMAT_REFRESH_IND                , TEXT("APP_MN_SIMAT_REFRESH_IND")}, 
{APP_MN_SIMAT_DISPLAY_TEXT_IND           , TEXT("APP_MN_SIMAT_DISPLAY_TEXT_IND")}, 
{APP_MN_SIMAT_GET_INKEY_IND              , TEXT("APP_MN_SIMAT_GET_INKEY_IND")}, 
{APP_MN_SIMAT_GET_INPUT_IND              , TEXT("APP_MN_SIMAT_GET_INPUT_IND")}, 
{APP_MN_SIMAT_PLAY_TONE_IND              , TEXT("APP_MN_SIMAT_PLAY_TONE_IND")}, 
{APP_MN_SIMAT_SETUP_MENU_IND             , TEXT("APP_MN_SIMAT_SETUP_MENU_IND")}, 
{APP_MN_SIMAT_SELECT_ITEM_IND            , TEXT("APP_MN_SIMAT_SELECT_ITEM_IND")}, 
{SIMAT_GET_DT_TZ_REQ                     , TEXT("SIMAT_GET_DT_TZ_REQ")}, 
{SIMAT_GET_LANG_REQ                      , TEXT("SIMAT_GET_LANG_REQ")}, 
{APP_MN_SIMAT_SETUP_IDLE_TEXT_IND        , TEXT("APP_MN_SIMAT_SETUP_IDLE_TEXT_IND")}, 
{APP_MN_SIMAT_LANG_NOTIFY_IND            , TEXT("APP_MN_SIMAT_LANG_NOTIFY_IND")}, 
{APP_MN_SIMAT_SEND_SMS_IND               , TEXT("APP_MN_SIMAT_SEND_SMS_IND")}, 
{SIMAT_SMS_PP_RSP                        , TEXT("SIMAT_SMS_PP_RSP")}, 
{SIMAT_SMS_CB_RSP                        , TEXT("SIMAT_SMS_CB_RSP")}, 
{APP_MN_SIMAT_SMS_CTL_TO_MMI_IND         , TEXT("APP_MN_SIMAT_SMS_CTL_TO_MMI_IND")}, 
{APP_MN_SIMAT_SEND_SS_IND                , TEXT("APP_MN_SIMAT_SEND_SS_IND")}, 
{APP_MN_SIMAT_SEND_USSD_IND              , TEXT("APP_MN_SIMAT_SEND_USSD_IND")}, 
{SIMAT_MO_SS_CONTROL_RSP                 , TEXT("SIMAT_MO_SS_CONTROL_RSP")}, 
{SIMAT_MO_USSD_CONTROL_RSP               , TEXT("SIMAT_MO_USSD_CONTROL_RSP")}, 
{APP_MN_SIMAT_SETUP_CALL_IND             , TEXT("APP_MN_SIMAT_SETUP_CALL_IND")}, 
{APP_MN_SIMAT_SEND_DTMF_IND              , TEXT("APP_MN_SIMAT_SEND_DTMF_IND")}, 
{SIMAT_MO_CC_RSP                         , TEXT("SIMAT_MO_CC_RSP")}, 
{APP_MN_SIMAT_CC_TO_MMI_IND              , TEXT("APP_MN_SIMAT_CC_TO_MMI_IND")}, 
{SIMAT_BC_SMS_RSP                        , TEXT("SIMAT_BC_SMS_RSP")}, 
{SIMAT_PP_SMS_RSP                        , TEXT("SIMAT_PP_SMS_RSP")}, 
{APP_MN_SIMAT_PRO_LOCAL_INFO_IND         , TEXT("APP_MN_SIMAT_PRO_LOCAL_INFO_IND")}, 
{APP_MN_SIMAT_REFRESH_CNF                , TEXT("APP_MN_SIMAT_REFRESH_CNF")}, 
{APP_MN_SIMAT_MORE_TIME_IND              , TEXT("APP_MN_SIMAT_MORE_TIME_IND")}, 
{SIMAT_SESSION_TERMINATED_IND            , TEXT("SIMAT_SESSION_TERMINATED_IND")}, 
{APP_MN_SIMAT_SEND_DATA_IND            , TEXT("APP_MN_SIMAT_SEND_DATA_IND")}, 
{APP_MN_SIMAT_RECEIVE_DATA_IND            , TEXT("APP_MN_SIMAT_RECEIVE_DATA_IND")}, 
{APP_MN_SIMAT_LAUNCH_BROWSER_IND            , TEXT("APP_MN_SIMAT_LAUNCH_BROWSER_IND")}, 
{APP_SIMAT_OPEN_CHANNEL_IND            , TEXT("APP_SIMAT_OPEN_CHANNEL_IND")}, 
{APP_SIMAT_CLOSE_CHANNEL_IND            , TEXT("APP_SIMAT_CLOSE_CHANNEL_IND")}, 
{APP_SIMAT_GET_CHANNEL_STATUS_IND            , TEXT("APP_SIMAT_GET_CHANNEL_STATUS_IND")}, 
{APP_MN_SIMAT_DISPLAY_MULTIMEDIA_MSG_IND            , TEXT("APP_MN_SIMAT_DISPLAY_MULTIMEDIA_MSG_IND")}, 
{APP_MN_SIMAT_RETRIEVE_MULTIMEDIA_MSG_IND            , TEXT("APP_MN_SIMAT_RETRIEVE_MULTIMEDIA_MSG_IND")}, 
{APP_MN_SIMAT_SUBMIT_MULTIMEDIA_MSG_IND            , TEXT("APP_MN_SIMAT_SUBMIT_MULTIMEDIA_MSG_IND")}, 
{APP_L1_GET_AFC_CNF                      , TEXT("APP_L1_GET_AFC_CNF")}, 
{APP_L1_GET_PA_CNF                       , TEXT("APP_L1_GET_PA_CNF")}, 
{APP_L1_GET_AGC_CNF                      , TEXT("APP_L1_GET_AGC_CNF")}, 
{APP_L1_GET_BLOCK_ERROR_RATIO_CNF        , TEXT("APP_L1_GET_BLOCK_ERROR_RATIO_CNF")}, 
{APP_MN_READ_DSP_MEM_CNF                 , TEXT("APP_MN_READ_DSP_MEM_CNF")}, 
{APP_MN_SWITCH_ARFCN_CNF                 , TEXT("APP_MN_SWITCH_ARFCN_CNF")}, 
