/******************************************************************************
 ** File Name:      mn_events.h                                               *
 ** Author:         Fancier fan                                               *
 ** Date:           02/20/2002                                                *
 ** Copyright:      Copyright 2001-2010 by Spreadtrum Communications,Inc.     *
 **                 All Rights Reserved.                                      *
 **                 This software is supplied under the terms of a license    *
 **                 agreement or non-disclosure agreement with Spreadtrum.    *
 **                 Passing on and copying of this document,and communication *
 **                 of its contents is not permitted without prior written    *
 **                 authorization.                                            *
 ** Description:    This header file defines constants and typedef used in    *
 **                 mn main task.                                             *                                                      
 ******************************************************************************

 ******************************************************************************
 **                        Edit History                                       *
 ** --------------------------------------------------------------------------*
 ** Date           Name             Description                               *
 **---------------------------------------------------------------------------*
 ** 02/20/2002     Fancier fan      Create.                                   *
 ******************************************************************************/

#ifndef  _MN_EVENTS_H
#define  _MN_EVENTS_H

#include "sci_service.h"

typedef enum
{
    EV_MN_APP_NETWORK_STATUS_IND_F = (MN_APP_PHONE_SERVICE<<8),/* MN report phone status to app*/
	EV_MN_APP_SIMCARD_READY_IND_F, /* simcard worked ok */  //1793
	EV_MN_APP_SIMCARD_NOT_READY_IND_F, /* simcard not ready */ 
	EV_MN_APP_SIMCARD_GET_PIN_IND_F, /* MN require chv value from APP */ 
	EV_MN_APP_SCELL_RSSI_IND_F, /* SCELL power indicator */ 
    EV_MN_APP_MS_POWERING_OFF_IND_F, 
    EV_MN_APP_DEACTIVE_PS_CNF_F, /* power off now */ 
	EV_MN_APP_NCELL_RSSI_CNF_F,	/* response for ncell rssi req */ 
    EV_MN_APP_AOC_MODIFIED_IND_F, /* ind acm increased */ //1800
	EV_MN_APP_FDN_SERVICE_IND_F, /* ind fdn enable or disable */
	EV_MN_APP_FDN_CAPABILITY_IND_F, /* ind fdn enable or disable */
	EV_MN_APP_ACL_SERVICE_IND_F, /* ind ACL enable or disable, CR220550 E */
    EV_MN_APP_PIN_FUNC_CNF_F,	/* pin func cnf */
    EV_MN_APP_PLMN_LIST_CNF_F,	/* plmn list result to app */
    EV_MN_APP_PLMN_SELECT_CNF_F, /* plmn select result to app */
    EV_MN_APP_PLMN_READ_CNF_F, /* plmn read from sim result to app */
    EV_MN_APP_PLMN_WRITE_CNF_F, /* plmn write to sim result to app */
    EV_MN_APP_CURRENT_RAT_IND_F, /* current rat ind to app */
    EV_MN_APP_PREFER_RAT_RSP_F, /* preferred rat setting result to app *///1810
    EV_MN_APP_CURR_CELL_CAPABILITY_IND_F,/* current cell capability ind to app */
    EV_MN_APP_AT_TRACE_IND_F,/*Trace ind to ATC*/
    EV_MN_APP_TD_NCELL_INFO_IND_F,
    EV_MN_APP_NETWORK_INFO_IND_F,
	
    EV_MN_APP_GPRS_ATTACH_RESULT_F,  //1815
    EV_MN_APP_GPRS_DETACH_RESULT_F,
    EV_MN_APP_DETACH_GSM_CNF_F,
    EV_MN_APP_PUCT_INFO_CNF_F,
	EV_MN_APP_PS_READY_IND_F,
	EV_MN_APP_SET_PREF_MODE_CNF_F, //1820
	EV_MN_APP_SET_BAND_CNF_F,
	EV_MN_APP_SET_SERVICE_TYPE_CNF_F,
	EV_MN_APP_SET_ROAM_MODE_CNF_F,
	EV_MN_APP_DISPLAY_PLMN_IND_F,
	EV_MN_APP_READ_GID_CNF_F,
	EV_MN_APP_PS_POWER_ON_CNF_F,
	EV_MN_APP_PS_POWER_OFF_CNF_F,
	EV_MN_APP_SIM_POWER_ON_CNF_F,
	EV_MN_APP_SIM_PIN_CHECK_IND_F,
	EV_MN_APP_SIM_POWER_OFF_CNF_F, //1830
	EV_MN_APP_SIM_PLUG_IN_IND_F,
	EV_MN_APP_LND_READY_IND_F ,
    EV_MN_APP_CPHS_READY_IND_F,
	EV_MN_APP_SIM_PRESENT_IND_F,
	EV_MN_APP_PREFER_PLMN_CHANGE_CNF_F,
	EV_MN_APP_LANGUAGE_UPDATE_CNF_F,
	#ifndef MMI_SIMULATOR	
	EV_MN_APP_SET_EXT_PROFILE_CNF_F,
	#endif
	EV_MN_APP_SIM_MBBMS_ALGO_CNF_F,
    EV_MN_APP_SIM_COMMON_ALGO_CNF_F, 
    EV_MN_APP_EMG_NUM_LIST_IND_F,
    EV_MN_APP_NETNAME_READY_F,
    EV_MN_APP_SWITCH_ARFCN_CNF_F,
    EV_MN_APP_IMS_STATE_IND_F,
    EV_MN_APP_CHANGE_RAT_CNF_F,
    EV_MN_APP_ERR_CONN_STATUS_IND_F,
    EV_MN_APP_HSL_ABORT_IND_F,
    EV_MN_APP_RECOVERY_IND_F,
    EV_MN_APP_LTE_PRIORITY_CNF_F,
    EV_MN_APP_HSL_START_CNF_F,
    EV_MN_APP_HSL_STOP_CNF_F,

    MAX_MN_APP_PHONE_EVENTS_NUM, 
	
	EV_MN_APP_CALL_START_IND_F = (MN_APP_CALL_SERVICE << 8),
	EV_MN_APP_ALERTING_IND_F, 
	EV_MN_APP_SETUP_COMPLETE_IND_F, 
	EV_MN_APP_SETUP_COMPLETE_CNF_F,
	EV_MN_APP_CALL_DISCONNECTED_IND_F, 
	EV_MN_APP_CALL_ERR_IND_F, 
	EV_MN_APP_SETUP_IND_F,
	EV_MN_APP_HELD_CNF_F, 
	EV_MN_APP_HELD_IND_F,
	EV_MN_APP_START_DTMF_CNF_F,
	EV_MN_APP_STOP_DTMF_CNF_F,
	EV_MN_APP_SYNC_IND_F,
	EV_MN_APP_RETRIEVED_CNF_F,
	EV_MN_APP_RETRIEVED_IND_F,
	EV_MN_APP_SWAP_IND_F,
	EV_MN_APP_SWAP_CNF_F,
	EV_MN_APP_ACMMAX_IND_F,
	EV_MN_APP_PROGRESS_IND_F,
	EV_MN_APP_USERTOUSER_IND_F,
	EV_MN_APP_MODIFY_CNF_F,
	EV_MN_APP_MODIFY_IND_F,
	EV_MN_APP_FORWARD_IND_F,
	EV_MN_APP_CALL_WAIT_IND_F,
	EV_MN_APP_CALL_BARRY_IND_F,
	EV_MN_APP_BUILD_MPTY_CNF_F,
	EV_MN_APP_BUILD_MPTY_IND_F,
	EV_MN_APP_SPLIT_MPTY_CNF_F,
	EV_MN_APP_SPLIT_MPTY_IND_F,
	EV_MN_APP_ECT_INVOKE_CNF_F,
	EV_MN_APP_ECT_INVOKE_IND_F,
	EV_MN_APP_CALLING_NAME_IND_F,
	EV_MN_APP_FORWARD_STATUS_IND_F,
	EV_MN_APP_CONNECTING_IND_F,
	EV_MN_APP_DISCONNECTING_IND_F,
	EV_MN_APP_HOLDING_IND_F,
	EV_MN_APP_RETRIEVING_IND_F,
	EV_MN_APP_BUILDING_MPTY_IND_F,
	EV_MN_APP_SPLITTING_MPTY_IND_F,
	EV_MN_APP_ECT_INVOKING_IND_F,
    EV_MN_APP_CALL_READY_IND_F, 
    EV_MN_APP_DISC_INFO_IND_F,
	EV_MN_APP_CLIR_SUPP_REJ_IND_F,
	EV_MN_APP_CALL_DEFLECT_IND_F,
	EV_MN_APP_CCBS_ACTIVATE_IND_F, 
	EV_MN_APP_CCBS_RECALL_IND_F, 
	EV_MN_APP_CALL_PATH_IND_F,
	EV_MN_APP_CALL_AUDIO_ON_IND_F,
	EV_MN_APP_CALL_AUDIO_RESTART_IND_F,
	MAX_MN_APP_CALL_EVENTS_NUM, 
	
	EV_MN_APP_SET_PDP_CONTEXT_CNF_F = (MN_APP_GPRS_SERVICE << 8),
	EV_MN_APP_SET_MIN_QOS_CNF_F,
	EV_MN_APP_SET_QOS_CNF_F,
	EV_MN_APP_SET_EXTEND_QOS_CNF_F,
	EV_MN_APP_SET_EXTEND_MIN_QOS_CNF_F,
	EV_MN_APP_ACTIVATE_PDP_CONTEXT_CNF_F,
	EV_MN_APP_DELETE_PDP_CONTEXT_CNF_F,
	EV_MN_APP_DELETE_MIN_QOS_CNF_F,
	EV_MN_APP_DELETE_QOS_CNF_F,
	EV_MN_APP_DEACTIVATE_PDP_CONTEXT_CNF_F,
    EV_MN_APP_MTACT_RESPOND_MODE_CNF_T, 
	EV_MN_APP_PUSH_GPRS_DATA_CNF_F,
	EV_MN_APP_DEACTIVATE_PDP_CONTEXT_IND_F,
	EV_MN_APP_GPRS_DETACH_IND_F,
	EV_MN_APP_MODIFY_PDP_CONTEXT_CNF_F ,
	EV_MN_APP_SET_EXT_QOS_CNF_F,
	EV_MN_APP_SET_EXT_MIN_QOS_CNF_F,
	EV_MN_APP_SET_TFT_CNF_F,
	EV_MN_APP_SET_SEC_PDP_CONTEXT_CNF_F,
	EV_MN_APP_ACTIVATE_PDP_CONTEXT_IND_F,
	MAX_MN_APP_GPRS_EVENTS_NUM,
    
    EV_MN_APP_SMS_READY_IND_F = ( MN_APP_SMS_SERVICE << 8 ) , 
	EV_MN_APP_SMS_MEM_FULL_IND_F,
	EV_MN_APP_SMS_MEM_FULL_IND_EX_F,

	EV_MN_APP_SMS_MEM_OVER_FLOW_IND_F,

    EV_MN_APP_READ_SMS_CNF_F          , 
    EV_MN_APP_UPDATE_SMS_STATUS_CNF_F  , 
    EV_MN_APP_READ_STATUS_REPORT_CNF_F, 
    EV_MN_APP_SMS_STATUS_REPORT_IND_F      , 
    EV_MN_APP_SEND_SMS_CNF_F          , 
    EV_MN_APP_CANCEL_SMS_CNF_F        ,
    EV_MN_APP_WRITE_SMS_CNF_F         , 
    EV_MN_APP_EDIT_SMS_CNF_F         , 
    EV_MN_APP_SMS_IND_F               , 
    EV_MN_APP_READ_SMS_PARAM_CNF_F    , 
    EV_MN_APP_WRITE_SMS_PARAM_CNF_F   , 
	EV_MN_APP_DELETE_SMS_RECORDS_IND_F,
	EV_MN_APP_DELETE_ALL_SMS_CNF_F	  ,
	EV_MN_SET_ASSERT_SMS_DESTADDR_CNF_F,
	EV_MN_APP_SET_SMS_RECEIVE_FUNC_CNF_F,
	EV_MN_APP_VMW_FALG_IND_F,
    EV_MN_APP_GET_VMW_FLAG_CNF_F,
    EV_MN_APP_SET_VMW_FLAG_CNF_F,
    EV_MN_APP_SET_VMW_ADR_CNF_F,
    EV_MN_APP_GET_VMW_ADR_CNF_F,
    EV_MN_APP_SMS_NUM_IND_F,
    MAX_MN_APP_SMS_EVENTS_NUM         , 
	
	EV_MN_APP_SMSCB_MSG_IND_F = ( MN_APP_SMSCB_SERVICE << 8 ), 
	EV_MN_APP_SMSCB_MACRO_MSG_IND_F,
	EV_MN_APP_SMSCB_REJ_IND_F,
	EV_MN_APP_SMSCB_MSG_PAGES_IND_F,
	EV_MN_APP_SMSCB_SET_PARAM_CNF_F,   /* cr250176 */
	EV_MN_APP_SMSCB_GET_PARAM_CNF_F,   /* cr250176 */
	EV_MN_APP_TDPS_SMSCB_MSG_IND_F,   /* cr250176_NEW */
	MAX_MN_APP_SMSCB_EVENTS_NUM       , 
	
	EV_MN_APP_BEGIN_REGISTER_SS_F = ( MN_APP_SS_SERVICE << 8 ) , 
	EV_MN_APP_BEGIN_ERASE_SS_F					, 
	EV_MN_APP_BEGIN_ACTIVATE_SS_F				,
	EV_MN_APP_BEGIN_DEACTIVATE_SS_F				, 
	EV_MN_APP_BEGIN_INTERROGATE_SS_F			, 
	EV_MN_APP_BEGIN_REGISTER_PASSWORD_F			, 
	EV_MN_APP_BEGIN_USSD_SERVICE_F				, 
	EV_MN_APP_REGISTER_SS_CNF_F					, 
	EV_MN_APP_ERASE_SS_CNF_F					, 
	EV_MN_APP_ACTIVATE_SS_CNF_F					, 
	EV_MN_APP_DEACTIVATE_SS_CNF_F				, 
	EV_MN_APP_INTERROGATE_CNF_F				, 
	EV_MN_APP_REGISTER_PASSWORD_CNF_F			, 
	EV_MN_APP_GET_PASSWORD_IND_F				, 
	EV_MN_APP_USSD_IND_F						, 
	EV_MN_APP_USSD_NOTIFY_IND_F					, 
	EV_MN_APP_USSD_SERVICE_CNF_F				, 
	EV_MN_APP_RELEASE_SS_F						, 
	EV_MN_APP_SS_BUSY_F							, 
	EV_MN_APP_CCBS_ERASE_CNF_F                  , 
	MAX_MN_APP_SS_EVENTS_NUM                    ,
    
    EV_MN_APP_SIMAT_DISPLAY_TEXT_IND_F = (MN_APP_SIMAT_SERVICE << 8),
    EV_MN_APP_SIMAT_GET_INKEY_IND_F,
    EV_MN_APP_SIMAT_GET_INPUT_IND_F,

	EV_MN_APP_SIMAT_MORE_TIME_IND_F,

    EV_MN_APP_SIMAT_PLAY_TONE_IND_F,
    EV_MN_APP_SIMAT_REFRESH_IND_F,
    EV_MN_APP_SIMAT_SETUP_MENU_IND_F,
    EV_MN_APP_SIMAT_SELECT_ITEM_IND_F,
    EV_MN_APP_SIMAT_SEND_SMS_IND_F,
    EV_MN_APP_SIMAT_SEND_SS_IND_F,
    EV_MN_APP_SIMAT_SEND_USSD_IND_F,
    EV_MN_APP_SIMAT_SETUP_CALL_IND_F,
    EV_MN_APP_SIMAT_PRO_LOCAL_INFO_IND_F,
    SIMAT_EVENT_SETUP_EVENT_LIST,
    EV_MN_APP_SIMAT_SETUP_IDLE_TEXT_IND_F,
    EV_MN_APP_SIMAT_SEND_DTMF_IND_F,
    EV_MN_APP_SIMAT_LANG_NOTIFY_IND_F,
    EV_MN_APP_SIMAT_CC_TO_MMI_IND_F,
    SIMAT_EVENT_SS_CON_RSP,
    SIMAT_EVENT_USSD_CON_RSP,
    EV_MN_APP_SIMAT_SMS_CTL_TO_MMI_IND_F,
    SIMAT_EVENT_SMS_PP_RSP,
    SIMAT_EVENT_SMS_CB_RSP,
    SIMAT_EVENT_SESSION_TERMINATE,
    SIMAT_EVENT_PROFILE_DOWNLOAD_CNF,
    EV_MN_APP_SIMAT_EVENT_REFRESH_CNF,
    EV_MN_APP_SIMAT_EVENT_REFRESH_CNF_F = EV_MN_APP_SIMAT_EVENT_REFRESH_CNF,

    EV_MN_APP_SIMAT_SEND_DATA_IND_F,
    EV_MN_APP_SIMAT_RECEIVE_DATA_IND_F,
    EV_MN_APP_SIMAT_LAUNCH_BROWSER_IND_F,
    EV_MN_APP_SIMAT_OPEN_CHANNEL_IND_F,
    EV_MN_APP_SIMAT_CLOSE_CHANNEL_IND_F,
    EV_MN_APP_SIMAT_GET_CHANNEL_STATUS_IND_F,
    EV_MN_APP_SIMAT_RETRIEVE_MULTIMEDIA_MSG_IND_F,     
    EV_MN_APP_SIMAT_SUBMIT_MULTIMEDIA_MSG_IND_F, 
    EV_MN_APP_SIMAT_DISPLAY_MULTIMEDIA_MSG_IND_F, 

    EV_MN_APP_SIMAT_FWD_PC_IND_F,
	EV_MN_APP_SIMAT_TERMINAL_RESPONSE_CNF_F, 
    EV_MN_APP_SIMAT_ENVELOP_CNF_F, 
    SIMAT_EVENT_NUM,

    EV_MN_APP_MSISDN_UPDATE_CNF_F = (MN_APP_SIM_SERVICE << 8),
    EV_MN_APP_ADN_UPDATE_CNF_F,
    EV_MN_APP_FDN_UPDATE_CNF_F,
    EV_MN_APP_LND_UPDATE_CNF_F,
    EV_MN_APP_GET_FREE_EXT_INFO_CNF_F,
    EV_MN_APP_CPHS_INFO_IND_F,
    EV_MN_APP_OPER_NAME_IND_F,
    EV_MN_APP_CFF_IND_F,
    EV_MN_APP_DCS_UPDATE_CNF_F,
    EV_MN_APP_CSP_UPDATE_CNF_F,
    EV_MN_APP_CSP_LINE2_UPDATE_CNF_F,
    EV_MN_APP_LINE_SELECTED_UPDATE_CNF_F,
    EV_MN_APP_LINE_LOCKSTATUS_UPDATE_CNF_F,
    EV_MN_APP_READ_SIM_FILE_BUF_CNF_F,
    EV_MN_APP_GET_SIM_TYPE_CNF_F,
	EV_MN_APP_GET_UIM_IMSI_CNF_F,
	EV_MN_APP_CRSM_CNF_F,
 
    EV_MN_APP_SIM_RECORD_NUM_CNF_F,
    EV_MN_APP_SIM_RECORD_READ_CNF_F,

    EV_MN_APP_SIM_BINARY_READ_CNF_F,
    EV_MN_APP_SIM_BINARY_UPDATE_CNF_F,    
#ifndef MMI_SIMULATOR	
	EV_MN_APP_ADD_INFO_READ_CNF_F,
	EV_MN_APP_UPDATE_USER_INFO_CNF_F,
	EV_MN_APP_DEL_USER_INFO_CNF_F,
#endif


#ifndef MMI_SIMULATOR	
	EV_MN_APP_TRIG_READ_AUTH_FILE_F,
#endif
    EV_MN_APP_RECORD_READ_CNF_F,
    EV_MN_APP_RECORD_UPDATE_CNF_F, 
    EV_MN_APP_SIM_READ_CNF_F, 
    EV_MN_APP_SIM_WRITE_CNF_F, 
    EV_MN_APP_GET_SIM_EF_ENTIRE_INFO_CNF_F,
    EV_MN_APP_SIM_SEARCH_RECORD_CNF_F,
    EV_MN_APP_CSIM_CNF_F,
    
	MAX_MN_APP_SIM_EVENTS_NUM ,
	
#ifdef _MNGPS_SUPPORT_
    EV_MN_APP_GPS_DOWNLOAD_CNF_F = (MN_APP_GPS_SERVICE << 8),
    EV_MN_APP_GPS_INIT_CNF_F,
    EV_MN_APP_GPS_START_CNF_F,
    EV_MN_APP_GPS_STOP_CNF_F,
    EV_MN_APP_GPS_RESET_CNF_F,
    EV_MN_APP_GPS_READ_STATUS_CNF_F,
    EV_MN_APP_GPS_READ_INFO_CNF_F,
    EV_MN_APP_GPS_OUTPUT_CNF_F,
    EV_MN_APP_GPS_POWEROFF_CNF_F,
    EV_MN_APP_GPS_OUTPUT_INFO_IND_F,
    EV_MN_APP_GPS_ERR_IND_F,
    EV_MN_APP_GPS_FIX_IND_F,
    GPS_EVENT_NUM,  
#endif    

} msg_def_type;

#endif /*End MN_events.h*/
