/******************************************************************************
 ** Copyright:  Copyright 2001-2010 by Spreadtrum Communications,Inc.         *
 **             All Rights Reserved.                                          *
 **             This software is supplied under the terms of a license        *
 **             agreement or non-disclosure agreement with Spreadtrum.        *
 **             Passing on and copying of this document,and communication     *
 **             of its contents is not permitted without prior written        *
 **             authorization.                                                *
 **                                                                           *
 ** ===========================================================================
 **
 **     Generated by code_adapter.Sat Sep 29 14:32:32 2012
 **
 *******************************************************************************/


#ifndef __TASKS_DEF_H__

#define __TASKS_DEF_H__

#define CUSTOMIZED_STATIC_TASKS      \
    P_DL,  \
    P_RRC, \
    P_SCT, \


#define CUSTOMIZED_DYNAMIC_TASKS   


#endif /*__TASKS_DEF_H__*/
