#ifdef VT_SUPPORT

//[[define image infomation
RES_ADD_IMG(IMAG_VT_HANDHOLD_OFF,"\\MMI_RES_##\\IMAG\\IMAG_VT_HANDHOLD_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_HANDHOLD_ON,"\\MMI_RES_##\\IMAG\\IMAG_VT_HANDHOLD_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_DISPLAY_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_DISPLAY_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_DISPLAY_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_DISPLAY_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_DISPLAY_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_VT_DISPLAY_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_HANDFREE_OFF,"\\MMI_RES_##\\IMAG\\IMAG_VT_HANDFREE_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_HANDFREE_ON,"\\MMI_RES_##\\IMAG\\IMAG_VT_HANDFREE_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_CAMERA_OFF,"\\MMI_RES_##\\IMAG\\IMAG_VT_CAMERA_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_CAMERA_ON,"\\MMI_RES_##\\IMAG\\IMAG_VT_CAMERA_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_CAMERA_GRAY,"\\MMI_RES_##\\IMAG\\IMAG_VT_CAMERA_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_DISPMODE_OFF,"\\MMI_RES_##\\IMAG\\IMAG_VT_DISPMODE_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_DISPMODE_ON,"\\MMI_RES_##\\IMAG\\IMAG_VT_DISPMODE_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_DISPMODE_GRAY,"\\MMI_RES_##\\IMAG\\IMAG_VT_DISPMODE_GRAY.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_BG_BANK,"\\MMI_RES_##\\IMAG\\IMAG_VT_BG_BANK.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_DEFAULT_PHOTO,"\\MMI_RES_##\\IMAG\\IMAG_VT_DEFAULT_PHOTO.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_TEXT_LABEL_BG,"\\MMI_RES_##\\IMAG\\IMAGE_VT_TEXT_LABEL_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_BG,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_ZOOM_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_ZOOM_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_ZOOM_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_ZOOM_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_CONTRAST_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_CONTRAST_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_CONTRAST_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_CONTRAST_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_BRIGHTNESS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_BRIGHTNESS_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_BRIGHTNESS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_BRIGHTNESS_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_ROTATE_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_ROTATE_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_ROTATE_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_ROTATE_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_ROTATE_90_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_ROTATE_90_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_ROTATE_90_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_ROTATE_90_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_ROTATE_180_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_ROTATE_180_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_VIDEO_OPTION_ROTATE_180_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_VIDEO_OPTION_ROTATE_180_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_STB_BG,"\\MMI_RES_##\\IMAG\\IMAG_VT_STB_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_LCD_BRIGHTNESS_OFF,"\\MMI_RES_##\\IMAG\\IMAG_VT_LCD_BRIGHTNESS_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_LCD_BRIGHTNESS_ON,"\\MMI_RES_##\\IMAG\\IMAG_VT_LCD_BRIGHTNESS_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_MAIN_PLAY_BG,"\\MMI_RES_##\\IMAG\\IMAG_VT_MAIN_PLAY_BY.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMAG_VT_ADJUST_DOWN_OFF,"\\MMI_RES_##\\IMAG\\IMAG_VT_ADJUST_DOWN_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ADJUST_DOWN_ON,"\\MMI_RES_##\\IMAG\\IMAG_VT_ADJUST_DOWN_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ADJUST_UP_OFF,"\\MMI_RES_##\\IMAG\\IMAG_VT_ADJUST_UP_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ADJUST_UP_ON,"\\MMI_RES_##\\IMAG\\IMAG_VT_ADJUST_UP_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ADJUST_LEFT_OFF,"\\MMI_RES_##\\IMAG\\IMAG_VT_ADJUST_LEFT_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ADJUST_LEFT_ON,"\\MMI_RES_##\\IMAG\\IMAG_VT_ADJUST_LEFT_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ADJUST_RIGHT_OFF,"\\MMI_RES_##\\IMAG\\IMAG_VT_ADJUST_RIGHT_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ADJUST_RIGHT_ON,"\\MMI_RES_##\\IMAG\\IMAG_VT_ADJUST_RIGHT_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ICON_BRIGHTNESS,"\\MMI_RES_##\\IMAG\\IMAG_VT_ICON_BRIGHTNESS.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ICON_CONTRAST,"\\MMI_RES_##\\IMAG\\IMAG_VT_ICON_CONTRAST.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ICON_LCD_BRIGHTNESS,"\\MMI_RES_##\\IMAG\\IMAG_VT_ICON_LCD_BRIGHTNESS.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ICON_ROTATE,"\\MMI_RES_##\\IMAG\\IMAG_VT_ICON_ROTATE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAG_VT_ICON_VOLUME,"\\MMI_RES_##\\IMAG\\IMAG_VT_ICON_VOLUME.bmp",IMG_CMP_BMP_16_565_RLE,0)

#ifdef TOUCH_PANEL_SUPPORT
RES_ADD_IMG(IMAGE_VT_BUTTON_DEL_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_DEL_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_DEL_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_DEL_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_ONE_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_ONE_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_ONE_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_ONE_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_TWO_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_TWO_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_TWO_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_TWO_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_THREE_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_THREE_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_THREE_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_THREE_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_FOUR_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_FOUR_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_FOUR_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_FOUR_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_FIVE_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_FIVE_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_FIVE_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_FIVE_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_SIX_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_SIX_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_SIX_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_SIX_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_SEVEN_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_SEVEN_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_SEVEN_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_SEVEN_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_EIGHT_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_EIGHT_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_EIGHT_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_EIGHT_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_NINE_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_NINE_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_NINE_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_NINE_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_ZERO_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_ZERO_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_ZERO_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_ZERO_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_STAR_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_STAR_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_STAR_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_STAR_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_HASH_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_HASH_OFF.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_VT_BUTTON_HASH_ON,"\\MMI_RES_##\\IMAG\\IMAGE_VT_BUTTON_HASH_ON.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

//]]define image infomation

//[[define anim infomation
//RES_ADD_ANIM(ANIM_MT_CALL,"\\MMI_RES_##\\ANIM\\ANIM_MT_CALL",AT_COMPRESS_STREAM,75,0x000000)
RES_ADD_ANIM(ANIM_MO_CALL,"\\MMI_RES_##\\ANIM\\ANIM_MO_CALL",AT_COMPRESS_STREAM,75,0x000000)
//RES_ADD_ANIM(ANIM_REDIAL_CALL,"\\MMI_RES_##\\ANIM\\ANIM_REDIAL_CALL",AT_COMPRESS_STREAM,75,0x000000)
//]]define anim infomation

//[[define string infomation
RES_ADD_STRING(TXT_VT_ANSWER_AUDIO,"Audio Answer")      //已有
RES_ADD_STRING(TXT_VIDEO_CALL_IN,"Video call incoming") //已有
RES_ADD_STRING(TXT_VIDEO_CALL_OUT,"Video calling") //“视频电话呼出中”
RES_ADD_STRING(TXT_VIDEO_CALL_REMOTE_ALERTING,"User alerting") //“对方振铃中”
RES_ADD_STRING(TXT_VIDEO_CALL_CONNECTING,"Connecting") //“连接中”
RES_ADD_STRING(TXT_VIDEO_CALL_DISCONNECTING,"Disconnecting") //“通话断开中”

RES_ADD_STRING(TXT_VIDEO_CALL_FB_QUERY,"Make voice call?") //“是否发起语音电话”
RES_ADD_STRING(TXT_VIDEO_CALL_FB_ACCEPT,"Auto make voice call...") //“自动转为语音电话...”
RES_ADD_STRING(TXT_VIDEO_CALL_FB_QUIT,"Call is cancelled!") //“是否发起语音电话”
RES_ADD_STRING(TXT_VIDEO_CALL_FB_WAIT,"Pls wait voice call...") //“请等待语音电话”

RES_ADD_STRING(TXT_VIDEO_CALL_FB_CAUSE_UNAVAILABLE,"Sorry, video call unavailable") //“对不起，不能发起视频电话”
RES_ADD_STRING(TXT_VIDEO_CALL_FB_CAUSE_NOT_START_SERVICE,"You never start service") //"主叫未开通可视电话业务"
RES_ADD_STRING(TXT_VIDEO_CALL_FB_CAUSE_TEMP_UNSUPPORTED,"User unsupport video call") //"对方暂不支持可视电话"
RES_ADD_STRING(TXT_VIDEO_CALL_FB_CAUSE_USER_CHOOSE_NC,"User chooses voice call") //"被叫选择语音呼叫"


//RES_ADD_STRING(TXT_CONECTED_MENU_STOP_RECORD,"Stop recording") //“停止录制”//replaced by common ID TXT_COMMON_STOP_RECORD  
RES_ADD_STRING(TXT_CONECTED_MENU_STOP_REPLACE,"Resume my image") //“恢复本地图像”
RES_ADD_STRING(TXT_CONECTED_MENU_TURNOFF_CAMERA,"Turn off camera") //“关闭摄像头”
RES_ADD_STRING(TXT_CONECTED_MENU_TURNON_CAMERA,"Turn on camera") //“开启摄像头”
RES_ADD_STRING(TXT_CONECTED_MENU_TURNOFF_REMOTE_MUTE,"Turn off remote mute") //“关闭远端静音”
RES_ADD_STRING(TXT_CONECTED_MENU_TURNON_REMOTE_MUTE,"Turn on remote mute") //“打开远端静音”
RES_ADD_STRING(TXT_CONECTED_MENU_TURNOFF_MUTE,"Turn off mute") //“关闭静音”
RES_ADD_STRING(TXT_CONECTED_MENU_TURNON_MUTE,"Turn on mute") //“开启静音”
RES_ADD_STRING(TXT_CONECTED_MENU_TURNOFF_BT,"Turn off bluetooth") //“关闭蓝牙通话”
RES_ADD_STRING(TXT_CONECTED_MENU_TURNON_BT,"Turn on bluetooth") //“开启蓝牙通话”
RES_ADD_STRING(TXT_CONECTED_MENU_REPLACE,"Replace") //“替代画面”
//RES_ADD_STRING(TXT_CONECTED_MENU_REPLACE_IMAGE,"Image") //“图片”  //replaced by common ID TXT_COMMON_PIC
//RES_ADD_STRING(TXT_CONECTED_MENU_REPLACE_VIDEO,"Video") //“视频”    //replaced by common ID TXT_VIDEO
RES_ADD_STRING(TXT_CONECTED_MENU_RECORD,"Record") //“录制”
//RES_ADD_STRING(TXT_CONECTED_MENU_PB,"Contacts") //“通讯录”    //replaced by common ID  STXT_MAIN_PB
//RES_ADD_STRING(TXT_CONECTED_MENU_SETTING,"Settings") //“设置”        //replaced by common ID STXT_MAIN_SETTING
//RES_ADD_STRING(TXT_3G_NOT_AVAILABLE,"Disconnected, not in 3G network") //需要改成“已断开，未能获得3G网络”
RES_ADD_STRING(TXT_VT_QUERY_VOICE_CALL,"Make a normal call?") //需要改成“是否选择语音呼叫？”
//RES_ADD_STRING(TXT_VT_REMOTE_CAMERA_OFF,"User shutoff DC") //需要改成“对方关闭摄像头”  //replaced by common ID TXT_COMM_REMOTE_CAMERA_OFF
RES_ADD_STRING(TXT_VT_REMOTE_CAMERA_ON,"User switch on DC") //需要改成“对方开启摄像头”
RES_ADD_STRING(TXT_VT_HIDE_ME,"Hide me") //"隐藏自己"
RES_ADD_STRING(TXT_VT_SHOW_ME,"Show me") //“显示自己”
//RES_ADD_STRING(TXT_VT_REF_ERROR_NO_SPACE,"Disk space is full") //“磁盘空间已满”  //replaced by common ID TXT_COMM_MEMORY_FULL
RES_ADD_STRING(TXT_VT_REF_ERROR_FILE_BIG,"File exceeds limit") //“文件过大”
RES_ADD_STRING(TXT_VT_REF_ERROR_FILE_ERROR,"File operation error") //“文件操作错误”

//RES_ADD_STRING(TXT_VT_STOP_RECORD,"Stop recording") //“录制停止” //replaced by common ID TXT_COMMON_STOP_RECORD 
RES_ADD_STRING(TXT_VT_START_RECORD,"Start recording") //“录制开始”

RES_ADD_STRING(TXT_VT_REF_ERROR_SENSOR_ERR,"Sensor error") //“传感器异常”
RES_ADD_STRING(TXT_VT_REF_ERROR_INVALID_PARAM,"Invalid parameter") //“参数非法”
RES_ADD_STRING(TXT_VT_REF_REPLACE_BY_DEFAULT,"Replaced by default image") //“使用默认图片替代”

//RES_ADD_STRING(TXT_VT_SIGNAL_UNCONNECT,"Signal unconnected") //"连接已断开"    //replaced by common ID TXT_COMMON_LINK_DISCONNECTED
//]]define string infomation


//[[define data infomation
//]]define data infomation

#endif //vt_support
