#ifdef DCD_SUPPORT
//[[define image infomation
//RES_ADD_IMG(IMAGE_DCD_DEFAULT_ICON_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_DEFAULT_ICON_IMAGE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_DEFAULT_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_DEFAULT_IMAGE.bmp",IMG_CMP_BMP_16_565_RLE,0)
#ifdef CMCC_UI_STYLE//xuefangjiang add
RES_ADD_IMG(IMAGE_DCD_DEFAULT_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_DEFAULT_CMCC_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DCD_UPDATING,"\\MMI_RES_##\\ANIM\\IMAGE_DCD_UPDATING_CMCC.gif",IMG_CMP_GIF_SCI,0)
#else
RES_ADD_IMG(IMAGE_DCD_DEFAULT_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_DEFAULT_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)

//RES_ADD_IMG(IMAGE_DCD_DEFAULT_TITLE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_DEFAULT_TITLE.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_PAGE_SELECT,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_PAGE_SELECT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_NO_READ_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_NO_READ_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DCD_UPDATING,"\\MMI_RES_##\\ANIM\\IMAGE_DCD_UPDATING.gif",IMG_CMP_GIF_SCI,0)
#endif
RES_ADD_IMG(IMAGE_DCD_IDLE_TAB_BGD_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_IDLE_TAB_BGD_IMAGE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_IDLE_LIST_BGD_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_IDLE_LIST_BGD_IMAGE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_DCD_TAB_CUR_BGD_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_TAB_CUR_BGD_IMAGE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_DCD_TAB_CUR_BGD_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_TAB_CUR_BGD_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DCD_TAB_FOCUS_BGD_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_TAB_FOCUS_BGD_IMAGE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_PHONEBOOK_GROUP4,"\\MMI_RES_##\\IMAG\\IMAGE_PHONEBOOK_GROUP4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DCD_NOT_READ_IMAGE,"\\MMI_RES_##\\IMAG\\IMAGE_DCD_NOT_READ_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image infomation

//[[define anim infomation
//]]define anim infomation
//[[define string infomation
//RES_ADD_STRING(TXT_DCD_QUICK_INFO,"QuickInfo")
RES_ADD_STRING(TXT_DCD_ITEM_LIST,"Item List")
RES_ADD_STRING(TXT_DCD_PREVIEW_LOCAL_ITEM,"Preview Local Item")
//RES_ADD_STRING(TXT_DCD_UPDATE_CHANNEL,"Update Channel")            //replaced by common ID TXT_COMMON_UPDATE
//RES_ADD_STRING(TXT_DCD_ADD_CHANNEL,"Add Channel")    //replaced by common ID TXT_ADD_CHANNEL
//RES_ADD_STRING(TXT_DCD_DELETE_CHANNEL,"Delete Channel")       //replaced by common ID TXT_COMMON_DELETE_CHANNEL
//RES_ADD_STRING(TXT_DCD_HELP,"Help")  //replaced by common ID TXT_HELP
//RES_ADD_STRING(TXT_DCD_SEND_BY_SMS,"Send by sms")  //replaced by common ID TXT_SMS
//RES_ADD_STRING(TXT_DCD_SEND_BY_MMS,"Send by mms")   //replaced by common ID TXT_MMS
RES_ADD_STRING(TXT_DCD_FUNCTION,"Function")
RES_ADD_STRING(TXT_DCD_CONNECT_MODE,"Connect mode")
RES_ADD_STRING(TXT_DCD_CONNECT_MODE_ALWAYS,"Always")
RES_ADD_STRING(TXT_DCD_CONNECT_MODE_MAN,"Man")
RES_ADD_STRING(TXT_DCD_CONNECT_MODE_OFF_WHEN_CRUISE,"Off when cruise")
RES_ADD_STRING(TXT_DCD_IDLE_SHOW,"Idle show")
RES_ADD_STRING(TXT_DCD_SCROLL_TIME,"Scroll time")
//RES_ADD_STRING(TXT_DCD_SCROLL_TIME_SLOW,"Slow")       //replaced by common ID TXT_COMMON_SLOW
RES_ADD_STRING(TXT_DCD_SCROLL_TIME_MIDDLE,"Middle")
//RES_ADD_STRING(TXT_DCD_SCROLL_TIME_FAST,"Fast")     //replaced by common ID TXT_COMMON_FAST  

RES_ADD_STRING(TXT_DCD_SERVICE_SWITCH,"DCD swtich")
RES_ADD_STRING(TXT_DCD_SHOW_READED,"show read")
RES_ADD_STRING(TXT_DCD_SHOW_READED_OPEN,"show")
//RES_ADD_STRING(TXT_DCD_SHOW_READED_CLOSE,"hide")    //replaced by common ID TXT_HIDE
//RES_ADD_STRING(TXT_DCD_MEMORY,"memory")  // replaced by common ID STXT_STORE_MEDIUM
//RES_ADD_STRING(TXT_DCD_STORE_ON_PHONE,"phone")        //replaced by common ID TXT_COMMON_UDISK    
//RES_ADD_STRING(TXT_DCD_STORE_ON_DISK,"Memory disk")  //replaced by common ID TXT_COMMON_SD_CARD
//RES_ADD_STRING(TXT_DCD_SIM1_INTERNET,"sim1 internet")   //replaced by common ID TXT_COMMON_SIM1_NETWORK_ACCOUNT
//RES_ADD_STRING(TXT_DCD_SIM2_INTERNET,"sim2 internet")   //replaced by common ID TXT_COMMON_SIM2_NETWORK_ACCOUNT
//RES_ADD_STRING(TXT_SET_RESET_FACTORY,"reset facrory")   //replaced by common ID TXT_COMMON_RESTORE_FACTORY_SETTINGS
RES_ADD_STRING(TXT_DCD_SET_RESET_FACTORY,"DCD reset factory")
RES_ADD_STRING(TXT_DCD_ORDER_CONTENT,"order content:")
RES_ADD_STRING(TXT_DCD_DL_CONTENT,"download content")
RES_ADD_STRING(TXT_DCD_LAST_CONNECT_TIME,"last update time")
RES_ADD_STRING(TXT_DCD_LAST_UPDATE_STATE,"last update state")
RES_ADD_STRING(TXT_DCD_NEXT_UPDATE_TIME,"next update time")

//RES_ADD_STRING(TXT_DCD_MINUTE, "minute")  //replaced by common ID TXT_TIME_MINUTE
RES_ADD_STRING(TXT_DCD_ORDER_VIEW, "order view")
//RES_ADD_STRING(TXT_DCD_RECORD, "record")       //replaced by common ID TXT_COMMON_SETTINGS_ENTRIES
RES_ADD_STRING(TXT_DCD_QUERY_CLOSE, "Close DCD")
RES_ADD_STRING(TXT_DCD_PROMPT_INFO, "order still exist")
RES_ADD_STRING(TXT_DCD_SAVED_IN_DISK, "saved in memory disk")
//RES_ADD_STRING(TXT_DCD_SAVE_SUCCESS, "Save sucess") //replaced by common ID TXT_COMM_SAVE_SUCCESS
RES_ADD_STRING(TXT_DCD_SAVED_IN_PHONE, "saved in phone")
RES_ADD_STRING(TXT_DCD_ERROR_WRONG_PROXY, "network is not work")
//RES_ADD_STRING(TXT_DCD_ERROR_TIMEOUT, "time out")  //replaced by common ID TXT_COMM_TIMEOUT
//RES_ADD_STRING(TXT_DCD_ERROR_UNKNOWN, "unkown error")    //replaced by common ID TXT_UNKNOWN_ERROR 
//RES_ADD_STRING(TXT_DCD_UPDATE_FAIL, "update fail")  //replaced by common ID TXT_UPDATE_FAIL


RES_ADD_STRING(TXT_DCD_UPDATING,"Update")
//RES_ADD_STRING(TXT_DCD_MORE,"Rename Group")  //replaced by common ID TXT_COMN_MORE
RES_ADD_STRING(TXT_DCD_LOCAL_TITLE,"Name")
RES_ADD_STRING(TXT_DCD_SER_SETTING,"Delete name")
RES_ADD_STRING(TXT_DCD_UPDATE_BEGIN,"Add name")
RES_ADD_STRING(TXT_DCD_AUTO_UPDATE,"Operate")
RES_ADD_STRING(TXT_DCD_IS_INVALID,"Call")
//RES_ADD_STRING(TXT_DCD_DETAIL,"detail")    //replaced by common ID STXT_DETAIL

RES_ADD_STRING(TXT_DCD_AUTO_PLAY,"Auto play")
RES_ADD_STRING(TXT_DCD_ABSTRACT_FILE,"Abstract file")
RES_ADD_STRING(TXT_DCD_TURN_ON,"turn on")
RES_ADD_STRING(TXT_DCD_TURN_OFF,"turn off")
//RES_ADD_STRING(TXT_DCD_SEND,"send")  //replaced by common ID TXT_SEND

RES_ADD_STRING(TXD_DCD_CHANNEL_MANAGEMENT,"Channel management")
RES_ADD_STRING(TXT_DCD_NO_SPACE,"No space to update DCD")
//RES_ADD_STRING(TXT_DCD_NO_CONTENT,"No  Content")    //replaced by common ID TXT_NO_CONTENT
RES_ADD_STRING(TXT_DCD_SAVE_50_ITEMS,"only can save 50 items")


//RES_ADD_STRING(TXT_DCD_UPDATE_CANCEL,"cancel update")       //replaced by common ID TXT_DCD_CANCEL_UPDATE
RES_ADD_STRING(TXT_DCD_BLANK,"no unread item")
RES_ADD_STRING(TXT_DCD_ONLINE_HELP,"online help")
RES_ADD_STRING(TXT_DCD_LOCAL_HELP_CONTENT,"help content")
RES_ADD_STRING(TXT_DCD_UPDATE_ERROR_CODE, "error code")
RES_ADD_STRING(TXT_DCD_CONTENT_IS_EMPTY, "content is empty")
RES_ADD_STRING(TXT_DCD_PROMPT_NET_LINK, "whether link to network")
RES_ADD_STRING(TXT_DCD_CANCEL_UPDATE, "cancel update")
RES_ADD_STRING(TXT_DCD_QUERY_UPDATE, "Update ?")
RES_ADD_STRING(TXT_DCD_UPDATE_SEND, "Update request has send, next request will be send manually")
RES_ADD_STRING(TXT_DCD_MAN_UPDATE_AGAIN, "update fail, update manually again")
RES_ADD_STRING(TXT_DCD_UPDATE_DATA, "new items, pictures  is updating")
RES_ADD_STRING(TXT_DCD_UPDATE_SINGLE_NEW_DATA, "new item, pictures  is updating")
//RES_ADD_STRING(TXT_DCD_MAINMENU, "main mainmenu")       //replaced by common ID TXT_COMMON_COMMON_CHANNEL_LIST  
RES_ADD_STRING(TXT_DCD_HAS_SAME_ITEM, "Has exist the same item")
RES_ADD_STRING(TXT_DCD_WAKEUP_OPEN, "dcd will be open")   
RES_ADD_STRING(TXT_DCD_READ_FAIL, "Read fail, please try later")   
//RES_ADD_STRING(TXT_DCD_MINUTES, "minutes")  //replaced by commonID TXT_COMM_MINUTES

RES_ADD_STRING(TXT_DCD_ERROR_DATA_WRONG, "data wrong")
//RES_ADD_STRING(TXT_DCD_ERROR_NETWORK_INVALID, "network invalid")  //replaced by common ID TXT_COMMON_NET_ERROR
RES_ADD_STRING(TXT_DCD_ERROR_NETWORK_USING, "network using")
RES_ADD_STRING(TXT_DCD_ERROR_DATA_TIMEOUT, "data timeout")
RES_ADD_STRING(TXT_DCD_TEXT_LINK_LIST, "DCD Account")
RES_ADD_STRING(TXT_DCD_UPDATE_COMPLEPTE, "Update complete")
RES_ADD_STRING(TXT_DCD_DATA_CHANGED, "Data has changed")
RES_ADD_STRING(TXT_DCD_UDISK_USING, "Udisk using, can't update dcd")
//]]define string infomation

//[[define data infomation
//]]define data infomation
#endif
