/****************************************************************************
** File Name:      mmicc_displaysize.h                                     *
** Author:                                                                 *
** Date:           13/04/2007                                              *
** Copyright:      2003 Spreadtrum, Incorporated. All Rights Reserved.     *
** Description:    This file is used to describe the mmi cc internal api   *
****************************************************************************
**                         Important Edit History                          *
** ------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                             *
** 4/2007        maggie.ren         Create
****************************************************************************/

#ifndef _MMICC_POSITION_H
#define _MMICC_POSITION_H

#ifdef __cplusplus
    extern   "C"
    {
#endif

#ifdef MAINLCD_SIZE_176X220
/* MO OR MT WIN */

#define MMICC_CALLING_TEXT_FORM_TOP MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM 112
        
#define MMICC_CALLING_TEXT_FORM_TOP_H MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM_H 91

#define MMICC_CALLING_ANIM_FORM_TOP MMICC_CALLING_TEXT_FORM_BOTTOM
#define MMICC_CALLING_ANIM_FORM_TOP_H MMICC_CALLING_TEXT_FORM_BOTTOM_H

#define MMICC_CALLING_TEXT_FORM_SPACE 4
#define MMICC_CALLING_TEXT_FORM_SPACE_H 0

#define MMICC_CALLING_STATE_ANIM_WIDTH 75
#define MMICC_CALLING_STATE_ANIM_HEIGHT 60

#define MMICC_CALLING_ANIM_FORM_HEIGHT (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_ANIM_FORM_HEIGHT_H (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP_H)

#define MMICC_CALLING_STATE_ANIM_LEFT 10
#define MMICC_CALLING_STATE_ANIM_RIGHT (MMICC_CALLING_STATE_ANIM_LEFT + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_STATE_ANIM_BOTTOM (MMICC_CALLING_STATE_ANIM_TOP + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_STATE_ANIM_LEFT_H 32
#define MMICC_CALLING_STATE_ANIM_RIGHT_H (MMICC_CALLING_STATE_ANIM_LEFT_H + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_STATE_ANIM_BOTTOM_H (MMICC_CALLING_STATE_ANIM_TOP_H + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_WIDTH 58
#define MMICC_CALLING_PHOTO_ANIM_HEIGHT 58

#define MMICC_CALLING_PHOTO_ANIM_LEFT (6 + MMICC_CALLING_STATE_ANIM_RIGHT)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT (MMICC_CALLING_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM (MMICC_CALLING_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_LEFT_H (30 + MMICC_CALLING_STATE_ANIM_RIGHT_H)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT_H (MMICC_CALLING_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM_H (MMICC_CALLING_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_PHOTO_ANIM_LEFT 11
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT (MMICC_CONNECTED_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP 48
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM (MMICC_CONNECTED_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)


#define MMICC_CONNECTED_PHOTO_ANIM_LEFT_H 32
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H (MMICC_CONNECTED_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP_H 30
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H (MMICC_CONNECTED_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_TEXT_FORM_LEFT (MMICC_CONNECTED_PHOTO_ANIM_RIGHT + 5)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT 
#define MMICC_CONNECTED_TEXT_FORM_TOP MMICC_CONNECTED_PHOTO_ANIM_TOP - 5
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM MMICC_CONNECTED_PHOTO_ANIM_BOTTOM + 10

#define MMICC_CONNECTED_TEXT_FORM_LEFT_H (MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H + 10)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT_H 
#define MMICC_CONNECTED_TEXT_FORM_TOP_H MMICC_CONNECTED_PHOTO_ANIM_TOP_H - 5
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM_H MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H + 10

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN 9
#define MMICC_CONNECTED_BUTTON_FORM_TOP (MMICC_CONNECTED_TEXT_FORM_BOTTOM + 8)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE 6

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN_H 49
#define MMICC_CONNECTED_BUTTON_FORM_TOP_H (MMICC_CONNECTED_TEXT_FORM_BOTTOM_H)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE_H 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE_H 6

#define MMICC_PROCESS_FORM_TOP 60
#define MMICC_PROCESS_FORM_TOP_H 30


    //通话音量调节
    #define MMICC_RING_VOL_BG_X        	5
    #define MMICC_RING_VOL_BG_Y			23//27//44

    //point of volume picture
    #define MMICC_RING_VOL_LEVEL_ONE_X		40//58
    #define MMICC_RING_VOL_LEVEL_ONE_Y		70//126
    #define MMICC_RING_VOL_LEVEL_TWO_X		23//37
    #define MMICC_RING_VOL_LEVEL_TWO_Y		74//131
    #define MMICC_RING_VOL_LEVEL_THREE_X	9//17
    #define MMICC_RING_VOL_LEVEL_THREE_Y	88//148
    #define MMICC_RING_VOL_LEVEL_FOUR_X	    22//35
    #define MMICC_RING_VOL_LEVEL_FOUR_Y	    105//170
    #define MMICC_RING_VOL_LEVEL_FIVE_X	    57//79
    #define MMICC_RING_VOL_LEVEL_FIVE_Y	    115//182
    #define MMICC_RING_VOL_LEVEL_SIX_X		99//134
    #define MMICC_RING_VOL_LEVEL_SIX_Y		112//179
    #define MMICC_RING_VOL_LEVEL_SEVEN_X	136//181
    #define MMICC_RING_VOL_LEVEL_SEVEN_Y	96//158

    #define MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT                143
    #define MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT               46
    #define MMICC_ADJUST_VOL_LEVEL_BOX_DISTANCE              22   
    #define MMICC_ADJUST_VOL_BG_WIDHT                        107
    #define MMICC_ADJUST_VOL_BG_HEIGHT                       89
    #define MMICC_ADJUST_VOL_PLUG_WIDTH                     47
    #define MMICC_ADJUST_VOL_PLUG_HEIGHT                    25
    #define MMICC_ADJUST_VOL_MINUS_LEFT              22 //音量调节减少按钮左边坐标

    #define MMICC_ADJUST_VOL_LEVEL_BOX_LEFT          ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_LEVEL_BOX_TOP           (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT >>1) + MMI_TITLE_HEIGHT)
    #define MMICC_ADJUST_VOL_BG_LEFT                 ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_BG_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_BG_TOP                  (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_BG_HEIGHT >>1) + ((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 1) + MMI_TITLE_HEIGHT)

    #define MMICC_ADJUST_VOL_PLUG_LEFT               (MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_PLUG_WIDTH) //音量调节增加按钮的左边坐标
    #define MMICC_ADJUST_VOL_PLUG_TOP                (MMICC_ADJUST_VOL_BG_TOP + ((MMICC_ADJUST_VOL_BG_HEIGHT - MMICC_ADJUST_VOL_PLUG_HEIGHT) >> 1)) //音量调节增加/减少按钮的上边坐标

    //音量调节button的坐标
    #define  MMICC_RING_DOWN_BUTTON_LEFT			22
    #define  MMICC_RING_DOWN_BUTTON_TOP		       MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_DOWN_BUTTON_RIGHT			46
    #define  MMICC_RING_DOWN_BUTTON_BOTTOM		MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    #define  MMICC_RING_UP_BUTTON_LEFT				MMICC_ADJUST_VOL_PLUG_LEFT
    #define  MMICC_RING_UP_BUTTON_TOP				MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_UP_BUTTON_RIGHT			MMICC_ADJUST_VOL_PLUG_LEFT + 24
    #define  MMICC_RING_UP_BUTTON_BOTTOM			MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    //#define CC_DIAL_BUTTON_RECT         {70, 290, 70+CC_DIAL_BUTTON_WIDTH-1, 290+CC_DIAL_BUTTON_HEIGHT-1}

    //cc通话中softkeybar中的拨号盘小button
    #define CC_DIAL_BUTTON_WIDTH        19
    #define CC_DIAL_BUTTON_HEIGHT       19
    #define CC_DIAL_BUTTON_RECT         {(MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2, 199, (MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2+CC_DIAL_BUTTON_WIDTH-1, 199+CC_DIAL_BUTTON_HEIGHT-1}

    #define MMICC_DISPLAY_STR_MAX_LEN   20
#ifndef MMI_GUI_STYLE_TYPICAL
#define MMICC_CC_END_BUTTON_BG_HEIGHT 33
#define MMICC_CC_END_BUTTON_MARGIN 10

#define MMICC_CC_PDA_CALL_PHOTO_LEFT 70
#define MMICC_CC_PDA_CALL_PHOTO_RIGHT 169
#define MMICC_CC_PDA_CALL_PHOTO_TOP 63
#define MMICC_CC_PDA_CALL_PHOTO_BOTTOM 142

#define MMICC_CC_PDA_HOLD_CALL_PHOTO_LEFT 170
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_RIGHT 239
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_TOP 111
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_BOTTOM 142

#define MMICC_CC_PDA_CALL_INFO_TOP 146

#define CC_HB_WIDTH 74 
#define CC_HB_HEIGHT 56
#define CC_HB_V_SPACE 4

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT 5
#define CC_HB_ONE_ONE_TOP 143
#define CC_HB_ONE_ONE_RIGHT 79 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM 199 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT 83 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP 143
#define CC_HB_ONE_TWO_RIGHT 157 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM 199 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT 161 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP 143
#define CC_HB_ONE_THREE_RIGHT 235//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM 199 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT 5
#define CC_HB_TWO_ONE_TOP 203
#define CC_HB_TWO_ONE_RIGHT 79 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM 259 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT 83 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP 203
#define CC_HB_TWO_TWO_RIGHT 157 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM 259 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT 161 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP 203
#define CC_HB_TWO_THREE_RIGHT 235 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM 259 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT 5
#define CC_HANGUP_BUTTON_TOP 263
#define CC_HANGUP_BUTTON_RIGHT 235
#define CC_HANGUP_BUTTON_BOTTOM 297

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT 6
#define CC_MAIN_INFO_ANIM_TOP 5
#define CC_MAIN_INFO_ANIM_RIGHT 38
#define CC_MAIN_INFO_ANIM_BOTTOM 37

#define CC_MAIN_INFO_NAME_LABEL_LEFT 41
#define CC_MAIN_INFO_NAME_LABEL_TOP 51
#define CC_MAIN_INFO_NAME_LABEL_RIGHT 172
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM 72

#define CC_MAIN_INFO_NUM_LABEL_LEFT 41
#define CC_MAIN_INFO_NUM_LABEL_TOP 74
#define CC_MAIN_INFO_NUM_LABEL_RIGHT 172
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM 95

#ifdef MMI_CALLCONTROL_MINI_SUPPORT
#define CC_MAIN_INFO_TIME_LABEL_LEFT 41
#define CC_MAIN_INFO_TIME_LABEL_TOP 28
#define CC_MAIN_INFO_TIME_LABEL_RIGHT 172
#define CC_MAIN_INFO_TIME_LABEL_BOTTOM 49

#define CC_MAIN_INFO_STATE_LABEL_OFFSET 44
#else
#define CC_MAIN_INFO_LOCAT_LABEL_LEFT 6
#define CC_MAIN_INFO_LOCAT_LABEL_TOP 42
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT 38
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM 55
#endif
#define CC_MAIN_INFO_STATE_LABEL_LEFT 41
#define CC_MAIN_INFO_STATE_LABEL_TOP 5
#define CC_MAIN_INFO_STATE_LABEL_RIGHT 172
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM 26

#define CC_SEC_INFO_ANIM_LEFT 6//3
#define CC_SEC_INFO_ANIM_TOP 103
#define CC_SEC_INFO_ANIM_RIGHT 38
#define CC_SEC_INFO_ANIM_BOTTOM 135

#define CC_SEC_INFO_NAME_LABEL_LEFT 41
#define CC_SEC_INFO_NAME_LABEL_TOP 126
#define CC_SEC_INFO_NAME_LABEL_RIGHT 172
#define CC_SEC_INFO_NAME_LABEL_BOTTOM 147

#define CC_SEC_INFO_NUM_LABEL_LEFT 41
#define CC_SEC_INFO_NUM_LABEL_TOP 149
#define CC_SEC_INFO_NUM_LABEL_RIGHT 172
#define CC_SEC_INFO_NUM_LABEL_BOTTOM 170

#define CC_SEC_INFO_STATE_LABEL_LEFT 41
#define CC_SEC_INFO_STATE_LABEL_TOP 103
#define CC_SEC_INFO_STATE_LABEL_RIGHT 172
#define CC_SEC_INFO_STATE_LABEL_BOTTOM 124

#define CC_MAIN_INFO_BOTTOM_ANIM_LEFT 0 
#define CC_MAIN_INFO_BOTTOM_ANIM_TOP 150 
#define CC_MAIN_INFO_BOTTOM_ANIM_RIGHT 176 
#define CC_MAIN_INFO_BOTTOM_ANIM_BOTTOM 195 

//单通电话图片文字y轴坐辈钪店
//#define SINGLE_CALL_SPACE  3//((CC_HB_ONE_ONE_TOP - (CC_MAIN_INFO_ANIM_BOTTOM - CC_MAIN_INFO_ANIM_TOP))/2)
#define SINGLE_CALL_SPACE  -15 //单通电话和多通电话active电话的偏移量
#define SINGLE_CALL_HEIGHT 23
#define SINGLE_CALL_HEIGHT_H 19

//multi call line
#define CC_MULTI_CALL_LINE_TOP 98

//option button 
#define CC_OPTION_BUTTON_LEFT 5
#define CC_OPTION_BUTTON_TOP 5
#define CC_OPTION_BUTTON_RIGHT 30 
#define CC_OPTION_BUTTON_BOTTOM 30

#define CC_OPTION_LABEL_LEFT 5
#define CC_OPTION_LABEL_TOP 32
#define CC_OPTION_LABEL_RIGHT 30
#define CC_OPTION_LABEL_BOTTOM 50

#define CC_HB_WIDTH_H 62 
#define CC_HB_HEIGHT_H 56
#define CC_HB_V_SPACE_H 5

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT_H 117
#define CC_HB_ONE_ONE_TOP_H 62
#define CC_HB_ONE_ONE_RIGHT_H 179 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM_H 118 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT_H 185 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP_H 62
#define CC_HB_ONE_TWO_RIGHT_H 247 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM_H 118 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT_H 253 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP_H 62
#define CC_HB_ONE_THREE_RIGHT_H 315//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM_H 118 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT_H 117
#define CC_HB_TWO_ONE_TOP_H 123
#define CC_HB_TWO_ONE_RIGHT_H 179 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM_H 179 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT_H 185 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP_H 123
#define CC_HB_TWO_TWO_RIGHT_H 247 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM_H 179 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT_H 253 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP_H 123
#define CC_HB_TWO_THREE_RIGHT_H 315 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM_H 179 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT_H 117
#define CC_HANGUP_BUTTON_TOP_H 184
#define CC_HANGUP_BUTTON_RIGHT_H 315
#define CC_HANGUP_BUTTON_BOTTOM_H 219

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT_H 6
#define CC_MAIN_INFO_ANIM_TOP_H 2
#define CC_MAIN_INFO_ANIM_RIGHT_H 38
#define CC_MAIN_INFO_ANIM_BOTTOM_H 34

#define CC_MAIN_INFO_NAME_LABEL_LEFT_H 44
#define CC_MAIN_INFO_NAME_LABEL_TOP_H 40
#define CC_MAIN_INFO_NAME_LABEL_RIGHT_H 214
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM_H 58

#define CC_MAIN_INFO_NUM_LABEL_LEFT_H 44
#define CC_MAIN_INFO_NUM_LABEL_TOP_H 59
#define CC_MAIN_INFO_NUM_LABEL_RIGHT_H 214
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM_H 77

#ifdef MMI_CALLCONTROL_MINI_SUPPORT
#define CC_MAIN_INFO_TIME_LABEL_LEFT_H 44
#define CC_MAIN_INFO_TIME_LABEL_TOP_H 21
#define CC_MAIN_INFO_TIME_LABEL_RIGHT_H 214
#define CC_MAIN_INFO_TIME_LABEL_BOTTOM_H 39

#define CC_MAIN_INFO_STATE_LABEL_OFFSET_H 50
#else
#define CC_MAIN_INFO_LOCAT_LABEL_LEFT_H 44
#define CC_MAIN_INFO_LOCAT_LABEL_TOP_H 19
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT_H 214
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM_H 30
#endif

#define CC_MAIN_INFO_STATE_LABEL_LEFT_H 44
#define CC_MAIN_INFO_STATE_LABEL_TOP_H 2
#define CC_MAIN_INFO_STATE_LABEL_RIGHT_H 214
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM_H 20

#define CC_SEC_INFO_ANIM_LEFT_H 6
#define CC_SEC_INFO_ANIM_TOP_H 81
#define CC_SEC_INFO_ANIM_RIGHT_H 38
#define CC_SEC_INFO_ANIM_BOTTOM_H 113

#define CC_SEC_INFO_NAME_LABEL_LEFT_H 44
#define CC_SEC_INFO_NAME_LABEL_TOP_H 100
#define CC_SEC_INFO_NAME_LABEL_RIGHT_H 214
#define CC_SEC_INFO_NAME_LABEL_BOTTOM_H 118

#define CC_SEC_INFO_NUM_LABEL_LEFT_H 44
#define CC_SEC_INFO_NUM_LABEL_TOP_H 119
#define CC_SEC_INFO_NUM_LABEL_RIGHT_H 214
#define CC_SEC_INFO_NUM_LABEL_BOTTOM_H 137

#define CC_SEC_INFO_STATE_LABEL_LEFT_H 44
#define CC_SEC_INFO_STATE_LABEL_TOP_H 81
#define CC_SEC_INFO_STATE_LABEL_RIGHT_H 214
#define CC_SEC_INFO_STATE_LABEL_BOTTOM_H 99

#define CC_MAIN_INFO_BOTTOM_ANIM_LEFT_H 0
#define CC_MAIN_INFO_BOTTOM_ANIM_RIGHT_H 220
#define CC_MAIN_INFO_BOTTOM_ANIM_TOP_H 124
#define CC_MAIN_INFO_BOTTOM_ANIM_BOTTOM_H 151

#define CC_OPTION_BUTTON_LEFT_H 90
#define CC_OPTION_BUTTON_TOP_H 5
#define CC_OPTION_BUTTON_RIGHT_H 115 
#define CC_OPTION_BUTTON_BOTTOM_H 30

#define CC_OPTION_LABEL_LEFT_H 90
#define CC_OPTION_LABEL_TOP_H 32
#define CC_OPTION_LABEL_RIGHT_H 115
#define CC_OPTION_LABEL_BOTTOM_H 50

#define CC_DIAL_PANEL_LEFT_H 172

//multi call line
#define CC_MULTI_CALL_LINE_TOP_H 79


#endif
#define MMICC_MULTI_FORM_MARGIN_X 2
#define MMICC_MULTI_FORM_MARGIN_X_H 5
#define MMICC_MULTI_FORM_MARGIN_Y 5
#define MMICC_MULTI_FORM_MARGIN_Y_H 0

#define MMICC_MULTI_CALL_PHOTO_WIDTH 32
#define MMICC_MULTI_CALL_FORM_SPACE 0
#elif defined (MAINLCD_SIZE_128X160)
/* MO OR MT WIN */

#define MMICC_CALLING_TEXT_FORM_TOP MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM 112
        
#define MMICC_CALLING_TEXT_FORM_TOP_H MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM_H 91

#define MMICC_CALLING_ANIM_FORM_TOP MMICC_CALLING_TEXT_FORM_BOTTOM
#define MMICC_CALLING_ANIM_FORM_TOP_H MMICC_CALLING_TEXT_FORM_BOTTOM_H

#define MMICC_CALLING_TEXT_FORM_SPACE 4
#define MMICC_CALLING_TEXT_FORM_SPACE_H 0

#define MMICC_CALLING_STATE_ANIM_WIDTH 75
#define MMICC_CALLING_STATE_ANIM_HEIGHT 60

#define MMICC_CALLING_ANIM_FORM_HEIGHT (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_ANIM_FORM_HEIGHT_H (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP_H)

#define MMICC_CALLING_STATE_ANIM_LEFT 10
#define MMICC_CALLING_STATE_ANIM_RIGHT (MMICC_CALLING_STATE_ANIM_LEFT + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_STATE_ANIM_BOTTOM (MMICC_CALLING_STATE_ANIM_TOP + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_STATE_ANIM_LEFT_H 32
#define MMICC_CALLING_STATE_ANIM_RIGHT_H (MMICC_CALLING_STATE_ANIM_LEFT_H + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_STATE_ANIM_BOTTOM_H (MMICC_CALLING_STATE_ANIM_TOP_H + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_WIDTH 58
#define MMICC_CALLING_PHOTO_ANIM_HEIGHT 58

#define MMICC_CALLING_PHOTO_ANIM_LEFT (6 + MMICC_CALLING_STATE_ANIM_RIGHT)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT (MMICC_CALLING_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM (MMICC_CALLING_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_LEFT_H (30 + MMICC_CALLING_STATE_ANIM_RIGHT_H)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT_H (MMICC_CALLING_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM_H (MMICC_CALLING_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_PHOTO_ANIM_LEFT 2
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT (MMICC_CONNECTED_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP 20
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM (MMICC_CONNECTED_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)


#define MMICC_CONNECTED_PHOTO_ANIM_LEFT_H 32
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H (MMICC_CONNECTED_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP_H 30
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H (MMICC_CONNECTED_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_TEXT_FORM_LEFT (MMICC_CONNECTED_PHOTO_ANIM_RIGHT )
#define MMICC_CONNECTED_TEXT_FORM_RIGHT 
#define MMICC_CONNECTED_TEXT_FORM_TOP MMICC_CONNECTED_PHOTO_ANIM_TOP 
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM MMICC_CONNECTED_PHOTO_ANIM_BOTTOM

#define MMICC_CONNECTED_TEXT_FORM_LEFT_H (MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H + 10)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT_H 
#define MMICC_CONNECTED_TEXT_FORM_TOP_H MMICC_CONNECTED_PHOTO_ANIM_TOP_H - 5
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM_H MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H + 10

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN 1
#define MMICC_CONNECTED_BUTTON_FORM_TOP (MMICC_CONNECTED_TEXT_FORM_BOTTOM + 2)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE 6

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN_H 49
#define MMICC_CONNECTED_BUTTON_FORM_TOP_H (MMICC_CONNECTED_TEXT_FORM_BOTTOM_H)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE_H 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE_H 6

#define MMICC_PROCESS_FORM_TOP 60
#define MMICC_PROCESS_FORM_TOP_H 30


    //通话音量调节
    #define MMICC_RING_VOL_BG_X        	5
    #define MMICC_RING_VOL_BG_Y			23//27//44

    //point of volume picture
    #define MMICC_RING_VOL_LEVEL_ONE_X		40//58
    #define MMICC_RING_VOL_LEVEL_ONE_Y		70//126
    #define MMICC_RING_VOL_LEVEL_TWO_X		23//37
    #define MMICC_RING_VOL_LEVEL_TWO_Y		74//131
    #define MMICC_RING_VOL_LEVEL_THREE_X	9//17
    #define MMICC_RING_VOL_LEVEL_THREE_Y	88//148
    #define MMICC_RING_VOL_LEVEL_FOUR_X	    22//35
    #define MMICC_RING_VOL_LEVEL_FOUR_Y	    105//170
    #define MMICC_RING_VOL_LEVEL_FIVE_X	    57//79
    #define MMICC_RING_VOL_LEVEL_FIVE_Y	    115//182
    #define MMICC_RING_VOL_LEVEL_SIX_X		99//134
    #define MMICC_RING_VOL_LEVEL_SIX_Y		112//179
    #define MMICC_RING_VOL_LEVEL_SEVEN_X	136//181
    #define MMICC_RING_VOL_LEVEL_SEVEN_Y	96//158

    #define MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT                143
    #define MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT               46
    #define MMICC_ADJUST_VOL_LEVEL_BOX_DISTANCE              22   
    #define MMICC_ADJUST_VOL_BG_WIDHT                        107
    #define MMICC_ADJUST_VOL_BG_HEIGHT                       89
    #define MMICC_ADJUST_VOL_PLUG_WIDTH                     47
    #define MMICC_ADJUST_VOL_PLUG_HEIGHT                    25
    #define MMICC_ADJUST_VOL_MINUS_LEFT              22 //音量调节减少按钮左边坐标

    #define MMICC_ADJUST_VOL_LEVEL_BOX_LEFT          ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_LEVEL_BOX_TOP           (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT >>1) + MMI_TITLE_HEIGHT)
    #define MMICC_ADJUST_VOL_BG_LEFT                 ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_BG_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_BG_TOP                  (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_BG_HEIGHT >>1) + ((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 1) + MMI_TITLE_HEIGHT)

    #define MMICC_ADJUST_VOL_PLUG_LEFT               (MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_PLUG_WIDTH) //音量调节增加按钮的左边坐标
    #define MMICC_ADJUST_VOL_PLUG_TOP                (MMICC_ADJUST_VOL_BG_TOP + ((MMICC_ADJUST_VOL_BG_HEIGHT - MMICC_ADJUST_VOL_PLUG_HEIGHT) >> 1)) //音量调节增加/减少按钮的上边坐标

    //音量调节button的坐标
    #define  MMICC_RING_DOWN_BUTTON_LEFT			22
    #define  MMICC_RING_DOWN_BUTTON_TOP		       MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_DOWN_BUTTON_RIGHT			46
    #define  MMICC_RING_DOWN_BUTTON_BOTTOM		MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    #define  MMICC_RING_UP_BUTTON_LEFT				MMICC_ADJUST_VOL_PLUG_LEFT
    #define  MMICC_RING_UP_BUTTON_TOP				MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_UP_BUTTON_RIGHT			MMICC_ADJUST_VOL_PLUG_LEFT + 24
    #define  MMICC_RING_UP_BUTTON_BOTTOM			MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    //#define CC_DIAL_BUTTON_RECT         {70, 290, 70+CC_DIAL_BUTTON_WIDTH-1, 290+CC_DIAL_BUTTON_HEIGHT-1}

    //cc通话中softkeybar中的拨号盘小button
    #define CC_DIAL_BUTTON_WIDTH        19
    #define CC_DIAL_BUTTON_HEIGHT       19
    #define CC_DIAL_BUTTON_RECT         {(MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2, 199, (MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2+CC_DIAL_BUTTON_WIDTH-1, 199+CC_DIAL_BUTTON_HEIGHT-1}

    #define MMICC_DISPLAY_STR_MAX_LEN   20
#ifndef MMI_GUI_STYLE_TYPICAL
#define MMICC_CC_END_BUTTON_BG_HEIGHT 33
#define MMICC_CC_END_BUTTON_MARGIN 10

#define MMICC_CC_PDA_CALL_PHOTO_LEFT 70
#define MMICC_CC_PDA_CALL_PHOTO_RIGHT 169
#define MMICC_CC_PDA_CALL_PHOTO_TOP 63
#define MMICC_CC_PDA_CALL_PHOTO_BOTTOM 142

#define MMICC_CC_PDA_HOLD_CALL_PHOTO_LEFT 170
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_RIGHT 239
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_TOP 111
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_BOTTOM 142

#define MMICC_CC_PDA_CALL_INFO_TOP 146

#define CC_HB_WIDTH 74 
#define CC_HB_HEIGHT 56
#define CC_HB_V_SPACE 4

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT 2//5
#define CC_HB_ONE_ONE_TOP 100//143
#define CC_HB_ONE_ONE_RIGHT 45//79 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM 119//199 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT 48//83 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP 100//143
#define CC_HB_ONE_TWO_RIGHT 85//157 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM 119//199 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT 88//161 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP 100//143
#define CC_HB_ONE_THREE_RIGHT 125//235//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM 119//199 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT 2
#define CC_HB_TWO_ONE_TOP 120//203
#define CC_HB_TWO_ONE_RIGHT 45 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM 139//259 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT 48 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP 120//
#define CC_HB_TWO_TWO_RIGHT 85 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM 139//259 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT 88 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP 120//
#define CC_HB_TWO_THREE_RIGHT 125 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM 139//259 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT 5
#define CC_HANGUP_BUTTON_TOP 263
#define CC_HANGUP_BUTTON_RIGHT 235
#define CC_HANGUP_BUTTON_BOTTOM 297

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT 5 
#define CC_MAIN_INFO_ANIM_TOP 2 
#define CC_MAIN_INFO_ANIM_RIGHT 28 
#define CC_MAIN_INFO_ANIM_BOTTOM 25 

#define CC_MAIN_INFO_NAME_LABEL_LEFT 30
#define CC_MAIN_INFO_NAME_LABEL_TOP 40
#define CC_MAIN_INFO_NAME_LABEL_RIGHT 128
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM 58

#define CC_MAIN_INFO_NUM_LABEL_LEFT 30
#define CC_MAIN_INFO_NUM_LABEL_TOP 59
#define CC_MAIN_INFO_NUM_LABEL_RIGHT 128
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM 77

#ifdef MMI_CALLCONTROL_MINI_SUPPORT
#define CC_MAIN_INFO_TIME_LABEL_LEFT 30
#define CC_MAIN_INFO_TIME_LABEL_TOP 21
#define CC_MAIN_INFO_TIME_LABEL_RIGHT 128
#define CC_MAIN_INFO_TIME_LABEL_BOTTOM 39

#define CC_MAIN_INFO_STATE_LABEL_OFFSET 38
#else
#define CC_MAIN_INFO_LOCAT_LABEL_LEFT 5
#define CC_MAIN_INFO_LOCAT_LABEL_TOP 29
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT 28
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM 40
#endif
#define CC_MAIN_INFO_STATE_LABEL_LEFT 30
#define CC_MAIN_INFO_STATE_LABEL_TOP 2
#define CC_MAIN_INFO_STATE_LABEL_RIGHT 124
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM 20

#define CC_SEC_INFO_ANIM_LEFT 5
#define CC_SEC_INFO_ANIM_TOP 81
#define CC_SEC_INFO_ANIM_RIGHT 28
#define CC_SEC_INFO_ANIM_BOTTOM 104

#define CC_SEC_INFO_NAME_LABEL_LEFT 30
#define CC_SEC_INFO_NAME_LABEL_TOP 100
#define CC_SEC_INFO_NAME_LABEL_RIGHT 128
#define CC_SEC_INFO_NAME_LABEL_BOTTOM 118

#define CC_SEC_INFO_NUM_LABEL_LEFT 30
#define CC_SEC_INFO_NUM_LABEL_TOP 119
#define CC_SEC_INFO_NUM_LABEL_RIGHT 128
#define CC_SEC_INFO_NUM_LABEL_BOTTOM 137

#define CC_SEC_INFO_STATE_LABEL_LEFT 30
#define CC_SEC_INFO_STATE_LABEL_TOP 81
#define CC_SEC_INFO_STATE_LABEL_RIGHT 128
#define CC_SEC_INFO_STATE_LABEL_BOTTOM 99

#define CC_MAIN_INFO_BOTTOM_ANIM_LEFT 0 
#define CC_MAIN_INFO_BOTTOM_ANIM_TOP 114 
#define CC_MAIN_INFO_BOTTOM_ANIM_RIGHT 128 
#define CC_MAIN_INFO_BOTTOM_ANIM_BOTTOM 139 

//单通电话图片文字y轴坐辈钪店
//#define SINGLE_CALL_SPACE  2
#define SINGLE_CALL_SPACE  -5 //单通电话和多通电话active电话的偏移量
#define SINGLE_CALL_HEIGHT  19
#define SINGLE_CALL_HEIGHT_H 15

//multi call line
#define CC_MULTI_CALL_LINE_TOP 79

//option button 
#define CC_OPTION_BUTTON_LEFT 5
#define CC_OPTION_BUTTON_TOP 5
#define CC_OPTION_BUTTON_RIGHT 30 
#define CC_OPTION_BUTTON_BOTTOM 30

#define CC_OPTION_LABEL_LEFT 5
#define CC_OPTION_LABEL_TOP 32
#define CC_OPTION_LABEL_RIGHT 30
#define CC_OPTION_LABEL_BOTTOM 50

#define CC_HB_WIDTH_H 62 
#define CC_HB_HEIGHT_H 56
#define CC_HB_V_SPACE_H 5

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT_H 117
#define CC_HB_ONE_ONE_TOP_H 62
#define CC_HB_ONE_ONE_RIGHT_H 179 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM_H 118 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT_H 185 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP_H 62
#define CC_HB_ONE_TWO_RIGHT_H 247 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM_H 118 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT_H 253 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP_H 62
#define CC_HB_ONE_THREE_RIGHT_H 315//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM_H 118 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT_H 117
#define CC_HB_TWO_ONE_TOP_H 123
#define CC_HB_TWO_ONE_RIGHT_H 179 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM_H 179 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT_H 185 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP_H 123
#define CC_HB_TWO_TWO_RIGHT_H 247 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM_H 179 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT_H 253 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP_H 123
#define CC_HB_TWO_THREE_RIGHT_H 315 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM_H 179 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT_H 117
#define CC_HANGUP_BUTTON_TOP_H 184
#define CC_HANGUP_BUTTON_RIGHT_H 315
#define CC_HANGUP_BUTTON_BOTTOM_H 219

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT_H 5
#define CC_MAIN_INFO_ANIM_TOP_H 2
#define CC_MAIN_INFO_ANIM_RIGHT_H 28
#define CC_MAIN_INFO_ANIM_BOTTOM_H 25

#define CC_MAIN_INFO_NAME_LABEL_LEFT_H 30
#define CC_MAIN_INFO_NAME_LABEL_TOP_H 32
#define CC_MAIN_INFO_NAME_LABEL_RIGHT_H 159
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM_H 46

#define CC_MAIN_INFO_NUM_LABEL_LEFT_H 30
#define CC_MAIN_INFO_NUM_LABEL_TOP_H 47
#define CC_MAIN_INFO_NUM_LABEL_RIGHT_H 159
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM_H 61

#ifdef MMI_CALLCONTROL_MINI_SUPPORT
#define CC_MAIN_INFO_TIME_LABEL_LEFT_H 30
#define CC_MAIN_INFO_TIME_LABEL_TOP_H 17
#define CC_MAIN_INFO_TIME_LABEL_RIGHT_H 159
#define CC_MAIN_INFO_TIME_LABEL_BOTTOM_H 31

#define CC_MAIN_INFO_STATE_LABEL_OFFSET_H 42
#else
#define CC_MAIN_INFO_LOCAT_LABEL_LEFT_H 5
#define CC_MAIN_INFO_LOCAT_LABEL_TOP_H 130
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT_H 112
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM_H 148
#endif

#define CC_MAIN_INFO_STATE_LABEL_LEFT_H 30
#define CC_MAIN_INFO_STATE_LABEL_TOP_H 2
#define CC_MAIN_INFO_STATE_LABEL_RIGHT_H 159
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM_H 16

#define CC_SEC_INFO_ANIM_LEFT_H 5
#define CC_SEC_INFO_ANIM_TOP_H 62
#define CC_SEC_INFO_ANIM_RIGHT_H 28
#define CC_SEC_INFO_ANIM_BOTTOM_H 87

#define CC_SEC_INFO_NAME_LABEL_LEFT_H 30
#define CC_SEC_INFO_NAME_LABEL_TOP_H 77
#define CC_SEC_INFO_NAME_LABEL_RIGHT_H 159
#define CC_SEC_INFO_NAME_LABEL_BOTTOM_H 91

#define CC_SEC_INFO_NUM_LABEL_LEFT_H 30
#define CC_SEC_INFO_NUM_LABEL_TOP_H 92
#define CC_SEC_INFO_NUM_LABEL_RIGHT_H 159
#define CC_SEC_INFO_NUM_LABEL_BOTTOM_H 106

#define CC_SEC_INFO_STATE_LABEL_LEFT_H 30
#define CC_SEC_INFO_STATE_LABEL_TOP_H 62
#define CC_SEC_INFO_STATE_LABEL_RIGHT_H 159
#define CC_SEC_INFO_STATE_LABEL_BOTTOM_H 76

#define CC_MAIN_INFO_BOTTOM_ANIM_LEFT_H 0
#define CC_MAIN_INFO_BOTTOM_ANIM_RIGHT_H 159
#define CC_MAIN_INFO_BOTTOM_ANIM_TOP_H 79
#define CC_MAIN_INFO_BOTTOM_ANIM_BOTTOM_H 107

#define CC_OPTION_BUTTON_LEFT_H 90
#define CC_OPTION_BUTTON_TOP_H 5
#define CC_OPTION_BUTTON_RIGHT_H 115 
#define CC_OPTION_BUTTON_BOTTOM_H 30

#define CC_OPTION_LABEL_LEFT_H 90
#define CC_OPTION_LABEL_TOP_H 32
#define CC_OPTION_LABEL_RIGHT_H 115
#define CC_OPTION_LABEL_BOTTOM_H 50

#define CC_DIAL_PANEL_LEFT_H 172

//multi call line
#define CC_MULTI_CALL_LINE_TOP_H 61

#endif    
#define MMICC_MULTI_FORM_MARGIN_X 2
#define MMICC_MULTI_FORM_MARGIN_X_H 5
#define MMICC_MULTI_FORM_MARGIN_Y 5
#define MMICC_MULTI_FORM_MARGIN_Y_H 0

#define MMICC_MULTI_CALL_PHOTO_WIDTH 32
#define MMICC_MULTI_CALL_FORM_SPACE 0
#elif MAINLCD_SIZE_240X320
/* MO OR MT WIN */

#define MMICC_CALLING_TEXT_FORM_TOP MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM 184
        
#define MMICC_CALLING_TEXT_FORM_TOP_H MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM_H 110

#define MMICC_CALLING_ANIM_FORM_TOP MMICC_CALLING_TEXT_FORM_BOTTOM
#define MMICC_CALLING_ANIM_FORM_TOP_H MMICC_CALLING_TEXT_FORM_BOTTOM_H

#define MMICC_CALLING_TEXT_FORM_SPACE 5
#define MMICC_CALLING_TEXT_FORM_SPACE_H 0

#define MMICC_CALLING_STATE_ANIM_WIDTH 75
#define MMICC_CALLING_STATE_ANIM_HEIGHT 60

#define MMICC_CALLING_ANIM_FORM_HEIGHT (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_ANIM_FORM_HEIGHT_H (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP_H)

#define MMICC_CALLING_STATE_ANIM_LEFT 30
#define MMICC_CALLING_STATE_ANIM_RIGHT (MMICC_CALLING_STATE_ANIM_LEFT + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_STATE_ANIM_BOTTOM (MMICC_CALLING_STATE_ANIM_TOP + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_STATE_ANIM_LEFT_H 60
#define MMICC_CALLING_STATE_ANIM_RIGHT_H (MMICC_CALLING_STATE_ANIM_LEFT_H + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_STATE_ANIM_BOTTOM_H (MMICC_CALLING_STATE_ANIM_TOP_H + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_WIDTH 90
#define MMICC_CALLING_PHOTO_ANIM_HEIGHT 90

#define MMICC_CALLING_PHOTO_ANIM_LEFT (30 + MMICC_CALLING_STATE_ANIM_RIGHT)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT (MMICC_CALLING_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM (MMICC_CALLING_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_LEFT_H (30 + MMICC_CALLING_STATE_ANIM_RIGHT_H)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT_H (MMICC_CALLING_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM_H (MMICC_CALLING_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_PHOTO_ANIM_LEFT 15
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT (MMICC_CONNECTED_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP 40
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM (MMICC_CONNECTED_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)


#define MMICC_CONNECTED_PHOTO_ANIM_LEFT_H 45
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H (MMICC_CONNECTED_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP_H 20
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H (MMICC_CONNECTED_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_TEXT_FORM_LEFT (MMICC_CONNECTED_PHOTO_ANIM_RIGHT + 10)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT 
#define MMICC_CONNECTED_TEXT_FORM_TOP MMICC_CONNECTED_PHOTO_ANIM_TOP
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM MMICC_CONNECTED_PHOTO_ANIM_BOTTOM + 10

#define MMICC_CONNECTED_TEXT_FORM_LEFT_H (MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H + 10)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT_H 
#define MMICC_CONNECTED_TEXT_FORM_TOP_H MMICC_CONNECTED_PHOTO_ANIM_TOP_H
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM_H MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H + 10
#ifndef MMI_GUI_STYLE_TYPICAL
#define MMICC_CC_END_BUTTON_BG_HEIGHT 33
#define MMICC_CC_END_BUTTON_MARGIN 5

#define MMICC_CC_PDA_CALL_PHOTO_LEFT 70
#define MMICC_CC_PDA_CALL_PHOTO_RIGHT 169
#define MMICC_CC_PDA_CALL_PHOTO_TOP 63
#define MMICC_CC_PDA_CALL_PHOTO_BOTTOM 142

#define MMICC_CC_PDA_HOLD_CALL_PHOTO_LEFT 170
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_RIGHT 239
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_TOP 111
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_BOTTOM 142

#define MMICC_CC_PDA_CALL_INFO_TOP 146

#define CC_HB_WIDTH 74 
#define CC_HB_HEIGHT 56
#define CC_HB_V_SPACE 4

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT 5
#define CC_HB_ONE_ONE_TOP 143
#define CC_HB_ONE_ONE_RIGHT 79 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM 199 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT 83 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP 143
#define CC_HB_ONE_TWO_RIGHT 157 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM 199 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT 161 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP 143
#define CC_HB_ONE_THREE_RIGHT 235//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM 199 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT 5
#define CC_HB_TWO_ONE_TOP 203
#define CC_HB_TWO_ONE_RIGHT 79 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM 259 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT 83 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP 203
#define CC_HB_TWO_TWO_RIGHT 157 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM 259 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT 161 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP 203
#define CC_HB_TWO_THREE_RIGHT 235 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM 259 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT 5
#define CC_HANGUP_BUTTON_TOP 263
#define CC_HANGUP_BUTTON_RIGHT 235
#define CC_HANGUP_BUTTON_BOTTOM 297

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT 5
#define CC_MAIN_INFO_ANIM_TOP 59
#define CC_MAIN_INFO_ANIM_RIGHT 85
#define CC_MAIN_INFO_ANIM_BOTTOM 139

#define CC_MAIN_INFO_NAME_LABEL_LEFT 94
#define CC_MAIN_INFO_NAME_LABEL_TOP 59
#define CC_MAIN_INFO_NAME_LABEL_RIGHT 235
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM 77

#define CC_MAIN_INFO_NUM_LABEL_LEFT 94
#define CC_MAIN_INFO_NUM_LABEL_TOP 80
#define CC_MAIN_INFO_NUM_LABEL_RIGHT 235
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM 98

#define CC_MAIN_INFO_LOCAT_LABEL_LEFT 94
#define CC_MAIN_INFO_LOCAT_LABEL_TOP 101
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT 235
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM 119

#define CC_MAIN_INFO_STATE_LABEL_LEFT 94
#define CC_MAIN_INFO_STATE_LABEL_TOP 122
#define CC_MAIN_INFO_STATE_LABEL_RIGHT 235
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM 139

#define CC_SEC_INFO_ANIM_LEFT 35
#define CC_SEC_INFO_ANIM_TOP 5
#define CC_SEC_INFO_ANIM_RIGHT 85
#define CC_SEC_INFO_ANIM_BOTTOM 55

#define CC_SEC_INFO_NAME_LABEL_LEFT 94
#define CC_SEC_INFO_NAME_LABEL_TOP 5
#define CC_SEC_INFO_NAME_LABEL_RIGHT 235
#define CC_SEC_INFO_NAME_LABEL_BOTTOM 21

#define CC_SEC_INFO_NUM_LABEL_LEFT 94
#define CC_SEC_INFO_NUM_LABEL_TOP 23
#define CC_SEC_INFO_NUM_LABEL_RIGHT 235
#define CC_SEC_INFO_NUM_LABEL_BOTTOM 38

#define CC_SEC_INFO_STATE_LABEL_LEFT 94
#define CC_SEC_INFO_STATE_LABEL_TOP 40
#define CC_SEC_INFO_STATE_LABEL_RIGHT 235
#define CC_SEC_INFO_STATE_LABEL_BOTTOM 55


//单通电话图片文字y轴坐辈钪店
#define SINGLE_CALL_SPACE ((CC_HB_ONE_ONE_TOP - (CC_MAIN_INFO_ANIM_BOTTOM - CC_MAIN_INFO_ANIM_TOP))/2)

//option button 
#define CC_OPTION_BUTTON_LEFT 5
#define CC_OPTION_BUTTON_TOP 5
#define CC_OPTION_BUTTON_RIGHT 30 
#define CC_OPTION_BUTTON_BOTTOM 30

#define CC_OPTION_LABEL_LEFT 5
#define CC_OPTION_LABEL_TOP 32
#define CC_OPTION_LABEL_RIGHT 30
#define CC_OPTION_LABEL_BOTTOM 50

#define CC_HB_WIDTH_H 62 
#define CC_HB_HEIGHT_H 56
#define CC_HB_V_SPACE_H 5

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT_H 117
#define CC_HB_ONE_ONE_TOP_H 62
#define CC_HB_ONE_ONE_RIGHT_H 179 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM_H 118 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT_H 185 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP_H 62
#define CC_HB_ONE_TWO_RIGHT_H 247 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM_H 118 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT_H 253 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP_H 62
#define CC_HB_ONE_THREE_RIGHT_H 315//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM_H 118 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT_H 117
#define CC_HB_TWO_ONE_TOP_H 123
#define CC_HB_TWO_ONE_RIGHT_H 179 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM_H 179 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT_H 185 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP_H 123
#define CC_HB_TWO_TWO_RIGHT_H 247 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM_H 179 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT_H 253 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP_H 123
#define CC_HB_TWO_THREE_RIGHT_H 315 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM_H 179 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT_H 117
#define CC_HANGUP_BUTTON_TOP_H 184
#define CC_HANGUP_BUTTON_RIGHT_H 315
#define CC_HANGUP_BUTTON_BOTTOM_H 219

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT_H 5
#define CC_MAIN_INFO_ANIM_TOP_H 5
#define CC_MAIN_INFO_ANIM_RIGHT_H 85
#define CC_MAIN_INFO_ANIM_BOTTOM_H 85

#define CC_MAIN_INFO_NAME_LABEL_LEFT_H 5
#define CC_MAIN_INFO_NAME_LABEL_TOP_H 90
#define CC_MAIN_INFO_NAME_LABEL_RIGHT_H 112
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM_H 108

#define CC_MAIN_INFO_NUM_LABEL_LEFT_H 5
#define CC_MAIN_INFO_NUM_LABEL_TOP_H 110
#define CC_MAIN_INFO_NUM_LABEL_RIGHT_H 112
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM_H 128

#define CC_MAIN_INFO_LOCAT_LABEL_LEFT_H 5
#define CC_MAIN_INFO_LOCAT_LABEL_TOP_H 130
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT_H 112
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM_H 148

#define CC_MAIN_INFO_STATE_LABEL_LEFT_H 5
#define CC_MAIN_INFO_STATE_LABEL_TOP_H 150
#define CC_MAIN_INFO_STATE_LABEL_RIGHT_H 112
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM_H 168

#define CC_SEC_INFO_ANIM_LEFT_H 117
#define CC_SEC_INFO_ANIM_TOP_H 5
#define CC_SEC_INFO_ANIM_RIGHT_H 167
#define CC_SEC_INFO_ANIM_BOTTOM_H 55

#define CC_SEC_INFO_NAME_LABEL_LEFT_H 172
#define CC_SEC_INFO_NAME_LABEL_TOP_H 5
#define CC_SEC_INFO_NAME_LABEL_RIGHT_H 315
#define CC_SEC_INFO_NAME_LABEL_BOTTOM_H 20

#define CC_SEC_INFO_NUM_LABEL_LEFT_H 172
#define CC_SEC_INFO_NUM_LABEL_TOP_H 23
#define CC_SEC_INFO_NUM_LABEL_RIGHT_H 315
#define CC_SEC_INFO_NUM_LABEL_BOTTOM_H 38

#define CC_SEC_INFO_STATE_LABEL_LEFT_H 172
#define CC_SEC_INFO_STATE_LABEL_TOP_H 40
#define CC_SEC_INFO_STATE_LABEL_RIGHT_H 315
#define CC_SEC_INFO_STATE_LABEL_BOTTOM_H 55

#define CC_OPTION_BUTTON_LEFT_H 90
#define CC_OPTION_BUTTON_TOP_H 5
#define CC_OPTION_BUTTON_RIGHT_H 115 
#define CC_OPTION_BUTTON_BOTTOM_H 30

#define CC_OPTION_LABEL_LEFT_H 90
#define CC_OPTION_LABEL_TOP_H 32
#define CC_OPTION_LABEL_RIGHT_H 115
#define CC_OPTION_LABEL_BOTTOM_H 50

#define CC_DIAL_PANEL_LEFT_H 172


#endif

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN 5
#define MMICC_CONNECTED_BUTTON_FORM_TOP (MMICC_CONNECTED_TEXT_FORM_BOTTOM + 55)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE 5
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE 6

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN_H 49
#define MMICC_CONNECTED_BUTTON_FORM_TOP_H MMICC_CONNECTED_TEXT_FORM_BOTTOM_H - 4
#define MMICC_CONNECTED_BUTTON_FORM_SPACE_H 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE_H 6

#define MMICC_PROCESS_FORM_TOP 80
#define MMICC_PROCESS_FORM_TOP_H 50

    //通话音量调节
    #define MMICC_RING_VOL_BG_X        	5
    #define MMICC_RING_VOL_BG_Y			44

    //point of volume picture
    #define MMICC_RING_VOL_LEVEL_ONE_X		58
    #define MMICC_RING_VOL_LEVEL_ONE_Y		126
    #define MMICC_RING_VOL_LEVEL_TWO_X		37
    #define MMICC_RING_VOL_LEVEL_TWO_Y		131
    #define MMICC_RING_VOL_LEVEL_THREE_X	17
    #define MMICC_RING_VOL_LEVEL_THREE_Y	148
    #define MMICC_RING_VOL_LEVEL_FOUR_X	    35
    #define MMICC_RING_VOL_LEVEL_FOUR_Y	    170
    #define MMICC_RING_VOL_LEVEL_FIVE_X	    79
    #define MMICC_RING_VOL_LEVEL_FIVE_Y	    182
    #define MMICC_RING_VOL_LEVEL_SIX_X		134
    #define MMICC_RING_VOL_LEVEL_SIX_Y		179
    #define MMICC_RING_VOL_LEVEL_SEVEN_X	181
    #define MMICC_RING_VOL_LEVEL_SEVEN_Y	158

    #define MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT                189 
    #define MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT               64   
    #define MMICC_ADJUST_VOL_BG_WIDHT                       69
    #define MMICC_ADJUST_VOL_BG_HEIGHT                      122
    #define MMICC_ADJUST_VOL_PLUG_WIDTH                     55
    #define MMICC_ADJUST_VOL_PLUG_HEIGHT                    33

    #define MMICC_ADJUST_VOL_LEVEL_BOX_LEFT          ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_LEVEL_BOX_TOP           (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT >>1) + MMI_TITLE_HEIGHT)
    #define MMICC_ADJUST_VOL_BG_LEFT                 ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_BG_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_BG_TOP                  (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_BG_HEIGHT >>1) + ((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 1) + MMI_TITLE_HEIGHT)

    #define MMICC_ADJUST_VOL_PLUG_LEFT               (MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_PLUG_WIDTH) //音量调节增加按钮的左边坐标
    #define MMICC_ADJUST_VOL_PLUG_TOP                (MMICC_ADJUST_VOL_BG_TOP + ((MMICC_ADJUST_VOL_BG_HEIGHT - MMICC_ADJUST_VOL_PLUG_HEIGHT) >> 1)) //音量调节增加/减少按钮的上边坐标

    //音量调节button的坐标
    #define  MMICC_RING_DOWN_BUTTON_LEFT			0
    #define  MMICC_RING_DOWN_BUTTON_TOP		       MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_DOWN_BUTTON_RIGHT			54
    #define  MMICC_RING_DOWN_BUTTON_BOTTOM		MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    #define  MMICC_RING_UP_BUTTON_LEFT				MMICC_ADJUST_VOL_PLUG_LEFT
    #define  MMICC_RING_UP_BUTTON_TOP				MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_UP_BUTTON_RIGHT			MMICC_ADJUST_VOL_PLUG_LEFT + 54
    #define  MMICC_RING_UP_BUTTON_BOTTOM			MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    //#define CC_DIAL_BUTTON_RECT         {107, 290, 107+CC_DIAL_BUTTON_WIDTH-1, 290+CC_DIAL_BUTTON_HEIGHT-1}

    //cc通话中softkeybar中的拨号盘小button
    #define CC_DIAL_BUTTON_WIDTH        26
    #define CC_DIAL_BUTTON_HEIGHT       26
    #define CC_DIAL_BUTTON_RECT         {(MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2, 290, (MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2+CC_DIAL_BUTTON_WIDTH-1, 290+CC_DIAL_BUTTON_HEIGHT-1}

    #define MMICC_BACKGROUND_IMAGE_RECT {0, 94, 239, 190}
    #define MMICC_BACKGROUND_DISPLAY_RECT {0, 186, 239, 281}


    #define MMICC_DISPLAY_STR_MAX_LEN   14

#define MMICC_MULTI_FORM_MARGIN_X 5
#define MMICC_MULTI_FORM_MARGIN_X_H 30
#define MMICC_MULTI_FORM_MARGIN_Y 15
#define MMICC_MULTI_FORM_MARGIN_Y_H 1

#define MMICC_MULTI_CALL_PHOTO_WIDTH 32
#define MMICC_MULTI_CALL_FORM_SPACE 3    
#elif MAINLCD_SIZE_128X64
/* MO OR MT WIN */

#define MMICC_CALLING_TEXT_FORM_TOP MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM 184
        
#define MMICC_CALLING_TEXT_FORM_TOP_H MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM_H 110

#define MMICC_CALLING_ANIM_FORM_TOP MMICC_CALLING_TEXT_FORM_BOTTOM
#define MMICC_CALLING_ANIM_FORM_TOP_H MMICC_CALLING_TEXT_FORM_BOTTOM_H

#define MMICC_CALLING_TEXT_FORM_SPACE 5
#define MMICC_CALLING_TEXT_FORM_SPACE_H 0

#define MMICC_CALLING_STATE_ANIM_WIDTH 75
#define MMICC_CALLING_STATE_ANIM_HEIGHT 60

#define MMICC_CALLING_ANIM_FORM_HEIGHT (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_ANIM_FORM_HEIGHT_H (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP_H)

#define MMICC_CALLING_STATE_ANIM_LEFT 30
#define MMICC_CALLING_STATE_ANIM_RIGHT (MMICC_CALLING_STATE_ANIM_LEFT + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_STATE_ANIM_BOTTOM (MMICC_CALLING_STATE_ANIM_TOP + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_STATE_ANIM_LEFT_H 60
#define MMICC_CALLING_STATE_ANIM_RIGHT_H (MMICC_CALLING_STATE_ANIM_LEFT_H + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_STATE_ANIM_BOTTOM_H (MMICC_CALLING_STATE_ANIM_TOP_H + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_WIDTH 90
#define MMICC_CALLING_PHOTO_ANIM_HEIGHT 90

#define MMICC_CALLING_PHOTO_ANIM_LEFT (30 + MMICC_CALLING_STATE_ANIM_RIGHT)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT (MMICC_CALLING_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM (MMICC_CALLING_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_LEFT_H (30 + MMICC_CALLING_STATE_ANIM_RIGHT_H)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT_H (MMICC_CALLING_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM_H (MMICC_CALLING_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_PHOTO_ANIM_LEFT 15
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT (MMICC_CONNECTED_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP 40
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM (MMICC_CONNECTED_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)


#define MMICC_CONNECTED_PHOTO_ANIM_LEFT_H 45
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H (MMICC_CONNECTED_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP_H 22
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H (MMICC_CONNECTED_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_TEXT_FORM_LEFT (MMICC_CONNECTED_PHOTO_ANIM_RIGHT + 10)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT 
#define MMICC_CONNECTED_TEXT_FORM_TOP MMICC_CONNECTED_PHOTO_ANIM_TOP
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM MMICC_CONNECTED_PHOTO_ANIM_BOTTOM

#define MMICC_CONNECTED_TEXT_FORM_LEFT_H (MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H + 10)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT_H 
#define MMICC_CONNECTED_TEXT_FORM_TOP_H MMICC_CONNECTED_PHOTO_ANIM_TOP_H
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM_H MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN 9
#define MMICC_CONNECTED_BUTTON_FORM_TOP (MMICC_CALLING_ANIM_FORM_TOP + 12)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE 6

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN_H 49
#define MMICC_CONNECTED_BUTTON_FORM_TOP_H (MMICC_CALLING_ANIM_FORM_TOP_H + 4)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE_H 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE_H 6

#define MMICC_PROCESS_FORM_TOP 80
#define MMICC_PROCESS_FORM_TOP_H 50

    //通话音量调节
    #define MMICC_RING_VOL_BG_X        	5
    #define MMICC_RING_VOL_BG_Y			44

    //point of volume picture
    #define MMICC_RING_VOL_LEVEL_ONE_X		58
    #define MMICC_RING_VOL_LEVEL_ONE_Y		126
    #define MMICC_RING_VOL_LEVEL_TWO_X		37
    #define MMICC_RING_VOL_LEVEL_TWO_Y		131
    #define MMICC_RING_VOL_LEVEL_THREE_X	17
    #define MMICC_RING_VOL_LEVEL_THREE_Y	148
    #define MMICC_RING_VOL_LEVEL_FOUR_X	    35
    #define MMICC_RING_VOL_LEVEL_FOUR_Y	    170
    #define MMICC_RING_VOL_LEVEL_FIVE_X	    79
    #define MMICC_RING_VOL_LEVEL_FIVE_Y	    182
    #define MMICC_RING_VOL_LEVEL_SIX_X		134
    #define MMICC_RING_VOL_LEVEL_SIX_Y		179
    #define MMICC_RING_VOL_LEVEL_SEVEN_X	181
    #define MMICC_RING_VOL_LEVEL_SEVEN_Y	158

    #define MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT                189 
    #define MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT               64   
    #define MMICC_ADJUST_VOL_BG_WIDHT                       69
    #define MMICC_ADJUST_VOL_BG_HEIGHT                      122
    #define MMICC_ADJUST_VOL_PLUG_WIDTH                     55
    #define MMICC_ADJUST_VOL_PLUG_HEIGHT                    33

    #define MMICC_ADJUST_VOL_LEVEL_BOX_LEFT          ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_LEVEL_BOX_TOP           (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT >>1) + MMI_TITLE_HEIGHT)
    #define MMICC_ADJUST_VOL_BG_LEFT                 ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_BG_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_BG_TOP                  (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_BG_HEIGHT >>1) + ((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 1) + MMI_TITLE_HEIGHT)

    #define MMICC_ADJUST_VOL_PLUG_LEFT               (MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_PLUG_WIDTH) //音量调节增加按钮的左边坐标
    #define MMICC_ADJUST_VOL_PLUG_TOP                (MMICC_ADJUST_VOL_BG_TOP + ((MMICC_ADJUST_VOL_BG_HEIGHT - MMICC_ADJUST_VOL_PLUG_HEIGHT) >> 1)) //音量调节增加/减少按钮的上边坐标

    //音量调节button的坐标
    #define  MMICC_RING_DOWN_BUTTON_LEFT			0
    #define  MMICC_RING_DOWN_BUTTON_TOP		       MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_DOWN_BUTTON_RIGHT			54
    #define  MMICC_RING_DOWN_BUTTON_BOTTOM		MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    #define  MMICC_RING_UP_BUTTON_LEFT				MMICC_ADJUST_VOL_PLUG_LEFT
    #define  MMICC_RING_UP_BUTTON_TOP				MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_UP_BUTTON_RIGHT			MMICC_ADJUST_VOL_PLUG_LEFT + 54
    #define  MMICC_RING_UP_BUTTON_BOTTOM			MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    //#define CC_DIAL_BUTTON_RECT         {107, 290, 107+CC_DIAL_BUTTON_WIDTH-1, 290+CC_DIAL_BUTTON_HEIGHT-1}

    //cc通话中softkeybar中的拨号盘小button
    #define CC_DIAL_BUTTON_WIDTH        26
    #define CC_DIAL_BUTTON_HEIGHT       26
    #define CC_DIAL_BUTTON_RECT         {(MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2, 290, (MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2+CC_DIAL_BUTTON_WIDTH-1, 290+CC_DIAL_BUTTON_HEIGHT-1}

    #define MMICC_BACKGROUND_IMAGE_RECT {0, 94, 239, 190}
    #define MMICC_BACKGROUND_DISPLAY_RECT {0, 186, 239, 281}


    #define MMICC_DISPLAY_STR_MAX_LEN   14
    #define MMICC_MULTI_CALL_FORM_SPACE 1    
#elif MAINLCD_SIZE_240X400
/* MO OR MT WIN */

#define MMICC_CALLING_TEXT_FORM_TOP MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM 260
        
#define MMICC_CALLING_TEXT_FORM_TOP_H MMI_STATUSBAR_HEIGHT
#define MMICC_CALLING_TEXT_FORM_BOTTOM_H 110

#define MMICC_CALLING_ANIM_FORM_TOP MMICC_CALLING_TEXT_FORM_BOTTOM
#define MMICC_CALLING_ANIM_FORM_TOP_H MMICC_CALLING_TEXT_FORM_BOTTOM_H

#define MMICC_CALLING_TEXT_FORM_SPACE 5
#define MMICC_CALLING_TEXT_FORM_SPACE_H 0

#define MMICC_CALLING_STATE_ANIM_WIDTH 75
#define MMICC_CALLING_STATE_ANIM_HEIGHT 60

#define MMICC_CALLING_ANIM_FORM_HEIGHT (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_ANIM_FORM_HEIGHT_H (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP_H)

#define MMICC_CALLING_STATE_ANIM_LEFT 30
#define MMICC_CALLING_STATE_ANIM_RIGHT (MMICC_CALLING_STATE_ANIM_LEFT + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_STATE_ANIM_BOTTOM (MMICC_CALLING_STATE_ANIM_TOP + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_STATE_ANIM_LEFT_H 60
#define MMICC_CALLING_STATE_ANIM_RIGHT_H (MMICC_CALLING_STATE_ANIM_LEFT_H + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_STATE_ANIM_BOTTOM_H (MMICC_CALLING_STATE_ANIM_TOP_H + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_WIDTH 90
#define MMICC_CALLING_PHOTO_ANIM_HEIGHT 90

#define MMICC_CALLING_PHOTO_ANIM_LEFT (30 + MMICC_CALLING_STATE_ANIM_RIGHT)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT (MMICC_CALLING_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM (MMICC_CALLING_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_LEFT_H (30 + MMICC_CALLING_STATE_ANIM_RIGHT_H)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT_H (MMICC_CALLING_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM_H (MMICC_CALLING_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)
 
#define MMICC_CONNECTED_PHOTO_ANIM_LEFT 15
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT (MMICC_CONNECTED_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP 40
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM (MMICC_CONNECTED_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_PHOTO_ANIM_LEFT_H 62
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H (MMICC_CONNECTED_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP_H 20
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H (MMICC_CONNECTED_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_TEXT_FORM_LEFT (MMICC_CONNECTED_PHOTO_ANIM_RIGHT + 10)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT 
#define MMICC_CONNECTED_TEXT_FORM_TOP MMICC_CONNECTED_PHOTO_ANIM_TOP
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM MMICC_CONNECTED_PHOTO_ANIM_BOTTOM + 10
 
#define MMICC_CONNECTED_TEXT_FORM_LEFT_H (MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H + 30)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT_H 
#define MMICC_CONNECTED_TEXT_FORM_TOP_H MMICC_CONNECTED_PHOTO_ANIM_TOP_H
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM_H MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H + 10

#ifndef MMI_GUI_STYLE_TYPICAL
#define MMICC_CC_END_BUTTON_BG_HEIGHT 33
#define MMICC_CC_END_BUTTON_MARGIN 5

#define MMICC_CC_PDA_CALL_PHOTO_LEFT 70
#define MMICC_CC_PDA_CALL_PHOTO_RIGHT 169
#define MMICC_CC_PDA_CALL_PHOTO_TOP 80
#define MMICC_CC_PDA_CALL_PHOTO_BOTTOM 159

#define MMICC_CC_PDA_HOLD_CALL_PHOTO_LEFT 170
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_RIGHT 239
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_TOP 128
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_BOTTOM 159

#define MMICC_CC_PDA_CALL_INFO_TOP 165


#define CC_HB_WIDTH 74 
#define CC_HB_HEIGHT 56
#define CC_HB_V_SPACE 4

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT 5
#define CC_HB_ONE_ONE_TOP 224
#define CC_HB_ONE_ONE_RIGHT 79 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM 280 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT 83 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP 224
#define CC_HB_ONE_TWO_RIGHT 157 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM 280 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT 161 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP 224
#define CC_HB_ONE_THREE_RIGHT 235//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM 280 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT 5
#define CC_HB_TWO_ONE_TOP 284
#define CC_HB_TWO_ONE_RIGHT 79 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM 340 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT 83 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP 284
#define CC_HB_TWO_TWO_RIGHT 157 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM 340 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT 161 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP 284
#define CC_HB_TWO_THREE_RIGHT 235 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM 340 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT 5
#define CC_HANGUP_BUTTON_TOP 344
#define CC_HANGUP_BUTTON_RIGHT 235
#define CC_HANGUP_BUTTON_BOTTOM 378

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT 5
#define CC_MAIN_INFO_ANIM_TOP 59
#define CC_MAIN_INFO_ANIM_RIGHT 85
#define CC_MAIN_INFO_ANIM_BOTTOM 139

#define CC_MAIN_INFO_NAME_LABEL_LEFT 94
#define CC_MAIN_INFO_NAME_LABEL_TOP 59
#define CC_MAIN_INFO_NAME_LABEL_RIGHT 235
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM 77

#define CC_MAIN_INFO_NUM_LABEL_LEFT 94
#define CC_MAIN_INFO_NUM_LABEL_TOP 80
#define CC_MAIN_INFO_NUM_LABEL_RIGHT 235
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM 98

#define CC_MAIN_INFO_LOCAT_LABEL_LEFT 94
#define CC_MAIN_INFO_LOCAT_LABEL_TOP 101
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT 235
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM 119

#define CC_MAIN_INFO_STATE_LABEL_LEFT 94
#define CC_MAIN_INFO_STATE_LABEL_TOP 122
#define CC_MAIN_INFO_STATE_LABEL_RIGHT 235
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM 139

#define CC_SEC_INFO_ANIM_LEFT 35
#define CC_SEC_INFO_ANIM_TOP 5
#define CC_SEC_INFO_ANIM_RIGHT 85
#define CC_SEC_INFO_ANIM_BOTTOM 55

#define CC_SEC_INFO_NAME_LABEL_LEFT 94
#define CC_SEC_INFO_NAME_LABEL_TOP 5
#define CC_SEC_INFO_NAME_LABEL_RIGHT 235
#define CC_SEC_INFO_NAME_LABEL_BOTTOM 21

#define CC_SEC_INFO_NUM_LABEL_LEFT 94
#define CC_SEC_INFO_NUM_LABEL_TOP 23
#define CC_SEC_INFO_NUM_LABEL_RIGHT 235
#define CC_SEC_INFO_NUM_LABEL_BOTTOM 38

#define CC_SEC_INFO_STATE_LABEL_LEFT 94
#define CC_SEC_INFO_STATE_LABEL_TOP 40
#define CC_SEC_INFO_STATE_LABEL_RIGHT 235
#define CC_SEC_INFO_STATE_LABEL_BOTTOM 55


//单通电话图片文字y轴坐辈钪店
#define SINGLE_CALL_SPACE 0

//option button 
#define CC_OPTION_BUTTON_LEFT 5
#define CC_OPTION_BUTTON_TOP 5
#define CC_OPTION_BUTTON_RIGHT 30 
#define CC_OPTION_BUTTON_BOTTOM 30

#define CC_OPTION_LABEL_LEFT 5
#define CC_OPTION_LABEL_TOP 32
#define CC_OPTION_LABEL_RIGHT 30
#define CC_OPTION_LABEL_BOTTOM 50

#define CC_HB_WIDTH_H 62 
#define CC_HB_HEIGHT_H 56
#define CC_HB_V_SPACE_H 6

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT_H 197
#define CC_HB_ONE_ONE_TOP_H 61
#define CC_HB_ONE_ONE_RIGHT_H 259 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM_H 117 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT_H 265 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP_H 61
#define CC_HB_ONE_TWO_RIGHT_H 327 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM_H 117 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT_H 333 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP_H 61
#define CC_HB_ONE_THREE_RIGHT_H 395//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM_H 117 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT_H 197
#define CC_HB_TWO_ONE_TOP_H 123
#define CC_HB_TWO_ONE_RIGHT_H 259 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM_H 179 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT_H 265 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP_H 123
#define CC_HB_TWO_TWO_RIGHT_H 327 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM_H 179 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT_H 333 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP_H 123
#define CC_HB_TWO_THREE_RIGHT_H 395 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM_H 179 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT_H 197
#define CC_HANGUP_BUTTON_TOP_H 185
#define CC_HANGUP_BUTTON_RIGHT_H 395
#define CC_HANGUP_BUTTON_BOTTOM_H 219

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT_H 5
#define CC_MAIN_INFO_ANIM_TOP_H 5
#define CC_MAIN_INFO_ANIM_RIGHT_H 85
#define CC_MAIN_INFO_ANIM_BOTTOM_H 85

#define CC_MAIN_INFO_NAME_LABEL_LEFT_H 5
#define CC_MAIN_INFO_NAME_LABEL_TOP_H 90
#define CC_MAIN_INFO_NAME_LABEL_RIGHT_H 186
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM_H 108

#define CC_MAIN_INFO_NUM_LABEL_LEFT_H 5
#define CC_MAIN_INFO_NUM_LABEL_TOP_H 110
#define CC_MAIN_INFO_NUM_LABEL_RIGHT_H 186
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM_H 128

#define CC_MAIN_INFO_LOCAT_LABEL_LEFT_H 5
#define CC_MAIN_INFO_LOCAT_LABEL_TOP_H 130
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT_H 186
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM_H 148

#define CC_MAIN_INFO_STATE_LABEL_LEFT_H 5
#define CC_MAIN_INFO_STATE_LABEL_TOP_H 150
#define CC_MAIN_INFO_STATE_LABEL_RIGHT_H 186
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM_H 168

#define CC_SEC_INFO_ANIM_LEFT_H 197
#define CC_SEC_INFO_ANIM_TOP_H 5
#define CC_SEC_INFO_ANIM_RIGHT_H 247
#define CC_SEC_INFO_ANIM_BOTTOM_H 55

#define CC_SEC_INFO_NAME_LABEL_LEFT_H 255
#define CC_SEC_INFO_NAME_LABEL_TOP_H 5
#define CC_SEC_INFO_NAME_LABEL_RIGHT_H 395
#define CC_SEC_INFO_NAME_LABEL_BOTTOM_H 20

#define CC_SEC_INFO_NUM_LABEL_LEFT_H 255
#define CC_SEC_INFO_NUM_LABEL_TOP_H 23
#define CC_SEC_INFO_NUM_LABEL_RIGHT_H 395
#define CC_SEC_INFO_NUM_LABEL_BOTTOM_H 38

#define CC_SEC_INFO_STATE_LABEL_LEFT_H 255
#define CC_SEC_INFO_STATE_LABEL_TOP_H 40
#define CC_SEC_INFO_STATE_LABEL_RIGHT_H 395
#define CC_SEC_INFO_STATE_LABEL_BOTTOM_H 55

#define CC_OPTION_BUTTON_LEFT_H 90
#define CC_OPTION_BUTTON_TOP_H 5
#define CC_OPTION_BUTTON_RIGHT_H 115 
#define CC_OPTION_BUTTON_BOTTOM_H 30

#define CC_OPTION_LABEL_LEFT_H 90
#define CC_OPTION_LABEL_TOP_H 32
#define CC_OPTION_LABEL_RIGHT_H 115
#define CC_OPTION_LABEL_BOTTOM_H 50

#define CC_DIAL_PANEL_LEFT_H 197
#endif
 
#define MMICC_CONNECTED_BUTTON_FORM_MARGIN 9
#define MMICC_CONNECTED_BUTTON_FORM_TOP (MMICC_CONNECTED_TEXT_FORM_BOTTOM + 132)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE 6

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN_H 49
#define MMICC_CONNECTED_BUTTON_FORM_TOP_H (MMICC_CONNECTED_TEXT_FORM_BOTTOM_H - 4)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE_H 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE_H 6

#define MMICC_PROCESS_FORM_TOP 80
#define MMICC_PROCESS_FORM_TOP_H 50

    //通话音量调节
    #define MMICC_RING_VOL_BG_X        	5
    #define MMICC_RING_VOL_BG_Y			44

    //point of volume picture
    #define MMICC_RING_VOL_LEVEL_ONE_X		58
    #define MMICC_RING_VOL_LEVEL_ONE_Y		126
    #define MMICC_RING_VOL_LEVEL_TWO_X		37
    #define MMICC_RING_VOL_LEVEL_TWO_Y		131
    #define MMICC_RING_VOL_LEVEL_THREE_X	17
    #define MMICC_RING_VOL_LEVEL_THREE_Y	148
    #define MMICC_RING_VOL_LEVEL_FOUR_X	    35
    #define MMICC_RING_VOL_LEVEL_FOUR_Y	    170
    #define MMICC_RING_VOL_LEVEL_FIVE_X	    79
    #define MMICC_RING_VOL_LEVEL_FIVE_Y	    182
    #define MMICC_RING_VOL_LEVEL_SIX_X		134
    #define MMICC_RING_VOL_LEVEL_SIX_Y		179
    #define MMICC_RING_VOL_LEVEL_SEVEN_X	181
    #define MMICC_RING_VOL_LEVEL_SEVEN_Y	158

    #define MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT                189 
    #define MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT               64   
    #define MMICC_ADJUST_VOL_BG_WIDHT                       69
    #define MMICC_ADJUST_VOL_BG_HEIGHT                      122
    #define MMICC_ADJUST_VOL_PLUG_WIDTH                     55
    #define MMICC_ADJUST_VOL_PLUG_HEIGHT                    33

    #define MMICC_ADJUST_VOL_LEVEL_BOX_LEFT          ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_LEVEL_BOX_TOP           (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT >>1) + MMI_TITLE_HEIGHT)
    #define MMICC_ADJUST_VOL_BG_LEFT                 ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_BG_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_BG_TOP                  (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_BG_HEIGHT >>1) + ((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 1) + MMI_TITLE_HEIGHT)

    #define MMICC_ADJUST_VOL_PLUG_LEFT               (MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_PLUG_WIDTH) //音量调节增加按钮的左边坐标
    #define MMICC_ADJUST_VOL_PLUG_TOP                (MMICC_ADJUST_VOL_BG_TOP + ((MMICC_ADJUST_VOL_BG_HEIGHT - MMICC_ADJUST_VOL_PLUG_HEIGHT) >> 1)) //音量调节增加/减少按钮的上边坐标

    //音量调节button的坐标
    #define  MMICC_RING_DOWN_BUTTON_LEFT			0
    #define  MMICC_RING_DOWN_BUTTON_TOP		       MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_DOWN_BUTTON_RIGHT			54
    #define  MMICC_RING_DOWN_BUTTON_BOTTOM		MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    #define  MMICC_RING_UP_BUTTON_LEFT				MMICC_ADJUST_VOL_PLUG_LEFT
    #define  MMICC_RING_UP_BUTTON_TOP				MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_UP_BUTTON_RIGHT			MMICC_ADJUST_VOL_PLUG_LEFT + 54
    #define  MMICC_RING_UP_BUTTON_BOTTOM			MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    //#define CC_DIAL_BUTTON_RECT         {107, 290, 107+CC_DIAL_BUTTON_WIDTH-1, 290+CC_DIAL_BUTTON_HEIGHT-1}

    //cc通话中softkeybar中的拨号盘小button
    #define CC_DIAL_BUTTON_WIDTH        26
    #define CC_DIAL_BUTTON_HEIGHT       26
    #define CC_DIAL_BUTTON_RECT         {(MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2, 370, (MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2+CC_DIAL_BUTTON_WIDTH-1, 370+CC_DIAL_BUTTON_HEIGHT-1}

    #define MMICC_BACKGROUND_IMAGE_RECT {0, 94, 239, 190}
    #define MMICC_BACKGROUND_DISPLAY_RECT {0, 186, 239, 281}


    #define MMICC_DISPLAY_STR_MAX_LEN   14

#define MMICC_MULTI_FORM_MARGIN_X 5
#define MMICC_MULTI_FORM_MARGIN_X_H 30
#define MMICC_MULTI_FORM_MARGIN_Y 15
#define MMICC_MULTI_FORM_MARGIN_Y_H 1

#define MMICC_MULTI_CALL_PHOTO_WIDTH 32
#define MMICC_MULTI_CALL_FORM_SPACE 3    
#elif MAINLCD_SIZE_320X480
/* MO OR MT WIN */
#define MMICC_CALLING_TEXT_FORM_TOP 75
#define MMICC_CALLING_TEXT_FORM_BOTTOM 332
        
#define MMICC_CALLING_TEXT_FORM_TOP_H 20
#define MMICC_CALLING_TEXT_FORM_BOTTOM_H 187

#define MMICC_CALLING_ANIM_FORM_TOP MMICC_CALLING_TEXT_FORM_BOTTOM
#define MMICC_CALLING_ANIM_FORM_TOP_H MMICC_CALLING_TEXT_FORM_BOTTOM_H

#define MMICC_CALLING_TEXT_FORM_SPACE 5
#define MMICC_CALLING_TEXT_FORM_SPACE_H 0

#define MMICC_CALLING_STATE_ANIM_WIDTH 75
#define MMICC_CALLING_STATE_ANIM_HEIGHT 60

#define MMICC_CALLING_ANIM_FORM_HEIGHT (MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_ANIM_FORM_HEIGHT_H (MMI_MAINSCREEN_WIDTH - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMICC_CALLING_ANIM_FORM_TOP_H)

#define MMICC_CALLING_STATE_ANIM_LEFT 63
#define MMICC_CALLING_STATE_ANIM_RIGHT (MMICC_CALLING_STATE_ANIM_LEFT + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_STATE_ANIM_BOTTOM (MMICC_CALLING_STATE_ANIM_TOP + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_STATE_ANIM_LEFT_H 132
#define MMICC_CALLING_STATE_ANIM_RIGHT_H (MMICC_CALLING_STATE_ANIM_LEFT_H + MMICC_CALLING_STATE_ANIM_WIDTH)
#define MMICC_CALLING_STATE_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_STATE_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_STATE_ANIM_BOTTOM_H (MMICC_CALLING_STATE_ANIM_TOP_H + MMICC_CALLING_STATE_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_WIDTH 90
#define MMICC_CALLING_PHOTO_ANIM_HEIGHT 90

#define MMICC_CALLING_PHOTO_ANIM_LEFT (30 + MMICC_CALLING_STATE_ANIM_RIGHT)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT (MMICC_CALLING_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP ((MMICC_CALLING_ANIM_FORM_HEIGHT - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM (MMICC_CALLING_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CALLING_PHOTO_ANIM_LEFT_H (50 + MMICC_CALLING_STATE_ANIM_RIGHT_H)
#define MMICC_CALLING_PHOTO_ANIM_RIGHT_H (MMICC_CALLING_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CALLING_PHOTO_ANIM_TOP_H ((MMICC_CALLING_ANIM_FORM_HEIGHT_H - MMICC_CALLING_PHOTO_ANIM_HEIGHT)/2 + MMICC_CALLING_ANIM_FORM_TOP_H)
#define MMICC_CALLING_PHOTO_ANIM_BOTTOM_H (MMICC_CALLING_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)
 
#define MMICC_CONNECTED_PHOTO_ANIM_LEFT 115
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT (MMICC_CONNECTED_PHOTO_ANIM_LEFT + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP 63
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM (MMICC_CONNECTED_PHOTO_ANIM_TOP + MMICC_CALLING_PHOTO_ANIM_HEIGHT)

#define MMICC_CONNECTED_PHOTO_ANIM_LEFT_H 195
#define MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H (MMICC_CONNECTED_PHOTO_ANIM_LEFT_H + MMICC_CALLING_PHOTO_ANIM_WIDTH)
#define MMICC_CONNECTED_PHOTO_ANIM_TOP_H 40
#define MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H (MMICC_CONNECTED_PHOTO_ANIM_TOP_H + MMICC_CALLING_PHOTO_ANIM_HEIGHT)
 
#define MMICC_CONNECTED_TEXT_FORM_LEFT (MMICC_CONNECTED_PHOTO_ANIM_RIGHT + 10)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT 
#define MMICC_CONNECTED_TEXT_FORM_TOP MMICC_CONNECTED_PHOTO_ANIM_TOP
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM MMICC_CONNECTED_PHOTO_ANIM_BOTTOM

#define MMICC_CONNECTED_TEXT_FORM_LEFT_H (MMICC_CONNECTED_PHOTO_ANIM_RIGHT_H + 10)
#define MMICC_CONNECTED_TEXT_FORM_RIGHT_H 
#define MMICC_CONNECTED_TEXT_FORM_TOP_H MMICC_CONNECTED_PHOTO_ANIM_TOP_H
#define MMICC_CONNECTED_TEXT_FORM_BOTTOM_H MMICC_CONNECTED_PHOTO_ANIM_BOTTOM_H

#ifndef MMI_GUI_STYLE_TYPICAL
#define MMICC_CC_END_BUTTON_BG_HEIGHT 42
#define MMICC_CC_END_BUTTON_MARGIN 10

#define MMICC_CC_PDA_CALL_PHOTO_LEFT 100
#define MMICC_CC_PDA_CALL_PHOTO_RIGHT 219
#define MMICC_CC_PDA_CALL_PHOTO_TOP 80
#define MMICC_CC_PDA_CALL_PHOTO_BOTTOM 199

#define MMICC_CC_PDA_HOLD_CALL_PHOTO_LEFT 245
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_RIGHT 292
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_TOP 152
#define MMICC_CC_PDA_HOLD_CALL_PHOTO_BOTTOM 199

#define MMICC_CC_PDA_CALL_INFO_TOP 205

#define CC_HB_WIDTH 96 
#define CC_HB_HEIGHT 97
#define CC_HB_V_SPACE 6

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT 10
#define CC_HB_ONE_ONE_TOP 194
#define CC_HB_ONE_ONE_RIGHT 106 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM 291 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT 112 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP 194
#define CC_HB_ONE_TWO_RIGHT 208 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM 291 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT 214 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP 194
#define CC_HB_ONE_THREE_RIGHT 310//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM 291 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT 10
#define CC_HB_TWO_ONE_TOP 297
#define CC_HB_TWO_ONE_RIGHT 106 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM 394 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT 112 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP 297
#define CC_HB_TWO_TWO_RIGHT 208 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM 394 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT 214 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP 297
#define CC_HB_TWO_THREE_RIGHT 310 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM 394 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT 10
#define CC_HANGUP_BUTTON_TOP 400
#define CC_HANGUP_BUTTON_RIGHT 310
#define CC_HANGUP_BUTTON_BOTTOM 450

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT 10
#define CC_MAIN_INFO_ANIM_TOP 84
#define CC_MAIN_INFO_ANIM_RIGHT 110
#define CC_MAIN_INFO_ANIM_BOTTOM 184

#define CC_MAIN_INFO_NAME_LABEL_LEFT 116
#define CC_MAIN_INFO_NAME_LABEL_TOP 84
#define CC_MAIN_INFO_NAME_LABEL_RIGHT 310
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM 106

#define CC_MAIN_INFO_NUM_LABEL_LEFT 116
#define CC_MAIN_INFO_NUM_LABEL_TOP 110
#define CC_MAIN_INFO_NUM_LABEL_RIGHT 310
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM 132

#define CC_MAIN_INFO_LOCAT_LABEL_LEFT 116
#define CC_MAIN_INFO_LOCAT_LABEL_TOP 136
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT 310
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM 158

#define CC_MAIN_INFO_STATE_LABEL_LEFT 116
#define CC_MAIN_INFO_STATE_LABEL_TOP 162
#define CC_MAIN_INFO_STATE_LABEL_RIGHT 310
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM 184

#define CC_SEC_INFO_ANIM_LEFT 40
#define CC_SEC_INFO_ANIM_TOP 7
#define CC_SEC_INFO_ANIM_RIGHT 110
#define CC_SEC_INFO_ANIM_BOTTOM 77

#define CC_SEC_INFO_NAME_LABEL_LEFT 116
#define CC_SEC_INFO_NAME_LABEL_TOP 7
#define CC_SEC_INFO_NAME_LABEL_RIGHT 310
#define CC_SEC_INFO_NAME_LABEL_BOTTOM 29

#define CC_SEC_INFO_NUM_LABEL_LEFT 116
#define CC_SEC_INFO_NUM_LABEL_TOP 31
#define CC_SEC_INFO_NUM_LABEL_RIGHT 310
#define CC_SEC_INFO_NUM_LABEL_BOTTOM 53

#define CC_SEC_INFO_STATE_LABEL_LEFT 116
#define CC_SEC_INFO_STATE_LABEL_TOP 55
#define CC_SEC_INFO_STATE_LABEL_RIGHT 310
#define CC_SEC_INFO_STATE_LABEL_BOTTOM 77


//单通电话图片文字y轴坐辈钪店
#define SINGLE_CALL_SPACE ((CC_HB_ONE_ONE_TOP - (CC_MAIN_INFO_ANIM_BOTTOM - CC_MAIN_INFO_ANIM_TOP))/2)

#define CC_OPTION_BUTTON_LEFT 5
#define CC_OPTION_BUTTON_TOP 5
#define CC_OPTION_BUTTON_RIGHT 30 
#define CC_OPTION_BUTTON_BOTTOM 30

#define CC_OPTION_LABEL_LEFT 5
#define CC_OPTION_LABEL_TOP 32
#define CC_OPTION_LABEL_RIGHT 30
#define CC_OPTION_LABEL_BOTTOM 50

#define CC_HB_WIDTH_H 86 
#define CC_HB_HEIGHT_H 77
#define CC_HB_V_SPACE_H 6

//cc win hot button position
#define CC_HB_ONE_ONE_LEFT_H 200
#define CC_HB_ONE_ONE_TOP_H 83
#define CC_HB_ONE_ONE_RIGHT_H 286 //(CC_HB_ONE_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_ONE_BOTTOM_H 160 //(CC_HB_ONE_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_TWO_LEFT_H 292 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_ONE_TWO_TOP_H 83
#define CC_HB_ONE_TWO_RIGHT_H 378 //(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_TWO_BOTTOM_H 160 //(CC_HB_ONE_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_ONE_THREE_LEFT_H 384 //(CC_HB_WIDTH + CC_HB_ONE_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_ONE_THREE_TOP_H 83
#define CC_HB_ONE_THREE_RIGHT_H 470//(CC_HB_ONE_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_ONE_THREE_BOTTOM_H 160 //(CC_HB_ONE_THREE_TOP + CC_HB_HEIGHT)

#define CC_HB_TWO_ONE_LEFT_H 200
#define CC_HB_TWO_ONE_TOP_H 166
#define CC_HB_TWO_ONE_RIGHT_H 286 //(CC_HB_TWO_ONE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_ONE_BOTTOM_H 243 //(CC_HB_TWO_ONE_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_TWO_LEFT_H 292 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE)
#define CC_HB_TWO_TWO_TOP_H 166
#define CC_HB_TWO_TWO_RIGHT_H 378 //(CC_HB_TWO_TWO_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_TWO_BOTTOM_H 243 //(CC_HB_TWO_TWO_TOP + CC_HB_HEIGHT)
#define CC_HB_TWO_THREE_LEFT_H 384 //(CC_HB_WIDTH + CC_HB_TWO_ONE_LEFT + CC_HB_V_SPACE*2)
#define CC_HB_TWO_THREE_TOP_H 166
#define CC_HB_TWO_THREE_RIGHT_H 470 //(CC_HB_TWO_THREE_LEFT + CC_HB_WIDTH)
#define CC_HB_TWO_THREE_BOTTOM_H 243 //(CC_HB_TWO_THREE_TOP + CC_HB_HEIGHT)

//HANGUP BUTTON POSITION
#define CC_HANGUP_BUTTON_LEFT_H 200
#define CC_HANGUP_BUTTON_TOP_H 249
#define CC_HANGUP_BUTTON_RIGHT_H 470
#define CC_HANGUP_BUTTON_BOTTOM_H 289

//CALL INFO CTRL(ANIM&LABEL) POSITION
#define CC_MAIN_INFO_ANIM_LEFT_H 10
#define CC_MAIN_INFO_ANIM_TOP_H 7
#define CC_MAIN_INFO_ANIM_RIGHT_H 110
#define CC_MAIN_INFO_ANIM_BOTTOM_H 107

#define CC_MAIN_INFO_NAME_LABEL_LEFT_H 10
#define CC_MAIN_INFO_NAME_LABEL_TOP_H 119
#define CC_MAIN_INFO_NAME_LABEL_RIGHT_H 190
#define CC_MAIN_INFO_NAME_LABEL_BOTTOM_H 141

#define CC_MAIN_INFO_NUM_LABEL_LEFT_H 10
#define CC_MAIN_INFO_NUM_LABEL_TOP_H 147
#define CC_MAIN_INFO_NUM_LABEL_RIGHT_H 190
#define CC_MAIN_INFO_NUM_LABEL_BOTTOM_H 169

#define CC_MAIN_INFO_LOCAT_LABEL_LEFT_H 10
#define CC_MAIN_INFO_LOCAT_LABEL_TOP_H 175
#define CC_MAIN_INFO_LOCAT_LABEL_RIGHT_H 190
#define CC_MAIN_INFO_LOCAT_LABEL_BOTTOM_H 197

#define CC_MAIN_INFO_STATE_LABEL_LEFT_H 10
#define CC_MAIN_INFO_STATE_LABEL_TOP_H 203
#define CC_MAIN_INFO_STATE_LABEL_RIGHT_H 190
#define CC_MAIN_INFO_STATE_LABEL_BOTTOM_H 225

#define CC_SEC_INFO_ANIM_LEFT_H 200
#define CC_SEC_INFO_ANIM_TOP_H 7
#define CC_SEC_INFO_ANIM_RIGHT_H 270
#define CC_SEC_INFO_ANIM_BOTTOM_H 77

#define CC_SEC_INFO_NAME_LABEL_LEFT_H 276
#define CC_SEC_INFO_NAME_LABEL_TOP_H 7
#define CC_SEC_INFO_NAME_LABEL_RIGHT_H 470
#define CC_SEC_INFO_NAME_LABEL_BOTTOM_H 29

#define CC_SEC_INFO_NUM_LABEL_LEFT_H 276
#define CC_SEC_INFO_NUM_LABEL_TOP_H 31
#define CC_SEC_INFO_NUM_LABEL_RIGHT_H 470
#define CC_SEC_INFO_NUM_LABEL_BOTTOM_H 53

#define CC_SEC_INFO_STATE_LABEL_LEFT_H 276
#define CC_SEC_INFO_STATE_LABEL_TOP_H 55
#define CC_SEC_INFO_STATE_LABEL_RIGHT_H 470
#define CC_SEC_INFO_STATE_LABEL_BOTTOM_H 77

#define CC_OPTION_BUTTON_LEFT_H 115
#define CC_OPTION_BUTTON_TOP_H 5
#define CC_OPTION_BUTTON_RIGHT_H 140 
#define CC_OPTION_BUTTON_BOTTOM_H 30

#define CC_OPTION_LABEL_LEFT_H 115
#define CC_OPTION_LABEL_TOP_H 32
#define CC_OPTION_LABEL_RIGHT_H 140
#define CC_OPTION_LABEL_BOTTOM_H 50

#define CC_DIAL_PANEL_LEFT_H 200 
#endif

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN 9
#define MMICC_CONNECTED_BUTTON_FORM_TOP (MMICC_CALLING_ANIM_FORM_TOP + 12)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE 6

#define MMICC_CONNECTED_BUTTON_FORM_MARGIN_H 49
#define MMICC_CONNECTED_BUTTON_FORM_TOP_H (MMICC_CALLING_ANIM_FORM_TOP_H + 4)
#define MMICC_CONNECTED_BUTTON_FORM_SPACE_H 7
#define MMICC_CONNECTED_CHILD_BUTTON_FORM_SPACE_H 6

#define MMICC_PROCESS_FORM_TOP 130
#define MMICC_PROCESS_FORM_TOP_H 75

    //通话音量调节
    #define MMICC_RING_VOL_BG_X        	5
    #define MMICC_RING_VOL_BG_Y			44

    //point of volume picture
    #define MMICC_RING_VOL_LEVEL_ONE_X		58
    #define MMICC_RING_VOL_LEVEL_ONE_Y		126
    #define MMICC_RING_VOL_LEVEL_TWO_X		37
    #define MMICC_RING_VOL_LEVEL_TWO_Y		131
    #define MMICC_RING_VOL_LEVEL_THREE_X	17
    #define MMICC_RING_VOL_LEVEL_THREE_Y	148
    #define MMICC_RING_VOL_LEVEL_FOUR_X	    35
    #define MMICC_RING_VOL_LEVEL_FOUR_Y	    170
    #define MMICC_RING_VOL_LEVEL_FIVE_X	    79
    #define MMICC_RING_VOL_LEVEL_FIVE_Y	    182
    #define MMICC_RING_VOL_LEVEL_SIX_X		134
    #define MMICC_RING_VOL_LEVEL_SIX_Y		179
    #define MMICC_RING_VOL_LEVEL_SEVEN_X	181
    #define MMICC_RING_VOL_LEVEL_SEVEN_Y	158

    #define MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT                189 
    #define MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT               64   
    #define MMICC_ADJUST_VOL_BG_WIDHT                       69
    #define MMICC_ADJUST_VOL_BG_HEIGHT                      122
    #define MMICC_ADJUST_VOL_PLUG_WIDTH                     55
    #define MMICC_ADJUST_VOL_PLUG_HEIGHT                    33

    #define MMICC_ADJUST_VOL_LEVEL_BOX_LEFT          ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_LEVEL_BOX_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_LEVEL_BOX_TOP           (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_LEVEL_BOX_HEIGHT >>1) + MMI_TITLE_HEIGHT)
    #define MMICC_ADJUST_VOL_BG_LEFT                 ((MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_BG_WIDHT) >> 1)
    #define MMICC_ADJUST_VOL_BG_TOP                  (((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 2) - (MMICC_ADJUST_VOL_BG_HEIGHT >>1) + ((MMI_MAINSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - MMI_TITLE_HEIGHT) >> 1) + MMI_TITLE_HEIGHT)

    #define MMICC_ADJUST_VOL_PLUG_LEFT               (MMI_MAINSCREEN_WIDTH - MMICC_ADJUST_VOL_PLUG_WIDTH) //音量调节增加按钮的左边坐标
    #define MMICC_ADJUST_VOL_PLUG_TOP                (MMICC_ADJUST_VOL_BG_TOP + ((MMICC_ADJUST_VOL_BG_HEIGHT - MMICC_ADJUST_VOL_PLUG_HEIGHT) >> 1)) //音量调节增加/减少按钮的上边坐标

    //音量调节button的坐标
    #define  MMICC_RING_DOWN_BUTTON_LEFT			0
    #define  MMICC_RING_DOWN_BUTTON_TOP		       MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_DOWN_BUTTON_RIGHT			54
    #define  MMICC_RING_DOWN_BUTTON_BOTTOM		MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    #define  MMICC_RING_UP_BUTTON_LEFT				MMICC_ADJUST_VOL_PLUG_LEFT
    #define  MMICC_RING_UP_BUTTON_TOP				MMICC_ADJUST_VOL_PLUG_TOP
    #define  MMICC_RING_UP_BUTTON_RIGHT			MMICC_ADJUST_VOL_PLUG_LEFT + 54
    #define  MMICC_RING_UP_BUTTON_BOTTOM			MMICC_ADJUST_VOL_PLUG_TOP + MMICC_ADJUST_VOL_PLUG_HEIGHT

    //#define CC_DIAL_BUTTON_RECT         {107, 290, 107+CC_DIAL_BUTTON_WIDTH-1, 290+CC_DIAL_BUTTON_HEIGHT-1}

    //cc通话中softkeybar中的拨号盘小button
    #define CC_DIAL_BUTTON_WIDTH        26
    #define CC_DIAL_BUTTON_HEIGHT       26
    #define CC_DIAL_BUTTON_RECT         {(MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2, 370, (MMI_MAINSCREEN_WIDTH-CC_DIAL_BUTTON_WIDTH)/2+CC_DIAL_BUTTON_WIDTH-1, 370+CC_DIAL_BUTTON_HEIGHT-1}

    #define MMICC_BACKGROUND_IMAGE_RECT {0, 94, 239, 190}
    #define MMICC_BACKGROUND_DISPLAY_RECT {0, 186, 239, 281}


    #define MMICC_DISPLAY_STR_MAX_LEN   14
    
#define MMICC_MULTI_FORM_MARGIN_X 5
#define MMICC_MULTI_FORM_MARGIN_X_H 30
#define MMICC_MULTI_FORM_MARGIN_Y 15
#define MMICC_MULTI_FORM_MARGIN_Y_H 1

#define MMICC_MULTI_CALL_PHOTO_WIDTH 32
#define MMICC_MULTI_CALL_FORM_SPACE 3
#else
    #error
#endif

#ifdef   __cplusplus
    }
#endif

#endif //_MMICC_POSITION_H
