//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NVEditor.rc
//
#define IDC_BTN_LAST                    3
#define ID_BTN_NEXT                     6
#define IDD_ABOUTBOX                    100
#define IDS_BMOPR_NOTREG                103
#define IDS_CREATE_BM_FAIL              107
#define IDS_NEWOPR_FAIL                 108
#define IDS_CREATETHREAD_FAIL           109
#define IDS_FILEINFO_ERROR              110
#define IDS_START_FAIL                  111
#define IDS_BM_NOTREG                   112
#define IDS_CHANNEL_ERROR               113
#define IDR_MAINFRAME                   128
#define IDR_NVEDITTYPE                  129
#define IDB_FOLDERS                     130
#define IDB_SUBITEMS                    131
#define IDD_EDIT_ITEM                   132
#define IDD_NEW_ITEM                    133
#define IDD_NEW_MODULE_DLG              134
#define IDD_NEW_PROJECT                 135
#define IDD_DIALOG_DLSETTING            136
#define IDM_INSERT_POP                  138
#define IDD_NEW_ITEM_INFO               139
#define IDD_PORT_SETTINGS               140
#define IDD_LFP_FEEDBACK                142
#define IDD_DIALOG_FLASH                143
#define IDD_STI_SETTING                 145
#define IDR_MODULE_POP                  147
#define IDD_READ_FLASH                  149
#define IDD_DIALOG_PASTE_SETTINGS       151
#define IDD_DIALOG_FUCTIONS             152
#define IDD_DIALOG_FIND                 153
#define IDD_DIALOG_EXPORT               154
#define IDD_DIALOG_BMDOWNLOAD           155
#define IDD_DIALOG_MSG                  156
#define IDI_ICON_ERROR                  158
#define IDD_EDT_BTN_DLG                 159
#define IDD_CHANGID_DLG                 160
#define IDD_PACKET_DLG                  161
#define IDD_DIALOG1                     162
#define IDD_DIALOG2                     163
#define IDD_DIALOG_PROMPT_TEXT          165
#define IDC_MODULE_NAME                 1002
#define IDC_FILE_NAME                   1003
#define IDC_PROJECT_DESCRIPTION         1004
#define IDC_ITEM_ID                     1005
#define IDC_EDIT_FILE                   1006
#define IDC_BUTTON_BROWSE               1007
#define IDC_EDIT_ADDRESS                1008
#define IDC_EDIT_NAME                   1009
#define IDC_EDIT_ID                     1010
#define IDC_COMBO_TYPE                  1011
#define IDC_PROJECT_NAME                1012
#define IDC_EDIT_DES                    1013
#define IDC_ITEM_PARENT                 1014
#define IDC_ITEM_TYPE                   1015
#define IDC_INFO                        1016
#define IDC_ITEM_DESCRIPTION            1017
#define IDC_MODULE_DESCRIPTION          1018
#define IDC_WRITEDSP                    1018
#define IDC_CHECK_WRITEDSP              1019
#define IDC_EDIT_DSPFILE                1020
#define IDC_DSPBROWSE                   1021
#define IDC_FILE_LOCATION               1022
#define IDC_ITEM_NAME                   1024
#define IDC_ITEM_LENGTH                 1025
#define IDC_OLDITEM_ID                  1025
#define IDC_ITEM_CONTENT                1026
#define IDC_CHECK_ARRAY                 1027
#define IDC_COMBO_PORT                  1028
#define IDC_TARGET_FILE_NAME            1029
#define IDC_COMBO_BAUDRATE              1030
#define IDC_EDIT_VALUE                  1031
#define IDC_COMBOBAUDRATE               1033
#define IDC_PROGRESS                    1034
#define IDC_ITEM_ARRAY_SIZE             1035
#define IDC_COMBO_FLASH_PORT            1038
#define IDC_COMBO_FLASH_BAUDRATE        1039
#define IDC_EDIT_FLASH_ADDRESS          1040
#define IDC_EDIT_FLASH_SIZE             1042
#define IDC_EDIT_FLASH_FILE             1043
#define IDC_STI_DSPFILE                 1043
#define IDC_EDIT_FDL                    1043
#define IDC_DL_MMIFILE                  1043
#define IDC_BUTTON_FLASH_BROWSE         1044
#define IDC_EDIT_FDL_BASE               1044
#define IDC_STI_FIXBIN                  1044
#define IDC_PAKET_MODERM                1044
#define IDC_BUTTON_BROWSE_FOLDER        1046
#define IDC_BUTTON_BROWSE_FOLDER2       1047
#define IDC_STI_WRITEDSP                1048
#define IDC_STI_BROWSE                  1049
#define IDC_CHECK_CALIPARAM             1050
#define IDC_STI_BROWSE2                 1050
#define IDC_FDL_BROWSE                  1051
#define IDC_STI_WRITEFIX                1051
#define IDC_FDL2_BROWSE                 1052
#define IDC_DL_LOADMMI                  1056
#define IDC_DL_MMIBROWSE                1057
#define IDC_EDIT_SIZE                   1059
#define IDC_BROWSE                      1061
#define IDC_CHECK_OLD_REPLACE_NEW       1062
#define IDC_EDIT_NV_BASE                1063
#define IDC_EDIT_ARRAY_SIZE             1065
#define IDC_STATIC_VERSION              1066
#define IDC_STATIC_BUILD                1067
#define IDC_PRODUCT_COMBO               1068
#define IDC_NEW_FDL_CHK                 1069
#define IDC_CHECK_KEEP_NAME             1070
#define IDC_IS_SHARK_CHK                1070
#define IDC_EDIT_NEW_NAME               1072
#define IDC_EDIT_NEW_ID                 1073
#define IDC_CHECK_KEEP_ID               1074
#define IDC_EDIT_FDL2                   1075
#define IDC_EDIT_FDL2_BASE              1076
#define IDC_DMF_LST_FUNS                1076
#define IDC_DMF_CHK_ALL                 1077
#define IDC_EDT_NOTICE                  1078
#define IDC_EDIT_STR_LEN                1083
#define IDC_EDIT_STR_LENGTH             1084
#define IDC_DF_EDT_TARGET               1085
#define IDC_DF_CHK_ITEM                 1086
#define IDC_DF_CHK_VALUE                1088
#define IDC_DF_CHK_FULL_MATCH           1089
#define IDC_LIST_LOG                    1092
#define IDC_DF_CHK_CHANGED              1093
#define IDC_ED_FILE                     1094
#define IDC_ED_BTN_BROW                 1095
#define IDC_ED_CHK_READONLY             1096
#define IDC_ED_CHK_CHANGED              1097
#define IDC_PRG_PROGRESS                1098
#define IDC_BTN_STOP                    1099
#define IDC_STC_STATE                   1100
#define IDC_STC_PROG                    1101
#define IDC_LST_ITEMS                   1101
#define IDC_STC_STEP                    1102
#define IDC_STC_TITLE                   1102
#define IDC_STC_ICON                    1103
#define IDC_MUL_FILE_CHECK              1105
#define IDC_CLEAR_BUT                   1106
#define IDC_FILE_LIST                   1109
#define IDC_EDT_TEXT                    1114
#define IDC_BTN_SEL                     1115
#define IDC_NEWITEM_ID                  1116
#define IDC_IT_NAME                     1117
#define IDC_VERSION_FLAG                1118
#define IDC_PACKET_NV                   1123
#define IDC_PACKETNV_BROWSE             1124
#define IDC_PACKETM_BROWSE              1125
#define IDC_MODERM_CHECK                1126
#define IDC_EDT_PROMPT_TEXT             1127
#define IDC_EDT_ERROR_CONTENT           1128
#define IDC_CHECK_APPEND_NV             1129
#define ID_NEW_PROJECT                  32771
#define ID_NEW_MODULE                   32772
#define ID_NEW_ITEM                     32773
#define ID_INSERT_MODULE                32774
#define ID_CLOSE_PROJECT                32775
#define ID_OPEN_PROJECT                 32776
#define ID_OPEN_IMAGE                   32777
#define ID_SAVE_PROJECT                 32778
#define ID_SAVE_PROJECT_AS              32779
#define ID_SAVE_TO_PHONE                32780
#define ID_SAVE_CHANGED_TO_PHONE        32781
#define ID_FILL_DEFAULT                 32782
#define ID_LOAD_FROM_PHONE              32783
#define ID_EDIT_PROJECT                 32784
#define ID_LOAD_IMAGE                   32785
#define ID_SAVE_IMAGE                   32786
#define ID_INSERT_BEFORE                32787
#define ID_INSERT_AFTER                 32788
#define ID_INSERT_AS_CHILD              32789
#define ID_REMOVE_ITEM                  32790
#define ID_FLASH_MEMORY                 32792
#define ID_PORT_SETTINGS                32793
#define ID_LOAD_FROM_PHONE_BOOT         32794
#define ID_SET_READONLY                 32795
#define ID_ERASE_READONLY               32796
#define ID_SET_APPENDABLE               32798
#define ID_ERASE_APPENDABLE             32799
#define ID_MODULE_SET_READONLY          32801
#define ID_MODULE_ERASEREADONLY         32802
#define ID_READ_FLASH                   32803
#define ID_LOAD_NVVALUE                 32804
#define ID_COPY_ITEM                    32805
#define ID_PASTE_AS_CHILD               32806
#define ID_PASTE_AFTER                  32807
#define ID_CUT_ITEM                     32808
#define ID_READ_NAND_FLASH              32809
#define ID_ERASE_NAND_FLASH             32810
#define ID_EXPORT_ITEM                  32811
#define ID_IMPORT_ITEM                  32812
#define ID_MENU_FUNCITIONS              32813
#define ID_MENU_FIND                    32814
#define ID_MENU_FIND_NEXT               32815
#define ID_DISPLAY_HEX                  32817
#define ID_SAVE_TO_PHONE_BOOT           32818
#define ID_EXPORT_STATIC                32819
#define ID_GENER_STATISTICAL            32820
#define ID_MERGE_NV                     32821
#define ID_MODIFY_ITEMID                32822
#define IDC_PACKET_MODERM               32824
#define ID_FAIL_NVINFO                  32825
#define ID_SHOW_MODIFY                  32826
#define ID_CALIBRATION_NV               32827
#define ID_BTN_LOAD_CUSTOMERNV          32828
#define ID_MARK_AS_CUSTNV               32829
#define ID_UNMARK_AS_CUSTNV             32830
#define ID_MARK_ALL_CHANGE_AS_CUSTNV    32831
#define ID_UNMARK_ALL_CHANGE_AS_CUSTNV  32832
#define ID_UNMARK_ALL_CUSTNV            32833
#define ID_MARK_AS_CUSTBASE             32834
#define ID_UNMARK_AS_CUSTBASE           32835
#define IDS_REMOVE_ITEM                 61448
#define IDS_OPEN_PRJ_FAIL               61450

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32836
#define _APS_NEXT_CONTROL_VALUE         1130
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
